### ISSUE TITLE
建议集成Flyway对数据库脚本进行管理

### ISSUE THREAD

**Issue by liaoyongxiong** [jeecgboot/jeecg-boot#1008]
##### 问题描述：建议集成Flyway对数据库脚本进行管理
现在平台没次发布版本，大部份情况会对数据库有增加、修改，建议引入工具对数据库脚本做版本管理。
Flyway是一个简单开源数据库版本控制器（约定大于配置），主要提供migrate、clean、info、validate、baseline、repair等命令。它支持SQL（PL/SQL、T-SQL）方式和Java方式，支持命令行客户端等，还提供一系列的插件支持（Maven、Gradle、SBT、ANT等）。

官方网站：https://flywaydb.org/

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wan84** [comment]
好东西

**Comment by leetone123** [comment]
建议使用Liquibase来对数据进行初始化操作，在部署新系统时，非常好用，还可以数据备份回滚，具体参见官网教程：
https://www.liquibase.org/get-started/quickstart

**Comment by zhangdaiscott** [comment]
类似问题  https://github.com/zhangdaiscott/jeecg-boot/issues/2297

**Comment by wan84** [comment]
> 类似问题 #2297

DB脚本和迁移，什么时候安排上啊？
