### ISSUE TITLE
关于在使用中自用的部分功能优化

### ISSUE THREAD

**Issue by AlpsDDJ** [jeecgboot/jeecg-boot#2089]
##### 版本号：
2.4

##### 问题描述：
1.数据权限：扩展数据权限，在实际使用中，需要用到动态设置数据权限的并不多，所以添加了数据权限注解PermissionDataRule，方便快捷设置数据权限访问，并且兼容原有的数据权限规则，PermissionDataEnum 提供常用的数据权限参数
2.swagger文档：自动分组，配置子项目接口文档，与system模块区分，是接口文档更清晰
3.多数据源：子项目使用单独数据源，与系统模块分开，并在Dict数据字典翻译中匹配相对应的数据源

##### 截图&代码：
1.数据权限PermissionDataRule
![image](https://user-images.githubusercontent.com/31677968/101566468-056c4e00-3a0a-11eb-9a0b-2b0179062ec4.png)

2. swagger分组
![image](https://user-images.githubusercontent.com/31677968/101567580-0605e400-3a0c-11eb-914a-7465b7f25c37.png)

3.多数据源：
![image](https://user-images.githubusercontent.com/31677968/101567630-2635a300-3a0c-11eb-8369-794cd31137f7.png)
![image](https://user-images.githubusercontent.com/31677968/101567818-83c9ef80-3a0c-11eb-9797-950cb8d228a5.png)

以上是根据在实际项目中使用需求而修改

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
赞
