### ISSUE TITLE
JDictSelectTag选择后不能触发验证

### ISSUE THREAD

**Issue by wan84** [jeecgboot/jeecg-boot#2472]
##### 版本号：

2.4.3

##### 问题描述：

JDictSelectTag组件，配置了validatorRules，trigger:["blur","change"]，当选择完成后，不能立即触发验证

##### 截图&代码：

![image](https://user-images.githubusercontent.com/4098915/114898647-e3b22600-9e44-11eb-9daf-d2c34de55ec2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下个版本更新
