### ISSUE TITLE
后台Token失效，请重新登录，没有给前台返回，前台未弹框 

### ISSUE THREAD

**Issue by xuqiang0628** [jeecgboot/jeecg-boot#2482]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/61533776/115322495-c8cf1100-a1b8-11eb-95ab-b9c554efa69f.png)
![image](https://user-images.githubusercontent.com/61533776/115322531-e3a18580-a1b8-11eb-8b08-b4ad8f8f5937.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
那个功能

**Comment by xuqiang0628** [comment]
就是长时间无操作之后 token会失效，直接后台抛异常没有做处理，message信息为空，前台根据message信息弹框这边就无法执行了，导致页面在转圈，但是没有弹出重新登录的提示

**Comment by xuqiang0628** [comment]
shiro抛异常之后  如何对这个异常进行处理  怎么把message返回给前台

**Comment by tcsiye** [comment]
前后端超时错误没有规范唯一标识所导致，用户登录超时抛出的信息状态码是500，而前端处理请求状态401才能跳转至登录页。个人认为用message用来做判断不规范。

**Comment by SuKaiFei** [comment]
token失效怎么让接口状态码返回401？

**Comment by zhangdaiscott** [comment]
经测试无问题
![image](https://user-images.githubusercontent.com/3162115/128305391-c482d96d-9ce2-4c76-afc0-1d5c134c3f80.png)
