### ISSUE TITLE
English translation for platform and important documentation

### ISSUE THREAD

**Issue by YGorillaY** [jeecgboot/jeecg-boot#2553]
Have no idea why, but there is no translation or documentation in English. Based on the number of stars, it is extremely popular and advanced. It would be great, if it can be translated into English, so that a global user base can be built ;)

**Comment by parminderjit-s** [comment]
hi, it would be helpful if there is a translation to English or any video tutorials in English?

**Comment by xinxingzhao** [comment]
支持国际化国内用户也有这样的需求，我觉得可以考虑加上，不过感觉工作量还是挺大的
