### ISSUE TITLE
首页设置缓存时路由缓存问题

### ISSUE THREAD

**Issue by anyanyan07** [jeecgboot/jeecg-boot#2565]
##### 问题描述：首页keepAlive为true ，点击左侧菜单打开另一个keepAlive为true的菜单项，关闭tab，再打开同样的tab，tab没有重新加载。只有关闭紧挨着首页的tab时有这个bug。

操作步骤：
正常情况：首页(keepAlive=true)—>打开"流程设计(keepAlive=true)"——>—>打开"表单设计器(keepAlive=true)"——>关闭“流程设计”——>再打开“流程设计”，“流程设计”重新加载了。

异常情况：首页(keepAlive=true)—>打开"流程设计(keepAlive=true)"——>关闭“流程设计”——>再打开“流程设计”，此时流程设计页没有重新加载

只有两个tab(首页和另一个)的时候有这样的问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20201855/118110427-f48a9300-b414-11eb-9d96-2106a3b3793d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by anyanyan07** [comment]
这几天跟了下代码逻辑和keep-alive的源码，发现时TabLayout和RouteView嵌套使用keep-alive的问题，自己改了下TabLayout的代码，暂时解决了问题，希望作者可以优化。
`watch: {
      '$route': function(newRoute) {
       //...
        //增加如下代码：只有首页时
        if(this.pageList&&this.pageList.length==1&&this.pageList[0].fullPath==indexKey){
          this.excludeRoutes = ['RouteView']
        }else{
          this.excludeRoutes = []
        }
      },`

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by zhangdaiscott** [comment]
未修复，暂时归集到https://github.com/jeecgboot/jeecg-boot/issues/1312
