### ISSUE TITLE
【报表设计器】循环块多行循环排版问题

### ISSUE THREAD

**Issue by laifu901** [jeecgboot/jeecg-boot#2609]
##### 截图&代码：
![QQ图片20210531103442](https://user-images.githubusercontent.com/39521412/120132383-dbe3f080-c1fc-11eb-9f8b-2ea7db7c9ddd.png)
![QQ图片20210531103347](https://user-images.githubusercontent.com/39521412/120132738-76443400-c1fd-11eb-80bd-38850af70831.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/123537492-4d628080-d762-11eb-9f0f-9103ed26d26b.png)
![image](https://user-images.githubusercontent.com/27989856/123537502-5d7a6000-d762-11eb-9296-cac094c869e4.png)
http://boot.jeecg.com:8080/jeecg-boot/jmreport/view/569037925349937152
请重新设计
