### ISSUE TITLE
添加spring native的支持

### ISSUE THREAD

**Issue by zhubinsheng** [jeecgboot/jeecg-boot#2664]
##### 版本号：
新建议

##### 问题描述：
[spring native链接](https://docs.spring.io/spring-native/docs/current/reference/htmlsingle/)
依赖native以到达最小的内存占用和最大的运行速度

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
spring native还不稳定，后期再说
