### ISSUE TITLE
Online开发附表情况下字段不支持分类字典树？

### ISSUE THREAD

**Issue by xinxingzhao** [jeecgboot/jeecg-boot#2677]
##### 版本号：
2.4.5

##### 问题描述：
Online开发附表情况下字段不支持分类字典树？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/122675020-2c51db00-d20a-11eb-8bfe-71398fde35ec.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
暂不支持

**Comment by xinxingzhao** [comment]
> 暂不支持

为什么附表不能支持分类字典树字段？
