### ISSUE TITLE
初始化SQL中包含脏数据导致部门管理新增公司下无法添加二级部门

### ISSUE THREAD

**Issue by dennishucd** [jeecgboot/jeecg-boot#2699]
##### 版本号：
2.4.5（发布日期：20210607）

##### 问题描述：
[1] 现象：系统启动后，在http://localhost:3000/isystem/depart中添加了一个新的公司能够成功，但在新公司下面添加二级部分就提示“操作失败”。
[2] 原因分析：
通过查看后端日志，提示“java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'A03A01' for key 'uniq_depart_org_code'”。再查看数据库的sys_depart表，发现其中有一条id为“743ba9dbdc114af8953a11022ef3096a”的记录，其中包含ord_code为“A03A01”，它的parent_id的值"f28c6f53abd841ac87ead43afc483433"在表中已经找不到了。推测这条记录是一条脏数据，是因为之前它的上级被删除了，但未做级联删除，导致这条数据留下了。
[3] 解决办法：
从jeecg-boot\jeecg-boot\db\jeecgboot-mysql-5.7.sql中删除如下这条插入语句
INSERT INTO `sys_depart` VALUES ('743ba9dbdc114af8953a11022ef3096a', 'f28c6f53abd841ac87ead43afc483433', '财务部', NULL, NULL, 0, NULL, '1', '2', 'A03A01', NULL, NULL, NULL, NULL, NULL, '0', NULL, 'admin', '2019-03-22 16:45:43', NULL, NULL);

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3702313/123387332-40ab2480-d5ca-11eb-93b3-77d5713e2075.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by dennishucd** [comment]
下次是不是可以直接发个PR？

**Comment by lsqGitHub716** [comment]
已处理

**Comment by lsqGitHub716** [comment]
DELETE FROM sys_depart WHERE id = '743ba9dbdc114af8953a11022ef3096a';
