### ISSUE TITLE
【online报表】怎么用href传范围参数？

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#2713]
##### 问题描述：
在报表中怎么用href传递范围查询的参数？
比如我统计了每个月的活动数，我这个时候我想回到活动表单然后给出4月的活动列表（根据活动表单的action_time字段,此字段为范围查询）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/123542440-4ba5b680-d77c-11eb-9e6f-5147a3140f18.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
范围参数？
