### ISSUE TITLE
JPopup弹窗选择组件单选模式出现多选

### ISSUE THREAD

**Issue by Eason31** [jeecgboot/jeecg-boot#2720]
##### 版本号：
2.2.1

##### 问题描述：
JPopup弹窗选择组件单选模式出现多选，有时可以正常填入，有时提示只能选择一个

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54342334/123723173-7139d980-d8bc-11eb-89d3-411e4671d962.png)
![image](https://user-images.githubusercontent.com/54342334/123723242-93cbf280-d8bc-11eb-8509-a341fabc2066.png)
![image](https://user-images.githubusercontent.com/54342334/123723302-ae05d080-d8bc-11eb-8974-a60de0d0421d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
测试未发现你说的问题，请复述一下你的操作步骤，或者贴一下你的jpopup配置
