### ISSUE TITLE
字典通过表名和两个字段名获取列表数据的接口存在重大安全漏洞

### ISSUE THREAD

**Issue by lywxin** [jeecgboot/jeecg-boot#2722]
##### 版本号：
2.4.3

##### 问题描述：
字典通过表名和两个字段名获取列表数据的接口存在重大安全漏洞，普通用户即可使用这个接口获取所有表的数据，包括用户表的用户名和密码等敏感信息

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版已经提交补丁

**Comment by lywxin** [comment]
看了最新版代码，似乎没有解决这个问题，可能是我表述不准确，在代码org.jeecg.modules.system.controller.SysDictController的接口getDictItems方法对外暴露了所有表的查询，比如通过sys_user,username,password的形式可以读取到任意表的任意字段数据，而这个接口是没有严格的权限控制的，不用管理员，所有一般用户都可以通过比如postman这类工具写一个调用接口的方法，那么整个数据库的数据都暴露了，包括用户名和密码。

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/5084818

**Comment by lywxin** [comment]
不是签名的问题，比如我在你们官网的在线演示环境通过这个漏洞，我可以查到你们admin的密码加密后是8956394f313fd3d4，salt是2sNyKYrq
