### ISSUE TITLE
【报表设计器】怎么避免自然计数法？

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#2724]
##### 问题描述：
【报表设计器】中使用sql进行sum计算，结果出现了自然计数法，使用cast做转换提示‘表不存在’

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/123905953-e92ffe80-d9a5-11eb-8369-5267ae10fa61.png)
![image](https://user-images.githubusercontent.com/7098009/123905996-fc42ce80-d9a5-11eb-9f84-e2e72553a54d.png)

![image](https://user-images.githubusercontent.com/7098009/123905922-d9181f00-d9a5-11eb-96d7-ee9402bd3820.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
你用的是什么数据库测得，然后数据库字段是什么类型的，下方截图是varchar和decimal的
