### ISSUE TITLE
jeecgboot采用达蒙数据库后，online代码生成模块配置数据库连接无法连接

### ISSUE THREAD

**Issue by caoshichao2019** [jeecgboot/jeecg-boot#2725]
##### 版本号：
V2.4.5

##### 问题描述：

jeecgboot采用达蒙数据库后，online代码生成模块配置数据库连接无法连接（系统运行正常,数据源配置数据库连接也正常）

##### 截图&代码：

diver_name=dm.jdbc.driver.DmDriver
url=jdbc:dm://XXXXXXXXXXX:5236/GZJW?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
username=GZJW
password=XXXXXXXX
database_name=GZJW

![image](https://user-images.githubusercontent.com/58460002/123919704-c9093b00-d9b7-11eb-9fd7-85bd1377f37c.png)
![image](https://user-images.githubusercontent.com/58460002/123919730-cf97b280-d9b7-11eb-8073-9c2ce4352e07.png)
![image](https://user-images.githubusercontent.com/58460002/123919797-e63e0980-d9b7-11eb-9d51-3cbd46763611.png)
![image](https://user-images.githubusercontent.com/58460002/123920087-28674b00-d9b8-11eb-993c-e5c8a13fa84e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wangq2008** [comment]
我使用最新的驱动使用功能一切正常，你可以试试。
	<dependency>
			<groupId>com.dameng</groupId>
			<artifactId>DmJdbcDriver18</artifactId>
			<version>8.1.1.193</version>
		</dependency>
		<dependency>
			<groupId>com.dameng</groupId>
			<artifactId>DmDialect-for-hibernate5.3</artifactId>
			<version>7.6.0.165</version>
		</dependency>

**Comment by wangq2008** [comment]
我使用最新的驱动功能正常
`	<dependency>
			<groupId>com.dameng</groupId>
			<artifactId>DmJdbcDriver18</artifactId>
			<version>8.1.1.193</version>
		</dependency>
		<dependency>
			<groupId>com.dameng</groupId>
			<artifactId>DmDialect-for-hibernate5.3</artifactId>
			<version>7.6.0.165</version>
		</dependency>`

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by zhangdaiscott** [comment]
已处理，代码生成器依赖升级到此版本

```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>codegenerate</artifactId>
  <version>1.3.5</version>
</dependency>
```
