### ISSUE TITLE
项目改为微服务后，单个微服务只能采用本地配置文件来修改mysql配置等内容，是否不妥？

### ISSUE THREAD

**Issue by x522491416** [jeecgboot/jeecg-boot#2726]
##### 版本号：
2.4.5

##### 问题描述：
项目改为微服务后，单个微服务想独立使用数据源，只能采用本地配置文件来修改mysql配置等内容，如果这样的话，就失去了采用nacos的意义，这样是否不妥？

而且这样有一个弊端，单个微服务在独立使用数据源时，本地配置文件无法配置 spring.profiles.actve (当前激活环境) 在打包时修改配置内容

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45849273/123932299-e3491600-d9c3-11eb-8c64-55f325da5cdd.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你也可以创建不同的nacos文件，让不同的模块，改造下，读取不同的nacos配置

**Comment by x522491416** [comment]
> 你也可以创建不同的nacos文件，让不同的模块，改造下，读取不同的nacos配置

在改造工作中遇到了困难，由于微服务模块都是基于jeecg-boot-starter-cloud，需要首先给他配置nacos，导致其他模块引入的时候会出问题，读不到配置，能否指点一下

**Comment by x522491416** [comment]
贵司能否考虑在采用微服务架构之后，各微服务模块的配置文件由nacos下发，减轻对jeecg-boot-starter-cloud依赖

**Comment by zhangdaiscott** [comment]
在考虑优化

**Comment by accpman** [comment]
> 贵司能否考虑在采用微服务架构之后，各微服务模块的配置文件由nacos下发，减轻对jeecg-boot-starter-cloud依赖

把jeecg-boot-starter-cloud中的bootstrap.yml 文件拷贝到具体服务中即可（切忌是拷贝bootstrap.yml文件到具体服务，跟application.yml同目录存放）

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2573651
