### ISSUE TITLE
前端页面访问白色，如何解决？

### ISSUE THREAD

**Issue by xinxingzhao** [jeecgboot/jeecg-boot#2727]
##### 版本号：
v2.4.5

##### 问题描述：
前端页面访问白色，如何解决？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13712791/123989099-24a8e800-d9fb-11eb-8202-39c09cff04ea.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
能描述清楚吗？哪个功能

**Comment by xinxingzhao** [comment]
> 能描述清楚吗？哪个功能

就是登录页
