### ISSUE TITLE
JPopup组件在modal中使用报错

### ISSUE THREAD

**Issue by wan84** [jeecgboot/jeecg-boot#2729]
##### 版本号：

v2.4.5
##### 问题描述：
在modal组件的表单中，加载jpopup报错

加了param参数之后，就会默认调用getData

经过测试发现，只要传了param参数，页面加载就会报错
![image](https://user-images.githubusercontent.com/4098915/124060833-6a4bcc00-da60-11eb-9c02-999c11686a92.png)

##### 截图&代码：

![image](https://user-images.githubusercontent.com/4098915/124059415-a7628f00-da5d-11eb-9c16-79167fd14d8a.png)
![image](https://user-images.githubusercontent.com/4098915/124059456-ba755f00-da5d-11eb-9323-3b2b5702de49.png)
![image](https://user-images.githubusercontent.com/4098915/124059530-cf51f280-da5d-11eb-9c25-5c920ee3ae81.png)
![image](https://user-images.githubusercontent.com/4098915/124059555-db3db480-da5d-11eb-8a24-4ef54ba2505b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wan84** [comment]
修改方案

原因分析
j-popup-onl-report 中配置了watch param等参数，param变动就会触发getData加载，而getData加载需要通过show函数初始化一些数据

修改方案
加载j-popup-onl-report和show确保一直执行

![image](https://user-images.githubusercontent.com/4098915/124062569-7edd9380-da63-11eb-8661-588a54092962.png)

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by zhangdaiscott** [comment]
确认是否已改

**Comment by wan84** [comment]
> 确认是否已改

我自己的项目里面修改了，没有提交到github

**Comment by sjlei** [comment]
问题已修复，下版本发布
