### ISSUE TITLE
代码生成的疑问

### ISSUE THREAD

**Issue by Andrewzhong** [jeecgboot/jeecg-boot#2731]
##### 版本号：

2.4.5
##### 问题描述：
在Online中配置好表单后，添加了自定义按钮和JS增强，但通过代码生成后生成的代码中并未包含，手动添加的按钮以及js增强。

##### 截图&代码：
![微信图片_20210701164534](https://user-images.githubusercontent.com/9566511/124095280-17880980-da8c-11eb-8195-bb6b50213815.png)
![微信图片_20210701164733](https://user-images.githubusercontent.com/9566511/124095282-17880980-da8c-11eb-8f84-3222c4cb4704.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
代码生成不包含这个增强功能的代码的，你需要手动去添加这个功能的代码，代码生成是按照代码的模板进行生成的
