### ISSUE TITLE
数据库有些表为什么要重复建索引？

### ISSUE THREAD

**Issue by leestar54** [jeecgboot/jeecg-boot#2733]
##### 版本号：
2.4.5

##### 问题描述：
索引字段是一样的，但是重复建了2个索引，其他表也有这种情况，index_\*\*和idx_\*\*

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6147833/124208255-beff4d80-db19-11eb-9235-fabc208a586c.png)

**Comment by zhangdaiscott** [comment]
脚步增量问题，可以自己删掉，不影响
