### ISSUE TITLE
Online表单新建表id主键默认为string，不能修改

### ISSUE THREAD

**Issue by wangq2008** [jeecgboot/jeecg-boot#2734]
##### 问题描述：Online表单新建表id主键默认为string,而文档建表规范里是id为long类型，与规范不一致.
既然推荐是long,这个Online新建应该允许使用long

##### 截图&代码：
![p1](https://user-images.githubusercontent.com/9882597/124209312-e6efb080-db1b-11eb-8a9c-02da32b32077.png)
![p2](https://user-images.githubusercontent.com/9882597/124209321-eb1bce00-db1b-11eb-9259-b1f7a6060a7b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
归集到 https://github.com/jeecgboot/jeecg-boot/issues/1312
