### ISSUE TITLE
2.4.5默认主题色配置失效

### ISSUE THREAD

**Issue by IgorZhang** [jeecgboot/jeecg-boot#2735]
##### 问题描述：
在拉取最新的2.4.5项目后，开发中发现 defaultSetting 文件中的默认主题色配置失效，打包后的生产环境也是无效，求解决，希望提供一下修复代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22829403/124209658-8c0a8900-db1c-11eb-976b-620a304520d7.png)
![image](https://user-images.githubusercontent.com/22829403/124209720-a5133a00-db1c-11eb-829b-4f901da2b592.png)
![image](https://user-images.githubusercontent.com/22829403/124209730-a93f5780-db1c-11eb-8a87-b8a2be4bb456.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by IgorZhang** [comment]
希望解决后能够提供一下修复代码，开发比较紧急，谢谢！

**Comment by lsqGitHub716** [comment]
2.4.5之前的版本你试过吗？好使吗？

**Comment by IgorZhang** [comment]
之前是好使的，上一个使用版本是2.4.2

**Comment by IgorZhang** [comment]
希望能提供一下修复代码，谢谢

**Comment by sjlei** [comment]
改默认主题色建议改`vue.config.js`配置文件里的。
defaultSetting 文件就算改了本质上还是原来的颜色代码，只不过每次刷新页面都编译一次。`vue.config.js`里配置的才是真正的默认主题颜色，编译后的默认颜色也是这个。

![image](https://user-images.githubusercontent.com/34293221/126759443-01f06969-72fa-45fd-86a6-41d9d577ad49.png)
