### ISSUE TITLE
配置字典生成代码后列表页面不显示，实际有值

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#2737]
##### 版本号：
2.4.5

##### 问题描述：
online表单开发在表中配置了字典，字典Table用的自己创建的表，生成代码后没动代码，打开页面后列表页面配置了字典的字段不显示值，是生成代码后哪里还要修改还是怎么的？看了文档，配置字典就下图这些地方，好像也没发现有问题呀！是怎么回事呢？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/124247669-aceed080-db54-11eb-84b8-c82c56729ce6.png)
![image](https://user-images.githubusercontent.com/55084864/124247722-ba0bbf80-db54-11eb-888c-225dff29ed44.png)
![image](https://user-images.githubusercontent.com/55084864/124247780-c7c14500-db54-11eb-9e7d-15603f5adac7.png)
![image](https://user-images.githubusercontent.com/55084864/124247857-de679c00-db54-11eb-8fd4-0112be863315.png)
![image](https://user-images.githubusercontent.com/55084864/124247930-efb0a880-db54-11eb-9cc0-e49453528ce7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
org.jeecg.common.aspect.DictAspect
debug

**Comment by tb2888** [comment]
后端list接口debug是有值的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张代浩@***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 配置字典生成代码后列表页面不显示，实际有值 (#2737)





 
org.jeecg.common.aspect.DictAspect
 debug

**Comment by zhangdaiscott** [comment]
接口json帖

**Comment by chengang2** [comment]
解决了吗？我也发现这个问题、列表不显示。在线开发那边测试功能是可以的，生成代码展示就不行

**Comment by chengang2** [comment]
@zhangdaiscott  好像是下拉框不行。下拉多选框是可以的。如果是字典的话，正常接口是要有xxx_dict 参数的。但是下拉框的字段不会传这个参数
![image](https://user-images.githubusercontent.com/16473239/124729714-44806480-df43-11eb-9a2b-93977ef30b6e.png)

**Comment by chengang2** [comment]
@zhangdaiscott 好像是下拉框不行。下拉多选框是可以的。如果是字典的话，正常接口是要有xxx_dict 参数的。但是下拉框的字段不会传这个参数
![image](https://user-images.githubusercontent.com/16473239/124729965-7bef1100-df43-11eb-8b76-e9f38b11dcb3.png)
 如图所示， kafkaNode 这个是下拉多选框会多个kafkaNode_dict参数。但是useMem 这个是下拉框的时候就不会传useMem_dict。然后前端vue里面的代码用的是useMem_dict。所以为空

**Comment by chengang2** [comment]
@zhangdaiscott  好像是下拉框不行。下拉多选框是可以的。如果是字典的话，正常接口是要有xxx_dict 参数的。但是下拉框的字段不会传这个参数

![image](https://user-images.githubusercontent.com/16473239/124730430-e99b3d00-df43-11eb-8dc0-431d4a6f3d42.png)

如图所示， kafkaNode 这个是下拉多选框会多个kafkaNode_dict参数。但是useMem 这个是下拉框的时候就不会传useMem_dict。然后前端vue里面的代码用的是useMem_dict。所以为空

**Comment by tb2888** [comment]
我的解决了，是因为我的类文件没放在org.jeecg.modules下面，要改配置
找到这个类DictAspect，
@Pointcut("execution(public * org.jeecg.modules..*.*Controller.*(..)) ")
    public void excudeService() {
    }

这个注解里加上你类放的包名
研究了好久才发现的，不知道你的是不是这样

**Comment by tb2888** [comment]
我的解决了，是因为我的类文件没放在org.jeecg.modules下面，要改配置
找到这个类DictAspect，




这个注解里加上你类放的包名
研究了好久才发现的，不知道你的是不是这样




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 配置字典生成代码后列表页面不显示，实际有值 (#2737)





 
@zhangdaiscott  好像是下拉框不行。下拉多选框是可以的。如果是字典的话，正常接口是要有xxx_dict 参数的。但是下拉框的字段不会传这个参数

**Comment by Feng-Xg** [comment]
> 我的解决了，是因为我的类文件没放在org.jeecg.modules下面，要改配置 找到这个类DictAspect， 这个注解里加上你类放的包名 研究了好久才发现的，不知道你的是不是这样
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年7月7日(星期三) 下午4:49 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jeecgboot/jeecg-boot] 配置字典生成代码后列表页面不显示，实际有值 (#2737) @zhangdaiscott 好像是下拉框不行。下拉多选框是可以的。如果是字典的话，正常接口是要有xxx_dict 参数的。但是下拉框的字段不会传这个参数 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，这个方法有效吗？我加上还是不行
新增、编辑、列表都不是字典内容，但是高级查询显示的是。

**Comment by Feng-Xg** [comment]
@tb2888 
你好，这个配置可以解决吗？
我的还是不能显示字典value。除高级查询可以外，列表、新增、编辑都不行
