### ISSUE TITLE
数据更新后，update_by和update_time无效

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2738]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124408921-e05e7480-dd79-11eb-936e-c3130cb3918b.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你都放出来，肯定是以你录入的为准，隐藏的话会自动注入
