### ISSUE TITLE
在jeecg中如何使用自定义按钮，选中一行或多行数据后，打印jimu单据，未找到教程，请大佬指点

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2739]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124411008-3503ee80-dd7e-11eb-8c69-ad2745865a29.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己写js增强

**Comment by jeffZbj** [comment]
能给我教程吗，jeecg有效的与jimu集合使用，我在官网上没有此类型的教程

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
下个版本会在更多里添加一个打印按钮
![image](https://user-images.githubusercontent.com/34293221/126988917-fdf163d9-4d7e-4492-b6ef-b9e0247546b0.png)

多选打印功能因为弹出多个窗口会被浏览器拦截，所以就不允许多选打印

**Comment by jeffZbj** [comment]
大佬，多条打印，可以弹出一个页面，这个页面有多页就可以批量打印了，可以吗jimu



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月26日(周一) 晚上8:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 在jeecg中如何使用自定义按钮，选中一行或多行数据后，打印jimu单据，未找到教程，请大佬指点 (#2739)




 
下个版本会在更多里添加一个打印按钮
 
 
多选打印功能因为弹出多个窗口会被浏览器拦截，所以就不允许多选打印

**Comment by sjlei** [comment]
> 大佬，多条打印，可以弹出一个页面，这个页面有多页就可以批量打印了，可以吗jimu

这个功能不支持

**Comment by jeffZbj** [comment]
什么时候出商业版jimu，可以批量打印，不然不能商用。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月27日(星期二) 晚上8:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在jeecg中如何使用自定义按钮，选中一行或多行数据后，打印jimu单据，未找到教程，请大佬指点 (#2739)
