### ISSUE TITLE
请问erp一对多的上面的header可以修改为多选框吗，因为需要多选后，点击自定义按钮操作。

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2740]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124411241-bf4c5280-dd7e-11eb-8f9e-360c8206f933.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不支持

**Comment by jeffZbj** [comment]
后面的版本可以优化一下吗。也可以保留单选。增加一个多选的样式。
