### ISSUE TITLE
请问大佬，这个教程在哪里。就这个没有“详见”

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2741]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/86937081/124413868-17d21e80-dd84-11eb-81ab-68e164c92b1f.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044054

**Comment by jeffZbj** [comment]
这个链接里也没有写打印教程
