### ISSUE TITLE
表单页面详情不用弹窗，改用打开href超链接跳转表单对应的详情页

### ISSUE THREAD

**Issue by jwcjf** [jeecgboot/jeecg-boot#2742]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18321599/125017775-68a88680-e0a6-11eb-80be-c9fea9fe50eb.png)

![image](https://user-images.githubusercontent.com/18321599/125017723-4e6ea880-e0a6-11eb-80db-79a5507b5985.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这种问题不要提，自己编码实现
