### ISSUE TITLE
sql增强问题，如果操作多行，例如截图中，多选后，可以激活多行被勾选的数据。

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2743]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124437606-cfc5f280-dda9-11eb-8cfc-121af1a2117c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
已经支持 下个版本发

**Comment by jeffZbj** [comment]
好的，谢谢。如果也jimu也支持批量打印就好了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月2日(周一) 晚上6:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] sql增强问题，如果操作多行，例如截图中，多选后，可以激活多行被勾选的数据。 (#2743)




 
已经支持 下个版本发
