### ISSUE TITLE
前端可否按需引用模块

### ISSUE THREAD

**Issue by QUbn** [jeecgboot/jeecg-boot#2744]
##### 版本号：
2.4.5-RC

##### 问题描述：
前端可否按需引用模块

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
?

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044027

**Comment by QUbn** [comment]
@jeecg/antd-online-mini  这个包能不能按需引入，比如报表设计没有用到，在build 以后的包里不包含此模块
