### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by aibz** [jeecgboot/jeecg-boot#2745]
##### 版本号：
2.4.5
##### 问题描述：
在idea开发环境中system-cloud-start是正常的，但是打包了以后，nacos注册的是modul-system中的端口号
##### 截图&代码：
![微信图片_20210705170631](https://user-images.githubusercontent.com/44859505/124446865-66e37800-ddb3-11eb-90e4-94dcedc9beeb.png)

**Comment by zhangdaiscott** [comment]
说明打包有问题

**Comment by luoqiuqiu** [comment]
你好，请问你解决了吗？我也是这样子。
