### ISSUE TITLE
关于postgresql数据源连接问题

### ISSUE THREAD

**Issue by guccee** [jeecgboot/jeecg-boot#2747]
##### 版本号：
2.4.5

##### 问题描述：
多数据源配置的时候，没有postgresql的选项，因此随便选了个，在jdbc的框按照postgresql的格式写，连接测试能通过。
但是在别的地方使用这个数据源的时候就会出问题，查不出数据，查询界面会一直在加载状态。（配置的MySQL数据源是能正常使用的。）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/58318101/124247581-99436a00-db54-11eb-9286-f957fb674209.png)

![image](https://user-images.githubusercontent.com/58318101/124247448-77e27e00-db54-11eb-9f8d-7a7b574b189e.png)

![image](https://user-images.githubusercontent.com/58318101/124248304-4918d780-db55-11eb-80f1-5b97f37778bf.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by zhangdaiscott** [comment]
下个版本发布
