### ISSUE TITLE
老大，在做online报表配置时，解析成功之后，文本为什么没有带出数据库中的comments

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2748]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124542017-32c09380-de55-11eb-8e2b-97f4733017ef.png)

![image](https://user-images.githubusercontent.com/86937081/124541811-c47bd100-de54-11eb-87a4-10d1cdf36f26.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
手工输入即可
