### ISSUE TITLE
前端页面小导航怎么取消掉

### ISSUE THREAD

**Issue by caodaqing** [jeecgboot/jeecg-boot#2752]
##### 版本号：

2.4.3
##### 问题描述：
怎么把页面的小导航取消掉，系统自带的用户管理等页面都没有

##### 截图&代码：

![image](https://user-images.githubusercontent.com/38416754/124568376-6dd3be80-de77-11eb-8d6f-bdfb6ff08a65.png)

![image](https://user-images.githubusercontent.com/38416754/124568428-7d530780-de77-11eb-918e-282a92ae2ae9.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
菜单配置，父组件
