### ISSUE TITLE
通过什么方式接收外部接口数据和对外提供接口数据

### ISSUE THREAD

**Issue by yangxlCSDN** [jeecgboot/jeecg-boot#2753]
##### 版本号：
2.3.0

##### 问题描述：
通过什么方式可以实现将外部接口数据对接到已创建的自定义表单当中，字段可以映射上，然后可以自定义的对外提供接口数据，麻烦解答一下，谢谢

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
这个需要你自己实现的
