### ISSUE TITLE
使用微服务想执行定时任务,执行任务日志提示执行器地址为空

### ISSUE THREAD

**Issue by jjhgxk** [jeecgboot/jeecg-boot#2756]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/62579413/124709913-a387ae80-df2e-11eb-83bd-950353e55ec0.png)
![image](https://user-images.githubusercontent.com/62579413/124709960-b306f780-df2e-11eb-94a1-c2d1926bb022.png)
![image](https://user-images.githubusercontent.com/62579413/124710064-d467e380-df2e-11eb-8513-712a6d6b54bb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看文档

**Comment by jjhgxk** [comment]
我就是按照你们集成xxl-job的步骤进行的 我要是看文档还来这提问题?
