### ISSUE TITLE
请问大佬，自定义按钮怎么才可以支持多条数据处理

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2757]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/86937081/124712352-ca93af80-df31-11eb-8d86-63743c678142.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by caodaqing** [comment]
我是在批量操作里面加了个按钮

**Comment by jeffZbj** [comment]
怎么加的大佬

**Comment by jeffZbj** [comment]
请问大佬您是生成代码了，用online模式不能实现吗

**Comment by xinxingzhao** [comment]
建议直接生成代码，这样可以按照自己的意愿修改，online还是作为辅助的比较好

**Comment by jeffZbj** [comment]
谢谢大佬

**Comment by jeffZbj** [comment]
![image](https://user-images.githubusercontent.com/86937081/125009158-8ec62a80-e096-11eb-98ee-05eb74a76ce4.png)
大佬，再请教一下，生成代码后截图中的自定义按钮和列设置都没有了？

**Comment by xinxingzhao** [comment]
java增强和js增强都不支持代码生成

**Comment by huangwei2013** [comment]
> 建议直接生成代码，这样可以按照自己的意愿修改，online还是作为辅助的比较好

很多功能设计，出发点很好，效果描述很诱人。但实现上，总感觉差两口气，又没有源码可以打patch，可叹可惜

@xinxingzhao
