### ISSUE TITLE
关于报表的查询功能

### ISSUE THREAD

**Issue by jw879** [jeecgboot/jeecg-boot#2760]
版本号：
jeecg 2.4.5

问题描述：
生成的Online报表上方允许查询的字段能否像Online表单一样可以支持下拉搜索查询？
现在只允许单条件和范围查询，是否可以改成支持模糊搜素？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
暂无此计划
