### ISSUE TITLE
后端启动报错，注入beans失败，提示：Field factory in org.jeecg.modules.system.controller.ThirdLoginController required a bean of type 'com.xkcoding.justauth.AuthRequestFactory' that could not be found.

### ISSUE THREAD

**Issue by liwanyin** [jeecgboot/jeecg-boot#2761]
##### 版本号：
版本号2.4.5

##### 问题描述：
后端启动报错，注入beans失败，提示：Field factory in org.jeecg.modules.system.controller.ThirdLoginController required a bean of type 'com.xkcoding.justauth.AuthRequestFactory' that could not be found.
The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'authRequestFactory' in 'JustAuthAutoConfiguration' not loaded because @ConditionalOnProperty (justauth.enabled=true) found different value in property 'enabled'

Action:

Consider revisiting the entries above or defining a bean of type 'com.xkcoding.justauth.AuthRequestFactory' in your configuration.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11974866/124742708-9202ce80-df4f-11eb-99c2-79cfb2643318.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
改路径了吧，保留jeecg的路径

**Comment by sdvdxl** [comment]
justauth:
  enabled: false


设置为false 就报这个错，true 不会报
