### ISSUE TITLE
代码生成器失效，无法自动生成mapper、controller等文件

### ISSUE THREAD

**Issue by TonyWang972** [jeecgboot/jeecg-boot#2762]
##### 版本号：
2.4.5

##### 问题描述：
在页面中可以正常进行增删改查，但是创建表之后不会自动在\jeecg-boot\jeecg-boot-module-system\src\main\java\org\jeecg\modules目录下生成mapper、controller等文件，使用代码生成器也会报错，不知道从何入手找BUG

##### 截图&代码：
后台报错信息：
`2021-07-07 19:49:41.976 [http-nio-8080-exec-3] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:57 - Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.jeecgframework.codegenerate.generate.pojo.ColumnVo.setExtendParams(Ljava/util/Map;)V
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.jeecgframework.codegenerate.generate.pojo.ColumnVo.setExtendParams(Ljava/util/Map;)V
`

前端报错信息：
![image](https://user-images.githubusercontent.com/55622087/124754834-3e977d00-df5d-11eb-801d-6694a2953f68.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你改坏东西了，或者环境没弄好
