### ISSUE TITLE
jddate问题

### ISSUE THREAD

**Issue by c270348095** [jeecgboot/jeecg-boot#2765]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/12913916/124846358-38d88080-dfcb-11eb-9964-fa1d38e91515.png)
![image](https://user-images.githubusercontent.com/12913916/124846380-41c95200-dfcb-11eb-855e-5361cdcf94d5.png)
![image](https://user-images.githubusercontent.com/12913916/124846399-4beb5080-dfcb-11eb-869d-d3507ec1ae9d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己写的，自己排除
