### ISSUE TITLE
大佬！js增强无效！在online表单开发后，默认风格样式，下面的附表增加js增强无论是list和fom都无效

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2768]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/124889620-da7ec280-e009-11eb-80e7-216d7bd992da.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
附表不支持js增强
