### ISSUE TITLE
online表单开发，配置成内嵌菜单后，点击+号报无权限访问

### ISSUE THREAD

**Issue by enterprising666** [jeecgboot/jeecg-boot#2769]
##### 版本号：
2.4.3

##### 问题描述：
online表单开发，配置成内嵌菜单后，点击+号报无权限访问，
跟踪代码发现只有getOnlineErpCode没有对内嵌表格获取code的方法，
点击+号后传的是cgrhead_id，此时构造的possibleUrl 有问题的，当然找不到菜单了

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by enterprising666** [comment]
除非是授权 online表单开发菜单权限，但实际业务场景用户并不一定需要online表单开发权限的

**Comment by enterprising666** [comment]
而且对于内嵌表单来说，tabletype 并非获取到
**String var9 = request.getParameter("tabletype");**
                if (this.b == null) {
                    this.b = (IOnlineBaseAPI)SpringContextUtils.getBean(IOnlineBaseAPI.class);
                }

                **var8 = this.b.getOnlineErpCode(var8, var9);**

**Comment by enterprising666** [comment]
而且对于内嵌表单来说，tabletype 并非获取到

**Comment by enterprising666** [comment]
对于内嵌表，能根据子表headid找到主表的headid 就能解决了，因为配的菜单就是主表的

**Comment by zhangdaiscott** [comment]
升级到最新版看看

**Comment by zhangdaiscott** [comment]
收录 sq (测)

**Comment by lsqGitHub716** [comment]
你是online开发，表单配置成内嵌风格后，功能测试，点+号报错吗？

**Comment by enterprising666** [comment]
嗯，新配得online表单开发菜单报无权限，角色是新创建得，auto权限也授权了。跟踪代码发现对于内嵌表格后端没收到tabletype参数导致进不去var8 = this.b.getOnlineErpCode(var8, var9); 方法所以报错了。如果高版本没有此问题，请忽略。

**Comment by enterprising666** [comment]
![image](https://user-images.githubusercontent.com/36030976/125256133-b8997e80-e32e-11eb-8776-ded072d10633.png)
getOnlineErpCode方法里仍需增加对innserTable得判断才行，如上图标色部分
