### ISSUE TITLE
想请教一下，popup里加了查询条件后，输入框里的placeholder怎么实现多语种，前端似乎没有源文件

### ISSUE THREAD

**Issue by pwyGouxiong** [jeecgboot/jeecg-boot#2770]
##### 版本号：
2.2.1

##### 问题描述：
想请教一下，popup里加了查询条件后，这个输入框的plea的“请输入”三个字翻译怎么改，因为是多语种项目。前端这边相关的代码看过了，似乎没有源码，请问这部分源码在哪里？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26954826/124894212-08660600-e00e-11eb-8187-1e3537f6700d.png)

![image](https://user-images.githubusercontent.com/26954826/124894082-e8364700-e00d-11eb-8739-40d50641069d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
国际化貌似还没支持吧？

**Comment by pwyGouxiong** [comment]
> 国际化貌似还没支持吧？

你说jeecg嘛？大体上是支持的，用i18n，也有需要自己改造一下。但是这个Jpopup是报表开发的，前端没源码，不知道怎么去改

**Comment by zhangdaiscott** [comment]
这块的代码没开放，改不了

**Comment by pwyGouxiong** [comment]
> 这块的代码没开放，改不了

那国际化的项目关于这里岂不是。。。。。。。。em
