### ISSUE TITLE
JEditable Table行数较多的时候卡顿

### ISSUE THREAD

**Issue by HWGALLEN** [jeecgboot/jeecg-boot#2771]
##### 版本号：
2.4.5

##### 问题描述：
当JEditable Table的数据量比较大（测试的时候每行18列，一共90行），滚动的时候会卡顿。
在测试数据有90行的时候，新增一行数据之后，点击主界面确定会卡几秒钟，然后才提交数据。
用add()增加90行，然后用setValues给每一行设置值时，主界面会卡住不动。
有没有什么解决方案。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
用新的组件
http://doc.jeecg.com/2043991
