### ISSUE TITLE
浏览器访问后端地址出错

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2772]
##### 版本号：
2.4.5

##### 问题描述：
获取验证码出错 报错如下
![image](https://user-images.githubusercontent.com/42630572/125046199-5fccaa80-e0d0-11eb-9c90-dad70061cdfc.png)
把验证码单独拿出来访问
![image](https://user-images.githubusercontent.com/42630572/125045952-1ed49600-e0d0-11eb-9027-6c878e1711e6.png)
但是在postman访问就正常
![image](https://user-images.githubusercontent.com/42630572/125046359-84c11d80-e0d0-11eb-955c-a29d2d6ea211.png)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tuikoushui** [comment]
后端端口换一个，6000是Chrome 默认非安全端口
