### ISSUE TITLE
请问子表要如何查询，在前台仿照主表添加子表信息的fieldList无法正常运行

### ISSUE THREAD

**Issue by 1575854147** [jeecgboot/jeecg-boot#2773]
##### 截图&代码：
![查询构造器](https://user-images.githubusercontent.com/36785328/125051938-09626a80-e0d6-11eb-80dd-153083c86883.png)
![前台](https://user-images.githubusercontent.com/36785328/125051943-0a939780-e0d6-11eb-8265-2873bee12a61.png)
![error](https://user-images.githubusercontent.com/36785328/125051947-0b2c2e00-e0d6-11eb-8c0b-2520d0568677.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
自己编码实现
