### ISSUE TITLE
websocket断开与服务自动停止

### ISSUE THREAD

**Issue by CaoZhengxi** [jeecgboot/jeecg-boot#2774]
##### 版本号：
2.4.5

##### 问题描述：
nginx配置了websocket代理，可以连接，nginx设置了proxy_read_timeout 3600s 一给小时会报错一次，过几个小时jar服务自动停止了，目前找不到jar停止的原因，谢谢！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20114648/125168428-241d0800-e1d8-11eb-9f16-6ce06dcab08a.png)

![image](https://user-images.githubusercontent.com/20114648/125168443-339c5100-e1d8-11eb-907a-ca5bb31166ee.png)
![image](https://user-images.githubusercontent.com/20114648/125168474-50d11f80-e1d8-11eb-9069-1cc9a1666561.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不用nginx看看

**Comment by SuperRichZhao** [comment]
@CaoZhengxi 你好，我遇到了同样的问题，也是这样的报错，只不过我是36秒就会断掉，请问您解决了吗
