### ISSUE TITLE
部署cloud-system失败，读取到单体system的配置文件，而不是nacos的，其他服务正常读取nacos的配置文件

### ISSUE THREAD

**Issue by luoqiuqiu** [jeecgboot/jeecg-boot#2776]
##### 问题描述：
部署cloud-system失败，读取到单体system的配置文件，而不是nacos的，其他服务正常读取nacos的配置文件

##### 截图&代码：
1、单体system的skip改成了true
![image](https://user-images.githubusercontent.com/52776176/125220983-1cee1b00-e2fa-11eb-8243-15e0af261112.png)
2、install打包
3、启动语句java -jar jeecg-cloud-system-start-2.4.5.jar  --server.port=7003  --spring.profiles.active=prod
4、报数据库连接失败，经过检查，读取了单体system的配置文件

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个得看你自己的打包

**Comment by luoqiuqiu** [comment]
> 这个得看你自己的打包
自己的打包是什么意思？

**Comment by luoqiuqiu** [comment]
有什么特殊的打包配置吗？或者步骤吗？

**Comment by luoqiuqiu** [comment]
> 这个得看你自己的打包

我就是按照文档的步骤打包的，我知道我打包出问题了，所以读到了单体的配置文件，那你要告诉我怎么打包才不会出现问题吧。

**Comment by luoqiuqiu** [comment]
> 这个得看你自己的打包
 理理我理理我
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
我们无法排除，自己坚持下打的包
