### ISSUE TITLE
请问通过菜单配置出来的vue页面，怎么把这个路由的keepAlive改为true

### ISSUE THREAD

**Issue by pwyGouxiong** [jeecgboot/jeecg-boot#2779]
##### 问题描述：
通过菜单配置出来的vue页面，怎么把这个路由的keepAlive改为true。
因为有个需求是，当由a页面跳转到b页面再回到a页面时，a页面不刷新。

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
online菜单？

**Comment by pwyGouxiong** [comment]
> online菜单？

嗯嗯，是的，就是通过菜单配置配置出来的路由菜单

**Comment by pwyGouxiong** [comment]
> online菜单？

嗯嗯，是的，就是通过菜单配置配置出来的路由菜单

**Comment by zhangdaiscott** [comment]
目前不支持
