### ISSUE TITLE
entity实体中的字段使用了@Dict注解，通过service中的list方法查询出的结果，怎么才能显示xx_dictText

### ISSUE THREAD

**Issue by wan84** [jeecgboot/jeecg-boot#2780]
##### 版本号：

v2.4.5
##### 问题描述：

直接通过service中的list(new QueryWrapper)查询的entity中，注解了@Dict的字段，怎么显示xx_dictText

如图最后一张图，返回的结果中并没有useScene_dictText字段，注，不是ant-design-vue-jeecg项目中，而是另加了一个h5前段

##### 截图&代码：

![image](https://user-images.githubusercontent.com/4098915/125403100-b515fe00-e3e7-11eb-83d7-02bee42d9e74.png)
![image](https://user-images.githubusercontent.com/4098915/125403153-c52ddd80-e3e7-11eb-9e68-9a26f4530582.png)
![image](https://user-images.githubusercontent.com/4098915/125403222-de368e80-e3e7-11eb-8dc3-0f34441f042c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
需要是分页的结果才行

**Comment by wan84** [comment]
> 需要是分页的结果才行

不分页，如果手动映射出结果呢？

**Comment by xinxingzhao** [comment]
> > 需要是分页的结果才行
> 
> 不分页，如果手动映射出结果呢？

可以自己写AOP方法扩展实现
