### ISSUE TITLE
请问导出的@EXCEL字典表注解功能，需要自己实现吗

### ISSUE THREAD

**Issue by 1575854147** [jeecgboot/jeecg-boot#2781]
##### 截图&代码：
![代码和表](https://user-images.githubusercontent.com/36785328/125411081-2a85cc80-e3f0-11eb-8b20-65390b8af63e.png)
![引出效果](https://user-images.githubusercontent.com/36785328/125411099-2d80bd00-e3f0-11eb-940f-465f5fa2e51d.png)
![receive_pay_number表](https://user-images.githubusercontent.com/36785328/125411667-b7c92100-e3f0-11eb-8348-2ca4034b8a9c.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
配置错误

**Comment by a123456wlzhyy** [comment]
遇到相同问题 哪里错了？？

**Comment by 1575854147** [comment]
> 遇到相同的问题 哪里错了？
要在vo文件夹下的xxxxPage里加注解，entity里加是不够的

**Comment by 1575854147** [comment]
> 遇到相同的问题 哪里错了？

要在vo文件夹下的xxxxPage里加注解，entity里加是不够的
