### ISSUE TITLE
进不去一直在加载中

### ISSUE THREAD

**Issue by Aixiaocheng1** [jeecgboot/jeecg-boot#2782]
##### 截图&代码：![image](https://user-images.githubusercontent.com/43107356/125422830-18e1a9f2-b660-4c41-80a6-723fcabae2a7.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by Aixiaocheng1** [comment]
关键是不报错，就是一直在加载，用最新下拉的源码 跑起来卡在加载中一会 还会让电脑直接断网

**Comment by HWGALLEN** [comment]
你检查一下浏览器的版本，用Google Chrome按F12，然后刷新一下页面就会有提示，很大概率是浏览器版本太低了。

**Comment by Aixiaocheng1** [comment]
![1626231634(1)](https://user-images.githubusercontent.com/43107356/125554259-f818a499-7d4e-4a18-97c4-44067de98926.jpg)
最新的360极速浏览器 切换成极速版 也进不去，node用的是14.17.3 长期支持版，vue cli 用4.0.0，其他vue项目一下就可以了

**Comment by zhangdaiscott** [comment]
确认演示地址
http://boot.jeecg.com

**Comment by Aixiaocheng1** [comment]
演示地址可以直接进

> 确认演示地址
> http://boot.jeecg.com

演示地址可以直接进

**Comment by Aixiaocheng1** [comment]
![image](https://user-images.githubusercontent.com/43107356/125557033-fc0bb8f1-c877-4801-bc79-c5e32501e3b9.png)
本地打包的文件可以进，执行开发 启动的不行

**Comment by Aixiaocheng1** [comment]
1、关闭 devtools 
2、电脑重启并更新
3、还原google默认设置 （我新安装的浏览器都会复制google的全部书签，不知道是不是也复制了配置）
**不知道这上面哪一步是正确的方式（现在问题解决）**

**Comment by TBX1314521** [comment]
你的解决了吗.大佬,我也是遇到这样的情况
