### ISSUE TITLE
代码优化和规范（ExcelImportServer.class）

### ISSUE THREAD

**Issue by mypeak** [jeecgboot/jeecg-boot#2783]
##### 问题描述：excel导入，打印这个异常
![image](https://user-images.githubusercontent.com/35057637/125423576-6fca6b94-2909-4ae0-ac06-6240622a42b9.png)

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35057637/125423317-c2f530a1-e6e1-44c3-9b22-ac3c39ef1c86.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
您的问题是什么？是这个方法的代码要规范一下吗？

**Comment by xinxingzhao** [comment]
> 您的问题是什么？是这个方法的代码要规范一下吗？

他的意思是不要用system 的打印日志，而是要用log

**Comment by lsqGitHub716** [comment]
已处理，下版本发布

**Comment by mypeak** [comment]
> 已处理，下发布版本
谢谢大佬
