### ISSUE TITLE
JVxeTable用loadNewData问题

### ISSUE THREAD

**Issue by HWGALLEN** [jeecgboot/jeecg-boot#2784]
##### 版本号：
2.4.5

##### 问题描述：
在一对多中，用JVxeTable的loadNewData方法读取数据，点击确定之后会将行的临时id保存到数据库中，是用法不对还是别的问题？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23203833/125467538-f6992fc4-7b94-496d-9c89-68ac48cd8e74.png)
![image](https://user-images.githubusercontent.com/23203833/125467754-f0d572f8-3f09-4a18-9189-7514f0cf1161.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by zhangdaiscott** [comment]
src/components/jeecg/JVxeTable/components/JVxeTable.js
```
    /**
     * 加载新数据，和 loadData 不同的是，用该方法加载的数据都是相当于点新增按钮新增的数据。
     * 适用于不是数据库里查出来的没有id的临时数据
     * @param dataSource
     */
    async loadNewData(dataSource) {
      if (Array.isArray(dataSource)) {
        let {xTable} = this.$refs.vxe.$refs
        // issues/2784
        // 先清空所有数据
        xTable.loadData([])
        // 再新增
        return xTable.insertAt(dataSource)
      }
      return []
    },
```
