### ISSUE TITLE
OnlineForm.css里有语法错误

### ISSUE THREAD

**Issue by sanmao3** [jeecgboot/jeecg-boot#2785]
##### 版本号：
"version": "2.4.5-RC"

##### 问题描述：
.css文件里有less写法

##### 截图&代码：
<img width="765" alt="截屏2021-07-14上午11 05 20" src="https://user-images.githubusercontent.com/5188427/125554612-c2524149-554a-46f5-8e5a-30342d75a3cb.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
影响功能使用？不影响忽略
