### ISSUE TITLE
online报表查询超时

### ISSUE THREAD

**Issue by zy528** [jeecgboot/jeecg-boot#2786]
##### 版本号：
2.4.0

##### 问题描述：
onlin报表查询超过9秒，前端超时

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30794610/125558022-0fbdbc0b-c3a9-409f-bb94-fd629e0ecef4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
最新版，已经取消了前端超时设置
