### ISSUE TITLE
下拉搜索框字段字典table加条件问题

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#2787]
##### 版本号：
2.4.5

##### 问题描述：
不知道是字典table内容配置的太长的原因还是怎么回事，后端断点配置的表名后面加的条件一部分SQL语句丢失，如下图！这种情况能解决么？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/125574132-33cd1841-ac1b-4681-8596-778359bd7869.png)

![image](https://user-images.githubusercontent.com/55084864/125573705-fc285185-ab85-4e26-b855-2390b5f60454.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看看数据库保存的值对不对

**Comment by tb2888** [comment]
是说这里么？这里没问题，这里SQL是全的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张代浩@***@***.***&gt;; 
发送时间: 2021年7月14日(星期三) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 下拉搜索框字段字典table加条件问题 (#2787)





 
看看数据库保存的值对不对

**Comment by tb2888** [comment]
我把SQL换短一点是没问题的，






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 下拉搜索框字段字典table加条件问题 (#2787)





 
看看数据库保存的值对不对

**Comment by tb2888** [comment]
> 看看数据库保存的值对不对

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
你把`onl_cgform_field`表的`dict_table`字段改长点试试

![image](https://user-images.githubusercontent.com/34293221/127129169-543a0b34-e3d1-426b-9a92-b69c9236a409.png)

**Comment by tb2888** [comment]
> 你把`onl_cgform_field`表的`dict_table`字段改长点试试
> 
> ![image](https://user-images.githubusercontent.com/34293221/127129169-543a0b34-e3d1-426b-9a92-b69c9236a409.png)

没用的！不是这个的问题，插入数据库的值是完整的！再说，如果是数据库设置的字段长度不够会报错：too long，不能保存成功的

**Comment by sjlei** [comment]
> 没用的！不是这个的问题，插入数据库的值是完整的！再说，如果是数据库设置的字段长度不够会报错：too long，不能保存成功的

那我测试的是没有问题，你把你的sql发过来我测试一下。

**Comment by tb2888** [comment]
> > 没用的！不是这个的问题，插入数据库的值是完整的！再说，如果是数据库设置的字段长度不够会报错：too long，不能保存成功的
> 
> 那我测试的是没有问题，你把你的sql发过来我测试一下。

![image](https://user-images.githubusercontent.com/55084864/127132661-3f2f2419-8b81-43ed-b554-2bd145b7b903.png)
下面这条SQL的长度是没问题的，上面那条不行，超过图中划线位置就不行了

**Comment by sjlei** [comment]
你可以去演示系统上测试一下 <http://boot.jeecg.com>

**Comment by tb2888** [comment]
> 你可以去演示系统上测试一下 http://boot.jeecg.com

刚刚试了演示系统好像没问题了，只有表名不一样
