### ISSUE TITLE
autopoi 复杂excel key-value导入开发时 无文档中的方法

### ISSUE THREAD

**Issue by BIIgZz** [jeecgboot/jeecg-boot#2789]
##### 问题描述：
autopoi 复杂excel key-value导入文档中有setKeyMark() setReadSingleCell（）方法，而实际开发中却没有

##### 截图&代码：

![image](https://user-images.githubusercontent.com/27594205/125627492-223d9fd2-4520-4cb5-8ff8-7c614b2b0e0f.png)

![image](https://user-images.githubusercontent.com/27594205/125627646-2322807b-9d31-41ac-abf3-daea3007fd2d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已测试，问题存在，待修改

**Comment by zhangdaiscott** [comment]
先归集到 https://github.com/jeecgboot/jeecg-boot/issues/1312
