### ISSUE TITLE
IllegalAccessError: class lombok.javac.apt.LombokProcessor

### ISSUE THREAD

**Issue by John88888888** [jeecgboot/jeecg-boot#2790]
##### 版本号：
jeecg-boot 2.4.5
JDK 16
##### 问题描述：
工程无法启动，启动报错
java: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x5034840b) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x5034840b

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
lombok 插件装了吗

**Comment by zhangdaiscott** [comment]
https://www.cjavapy.com/article/1932/
