### ISSUE TITLE
配置聚合菜单后报错：Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edana-dev** [jeecgboot/jeecg-boot#2791]
##### 版本号：
2.4.5

##### 问题描述：
在菜单里配置聚合菜单后，菜单加载空白，并且控制台报错：[Vue warn]: Error in render: "RangeError: Maximum call stack size exceeded"

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5830134/125727013-674f7553-5f64-4b2e-8e84-79bfb60293b0.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
经测试，聚合路由的配置没有问题，可能是你配错了。
配置文档：<http://doc.jeecg.com/2043937>

这一点需要注意：
![image](https://user-images.githubusercontent.com/34293221/127128437-d3c8f457-abc3-4855-8e03-35f20b460710.png)

**Comment by edana-dev** [comment]
嗯，是没有照这个配置来做的。
