### ISSUE TITLE
删除租户时,未验证租户是否已被引用

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/jeecg-boot#2795]
##### 版本号：
2.4.5

##### 问题描述：
删除租户时,没有判断该租户是否已经与某个用户绑定,依赖可以删除,删除后该用户依然可以登陆,并在请求中依赖可以拿到租户的ID。

#####  #截图&代码：
![无标题](https://user-images.githubusercontent.com/26646785/125882746-94421782-069f-45ee-9c2d-8e204460aa9e.png)
![无标题](https://user-images.githubusercontent.com/26646785/125882908-7a6d86b1-73df-4a65-9d12-ddfd1fc270e0.png)
已经删除了10002的租户,该用户依解可以登陆.
建议对已使用的租户不能进行删除.

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  jl
