### ISSUE TITLE
已冻结的租户下的用户依然可以登陆

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/jeecg-boot#2796]
##### 截图&代码：
![无标题](https://user-images.githubusercontent.com/26646785/125883952-b842d9e8-c32b-4b02-92e5-0c76d72587d1.png)
![无标题](https://user-images.githubusercontent.com/26646785/125884614-dd3c02cb-791f-4c86-bdfc-62c3c5de9848.png)
将租户结束时间调整为当前时间之前后,该租户下用户依然可以登陆

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
