### ISSUE TITLE
增加额外表查询条件功能

### ISSUE THREAD

**Issue by guaicaiboshi** [jeecgboot/jeecg-boot#2797]
##### 问题描述：
A B 2个表， 界面查询展示的列表是A表，B是A的一个关联表，界面查询条件想增加一个B表的 type字段作为查询条件，这个是否支持？

##### 截图&代码：

我们的项目是否支持这种配置操作？

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
可以通过冗余字段实现，或者用online报表，或者生成代码自己修改

**Comment by zhangdaiscott** [comment]
online下个版本支持，代码生成的自己改
