### ISSUE TITLE
下拉多选框查询配置不显示引用字典内容

### ISSUE THREAD

**Issue by Code-prodigal** [jeecgboot/jeecg-boot#2798]
##### 版本号：
Jeecg  Boot Version: 2.4.5
Spring Boot Version: 2.3.5.RELEASE (v2.3.5.RELEASE)

##### 问题描述：
下拉多选框使用查询配置因为字典数据后  数据不显示，换成单选框后没有问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/32701259/125888413-230312a5-21d4-4005-9b63-ee54b0e6b38b.png)
![image](https://user-images.githubusercontent.com/32701259/125888511-c39d13c5-752f-4d23-be2c-e20d6564e622.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你没有字段配置，不出来不是对的吗
