### ISSUE TITLE
 ##### 问题描述：online制作的表单，导入时，可以做唯一性校验吗，请大佬看图

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2800]
##### 截图&代码：
![QQ图片20210716162748](https://user-images.githubusercontent.com/86937081/125917427-8d490671-d3a1-4c3c-9b68-0c7aa0ac8bc1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
其实不只是online的导入，生成的代码也希望加入检验规则，例如必填和唯一校验

**Comment by zhangdaiscott** [comment]
最新版应该支持，如果不支持可以自定义导入的增强

**Comment by tygithub1** [comment]
导入时，唯一校验 不支持
