### ISSUE TITLE
大佬请看，在online报表配置中，如果一个字段为查询项，无法设置这个查询项为popup

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2801]
##### 截图&代码：
![QQ图片20210716163004](https://user-images.githubusercontent.com/86937081/125917784-c7a48d5c-a9b8-4d93-b06b-7f1490af345a.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
online报表为什么要支持popup
