### ISSUE TITLE
jeecgboot不同页面切换会重新刷新页面，导致原本页面中输入的查询条件丢失

### ISSUE THREAD

**Issue by taoqinci2021** [jeecgboot/jeecg-boot#2804]
##### 版本号：
2.4

##### 问题描述：
jeecgboot框架中打开一个页面后，输入相关查询条件查询一条特定的数据，然后在打开别的页面后在切回有查询条件的页面，此时页面会重新刷新并插叙所有数据。设置缓存路由后也解决不了根本问题，因为只要页面地址变了之后缓存路由也不起作用

##### 截图&代码：
1、打开一个页面输入查询条件：
![图片](https://user-images.githubusercontent.com/87628085/126096765-8890855d-bd18-448e-80dc-a6a31f84b615.png)
2、在打开另外一个页面
![图片](https://user-images.githubusercontent.com/87628085/126096815-8d182dd5-0b0c-42d3-b158-cc324551179c.png)
3、然后在切回原来有查询条件的页面，此时该页面会重新刷新掉，原来的查询数据会被重新刷掉，这样系统没法用
![图片](https://user-images.githubusercontent.com/87628085/126096885-b47c1380-43ac-4dab-bfe5-17e162c0e8d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by ToDarcy** [comment]
https://www.cnblogs.com/wendy-0901/p/14385665.html

看这个

**Comment by zhangdaiscott** [comment]
未修复，暂时归集到https://github.com/jeecgboot/jeecg-boot/issues/1312

**Comment by taoqinci2021** [comment]
请问以上问题解决没，后续没法用

**Comment by yellowseasky** [comment]
看看这个代码, 我用得没什么问题https://blog.csdn.net/qq_37322135/article/details/126013301

**Comment by fireinjava** [comment]
`export default {   
     name: 'OrderIndex', //  这个属性少了也会导致切换tab刷新
}
`
