### ISSUE TITLE
前端List页面增加其它表的字段显示，如何实现？

### ISSUE THREAD

**Issue by gicp** [jeecgboot/jeecg-boot#2805]
##### 版本号：
2.3.5.RELEASE

##### 问题描述：
前端List页面增加其它表的字段显示，如何实现？

##### 截图&代码：
![微信图片_20200917184016](https://user-images.githubusercontent.com/31814666/126118481-ec593d89-2f9d-4b95-b8fd-b6c27aa994ce.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by xinxingzhao** [comment]
如果是Online开发的话，你需要在表里面新增冗余字段，如果你已经生成代码了，那你就直接改代码，重新写一个分页查询好了
