### ISSUE TITLE
求教：列表页，想在数据load后做一些逻辑处理，如何操作？是否有钩子？

### ISSUE THREAD

**Issue by TheMrCoder** [jeecgboot/jeecg-boot#2806]
##### 问题描述：
列表页，想在数据load后做一些逻辑处理，如何操作？是否有钩子？

##### 截图&代码：
create执行时似乎数据还没加载出来

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by TheMrCoder** [comment]
补充：在线表单开发

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
暂不支持功能归集 #1312
