### ISSUE TITLE
省市区组件的字典怎么维护

### ISSUE THREAD

**Issue by i-Hu** [jeecgboot/jeecg-boot#2807]
##### 版本号：
2.4.5

##### 问题描述：
从area-data更新到china-area-data后，新增的区划显示异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/126271204-36160e8b-ab73-4c02-844e-391f679e0720.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
jeecg-boot-module-demo/org/jeecg/modules/demo/mock/json/area.json
