### ISSUE TITLE
可能是重大bug：在改变浏览器窗体大小时，页面重新加载，内容被清空

### ISSUE THREAD

**Issue by sunsdy2018** [jeecgboot/jeecg-boot#2808]
##### 版本号：
2.4.5

##### 问题描述：
您好，这可能是一个bug。我新增了一个页面，上面有一个画布，画上了东西。在调整浏览器大小时，当大小变化到一定程度时，页面会有一层灰色半透明蒙版，左侧的导航栏会突出显示，而画布上的内容全都消失。
不知道这是一个bug，还是说我有哪里设置不对

##### 截图&代码：
第一步：
![image](https://user-images.githubusercontent.com/38706610/126277294-5842555c-a57a-4050-8b2b-611d972c86d9.png)

第二步：
左右拖动浏览器，让它变小，到一定程度时，页面会有一层灰色半透明蒙版，左侧的导航栏会突出显示，而画布上的内容全都消失。
![image](https://user-images.githubusercontent.com/38706610/126277457-a13804a1-b2a8-4478-90b1-2cc8bcf8f2ad.png)

第三步：
继续缩小
![image](https://user-images.githubusercontent.com/38706610/126277556-246fcac5-d1ae-4c32-96f6-e9a6674915aa.png)

第四步：
左右拖动窗体，放大，画布不会自动重新画上

打开F12，在vue的created()里面console.log('created')，发现在第二步时，会执行这个log语句

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by sunsdy2018** [comment]
qq群里有人提示设置缓存路由的解决办法，经尝试，没有用的

**Comment by zhangdaiscott** [comment]
不是bug，这是页面做的自适应逻辑

**Comment by sunsdy2018** [comment]
既然是自适应逻辑，那不能把内容清空啊

**Comment by sunsdy2018** [comment]
自适应缩放改的是界面，而非内容。把内容清空的自适应逻辑，就已经是错误的逻辑了。
另外，console.log('created')显示，在自适应过程中，原网页被摧毁，重新加载了网页。
逻辑不能这么写。

**Comment by sunsdy2018** [comment]
贸然把问题关闭，不合理吧

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/804
