### ISSUE TITLE
JSearchSelectTag 在火狐浏览器滑动时会出现空白

### ISSUE THREAD

**Issue by SunJianMing** [jeecgboot/jeecg-boot#2809]
##### 问题描述：
在火狐浏览器使用JSearchSelectTag下拉框，用鼠标在上面上下滑动是，文字会消失

##### 截图&代码：
![1901626833148_ pic](https://user-images.githubusercontent.com/22882394/126419169-1995f499-7db5-446b-b1c1-5a7ec6d70a6f.jpg)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by lsqGitHub716** [comment]
你的火狐版本是什么？你的常用实例下面的
![image](https://user-images.githubusercontent.com/65587928/126974899-598cd710-c0c7-4d5e-95ac-4845de1b6e3c.png)
xianshi显示的正常吗？
