### ISSUE TITLE
系统自带定时任务启动项目不执行

### ISSUE THREAD

**Issue by ikenneth** [jeecgboot/jeecg-boot#2811]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/7484551/126454614-c74934a8-d16f-4ca3-be7a-48cf438f1c92.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
看看是不是类似问题
https://github.com/jeecgboot/jeecg-boot/issues/1997
