### ISSUE TITLE
最新代码在开发环境无法在ie11上打开

### ISSUE THREAD

**Issue by wengfengtong** [jeecgboot/jeecg-boot#2812]
##### 版本号：
2.4.5（发布日期：20210607）

##### 问题描述：
拉取最新代码在本地运行无法在ie11上打开，一直在加载中。
发布到线上之后可以打开

##### 截图&代码：

![image](https://user-images.githubusercontent.com/37279162/126499504-95b6809a-ae95-450a-975f-6effccc8fe61.png)

**Comment by zhangdaiscott** [comment]
？

**Comment by wengfengtong** [comment]
可以拉取到本地试试哦

**Comment by zhangdaiscott** [comment]
依赖改成这个版本，并按照下面的链接说明做配置
`    "@jeecg/antd-online-mini": "2.4.5-RC2",`

https://www.npmjs.com/package/@jeecg/antd-online-mini
