### ISSUE TITLE
多租户安全问题

### ISSUE THREAD

**Issue by edana-dev** [jeecgboot/jeecg-boot#2814]
##### 版本号：
3.4.5

##### 问题描述：
目前多租户只通过HTTP头判断，且没有校验当前用户是否属于此租户，所以存在越权操作的可能。

##### 截图&代码：
org.jeecg.config.shiro.filters.JwtFilter
![image](https://user-images.githubusercontent.com/5830134/126584956-79c4359f-8854-4c44-a6a0-7691f50bc642.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
已处理，下版本发布
