### ISSUE TITLE
beforeDelete无效

### ISSUE THREAD

**Issue by hlning** [jeecgboot/jeecg-boot#2815]
##### 版本号：
V2.4.5

##### 问题描述：
JS增强，list=>beforeDelete无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57277046/126596575-b3e1de72-f120-4fe6-b833-fb6893944580.png)
![image](https://user-images.githubusercontent.com/57277046/126596637-4b85abd7-a163-4301-ad5b-00319d033fab.png)
![image](https://user-images.githubusercontent.com/57277046/126596649-39a1a4d4-a988-4c87-a63d-204699825f86.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by tygithub1** [comment]
经测试，没有问题，请跟进后续新的版本
![image](https://user-images.githubusercontent.com/27989856/127802273-670c35af-c23c-4749-b52f-a0332aa76e66.png)
