### ISSUE TITLE
主附表代码生成前后页面不同

### ISSUE THREAD

**Issue by bestitxq** [jeecgboot/jeecg-boot#2816]
##### 版本号：
2.4

##### 问题描述：
主附表  代码生成前表单测试与生成代码后校验字段提示样式不同， 且必填也没有显示※号了

##### 截图&代码：
表单开发中：
![image](https://user-images.githubusercontent.com/33947373/126606637-88d811db-60b7-45f9-b670-3660a1ba0568.png)
代码生成后配置菜单显示结果：
![image](https://user-images.githubusercontent.com/33947373/126606742-ad997068-2e3b-4ef8-8063-7c883a851c6d.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
你可以选择不同的模板生成
