### ISSUE TITLE
在线表单开发，使用triggleChangeValues设置控件值，页面上已经改变，但表单提交时，字段仍然是空的

### ISSUE THREAD

**Issue by TheMrCoder** [jeecgboot/jeecg-boot#2824]
##### 问题描述：

在线表单开发，使用triggleChangeValues设置控件值，**页面上已经改变**，但表单提交时，字段仍然是空的（不在提交消息体中）

##### 截图&代码：
  let biz={"biz_id":res.info.id}
  that.triggleChangeValues(biz);

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by TheMrCoder** [comment]
补充说明：修改控件值的逻辑在 beforeSubmit函数里，查询接口并将response里的id设置个一个控件

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by tygithub1** [comment]
不支持，  beforeSubmit调用的时候  表单的值已经获取到了，如果你要重新写表单值，直接row.属性名=属性值 即可，不需要再重置控件的值
