### ISSUE TITLE
j-image-upload模块可以改成预览图片时支持左右翻页么

### ISSUE THREAD

**Issue by i-Hu** [jeecgboot/jeecg-boot#2826]
##### 版本号：
2.4.5

##### 问题描述：
j-image-upload模块可以改成预览图片左右翻页么

##### 截图&代码：
图片预览demo可以左右翻页
![image](https://user-images.githubusercontent.com/26364818/126760710-00091024-cf29-4a09-9cc5-be6361197afe.png)
使用上传模块时不能左右翻页
![image](https://user-images.githubusercontent.com/26364818/126760890-366f5171-73d7-44fb-8069-87ebcd788a70.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/126895744-81be6ad5-59e2-4a8c-ab39-280a2c00cb28.png)

常用示例里面有例子，可以自己参考做
