### ISSUE TITLE
部门管理不显示同步企业微信 为什么呢?

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2827]
##### 版本号：
2.4.5

##### 问题描述：
按照文档说的 在部门管理那里有同步企业微信按钮的
http://doc.jeecg.com/2292481#_65

但是实际跑起来没有  配置文件那里的配置已配置了的

为什么它不显示呢?

##### 截图&代码：
实际效果图:
![image](https://user-images.githubusercontent.com/42630572/126771839-b5c0f1c5-80b6-4cbd-8788-40234634c86b.png)
组件处也有按钮的代码:
![image](https://user-images.githubusercontent.com/42630572/126771967-ff4e0bc4-d5f7-4686-8dff-26d9f3f1c5d2.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
新的部门管理菜单

**Comment by baicaiit** [comment]
那我要怎么显示出来呢
