### ISSUE TITLE
@DS动态数据源使用问题

### ISSUE THREAD

**Issue by wan84** [jeecgboot/jeecg-boot#2829]
##### 版本号：
v2.4.5

##### 问题描述：
@DS 文档建议注解在mapper或service的实现上，

我有如下两个库db1，db2表和结果完全不同

需要在service的实现方法A中，同时向db1.A表和db2.B表插入数据，请问@DS动态数据源应该如何注解

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by wan84** [comment]
为什么不是直接作用的entity上，且数据源和表相关

**Comment by wan84** [comment]
@DS 直接注解在mapper上，service中的getOne,list等方法不会切换数据源？这样切换好复杂，能不能直接在entiry上，或者mapper上注解了，service自动生效

**Comment by wan84** [comment]
还有如下情况如何解决
![image](https://user-images.githubusercontent.com/4098915/126867345-0be7312e-0425-4156-be21-972987522435.png)

**Comment by zhangdaiscott** [comment]
@DS 是mybatis plus的规则
