### ISSUE TITLE
online表单开发，主附表功能一对多功能，编辑附表数据问题

### ISSUE THREAD

**Issue by enterprising666** [jeecgboot/jeecg-boot#2830]
##### 版本号：
2.4.5

##### 问题描述：
场景:附表有数据时，改数据后保存，后台触发sql依然是insert，如果附表某字段disabled，保存后该字段原值会被清空了。
建议：保存时应该先按照主键值更新附表，只更新有值得字段即可。
总结：问题在于不应该全都删除重新insert，应该更新无结果后再将该条数据insert

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
经测试，附表字段设置初始值，然后修改附表表单配置-->是否只读-->勾选 ,再测试，字段原值没有被清空。
并且底层工具类，无论是JVXETable 还是JEditableTable ，字段禁用都不会影响传值。

**Comment by zhangdaiscott** [comment]
online功能测试的确没有问题，禁用字段值没问题；
你是online功能测试，还是代码生成？行组件用的又是那个？
