### ISSUE TITLE
联动组件在生成代码时,变成input框,但是online表单在线测试是正常的

### ISSUE THREAD

**Issue by hsk199805** [jeecgboot/jeecg-boot#2832]
##### 版本号：
2.4.5

##### 问题描述：
联动组件在生成代码时,变成input框,但是online表单在线测试是正常的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49779601/127089019-2a815d70-223d-4ba4-a47b-3dae561d8129.png)
![image](https://user-images.githubusercontent.com/49779601/127089086-73364672-6b58-4e80-9956-1c4c1b3fbcd4.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
联动组件不支持生成，生成后手工编码
