### ISSUE TITLE
j-popup 弹窗组件如何默认选中数据

### ISSUE THREAD

**Issue by PjqDD** [jeecgboot/jeecg-boot#2836]
##### 截图&代码：
![8DD47DA9-5E1B-4100-BE4C-2C3314B0C4B5](https://user-images.githubusercontent.com/44695129/127250277-43546828-8b96-44ae-87ee-f8c536805acb.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
项目有类似的例子，自己找代码参考

**Comment by PjqDD** [comment]
> 项目有类似的例子，自己找代码参考

能找到类似的例子，我还用提交个lssues吗？
![1627630757(1)](https://user-images.githubusercontent.com/44695129/127619460-cd75ae74-7469-419b-980d-df98446338f8.jpg)
