### ISSUE TITLE
j-editable-table FormTypes.slot 类型 无法获取到值

### ISSUE THREAD

**Issue by guaicaiboshi** [jeecgboot/jeecg-boot#2838]
##### 版本号：
2.4.5

##### 问题描述：
https://github.com/jeecgboot/jeecg-boot/issues/1095
参考这个二楼的代码，提示找不到对应的数组，还有就是自定义校验规则提示row一直是“”，以及无法触发(type === 'blur')，我调试发现都是getValues这个类型。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2748771/127258066-1301dcd1-bd13-4dc3-ae58-f43ba8ad4dcf.png)
![image](https://user-images.githubusercontent.com/2748771/127258078-c6038200-f729-4e38-97a4-45dbf5dac0fd.png)
![image](https://user-images.githubusercontent.com/2748771/127258183-2177e20f-d7d9-46fd-84cd-b846850f1e32.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
1、一直是`“”`是正常的，因为slot的值不由JEditable管理。
![image](https://user-images.githubusercontent.com/34293221/127850648-feabc7d1-b93a-4165-8d24-2e68a6a31a4b.png)


2、提示找不到对象是因为JS方法this作用域的问题，可以使用箭头函数，或者保存this对象
```
// 在方法外定义：
let that = this;
```
