### ISSUE TITLE
mybatis plus 3.4.1版本 @SqlParser 注解过时，近期有考虑升级到mybatis plus  3.4.3吗？

### ISSUE THREAD

**Issue by x522491416** [jeecgboot/jeecg-boot#2840]
##### 版本号：
2.4.5

##### 问题描述：
mybatis plus 3.4.1版本 @SqlParser 注解过时，近期有考虑升级到mybatis plus  3.4.3吗？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 sc

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
