### ISSUE TITLE
IE11打开登录页，无法正常显示，一直转圈

### ISSUE THREAD

**Issue by chqing0913** [jeecgboot/jeecg-boot#2841]
##### 问题描述：

IE11打开登录页，无法正常显示，一直转圈。

看之前的issue，提到支持IE11+，且IE11转圈问题已解决，但我拉取的最新master，仍有此问题。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/10457960/127424663-539d910d-2aca-48df-b76f-ff62352c2c20.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
master 未更新

**Comment by chqing0913** [comment]
> master 未更新

哪个分支有更新？新拉下来的2.4.3也不行

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/2812
