### ISSUE TITLE
js增强的代码 应该手动添加到自动生成代码的哪个文件里面呢?

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2842]
##### 版本号：
2.4.5

##### 问题描述：
你好 那个自动生成代码 没有生成js增强的部分  那我写的js增强的代码 应该自己添加到哪里呢? 
还是说这段代码只在在线有效?  如果想在文件实现效果的话 需要用vue的语法来写?
##### 截图&代码：
```
onlChange(){
   return {
    
     type(){
       	console.log(event)
       	console.log(that)
        let value = event.value
        that.sh.ee=false
       	if(value == 3) {
          that.sh.ee=true
        }   
     }
     
    }
 }
```

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by baicaiit** [comment]
这个解决了 通过生成代码 自己控制一个变量的渲染

**Comment by baicaiit** [comment]
还有个疑问?js增强的代码是放到哪里的呢?

**Comment by zhangdaiscott** [comment]
js增强不支持生成

**Comment by baicaiit** [comment]
知道不支持生成 你看描述呀? 我应该把那段写的js代码  手动手动 放到生成的文件哪里?  还是要自己另外写vue的语法才能实现效果

**Comment by baicaiit** [comment]
知道不支持生成 你看描述呀? 我应该把那段写的js代码  手动手动 放到生成的文件哪里?  还是要自己另外写vue的语法才能实现效果

**Comment by baicaiit** [comment]
> js增强不支持生成

知道不支持生成 你看描述呀? 我应该把那段写的js代码 手动手动 放到生成的文件哪里? 还是要自己另外写vue的语法才能实现效果
