### ISSUE TITLE
文档没提他们的用法或者案例

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2844]
##### 版本号：
2.4.5

##### 问题描述：
请问这些有什么用呢? 怎么参考他们? 文档没提他们的用法或者案例? 是要自己去看源码么?

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42630572/127596228-48d397da-f0bd-4a4b-918d-681c5239bfc0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这是页面模板，自己看代码
