### ISSUE TITLE
部署到tomcat ，WebSocket 报404错误

### ISSUE THREAD

**Issue by aijuntao** [jeecgboot/jeecg-boot#2845]
##### 版本号：
 2.4.5

##### 问题描述：
 前端部署到nginx，jeecg-boot 部署到 tomcat，登录、系统功能都正常，
但是websocket 一直报404错误，可能是哪里配置错误呢？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11253104/127617149-0a596fd6-9854-4ec5-a21f-a80b929b3eaf.png)

![image](https://user-images.githubusercontent.com/11253104/127617456-fa179a53-e8b5-4040-a8a8-3a25f14b55a0.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
这个自己部署文档，自己研究
