### ISSUE TITLE
js增强的api 我可以在自定义的代码文件中使用么? 要如何操作呢?

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2846]
##### 版本号：
2.4.5

##### 问题描述：
比如 onlChange() 
that.sh.fieldname 这些api和函数   我可以在自己的代码文件中使用么? 如果可以 应该写在哪里呢?

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
不可以
