### ISSUE TITLE
online 报表 sql数据字典，上面查询结果只显示该页数据有的值，其他值不显示，

### ISSUE THREAD

**Issue by He-Xiao-Bo** [jeecgboot/jeecg-boot#2849]
##### 问题描述：online 报表 sql数据字典，上面查询结果只显示该页数据有的值，其他值不显示
就是我online报表解析完sql后其中一列我用数据字典实现(一条sql)，同时这一列也是放开查询的，但是发现放开查询下拉框不是应该该条sql的全部值吗？但是现在只是该页存在的值，比如该页10条数据都是‘温室系统’ 所以下拉框只有一个值，到第二页10条数据有2个值‘温室系统’和‘净水系统’，那么下拉框显示2个值，帮忙看一下是啥问题，万分感谢，期待你回复

##### 截图&代码：
<img width="668" alt="76865210e774ab0a19afc5e3815fbdc" src="https://user-images.githubusercontent.com/25975216/127798584-aaa601c9-1e83-47b1-bd63-fc5bf3e87c7a.png">
<img width="664" alt="4e86048732080dd302eb44188aabe21" src="https://user-images.githubusercontent.com/25975216/127798596-95041b88-8ffe-4708-ad10-2ce54e3fa86d.png">
<img width="931" alt="0791960124d7113edbf2b316179a80f" src="https://user-images.githubusercontent.com/25975216/127798743-b09411bf-3605-4732-85f9-6bad4b8dc7d5.png">

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
升级到最新版本，已经解决

**Comment by He-Xiao-Bo** [comment]
不想升级到最新的版本，请问升级到2.2.3，是否可以解决这个issue,期待你回复，谢谢～～

**Comment by zhangdaiscott** [comment]
不知道，你自己查看日志，看看是那个版本解决的
