### ISSUE TITLE
jrebel 启动报错  Can't load IA 32-bit .dll on a AMD 64-bit platform

### ISSUE THREAD

**Issue by bswsfhcw** [jeecgboot/jeecg-boot#2850]
##### 问题描述：

Could not find agent library C:\Users\Administrator\.IntelliJIdea2018.2\config\plugins\jr-ide-idea\lib\jrebel6\lib\jrebel32.dll in absolute path, with error: Can't load IA 32-bit .dll on a AMD 64-bit platform

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
跟jeecgboot无关的问题不要提
