### ISSUE TITLE
在线报表导出的合计数据与页面上显示的不一致

### ISSUE THREAD

**Issue by xiaoyizeng** [jeecgboot/jeecg-boot#2852]
##### 版本号：
jeecgboot 2.4.5
##### 问题描述：
菜单位置：在线开发-->在线报表
使用合计功能时，页面上查询得出的结果是正确的，但是导出的execl里面，除了第一个合计的数据是对的，后面的数据合计就是错的了。尝试用了数值型跟长整型，发现问题并没有解决。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/81517044/127828002-3b49ef10-6700-4049-86cc-a396dc994e4c.png)

![image](https://user-images.githubusercontent.com/81517044/127828078-82997620-71b5-47aa-8164-19e4b3bb72d1.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
