### ISSUE TITLE
在linux环境下或者window下的docker desktop中使用docker compose构建的项目,jeecg-boot-system模块无法访问

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2854]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/127843052-d184ef19-cd65-4c6d-9368-5ea538b4a7e9.png)
![image](https://user-images.githubusercontent.com/50698315/127843115-243759ad-2ffe-467e-a735-3d6f20a0ce7f.png)
![image](https://user-images.githubusercontent.com/50698315/127843178-baa39dd4-5910-4f81-88d5-8741268c843e.png)

友情提示： 未按格式要求发帖，会直接删掉。

**Comment by yangkui001** [comment]
官方是否能看到这个帖子.

**Comment by yangkui001** [comment]
![image](https://user-images.githubusercontent.com/50698315/127843684-a61a3b05-40cd-4f16-806a-dc03f7d1c50f.png)
其他模块都启动成功,并且测试也正常

**Comment by zhangdaiscott** [comment]
通过gateway访问，如果需要直接访问把docker7001端口开放出来

**Comment by yangkui001** [comment]
好的，谢谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在linux环境下或者window下的docker desktop中使用docker compose构建的项目,jeecg-boot-system模块无法访问 (#2854)





 
通过gateway访问，如果需要直接访问把docker7001端口开放出来
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yangkui001** [comment]
&nbsp; &nbsp; &nbsp; 用网关访问最开始部署到开发环境报图中错误，F5刷新能成功显示页面，几个小时之后在访问http://192.168.6.188:9999/ 就不能显示首页API了，如图所示，请问这个问题如何解决？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在linux环境下或者window下的docker desktop中使用docker compose构建的项目,jeecg-boot-system模块无法访问 (#2854)





 
通过gateway访问，如果需要直接访问把docker7001端口开放出来
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
