### ISSUE TITLE
upload 上传组件上传图片返回的 base 64 为图片内容被裁剪

### ISSUE THREAD

**Issue by 1690363967** [jeecgboot/jeecg-boot#2856]
##### 版本号：
1.7.6版本

##### 问题描述：
使用 upload 组件上传的图片，过长的图片在上传完毕后图片被放大以及裁减了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52990295/127984436-3f738579-299c-474c-a09c-672e932169cf.png)
上传后的图片

![defaultCar](https://user-images.githubusercontent.com/52990295/127984522-90f1043a-125e-4d28-8660-23f0af02e073.jpg)
上传前的文件

![image](https://user-images.githubusercontent.com/52990295/127984582-578c7c1c-c901-4e86-aa1f-a5d1604a7ada.png)

`//预览图片
    handlePreview(file) {
      this.previewImage = file.url || file.thumbUrl
      this.previewVisible = true
    },
    beforeUpload(file) {
      return new Promise((resolve, reject) => {
        const maxSize = 1024*1024*10
        const isLt10M = file.size < maxSize
        if (!isLt10M) {
          this.$warning({
            title: '上传图片大小不能超过10m！',
            okText: '确定',
          })
          return reject(false)
        }
        const isJpgOrPng = file.type === 'image/jpeg' || file.type === 'image/png'
        if (!isJpgOrPng) {
          this.$warning({
            title: '图片仅支持.JPG和.PNG格式，请选择正确格式的文件',
            okText: '确定',
          })
          return reject(false)
        }
        return resolve(true)
      })
    },
    //上传图片
    handleChangePic(file) {
      console.log('上传文件返回：',file);
      this.fileList = file.fileList
      this.$parent.testView = false
    },`

处理代码

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
是因为你自己写的方法没有对返回的地址做处理，建议使用`JUpload`组件，内部处理了。

![image](https://user-images.githubusercontent.com/34293221/128804747-c267ca1a-b496-47e3-ae0b-c9e0132d56ea.png)
![image](https://user-images.githubusercontent.com/34293221/128804817-9e8c4570-af93-4cc9-b341-9db05c22f000.png)


![image](https://user-images.githubusercontent.com/34293221/128804629-a7fa335a-60d7-4fe1-9215-80aa2be43824.png)

**Comment by 1690363967** [comment]
好的，了解了；感谢
