### ISSUE TITLE
这个是企业微信通知么?还是微信模板消息?

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2857]
##### 版本号：
2.4.5

##### 问题描述：
文档没有提到这个

![1194C7B873226CCFE51DDB3128D7BB3B](https://user-images.githubusercontent.com/42630572/128003073-f7f7b53a-febb-4653-a306-604565c7bed7.jpg)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043950
需要自己实现
