### ISSUE TITLE
系统通知和消息推送 具体有啥区别么

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2859]
##### 版本号：
2.4.5

##### 问题描述：
请问 这两个有啥区别么 文档说的太简单 没怎么看懂  
pushMsgUtil.sendMessage() 和 sysbaseapi接口的方法 有啥区别么

![0B6A669AF411BE0CB5E7CF10A8D5951E](https://user-images.githubusercontent.com/42630572/128003279-700d9582-7ac2-4dc0-aef7-2a2ad1a8ecca.jpg)
![image](https://user-images.githubusercontent.com/42630572/128003301-87e924ea-91a4-4588-935f-80ce1fae7b75.png)
![0B6A669AF411BE0CB5E7CF10A8D5951E](https://user-images.githubusercontent.com/42630572/128003314-36527bae-fe10-4971-a853-6123be3df3fc.jpg)

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
PushMsgUtil 目前项目里目前没用到
