### ISSUE TITLE
【流程设计】怎么从表单中获取下一步流程

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#2860]
##### 问题描述：
一个业务场景，我需要一个人员协助，则创建申请表，填入申请人员名单，
如何在流程表中把下一个审批人设定为我填写的人员？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/128097833-0dfded43-56aa-4f66-860f-9f3730bc7c43.png)
![image](https://user-images.githubusercontent.com/7098009/128098424-8d1bb5d2-c868-4b5a-87fd-d2f4a9e1931e.png)

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
开源没有流程
