### ISSUE TITLE
微服务jeecg-boot-system启动之后一直报rabbitmq错误

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2861]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/128110880-457a6f87-c0c2-4eb3-8766-a137574a906e.png)

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
连上mq即可，不连报错也不影响使用
