### ISSUE TITLE
修改数据为postgre 菜单管理中数据规则添加失败

### ISSUE THREAD

**Issue by 985430026** [jeecgboot/jeecg-boot#2862]
##### 版本号：
 2.2.0

##### 问题描述：
修改数据为postgre
菜单管理中数据规则添加失败
数据库中该字段设置为int4
实体类中该字段设置为boolean
并在数据库中添加
CREATE OR REPLACE FUNCTION "public"."bool_to_integer"(bool)
  RETURNS "pg_catalog"."int4" AS $BODY$        
  select CAST($1::integer as int4);
$BODY$
  LANGUAGE sql VOLATILE STRICT
  COST 100CREATE OR REPLACE FUNCTION "public"."bool_to_integer"(bool)
  RETURNS "pg_catalog"."int4" AS $BODY$        
  select CAST($1::integer as int4);
$BODY$
  LANGUAGE sql VOLATILE STRICT
  COST 100
##### 截图&代码：
![QQ图片20210804105205](https://user-images.githubusercontent.com/58969483/128114426-ec835a3d-7818-4ca1-86e2-cadd2f551aca.png)

麻烦您了

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044271
