### ISSUE TITLE
分类字典使用

### ISSUE THREAD

**Issue by suih-112** [jeecgboot/jeecg-boot#2864]
##### 截图&代码：
![1628129286(1)](https://user-images.githubusercontent.com/56631446/128279686-930ebeea-54be-4be0-8da1-128a68edfa88.png)
![1628129379(1)](https://user-images.githubusercontent.com/56631446/128279809-7617afe2-b972-47be-88f1-79bef1f8a6ea.png)

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
没看明白
