### ISSUE TITLE
大佬，请问现在主付表，可以给附表再增加一个关联表吗。

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2865]
##### 截图&代码：这个不需要截图，大佬别关闭这个问题

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by Benjamin-536** [comment]
貌似不行把

**Comment by zhangdaiscott** [comment]
不支持
