### ISSUE TITLE
oConvertUtils引用问题

### ISSUE THREAD

**Issue by liubinylx** [jeecgboot/jeecg-boot#2866]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/23149881/128286719-50085973-2130-4a7c-b7c3-f56f61914d8e.png)

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
??

**Comment by liubinylx** [comment]
> ??

引用报错，无法引用
