### ISSUE TITLE
JVXETable联动展示与选择BUG

### ISSUE THREAD

**Issue by dlt116616059** [jeecgboot/jeecg-boot#2867]
##### 问题描述：
常见案例中给出的JVXETable示例中的联动示例，使用的@valueChange进行后续控件联动。
第二行录入数据与第一行数据不一致时，修改第一行数据，没有重新根据第一行数据重新获取下拉框选择值。
建议是否增加增加修改前trigger事件，修改前刷新select的options

##### 截图&代码：

![image](https://user-images.githubusercontent.com/13620382/128287500-c68bdced-b32c-48a0-9972-eae80806bc56.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，更新了联动实现方式，更新了联动示例，下版本发布。
