### ISSUE TITLE
使用autopoi导入提示缺少方法

### ISSUE THREAD

**Issue by volfiening** [jeecgboot/jeecg-boot#2868]
##### 版本号：

v2.4.5
##### 问题描述：
使用autopoi导入时报错

##### 截图&代码：
entity实体:
            @Data
@TableName("testuser")
public class TestUser implements Serializable {
    private static final long serialVersionUID = 1L;

    @TableId(type = IdType.ASSIGN_ID)
    private int id;

    @Excel(name = "用户id")
    private String userid;

    @Excel(name = "用户名",width = 30)
    private String username;

}
controller代码：
           MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;
            List<MultipartFile> files = multipartRequest.getFiles("file");
            MultipartFile file = files.get(0);

            //导入excel
            ImportParams params = new ImportParams();
            params.setHeadRows(0);
            params.setSheetNum(1);
            params.setNeedSave(false);
            boolean flag = ExcelImportCheckUtil.check(file.getInputStream(),TestUser.class,params);
            if(!flag) return Result.error("导入失败，请检查");
            ExcelImportUtil.importExcel(file.getInputStream(),TestUser.class,params);//这一行执行报 没有该方法 isNullObject
            return Result.OK("导入成功");

--------错误日志
2021-08-05 13:23:04.149 [http-nio-8080-exec-3] INFO  o.j.poi.excel.imports.ExcelImportServer:423 -   >>>  poi3升级到4.0兼容改造工作, isXSSFWorkbook = false
没有该方法 isNullObject
没有该方法 isNullObject
没有该方法 isNullObject
没有该方法 isNullObject
没有该方法 isNullObject
没有该方法 isNullObject
没有该方法 isNullObject

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by zhangdaiscott** [comment]
目前影响功能吗？
