### ISSUE TITLE
nacos更改配置，需要重启服务才能生效

### ISSUE THREAD

**Issue by luoqiuqiu** [jeecgboot/jeecg-boot#2869]
##### 问题描述：
nacos更改配置，需要重启服务才能生效，有什么办法可以更改之后，就生效，不用重启服务呢？

##### 截图&代码：

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
更改的什么内容

**Comment by luoqiuqiu** [comment]
> 更改的什么内容

有一次是改了数据库、redis
这次是改了xxljob的改为false关闭

**Comment by zhangdaiscott** [comment]
你改的这些参数都是程序在启动的时候去加载的，肯定需要重启服务。
通过	@Value("${cas.prefixUrl}")方式引用的属性，只有变，就说明nacos的动态属性机制没问题

**Comment by luoqiuqiu** [comment]
> 你改的这些参数都是程序在启动的时候去加载的，肯定需要重启服务。
> 通过	@value("${cas.prefixUrl}")方式引用的属性，只有变，就说明nacos的动态属性机制没问题

啊，这样子啊。那好吧。
