### ISSUE TITLE
关于JPopup框多选带出效果实现

### ISSUE THREAD

**Issue by iGuozy** [jeecgboot/jeecg-boot#2876]
##### 版本号：
2.4.5

##### 问题描述：
目前JPopup框在table多选带出是合并成一行。（如图1）
希望实现效果是分开行带出。（如图2）有没有计划什么时候可以实现这种功能？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48822119/128671940-94734558-6637-411c-95f3-53ab538fd18f.png)
![image](https://user-images.githubusercontent.com/48822119/128672209-4fb158a6-f2f3-4a9b-87fc-a379ce571aa3.png)

友情提示： 未按格式要求发帖，会直接删掉;
          Online问题请明确指出主题模板、报错问题请提供重现步骤或者视频;

**Comment by zhangdaiscott** [comment]
没有计划

**Comment by iGuozy** [comment]
已自己改造了。

**Comment by LiCain** [comment]
> 已自己改造了。

请问下兄弟，你是怎么样改的呀，我也需要
