### ISSUE TITLE
Java内存溢出+积木报表加上查询条件后查询慢

### ISSUE THREAD

**Issue by mszuishuai** [jeecgboot/jeecg-boot#2877]
##### 问题描述：**尊敬的开源者您好，非常感谢您能开放此项目的代码，在使用该项目的积木报表时遇到了以下问题：**
**1、**报错内存溢出的问题（见图1），刚开始以为是设置的内存不够，然后便在springboot启动的脚本中设置了更大的内存（见图2），重新启动使用项目后，刚开始并没有出现问题，过了一段时间又出现了内存溢出的报错。这个时候我就觉得应该不是内存不够用的原因了，然后我便开始监视java程序在服务器上的运行情况（见图3），刚启动项目的时候的时候Java程序占用内存的情况（见图4），使用了一段时间后的内存情况（见图5），关闭系统使用后隔一段时间的内存情况（见图6）。根据以上观察，我觉得应该不是内存不足的原因，可能是回收机制存在一定问题，关闭系统使用或者关闭部分查询后内存没有得到释放，导致java程序内存越来越高，直到报错内存溢出。
**2、**积木报表加上查询条件后查询速度慢的问题（偶尔会抛出关闭连接的异常，“你的主机中的软件中止了一个已建立的连接”），首先我们的报表都是连接其他项目的数据源，有可能一个报表存在多个数据源，刚开始以为是数据量过大而导致查询速度慢（百万条数据，勾选上了分页），经过不断的尝试后，发现去掉查询条件后的查询速度几乎是秒查询。加上一个查询条件就需要1分钟左右的时间，查询条件加的越多查询时间越长，甚至有可能查不出来。
**以上两个问题是使用了该项目一段时间后发现的问题，麻烦开源者直接指明问题出在哪里，期待您的回复，谢谢**

##### 截图&代码：
![图1](https://user-images.githubusercontent.com/48348684/128795388-49ae825f-b214-4dc4-b18e-f3089da83442.png)
![图2](https://user-images.githubusercontent.com/48348684/128795703-a432dc66-53ba-4461-bdd8-1a554fe1041d.png)
![图3](https://user-images.githubusercontent.com/48348684/128795769-e6c6c8b4-5ff2-43be-ae24-88845342bd56.png)
![图4](https://user-images.githubusercontent.com/48348684/128795892-5ccffd16-5d92-4304-aa89-cea21856c795.png)
![图5](https://user-images.githubusercontent.com/48348684/128796004-83f1c3fc-fbc6-4e09-a4ed-4c0705e642c6.png)
![图6](https://user-images.githubusercontent.com/48348684/128796141-2efcf095-2c76-4589-815c-8ad8f4bf78fa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
查询条件已经优化，下个版本发布
