### ISSUE TITLE
online java 增强当设置的增强过多时，显示异常

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#2880]
##### 版本号：

2.4.5
##### 问题描述：
java 增强当设置的按钮增强项目超过10条后，显示超范围，建议增加下拉框或者翻页

##### 截图&代码：

![image](https://user-images.githubusercontent.com/66394184/128951963-f5f122dd-cba0-426a-8681-34b45b666ff3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by zhangdaiscott** [comment]
已处理，升级  `  "@jeecg/antd-online-mini": "2.4.6-beta3"`


![输入图片说明](https://images.gitee.com/uploads/images/2021/0818/141704_504b62ae_57093.png "屏幕截图.png")
