### ISSUE TITLE
数据脱敏处理

### ISSUE THREAD

**Issue by mark0614** [jeecgboot/jeecg-boot#2882]
##### 版本号：

2.4.5
##### 问题描述：
是否有计划实现关键数据如：证件号码、手机号等字段的脱敏功能？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没有
