### ISSUE TITLE
JTreeSelect在树结构没有子节点的情况下依然显示展开箭头

### ISSUE THREAD

**Issue by Naganohara-Mio** [jeecgboot/jeecg-boot#2885]
##### 截图&代码：

修改建议：

文档里加上hasChildField参数，或者将默认值修改成has_child(即在线文档默认生成的判断是否存在孩子节点列)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Naganohara-Mio** [comment]
唉，只是文档没写参数，看xml文件才搞明白

**Comment by sjlei** [comment]
文档已更新，增加了`hasChildField`的描述。
这个参数不能加默认值，因为是直接读的数据库，如果加上默认值而表里没有这个字段就会报错。
