### ISSUE TITLE
在线开发数据表的视图配置java增强类无效

### ISSUE THREAD

**Issue by showDgpl123** [jeecgboot/jeecg-boot#2886]
##### 版本号：
2.2.0

##### 问题描述：
在数据表的视图中，配置视图的java增强类，无效。请问视图的java增强应该怎么配置

##### 截图&代码：
图1
![1628666195(1)](https://user-images.githubusercontent.com/86600259/128986695-1e45306c-d912-429f-804f-a546f4b8945e.jpg)
图2
![1628666135(1)](https://user-images.githubusercontent.com/86600259/128986709-c9353253-01da-4324-b305-381ae65c3520.jpg)

**Comment by zhangdaiscott** [comment]
无效是什么意思？

**Comment by showDgpl123** [comment]
无效就是，切面类的代码根本不会执行&nbsp;








肖亚琼



17347046667

深圳市宝安区福永街道兴围社区深圳国际机场机场四道物流大厦




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***"; 
Date: 2021年8月11日(星期三) 下午3:55
To: "jeecgboot/jeecg-boot"; 
Cc: "showDgpl123"; "Author"; 
Subject: Re: [jeecgboot/jeecg-boot] 在线开发数据表的视图配置java增强类无效 (#2886)

&nbsp;


 
无效是什么意思？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by showDgpl123** [comment]
> 无效是什么意思？
就是切面类里的代码根本就不会执行

**Comment by showDgpl123** [comment]
能复现出来吗？

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
配置 事件状态为 开始
