### ISSUE TITLE
路由带参跳转页面，会打开两个页面

### ISSUE THREAD

**Issue by King10031** [jeecgboot/jeecg-boot#2888]
##### 问题描述：
功能需求： 列表中点击详情按钮 跳转到我自己复制的的一个表单详情页中 ，需要带上一列的id作为详情页展示的查询条件。
遇到的问题：通过 `<router-link :to="{ name: 'cause-modules-CasuseDetail',query: {id:record.id}}">详情</router-link>` 路由跳转后会出现两个table详情页，一个url上是带参数的(id)，一个url上是不带参数的。具体截图如下。

##### 截图&代码：

![6e6b464532da4ae819b1dda3fb0f8a7](https://user-images.githubusercontent.com/49204361/129125803-5f75123c-8274-4c36-9b19-0d3bf5699a36.png)
![64eb6054bdbdd779f7bc8df47526c82](https://user-images.githubusercontent.com/49204361/129125808-d8fe24b2-7459-4781-921a-3eba48c6a518.png)
![76dc6e2b46f9c50e17b1a077df82046](https://user-images.githubusercontent.com/49204361/129125811-78c8f21e-ca18-4dd8-983a-b97b2f41e064.png)
![8206142454db6abd7c8c50e1128a972](https://user-images.githubusercontent.com/49204361/129125813-72d42702-c11d-432a-bfc5-103d29674ae0.png)
![af0b0c141d479414b261e6a079c551a](https://user-images.githubusercontent.com/49204361/129125814-d2d62ca3-deb8-40fc-aa8f-be4e0f18e9d9.png)
![2d99c8f269e80ed42fb5b6695e483f1](https://user-images.githubusercontent.com/49204361/129125815-5df82f75-b0d3-426f-9a6e-9ba3c57dae2d.png)

**Comment by yogwang** [comment]
也许是因为 `<router-view>` 没有 `key` 的关系，可以把 `$route.path` 当成 `key` 试试看，我记得是可以的，刷新也不会丢失参数，只不过你其它相同`path`的页面也会被合并。
或者说使用 `$router.push({ name:"page-detail", params: { id: id } })` 的形式来跳转，只是这样跳转的话刷新页面会丢失params参数，你自己考量。

记得编辑的路由不要最后加上 `:id` [ __page/detail ~~/:id~~__ ]，不然使用 `name` 跳转会遇到我的那个问题，`fullpath` 也会改变。
我现在是详情页用的query（刷新保持id），编辑页就是用params（刷新丢失id）

**Comment by King10031** [comment]
> 也许是因为 `<router-view>` 没有 `key` 的关系，可以把 `$route.path` 当成 `key` 试试看，我记得是可以的，刷新也不会丢失参数，只不过你其它相同`path`的页面也会被合并。
> 或者说使用 `$router.push({ name:"page-detail", params: { id: id } })` 的形式来跳转，只是这样跳转的话刷新页面会丢失params参数，你自己考量。
> 
> 记得编辑的路由不要最后加上 `:id` [ **page/detail ~/:id~** ]，不然使用 `name` 跳转会遇到我的那个问题，`fullpath` 也会改变。
> 我现在是详情页用的query（刷新保持id），编辑页就是用params（刷新丢失id）

谢谢老哥 还是不行  等等官方吧

**Comment by yogwang** [comment]
> 谢谢老哥 还是不行 等等官方吧

这种应该是不会修的，属于自己项目上的设计问题。

**Comment by King10031** [comment]
> > 谢谢老哥 还是不行 等等官方吧
> 
> 这种应该是不会修的，属于自己项目上的设计问题。

我菜单的配置问题吗 ？还是 ？ 没大明白

**Comment by yogwang** [comment]
> 我菜单的配置问题吗 ？还是 ？ 没大明白

属于是 `<BasicLayout>` 上的问题，开发者可以按照自己的需求去修改，所以不算是BUG，只是我一直想要官方可以出一个全局管理 `Tabs` 的API，起码可以让我们手动跨页面关闭，就比如说你编辑一个文章，点击确定，Tabs还会存在的。

**Comment by King10031** [comment]
目前还是没解决 等待官方提供一个解决方案

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/1289

**Comment by King10031** [comment]
> #1289

意思是 我需要自己去改造一下路由加载的逻辑

**Comment by King10031** [comment]
？？

**Comment by yogwang** [comment]
> #1289

那么提供一下跨页面的tabs关闭api可不可以考虑一下 😁
之前自己想做来着，但是后来业务不需要了，就没继续下去了，
考虑是放到vuex来管理，然后操作数据去打开关闭和handle当前页面tab关闭跳转

**Comment by TankCoder** [comment]
@yogwang  打扰你一下，麻烦问下是否有配置过3级隐藏子页面？  我遇到了配置三级子页面无法访问的情况， 这是我的问题，官方也没有正面回复 https://github.com/jeecgboot/jeecg-boot/issues/4018
