### ISSUE TITLE
关于数据库选择的问题

### ISSUE THREAD

**Issue by 1737255535** [jeecgboot/jeecg-boot#2889]
##### 版本号：
2.4.5

##### 问题描述：
贵公司可否在程序运行初始化的时候进行数据库的初始化，即在第一次使用的时候进行数据库、管理员账户、上传文件存储位置等选项的配置，这样可以自由的控制数据库、上传文件存储位置等内容，更有利于定制

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是个开发工具级别的产品，没太大必要，如果是做成业务化的产品，可以这么改
