### ISSUE TITLE
online在线功能，java增强导入设置成开始的时候可以生效，但是设置成结束的时候不能生效

### ISSUE THREAD

**Issue by yangyongjx** [jeecgboot/jeecg-boot#2891]
##### 版本号：
v2.4.5

##### 问题描述：

online在线功能，java增强导入设置成开始的时候可以生效，但是设置成结束的时候不能生效
##### 截图&代码：
![image](https://user-images.githubusercontent.com/3679298/129132533-6cd9fe3e-2223-436b-b78f-efaa5ae4f385.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yangyongjx** [comment]
新增和编辑 设置结束时可以生效的

**Comment by zhangdaiscott** [comment]
应该导入结束没做增强逻辑

**Comment by zhangdaiscott** [comment]
收录 ty
