### ISSUE TITLE
IE11一直显示loading，无法进入登录页或首页

### ISSUE THREAD

**Issue by MJ11111** [jeecgboot/jeecg-boot#2892]
##### 问题描述：IE11进入系统，无法正常显示，一直转圈，显示加载中，页面无法跳转。

看官网说 支持IE11+，且询问客服也回复支持ie11，可在官网在线演示中看，但拉下最新的源码看依然是一直在转圈，jeecg在线演示虽然可以跳转到登录页，但是输入账号密码后页面也无法跳转，仍有此问题。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/11596938/129144294-581fadae-2395-4b35-ac77-d95929d55c2c.png)
![image](https://user-images.githubusercontent.com/11596938/129144538-ae789b9a-2a88-405d-9d9e-4e4903b29aaf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/2812

**Comment by MJ11111** [comment]
#2812  的试过了不能解决才提问的，而且使用#2812的方法配置后本地开发环境无法正常访问，只有build之后部署到生产线才能正常访问页面

**Comment by zhangdaiscott** [comment]
忽略吧，IE11即使兼容也很慢

**Comment by sharpJH** [comment]
这个问题解决了吗？有没有什么办法呢？
