### ISSUE TITLE
linux服务器上以JAR方式发布如何使用代码生成器

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2894]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/50698315/129175492-1aec4f66-377e-4301-b1ba-eec4de066dd9.png)
![image](https://user-images.githubusercontent.com/50698315/129175977-a902a5d3-2ce6-497e-a538-8638ad7fd401.png)
                                                                                                 （图二）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看文档

**Comment by yangkui001** [comment]
就是没看明白啊，我的问题是按照这个文档操作以后下一步如何操作？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] linux服务器上以JAR方式发布如何使用代码生成器 (#2894)





 
看文档
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by priceou** [comment]
> 就是没看明白啊，我的问题是按照这个文档操作以后下一步如何操作？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jeecgboot/jeecg-boot" ***@***.***&gt;; 发送时间:&nbsp;2021年8月13日(星期五) 上午10:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [jeecgboot/jeecg-boot] linux服务器上以JAR方式发布如何使用代码生成器 (#2894) 看文档 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这个意思应该是假设你的jar在/root/jeecg-boot-module.jar,  那你就建一个/root/config , 然后把 jeecg目录放到config目录下
