### ISSUE TITLE
IE游览器无法打开页面，一直在加载转圈圈

### ISSUE THREAD

**Issue by bean542469669** [jeecgboot/jeecg-boot#2895]
##### 版本号：
v2.4.5

##### 问题描述：
IE游览器无法打开页面，一直在加载转圈圈,无法正常访问浏览。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44425693/129287752-81b01f03-1aba-4c6b-a53e-d165de7bded3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/2812

**Comment by LYHHS** [comment]
我也遇到同样的问题，请问您解决了没有
