### ISSUE TITLE
第三方APP消息测试问题 “字段太长,超出数据库字段的长度” 解决方案

### ISSUE THREAD

**Issue by wanggh1021** [jeecgboot/jeecg-boot#2898]
##### 截图&代码：

暂无

##### 建议解决方式：

在 jeecg-boot-module-system/target/classes/org/jeecg/modules/system/mapper/xml/SysThirdAccountMapper.xml 文件中
WHERE 条件 中 third_type 字段未指定表名，改为如下：

SELECT third_user_id FROM sys_third_account
        INNER JOIN sys_user ON sys_user.id = sys_third_account.sys_user_id
        WHERE sys_third_account.third_type = #{thirdType} AND

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经改了，马上发布
