### ISSUE TITLE
建议：online表单，页面属性->控件类型，增加日期格式以毫秒显示

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#2900]
##### 版本号：
2.4.5

##### 问题描述：
online表单，页面属性->控件类型，增加日期格式以毫秒显示，满足用户的各种需求，“format = "yyyy-MM-dd HH:mm:ss zzz"”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66394184/129303503-c4407d43-30ea-44e1-bc78-3173df4d8544.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂不实现
