### ISSUE TITLE
JVXETable 如何实现列的拉伸，以及指定列合计。编辑状态下回车键自动切换到下一输入焦点。

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecg-boot#2902]
##### 问题描述：

JVXETable 如何实现列的拉伸，以及指定列合计功能，包括Online及生成代码。像列表以及表单ERP样式里的一对多，如何实现指定列的合计及拉伸。

还有弹出表单中如何实现按回车键可以自动将输入焦点切换到下一个输入控件上，相当于回车替代Tab键

**Comment by sjlei** [comment]
1、列的拉伸不支持
2、指定列合计可以看文档
<http://doc.jeecg.com/2043992>
![image](https://user-images.githubusercontent.com/34293221/133062391-793f825f-ee36-4cc5-9b48-8478e78a9a84.png)
3、键盘操作不支持
