### ISSUE TITLE
JImageUpload无法删除本地图片

### ISSUE THREAD

**Issue by HWGALLEN** [jeecgboot/jeecg-boot#2905]
##### 版本号：
2.4.5

##### 问题描述：
在生成代码的功能中，通过JImageUpload组件上传照片，点击删除将照片删除后，数据库的照片字段的内容会清空，但上传的照片不会同步删除。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23203833/129375173-7e145ac6-b86d-45c5-a498-0cbfaca73e1e.png)
![image](https://user-images.githubusercontent.com/23203833/129375335-2c2eb810-9a9d-4534-b00a-b2d251a63142.png)
![image](https://user-images.githubusercontent.com/23203833/129375519-29b47de2-75be-419f-9896-a164f1b675e7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by sjlei** [comment]
目前只做了清空数据库字段，真实文件不会删除，可以自己实现一下。
