### ISSUE TITLE
低级bug

### ISSUE THREAD

**Issue by 1156230954** [jeecgboot/jeecg-boot#2906]
##### 版本号：
2.4.5

##### 问题描述：
低级bug，在 org.jeecg.common.util.YouBianCodeUtil#getNextYouBianCode 出现了 code == ""，导致误判

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57119246/129389979-160567d8-fd37-472a-8c6b-6a57ce7eb8ed.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经修复
