### ISSUE TITLE
升级到2.4.6后@jeecg/antd-online-mini": "2.4.6-beta组件影响了ant design vue的button type='danger'时的样式

### ISSUE THREAD

**Issue by rockjava** [jeecgboot/jeecg-boot#2909]
##### 版本号：
2.4.6

##### 问题描述：
前端
@jeecg/antd-online-mini": "2.4.6-beta组件影响了ant design vue的button type='danger'时的样式
##### 截图&代码：
原有样式
![image](https://user-images.githubusercontent.com/2434533/129464632-b1a2cbb5-5b00-4418-b37e-9604c36eea2d.png)
升级后的样式
![image](https://user-images.githubusercontent.com/2434533/129464642-d37f5649-2eb6-4185-8f4d-ac5e84f862b0.png)

目前解决办法，把jeecg/antd-online-mini回退到2.4.5-RC版本。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到 Version
2.4.6-beta1
