### ISSUE TITLE
更新项目

### ISSUE THREAD

**Issue by dc1396765008** [jeecgboot/jeecg-boot#2911]
##### 版本号：
2.4.6

##### 问题描述：
如何升级成2.4.6版本，之前的配置会不会被覆盖没拉

##### 截图&代码：
无需图片

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/blob/master/jeecg-boot/db/%E5%A2%9E%E9%87%8FSQL/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.txt
