### ISSUE TITLE
js增强点击无效

### ISSUE THREAD

**Issue by i-Hu** [jeecgboot/jeecg-boot#2912]
##### 版本号：
2.4.6

##### 问题描述：
js增强点击无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/129527614-4bd86418-7a24-4fce-9491-754f0f915e9a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
解决了，请更新代码
