### ISSUE TITLE
数据库脚本中，sys_dict_item表“数据库类型”的item_value值重复问题

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/jeecg-boot#2914]
##### 版本号：
2.4.6

##### 问题描述：
增量SQL文件《2.4.5升级到2.4.6增量MYSQL.sql》和《jeecgboot-mysql-5.7.sql》中
sys_dict_item表中的名称为“数据库类型”的数据字典，MYSQL5.7和 Postgresql 的item_value值重复问题。
同一个字典下，item_value重复，这个应该是有问题的吧？
发现oracle和 sqlserver 的脚本也有同样情况。

##### 截图&代码：
《2.4.5升级到2.4.6增量MYSQL.sql》中
第12行，将MYSQL5.7的item_value更新为6
在第14行给sys_dict_item表插入的新数据 Postgresql 的 item_value 也是 6
<img width="1134" alt="增量脚本问题" src="https://user-images.githubusercontent.com/17849555/129533748-9ae91cc4-a27a-42a0-a48e-7833bb15ac15.png">

《jeecgboot-mysql-5.7.sql》中，
3673 行给sys_dict_item表插入的新数据 MYSQL5.7 的 item_value 是 6
3676 行给sys_dict_item表插入的新数据 Postgresql 的 item_value 也是 6
<img width="966" alt="全量脚本问题" src="https://user-images.githubusercontent.com/17849555/129533796-0f67bec7-6675-4655-875a-15cd8b7f2244.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ddwolf715** [comment]
2.4.0升级2.4.2时

**Comment by ddwolf715** [comment]
2.4.0升级2.4.2时
MYSQL5.7 的 item_value 是 4，这次升级2.4.6，发现脚本中MYSQL5.7 和 Postgresql 的 item_value值重复了，都为 6 。

**Comment by zhangdaiscott** [comment]
这个类型没什么用处了，类型判断已经通过url来匹配，可以忽略
