### ISSUE TITLE
sqlserver同步数据库报错，SQL to parse以后与sqlserver不兼容

### ISSUE THREAD

**Issue by i-Hu** [jeecgboot/jeecg-boot#2915]
##### 版本号：
jeecg-boot 2.4.6
sqlserver2019

##### 问题描述：
sqlserver同步数据库报错，SQL to parse以后与sqlserver不兼容

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/129655975-d9965aae-04b0-454f-b21c-231a75ca55f0.png)

![image](https://user-images.githubusercontent.com/26364818/129655873-a6ece989-d039-45a1-b6c8-569353b0bfe3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sqlserver2019没测过，建议用 sqlserver2017

**Comment by i-Hu** [comment]
跟sqlserver版本关系不大吧
sqlserver添加列语法应该是 alter table 表名 add 列名 varchar(32)
这里parse后多了COLUMN
![image](https://user-images.githubusercontent.com/26364818/129659526-e22b5a75-1bab-4c6c-83c8-ee011d3b24f3.png)

**Comment by zhangdaiscott** [comment]
更新代码
