### ISSUE TITLE
限制删除，只限制了每行的删除按钮，批量删除还是可以删除呀？

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#2916]
##### 版本号：
2.4.6

##### 问题描述：

限制删除，只限制了每行的删除按钮，批量删除还是可以删除
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
?

**Comment by tb2888** [comment]
> ?

http://doc.jeecg.com/2061290
这里限制数据不能删除对批量删除不起作用，只有每行后面的删除按钮有效
![image](https://user-images.githubusercontent.com/55084864/129676964-f57e3a94-1650-412a-8a21-9778e8119aee.png)

**Comment by zhangdaiscott** [comment]
不想要批量删除，你可以通过授权给屏蔽掉
