### ISSUE TITLE
大佬见截图，列表点击详情，出现id，好难看

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2922]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/129860728-2744e1d0-fd5d-435c-a3e7-9ee591faa7fa.png)
![image](https://user-images.githubusercontent.com/86937081/129860846-bee4c62c-e8de-403c-ace3-bcaef8b13dcd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是你配置的问题吧

**Comment by jeffZbj** [comment]
点编辑，正常的



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月18日(周三) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 大佬见截图，列表点击详情，出现id，好难看 (#2922)




 
是你配置的问题吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
发现问题了，稍等

**Comment by jeffZbj** [comment]
好的，大佬，谢谢



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月18日(周三) 下午4:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 大佬见截图，列表点击详情，出现id，好难看 (#2922)




 
发现问题了，稍等
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
解决了，升级版本    
`"@jeecg/antd-online-mini": "2.4.6-beta4",`

**Comment by jeffZbj** [comment]
谢谢大佬



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月18日(周三) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 大佬见截图，列表点击详情，出现id，好难看 (#2922)




 
解决了，升级版本
 ***@***.***/antd-online-mini": "2.4.6-beta4",
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jeffZbj** [comment]
大佬，这个怎么升级，我只做过搭建和增量。



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月18日(周三) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 大佬见截图，列表点击详情，出现id，好难看 (#2922)




 
解决了，升级版本
 ***@***.***/antd-online-mini": "2.4.6-beta4",
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
