### ISSUE TITLE
升级完 "@jeecg/antd-online-mini": "2.4.6-beta4",保存个别表时，保存不上，一直转啊转的

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2924]
##### 问题描述：
升级完 "@jeecg/antd-online-mini": "2.4.6-beta4",保存个别表时，保存不上，一直转啊转的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/129993808-f9f9178d-6f33-42e2-91c4-4ba3e51ca6d2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级到 2.4.6-beta5

**Comment by jeffZbj** [comment]
谢谢，大佬！解决了！



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月19日(周四) 上午9:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 升级完 ***@***.***/antd-online-mini": "2.4.6-beta4",保存个别表时，保存不上，一直转啊转的 (#2924)




 
升级到 2.4.6-beta5
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
