### ISSUE TITLE
Shiro能否换成spring security?现在主流的都是用这个框架

### ISSUE THREAD

**Issue by zengziqiang** [jeecgboot/jeecg-boot#2925]
##### 版本号：
master

##### 问题描述：
Shiro能否换成spring security?现在主流的都是用这个框架

##### 截图&代码：
`...`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ljp190** [comment]
既然要换，为什么不换成sa token
更加的简便好用
security还是算了吧，如果security好用就不会有shiro的出现了

**Comment by freewind1977** [comment]
建议官方关注一下spring authorization server的时进展，计划中有支持OICD，已经发了0.2.0版本

**Comment by zhangdaiscott** [comment]
好的

**Comment by zhangyingrepo** [comment]
spring security早日提上日程呀，冲鸭

**Comment by zhangdaiscott** [comment]
已经提供分支
https://github.com/jeecgboot/jeecg-boot/tree/springboot3_sas
