### ISSUE TITLE
我的部门下面进行用户信息查询不支持模糊查询

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/jeecg-boot#2929]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26646785/130018809-9b76faff-bd61-4687-9c06-f9113c98f7ca.png)

上图中查询条件不支持模糊查询。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种需求自己改就行了
