### ISSUE TITLE
第三方用户账号问题

### ISSUE THREAD

**Issue by freewind1977** [jeecgboot/jeecg-boot#2930]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26646785/130022684-c6ff3ef2-31f1-4789-83f4-787c32d32606.png)

在sys_third_account表中一个用户对应两个第三方登录账号，登录时代码报错

![image](https://user-images.githubusercontent.com/26646785/130022840-b223f561-50ce-4b35-9565-2f60ec473e84.png)

![image](https://user-images.githubusercontent.com/26646785/130023350-44369b10-3e33-40a2-bdb0-5884baddd29f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录  jl

**Comment by zhangdaiscott** [comment]
你的版本有点老了，要不你参考下最新版

**Comment by freewind1977** [comment]
没太理解版本有点老的意思，我看了最新的2.4.6的代码跟我现在2.4.5的这个方法的代码是一样的

**Comment by zhangdaiscott** [comment]
改造过了

**Comment by sjlei** [comment]
可能是你的数据有问题，一个用户可以有多个第三方登录方式，用`third_type`区分，看看你的数据是不是存在一个用户有一样的`third_type`
![image](https://user-images.githubusercontent.com/34293221/130767272-583b654f-afa8-4fca-ba04-ddc55dbb8fff.png)

**Comment by freewind1977** [comment]
谢谢回复，我核对一下数据
