### ISSUE TITLE
大佬！请看下，生成代码路径和截图填入的路径不一样，多了一个demo文件夹

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2932]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/130039581-140bd3d2-ac47-4b21-9586-1428a79f08bd.png)
![image](https://user-images.githubusercontent.com/86937081/130039416-6db64457-0d6e-43ed-bb21-46fff52509a7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是你定义的业务包名
