### ISSUE TITLE
jpopup组件在列表页调用时导致页面变形

### ISSUE THREAD

**Issue by ofllm** [jeecgboot/jeecg-boot#2935]
在留言区更新描述。

##### 问题描述：
当页面和菜单数据较少（右侧无滚动条）时，在列表页使用jpopup组件弹出窗口，页面右侧滚动条占据的位置会消失，关闭弹窗后，页面自动恢复。

##### 截图&代码：

使用弹出窗口前：

![image](https://user-images.githubusercontent.com/3360852/130161389-4552b90f-64b1-41e1-9f3e-67ac52984f2c.png)

打开弹出窗口：

![image](https://user-images.githubusercontent.com/3360852/130161481-ea63a05a-3e01-497d-8297-1c874e87e936.png)

关闭弹出窗口：

![image](https://user-images.githubusercontent.com/3360852/130161555-a6b99656-0729-4b3e-a8f6-834ae2795e1b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截图不清晰，没看明白

**Comment by ofllm** [comment]
未调用popup组件前，页面最右侧有滚动条预留的灰色边占位，打开popup组件后，页面右侧灰色占位边消失，关闭组件后恢复正常。展现出来的效果是打开关闭组件后，页面会有闪烁。当页面和菜单数据较少（右侧无滚动条）时出现。
调用前：
![image](https://user-images.githubusercontent.com/3360852/130179219-8b39817f-b662-4199-95ba-56f6956e4a97.png)

打开popup:
![image](https://user-images.githubusercontent.com/3360852/130179323-5cf15ab1-18f8-4de2-92b5-0bb141f73cdc.png)

关闭popup:
![image](https://user-images.githubusercontent.com/3360852/130179363-5e990e4f-c8dc-4b14-96ca-36b1d5358fc0.png)

**Comment by zhangdaiscott** [comment]
没必要改，需要的话，自己改把
