### ISSUE TITLE
2.4.6 online生成表主键为varchar36

### ISSUE THREAD

**Issue by park96323** [jeecgboot/jeecg-boot#2936]
##### 问题描述：
2.4.6更新版本日志中显示
主键策略修改 IdType.ID_WORKER_STR --> IdType.ASSIGN_ID

但是使用online生成表主键为 varchar36

##### 截图&代码：
![Snipaste_2021-08-20_11-51-39](https://user-images.githubusercontent.com/16518337/130176464-98c3404c-fdcf-4840-b316-3bdae281ad0e.png)

**Comment by zhangdaiscott** [comment]
字符串类型的IdType.ASSIGN_ID
