### ISSUE TITLE
online 生产字段关键字校验 short

### ISSUE THREAD

**Issue by dangzhenghui1985** [jeecgboot/jeecg-boot#2938]
##### 问题描述：
short 是java关键字 不能做为字段名称所有要校验下 online可以用生成代码后显示关键字报错了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这属于你配置的问题，这种问题可改可不改
