### ISSUE TITLE
addBeFore

### ISSUE THREAD

**Issue by Benjamin-536** [jeecgboot/jeecg-boot#2939]
##### 版本号：

2.4.6
##### 问题描述：
JEditable 下子表 addBefore()方法，在其中自定义调用其他方法不生效如何解决。
JVexTable 没有这个问题。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/66345194/130208749-e13f364f-2487-47f2-99f3-817120842355.png)

![image](https://user-images.githubusercontent.com/66345194/130208790-021dddd2-f7b3-41e9-8100-c642f5d6b271.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
问题已修复，下版本发布
