### ISSUE TITLE
打印的时候能否支持固定表头

### ISSUE THREAD

**Issue by songyinhai2006** [jeecgboot/jeecg-boot#2940]
##### 版本号：
版本号：2.4.6

##### 问题描述：
打印的时候能否支持固定表头

##### 截图&代码：

![打印](https://user-images.githubusercontent.com/52561802/130209624-300a1df2-c461-4a93-8cdb-81edc0eec491.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
