### ISSUE TITLE
jPopup怎样可以实现table里的popup框二次传参？

### ISSUE THREAD

**Issue by iGuozy** [jeecgboot/jeecg-boot#2943]
##### 版本号：
2.4.5

##### 问题描述：
JVXE-table编辑页面的form表单，在打开时，popup框的参数会自动传一次，但如果我更改了form上面的字段值后，怎样才可以触发把新值再传到table里的popup框参数？？文档里没找到有相关说明，请指教一下。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48822119/130317833-f5b204ef-71b7-47d4-99ac-cd47ce9948f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
供应商ID触发 change 事件的时候，动态改变`JVXETable`的`popup`列的`param`值即可
![image](https://user-images.githubusercontent.com/34293221/131306987-6708ce66-4c6c-4e77-b098-2bf1a334642b.png)

![image](https://user-images.githubusercontent.com/34293221/131308128-79e71c93-e84d-4df2-8052-06b48a9c51c9.png)

![image](https://user-images.githubusercontent.com/34293221/131308071-1bafc070-7a69-4f20-bf8e-ec18d939c83b.png)
