### ISSUE TITLE
js增强实现自定义弹框功能报错

### ISSUE THREAD

**Issue by FreedomStark** [jeecgboot/jeecg-boot#2944]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/130408030-d7247256-ed74-42a7-9120-30b4f4d4312f.png)
![image](https://user-images.githubusercontent.com/63634402/130408066-411952c3-def3-4f52-b403-6bb430508798.png)
![image](https://user-images.githubusercontent.com/63634402/130408295-45524b30-64a3-4f6d-92d7-0c1c9a40c64f.png)
![1](https://user-images.githubusercontent.com/63634402/130408523-afd45f44-ccb3-43be-a531-d4c13b22f443.gif)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以试下最新版，2.4.5好像是支持，应该是你用法问题

**Comment by FreedomStark** [comment]
换了新版本可以了
