### ISSUE TITLE
使用非jeecg-boot数据库的表，点击online 表单下对应记录的功能测试按钮引起的错误

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2945]
##### 问题描述：online代码生成器
     online单表tcjt_zc_electron_sign生成代码之后，当tcjt_zc_electron_sign不在jeecg-boot中存在的情况下点击更多/功能测试报错如下所示，如何使用其它数据库的表能正常使用online的功能测试进行测试？

数据库查询失败， ### Error querying database.
 Cause: java.sql.SQLSyntaxErrorException: Table 'jeecg-boot.tcjt_zc_electron_sign' doesn't exist
 ### The error may exist in URL [jar:file:/jeecg-cloud-system/jeecg-cloud-system-start-2.4.6.jar!/BOOT-INF/lib/hibernate-re-2.4.6-beta1.jar!/org/jeecg/modules/online/cgform/mapper/xml/OnlCgformFieldMapper.xml] ### The error may involve org.jeecg.modules.online.cgform.mapper.OnlCgformFieldMapper.selectPageBySql-Inline ### The error occurred while setting parameters ### SQL: SELECT COUNT(*) FROM tcjt_zc_electron_sign WHERE 1 = 1 ### Cause: java.sql.SQLSyntaxErrorException: Table 'jeecg-boot.tcjt_zc_electron_sign' doesn't exist ; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Table 'jeecg-boot.tcjt_zc_electron_sign' doesn't exist

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/130413507-e6e759b1-7200-439d-8b4f-bdcc1dab7f03.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个表必须存在
