### ISSUE TITLE
大佬！附表配置popup弹出框可以多选支持多选么？多选生成多条附表记录的那种！

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#2946]
##### 版本号：
2.4.6

##### 问题描述：
主附表关系录入界面，附表配置一个弹出框，当在弹出框中选择多行时，对应附表也生成多条记录，这样可不可以实现呀？大佬！以前老版本（非boot版本）可以这样的！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请图文并茂

**Comment by tb2888** [comment]
> 请图文并茂
就像下面一样，我在送货明细中（产品名称popup弹出框）选择产品信息，如果在弹出框中选了多条，确定之后就会把弹出框中选择的多条带入送货明细中！
![image](https://user-images.githubusercontent.com/55084864/130537082-ef10c7cd-348d-4101-9487-c9c233344e16.png)
![image](https://user-images.githubusercontent.com/55084864/130537065-6fc0069a-4242-4da3-963e-d25e06644a97.png)

**Comment by zhangdaiscott** [comment]
可以自己实现，目前默认没有
