### ISSUE TITLE
2.4.6版本自定义弹窗，加载不到自定义的页面

### ISSUE THREAD

**Issue by fcpglss** [jeecgboot/jeecg-boot#2947]
##### 问题描述：

online表单自定义弹框加载不到自定义的页面

##### 截图&代码：
自定义按钮
![image](https://user-images.githubusercontent.com/19617885/130542010-cd4ebe15-6ec2-43ee-acf9-6488eb44ad1e.png)
对应代码
![image](https://user-images.githubusercontent.com/19617885/130542058-0534acb5-6797-4821-bcec-e991d8904069.png)
文件路径
![image](https://user-images.githubusercontent.com/19617885/130542102-137726d1-e53b-48ab-9037-6c91831d497b.png)
点击弹窗后效果，窗口打开了，但是内容没有，如果不用formComponent，是可以出现表单的
![image](https://user-images.githubusercontent.com/19617885/130542311-6dd74054-dc97-4ca0-a785-1469d6a4ef72.png)
我试着配置到菜单里面是可以访问的
![image](https://user-images.githubusercontent.com/19617885/130542715-361ec890-2d99-45fd-8d21-6ae55a70342e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开源版本此功能暂时无法使用，后期优化

**Comment by it-xhp** [comment]
现在可以了嘛  2023年了

**Comment by it-xhp** [comment]
> 开源版本此功能暂时无法使用，后期优化

现在开源版本能使用这个功能嘛
