### ISSUE TITLE
Online表单如果是附表，控件类型选项缺少了多行文本、富文本框等

### ISSUE THREAD

**Issue by TangTank** [jeecgboot/jeecg-boot#2948]
##### 版本号：
2.4.6

##### 问题描述：
Online表单开发中，如果A为主表、B为附表 ，在页面属性Tab：
在A表单开发里，控件类型可选项是全的，包含了多行文本，富文本编辑器等
在B表单开发中，控件类型**缺失了**部分选项，如多行文本、富文本编辑器等

##### 截图&代码：
![image](https://user-images.githubusercontent.com/2957333/130543543-f127cf5d-38d3-49fe-972c-f06a02aa8cea.png)

![image](https://user-images.githubusercontent.com/2957333/130543448-474664a1-3f57-4bcf-979c-12a83aa73bf9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by TangTank** [comment]
当前的解决办法是，将附表先改为单表模式，将控件类型选好后，再改回附表(一对多)

**Comment by zhangdaiscott** [comment]
行模式显示富文本编辑器好看吗

**Comment by TangTank** [comment]
> 行模式显示富文本编辑器好看吗

需要使用多行文本框

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
下个版本支持 多行文本
