### ISSUE TITLE
Online报表字段Href跳转到组件报错

### ISSUE THREAD

**Issue by GEEKZX** [jeecgboot/jeecg-boot#2950]
##### 版本号：
2.4.5

##### 问题描述：
Online报表字段Href跳转到组件报错,按照网上搜索到的老代码，测试运行正确

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12831180/130583971-4a8136e1-cb9e-41d6-8e62-0cede856b1b3.png)
![image](https://user-images.githubusercontent.com/12831180/130584064-8fc39d0b-1ccc-4174-95aa-5e84835a06d8.png)
以下为网上搜索的老代码及本地测试
![IVVBLH P(DLH27I8LFTZAF](https://user-images.githubusercontent.com/12831180/130584125-2ffdf5ec-2ded-4093-b5a4-e30af8788a40.png)
![~6(1S3D(C}`M$@P7@H1BRA0](https://user-images.githubusercontent.com/12831180/130584169-22c3e7b0-ad88-488c-846f-8bc8405baf21.png)
![DHSG@4CD055KR7P2M Z_%0T](https://user-images.githubusercontent.com/12831180/130584263-16aa04f7-9cb4-42a6-886d-02eb0dba719e.png)
![5P%W3@KT48MR MOOY@%58SJ](https://user-images.githubusercontent.com/12831180/130584290-de6800aa-f3d3-421e-8509-29fb0fd7ea5c.png)
![image](https://user-images.githubusercontent.com/12831180/130584415-4fa098f1-79f8-4d4a-8aac-e986e79ec63a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你的版本2.1.5 太老，不支持

**Comment by zhangdaiscott** [comment]
开源版本此功能暂时无法使用，后期优化
