### ISSUE TITLE
一对多情况下，生成的代码“多方”tab栏中的查询框丢失

### ISSUE THREAD

**Issue by TangTank** [jeecgboot/jeecg-boot#2952]
##### 版本号：
2.4.6

##### 问题描述：
使用一对多表结构，ERP风格，在线功能测试时，TAB中是有查询框的，但是生成的代码，查询框丢失了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/2957333/130714398-5f45f084-99d7-485a-8ee7-9c087b0c6044.png)

![image](https://user-images.githubusercontent.com/2957333/130714528-f87b406b-aff1-4f80-9112-303f4dba676d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前没做那么细，生成后自己改造吧
