### ISSUE TITLE
JS增强报错

### ISSUE THREAD

**Issue by FreedomStark** [jeecgboot/jeecg-boot#2953]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/130716982-c97c12c5-299c-4ba3-94bb-e4c728de57ac.png)
![image](https://user-images.githubusercontent.com/63634402/130717088-4e0ecf10-ebf0-4541-b5cf-a9123c3d8f8e.png)
![image](https://user-images.githubusercontent.com/63634402/130716999-f2bf58aa-19b8-4c44-9b7a-5cdcacc953b1.png)
![image](https://user-images.githubusercontent.com/63634402/130717017-86cc3c5d-7d03-4792-9a0d-eb7a29823060.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
用法不对
