### ISSUE TITLE
JS增强报错

### ISSUE THREAD

**Issue by FreedomStark** [jeecgboot/jeecg-boot#2954]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/130719872-05a1ca90-43a5-4e77-9e05-cf0983bd62ea.png)
![image](https://user-images.githubusercontent.com/63634402/130719893-072b675a-b631-4458-98ff-58593d47b386.png)
![image](https://user-images.githubusercontent.com/63634402/130720138-93904afd-cbfe-4c33-b408-152e1f191a3f.png)
![1](https://user-images.githubusercontent.com/63634402/130720012-0e76b54d-4838-4754-a12e-b7025d844b05.gif)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
报什么错，具体说明

**Comment by FreedomStark** [comment]
![image](https://user-images.githubusercontent.com/63634402/130720151-cc91d9aa-372e-4c8c-83ec-3daccedff352.png)

**Comment by zhangdaiscott** [comment]
你有sub这个字段吗

**Comment by FreedomStark** [comment]
没有sub字段，但是按钮编码是sub

**Comment by zhangdaiscott** [comment]
用法不对
