### ISSUE TITLE
请问怎么关闭 积木报表 呢?

### ISSUE THREAD

**Issue by baicaiit** [jeecgboot/jeecg-boot#2956]
##### 版本号：
2.4.5

##### 问题描述：
![image](https://user-images.githubusercontent.com/42630572/130747425-3fcdd759-392f-405a-9cd1-5c397506e141.png)
不想使用这块功能 减少加载时间 我应该在哪关闭掉呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
删除积木报表的依赖jar即可
