### ISSUE TITLE
字段Href相关问题

### ISSUE THREAD

**Issue by Code-prodigal** [jeecgboot/jeecg-boot#2958]
##### 截图&代码：
![1629880563(1)](https://user-images.githubusercontent.com/32701259/130757883-f613343e-8765-4a4c-be97-3b5810acf6d9.jpg)

![1629880933(1)](https://user-images.githubusercontent.com/32701259/130758307-7520deb5-f7d8-4319-8d8c-e90f1db59c90.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成后，需要自己实现，不支持代码生成
