### ISSUE TITLE
微服务版集成企业微信单点登录

### ISSUE THREAD

**Issue by 743636214** [jeecgboot/jeecg-boot#2959]
##### 问题描述：
微服务版集成企业微信和钉钉单点登录问题，由于官方视频和文档只记录了单机版的集成方式，所以导致好像只有单机版本才能单点登录，微服务版报重定向url错误

##### 截图&代码：
微服务版错误信息：
![SORV1VD1$VRVLOY9C5QE}$J](https://user-images.githubusercontent.com/51351795/130767299-215fb6a2-35d8-490b-bbd2-4b1d64451754.png)
单机版成功登录界面：
![0 0(LGKG{UJ97IH4%P0F92](https://user-images.githubusercontent.com/51351795/130767227-f9c5ce99-2d8b-4983-8dbc-57edb02f9dd6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
问题已修复，下版本发布。

### 原因
因为微服务版没有端口号，导致 `SpringContextUtils.getDomain()` 方法获取的域名的端口号变成了`:-1`所以出问题了，只需要把这个-1给去掉就可以了。
![image](https://user-images.githubusercontent.com/34293221/131488483-432b4fc2-46dc-4883-b078-46ed20f9a510.png)

### 修改方案
修改以下类：
`org.jeecg.common.util.RestUtil`
`jeecg-boot-base\jeecg-boot-base-core\src\main\java\org\jeecg\common\util\RestUtil.java`
![image](https://user-images.githubusercontent.com/34293221/131488751-20042c2b-1133-454a-bc71-da024db7ba4f.png)
``` java
public static String getDomain() {
    if (domain == null) {
        domain = SpringContextUtils.getDomain();
        if (domain.endsWith(":-1")) {
            domain = domain.substring(0, domain.length() - 3);
        }
    }
    return domain;
}
```
------

以上修改将在下版本更新后同步。
