### ISSUE TITLE
集成开源视频通话 jitsi

### ISSUE THREAD

**Issue by 743636214** [jeecgboot/jeecg-boot#2962]
##### 版本号：
2.4.6

##### 问题描述：
建议jeecg-boot集成视频通话，有如下建议方案：
jitsi 免费开源视频框架，自己搭建服务器，适用于内部网络或政务网络

##### 截图&代码：
![企业微信截图_16299497101149](https://user-images.githubusercontent.com/51351795/130898004-304f3223-a8ef-48a0-b5ea-8131be8f95d8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂时不做需要可以自己集成，如果你做了的话，可以分享到论坛http://bbs.jeecg.com/forum-244-1.html
