### ISSUE TITLE
JVXETable 验证时弹出红色框提示框，如果这是滚动页面，红色框提示框留在固定位置，而验证的文本框随页面滚动

### ISSUE THREAD

**Issue by sunjianming2021** [jeecgboot/jeecg-boot#2963]
##### 版本号：
version: 2.4.3

##### 问题描述：
JVXETable 验证时弹出红色框提示框，如果这是滚动页面，红色框提示框留在固定位置，而验证的文本框随页面滚动

##### 截图&代码：
![image](https://user-images.githubusercontent.com/85572518/130924678-eff2eb6a-b871-49af-a2b3-cbe13da79907.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sjlei** [comment]
需要升级vxe-table的版本，但目前无法升级，所以暂时无法修复该问题
