### ISSUE TITLE
创建多个附表时生成代码提示url too long

### ISSUE THREAD

**Issue by Rewivy** [jeecgboot/jeecg-boot#2965]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/48473052/131069124-47318bb6-7ac9-4ad8-a760-ad4b0fe5cfb1.png)

![image](https://user-images.githubusercontent.com/48473052/131069172-eb482f5c-2ace-4de8-9032-0230faffd595.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你这是点击下载导致的吧，你直接生成到对应目录不就行了

**Comment by Rewivy** [comment]
对应目录不在我电脑上，后面让同事打包给我了




在2021年09月01日 ***@***.*** 写道：

你这是点击下载导致的吧，你直接生成到对应目录不就行了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
https://cloud.tencent.com/developer/article/1497679
