### ISSUE TITLE
在线报表，制作popup时，是否显示列置空，或者可以取消全选

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#2970]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/131205090-7599f2a6-7bee-47a9-b367-1eefadcfbc59.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
一个字段不显示意义？

**Comment by jeffZbj** [comment]
比如弹窗只展示三个字段就够了，就是我自己可以勾选，如果一堆字段默认被勾选，我就要去掉很多。请大佬明鉴！



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年8月28日(周六) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 在线报表，制作popup时，是否显示列置空，或者可以取消全选 (#2970)




 
一个字段不显示意义？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
可以一个一个扣掉，没必要做这个功能
