### ISSUE TITLE
多数据源情况下开启如何开启非主库的事务

### ISSUE THREAD

**Issue by zhanfk** [jeecgboot/jeecg-boot#2971]

**Comment by zhangdaiscott** [comment]
多数据源，那个用法？具体说明

**Comment by zhanfk** [comment]
> 多数据源，那个用法？具体说明
您好，我是在配置文件种配置得多数据源（如下图），然后我再Mapper里面使用@DS来切换数据源，但是在使用控制器里面使用@Transactional开启事物之后，方法里面的操作就会去主库进行，无法正常读写数据。请问下我应该怎么操作才能开启正确的事务
![image](https://user-images.githubusercontent.com/29629745/131425808-31e27991-f69f-48d3-99a5-645d9b256f71.png)

**Comment by zhangdaiscott** [comment]
看看有没有帮助

https://blog.csdn.net/w57685321/article/details/106823660/
https://mp.baomidou.com/guide/dynamic-datasource.html#%E6%96%87%E6%A1%A3-documentation
