### ISSUE TITLE
webSocket 报错

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2972]
##### 问题描述：F12一直提示这个错误，后端通过swagger测试接口没有问题，导致此错误该如何解决？
app.cbf7c337.js:1 WebSocket connection to 'ws://192.168.6.188:9999//websocket/e9ca23d68d884d4ebb19d07889727dae' failed: Error during WebSocket handshake: Unexpected response code: 404

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/131308856-78f47f8a-8460-4498-83cc-f6b451b06421.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/qq_18649209/article/details/79529434
参考

**Comment by zhangdaiscott** [comment]
还有可能是ngnix配置问题，自己排查吧，程序没问题
