### ISSUE TITLE
查询配置相关问题

### ISSUE THREAD

**Issue by Code-prodigal** [jeecgboot/jeecg-boot#2973]
##### 问题描述：
在线表单中没有问题   代码导出后  查询配置不能使用

##### 截图&代码：
在线表单：
![1630313702(1)](https://user-images.githubusercontent.com/32701259/131314261-8cd53d72-11f7-488a-96bd-d8be4f951be9.png)
代码导出后：
![1630313763(1)](https://user-images.githubusercontent.com/32701259/131314266-baf780e7-f3e6-44cc-8e52-2531a04be5c9.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
并不是所有在线配置都支持生成
