### ISSUE TITLE
新版本前端突然无法通过gateway访问后端独立的微服务接口

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2976]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/131439150-26bb18c1-dd5c-4660-a759-10ab2439ed62.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看看是不是做了什么重复跨域设置

**Comment by yangkui001** [comment]
**跨域所涉及的代码如下所示，请官方帮忙看看是哪个步骤出现了问题**
![image](https://user-images.githubusercontent.com/50698315/131450987-d45bcb23-a522-44f4-978e-add9e1f53120.png)
![image](https://user-images.githubusercontent.com/50698315/131451081-d9d69912-3275-4af6-aad2-2daf27cd9f63.png)
![image](https://user-images.githubusercontent.com/50698315/131451094-98911a37-4a56-4d91-9ee1-032d7ec616b3.png)
![image](https://user-images.githubusercontent.com/50698315/131451101-2cf4299f-a71f-4dcc-a004-1f770ea2aaca.png)

**Comment by yangkui001** [comment]
> 看看是不是做了什么重复跨域设置

可以看看我的回复吗，在线等！

**Comment by zhangdaiscott** [comment]
看不出来，本地测试下

**Comment by tb2888** [comment]
最后是怎么解决的呢？

**Comment by yangkui001** [comment]
调整一下配置文件，改一下网络配置，解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月7日(星期天) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 新版本前端突然无法通过gateway访问后端独立的微服务接口 (#2976)





 
最后是怎么解决的呢？
