### ISSUE TITLE
关于多租户与企业微信的一些问题

### ISSUE THREAD

**Issue by alexwanghc** [jeecgboot/jeecg-boot#2977]
##### 版本号：
2.4.5

##### 问题描述：
请问我开启了SaaS多租户模式
1. sys开头的表 需不需要加 租户id字段？如果加了，那么初始数据怎么办？（我们想要的效果是各个用户可以维护各自的角色权限，除了菜单估计都要加多租户的字段）？如果不支持，那么有没有什么好的改造方案？
2. 假如一张 tb_goods（商品表），开启了多租户，那么我怎么查所有租户的商品（平台管理员的概念）？
3. 企业微信的工具类，支不支持服务商接口？（不是自有应用）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/zhangdaiscott/article/details/119780074
