### ISSUE TITLE
swagger无法登录

### ISSUE THREAD

**Issue by Benjamin-536** [jeecgboot/jeecg-boot#2978]
##### 版本号：
2.4.6

##### 问题描述：
使用yml中的swagger账号无法登录

##### 截图&代码：

![image](https://user-images.githubusercontent.com/66345194/131610830-aa94ca8c-c833-4f00-9fc5-b5e5617ef495.png)

![image](https://user-images.githubusercontent.com/66345194/131610813-0c603c42-3165-4bf4-bd22-61ef96081b68.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截图看提示

**Comment by Benjamin-536** [comment]
enable改了能进了.
