### ISSUE TITLE
页面按钮权限遇到问题

### ISSUE THREAD

**Issue by FreedomStark** [jeecgboot/jeecg-boot#2979]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63634402/131645449-3ffe47e7-c871-44a7-bb2c-426fd47fec89.png)
![image](https://user-images.githubusercontent.com/63634402/131645724-ee5ffded-9eba-4339-b225-78ddb2649f11.png)
![1](https://user-images.githubusercontent.com/63634402/131645759-94f81d14-c1c0-4333-8699-d4605b7bd8a5.gif)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看视频
