### ISSUE TITLE
执行sql脚本错误

### ISSUE THREAD

**Issue by MrWentao** [jeecgboot/jeecg-boot#2980]
##### 版本号：
2.4

##### 问题描述：
执行sql脚本出现错误,问一下这个问题是正常的吗?

##### 截图&代码：
![image](https://user-images.githubusercontent.com/82214662/131703353-5f6fa85a-5ac5-4c97-a772-9204063620e7.png)

![微信图片_20210901234857](https://user-images.githubusercontent.com/82214662/131702998-cc0ebc19-a5f7-4803-9fe1-78f2a38b201c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by MrWentao** [comment]
排除版本低

**Comment by zhangdaiscott** [comment]
不正常，看看什么错
