### ISSUE TITLE
JAVA的类名的首字母，居然用小写

### ISSUE THREAD

**Issue by wang-sm** [jeecgboot/jeecg-boot#2981]
##### 截图&代码：

![NS6EN6F2SC1IVZ{_~ XF_WP](https://user-images.githubusercontent.com/9496298/131777781-15dc157a-5fc3-4c8d-9569-6abf8c89dbe7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
历史原因，改不动了
