### ISSUE TITLE
隐藏域

### ISSUE THREAD

**Issue by MavonCmc** [jeecgboot/jeecg-boot#2984]
##### 版本号：
2.4.6

##### 问题描述：
页面属性是否可放开，添加隐藏域。
比如popup弹出，带回来名字和ID，展示名称，id不显示。这种怎么处理？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个是你的页面设置，跟返回哪些值没关系
