### ISSUE TITLE
是否可以出一个微信小程序的版本及单独出一个电商常用功能的模块

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#2987]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
我们不能把平台做的太臃肿，你可以开发一个，分享到论坛 http://bbs.jeecg.com/forum-244-1.html
