### ISSUE TITLE
积木报表安全漏洞【严重】

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/jeecg-boot#2989]
##### 版本号：
jeecg-boot 2.4.6+jmreport 1.3.78

##### 问题描述：
报表设计器没受权限控制，只要拿到任何有效token后都直接可以进行报表设计，任何登录用户都可以修改任何报表，将导致报表会进行篡改，而且数据将暴露。

##### 截图&代码：
1、任何用户通过替换自己的token就直接可以修改报表：
![image](https://user-images.githubusercontent.com/3874472/132123185-5479f541-d156-44f9-a8df-509dd81049d0.png)

![image](https://user-images.githubusercontent.com/3874472/132123286-5cfc804c-4ade-446c-bccf-5c79ec072245.png)
2、而且能拿到sql或api的数据
![image](https://user-images.githubusercontent.com/3874472/132123314-29d060e9-974f-4853-9ccb-e085bcfd0810.png)
3、数据字典可以任意修改
![image](https://user-images.githubusercontent.com/3874472/132123397-96d15483-1f35-4d44-82db-a4c48dc51cd6.png)

##### 建议：
增加每个报表分级授权和权限控制，并对数据字典和报表设计模块分开  并进行权限控制

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开启saas模式，就可以实现数据格式了
http://report.jeecg.com/2302149
