### ISSUE TITLE
版本2.2.0 配置多数据源时无效, 一直都是使用默认master数据源

### ISSUE THREAD

**Issue by lihongguang-lhg** [jeecgboot/jeecg-boot#2991]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/66587661/132181628-ff1310e7-47ee-452c-b0d6-e1301917c0c4.png)
![image](https://user-images.githubusercontent.com/66587661/132181775-28f0400b-b52c-40fc-8a0c-db6c5e3ea264.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ds注解是mybatisplus的，springjdbc不走ds注解

**Comment by lihongguang-lhg** [comment]
> ds注解是mybatisplus的，springjdbc不走ds注解

我用mybatisplus的查询也是一样的错误! 我这个spring jdbc在你们最新版本2.4.6是可以成功的, 我看这里也有几个人问过这个问题,但是都没看到结果
