### ISSUE TITLE
dict code table bug

### ISSUE THREAD

**Issue by zhongjunwang** [jeecgboot/jeecg-boot#2992]
##### 问题描述：
如果字典 text 或者value 有一个为空导致保存或者业务不对

##### 截图&代码：
修复方案 过滤掉 空的字典数据
```
	<select id="queryTableDictItemsByCode" parameterType="String"  resultType="org.jeecg.common.system.vo.DictModel">
		   select ${text} as "text",${code} as "value" from ${table} where ${text} is not null and ${code} is not null;
	</select>
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么功能，什么使用方式

**Comment by zhongjunwang** [comment]
![image](https://user-images.githubusercontent.com/90086254/132202193-e31eda3e-6e90-420b-be51-7427fc40fde9.png)
`
                <j-search-select-tag placeholder="请选择用户姓名" v-model="queryParam.realName" dict="sys_user,realName,realName"/>

`
如果不按照的改的话会返回一个空的对象 然后这个下拉查询那个就会报错了

**Comment by zhangdaiscott** [comment]
为什么会出现空的情况
