### ISSUE TITLE
下拉搜索框 字典建议

### ISSUE THREAD

**Issue by zhongjunwang** [jeecgboot/jeecg-boot#2993]
##### 问题描述：
有时候我们想要有个下拉搜索比如订单编号，产品名称搜索，在一个商品表里面，我们用现在的  goods,name,name, 那个有点问题
如果有重复的产品名 或者有空的都查回来了，我们想要的效果是要去重加过滤空的
建议在加一个table,name的选项
 `
              j-search-select-tag v-model="model.name" dict="good,name"  
	
	<select id="queryTableCodeDictItemsByCode" parameterType="String"  resultType="org.jeecg.common.system.vo.DictModel">
		   select DISTINCT ${code} as "text",${code} as "value" from ${table} where ${code} is not null;
	</select>`
这样下拉搜索用户就很方便了

##### 截图&代码：
修复方案 过滤掉 空的字典数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
个性化需求，自己封装一个新组件即可
