### ISSUE TITLE
online对接积木报表，api数据集无法正常解析

### ISSUE THREAD

**Issue by Tdickson3** [jeecgboot/jeecg-boot#2994]
##### 版本号：
2.4.6

##### 问题描述：
在[B站视频JeecgBoot2.4.6新特性讲解—专题视频](https://www.bilibili.com/video/BV1Y541147m1) 学习online在线表单对接积木报表时，无法使用api地址`http://localhost:8080/jeecg-boot/online/cgform/api/data/{tableName}/queryById?id='${id}'&token='${token}'`正常解析。请问是需要修改代码或者做其他配置吗？

##### 截图&代码：
表结构：
![image](https://user-images.githubusercontent.com/44915990/132197852-3f637c23-47c6-4a6a-a12f-bc596329c603.png)
api解析：
![image](https://user-images.githubusercontent.com/44915990/132198462-987e7ff0-15c6-49a4-a867-d055031122a5.png)
浏览器直接访问api：
![image](https://user-images.githubusercontent.com/44915990/132198322-391217c7-32ce-442a-9094-858d469694c9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你本地的后台地址是什么

**Comment by zhangdaiscott** [comment]
未参数对应的参数

**Comment by Tdickson3** [comment]
> 未参数对应的参数

请问可以具体一点吗，不太理解“未参数对应的参数”这句话🙏

**Comment by zhangdaiscott** [comment]
参数设置默认值
![MB`)3VCE {~_4_(8AQ8SI9M](https://user-images.githubusercontent.com/3162115/132453077-d0141d58-0cac-4bc9-a063-82d944ce8160.png)
