### ISSUE TITLE
小屏样式日期错位

### ISSUE THREAD

**Issue by zhongjunwang** [jeecgboot/jeecg-boot#2995]
##### 问题描述：
我的是mbp13电脑 日期会错位
![image](https://user-images.githubusercontent.com/90086254/132199386-9f15053f-8024-4e15-953c-e7cd4aaf4dcf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
那个功能

**Comment by zhongjunwang** [comment]
查询功能列表的查询如果有日期范围控件如果是笔记本就会错位变成上下的

**Comment by zhongjunwang** [comment]
![image](https://user-images.githubusercontent.com/90086254/132200547-09ca05c1-19c8-4b98-93e6-0b68af23d216.png)
我看官方演示里面日期范围选择控件都变了 应该是代码生产那个日期范围控件有问题小屏不行然后都改成我截图这个了，这个代码生成的时候能同步修改下吗

**Comment by zhongjunwang** [comment]
那个最小的设置成10了改成11就好了

**Comment by zhangdaiscott** [comment]
说明那个功能

**Comment by zhongjunwang** [comment]
![image](https://user-images.githubusercontent.com/90086254/133048247-785bfba3-bd59-44cd-8b80-1e6599c1dda3.png)
就是查询列表你要是日期范围的时候那个样式排序那个默认最小版本的那个宽度默认是10 应该是11才行要不返回日期的就长度不够了
![image](https://user-images.githubusercontent.com/90086254/133048470-1cf09827-46ec-4e15-b650-30f5f42ec288.png)
代码s生成器生成的是10是不对的 要改成11
