### ISSUE TITLE
日志管理中没有异常日志记录

### ISSUE THREAD

**Issue by suhaojava** [jeecgboot/jeecg-boot#2996]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18672799/132270373-e32b740c-8ecc-4e04-80ff-ddc6939f3023.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
需要什么样的日志，是自己加的，我们默认只是做部分例子，真正项目可以根据自己需求加
`baseCommonService.addLog("手机号已经注册，请直接登录！", CommonConstant.LOG_TYPE_1, null);`

![image](https://user-images.githubusercontent.com/3162115/146858267-4be01787-ccfc-404c-a931-97c0dc97dc48.png)

**Comment by zhangdaiscott** [comment]
操作类型自己拓展即可
