### ISSUE TITLE
定时任务

### ISSUE THREAD

**Issue by 743636214** [jeecgboot/jeecg-boot#2998]
##### 版本号：
2.4.5

##### 问题描述：
制订了定时任务计划，执行了一次就不执行了，但是使用每秒执行计划，就没问题。
猜想：我之前用了好几个版本的jeecg-boot，其中发现有两个版本遇到这样的问题，我感觉是我的环境配置有问题，但是不知道在哪里。

##### 截图&代码：
![企业微信截图_16309876324268](https://user-images.githubusercontent.com/51351795/132282831-851579b5-06cb-4284-ab48-b37b71f7e26f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
清空定时任务的数据，全部重新发布
