### ISSUE TITLE
微服务模式下在docker容器中的图片访问不到

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#2999]
##### 问题描述：docker部署的微服务，使用系统接口把图片上传到docker容器服务中，在前端浏览器使用如下地址不能正常预览图片，请教官方我应该如何解决这个访问路径问题啊
http://192.168.6.188:9999/opt/upFiles/temp/1_1630292411211.jpg

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/132304957-6ba7d031-2e0d-4228-be5a-1c83064a36a8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
谁告诉你可以这么访问的？

**Comment by zhangdaiscott** [comment]
谁告诉你可以这么访问的？

**Comment by yangkui001** [comment]
&nbsp; &nbsp;张老师，我应该如何访问上传到docker的图片,是否能给个截图




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 晚上8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 微服务模式下在docker容器中的图片访问不到 (#2999)





 
谁告诉你可以这么访问的？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
