### ISSUE TITLE
定时任务出错

### ISSUE THREAD

**Issue by yantao95** [jeecgboot/jeecg-boot#3000]
##### 截图&代码：
<img width="375" alt="7e690633be87ae0d5815a06eb569e11" src="https://user-images.githubusercontent.com/87693713/132316460-3024fbb4-5b26-426b-b250-bbfd1e796e54.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yantao95** [comment]
有遇到这个问题的吗，求大佬们解答一下，救救孩子吧。

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
78

**Comment by yantao95** [comment]
但是每天晚上就测试环境在运行，而且本地的代码都一样，就算其他服务器跑了，也应该有数据。可是没有，本地都不起就在测试环境试也是一样。

**Comment by zhangdaiscott** [comment]
哪你加点日志，跟踪下
