### ISSUE TITLE
微服务下如何正确访问docker中上传的图片

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3001]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/132343598-361f0de4-3a85-437c-8211-ef9313dd6e33.png)
![image](https://user-images.githubusercontent.com/50698315/132343807-b3737718-7d26-4904-ba7c-c7df7406efa7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043968

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043968
