### ISSUE TITLE
关于表单树的改进建议-增加树的节点选择如treeId

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3003]
##### 版本号：
2.4.6

##### 问题描述：
建议增加表单树的节点选择如treeId，这样可以对treeId 的编码使用 如分类字典编码生成 编码规则，这样让树的treeId,产生上下级关系，方便在表单的自定义树中使用，达到 选择父节点，可以查出所有相关子节点的 关联数据。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29143702/132443705-d9936770-c01c-4428-89f2-2434720bd701.png)

![image](https://user-images.githubusercontent.com/29143702/132443655-6f192962-2e5a-476d-940f-63172e59d23a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
咱无计划
