### ISSUE TITLE
登陆过期，弹出登录过期的提示后，不点确定，点浏览器的刷新，有时候又回到了当前页面，有时候跳转到404

### ISSUE THREAD

**Issue by pwyGouxiong** [jeecgboot/jeecg-boot#3004]
##### 问题描述：
偶发性bug，登陆过期，弹出登录过期的提示后，不点确定，点浏览器的刷新，有时候又回到了当前页面，有时候跳转到404。

作为开发我觉得这操作很蠢，但是我又不能直接说客户你操作的蠢。。。所以询问下开发团队，可有解决办法。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本太老了，新版存在这个问题吗

**Comment by pwyGouxiong** [comment]
> 版本太老了，新版存在这个问题吗

em   我去瞅瞅。。谢谢回复。
