### ISSUE TITLE
shiro并没有验证用户api权限，如果系统暴漏在公网下则十分危险！！！

### ISSUE THREAD

**Issue by funnyzpc** [jeecgboot/jeecg-boot#3008]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/25891320/132480271-91caaa47-5796-490e-98ed-87156c0409be.png)

![image](https://user-images.githubusercontent.com/25891320/132480174-ee458fd8-3a8c-4af0-9073-db7c20436640.png)

![image](https://user-images.githubusercontent.com/25891320/132480090-d05ad543-77aa-4884-ad29-2740d82c8efc.png)

##### 建议
`建议对所有接口敏感接口添加角色（最好是权限唯一标识）验证（一般是用shiro注解） ，也可以在shiro全局或者切面或者拦截器做安全校验`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
需要权限，给对应的接口加注解
