### ISSUE TITLE
在线生成bussi_package路径

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3010]
##### 版本号：
2.4.6

##### 问题描述：
在线生成bussi_package路径能改吗，默认org.jeecg.modules.demo文件夹下就可以，我改成org.huael.modules或直接org就不行

##### 截图&代码：

jeecg_config.properties文件夹下的bussi_package

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修改 jeecg_config.properties文件夹下的bussi_package  可以生效

**Comment by 3509282792** [comment]
我已经改了，代码也生成了，但是我运行起来后通过http://localhost:8080/jeecg-boot/查询不到我org.huael.modules的api，改成org.jeecg.modules的路径就可以了

**Comment by 3509282792** [comment]
![image](https://user-images.githubusercontent.com/90361617/132610200-007f4495-68fe-4860-b48a-8c331f5f6a47.png)

**Comment by 3509282792** [comment]
这样才算成功吧
![image](https://user-images.githubusercontent.com/90361617/132610291-f68cad40-0ee9-4aa0-b79d-62621221f4ec.png)

**Comment by 3509282792** [comment]
这样才算成功吧
![image](https://user-images.githubusercontent.com/90361617/132610370-eceb8e54-ba75-47a5-a342-fd8a9f7f84f2.png)

**Comment by zhangdaiscott** [comment]
哪是扫描路径配置问题，自己研究吧

**Comment by 3509282792** [comment]
能帮我指一下吗，改哪个类，研究好多天了，没找到

**Comment by 3509282792** [comment]
是这里吗
![Uploading image.png…]()

**Comment by 3509282792** [comment]
是这里改吗
![image](https://user-images.githubusercontent.com/90361617/132619336-a4cc69fd-335f-45e6-9985-1c327677fd6b.png)

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
91
