### ISSUE TITLE
代码可以生成自定义按钮吗

### ISSUE THREAD

**Issue by treemp3** [jeecgboot/jeecg-boot#3011]
##### 版本号：
2.4.6

##### 问题描述：
online表单里面的代码生成功能，生成的代码中，包含自定义按钮吗？

##### 截图&代码：
文档里面说的不清楚，建议完善一下文档。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
