### ISSUE TITLE
在线表单报表详情页中固定会出现 ”ID“ 表单

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#3012]
##### 版本号：
v2.4.6

##### 问题描述：

更新到 v2.4.6 版本后，在线表单报表详情页中固定会出现 ”ID“ 表单

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20742044/132637690-79157dda-3807-4b08-acff-6cf19ed57b6b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经处理，更新代码

**Comment by zhangdaiscott** [comment]
已经处理，更新代码

**Comment by xiaolinVV** [comment]
好的，谢谢

**Comment by xiaolinVV** [comment]
额，我刚更新完代码，确保代码是最新的，可是还是没有解决，是不是对原来的创建的在线表单无效？
