### ISSUE TITLE
jeecg-boot-starter-cloud模块报错

### ISSUE THREAD

**Issue by lihaoyuan1** [jeecgboot/jeecg-boot#3013]
##### 版本号：
2.4.6

##### 问题描述：
jeecg-boot-starter-cloud模块报错

##### 截图&代码：
2021-09-10 10:06:18.259 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter:40 -

***************************

APPLICATION FAILED TO START

***************************

Description:

The bean 'feignDecoder', defined in class path resource [org/jeecg/config/FeignConfig.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/openfeign/FeignClientsConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是什么情况下，出现的错误

**Comment by lihaoyuan1** [comment]
kubesphere部署，启动报错的



---原始邮件---
发件人: ***@***.******@***.***&gt;
发送时间: 2021年9月10日(周五) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] jeecg-boot-starter-cloud模块报错 (#3013)




 
你是什么情况下，出现的错误
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
本地没问题的话，你得研究下你的环境了

**Comment by lihaoyuan1** [comment]
就是用的官方Dockerfile构建的镜像，不应该呀

**Comment by zhangdaiscott** [comment]
哪你直接启动docker看看

**Comment by 13223746581** [comment]
你的配置有问题
![image](https://user-images.githubusercontent.com/68310022/132855583-1c528160-2dc2-41bb-a849-f73355d94089.png)

**Comment by wjcIvan** [comment]
类似的问题 windows打包正常  在linux打包会出现这个问题

**Comment by jesse-ou** [comment]
> 类似的问题 windows打包正常 在linux打包会出现这个问题
我也遇到这个问题，linux 编译打包就不行，在windows编译打包好后复制jar到linux就可以运行，请问是否已有解决方案？

**Comment by wjcIvan** [comment]
> > 类似的问题 windows打包正常 在linux打包会出现这个问题
> > 我也遇到这个问题，linux 编译打包就不行，在windows编译打包好后复制jar到linux就可以运行，请问是否已有解决方案？

我把FeignConfig里的feignDecoder方法注释掉了，暂时没发现有什么影响

**Comment by lihaoyuan1** [comment]
我是因为k8s镜像缓存导致的，每次重启重新拉取镜像就没出现问题了。

**Comment by zhangdaiscott** [comment]
```
jeecg-boot-base\jeecg-boot-base-api\jeecg-system-cloud-api\src\main\java\org\jeecg\config\FeignConfig.java
jeecg-boot-starter\jeecg-boot-starter-cloud\src\main\java\org\jeecg\config\FeignConfig.java
```
项目中有两个类，目的是重写，做不同的调用，确认下有无修改

**Comment by jesse-ou** [comment]
> ```
> jeecg-boot-base\jeecg-boot-base-api\jeecg-system-cloud-api\src\main\java\org\jeecg\config\FeignConfig.java
> jeecg-boot-starter\jeecg-boot-starter-cloud\src\main\java\org\jeecg\config\FeignConfig.java
> ```
> 
> 项目中有两个类，目的是重写，做不同的调用，确认下有无修改

代码未做修改，同一个gitlab仓库，maven、java版本一致，在linux下使用mvn clean package编译后运行会有这个问题，在windows下mvn clean package后拷贝jar至linux运行则没有问题

**Comment by zhangdaiscott** [comment]
把这个jeecg-boot-base\jeecg-boot-base-api\jeecg-system-cloud-api\src\main\java\org\jeecg\config\FeignConfig.java
删掉
