### ISSUE TITLE
jeecg-boot使用websocket推送消息无响应

### ISSUE THREAD

**Issue by OnTheWay6** [jeecgboot/jeecg-boot#3015]
##### 问题描述：
使用jeecg-boot 2.4.3  webSocket.sendMessage方法向后台管理员推送消息无响应。使用TestSocketController中的sendUser测试方法发送也无响应，前台websocket连接提示正常。

##### 截图&代码：
![1631260744(1)](https://user-images.githubusercontent.com/49018425/132821250-d2d2e067-9921-4abf-802a-02e900ec4866.jpg)
![1631261028(1)](https://user-images.githubusercontent.com/49018425/132821251-3a625b3d-252f-4baa-a805-4ecf107213ff.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
本地环境还是部署

**Comment by OnTheWay6** [comment]
本地和服务器都一样，服务器使用了腾讯的负载均衡。在系统通告中可以看到发送记录。但是在消息中看不到记录.在sys_announcement表中加入记录。sys_announcement_send无记录

**Comment by zhangdaiscott** [comment]
你点击发布了吗
