### ISSUE TITLE
【Online表单】两个在线表单tab之间切换，产生多余查询

### ISSUE THREAD

**Issue by zoemak** [jeecgboot/jeecg-boot#3016]
##### 版本号：
2.4.6

##### 问题描述：
两个在线表单tab之间切换，产生多余查询。
不知道是否这个原因，导致偶尔会报出sql错误（where 1=1 ORDER BY后面没有拼接id）。

##### 截图&代码：

在离开第一个tab之后，仍然查了一次第一个tab的接口：
![微信截图_20210910183916](https://user-images.githubusercontent.com/16585243/132842292-e438334f-630e-4953-a0b9-a19e9bf5a189.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改，请等新版本发布

**Comment by SultanST** [comment]
请问基础版本有哪些功能，哪些功能属于高级版的，收费咋样

**Comment by zoemak** [comment]
> 请问基础版本有哪些功能，哪些功能属于高级版的，收费咋样

除了工作流和表单设计器，其他的应该都有。高级版还有核心源码（在线报表、在线表单等等这些核心功能），开源版是没的。
