### ISSUE TITLE
微服务下 生产销售监控以及智慧物流监控无法请求到数据

### ISSUE THREAD

**Issue by 13223746581** [jeecgboot/jeecg-boot#3017]
##### 版本号：
2.4.6

##### 问题描述：
微服务下 前端 报表设计模块下的生产销售监控以及智慧物流监控,请求后台css,js全部404,但是单体模式下可以访问到

##### 截图&代码：
![two](https://user-images.githubusercontent.com/68310022/132852590-34c5a2d2-1fa8-444d-a695-a56870487faf.jpg)

![test](https://user-images.githubusercontent.com/68310022/132852579-bd014e94-3bb6-4060-bf98-c43b86b4445a.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
路由网关怎么配置的？改过？

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/132853511-b2cd793b-0d7e-4822-9b5f-dbc599e3a4e1.png)

**Comment by 13223746581** [comment]
这里 我配置了一下还是不行 而且网关的配置是从nacos中获取的
![image](https://user-images.githubusercontent.com/68310022/132854781-91080972-3ec9-46ad-9a0a-8718e1c00aea.png)

**Comment by 13223746581** [comment]
> 路由网关怎么配置的？改过？

这里 我配置了一下还是不行 而且网关的配置是从nacos中获取的
![image](https://user-images.githubusercontent.com/68310022/132855136-1b520844-44fd-4570-ae60-fdc3dde69d2a.png)

**Comment by zhangdaiscott** [comment]
demo是作为微服务项目独立启动吗。如果不是把demo服务的路由配置加到system里面

**Comment by 13223746581** [comment]
> demo是作为微服务项目独立启动吗。如果不是把demo服务的路由配置加到system里面

是独立启动的

**Comment by zhangdaiscott** [comment]
自己好好研究吧，我们测没问题
