### ISSUE TITLE
在线表单功能，内嵌主题和默认主题的展开按钮样式不一致

### ISSUE THREAD

**Issue by zksong** [jeecgboot/jeecg-boot#3019]
##### 版本号：
V2.4.6

##### 问题描述：
在线表单功能，内嵌主题和默认主题的展开按钮样式不一致

##### 截图&代码：
![1631430852023_683FFEB9-5E56-4612-AC5F-79D39A73FDF9](https://user-images.githubusercontent.com/17975933/132977383-729d4e42-afac-422d-9360-81690c7d47f0.png)
![1631430868308_8EA1ADE0-78A8-47f6-B864-B55ECC7E885B](https://user-images.githubusercontent.com/17975933/132977390-1e229e54-7bcc-4335-8815-e9ee39737024.png)

**Comment by zhangdaiscott** [comment]
这个不重要

**Comment by zksong** [comment]
风格不一样没法用，有没有方式调整，我自己改也行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上6:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在线表单功能，内嵌主题和默认主题的展开按钮样式不一致 (#3019)





 
这个不重要
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
