### ISSUE TITLE
在线表单功能，内嵌主题“高级查询”按钮权限设置完不起作用

### ISSUE THREAD

**Issue by zksong** [jeecgboot/jeecg-boot#3020]
##### 版本号：
V2.4.6

##### 问题描述：
在线表单功能，内嵌主题“高级查询”按钮权限设置完不起作用

##### 截图&代码：
![1631431224247_9964013A-0603-4002-ABBA-6A8645C9AEF3](https://user-images.githubusercontent.com/17975933/132977524-c6de2161-6741-42aa-bace-67c542e85057.png)

![1631431112481_F151EAFD-4F94-40e0-80B6-600A407C40BC](https://user-images.githubusercontent.com/17975933/132977466-db60e6ca-ca55-4c26-ac9e-ff8809def9ab.png)

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修改，请等新版本发布
