### ISSUE TITLE
Js增强，添加函数页面查询报错：Uncaught (in promise) SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by showDgpl123** [jeecgboot/jeecg-boot#3021]
##### 问题描述：在一个list页面，新建一个Js增强按钮。在js增强中天界了同名函数。在list页面查询报错：
![image](https://user-images.githubusercontent.com/86600259/133013506-bf9c43ba-fcc5-4460-89e2-88a103e55582.png)
去掉这个函数，查询就正常了

##### 截图&代码：按钮同名函数
tmsOrdersGetOwnTrackingnum(row){
    var ids = "";
    var illegal_ids = "";
	var illegal_ownids = "";
    for(var i =0 ;i<row.table.selectionRows.length;i++){
      if(i<row.table.selectionRows.length-1){
         if(row.table.selectionRows[i].trackingnum==null||row.table.selectionRows[i].trackingnum==""||row.table.selectionRows[i].trackingnum=="null"){
			if(row.table.selectionRows[i].is_third_party_tracking=="1"){
				illegal_ids +=row.table.selectionRows[i].id+",";
			}else{
			  ids +=row.table.selectionRows[i].id+",";
			}
			if(row.table.selectionRows[i].requestedexpresscorp!="JNE"){
			  illegal_ownids +=row.table.selectionRows[i].id+",";
			}
    }
      
    }else{
      if(row.table.selectionRows[i].trackingnum==null||row.table.selectionRows[i].trackingnum==""||row.table.selectionRows[i].trackingnum=="null"){
		if(row.table.selectionRows[i].is_third_party_tracking=="1"){
			illegal_ids +=row.table.selectionRows[i].id+",";
		}else{
		  ids +=row.table.selectionRows[i].id+",";
		}
		if(row.table.selectionRows[i].requestedexpresscorp!="JNE"){
		  illegal_ownids +=row.table.selectionRows[i].id+",";
		}
    }      
    }
    }
    if(illegal_ids.length!=""){
    alert('第三方运单，禁止获取运单号')
    return
    }
    console.log("输出：：："+illegal_ids);
    if(ids==""){
    alert('未选中任何数据,或者选中行已经有单号')
    return
    }
	if(illegal_ownids!=""){
	alert('生成运单号仅支持JNE')
	return
	}
    getAction('url地址',{ids: ids}).then(res=>{
    alert('获取成功')
    })
    }
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by showDgpl123** [comment]
检查函数，并没有发现语法错误

**Comment by showDgpl123** [comment]
```javascript
  tmsOrdersGetOwnTrackingnum(row) {
    var ids = "";
    var illegal_ids = "";
    var illegal_ownids = "";
    for (var i = 0; i < row.table.selectionRows.length; i++) {
      if (i < row.table.selectionRows.length - 1) {
        if (row.table.selectionRows[i].trackingnum == null || row.table.selectionRows[i].trackingnum == "" || row.table.selectionRows[i].trackingnum == "null") {
          if (row.table.selectionRows[i].is_third_party_tracking == "1") {
            illegal_ids += row.table.selectionRows[i].id + ",";
          } else {
            ids += row.table.selectionRows[i].id + ",";
          }
          if (row.table.selectionRows[i].requestedexpresscorp != "JNE") {
            illegal_ownids += row.table.selectionRows[i].id + ",";
          }
        }

      } else {
        if (row.table.selectionRows[i].trackingnum == null || row.table.selectionRows[i].trackingnum == "" || row.table.selectionRows[i].trackingnum == "null") {
          if (row.table.selectionRows[i].is_third_party_tracking == "1") {
            illegal_ids += row.table.selectionRows[i].id + ",";
          } else {
            ids += row.table.selectionRows[i].id + ",";
          }
          if (row.table.selectionRows[i].requestedexpresscorp != "JNE") {
            illegal_ownids += row.table.selectionRows[i].id + ",";
          }
        }
      }
    }
    if (illegal_ids.length != "") {
      alert('第三方运单，禁止获取运单号')
      return
    }
    console.log("输出：：：" + illegal_ids);
    if (ids == "") {
      alert('未选中任何数据,或者选中行已经有单号')
      return
    }
    if (illegal_ownids != "") {
      alert('生成运单号仅支持JNE')
      return
    }
    getAction('url地址', {"ids": ids }).then(res=>{
      alert("获取成功")
    })
  }
```

**Comment by zhangdaiscott** [comment]
老版本无法处理，先确认新版是否存在问题
