### ISSUE TITLE
建议代码生成，列表加上图片预览功能，我们框架已经内置预览，

### ISSUE THREAD

**Issue by zhongjunwang** [jeecgboot/jeecg-boot#3022]
##### 问题描述：
建议代码生成，列表加上图片预览功能，我们框架已经内置预览，
![image](https://user-images.githubusercontent.com/90086254/133047478-c47f6f07-d265-4156-8ee9-0ef8d01a60a0.png)
这个样点击图片自己能够预览体验非常好 只需要改动很小
![image](https://user-images.githubusercontent.com/90086254/133047827-df10b7d2-377e-40a1-887e-c9bed593a0c1.png)
![image](https://user-images.githubusercontent.com/90086254/133047900-5e3d7654-09c2-451d-bd2b-cbba25ee8d4f.png)
用id来标记就可以预览当前行的全部图片
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by xiaolinVV** [comment]
您好，请问下，列表图片预览你是在 img 标签中加入 :preview="record.id" 就可以点击预览全部图片了？

![image](https://user-images.githubusercontent.com/20742044/134615583-1b1ce146-6507-48da-8414-9684c7ae8116.png)

**Comment by zhongjunwang** [comment]
@xiaolinVV 是的 这个是一个插件的指令功能

**Comment by zhangdaiscott** [comment]
自己改造代码生成器模板就可以了

**Comment by uckyo** [comment]
3.20最新版怎么实现，我加上:preview="record.id" 还是不显示，列表还乱了
