### ISSUE TITLE
列表页增加自定义排序后，使用高级查询前端卡死

### ISSUE THREAD

**Issue by suhaojava** [jeecgboot/jeecg-boot#3023]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/18672799/133057046-7e40ea67-bf98-48fd-902a-a3645a8083ce.png)
![image](https://user-images.githubusercontent.com/18672799/133057266-042df504-4718-42a3-8cd1-08a1c99787ed.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的代码，请自己排查

**Comment by suhaojava** [comment]
直接生成代码，什么都不改，点排序字段后，高级查询就不能用了。

> 自己写的代码，请自己排查

直接生成代码，什么都不改，点排序字段后，高级查询就不能用了。
