### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by baiyunlqy** [jeecgboot/jeecg-boot#3025]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
排序规则不支持生成，生成后手工改没什么成本

**Comment by lingyun-12** [comment]
> 排序规则不支持生成，生成后手工改没什么成本

在哪里修改规则呢，对这套系统的代码框架不熟悉。看请求是前端发送的排序方式，但目前没有找到前端vue3对应的代码
