### ISSUE TITLE
websocket相关

### ISSUE THREAD

**Issue by Caisen1988** [jeecgboot/jeecg-boot#3026]
##### 版本号：
v2.4.5

##### 问题描述：
1. websocket总是重新连接
2. get方法是可以的，但是除了get方法以外，都无法获取资源

##### 截图&代码：
1. Nginx 配置截图
1.1http部分
![image](https://user-images.githubusercontent.com/11453160/133207427-37a66bec-0bd7-40f3-a6fb-ff7074839fc2.png)
1.2 80端口部分
![image](https://user-images.githubusercontent.com/11453160/133207509-9915cfb9-68db-4522-9e92-1d612904600d.png)

2. 报错截图
2.1 总是自动重连
![image](https://user-images.githubusercontent.com/11453160/133207561-5d4e6ab5-5c64-41d5-a6f9-43bc1ef11302.png)
2.2 edit等方法无响应，get请求是可以的
![image](https://user-images.githubusercontent.com/11453160/133207700-da90a311-5999-4b2b-8ec8-611bc9abfd32.png)
2.3 catalina报错日志
![image](https://user-images.githubusercontent.com/11453160/133207815-3e2fe453-0dda-4c89-aa49-d3814e4d6109.png)
2.4 前端配置截图
![image](https://user-images.githubusercontent.com/11453160/133207865-88a5feb6-ee55-4337-a004-e00c6edf5dab.png)
![image](https://user-images.githubusercontent.com/11453160/133207898-2d574c58-ce48-4b8c-ad1f-0046bad9718d.png)
![image](https://user-images.githubusercontent.com/11453160/133207931-d95a9c6f-5bb8-4920-ad88-67f50896ebe8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
47-2
