### ISSUE TITLE
Online表单开发，mysql中bigint类型导入表单类型对应Integer,插入数据时超过长度限制

### ISSUE THREAD

**Issue by suhaojava** [jeecgboot/jeecg-boot#3029]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/18672799/133532817-38d354b6-991d-4f27-8849-a76849ce0ab9.png)
![image](https://user-images.githubusercontent.com/18672799/133532830-661dfe1d-3dc3-4796-a526-146e76e60711.png)

![image](https://user-images.githubusercontent.com/18672799/133533264-6a271c6d-125f-4683-bb4e-77ef7309518a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂时先手工调整代码吧
