### ISSUE TITLE
When to convert to the vite2 framework？

### ISSUE THREAD

**Issue by CangJieStore** [jeecgboot/jeecg-boot#3031]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
内部已经启动vue3研发工作，前端全部重写，如果快的话，年底前会发布第一个版本
