### ISSUE TITLE
自定义按钮如何选多条数据？？

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3032]
##### 版本号：
2.4.6

##### 问题描述：
业务上需要对多条数据进行合并 ，需要选在多条数据，不知道如何解决

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29143702/133545224-4bff8e49-7dcc-48a3-bddc-a9f6efe3566c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
下个版本就支持了
