### ISSUE TITLE
切换标签的时候，数据会刷新，导致原来的选择条件都没有了，是不是有配置能解决？？

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3033]
##### 版本号：

2.4.6
##### 问题描述：
切换标签的时候，数据会刷新，导致原来的选择条件都没有了，是不是有配置能解决？？
能不能配置 标签激活 不刷新

##### 截图&代码：

![image](https://user-images.githubusercontent.com/29143702/133545438-014bb71d-9b8a-4063-91ea-b9b7c3720b76.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ddwolf715** [comment]
我也有同样的需求，等高人指点。。。。。。

**Comment by zhangdaiscott** [comment]
最新版 online的功能已经实现了缓存

**Comment by Changer0914** [comment]
@zhangdaiscott  这个咋用呢，我24年10月份，使用的版本 还有这个问题
