### ISSUE TITLE
求助：自定义按钮弹出框 找不到组件？

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3034]
##### 版本号：
2.4.6

##### 问题描述：
自定义按钮弹出框 找不到组件？
如何配置？
##### 截图&代码：
![image](https://user-images.githubusercontent.com/29143702/133546446-67bf9748-0903-4ade-af0b-7fb27890f571.png)

![image](https://user-images.githubusercontent.com/29143702/133546331-4359766b-ddaf-487f-a8c5-e5cbac129657.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开源版本，不支持
