### ISSUE TITLE
Online表单，建议单独增加字段是否可修改权限

### ISSUE THREAD

**Issue by zksong** [jeecgboot/jeecg-boot#3035]
##### 版本号：
2.4.6

##### 问题描述：
目前设置字段不可编辑后，新建页面也不能填写了，希望效果是新建页面可以填写，编辑页面是只读状态。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17975933/133709266-055b88d8-731e-413b-bf9a-cb404468056b.png)
![image](https://user-images.githubusercontent.com/17975933/133709302-b7830d1e-76af-42d8-b6f5-83159fb9def6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以尝试用js增强实现，试试
