### ISSUE TITLE
前端部署到服务器用nginx代理以后，监控跨域报错

### ISSUE THREAD

**Issue by chenbo443756309** [jeecgboot/jeecg-boot#3037]
##### 版本号：
2.4.6

##### 问题描述：
前端部署到服务器用nginx代理以后，监控跨域报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19160928/133745677-5c480b63-fafb-4173-ac0d-ecf7ba161a13.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个得你自己确认部署问题
