### ISSUE TITLE
代码生成下载到本地功能无法使用

### ISSUE THREAD

**Issue by beyondiary** [jeecgboot/jeecg-boot#3039]
##### 问题描述：
代码生成下载到本地无法使用
org.jeecg.modules.online.cgform.c.a#a(java.util.List<java.lang.String>, javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
实现有点问题
989行这个临时目录不要写死，建议设置成配置项目
final String var6 = "/opt/temp/codegenerate/" + var5;
部署这个服务的系统并非都有这个目录，且有写权限

##### 截图&代码：

![image](https://user-images.githubusercontent.com/71167107/133776632-fcfe6a21-9ae5-4f63-84af-a0913f7385c4.png)

![image](https://user-images.githubusercontent.com/71167107/133776865-212393f6-4266-4114-b4f2-1c1c65707680.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开发环境，直接生成到本地目录就可以了，这个功能用的并不多
