### ISSUE TITLE
主表内嵌通过代码生成功能生成的页面与功能测试不一样

### ISSUE THREAD

**Issue by espooky** [jeecgboot/jeecg-boot#3040]
##### 版本号：
2.4.6

##### 问题描述：

主表内嵌通过代码生成功能生成的页面与示例不一样。左边的+号没了

例如在线表单开发中的【测试订单主表】功能测试显示正常，但是代码生成配置菜单浏览，页面显示就不正常了。例如左边的+号没了，编辑页面的样式也有所变化

##### 截图&代码：
代码生成的页面
![image](https://user-images.githubusercontent.com/8514942/133784642-135db55e-0437-45b8-836f-13bdd662506d.png)
示例在线测试的页面
![image](https://user-images.githubusercontent.com/8514942/133784810-c552a2f7-618c-48fe-84f8-a1ea98973330.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
细节生成后，可以自己微调
