### ISSUE TITLE
Online date类型显示异常，编辑界面显示异常，保存异常

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/jeecg-boot#3041]
##### 版本号：
jeecg版本2.4.6 
mysql 8.0.15
Server Default Charset        : utf8mb4
##### 问题描述：
1、示例程序 《online订单管理》 时间日期格式错误，见截图！
2、示例程序《online用户报表》 时间日期格式错误，见第四张截图！
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7546194/133793536-9e8c7d46-5319-4b63-b31a-4cd8f0029df7.png)
![image](https://user-images.githubusercontent.com/7546194/133793590-7b977cee-4383-4f2e-b624-395826f7066e.png)
![image](https://user-images.githubusercontent.com/7546194/133793639-d57ea835-089c-4d80-9610-1b399b3fae1f.png)
![image](https://user-images.githubusercontent.com/7546194/133793947-5d57e679-46be-41c3-bdce-bed223983726.png)

**Comment by zhangdaiscott** [comment]
已经修复，请更新代码
