### ISSUE TITLE
【求助】微服务模式下，业务服务在后台怎么获取当前登录用户

### ISSUE THREAD

**Issue by zksong** [jeecgboot/jeecg-boot#3043]
##### 版本号：
V2.4.6

##### 问题描述：
使用LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();返回null

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by chenbo443756309** [comment]
![image](https://user-images.githubusercontent.com/19160928/133870849-f2b85820-8345-4037-bb95-a19a89c99d19.png)
通过token去拿

**Comment by zksong** [comment]
OK，谢谢
