### ISSUE TITLE
【建议】Online表单，列表中大文本列能否自动换行或者具有titile提示

### ISSUE THREAD

**Issue by zksong** [jeecgboot/jeecg-boot#3045]
##### 版本号：
V2.4.6

##### 截图&代码：

![image](https://user-images.githubusercontent.com/17975933/133873595-297b9207-bee8-43a9-a555-788fe9d70ba6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以配置截取显示

**Comment by zksong** [comment]
截取完在列表页信息看不全，如果能增加悬浮显示就更好了。
