### ISSUE TITLE
字段label设置过长被遮盖怎么解决？

### ISSUE THREAD

**Issue by jack-zxj** [jeecgboot/jeecg-boot#3046]
##### 版本号：
2.4.6

##### 问题描述：
字段label设置过长怎么控制其不被文本框等遮盖

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52274422/133880676-6f43a90a-9775-4275-b89e-94db9bb70209.png)
![image](https://user-images.githubusercontent.com/52274422/133880692-8a776523-8d53-4b2a-b49f-9069a21d1db0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
下个版本可以自定义弹窗宽度

**Comment by Icodezhan** [comment]
> 下个版本可以自定义弹窗宽度

怎么配置啊，文档也没说明
