### ISSUE TITLE
Online表单开发，希望在查询配置增加联动控件

### ISSUE THREAD

**Issue by stone2world** [jeecgboot/jeecg-boot#3047]
##### 版本号：
2.4.6
##### 问题描述：

Online表单开发，页面属性可以使用联动控件，查询配置没有联动控件,导致多级联动只能录入，不能查询，希望查询配置增加联动控件

##### 截图&代码：
这是页面属性控件列表
![image](https://user-images.githubusercontent.com/43597843/133882188-16749f65-b262-499e-b3c4-037a023f8a34.png)
这是查询属性控件列表，希望增加联动控件
![image](https://user-images.githubusercontent.com/43597843/133882389-3cb17ee0-aa85-430d-b10d-091b41725375.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂无计划
