### ISSUE TITLE
部门权限无效，只有部门角色的权限有效

### ISSUE THREAD

**Issue by luoqiuqiu** [jeecgboot/jeecg-boot#3052]
##### 问题描述：
目前jeecgboot，给部门授权，用户配置所属部门，没有建部门角色，该用户不能拥有该部门下的权限，是这个样子吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
部门拥有的权限，是需要给部门角色分配上，人挂角色才行
