### ISSUE TITLE
逻辑删除

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/jeecg-boot#3054]
##### 版本号：
2.4.6

##### 问题描述：
是否考虑在线代码生成器里添加逻辑删除的配置功能？配置生成一个业务界面时，可定义是物理删除还是逻辑删除。

##### 截图&代码：
无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后期规划
