### ISSUE TITLE
过滤条件不能过滤为空或不为空的数据

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/jeecg-boot#3055]
##### 版本号：
2.4.6

##### 问题描述：
目前界面的过滤条件好像不支持过滤为空或不为空的数据，即数据库中的 is null 或 is not null 的过滤条件，在高级查询里也没有。
用户要通过查找这类空值的列，进行补数据。

是否会考虑在过滤条件添加空值的查找？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个需求自己改造吧
