### ISSUE TITLE
查询过滤器如何实现多个查询字段模糊查询时是or而不and

### ISSUE THREAD

**Issue by longhao1987** [jeecgboot/jeecg-boot#3056]
##### 版本号：
2.4.6

##### 问题描述：
查询过滤器如何实现多个查询字段模糊查询时是or而不and，当前没找到配置项默认是and查询sql
##### 截图&代码：
![image](https://user-images.githubusercontent.com/37317006/134485661-f0dfaeea-ec85-4bab-9796-2586df53357f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
特殊的逻辑，你可以后台自己编码实现
