### ISSUE TITLE
Online表单开发时，新建表单进行功能测试时，日期格式展示为时间戳的形式

### ISSUE THREAD

**Issue by qiaochengqiang** [jeecgboot/jeecg-boot#3057]
##### 版本号：
2.4.6

##### 问题描述：
Online表单开发时，新建表单进行功能测试时，日期格式展示位时间戳的形式，直接使用已存在的样例进行查看测试，一样是时间戳的形式

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57664443/134491896-7c2525cb-1f0c-4475-8dfd-3613371da737.png)
![image](https://user-images.githubusercontent.com/57664443/134492015-18975501-741c-4bd9-ab2b-047994bf8af8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么数据库？

**Comment by zhangdaiscott** [comment]
已经修复，请更新代码
