### ISSUE TITLE
后端将long转为string后，前端的数据类型对不上，导致报错，比如table分页

### ISSUE THREAD

**Issue by luoqiuqiu** [jeecgboot/jeecg-boot#3058]
##### 问题描述：
后端将long转为string后，前端的数据类型对不上，导致报错，比如table分页
之前版本的代码没有这个问题
虽然可以在前端Number(string) ，但是还是十分不方便，感觉有很多地方要改
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776176/134613069-7e470d40-febc-4760-b270-d894b9be84e2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已经修复，请更新代码
