### ISSUE TITLE
积木报表的主子报表参数无法保存

### ISSUE THREAD

**Issue by xiaoyizeng** [jeecgboot/jeecg-boot#3059]
##### 版本号：
jeecgboot 2.4.6

##### 问题描述：
在最新的版本中，使用积木报表中的主子报表参数时，会出现无法新增的情况。jeecgboot的数据库版本是postgresql，在配置中也配置了minidao的数据库类型为 postgresql。查看之后发现sql报错： bad SQL grammar [INSERT INTO jimu_report_link ( ID ,REPORT_ID ,PARAMETER ,EJECT_TYPE ,LINK_NAME ,API_METHOD ,LINK_TYPE ,API_URL ,LINK_CHART_ID ,`EXPRESSION` ) values ( ? ,? ,? ,? ,? ,? ,? ,? ,? ,? )]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "`"
其中`EXPRESSIO`是按照MySql中关键字的写法，但是并不适用于其他数据库。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/81517044/134627012-f454ae74-707d-403e-aaee-6a4b8b20160e.png)
![image](https://user-images.githubusercontent.com/81517044/134626579-98742c07-11c3-49fb-bac1-6eaaef4f6419.png)
![image](https://user-images.githubusercontent.com/81517044/134626615-b5177b5a-6e2c-418d-b550-871cd095e629.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
升级积木报表到最新版http://jimureport.com/doc/log
