### ISSUE TITLE
调度失败：执行器地址为空

### ISSUE THREAD

**Issue by he0128** [jeecgboot/jeecg-boot#3066]
##### 问题描述：
参照文档 生成xxljob定时任务，报错 调度失败：执行器地址为空

##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776371/134802624-68085bfd-0c4b-4e48-8509-ef9efe67aa96.png)

![image](https://user-images.githubusercontent.com/52776371/134802594-b4a77947-4eeb-4660-b567-49350de54952.png)

![image](https://user-images.githubusercontent.com/52776371/134802363-9e9b9605-f8c4-4831-96dd-912378c3e671.png)

![image](https://user-images.githubusercontent.com/52776371/134802672-c2fcb5a6-f7a9-4c0b-9f04-bee97c1f97d0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
配置对吗

**Comment by he0128** [comment]
很无奈 弄了一下午都没好使 刚才不知道改啥 就好使了 可以关了
