### ISSUE TITLE
safari 15.0  首页卡死

### ISSUE THREAD

**Issue by jiangzif** [jeecgboot/jeecg-boot#3067]
##### 版本号：
2.4+

##### 问题描述：
使用最新版本safari访问网站登录后首页直接卡死，canvs图标均不能显示，猜测和canvs有关
访问官方演示即可复现：http://boot.jeecg.com
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
什么效果，控制台什么错误？
