### ISSUE TITLE
前端项目导入electron进行打包后，控制台报错!!!

### ISSUE THREAD

**Issue by Zll06** [jeecgboot/jeecg-boot#3068]
##### 版本号：
master主分支

##### 问题描述：
前端项目导入electron进行打包后，控制台报错!!!

##### 截图&代码：
![微信截图_20210927113937](https://user-images.githubusercontent.com/59157537/134842144-9e1847b2-b109-49cc-a883-b585ae18052d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yourenyouyu** [comment]
这个为啥会报错呢，我也遇到系统问题了
