### ISSUE TITLE
代码自动生成的列表console报分页错误

### ISSUE THREAD

**Issue by mianfeidog** [jeecgboot/jeecg-boot#3071]
##### 版本号：
2.4.6

##### 问题描述：
代码自动生成的列表console报分页错误，不影响运行，但报的错误信息很多，影响体验

##### 截图&代码：
nvalid prop: custom validator check failed for prop "pagination".

found in

---> <Table>
       <ATable>
         <ACard>
           <SingleList> at src/views/erp/test/SingleList.vue
             <RouteView> at src/components/layouts/RouteView.vue
               <Anonymous>
                 <ALayoutContent>
                   <Anonymous>
                     <ALayout>
                       <Anonymous>
                         <ALayout>
                           <GlobalLayout> at src/components/page/GlobalLayout.vue
                             <TabLayout> at src/components/layouts/TabLayout.vue
                               <ALocaleProvider>
                                 <LocaleReceiver>
                                   <AConfigProvider>
                                     <App> at src/App.vue
                                       <Root>

 Invalid prop: type check failed for prop "total". Expected Number with value 2, got String with value "2".

found in

---> <APagination>
       <ASpin>
         <Table>
           <ATable>
             <ACard>
               <SingleList> at src/views/erp/test/SingleList.vue
                 <RouteView> at src/components/layouts/RouteView.vue
                   <Anonymous>
                     <ALayoutContent>
                       <Anonymous>
                         <ALayout>
                           <Anonymous>
                             <ALayout>
                               <GlobalLayout> at src/components/page/GlobalLayout.vue
                                 <TabLayout> at src/components/layouts/TabLayout.vue
                                   <ALocaleProvider>
                                     <LocaleReceiver>
                                       <AConfigProvider>
                                         <App> at src/App.vue
                                           <Root>

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新代码
