### ISSUE TITLE
代码生成与预览效果不一致

### ISSUE THREAD

**Issue by sayhei** [jeecgboot/jeecg-boot#3074]
##### 版本号：
2.4.6

##### 问题描述：
1.嵌子表导出与预览效果不一致 
2.在java代码里写了默认值规则，测试预览可以正常，但是代码生成出来的代码，页面无相关效果，前端代码里也无相关代码
##### 截图&代码：
问题1：
表单开发，功能测试截图如下
![image](https://user-images.githubusercontent.com/8320880/134889635-b1ee5a44-7ce2-47c7-b426-1e249caef622.png)
代码生成器生成代码效果如下
![image](https://user-images.githubusercontent.com/8320880/134889981-46d15df4-f8e6-444a-9982-83371a981f0c.png)

问题2：
表单开发，功能测试截图如下
![image](https://user-images.githubusercontent.com/8320880/134890906-42059603-8e98-47a3-a28b-3d75ba9c8fde.png)
代码生成器生成代码效果如下
![image](https://user-images.githubusercontent.com/8320880/134891187-044e0862-1868-4f20-ad93-374c7e506087.png)

**Comment by zhangdaiscott** [comment]
默认值规则不支持生成

**Comment by RamboWu** [comment]
> 默认值规则不支持生成

做的有点那么不人性化
