### ISSUE TITLE
【功能建议】关于 JPopup 组件的两个建议

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#3076]
##### 版本号：
v2.4.6

##### 问题描述：

`JPopup` 组件挺好用的，但是我个人了解之后发现有以下两个建议：

- 建议 `JPopup` 组件加一个默认选中的功能，就是点击打开弹窗后，默认勾选上上次回显的列表
- 建议 `JPopup` 组件把回显的值进行一下区分，正常我们表单选中之后回显的文本名称（text）,但是表单内部传参是对应的值（value）但是目前来看，`JPopup` 把 value、text 共用了，导致只能把 value 字段回显到组件上，要是回显名称到组件上，那传参就变成传 text 了，这显然也不符合使用习惯

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
马上出vue3版本了，新版本会考虑你的建议

**Comment by xiaolinVV** [comment]
期待，预计啥时候上新版本呀  @zhangdaiscott

**Comment by zhanghaiqun** [comment]
生成代码, 修改 ***List.vue文件中的  <j-popup   :field="getPopupField('field_name')>， 把 field_name 改成需要回显的字段
