### ISSUE TITLE
k8s部署前后端，websocket一直断开

### ISSUE THREAD

**Issue by hw0809** [jeecgboot/jeecg-boot#3077]
##### 版本号：
V2.4.6

##### 问题描述：
使用k8s部署前后端，websocket一直会断开，页面就会一直重新链接，按照之前的回复的解决方法，在dockerfile给nginx加了配置Upgrade，Connection，部署之后还是有问题。

我自己的解决方法是把HeaderNotice.vue的心跳注释打开了，这样子就不会有报错了。但是我不知道直接打开注释会不会有什么问题，在修改log里面没找到为什么要注释掉心跳，不知道我这边直接打开是否会有什么问题。

##### 截图&代码：
![页面重新链接](https://user-images.githubusercontent.com/24838332/135239803-b8dc1111-edbb-416b-a180-1a2491c07458.png)
![dockerfile](https://user-images.githubusercontent.com/24838332/135239818-c6fa0308-0bc0-4426-99ba-5d48325bb280.png)
![日志](https://user-images.githubusercontent.com/24838332/135239834-f17c9a52-6515-4a92-a33e-bef4a5f296fd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ma19881117** [comment]
ingress 需要增加websocket的配置：

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $APP_NAME-ingress
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: $APP_NAME-ws-service

**Comment by wanghh2000** [comment]
部署在k8s环境中, mariadb, redist, 后台都可以正常工作，但是前端页面一下打不。
