### ISSUE TITLE
【Gateway问题】后端请求地址不正常

### ISSUE THREAD

**Issue by february** [jeecgboot/jeecg-boot#3078]
##### 版本号：
V2.4.6

##### 问题描述：
我在微服务模式上进行测试，发现一个问题。想请教一下。
以获取登录图形验证码场景来说，通常情况，前端向后端请求数据时，是以下形式：
`http://xxxx/api/sys/randomImage/1632909295368?_t=1632909295（注解：URL中的"api"是我在nginx中做的代理）`
通常情况，以上url是可以正常访问的，但是也有的时候突然就不行了。
我自己调查过，当不能访问的时候，是可以用以下形式访问的：
`http://xxx/api/jeecg-system/sys/randomImage/1632909295368?_t=1632909295（注意：在url中多了“jeecg-system”部分）`

发生这种情况我只能通过重新导入nacos库的数据并重启框架才能恢复正常。
我感觉应该是我的某个参数没有配置正确导致的这个现象，但实在是找不到问题所在了，所以才来请教一下各位老师：
我究竟该修改哪里的参数才可以解决这个现象呢？
谢谢！

##### 截图&代码：

![1632913300(1)](https://user-images.githubusercontent.com/259431/135256196-ee02cfd0-2c35-48db-992e-f50ad49a3621.png)

**Comment by zhangdaiscott** [comment]
你改naocs了？

**Comment by february** [comment]
没改nacos。

**Comment by february** [comment]
通过反复实验，我大概知道是哪里的问题了。
事情的起因是，因为我的后台服务做了nginx代理，即在请求地址前加了/api。
但是这就会造成一个问题，框架内置的积木报表设计就会显示不正常。
![1632976634(1)](https://user-images.githubusercontent.com/259431/135388158-cefdd2cb-f7eb-4599-a8df-ddf96aa63e7b.png)
为了解决这个问题，我在配置文件中加了这个配置。
![1632976601(1)](https://user-images.githubusercontent.com/259431/135388186-86eb80e0-5bff-4dc1-ac9b-84206d4c58a4.png)
在nacos动态加了这个配置之后（没用重启框架），积木报表设计就显示正常了。
但是等下次框架重启启动之后，就会发生最一开始所提到的那个问题。

**Comment by february** [comment]
> 通过反复实验，我大概知道是哪里的问题了。 事情的起因是，因为我的后台服务做了nginx代理，即在请求地址前加了/api。 但是这就会造成一个问题，框架内置的积木报表设计就会显示不正常。 ![1632976634(1)](https://user-images.githubusercontent.com/259431/135388158-cefdd2cb-f7eb-4599-a8df-ddf96aa63e7b.png) 为了解决这个问题，我在配置文件中加了这个配置。 ![1632976601(1)](https://user-images.githubusercontent.com/259431/135388186-86eb80e0-5bff-4dc1-ac9b-84206d4c58a4.png) 在nacos动态加了这个配置之后（没用重启框架），积木报表设计就显示正常了。 但是等下次框架重启启动之后，就会发生最一开始所提到的那个问题。

可能还不是这个原因。我这边又再现这个问题了。

**Comment by zhangdaiscott** [comment]
积木前缀不好使吗
