### ISSUE TITLE
大佬，我又来了，有个问题。ERP风格生成代码后，列表-->更多-->详情没有自动生成。自己加代码，效果却为编辑页面，不是可读页面

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#3079]
##### 版本号：
2.4.6

##### 问题描述：
大佬，我又来了，有个问题。ERP风格生成代码后，列表-->更多-->详情没有自动生成。自己加代码，效果却为编辑页面，不是可读页面.截图是加的代码和页面效果

##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/135408562-aeab0186-18a2-41a4-bf43-38f0d92f6852.png)
![image](https://user-images.githubusercontent.com/86937081/135408656-2a527db1-ab89-488c-b506-7fea5597afdc.png)
![image](https://user-images.githubusercontent.com/86937081/135408844-78c1e91b-cb3a-4203-ab5d-336b789e0639.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己参考示例改，模板都可以自定义，这种问题不做修复了
