### ISSUE TITLE
Online 报表自定义分页参数

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#3083]
##### 版本号：
v2.4.6

##### 问题描述：
Online 报表如何自定义修改分页参数？ 现在都是默认每个 10 条，现在我们业务上要求改完每页 30 条，我发现没法修改，但是我很多统计报表都是直接用 Online 报表做好了功能，没道理为了修改每页数量我重新写一套代码吧？ 事情比较紧急，麻烦帮忙解答一下，万分感谢~ @zhangdaiscott 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持自定义
