### ISSUE TITLE
online表单开发，内嵌子表没有级联link_down，内嵌子表无法配置级联

### ISSUE THREAD

**Issue by enterprising666** [jeecgboot/jeecg-boot#3087]
##### 版本号：
新版依然存在

##### 问题描述：
online表单开发，内嵌子表没有级联link_down，内嵌子表无法配置级联

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by enterprising666** [comment]
请注意：不是生成的代码

**Comment by zhangdaiscott** [comment]
不支持
