### ISSUE TITLE
大佬！求助！JS增强不能用！见截图！

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#3103]
##### 问题描述：
大佬！求助！JS增强不能用！见截图！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/137235205-9b3ed380-603f-4e2c-8b9b-edf7806404f3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪应该是你自己升级出了问题，你可以跑下最新版本试试
