### ISSUE TITLE
跨域问题咨询

### ISSUE THREAD

**Issue by iwen-git** [jeecgboot/jeecg-boot#3109]
##### 版本号：
2.4

##### 问题描述：
你好，如果shiro放开了部分请求路径的请求，那么这些请求不会走jwtfilter的prehHandle方法设置跨域参数，如何让shiro放开的那些路径也走跨域配置呢，发现放开的路径请求都不支持跨域。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by iwen-git** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
org.jeecg.config.shiro.filters.JwtFilter  里面的跨域代码注释掉
直接用org.jeecg.config.WebMvcConfiguration的跨域设置
`@Conditional(CorsFilterCondition.class)` 注释这段代码
