### ISSUE TITLE
部门管理的缓存不生效

### ISSUE THREAD

**Issue by Apiee** [jeecgboot/jeecg-boot#3113]
##### 版本号：
2.4.5

##### 问题描述：
部署到线上 部门管理的缓存没写进reids 不知道为啥
在自己的电脑是可以写进去的
![image](https://user-images.githubusercontent.com/24862113/137876305-a84b9b57-bc8f-4498-adef-d12517996fc6.png)
![image](https://user-images.githubusercontent.com/24862113/137876391-74415624-a771-4548-9c26-6173c29d25c2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种问题无法解决，自己排查吧
