### ISSUE TITLE
JEditableTable单元格溢出鼠标停留不显示文本

### ISSUE THREAD

**Issue by 0xCoding** [jeecgboot/jeecg-boot#3114]
##### 版本号：
Version: 2.4.2

##### 问题描述：
JEditableTable当单元格内容过长不能全部显示时，鼠标停留到单元格表单没有显示内容，类似title属性

##### 截图&代码：

![image](https://user-images.githubusercontent.com/61595017/137885034-474fa972-926a-4130-9cc6-b4556f072b01.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
无此功能
