### ISSUE TITLE
@CacheEable在哪配置了存到reids里面的

### ISSUE THREAD

**Issue by Apiee** [jeecgboot/jeecg-boot#3116]
##### 版本号：
2.4.5

##### 问题描述：
请问一下 这个框架 的@CacheEable 是在哪定义了存储位置呢 我在配置文件 没找到spirng.cache.type=redis这个选项

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个百度吧，springboot默认
