### ISSUE TITLE
jeecgboot 如何脱离主体 单独开发boot项目 单独测试 然后集成到主体

### ISSUE THREAD

**Issue by anzhaowang** [jeecgboot/jeecg-boot#3120]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2194069
微服务模式可以
