### ISSUE TITLE
jeecg.path.webapp配置无效

### ISSUE THREAD

**Issue by timfengzi** [jeecgboot/jeecg-boot#3126]
##### 版本号：
2.4.6

##### 问题描述：
jeecg.path.webapp配置无效，返回404。2.4.5版本是可以的，而且upload的路径也可以，就是webapp不行。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
你想通过这个配置达到什么目的？

**Comment by timfengzi** [comment]
还是不行，我是直接拉git的代码的，upLoadPath这个即使不设置WebMvcConfiguration也能访问，webAppPath怎么设置都不行，所以应该哪里冲突了，改了addResourceHandler("/**")这个就可以。

**Comment by tygithub1** [comment]
你重新打包了吗

**Comment by timfengzi** [comment]
重新打包也是不行

**Comment by timfengzi** [comment]
![image](https://user-images.githubusercontent.com/8926448/142169452-05f69291-4e58-45ab-8ab8-a8ccde125262.png)

**Comment by timfengzi** [comment]
spring-boot-starter-jimureport这个包覆盖了

**Comment by zhangdaiscott** [comment]
已经修复了，下个版本发布
