### ISSUE TITLE
微服务环境下访问积木报表的预览页面显示空白

### ISSUE THREAD

**Issue by exceedinglySad** [jeecgboot/jeecg-boot#3140]
##### 版本号：
V3.0

##### 问题描述：
积木报表页面使用图形报表，再图形报表设计页面设置两个数据集，将两个数据集结果拖拽到页面，点击预览。无法显示数据
但是如果直接跳过微服务直接访问积木报表，则可以正常显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/70218047/139625704-c944c617-513c-40fe-acb9-a239120e5564.png)
后台报错：
![image](https://user-images.githubusercontent.com/70218047/139625739-aa58a68b-faa5-4801-9ec1-7cb5ea24312f.png)
使用系统服务的端口号，显示正常：
![image](https://user-images.githubusercontent.com/70218047/139625823-9a769060-4d96-454b-b39c-9ae9d004623a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://report.jeecg.com/2506684
