### ISSUE TITLE
平台积木报表多租户问题咨询

### ISSUE THREAD

**Issue by exceedinglySad** [jeecgboot/jeecg-boot#3141]
##### 版本号：
V3.0

##### 问题描述：
新版的Jeecg-boot平台是否支持积木报表的多租户模式，如果支持如何修改积木报表的实体类？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
暂时不支持
