### ISSUE TITLE
v3.0 前端 关于页面 文档地址错误

### ISSUE THREAD

**Issue by 098018** [jeecgboot/jeecg-boot#3143]
##### 问题描述：
v3.0 前端 关于页面 文档地址错误，vue3.doc.jeecg.com 应为 vue3.jeecg.com

##### 截图&代码：
![image](https://user-images.githubusercontent.com/61051793/139643759-9000c8b1-ce19-4e0c-8eb2-4d4f25c340df.png)

sys/about/index

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已修复
