### ISSUE TITLE
请问如何连接“人大金仓数据库”呢？

### ISSUE THREAD

**Issue by yijian0645** [jeecgboot/jeecg-boot#3145]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/14273752/139666443-626cea32-575d-4d89-bb16-e0ac7af6874f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
驱动包得自己加

**Comment by yijian0645** [comment]
> 驱动包得自己加

我知道啊，我在项目里已经添加依赖的驱动jar包了啊，可是启动还是报这个错误。。。这是怎么回事呢？

我是在后端项目的每个module都引入这个驱动jar包了
