### ISSUE TITLE
地址获取到多个地址， 地址过长导致权限菜单修改失败

### ISSUE THREAD

**Issue by zhongjunwang** [jeecgboot/jeecg-boot#3148]
##### 问题描述：
![image](https://user-images.githubusercontent.com/90086254/139804384-b09dabc5-94cc-4f5e-b682-cc058a1de5a1.png)
![image](https://user-images.githubusercontent.com/90086254/139804433-8e6791c4-96ed-4c0a-8efc-7d1dc1a9688f.png)
![image](https://user-images.githubusercontent.com/90086254/139806691-428cab5e-6eda-4567-9aee-5481f036ccb5.png)

需要把ip字段弄大点

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪个表，日志截全了

**Comment by zhongjunwang** [comment]
![image](https://user-images.githubusercontent.com/90086254/140676626-a975da1e-24bc-4e27-89fa-58203a8266c6.png)
@

**Comment by zhongjunwang** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
哪你先自己改下长度即可
