### ISSUE TITLE
jeecgboot 微服务版本如何更改项目名称和包路径

### ISSUE THREAD

**Issue by anzhaowang** [jeecgboot/jeecg-boot#3151]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
包路径保留jeecg的配置，剩下自己随便改

**Comment by anzhaowang** [comment]
请问可以说的详细一下吗，包路径保留jeecg的配置是什么意思，有点不太理解，谢谢

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=lrec_anzw&uid=lrec_anzw%40lenovo.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fsm5f370bd8f9c04ad4450ffd3e1ff14ed7.jpg&items=%5B%22lrec_anzw%40lenovo.com%22%5D&logoUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyeicon%2F7a7d4dc495fa2b9c5f65ca19e32e9e80.png>
[https://mail-online.nosdn.127.net/sm5f370bd8f9c04ad4450ffd3e1ff14ed7.jpg]
lrec_anzw
        [https://mail-online.nosdn.127.net/qiyelogo/7a7d4dc495fa2b9c5f65ca19e32e9e80.png]
***@***.***

签名由网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81>定制
在2021年11月3日 ***@***.******@***.***> 写道：

包路径保留jeecg的配置，剩下自己随便改

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeecgboot%2Fjeecg-boot%2Fissues%2F3151%23issuecomment-958971571&data=04%7C01%7Clrec_anzw%40lenovo.com%7C48cbced2df12421b3a0108d99ec316e3%7C5c7d0b28bdf8410caa934df372b16203%7C1%7C0%7C637715383004041143%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nBtHSoXds04pga%2Fo6AW%2FoFnsSEwEhecoo6x8Le8TjCI%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWCF5QDDXHYVAF5OTSBM5G3UKERHTANCNFSM5HH2LJVQ&data=04%7C01%7Clrec_anzw%40lenovo.com%7C48cbced2df12421b3a0108d99ec316e3%7C5c7d0b28bdf8410caa934df372b16203%7C1%7C0%7C637715383004051139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Siy0yNDESGW0cI43YH4BELJLQbNiobBdftVS8GXoXcQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clrec_anzw%40lenovo.com%7C48cbced2df12421b3a0108d99ec316e3%7C5c7d0b28bdf8410caa934df372b16203%7C1%7C0%7C637715383004051139%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b77n1M5EzH9h4ftLjIHRgNhjCtL%2FU8eY5ZoLPVkadOY%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clrec_anzw%40lenovo.com%7C48cbced2df12421b3a0108d99ec316e3%7C5c7d0b28bdf8410caa934df372b16203%7C1%7C0%7C637715383004061131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VrbD1jrKyMT9xZRcss0MpIqxDaCEipyMGPt5v6okMlI%3D&reserved=0>.
