### ISSUE TITLE
vue3演示环境无法登录？

### ISSUE THREAD

**Issue by Forevery1** [jeecgboot/jeecg-boot#3152]
##### 问题描述：
无法登录

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19872771/140007180-2a4c0e35-6f11-4fc2-aeec-358476925e6a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没问题
