### ISSUE TITLE
在线表单的href跳转不能进行筛选

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3154]
##### 版本号：
3.0.0

##### 问题描述：
在线表单的href跳转不能进行筛选
![image](https://user-images.githubusercontent.com/29143702/140012583-5ace23b7-af1d-4a7d-9cbe-7e5a25104a0c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没这功能吧

**Comment by lexmarn001** [comment]
这个功能。


http://doc.jeecg.com/2044135










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在线表单的href跳转不能进行筛选 (Issue #3154)





 
没这功能吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tygithub1** [comment]
普通列表没问题，erp风格有bug，已修复!

**Comment by lexmarn001** [comment]
需要更新什么？还是等下一个版本？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月16日(周二) 下午3:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 在线表单的href跳转不能进行筛选 (Issue #3154)




 
Closed #3154.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
按照截图升级
![image](https://user-images.githubusercontent.com/3162115/142093248-99367e40-94ae-490d-8e9b-4f047fc560d8.png)
