### ISSUE TITLE
在线标的时间格式化不起作用，中间多了T

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3155]
##### 版本号：
3.0

##### 问题描述：
在线标的时间格式化不起作用，中间多了T
![image](https://user-images.githubusercontent.com/29143702/140012704-a8e94549-856e-4fc3-9b8a-3e77ddcb779c.png)

![image](https://user-images.githubusercontent.com/29143702/140012749-29795a0a-30c9-4671-a82f-e22b82b4be24.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么数据库？具体怎么用的

**Comment by lexmarn001** [comment]
mysql 8.0.20


就是正常的建表&nbsp;

库中数据也正常













&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月3日(星期三) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 在线标的时间格式化不起作用，中间多了T (Issue #3155)





 
什么数据库？具体怎么用的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lexmarn001** [comment]
![image](https://user-images.githubusercontent.com/29143702/140022958-5b1b35da-2909-4f3e-97dc-da51cf988559.png)
![image](https://user-images.githubusercontent.com/29143702/140022973-ace18e09-c8e2-4963-868b-afd6e84b65a2.png)
![image](https://user-images.githubusercontent.com/29143702/140022989-cdd4b6a5-ff36-4fb1-b83f-26f499d0d6b5.png)
![image](https://user-images.githubusercontent.com/29143702/140022997-31710428-ad12-4589-bd54-ca692d5effdd.png)

**Comment by lvdandan16** [comment]
是online在线表单吗

**Comment by lexmarn001** [comment]
是的，在线表单



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月3日(周三) 下午4:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 在线标的时间格式化不起作用，中间多了T (Issue #3155)




 
是online在线表单吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvdandan16** [comment]
我们未测试此问题，应该是你本地数据库的问题
