### ISSUE TITLE
请问对于excel交叉表单导入数据应该怎么处理？

### ISSUE THREAD

**Issue by suthaohaoxuexi** [jeecgboot/jeecg-boot#3157]
##### 版本号：
jeecg-boot 2.2

##### 问题描述：
请问对于excel交叉表单导入数据应该怎么处理？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/21076655/140034979-b4311143-c119-48d4-84c6-7ba17117981a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
手工编码
