### ISSUE TITLE
参照JeecgBoot单体升级微服务启动，无法显示登陆验证码，请求返回404

### ISSUE THREAD

**Issue by firebear-ssl** [jeecgboot/jeecg-boot#3158]
##### 问题描述：
参照JeecgBoot单体升级微服务启动，无法显示登陆验证码，请求返回404

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/22034607/140094163-9d022feb-ac3a-40fc-86d9-e99170505390.png)
![图片](https://user-images.githubusercontent.com/22034607/140094271-0593e088-f795-4856-b4da-94c6e609d8f3.png)
![图片](https://user-images.githubusercontent.com/22034607/140094355-2b4390b0-db2d-41ca-95dc-142638588514.png)
![图片](https://user-images.githubusercontent.com/22034607/140094418-d7ea7388-fde2-41c1-b7e4-0f2663a88cf3.png)

#### 友情提示（为了提高issue处理效率）：
[参照JeecgBoot单体升级微服务启动，无法显示登陆验证码，请求返回404，所有都是按着
[【JeecgBoot单体升级微服务启动】](http://doc.jeecg.com/2043906#host_23)
写的进行了配置，启动也都是正常，没有报错误。但是最终就是这样一个情况，登陆验证码出不来。
重新下载GIT两次，结果都是这样，请指导一下，差什么了。
  
http://doc.jeecg.com/2043906#host_23

**Comment by zhangdaiscott** [comment]
后台接口地址配置的对吗
