### ISSUE TITLE
自定义树控件只显示父节点，子节点无法展开

### ISSUE THREAD

**Issue by 1060724215** [jeecgboot/jeecg-boot#3159]
##### 问题描述：
按文档说明添加单表的自定义树控件，自定义树控件只显示父节点，点击子节点无法展开，
使用源码自带的ces_shop_goods和ces_shop_type两表测试，新增商品选择商品类别，点击子节点也无法展开

##### 截图&代码：

![image](https://user-images.githubusercontent.com/30305102/140255208-ccbb61b7-76bf-4628-a52d-1ee6bbd9f5ad.png)
![image](https://user-images.githubusercontent.com/30305102/140255391-3799cfab-a603-4de2-af12-0c0f043fa5c8.png)
![image](https://user-images.githubusercontent.com/30305102/140255449-56659abd-12f3-4f51-8f70-695848629142.png)

**Comment by 1060724215** [comment]
![image](https://user-images.githubusercontent.com/30305102/140692065-a78f3fc1-30c6-4ca3-a0e9-3cde98ac68f1.png)
AUTO在线表单，自定义树控件的功能测试，查询出来，衣服的leaf为false没有子节点，鞋子的leaf为true有子节点，渲染出来缺是衣服有子节点，鞋子没有，会不会是控件里判断是否有子节点的判断条件写反了？

**Comment by tygithub1** [comment]
已修复
