### ISSUE TITLE
online 报表 bug

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#3162]
##### 问题描述：
online报表有多次请求的问题，一般2次，甚至3次、4次，造成影响：
1）增加服务器压力；
2）用户在已查询的数据操作时，下一次的响应过来，会造成页面刷新；
3）用户打开新的online查询后，上一报表的下一次的响应过来，会造成数据显示上一个查询的数据；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/140276623-73e764eb-39f7-48c4-aa3e-7afb60f663db.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已修复
