### ISSUE TITLE
online 在线开发 保存明细数据报错

### ISSUE THREAD

**Issue by jmuchch** [jeecgboot/jeecg-boot#3165]
##### 问题描述：
org.springframework.dao.DataIntegrityViolationException: 
### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1636010822000' for column 'create_time' at row 1
; Data truncation: Incorrect datetime value: '1636010822000' for column 'create_time' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1636010822000' for column 'create_time' at row 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)

com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1636010822000' for column 'create_time' at row 1

mysql 版本5.7

祥见图

##### 截图&代码：
![bug issue](https://user-images.githubusercontent.com/26559599/140444295-95a3a2e9-c0b5-4063-a21e-dc84d972847d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jmuchch** [comment]
![image](https://user-images.githubusercontent.com/26559599/140446403-34df3abd-f6bb-4f0d-a779-902c78adca1f.png)

**Comment by zhangdaiscott** [comment]
此问题早修复了，更新代码
