### ISSUE TITLE
最新版本源码拉下来 nacos 启动后，在nacos 后台无法编辑配置？？？  新增和sql初始化进去的配置都无法编辑？

### ISSUE THREAD

**Issue by BruceOuyang** [jeecgboot/jeecg-boot#3166]
##### 版本号：
3.0

##### 问题描述：
源码拉下来 nacos 启动后，在nacos 后台无法编辑配置？？？  新增和sql初始化进去的配置都无法编辑？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/5382942/140470052-86dff76f-66d8-45d6-bae5-2e42a7562888.png)

**Comment by zhangdaiscott** [comment]
?

**Comment by zhangdaiscott** [comment]
长期无回复关闭
