### ISSUE TITLE
配置外部菜单时出现frame because it set 'X-Frame-Options' to 'sameorigin'.问题

### ISSUE THREAD

**Issue by suthaohaoxuexi** [jeecgboot/jeecg-boot#3167]
##### 版本号：
2.2

##### 问题描述：
配置外部菜单为百度时，页面会报错，后台出现frame because it set 'X-Frame-Options' to 'sameorigin'.问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/21076655/140472704-7e38ed99-ab86-45be-a12a-229a9ff16e48.png)
![image](https://user-images.githubusercontent.com/21076655/140472732-abb2594d-7ec6-45f0-9fae-e5e1631cb200.png)
![image](https://user-images.githubusercontent.com/21076655/140472760-9c46e520-4617-4f00-9729-86549fede629.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
参考常用示例里面的配置

**Comment by suthaohaoxuexi** [comment]
能提供一下相关地址嘛？我是按照开发文档配置的  可是出现了这个问题
