### ISSUE TITLE
online报表配置不能支持分类字典的转换功能

### ISSUE THREAD

**Issue by yanchenchen** [jeecgboot/jeecg-boot#3169]
##### 版本号：

3.0
##### 问题描述：

某个表单使用联动组件，关联分类字典
通过online报表配置该表单，查询出来的字符串显示的是分类字典中某项的id，而不是对应该id的文本。
注意到，online报表配置支持 数据字典的转换功能。

##### 截图&代码：
如下图，红色方框中显示的是分类字典项的id，而不是文本（希望的效果是显示黄色区域内的文本）
![image](https://user-images.githubusercontent.com/8335270/140493395-363b1d99-f392-48fd-a82f-322e7579a564.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by tygithub1** [comment]
online表单配置的联动组件和online报表配置没有关系，这完全是两个菜单下的两个功能。
需要在报表里作字典翻译，请参考报表中字典使用的文档： http://doc.jeecg.com/2044156

**Comment by yanchenchen** [comment]
在报表里作字典翻译只支持数据字典，不支持分类字典。
我的问题online表单中使用了分类字典做联动，用online报表配置查询出来的分类字典没有进行翻译。
