### ISSUE TITLE
富文本框JEditor，属性设置下拉选层级显示

### ISSUE THREAD

**Issue by RedSuper** [jeecgboot/jeecg-boot#3170]
##### 问题描述：
富文本框JEditor，表格属性设置等，右键弹出设置下拉选，层级显示均有问题。看图片

此问题在官方的网站也能复现。
http://boot.jeecg.com/modules/message/sysMessageTemplateList

##### 截图&代码：
![image](https://user-images.githubusercontent.com/11624856/140495883-6aa28337-db78-4837-99d8-f9410f41b9ab.png)

**Comment by tygithub1** [comment]
修改package.json:
```
    "tinymce": "5.4.1",
```
