### ISSUE TITLE
请问我在2.4.6版本上已经做了功能开发，不想升级到3.0，但是现在有一个问题，点击JS增强报错，我该怎么更新才可以解决

### ISSUE THREAD

**Issue by jeffZbj** [jeecgboot/jeecg-boot#3171]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/86937081/140633780-faba692d-178f-473c-b0be-271233b9731b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以尝试只升级online相关模块依赖，前端package,json和后端jar,和对应升级sql
