### ISSUE TITLE
消息通知不是实时推送的么？

### ISSUE THREAD

**Issue by whg7251** [jeecgboot/jeecg-boot#3172]
##### 版本号：

2.4.6
##### 问题描述：
消息通知不是实时推送的么？我看了一下请求的接口时http接口

`http://localhost:9999/sys/annountCement/listByUser`，每次登陆请求一次。
可是如果登陆期间不刷新页面，新消息就不会推送给该页面。
请问目前这个功能就是这么设计的么？如果想实现我的需求应该怎么改造呢？谢谢大佬

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49737277/140715541-3dbc32ad-9087-49ba-9cd2-ce8518d6e8b3.png)
![image](https://user-images.githubusercontent.com/49737277/140715668-8abe36dd-1172-47e3-9c06-a94dfd2dc516.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by whg7251** [comment]
我看了一下代码，后端在发送系统通知的时候，已经通过websocket发送给前端数据了
![image](https://user-images.githubusercontent.com/49737277/140873510-5eeba171-38b7-4bf9-a22e-2811d3b3aa53.png)
，但是前端原始代码没有实时更新

**Comment by zhangdaiscott** [comment]
不刷新页面也有提醒，websocket

**Comment by zhangdaiscott** [comment]
看下日志 ，确认下websocket通信是否成功

**Comment by whg7251** [comment]
好的，谢谢了
