### ISSUE TITLE
JEditableTable可编辑表格能否支持前几列固定

### ISSUE THREAD

**Issue by rareloved** [jeecgboot/jeecg-boot#3174]
##### 版本号：
2.4.5

##### 问题描述：
可编辑表格控件，在子表录入时，需要录入信息特别长时，需要拖动滚动条，想着要是首列或首两列能固定住，后边录入时
不容易串行。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没实现这个功能
