### ISSUE TITLE
在线开发编辑时，表字段展示不全，且无法保存新增字段

### ISSUE THREAD

**Issue by Rewivy** [jeecgboot/jeecg-boot#3175]
##### 截图&代码：

接口显示返回数据有16条，但页面展示只有15条
![image](https://user-images.githubusercontent.com/48473052/141038514-110cacc1-bfa5-4f33-a7c1-4430894c27b4.png)

点击新增按钮后出现第16条数据
![image](https://user-images.githubusercontent.com/48473052/141038547-18f823ff-dda3-4b33-a2eb-a0216d1a9038.png)

再点新增后才可以增加字段，但这时的数据点保存后一直停留在原界面，无法保存
![企业微信截图_16365109162087](https://user-images.githubusercontent.com/48473052/141038679-63d378dd-3421-466d-b1c9-b3d3181b4ea5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么浏览器

**Comment by Rewivy** [comment]
谷歌浏览器

**Comment by Rewivy** [comment]
> 什么浏览器

谷歌浏览器

**Comment by zhangdaiscott** [comment]
你手工升级到我们最新版看看
