### ISSUE TITLE
通知公告——模板管理、消息管理页面功能设计的意义是啥

### ISSUE THREAD

**Issue by whg7251** [jeecgboot/jeecg-boot#3176]
##### 版本号：
2.4.6

##### 问题描述：

请问，模板编辑完后，发送测试，相关消息是会插入到sys_sms表中

1. 在消息管理里面为什么只会展示一条简单的数据呢？
2. 发送的次数和状态为什么设计成了0次和未发送？
3. 点击详情后也展示不出相关的通知，只有html的一堆标签，是现在功能没完善么？
4. 系统通告表、用户通告阅读标记表与sys_sms的关系是什么呢？感觉目前没有实际的关系
5. 当初设计模板管理和消息管理的目的是什么呢？文档里也没有详细的说明，多谢了大佬了，麻烦了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49737277/141041977-4173de51-212c-4970-9a0c-7a0c9eac395d.png)
![image](https://user-images.githubusercontent.com/49737277/141042068-d32792b6-c13b-4c06-b318-d4392f7b3861.png)
![image](https://user-images.githubusercontent.com/49737277/141042449-40d0fb1f-8614-4ec0-8a61-f34f9b3d1f23.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看文档了吗
http://doc.jeecg.com/2043950


消息管理没什么用，只是记录下推送的消息
