### ISSUE TITLE
yarn run build 打包问题

### ISSUE THREAD

**Issue by hualinglin** [jeecgboot/jeecg-boot#3178]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/42462340/141078888-f8b40df3-f578-400a-862a-7aba3284f8c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by hualinglin** [comment]
依赖删掉重新build 也一直还出现这样的问题 ，直接本地运行是正常的 就打包会出现问题

**Comment by zhangdaiscott** [comment]
警告忽略就行

**Comment by hualinglin** [comment]
![image](https://user-images.githubusercontent.com/42462340/141086147-b42a8f50-99c0-4cf0-a928-3546c1ce1bc9.png)

**Comment by hualinglin** [comment]
> 警告忽略就行

![image](https://user-images.githubusercontent.com/42462340/141086236-9f9dc004-00e4-48d5-8e5d-07e3c08b4915.png)
但是打包之后 进不去页面呢
