### ISSUE TITLE
src/components/menu/index.js里select事件未触发

### ISSUE THREAD

**Issue by ZhouNick** [jeecgboot/jeecg-boot#3184]
##### 版本号：
2.4.6

##### 问题描述：
在src/components/menu/index.js里，绑定了select和openChange事件，菜单选中，应该触发的select事件没有触发，我直接改成onSelect也不行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22462099/141749610-71d65598-9520-4940-9e1a-aaa772c1b350.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是要做什么，代码阅读问题最好自己解决

**Comment by sjlei** [comment]
可以用 click 事件替代
