### ISSUE TITLE
v-charts封装的组件如何修改配置项

### ISSUE THREAD

**Issue by yanyan965914478** [jeecgboot/jeecg-boot#3188]
##### 版本号：
2.4.6
##### 问题描述：
v-charts封装的组件如何修改配置项 如何设置配置项，就比如饼状图我想设置legend显示数量限制
##### 截图&代码：
![$3OABXLBMG$A~C08LDQ GXT](https://user-images.githubusercontent.com/52962001/142128076-b2e62888-c486-4ac7-9370-2706a5e12d94.png)

**Comment by zhangdaiscott** [comment]
二开的问题自己解决
