### ISSUE TITLE
antd-online-mini online表单开发组件 url 不支持自定义context-path

### ISSUE THREAD

**Issue by beyondiary** [jeecgboot/jeecg-boot#3189]
##### 版本号：

当前最新版本： 2.4.6（发布日期：20210816）

##### 问题描述：

我修改后台服务端的uri context-path，同时修改了前段的请求相关参数配置。

登录 和其他的列表页面正常，online表单和一些请求提示资源未找到  。
![image](https://user-images.githubusercontent.com/71167107/142128145-3deeaade-6f3c-4f86-8491-edf095b47a91.png)

 antd-online-mini online表单开发组件 url 不支持自定义context-path，希望可以支持下

##### 截图&代码：

server:
    port: 9000
    servlet:
        context-path: /zeus

![image](https://user-images.githubusercontent.com/71167107/142128480-78e8bf16-7bc5-494e-b3a5-73ebcb8725cc.png)

![image](https://user-images.githubusercontent.com/71167107/142128479-6c041a3d-1861-4525-8135-7f82a4e31072.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
直接配置域名就行， 不需要代理
![image](https://user-images.githubusercontent.com/3162115/142131757-a86555fb-3b01-4b5c-88b9-14dc7c4e5b18.png)
