### ISSUE TITLE
通过docker的方式部署，无法使用代码生成工具

### ISSUE THREAD

**Issue by linjie830914** [jeecgboot/jeecg-boot#3190]
##### 版本号：
3.0

##### 问题描述：
通过docker的方式部署，参考http://doc.jeecg.com/2043889
参考图一
可以访问系统，但是代码生成工具报错，
参考图二
有相关解决jar部署方式的说明，http://doc.jeecg.com/2043922
但是docker部署方式，里面的jeecg-boot-system容器用的是jeecg-cloud-system-start，里面依赖jeecg-boot-module-system,
没有办法按照说明进行问题处理

请协助反馈下解决思路吧，感谢

##### 截图&代码：
图一
![image](https://user-images.githubusercontent.com/7983557/142194698-7771bb26-0a26-48b2-b441-dcb405a8a0f9.png)

图二
![image](https://user-images.githubusercontent.com/7983557/142194812-2a023189-846d-4a44-b238-b5c0b70ee1ac.png)

图三
![image](https://user-images.githubusercontent.com/7983557/142194998-dd965305-37fe-4616-8745-34aef7c3fd1f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
一样的

**Comment by linjie830914** [comment]
能详细说明一下吗？
是把config放到 jeecg-cloud-system-start-3.0.jar的同目录下吗？
![image](https://user-images.githubusercontent.com/7983557/142348412-78620178-6dfa-4614-a941-df433e8b7b30.png)
