### ISSUE TITLE
咨询前端代码配置问题，.env.development中的VUE_APP_API_BASE_URL，是配置网关地址还是配置后台system模块的地址？

### ISSUE THREAD

**Issue by linjie830914** [jeecgboot/jeecg-boot#3192]
##### 版本号：
jeecg boot 3.0

##### 问题描述：
咨询前端代码配置问题，.env.development中的VUE_APP_API_BASE_URL，是配置网关地址还是配置后台system模块的地址？
参考图一

##### 截图&代码：
图一
![image](https://user-images.githubusercontent.com/7983557/142349316-ed272ef9-74f9-4084-822c-f1aaee3f6802.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
文档里不是写了吗
微服务情况下，配置网关

**Comment by linjie830914** [comment]
单体情况下，配置system那个地址吗？
