### ISSUE TITLE
前端代码中，Dockerfile里的proxy_pass配置的是jeecg-boot-system模块的访问地址吗？

### ISSUE THREAD

**Issue by linjie830914** [jeecgboot/jeecg-boot#3193]
##### 版本号：
JEECG BOOT 3.0

##### 问题描述：
前端代码中，Dockerfile里的proxy_pass配置的是jeecg-boot-system模块的访问地址吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7983557/142349591-2587fc88-f7b1-41b5-97bd-3ecc55ddf3e4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是单体模式吧

**Comment by linjie830914** [comment]
现在我是配置的单体模式，那应该配置那个地址？
