### ISSUE TITLE
返回的数据为String 字符串时默认会调用返回message的那个方法

### ISSUE THREAD

**Issue by mrdong916** [jeecgboot/jeecg-boot#3195]
##### 版本号：
3.0

##### 问题描述：
当返回的数据为String 字符串时，就会默认调用返回message的那个方法，而请求回来的数据就会变成下面的样子，其中`http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`是我要返回的字符串，建议优化一下这个地方

```
{"code":200,"message":"http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","success":true,"timestamp":1637235827888}
```

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20489554/142409997-2c6912eb-8b8a-479c-a6e9-229a42818b1b.png)

![image](https://user-images.githubusercontent.com/20489554/142409814-283975f1-d8d8-46e8-ad01-928d4180b60e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecg-boot/issues/I4IP3D
