### ISSUE TITLE
用户数据量较大时，功能测试报错

### ISSUE THREAD

**Issue by 915999136** [jeecgboot/jeecg-boot#3196]
##### 版本号：
2.4.6,3.0都有

##### 问题描述：
Online表单开发,当表单里使用了用户选择控件时，打开功能测试页面报错，用户表数据量7万左右
请求网址: http://localhost:9999/online/cgform/api/getColumns/18f064d1ef424c93ba7a16148851664f?_t=1637299508
访问超时，请稍后再试!

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59550516/142570792-4f0141bb-8c7d-4e36-9128-6b0127cd2206.png)

![image](https://user-images.githubusercontent.com/59550516/142570745-85b8bdda-1cd1-482f-9590-c4b143c56bc9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不分页？

**Comment by 915999136** [comment]
是选择用户的控件加载用户信息时执行了查询所以用户

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
使用的是这个组件吗，经查用户查询是分页查的，是不是部门数据量过大导致？

**Comment by 915999136** [comment]
从后台sql能看出，页面加载时就去取查询了所有用户信息，还没打开组件，就打开页面时就会等很久然后报错，删掉一半用户就能打开页面了，测试时oracle7万个用户

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/144536103-a6edb003-b429-497f-a71b-c7c515c48004.png)
用户是分页查询的 
左边部门树的加载是查询所有的数据，是不是你的部门也有很多，然后卡住了，
左边部门树 现已改成异步加载，等下个版本

**Comment by zhangdaiscott** [comment]
已经处理，请更新代码

**Comment by 915999136** [comment]
![image](https://user-images.githubusercontent.com/59550516/144780910-3bc49b4e-2133-43ce-88fa-8c223773453f.png)
为啥我这用户没分页......
