### ISSUE TITLE
在线表单编辑的时候在控制台有报错 You can use `getFieldDecorator(id, options)` 

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3198]
##### 版本号：
3.0

##### 问题描述：
在线表单编辑的时候在控制台有报错

You cannot set a form field before rendering a field associated with the value. You can use `getFieldDecorator(id, options)` instead `v-decorator="[id, options]"` to register it before render.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29143702/142748194-f3be1e24-309a-493f-a522-b0132d880df4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
警告忽略即可

**Comment by SunJary** [comment]
@zhangdaiscott 用的vue2版本，在线报表功能的报表SQL输入框无法用鼠标移动光标，特别是长sql，键盘左右键也无法移动光标。
只有input之后，内容发生改变了之后才能正常移动光标
报错内容跟这个一样：
`warning.js?d96e:34 Warning: You cannot set a form field before rendering a field associated with the value. You can use `getFieldDecorator(id, options)` instead `v-decorator="[id, options]"` to register it before render.`

这部分代码不是开源的，也没有办法修改，麻烦确认下是否有这个问题
