### ISSUE TITLE
建议添加飞书对接功能

### ISSUE THREAD

**Issue by liwanyin** [jeecgboot/jeecg-boot#3202]
##### 版本号：

2.4.6
##### 问题描述：
建议对接飞书的功能

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？

**Comment by liwanyin** [comment]
集成字节跳动的飞书的登录，飞书人员架构以及通知等功能

**Comment by zhangdaiscott** [comment]
收录到 https://github.com/jeecgboot/jeecg-boot/issues/1312
