### ISSUE TITLE
JSelectBizComponent columns 建议开放customRender等方法类配置

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/jeecg-boot#3203]
##### 版本号：
3.0

##### 问题描述：
JSelectBizComponent 中对columns深克隆时，使用util中的深克隆方法导致，columns 中自定义customRender等方法丢失，照成不能使用customRender修改列渲染！，是否可以考虑开放列的方法配置

      // 表头
      innerColumns() {
        let columns = cloneObject(this.columns)
        columns.forEach(column => {
          // 给所有的列加上过长裁剪
          if (this.ellipsisLength !== -1) {
            column.customRender = (text) => this.renderEllipsis(text)
          }
        })
        return columns
      },
    },

/**
 * 深度克隆对象、数组
 * @param obj 被克隆的对象
 * @return 克隆后的对象
 */
export function cloneObject(obj) {
  return JSON.parse(JSON.stringify(obj))
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布。

![image](https://user-images.githubusercontent.com/34293221/143806153-56fb5ba0-7362-45b4-9720-5e5dd496b49f.png)

> 注：如果使用了非文本形式的返回值，则需要自行处理过长裁剪。

![image](https://user-images.githubusercontent.com/34293221/143806138-f123bf61-8d9f-49aa-8ca0-8a6d98f708a7.png)

**Comment by zhangdaiscott** [comment]
代码已经上传，请更新
