### ISSUE TITLE
一个账户只能在一个客户端登录，目前可以多个客户端用同一个账户登录

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3205]
##### 版本号：
3.0.0

##### 问题描述：
目前发现一个admin账户可以通过多个客户端登录，这个限制哪里控制

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/142848861-be3ac633-f96a-4818-bab2-979a0c2822d4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
需要自己改造
