### ISSUE TITLE
关于上传文件（非图片）是否能保留显示文件或者预览

### ISSUE THREAD

**Issue by sunrisesong** [jeecgboot/jeecg-boot#3206]
##### 截图&代码：
上传时：
![QQ截图1](https://user-images.githubusercontent.com/94886768/142974379-9f7e2bf7-4eae-4ad3-b9dc-789feb59d5a6.png)

关闭弹框重开弹框：
![2](https://user-images.githubusercontent.com/94886768/142974426-1bb23598-0f2b-4dc2-995d-7a72b7df4006.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以自己改造
