### ISSUE TITLE
gateway的运行一段时间后，存在OutOfDirectMemoryError情况

### ISSUE THREAD

**Issue by 244707133** [jeecgboot/jeecg-boot#3209]
##### 问题描述：
gateway的运行一段时间后，存在OutOfDirectMemoryError情况

##### 截图&代码：

![COEVDYTFXZAEZG~16SIU~6Q](https://user-images.githubusercontent.com/54700030/143167779-2c3b1b7b-679a-40e9-aa60-5525dfe5984d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
找了几个博客，你可以自己尝试下

https://blog.csdn.net/LDY1016/article/details/120427354
http://www.manongjc.com/detail/19-pvvztizymdycwbx.html

**Comment by 244707133** [comment]
2.4.0后面的版本你们是不是改了gateway加载路由的方式。
