### ISSUE TITLE
jeecgboot 多租户版，在线开发，每次生成一张表，都需要手动去MybatisPlusSaasConfig添加相应表吗？

### ISSUE THREAD

**Issue by anzhaowang** [jeecgboot/jeecg-boot#3210]
##### 问题描述：
1. jeecgboot 多租户版，如果在线开发，每次生成一张表，都需要手动去MybatisPlusSaasConfig添加相应表吗？
2. 如果是这样对代码侵入性太高了，没法维护，有没有好的解决办法？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/92561088/143194615-5f4472ca-7660-410f-a749-b579a09c0f82.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
无
