### ISSUE TITLE
Online在线功能 子表视图XXX$1写JS增强后，JS增强无效

### ISSUE THREAD

**Issue by sunzhwei86** [jeecgboot/jeecg-boot#3212]
##### 版本号：
3.0.0

##### 问题描述：
Online在线功能 子表视图XXX$1写JS增强后，主表视图中所有的JS增强全部失效。
业务需要主表A和从表B，功能写好并JS增强后，Online功能正常，包括从改主事件可用，
需要多个前端入口，故给主表A复制了视图A$1，从表B复制了视图B$1，online功能界面正常，视图A$1中按钮事件也正常。

但子表视图B$1一写JS增强后，主表A$1所有的JS增强全部失效，包括按钮JS也失效，主表视图的JS未尝试

是否英文子表视图写onlChange时包含了特殊符号$？

按钮Online视图的逻辑，视图的表名还必须是业务表名$1/2/3等，视图名修改为其他后台逻辑均异常
去除$1，抛数组下标越界
去除1，保留$，如A$cont后，类型转换异常，无法生成新视图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53286757/143383989-a8a56be6-171d-4f61-86a6-bd4b0605a310.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by sunzhwei86** [comment]
请问是否有升级计划？
或者后续的版本将按照何种方式体现子表视图的JS增强？是将$替换成其他特殊符号，如#或@符号，还是其他方案？建议尽可能平滑升级后台逻辑。
若可以，建议生成视图时判断，遍历是否有视图数，直接主表名 拼接 特殊符号 拼接 count(视图数)+1
另，建议在online增加一个非必填的说明字段，用于描述业务表或视图的作用，毕竟以数字结尾，时间长了容易遗忘
ty

**Comment by tygithub1** [comment]
视图无主子表，只支持单表
