### ISSUE TITLE
页面右侧预留滑动条的空白，导致弹出/关闭表单时页面抖动

### ISSUE THREAD

**Issue by wxb2dyj** [jeecgboot/jeecg-boot#3213]
##### 版本号：
VUE3Beta版

##### 问题描述：
由于页面右侧预留滑动条的空白，导致弹出/关闭表单时页面抖动

##### 截图&代码：

打开表单前：
![1](https://user-images.githubusercontent.com/44050993/143397332-d949c1a2-77ea-4f4c-946a-bd34203abc37.png)

打开表单后：
![2](https://user-images.githubusercontent.com/44050993/143397366-bb4fdfaa-2605-42f1-99ad-d1b6a58f8e01.png)

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
什么浏览器

**Comment by SuperQjh** [comment]
怎么删除右侧的留白
