### ISSUE TITLE
@Dict字典表翻译用法

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3214]
##### 版本号：
3.0

##### 问题描述：
目前通过dicText，只能显示一个字段，如果想显示多个应该怎么配置

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/143419043-42a18bab-93ee-4831-864f-f58bb4900970.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by zjarlin** [comment]
https://www.bilibili.com/video/BV19m4y1673v/?spm_id_from=333.999.0.0

**Comment by zjarlin** [comment]
@zhangdaiscott 你看下我这个支持嵌套实体翻译,现在也支持可重复注解

**Comment by zhangdaiscott** [comment]
不是做不了，而且牺牲的性能太多，建议个性化自己搞

**Comment by zjarlin** [comment]
@zhangdaiscott 作者大大,还请再看下issue #4420,给个思路也行,或者有空在b站交流下,现在微服务的翻译只能手动set了,非常希望能实现微服务任意表的字典翻译
![image](https://user-images.githubusercontent.com/67467679/234749138-0d8c1811-b5fb-4b01-bff4-a925bbf87e37.png)

**Comment by zhangdaiscott** [comment]
你可以扩展下字典标签，加上一个参数 “数据源key”，查询数据的地方加上从不同数据源取数的逻辑
