### ISSUE TITLE
你好，目前开源版本代码里不包括服务器监控、JVM监控么？

### ISSUE THREAD

**Issue by whg7251** [jeecgboot/jeecg-boot#3216]
##### 版本号：
2.4.6

##### 问题描述：
你好，目前开源版本代码里不包括服务器监控、JVM监控么？没看到相关代码....
好像只实现了Redis监控和磁盘监控

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49737277/143549988-54506e5b-49ec-4b7a-8c0c-5ac43241528c.png)
![image](https://user-images.githubusercontent.com/49737277/143550041-299d65e3-4800-4787-84be-7fda331b8bc1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这springboot自带的功能
