### ISSUE TITLE
部署到服务器后，前端不显示内容，console报错 Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by kytieguo** [jeecgboot/jeecg-boot#3218]
##### 问题描述：
部署到服务器后，前端不显示内容，console报错Uncaught SyntaxError: Unexpected token '<'

##### 截图&代码：
![捕获](https://user-images.githubusercontent.com/55947403/143690471-aa456a56-b188-4854-986e-18f8603107b5.PNG)

![1](https://user-images.githubusercontent.com/55947403/143690475-950c9aad-c002-4a81-90b8-14908bb57474.PNG)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
删除，重新打包

**Comment by BIC20** [comment]
> 删除，重新打包

不行，我换了好几台电脑了 还是同样的问题

**Comment by zhangdaiscott** [comment]
应该是你部署有问题，具体自己排查下

**Comment by shellyaoo** [comment]
![1659545038511](https://user-images.githubusercontent.com/30407654/182663609-4d3ff334-584d-44ad-9cf7-13a4168be860.png)
wo我也遇到这个问题，请问怎么解决
