### ISSUE TITLE
字典值无法设置"_"

### ISSUE THREAD

**Issue by chrelyonly** [jeecgboot/jeecg-boot#3219]
##### 版本号：
jeecg3.0

##### 问题描述：
均是最新代码
1.字典值无法设置  _ 值  例如:    my_api   com_money_xx

##### 截图&代码：
本地
![image](https://user-images.githubusercontent.com/62467038/143805354-8081cf64-6092-4f0e-8ffc-4ee654e85377.png)
官网的
![image](https://user-images.githubusercontent.com/62467038/143805297-59840f5d-3edd-4f3d-8221-d655bf94a251.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
特意的设计，如果需要你可以自己改下校验规则，但可能会出现未知bug
