### ISSUE TITLE
平台切到移动端，列表页列表列表项展示不全，滚动条无法滚动，操作栏会挡住大部分屏幕内容

### ISSUE THREAD

**Issue by mzhiyo0815** [jeecgboot/jeecg-boot#3220]
##### 版本号：

3.0
##### 问题描述：

平台切到移动端，列表页列表列表项展示不全，滚动条无法滚动，操作栏会挡住大部分屏幕内容
##### 截图&代码：
![微信截图_20211129123046](https://user-images.githubusercontent.com/68221187/143809890-9495acb8-729e-4079-8c55-9f5a822ff392.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是那个功能

**Comment by mzhiyo0815** [comment]
所有列表页都有这个问题，官网的演示版本也有这个问题

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
经测试，用户列表等其他多个列表均无问题，移动端可滚动，也没有固定操作栏。请说明出问题的具体功能。
