### ISSUE TITLE
最新版本怎么支持hive

### ISSUE THREAD

**Issue by zombietramp** [jeecgboot/jeecg-boot#3221]
##### 截图&代码：
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1066758/143974411-e12ab7e1-e67e-4551-9702-37584979716f.png">

<img width="772" alt="image" src="https://user-images.githubusercontent.com/1066758/143974503-48e3aded-e797-48e7-9586-24f19a095dde.png">

**Comment by zombietramp** [comment]
已经解决

**Comment by laynelee28** [comment]
请问怎么解决的？怎么连接上hive？
