### ISSUE TITLE
反射型XSS漏洞

### ISSUE THREAD

**Issue by Tsuki124** [jeecgboot/jeecg-boot#3223]
##### 版本号：
3.0

##### 问题描述：
http://boot.jeecg.com:8080/jeecg-boot/jmreport/view/')%22onmouseover=alert('hacking')%20%20(

##### 截图&代码：
![image](https://user-images.githubusercontent.com/63626545/144021468-eedd94b9-694a-435d-8588-a747f3410ab2.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复

**Comment by assaf-benjosef** [comment]
hi, where was this vulnerability fixed? i can't find the commit. thanks! 🙏

**Comment by zhangdaiscott** [comment]
升级到最新版1.4.32

```
<dependency>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.4.32</version>
</dependency>
```
