### ISSUE TITLE
Excel导入问题

### ISSUE THREAD

**Issue by ghost5444** [jeecgboot/jeecg-boot#3224]
##### 版本号：
2.4.6

##### 问题描述：
Excel导入时,默认设置前两行为标题,第三行为列名
是否可更改为判断单元格是否合并,而决定是否将前两行设为标题行,
更灵活一点

##### 截图&代码：
ImportParams params = new ImportParams();
params.setTitleRows(2);
params.setHeadRows(1);
params.setNeedSave(true);

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个代码，可以自己改的
