### ISSUE TITLE
高级查询组件改造list页面方法之间屏蔽了之前的页面list

### ISSUE THREAD

**Issue by CZHR** [jeecgboot/jeecg-boot#3226]
##### 版本号：
 2.4.6

##### 问题描述：
您好，我使用了自定义组件中的 高级查询功能，按照开发文档当中进行配置，结果把我以前能够显示的页面list给全部屏蔽了，组件也无法正常使用，当我注释掉 改造list页面方法 之后 就能够正常显示，但是查询功能依然无法使用。感谢您的教导，感谢大佬帮助！！

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/51224420/144184679-6f960294-7cbd-4871-8f11-4752c00b4889.png)
![图片](https://user-images.githubusercontent.com/51224420/144184819-51acbfd2-d7c6-4795-8806-d044f3acd538.png)
![图片](https://user-images.githubusercontent.com/51224420/144184916-c9ce1d42-1084-41bf-918a-e13b3ec8fdaf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
参考我们的例子改把，你自己写的，我们无法分析
