### ISSUE TITLE
Online报表-导出的Excel单元格格式不支持数字类型和日期类型

### ISSUE THREAD

**Issue by xiny-cloud** [jeecgboot/jeecg-boot#3227]
##### 版本号：
前最新版本： 3.0（发布日期：2021-11-01）

##### 问题描述：
【在线开发】-【online报表配置】功能中，生成的报表导出后，excel中的数据类型全都为文本类型。
这样的话，无法对excel报表的数字列，和日期类型做统计或其他处理。
源码中似乎做了处理，但好像并没有生效。

建议：导出的Excel， 单元格格式是否可以支持 数字类型和日期类型（跟【动态报表配置明细】中的数据类型一致）。
 或者提供一个扩展点，供有需要的开发者自行实现呢？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50361224/144189347-6076d368-a277-402b-be7e-75015ff525ac.png)
![image](https://user-images.githubusercontent.com/50361224/144189438-2eedaa30-7bfb-435d-ad1a-b6059e205fec.png)
![image](https://user-images.githubusercontent.com/50361224/144189497-ff524b56-666c-4d07-b1af-7159ea9e2434.png)
![image](https://user-images.githubusercontent.com/50361224/144189661-444578a7-3b54-45a1-a104-30acf95492f3.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
数字类型已处理，下版本发布。
日期类型暂不支持。
