### ISSUE TITLE
Online报表-字典参数-高级用法(数据条数有误)

### ISSUE THREAD

**Issue by Jinyunpeng0903** [jeecgboot/jeecg-boot#3228]
##### 版本号：
jeecgboot：3.0

##### 问题描述：
Online报表-字典参数-高级用法(数据条数有误)，报表设置筛选参数下拉，配置的sql结果只有十条，表中数据大于10条

##### 截图&代码：

![image](https://user-images.githubusercontent.com/42921186/144350731-1aa48426-d9d8-4aa4-8835-e1571d2377a4.png)
![image](https://user-images.githubusercontent.com/42921186/144350768-ce9db42e-8d6f-4a69-a71e-684fc6fd888a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
默认下拉只展示10条，会根据你输入而变化。
一次性加载全部数据，系统会崩溃

**Comment by Jinyunpeng0903** [comment]
我怎么显示其他数据？
下滑，滑不动




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月3日(星期五) 晚上6:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] Online报表-字典参数-高级用法(数据条数有误) (Issue #3228)





 
默认下拉只展示10条，会根据你输入而变化。
 一次性加载全部数据，系统会崩溃
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
