### ISSUE TITLE
列表显示ID，和使用ID查询

### ISSUE THREAD

**Issue by helloobj** [jeecgboot/jeecg-boot#3229]
##### 版本号：
2.4.6

##### 问题描述：
请问为什么不能在列表显示ID， 和使用ID查询？

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/18436353/144389675-22b28ad5-f2dc-4692-879a-cdca3202bb52.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
倒是可以放开，意义大吗
