### ISSUE TITLE
【bug】角色管理分配授权菜单无法显示【已处理】

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/jeecg-boot#3230]
##### 版本号：
3.0

##### 问题描述：
分配角色权限，只要不全选，那该目录下所有菜单都出不来？
测试过，不/分配部门，不/分配部门权限，父子不/关联，等多种场景。
预期效果：
选择部分菜单，就可以看到部分菜单

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29787967/144390323-a0d61abf-0f9f-4173-9bd6-0a90a96ac04c.png)

## 已解决
图一，点击一下就可以
![image](https://user-images.githubusercontent.com/29787967/144397400-a2dde517-aee2-47d3-80c3-0bf00f059381.png)

图二，的父子联动就不行
![image](https://user-images.githubusercontent.com/29787967/144397598-b9a54330-a79e-4e3e-87a6-d005a4a096fe.png)

**Comment by huguojia** [comment]
@zhangdaiscott     JEECG-BOOT   3.2.0 版本还是存在这个问题  请问如何解决?
