### ISSUE TITLE
版本升级后菜单怎么乱了？

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#3231]
##### 版本号：
3.0

##### 问题描述：
菜单刚刷新的时候没问题！反复展开过几次就乱了！怎么回事呢？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/144394515-9e89f958-dae4-4916-b575-bb6e450a7af8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by JaneYork** [comment]
排序编号问题，如果没有填写默认为空，每次刷新，会随机

**Comment by tb2888** [comment]
> 
![image](https://user-images.githubusercontent.com/55084864/144400665-ddf60aff-e0ce-41fc-a0b2-41320a492d8d.png)
刚进系统是下图这样
![image](https://user-images.githubusercontent.com/55084864/144400804-c5a1afce-1b5c-48c5-8296-52a37b4cc33a.png)
一点下面那个菜单菜单名称就变了，也进入了上面那个菜单
![image](https://user-images.githubusercontent.com/55084864/144400894-974ca15c-7c2b-4adc-be05-41f941fd2cac.png)

**Comment by zhangdaiscott** [comment]
F12看有错没，我们本地无问题

**Comment by tb2888** [comment]
> F12看有错没，我们本地无问题

我把两个菜单都删了重新创建，重新授权又没问题了，开始从online表单开发那里点对应表的功能测试都会有问题！显示的数据是对的，就是菜单名乱了；比如说上面的图片我点击宿舍等级，结果菜单名字会变成员工培训，但是数据是宿舍登记的数据；
