### ISSUE TITLE
JS增强中获取用户名为空

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#3232]
##### 版本号：

3.0
##### 问题描述：

JS增强中使用that.$store.getters.username获取当前登录用户名，但是为空
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7098009/144447290-23812ccf-46bf-47f8-85eb-cea81f8853bd.png)
![image](https://user-images.githubusercontent.com/7098009/144447394-81694945-b552-44cc-b013-82f88e6da5ce.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布。
或者还可以使用  `that.$store.getters.userInfo.username` 来获取
