### ISSUE TITLE
war包部署无法获取tomcat信息

### ISSUE THREAD

**Issue by boluofan** [jeecgboot/jeecg-boot#3233]
##### 问题描述：项目部署时候，如果是war包部署，系统监控里的tomcat信息将无法获取
 是否是因为只做了jar包内嵌tomcat信息获取方式，war包移除了内嵌tomcat

##### 截图&代码：
![$_ Q71RZ@7JX%R0XIQJKE7X](https://user-images.githubusercontent.com/40459801/144528311-3f172949-e7d2-4fc7-9493-6d375f605010.png)

**Comment by zhangdaiscott** [comment]
这个是springboot提供的接口，你外部的tomcat springboot应该获取不到吧
