### ISSUE TITLE
字典Dict 前端没有展示，有实际值

### ISSUE THREAD

**Issue by Feng-Xg** [jeecgboot/jeecg-boot#3235]
##### 问题描述：
微服务模式，新建服务使用了代码生成，对字段进行了字典配置，接口返回有增加字段名_dictText的字典内容。
前端列表、编辑和新增字段没有展示下拉框，但是高级查询可以下拉框选值。
DictAspect增加了新服务的包。

##### 截图&代码：

![middle_img_v2_815bbc9f-d9a6-45c6-8cf4-036e1de1bcbg](https://user-images.githubusercontent.com/19472852/144585014-2a85d64a-e08b-460b-a304-59239d1e953d.jpg)
![middle_img_v2_dd2349e9-0c5c-4288-883f-b9a99b3c2bag](https://user-images.githubusercontent.com/19472852/144585033-ada078f9-46e2-4e4d-8167-69049decbc7d.jpg)
![middle_img_v2_87f26e96-8d74-4d3b-a9f4-40a5eaf8763g](https://user-images.githubusercontent.com/19472852/144585045-8dddba65-ab37-475a-a36b-5fe34e573333.jpg)
![middle_img_v2_75d6b777-8482-4bf7-8e34-fd1ea556272g](https://user-images.githubusercontent.com/19472852/144585062-86a7c775-e20b-46e0-a5d1-aae430029f77.jpg)
![middle_img_v2_149d9190-f085-4d59-a87e-2b4f079c5c6g](https://user-images.githubusercontent.com/19472852/144585072-8dc75812-0afa-4388-9c9b-e22923ce9b76.jpg)
![middle_img_v2_ad55dc85-1795-4334-8bde-26d05594f78g](https://user-images.githubusercontent.com/19472852/144585089-046313a7-8d8b-458d-9ede-8f912f253b58.jpg)

![middle_img_v2_1e2b3768-8f30-4661-a756-b63220c0e32g](https://user-images.githubusercontent.com/19472852/144585123-d2ea1b32-4ae2-4a5d-aa3e-3c22c4718d5b.jpg)

![middle_img_v2_d9aaf69c-be87-47a6-a755-1622cdb6393g](https://user-images.githubusercontent.com/19472852/144585116-d56d6546-c877-4ebf-a92f-7001eba7f2f6.jpg)

####  #友情提示（为了提高issue处理效率）
  #

**Comment by Feng-Xg** [comment]
#2737

**Comment by zhangdaiscott** [comment]
online配置的是什么样的控件？

**Comment by zhangdaiscott** [comment]
长时间无回复，关闭
