### ISSUE TITLE
部门权限控制，查询列表第一次查询没带任何参数，导致查询到所有数据

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3238]
##### 版本号：
3.0.0

##### 问题描述：
部门权限控制，查询列表第一次查询没带任何参数，导致查询到所有数据

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/144708077-2cfbe95f-997e-4149-86ee-b66f4a873f72.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请截图说明，那个功能
