### ISSUE TITLE
使用H2数据库疑问

### ISSUE THREAD

**Issue by programmerlc** [jeecgboot/jeecg-boot#3239]
##### 版本号：
2.4.6

##### 问题描述：
目前贵公司提供了mysql/oracle/sqlserver的初始化脚本，能否提供h2等嵌入式类型的数据库初始化脚本？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49057540/144732465-123c45c8-a15e-4657-923a-fe4721dddadd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己转吧
