### ISSUE TITLE
spring-boot2.3.5 已经停止维护,请问有升级到2.6的计划吗?

### ISSUE THREAD

**Issue by 1332987** [jeecgboot/jeecg-boot#3242]
##### 问题描述：
spring-boot2.3.5 已经停止维护,请问有升级到2.6的计划吗?

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40618162/144782829-1362dbba-8630-43cb-ac44-5479e9590076.png)
![image](https://user-images.githubusercontent.com/40618162/144782956-12c7b6eb-b61d-4741-a45c-9e2dcc277a60.png)

**Comment by zhangdaiscott** [comment]
感谢，会尽快安排

**Comment by zhangdaiscott** [comment]
收录 yf
