### ISSUE TITLE
使用CompressionPlugin打包插件，dist包变大。是否还有必要使用

### ISSUE THREAD

**Issue by a152832** [jeecgboot/jeecg-boot#3244]
##### 截图&代码：vue.config.js
    // 生产环境，开启js\css压缩
    if (process.env.NODE_ENV === 'production') {
      config.plugin('compressionPlugin').use(new CompressionPlugin({
        test: /\.(js|css|less)$/, // 匹配文件名
        threshold: 10240, // 对超过10k的数据压缩
        deleteOriginalAssets: false // 不删除源文件
      }))
    }

**Comment by zhangdaiscott** [comment]
这个是生成静态资源对应的压缩文件，变大不影响
