### ISSUE TITLE
online报表链接排序多字段失效

### ISSUE THREAD

**Issue by yyyiced** [jeecgboot/jeecg-boot#3245]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/55883703/144823468-86a75ac3-6684-4399-a8b5-e79b74ef0ec3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
