### ISSUE TITLE
集成积木报表报错

### ISSUE THREAD

**Issue by ViiGoooo** [jeecgboot/jeecg-boot#3246]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/27795396/144955669-701d3b6c-2866-4b41-a5e9-5c3b93656e29.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么项目，请详细说明

**Comment by ViiGoooo** [comment]
jeecgboot项目

**Comment by zhangdaiscott** [comment]
启动类保留jeecg的路径

**Comment by ViiGoooo** [comment]
![image](https://user-images.githubusercontent.com/27795396/144960658-6b6c233e-3816-49ed-b41a-4057a0876f7b.png)
有的

**Comment by ViiGoooo** [comment]
![image](https://user-images.githubusercontent.com/27795396/144960695-5547b6e3-8200-4fe5-b4fd-9758fde25f61.png)
