### ISSUE TITLE
新建模块启动错误

### ISSUE THREAD

**Issue by YuJingGuang** [jeecgboot/jeecg-boot#3247]
##### 问题描述：新建模块启动错误，新建的模块已经引入core，还有system-local-api。system模块也导入了新建的模块，parent也导入了
Field commonAPI in org.jeecg.common.aspect.DictAspect required a bean of type 'org.jeecg.common.api.CommonAPI' that could not be found.
单体项目，没有引入微服务模块

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66401112/144990465-668d113f-1c5b-4163-986b-af6e40e87335.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
微服务吗

**Comment by YuJingGuang** [comment]
> 微服务吗
> 
> 微服务参考这个 http://doc.jeecg.com/2043906 http://doc.jeecg.com/2194069

不是微服务，参考这个https://github.com/jeecgboot/jeecg-boot/issues/1806，类似

**Comment by zhangdaiscott** [comment]
不是微服务，哪详细说明如何启动的

**Comment by YuJingGuang** [comment]
> 不是微服务，哪详细说明如何启动的

![image](https://user-images.githubusercontent.com/66401112/144994458-5ed5e61b-7abc-4b71-a172-439a196e2a51.png)
按照system那样

**Comment by zhangdaiscott** [comment]
不是微服务不支持独立启动，需要在system引入新建maven，启动system
