### ISSUE TITLE
V3.0.0版本前端系统管理功能找不到接口

### ISSUE THREAD

**Issue by fdbxfghfn** [jeecgboot/jeecg-boot#3249]
##### 版本号：
V3.0.0

##### 问题描述：
使用VUE3.0的前端访问系统，系统管理中用户管理、角色管理等界面报找不到接口的问题，另外对比3.0beta预览地址与master跑出来的效果，并不一致

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
还未正式发布
