### ISSUE TITLE
角色权限中，除在线开发外，其他权限只勾选子项，不勾选父项会导致菜单无法显示

### ISSUE THREAD

**Issue by fuyongpingzoomkey** [jeecgboot/jeecg-boot#3250]
##### 版本号：
3.0.0

##### 问题描述：
复现步骤1：在角色权限页面，只勾选在线开发的一个子项，父项不勾选，如下图1所示。
结果1：刷新后可以正常显示在线开发子项的菜单。如下图2所示。
复现步骤2：在角色权限页面，只勾选消息中心下的我的消息，父项不勾选，如下图3所示。
结果2：刷新后不能显示我的消息菜单，如下图4所示。
期望结果：
其他菜单的逻辑应该与在线菜单保持一致，也是权限只勾选子项即可显示该子项的菜单。

##### 截图&代码：
图1：
![image](https://user-images.githubusercontent.com/35991617/145157406-866630f2-0590-4e4a-8e62-e6dc69d2e3ad.png)
图2：
![image](https://user-images.githubusercontent.com/35991617/145157859-91cfab4e-d03e-4527-8b22-3ed78da1ce64.png)
图3：
![image](https://user-images.githubusercontent.com/35991617/145157592-7b68b964-fe19-47ca-9616-68b4e6fa652d.png)
图4：
![image](https://user-images.githubusercontent.com/35991617/145157649-8e709bc2-6dd8-4cd4-ab6d-526287adec65.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
需要够选父亲的

**Comment by zhangdaiscott** [comment]
是的

**Comment by fuyongpingzoomkey** [comment]
> 是的

代码是在哪处理的，能说一下吗？
