### ISSUE TITLE
自定义导出excel模板

### ISSUE THREAD

**Issue by 458126871** [jeecgboot/jeecg-boot#3252]
##### 版本号：
V2.0

##### 问题描述：
1、自定义导出excel模板可否存在项目文件夹中
如果可以存放在哪，需要修改yml中的文件么
尝试了Demo中的代码提示报错 无法访问路径文件
2、excel导入时  是否可以有某一行为空的校验提示

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.autopoi.jeecg.com/1623974

**Comment by 458126871** [comment]
请问下


这个版本的jar&nbsp; 未找到&nbsp; 是因为还未上传么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 自定义导出excel模板 (Issue #3252)





 
http://doc.autopoi.jeecg.com/1623974
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
