### ISSUE TITLE
【重磅消息】想提前拥有JeecgBoot VUE3版本不，速度投票啦！！

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#3254]
> **JeecgBoot 正在参与2021年度开源评选，总票额达到3000票，提前发布VUE3版本，速度点起！！**

###### 投票地址： https://www.oschina.net/project/top_cn_2021?id=292

![](https://oscimg.oschina.net/oscnet/up-6ce6dd03afc5d97e5ac1163a73bfc75e284.png)

###### JeecgBoot VUE3 惊艳效果 - 抢先看

> 一个精心打造的全新前端版本，前端全部重写，每一行代码都追求极致！
> 全新的VUE3技术栈，不只是追赶技术潮流，更加适合大型项目。

- 演示环境：http://boot3.jeecg.com
- 文档地址：http://vue3.jeecg.com

![](https://jeecgos.oss-cn-beijing.aliyuncs.com/imfile/QQ%E5%9B%BE%E7%89%8720211208180919.png)
![](https://jeecgos.oss-cn-beijing.aliyuncs.com/imfile/QQ%E5%9B%BE%E7%89%8720211208180922.png)

**Comment by walkTtalk** [comment]
已投票，怎么提前

**Comment by zhangdaiscott** [comment]
票数到3000就提前发布

**Comment by fangyueben** [comment]
![image](https://user-images.githubusercontent.com/39821417/145343254-b1350091-1049-4208-8a17-ade5d1ff564a.png)
已投 期待发布

**Comment by ddwolf715** [comment]
已投。

**Comment by fdbxfghfn** [comment]
奈何参与人数不多，你的票数已经是最高了

**Comment by galaxist** [comment]
![image](https://user-images.githubusercontent.com/3365218/146331686-87cc998e-56b6-43d3-81f9-a39796bfee1b.png)
已投票
