### ISSUE TITLE
控制台页面报pluginnamearr重复定义是咋回事？

### ISSUE THREAD

**Issue by yanyan965914478** [jeecgboot/jeecg-boot#3255]
##### 版本号：
 2.4.6

##### 问题描述：
控制台报这个错怎么解决？
VM355:1 Uncaught SyntaxError: Identifier 'pluginnamearr' has already been declared
##### 截图&代码：

![image](https://user-images.githubusercontent.com/52962001/145201491-13576d16-a19b-4fd8-997f-2c4b024a346d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不清楚，没有遇到过

**Comment by yanyan965914478** [comment]
你们官方的页面也报这个错误，麻烦一起研究研究

**Comment by zhangdaiscott** [comment]
提供重现步骤

**Comment by yanyan965914478** [comment]
点击左侧菜单的时候会报这个错误

**Comment by Creabine** [comment]
同求

**Comment by jndxzqc** [comment]
> ##### 版本号：
> 2.4.6
> 
> ##### 问题描述：
> 控制台报这个错怎么解决？ VM355:1 Uncaught SyntaxError: Identifier 'pluginnamearr' has already been declared
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/52962001/145201491-13576d16-a19b-4fd8-997f-2c4b024a346d.png)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；

是不是用了什么浏览器插件，无痕模式试下呢
