### ISSUE TITLE
docker镜像部署，容器内后端不能连接redis

### ISSUE THREAD

**Issue by kytieguo** [jeecgboot/jeecg-boot#3258]
##### 问题描述：
按照文档，通过docker镜像部署，在镜像内，后端容器不能访问redis容器，连接失败，redis正常启动

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55947403/145343484-a0bf40a9-67e5-4e8c-ac86-103b92cbc061.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种问题不要提，部署问题自己解决，你肯定docker之间不互通
