### ISSUE TITLE
web 端打包文件太大，怎么做优化

### ISSUE THREAD

**Issue by 283288675** [jeecgboot/jeecg-boot#3260]
##### 版本号：
2.4.0

##### 问题描述：
web 端build打包出来js文件太大，已经启用了压缩之后，chunk-vendors.4fe6935d.js  8.06M，chunk-562fc808.1b5f8ffe.js 1.45M，
请教优化？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/15771966/145371052-aec64cea-ed9e-44bf-8b54-aab4e98dc3ff.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044025
