### ISSUE TITLE
请问下多对多的关系，怎么用主附表实现？

### ISSUE THREAD

**Issue by bigfacewo** [jeecgboot/jeecg-boot#3265]
##### 版本号：
2.4.6

##### 问题描述：
我有两张表是多对多的关系，我可以转换为两个1对多的关系。
即打算做成两张主表、一张附表的形式，但是附表不支持多个外键。

如果主附表不能实现，请问下有没有什么别的办法来解决这个问题？

**Comment by zhangdaiscott** [comment]
通过popup实现字段的关联
