### ISSUE TITLE
online表单     在线表单主表和附表，配置好后功能测试展示和生成代码配置之后不一样

### ISSUE THREAD

**Issue by a2685777864** [jeecgboot/jeecg-boot#3267]
##### 版本号：
4.0

##### 问题描述：
Online表单主表和附表，配置好后功能测试展示和  生成代码配置之后不一样

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48341207/145833429-b05e4c4e-87bd-48d6-b8b8-afeb757b4d0f.png)

生成的代码为什么只有主表的信息，而不是关联查询的信息

	@AutoLog(value = "产品表-分页列表查询")
	@ApiOperation(value="产品表-分页列表查询", notes="产品表-分页列表查询")
	@GetMapping(value = "/list")
	public Result<?> queryPageList(ProductTable productTable,
								   @RequestParam(name="pageNo", defaultValue="1") Integer pageNo,
								   @RequestParam(name="pageSize", defaultValue="10") Integer pageSize,
								   HttpServletRequest req) {
		QueryWrapper<ProductTable> queryWrapper = QueryGenerator.initQueryWrapper(productTable, req.getParameterMap());
		Page<ProductTable> page = new Page<ProductTable>(pageNo, pageSize);
		IPage<ProductTable> pageList = productTableService.page(page, queryWrapper);
		return Result.OK(pageList);
	}
	
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
关联展示不支持代码生成
