### ISSUE TITLE
online报表使用系统变量，报错提示找不到该变量

### ISSUE THREAD

**Issue by iGuozy** [jeecgboot/jeecg-boot#3268]
##### 问题描述：
online报表配置使用了系统变量后，功能测试提示找不到该变量

##### 截图&代码：
<img width="781" alt="image" src="https://user-images.githubusercontent.com/48822119/145850042-ef136c08-3306-4a78-87fc-ed2b5aeca58b.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/48822119/145850200-354cbcbc-1ad9-48a0-b556-cd60190bcf55.png">
<img width="646" alt="image" src="https://user-images.githubusercontent.com/48822119/145850468-38e7b1ea-f653-422d-bbbd-d5c6481aae0c.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by zhangdaiscott** [comment]
请把你的配置截图出来，我们测试无问题
