### ISSUE TITLE
Cron表达式组件中周界面的小建议

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/jeecg-boot#3269]
##### 版本号：
3.0

##### 问题描述：
原始Cron表达式组件界面见截图1，周界面下“指定”的选项，是按 1 ~ 7，本身周表达式1代表周日，7代表周六。
但用户直观上看到 1 ~ 7 的顺序，第一反应认为是 周一 ~ 周日 ，如果不仔细看样例数据，就会出现理解和实际运行时间不符合。

所以我个人在自己下载的代码中改了一下，也把这个建议反馈到这里，供参考。

截图2是我改后的效果，直接把数字 1 ~ 7，转为汉语的 周日 ~ 周六 ，这样与上面的“区间”和“循环”里的显示值匹配，用户体验上，第一反应就比较好理解，即使不看样例数据，也不会出现理解和实际运行不符合的情况。

截图3是我改动代码的地方，修改了week.vue 文件中，“指定”标签下的代码，由原始 for 循环遍历 specifyRange 的值，改为遍历 WEEK_MAP 的值，并把WEEK_MAP中周日的位置调整理到第一位，减少用户理解上的误差。

以上只是我个人小小建议，发出来分享给大家。

##### 截图&代码：
截图1 --》原始Cron表达式组件界面
<img width="726" alt="image" src="https://user-images.githubusercontent.com/17849555/145913903-5c666575-6aaa-40d8-a123-665a3db8ad0e.png">

截图2 --》修改后的界面
<img width="796" alt="image" src="https://user-images.githubusercontent.com/17849555/145915705-d57512fe-0213-4823-83fe-d26c7ad9c8a9.png">

截图3 --》代码改动的位置
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/17849555/145915192-a3798048-be93-4846-8f27-766943d3c7a4.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Dev-Lon** [comment]
这个建议可以，这样修改页面显示更加直观。

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
已采纳，下版本发布
