### ISSUE TITLE
使用WAR方式打包Tomcat异常无法启动

### ISSUE THREAD

**Issue by sunzhwei86** [jeecgboot/jeecg-boot#3270]
##### 版本号：
V3.0.0

##### 问题描述：
使用WAR方式打包Tomcat异常无法启动
本地开发工具启动前后端均正常，系统可访问，Jeecg-boot是3.0版本、JimuReport1.4.2版本，Tomcat8.5版本
但使用WAR方式进行线上部署时，后台异常：
[mysql-cj-abandoned-connection-cleanup] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading 非法访问：此Web应用程序实例已停止。无法加载[]。为了调试以及终止导致非法访问的线程，将抛出以 下堆栈跟踪。
        java.lang.IllegalStateException: 非法访问：此Web应用程序实例已停止。无法加载[]。为了调试以及终止导致非法访问的线程，将抛出以下堆栈跟踪。
参见下图

是因为MySQL的Jar有更新吗？还是需要做什么代码修改才能部署
##### 截图&代码：
![image](https://user-images.githubusercontent.com/53286757/145923996-e7bc844f-c2bd-47d1-9fa0-12a0534e5c73.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by sunzhwei86** [comment]
使用的是单体模式，MySQL8.0版本，代码中连接数据库及VUE配置均是具体的IP地址，目前前端也不展示登录界面

**Comment by sunzhwei86** [comment]
![image](https://user-images.githubusercontent.com/53286757/145925554-c3dc551d-8f28-413c-be8b-64ed2c54bc4c.png)

**Comment by zhangdaiscott** [comment]
我们测试无问题，你自己再研究下，百度搜索对应的错误

**Comment by wlgshf** [comment]
请问解决了吗  同样问题  以前版本war没问题
