### ISSUE TITLE
CAS 登录ST验证成功，接口debug返回正常数据，页面调试显示为failed

### ISSUE THREAD

**Issue by Jinyunpeng0903** [jeecgboot/jeecg-boot#3272]
##### 版本号：
3.0

##### 问题描述：
CAS 登录ST验证成功（validateLogin），debug 显示success true 且返回正常数据，接口却显示为field

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42921186/145961363-dc6ef1fc-0021-44df-bed7-0fb712fca64c.png)
![image](https://user-images.githubusercontent.com/42921186/145961585-e4b55da6-01e1-438c-a55b-088c8608adff.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
cas服务端你怎么写的

**Comment by Jinyunpeng0903** [comment]
字段问题
