### ISSUE TITLE
exportBigExcel 处理大excel导出

### ISSUE THREAD

**Issue by Caisen1988** [jeecgboot/jeecg-boot#3274]
##### 版本号：
V2.4.5

##### 问题描述：
看到有处理大excel的教程
http://doc.jeecg.com/2325817
但是没有找到exportBigExcel 函数

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
