### ISSUE TITLE
online 表单新增按钮 js增强问题

### ISSUE THREAD

**Issue by Apollo666** [jeecgboot/jeecg-boot#3275]
##### 版本号：
V2.4.5

##### 问题描述：
在online表单 新增按钮 js增强list的时候，怎么才能弹出新的vue实例呢？
现在只能弹出alert简单的组件，我想弹出自己写vue内容，不知道怎样才能实现，谢了。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Apollo666** [comment]
![image](https://user-images.githubusercontent.com/10209914/146166849-6fca7395-f876-4ae2-9b61-1751871ddea7.png)
![image](https://user-images.githubusercontent.com/10209914/146166922-fbdcb278-9bd9-4a81-b6fd-5ab356dd0abe.png)

**Comment by Apollo666** [comment]
官网上有这个例子，但是没有对应的js增强脚本，不知道是怎么创建的。

**Comment by kasidier** [comment]
这个应该是流程设置后就自动有吧？

**Comment by kasidier** [comment]
网上看到的例子

![20200711100529600](https://user-images.githubusercontent.com/7098009/146494193-fbf188db-aa50-43a9-9a64-69bc351c72e9.png)
![20200711102404101](https://user-images.githubusercontent.com/7098009/146494216-6c532cb8-25ca-4239-ac6b-92af4521176c.png)
![20200711101609153](https://user-images.githubusercontent.com/7098009/146494238-b6906dbd-2764-4bcf-8baa-f1a24a813f1f.png)

**Comment by zhangdaiscott** [comment]
目前暂时不支持
