### ISSUE TITLE
【Online表单开发】下拉搜索组件问题

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#3276]
##### 版本号：
v3.0

##### 问题描述：

【Online表单开发】下拉搜索组件的显示数据只有10个，无法在Online表单开发中进行排序，造成如果有较多的相近数据，无法显示
##### 截图&代码：
使用的字典表数据如下
![image](https://user-images.githubusercontent.com/7098009/146147301-ea13175f-831e-48a8-a8cb-b4d278ef151b.png)
然后在表单中配置下拉搜索
![image](https://user-images.githubusercontent.com/7098009/146147380-8a3f8ce7-aba3-4edd-9b35-01bb7a9fe52f.png)

在表单新建中，输入“测试”两个字搜索，只能显示“测试10”-“测试1”10条数据，而无法选择**“测试”**这一条
![image](https://user-images.githubusercontent.com/7098009/146147619-6922ef0b-5218-467e-8d16-ca261347754b.png)
![image](https://user-images.githubusercontent.com/7098009/146147764-bd082520-1929-419c-a363-3feac8b945f7.png)

但是在查询配置中设置的，则不受10条限制
![image](https://user-images.githubusercontent.com/7098009/146147913-0b97f74c-44de-4981-b2bb-2b5e89138ce0.png)
![image](https://user-images.githubusercontent.com/7098009/146148009-6db4ec53-c576-4e19-8d88-994bcbe7224e.png)
![image](https://user-images.githubusercontent.com/7098009/146148163-5afa7cd6-fef5-40da-ab15-ff9c5a94bb85.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你这种几率很小吧，目前这块分页搜索目前是防止大数据导致页面崩溃。
当然如果觉得不满足需求，可以自己改造

**Comment by kasidier** [comment]
> 
那能问下，这个排序是按什么排序？online 设计是否提供参数支持，就是比如我可否在下拉搜索使用的字典表那一栏加order by?

**Comment by kasidier** [comment]
那online表单设计支持给下拉搜索加参数么？比如我加个order by 什么的



| |
kasidier_crystal
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月21日 11:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] 【Online表单开发】下拉搜索组件问题 (Issue #3276) |

你这种几率很小吧，目前这块分页搜索目前是防止大数据导致页面崩溃。
当然如果觉得不满足需求，可以自己改造

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kasidier** [comment]
能问下现在商务版是什么版本么？对标线上版的哪一版本？最新的更新计划是什么时间？













在 2021-12-21 11:12:40，"JEECG" ***@***.***> 写道：

你这种几率很小吧，目前这块分页搜索目前是防止大数据导致页面崩溃。
当然如果觉得不满足需求，可以自己改造

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
