### ISSUE TITLE
请问jeecgboot有实现批量下载功能吗，数据量大的时候选择记录行里的下载很耽误时间

### ISSUE THREAD

**Issue by molinlizhongli** [jeecgboot/jeecg-boot#3277]
##### 问题描述：
我们在使用jeecgboot做开发时，经常会碰到记录行里有下载功能，选择一条下载固然没问题，但有时候需要下载很多个，一个个点很耽误工作

##### 截图&代码：
![image](https://user-images.githubusercontent.com/25787150/146158861-fb7e8bfe-d079-42b8-a31c-cc5c06680551.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个自己二开即可
