### ISSUE TITLE
v2.4.6 的 websocket 服务端，存在性能和安全问题。

### ISSUE THREAD

**Issue by adu-shzz** [jeecgboot/jeecg-boot#3278]
##### 版本号：
v2.4.6

##### 问题描述：
websocket::onMessage 性能和安全问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48935792/146172495-75b7efd6-5c3e-467c-8b7f-898943575926.png)
![image](https://user-images.githubusercontent.com/48935792/146173384-d6e65ab0-2914-4c13-95d9-45e476093c99.png)

如图中代码：
1、性能问题：在 onMessage/1  接收到客户端消息后，双循环全服广播，即，如果有N人在线，就发送 N×N次消息。
2、安全问题：没有校验 websocket 连接的有效性，谁都可以连接上服务端。另外，看 onMessage/1 的代码，猜测是想实现客户端和服务端彼此心跳保持，但没有验证消息内容是否表达心跳含义，并且N×N的消息量没有任何保护，对服务端容易造成攻击，短时间可能打满内存。

**Comment by adu-shzz** [comment]
补充性能和安全问题：
![image](https://user-images.githubusercontent.com/48935792/146175094-5b7f12ca-8646-4145-bb1f-37d524acbad2.png)

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
