### ISSUE TITLE
前端登录时缓存数据字典问题

### ISSUE THREAD

**Issue by miko-chen** [jeecgboot/jeecg-boot#3279]
##### 版本号：
到目前github上最新提交版本都有问题

##### 问题描述：
localStorage最大配额是5M，而在登录时前端在localStorage缓存了token、username、userinfo、UI_CACHE_DB_DICT_DATA，前三者都能理解，为啥还要缓存数据字典？
目前现有的一个项目是用jeecg做的开发，因为一些特殊需求，数据字典大小超过了5M，在点击登录时极度缓慢，且报错“Failed to execute 'setItem' on 'Storage': Setting the value of 'pro__UI_CACHE_DB_DICT_DATA' exceeded the quota.”
个人感觉对数据字典进行前端浏览器缓存操作没有任何必要，本身localStorage存的量就不大，速度提升并不明显，数据量超过500K就拖得速度巨慢

##### 截图&代码：
![QQ截图20211214171842](https://user-images.githubusercontent.com/48851380/146299887-0038e28c-a463-4c72-aba0-6660ef115185.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是为了提升系统性能，不用每次都去请求接口，不需要的话，可以自己去掉
