### ISSUE TITLE
@DS注解，在Mapper上使用注入数据源无效（有时有效）

### ISSUE THREAD

**Issue by YizhiDu** [jeecgboot/jeecg-boot#3285]
##### 版本号：
2.4.6

##### 问题描述：
@DS多数据源，使用的是mysql，注解在Dao文件方法上使用，注入多数据源时好时坏

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44801316/146488651-a5162bbf-59cc-4d64-aa4e-6df37aa6e34d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个你得自己排查下，iisue过于简单，无法分析
