### ISSUE TITLE
语言切换的疑惑

### ISSUE THREAD

**Issue by Apiee** [jeecgboot/jeecg-boot#3287]
##### 版本号：
v3.0.0

##### 问题描述：
![image](https://user-images.githubusercontent.com/24862113/146511395-515a6c81-f88b-45b9-8c70-9096a2325c20.png)
这个在源码没有么? 我搜不到它的位置

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
默认没做国际化，提供了技术方案，可以自己改
http://doc.jeecg.com/2043980
