### ISSUE TITLE
多租户的字典不同需求问题

### ISSUE THREAD

**Issue by qinbo1022** [jeecgboot/jeecg-boot#3289]
##### 版本号：
v3.0

##### 问题描述：
数据字典没有隔离，多租户有不同字典需求时如何满足？例如type字典，a租户的字典值是123，b租户的字典值是234，但按当前配置方式实际1234都能看到，恳请能够指点一下

##### 截图&代码：

![image](https://user-images.githubusercontent.com/33479256/146517427-5b4e57ba-00c3-472c-9295-1d971282a4a7.png)

**Comment by zhangdaiscott** [comment]
这块得自己改造，默认没做多租户可以
