### ISSUE TITLE
jar包分离部署报错

### ISSUE THREAD

**Issue by 444690619** [jeecgboot/jeecg-boot#3290]
##### 版本号：
3.0.0

##### 问题描述：
jar包分离后,部署启动时报错
直接打包则可以正常部署启动

##### 截图&代码：
打包步骤:
1.jeecg-boot-parent下执行maven install
2.mvn clean package正常打出jar包
3.提取lib后修改配置,再次执行mvn clean package打出jar包

配置截图
两种打包方式只有jeecg-boot-module-system模块下的pom.xml文件有差异 其它步骤一模一样
1.直接打包使用默认配置
2.jar包分离方式,根据文档说明修改了jeecg-boot-module-system模块配置的build部分
![image](https://user-images.githubusercontent.com/30424611/146671529-906a33a1-5fec-49a6-a34c-3d2d32ef9000.png)

启动脚本:
分离后的jar包放在/home/tmn/webserver/jeecgbootlib/lib目录下
jar包分离启动脚本
nohup java -Ddebug=true -Dloader.path=/home/tmn/webserver/jeecgbootlib/lib -jar /home/tmn/webserver/jeecg-boot-module-system-3.0.jar >> jeecgboot.log &
正常打包启动脚本
nohup java -jar /home/tmn/webserver/jeecg-boot-module-system-3.0.jar >> jeecgboot.log &

报错截图
![image](https://user-images.githubusercontent.com/30424611/146671418-5b6be678-615a-4bd2-81bd-d69b69b501c3.png)

![image](https://user-images.githubusercontent.com/30424611/146671329-9431f9fd-e819-4c22-8209-0f7e239d2ba5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己多研究下吧，我们演示环境都是分离打包的，没有问题。
http://doc.jeecg.com/2043890

**Comment by 444690619** [comment]
从idea里面移除项目，然后重新添加就好了，之前那个错误是因为一直从demo模块启动，大坑

**Comment by 444690619** [comment]
![image](https://user-images.githubusercontent.com/30424611/149417135-98e40a16-9c31-44ae-abe6-ff9c469572dd.png)
jeecg-boot-module-demo-3.0.jar 把这个类注释掉就好了

**Comment by zhangdaiscott** [comment]
为什么？要注释掉demo模块

**Comment by zhangdaiscott** [comment]
demo jar里面有个application.yml，把他删掉就好了
或者在system jar同级创建一个config，把配置文件拷贝进去也可以
![image](https://user-images.githubusercontent.com/3162115/184094698-f255b00f-f75f-482a-b510-68cfcba9808b.png)

参考
https://blog.csdn.net/user2025/article/details/108173007
