### ISSUE TITLE
online表单的部门选择器不能快速定位和过滤

### ISSUE THREAD

**Issue by iamfred** [jeecgboot/jeecg-boot#3293]
##### 问题描述：
我现在使用online表单时，使用的，将某个字段设置为使用部门选择器。（表类型：单表、表单分类：测试表单、主题模板：默认主题）
我是将部门当成公司信息在使用，所以部门数据非常多。
当弹出部门选择器的时候，输入公司名称没有办法快速定位或者只保留检索匹配的内容，导致这个部门选择器使用起来比较鸡肋。
有没有什么办法快速定位到检索的公司？（我不想用Popup组件，既然提供了部门选择器，按理说就应该能用才对）

##### 截图&代码：
弹出部门选择器后，输入要检索的公司名称，回车并未跳转到目标公司
![image](https://user-images.githubusercontent.com/6022442/146867889-cf8e3393-c3fb-4aa1-85c4-9eaec5f81b87.png)
只能手动下拉滚动条去找到高亮的关键字，然后勾选并确定
![image](https://user-images.githubusercontent.com/6022442/146868012-78737acf-aaca-47ce-923e-80363305e319.png)
按这种方式的查找效率太低了，而且公司数据多的话要滑动自己找半天标红的高亮数据。
能不能输入关键字回车后直接跳转到第一个匹配，或者仅保留匹配的数据，其他数据隐藏？

**Comment by zhangdaiscott** [comment]
直接自己扩展部门选择组件即可

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
