### ISSUE TITLE
代码生成1:1子表，子表数据始终以Null对象保存入库

### ISSUE THREAD

**Issue by sunzhwei86** [jeecgboot/jeecg-boot#3294]
##### 版本号：
V3.0.0

##### 问题描述：
Online设计的主表1:1子表无法保存，前后端均无异常抛出，但前端在主表From中的子表List是null，子表对象传入后端以Null对象保存，子表数据表无值，是空表。即使手工在数据库中插入数据，修改前可以看到子表数据，但保存后仍传Null值到后端Action

1：N子表可保存

##### 截图&代码：
1：1代码及console如下：
![image](https://user-images.githubusercontent.com/53286757/146873721-9cf42931-01d5-4506-85d5-4465dc4a9750.png)

新增/修改保存后，1:1子表对象是空值
![image](https://user-images.githubusercontent.com/53286757/146873769-ae4ea3e6-a063-4186-ab05-03a7162967c8.png)

跟踪后发现子表Form.vue进行getFormData后已经是Null对象了
![image](https://user-images.githubusercontent.com/53286757/146873991-1b8df7ed-031c-4e0b-b2f1-65d21d5eea01.png)

子表Form.vue该方法如何修改？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的代码，我们无法排查，还是自己debug跟踪吧

**Comment by sunzhwei86** [comment]
不是自己写的代码，是代码生成器生成的逻辑，我只加了console跟踪不到，只能判定对一的子表的对象一点保存就是空

**Comment by sunzhwei86** [comment]
> 自己写的代码，我们无法排查，还是自己debug跟踪吧

@zhangdaiscott 这个问题确实不是自己写的代码逻辑，尝试多次终于初步定位到原因，但是不清楚自己是否能改。
步骤重现
1：1的子表对字段在Online中设置唯一校验后，子表保存时将以NULL传入子表List中，造成后台子表无数据保存
注：当子表字段不设置唯一检验，则不会产生任何问题

以下代码是设置唯一检验后，代码生成器生成的代码，未做任何修改，仅增加了注释用于个人备注
![image](https://user-images.githubusercontent.com/53286757/147389148-15f0bc90-ebf7-45dc-aa48-3d8d548d4c64.png)

或者是否可在子表的function中进行修改？

**Comment by sunzhwei86** [comment]
> 自己写的代码，我们无法排查，还是自己debug跟踪吧

@zhangdaiscott 这个问题确实不是自己写的代码逻辑，尝试多次终于初步定位到原因，但是不清楚自己是否能改。
步骤重现
1：1的子表对字段在Online中设置唯一校验后，子表保存时将以NULL传入子表List中，造成后台子表无数据保存
注：当子表字段不设置唯一检验，则不会产生任何问题

以下代码是设置唯一检验后，代码生成器生成的代码，未做任何修改，仅增加了注释用于个人备注
![image](https://user-images.githubusercontent.com/53286757/147389148-15f0bc90-ebf7-45dc-aa48-3d8d548d4c64.png)

或者是否可在子表的function中进行修改？
