### ISSUE TITLE
【应用首页】这里的应用可以设置权限么？

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#3295]
##### 版本号：
3.0

##### 问题描述：

1.应用首页功能，是添加一个应用，然后在内部设置相应列表小功能的意思么？

2.那这个应用开放的权限是在哪里控制呢？
就比如我设置了3个应用A\B|C
然后想A和B 是给所有人看的，而C是只有特殊角色可看的，应该怎么设置？

3.图标和Logo都是什么情况下显示的？

4.怎么配置应用首页？和首页的优先级是怎样的？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/7098009/146885881-3f47542c-579d-442c-9525-ba90b6d340b2.png)

![1640069888(1)](https://user-images.githubusercontent.com/7098009/146885783-a2b5342f-d2ef-4e02-9e7f-a2620c290f8b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
目前只是雏形功能，比较简陋，无你要的功能
