### ISSUE TITLE
【Online表单设计】多子表可以设置子表上下排列么？

### ISSUE THREAD

**Issue by kasidier** [jeecgboot/jeecg-boot#3296]
##### 版本号：
3.0

##### 问题描述：
现在多子表如果用默认模板样式，是在主表下用Tab形式展示，
可以设置子表上下展示么？或者说我可以设置子表在主表的某个位置在多大范围内展示么？

##### 截图&代码：
当前多子表效果

![image](https://user-images.githubusercontent.com/7098009/146886871-32a3290e-d258-45f5-ae49-83d25d98006e.png)

期待多子表效果

![image](https://user-images.githubusercontent.com/7098009/146887640-0c999f55-1b21-4330-93fe-c079f26d2e4d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
