### ISSUE TITLE
org.jeecg.boot.starter.lock.aspect.DistributedLockHandler 逻辑异常

### ISSUE THREAD

**Issue by xinwu-yang** [jeecgboot/jeecg-boot#3297]
##### 版本号：
2.4.3

##### 问题描述：
org.jeecg.boot.starter.lock.aspect.DistributedLockHandler 逻辑异常

##### 截图&代码：
```java
LockModel lockModel = jLock.lockModel();
if (!lockModel.equals(LockModel.MULTIPLE) && !lockModel.equals(LockModel.REDLOCK) && keys.length > 1) {
    throw new RuntimeException("参数有多个,锁模式为->" + lockModel.name() + ".无法锁定");
}
RLock rLock = null;
String keyConstant = jLock.keyConstant();
if (lockModel.equals(LockModel.AUTO)) {
    if (keys.length > 1) { 
        // 此分支永远不可能执行，大于1就已经在前抛出异常了
        lockModel = LockModel.REDLOCK;
    } else {
        lockModel = LockModel.REENTRANT;
    }
}
```
当lockModel 等于AUTO时 keys.length 一定不大于1了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
已修复，if (!lockModel.equals(LockModel.MULTIPLE) && !lockModel.equals(LockModel.REDLOCK) && keys.length > 1) {
    throw new RuntimeException("参数有多个,锁模式为->" + lockModel.name() + ".无法锁定");
}放下面即可

**Comment by xinwu-yang** [comment]
OK！
