### ISSUE TITLE
online或积木报表如何根据sql进行定时存库

### ISSUE THREAD

**Issue by carrotzizi** [jeecgboot/jeecg-boot#3298]
##### 版本号：
2.4.6

##### 问题描述：
使用online报表，或积木报表如何根据sql进行定时存库，或者相关功能点在其他模块？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
无

**Comment by carrotzizi** [comment]
好的谢谢
