### ISSUE TITLE
jeect-boot老版本sql注入问题如何修复

### ISSUE THREAD

**Issue by 154189398** [jeecgboot/jeecg-boot#3300]
##### 版本号：
2.1.3

##### 问题描述：
不是微服务版的jeecg-boot框架，sql注入要如何修复？
风险等级：高
漏洞说明：通过手工渗透，发现系统存在SQL注入的漏洞，注入点很多，攻击者可以利用该漏洞直接获取数据库数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59166314/146949041-092ee0b2-c38d-4db7-b11f-b332b7148b07.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
手工升级到最新版本 或者参考最新版的修改，自己修复
