### ISSUE TITLE
积木报表 api解析报错

### ISSUE THREAD

**Issue by 1124095976** [jeecgboot/jeecg-boot#3301]
##### 版本号：

jeecgboot2.4.6

##### 问题描述：
积木报表 api解析报错

##### 截图&代码：
默认id和 token已经填进去了
解析不出来，后台会报错
![image](https://user-images.githubusercontent.com/55647113/147023718-f37f834d-a676-4e55-9fbc-b1a80be01eda.png)

![image](https://user-images.githubusercontent.com/55647113/147023774-64eb470a-9153-420a-ae03-07e871519bd9.png)

**Comment by zhangdaiscott** [comment]
接口要参数，未传递正确参数

**Comment by 1124095976** [comment]
不是这个原因，我已经传参数了
![image](https://user-images.githubusercontent.com/55647113/147026887-843ee75c-02ec-44a2-9594-3cf11be0224b.png)
