### ISSUE TITLE
积木报表 api解析报错默认的id和 token已经填进去了  解析不出来，后台会报错

### ISSUE THREAD

**Issue by 1124095976** [jeecgboot/jeecg-boot#3302]
版本号：
jeecgboot2.4.6

问题描述：
积木报表 api解析报错
默认的id和 token已经填进去了 
解析不出来，后台会报错

截图&代码：
![image](https://user-images.githubusercontent.com/55647113/147027065-4e18107f-2eef-4446-bc3e-80204f5b18f4.png)
![image](https://user-images.githubusercontent.com/55647113/147027096-f621538f-60d8-4543-aada-4c4aba8afd59.png)
![image](https://user-images.githubusercontent.com/55647113/147027237-d1ee9ff1-308d-4ae6-8c0c-b37211136bce.png)

**Comment by 1124095976** [comment]
是这个接口在报错，不知道哪里弄错了
http://localhost:8001/jeecg-boot/online/cgform/api/data/mytest/queryById?id=1467769838800015361&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDAxMzg1MjUsInVzZXJuYW1lIjoiYWRtaW4ifQ.hN-0ONGDYigmczPzjlEvzJWtZdFNJuhEb-MEx4-A_gk

**Comment by zhangdaiscott** [comment]
老版本有bug，升级到最新的版本
