### ISSUE TITLE
online 表单 添加部门选择器，保存后是ID

### ISSUE THREAD

**Issue by Apollo666** [jeecgboot/jeecg-boot#3305]
##### 版本号：

3.0
##### 问题描述：
online 表单添加里，选择部门选择器，新增添加部门是id，不是部门编号。
我在人员管理里，新增完部门在数据库里就是部门编号，请问这个要怎么成保存是部门编号？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/10209914/147080706-45126e9b-886b-47a6-9609-70081d37eba8.png)

![image](https://user-images.githubusercontent.com/10209914/147080899-44f00530-0476-4239-97d2-b2262785d45d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看文档，拓展参数
