### ISSUE TITLE
请教下如何给Form中的某个input输入框赋值

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecg-boot#3307]
##### 问题描述：

请教下如何给Form中的某个input输入框赋值，按文档试了下用
that.$nextTick(() => {
    that.form.setFieldsValue("code",res.result);
});
跟 that.triggleChangeValue("code",res.result)都不行，是哪个地方不对吗

**Comment by zhangdaiscott** [comment]
最新版已经支持双向绑定了，不用这么写了
