### ISSUE TITLE
sql导入失败

### ISSUE THREAD

**Issue by wyx666518** [jeecgboot/jeecg-boot#3308]
##### 版本号：
3.0.0

##### 问题描述：
默认的mysql数据库脚本导入，提示Specified key was too long; max key length is 1000 bytes，Mysql版本 5.7.30

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
有大字段，百度改下数据库配置就行
https://blog.csdn.net/weixin_42867972/article/details/107564121
