### ISSUE TITLE
在线开发时，使用字典table，添加where条件，在线测试没问题，生成代码，不能使用，遗失where条件

### ISSUE THREAD

**Issue by qiaochengqiang** [jeecgboot/jeecg-boot#3309]
##### 问题描述：
在线开发时，使用字典table，添加where条件，在线测试没问题，生成代码，不能使用，遗失where条件。
使用字典table，代码sys_dict_item2 where dict_id='1470000610754912258' ，在线测试时，where条件没问题，但是生成代码，查询的是所有数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/57664443/147313844-9a4b3c62-e7b3-4530-8224-92bf0eb7b3a2.png)
![image](https://user-images.githubusercontent.com/57664443/147313855-ab9a07fc-7dd0-4cd6-801e-bcf8243d9582.png)
![image](https://user-images.githubusercontent.com/57664443/147314151-e3009893-0cbe-457f-a5c2-a178f474aa2b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by qiaochengqiang** [comment]
麻烦有时间解决一下，生产代码这一块的问题

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
