### ISSUE TITLE
online报表sql解析无法识别date_formate()和now()函数

### ISSUE THREAD

**Issue by lanfengqiuqian** [jeecgboot/jeecg-boot#3310]
##### 版本号：
2.7

##### 问题描述：
我想要获取当月项目总收入和总成本，但是获取本月月份的函数不支持，now()测试了也不支持

##### 截图&代码：
SELECT SUM(total_income) AS total_income, SUM(total_out) AS total_out FROM gm_bill_month WHERE bill_date = DATE_FORMAT(NOW(),'%Y-%m')

如上面的sql会报错，但是把时间换成写死的就可以

SELECT SUM(total_income) AS total_income, SUM(total_out) AS total_out FROM gm_bill_month WHERE bill_date = '2021-12-24'

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
提供错误日志，另外jeecg也没有2.7这个版本号

**Comment by zhangdaiscott** [comment]
ws test

**Comment by 1298191366** [comment]
你用的是什么数据库，我在mysql中测试这样子写是没有问题的，看看你的字段 bill_date 是否为varchar类型的，如果是date类型的这样子写数据库都执行不成功，你可以写成DATE_FORMAT(now(),'%Y-%m-%d')
![image](https://user-images.githubusercontent.com/30997828/148747436-1b0b1eaa-6ed1-4c72-b548-4b5786b47d0d.png)
