### ISSUE TITLE
online报表默认查询条件设置

### ISSUE THREAD

**Issue by carrotzizi** [jeecgboot/jeecg-boot#3313]
##### 版本号：
2.2.0

##### 问题描述：
请问online报表怎么才能设定默认查询条件值，例如，默认查询当天，然后可以手动切换

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
当前不支持，后期规划
