### ISSUE TITLE
代码生成的列表页面能把自定义列功能加上么？

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#3314]
##### 版本号：
3.0

##### 问题描述：
代码生成的列表页面能把自定义列功能加上么？

##### 截图&代码：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
图片裂了

**Comment by tb2888** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 代码生成的列表页面能把自定义列功能加上么？ (Issue #3314)





 
图片裂了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
