### ISSUE TITLE
多数据源配置后在保存的时候，没有切换数据源

### ISSUE THREAD

**Issue by wangjun8023** [jeecgboot/jeecg-boot#3315]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/74419867/147376495-0faec12c-04d8-4448-844c-df0039bebeec.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Lyong2018** [comment]
配置多数据源有两步操作：
1. 在配置文件中配置一下多个数据连接，保证连接参数：url、username、password正确；
2. 检查一下如果用的不是mysql要把”SELECT 1 FROM DUAL“这句sql改掉；
3. service里面一定要加上这一句：@DS("multi-datasource1")；
4. 注意你的yml配置文件里面每个参数前面的空格，不要多了也不要少了

**Comment by aihongsen** [comment]
多数据源  无法使用online 生成代码功能 请作者指导
