### ISSUE TITLE
link_down 下拉级联组件，无法高级搜素

### ISSUE THREAD

**Issue by enterprising666** [jeecgboot/jeecg-boot#3316]
##### 版本号：
2.4.3

##### 问题描述：
link_down 下拉级联组件，无法高级搜素，而且只显示了一个字段，附属字段没有显示

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己二次开发吧
