### ISSUE TITLE
导入导出字典数据不能备翻译的问题

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3317]
##### 版本号：
3.0

##### 问题描述：
请问导出导入的字典数据翻译是需要 设置什么或者注意什么？还是需要自己写转化器

##### 截图&代码：
导出的sys_dict字典表的数据不能被翻译，自定义的从其他表中的字典数据能被翻译
![image](https://user-images.githubusercontent.com/29143702/147397206-07c838e8-d583-4fd4-941e-8cc5049f774a.png)

导入的都数据都不能被翻译
![image](https://user-images.githubusercontent.com/29143702/147397221-4b89ac1a-f3a9-4ba8-9bab-57df067dff94.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
debug跟踪代码，这样的issue 我们无法分析
