### ISSUE TITLE
JEECG_BOOT，验证码报404

### ISSUE THREAD

**Issue by GuiYuan1** [jeecgboot/jeecg-boot#3318]
##### 版本号：
JEECG BOOT 低代码开发平台（前后端分离版本） 当前最新版本： 3.0（发布日期：2021-11-01）
##### 问题描述：
按照项目下载和运行命令全部执行完毕后，打开登录页面，验证码报404，控制台报错为：
`XMLHttpRequest: 网络错误 0x2efd, 由于出现错误 00002efd 而导致此项操作无法完成。`
.env.production、.env.test、.env.development这三个文件改服务器IP，域名皆无效。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/96643866/147427885-895ffe02-def4-4913-81d2-3f0e487b822e.png)
![image](https://user-images.githubusercontent.com/96643866/147428159-7f7a18ba-a60a-482c-a993-4e2ac4bc8039.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
1、确认后台服务是否启动成功
2、确认前端配置的后端地址是否正确
