### ISSUE TITLE
Form中控件赋值问题

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecg-boot#3319]
##### 问题描述：
需求是选择项目时根据项目自动获取最大单号，后台单号已经获取成功，在给单号input控件赋值后不会立刻显示出来，需要在Form上其它控件随便输下，才会显示出来单号

##### 截图&代码：
![1](https://user-images.githubusercontent.com/54636793/147433440-e2925acc-27d5-4d13-b9e5-63a8100d5296.png)
![2](https://user-images.githubusercontent.com/54636793/147433444-f7e11e13-3de3-479b-9c73-b31927dcc614.png)
![3](https://user-images.githubusercontent.com/54636793/147433448-80f7ee97-9930-442b-8fee-c1a703679029.png)
![4](https://user-images.githubusercontent.com/54636793/147433450-c0f7cad2-5e54-4233-9919-24e974a58ded.png)

**Comment by zhangdaiscott** [comment]
自己写的代码，不要发issue
