### ISSUE TITLE
onl表单开发导入字典数据不能被翻译成code还保留了中文值

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3320]
##### 版本号：

3.0
##### 问题描述：
onl表单开发导入字典数据不能被翻译成code还保留了中文值

##### 截图&代码：
视频录制如下：

https://user-images.githubusercontent.com/29143702/147518652-26a962c4-a718-4871-8b62-34ace5932710.mp4

https://user-images.githubusercontent.com/29143702/147518656-6a629241-8808-4b15-966f-b1df1f34ff63.mp4

表单设置如下
![image](https://user-images.githubusercontent.com/29143702/147450143-85b323f6-56dd-4ae7-be20-afa8115d46c2.png)
![image](https://user-images.githubusercontent.com/29143702/147450144-a69b2180-f4ee-4417-aaaa-43374d214914.png)

导入数据表如下：
![image](https://user-images.githubusercontent.com/29143702/147450161-e65fd39e-40d7-4148-9934-b8f2149e12c7.png)

数据库中显示如下：
![image](https://user-images.githubusercontent.com/29143702/147450225-213f30ce-6157-4a5a-a421-4fcbafd50f6c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
用户表里有张小红这人？

**Comment by lexmarn001** [comment]
有的&nbsp;
zz123	123123
zhangsan	张三
jeecg	jeecg
admin	管理员
zhagnxiao	张小红







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] onl表单开发导入字典数据不能被翻译成code还保留了中文值 (Issue #3320)





 
用户表里有张小红这人？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
先测导出，看导出翻译，最好录个视频，描述太简单

**Comment by lexmarn001** [comment]
好的！一会录完传上去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月27日(周一) 下午5:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] onl表单开发导入字典数据不能被翻译成code还保留了中文值 (Issue #3320)




 
先测导出，看导出翻译，最好录个视频，描述太简单
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lexmarn001** [comment]
视频如何发给你呢，已经录好了@zhangdaiscott

**Comment by lexmarn001** [comment]
视频超过了10M，分成了2个

https://user-images.githubusercontent.com/29143702/147518598-4af7b469-3fd6-46f0-9f3a-a51634d5558b.mp4


https://user-images.githubusercontent.com/29143702/147518605-d23febed-7b62-4883-ab65-ce609d048017.mp4

**Comment by lexmarn001** [comment]
视频已经录入，放到了评论里面，请排查一下



郑州云卓科技有限公司&nbsp; &nbsp;&nbsp;
马阳&nbsp;
18838292559
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] onl表单开发导入字典数据不能被翻译成code还保留了中文值 (Issue #3320)





 
先测导出，看导出翻译，最好录个视频，描述太简单
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
你确定你的是3.0版本？
我这边测试无任何问题
