### ISSUE TITLE
上传图片功能能不能优化一下？

### ISSUE THREAD

**Issue by a2685777864** [jeecgboot/jeecg-boot#3322]
##### 版本号：
2.3和3.0都会有

##### 问题描述：
上传图片功能，上传附件后  会自动增加回显（需求就是去掉  上传图片功能  上传非图片时不反写）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48341207/147545511-5d093706-43a2-4811-82aa-9c591fd12113.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
二开需求，自己扩展源码即可
