### ISSUE TITLE
代码生成后，Online的一些前端js增强，默认日期等配置未生成，如何添加上，在那个位置添加？我是一名后端，对前端不是很懂！请求指导！

### ISSUE THREAD

**Issue by shenglongh** [jeecgboot/jeecg-boot#3323]
##### 版本号：
2.4

##### 问题描述：
1.代码生成后，js增强失效，如何在前端页面写上js增强的代码，写在哪，能简单的出个示例么？
2.填值规则，在代码生成后失效了，重写了一个后台值自增的接口，如何在前端代码上，某个字段上获取，可以出个示例么？
3.值自增，并在触发按钮的时候，自动填写在文本框里，怎么实现，可以指导一下么？
4.代码生成后，前端日期控件默认获取当前日期，失效了，这个怎么在前端页面上补上代码，怎么补，补在那个位置，可以出个示例么？
备注：我是一名后端，但是公司用了咱们的商业版框架，对前端不熟悉，请求指导

##### 截图&代码：

![0de1799b1aadc0299c7f2a50b56559e](https://user-images.githubusercontent.com/50540440/147545736-14a87aae-7225-44c5-a61f-ce254ef12880.png)
![d249e0023d80b50113d266e3faba73b](https://user-images.githubusercontent.com/50540440/147545789-6b962d45-7de3-41e5-997e-f04daddae29a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持js增强生成，文档写了。
可以生成后，手工加上逻辑
