### ISSUE TITLE
访问关网gateway 一直报 “Knife4j文档请求异常”

### ISSUE THREAD

**Issue by chenfajun** [jeecgboot/jeecg-boot#3324]
##### 版本号：
2.4.6

##### 问题描述：
访问关网gateway 一直报 “Knife4j文档请求异常”

##### 截图&代码：
http://43.254.55.14:9999/jeecg-system/v2/api-docs  404

**Comment by zhangdaiscott** [comment]
先启动单独服务模块 system，demo， 最后启动gateway
