### ISSUE TITLE
下载最新的3.0版本，导出操作异常

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3325]
##### 版本号：

3.0
##### 问题描述：
下载最新的3.0版本，onl表单导出操作异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29143702/147559408-35f850dd-3fb6-4c3b-b8a7-be94ca9f26fe.png)

![image](https://user-images.githubusercontent.com/29143702/147559364-b8b60fa7-e071-4383-bcb6-ebc50101a2c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
怎么重现

**Comment by lexmarn001** [comment]
我从gitee下载的最新版本，要不你们下载一下试试，
会不会是你们代码加密的时候有问题，你们没加密情况没事



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 晚上8:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 下载最新的3.0版本，导出操作异常 (Issue #3325)




 
怎么重现
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
