### ISSUE TITLE
autopoi模板导出Excel功能，#fe: 横向遍历不好用

### ISSUE THREAD

**Issue by wlgshf** [jeecgboot/jeecg-boot#3328]
##### 版本号：1.3.6 官方最新版本
<dependency>
			<groupId>org.jeecgframework</groupId>
			<artifactId>autopoi-web</artifactId>
			<version>1.3.6</version>
			<exclusions>
				<exclusion>
					<groupId>commons-codec</groupId>
					<artifactId>commons-codec</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

##### 问题描述：
#fe: | 横向遍历失效，无数据
其他!fe $fe都正常好用

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by wlgshf** [comment]
就没人回复下吗  我怀疑TemplateExportParams 少了属性colForEach  请官方核实下

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
问题已收录

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by qh2332449176** [comment]
我也发现了，请部解决了吗？

**Comment by Heath-Ho** [comment]
解决了吗？刚刚用1.4.6版本，横向遍历还是不能用

**Comment by github-LY-code** [comment]
1.4.8 还是不能用
