### ISSUE TITLE
官网演示系统onl导入有bug

### ISSUE THREAD

**Issue by lexmarn001** [jeecgboot/jeecg-boot#3329]
##### 版本号：
3.0

##### 问题描述：

2、导入没有翻译 看图3 

在线表单 ces_test_impor
以上操作均在官网演示系统，应该是存在bug的。

##### 截图&代码：
1、我在演示系统上创建了一个在线的表单&nbsp;ces_test_impor
![image](https://user-images.githubusercontent.com/29143702/147726597-bb2a8c3c-4345-4222-9637-b68a340dea0f.png)

2、在测试中，通过【新增】 的数据是正常的
![image](https://user-images.githubusercontent.com/29143702/147726605-f7588e5d-ef4b-413d-a56c-17ca7529d912.png)

3、但是通过导入的数据 不正常，导入的数据并没有被翻译生相应的字典数据

![image](https://user-images.githubusercontent.com/29143702/147726608-7b32d16d-972b-4c5e-9df8-68337fdd3f00.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没看明白

**Comment by lexmarn001** [comment]
1、我在演示系统上创建了一个在线的表单&nbsp;ces_test_impor



2、在测试中，通过【新增】 的数据是正常的



3、但是通过导入的数据 不正常，导入的数据并没有被翻译生相应的字典数据










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月30日(星期四) 中午1:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 官网演示系统onl导入有bug (Issue #3329)





 
没看明白
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
创建人如何配置，截图

**Comment by lexmarn001** [comment]
用的是 用户选择控件，
在官网演示系统上，可以上去操作一下看

![image](https://user-images.githubusercontent.com/29143702/147758780-05ef01ef-6718-4f5f-bce4-08d7481d61f9.png)

**Comment by zhangdaiscott** [comment]
ws test

**Comment by lexmarn001** [comment]
啥意思啊？？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月7日(周五) 晚上7:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 官网演示系统onl导入有bug (Issue #3329)




 
ws test
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1298191366** [comment]
问题未测出，请查看你的导入的excel是否按照正常格式填写
![image](https://user-images.githubusercontent.com/30997828/148906724-d34258c5-e334-44a2-a14d-7ed6a698c398.png)
一开始为三条数据返回结果
![image](https://user-images.githubusercontent.com/30997828/148906691-cf84f063-327a-46b4-8410-32f97bb1ae88.png)
导入之后变成了四条
![image](https://user-images.githubusercontent.com/30997828/148906821-a68f1e39-ad25-4c27-8f19-86dc20ad1d5c.png)

**Comment by lexmarn001** [comment]
您是在官网测试的，还是在自己的代码上测试的，
我用的excel来源步骤
1、在官网新增一条
2、导出新增的一条
3、复制一下，作为第二和第三条&nbsp;
4、再次导入。
5、查询的结果发现没有翻译




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 官网演示系统onl导入有bug (Issue #3329)





 
问题未测出，请查看你的导入的excel是否按照正常格式填写
 
 一开始为三条数据返回结果
 
 导入之后变成了四条
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1298191366** [comment]
我刚刚在官网测试的，用的你的示例ces_test_impor，测试无问题，你再去官网看看还有没有该问题
![image](https://user-images.githubusercontent.com/30997828/148933911-02ed9e42-73d2-4182-909e-af9576fa0f7b.png)
