### ISSUE TITLE
前端dictCode设置从表中获取数据源，有一定概率加载失败

### ISSUE THREAD

**Issue by EvanYou** [jeecgboot/jeecg-boot#3330]
##### 问题描述：
使用的为生成后的代码；
使用JVxeTable组件，columns使用JVXETypes.select类型，dictCode设置为从表中获取数据源，已存储好的数据，在加载时有一定概率会加载失败，直接显示该字段的原始ID。本地开发运行时发生概率较小，部署出来运行发生概率较大。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3600653/147642105-5320b63e-5d30-4c3e-a9cd-c6d1bdeae6e9.png)
![image](https://user-images.githubusercontent.com/3600653/147642152-1afc2fcd-9143-4c4c-9db9-388587cb4a72.png)
![image](https://user-images.githubusercontent.com/3600653/147642229-2407b4d6-318c-4a9d-920f-96bcf90d5810.png)
![image](https://user-images.githubusercontent.com/3600653/147642281-65082d16-5f47-4707-ade2-0312c76f744a.png)

相关代码示例：
组件使用代码
<j-vxe-table
          keep-source
          :ref="refKeys[0]"
          :loading="wfNodeTable.loading"
          :columns="wfNodeTable.columns"
          :dataSource="wfNodeTable.dataSource"
          :maxHeight="300"
          :disabled="formDisabled"
          :rowNumber="true"
          :rowSelection="true"
          :toolbar="true"
          />
组件配置代码
wfNodeTable: {
          loading: false,
          dataSource: [],
          columns: [
            {
              title: '节点名称',
              key: 'nodeName',
               type: JVXETypes.input,
              width:"200px",
              placeholder: '请输入${title}',
              defaultValue:'',
              validateRules: [{ required: false, message: '${title}不能为空' }],
            },
            {
              title: '节点类型',
              key: 'nodeType',
              type: JVXETypes.select,
              options:[],
              dictCode:"flow_node_type",
              width:"200px",
              placeholder: '请输入${title}',
              defaultValue:'',
              validateRules: [{ required: true, message: '${title}不能为空' }],
            },
            {
              title: '角色',
              key: 'roleId',
              type: JVXETypes.select,
              options:[],
              dictCode:"sys_role,role_name,id",
              width:"200px",
              validateRules: [{ required: true, message: '${title}不能为空' }],
            },
            {
              title: '节点序号',
              key: 'nodeOrder',
              type: JVXETypes.select,
              options:[
                {text:'1',value:'1'},
                {text:'2',value:'2'},
                {text:'3',value:'3'},
                {text:'4',value:'4'},
                {text:'5',value:'5'},
                {text:'6',value:'6'},
                {text:'7',value:'7'},
                {text:'8',value:'8'},
                {text:'9',value:'9'},
                {text:'10',value:'10'},    
              ],
              width:"140px",
              placeholder: '请输入${title}',
              defaultValue:'',
              validateRules: [{ required: true, message: '${title}不能为空' }],
            },
          ]
        },

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
提供重现步骤

**Comment by EvanYou** [comment]
**步骤：**
列表页面点击编辑时，弹出的表单页面加载明细列表时有概率产生此问题。
今天早上反复调试修改后已大致定位问题原因，以及找到了解决的方案，目前测试运行下来未再出现过异常，相关过程如下。
**调试过程及思路：**
1.弹出的表单页面加载子表数据时，是调用的如下方法进行加载
![image](https://user-images.githubusercontent.com/3600653/147725880-d61ee4c4-2a77-4802-8fe0-edefa6bbf364.png)
2.初步猜测是列表数据加载和列表column绑定option表字典关系的顺序导致的问题，列表加载数据的方法代码位于JVxeTableModelMixin.js中的requestSubTableData方法，字典关系绑定的方法位于JVxeTable.js中的_loadDictConcatToOptions方法。
3.争对这2个方法进行了调试，2个方法均通过异步获取后台数据，前端加载本身也存在先后顺序，正常来说都是先绑定option字典关系，再加载列表数据，2个方法执行获取的结果也是按照正常的先后顺序执行的。
4.我的猜测：按顺序异步请求成功后，这2个方法具体绑定数据的顺序处于平级状态，如先加载了列表数据，再绑定option的字典关系，就有几率导致加载顺序与预想的不一致而导致显示失败。
5.必定重现异常加载的办法：修改JVxeTable.js的_loadDictConcatToOptions方法，延迟绑定option关系，这样必定能复现前面说的加载异常现象，代码如下
![image](https://user-images.githubusercontent.com/3600653/147726635-44628c51-8828-4d91-8da4-4937897ed738.png)
6.解决办法：反向按第5条的办法修改，修改JVxeTableModelMixin.js中的requestSubTableData方法，延迟绑定明细列表的datasource即可，代码如下
![image](https://user-images.githubusercontent.com/3600653/147726771-f3c849c9-80fe-446b-96b4-c37b7fc4a679.png)


**### 本人并非专门的前端，有些地方理解不一定对，上面的方法如有错误之处请指正，谢谢**

**Comment by zhangdaiscott** [comment]
可能是网络慢导致的，具体出现问题，自己适当调整代码吧

**Comment by SuperRichZhao** [comment]
这和网络也许有一定的关系, 但关系不大, 请求子表数据接口与请求字典数据接口确实会存在异步问题, 若字典接口返回数据慢于子表数据接口, 就会出现如提出者@[EvanYou](https://github.com/EvanYou)所说的问题, 但是我发现了, 如果将当前jvxetable, 传入一个:always-edit="true" 则不会出现该问题, 但因此会作出一定性能的损耗
