### ISSUE TITLE
连接SQLServer报错

### ISSUE THREAD

**Issue by XianRenYan** [jeecgboot/jeecg-boot#3332]
##### 问题描述：
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS12]". ClientConnectionId:6795572c-8b2e-41c0-9a22-0f8f4933ef48

##### 截图&代码：

![image](https://user-images.githubusercontent.com/32242242/147644313-c985f042-ec4b-4665-b4bc-25537383382c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看文档
