### ISSUE TITLE
使用<JSelectUserByDep>组件，在选择部门后，右侧列表人员下方统计的分页信息与上方List中实际展示的数据不符

### ISSUE THREAD

**Issue by wanggh1021** [jeecgboot/jeecg-boot#3333]
##### 问题描述：

使用<JSelectUserByDep>组件，在选择部门后，右侧列表人员下方统计的分页信息与上方List中实际展示的数据不符
原因是在存在一个部门下有2级或2级以上个部门时，一个人员被分配在这个多级部门下（分配2级和3级部门），就会出现这个现象，
主要是在sys_user_depart 这个表存在一个user_id对应多个depart_id的情况，而在查询中SQL语句没有进行去重，导致mybait统计的分页相关信息不准确，而java在查询数据后却在service进行数据去重，所以会产生list表中数据与分页信息不符；

##### 截图&代码：
前提条件是如下图，设置一个人有两个部门，运营二组是 小红书事业部的二级部门
![image](https://user-images.githubusercontent.com/9603069/147724872-fbceb6d7-953d-4c95-ab9d-b6ecb647a967.png) 

使用组件进行选择时，左侧部门选择小红书事业部，会看到这个人在第一页出现，供33条数据，每页10行
![image](https://user-images.githubusercontent.com/9603069/147725119-77eabaf6-af28-4255-b22a-acd9ad8116d4.png)

翻到第3页还有这个人，而且每页10条，一共4页，在第3页只显示了8条数据
![image](https://user-images.githubusercontent.com/9603069/147725283-9169281f-5955-4af8-8fbf-317e8190f6f7.png)

修改方式：
在src/main/java/org/jeecg/modules/system/mapper/xml/SysUserDepartMapper.xml中对SQL语句进行分组
``` java
<mapper namespace="org.jeecg.modules.system.mapper.SysUserDepartMapper">
    <select id="getUserDepartByUid" parameterType="String" resultType="org.jeecg.modules.system.entity.SysUserDepart">
		SELECT *
		FROM sys_user_depart
		WHERE user_id = #{userId, jdbcType=VARCHAR}
    </select>

	<!-- 查询指定部门下的用户 并且支持用户账号模糊查询 -->
	<select id="queryDepartUserList" resultType="org.jeecg.modules.system.entity.SysUser">
		select a.* from sys_user a
		join sys_user_depart b on b.user_id = a.id
		join sys_depart c on b.dep_id = c.id
		where a.del_flag = 0 and c.org_code like '${orgCode}%'
		<if test="realname!=null and realname!=''">
			and a.realname like '%${realname}%'
		</if>
		group by b.user_id
	</select>

	<!-- 根据部门查询部门用户 分页 -->
	<select id="queryDepartUserPageList" resultType="org.jeecg.modules.system.entity.SysUser">
		select a.*, c.depart_name as org_code_txt from sys_user a
		join sys_user_depart b on b.user_id = a.id
		join sys_depart c on b.dep_id = c.id
		where a.del_flag = 0 and c.org_code like '${orgCode}%'
		<if test="username!=null and username!=''">
			and a.username like '%${username}%'
		</if>
		<if test="realname!=null and realname!=''">
			and a.realname like '%${realname}%'
		</if>
		group by b.user_id
	</select>
</mapper>
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
图文并茂

**Comment by wanggh1021** [comment]
> 图文并茂

已增加截图

**Comment by zhangdaiscott** [comment]
ws test

**Comment by 1298191366** [comment]
未测出
![部门bug](https://user-images.githubusercontent.com/30997828/148900778-2799bf0d-6254-4724-9d90-0c12251647e1.gif)

**Comment by wanggh1021** [comment]
感谢，可能是本地修改了根据用户名称检索导致。。。建议官方用户列表上方检索默认采用 “用户名称” 检索，钉钉同步过来账号是一串数字，不方便
