### ISSUE TITLE
关于Online在线功能，主表字段布局、附表功能、下拉选项等的开发建议

### ISSUE THREAD

**Issue by YUMOMODE** [jeecgboot/jeecg-boot#3337]
版本号：3.0

问题描述：
1. 主表字段布局的灵活性可以进一步提升
2. 附表字段自定义程度可以进一步提升
3. 下拉框系列的候选数据可以进一步提升

作者您好，感谢您对开源项目的付出！如果您有时间，可以参考一下以下建议，不胜惶恐，如有问题，还请指出：
鄙人是刚接触jeecg几天，尝试着使用Online功能搭建一个完整项目（信息管理类的项目），感觉非常不错，资料很详细，上述三个问题似乎是目前Online功能无法满足的，对此，鄙人有些建议或许可以解决这三个问题。
1. 主表字段布局灵活性问题：
![image](https://user-images.githubusercontent.com/19457554/147760340-bfb03958-7f2d-4f39-9a14-d3c9c92cbc94.png)
建议：在现有字段”表单风格“的基础上，可以在”页面属性“中加入百分比的”控件长度“属性，如：当表单风格为1列时，控件长度默认为1(即100%)，不可更改，当表单风格为2列时，控件长度默认为1/2，可更改，候选长度为1、1/2，当表单风格为3列时，控件默认长度为1/3，可更改，候选长度为1、1/2、1/3，以此类推，则可以满足更加多样化的页面控件布局需求
2. 附表字段自定义程度略低的问题：
当前附表字段自定义长度略低，如：不支持增强、不支持弹窗表单新增(当前似乎均为表格内编辑)
建议：增加附表风格”是否弹窗表单“，即自由控制列表和表单的字段展示，控制风格和主表类似。由此，如果增加了表单弹窗，那是否可以考虑为附表使用JS增强功能？
3. 下拉框系列控件的候选数据可以进一步提升：
当前下拉框系统控件支持表、字典，是否考虑支持Online报表？(目前仅popup控件支持Online报表)，因为许多候选数据，需要一系列的数据组合来呈现，不过倒是可以通过创建数据库的视图来解决这个问题

**Comment by zhangdaiscott** [comment]
1、支持表单宽度设置
2、有erp风格
3、暂不考虑online报表，支持表字典sql
