### ISSUE TITLE
部署后Websocket无法连接

### ISSUE THREAD

**Issue by Q3B0** [jeecgboot/jeecg-boot#3338]
##### 版本号：

2.3.0
##### 问题描述：
部署到服务器后，使用Nginx，websocket无法连接

##### 截图&代码：
前端VUE连接报错
![image](https://user-images.githubusercontent.com/8241503/147799340-93a72696-7334-4002-96f7-78eaa7669ff7.png)
Nginx配置
![image](https://user-images.githubusercontent.com/8241503/147799360-fa8ad30e-f942-46bd-942a-2b0bc674ebbc.png)
小程序连接报错
![image](https://user-images.githubusercontent.com/8241503/147799374-1d3340f9-6f3d-4839-a8e8-e810041ec539.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Q3B0** [comment]
服务器配置问题

**Comment by Liu98Fan** [comment]
你好，请问是如何解决的？
