### ISSUE TITLE
用户变量orgCodeTxt被transient修饰

### ISSUE THREAD

**Issue by suxioanan** [jeecgboot/jeecg-boot#3340]
版本号：
2.3.0

问题描述：
请问下:
用户实体类SysUser.java中的orgCodeTxt被transient修饰后,应该是不能被序列化的,但是最终返回输出还是有值,请问下是在哪里有做处理了吗?因为我这边在调整jeecg的时候,突然发现orgCodeTxt返回被忽略了,从而没有值
如果用@TableField(exist = false)修饰可以吗

截图&代码：
<#if po.fieldDbType=='Blob'>

    @TableField(exist = false)
    private  String orgCodeTxt;

@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
public class SysUser implements Serializable {
       /**
     * 部门名称
     */
    private transient String orgCodeTxt;

}
	
</#if>

**Comment by zhangdaiscott** [comment]
transient 的意思是不持久化db
