### ISSUE TITLE
微服务模式，登录页F5刷新、登录后首页F5刷新、退出登录报错404

### ISSUE THREAD

**Issue by snow322** [jeecgboot/jeecg-boot#3341]
##### 版本号：
3.0

##### 问题描述：
1）微服务模式，按照开发文档《系统监控跨域问题修复2.4》情况二处理后，登录页F5刷新、登录后首页F5刷新、退出登录都报错404。
2）没按情况二处理前，没有此现象。
3）代码其他地方没大改。

##### 截图&代码：
登录页F5刷新报错页面：
![image](https://user-images.githubusercontent.com/58735653/147811104-911517fb-8541-4d50-b184-b8ca6aefd5bd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
本地？

**Comment by snow322** [comment]
是的

**Comment by zhangdaiscott** [comment]
提供重现步骤，我们无此问题

**Comment by snow322** [comment]
我的步骤如下
1官网下载项目，改造成微服务，参考的官网《单体升级为微服务方案2.4+》。
2修改前端src/utils/request.js和vue.config.js，参考的官网《系统监控跨域问题修复2.4》。
![图片](https://user-images.githubusercontent.com/58735653/148012617-058b649e-a414-44cd-86ce-d93060bb1647.png)
3redis和rabbitmq都启动后，正常启动各模块，登录等其他操作都正常。
4登录页和首页刷新、退出登录就遇到404报错了。

**Comment by zhangdaiscott** [comment]
为什么要设置转发，我们不是提供了后台接口配置方式了吗

**Comment by snow322** [comment]
不设置转发的话，《后台接口配置方式》我可以在哪个相关文档学习使用下
