### ISSUE TITLE
online报表配置没有分类字典的翻译功能

### ISSUE THREAD

**Issue by yanchenchen** [jeecgboot/jeecg-boot#3342]
##### 版本号：
3.0

##### 问题描述：

用online报表配置查询出来的分类字典无法进行翻译。

报表配置里作字典翻译只支持数据字典，不支持分类字典。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
无此功能
