### ISSUE TITLE
如果一张表既是主表又是附表怎么配置

### ISSUE THREAD

**Issue by xiaodaidi1** [jeecgboot/jeecg-boot#3344]
##### 版本号：

2.4.6

##### 问题描述：

Online在线开发功能

如果一张表本身是另外一张表的附表.

但是同时又有另外一张表的外键关联到他

尝试过通过新建视图的方式,但是视图里只能使用单表

应该要怎么做才行?

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
作为附表的时候，你可以配置一个表下拉组件，下拉这个表的数据

**Comment by ZJR24** [comment]
感觉没有解决问题，希望能更新文档，或者上图，谢谢
