### ISSUE TITLE
代码生成提示成功但是并没有生成代码

### ISSUE THREAD

**Issue by wangkai168** [jeecgboot/jeecg-boot#3350]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/12244368/148309302-0f35a21a-8ba3-491e-8056-4f754c43656b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看常见问题贴
