### ISSUE TITLE
randomImage 代码有明显错误

### ISSUE THREAD

**Issue by lxw-man** [jeecgboot/jeecg-boot#3352]
##### 版本号：
3.9+

##### 问题描述：

随机验证码生成后，转换成小写加密换成，但是输出到前端依然是原始验证码，造成验证码有时候实效

##### 截图&代码：

@ApiOperation("获取验证码")
	@GetMapping(value = "/randomImage/{key}")
	public Result<String> randomImage(HttpServletResponse response,@PathVariable String key){
		Result<String> res = new Result<String>();
		try {
			String code = RandomUtil.randomString(BASE_CHECK_CODES,4);
			**_String lowerCaseCode = code.toLowerCase();_**
			String realKey = MD5Util.MD5Encode(lowerCaseCode+key, "utf-8");
			redisUtil.set(realKey, lowerCaseCode, 60);
		       **_String base64 = RandImageUtil.generate(code);_**
			res.setSuccess(true);
			res.setResult(base64);
		} catch (Exception e) {
			res.error500("获取验证码出错"+e.getMessage());
			e.printStackTrace();
		}
		return res;
	}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lxw-man** [comment]
建议把里面的0 O o i I 1 这几个不容易区分的过滤掉。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] randomImage 代码有明显错误 (Issue #3352)





 
这逻辑有什么问题? 提交的时候也换成了小写
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhangdaiscott** [comment]
版本号写的都不对，你肯定是老版的

**Comment by lxw-man** [comment]
谢谢 回答的非常及时，我核对一下。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] randomImage 代码有明显错误 (Issue #3352)





 
版本号写的都不对，你肯定是老版的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
