### ISSUE TITLE
CAS服务器 jdbc打通sys_user不会配置，请求帮忙

### ISSUE THREAD

**Issue by bangcd999** [jeecgboot/jeecg-boot#3353]
##### 版本号：
3.0

##### 问题描述：
CAS服务器,application.properties 该如何配置jdbc，才能与 jeecgboot 后台 sys_user 表整合，实现登录

##### 截图&代码：
![image](https://user-images.githubusercontent.com/71172145/148313983-7b563786-5b82-4e30-b97c-122ef2439382.png)

cas.authn.jdbc.encode[0].url=jdbc:mysql://192.168.2.67:3306/jeecg-boot?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
cas.authn.jdbc.encode[0].user=root
cas.authn.jdbc.encode[0].password=root
cas.authn.jdbc.encode[0].sql=SELECT * FROM  sys_user WHERE username = ?
cas.authn.jdbc.encode[0].passwordFieldName=password
cas.authn.jdbc.encode[0].driverClass=com.mysql.jdbc.Driver
cas.authn.jdbc.encode[0].numberOfIterations=1000
#cas.authn.jdbc.encode[0].numberOfIterationsFieldName=

cas.authn.jdbc.encode[0].saltFieldName=salt

cas.authn.jdbc.encode[0].staticSalt=63293188

cas.authn.jdbc.encode[0].algorithmName=PBEWithMD5AndDES
cas.authn.jdbc.encode[0].expiredFieldName=expired
cas.authn.jdbc.encode[0].disabledFieldName=disabled

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己的服务端，肯定根据自己的实现来配置，我们未提供统一的服务端代码

**Comment by bangcd999** [comment]
> 自己的服务端，可以根据自己的实现来配置，我们未提供统一的服务端代码

是这样的，CAS 服务器配置JDBC,要用咱们的sys_user表，但是因为复杂的加密加盐，我这边配置的CAS不好使，您这边有没有相应的demo参考

**Comment by hanhan721** [comment]
哥们,解决了吗?
