### ISSUE TITLE
查询条件是否支持模糊匹配的设置？

### ISSUE THREAD

**Issue by tangyijie** [jeecgboot/jeecg-boot#3355]
##### 版本号：
3.0

##### 问题描述：
如何配置在线表单的查询条件模糊匹配，比如：公司名称  我输入“上海” ，能把包含上海的信息全部查询出来

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
提供了模糊查询的文本组件
http://doc.jeecg.com/2044007
