### ISSUE TITLE
服务运行一段时间后就死掉

### ISSUE THREAD

**Issue by HiTigerXu** [jeecgboot/jeecg-boot#3356]
##### 截图&代码：

![企业微信截图_5e99468a-0dea-485b-b9bc-472a843ccbc4](https://user-images.githubusercontent.com/20093698/148482723-da12f479-cbce-49b2-af00-17117002eac9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个得自己排查
