### ISSUE TITLE
Shiro鉴权代码Bug

### ISSUE THREAD

**Issue by huangguocai** [jeecgboot/jeecg-boot#3358]
##### 截图&代码：

public boolean jwtTokenRefresh(String token, String userName, String passWord) {
        String cacheToken = String.valueOf(redisUtil.get(CommonConstant.PREFIX_USER_TOKEN + token));
            if (oConvertUtils.isNotEmpty(cacheToken)) {
            // 校验token有效性
            if (!JwtUtil.verify(cacheToken , userName, passWord)) {
                String newAuthorization = JwtUtil.sign(userName, passWord);
                // 设置超时时间
                redisUtil.set(CommonConstant.PREFIX_USER_TOKEN + token, newAuthorization);
                redisUtil.expire(CommonConstant.PREFIX_USER_TOKEN + token, JwtUtil.EXPIRE_TIME * 2 / 1000);
                log.debug("——————————用户在线操作，更新token保证不掉线—————————jwtTokenRefresh——————— " + token);
            }
            return true;
        }

个人认为以上代码BUG有两点：
BUG1:
String cacheToken = String.valueOf(redisUtil.get(CommonConstant.PREFIX_USER_TOKEN + token));
该代码无论redis里面这个key是否过期该字符串都不会为空，如果没有则是“null”字符串

BUG2:
 if (!JwtUtil.verify(cacheToken , userName, passWord)) {
该判断存在BUG，JWT校验不通过才刷新？还是校验通过才刷新？
基于BUG1的场景,null的字符串校验肯定不能过，所以刚好进入该逻辑，redis重新设置了前端token的有效时间，基于以上两个BUG，出现了用户登录回话不会过期的BUG现象。

**Comment by huangguocai** [comment]
刚仔细读了一下代码，bug2到底有没有问题还有待商榷，是否只是碰上BUG1凑巧出现的现象还需要你们再排查一下

**Comment by xiezhuojin** [comment]
> 

这几天刚好看到这块（我是因为这个框架用jwt而把secret暴漏在前端而对验证感到好奇然后看到的），第一点应该确实是bug，第二点不是。而且这个问题在3.0版本也存在。

**Comment by huangguocai** [comment]
> > 
> 
> 这几天刚好看到这块（我是感到好奇然后看到的），token过期redis就返回空，所以应该没问题。

这个问题我大概分析了一下：
redis里面的token有效期是jwt的两倍，也就是说JWT校验会在超过时间失效，但是redis由于有效期是双倍，所以key并没过期，会存在一个token续期的问题。

我所说的BUG就是redis里面我把key都删除了，这里走校验的时候自动给我续上了token，这样就会出现用户只要前端ls里面有token，就直接登上了，redis里面没有都能续上。
BUG的代码就是我上面说的BUG1

**Comment by zhangdaiscott** [comment]
```
BUG1:
String cacheToken = String.valueOf(redisUtil.get(CommonConstant.PREFIX_USER_TOKEN + token));
该代码无论redis里面这个key是否过期该字符串都不会为空，如果没有则是“null”字符串
```

判断非空逻辑，已经考虑到了"null"问题
