### ISSUE TITLE
系统涉及多种技术栈及依赖，建议提供docker镜像，简化测试使用。

### ISSUE THREAD

**Issue by dengqizhou30** [jeecgboot/jeecg-boot#3359]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jeecgboot是个开发框架，需要搭建本地开发环境。
因为他不单纯是业务系统，所以单纯用docker启动没意义。
当然我们项目中也提供了docker file，你可以自己下载源码制作镜像
