### ISSUE TITLE
依赖不存在

### ISSUE THREAD

**Issue by den233** [jeecgboot/jeecg-boot#3362]
2.1.4

Could not find artifact org.hibernate:hibernate-re:pom:2.1.4 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public)

**Comment by zhangdaiscott** [comment]
配置jeecg私服
http://doc.jeecg.com/2043876

**Comment by wmm-wrb** [comment]
请问为什么配置了  还是不行
