### ISSUE TITLE
online 在线表单 针对附表的生成的视图管理，无法修改/添加外键

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3365]
##### 版本号：
3.0

##### 问题描述：
online 在线表单 
问题起因：主表生成一个视图（主视图1），附表也生成一个视图（附视图1），需要主视图1与附视图1进行绑定时，附表视图无法添加或修改外键（主表id），导致主视图1仅能进行单表显示，无法显示附表内容

建议：
1、附表生成视图时，默认带入对应附表中的外键（主从关系）；
2、当附表视图的表类型为附表时，将外键中字段设置为可以修改；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66394184/149046164-7e1e051f-82bb-427a-8773-88682ff13c8b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
视图设计的就是只支持单表操作
