### ISSUE TITLE
online 在线表单 一对多默认主题时 附表删除按钮没做限制

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3366]
##### 版本号：
2.4.5

##### 问题描述：
online 在线表单 一对多默认主题时 选择主表一条数据--》点击查看--》勾选一条附表中的数据--》点击删除
可以删除附表中的数据，
 删除按钮虽然为灰色，但是可以触发对应功能

##### 截图&代码：

![111](https://user-images.githubusercontent.com/66394184/149047473-a23d791b-9606-47c3-bb3b-7fe23ed58ae9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，将在下版本更新
