### ISSUE TITLE
vxe-table升级到3+报错

### ISSUE THREAD

**Issue by gxdxlht** [jeecgboot/jeecg-boot#3367]
##### 版本号：
2.1.4

##### 问题描述：
由于JVXETable没有树结构表格，故而用vxe的树表格，想将vxe-table升级到3+，但是升级后前端项目启动不了，报错如下图。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/24773623/149046850-350c5681-a00e-461c-b069-49423b6576e3.png)

![image](https://user-images.githubusercontent.com/24773623/149046724-67df21a6-8d8b-4790-9ab9-0f0eaeb084dd.png)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vxe-table的3是基于vue3的吧，不兼容
