### ISSUE TITLE
目前表单编辑器不能编辑表单元素的逻辑关系

### ISSUE THREAD

**Issue by EdwardZheng86** [jeecgboot/jeecg-boot#3371]
可否替换成下面这个开源项目，表单编辑功能更强：
https://github.com/xaboy/form-create-designer

**Comment by zhangdaiscott** [comment]
感谢建议，暂时收录

**Comment by xiaolinVV** [comment]
@EdwardZheng86 看了下 form-create-designer 是 element ui 的，不支持 antdesign 的呀
