### ISSUE TITLE
需求：能否给jeecgboot框架添加数据安全功能？

### ISSUE THREAD

**Issue by zihanbobo** [jeecgboot/jeecg-boot#3373]
前端请求(参数加密)得到(响应数据加密返回)进行数据解密，jeecgboot框架实现请求数据解密，响应数据加密的功能。有优雅的解决方案也可以

**Comment by zhangdaiscott** [comment]
找个前端AES加密加密解密 工具类就行

**Comment by towry** [comment]
@zihanbobo 您好，能留下您的联系方式吗？（email，手机号），有人想请您喝茶。
