### ISSUE TITLE
tomcat部署war包后报Endpoint实例创建失败

### ISSUE THREAD

**Issue by xuqingyu2021** [jeecgboot/jeecg-boot#3376]
##### 版本号：
 3.0

##### 问题描述：
部署war包中webSocket一直连接不上，报Endpoint实例创建失败。

##### 截图&代码：

![3a1e34adac0730d646a5dbb3ca2d775](https://user-images.githubusercontent.com/94360597/149718268-0544334c-57da-4f38-94fb-72cc7e3aed8a.png)
代码是按照上线发布中的war部署方案执行的
![7c8d8a9a061961b182a06163db55a50](https://user-images.githubusercontent.com/94360597/149718496-a1f62ab5-48aa-4d1c-a1b2-a4994e69d116.png)
![image](https://user-images.githubusercontent.com/94360597/149718536-fd772b92-ac33-42a9-8cdb-c3f23e6f6819.png)
![3d59976648d1ed1f130aec443551109](https://user-images.githubusercontent.com/94360597/149718615-13463826-f122-40c9-9f7f-5789bd1266b4.png)
![c1c39b1b2a319646548aaa6fbbe380f](https://user-images.githubusercontent.com/94360597/149718730-8f32cae5-bb1d-4549-91f7-c6ab25aea3e5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043887
