### ISSUE TITLE
MySql8.0.25版本下online表单-导入数据库表-获取数据库表列表接口报错

### ISSUE THREAD

**Issue by YouToBeYourself** [jeecgboot/jeecg-boot#3377]
##### 版本号：
3.0

##### 问题描述：
本地Mysql 5.7.26版本，可以正常使用online表单-导入数据库表功能（获取数据库表列表接口）获取数据库表列表
测试环境MySQL8.0.25版本，无法使用online表单-导入数据库表获取数据库表列表数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9395855/149806618-a36fbcfc-c638-4772-b9f4-e68ee4fb64f3.png)
![image](https://user-images.githubusercontent.com/9395855/149806933-c7009602-b428-4b77-a548-5ef2d178b326.png)

报错：java.sql.SQLSyntaxErrorException: Table 'XXX.user_tab_cols' doesn't exist

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
测试 ws

**Comment by YouToBeYourself** [comment]
已经收到你的的邮件，我会尽快回复的！谢谢，辛苦了！

**Comment by 1298191366** [comment]
经测试，未重现此问题，我看你的报错信息是yfind_admin.user_tab_cols表找不到，是加了什么配置吗
![image](https://user-images.githubusercontent.com/30997828/150253623-52d932c1-1473-417b-a909-2cc5bc0b49ec.png)
![image](https://user-images.githubusercontent.com/30997828/150263341-d0ccd1cb-a0f9-45fb-8b4d-4238806c7e48.png)
在jeecg_database.properties下面我是这样子写的
![image](https://user-images.githubusercontent.com/30997828/150263455-a4b9ffcf-aff7-4c6a-9fe6-3f1a9194b652.png)

**Comment by yangzhiwei666** [comment]
请问这个问题解决了吗，我也遇到了相同的问题

**Comment by YouToBeYourself** [comment]
已经收到你的的邮件，我会尽快回复的！谢谢，辛苦了！
