### ISSUE TITLE
代码生成器修改生成类的包名前端报 404

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#3378]
##### 版本号：
3.0.0

##### 问题描述：
代码生成器将 org.jeecg.modules.demo 修改成自己的包名会导致找不到类

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48941586/149907835-d457b4d8-56c7-4f28-93d8-bd2d257516c9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Chris-Arith** [comment]
swagger 文档中也不显示相关接口信息，通过 postman 调用依然提示 404

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
91
