### ISSUE TITLE
代码生成与online表单效果不一致

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#3380]
##### 版本号：
3.0

##### 问题描述：
online表单前端添加了很多校验条件，代码生成后就不生效了。
多谢。

##### 截图&代码：
**online表单配置**
![image](https://user-images.githubusercontent.com/48941586/150059810-368c118f-2236-4b23-9b61-73e3b487c767.png)
![image](https://user-images.githubusercontent.com/48941586/150059843-2d6821f2-1e9b-435c-8854-62a3cc527a60.png)
![image](https://user-images.githubusercontent.com/48941586/150059901-4c0a66ad-dd78-4cef-90cd-434319b74325.png)

**online表单功能测试**
![image](https://user-images.githubusercontent.com/48941586/150059969-aab0bebc-85b2-4d89-8dc6-41202295fd71.png)

**代码生成测试**
![image](https://user-images.githubusercontent.com/48941586/150060015-b79a1a1a-dd89-4e05-8a19-9285aefeda1d.png)

**前端代码**
![image](https://user-images.githubusercontent.com/48941586/150060045-148c04a7-e7c9-4b33-9848-a9b26ecd69db.png)

**后端代码**
![image](https://user-images.githubusercontent.com/48941586/150060086-71272769-cb5c-46a3-9e60-73d40ed6d5f2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代码生成不够细的地方，手工调整生成的代码即可 。
