### ISSUE TITLE
online 在线表单 使用文件组件时，上传文件名中含%，下载异常

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3381]
##### 问题描述：

online 在线表单 使用文件组件时，上传文件名中含%，下载该文件时提示400异常

##### 截图&代码：

提示如下：

HTTP Status 400 – Bad Request
Type Status Report

Message Invalid URI: isHexDigit

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Apache Tomcat/9.0.39

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty
