### ISSUE TITLE
当搜索框里只输入 * 时，后台索引越界。

### ISSUE THREAD

**Issue by a736730489** [jeecgboot/jeecg-boot#3382]
##### 版本号：
v3.0

##### 问题描述：
当搜索框里只输入 * 时，后台索引越界。
 我的修改：QueryGenerator 类381行  value =  val.length() >=2 ? val.substring(1, val.length() - 1) : "";
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28732971/150090811-8829cf61-9c73-46ea-8b61-ebd9891040fe.png)
![image](https://user-images.githubusercontent.com/28732971/150091011-93bbcd00-eceb-4765-a72f-595f39c0946a.png)

**Comment by zhangdaiscott** [comment]
收录 ty
