### ISSUE TITLE
Excel 导入数据被正则表达式校验住但是不打印错误日志

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#3384]
##### 版本号：
3.0

##### 问题描述：
Excel 导入数据，在实体类定义的时候使用正则表达式做数据校验，校验成功且没有数据插入，但是不打印错误日志，页面提示导入成功 0 条，详情见截图。

##### 截图&代码：
**实体类配置**
![image](https://user-images.githubusercontent.com/48941586/150119585-cd38ec97-1259-4d21-a6a4-d148d3c85c63.png)

**页面提示信息**
![image](https://user-images.githubusercontent.com/48941586/150119687-944662a5-4e8a-4fd0-81f6-8237d1e7f3ee.png)

**校验异常被吞**
![image](https://user-images.githubusercontent.com/48941586/150120336-83500936-7d3c-4caa-b1e8-ac753a1d5413.png)

**尝试添加校验工具类，不生效**
![image](https://user-images.githubusercontent.com/48941586/150120424-73b05f03-79f8-475b-b25c-c0838c9cc431.png)

**控制台输出**
![image](https://user-images.githubusercontent.com/48941586/150120531-2238a121-cbef-49f3-9451-afb74ff4aaa2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
请使用java的语法写，你写的是js下识别的代码
