### ISSUE TITLE
Online树形结构表单，操作里的添加下级按钮无法设置权限

### ISSUE THREAD

**Issue by sxl53037072** [jeecgboot/jeecg-boot#3387]
##### 版本号：
3.0

##### 问题描述：
1. Online树形结构表单，操作里的添加下级按钮无法设置权限，是否有办法设置权限或者直接全局隐藏
2. 只读表单，因为有这个按钮会导致用户可以添加数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/3907037/150317283-20440e4c-059e-4810-be77-0dd23550c7ee.png)

**Comment by zhangdaiscott** [comment]
收录  ty

**Comment by tygithub1** [comment]
已修复
