### ISSUE TITLE
popup选择框，弹出的列表目前是可以多选的，是否能禁止多选，只能单选？

### ISSUE THREAD

**Issue by gyb3320** [jeecgboot/jeecg-boot#3388]
##### 版本号：
V3.0

##### 问题描述：
popup选择框，弹出的列表目前是可以多选的，是否能禁止多选，只能单选？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6359387/150355511-067f902c-b04e-4177-8f4e-00e50b790983.png)
![image](https://user-images.githubusercontent.com/6359387/150355673-073307fd-9a32-4374-aa47-c6360f7649eb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/
