### ISSUE TITLE
增加密码策略建议

### ISSUE THREAD

**Issue by 02Amy** [jeecgboot/jeecg-boot#3389]
##### 问题描述：建议增加环境设置，如密码策略，包括密码设置策略、密码有效期策略、密码异常锁定策略等。
密码设置策略包含密码长度、密码复杂度、密码不能与历史密码相同等；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
平台默认没必要做这么复杂，具体可以按照项目要求自己拓展
