### ISSUE TITLE
展示子表数据接收参数

### ISSUE THREAD

**Issue by lanfengqiuqian** [jeecgboot/jeecg-boot#3395]
##### 版本号：
2.4.0

##### 问题描述：
使用代码生成器能否对于online表单的子表进行生成，或者是功能测试页面能否接收参数

我这边使用生成子表视图的方式生成了子表的页面，但是我想要接收参数，需要展示的数据只是特定的某一个主表的数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
