### ISSUE TITLE
jar 打包运行时，后台报错 Field factory in org.jeecg.modules.system.controller.ThirdLoginController required a bean of type 'com.xkcoding.justauth.AuthRequestFactory' that could not be found.

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#3396]
##### 版本号：
3.0.0

##### 问题描述：
jar 打包运行时，后台报错 
Field factory in org.jeecg.modules.system.controller.ThirdLoginController required a bean of type 'com.xkcoding.justauth.AuthRequestFactory' that could not be found.
##### 截图&代码：

![image](https://user-images.githubusercontent.com/8438712/150950495-f3e0d48a-0319-4d08-84ff-31004be7389e.png)

2022-01-25 16:58:12.083 [main] [34mINFO [0;39m [36mo.s.b.a.l.ConditionEvaluationReportLoggingListener:136[0;39m - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-25 16:58:13.608 [main] [1;31mERROR[0;39m [36mo.s.b.diagnostics.LoggingFailureAnalysisReporter:40[0;39m - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field factory in org.jeecg.modules.system.controller.ThirdLoginController required a bean of type 'com.xkcoding.justauth.AuthRequestFactory' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'authRequestFactory' in 'JustAuthAutoConfiguration' not loaded because @ConditionalOnProperty (justauth.enabled=true) found different value in property 'enabled'

Action:

Consider revisiting the entries above or defining a bean of type 'com.xkcoding.justauth.AuthRequestFactory' in your configuration.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ming820214** [comment]
临时解决办法：我这边临时把有问题的几个点注释掉了。

**Comment by zhangdaiscott** [comment]
yaml少配置了吧

**Comment by ming820214** [comment]
那这个是缺少哪个配置导致的啊？

**Comment by ming820214** [comment]
> yaml少配置了吧

能知道是缺少哪个配置导致的么？

**Comment by alci2014** [comment]
其实已经提示了未能加载的原因的，是justauth.enabled发现了不同的值。
The following candidates were found but could not be injected:
- Bean method 'authRequestFactory' in 'JustAuthAutoConfiguration' not loaded because @ConditionalOnProperty (justauth.enabled=true) **found different value in property 'enabled'**
你应该是修改了配置文档的值 justauth:enabled的值 修改为 justauth:enabled:true 应该就可以了
