### ISSUE TITLE
Online表单 字段href 跳转至组件 失效

### ISSUE THREAD

**Issue by yoyapapa** [jeecgboot/jeecg-boot#3399]
##### 版本号：
3.0

##### 问题描述：
Online在线功能中(默认主题),填写正确的组件地址,如:jeecg/helloworld.vue 或 /jeecg/helloworld.vue 无法实现跳转,提示:Error: Cannot find module './jeecg/helloworld.vue'

##### 截图&代码：
 **1.默认主题** 
    ![默认主题](https://images.gitee.com/uploads/images/2022/0124/014608_3ed76412_4997388.png "屏幕截图.png")

 **2.输入组件地址** 
    ![输入组件地址](https://images.gitee.com/uploads/images/2022/0124/014129_0cd09246_4997388.png "屏幕截图.png")
 **3.显示超链接** 
    ![显示超链接](https://images.gitee.com/uploads/images/2022/0124/014218_4caf40e7_4997388.png "屏幕截图.png")
 **4.点击后显示空白,并输错错误提示** 
    ![点击后显示空白,并输错错误提示](https://images.gitee.com/uploads/images/2022/0124/014311_e03325af_4997388.png "屏幕截图.png")
 **5.错误提示** 
    ![错误提示](https://images.gitee.com/uploads/images/2022/0124/014402_7d7c75cc_4997388.png "屏幕截图.png")

**Comment by zhangdaiscott** [comment]
开源版，暂时不支持
