### ISSUE TITLE
JModal+a-form，弹窗中表单的提交方法1秒内可以迅速点击多次，导致得多次请求

### ISSUE THREAD

**Issue by trampeagler** [jeecgboot/jeecg-boot#3402]
##### 版本号：
2.4.6-beta5

##### 问题描述：
JModal+a-form，弹窗中表单的提交方法1秒内可以迅速点击多次，导致得多次请求

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33918175/152911700-d27d45e9-8e76-4632-8dbe-592dae8b314c.png)

![image](https://user-images.githubusercontent.com/33918175/152911794-bde43ebe-2899-4dfe-af6f-c607aa4f6f73.png)

![image](https://user-images.githubusercontent.com/33918175/152911860-e63d8b39-3df0-4df1-87a7-cedd84ed7adc.png)

![image](https://user-images.githubusercontent.com/33918175/152911899-efd57c49-b0c2-4308-8992-59bfab58a98a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
有严格要求，可以弄个事务锁

**Comment by trampeagler** [comment]
> 有严格要求，可以弄个事务锁

可以举个例子吗

**Comment by trampeagler** [comment]
你们这也没有个使用组件的详细说明啊，什么严格要求，写在哪里了？
