### ISSUE TITLE
自定义导出Map时，字典属性该如何关联

### ISSUE THREAD

**Issue by bangcd999** [jeecgboot/jeecg-boot#3403]
##### 版本号：
3.0

##### 问题描述：
自定义导出时，若想使用 MAP，字典属性该如何关联？  因为默认的是自动执行，没找到 org.jeecg.config.AutoPoiDictConfig 何时调用，请大神帮忙

##### 截图&代码：
![WeChate8fb92e1c1a50985264601329e033008](https://user-images.githubusercontent.com/71172145/153156470-6b7af80f-4633-4cd2-b633-149040d64a97.png)
![WechatIMG564](https://user-images.githubusercontent.com/71172145/153156497-3b12185e-f22f-492f-be1a-3a2060405f05.png)

 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
map不支持，需要自己翻译

**Comment by bangcd999** [comment]
好的，谢谢
