### ISSUE TITLE
Excel导出时如何实现带有下拉框？

### ISSUE THREAD

**Issue by bangcd999** [jeecgboot/jeecg-boot#3404]
##### 版本号：
3.0
##### 问题描述：
现在想实现导出的Excel有下拉框，请问后端改如何操作？；
是在new JeecgMapExcelView()中做操作吗？

##### 截图&代码：
![123](https://user-images.githubusercontent.com/71172145/153320619-a16c68f3-0c64-4f0f-b061-1537a4f232ac.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持，需要自己实现

**Comment by 979943370** [comment]
1，新建类继承 JeecgEntityExcelView
2，重写 renderMergedOutputModel();
适当位置加上
`        Sheet sheetAt = workbook.getSheetAt(0);
        // 设置第0列的2-最后一行行为下拉列表
        CellRangeAddressList regions2 = new CellRangeAddressList(1, sheetAt.getLastRowNum(),0, 0);
        // 创建下拉列表数据
        String[] datas = new String[]{"原有","修改","删除"};
        DVConstraint constraint2 = DVConstraint.createExplicitListConstraint(datas);
        // 绑定
        HSSFDataValidation dataValidation2 = new HSSFDataValidation(regions2, constraint2);
        sheetAt.addValidationData(dataValidation2);
`
