### ISSUE TITLE
登录页面验证码图片无法显示

### ISSUE THREAD

**Issue by hfhgui78** [jeecgboot/jeecg-boot#3405]
##### 截图&代码：
![QQ图片20220210104939](https://user-images.githubusercontent.com/45563728/153327877-32f47e3e-0568-4dc4-aca8-50c9e3044c91.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
说明接口地址不通

**Comment by hfhgui78** [comment]
我在后台代码这台服务器上访问，验证码的图片是可以正常显示的呢？需要如何修改接口地址才能让它在其它电脑上访问都可以正常显示呢

**Comment by xiamy-summer** [comment]
请问下，有解决吗？我也是同样的问题。部署上服务器后，验证码刷新不出来。服务器和服务器之间调用api都可以访问。。
