### ISSUE TITLE
请问Jeecg-Boot 2.0.2 版本如何升级到3.0版本呢？

### ISSUE THREAD

**Issue by hfhgui78** [jeecgboot/jeecg-boot#3407]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/45563728/153366004-1365f497-ca8b-4f82-9453-5cc9ac6a740d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/blob/master/jeecg-boot/db/%E5%A2%9E%E9%87%8FSQL/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.txt
