### ISSUE TITLE
online表单开发：当变更了数据库字段名称后，字段变更生效，但是数据库数据全部丢失

### ISSUE THREAD

**Issue by RobbieRain** [jeecgboot/jeecg-boot#3408]
##### 版本号：
3.0

##### 问题描述：

online表单开发：当变更了数据库字段名称后，字段变更生效，但是数据库数据全部丢失

##### 截图&代码：
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/23087721/153374238-f341c9d4-7ef4-40f8-89dc-5fb4e4316479.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么数据库？什么类型字段？怎么个变更情况

**Comment by RobbieRain** [comment]
MySql数据库，字段类型：date型
原来字段名：product_cuishu_start  改成 product_start，其他信息未变

**Comment by zhangdaiscott** [comment]
未重现
