### ISSUE TITLE
字段Href跳转建菜单以后失效

### ISSUE THREAD

**Issue by ryuukisei** [jeecgboot/jeecg-boot#3409]
##### 版本号：
3.0

##### 问题描述：
Online在线功能生成表，配置了字段跳转到其他表，在功能测试里面可以跳转，但是生成代码并创建菜单以后跳转失效。
（未使用微服务相关功能）

##### 截图&代码：
建表时的字段href
![20352ae05dd2e932c604adad24ff70e](https://user-images.githubusercontent.com/56123273/153526453-3b9af470-d103-46ab-8304-cde42832ff7f.png)
这是功能测试时有跳转表的功能（字段是蓝色的）：
![7fce884b03908c8ce2aa867cb3a3ee0](https://user-images.githubusercontent.com/56123273/153526570-27c014bf-2afc-40b5-af64-326f30e57ea5.png)
这是生成代码并且创建菜单之后，菜单中的表，失去了跳转功能（插入字段的数据变为黑色，点击以后不能跳转，此时功能测试仍然是正常的，也是可以跳转的但是菜单里面是无法跳转的）。
![e972c3c75b45de754530ed5fc56cd7e](https://user-images.githubusercontent.com/56123273/153526837-f443c1c5-a0aa-4d7b-b69e-2d5daea52f3f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by JiaziJia** [comment]
博主知道是什么问题吗？遇到了相同的问题，求教

**Comment by xu-my** [comment]
不支持
