### ISSUE TITLE
附表的权限控制没有按钮权限和数据权限

### ISSUE THREAD

**Issue by flywalker** [jeecgboot/jeecg-boot#3410]
##### 问题描述：
主表的权限控制有字段权限、按钮权限和数据权限
附表的权限控制只有字段权限，没有按钮权限和数据权限

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
附表没做数据权限逻辑

**Comment by PingZiXianSheng** [comment]
同问 如何解决 这新版的反而没有老版的好用了？
