### ISSUE TITLE
查询排序配置"orderRule"不生效

### ISSUE THREAD

**Issue by patrickhu1** [jeecgboot/jeecg-boot#3412]
##### 版本号：
jeecg-boot 3.0

##### 问题描述：
按照文档配置后，查询排序依然使用id倒序，排序配置没有生效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/153564966-39969fa8-cb8e-4f0b-a851-3609087eb2de.png)
![image](https://user-images.githubusercontent.com/26364818/153565107-b9f81745-20e7-4d7d-b896-3d348254a593.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
确定是3.0版本?

**Comment by patrickhu1** [comment]
在在线演示可以复现这个问题，以项目信息表为例
![image](https://user-images.githubusercontent.com/26364818/153604063-202fb06d-db11-4dc0-b940-e4bf06bcfbc1.png)

![image](https://user-images.githubusercontent.com/26364818/153604003-c872ba90-1b5a-4baa-95f5-7374637ca120.png)

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
请查实最新版本3.1.0

**Comment by softboy99** [comment]
3.7.1依然有问题：

是否是从表的问题？
现象：从表，对应字段设置不可见
![Image](https://github.com/user-attachments/assets/239a7aa7-6593-4036-ad66-6be154c9a858)

![Image](https://github.com/user-attachments/assets/79967fee-0ffb-4d84-b258-8719432e4e38)

![Image](https://github.com/user-attachments/assets/8935bbfa-f76b-41ec-a4e8-a4b1ca65fd28)
