### ISSUE TITLE
在线生成的表单，列表表格内容如何设置左对齐显示

### ISSUE THREAD

**Issue by RobbieRain** [jeecgboot/jeecg-boot#3417]
##### 版本号：
3.0

##### 问题描述：
在线生成的表单，列表表格内容如何设置左对齐显示

##### 截图&代码：
当前是这样的，希望可以设置左对齐：
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/23087721/154209950-6431aa7d-e5ad-4e61-a6a9-dea678e99585.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
没有这个功能
