### ISSUE TITLE
多数据源获取，代码问题咨询，感谢官方，永久支持

### ISSUE THREAD

**Issue by javazhijia** [jeecgboot/jeecg-boot#3418]
##### 版本号：
最新版本

##### 问题描述：
我现在从缓存中获取数据源信息，获取到的信息是空的，jeecg这个框架是在哪里把数据源放到缓存中的啊？排查了好长时间代码，只看到从缓存中拿和删除了，但是没发现在哪统一初始化进去的啊 能给说一下具体的代码位置和实现逻辑吗，感谢官方，永久支持。

##### 截图&代码：
![$3JB6GU 750W4 TEPMV7T@Q](https://user-images.githubusercontent.com/89176465/154413654-1387d6a0-474c-443b-b774-4d7e8b3a04b7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/155648087-66300bc5-c6de-4e6a-860c-17d77746b3e9.png)

**Comment by zhangdaiscott** [comment]
在线数据源编辑的时候，会清空缓存。如果你是手工改的数据库就会出问题
