### ISSUE TITLE
2.4.0版本通过扩展参数限制大文本在列表页面的展示长度不生效

### ISSUE THREAD

**Issue by Moe-Shiro** [jeecgboot/jeecg-boot#3419]
##### 截图&代码：
使用http://doc.jeecg.com/2044137#_21此文档的配置方法
![image](https://user-images.githubusercontent.com/50688978/154446114-88a42e3d-27d1-4be5-8027-1814222c751d.png)
![image](https://user-images.githubusercontent.com/50688978/154446250-08b5d0ec-8bff-47bb-b9dd-95b375eb5a87.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请尝试最新版
