### ISSUE TITLE
online在线生成小问题

### ISSUE THREAD

**Issue by IzayuiAki** [jeecgboot/jeecg-boot#3420]
##### 版本号：
3.0.0

##### 问题描述：
online在线生成代码存在部分问题

##### 截图&代码：
1. 树表查询，查询子节点时，树结构无法自动展开并定位到被查询的子节点
![image](https://user-images.githubusercontent.com/90434101/154449787-6b6196c6-91bf-4331-adc4-fb77b1bef680.png)

2. ERP风格，无法对附表进行过滤查询
![image](https://user-images.githubusercontent.com/90434101/154450278-e601d9bb-715d-4336-bcde-b09adbcfb163.png)

3. JVXE风格，数据详情页【删除】按钮依然可以点击
![image](https://user-images.githubusercontent.com/90434101/154450541-52b181af-81a0-4bd9-845d-14b2f43c4d74.png)

4. 内嵌风格，datetime控件样式异常
![image](https://user-images.githubusercontent.com/90434101/154450675-622df713-b921-462a-b250-75508763523c.png)

5. TAB风格，主表数据记录【操作】项中没有【详情】
![image](https://user-images.githubusercontent.com/90434101/154450943-9bf28c93-91f2-4993-a4c9-4da09b9f2a36.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by zhangdaiscott** [comment]
2不改
