### ISSUE TITLE
前端build后，logo出不来，登录成功，但是进不去首页

### ISSUE THREAD

**Issue by 552103917** [jeecgboot/jeecg-boot#3423]
##### 版本号：
2.4.6

##### 问题描述：
前端build后，logo出不来，
登录成功，但是进不去首页

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46283039/154613258-5ffd5fc9-07da-4493-98a0-990e8f360c62.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这种问题应该自己环境没弄好，自己排查

**Comment by 552103917** [comment]
你好，应该不是。jeecgboot其它版本我们也用过，打包之后是没问题的。这个版本根据vue.config.js里提示，放开这个配置，登录就登不进首页，还有登录页logo显示不出来
//打包app时放开该配置
publicPath:'./',



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 前端build后，logo出不来，登录成功，但是进不去首页 (Issue #3423)





 
这种问题应该自己环境没弄好，自己排查
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
