### ISSUE TITLE
后台第三方登录-企业微信

### ISSUE THREAD

**Issue by wl0927** [jeecgboot/jeecg-boot#3430]
##### 问题描述：
Illegal state [WECHAT_ENTERPRISE]  偶尔会出这个问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/40060109/154657661-98e2858a-b191-42b8-a1b2-bb9590d3f225.png)

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
没有复现这个问题，请提供更详细的复现步骤

**Comment by Duanhuihui** [comment]
请问问题解决了吗，是如何解决的。我也遇到了
