### ISSUE TITLE
省市县级联查询数据源

### ISSUE THREAD

**Issue by arno-yu** [jeecgboot/jeecg-boot#3431]
##### 版本号：
3.0

##### 问题描述：

省市县级联的数据源是否可以进行替换?
目前数据来源是民政部,我想修改为国家标准GB/T 2260-2007的现行内容
我个人对vue不是很懂.目前找到了数据源可是没办法进行替换
目前省市县的数据是来自[http://www.mca.gov.cn/article/sj/xzqh/1980/](https://gitee.com/link?target=http%3A%2F%2Fwww.mca.gov.cn%2Farticle%2Fsj%2Fxzqh%2F1980%2F)

而根据标准:http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=C9C488FD717AFDCD52157F41C3302C6D
##### 截图&代码：

![image](https://user-images.githubusercontent.com/43564552/154657867-513605ac-cf32-4e67-bb87-b1cbed7dad59.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以替换

**Comment by arno-yu** [comment]
我应该如何替换他？

**Comment by arno-yu** [comment]
> 可以替换

我应该如何替换他？
