### ISSUE TITLE
Online表单配置界面-检验字段tab-字段href 传参无效

### ISSUE THREAD

**Issue by mapleafly** [jeecgboot/jeecg-boot#3432]
##### 版本号：
3.0

##### 问题描述：
字段href中填写路由如下：
     /online/cgformList/6d3bf1a8cd3f4667948cb96763abca23?name=${name}
其中name参数不起作用。页面显示全部信息。

论坛中一位大侠的解决办法在被调页面中添加js加强：
created(){
  let name = that.$route.query.name
  console.log('$route name: ', name);
  that.queryParam={name:name};
}

**Comment by zhangdaiscott** [comment]
其中name参数不起作用是什么意思？你想传到查询条件里面？

**Comment by tygithub1** [comment]
并不是说你传个name我就把name拿到去作查询，只有被传值的表单 有name这个字段，然后name还需要设置成查询条件，才能支持参数的传递
