### ISSUE TITLE
积木报表参数传递后读取到的是变量名字而不是变量值

### ISSUE THREAD

**Issue by CNBruceLee** [jeecgboot/jeecg-boot#3433]
##### 版本号：
 <jeecgboot.version>2.4.6</jeecgboot.version>

##### 问题描述：
积木报表传递动态参数后台识别为变量名

##### 截图&代码：
积木报表sql
![image](https://user-images.githubusercontent.com/44367792/154782311-aff2b5c5-a80f-42dd-8c33-96800f93847e.png)
参数设置
![image](https://user-images.githubusercontent.com/44367792/154782322-1421f6e7-7eb1-4286-a4c2-74250cff2614.png)

后台识别到的SQL
![image](https://user-images.githubusercontent.com/44367792/154782361-0512c3d5-6030-4c93-a5c9-4ab6c43466ba.png)

这个是配置不对吗？还是bug，原先想做时间区间查询的，结果一直没有实现，经查看后台读出来的是变量的名字，而不是变量值

**Comment by zhangdaiscott** [comment]
不够详细，怎么用的？

**Comment by CNBruceLee** [comment]
今天恢复场景时，使用动态参数又可以了，后台可以正常接收到参数的值，后边问题再重现后我再提交详细说明。感谢你们的开源付出
![image](https://user-images.githubusercontent.com/44367792/155332539-c75d15ab-9afb-41e7-9249-8c4246a262dc.png)

**Comment by BO-DI** [comment]
> 今天恢复场景时，使用动态参数又可以了，后台可以正常接收到参数的值，后边问题再重现后我再提交详细说明。感谢你们的开源付出 ![image](https://user-images.githubusercontent.com/44367792/155332539-c75d15ab-9afb-41e7-9249-8c4246a262dc.png)

请问api数据集在查询项的参数配置里可以接收动态传参吗？比如如下参数改成变量，从业务系统中接收？
![image](https://github.com/user-attachments/assets/ee73e82d-62d4-48cd-8197-9f37108dfb17)
