### ISSUE TITLE
查询条件的值为等号（=）bug

### ISSUE THREAD

**Issue by keith-ch** [jeecgboot/jeecg-boot#3443]
##### 版本号：
3.0.0
##### 问题描述：
当字段值为“=”时，查询会把这个=给移除掉

##### 截图&代码：
页面截图：条件选择了“=”，查出来多余的数据
![企业微信截图_16454931266110](https://user-images.githubusercontent.com/15343645/155046557-07876356-feba-4870-b565-8a53d809e73e.png)
bug代码：https://github.com/jeecgboot/jeecg-boot/blob/master/jeecg-boot/jeecg-boot-base/jeecg-boot-base-core/src/main/java/org/jeecg/common/system/query/QueryGenerator.java

**Comment by zhangdaiscott** [comment]
收录 ty
