### ISSUE TITLE
linux maven构建,启动cloud-gateway 出现 FeignConfig 重复注册 

### ISSUE THREAD

**Issue by DaGou12138** [jeecgboot/jeecg-boot#3444]
##### 版本号：
2.4.6

##### 问题描述：
使用cloud模式启动cloud-gateway，linux maven构建出现 FeignConfig 重复注册，Windows本地启动无问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34116092/155050125-34293b97-28be-4d86-9ca9-147b7f5d3cec.png)

**Comment by zhangdaiscott** [comment]
给yml配置文件加上，这个 配置参数
![image](https://user-images.githubusercontent.com/3162115/155146452-388465c4-bbb0-4c1c-a2bc-1c1079666ddf.png)

**Comment by DaGou12138** [comment]
加了配置后也无效，目前我的方案是将工程jeecg-boot-starter-cloud的FeignConfig类中的bean的feignDecoder重命名并设置优先级，但不知道有无问题。
![image](https://user-images.githubusercontent.com/34116092/155160685-6a436158-db5e-4175-bc6c-6c23286cf6da.png)
