### ISSUE TITLE
jeecgboot启动时 mongodb 连接超时

### ISSUE THREAD

**Issue by weiwang988** [jeecgboot/jeecg-boot#3445]
##### 版本号：
>2.4.0

##### 问题描述：
jeecgboot启动时 mongodb 连接超时，由于没有使用mongodb，是否可以在配置文件里更改配置，启动时不加载mongodb 

##### 截图&代码：
![1645497711(1)](https://user-images.githubusercontent.com/58241726/155053478-496530ae-b771-40d5-801b-0e1920e1b850.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
忽略即可，或者参考最新版启动类加上排除mogo的类
