### ISSUE TITLE
mysql切换到postgresql之后不会导入数据

### ISSUE THREAD

**Issue by klhgithub** [jeecgboot/jeecg-boot#3446]
##### 版本号：
3.0

##### 问题描述：
用mysql的时候有jeecgboot-mysql-5.7.sql直接导入数据到数据库。现在切换到了postgresql数据库，感觉少了个jeecgboot-postgresql.sql文件。因为不知道怎么从mysql转到postgresql。求助

**Comment by zhangdaiscott** [comment]
自己通过navicat转

**Comment by chenchangqing** [comment]
<img width="998" alt="Screenshot 2024-10-03 at 19 27 34" src="https://github.com/user-attachments/assets/ca333a8f-23e2-4926-b53d-691c2144bbdb">
请问转postgresql 17出现这样的错误该如何解决？
