### ISSUE TITLE
gateway整合Hystrix 配置未启用

### ISSUE THREAD

**Issue by g9420** [jeecgboot/jeecg-boot#3447]
##### 问题描述：
新增文件上传file服务，针对该服务单独配置熔断时间，配置未生效，可以帮忙看下吗，yml配置如下

##### 截图&代码：
![91XJP H_O5ZF$Q}76G%TQW](https://user-images.githubusercontent.com/41284829/155140779-34782379-8cef-4382-983a-29afc278d27b.png)
![6G{}{2V8TH`9}YJUVNK_L9G](https://user-images.githubusercontent.com/41284829/155140792-17079219-1dbc-4588-9880-30de478cbde2.png)
![image](https://user-images.githubusercontent.com/41284829/155140877-5ede20da-4864-482e-a76c-9ad200cc2be7.png)
![image](https://user-images.githubusercontent.com/41284829/155140920-3d15874b-cc84-4f6a-9fef-7311b5216e2d.png)
![image](https://user-images.githubusercontent.com/41284829/155140941-51edb81e-2ea9-4b41-89be-44b6c13f6b65.png)

**Comment by zhangdaiscott** [comment]
收录 yf

**Comment by accpman** [comment]
![image](https://user-images.githubusercontent.com/4446237/156115560-053589d2-49ed-4483-8665-54828ba78098.png)
把全局熔断配置去掉
