### ISSUE TITLE
jar部署到winserver2012 r2 上面服务器上的服务不定时停止

### ISSUE THREAD

**Issue by yankangZhou** [jeecgboot/jeecg-boot#3449]
##### 版本号：
2.2.1

##### 问题描述：
jar部署到winserver2012 r2 上面服务器上的服务不定时停止。log日志如下。请指导调查方向谢谢。

##### 截图&代码：

#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 32744 bytes for ChunkPool::allocate
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
#   JVM is running with Unscaled Compressed Oops mode in which the Java heap is
#     placed in the first 4GB address space. The Java Heap base address is the
#     maximum limit for the native heap growth. Please use -XX:HeapBaseMinAddress
#     to set the Java Heap base and to place the Java Heap above 4GB virtual address.
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (allocation.cpp:272), pid=102752, tid=0x0000000000008d20
#
# JRE version: Java(TM) SE Runtime Environment (8.0_321-b07) (build 1.8.0_321-b07)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.321-b07 mixed mode windows-amd64 compressed oops)
# Core dump written. Default location: D:\web-project\service\hs_err_pid102752.mdmp
#

---------------  T H R E A D  ---------------

Current thread (0x0000009e9c3a9000):  JavaThread "C1 CompilerThread1" daemon [_thread_in_native, id=36128, stack(0x0000009e9d060000,0x0000009e9d160000)]

Stack: [0x0000009e9d060000,0x0000009e9d160000]
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x32fc49]
V  [jvm.dll+0x2761a2]
V  [jvm.dll+0x276e4d]
V  [jvm.dll+0x26d7f5]
V  [jvm.dll+0xd5ead]
V  [jvm.dll+0xd620c]
V  [jvm.dll+0x3f9db3]
V  [jvm.dll+0x3f9e80]
V  [jvm.dll+0x3fc41d]
V  [jvm.dll+0x3fe3d9]
V  [jvm.dll+0x3e1ddf]
V  [jvm.dll+0x3e164d]
V  [jvm.dll+0x3e182e]
V  [jvm.dll+0x3e0f81]
V  [jvm.dll+0x3e29bf]
V  [jvm.dll+0xac68b]
V  [jvm.dll+0xaaceb]
V  [jvm.dll+0x23e6f2]
V  [jvm.dll+0x292edc]
C  [ucrtbase.DLL+0x1f4a0]
C  [KERNEL32.DLL+0x13f2]
C  [ntdll.dll+0x154f4]

Current CompileTask:
C1:294495809 33096   !   3       org.jeecg.modules.system.service.impl.SysDictServiceImpl$$FastClassBySpringCGLIB$$b9b72399::invoke (1341 bytes)

---------------  P R O C E S S  ---------------

Java Threads: ( => current thread )
  0x000000a63ac43800 JavaThread "Thread-43295" daemon [_thread_in_vm, id=126776, stack(0x000000a97a2e0000,0x000000a97a3e0000)]
  0x000000a968c4d800 JavaThread "Thread-43294" daemon [_thread_in_vm, id=7404, stack(0x000000a958010000,0x000000a958110000)]

  0x000000a718040800 JavaThread "Thread-40551" [_thread_blocked, id=174272, stack(0x000000a8c9bd0000,0x000000a8c9cd0000)]
  0x000000a718041800 JavaThread "Thread-40550" [_thread_blocked, id=180496, stack(0x000000a8c9ad0000,0x000000a8c9bd0000)]
  0x000000a71803a800 JavaThread "Thread-40549" [_thread_blocked, id=130432, stack(0x000000a8c99d0000,0x000000a8c9ad0000)]
  0x000000a71803d800 JavaThread "Thread-40548" [_thread_blocked, id=142248, stack(0x000000a8c98d0000,0x000000a8c99d0000)]
  0x000000a71803c800 JavaThread "Thread-40547" [_thread_blocked, id=39428, stack(0x000000a8c97d0000,0x000000a8c98d0000)]
  0x000000a71803b000 JavaThread "Thread-40546" [_thread_blocked, id=74780, stack(0x000000a8c96d0000,0x000000a8c97d0000)]
  0x000000a718039800 JavaThread "Thread-40545" [_thread_blocked, id=2624, stack(0x000000a8c95d0000,0x000000a8c96d0000)]
  0x000000a71803c000 JavaThread "Thread-40544" [_thread_blocked, id=143652, stack(0x000000a8c94d0000,0x000000a8c95d0000)]
  0x000000a718037800 JavaThread "Thread-40543" [_thread_blocked, id=167392, stack(0x000000a8c93d0000,0x000000a8c94d0000)]
  0x000000a718036800 JavaThread "Thread-40542" [_thread_blocked, id=131652, stack(0x000000a8c92d0000,0x000000a8c93d0000)]
  0x000000a718036000 JavaThread "Thread-40541" [_thread_blocked, id=124588, stack(0x000000a8c91d0000,0x000000a8c92d0000)]
  0x000000a718039000 JavaThread "Thread-40540" [_thread_blocked, id=106844, stack(0x000000a8c90d0000,0x000000a8c91d0000)]
  0x000000a718035000 JavaThread "Thread-40539" [_thread_blocked, id=135552, stack(0x000000a8c8fd0000,0x000000a8c90d0000)]
  0x000000a718038000 JavaThread "Thread-40538" [_thread_blocked, id=41112, stack(0x000000a8c8ed0000,0x000000a8c8fd0000)]
  0x000000a718031800 JavaThread "Thread-40537" [_thread_blocked, id=150940, stack(0x000000a8c8dd0000,0x000000a8c8ed0000)]
  0x000000a718034800 JavaThread "Thread-40536" [_thread_blocked, id=15904, stack(0x000000a8c8cd0000,0x000000a8c8dd0000)]
  0x000000a718030800 JavaThread "Thread-40535" [_thread_blocked, id=158936, stack(0x000000a8c8bd0000,0x000000a8c8cd0000)]
  0x000000a718033800 JavaThread "Thread-40534" [_thread_blocked, id=74240, stack(0x000000a8c8ad0000,0x000000a8c8bd0000)]
  0x000000a718030000 JavaThread "Thread-40533" [_thread_blocked, id=119380, stack(0x000000a8c89d0000,0x000000a8c8ad0000)]
  0x000000a718032000 JavaThread "Thread-40532" [_thread_blocked, id=12680, stack(0x000000a8c88d0000,0x000000a8c89d0000)]
  0x000000a718033000 JavaThread "Thread-40531" [_thread_blocked, id=171648, stack(0x000000a8c87d0000,0x000000a8c88d0000)]
  0x000000a71802c000 JavaThread "Thread-40530" [_thread_blocked, id=163668, stack(0x000000a8c86d0000,0x000000a8c87d0000)]
  0x000000a71802d800 JavaThread "Thread-40529" [_thread_blocked, id=40372, stack(0x000000a8c85d0000,0x000000a8c86d0000)]
  0x000000a71802e800 JavaThread "Thread-40528" [_thread_blocked, id=105780, stack(0x000000a8c84d0000,0x000000a8c85d0000)]
  0x000000a71802f000 JavaThread "Thread-40527" [_thread_blocked, id=45172, stack(0x000000a8c83d0000,0x000000a8c84d0000)]
  0x000000a71802a000 JavaThread "Thread-40526" [_thread_blocked, id=118680, stack(0x000000a8c82d0000,0x000000a8c83d0000)]
  0x000000a71802d000 JavaThread "Thread-40525" [_thread_blocked, id=20080, stack(0x000000a8c81d0000,0x000000a8c82d0000)]
  0x000000a718029000 JavaThread "Thread-40524" [_thread_blocked, id=168424, stack(0x000000a8c80d0000,0x000000a8c81d0000)]
  0x000000a718028800 JavaThread "Thread-40523" [_thread_blocked, id=15180, stack(0x000000a8c7fd0000,0x000000a8c80d0000)]
  0x000000a71802b800 JavaThread "Thread-40522" [_thread_blocked, id=114728, stack(0x000000a8c7ed0000,0x000000a8c7fd0000)]
  0x000000a71802a800 JavaThread "Thread-40521" [_thread_blocked, id=25044, stack(0x000000a8c7dd0000,0x000000a8c7ed0000)]
  0x000000a718025800 JavaThread "Thread-40520" [_thread_blocked, id=27912, stack(0x000000a8c7cd0000,0x000000a8c7dd0000)]
  0x000000a718026000 JavaThread "Thread-40519" [_thread_blocked, id=151080, stack(0x000000a8c7bd0000,0x000000a8c7cd0000)]
  0x000000a718027800 JavaThread "Thread-40518" [_thread_blocked, id=74176, stack(0x000000a8c7ad0000,0x000000a8c7bd0000)]
  0x000000a718024000 JavaThread "Thread-40517" [_thread_blocked, id=29972, stack(0x000000a8c79d0000,0x000000a8c7ad0000)]
  0x000000a718027000 JavaThread "Thread-40516" [_thread_blocked, id=121120, stack(0x000000a8c78d0000,0x000000a8c79d0000)]
  0x000000a718021800 JavaThread "Thread-40515" [_thread_blocked, id=26136, stack(0x000000a8c77d0000,0x000000a8c78d0000)]
  0x000000a718023000 JavaThread "Thread-40514" [_thread_blocked, id=124304, stack(0x000000a8c76d0000,0x000000a8c77d0000)]
  0x000000a718022800 JavaThread "Thread-40513" [_thread_blocked, id=65256, stack(0x000000a8c75d0000,0x000000a8c76d0000)]
  0x000000a718024800 JavaThread "Thread-40512" [_thread_blocked, id=129036, stack(0x000000a8c74d0000,0x000000a8c75d0000)]
  0x000000a718021000 JavaThread "Thread-40511" [_thread_blocked, id=180248, stack(0x000000a8c73d0000,0x000000a8c74d0000)]
  0x000000a71801d000 JavaThread "Thread-40510" [_thread_blocked, id=121292, stack(0x000000a8c72d0000,0x000000a8c73d0000)]
  0x000000a718020000 JavaThread "Thread-40509" [_thread_blocked, id=58148, stack(0x000000a8c71d0000,0x000000a8c72d0000)]
  0x000000a71801c800 JavaThread "Thread-40508" [_thread_blocked, id=108932, stack(0x000000a8c70d0000,0x000000a8c71d0000)]
  0x000000a71801f800 JavaThread "Thread-40507" [_thread_blocked, id=168684, stack(0x000000a8c6fd0000,0x000000a8c70d0000)]
  0x000000a71801e000 JavaThread "Thread-40506" [_thread_blocked, id=95816, stack(0x000000a8c6ed0000,0x000000a8c6fd0000)]
  0x000000a71801e800 JavaThread "Thread-40505" [_thread_blocked, id=160904, stack(0x000000a8c6dd0000,0x000000a8c6ed0000)]
  0x000000a71801b800 JavaThread "Thread-40504" [_thread_blocked, id=105532, stack(0x000000a8c6cd0000,0x000000a8c6dd0000)]
  0x000000a71801a000 JavaThread "Thread-40503" [_thread_blocked, id=152440, stack(0x000000a8c6bd0000,0x000000a8c6cd0000)]
  0x000000a71801b000 JavaThread "Thread-40502" [_thread_blocked, id=6840, stack(0x000000a8c6ad0000,0x000000a8c6bd0000)]
  0x000000a718018000 JavaThread "Thread-40501" [_thread_blocked, id=62836, stack(0x000000a8c69d0000,0x000000a8c6ad0000)]
  0x000000a718019800 JavaThread "Thread-40500" [_thread_blocked, id=160344, stack(0x000000a8c68d0000,0x000000a8c69d0000)]
  0x000000a718016800 JavaThread "Thread-40499" [_thread_blocked, id=17544, stack(0x000000a8c67d0000,0x000000a8c68d0000)]
  0x000000a718015800 JavaThread "Thread-40498" [_thread_blocked, id=131708, stack(0x000000a8c66d0000,0x000000a8c67d0000)]
  0x000000a718018800 JavaThread "Thread-40497" [_thread_blocked, id=73420, stack(0x000000a8c65d0000,0x000000a8c66d0000)]
  0x000000a718017000 JavaThread "Thread-40496" [_thread_blocked, id=86716, stack(0x000000a8c64d0000,0x000000a8c65d0000)]
  0x000000a718015000 JavaThread "Thread-40495" [_thread_blocked, id=23220, stack(0x000000a8c63d0000,0x000000a8c64d0000)]
  0x000000a718014000 JavaThread "Thread-40494" [_thread_blocked, id=79780, stack(0x000000a8c62d0000,0x000000a8c63d0000)]
  0x000000a718013800 JavaThread "Thread-40493" [_thread_blocked, id=43652, stack(0x000000a8c61d0000,0x000000a8c62d0000)]
  0x000000a237af4000 JavaThread "Thread-40492" [_thread_blocked, id=51772, stack(0x000000a8c60d0000,0x000000a8c61d0000)]
  0x000000a237af0800 JavaThread "Thread-40491" [_thread_blocked, id=123500, stack(0x000000a8c5fd0000,0x000000a8c60d0000)]
  0x000000a237af1000 JavaThread "Thread-40490" [_thread_blocked, id=155044, stack(0x000000a8c5ed0000,0x000000a8c5fd0000)]
  0x000000a237af3800 JavaThread "Thread-40489" [_thread_blocked, id=90772, stack(0x000000a8c5dd0000,0x000000a8c5ed0000)]
  0x000000a237af2000 JavaThread "Thread-40488" [_thread_blocked, id=32324, stack(0x000000a8c5cd0000,0x000000a8c5dd0000)]
  0x000000a237af2800 JavaThread "Thread-40487" [_thread_blocked, id=43392, stack(0x000000a8c5bd0000,0x000000a8c5cd0000)]
  0x000000a237aef800 JavaThread "Thread-40486" [_thread_blocked, id=107836, stack(0x000000a8c5ad0000,0x000000a8c5bd0000)]
  0x000000a237aef000 JavaThread "Thread-40485" [_thread_blocked, id=65028, stack(0x000000a8c59d0000,0x000000a8c5ad0000)]
  0x000000a237aee000 JavaThread "Thread-40484" [_thread_blocked, id=44808, stack(0x000000a8c58d0000,0x000000a8c59d0000)]
  0x000000a237aeb000 JavaThread "Thread-40483" [_thread_blocked, id=167536, stack(0x000000a8c57d0000,0x000000a8c58d0000)]
  0x000000a237aed800 JavaThread "Thread-40482" [_thread_blocked, id=62032, stack(0x000000a8c56d0000,0x000000a8c57d0000)]
  0x000000a237aea800 JavaThread "Thread-40481" [_thread_blocked, id=21876, stack(0x000000a8c55d0000,0x000000a8c56d0000)]
  0x000000a237aec800 JavaThread "Thread-40480" [_thread_blocked, id=172700, stack(0x000000a8c54d0000,0x000000a8c55d0000)]
  0x000000a237aec000 JavaThread "Thread-40479" [_thread_blocked, id=111948, stack(0x000000a8c53d0000,0x000000a8c54d0000)]
  0x000000a237ae9800 JavaThread "Thread-40478" [_thread_blocked, id=133324, stack(0x000000a8c52d0000,0x000000a8c53d0000)]
  0x000000a237ae9000 JavaThread "Thread-40477" [_thread_blocked, id=17064, stack(0x000000a8c51d0000,0x000000a8c52d0000)]
  0x000000a237ae5000 JavaThread "Thread-40476" [_thread_blocked, id=180740, stack(0x000000a8c50d0000,0x000000a8c51d0000)]
  0x000000a237ae8000 JavaThread "Thread-40475" [_thread_blocked, id=5336, stack(0x000000a8c4fd0000,0x000000a8c50d0000)]
  0x000000a237ae7800 JavaThread "Thread-40474" [_thread_blocked, id=74580, stack(0x000000a8c4ed0000,0x000000a8c4fd0000)]
  0x000000a237ae6800 JavaThread "Thread-40473" [_thread_blocked, id=39160, stack(0x000000a8c4dd0000,0x000000a8c4ed0000)]
  0x000000a237ae6000 JavaThread "Thread-40472" [_thread_blocked, id=102320, stack(0x000000a8c4cd0000,0x000000a8c4dd0000)]
  0x000000a237ae4800 JavaThread "Thread-40471" [_thread_blocked, id=160052, stack(0x000000a8c4bd0000,0x000000a8c4cd0000)]
  0x000000a237ae3800 JavaThread "Thread-40470" [_thread_blocked, id=13916, stack(0x000000a8c4ad0000,0x000000a8c4bd0000)]
  0x000000a237adf800 JavaThread "Thread-40469" [_thread_blocked, id=94344, stack(0x000000a8c49d0000,0x000000a8c4ad0000)]
  

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
内存溢出？

**Comment by yankangZhou** [comment]
是的啊  我们尝试了些解决办法都没啥效果。请问有什么好的建议调查思路没啊？

**Comment by zhangdaiscott** [comment]
启动的时候设置下内存参数，正常是不需要设置，只有服务器内存够就没问题
