### ISSUE TITLE
jeecg-cloud-system-start怎样可以引用jeecg-system-cloud-api

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3450]
##### 版本号：
2.4.6

##### 问题描述：
jeecg-cloud-system-start怎样可以引用jeecg-system-cloud-api

##### 截图&代码：

![1645599925](https://user-images.githubusercontent.com/44563730/155274562-0c89ff15-bccc-4002-9826-ed51b5a9db1c.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
设计是不允许的，你为什么有这样的需求，自己调自己？
