### ISSUE TITLE
单体应用 数据表主键使用自增ID

### ISSUE THREAD

**Issue by chenlvzhou** [jeecgboot/jeecg-boot#3452]
##### 问题描述：
使用代码生成器生成的entity文件，ID是全局唯一的，但是我现在想改为自增的，

##### 截图&代码：
<img width="859" alt="image" src="https://user-images.githubusercontent.com/6197469/155280874-1f9fc938-3a83-439d-9960-55775e8e2653.png">
重新生成表之后，ID还是字符串类型，打开code-template文件之后才发现@TableId(type = IdType.ASSIGN_ID)是写死的
<img width="663" alt="image" src="https://user-images.githubusercontent.com/6197469/155281068-bc345406-9df5-41f7-8c48-cfbc51be09e8.png">

请问：如果单体应用下，我的ID想用Int类型的自增主键，必须修改模板文件吗？

**Comment by zhangdaiscott** [comment]
你可以直接改代码生成器的模板，或者修改生成后的代码
