### ISSUE TITLE
不能从详情关联的表单数据直接跳转到对应数据的详情吗？

### ISSUE THREAD

**Issue by lkh1255056405** [jeecgboot/jeecg-boot#3453]
##### 问题描述：
online表单-下拉框等直接关联其他表单的控件，从数据库查的数据保存着数据id，查看详情时不能跳转到对应表单的详情吗?href好像只能跳转到列表页

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不能

**Comment by lkh1255056405** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/1480  我说的是这个功能吧，能实现？列表如果可以，详情里面呢
