### ISSUE TITLE
新增角色报错

### ISSUE THREAD

**Issue by chenlvzhou** [jeecgboot/jeecg-boot#3457]
##### 问题描述：
按照文档打包完成，部署到线上之后，新增角色报错，但是在开发环境下没有报错，
报错的内容：
{"success":false,"message":"操作失败，Required request body is missing: public org.jeecg.common.api.vo.Result<org.jeecg.modules.system.entity.SysRole> org.jeecg.modules.system.controller.SysRoleController.add(org.jeecg.modules.system.entity.SysRole)","code":500,"result":null,"timestamp":1645777863255}

##### 截图&代码：
curl 'http://127.0.0.1/jeecg-boot/sys/role/add' \
  -X 'POST' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'X-TIMESTAMP: 20220225163103' \
  -H 'X-Sign: 38975B12E4525D81D84B03B0F1AEEF58' \
  -H 'tenant-id: 0' \
  -H 'X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDU3Nzk2MjMsInVzZXJuYW1lIjoiYWRtaW4ifQ.ses0U-ufmhsgkXxtBGcvWfZ-n119OaJcGoZqGAWKJXE' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Origin: http://127.0.0.1' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://127.0.0.1/' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,mt;q=0.6' \
  --compressed

发现缺少了--data-raw这个节点。

**Comment by zhangdaiscott** [comment]
不会有这么低级的问题，确认下自己的编译是否有问题
