### ISSUE TITLE
前端首页打开非常慢，发现有个app.js 的文件在一直加载，而且文件非常大（超过50M）

### ISSUE THREAD

**Issue by luozicheng2019** [jeecgboot/jeecg-boot#3460]
##### 问题描述：前端首页打开非常慢（超过1分钟），发现有个app.js 的文件在一直加载，而且文件非常大（超过50M）。有什么办法可以优化吗？
PS：下载后基本未做改动。

##### 截图&代码：
![QQ图片20220226102000](https://user-images.githubusercontent.com/100453805/155825238-05af20aa-3767-495a-9ea4-f8630626776e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043891
