### ISSUE TITLE
给新建用户赋予角色的逻辑漏洞

### ISSUE THREAD

**Issue by mapleafly** [jeecgboot/jeecg-boot#3461]
##### 版本号：
v3.0

##### 问题描述：
建立admin之下的二级管理员用户A，只要这个用户A拥有部门管理、用户管理或者我的部门这三个权限之一，这个用户A就可以创建一个赋予管理员角色的用户B。

参见 #1538。好像没有解决这个问题。
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by 1298191366** [comment]
已修复，待新版本发布
