### ISSUE TITLE
浏览器重新加载此页后返回401

### ISSUE THREAD

**Issue by Mqinkai** [jeecgboot/jeecg-boot#3462]
##### 版本号：

3.0.0
##### 问题描述：
访问http://localhost:3000/可正常跳转页面，刷新页面（F5），后台“身份认证失败,token为空”，页面显示错误码。
我只修改了后台访问默认路径相关代码（去掉了/jeecg-boot）

##### 截图&代码：
![1646020893(1)](https://user-images.githubusercontent.com/21375197/155921949-348e2414-bf51-4e2e-9352-fed737cab371.png)

代码修改部分：
![1646020725(1)](https://user-images.githubusercontent.com/21375197/155921745-7e11789e-5f1d-4444-bbbc-98f8b7b36e99.png)

![1646025336(1)](https://user-images.githubusercontent.com/21375197/155927960-3f8d1f0d-2871-4c82-9a36-e8a3b82515f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个注释掉试试，你这么配置的意思，所有请求都走后台接口
![image](https://user-images.githubusercontent.com/3162115/156308207-ea2426a2-7c9e-4e85-be08-dac2355eef09.png)
