### ISSUE TITLE
Failed to parse configuration class [org.jeecg.JeecgGatewayApplication]; nested exception is java.lang.IllegalArgumentException: Could not find class [com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure]

### ISSUE THREAD

**Issue by woodj41** [jeecgboot/jeecg-boot#3463]
##### 版本号：
3.1.0

##### 问题描述：
JeecgGatewayApplication启动报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/10631352/155967129-0f716e32-9eaf-4702-9102-1afef995b8c3.png)

![image](https://user-images.githubusercontent.com/10631352/155967080-9ce777c2-a117-498d-bc1e-bb4c3598dcc1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
按照文档一步一步来，确认nacos启动等没问题
http://doc.jeecg.com/2043906
