### ISSUE TITLE
首页首次打开慢(经常超过20秒)，用了开发文档里的Nginx压缩后，加载文件大小仍有10M, 有什么解决办法?

### ISSUE THREAD

**Issue by luozicheng2019** [jeecgboot/jeecg-boot#3464]
##### 截图&代码：

![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
大小解决不了，你如果不需要那么多组件，可以改成按需加载

http://doc.jeecg.com/2044026
http://doc.jeecg.com/2044027
