### ISSUE TITLE
验证码刷新不出来

### ISSUE THREAD

**Issue by fantasyxl99** [jeecgboot/jeecg-boot#3466]
##### 版本号：
v3.0

##### 问题描述：
微服务方式启动，本地验证码刷不出来，单体服务启动，本地代码可以刷新，单内网访问时刷新不出来
(另一个issues的解决方法并不适用，附上链接 https://github.com/jeecgboot/jeecg-boot/issues/1228)
##### 截图&代码：

![image](https://user-images.githubusercontent.com/26175917/156093397-8e29fa29-8066-41e5-8928-9e87abfb28fa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
F12点击验证码，看请求状态

**Comment by fantasyxl99** [comment]
![image](https://user-images.githubusercontent.com/26175917/156093989-72c92de2-b1ed-4641-99b6-64a47d4565c0.png)

**Comment by zhangdaiscott** [comment]
后台启动成功了吗？
前端后台配置接口地址正确吗？

**Comment by fantasyxl99** [comment]
> 后台启动成功了吗？ 前端后台配置接口地址正确吗？

![image](https://user-images.githubusercontent.com/26175917/156099504-0a31361d-49c4-4fcc-b156-d4a477021cf8.png)
服务正常启动，并且swagger也可以访问到，你这边说的前后台接口配置我看了下确实没配置，于是我吧前台地址指向了网关（jeecg-gateway），但是最后还是无法刷新验证码。

修改配置jeecg-boot/ant-design-vue-jeecg/.env.development 文件: VUE_APP_API_BASE_URL=http://localhost:9998/jeecg-boot
修改后验证码请求错误:
![image](https://user-images.githubusercontent.com/26175917/156099955-d2298717-5a24-49c6-9ff9-51fe1e251b3d.png)

或者还有那些配置需要修改的么？

**Comment by zhangdaiscott** [comment]
仔细看文档，你这个后台地址配置错误

**Comment by fantasyxl99** [comment]
![image](https://user-images.githubusercontent.com/26175917/156102593-f8c4aaeb-6dde-4394-ab44-9a53a2c9db6c.png)
我看文档也是这么写的，我本地9999端口占用了，所以我换成了9998端口了

**Comment by adf61** [comment]
如果不启动网关，前端接口地址应该怎么配呢？

**Comment by pan-012** [comment]
+1 遇到同样的问题，不知道如何解决

**Comment by lovebetterworld** [comment]
已经解决了。

**Comment by lovebetterworld** [comment]
> +1 遇到同样的问题，不知道如何解决

我已经解决了。

**Comment by lkm0522** [comment]
> > +1 遇到同样的问题，不知道如何解决
> 
> 我已经解决了。

请问是怎么解决的问题呢

**Comment by liuzetan** [comment]
> > +1 遇到同样的问题，不知道如何解决
> 
> 我已经解决了。

请问是怎么解决的呢？

**Comment by liuzetan** [comment]
> > +1 遇到同样的问题，不知道如何解决
> 
> 我已经解决了。

请问是怎么解决的呢？ @lkm0522

**Comment by lovebetterworld** [comment]
> > > +1 遇到同样的问题，不知道如何解决
> > 
> > 
> > 我已经解决了。
> 
> 请问是怎么解决的问题呢

我记得我在他们的issue里面发了解决办法来着
