### ISSUE TITLE
在根目录部署另一个项目时，框架内访问 404

### ISSUE THREAD

**Issue by heptaluan** [jeecgboot/jeecg-boot#3467]
##### 版本号：
"version": "2.4.6"

##### 问题描述：

现在有另外一个项目，将其放在本项目的根目录的 test 文件夹当中（如图所示，都是打包后的文件），然后一起部署，但是发现在框架内部使用 iframe 嵌套访问该项目地址时，会直接跳转到 404

但是如果将该 test 项目放置于另外一个域名下，两者之间是可以正常访问的

请问这种情况该如何解决，也就是如何将另一个项目部署到该项目的目录之下

##### 截图&代码：

<img width="238" alt="01" src="https://user-images.githubusercontent.com/18285736/156101030-764d0766-a84f-4e7c-85f2-39ee1e71a82e.png">

![222](https://user-images.githubusercontent.com/18285736/156101260-00778146-44bb-415f-9577-59d0c67ee887.png)

**Comment by zhangdaiscott** [comment]
你这用法有点诡异，自己研究吧
