### ISSUE TITLE
主表编辑表单子表新增按钮没有权限控制，以及js增强

### ISSUE THREAD

**Issue by IsMrChen** [jeecgboot/jeecg-boot#3469]
##### 版本号：
3.0

##### 问题描述：
主表编辑表单子表时，新增按钮没有权限控制，以及js增强

##### 截图&代码：

![11](https://user-images.githubusercontent.com/53907291/156169985-45fc3af5-e8c3-446b-a0eb-ba790b02b554.png)

![12](https://user-images.githubusercontent.com/53907291/156169999-30d24961-7223-4519-ad29-7038c3c27302.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
子表支持的还不够
