### ISSUE TITLE
ERP主题模板下页面跳转带参数失效

### ISSUE THREAD

**Issue by sz2349** [jeecgboot/jeecg-boot#3471]
![1646186934868_B613BF7E-0895-4123-AE32-D8A635526DED](https://user-images.githubusercontent.com/42996028/156281146-d7d2453c-d525-402d-a859-ddf56f72a673.png)

图片中携带的参数只在默认主题模板下生效

**Comment by tygithub1** [comment]
测试没问题，
请确认字段名称是否拼写正确。
以及版本问题，这个问题2020年就处理过

**Comment by sz2349** [comment]
谢谢您的来件，我将尽快给您回复。
