### ISSUE TITLE
项目运行起来后前端访问列表页下的角色列表和用户列表报错

### ISSUE THREAD

**Issue by liu923014086** [jeecgboot/jeecg-boot#3472]
##### 版本号：
master

##### 问题描述：
项目运行起来后前端访问列表页下的角色列表和用户列表报错

##### 截图&代码：

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in data(): "TypeError: Cannot read properties of undefined (reading 'x')"

found in
<Table>
       <ATable>
         <STable>
           <ACard>
             <TableList> at src/views/examples/list/RoleList.vue
               <RouteView> at src/components/layouts/RouteView.vue
                 <LayoutContent> at src/components/page/PageLayout.vue
                   <PageContent> at src/components/layouts/PageView.vue
                     <Anonymous>
                       <ALayoutContent>
                         <Anonymous>
                           <ALayout>
                             <Anonymous>
                               <ALayout>
                                 <GlobalLayout> at src/components/page/GlobalLayout.vue
                                   <TabLayout> at src/components/layouts/TabLayout.vue
                                     <ALocaleProvider>
                                       <LocaleReceiver>
                                         <AConfigProvider>
                                           <App> at src/App.vue
                                             <Root>

且每次点击时会报Uncaught (in promise) Error: Avoided redundant navigation to current location: "/list/role-list".
    at createRouterError (vue-router.esm.js?8c4f:2062:1)
    at createNavigationDuplicatedError (vue-router.esm.js?8c4f:2035:1)
    at HTML5History.confirmTransition (vue-router.esm.js?8c4f:2195:1)
    at HTML5History.transitionTo (vue-router.esm.js?8c4f:2125:1)
    at HTML5History.push (vue-router.esm.js?8c4f:2492:1)
    at eval (vue-router.esm.js?8c4f:2913:1)
    at new Promise (<anonymous>)
    at VueRouter.push (vue-router.esm.js?8c4f:2912:1)
    at VueComponent.localPaginationCurrent (index.js?e8c4:47:1)
    at Watcher.run (vue.runtime.esm.js?2b0e:4568:1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liu923014086** [comment]
经过源码查看发现ant-design-vue-jeecg/node_modules/ant-design-vue/es/table/Table.js下148行判断warning(!props.expandedRowRender || !('scroll' in props) || !props.scroll.x, '`expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.');
   此判断有问题，props.scroll是undefined

**Comment by liu923014086** [comment]
版本是否考虑一下更新此问题？

**Comment by zhangdaiscott** [comment]
截图看看，是那个菜单

**Comment by zhangdaiscott** [comment]
这是示例，不重要，等下个版本我们看看

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by 1298191366** [comment]
已修复，待新版本发布
