### ISSUE TITLE
点击退出后，会自动重定向到/dashboard/analysis

### ISSUE THREAD

**Issue by qq1778551951** [jeecgboot/jeecg-boot#3475]
##### 版本号：

3.1.0
##### 问题描述：

点击退出后，会自动重定向到/dashboard/analysis
##### 截图&代码：

![image](https://user-images.githubusercontent.com/38367522/156311664-c7c706ec-9d3d-470a-af00-06f845564c79.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/3462
