### ISSUE TITLE
java 增强导入类异常

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3479]
##### 版本号：
3.1

##### 问题描述：
java 增强导入类异常，继承CgformEnhanceJavaImportInter后需要返回是个枚举d.class

##### 截图&代码：
public class testimport implements CgformEnhanceJavaImportInter {
    @Override
    public d execute(String s, JSONObject jsonObject) throws BusinessException {
        return null;
    }
}
***************************************
public enum d {
    a,
    b,
    c;

    public static d[] a() {
        return (d[])d.clone();
    }

    public static d a(String var0) {
        return (d)Enum.valueOf(d.class, var0);
    }

    private d() {
    }
}
***************************************
![CgformEnhanceJavaImportInter](https://user-images.githubusercontent.com/66394184/156514310-20919884-b3b6-4eed-9f92-ad8e34ca01b8.png)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录

**Comment by zhangdaiscott** [comment]
升级jar版本号
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>hibernate-re</artifactId>
  <version>3.1.0-beta1</version>
</dependency>
```
