### ISSUE TITLE
jeecg正式环境登录接口地址密码错误问题

### ISSUE THREAD

**Issue by PerfectYingxu** [jeecgboot/jeecg-boot#3484]
##### 问题描述：
进接口文档的后台开启了生产环境屏蔽，输入正确的账号密码，为什么进不去，报图一错误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/101000223/156881727-7aca86e0-3576-4bd1-99ef-0d1547d917f4.png)
![image](https://user-images.githubusercontent.com/101000223/156881740-4a8cd1c8-08f6-48b0-b5f5-26f986da5884.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看常见问题
