### ISSUE TITLE
Online在线功能是否支持非平台数据库使用

### ISSUE THREAD

**Issue by szgeqin** [jeecgboot/jeecg-boot#3488]
##### 问题描述：场景：微服务启动方式，其他模块使用单独的数据库。
问题：Online在线功能是否只能用平台数据库jeecg-boot？是否可以通过多数据源或者修改jeecg_database.properties解决？目前修改了CodeGenerateDbConfig和jeecg_database.properties，Online在线功能生成的表结构还是在平台数据库。这种情况下我是不是只能使用代码生成功能？

##### 截图&代码：
注释了CodeGenerateDbConfig，修改jeecg_database.properties为其他模块的数据库链接。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持多数据源
