### ISSUE TITLE
3.1版本 online表单在线-数据库表格式为Datetime时，通过日期查询组件（yyyy-MM-dd格式）查询报错

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3489]
##### 版本号：

3.1

##### 问题描述：

执行该条语句后，原有表单查询按yyyy-MM-dd格式查询Datetime格式报错

-- online 表单字段db类型，区分年月日和年月日时分秒
UPDATE onl_cgform_field SET db_type = 'Datetime' where db_type = 'Date';

例如：
        -数据库表格式为Datetime时
        -页面属性-控件类型-日期（yyyy-MM-dd），前台查询报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/66394184/157183448-ff296c69-2e2d-4897-a210-35e3f927ccae.png)

数据库查询失败，nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT order_code,order_date,descc,xiala ,id FROM test_order_main t where t.order_date= ORDER BY id desc ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT order_code,order_date,descc,xiala ,id FROM test_order_main t where t.order_date= ORDER BY id desc

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么数据库

**Comment by 793292556** [comment]
mysql

> 什么数据库

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复

**Comment by zhangdaiscott** [comment]
配置 [jeecg私服](http://doc.jeecg.com/2043876)，升级版本号看看是否解决了此问题
```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>hibernate-re</artifactId>
  <version>3.1.0-beta2</version>
</dependency>
```

**Comment by 793292556** [comment]
> 配置 [jeecg私服](http://doc.jeecg.com/2043876)，升级版本号看看是否解决了此问题
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot</groupId>
>   <artifactId>hibernate-re</artifactId>
>   <version>3.1.0-beta2</version>
> </dependency>
> ```

升级后可以了，不过配置私库没有，我在中心仓库下载的
