### ISSUE TITLE
idea本地项目能启动，打成jar包启动报错，为注册bean

### ISSUE THREAD

**Issue by XianRenYan** [jeecgboot/jeecg-boot#3492]
##### 问题描述：
idea本地项目能启动，打成jar包启动报错，未注册bean。可是我service层 mapper都添加了注解 也没漏

##### 截图&代码：
本地
![image](https://user-images.githubusercontent.com/32242242/157365241-92a2f5ba-1ab1-4bd9-91ac-fbf2aab8c45f.png)
jar包
![image](https://user-images.githubusercontent.com/32242242/157365376-30b2df5e-072e-4d95-902f-360169015cac.png)
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-09 11:09:28.359 [main] ERROR org.springframework.boot.SpringApplication:858 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageToUser_Controller': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mICheckCode_Service': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageSending_Service': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.jeecg.modules.orderManager.service.impl.MessageSending_Service] from ClassLoader [org.springframework.boot.loader.LaunchedURLClassLoader@20ad9418]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的代码问题，不要发issue
![image](https://user-images.githubusercontent.com/3162115/157365822-e5dc43f8-2bbc-4db6-b31f-6006857d6c6b.png)
