### ISSUE TITLE
菜单设置了缓存路由

### ISSUE THREAD

**Issue by yanyan965914478** [jeecgboot/jeecg-boot#3493]
##### 版本号：
2.4.6

##### 问题描述：
菜单设置了缓存路由，但是页面不生效，点击切换的时候还是会刷新页面。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/52962001/157365684-d3a4dd45-a385-4bff-93dd-75b3f5f3a92e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhanfk** [comment]
我也是同样的问题，楼主是否解决这个问题了呢

**Comment by 5563** [comment]
应该是三级路由吧 ，需要改RouteView.vue文件

**Comment by 3509282792** [comment]
二级我试过可以，3级菜单没试过

**Comment by taopoppy** [comment]
我这里版本是3.5.2都不生效，咋回事
