### ISSUE TITLE
使用字典下拉和多选有BUG

### ISSUE THREAD

**Issue by 1069385070** [jeecgboot/jeecg-boot#3495]
##### 截图&代码：
![S0S42OVZ8 SDQT7~VG86EEE](https://user-images.githubusercontent.com/37887843/157396319-c7559fc3-0363-4c4a-89ec-a6942499f146.png)

![image](https://user-images.githubusercontent.com/37887843/157396433-57f643f3-2eee-414d-a810-52afc04cd4a7.png)

![image](https://user-images.githubusercontent.com/37887843/157396468-a8281e46-789b-45c6-b742-b8e740c4c4d1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
写的很模糊
