### ISSUE TITLE
有考虑开发在线用户，踢掉用户功能吗

### ISSUE THREAD

**Issue by x522491416** [jeecgboot/jeecg-boot#3497]
##### 版本号：
3.1

##### 问题描述：
有考虑开发在线用户，踢掉用户功能吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不是有在线用户功能吗

**Comment by x522491416** [comment]
没找到啊，能说下在那吗
![image](https://user-images.githubusercontent.com/45849273/157430049-49b110f4-148d-40b7-a3ec-9755cbaa8ef1.png)

**Comment by x522491416** [comment]
> 不是有在线用户功能吗

没找到啊，能说下在那吗
![image](https://user-images.githubusercontent.com/45849273/157430191-7b617175-38c9-49fe-8412-a767d21d4a04.png)

**Comment by zhangdaiscott** [comment]
系统监控

**Comment by lliaoliao** [comment]
我也没找到到底在哪呢？
