### ISSUE TITLE
online表单查询时带逗号的字段内容不能直接查询出来

### ISSUE THREAD

**Issue by patrickhu1** [jeecgboot/jeecg-boot#3499]
##### 版本号：
3.1.0

##### 问题描述：
online表单查询时带逗号的字段内容不能直接查询出来
建议split切分后把原字段内容也加到数组中

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/157594780-090b18cd-d8a5-49b4-b4f7-b58b8e854af2.png)
![image](https://user-images.githubusercontent.com/26364818/157594796-1665412e-5e46-4d88-930b-08cefa253478.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以自己扩展改造查询过滤器
