### ISSUE TITLE
online表单下拉搜索框表字典配置#{sys_org_code}报错

### ISSUE THREAD

**Issue by patrickhu1** [jeecgboot/jeecg-boot#3500]
##### 版本号：
3.1.0

##### 问题描述：
online表单下拉搜索框表字典配置#{sys_org_code}报错
下拉框正常，只有下拉搜索框有问题
##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/157610923-f243ea7a-3ddc-4324-bc26-05b1dc5eb8ab.png)

![image](https://user-images.githubusercontent.com/26364818/157611072-e85573e8-1b8a-4cd1-bc51-833a4d6e7554.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 ty

**Comment by tygithub1** [comment]
已修复
