### ISSUE TITLE
Java【spring-key增强按钮】点击报异常

### ISSUE THREAD

**Issue by IsMrChen** [jeecgboot/jeecg-boot#3501]
##### 版本号：
3.1.0
##### 问题描述：
java增强按钮点击报异常

报错信息：
2022-03-10 17:37:16.175 [http-nio-8080-exec-8] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:71 - Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Method org/jeecg/modules/Enhance/StayApplyEnhance.execute(Ljava/lang/String;Lcom/alibaba/fastjson/JSONObject;)V is abstract
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.AbstractMethodError: Method org/jeecg/modules/Enhance/StayApplyEnhance.execute(Ljava/lang/String;Lcom/alibaba/fastjson/JSONObject;)V is abstract

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53907291/157633534-9e3e3764-6123-4666-9410-bc7a832fbadd.png)

![image](https://user-images.githubusercontent.com/53907291/157633709-23356b69-f24a-4e80-922f-79a0f6a46362.png)

代码：

```
@Component("StayApplyEnhance")
@Slf4j
public class StayApplyEnhance implements CgformEnhanceJavaInter {
    @Override
    public int execute(String s, Map<String, Object> map) throws BusinessException {
        return 0;
    }

    @Override
    public int execute(String s, JSONObject jsonObject) throws BusinessException {
        log.info("加强接口运行了");
        return 0;
    }
}
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是自己增量升级的吧，接口已经变了

**Comment by IsMrChen** [comment]
嗯嗯是的今天做看升级。请问文档同步更新了吗





------------------ 原始邮件 ------------------
发件人: JEECG ***@***.***&gt;
发送时间: 2022年3月10日 21:55
收件人: jeecgboot/jeecg-boot ***@***.***&gt;
抄送: Squirrel ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jeecgboot/jeecg-boot] Java【spring-key增强按钮】点击报异常 (Issue #3501)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044114
