### ISSUE TITLE
打成jar包运行时，WebMvcConfiguration的addResourceHandlers方法不调用

### ISSUE THREAD

**Issue by allanwxm** [jeecgboot/jeecg-boot#3505]
##### 版本号：
3.1.0

##### 问题描述：
用maven打成jar包，运行时WebMvcConfiguration的addResourceHandlers方法不调用，添加的日志不输出，添加的自定义资源文件夹不生效（框架自带的upload和webapp生效），访问自定义资源文件夹下的png文件，提示404

##### 截图&代码：
<img width="478" alt="image" src="https://user-images.githubusercontent.com/5036833/157815200-24a1b7e3-30e2-4f04-a128-8a55cd60936b.png">
<img width="855" alt="image" src="https://user-images.githubusercontent.com/5036833/157815241-3c856117-ccfd-4b3c-8353-a01e41b1d27b.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/5036833/157815304-acee7ff7-f000-4b96-9bd5-a95cf2755f71.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修改这个属性
spring.resource.static-locations
