### ISSUE TITLE
Mysql初始化数据库问题

### ISSUE THREAD

**Issue by ZhisenLiu** [jeecgboot/jeecg-boot#3506]
##### 截图&代码：
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/49870364/158006061-6fab5d86-a777-4d7d-9f02-fb2fe3f7246d.png">

按照官网技术文档安装，除却一点，系统为MAC OS 12.2.1
node 及yarn通过homebrew安装
各个tool版本：
node   v17.6.0
npm    v8.5.2
yarn    v1.22.17
maven    v3.8.4
java 1.8
mysql 8.0.28

运行
<img width="934" alt="image" src="https://user-images.githubusercontent.com/49870364/158006195-893a1f6a-e0e3-48ff-adfc-11f1a61bd19a.png">
该步骤时报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你看看你下的脚本里面有建表的逻辑吗

**Comment by zhangdaiscott** [comment]
无及时回复，关闭
