### ISSUE TITLE
Nacos 1.4.1 依然存在权限绕过的漏洞

### ISSUE THREAD

**Issue by yimisunrise** [jeecgboot/jeecg-boot#3507]
##### 版本号：
Nacos 1.4.1

##### 问题描述：
存在权限绕过的漏洞，可以绕过权限注册帐号并正常登录

目前咱们框架貌似依然使用的是nacos1.4.1吧？

**Comment by zhangdaiscott** [comment]
下个版本发布新的 2.0.4
