### ISSUE TITLE
模板管理發送消息出現NullPointerException 錯誤

### ISSUE THREAD

**Issue by tamkenrick** [jeecgboot/jeecg-boot#3512]
##### 版本号：
3.0.0

##### 问题描述：
消息中心->模板管理, 發送訊息出現NullPointerException 錯誤

##### 截图&代码：
![image](https://user-images.githubusercontent.com/43806601/158322666-9c428305-4d16-4261-80c1-89c860e7b662.png)
![image](https://user-images.githubusercontent.com/43806601/158322719-e99e5688-0804-4bd7-ba6e-35b457eb3bae.png)
![image](https://user-images.githubusercontent.com/43806601/158322182-344a30a8-5ba3-4c58-a552-ea531c76d300.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
