### ISSUE TITLE
技术文档标题写错了

### ISSUE THREAD

**Issue by lhy507613824** [jeecgboot/jeecg-boot#3513]
##### 版本号：

2.4
##### 问题描述：
技术文档标题写错了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49083968/158355689-4cb10955-ac8b-4952-b16c-826f6bc27c12.png)

http://doc.jeecg.com/2653459
标题写的是 @**Hystric**Command配置参数详解
应该是**Hystrix**Command

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
3Q
