### ISSUE TITLE
前端node-ipc包依赖问题

### ISSUE THREAD

**Issue by GEEKZX** [jeecgboot/jeecg-boot#3514]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/12831180/158529556-7e26a8a0-c2d8-4cb9-98e6-4f941930483c.png)
![image](https://user-images.githubusercontent.com/12831180/158529701-de998518-1c6b-4aa1-92a8-ec21fb3c55be.png)

node-ipc包出现问题    peacenotwar投毒包无法下载
解决方案：用本地老的包替换至node_modules里
风险：如无cache，新的install会报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by GEEKZX** [comment]
just for remind

**Comment by zhangdaiscott** [comment]
了解
