### ISSUE TITLE
过扩展参数设置部门/用户组件 存储字段和展示字段online功能测试没问题，形成代码后用代码保存就不行了

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3519]
##### 版本号：
v3.1.0

##### 问题描述：
过扩展参数设置部门/用户组件 存储字段和展示字段online功能测试没问题，形成代码后用代码保存就不行了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/158917991-35ba98b0-b623-4b0f-aa0a-d846d31931ce.png)
![image](https://user-images.githubusercontent.com/90361617/158918019-de3d96d3-69ab-4af1-96e4-67fe71194757.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
报什么错

**Comment by 3509282792** [comment]
没有报错，都是正常的，就是那个扩展参数设置好像通过代码生成的没用

**Comment by 3509282792** [comment]
通过online的测试功能，扩展参数设置都是设置成功的，代码生成后，用代码运行起来就不行了

**Comment by 3509282792** [comment]
比如用户组件的用户多选与单项参数设置，我已经设置了单项，功能测试也达到了功能，但是生成的代码没用
![image](https://user-images.githubusercontent.com/90361617/158921454-be018021-d43c-4df2-a340-ab1868fed450.png)
![image](https://user-images.githubusercontent.com/90361617/158921525-cb32d358-8157-41ca-8bdc-a08f4ea94899.png)

**Comment by zhangdaiscott** [comment]
哪手工调整代码，不是所有的在线配置都能生成

**Comment by 3509282792** [comment]
那用户组件默认选择用户默认是保存用户工号的，代码上哪里改可以保存保存用户id呀，请教下
