### ISSUE TITLE
online表单主表设置启动联合查询，auto在线表单没问题，但是自动生成代码后无效果为最基本的搜索和显示

### ISSUE THREAD

**Issue by zhubinsheng** [jeecgboot/jeecg-boot#3521]
##### 版本号：
当前最新版本： 3.1.0（发布日期：20220301）

##### 问题描述：

online表单主表设置启动联合查询，auto在线表单没问题，但是自动生成代码后无效果为最基本的搜索和显示
##### 截图&代码：

![微信截图_20220319101455](https://user-images.githubusercontent.com/44765143/159102978-05e5c709-06f6-480a-ab2b-ec44d194e781.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhubinsheng** [comment]
![微信截图_20220319101101](https://user-images.githubusercontent.com/44765143/159103020-5e294b8c-0b0c-4cee-8f5e-07dbba0585b0.png)
auto在线无问题

**Comment by zhangdaiscott** [comment]
不支持代码生成
