### ISSUE TITLE
前端登录报错

### ISSUE THREAD

**Issue by JensenLau** [jeecgboot/jeecg-boot#3522]
##### 版本号：
3.1.0

##### 问题描述：
jeecg-boot前后端搭建完成（按照官网），后端运行能够访问swagger文档，前端页面加载正常，但是登录时提示431，请问大佬这是哪里出的问题？

##### 截图&代码：
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/49870364/159150347-819bb6c4-8d91-457c-9176-5e1e3ce31d9c.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看你这登录界面，根本不是3.1.0，从不知道哪个版本开始，登录页面有验证码

**Comment by JensenLau** [comment]
为啥关闭。。
