### ISSUE TITLE
运行正常，打包后运行没有初始化demo模块 

### ISSUE THREAD

**Issue by zhubinsheng** [jeecgboot/jeecg-boot#3523]
##### 版本号：
 3.1.0（发布日期：20220301）

##### 问题描述：
idea中运行正常的，打包后运行时，没有初始化demo模块 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhubinsheng** [comment]
![Screenshot from 2022-03-21 15-49-22](https://user-images.githubusercontent.com/44765143/159221767-33ec7243-8dfe-405c-8b7f-f4dad57b0d50.png)
demo模块是以jar存放的 但是没有初始化

**Comment by zhangdaiscott** [comment]
没有初始化是什么意思

**Comment by zhubinsheng** [comment]
就是Controller没有初始化

**Comment by zhangdaiscott** [comment]
本地呢，怎么会有这样的问题

**Comment by zhubinsheng** [comment]
> 本地呢，怎么会有这样的问题

idea运行没问题，打包后有这样的问题，我就是想请教你出现这样的问题的原因
