### ISSUE TITLE
大屏设计器报token校验失败

### ISSUE THREAD

**Issue by zhoulincome** [jeecgboot/jeecg-boot#3526]
##### 问题描述：
org.jeecgframework.jimureport  1.4.4-beta
1、我在菜单管理添加了大屏设计器了，给管理员授权了，大屏设计器的按钮也出来了，但是点击大屏设计器后返回授权失败
2、我配置的是bigscreen为啥点击后是big/screen，有啥特殊处理吗
{{ window._CONFIG['domianURL'] }}/bigscreen/#?token=${token}
##### 截图&代码：
添加配置项
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6369667/159409876-7cb5c16c-316b-42fd-9758-00023b994821.png">
点击配置信息后报错
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/6369667/159410637-950b9459-534d-469f-9598-326d703ec174.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
大屏功能未开放，配置用不了

**Comment by zhoulincome** [comment]
ok
