### ISSUE TITLE
积木报表是否支持计数

### ISSUE THREAD

**Issue by czzt1** [jeecgboot/jeecg-boot#3527]
##### 版本号：
3.0

##### 问题描述：
积木报表是否支持计数？或者换种说法，sql数据源返回的总数量能否在报表中使用？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19328207/159411616-b5f10daf-c15d-457d-9391-0f6134671bf3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以

**Comment by czzt1** [comment]
> 可以

可以麻烦给个实例吗
