### ISSUE TITLE
一对多代码生成，外键关联字段错误

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#3528]
##### 版本号：
3.1

##### 问题描述：
一对多表单代码生成，online表单展示没有问题，但是生成代码后回填的是主键ID的值而不是关联的外键字段，应该是截图地方的问题，生成代码不是动态的，会默认取ID字段

#### 外键关联字段配置
![image](https://user-images.githubusercontent.com/48941586/159601589-a4a41ee1-4ef2-49ec-8d59-34e159268fd5.png)

#### 错误展示
![image](https://user-images.githubusercontent.com/48941586/159601469-524ef3d4-9ea8-47ea-8d30-b934203fb67e.png)

### 代码生成有问题的地方
![image](https://user-images.githubusercontent.com/48941586/159601204-cf893950-cb9f-4da1-b5b8-3a1efe81109e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Chris-Arith** [comment]
还有一个就是子表的查询框也没有了

**Comment by zhangdaiscott** [comment]
截图看你的配置

**Comment by Chris-Arith** [comment]
> 截图看你的配置

### 主表配置
![image](https://user-images.githubusercontent.com/48941586/159635590-83074293-a7ae-42fa-a457-77fbaf313ce5.png)

### 子表配置
![image](https://user-images.githubusercontent.com/48941586/159635474-ef0ffcdd-29a3-46a8-b032-7c58816217ce.png)
![image](https://user-images.githubusercontent.com/48941586/159635689-11ce520a-95fe-48ad-ab21-9e1b0e96f9ec.png)

### 代码生成风格
ERP风格

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修复
