### ISSUE TITLE
可能是个BUG。多租户启用后，存到数据库的租户id不是本用户的

### ISSUE THREAD

**Issue by Sweety-Feel** [jeecgboot/jeecg-boot#3529]
##### 版本号：
2.4.6

##### 问题描述：
租户A和租户B分别用不同的浏览器,租户B进入到导入文件的页面，租户A刷新页面将tenant-id改为租户A的，此时租户B不刷新页面等待一会，直接导入文件，存到数据库的租户id是租户A的

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20548980/159604496-f388a651-3d36-4263-9f92-3d743118307b.png)

![image](https://user-images.githubusercontent.com/20548980/159604970-9fe03bb5-ce64-481f-b978-414e99953e27.png)

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
未测出
