### ISSUE TITLE
代码生成按钮只能生成一个空的xml

### ISSUE THREAD

**Issue by lkl1** [jeecgboot/jeecg-boot#3530]
##### 问题描述：
点击代码生成只能生成一个空的xml，

##### 截图&代码：
![image](https://user-images.githubusercontent.com/34978141/159620693-f56fccd6-ef47-4a25-bfaf-522c772db807.png)

![image](https://user-images.githubusercontent.com/34978141/159620450-d1dc5f8b-60e6-4ab4-a918-b6286d6a7993.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本太低

**Comment by lkl1** [comment]
我下载最新的jeectboot代码我看了下，是有那个版本号
![image](https://user-images.githubusercontent.com/34978141/159631829-5fcd3c15-1d1e-4f25-adf2-cd4d780e4626.png)
但是我现在的项目上是
![image](https://user-images.githubusercontent.com/34978141/159632224-c5a93804-a782-467b-9078-b941be352dfd.png)
这个是jeecg的版本号是吗？想确定下。

**Comment by lkl1** [comment]
项目里没有jeecgboot名称的标签

**Comment by lkl1** [comment]
我提刚才上面提问题时候版本号写的是1.0.0   写错了 。
是2.4.3版本。还是上面的问题不知道因为什么。
能帮我解答下吗？

**Comment by lkl1** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
你发的issue，让我们无法入手

**Comment by lkl1** [comment]
版本是2.4.3
<img width="1152" alt="1648191664(1)" src="https://user-images.githubusercontent.com/34978141/160070660-4a3b7d1f-c17d-415c-a093-7b706ed732f9.png">
这是点击生成代码按钮后的日志
[日志.txt](https://github.com/jeecgboot/jeecg-boot/files/8348196/default.txt)
这是cs类代码的路径的配置(在项目上 这个路径没用上，在代码的弹出框里可以直接选路径)
<img width="553" alt="1648191794(1)" src="https://user-images.githubusercontent.com/34978141/160070971-a4b0efe1-34d3-425a-a07d-7c833ac2c209.png">
这是配置类的配置（这个配置类注释过了，试了试不行）
<img width="688" alt="1648191867(1)" src="https://user-images.githubusercontent.com/34978141/160071126-4a524097-379f-4dbd-9ee9-58e970ea4227.png">
这下面这张图的版本是1.3.1
<img width="406" alt="1648192057(1)" src="https://user-images.githubusercontent.com/34978141/160071578-5e08c8cd-f552-4661-9f98-9fb87b0df61c.png">
是哪的问题一直没找到，大佬求解
