### ISSUE TITLE
jeecg-boot3.1.0 添加热部署依赖启动ISysBaseAPI ,could not be found.

### ISSUE THREAD

**Issue by 577903774** [jeecgboot/jeecg-boot#3531]
##### 版本号：
3.1.0

##### 问题描述：
system 模块引入 devtools 热部署依赖后，启动项目抛出异常

##### [截图&代码：](url)
![image](https://user-images.githubusercontent.com/45093841/159661106-a82733c9-88ae-42bd-a3ff-c7f94ce9132c.png)

![1648025828(1)](https://user-images.githubusercontent.com/45093841/159661257-803d1878-3540-4b10-9676-bb9436eccc48.jpg)
![image](https://user-images.githubusercontent.com/45093841/159661311-4b7900de-eb6e-4de0-b4c0-a59d56e26496.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 577903774** [comment]
谢谢，已解决

**Comment by LeonemZhang** [comment]
> 谢谢，已解决

请问是怎么解决的，可以说一下嘛。不会还是用的jrebel吧~

**Comment by LeonemZhang** [comment]
> 为什么不用jrebel

为什么不用devtools

**Comment by stj84** [comment]
请问怎么处理的
Caused by: java.lang.IllegalArgumentException: interface org.jeecg.common.system.api.ISysBaseAPI is not visible from class loader
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:581)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)

刚下载的项目，IDEA中启动失败了，打成jar包后可以直接-jar启动的
