### ISSUE TITLE
不能以单个字母加下划线开头

### ISSUE THREAD

**Issue by liush2** [jeecgboot/jeecg-boot#3533]
##### 版本号：
 3.1.0

##### 问题描述：

代码自动生成，没法正对单个字母开头的表生成
##### 截图&代码：

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/59461366/159666967-1a6b217d-665d-49f9-ae92-0994c3bc3cce.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你这样的命名不规范
