### ISSUE TITLE
数据库表主键id生成规则有问题

### ISSUE THREAD

**Issue by liush2** [jeecgboot/jeecg-boot#3536]
##### 版本号：
3.1.0

##### 问题描述：
数据库表主键设置为bigint(20)，自动生成的代码字段类型为integer，应该是为Long才对，生成页面主键无边编辑类型，导致无法手动修改

##### 截图&代码：
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/59461366/159675968-fb8cb7d5-3d51-4d62-9128-410a46ecf7b7.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成后，手工调整吧，或者改代码生成器的模板

**Comment by liush2** [comment]
ok
