### ISSUE TITLE
这块代码有SQL注入的风险

### ISSUE THREAD

**Issue by lihulanxx** [jeecgboot/jeecg-boot#3538]
##### 版本号：

3.1.0
##### 问题描述：

这段代码提示有sql注入的风险
##### 截图&代码：
![image](https://user-images.githubusercontent.com/21300619/159827886-949b75ca-2395-40b4-a2c2-4dbaaba78195.png)
![image](https://user-images.githubusercontent.com/21300619/159828028-6079bd12-d645-4b7c-b025-84335af15fd4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修改
