### ISSUE TITLE
组件部门选择器父子关联功能没有

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3540]
##### 版本号：
 v3.1.0 

##### 问题描述：
用了部门选择器后，如何设置父子关联呢，就是勾选父类子类默认打钩

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/159849253-215c7a41-2dad-41d5-8b12-c037e534b06c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
应该没实现，可以自己扩展下
