### ISSUE TITLE
国产数据库适配异常

### ISSUE THREAD

**Issue by QinFangYuan** [jeecgboot/jeecg-boot#3543]
##### 问题描述：国产数据库适配异常

最近公司的项目在和国产数据库（**Goldilocks**、**csiidb**）进行适配工作
因为了解到 **jeecg-boot** 中持久层框架采用了 **MybatisPlus** ，于是查询了下

**MybatisPlus** 官方，在版本 3.5.0+ 中已经加入了对国产数据库（**Goldilocks**、**csiidb**）的支持，想问一下jeecg-boot是否可以在后续的版本中，兼容Mybatis-plus 3.5.0+及以上版本，提供对上述两款国产数据库的支持
![12786c33094cc9f45fc543457b242ff](https://user-images.githubusercontent.com/46182166/159889549-8c27e8da-d2fd-4222-ba5b-8502c7dab65c.png)

我在此非常期待能够得到官方团队的支持，当然，如果有需要的话，可以和我司进行必要的商务洽淡。

##### 截图&代码：
jdbc连接配置如下
![679aab52aab55eee0fa014e259ccc26](https://user-images.githubusercontent.com/46182166/159883935-8dca9298-fd25-4a7f-8f8d-e7fc999091e5.png)

项目启动报错
![a272aebf25961eedcbd865dd5ad422b](https://user-images.githubusercontent.com/46182166/159884082-207b1eab-1e91-4654-9fdc-1f88847908c2.png)

**jeecg-boot** 2.4.6 版本  中 **MybatisPlus**  的版本（还未加入对**Goldilocks**、**csiidb**的支持）
![1de4aceb3abe1704f27c0d138c47ee4](https://user-images.githubusercontent.com/46182166/159885102-56634f93-00f1-4420-bde3-1d4355680661.png)

**Comment by zhangdaiscott** [comment]
后续版本  会升级

**Comment by QinFangYuan** [comment]
> 

想问一下，jeecg-boot 升级 Mybatis-plus 3.5.0+ 之后，就可以避免上述由于数据库类型不支持导致的应用启动报错吗？

另外，如果可以的话，我能了解下这部分的兼容工作有大致的时间安排吗？

**Comment by zhangdaiscott** [comment]
下个版本发布
