### ISSUE TITLE
集成的jimuReport，数据字典不能打开字典配置页面

### ISSUE THREAD

**Issue by mapleafly** [jeecgboot/jeecg-boot#3544]
##### 版本号：
3.1.0   自3.0.0升级

##### 问题描述：
1.可以新建字典。
2.不能打开字典配置页面。
3.浏览器没有报错。

查看浏览器信息显示连接地址：
http://localhost:8080/fence/jmreport/dictItem/list?pageNo=1&dictId=d6e1152968b02d69ff358c75b48a6ee1
其中fence是自改的路径。

##### 截图&代码：

![微信图片编辑_20220324183251](https://user-images.githubusercontent.com/790790/159897722-89db2833-8e69-4430-b067-e4752a4cae3b.jpg)

![微信截图_20220324183358](https://user-images.githubusercontent.com/790790/159897881-6033a04d-9609-47ee-b000-20cdb1cf0ee8.png)

看起来也有返回数据，但是没有调动页面。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
详细说明下

**Comment by mapleafly** [comment]
查看数据库表jimu_dict，新添加的字典已经写入，说明数据库及路径配置没问题。还是不知为何“字典配置”点击无反映。

**Comment by zhangdaiscott** [comment]
不清楚，写的issue也太不专业

**Comment by mapleafly** [comment]
@zhangdaiscott  很感谢回复。 原来就是点击“字典配置”没有反应。刚才重走一遍又能打开了。
