### ISSUE TITLE
单标签页模式下，打开外部链接 报错误 “这是最后一页，不能再关闭了啦”

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/jeecg-boot#3546]
##### 问题描述：
当项目不使用标签页的情况下（defaultSettings中multipage: false）

打开外部链接弹出如下提示信息！
'这是最后一页，不能再关闭了啦'

##### 截图&代码：
this.$message.warning('这是最后一页，不能再关闭了啦')
未截到图，具体报错位置如上！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by ma19881117** [comment]
if(this.multipage) {
    // 多页签情况下关闭当前页面
    this.closeCurrent();
  } else {
    this.$router.back();
  }
   window.open(this.url);
修改为$router.back() 会导致页面刷新，数据丢失！

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布。
