### ISSUE TITLE
微服务启动时报org.jeecg.modules.online.cgform.service.impl.d required a bean of type 'org.jeecg.common.system.api.ISysBaseAPI' that could not be found.

### ISSUE THREAD

**Issue by 564853048** [jeecgboot/jeecg-boot#3548]
##### 截图&代码：Error creating bean with name 'onlCgformAuthController': Unsatisfied dependency expressed through field 'onlCgformFieldService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'onlCgformFieldServiceImpl': Unsatisfied dependency expressed through field 'sysBaseAPI'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.system.api.ISysBaseAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

![61ee67afa3f82e3c128dc577f95656c](https://user-images.githubusercontent.com/51633353/160094855-4cb10e6d-fca5-4bed-b416-a66d8ba4fce7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看常见问题贴

**Comment by 564853048** [comment]
是因为我把那个base的模块名改为了common吧=。=
