### ISSUE TITLE
sql字典根据条件查询

### ISSUE THREAD

**Issue by hao1030153145** [jeecgboot/jeecg-boot#3549]
##### 版本号：
3.4.1

##### 问题描述：
在线报表里面，查询参数  sql字典，希望能根据系统参数进行查询数据，而不是全部查询出来

##### 截图&代码：
select proj_code as value, proj_name as text, taxpayer_code from rnd_project 
能否在该sql字典语句 后面 加上 条件查询

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以加where条件
