### ISSUE TITLE
Autocomplete标签

### ISSUE THREAD

**Issue by Caisen1988** [jeecgboot/jeecg-boot#3551]
##### 版本号：
V2.4.5

##### 问题描述：
您好，感谢带了这么优秀的项目，现在前端好像没有Autocomplete标签库哈，看到有相关文档。
http://idoc.jeecg.com/1275940

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你看的是老文档，请看新文档 doc.jeecg.com
