### ISSUE TITLE
Online表单设计，功能测试表单样式与生成的代码样式不一致。

### ISSUE THREAD

**Issue by Erlin610** [jeecgboot/jeecg-boot#3552]
##### 问题描述：
online表单设计，表单采用“官方示例”，表单设计完成后，生成的代码样式与“功能测试”的表单样式不一致。主要表现为：排版不一致，富文本编辑框大小不一致，label部分显示“：”（冒号），部分不显示。

##### 截图&代码：

online功能测试的时候表单是这样的：
![QQ图片20220328090055](https://user-images.githubusercontent.com/54437733/160309758-2db3d6f4-1098-4eb8-bedc-47e2b24ab963.png)

但是实际生成的代码表单是这样的：

![QQ图片20220328090156](https://user-images.githubusercontent.com/54437733/160309791-99504841-0052-45a3-ab42-1ce17f56bbb6.png)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/1312
