### ISSUE TITLE
微信扫码登录，绑定操作未验证手机验证码，存在安全隐患（只要知道用户的手机号，就可以通过扫码登录绑定用户身份）

### ISSUE THREAD

**Issue by xyudi** [jeecgboot/jeecg-boot#3555]
##### 版本号：
3.1.0
3.0.0

##### 问题描述：
微信扫码登录的场景，扫码后，需要验证手机号，绑定用户，我录入用户表存在的手机号，然后验证码是随便录的，点确定，就绑定上了，也就是只要知道用户表里的手机号，就能绑定，验证码不起作用，我看了绑定的代码，没验证，直接绑定了。

##### 截图&代码：
![7F}%D3YKO}3G33K2{IE2@GV](https://user-images.githubusercontent.com/10971018/160528306-dc4efbe1-69a9-4988-b2c8-4838ea236555.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
收录 jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
