### ISSUE TITLE
jvxetable使用问题

### ISSUE THREAD

**Issue by laoyao789** [jeecgboot/jeecg-boot#3556]
##### 版本号：

jeecgboot 3.0
##### 问题描述：

jvxetable可以绑定datasource里对象的子属性吗
##### 截图&代码：

<j-vxe-table
    ref="table"
    toolbar
    row-number
    row-selection
    drag-sort
    keep-source
    :height="580"
    :loading="loading"
    :dataSource="dataSource"
    :columns="columns"
    style="margin-top: 8px;"
    @valueChange="handleValueChange"
  >

  </j-vxe-table>

datasource=[
  {id:1,name:'测试数据',area:{name:"北京",lat:'166.988888',lng"32.0000"}}
]

datasource是这样的数字，地区名称是一个子对象的属性，应该怎么显示地区名？columns应该怎么定义？

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
绑定不了更深层的字段，可以写自定义组件或 slot 插槽，也可以在传给jvxetable的时候处理一下数据，将 area.name 展开为 areaName ，然后字段上绑定 areaName
