### ISSUE TITLE
两个JEECG-BOOT项目，点击按钮后跳转到另个JEECG-Boot项目，并且免登录

### ISSUE THREAD

**Issue by bangcd999** [jeecgboot/jeecg-boot#3557]
##### 版本号：
Jeecg  Boot Version: 3.0
Spring Boot Version: 2.3.5.RELEASE (v2.3.5.RELEASE)

##### 问题描述：
你好，现在是两个jeecg-boot项目，我想在第一个项目中，点击跳转按钮，跳到第二个项目（两个项目端口不同），账号已经是同步的了，我该如何实现？

##### 截图&代码：
已经拿到token了，但是不知道接下来如何操作
<img width="1186" alt="2" src="https://user-images.githubusercontent.com/71172145/160572126-cc9bfb49-14db-4929-a1ad-2ff6df045351.png">
<img width="1714" alt="token" src="https://user-images.githubusercontent.com/71172145/160572205-b5f8b392-61c4-4e38-9e93-6bf90194d179.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
连同一个redis试试
