### ISSUE TITLE
在线报表部分功能报错

### ISSUE THREAD

**Issue by lovemyhan** [jeecgboot/jeecg-boot#3558]
##### 版本号：
3.1.0

##### 问题描述：
http://boot.jeecg.com/online/cgreport
1. 随便点一个报表，编辑按钮。
2. 点击SQL解析。
<img width="393" alt="image" src="https://user-images.githubusercontent.com/26110382/160731742-8a6f087d-77a8-493e-874a-edf77ccc5144.png">
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/26110382/160731835-48dbdf4e-87a1-4f4a-82b6-b4e5074edeb2.png">

3. 更改下面字段内容点击确定也会报一样的错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
线上服务器配置问题
