### ISSUE TITLE
Quartz定时任务后台重启后不执行

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#3560]
##### 版本号：
v3.1.0

##### 问题描述：
用的示例代码里的定时任务，目前存在两个问题
- 启动定时任务后不会自动执行，需要手动点击执行一次才会开始执行，看了下代码，`QuartzJobController` 中 `resume` 方法注掉了一行，放开后就好了，详见 `截图一`，不知道这一块为什么要注释掉？
- 点击启动后定时任务执行，但是重启后台代码后定时任务没有执行，issue#81 中提及下个版本解决，但是 v3.1.0 版本好像还是不能自动执行。

### 截图一
![image](https://user-images.githubusercontent.com/48941586/160737099-7130d543-d234-426a-85be-855b670cdcb4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sco

**Comment by niexinpeng** [comment]
ty啥意思

**Comment by zhangdaiscott** [comment]
常见问题52 ：http://jeecg.com/doc/qa

**Comment by niezixu** [comment]
我这边也遇到同样的问题，可以确定不是“常见问题52”这种情况

**Comment by sdvdxl** [comment]
需要设置为true，默认是false ，为啥要设置为false呢。

![image](https://user-images.githubusercontent.com/3821540/209750416-2c5e483b-c760-427f-b2a5-008f2d95a256.png)

**Comment by wjy000** [comment]
确实是被注释了这一行, 我都被这个问题搞死了, 搜了一圈, 到处都在发常见问题52, 可是根本就不是这个52问题, 这群人真的自己跑了项目? 解开这行注释, 定时任务就能执行了, 不知道为什么要注释掉

**Comment by panyuzhe73** [comment]
对 秒级就能执行，一到分钟就不行了
