### ISSUE TITLE
Online表单开发,数据表命名问题

### ISSUE THREAD

**Issue by 2011ci** [jeecgboot/jeecg-boot#3562]
##### 问题描述：
为什么命名不能使用单字母加下划线?
![image](https://user-images.githubusercontent.com/5737868/160786483-6d742465-6867-4417-b8c7-22d4074a2b4d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不规范

**Comment by 2011ci** [comment]
如果我所有的表都是这么用的,需要怎么修改 源码,
或者说这种有什么不规范产生的后果

**Comment by zhangdaiscott** [comment]
目前改不了，我们不支持这种命名
