### ISSUE TITLE
用户管理页面 小屏幕设备显示问题

### ISSUE THREAD

**Issue by Nguyendream** [jeecgboot/jeecg-boot#3563]
##### 版本号：
3.1.0

##### 问题描述：
用户管理页面，小屏幕设备显示存在问题，字段过多，显示不全

设备为13寸笔记本，分辨率2.5k(2560x1600)，文本缩放200%

##### 截图&代码：
![屏幕截图 2022-03-30 163252](https://user-images.githubusercontent.com/33228912/160790019-3fb3ae58-a99a-4c82-a7e8-b3aca258b411.png)

建议改为下图的展示效果（修改少就不提pr了）
![屏幕截图 2022-03-30 164048](https://user-images.githubusercontent.com/33228912/160790598-2aed02be-27bf-43e2-8b28-f26c64c69739.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个自己加个参数即可
