### ISSUE TITLE
系统管理->用户管理->导出(导入)不支持角色分配

### ISSUE THREAD

**Issue by falconbin** [jeecgboot/jeecg-boot#3568]
##### 版本号：
3.0

##### 问题描述：
系统管理->用户管理->导出(导入)不支持角色分配

##### 截图&代码：
导出的excel表格里没有角色字段：
![image](https://user-images.githubusercontent.com/20329141/160964101-eac525f4-5623-4752-9134-0a52c7dc69e0.png)

导入的用户没有角色：
![image](https://user-images.githubusercontent.com/20329141/160965659-cd0803c5-68f1-4268-a1ae-6c7745a62c69.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  
### 解决方法：
 给entity\SysUser添加角色字段，对应excel表格里新添加的一列(角色), 然后导入的时候调用SysUserService里的saveUser方法。
![image](https://user-images.githubusercontent.com/20329141/160964644-7957b7bf-08fa-475d-84fb-8a1008b6e5ec.png)
现在调用的是save方法，不支持保存角色：
![image](https://user-images.githubusercontent.com/20329141/160965970-b8ae108a-6a01-4040-99fc-b6323438c5cb.png)

**Comment by zhangdaiscott** [comment]
默认没做这个逻辑，如果想做的话，用户和部门关系也没导入。
这个需求自己二开吧
