### ISSUE TITLE
菜单管理配置接口权限的建议

### ISSUE THREAD

**Issue by Nguyendream** [jeecgboot/jeecg-boot#3571]
##### 版本号：
3.1.0

##### 问题描述：
目前菜单管理里只能对按钮或者后端请求路径配置**授权标识**，无法对菜单进行配置。

如果想要控制菜单（页面）对应后端接口的访问权限，则需要在子菜单下添加至少一个权限（列表、添加、修改、删除、导出等）
这样在配置上就显得比较繁琐。

###### 改进建议：
支持给一级菜单和子菜单添加**授权标识**（非必填）
针对一些权限不需要细分的页面，一个授权标识可以包含所有增删改查的接口，就不需要在菜单管理里增加一条数据

这样就可以在控制页面路由时，能够更方便的配置后端接口权限
能够使权限配置更灵活，更简洁

##### 截图&代码：
![屏幕截图 2022-03-31 110803](https://user-images.githubusercontent.com/33228912/160983032-565ee9f3-1cb3-430e-9c9c-a0b828bb50ff.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
感谢你的建议，先收录

**Comment by TankCoder** [comment]
@Nguyendream 请问您这边使用jeecgboot开发时，配置了几层菜单？ 我这边配置到第三层隐藏路由子菜单时，无法访问该页面，不知道你是否遇到过？  这是我的问题 https://github.com/jeecgboot/jeecg-boot/issues/4013
