### ISSUE TITLE
<优化>online 在线表单，是否考虑新增一列序号，可在表单创建时选择是否显示序号

### ISSUE THREAD

**Issue by 793292556** [jeecgboot/jeecg-boot#3573]
##### 版本号：
3.1

##### 问题描述：

online 在线表单，是否考虑新增一列序号，可在表单创建时选择是否显示序号，目前生成代码后的前端页面是有序号展示，但在线表单并没有，需要序号只能自己修改页面，但又失去了使用online表单的便捷性，

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66394184/160987086-016c8677-8218-45ea-8d7f-add64e5c7c23.png)

![image](https://user-images.githubusercontent.com/66394184/160987190-08a56534-f253-447d-8322-0874c79976b2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后期考虑下
