### ISSUE TITLE
Online表单  自定义按钮可以实现提示确认框吗？

### ISSUE THREAD

**Issue by Krison-LIYUN** [jeecgboot/jeecg-boot#3576]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/42985931/161186243-e91b435b-970c-4902-a6e0-736f7a19cc3d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
只有modal这种效果的：
![image](https://user-images.githubusercontent.com/27989856/163666316-932cdcd1-5c03-4e45-bed6-7cfbb7af8d9b.png)
```
test(row){
	that.$confirm({
    title: "确认操作",
    content: "是否需要作此操作?",
    onOk: function () {
      console.log(row)
      // do sth
    }
  })
}
```
