### ISSUE TITLE
服务器上采用docker部署后端报数据库连接问题

### ISSUE THREAD

**Issue by 2842902295** [jeecgboot/jeecg-boot#3579]
##### 版本号：
3.1.0

##### 问题描述：
服务器上采用docker部署后端报数据库连接问题, 本地运行无问题, linux使用jar包运行也无问题, linux hosts也已配置. 

create connection SQLException, url: jdbc:mysql://jeecg-boot-mysql:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai, errorCode 0, state 08S01
jeecg-boot-system    | com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

##### 截图&代码：
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/39236610/161372166-aab78398-bad2-48be-af1b-6828dc50eba6.png">
<img width="468" alt="image" src="https://user-images.githubusercontent.com/39236610/161372200-16364361-643b-4f89-9a73-eebbd7a8144e.png">
<img width="697" alt="image" src="https://user-images.githubusercontent.com/39236610/161372284-19f6dfe5-0052-4894-82a2-110a3ff829f6.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
数据库怎么装的，不会docker吧

**Comment by zhangdaiscott** [comment]
无后续回复，暂时关闭

**Comment by 2842902295** [comment]
是的，docker装的。怎么解决呢

**Comment by jacobcyl** [comment]
请问你的问题解决了没有？如果解决了是如何解决的？拜托了
