### ISSUE TITLE
请问表单设计器的代码在那里啊？我找了半天没找到

### ISSUE THREAD

**Issue by hkx1312525825** [jeecgboot/jeecg-boot#3582]
##### 版本号：
 3.1.0

##### 问题描述：
请问表单设计器的代码在那里啊？我找了半天没找到

##### 截图&代码：
![image](https://user-images.githubusercontent.com/64239795/162107905-1ed36ce5-6909-410a-b049-abf43b4d71bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看功能介绍，非开源功能

**Comment by zhangdaiscott** [comment]
看功能介绍，非开源功能

**Comment by hkx1312525825** [comment]
好的谢谢
