### ISSUE TITLE
系统时常会报Network Error 

### ISSUE THREAD

**Issue by jsf0433** [jeecgboot/jeecg-boot#3585]
##### 截图&代码：
![933fd07bba8170a4fe22907aff5809a](https://user-images.githubusercontent.com/55685162/162130864-a8dbdbe1-adba-4c0e-9a1f-770f9dcc72a7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪就是后台接口不通，看看是不是数据库连接数太少，或者后台并发不够，扩展负载部署下
