### ISSUE TITLE
获取用户登录信息

### ISSUE THREAD

**Issue by zasxws** [jeecgboot/jeecg-boot#3586]
##### 版本号：
3.1.0

##### 问题描述：
获取用户登录信息，用户id和用户表里用户id不一致

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26472907/162425829-53bc59f3-3381-4d41-9986-658c1f2f2460.png)
![image](https://user-images.githubusercontent.com/26472907/162425881-2d981e52-aa46-469e-b930-3c2e8aa32271.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by zasxws** [comment]
> ty

什么意思，该怎么处理

**Comment by Chris-Arith** [comment]
> > ty
> 
> 什么意思，该怎么处理

ty应该是团队里的一名开发者，这是让开发者修复呢，等等看吧

**Comment by tygithub1** [comment]
测试没有此问题，请问是什么操作出现的？
