### ISSUE TITLE
微服务nacos指使group注册无效

### ISSUE THREAD

**Issue by huangye123** [jeecgboot/jeecg-boot#3587]
##### 版本号：
V3.1

##### 问题描述：

配置已经指定nacos的group，但运行时注册还是默认的DEFAULT_GROUP

##### 截图&代码：
![Snipaste_2022-04-11_11-51-24](https://user-images.githubusercontent.com/28778519/162662462-c9dc671b-e487-4b05-b844-c9c3c8f34671.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你走的是dev模式吗

**Comment by zhangdaiscott** [comment]
无回复，关闭
