### ISSUE TITLE
自动生成的代码后将项目放入代码中报有两个bean问题

### ISSUE THREAD

**Issue by zhoulincome** [jeecgboot/jeecg-boot#3590]
##### 版本号：
3.1.0

##### 问题描述：
自动生成的代码后将项目放入代码中报有两个bean。
***************************
APPLICATION FAILED TO START
***************************

Description:

Field service in org.jeecg.common.system.base.controller.JeecgController required a single bean, but 2 were found:
	- oaDocumentFlowServiceImpl: defined in file [/Users/tfgc/Documents/GitSource/zyt/gc-gw-application-new/jeecg-boot/tfgc-module-gw/target/classes/com/tfgc/gw/oa/documentFlow/service/impl/OaDocumentFlowServiceImpl.class]
	- IOaDocumentFlowService: defined in file [/Users/tfgc/Documents/GitSource/zyt/gc-gw-application-new/jeecg-boot/tfgc-module-gw/target/classes/com/tfgc/gw/oa/documentFlow/service/IOaDocumentFlowService.class]

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed

##### 截图&代码：

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/6369667/162711131-a1a10588-6c33-40af-adfc-905cdbefe447.png">

我自己的解决方案
在OaDocumentFlowController中IOaDocumentFlowService改成OaDocumentFlowServiceImpl就正常

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你为什么要有两个一样的类

**Comment by fredworks** [comment]
1、并不是两个一样的类，一个是接口，一个是实现类。
2、这个是你的代码生成器生成的。

**Comment by fredworks** [comment]
@zhoulincome 我也遇到了一样的问题，但是发现是因为使用了 @MapperScan 注解，且设置扫描的包范围太大，包含了Service所在的包，带来的问题。
因为 @MapperScan 注解，会为扫描到的接口自动生成代理实现类，并未代理类创建bean，然后注册到 spring 容器。因此，会出现同一个接口的两个Bean。
