### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecg-boot#3591]
##### 版本号：
3.1.0

##### 问题描述：
has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

访问登录页 验证码404

##### 截图&代码：

![image](https://user-images.githubusercontent.com/50694382/162718268-efe463f7-e28e-4b06-a72f-8ceb64a30d7a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
通过浏览器访问这个地址，看看通吗
![image](https://user-images.githubusercontent.com/3162115/162724055-5b7615c6-acdd-408d-a62f-af66bdbee8ca.png)
