### ISSUE TITLE
启动报错：Cannot resolve com.sun:tools:1.8.0

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecg-boot#3596]
##### 版本号：
3.1.0

##### 问题描述：
报错：Cannot resolve com.sun:tools:1.8.0，
需排除依赖：com.puppycrawl.tools:checkstyle
```xml
<!-- shiro-redis -->
<dependency>
	<groupId>org.crazycake</groupId>
	<artifactId>shiro-redis</artifactId>
	<version>${shiro-redis.version}</version>
	<exclusions>
		<exclusion>
			<groupId>org.apache.shiro</groupId>
			<artifactId>shiro-core</artifactId>
		</exclusion>
		<exclusion>
			<groupId>com.puppycrawl.tools</groupId>
			<artifactId>checkstyle</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

此外，返回结果乱码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14859466/163173800-aa79fdbe-3f25-42ae-8411-0249d54c7c5b.png)
乱码：
![image](https://user-images.githubusercontent.com/14859466/163174061-db9dda2d-b03e-4354-a966-a93d6ad03dba.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sco

**Comment by zhangdaiscott** [comment]
3q
