### ISSUE TITLE
新建module,生在代码后启动报错

### ISSUE THREAD

**Issue by kaleLiu** [jeecgboot/jeecg-boot#3597]
##### 截图&代码：
<img width="1036" alt="D8BBDBA5-80EE-48EF-8483-6D636CBF257D" src="https://user-images.githubusercontent.com/13827926/163297451-f0194536-f7a9-428e-917f-fd7cc9fdbd51.png">

<img width="1327" alt="屏幕快照 2022-04-13 下午6 30 23" src="https://user-images.githubusercontent.com/13827926/163297234-6a3fd553-3f98-4f97-b27e-e2444000227e.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jdk?

**Comment by zhangdaiscott** [comment]
看看新生成的模块pom.xml

**Comment by zhangdaiscott** [comment]
百度下你的错吧
