### ISSUE TITLE
sql监控页面显示异常

### ISSUE THREAD

**Issue by jackyHJ** [jeecgboot/jeecg-boot#3598]
##### 版本号：
3.1.0

##### 问题描述：
微服务sql监控页面出不来，Sorry, you are not permitted to view this page.

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/32256773/163304817-9340bcb6-ce2c-4ba4-91e9-f7c83f0c3948.png)

![图片](https://user-images.githubusercontent.com/32256773/163304672-e8765cdf-c1b9-4402-9962-0f3ac2e9295d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by fei550815954** [comment]
网页打开http://120.26.88.188:8080/jeecg-boot/druid  你试试 ip和端口号换成你的

**Comment by fei550815954** [comment]
https://gitee.com/jeecg/jeecg-boot/issues/I27AWW    点击这个连接，出门右转官方常见问题
