### ISSUE TITLE
jeecg-boot 3.1.0 微服务启动问题

### ISSUE THREAD

**Issue by hu245546853** [jeecgboot/jeecg-boot#3599]
##### 版本号：
jeecg-boot 3.1.0

##### 问题描述：
采用微服务方式启动时，启动system模块失败。
操作步骤如下：
1.勾选MAVEN中 springCloud 选项
2.修改parent中的POM文件，使用已搭建好的nacos 、mysql、redis等
3.由于网关服务无法启动，添加如下配置后，目前已启动成功
4.其他微服务启动需要注释和打开某些代码已按照操作文档操作
5.修改nacos中jeecg-dev.yaml 文件中的mysql、redis的host和账号密码信息
6.启动jeecg-cloud-system-start  失败，报错内容如下：
      ***************************
      APPLICATION FAILED TO START
      ***************************
      Description:
      Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
      Reason: Failed to determine a suitable driver class

##### 截图&代码：
1.![image](https://user-images.githubusercontent.com/57215027/163331064-fac41250-0394-4a30-88bf-40d9a20da8a2.png)
2.![image](https://user-images.githubusercontent.com/57215027/163331535-5db4062b-a2a4-4977-8184-a8d877dbb1b0.png)
3.![image](https://user-images.githubusercontent.com/57215027/163331872-9f5c3944-bfad-4414-af5e-2881e11e8cb4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
- 1 这个不需要加，默认就是数据库模式在nacos中的jeecg-dev,yaml中
![image](https://user-images.githubusercontent.com/3162115/163344590-f8c1a2c2-47de-4a03-8ad5-6df233fc5288.png)
- 2 确认下这个nacos是否能连上， 还有你的nacos中是否创建了jeecg所需要的配置文件 jeecg.yaml  jeecg-dev.yaml
目前jeecg提供了[nacos初始化脚本](https://gitee.com/jeecg/jeecg-boot/blob/master/jeecg-boot/db/tables_nacos.sql) 

![image](https://user-images.githubusercontent.com/3162115/163344703-adc3c22d-1200-42bc-b03e-156014b85cfb.png)
