### ISSUE TITLE
退出登录后一直白屏，无任何报错

### ISSUE THREAD

**Issue by czzzjj** [jeecgboot/jeecg-boot#3601]
##### 版本号：
3.1.0

##### 问题描述：
退出登录后一直白屏，无任何报错，切换浏览器也无用，指向的路由为登录页
只有重新布置一份前端代码运行才变成正常状态，但是退出登录后依旧会白屏

##### 截图&代码：

![白屏](https://user-images.githubusercontent.com/71303513/163357964-eb4f9db6-99aa-4c07-b7b8-eee4b77a40a8.png)

**Comment by zhangdaiscott** [comment]
你反馈的问题，提供信息太少，无法分析
