### ISSUE TITLE
前端项目初始化失败

### ISSUE THREAD

**Issue by 554860975** [jeecgboot/jeecg-boot#3603]
##### 截图&代码：

![1649950059(1)](https://user-images.githubusercontent.com/43947020/163422992-b87b1291-b87a-4663-a975-cc8f46387a30.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
？什么意思

**Comment by 554860975** [comment]
我换一台电脑又正常了，之前是解析整个项目从main.js执行下去，还没有执行到Vue.use(Storage, config.storageOptions)，却去解析其他js文件了，导致解析过程中遇到对Vue.ls的调用而保存，我现在正常的电脑成功运行过程中，那些js文件是没有执行的。

**Comment by 554860975** [comment]
我换一台电脑又正常了，之前是解析整个项目从main.js执行下去，还没有执行到Vue.use(Storage, config.storageOptions)，却去解析其他js文件了，导致解析过程中遇到对Vue.ls的调用而报错，我现在正常的电脑成功运行过程中，那些js文件是没有执行的

**Comment by 554860975** [comment]
最终找到了原因：是因为浏览器安装了插件Vue.js devtools导致
