### ISSUE TITLE
没有聊天功能，与在线演示的不符

### ISSUE THREAD

**Issue by LiTianyu391222** [jeecgboot/jeecg-boot#3608]
##### 版本号：
3.1.0

##### 问题描述：
右下角，没有 我的聊天按钮

##### 截图&代码：
正式：
![image](https://user-images.githubusercontent.com/85611138/163540833-0deb4ded-d4c8-4411-ae7c-737aaefd7523.png)
我的本地：
![image](https://user-images.githubusercontent.com/85611138/163540890-90ab6952-7ce2-4785-b79b-3764f1bde70c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
非开源部分

**Comment by LiTianyu391222** [comment]
> 非开源部分

好吧，本来想学习一下的。。。感谢
