### ISSUE TITLE
Online表单开发控件长度设置无效

### ISSUE THREAD

**Issue by WindWaving** [jeecgboot/jeecg-boot#3610]
##### 版本号：
3.1.0

##### 问题描述：
Online表单开发，设置控件长度无效

##### 截图&代码：
配置：
![image](https://user-images.githubusercontent.com/39412843/163668329-4555f3da-386a-4fba-8622-5b7a8a7fd393.png)
效果：
![image](https://user-images.githubusercontent.com/39412843/163668344-20089242-3c0b-45c0-8c7f-842614215e93.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个只对子表的行编辑模式有效
