### ISSUE TITLE
一对多时,子表输入框文字过长时无法显示后面的内容

### ISSUE THREAD

**Issue by zhengdebin** [jeecgboot/jeecg-boot#3616]
##### 版本号：
3.0

##### 问题描述：
当有关联表时,主表弹窗中包含的子表部分输入框内容超过输入框宽度时,超过宽度的内容默认无法显示,是否有类似于textarea这种能换行或是能自动换行等将内容显示全的方案，谢谢!
##### 截图&代码：

![image](https://user-images.githubusercontent.com/7885964/164132544-3da686db-0bfa-4fa9-b9cf-71ac6265b542.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以用多行文本组件
![image](https://user-images.githubusercontent.com/3162115/164728003-cad3618d-7899-4230-a8b3-88609a1e83b8.png)

**Comment by zhengdebin** [comment]
用了多行文本表现还是一样的，出来还是文本框
![image](https://user-images.githubusercontent.com/7885964/164956045-0aff3b9c-857c-40d2-ab70-231e47b00e2d.png)

![image](https://user-images.githubusercontent.com/7885964/164955905-cc40d401-5348-4ed8-be07-edf9f722979b.png)

**Comment by zhangdaiscott** [comment]
升级最新版看看

**Comment by zhengdebin** [comment]
试了一下，可以将type的值由FormTypes.input改为FormTypes.input_pop
![image](https://user-images.githubusercontent.com/7885964/164969356-c229bafe-aef5-4183-9e5d-fe6a269a8eb2.png)
![image](https://user-images.githubusercontent.com/7885964/164969367-4161d295-31af-4a62-a2cb-5b0d004f43f2.png)
