### ISSUE TITLE
Online表单支持一表多用吗？

### ISSUE THREAD

**Issue by jiawei5807** [jeecgboot/jeecg-boot#3618]
##### 问题描述：
情景：A，B，C三张表，B中有外键A，C中有外键B。
需求：实现查询 B表 的时候能够看到 相应的A表的数据查询C表 的时候可以看到相应的B表数据，应该如何通过在线表单功能实现？
目前发现无法通过主附表方式实现，因为B表只能作为主表或附表使用，不能同时设置。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
online表单测试数据维护，不支持
你可以通过online报表写sql，实现你的数据查询
