### ISSUE TITLE
没有流程设计等菜单

### ISSUE THREAD

**Issue by liuliang6666** [jeecgboot/jeecg-boot#3619]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/103915530/164411953-45736565-27d3-450d-a952-5a82a5aed15c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看功能介绍
