### ISSUE TITLE
JeecgDemoCloudApplication 启动报错

### ISSUE THREAD

**Issue by aaronlean** [jeecgboot/jeecg-boot#3622]
##### 版本号：
Jeecg-Boot 3.2.0（发布日期：20220425）

##### 问题描述：

Error creating bean with name 'shiroFilterFactoryBean' 
项目其它模块都成功启动，JeecgDemoCloudApplication启动报错
##### 截图&代码：
![image](https://user-images.githubusercontent.com/9336658/164880168-2463c51c-3840-4e6f-814b-6c477f2968a3.png)

![image](https://user-images.githubusercontent.com/9336658/164880394-4e5a04a7-e20e-4823-bfe7-5bdd68354265.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
clean 下 maven

**Comment by luo-ky** [comment]
兄台，请问你解决这个问题了吗？

**Comment by aaronlean** [comment]
@zhangdaiscott @luo-ky
还是没搞定，一样的错误

**Comment by luo-ky** [comment]
> @zhangdaiscott @luo-ky 还是没搞定，一样的错误

兄弟 ，我解决了，我重新拉了git的 jeecg-boot最新代码，然后放至d盘建了一个itemspace的文件夹，再把 jeecg-boot.zip 解压放至itemspace的文件夹下，就是itemspace -> jeecg-boot/ant-design-vue-jeecg 这样的结构，导入idea运行就可以了。我昨天上的gitee拉的代码就一直报这个错，也不知道是我这边哪里没配置好还是项目放的目录不对的问题？这个问题我看了别人之前也遇到过，他的解决方法就是目录那里多了一个. 导致的，你试下对你有用没？

**Comment by hdtopku** [comment]
@aaronlean 解决了吗？同样的报错

**Comment by aaronlean** [comment]
> 兄弟 ，我解决了，我重新拉了git的 jeecg-boot最新代码，然后放至d盘建了一个itemspace的文件夹，再把 jeecg-boot.zip 解压放至itemspace的文件夹下，就是itemspace -> jeecg-boot/ant-design-vue-jeecg 这样的结构，导入idea运行就可以了。我昨天上的gitee拉的代码就一直报这个错，也不知道是我这边哪里没配置好还是项目放的目录不对的问题？这个问题我看了别人之前也遇到过，他的解决方法就是目录那里多了一个. 导致的，你试下对你有用没？ @aaronlean

@luo-ky @hdtopku 搞定了，谢谢啊

**Comment by aaronlean** [comment]
> @aaronlean 解决了吗？同样的报错

解决了

**Comment by hdtopku** [comment]
> 兄弟 ，我解决了，我重新拉了git的 jeecg-boot最新代码，然后放至d盘建了一个itemspace的文件夹，再把 jeecg-boot.zip 解压放至itemspace的文件夹下，就是itemspace -> jeecg-boot/ant-design-vue-jeecg 这样的结构，导入idea运行就可以了。我昨天上的gitee拉的代码就一直报这个错，也不知道是我这边哪里没配置好还是项目放的目录不对的问题？这个问题我看了别人之前也遇到过，他的解决方法就是目录那里多了一个. 导致的，你试下对你有用没？ @aaronlean

@aaronlean 是这么解决的吗？

**Comment by hdtopku** [comment]
我按上面的操作，没搞定，怎么搞定的不能说一下吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月26日(周二) 中午11:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] JeecgDemoCloudApplication 启动报错 (Issue #3622)




  
@aaronlean 解决了吗？同样的报错
  
解决了

**Comment by aaronlean** [comment]
我把所有的文件都删了，从新下载了，更改了文件目录
![image](https://user-images.githubusercontent.com/9336658/166870585-7f30cc2e-ebfa-4a3d-952e-0b404b5f52a8.png)
