### ISSUE TITLE
Knife4j ui  接口文档不显示

### ISSUE THREAD

**Issue by leohao1018** [jeecgboot/jeecg-boot#3623]
##### 版本号：
3.2.0
##### 问题描述：
Knife4j ui  接口文档显示不出来

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
能详细点吗

**Comment by leohao1018** [comment]
微服务模式启动 swagger 文档页面能显示，但是不现实接口信息，也没法测试；
已解决：
    默认nacos 中的配置的问题缺少了线面的配置
# 设置静态文件路径，js,css等
  mvc:
    #Spring Boot 2.6+后映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser,需要手动指定为ant-path-matcher
    pathmatch:
      matching-strategy: ant_path_matcher
