### ISSUE TITLE
数据库执行异常handleDataIntegrityViolationException提示有误

### ISSUE THREAD

**Issue by huangye123** [jeecgboot/jeecg-boot#3624]
##### 版本号：
V3.1

##### 问题描述：

执行数据库异常时，如某个非空的字段未赋值异常时，返回前端时统一”字段太长,超出数据库字段的长度“，容易对异常信息造成误判。

实际异常原因与提示的原因不一致。

Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: null value in column "taskicon_id" of relation "agr_base_tasktype" violates not-null constraint

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28778519/164894541-a9789f78-b688-4930-8bb9-fe30576d68b3.png)
![image](https://user-images.githubusercontent.com/28778519/164894544-8ba3e76c-516e-408e-abdb-ae76172745e0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sco

**Comment by zhangdaiscott** [comment]
已经修复
```
   @ExceptionHandler(DataIntegrityViolationException.class)
    public Result<?> handleDataIntegrityViolationException(DataIntegrityViolationException e) {
    	log.error(e.getMessage(), e);
    	//【issues/3624】数据库执行异常handleDataIntegrityViolationException提示有误 #3624
        return Result.error("执行数据库异常,违反了完整性例如：违反惟一约束、违反字段非空限制、字段内容超出长度等");
    }
```
