### ISSUE TITLE
online表单开发 功能测试和生成的代码结果不一致bug

### ISSUE THREAD

**Issue by yilongmd** [jeecgboot/jeecg-boot#3625]
##### 版本号：
3.1.0

##### 问题描述：
在线测试和部署不一致, 数据库也存储也有问题(Auto在线表单存储的是id字段, 部署代码存储是username)

##### 截图&代码：
在线功能测试
![image](https://user-images.githubusercontent.com/6745227/164944232-b5423fb4-e841-44bd-8a81-144b41dc6d1c.png)

生成代码部署:
![image](https://user-images.githubusercontent.com/6745227/164944235-9b61d9fc-8925-4de6-8f57-f7206278e4b6.png)

生成代码新增一行数据:
![image](https://user-images.githubusercontent.com/6745227/164944240-5bafea40-36a4-4ca2-9062-d1ba0a8425e2.png)

数据库存储也有问题:
![image](https://user-images.githubusercontent.com/6745227/164944246-6d1370b5-9625-4c0d-8126-7136b20e9e8e.png)

表单设计:
![image](https://user-images.githubusercontent.com/6745227/164944252-789ba050-2889-4b83-a431-28a7ef35ad97.png)

扩展参数:
{"store":"id", "text":"username"}

**Comment by zhangdaiscott** [comment]
看看生成的代码，代码截图
![image](https://user-images.githubusercontent.com/3162115/164972083-16893cfb-ceb5-4c0d-a0ac-067e09b13715.png)

**Comment by zhangdaiscott** [comment]
无回复，一天后关闭

**Comment by yilongmd** [comment]
导致不一样的是因为, 在线生成器生成代码 dicCode保持了默认, 没有使用配置的{"store":"id", "text":"username"}, 其他地方某些地方是否也有影响
`/**绑定用户*/
	@Excel(name = "绑定用户", width = 15, dictTable = "sys_user", dicText = "realname", dicCode = "username")
	@Dict(dictTable = "sys_user", dicText = "realname", dicCode = "username)
    @ApiModelProperty(value = "绑定用户")
    private java.lang.String bindUser;`

我手工修改成了:
`/**绑定用户*/
	@Excel(name = "绑定用户", width = 15, dictTable = "sys_user", dicText = "username", dicCode = "id")
	@Dict(dictTable = "sys_user", dicText = "username", dicCode = "id")
    @ApiModelProperty(value = "绑定用户")
    private java.lang.String bindUser;`

......

**Comment by yilongmd** [comment]
> 

导致不一样的是因为, 在线生成器生成代码 dicCode保持了默认, 没有使用配置的{"store":"id", "text":"username"}, 其他地方某些地方是否也有影响
/**绑定用户*/ @Excel(name = "绑定用户", width = 15, dictTable = "sys_user", dicText = "realname", dicCode = "username") @Dict(dictTable = "sys_user", dicText = "realname", dicCode = "username) @ApiModelProperty(value = "绑定用户") private java.lang.String bindUser;

我手工修改成了:
/**绑定用户*/ @Excel(name = "绑定用户", width = 15, dictTable = "sys_user", dicText = "username", dicCode = "id") @Dict(dictTable = "sys_user", dicText = "username", dicCode = "id") @ApiModelProperty(value = "绑定用户") private java.lang.String bindUser;

......

**Comment by tygithub1** [comment]
已修改
