### ISSUE TITLE
用户管理表sys_user字段org_code

### ISSUE THREAD

**Issue by gelinagg** [jeecgboot/jeecg-boot#3626]
##### 版本号：
3.1

##### 问题描述：
用户管理表sys_user字段org_code新增、编辑

##### 截图&代码：
用户管理表sys_user字段org_code新增、编辑的时候，数据库中该字段没有保存，是取消这个功能了吗？
![image](https://user-images.githubusercontent.com/17491916/164953495-bf5c895c-3355-4ad4-9a7f-bd3dca2b5750.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不建议

**Comment by gelinagg** [comment]
是不建议这个字段中保存部门编码的信息吗？
