### ISSUE TITLE
jeecgboot online表单开发，表类型为：单表(树)；自定义一张表以后，添加完数据不能自动刷新

### ISSUE THREAD

**Issue by hrbshengdong** [jeecgboot/jeecg-boot#3628]
##### 截图&代码：在B站里有视频，请点击看一下，能让贵单位更清晰了解问题
https://www.bilibili.com/video/bv1YY411P7Pi

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
版本太老了，无法处理
