### ISSUE TITLE
springcloud无法启动，报错FallbackFactory.class does not exist

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecg-boot#3632]
##### 版本号：
版本发布 3.2.0

##### 问题描述：
springcloud项目启动报错：
Failed to parse configuration class [org.jeecg.JeecgDemoCloudApplication]; nested exception is java.io.FileNotFoundException: class path resource [feign/hystrix/FallbackFactory.class] cannot be opened because it does not exist
网上查的是：[关于java:springbootspringcloud-版本升级带来了对feignhystrix使用的思考](https://lequ7.com/guan-yu-javaspringbootspringcloud-ban-ben-sheng-ji-dai-lai-le-dui-feignhystrix-shi-yong-de-si-kao.html)，不过我把openfeign降级到2.2.2.RELEASE，还是同样的报错，不知道什么原因导致的

##### 截图&代码：
配置正常gou shan勾上了
![image](https://user-images.githubusercontent.com/14859466/165066285-78a22403-a0b5-43d6-910a-cbd09b1b7694.png)
报错信息
![image](https://user-images.githubusercontent.com/14859466/165066570-60412b96-5d6f-4f59-93d2-89a061b2ef76.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你跑的是原始下载版本还是自己升级的？

**Comment by hdtopku** [comment]
> 你跑的是原始下载版本还是自己升级的？

就是直接pull下来的最新版，跑的时候就报错了

![image](https://user-images.githubusercontent.com/14859466/165072216-ec3385e6-bfc7-489b-b7bd-eff23d37a6de.png)

**Comment by hdtopku** [comment]
我的hosts信息如下配置，redis、mysql和nacos用的是自己服务器地址，会是下面的原因导致的吗？
```
121.41.17.120 jeecg-boot-redis
121.41.17.120 jeecg-boot-mysql
121.41.17.120 jeecg-boot-nacos
0.0.0.0 jeecg-boot-gateway
0.0.0.0 jeecg-boot-system
0.0.0.0 jeecg-boot-sentinel
0.0.0.0 jeecg-boot-xxljob
0.0.0.0 jeecg-boot-rabbitmq
```

**Comment by hdtopku** [comment]
nacos中的配置
![image](https://user-images.githubusercontent.com/14859466/165076889-f07e2b3c-4b9b-4292-b236-ca44b458ec08.png)

**Comment by zhangdaiscott** [comment]
别人运行没有问题，确认下你项目里哪里用到了这个
![image](https://user-images.githubusercontent.com/3162115/165078423-e0199bc0-9823-45a1-92c2-f49d2b97c345.png)

**Comment by zhangdaiscott** [comment]
你的nacos配置是不是用的老的？

**Comment by hdtopku** [comment]
整个项目是新拉下来的，启动就报错了。


> 你的nacos配置是不是用的老的？

这是我nacos的配置：[https://ws28.cn/f/85vizf15q25](https://ws28.cn/f/85vizf15q25)

我用的是自己的nacos，我记得nacos不需要密码，为啥这里填了密码呢？我nacos的密码不是nacos，会不会是这个原因？

![image](https://user-images.githubusercontent.com/14859466/165083360-d0c3fd56-a318-4d55-8e26-ce8736c1acbf.png)

**Comment by hdtopku** [comment]
这是我nacos的配置：[https://ws28.cn/f/85vkbjiqg2f)](https://ws28.cn/f/85vkbjiqg2f))

**Comment by zhangdaiscott** [comment]
当然有问题，如果密码不对，nacos肯定连不上

**Comment by hdtopku** [comment]
修改了密码，也没用，报同样的错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月25日(周一) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] springcloud无法启动，报错FallbackFactory.class does not exist (Issue #3632)




 
当然有问题，如果密码不对，nacos肯定连不上

**Comment by hdtopku** [comment]
重新拉一下代码，没报错了
