### ISSUE TITLE
JwtFilter中ThreadLocal需要及时清除

### ISSUE THREAD

**Issue by liuhr-ncu** [jeecgboot/jeecg-boot#3634]
##### 截图&代码：
JwtFilter.java
![1650935798(1)](https://user-images.githubusercontent.com/29883424/165199694-270fa152-d2ca-4ccb-a111-931cda2945e4.png)

需要加上清除代码

```
    @Override
    public void afterCompletion(ServletRequest request, ServletResponse response, Exception exception) throws Exception {
        TenantContext.clear();
    }
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
修复了，下个版本发布
