### ISSUE TITLE
[bug] config.headers[ 'tenant-id' ] = ‘’时，接口会把其他所有租户的数据都查询出来

### ISSUE THREAD

**Issue by a6051529** [jeecgboot/jeecg-boot#3635]
##### 截图&代码：
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/7309118/165203962-8200b9f7-afb9-428e-bc2b-ada8f7381a34.png">
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/7309118/165204243-f4aaf342-8b95-41be-ac3f-70541805d27d.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如果你需要严格的，可以在后台加一个默认租户ID,为空的时候，设置一个默认的

**Comment by a6051529** [comment]
> 如果你需要严格的，可以在后台加一个默认租户ID,为空的时候，设置一个默认的

此处的核心问题不是设置一个默认的，如果前端知道其他的租户id，或者随便传递一个config.headers[ 'tenant-id' ] = ‘3’，如果后端不加以鉴权的话，会把其他租户的数据也查询出来，不知道现在后台系统里面有没有方法可以识别出当前请求用户的身份，不采用前端传值的方式
