### ISSUE TITLE
版本2.4.6  服务器部署之后 第一次加载非常缓慢，

### ISSUE THREAD

**Issue by EdisionLiu** [jeecgboot/jeecg-boot#3639]
##### 版本号：
2.4.6

##### 问题描述：

版本2.4.6  服务器部署之后 第一次加载非常缓慢，已经使用nginx压缩，antdesign 按需加载
##### 截图&代码：
![微信图片_20220427135038](https://user-images.githubusercontent.com/44572438/165452065-f7034538-d578-409b-ac8d-b59ccf4759c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
哪没别的更好办法了
