### ISSUE TITLE
jeecg-cloud-xxljob不支持oracle

### ISSUE THREAD

**Issue by lulusoft** [jeecgboot/jeecg-boot#3643]
##### 版本号：
3.2.0

##### 问题描述：
jeecg-cloud-xxljob 的mybatis-mapper的xml不支持oracle
启动报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/3874472/165656224-0287ba0f-a608-480f-9a16-0a77a1db4661.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这是xxljob的代码，需要其他库，请自己改造
