### ISSUE TITLE
cloud 启动 提示定时任务没有数据源 ${dataSource-1}

### ISSUE THREAD

**Issue by 2egg** [jeecgboot/jeecg-boot#3644]
##### 版本号：
3.2

##### 截图&代码：

dataSource-1,master} inited
Scheduler MyScheduler_$_test01771651115523602 shutting down.
Scheduler MyScheduler_$_test01771651115523602 paused.
Database connection shutdown unsuccessful.
There is no DataSource named 'null'
Error creating bean with name 'quartzJobServiceImpl': Unsatisfied dependency expressed through field 'scheduler'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'quartzScheduler' defined in class path resource [org/springframework/boot/autoconfigure/quartz/QuartzAutoConfiguration.class]: Invocation of init method failed; nested exception is org.quartz.SchedulerConfigException: DataSource name not set.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
启动的那个类

**Comment by 2egg** [comment]
CLOUD-SYSTEM-START

**Comment by 2egg** [comment]
我把application-dev.yml 中的
![网页捕获_28-4-2022_13396_localhost](https://user-images.githubusercontent.com/42636585/165683836-06feb9f2-3fde-4a31-8748-a130e94a5cf6.jpeg)
class 注释之后不出现这个问题了， 这样是对的吗？

**Comment by zhangdaiscott** [comment]
最新版已经改了，你用自己的naocs不升级导致
