### ISSUE TITLE
关于导入Excel文件功能，数据入库前须检查或预处理的需求

### ISSUE THREAD

**Issue by yjh4866** [jeecgboot/jeecg-boot#3645]
##### 版本号：
所有版本

##### 问题描述：
导入Excel文件时，建议增加一个莱姆达回调，用于数据入库前的检查，或者数据的特殊处理

##### 截图&代码：
JeecgController中的方法importExcel

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
参考下用户列表的导入，可以手工加校验
org.jeecg.modules.system.controller.SysUserController#importExcel

其他
http://doc.jeecg.com/2043966
