### ISSUE TITLE
前端权限控制，v-has只支持一个权限标识，希望可以支持权限标识的与或混合表达式

### ISSUE THREAD

**Issue by yjh4866** [jeecgboot/jeecg-boot#3647]
##### 版本号：
所有版本

##### 问题描述：
前端权限控制，v-has只支持一个权限标识，希望可以支持权限标识的与或混合表达式

##### 截图&代码：
实现这个功能有点难度，需要懂编译原理，文法分析、语法分析

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/167540884-cfedbfa1-4297-40b9-a39f-b9b074c88f48.png)

**Comment by yjh4866** [comment]
逗号分隔的多个标识，既可以与运算也可以或运算？
