### ISSUE TITLE
积木报表中API数据集解析时出现数据为空，可是在浏览器中可以得到相应的数据

### ISSUE THREAD

**Issue by fendouhuohuo** [jeecgboot/jeecg-boot#3648]
##### 版本号：
3.1.0

##### 问题描述：
积木报表中API数据集解析时出现数据为空，可是在浏览器中可以得到相应的数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/77576749/165697041-15a711cf-61fc-4ff7-874b-bf2e85cfc4a7.png)
![image](https://user-images.githubusercontent.com/77576749/165697104-d2c857ad-2b30-4f23-a07a-cbed90436122.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by fendouhuohuo** [comment]
已解决

**Comment by zyinux** [comment]
兄弟，怎么解决的，我也遇到这个问题了

**Comment by HuDengfei** [comment]
请问怎么解决的
