### ISSUE TITLE
【代码生成器】linux 环境docker部署 提示error

### ISSUE THREAD

**Issue by iwongta** [jeecgboot/jeecg-boot#3649]
##### 版本号：
<groupId>org.jeecgframework.boot</groupId>
  <artifactId>jeecg-boot-parent</artifactId>
  <version>3.1.0</version>

##### 问题描述：

**linux 环境docker部署 提示:**
:::::: 生成失败ERROR提醒 ::::::

1.未找到代码生成器模板，请确认路径是否含有中文或特殊字符！

2.如果是JAR包运行，请参考此文档 http://doc.jeecg.com/2043922

**后端服务日志：**
![image](https://user-images.githubusercontent.com/35144144/165706618-b6fa6c6e-3769-4dfb-b975-c25469ff298b.png)

out目录下未找到生成的代码，请问是什么原因呢

**Comment by zhangdaiscott** [comment]
常见问题有这个问题：http://jeecg.com/doc/qa

**Comment by iwongta** [comment]
> 常见问题有这个问题：http://jeecg.com/doc/qa

升级了版本还是不行

**Comment by iwongta** [comment]
out路径是：out GenerateRootDir:/opt/jre     不存在中文和空格
