### ISSUE TITLE
用户管理处编辑了用户的负责部门后表格没有刷新

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#3650]
##### 版本号：
3.2.0\vue3前端

##### 问题描述：
用户管理处编辑了用户的负责部门后表格没有刷新

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/165718922-791edf7d-50b7-4553-ad7b-225c0312865e.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
已处理，下个版本发布
