### ISSUE TITLE
大哥们，自己业务的数据库表能跟jeecgboot的数据库表分开吗

### ISSUE THREAD

**Issue by ycruel318** [jeecgboot/jeecg-boot#3658]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/75959670/165933054-b52625fa-6ecf-4f72-bc7b-f6f3323c64ff.png)

**Comment by ycruel318** [comment]
谢谢啦

**Comment by chrelyonly** [comment]
可以考虑多数据源来管理
