### ISSUE TITLE
同步钉钉用户到本地

### ISSUE THREAD

**Issue by 826309604** [jeecgboot/jeecg-boot#3666]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/20295476/166855530-c7bb3580-f90a-4b48-bad0-6511758efc1d.png)
![image](https://user-images.githubusercontent.com/20295476/166855640-c2a81b17-9aea-433a-ad56-437f8c91f929.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
