### ISSUE TITLE
[BUG?]表单一对多，字表查询无法生成

### ISSUE THREAD

**Issue by ycruel318** [jeecgboot/jeecg-boot#3667]
##### 问题描述：
功能测试的时候附表有查询条件，代码生成出来没有

##### 截图&代码：
功能测试的时候有
![image](https://user-images.githubusercontent.com/75959670/166859285-662ade3b-a74a-4e4f-9489-247ddc5f0e92.png)
代码生成出来没有
![image](https://user-images.githubusercontent.com/75959670/166859243-1f0c2276-11fa-4cc4-860d-388af2a6dc72.png)

**Comment by zhangdaiscott** [comment]
online在线功能，并不是全支持生成，不支持的，请手工修改代码实现
