### ISSUE TITLE
扩展参数showLength配置在生成代码后无效问题

### ISSUE THREAD

**Issue by ysy411** [jeecgboot/jeecg-boot#3670]
##### 版本号：
3.2.0

##### 问题描述：
扩展参数showLength配置在生成代码后无效问题，在online开发“功能测试”中是正常的。

##### 截图&代码：
![@MMS5PP~8(GDYZT $({A`MK](https://user-images.githubusercontent.com/36321617/166893712-453c06d5-0b81-403e-ad4f-e805ee493a35.png)

![N$WN0{}7ON67N741IMVT%}4](https://user-images.githubusercontent.com/36321617/166893736-1d1d3954-21b1-4599-84e3-aff58b3245f1.png)
![VAPDNZU98 ~7JK$OMW6USTQ](https://user-images.githubusercontent.com/36321617/166893753-a05897a6-a725-47a9-9ef7-d0a1757ee6f0.png)

生成的代码：
GriddingInformationList.vue
-------------------------
<template>
  <a-card :bordered="false">
    
    <div class="table-page-search-wrapper">
      <a-form layout="inline" @keyup.enter.native="searchQuery">
        <a-row :gutter="24">
          <a-col :xl="6" :lg="7" :md="8" :sm="24">
            <a-form-item label="网格名称">
              <a-input placeholder="请输入网格名称" v-model="queryParam.gridName"></a-input>
            </a-form-item>
          </a-col>
          <a-col :xl="6" :lg="7" :md="8" :sm="24">
            <a-form-item label="网格级别">
              <j-dict-select-tag placeholder="请选择网格级别" v-model="queryParam.gridLevel" dictCode="grid_level"/>
            </a-form-item>
          </a-col>
          <a-col :xl="6" :lg="7" :md="8" :sm="24">
            <span style="float: left;overflow: hidden;" class="table-page-search-submitButtons">
              <a-button type="primary" @click="searchQuery" icon="search">查询</a-button>
              <a-button type="primary" @click="searchReset" icon="reload" style="margin-left: 8px">重置</a-button>
              <a @click="handleToggleSearch" style="margin-left: 8px">
                {{ toggleSearchStatus ? '收起' : '展开' }}
                <a-icon :type="toggleSearchStatus ? 'up' : 'down'"/>
              </a>
            </span>
          </a-col>
        </a-row>
      </a-form>
    </div>
    

    
    <div class="table-operator">
      <a-button @click="handleAdd" type="primary" icon="plus">新增</a-button>
      <a-button type="primary" icon="download" @click="handleExportXls('网格信息表')">导出</a-button>
      <a-upload name="file" :showUploadList="false" :multiple="false" :headers="tokenHeader" :action="importExcelUrl" @change="handleImportExcel">
        <a-button type="primary" icon="import">导入</a-button>
      </a-upload>
      
      <j-super-query :fieldList="superFieldList" ref="superQueryModal" @handleSuperQuery="handleSuperQuery"></j-super-query>
      <a-dropdown v-if="selectedRowKeys.length > 0">
        <a-menu slot="overlay">
          <a-menu-item key="1" @click="batchDel"><a-icon type="delete"/>删除</a-menu-item>
        </a-menu>
        <a-button style="margin-left: 8px"> 批量操作 <a-icon type="down" /></a-button>
      </a-dropdown>
    </div>

    
    <div>
      <div class="ant-alert ant-alert-info" style="margin-bottom: 16px;">
        <i class="anticon anticon-info-circle ant-alert-icon"></i> 已选择 <a style="font-weight: 600">{{ selectedRowKeys.length }}</a>项
        <a style="margin-left: 24px" @click="onClearSelected">清空</a>
      </div>

      <a-table
        ref="table"
        size="middle"
        rowKey="id"
        class="j-table-force-nowrap"
        :scroll="{x:true}"
        :columns="columns"
        :dataSource="dataSource"
        :pagination="ipagination"
        :loading="loading"
        :expandedRowKeys="expandedRowKeys"
        @change="handleTableChange"
        @expand="handleExpand"
        v-bind="tableProps">

        <template slot="imgSlot" slot-scope="text,record">
          <span v-if="!text" style="font-size: 12px;font-style: italic;">无图片</span>
          <img v-else :src="getImgView(text)" :preview="record.id" height="25px" alt="" style="max-width:80px;font-size: 12px;font-style: italic;"/>
        </template>
        <template slot="fileSlot" slot-scope="text">
          <span v-if="!text" style="font-size: 12px;font-style: italic;">无文件</span>
          <a-button
            v-else
            :ghost="true"
            type="primary"
            icon="download"
            size="small"
            @click="downloadFile(text)">
            下载
          </a-button>
        </template>

        <span slot="action" slot-scope="text, record">
          <a @click="handleEdit(record)">编辑</a>

          <a-divider type="vertical" />
          <a-dropdown>
            <a class="ant-dropdown-link">更多 <a-icon type="down" /></a>
            <a-menu slot="overlay">
              <a-menu-item>
                <a @click="handleAddChild(record)">添加下级</a>
              </a-menu-item>
              <a-menu-item>
                <a-popconfirm title="确定删除吗?" @confirm="() => handleDeleteNode(record.id)" placement="topLeft">
                  <a>删除</a>
                </a-popconfirm>
              </a-menu-item>
            </a-menu>
          </a-dropdown>
        </span>

      </a-table>
    </div>

    <griddingInformation-modal ref="modalForm" @ok="modalFormOk"></griddingInformation-modal>
  </a-card>
</template>

<script>

  import { getAction, deleteAction } from '@/api/manage'
  import { JeecgListMixin } from '@/mixins/JeecgListMixin'
  import GriddingInformationModal from './modules/GriddingInformationModal'
  import {filterMultiDictText} from '@/components/dict/JDictSelectUtil'
  import { filterObj } from '@/utils/util';
  import { loadCategoryData } from '@/api/api'

  export default {
    name: "GriddingInformationList",
    mixins:[JeecgListMixin],
    components: {
      GriddingInformationModal
    },
    data () {
      return {
        description: '网格信息表管理页面',
        // 表头
        columns: [
          {
            title:'网格名称',
            align:"left",
            dataIndex: 'gridName'
          },
          {
            title:'网格级别',
            align:"left",
            dataIndex: 'gridLevel_dictText'
          },
          {
            title:'网格描述',
            align:"left",
            dataIndex: 'gridDesc'
          },
          {
            title:'中心点经度',
            align:"left",
            dataIndex: 'longitude',
            customRender: (text) => (text ? filterMultiDictText(this.dictOptions['longitude'], text) : '')
          },
          {
            title:'中心点纬度',
            align:"left",
            dataIndex: 'latitude'
          },
          {
            title:'边界经纬度',
            align:"left",
            dataIndex: 'llBorder'
          },
          {
            title:'有效性状态',
            align:"left",
            dataIndex: 'statusValid_dictText'
          },
          {
            title: '操作',
            dataIndex: 'action',
            align:"center",
            fixed:"right",
            width:147,
            scopedSlots: { customRender: 'action' },
          }
        ],
        url: {
          list: "/grid/griddingInformation/rootList",
          childList: "/grid/griddingInformation/childList",
          getChildListBatch: "/grid/griddingInformation/getChildListBatch",
          delete: "/grid/griddingInformation/delete",
          deleteBatch: "/grid/griddingInformation/deleteBatch",
          exportXlsUrl: "/grid/griddingInformation/exportXls",
          importExcelUrl: "grid/griddingInformation/importExcel",
        },
        expandedRowKeys:[],
        hasChildrenField:"hasChild",
        pidField:"pid",
        dictOptions: {},
        loadParent: false,
        superFieldList:[],
      }
    },
    created() {
      this.getSuperFieldList();
    },
    computed: {
      importExcelUrl(){
        return `${window._CONFIG['domianURL']}/${this.url.importExcelUrl}`;
      },
      tableProps() {
        let _this = this
        return {
          // 列表项是否可选择
          rowSelection: {
            selectedRowKeys: _this.selectedRowKeys,
            onChange: (selectedRowKeys) => _this.selectedRowKeys = selectedRowKeys
          }
        }
      }
    },
    methods: {
      loadData(arg){
        if(arg==1){
          this.ipagination.current=1
        }
        this.loading = true
        let params = this.getQueryParams()
        params.hasQuery = 'true'
        getAction(this.url.list,params).then(res=>{
          if(res.success){
            let result = res.result
            if(Number(result.total)>0){
              this.ipagination.total = Number(result.total)
              this.dataSource = this.getDataByResult(res.result.records)
              return this.loadDataByExpandedRows(this.dataSource)
            }else{
              this.ipagination.total=0
              this.dataSource=[]
            }
          }else{
            this.$message.warning(res.message)
          }
        }).finally(()=>{
          this.loading = false
        })
      },
      // 根据已展开的行查询数据（用于保存后刷新时异步加载子级的数据）
      loadDataByExpandedRows(dataList) {
        if (this.expandedRowKeys.length > 0) {
          return getAction(this.url.getChildListBatch,{ parentIds: this.expandedRowKeys.join(',') }).then(res=>{
            if (res.success && res.result.records.length>0) {
              //已展开的数据批量子节点
              let records = res.result.records
              const listMap = new Map();
              for (let item of records) {
                let pid = item[this.pidField];
                if (this.expandedRowKeys.join(',').includes(pid)) {
                 let mapList = listMap.get(pid);
                  if (mapList == null) {
                    mapList = [];
                  }
                  mapList.push(item);
                  listMap.set(pid, mapList);
                }
              }
              let childrenMap = listMap;
              let fn = (list) => {
                if(list) {
                  list.forEach(data => {
                    if (this.expandedRowKeys.includes(data.id)) {
                      data.children = this.getDataByResult(childrenMap.get(data.id))
                      fn(data.children)
                    }
                  })
                }
              }
              fn(dataList)
            }
          })
        } else {
          return Promise.resolve()
        }
      },
      getQueryParams(arg) {
        //获取查询条件
        let sqp = {}
        let param = {}
        if(this.superQueryParams){
          sqp['superQueryParams']=encodeURI(this.superQueryParams)
          sqp['superQueryMatchType'] = this.superQueryMatchType
        }
        if(arg){
          param = Object.assign(sqp, this.isorter ,this.filters);
        }else{
          param = Object.assign(sqp, this.queryParam, this.isorter ,this.filters);
        }
        if(JSON.stringify(this.queryParam) === "{}" || arg){
          param.hasQuery = 'false'
        }else{
          param.hasQuery = 'true'
        }
        param.field = this.getQueryField();
        param.pageNo = this.ipagination.current;
        param.pageSize = this.ipagination.pageSize;
        return filterObj(param);
      },
      searchReset() {
        //重置
        this.expandedRowKeys = []
        this.queryParam = {}
        this.loadData(1);
      },
      getDataByResult(result){
        if(result){
          return result.map(item=>{
            //判断是否标记了带有子节点
            if(item[this.hasChildrenField]=='1'){
              let loadChild = { id: item.id+'_loadChild', name: 'loading...', isLoading: true }
              item.children = [loadChild]
            }
            return item
          })
        }
      },
      handleExpand(expanded, record){
        // 判断是否是展开状态
        if (expanded) {
          this.expandedRowKeys.push(record.id)
          if (record.children.length>0 && record.children[0].isLoading === true) {
            let params = this.getQueryParams(1);//查询条件
            params[this.pidField] = record.id
            params.hasQuery = 'false'
            params.superQueryParams=""
            getAction(this.url.childList,params).then((res)=>{
              if(res.success){
                if(res.result.records){
                  record.children = this.getDataByResult(res.result.records)
                  this.dataSource = [...this.dataSource]
                }else{
                  record.children=''
                  record.hasChildrenField='0'
                }
              }else{
                this.$message.warning(res.message)
              }
            })
          }
        }else{
          let keyIndex = this.expandedRowKeys.indexOf(record.id)
          if(keyIndex>=0){
            this.expandedRowKeys.splice(keyIndex, 1);
          }
        }
      },
      handleAddChild(record){
        this.loadParent = true
        let obj = {}
        obj[this.pidField] = record['id']
        this.$refs.modalForm.add(obj);
      },
      handleDeleteNode(id) {
        if(!this.url.delete){
          this.$message.error("请设置url.delete属性!")
          return
        }
        var that = this;
        deleteAction(that.url.delete, {id: id}).then((res) => {
          if (res.success) {
             that.loadData(1)
          } else {
            that.$message.warning(res.message);
          }
        });
      },
      batchDel(){
        if(this.selectedRowKeys.length<=0){
          this.$message.warning('请选择一条记录！');
          return false;
        }else{
          let ids = "";
          let that = this;
          that.selectedRowKeys.forEach(function(val) {
            ids+=val+",";
          });
          that.$confirm({
            title:"确认删除",
            content:"是否删除选中数据?",
            onOk: function(){
              that.handleDeleteNode(ids)
              that.onClearSelected();
            }
          });
        }
      },
      getSuperFieldList(){
        let fieldList=[];
        fieldList.push({type:'string',value:'pid',text:'上级网格',dictCode:''})
        fieldList.push({type:'string',value:'gridName',text:'网格名称',dictCode:''})
        fieldList.push({type:'int',value:'gridLevel',text:'网格级别',dictCode:'grid_level'})
        fieldList.push({type:'Text',value:'gridDesc',text:'网格描述',dictCode:''})
        fieldList.push({type:'string',value:'longitude',text:'中心点经度'})
        fieldList.push({type:'string',value:'latitude',text:'中心点纬度',dictCode:''})
        fieldList.push({type:'Text',value:'llBorder',text:'边界经纬度',dictCode:''})
        fieldList.push({type:'int',value:'statusValid',text:'有效性状态',dictCode:'valid_status'})
        this.superFieldList = fieldList
      }
    }
  }
</script>
<style scoped>
  @import '~@assets/less/common.less';
</style>
------------------------
GriddingInformationModal.vue

-------------------------------
<template>
  <j-modal
    :title="title"
    :width="width"
    :visible="visible"
    :confirmLoading="confirmLoading"
    switchFullscreen
    @ok="handleOk"
    @cancel="handleCancel"
    cancelText="关闭">
    <a-spin :spinning="confirmLoading">
      <a-form-model ref="form" :model="model" :rules="validatorRules">
        <a-form-model-item label="上级网格" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="pid">
          <j-tree-select
            ref="treeSelect"
            placeholder="请选择上级网格"
            v-model="model.pid"
            dict="gridding_information,grid_name,id"
            pidField="pid"
            pidValue="0"
            hasChildField="has_child"
            >
          </j-tree-select>
        </a-form-model-item>
        <a-form-model-item label="网格名称" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="gridName">
          <a-input v-model="model.gridName" placeholder="请输入网格名称" ></a-input>
        </a-form-model-item>
        <a-form-model-item label="网格级别" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="gridLevel">
          <j-dict-select-tag type="list" v-model="model.gridLevel"  dictCode="grid_level" placeholder="请选择网格级别" />
        </a-form-model-item>
        <a-form-model-item label="网格描述" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="gridDesc">
          <a-input v-model="model.gridDesc" placeholder="请输入网格描述" ></a-input>
        </a-form-model-item>
        <a-form-model-item label="中心点经度" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="longitude">
          <j-category-select v-model="model.longitude" pcode="B01" placeholder="请选择中心点经度"  />
        </a-form-model-item>
        <a-form-model-item label="中心点纬度" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="latitude">
          <a-input v-model="model.latitude" placeholder="请输入中心点纬度" ></a-input>
        </a-form-model-item>
        <a-form-model-item label="边界经纬度" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="llBorder">
          <a-textarea v-model="model.llBorder" rows="4" placeholder="请输入边界经纬度" />
        </a-form-model-item>
        <a-form-model-item label="有效性状态" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="statusValid">
          <j-dict-select-tag type="list" v-model="model.statusValid"  dictCode="valid_status" placeholder="请选择有效性状态" />
        </a-form-model-item>
        
      </a-form-model>
    </a-spin>
  </j-modal>
</template>

<script>

  import { httpAction } from '@/api/manage'
  import { validateDuplicateValue } from '@/utils/util'
  export default {
    name: "GriddingInformationModal",
    components: { 
    },
    data () {
      return {
        title:"操作",
        width:800,
        visible: false,
        model:{
         },
        labelCol: {
          xs: { span: 24 },
          sm: { span: 5 },
        },
        wrapperCol: {
          xs: { span: 24 },
          sm: { span: 16 },
        },

        confirmLoading: false,
        validatorRules: {
           pid: [
              { required: true, message: '请输入上级网格!'},
           ],
           gridName: [
              { required: true, message: '请输入网格名称!'},
           ],
           gridLevel: [
              { required: true, message: '请输入网格级别!'},
           ],
           longitude: [
              { required: true, message: '请输入中心点经度!'},
           ],
           latitude: [
              { required: true, message: '请输入中心点纬度!'},
           ],
           llBorder: [
              { required: true, message: '请输入边界经纬度!'},
           ],
           statusValid: [
              { required: true, message: '请输入有效性状态!'},
           ],
        },
        url: {
          add: "/grid/griddingInformation/add",
          edit: "/grid/griddingInformation/edit",
        },
        expandedRowKeys:[],
        pidField:"pid"
     
      }
    },
    created () {
       //备份model原始值
       this.modelDefault = JSON.parse(JSON.stringify(this.model));
    },
    methods: {
      add (obj) {
        this.modelDefault.pid=''
        this.edit(Object.assign(this.modelDefault , obj));
      },
      edit (record) {
        this.model = Object.assign({}, record);
        this.visible = true;
      },
      close () {
        this.$emit('close');
        this.visible = false;
        this.$refs.form.clearValidate()
      },
      handleOk () {
        const that = this;
        // 触发表单验证
       this.$refs.form.validate(valid => {
          if (valid) {
            that.confirmLoading = true;
            let httpurl = '';
            let method = '';
            if(!this.model.id){
              httpurl+=this.url.add;
              method = 'post';
            }else{
              httpurl+=this.url.edit;
               method = 'put';
            }
             if(this.model.id && this.model.id === this.model[this.pidField]){
              that.$message.warning("父级节点不能选择自己");
              that.confirmLoading = false;
              return;
            }
            httpAction(httpurl,this.model,method).then((res)=>{
              if(res.success){
                that.$message.success(res.message);
                this.$emit('ok');
              }else{
                that.$message.warning(res.message);
              }
            }).finally(() => {
              that.confirmLoading = false;
              that.close();
            })
          }else{
             return false
          }
        })
      },
      handleCancel () {
        this.close()
      },
      handleCategoryChange(value,backObj){
        this.model = Object.assign(this.model, backObj);
       },
      submitSuccess(formData,flag){
        if(!formData.id){
          let treeData = this.$refs.treeSelect.getCurrTreeData()
          this.expandedRowKeys=[]
          this.getExpandKeysByPid(formData[this.pidField],treeData,treeData)
          this.$emit('ok',formData,this.expandedRowKeys.reverse());
        }else{
          this.$emit('ok',formData,flag);
        }
      },
      getExpandKeysByPid(pid,arr,all){
        if(pid && arr && arr.length>0){
          for(let i=0;i<arr.length;i++){
            if(arr[i].key==pid){
              this.expandedRowKeys.push(arr[i].key)
              this.getExpandKeysByPid(arr[i]['parentId'],all,all)
            }else{
              this.getExpandKeysByPid(pid,arr[i].children,all)
            }
          }
        }
      }
      
      
    }
  }
</script>
------------------------------

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
