### ISSUE TITLE
Mapper中用了多表连接，但代理时只查询主表，导致查询page总数时报错

### ISSUE THREAD

**Issue by Rewivy** [jeecgboot/jeecg-boot#3671]
##### 截图&代码：
出错sql：
![企业微信截图_16518002311421](https://user-images.githubusercontent.com/48473052/167062656-bba34ad3-0c7f-4e40-b40c-ae0e559f609b.png)

出错调用语句：
![image](https://user-images.githubusercontent.com/48473052/167062873-b22fd2dc-24c8-4509-8e1d-83bfdd1ec083.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
代理是什么意思?

**Comment by Rewivy** [comment]
> 

就是出错的sql是程序运行到出错调用语句后自动执行的，不是我们写的

**Comment by zhangdaiscott** [comment]
你发这样的issue，让我们猜吗？把你写的sql和用法都详细的贴出来

**Comment by Rewivy** [comment]
这是一个查询用户信息的sql语句，我的mapper语句如下，可以正常运行：
       <select id="queryCandidateList" parameterType="org.jeecg.modules.mis.dto.HrmCandidateDto"
            resultType="org.jeecg.modules.mis.dto.HrmCandidateDto">
        SELECT
        `t1`.`id` AS `candidate_id`,
        `t7`.`id` AS `application_id`,
        `t1`.`candidate_name` AS `candidate_name`,
        `t1`.`recruit_channel` AS `recruit_channel`,
        `t1`.`sex` AS `sex`,
        `t1`.`education` AS `education`,
        `t1`.`school` AS `school`,
        `t1`.`major` AS `profession`,
        `t1`.`latest_work_name` AS `latest_work_name`,
        `t1`.`latest_job` AS `latest_job`,
        `t1`.`create_by` AS `create_by`,
        `t7`.`create_time` AS `create_time`,
        `t7`.`candidate_status` AS `candidate_status`,
        -- `t2`.`position_id` AS `position_id`,
        `t3`.`age` AS `age`,
        `t3`.`work_year` AS `work_year`,
        `t4`.`mobile` AS `mobile`,
        `t4`.`email` AS `email`,
        `t5`.`department` AS `department`,
        `t6`.`tag` AS `tag`,
        `t7`.`company_id` as `company_id`,
        `t7`.`position_id` as `position_id`,
        `t11`.`position_type` as `position_type`,
        `t7`.`referral_id` as `referral_id` ,
        `t7`.`referral_dep` as `referral_dep`,
        `t7`.`stop_reason` as `stop_reason`,
        `t7`.`stop_remark` as `stop_remark`,
        `t7`.`rotate` as `rotate`,
        `t7`.`method` as `method`,
        `t7`.`address` as `address`,
        `t7`.`interviewer` as `interviewer` ,
        `t7`.`interview_time` as `interview_time`,
        `t7`.`contact_person` as `contact_person`,
        `t7`.`contact_phone` as `contact_phone`,
        `t7`.`is_send` as `is_send`,
        `t7`.`is_fill` as `is_fill`,
        `t7`.`project_id` as `project_id`,
        `t8`.`expected_salary` as `expected_salary`,
        `t9`.company `offerCompany`,
        `t9`.department `offerDep`,
        `t10`.realname `referral_name`,
        `t10`.phone `referral_mobile`
        FROM `hrm_application` `t7`
        LEFT JOIN `hrm_candidate` `t1` on `t1`.`id` = `t7`.`candidate_id` and t1.id is not null and t1.delete_time is
        null
        LEFT JOIN `mis_recruitment_job` `t11` ON `t11`.`id` = `t7`.`position_id`
        -- LEFT JOIN `hrm_candidate_record` `t2` ON `t1`.`id` = `t2`.`candidate_id`
        LEFT JOIN `hrm_candidate_personal` `t3` ON `t1`.`id` = `t3`.`candidate_id` and t3.delete_time is null
        LEFT JOIN `hrm_candidate_contact` `t4` ON `t1`.`id` = `t4`.`candidate_id` and t4.delete_time is null
        LEFT JOIN `hrm_enrollment` `t5` ON `t1`.`id` = `t5`.`candidate_id` and t5.delete_time is null
        LEFT JOIN (
        select candidate_id,tag from `hrm_candidate_tag` tag1
        where delete_time is null and id=(select max(id) from hrm_candidate_tag tag2 where
        tag2.candidate_id=tag1.candidate_id
        
        
        
        <if test="params.tags!=null and params.tags!='' ">
            and tag in
            <foreach collection="params.tags" item="item" open="(" close=")" separator=",">
                #{item}
            </foreach>
        </if>
        )
        order by candidate_id desc
        ) `t6` ON `t1`.`id` = `t6`.`candidate_id`
        LEFT JOIN `hrm_candidate_jobintention` `t8` on `t1`.`id` = `t8`.`candidate_id` and t8.delete_time is null
        LEFT JOIN (select * from `hrm_candidate_offer` order by create_time desc limit 1)`t9` on `t1`.`id` =
        `t9`.`candidate_id` and t9.delete_time is null
        LEFT JOIN `sys_user` `t10` on `t7`.referral_id = `t10`.id
        <where>
            t7.delete_time is null
            <if test="params.projectIds != null and params.projectIds != ''">
                and t7.project_id in
                <foreach collection="params.projectIds" item="item" open="(" close=")" separator=",">
                    #{item}
                </foreach>
            </if>
            <choose>
                <when test="params.superQueryCondition != null and params.superQueryCondition != ''">
                    ${params.superQueryCondition}
                </when>
                <otherwise>

                </otherwise>
            </choose>
        </where>
    </select>
我的参数传了IPage，报错的是Page查询总数的代码

**Comment by Rewivy** [comment]
报错的原因就是因为Ipage的总数查询只查询了我的主表t7，没有把我连接的表t4带上

**Comment by Rewivy** [comment]
已找到解决方案，可关闭issue。
解决方案：
 page.setSearchCount(false);
在Mapper中重新定义查询总数的方法，并将所得查询结果赋值为page的total参数
