### ISSUE TITLE
下拉联动组件

### ISSUE THREAD

**Issue by shiyongcui** [jeecgboot/jeecg-boot#3673]
##### 截图&代码：
online表单开发中功能测试没问题
![image](https://user-images.githubusercontent.com/55284347/167076548-c8e72db5-f647-4916-abdb-9753e05f359d.png)
![image](https://user-images.githubusercontent.com/55284347/167076556-b98ea8be-49a6-474b-9f4e-a11f987bfb7a.png)
生成后的代码
![image](https://user-images.githubusercontent.com/55284347/167076607-558ca73c-3574-4d45-ad48-20e5f868ed87.png)
![image](https://user-images.githubusercontent.com/55284347/167076641-cf247141-8668-4412-9044-2de5022de9c4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持生成
