### ISSUE TITLE
单体切换微服务未能成功

### ISSUE THREAD

**Issue by deshengchen** [jeecgboot/jeecg-boot#3677]
##### 版本号：
3.2.0

##### 问题描述：
下载最新版本项目，按照http://doc.jeecg.com/2704725 步骤切换微服务，启动nacos失败。

##### 截图&代码：
![1651908921(1)](https://user-images.githubusercontent.com/25933384/167244102-ca4ab902-8fba-4c67-96c2-6397992f941a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
nacos的数据库配置了吗

**Comment by deshengchen** [comment]
作者你好，我的情况是
1、本地没有安装nacos
2、配置host（未配置）
3、勾选中Maven Profile SpringCloud（已配置）
4、创建微服务的数据库jeecg-boot、nacos、xxl_job（已操作）
5、jeecg-cloud-module\jeecg-cloud-nacos项目数据库连接（已配置）
6、启动nacos项目jeecg-cloud-module\jeecg-cloud-nacos（失败报上图错误）

另：单体应用启动类一直有个报错，但是后台可以运行，这个需要修复吗？
![image](https://user-images.githubusercontent.com/25933384/167246322-881c6672-2764-4294-87af-fa9e2033571f.png)

**Comment by zhangdaiscott** [comment]
host不配置，你是怎么想的

**Comment by deshengchen** [comment]
叨扰作者了，我是初学jeecg。
host应该是指etc下的hosts文件吧？
按照指点，我已在hosts文件增加相关配置
![1651913233(1)](https://user-images.githubusercontent.com/25933384/167246790-aaf42e0c-d03d-470a-8d4a-03aac46a9b47.png)
运行后还是报错，但是提示的类发生变化了，不知还有哪里出了问题
![1651913454(1)](https://user-images.githubusercontent.com/25933384/167246930-62399554-bc2d-465b-aea5-ea1c75415147.png)

**Comment by deshengchen** [comment]
多谢作者，已成功
