### ISSUE TITLE
Method code too large!  

### ISSUE THREAD

**Issue by ych6666** [jeecgboot/jeecg-boot#3678]
##### 版本号：
1.4.0

##### 问题描述：
查询内容多会出现Method code too large!

##### 截图&代码：

![image](https://user-images.githubusercontent.com/89495170/167246608-1c7a8d9d-52f4-4f84-83f3-12462d4048ec.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
去积木报表那边发

**Comment by ych6666** [comment]
好的

**Comment by ych6666** [comment]
> 去积木报表那边发

好的
