### ISSUE TITLE
JEditableTable,当 type=popup , multi为false时,单选某一行 radio不能选中

### ISSUE THREAD

**Issue by laoyam** [jeecgboot/jeecg-boot#3679]
##### 问题描述：
JEditableTable,当 type=popup , multi为false时,单选某一行 radio不能选中

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26473455/167278094-a9004c80-579f-4625-ac46-140d2de15970.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
提供代码示例

**Comment by zhangdaiscott** [comment]
sq

**Comment by 1298191366** [comment]
经测试，未复现，你是说的是JEditableTable，columns里面设置的popup 吗
![popup](https://user-images.githubusercontent.com/30997828/170962287-8cc663cb-415e-4974-b84e-0c8763514be7.gif)

**Comment by 1298191366** [comment]
经测试，未复现，你是说的JEditableTable中的columns中设置popup吗，还有我们这没有刷新按钮，你是不是改代码了
![popup](https://user-images.githubusercontent.com/30997828/170963197-2142d882-48ce-4b73-953e-8b193802bcd4.gif)
