### ISSUE TITLE
jeecg.com首页的介绍文案，数字编号有重复

### ISSUE THREAD

**Issue by haikeyiguo** [jeecgboot/jeecg-boot#3680]
##### 版本号：
无

##### 问题描述：
jeecg.com首页的 “为什么选择Jeecg-Boot？” 这部分介绍，每一条都有数字编号。其中，27号重复了（截至2022年5月8日）。

##### 截图&代码：
![微信图片_20220508132950](https://user-images.githubusercontent.com/65058023/167283230-bad26767-c015-4c00-8559-ed8dfce0c854.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
3q
