### ISSUE TITLE
使用页面Online表单开发，导入数据库表示报错

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3683]
##### 版本号：
2.4.6

##### 问题描述：
点解 导入数据库 报错  Caused by: java.lang.NoSuchMethodError: 'java.util.List org.jeecgframework.codegenerate.database.DbReadTableUtil.readAllTableNames()'

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44563730/167331027-421f2d06-66a6-4dbe-8669-02fe5d9d5331.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你是不是手工升级的，不兼容

**Comment by yzmking** [comment]
ok，已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 中午11:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 使用页面Online表单开发，导入数据库表示报错 (Issue #3683)





 
你是不是手工升级的，不兼容
