### ISSUE TITLE
online表单开发生成树形表单代码找不到类

### ISSUE THREAD

**Issue by Durant-Wen** [jeecgboot/jeecg-boot#3684]
##### 截图&代码：
![1](https://user-images.githubusercontent.com/46209098/167352070-2f0c3243-60b1-4cc9-b4fd-6f101df01a3d.png)
![2](https://user-images.githubusercontent.com/46209098/167352069-3e29c013-1068-4265-8899-3ee824fdad75.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新最新的模板

**Comment by Durant-Wen** [comment]
> 



> 更新最新的模板

请问在哪更新呢？

**Comment by Durant-Wen** [comment]
> 

@zhangdaiscott 老师您好，请问在哪里更新最新的模板呢？
