### ISSUE TITLE
登录的失效时长，我想设置长一点，没有找到更改的地方

### ISSUE THREAD

**Issue by chenzijie1991** [jeecgboot/jeecg-boot#3690]
##### 问题描述：
登录的失效时长，现在用的是默认时间，大概是30分钟，我想设置长一些，比如12小时，24小时这种，或者让登录一直不失效也可以，没有找到更改的地方。

##### 截图&代码：
我在yml文件中添加了下面的代码 但是没好使

  servlet:
    session:
      timeout: 36000s

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
常见问题有这个问题：http://jeecg.com/doc/qa
