### ISSUE TITLE
v-has使用问题

### ISSUE THREAD

**Issue by mynameiswxl** [jeecgboot/jeecg-boot#3691]
##### 问题描述：
根据在线文档：页面按钮权限用法，button中增加了v-has，在后台管理中增加了相应的按钮权限进行了角色授权。
但是再前端页面中按钮权限控制未生效，请教下v-has再前端项目中如何具体使用？有无demo示例？

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/55384839/167817717-ca376402-7c84-40a4-8905-98306943ab48.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044041
