### ISSUE TITLE
online表单开发，强制同步后索引丢失

### ISSUE THREAD

**Issue by sunbeams001** [jeecgboot/jeecg-boot#3693]
##### 版本号：
3.1.0

##### 问题描述：
online表单开发，强制同步后索引丢失

##### 截图&代码：
复现流程（过于简单就不上图了）：
1. 新建测试表，字段name，sex，name加索引，同步数据库，此时有name索引
2. 新建sex索引，强制同步数据库，此时只剩sex索引，name索引丢失
3. 新建字段info，不加索引，强制同步数据库，此时索引为空

推测是强制同步数据库的逻辑中，只处理了本次编辑新增的索引，如果本次编辑无新增则直接不创建任何索引

**Comment by zhangdaiscott** [comment]
下个版本发布
