### ISSUE TITLE
使用ISysBaseAPI.getDeptUserByOrgCode(String orgCode)获取到都系顶级部门的下级部门

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3696]
##### 版本号：
2.4.6

##### 问题描述：
使用ISysBaseAPI.getDeptUserByOrgCode(String orgCode)获取到都系顶级部门的下级部门
以下的一段代码，写死了截止前三位的部门代码

##### 截图&代码：
![1652324731(1)](https://user-images.githubusercontent.com/44563730/167984087-537c9b9f-71c5-401b-a41d-7174ce58fcf9.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
?

**Comment by yzmking** [comment]
部门结构为  总部->财务部->会计   用户是财务部的，使用这个接口查询的时候，原来应该返回会计部门的，结果是返回财务部

**Comment by zhangdaiscott** [comment]
sq

**Comment by 1298191366** [comment]
`YouBianCodeUtil.ZHANWEI_LENGTH`是自己自动配置的，默认是三位，目前的规则就是这样的，他是直接取最顶级部门，然后将第二级部门查询出来，未复现你说的问题，你是不是改了部门编码，导致和配置的不一致
数据库中的树据
![image](https://user-images.githubusercontent.com/30997828/171087958-a30aa2d6-0447-4fd1-b72a-d49c8b91ba55.png)

请求数据
![image](https://user-images.githubusercontent.com/30997828/171088184-f98743fe-6171-4b24-850e-363b10bf69d1.png)

**Comment by yzmking** [comment]
好的

**Comment by yzmking** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月31日(星期二) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 使用ISysBaseAPI.getDeptUserByOrgCode(String orgCode)获取到都系顶级部门的下级部门 (Issue #3696)





 
YouBianCodeUtil.ZHANWEI_LENGTH是自己自动配置的，默认是三位，目前的规则就是这样的，他是直接取最顶级部门，然后将第二级部门查询出来，未复现你说的问题，你是不是改了部门编码，导致和配置的不一致
 数据库中的树据
 
 
请求数据
