### ISSUE TITLE
分包打包部署后调用的profile是“default”

### ISSUE THREAD

**Issue by yanchenchen** [jeecgboot/jeecg-boot#3698]
##### 版本号：

3.2
##### 问题描述：
分包打包部署后调用的profile是“default”，怎么设置成“prod”

##### 截图&代码：
![image](https://user-images.githubusercontent.com/8335270/167992059-ba7b8549-facb-4b29-bbe4-4ede447f73ef.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
打包的时候勾上需要的
![image](https://user-images.githubusercontent.com/3162115/168106520-7ba70124-6342-4db4-b27c-d99d0572e328.png)

**Comment by yanchenchen** [comment]
已经勾选了，但是还是会出现这个问题。
