### ISSUE TITLE
10万条数据的表做字典Table，在线开发很卡怎么处理？

### ISSUE THREAD

**Issue by Rewivy** [jeecgboot/jeecg-boot#3699]
##### 问题描述：10万条数据的表做字典Table，在线开发很卡怎么处理？
/online/cgform/api/getColumns接口返回的dictOptions中会把10万条数据包含进去，导致接口响应时间久，页面显示卡顿

##### 截图&代码：
![WXWorkCapture_1652411374845](https://user-images.githubusercontent.com/48473052/168204533-746f4463-6da2-4d34-b300-ef278add4767.png)

![WXWorkCapture_16524114131674](https://user-images.githubusercontent.com/48473052/168204542-2e6d245c-ee93-4bd8-8193-8aaea5cff8b8.png)

![WXWorkCapture_16524116733102](https://user-images.githubusercontent.com/48473052/168204553-5a00266c-6be8-4869-81a7-c0e3fac73361.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
换成下拉搜索组件

**Comment by xu-my** [comment]
他这个10万条数据，使用下拉搜索组件 支持 汉字首字母查询嘛？

**Comment by BruceOuyang** [comment]
> 他这个10万条数据，使用下拉搜索组件 支持 汉字首字母查询嘛？

@xu-my 可以加个字段存拼音，可以搜一下 to_pinyin 数据库函数脚本，创建好 to_pinyin函数后就简单了呀
```
update biz_table set biz_filed_pinyin = to_pinyin(biz_filed)
```
