### ISSUE TITLE
sql脚本中字符集编码错误，uft8应为utf8mb4

### ISSUE THREAD

**Issue by dusthunter** [jeecgboot/jeecg-boot#3703]
##### 版本号：
1.1.0-beta

##### 问题描述：
jeecg-boot/db/jeecgboot-mysql-5.7.sql 中字符集编码uft8应为utf8mb4，排序utf8_general_ci 应为utf8mb4_general_ci 。

##### 截图&代码：

DROP TABLE IF EXISTS `demo`;
CREATE TABLE `demo`  (
  `id` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '主键ID',
  `name` varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '姓名',
  `key_word` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '关键词',
......

#### 修改建议：
相关脚本通过查找替换，将字符集编码‘ uft8 ’替换为‘ utf8mb4 ’，排序‘ utf8_general_ci ’ 替换为‘ utf8mb4_general_ci ’ 。

**Comment by zhangdaiscott** [comment]
自己手工调整吧
