### ISSUE TITLE
JTreeSelect树形下拉框(异步加载) 自定义查询条件 查询结果问题

### ISSUE THREAD

**Issue by Nguyendream** [jeecgboot/jeecg-boot#3709]
##### 版本号：
3.1.0

##### 问题描述：
JTreeSelect树形下拉框 自定义查询条件 查询结果没有异步，没有树状结构了

查询自定义树表，JTreeSelect参数`condition='{"del_flag":"0"}'`，意在过滤逻辑删除的数据。 [参考文档](http://doc.jeecg.com/2044006)

根据xml代码，查询条件为`where 1 = 1 and del_flag LIKE 0`，未达到预期效果

看提交是版本3.1.0修改的，是为了哪部分考虑？

##### 截图&代码：
https://github.com/jeecgboot/jeecg-boot/blob/2e90f73da26992cf1bb8cc4e699d780c45a3c1b2/jeecg-boot/jeecg-boot-module-system/src/main/java/org/jeecg/modules/system/mapper/xml/SysDictMapper.xml#L138-L153

**Comment by zhangdaiscott** [comment]
ws

**Comment by sjlei** [comment]
问题已修复，下版本发布
