### ISSUE TITLE
that.triggleChangeValues(values,id,targrt) 不能修改 附表的下拉框

### ISSUE THREAD

**Issue by beidouchain005outlook** [jeecgboot/jeecg-boot#3710]
##### 版本号：
ant-design-vue-jeecg      3.1.0

##### 问题描述：
js增强：主表A，附表A1   在A中配置JS增强，目的是A1中实现多级联动。用triggleChangeValues可以修改文本框没问题，但是修改下拉框修改不了，调查后发现只是修改了下拉框中显示值，选项值并未修改。

that.triggleChangeValues(values,id,targrt) 不能修改 附表的下拉框

有什么其他的方法吗？
万分感谢
##### 截图&代码：
![image](https://user-images.githubusercontent.com/40236472/168784534-baffe062-d269-4e06-a5cc-f841a5398e6a.png)
![image](https://user-images.githubusercontent.com/40236472/168784725-67c17310-8c4a-4c0a-be93-86c606fe5757.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
`triggleChangeValues` 这个方法是用来修改组件的值的，动态修改附表下拉框的options这个功能还不支持。
