### ISSUE TITLE
菜单栏由于设置了权限按钮而无法显示并无法恢复

### ISSUE THREAD

**Issue by JennyMomomo** [jeecgboot/jeecg-boot#3714]
##### 版本号：
VUE3

##### 问题描述：
在菜单栏设置了按钮权限，勾选可见可访问和有效，然后重新登录（账号本来已授权可见该菜单），我的菜单就不见了，不知要从哪里找回来

##### 截图&代码：
![26%%~LV{LYLEM9 B$70%345](https://user-images.githubusercontent.com/103089370/168969655-0d4ca082-f4f7-45a0-b3d9-302e60402376.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
改数据库
