### ISSUE TITLE
erp风格生成代码有错误

### ISSUE THREAD

**Issue by 171444135** [jeecgboot/jeecg-boot#3715]
##### 问题描述：
erp风格测试正常，生成vue代码有bug

##### 截图&代码：

![c365ffedfdd2986336fcc6642db3558](https://user-images.githubusercontent.com/58811727/168984181-2bc36890-c6bd-4781-90a5-ac14d0b713f7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 171444135** [comment]
其他风格导出的代码正常使用，但是erp导出的代码就有问题

**Comment by zhangdaiscott** [comment]
更新代码
