### ISSUE TITLE
sql参数无法获悉,导致预览报表数据无法展示

### ISSUE THREAD

**Issue by zz-2684** [jeecgboot/jeecg-boot#3716]
##### 版本号：
1.5.0-beta

##### 问题描述：
springboot集成之后制作报表无法给sql语句进行传参,预览sql有数据,但是预览报表的时候没有数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/73687071/168996026-3f12d3b0-03cb-4e8c-8812-7f01eb4d25a3.png)
![image](https://user-images.githubusercontent.com/73687071/168996186-3ecdb07b-51f1-4abc-bf8f-31581f08474f.png)
![image](https://user-images.githubusercontent.com/73687071/168996291-f17ffed5-72f9-43b3-85f1-1cceb164aec6.png)
![image](https://user-images.githubusercontent.com/73687071/168996409-eb3006ae-7717-41d6-8ca3-02b24e744813.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
你是否填写了默认值，预览报表的时候是否有传参，可以根据查询来做处理，如还有问题，请在次回复
查询文档：http://report.jeecg.com/2373403

**Comment by zz-2684** [comment]
我sql有写参数，查询数据也显示有数据，但是放到表格里面就不行了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月30日 10:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] sql参数无法获悉,导致预览报表数据无法展示 (Issue #3716) |

你是否填写了默认值，预览报表的时候是否有传参，可以根据查询来做处理，如还有问题，请在次回复
查询文档：http://report.jeecg.com/2373403

**Comment by 1298191366** [comment]
我测着是没有问题的，我不知道你是如何设计的，你这设计页面都打着马赛克，有可能你设计页面设计的不对
参数
![image](https://user-images.githubusercontent.com/30997828/170938776-fd871e09-8662-4fda-88fb-785f56ba4660.png)
数据预览
![image](https://user-images.githubusercontent.com/30997828/170939805-6cd42496-69c3-46d1-a857-61199ba1e9d7.png)

预览页面
![image](https://user-images.githubusercontent.com/30997828/170938940-6502bc4f-552e-4b2f-b6f3-20b0fab1b2e0.png)
