### ISSUE TITLE
微服务以单机模式启动了

### ISSUE THREAD

**Issue by hdtopku** [jeecgboot/jeecg-boot#3717]
##### 版本号：
当前最新版本： 3.2.0

##### 问题描述：
更新了今天的代码，发现微服务以单机模式启动了
![image](https://user-images.githubusercontent.com/14859466/169025776-3e7af29b-72b9-45a7-8f2a-1be525297a70.png)

##### 截图&代码：
![image](https://user-images.githubusercontent.com/14859466/169025498-a4ac5298-10b5-460a-80f4-36fe2a7ed7ba.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
system重现编译下

**Comment by hdtopku** [comment]
> system重现编译下

不好使，重新clean，编译了。reset 到版本，又好使了。
此外，今天的代码虽然能连上gateway，但确是8080端口，用9999端口访问不到system服务

![image](https://user-images.githubusercontent.com/14859466/169028061-abf8cfe0-353b-4739-9f65-b75c13d24c69.png)


![image](https://user-images.githubusercontent.com/14859466/169027913-96fc4810-4b67-446e-949b-c7e3b141aaa7.png)

**Comment by zhangdaiscott** [comment]
我们特意改了，测试过没问题
