### ISSUE TITLE
版本升级集成Swagger路径匹配问题导致空指针异常 

### ISSUE THREAD

**Issue by ishuibo** [jeecgboot/jeecg-boot#3720]
版本号：3.2.0

问题描述：3.0升级3.2.0，应用启动的时候报错，Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException，报错原因为集成Swagger时因为Springfox 使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher,所以导致空指针异常，遂尝试手工配置第一种方案
`spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher`
不论是配置在bootstrap.yml还是Nacos配置中心均不起作用，此方案失败！

第二种方案通过降低Spring Boot 版本来解决问题，但因3.2.0版本要求Spring Boot版本最低为2.6.x，此方案失败！

第三种配置@EnableWebMvc注解，经实践也失败了！

截图&代码：
![1](https://user-images.githubusercontent.com/33535844/169284998-fd3cc877-4885-4fd6-859f-7697286146b3.png)

友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；

  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
说明你没升好，仔细对比，或者百度错误把

**Comment by ishuibo** [comment]
百度的所有方案都看了，都适用不了，对比配置了`spring: mvc: pathmatch: matching-strategy: ant_path_matcher`依旧不起作用。

**Comment by ishuibo** [comment]
目前没啥方向了，还望能指点迷津
