### ISSUE TITLE
如何实现nacos集群

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3722]
##### 截图&代码：   
![image](https://user-images.githubusercontent.com/50698315/169431709-cf0250c5-03c8-4e57-aa0b-2f1552c3baa1.png)
![image](https://user-images.githubusercontent.com/50698315/169433100-fed5fd14-d8cf-497d-b1e5-b8ff7bf8facb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个请自己百度解决

**Comment by yangkui001** [comment]
你好，因为jeecg 封装了nacos，我们使用的架构也是jeecgboot.2.4.6,百度没找到办法解决，所以才来提问官方是如何解决的
