### ISSUE TITLE
通过Gateway访问后端System模块接口报错404

### ISSUE THREAD

**Issue by zjw443124419** [jeecgboot/jeecg-boot#3725]
##### 版本号：
3.1.0

##### 问题描述：
Gateway端口 9999 地址：http://localhost:9999/sys/randomImage/1653116136961?_t=1653116136
System端口 7001 地址  http://localhost:7001/sys/randomImage/1653116136961?_t=1653116136
服务都成功注册到了Nacos,但是通过Gateway访问后端System接口404，后台控制台无报错信息；不通过Gateway，直接访问后端System接口可以正常访问；

##### 截图&代码：
![image](https://user-images.githubusercontent.com/98029284/169639408-8948d8e5-09c9-4bfe-9ac4-03dabf5896d9.png)
![image](https://user-images.githubusercontent.com/98029284/169640725-2c511ec8-5241-4ff7-a0c1-c9bbc8c99cd1.png)
![image](https://user-images.githubusercontent.com/98029284/169640873-27cbcc94-64a5-471b-8e81-c5c47cacd087.png)
![image](https://user-images.githubusercontent.com/98029284/169640924-a8720d3e-23eb-41ab-808c-4b7b571f9b36.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己排查

**Comment by 313988838** [comment]
麻烦问下这个问题你怎么处理的呀。解决了吗？我们现场会出现这种。而且不定期@
