### ISSUE TITLE
3.2.0 微服务 sysytem模块启动报错

### ISSUE THREAD

**Issue by jiangxiaozheng** [jeecgboot/jeecg-boot#3726]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/54165898/169648916-6d6cae37-b40f-4b20-bca7-5288eed685b1.png)

![image](https://user-images.githubusercontent.com/54165898/169648947-5a98a666-d704-49cd-aa2d-a1c73e4f35a8.png)
![image](https://user-images.githubusercontent.com/54165898/169648996-172075c5-e459-470b-8ee2-386433ad67c7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
安装文档操作
