### ISSUE TITLE
系统提示！很抱歉，资源未找到!

### ISSUE THREAD

**Issue by xu-my** [jeecgboot/jeecg-boot#3728]
##### 问题描述： 新建不以 org.jeecg  开头的包路径 产生 资源获取失败。

数据库xml文件已经注册成功。online在线测试也没问题，生产代码配置菜单后就出现了这样的问题。

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/96990578/169692251-a3db9125-cc53-49b5-b65a-486e4b16e2e9.png)
![图片](https://user-images.githubusercontent.com/96990578/169692271-9b725622-4e37-4400-92a2-f1e6e3c1d274.png)

**Comment by xu-my** [comment]
文件解决了，启动扫描没有配！

**Comment by yuanfei726** [comment]
你好，请问除了菜单授权，application.yml以及MybatisPlusSaasConfig修改,还有那个地方要修改啊？启动中配置扫描路径是指那个类？
![image](https://user-images.githubusercontent.com/78579012/218665341-ad3e1256-1a67-4006-8da4-aa7d5c289a8a.png)
![image](https://user-images.githubusercontent.com/78579012/218665521-b8d398e2-6093-45b1-8091-902fd146defd.png)
