### ISSUE TITLE
微服务模式下nacos使用自定义namespace时，访问gateway中的swagger文档首页页面空白

### ISSUE THREAD

**Issue by climpeaker** [jeecgboot/jeecg-boot#3729]
##### 版本号：
3.2.0

##### 问题描述：
微服务模式下nacos使用自定义namespace时，访问gateway中的swagger文档首页页面空白

##### 截图&代码：
项目根目录 pom 设置nacos的namespace为 jeecg，如图：
![zidingyi](https://user-images.githubusercontent.com/10292915/169762191-feb1221b-5193-4879-ac5e-58f7b2ba330c.png)

gateway浏览器访问时，页面空白，如图：

![kongbai](https://user-images.githubusercontent.com/10292915/169762244-31e3de15-9f5c-40dd-b84c-722c5e9413c3.png)

造成原因，为swagger加载方法处理时，只是用了 nacos的 地址，没有使用namespace参数：

![yuanyin](https://user-images.githubusercontent.com/10292915/169762243-d89057b5-f964-4ff0-a00c-6a47460badb5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by climpeaker** [comment]
同样的问题，在监控中心组件也存在。

**Comment by climpeaker** [comment]
如果我的nacos中自定义命名空间为 jeecg ，那么这里将如何配置才可以保证程序正常使用？
![07](https://user-images.githubusercontent.com/10292915/169851700-7da2189c-9edc-4be1-aeaa-4b3d3f979b4c.png)

**Comment by climpeaker** [comment]
> ![image](https://user-images.githubusercontent.com/3162115/169766842-cc692932-5b76-45e8-a32e-cbc0b855e7a7.png)

![07](https://user-images.githubusercontent.com/10292915/169851750-6445c529-7f1e-4cb6-bec0-901caf0d0716.png)
如果我的nacos中自定义命名空间为 jeecg ，那么这里将如何配置才可以保证程序正常使用？

**Comment by zhangdaiscott** [comment]
不看给你的截图吗
