### ISSUE TITLE
微服务版本中这个quartz启动不起来

### ISSUE THREAD

**Issue by yzy-1995** [jeecgboot/jeecg-boot#3730]
版本号：
3.2.0

问题描述：
微服务版本中这个quartz启动不起来

截图&代码：
![image](https://user-images.githubusercontent.com/24284910/169871371-0d182ede-94e3-41ab-99c1-a473cbb7cfcb.png)

**Comment by zhangdaiscott** [comment]
微服务走的是nacos，跟这个配置文件有什么关系
