### ISSUE TITLE
被封装的nacos如何实现集群

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3731]
##### 问题描述：由于jeecg封装了nacos，如果修改JeecgNacosApplication中的standalone=“flase”
启动就会报错，百度也没找到解决办法，有没好的解决方案，急等！！！！！！！！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/169929312-57f15f10-1dac-40d5-bb23-1d12170046ab.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
nacos不是必须使用我们的，我们也是用官方的代码编译成的，集群跟我们打包也没什么关系。
实在弄不明白，你可以直接用官方的版本，用jeecgboot库
