### ISSUE TITLE
Autopoi字段Type文档与实际代码控制不一致

### ISSUE THREAD

**Issue by OrangutanLv** [jeecgboot/jeecg-boot#3732]
##### 截图&代码：
文档中描述 type = 10代表数字， org.jeecgframework.poi.excel.export.base.ExcelExportBase 中通过type = 4 判断数值
![image](https://user-images.githubusercontent.com/15025349/169929863-d3a6cd13-45e6-4e52-9658-b4c33173046c.png)
 
![image](https://user-images.githubusercontent.com/15025349/169930005-b4c0eccf-29a4-492a-ae18-8cf9e6d6ab71.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by OrangutanLv** [comment]
您好，我已收到您的邮件。我会尽快给您回复。谢谢！

**Comment by lsqGitHub716** [comment]
文档已修改。谢谢！
