### ISSUE TITLE
2022年5月23日，sql、java、js增强都不能保存了

### ISSUE THREAD

**Issue by gaobeijia** [jeecgboot/jeecg-boot#3734]
##### 版本号：
v2.4.6

##### 问题描述：
2022年5月23日，sql、java、js增强都不能保存了

##### 截图&代码：
![1653372560](https://user-images.githubusercontent.com/95906870/169960830-9e902766-6d7f-4b9e-b309-3b51e171c025.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by gaobeijia** [comment]
![1653372560](https://user-images.githubusercontent.com/95906870/169960760-f6feb3aa-219e-4a4c-b0fe-37f26465dcd2.jpg)

**Comment by gaobeijia** [comment]
qq群里有人碰到同样的问题，同样的时间发生

**Comment by southwind1** [comment]
没错那个人就是我。

**Comment by zhangdaiscott** [comment]
本地还是线上？

**Comment by bghx123** [comment]
我也碰到了，刚开始以后是浏览器版本问题，但换新版也不行

**Comment by bghx123** [comment]
我也碰到了，刚开始以为是浏览器版本问题，但换新版也不行

**Comment by bghx123** [comment]
我也碰到了，刚开始以为是浏览器版本问题，但换新版也不行
