### ISSUE TITLE
erp风格能否左右展示而不是上下

### ISSUE THREAD

**Issue by 171444135** [jeecgboot/jeecg-boot#3735]
![a24042bd917f8e6881f1b5c557848ae](https://user-images.githubusercontent.com/58811727/169971754-a7d4fc66-d9a2-49d1-895b-1d6e138f5764.png)
##### 问题描述：
**erp风格能否左右展示而不是上下**

##### 截图&代码：

如图，当列数少的时候可否让其主附表左右展示

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
常用示例里面不是很多排版效果吗
