### ISSUE TITLE
单元测试报错

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3736]
##### 版本号：
v3.2.0

##### 问题描述：
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method forcePrometheusPostProcessor in org.jeecg.config.WebMvcConfiguration required a bean of type 'io.micrometer.prometheus.PrometheusMeterRegistry' that could not be found.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/169973996-373efc21-4ace-46fa-afe9-42dd08ac1604.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecg-boot/issues/I561IU
