### ISSUE TITLE
前端js里判断是否拥有权限

### ISSUE THREAD

**Issue by Haowensheng** [jeecgboot/jeecg-boot#3738]
##### 版本号：
3.1.0
##### 问题描述：
请教一个关于前端权限的问题 
我看过官方文档之后知道在html里面判断权限可以用v-has来判断 但是我现在有一个需求是需要在js里面判断权限 那么我该怎样判断呢 我看了代码好像也没有相关的方法

**Comment by zhangdaiscott** [comment]
这个还不简单，通过写js，编码控制页面控件的显示与隐藏。
至于权限怎么获取，就是你编码的逻辑问题，自己想怎么实现都可以
