### ISSUE TITLE
每点击一次锚点，就会在首页生成一个新的页面

### ISSUE THREAD

**Issue by zhouyang120599** [jeecgboot/jeecg-boot#3740]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/38548209/170166088-b417d790-7882-46bb-b247-adffe2247e2d.png)

![ZAR $0208%8ZV1K$L9LM%9S](https://user-images.githubusercontent.com/38548209/170166063-71747e67-e100-4335-9a81-cc06400bebc8.png)
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的代码，就不要发issue了
