### ISSUE TITLE
jeecg-boot 3.2.0使用的knife4j在使用@DynamicParameters情况下会报错

### ISSUE THREAD

**Issue by cosolar** [jeecgboot/jeecg-boot#3741]
##### 版本号：
<version>3.2.0</version>

##### 问题描述：

jeecg-boot使用的knife4j在使用@DynamicParameters情况下会报错，请查看验证什么原因导致的？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28598727/170169601-f6c18cb0-15c5-4976-9d2b-e02c845bc7ae.png)

错误信息：
[main] ERROR com.github.xiaoymin.knife4j.spring.util.ByteUtils:82 - by java.lang.ClassFormatError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/github/xiaoymin/knife4j/model/logincontroller/Login"

**Comment by zhangdaiscott** [comment]
sq
