### ISSUE TITLE
报表单元格之间加减运算问题

### ISSUE THREAD

**Issue by wang38651962** [jeecgboot/jeecg-boot#3743]
##### 问题描述：
报表单元格公式里面，为什么单独字段的合计都没问题，但我单元合计后再做加减就不行了？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/94945690/170197991-fa21ce39-d4ff-459d-bc3b-c14beb0338db.png)
![image](https://user-images.githubusercontent.com/94945690/170198014-2d800927-6cd5-4389-98cd-09d86c7efce9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
标清楚，哪个表达式不好使？

**Comment by wang38651962** [comment]
> 标清楚，哪个表达式不好使？

红色方框选择的最左上交，sum后相加结果不对。第二列是单独求和的结果都正确，求和后再相加就不对了，显示结果是0

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
`sum、max、min、average`不支持加减乘除,如果想要相加请使用`SUM(K2:H5)`

**Comment by wang38651962** [comment]
> `sum、max、min、average`不支持加减乘除,如果想要相加请使用`SUM(K2:H5)`

![image](https://user-images.githubusercontent.com/94945690/171077119-c7a54349-7c34-44ec-9910-7331fa7d9a16.png)
![image](https://user-images.githubusercontent.com/94945690/171077161-0035b696-4fc7-41f1-b595-c04202d89c0b.png)
使用=sum(M2,J5)的结果依然不对，正确结果应该是1,980,170.24，但显示结果为0

**Comment by 1298191366** [comment]
你设计页面是咋设计的，请提供报表配置及数据
![image](https://user-images.githubusercontent.com/30997828/171077589-d6e46400-b369-4e8f-b0fa-37d7bc14d8cb.png)
![image](https://user-images.githubusercontent.com/30997828/171077636-73b83e9d-042d-4cb6-960e-ecc6815b93a0.png)

**Comment by 1298191366** [comment]
你设计页面是怎样设计的，你是不是多个数据集进行的计算，多个数据集不支持，还有一个就是`SUM(C1,C2)`仅算C1和C2所在单元格的数据
![image](https://user-images.githubusercontent.com/30997828/171079101-e717bd66-39db-408a-9e14-44b0a20ffb92.png)
