### ISSUE TITLE
VUE3前端加载慢

### ISSUE THREAD

**Issue by zbozhk** [jeecgboot/jeecg-boot#3745]

**Comment by zhangdaiscott** [comment]
不同步是因为文件名大小写不规范导致，你查下

**Comment by zbozhk** [comment]
> 不同步是因为文件名大小写不规范导致，你查下 第一次运行慢，现在最新代码，做了优化可以更新看看

不同步问题解决了，请问最新代码是15天前的版本吗，我们现在下载的VUE3的仓库显示的是15天前的版本，还是第一次运行很慢

**Comment by zhangdaiscott** [comment]
vite的机制，我们改了下，提升了一些
他这个启动很快，访问的时候慢，访问之后就快了

**Comment by orienthong** [comment]
部署的情况下，第一次访问确实太慢，第二次快的原因是有缓存就快了，但这没有从根本解决问题
