### ISSUE TITLE
jvxetable列类型slot在不编辑时没有与其单元格保持一样的样式

### ISSUE THREAD

**Issue by cgwykgw** [jeecgboot/jeecg-boot#3746]
##### 版本号：
2.4.2

##### 截图&代码：

![image](https://user-images.githubusercontent.com/38972781/170408151-dbbed359-4819-44c7-879f-1a595bc2b66b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
slot一般用于按钮等操作，所以就是这样设计的，会一直显示出来。
想要实现不编辑时显示文字，可以自定义一个行编辑的组件。

参考：
`src/components/JVxeCustom/index.ts`
`src/components/JVxeCustom/src/components/JVxeSelectDictSearchCell.ts`
![image](https://user-images.githubusercontent.com/34293221/170962952-b6be1d8c-9b39-4886-a2ad-a46328891e34.png)
