### ISSUE TITLE
自定义左侧菜单不生效

### ISSUE THREAD

**Issue by k1195453766** [jeecgboot/jeecg-boot#3747]
##### 版本号：
3.1.0

##### 问题描述：
不使用系统配置菜单，单独在 src/config/router.config.js 中添加添加路由，在页面能跳转但是不显示
具体路由配置如下，教育管理模块和视频管理模块不能出现在左侧菜单栏：
{
    path: '/',
    name: 'index',
    component: TabLayout,
    meta: {title: '1'},
    redirect: '/dashboard/analysis',
    children: [
      {
        path: '/dashboard/analysis',
        name: 'dashboard',
        component: () => import('@/views/dashboard/Analysis'),
        meta: { title: '首页', icon: 'dashboard'}
      },
      {
        path: '/edu',
        name: 'edu',
        redirect: '/edu/eduEnglish',
        component: RouteView,
        meta: { title: '教育管理', icon: 'dashboard'},
        children: [
          {
            path: '/edu/eduEnglish',
            name: 'EduEnglish',
            component: () => import('@/views/edu/HelloWorld'),
            meta: { title: '教育详情' }
          }
        ]
      },
      {
        path: '/video',
        name: 'video',
        component: RouteView,
        redirect: '/video/realTimeMonitoring',
        meta: { title: '视频管理', icon: 'home' },
        children: [
          {
            path: '/video/realTimeMonitoring',
            name: 'RealTimeMonitoring',
            component: () => import('@/views/videoManage/RealTimeMonitoring'),
            meta: { title: '视频监控' }
          },
          {
            path: '/video/historicalMonitoring',
            name: 'HistoricalMonitoring',
            component: () => import('@/views/videoManage/HistoricalMonitoring'),
            meta: { title: '历史监控' }
          }
        ]
      },
      
    ]
  }
]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己特殊用法，自己多研究下吧

**Comment by k1195453766** [comment]
@zhangdaiscott 额，大佬，意思就是说我这样用本身就不能生成菜单栏，需要自己解决是么？

**Comment by TankCoder** [comment]
> @zhangdaiscott 额，大佬，意思就是说我这样用本身就不能生成菜单栏，需要自己解决是么？

@k1195453766 你最后有解决吗？

**Comment by k1195453766** [comment]
> 
算是解决了吧，自己把自定义的路由 手动添加到 菜单栏里。目前能添加，但是没做顺序限制，只能排在系统菜单的后面

**Comment by TankCoder** [comment]
> > 
> 
> 算是解决了吧，自己把自定义的路由 手动添加到 菜单栏里。目前能添加，但是没做顺序限制，只能排在系统菜单的后面

@k1195453766  感谢回复，我这边要加很多的详情页，但是官方的三级隐藏路由貌似有问题，你这边有添加过动态路由吗？
我也提了个问题，目前官方还没有回复
https://github.com/jeecgboot/jeecg-boot/issues/4013
