### ISSUE TITLE
定时任务问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3748]
##### 版本号：
v3.2.0

##### 问题描述：
新增的第一次可以循环自动，重启服务后不行，然后重新一样的配置新增一个就又可以了，重启tomcat服务器后自动循环的又没了，开始以为是多个后端服务开启的原因，关闭了只剩一个也不行，然后新增新的就可以，暂定服务后不重启tomcat再点启动服务循环也不会执行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/170473224-38634bd0-01c7-4dff-8646-1a40a1d0d379.png)
![image](https://user-images.githubusercontent.com/90361617/170473265-d2cfb457-b4c4-43ad-a307-e0aa24b2af54.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
说绕口令呢

**Comment by accpman** [comment]
未发现你说的问题 按如下配置试试
  ## quartz定时任务,采用数据库方式
  quartz:
    job-store-type: jdbc
    initialize-schema: embedded
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #延迟10秒启动定时任务
    startup-delay: 1s
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            misfireThreshold: 12000
            clusterCheckinInterval: 15000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
