### ISSUE TITLE
切换为微服务后，访问在线表单开发模块404

### ISSUE THREAD

**Issue by tony2y** [jeecgboot/jeecg-boot#3752]
##### 截图&代码：
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/38598582/170650104-7144843a-e6e2-4e67-a003-8f8dacbc1679.png">
<img width="676" alt="image" src="https://user-images.githubusercontent.com/38598582/170650164-0c68b5d8-9887-4006-affb-1db3846f0a79.png">
<img width="578" alt="image" src="https://user-images.githubusercontent.com/38598582/170650266-6aef6583-6975-4916-98d4-4fcbbf3c3403.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
网管怎么配置的

**Comment by tony2y** [comment]
server:
  port: 9999
spring:
  application:
    name: jeecg-gateway
  main:
    #循环依赖默认情况下已经被禁止了
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    #Sentinel配置
    sentinel:
      transport:
        dashboard: jeecg-boot-sentinel:9000
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false
      datasource:
        #流控规则
        flow:  # 指定数据源名称
          # 指定nacos数据源
          nacos:
            server-addr: @config.server-addr@
            # 指定配置文件
            dataId: ${spring.application.name}-flow-rules
            # 指定分组
            groupId: SENTINEL_GROUP
            # 指定配置文件规则类型
            rule-type: flow
            # 指定配置文件数据格式
            data-type: json
        #降级规则
        degrade:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        #系统规则
        system:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
            data-type: json
        #授权规则
        authority:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
            data-type: json
        #热点参数
        param-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-param-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        #网关流控规则
        gw-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
            data-type: json
        #API流控规则
        gw-api-group:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-api-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 5s
#      # Nacos的yml方式路由配置(默认注释掉，采用数据库加载)
#        - id: jeecg-demo
#          uri: lb://jeecg-demo
#          predicates:
#            - Path=/mock/**,/test/**,/bigscreen/template1/**,/bigscreen/template2/**
#        - id: jeecg-system
#          uri: lb://jeecg-system
#          predicates:
#            - Path=/sys/**,/eoa/**,/v1/**,/joa/**,/online/**,/bigscreen/**,/jmreport/**,/desform/**,/act/**,/plug-in/**,/generic/**
#        - id: jeecg-system-websocket
#          uri: lb:ws://jeecg-system
#          predicates:
#            - Path=/websocket/**,/eoaSocket/**,/newsWebsocket/**
#        - id: jeecg-demo-websocket
#          uri: lb:ws://jeecg-demo
#          predicates:
#            - Path=/vxeSocket/**

**Comment by tony2y** [comment]
server:
  port: 9999
spring:
  application:
    name: jeecg-gateway
  main:
    #循环依赖默认情况下已经被禁止了
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    #Sentinel配置
    sentinel:
      transport:
        dashboard: jeecg-boot-sentinel:9000
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false
      datasource:
        #流控规则
        flow:  # 指定数据源名称
          # 指定nacos数据源
          nacos:
            server-addr: @config.server-addr@
            # 指定配置文件
            dataId: ${spring.application.name}-flow-rules
            # 指定分组
            groupId: SENTINEL_GROUP
            # 指定配置文件规则类型
            rule-type: flow
            # 指定配置文件数据格式
            data-type: json
        #降级规则
        degrade:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        #系统规则
        system:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
            data-type: json
        #授权规则
        authority:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
            data-type: json
        #热点参数
        param-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-param-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        #网关流控规则
        gw-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
            data-type: json
        #API流控规则
        gw-api-group:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-api-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 5s
#      # Nacos的yml方式路由配置(默认注释掉，采用数据库加载)
#        - id: jeecg-demo
#          uri: lb://jeecg-demo
#          predicates:
#            - Path=/mock/**,/test/**,/bigscreen/template1/**,/bigscreen/template2/**
#        - id: jeecg-system
#          uri: lb://jeecg-system
#          predicates:
#            - Path=/sys/**,/eoa/**,/v1/**,/joa/**,/online/**,/bigscreen/**,/jmreport/**,/desform/**,/act/**,/plug-in/**,/generic/**
#        - id: jeecg-system-websocket
#          uri: lb:ws://jeecg-system
#          predicates:
#            - Path=/websocket/**,/eoaSocket/**,/newsWebsocket/**
#        - id: jeecg-demo-websocket
#          uri: lb:ws://jeecg-demo
#          predicates:
#            - Path=/vxeSocket/**

**Comment by tony2y** [comment]
server:
  port: 9999
spring:
  application:
    name: jeecg-gateway
  main:
    #循环依赖默认情况下已经被禁止了
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    #Sentinel配置
    sentinel:
      transport:
        dashboard: jeecg-boot-sentinel:9000
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false
      datasource:
        #流控规则
        flow:  # 指定数据源名称
          # 指定nacos数据源
          nacos:
            server-addr: @config.server-addr@
            # 指定配置文件
            dataId: ${spring.application.name}-flow-rules
            # 指定分组
            groupId: SENTINEL_GROUP
            # 指定配置文件规则类型
            rule-type: flow
            # 指定配置文件数据格式
            data-type: json
        #降级规则
        degrade:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        #系统规则
        system:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
            data-type: json
        #授权规则
        authority:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
            data-type: json
        #热点参数
        param-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-param-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        #网关流控规则
        gw-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
            data-type: json
        #API流控规则
        gw-api-group:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-api-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 5s
#      # Nacos的yml方式路由配置(默认注释掉，采用数据库加载)
#        - id: jeecg-demo
#          uri: lb://jeecg-demo
#          predicates:
#            - Path=/mock/**,/test/**,/bigscreen/template1/**,/bigscreen/template2/**
#        - id: jeecg-system
#          uri: lb://jeecg-system
#          predicates:
#            - Path=/sys/**,/eoa/**,/v1/**,/joa/**,/online/**,/bigscreen/**,/jmreport/**,/desform/**,/act/**,/plug-in/**,/generic/**
#        - id: jeecg-system-websocket
#          uri: lb:ws://jeecg-system
#          predicates:
#            - Path=/websocket/**,/eoaSocket/**,/newsWebsocket/**
#        - id: jeecg-demo-websocket
#          uri: lb:ws://jeecg-demo
#          predicates:
#            - Path=/vxeSocket/**

**Comment by tony2y** [comment]
`server:
  port: 9999
spring:
  application:
    name: jeecg-gateway
  main:
    #循环依赖默认情况下已经被禁止了
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    #Sentinel配置
    sentinel:
      transport:
        dashboard: jeecg-boot-sentinel:9000
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false
      datasource:
        #流控规则
        flow:  # 指定数据源名称
          # 指定nacos数据源
          nacos:
            server-addr: @config.server-addr@
            # 指定配置文件
            dataId: ${spring.application.name}-flow-rules
            # 指定分组
            groupId: SENTINEL_GROUP
            # 指定配置文件规则类型
            rule-type: flow
            # 指定配置文件数据格式
            data-type: json
        #降级规则
        degrade:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        #系统规则
        system:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
            data-type: json
        #授权规则
        authority:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
            data-type: json
        #热点参数
        param-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-param-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        #网关流控规则
        gw-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
            data-type: json
        #API流控规则
        gw-api-group:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-api-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 5s
#      # Nacos的yml方式路由配置(默认注释掉，采用数据库加载)
#        - id: jeecg-demo
#          uri: lb://jeecg-demo
#          predicates:
#            - Path=/mock/**,/test/**,/bigscreen/template1/**,/bigscreen/template2/**
#        - id: jeecg-system
#          uri: lb://jeecg-system
#          predicates:
#            - Path=/sys/**,/eoa/**,/v1/**,/joa/**,/online/**,/bigscreen/**,/jmreport/**,/desform/**,/act/**,/plug-in/**,/generic/**
#        - id: jeecg-system-websocket
#          uri: lb:ws://jeecg-system
#          predicates:
#            - Path=/websocket/**,/eoaSocket/**,/newsWebsocket/**
#        - id: jeecg-demo-websocket
#          uri: lb:ws://jeecg-demo
#          predicates:
#            - Path=/vxeSocket/**`

**Comment by tony2y** [comment]
`server:
  port: 9999
spring:
  application:
    name: jeecg-gateway
  main:
    #循环依赖默认情况下已经被禁止了
    allow-circular-references: true
    allow-bean-definition-overriding: true
  cloud:
    #Sentinel配置
    sentinel:
      transport:
        dashboard: jeecg-boot-sentinel:9000
      # 支持链路限流
      web-context-unify: false
      filter:
        enabled: false
      # 取消Sentinel控制台懒加载
      eager: false
      datasource:
        #流控规则
        flow:  # 指定数据源名称
          # 指定nacos数据源
          nacos:
            server-addr: @config.server-addr@
            # 指定配置文件
            dataId: ${spring.application.name}-flow-rules
            # 指定分组
            groupId: SENTINEL_GROUP
            # 指定配置文件规则类型
            rule-type: flow
            # 指定配置文件数据格式
            data-type: json
        #降级规则
        degrade:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
            data-type: json
        #系统规则
        system:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
            data-type: json
        #授权规则
        authority:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
            data-type: json
        #热点参数
        param-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-param-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow
            data-type: json
        #网关流控规则
        gw-flow:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
            data-type: json
        #API流控规则
        gw-api-group:
          nacos:
            server-addr: @config.server-addr@
            dataId: ${spring.application.name}-api-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
            data-type: json
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

**Comment by tony2y** [comment]
默认配置

**Comment by tony2y** [comment]
哪里需要更改一下呢

**Comment by zhangdaiscott** [comment]
理解的就不对

**Comment by tony2y** [comment]
改怎么调整呢

**Comment by tony2y** [comment]
就是需要微服务情况下 能正常使用online表单模块

**Comment by tony2y** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/38598582/170870878-7448a748-59bd-4af3-996d-4698a137c5e7.png">

**Comment by zhangdaiscott** [comment]
我们测试无问题，自己看看改过什么，或者 缺少什么配置

**Comment by tony2y** [comment]
全部是都是最新的代码拉下来，按照文档切换成微服务模式，然后前端路径 localhost:9999
