### ISSUE TITLE
切换微服务nacos启动不起来

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3753]
##### 版本号：
 v3.2.0

##### 问题描述：
按说明配置了，可是启动nacos提示No DataSource set

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/170658594-599ac3a9-219a-462d-86cd-28de2a0cb480.png)
![image](https://user-images.githubusercontent.com/90361617/170658616-f869e8bf-7295-4cc2-81f2-c4540d37d53d.png)
![image](https://user-images.githubusercontent.com/90361617/170658846-f84ddbf6-5f83-4989-9a69-ca8f52706b0e.png)
![image](https://user-images.githubusercontent.com/90361617/170659667-707f3cb0-424f-435d-b993-81ec30cd57a0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
nacos数据库的配置？
