### ISSUE TITLE
数据过多时图表X轴显示不全，无法滚动显示

### ISSUE THREAD

**Issue by YZz-S** [jeecgboot/jeecg-boot#3756]
##### 版本号：
3.0.0（发布日期：2021-11-01）

##### 问题描述：
数据过多时图表X轴文字显示不全，无法滚动显示

##### 截图&代码：

  
![image](https://user-images.githubusercontent.com/44917477/170741024-418e87d4-2d9e-4347-a951-82d8798167d4.png)

**Comment by zhangdaiscott** [comment]
你得自己设下比例

**Comment by hzl7652** [comment]
@zhangdaiscott 这个比例怎么设置
