### ISSUE TITLE
渲染列表

### ISSUE THREAD

**Issue by fendouhuohuo** [jeecgboot/jeecg-boot#3759]
##### 版本号：
3.1.0

##### 问题描述：
在Online在线功能中，数据是从其他的服务中得到的，数据是List形式，在点击功能测试的时候，怎样将得到的数据展示在页面中

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你可以通过online报表来实现，那边支持接口

**Comment by fendouhuohuo** [comment]
![image](https://user-images.githubusercontent.com/77576749/170957870-81d2c366-7ac1-42c9-b956-627dc2d5b57c.png)这里没有配置接口呀

**Comment by fendouhuohuo** [comment]
> 你可以通过online报表来实现，那边支持接口

![](https://user-images.githubusercontent.com/77576749/170957870-81d2c366-7ac1-42c9-b956-627dc2d5b57c.png)

这里没有配置接口呀

**Comment by zhangdaiscott** [comment]
哪就是不支持
