### ISSUE TITLE
新微服务模块如何添加路由网关

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3762]
##### 版本号：
v3.2.0

##### 问题描述：
是通过使用archetype生成新微服务模块，已经能单独启动成功了，如何添加路由网关呢

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/170961312-cfc60a90-0c97-4245-b628-a04adbf2e05e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 3509282792** [comment]
知道了，这里有http://doc.jeecg.com/2294757

**Comment by yxlcode** [comment]
> 知道了，这里有http://doc.jeecg.com/2294757

我这边新增了一个微服务模块，path填的比如aa，前端也填了，但是没启作用，你遇到了吗

**Comment by SupYouM** [comment]
你要在nacos的jeecg-gateway-router.json文件中添加上你新的微服务的引用，同时网关还需要重启
