### ISSUE TITLE
平台维护的路由网关菜单问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3763]
##### 版本号：
v3.2.0

##### 问题描述：
再通过系统管理下的路由配置菜单进行路由维护，添加路由条件选项没有path选项

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/170972724-ed2d0217-6da4-4649-bc7c-d0b89e374793.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请更新代码
