### ISSUE TITLE
centos7 jenkins Maven 打包失败

### ISSUE THREAD

**Issue by zhaozhuangwang** [jeecgboot/jeecg-boot#3764]
##### 版本号：
centos 7

jenkins   2.319.2

Maven  3.8.1 (已经配置  jeecg阿里镜像源)
![image](https://user-images.githubusercontent.com/42265723/171075871-3ee48a4e-dd41-4290-b4e0-b78ae6b77b37.png)

![image](https://user-images.githubusercontent.com/42265723/171075546-40c346e0-ae01-4687-9593-2dc4526e375c.png)

jdk   jdk1.8.0_121  &  jdk1.8.0_333

##### 问题描述：

boot 源码只是修改了mysql Redis 等配置，其他没做任何修改

2月底的时候，Jenkins  Maven   自动打包没问题，5.27 这几天 更新了一下官方的包，提交后，就报错了，查阅了很多问题，但是依然不得而知问题在哪里，

##### 截图&代码：

![image](https://user-images.githubusercontent.com/42265723/171075658-378bfe35-0999-4541-9aba-ed879e1ecebd.png)

**Comment by zhangdaiscott** [comment]
自己先本地研究打包看看，多测测
我们也用jks，没有任何问题

**Comment by zhaozhuangwang** [comment]
我的问题不是问源码， 本地打包是可以的，我就是想问一下是我 centos 哪里配置的不对么？
