### ISSUE TITLE
自定义树,链接超时

### ISSUE THREAD

**Issue by xu-my** [jeecgboot/jeecg-boot#3767]
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/96990578/171342029-1d432056-944c-4ed3-ae8b-f630a7732be0.png)
****
直接使用配置路径 进行配置没有问题。
如下：
![图片](https://user-images.githubusercontent.com/96990578/171342257-2d46028a-f6ad-4da0-be5e-004d579a1663.png)
##  以上都没有问题，但是 生成代码产生一个问题：
  DivisionsModal组件中 <br>

 add (obj) {
        this.modelDefault.=''   <====  这里的 pid 没有生成，我给它加上
        this.edit(Object.assign(this.modelDefault , obj));
      },

在前端中有配置了一个新菜单，发现打不开 超时9000错误
![图片](https://user-images.githubusercontent.com/96990578/171343215-1218ecb7-a3c5-4f01-93f2-5a79f0e18605.png)
![图片](https://user-images.githubusercontent.com/96990578/171343302-6842b626-3170-46c4-9902-b7051af5427b.png)

**Comment by zhangdaiscott** [comment]
贴代码，这种问题自己排查会更快
