### ISSUE TITLE
网关服务启动报错

### ISSUE THREAD

**Issue by badguyjdeson** [jeecgboot/jeecg-boot#3770]
##### 版本号：

 3.2.0

##### 问题描述：

启动cloud-module中网关服务报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/62640951/171574523-b9055584-4f80-462c-90db-aff5a1b2dff2.png)

#### 友情提示（为了提高issue处理效率）：

  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
maven 刷新
