### ISSUE TITLE
mysql 使用JeecgOneGUI生成代码 提示user_tab_cols doesn't exist

### ISSUE THREAD

**Issue by kdafang** [jeecgboot/jeecg-boot#3771]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/28125438/171576038-0cea392c-7a33-44d8-b6d1-c90dfadc13ca.png)

![image](https://user-images.githubusercontent.com/28125438/171576325-a3db51d9-5b2e-4ec7-b72f-f7e89195b551.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
测试无问题，请提供重现步骤

**Comment by kdafang** [comment]
![image](https://user-images.githubusercontent.com/28125438/172083760-8303b06d-0698-4205-9d8d-48eeafc8e14c.png)
使用JeecgOneGUI生成代码，数据库为mysql，数据库名中包含admin时会报上述错误，修改数据库名为不包含dm字符后功能正常
![image](https://user-images.githubusercontent.com/28125438/172083970-b95df715-502d-4d9e-8ad0-b78950075077.png)

**Comment by zhangdaiscott** [comment]
mysql版本号，同样配置无任何问题

**Comment by kdafang** [comment]
5.7.23

**Comment by zhangdaiscott** [comment]
测试无任何问题，请提供准备的重现步骤，再发issue

**Comment by yimogithub** [comment]
> mysql版本号，同样配置无任何问题

遇到楼主同样问题，数据库名 admintest
