### ISSUE TITLE
mybatis自动更新字段问题

### ISSUE THREAD

**Issue by PerfectYingxu** [jeecgboot/jeecg-boot#3773]
##### 版本号：
3.0

##### 问题描述：
mybatis在执行save方法的时候会自动更新创建时间；执行update方式会自动更新更新时间，请问下这个配置可以在哪里修改

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
拦截器

**Comment by PerfectYingxu** [comment]
这个拦截器是写在哪个包下的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月4日(周六) 上午10:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] mybatis自动更新字段问题 (Issue #3773)




 
拦截器
