### ISSUE TITLE
online报表是否支持动态参数查询

### ISSUE THREAD

**Issue by KeZhichang** [jeecgboot/jeecg-boot#3775]
##### 版本号：
3.1

##### 问题描述：
若有一些稍微复杂的逻辑，是否支持通过查询的方式传入动态参数，希望能通过这种方式将参数传入SQL的子查询，例子如下图所示，需求为，通过code组织子查询条件查出对应报表结果

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36397488/172016143-1583b1f6-7a97-46e9-8701-0d59aab0a538.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
支持，看文档
