### ISSUE TITLE
数据快照功能优化需求望大佬支持实现

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#3776]
##### 版本号：
v3.2.0

##### 问题描述：
当前使用方式为
``` java
sysDataLogService.addDataLog("lims_part", part.getId(), JSON.toJSONString(part, SerializerFeature.WriteMapNullValue));
```

因为类似add\edit都传递了实体对象（例如part），能否提供一个注解，@AutoDataLog(table = "lims_part")这样的功能来添加数据日志？
望大佬实现。

##### 截图&代码：
http://doc.jeecg.com/2043938

**Comment by zhangdaiscott** [comment]
不是提供了吗
