### ISSUE TITLE
查询过滤器优化望大佬实现

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#3777]
##### 版本号：
v3.2.0

##### 问题描述：
当前将表单转为mybatisPlus的QueryMapper为字段名，例如eq("name","张三")，能否转为表名.字段名，例如将前端的student.name转换为eq.("student.name",“张三”)，避免querymapper追加到mybatis中由于两个join表有相同列name而发生错误？

望大佬实现。
##### 截图&代码：
http://doc.jeecg.com/2043941

**Comment by zhangdaiscott** [comment]
你可以自己实现
