### ISSUE TITLE
3.2版本验证码报404

### ISSUE THREAD

**Issue by zbkpointer** [jeecgboot/jeecg-boot#3780]
##### 问题描述：
部署到阿里云服务器上，登录界面验证码404。
前端使用Nginx部署，端口是3000，后端使用命令行 java -jar部署，端口是8082。

##### 截图&代码：
前端生产文件**.env.production**的参数如下：
```
VUE_APP_API_BASE_URL=http://121.40.116.128:8082/jeecg-boot
VUE_APP_CAS_BASE_URL=http://121.40.116.128:8888/cas
VUE_APP_ONLINE_BASE_URL=http://fileview.jeecg.com/onlinePreview
```
Nginx的配置如下：
```
  listen       3000;
#server_name  localhost;

#后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问		
location ^~ /jeecg-boot {
proxy_pass              http://121.40.116.128:8082/jeecg-boot/;#尝试更换127.0.0.1也不行
proxy_set_header        Host 121.40.116.128;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
}
#解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
location / {
root   C:/MiddleSoftware/jeecg-boot/ant-design-vue-jeecg/dist;
index  index.html index.htm;
if (!-e $request_filename) {
rewrite ^(.*)$ /index.html?s=$1 last;
break;
}
}
```
访问界面如下图所示：

![image](https://user-images.githubusercontent.com/32861808/172281090-1ae1a5f0-9fc5-456d-8bef-1e17970712bd.png)
控制台输出配置项为：
```
{
    "VUE_APP_API_BASE_URL": "",
    "VUE_APP_CAS_BASE_URL": "",
    "VUE_APP_ONLINE_BASE_URL": "",
    "domianURL": "http://121.40.116.128:8082/jeecg-boot",
    "casPrefixUrl": "http://121.40.116.128:8888/cas",
    "onlinePreviewDomainURL": "http://fileview.jeecg.com/onlinePreview",
    "staticDomainURL": "http://121.40.116.128:8082/jeecg-boot/sys/common/static",
    "pdfDomainURL": "http://121.40.116.128:8082/jeecg-boot/sys/common/pdf/pdfPreviewIframe"
}
```

单独请求 `http://121.40.116.128:8082/jeecg-boot/sys/randomImage/1654567976358?_t=1654567976`亦是无响应，
不知道是哪里的配置问题？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043886

**Comment by zbkpointer** [comment]
你的邮件已经收到。别着急，会尽快处理的。Your email has been received.Don't  worry,it will be dealt with as soon as possible.

**Comment by zbkpointer** [comment]
你的邮件已经收到。别着急，会尽快处理的。Your email has been received.Don't  worry,it will be dealt with as soon as possible.

**Comment by AlibabaP8Developer** [comment]
<img width="2415" height="1596" alt="Image" src="https://github.com/user-attachments/assets/275bf243-f838-489b-aa01-d78fb7655d20" />

<img width="2457" height="1648" alt="Image" src="https://github.com/user-attachments/assets/33cb7ca6-d728-4f30-b8e0-e5d20f1670e6" />

验证码出不来，一直转圈，啥破玩意儿，求解？

<img width="1234" height="889" alt="Image" src="https://github.com/user-attachments/assets/d4dd293c-16ea-4aad-8a26-9b627dbbf0d2" />

**Comment by zbkpointer** [comment]
你的邮件已经收到。别着急，会尽快处理的。Your email has been received.Don't  worry,it will be dealt with as soon as possible.
