### ISSUE TITLE
数据库中毒

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3781]
##### 版本号：
v3.2.0

##### 问题描述：
这个情况怎么杜绝呀，之前为了研究jeecg大屏，那大屏对接是可以数据库对接的，所以把端口映射出去了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/172301900-374a146a-2c8c-4e02-8f12-413f274d5423.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个是你数据库或者服务器密码太简单，被攻击了
跟jeecg无关
