### ISSUE TITLE
Jeecgboot-Vue3 v1.2.0 版本online表单问题

### ISSUE THREAD

**Issue by freedom20200918** [jeecgboot/jeecg-boot#3783]
##### 问题描述：
个版本前端中的 【在线开发】有bug ，重现方式进入在线开发-》选择任意表->更多->功能测试  

进入画面后提示获取查询条件失败 然后页面就不渲染了  ，查看接口后发现  

新版本的接口为：
http://localhost:9991/online/cgform/api/getQueryInfoVue3/8ac0800e813c362201813c3a59650001?_t=1654582257433
这个请求结果为404

然后比对老的 vue2的版本发现 请求地址为 （getQueryInfo）
http://localhost:9991/online/cgform/api/getQueryInfo/8ac0800e813c362201813c3a59650001?_t=1654582257433
尝试使用postman 访问  getQueryInfo的接口结果能返回请求，所以是否代码没有提交完全 的导致的bug是否能发个补丁...[流泪]

##### 截图&代码：

![image](https://user-images.githubusercontent.com/74686208/172313936-0f364858-bb20-4ded-9019-c4f73f75492b.png)
![image](https://user-images.githubusercontent.com/74686208/172314085-0c6972b1-618b-4b77-b0cf-d334152756ee.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新后台代码
