### ISSUE TITLE
项目运行突然启动报找不到org.jeecg.common.constant.enums.ModuleType;

### ISSUE THREAD

**Issue by qiuxianggengs** [jeecgboot/jeecg-boot#3784]
##### 版本号：
3.1.0，JDK1.8 

##### 问题描述：
项目运行突然启动报找不到org.jeecg.common.constant.enums.ModuleType;

/jeecg-boot-base-core/src/main/java/org/jeecg/common/aspect/annotation/AutoLog.java:[46,5] 找不到符号
/jeecg-boot-base-core/src/main/java/org/jeecg/common/util/BrowserUtils.java:[79,19] 找不到符号
/jeecg-boot-base-core/src/main/java/org/jeecg/common/util/security/SecurityTools.java:[43,41] 找不到符号

##### 截图&代码：

![image](https://user-images.githubusercontent.com/107164621/172758256-35a2cf8e-c7eb-46d9-92b8-ae94832af552.png)
![image](https://user-images.githubusercontent.com/107164621/172758294-a73b1a34-5baf-4337-9c1b-165fbb08ec09.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
clean maven刷新

**Comment by qiuxianggengs** [comment]
clean过了，还是不可以

**Comment by qiuxianggengs** [comment]
![image](https://user-images.githubusercontent.com/107164621/172782286-e6a4a1a4-5a9d-419e-b38a-6bfa24f10a75.png)

**Comment by qiuxianggengs** [comment]
项目删了，重新打开，jdk，maven都删了重新安装还是不一样。到其他电脑还是一样
