### ISSUE TITLE
关于FeignClient调用的2个问题，麻烦帮忙解决

### ISSUE THREAD

**Issue by liujia3351** [jeecgboot/jeecg-boot#3787]
##### 版本号：
当前最新版本： 3.2.0（发布日期：2022-04-25）

##### 问题描述：
问题1：使用JeecgFeignService类的构造方法时，Client和Contract参数会提示无法自动装配编译错误，详见截图1

问题2：使用静态调用JeecgTestClientFactory调用FeignConfig配置类时，会有返回错误信息乱码问题，使用JeecgFeignService动态调用FeignClient不走FeignConfig配置类时没有错误乱码问题，详见截图2

##### 截图&代码：
问题截图和代码1:
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/74476060/173274557-1b13c606-018a-4141-b6f6-89ecda022b19.png">

问题截图和代码2:
使用JeecgFeignService动态调用没有问题
<img width="917" alt="image" src="https://user-images.githubusercontent.com/74476060/173274765-7eed99ba-682f-49ac-b4cd-20a642d96b87.png">

使用JeecgTestClientFactory调用FeignConfig配置类时会有乱码问题
<img width="905" alt="image" src="https://user-images.githubusercontent.com/74476060/173274783-0a355c97-5c81-43df-b8b7-c86defff8d86.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
最新版已经取消了JeecgFeignService，你确定你是3.2?
