### ISSUE TITLE
如果admin账号租户 tenant_id=0，如何设置查询所有账号下面数据？

### ISSUE THREAD

**Issue by qiuxianggengs** [jeecgboot/jeecg-boot#3790]
##### 版本号：
jeecboot3，jdk1.8 

##### 问题描述：
目前开启了租户模式，账号admin未分配租户，账号test1=1，test2=2，test3=3 分配租户查询正常，但目前admin用户租户id=0，如何设置才能查询所有用户下数据？目前查询不到 tenant_id=0

##### 截图&代码：
![image](https://user-images.githubusercontent.com/107164621/173354612-e2b3eef6-20f1-4075-b20b-ea17a2037570.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by liaoyongxiong** [comment]
在jeecg-boot/jeecg-boot-base/jeecg-boot-base-core/src/main/java/org/jeecg/config/mybatis/MybatisPlusSaasConfig.java里，判断租户为0的用户，不进行租户注入，应就可以

**Comment by qiuxianggengs** [comment]
没用的，本身代码里已经写如果没租户默认是0了

**Comment by Feng-Xg** [comment]
> 这样写
![image](https://github.com/jeecgboot/jeecg-boot/assets/19472852/108007ff-5b8b-43e6-8a3e-fb63b7dcf834)
