### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'ENV' as it is undefined

### ISSUE THREAD

**Issue by 280377485** [jeecgboot/jeecg-boot#3792]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/55683514/173470443-3a4f107b-f07a-4709-a090-d997dd5189fd.png)

![image](https://user-images.githubusercontent.com/55683514/173470462-da35d318-a5b7-4102-afad-dad258e205a6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by jhonboHou** [comment]
遇到同样的问题，直接使用yarn run build 然后把dist上传到服务器，运行即报这个错误

**Comment by zhangdaiscott** [comment]
> 遇到同样的问题，直接使用yarn run build 然后把dist上传到服务器，运行即报这个错误，有没有解决方法

哪个版本？

**Comment by jhonboHou** [comment]
3.4.0 
![image](https://user-images.githubusercontent.com/49391942/200730141-7552e724-f252-4f1b-b4e6-902da8e95cf7.png)

**Comment by jhonboHou** [comment]
修改了下解决掉了
![image](https://user-images.githubusercontent.com/49391942/200731635-794b929c-03eb-4dfb-b7a3-0f305c1aacdf.png)
