### ISSUE TITLE
WebSocket failed

### ISSUE THREAD

**Issue by a296421914** [jeecgboot/jeecg-boot#3795]
WebSocket connection to 'wss://api.boot.jeecg.com/websocket/a75d45a015c44384a04449ee80dc3503' failed
<img width="833" alt="image" src="https://user-images.githubusercontent.com/9105297/173770785-a76fae53-5d7b-409e-a955-87c8b394ad4c.png">

**Comment by zhangdaiscott** [comment]
总被共计，演示系统关闭了websocket，非功能问题
