### ISSUE TITLE
打开【online表单开发】，弹出token失效，无法进入页面

### ISSUE THREAD

**Issue by zander001** [jeecgboot/jeecg-boot#3796]
##### 版本号：
3.2.0

##### 问题描述：
打开【online表单开发】，弹出token失效，无法进入页面

后台打印
 ————————身份认证失败——————————IP地址:  192.168.0.106，URL:/jeecg-boot/online/cgform/head/list
##### 截图&代码：
![微信截图_20220615165116](https://user-images.githubusercontent.com/55526237/173785597-60b528fb-e587-4068-ac74-45301e6e3a46.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
清空vite缓存
