### ISSUE TITLE
在线表单开发,功能测试.点击404

### ISSUE THREAD

**Issue by jiangxiaozheng** [jeecgboot/jeecg-boot#3798]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/54165898/173849676-98df7f6a-1442-4bac-af38-6e99202020f5.png)
![image](https://user-images.githubusercontent.com/54165898/173849455-46770667-51fe-44f2-9ee1-55fde04f545b.png)
![image](https://user-images.githubusercontent.com/54165898/173850400-03f08a6b-2bf2-42e4-a96d-7a463a4f6c4a.png)
![image](https://user-images.githubusercontent.com/54165898/173850061-4a31dd55-400c-43e6-b990-124a03b2438b.png)
![image](https://user-images.githubusercontent.com/54165898/173850534-f640a31e-fbbd-45d4-99a0-117ac4e08e15.png)

在线开发不能设置为二级菜单吗?
还是要在shiro上放开权限,我看shiro上没有放开 /online/cgformList/  的权限

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
看错误是路由配置错误导致

**Comment by jiangxiaozheng** [comment]
是的,经过昨天的排查,发现是为了路由地址风格统一,将原先/online 路由修改为 /dev/online,虽然页面可以进去,但是页面上的功能却不能使用.
如果想改 /online的路径,是否能提供一个解决方案呢?
