### ISSUE TITLE
vue3的在线开发的online表单开发，更多中的更能测试按钮，有一个getQueryInfoVue3接口后端代码中没有

### ISSUE THREAD

**Issue by CNsmallC** [jeecgboot/jeecg-boot#3799]
##### 版本号：
master最新版本
用的vue3前端也是最新版本

##### 问题描述：
vue3的在线开发的online表单开发，更多中的更能测试按钮，有一个getQueryInfoVue3接口后端代码中没有这个接口对应的路由转换的枚举。
类应该是src/main/java/org/jeecg/modules/system/service/impl/SysBaseApiImpl.java

##### 截图&代码：
这个是**官方线上**：
![image](https://user-images.githubusercontent.com/19250568/174027838-715496ef-2cfa-4be7-8edc-0e88e8e5a761.png)

这个是**本地**：
![image](https://user-images.githubusercontent.com/19250568/174028755-b4e6a4fa-e8a6-49c3-9384-abd01d0e6e17.png)
![image](https://user-images.githubusercontent.com/19250568/174028916-a1438cbc-14ed-4447-8e4f-ea94be720598.png)

后端没有这个路由转换
![image](https://user-images.githubusercontent.com/19250568/174029406-ebc018f2-51bb-4eb5-b37f-07da3d21ce8a.png)

**Comment by zhangdaiscott** [comment]
你的后台没升级

**Comment by CNsmallC** [comment]
> 

最下面这个枚举的截图是直接截图的官方的master分支中的类，不是我本地，
我看里面没有getQueryInfoVue3的枚举项，是不是不走这里啊？

**Comment by CNsmallC** [comment]
好像是打包有点问题，重新clean打包问题解决了，但是不知道这个getQueryInfoVue3的地址是在哪里的，代码里没找到对应接口地址和相关代码..
