### ISSUE TITLE
内嵌子表风格bug

### ISSUE THREAD

**Issue by github944674100** [jeecgboot/jeecg-boot#3800]
##### 版本号：
当前最新版本： 3.2.0（发布日期：2022-04-25）
##### 问题描述：
1.代码生成内嵌子表风格，主表有勾选是否查询时会报错，没勾选就不会报错
2.代码生成内嵌子表风格，子表控件类型为popup时回填到表单的列名有误，导致无法正确回填数据
##### 截图&代码：
1.
![image](https://user-images.githubusercontent.com/72907009/174214912-e5c20170-5c4e-458f-99bd-ab49e4791f2a.png)
2.
![image](https://user-images.githubusercontent.com/72907009/174220317-39565621-f676-41b6-9d2a-4edce6a52c83.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
请说明，具体哪个控件导致

**Comment by github944674100** [comment]
> 请说明，具体哪个控件导致

第一个问题是任意控件选择是否查询都会报错

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
问题1已复现，问题2未复现，你的popup是怎样配置的，
online页面设置
![image](https://user-images.githubusercontent.com/30997828/176152388-042ffa41-1a67-4227-a25c-e462ae125e4f.png)

设置数据
![image](https://user-images.githubusercontent.com/30997828/176152030-0a427c6b-5b90-4e44-849c-c1049be96420.png)
