### ISSUE TITLE
3.2.0版本启动失败，shiro配置初始化时空指针

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/jeecg-boot#3802]
##### 版本号：
3.2

##### 问题描述：
微服务版启动类 org.jeecg.JeecgSystemCloudApplication 报空

##### 截图&代码：
![image](https://user-images.githubusercontent.com/998105/174450770-a827ffce-2751-477f-9f36-ac84456ac83f.png)

![image](https://user-images.githubusercontent.com/998105/174450798-98cd393f-3782-4730-a57f-89f857671545.png)

jeeccgBaseConfig 为空

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
clean下项目

**Comment by zjh0517** [comment]
2023了现在解决了吗
