### ISSUE TITLE
部门用户可以有 admin权限的问题

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/jeecg-boot#3806]
##### 版本号：
3.2.0 

##### 截图&代码：
角色名称：测试部门 ，我给授权了如下图的权限，没有其他的。
![image](https://user-images.githubusercontent.com/998105/174569735-bcc4b0de-1010-46ab-a712-485a743906ed.png)

给这个权限 关联了 ceshibumengjingli 这个账户
![image](https://user-images.githubusercontent.com/998105/174570185-bada064a-ad88-44a0-a05a-e098675d3f32.png)

加了一个部门
![image](https://user-images.githubusercontent.com/998105/174570608-1e981cc4-87e1-4238-bf1f-8657bf0b726a.png)

然后另一个浏览器登录这个账户
角色分配这里可以选择 admin的角色
![image](https://user-images.githubusercontent.com/998105/174570944-82bca2c5-9c3a-427e-aeb5-fffab4ada7c3.png)

这样的话部门权限没啥用了吧。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已解决，下个版本发布
