### ISSUE TITLE
自定义数据字典无权限控制

### ISSUE THREAD

**Issue by IsMrChen** [jeecgboot/jeecg-boot#3807]
##### 版本号：
3.2.0

##### 问题描述：
场景：自定义数据字典下拉选项，需要按照表部门信息，做数据权限控制，目前看无法按照以下方式控制，是暂不支持么？
##### 截图&代码：
园区信息列表经过权限控制后无信息：
![image](https://user-images.githubusercontent.com/53907291/174572248-e8460cf6-d1d0-4679-b837-52b2ff5918e7.png)
楼栋数据，利用数据字典查询园区下拉选项值，无权限控制
![image](https://user-images.githubusercontent.com/53907291/174572045-690a8025-0d68-4ccd-acdb-50e62eb40d80.png)
![image](https://user-images.githubusercontent.com/53907291/174572063-61c02d64-19c0-4213-8678-ca2b396346b9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
