### ISSUE TITLE
数据权限规则问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3810]
##### 版本号：
 v3.2.0

##### 问题描述：
发现查询A栋数据，我选择的是右模糊，也就是代码应该是 数据值 001%,可是实际的代码是包含模糊 %001%

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/174723922-f43a368a-1434-4cbd-851e-8ad5369fae04.png)

![image](https://user-images.githubusercontent.com/90361617/174723833-2f0330e9-4d26-4949-9246-6b61a49b9420.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修改
