### ISSUE TITLE
JImageUpload

### ISSUE THREAD

**Issue by xb4876** [jeecgboot/jeecg-boot#3811]
##### 版本号：
3.1.0-beta

##### 问题描述：
JImageUpload 上传图片后没有给变量赋值   应该注意什么啊

##### 截图&代码：
![K} MNABBR2@E%7)BB(_6I_T](https://user-images.githubusercontent.com/18182812/174733441-eddb74a7-10f0-4195-8ec8-afd4d3054a59.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
描述过意简单，你可以看下jeecg提供的示例，是否有问题
