### ISSUE TITLE
Online控件默认值表达式规则不生效

### ISSUE THREAD

**Issue by Heart-666** [jeecgboot/jeecg-boot#3813]
##### 版本号：

最新
##### 问题描述：

为什么我使用自定义JS表达式没有生效，我调用了sayHi函数有用，但是我发现我去改了sayHi函数里面的内容，依旧还是原来的值，现在就是调用的sayHi函数相当于我并没有成功修改，但是我整个项目找下来就是只有CustomExpression.js这一个文件里面有这个函数，并且我刷新了网页重启项目都没有用，我在sayHi函数进行控制台输出，发现没有调用，但是实际上我测试的时候调用sayHi就有用
##### 截图&代码：

![image](https://user-images.githubusercontent.com/77538584/174845393-714e992f-8a01-44cd-a5cd-c57ee351ca42.png)
![image](https://user-images.githubusercontent.com/77538584/174845506-48bc5c56-cc22-4b29-8d98-9a11d2bf625b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
开源的不支持此功能
