### ISSUE TITLE
企业微信提示，用户列表查询失败！

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3814]
##### 版本号：
v3.2.0

##### 问题描述：
是不是免费版本的企业微信与钉钉不能用？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/174938002-a507d0f1-62b3-42ba-9d4f-df4072937994.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以用，应该是你配置有问题
