### ISSUE TITLE
部门编码可以选择手动生成吗

### ISSUE THREAD

**Issue by lengjinke** [jeecgboot/jeecg-boot#3818]
##### 版本号：
V3.2.0

##### 问题描述：
目前部门编码是自动生成的，可不可以选择手动生成
而且现在判断唯一是根据部门编码，可不可以根据部门编码+租户id判断唯一

如果我导入一个一级部门，部门的编码没有按照自动生成的格式写，在页面再新增一级部门会报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/106538473/175028987-cc49dfe9-dfd4-4b77-97ba-63151353b040.png)
![image](https://user-images.githubusercontent.com/106538473/175029159-78fda5dc-6cb4-4d9d-a875-7ab58093f8f2.png)
![image](https://user-images.githubusercontent.com/106538473/175030643-974e7d34-9c0a-4a5c-aa19-94df739bc49a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
导入可以自定义，页面需要得改代码
