### ISSUE TITLE
VUE3最新版本

### ISSUE THREAD

**Issue by haoyanru2022** [jeecgboot/jeecg-boot#3820]
##### 问题描述：报表设计菜单打不开
菜单管理里面去查看了”报表设计“这个菜单，访问路径报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截图说明，F12看错误

**Comment by zhangdaiscott** [comment]
测试无问题，自查本地环境，依赖是否下载成功
