### ISSUE TITLE
打包部署上服务器后，验证码刷新不出来

### ISSUE THREAD

**Issue by xiamy-summer** [jeecgboot/jeecg-boot#3821]
##### 截图&代码：
<img width="1910" alt="image" src="https://user-images.githubusercontent.com/39183612/175241372-e8aa4568-00ec-4809-892c-795aaa203d6b.png">
<img width="777" alt="image" src="https://user-images.githubusercontent.com/39183612/175241458-c1357fdd-71d7-4172-8bec-64aab5f50f64.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
说明你nginx映射的有问题
