### ISSUE TITLE
中转HTTP请求，解决跨域问题bug

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#3826]
##### 版本号：

3.2.0

##### 问题描述：

中转HTTP请求，解决跨域问题：`/sys/common/transitRESTful`  中查询参数对象 `variables` 参数不为 null ，但是参数为空，导致 `RestUtil.request` 中  拼接 url 参数发生异常。

##### 截图&代码：

<img width="520" alt="image" src="https://user-images.githubusercontent.com/20742044/175770115-bdcedd0b-34ff-400c-8663-fa8199261717.png">

当 `variables` 不为 null 但是参数为空时，会报如下异常：

<img width="598" alt="image" src="https://user-images.githubusercontent.com/20742044/175770147-cd846a25-e8ff-41cb-8d56-9edb1ba8f068.png">

建议修改如下，增加参数不为空校验：

```java
// 拼接 url 参数
        if (variables != null && variables.size() != 0) {
            url += ("?" + asUrlVariables(variables));
        }
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
