### ISSUE TITLE
3.2.0 微服务 nacos 配置文件的问题

### ISSUE THREAD

**Issue by kerasking** [jeecgboot/jeecg-boot#3827]
##### 版本号：

3.2.0
##### 问题描述：
nacos 服务是正常的，启动gateway服务的时候报redis连不上，redis的配置挪到 jeecg,yaml 就可以启动服务，放在jeecg-dev.yaml里就读取不到redis配置的情况。
 jeecg.yaml jeecg-dev.yaml 这两个配置都在nacos里面配置了，启动的环境是dev模式
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
如何重现？我们使用都正常

**Comment by kerasking** [comment]
发现问题原因了，文件名称必须带 .yaml 后缀才能读取配置信息，比如 jeecg  jeecg-dev 这种命名只能读取jeecg，jeecg-dev就不能读取，但是jeecg.yaml jeecg-dev.yaml 文件名称这样的话都能读取了

![image](https://user-images.githubusercontent.com/998105/176068855-419452e8-388e-419c-8aa1-35286d5ad263.png)

**Comment by zhangdaiscott** [comment]
nacos基本知识不会吗

**Comment by kerasking** [comment]
回去看看
