### ISSUE TITLE
j-editable-table某字段设置statistics：true，使用setValues对该字段赋值，赋值后，没有进行统计

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3828]
##### 版本号：
2.4.6

##### 问题描述：
j-editable-table某字段设置statistics：true，使用setValues对该字段赋值，赋值后，没有进行统计

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44563730/175915012-115ca561-44eb-424a-9f74-347be2d045b4.png)
![image](https://user-images.githubusercontent.com/44563730/175915302-c0b7eb33-c61e-461b-9000-b81bac29c11d.png)
![image](https://user-images.githubusercontent.com/44563730/175915107-6affad14-9455-44c9-a8b9-4f0d9d96aefd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布。
