### ISSUE TITLE
AutoPOI如何导出带有数据的下拉选Excel模板 ？？？

### ISSUE THREAD

**Issue by bangcd999** [jeecgboot/jeecg-boot#3832]
##### 版本号：
3.0

##### 问题描述：
现在想要实现导出的Excel具有下拉列表的选项，不知是否可以实现？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/71172145/176079815-ad365609-fc9b-4bdd-ba66-36c3552067d8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持，得自己定义开发
