### ISSUE TITLE
cnpm run build  无法打包

### ISSUE THREAD

**Issue by Henryyanl** [jeecgboot/jeecg-boot#3834]
##### 版本号：
v1.3.0

##### 问题描述：
cnpm run build  无法打包

##### 截图&代码：
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/35865246/176142195-59627b2d-5bda-47ac-94ea-7c9b571662d6.png">

**Comment by zhangdaiscott** [comment]
删除依赖重试

**Comment by Henryyanl** [comment]
删过没用
