### ISSUE TITLE
开发文档中JVxeTable组件自定义工具栏配置案例与实际代码不一致问题

### ISSUE THREAD

**Issue by StevenQin97** [jeecgboot/jeecg-boot#3835]
##### 版本号：
3.2.0

##### 问题描述：

JVxeTable组件，toolbarConfig配置，开发文档中的格式与代码不一致，代码中的key为slot和btn，没有末尾的s，按照文档编写代码会报错

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23557046/176331655-19bc5797-9316-4d32-ac1e-6ad9ceeefb23.png)

![image](https://user-images.githubusercontent.com/23557046/176346843-2c2fe42f-1182-4b27-86b9-7c520136b288.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
此处是文档错误，已修复文档。
