### ISSUE TITLE
修改项目目录，在线表单功能404，如何用起来

### ISSUE THREAD

**Issue by ppepenpeng** [jeecgboot/jeecg-boot#3836]
##### 版本号：

3.2
##### 问题描述：

请问一下现在我改了项目的目录名称 原来是org.jeecg改成别的了，然后发现在线表单那用不了了。后来发现是spring扫描包没扫描到原来的org.jeecg，后来增加了这个包的扫描后，发现他又依赖org.jeecg下的其他类 但我已经改名了，有没有办法用起来
##### 截图&代码：
![image](https://user-images.githubusercontent.com/108248278/176345711-67f8f944-5528-4946-a5d4-be4ef4d18e51.png)
![image](https://user-images.githubusercontent.com/108248278/176345792-0b60ee10-0970-403c-8c50-37860ad974aa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
底层不要改
