### ISSUE TITLE
部门管理删除权限，会删除非本部门角色下的相关权限。

### ISSUE THREAD

**Issue by wlf36** [jeecgboot/jeecg-boot#3837]
##### 问题描述：
部门管理删除权限，会删除非本部门角色下的相关权限。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/12623898/176347272-913d3812-eee5-4849-8ff8-4ab4dc680e43.png)

是不是应该把roleIds传进去一起处理才正确

**Comment by zhangdaiscott** [comment]
操作配置截图
