### ISSUE TITLE
2.4.0版本，代码生成依赖jar包下载失败

### ISSUE THREAD

**Issue by youzhajun** [jeecgboot/jeecg-boot#3841]
##### 版本号：
2.4.0

##### 问题描述：

接手公司旧项目，jeecgboot2.4.0版本代码生成器依赖下载失败。maven仓库也找不到这个版本。请问是换了地址还是什么原因？能提供下jar包吗？
<codegenerate.version>1.2.5</codegenerate.version>

<dependency>
	<groupId>org.jeecgframework.boot</groupId>
	<artifactId>codegenerate</artifactId>
	<version>${codegenerate.version}</version>
</dependency>

##### 截图&代码：
![image](https://user-images.githubusercontent.com/84554002/176659108-4f7e37db-c0a2-4d67-8a7c-417196825543.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043876
