### ISSUE TITLE
Online对接积木报表后不显示打印按钮

### ISSUE THREAD

**Issue by LancCJ** [jeecgboot/jeecg-boot#3843]
##### 版本号：

3.2
##### 问题描述：
在该版本online表单 配置积木报表，并且配置地址，在 功能测试 更多不出现打印按钮，什么情况是改了么，假如没有我改如何自己添加

##### 截图&代码：

<img width="910" alt="image" src="https://user-images.githubusercontent.com/2968042/176799512-2ad891e8-887f-4585-af32-a327c7a408e8.png">
<img width="612" alt="image" src="https://user-images.githubusercontent.com/2968042/176799628-cabd08de-1e3e-40f0-b0fd-e4cfd365fadc.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
vue3 还是vue2

**Comment by LancCJ** [comment]
> vue3 还是vue2

vue2的

**Comment by zhangdaiscott** [comment]
jl
