### ISSUE TITLE
初始密码

### ISSUE THREAD

**Issue by baboooooo** [jeecgboot/jeecg-boot#3844]
##### 问题描述：SQL中初始化用户名密码.密码解密.
这几个用户密码是多少呢,解密需要创建时候的密码.

##### 截图&代码：
![image](https://user-images.githubusercontent.com/37157121/176806231-47a4023e-76be-4f2c-830c-26ec93bf3fb0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持解密，可以通过页面更改密码

**Comment by baboooooo** [comment]
> 不支持解密，可以通过页面更改密码
这几个账户的初始密码可以告诉一下嘛...

**Comment by baboooooo** [comment]
> 不支持解密，可以通过页面更改密码

目前系统不能更新需要密码登录才行
