### ISSUE TITLE
qartz的mysql版的表都是小写的，Linux默认是区分大小写的，建议修改为大写表名

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#3845]
##### 版本号：
V3.2.0

##### 问题描述：
qartz的mysql版的表都是小写的，Linux默认是区分大小写的，建议修改为大写表名。
qartz偏好大写的表名，建议jeecg默认的为大写，否则得配置Linux版的MySQL不区分大小写。

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写
