### ISSUE TITLE
部署过程遇到的问题

### ISSUE THREAD

**Issue by OgAZC** [jeecgboot/jeecg-boot#3849]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/73862964/177006655-3363e9d7-2d05-4c67-b14f-8ffd875d5ff0.png)
org.hibernate:hibernate-re:pom:2.3.07 was not found in http://maven.aliyun.com/nexus/content/groups/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of nexus-aliyun has elapsed or updates are forced

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
依赖没下载成功，maven刷新
