### ISSUE TITLE
报表设计器 工具栏无法隐藏

### ISSUE THREAD

**Issue by JxlWen** [jeecgboot/jeecg-boot#3851]
##### 版本号：
3.1.0

##### 问题描述：
大屏报表参数设置不生效，viewToolbar 参数不生效，其他参数可以生效，前段是vue 3，1.2.0版本

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50694382/177075750-7bc27928-27c1-49c7-b0c1-05de54e8561b.png)
![image](https://user-images.githubusercontent.com/50694382/177075804-613d38d7-c555-4057-84b6-044da547fb72.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by lvdandan16** [comment]
收录 ws

**Comment by xingyuehaiqing** [comment]
你是买的商业版吗，大屏不是不开源的吗

**Comment by 1298191366** [comment]
这个动能已经去除了。如果想控制可以在设计页面
