### ISSUE TITLE
附表问题控件类型问题

### ISSUE THREAD

**Issue by github944674100** [jeecgboot/jeecg-boot#3854]
##### 版本号：
当前最新版本： 3.2.0（发布日期：2022-04-25）

##### 问题描述：
附表控件类型为popup必填时未选择值提交表单会报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/72907009/177351821-7a976e11-6a0e-414e-8a1b-ea1afd9214d7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
该报错不影响正常使用，问题已优化，控制台不再报错，下版本发布。
