### ISSUE TITLE
j-vxe-table 下拉框options 属性无效

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3855]
##### 版本号：
3.0

##### 问题描述：
j-vxe-table 下拉框 options 属性  ， 怎样把后台查询的数据赋给options 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44563730/177358274-bca9dd20-fe80-43ba-821a-1a1c66a68e35.png)
![image](https://user-images.githubusercontent.com/44563730/177358326-590b3cbd-88a3-4ae2-9501-810e4b5a3451.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
把`columns`改成计算属性，或者用`this.columns[index].options = []`的方式更改

**Comment by yzmking** [comment]
好的，我试试

**Comment by xiaohuang-123** [comment]
解决了吗

**Comment by yzmking** [comment]
好像用上面那条回复可以，你试试


寂寞の快乐
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月16日(星期一) 下午4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] j-vxe-table 下拉框options 属性无效 (Issue #3855)





 
解决了吗
