### ISSUE TITLE
JLock   MULTIPLE

### ISSUE THREAD

**Issue by fulintang** [jeecgboot/jeecg-boot#3856]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/44566955/177503711-74e8db8f-df4a-4dbc-a448-9309eaab3a7f.png)

请问我是像这样写嘛，还是需要怎么传入参数呢？
小白不是太懂哦……

**Comment by accpman** [comment]
//lockKey支持spel表达式
 @JLock(lockKey= "redis-lock") 
 @JLock(lockKey="#user.name")
 @JLock(lockKey ={"#user.name","#user.id"})
https://www.kancloud.cn/zhangdaiscott/jeecg-boot/2043896

**Comment by fulintang** [comment]
答非所问，浮躁的人，审题啊，我传入的是个ID的List，要把这个List写成SPEL

**Comment by fulintang** [comment]
> //lockKey支持spel表达式 @jlock(lockKey= "redis-lock") @jlock(lockKey="#user.name") @jlock(lockKey ={"#user.name","#user.id"}) https://www.kancloud.cn/zhangdaiscott/jeecg-boot/2043896

答非所问

**Comment by fulintang** [comment]
估计得我自己研究研究了，参数是个List怎么把参数通过SPEL表达式传进去，我来学学Spring的SPEL解析然后把这个JLock重构了吧，现在的JLock传参不太优惠券，参考下SpringCache的传参然后改改吧
