### ISSUE TITLE
3.2.0版本菜单缺失

### ISSUE THREAD

**Issue by lkyting** [jeecgboot/jeecg-boot#3865]
##### 版本号：

jeecg-boot  3.2.0 版本

##### 问题描述：
本地运行的项目 admin角色已勾选所有菜单 
演示环境很多有的菜单 拉下来的代码运行都没有这些菜单  例如： Online图表配置菜单 本地没有

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
非开源功能
