### ISSUE TITLE
升级Vue2.7，项目启动有问题

### ISSUE THREAD

**Issue by Jony1943** [jeecgboot/jeecg-boot#3866]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/19758010/177948799-c5c1c71a-e4e4-4eb8-b3b1-5eced16febbc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己升级，得自己分析

**Comment by hqb72** [comment]
我没升级, 也有这个问题呢

**Comment by hqb72** [comment]
@zhangdaiscott
