### ISSUE TITLE
切换成postgresql好多字段报不存在

### ISSUE THREAD

**Issue by huashengmingtian** [jeecgboot/jeecg-boot#3869]
##### 版本号：
3.2.0

##### 问题描述：
切换成postgresql后报字段不存在

##### 截图&代码：

![QQ截图20220711153045](https://user-images.githubusercontent.com/20311049/178214640-bdb04bd5-9762-4c70-bcaf-37c98519ee65.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by huashengmingtian** [comment]
官方能否提供一个postgresql版本的脚本文件，这样搭建起来会轻松很多

**Comment by zhangdaiscott** [comment]
是你转的有问题

**Comment by huashengmingtian** [comment]
那你们能提供个转换的方法不？怎么就给问题关闭了呢，回答什么了。postgresql对大小写敏感你们不知道？另外一些布尔值的字段postgresql也有问题，需要改字段类型，甚至需要改mapper文件

**Comment by hejiahuichengxuyuan** [comment]
怎么给关了问题？？？

**Comment by huashengmingtian** [comment]
这就是他们处理问题的态度，没办法

**Comment by huashengmingtian** [comment]
> 怎么给关了问题？？？

这就是他们处理问题的态度，没办法
