### ISSUE TITLE
redisson报错

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3876]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/178469106-2559d450-7583-47fd-8d2f-99334c31d766.png)
![image](https://user-images.githubusercontent.com/50698315/178469130-a4adc66e-f07d-4bbe-a76c-c2bbc4fc173a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
配置不对吧

**Comment by yangkui001** [comment]
> 配置不对吧
配置如图所示，我用客户端redis工具是可以连接的，我有个想法，如果我把enabled: true更改为enabled: false是否可以避免上面的那些报错
![image](https://user-images.githubusercontent.com/50698315/178482222-86090b58-de3c-46d4-a841-867e161655e5.png)
