### ISSUE TITLE
生成代码，添加菜单打不开

### ISSUE THREAD

**Issue by wangwp1990** [jeecgboot/jeecg-boot#3881]
##### 版本号：
3.2.0

##### 问题描述：
online表单开发->生成代码，添加菜单打不开，跳到了404页面。控制台不报任何错误；admin角色已授权；前后端已重启；
访问地址http://localhost:3000/test/TestDanbiaoList

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44253878/178663123-149dfa71-7ab4-4353-9779-dd4563c6c487.png)
![image](https://user-images.githubusercontent.com/44253878/178663676-8b2be2d5-1faf-42a2-82d2-54cd3f118f59.png)

**Comment by wangwp1990** [comment]
上级菜单需要这么设置
![C3JBH3V}I ~D34YG0~ZFQBS](https://user-images.githubusercontent.com/44253878/178675408-1fb97f98-516c-4fca-b446-2fc0518d2d48.png)

**Comment by c0609003** [comment]
我也碰到这问题，咋解决的？

**Comment by zhangdaiscott** [comment]
说明配置的菜单不对
