### ISSUE TITLE
Online表单对接积木报表

### ISSUE THREAD

**Issue by wangshiwen226** [jeecgboot/jeecg-boot#3887]
##### 版本号：
3.0

##### 问题描述：
Online表单对接积木报表时，使用API数据集，通过解析API时，提示【 数据为空，报表字段明细会被清空！
 [】，但是我在Online表单中新增的有数据，通过使用手册中的]( {{ domainURL }}/online/cgform/api/data/{tableName}/queryById?id=${id}&token=${token}&mock=true)来实现，将{tableName}改成了自己Online表单中的表名

##### 截图&代码：
![C`ZNS5UQA(VQIY HSGDT03O](https://user-images.githubusercontent.com/51777965/178928607-ce6ae027-8930-44c8-92b8-8f282d327297.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
下个版本优化体验
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布
