### ISSUE TITLE
路由以 "/map" 开头会忽略鉴权

### ISSUE THREAD

**Issue by iarray** [jeecgboot/jeecg-boot#3888]
##### 版本号：
3.2.0

##### 问题描述：
路由以 "/map" 开头会忽略鉴权， 确认没有修改ShiroConfig

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/178939456-0cb3a723-dd16-42e6-955b-97f92ff0f245.png)
