### ISSUE TITLE
CAS单点登出(注销)，jeecg-boot无法正常登出问题  

### ISSUE THREAD

**Issue by beAnger** [jeecgboot/jeecg-boot#3890]
##### 版本号：
2022-07-14 master

##### 问题描述：
现在有服务A(普通springboot)、服务B(Jeecg-boot)、服务C(CAS官方demo)接入了CAS，分别在两个服务进行了登录，在服务A手动登出的时候，服务C自动登出，服务B没有自动进行登出

##### 截图&代码：
[img](https://user-images.githubusercontent.com/68948300/178964155-4557f365-8a7b-4dbb-abe5-5ec9575b00c5.gif)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by powanjuanshu** [comment]
现在是前端将ST传入，后端验证，暂时做不到单点登出吧？
