### ISSUE TITLE
部门管理

### ISSUE THREAD

**Issue by NotKnow-UserName** [jeecgboot/jeecg-boot#3891]
##### 版本号：

 v1.22.17
##### 问题描述：

部门管理本地环境下可以显示全，线上环境无法显示全
##### 截图&代码：

<img width="789" alt="image" src="https://user-images.githubusercontent.com/33274017/179058830-51a765c7-8feb-42be-9efd-6623aabc0e7e.png">

<img width="658" alt="image" src="https://user-images.githubusercontent.com/33274017/179058753-85a849d0-fd46-4efa-b0ae-59a9eecd316f.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
这个你可以多加点日志，得自己分析
