### ISSUE TITLE
路由菜单及api配置

### ISSUE THREAD

**Issue by panghu19** [jeecgboot/jeecg-boot#3892]
##### 版本号：
1.3.0

##### 问题描述：
没有根据你们的项目启动进行intel idea配置数据库等，跑的是本地服务器，能登录，不过登录进去只能看到首页，我是前端。我现在想的是在代码层面，写出路由菜单，我找不到在哪去写，这个路由菜单设置的接口在哪，是/sys/permission/getUserPermissionByToken这个吗？以及其他不需要的路由菜单如何进行删除，我是需要叫后端把这个接口写完整给我替换api之后才能进行路由的更改还是？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/94041394/179139635-67faf781-cce8-42bf-b134-5a1be7528016.png)
![image](https://user-images.githubusercontent.com/94041394/179140201-edefe929-d166-4d4d-888e-c72e2b047159.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
/sys/permission/getUserPermissionByToken
