### ISSUE TITLE
j-search-select 如何默认选中第一项

### ISSUE THREAD

**Issue by Henryyanl** [jeecgboot/jeecg-boot#3893]
##### 版本号：
vue3

##### 问题描述：
j-search-select 如何默认选中第一项

##### 截图&代码：
<img width="589" alt="image" src="https://user-images.githubusercontent.com/35865246/179218415-14589c4e-bbd9-408c-9e90-077ae8601c48.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
可以设置默认值，默认第一个没这逻辑，可以自己实现
