### ISSUE TITLE
是否可以根据字典进行映射后，在分组

### ISSUE THREAD

**Issue by coder-wangfugui** [jeecgboot/jeecg-boot#3894]
##### 版本号：
  <version>1.4.2</version>

##### 问题描述：

字典值存在多对一的映射关系，映射后无法分组（就是无法合并单元格），可以实现吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
什么意思

**Comment by coder-wangfugui** [comment]
一个表原来是：
|姓名|  籍贯|
|--|--|
|张三|101|
|李四|102|

字典值里：名称：北京，数据值：101；名称：北京，数据值：102

根据字典替换后
|姓名|  籍贯|
|--|--|
|张三|北京|
|李四|北京|


这两个北京可以合并吗

**Comment by zhangdaiscott** [comment]
这个是你表格的实现，默认没这功能

**Comment by coder-wangfugui** [comment]
确实是，谢谢回复
