### ISSUE TITLE
shiro remember me的漏洞问题

### ISSUE THREAD

**Issue by CenMinghao** [jeecgboot/jeecg-boot#3895]
##### 版本号：
2.4.3

##### 问题描述：
①remember是不是没有使用？
②如何禁用shiro的rememberMe功能，既cookie里不出现rememberMe=deleteMe

##### 截图&代码：

![image](https://user-images.githubusercontent.com/29631645/179343481-2a147742-226c-4179-9f60-9827ff235a1e.png)

**Comment by zhangdaiscott** [comment]
什么漏洞

**Comment by CenMinghao** [comment]
Shiro remeberMe反序列化漏洞，以前的了，主要是想确认一下问题描述里面的第一点和先了解怎么处理第二点

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
①项目没有使用shiro的remember功能

**Comment by CenMinghao** [comment]
明白




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月9日(星期天) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] shiro remember me的漏洞问题 (Issue #3895)





 
①项目没有使用shiro的remember功能

**Comment by GitACDreamer** [comment]
@zhangdaiscott 您好，我根据shiro提供的资料，做了rememberMe,但是在  
```
Subject userSubject = SecurityUtils.getSubject();
UsernamePasswordToken token = new UsernamePasswordToken(username, password, isRemember);
userSubject.login(token) ;
```
这句话调用会报错
```
Realm [org.jeecg.config.shiro.ShiroRealm@57fa5b31] does not support authentication token [org.apache.shiro.authc.UsernamePasswordToken - admin, rememberMe=true]. Please ensure that the appropriate Realm implementation is configured correctly or that the realm accepts AuthenticationTokens of this type.
```
错误。
我看jeectboot代码里已经实现了`JwtToken`,继承`AuthenticationToken`，这个需要修改吗？
