### ISSUE TITLE
xxljob 被 shiro 拦截

### ISSUE THREAD

**Issue by tzou24** [jeecgboot/jeecg-boot#3897]
##### 版本号：
jeecg-boot 3.0.0

##### 问题描述：
jeecg-cloud-xxljob 配置自定义模块，测试执行任务。被 shiro 拦截。
请指点下方向，优雅的解决这个问题，谢谢。

##### 截图&代码：
org.jeecg.config.shiro.ShiroRealm        : ————————身份认证失败——————————IP地址:  127.0.0.1

![image](https://user-images.githubusercontent.com/19379654/179652628-2bdc62d1-5f57-4a6a-8095-f92e6d0b16b3.png)

![image](https://user-images.githubusercontent.com/19379654/179652819-f621071d-63de-4bd0-a2da-9ac33f7e1e02.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2725212

**Comment by tzou24** [comment]
文档中是在任务执行方法内生成token，而我现在连 demoJobHandler 方法也不能进入，是需要修改哪一块呢？
