### ISSUE TITLE
Online表单开发设置了校验必填，但是生成的代码，导入EXCEL的时候没有必填校验

### ISSUE THREAD

**Issue by 1341497922** [jeecgboot/jeecg-boot#3899]
版本号：3.2.0
问题描述：Online表单开发设置了校验必填，但是生成的代码，导入EXCEL的时候没有必填校验
截图&代码：
![image](https://user-images.githubusercontent.com/109588053/179718715-79eecdbd-a5ef-4428-b04a-4a57af5b4f1a.png)
![image](https://user-images.githubusercontent.com/109588053/179718921-0855fe71-3b5d-4147-8876-b9a8deb19852.png)

![image](https://user-images.githubusercontent.com/109588053/179718850-b7f67649-61c2-4910-b032-20029d6d67bc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
生成后，手工改代码
