### ISSUE TITLE
在线按钮权限不起作用

### ISSUE THREAD

**Issue by IsMrChen** [jeecgboot/jeecg-boot#3902]
##### 版本号：

3.2.0
##### 问题描述：
想为在线开发页面按钮增加按钮权限，不起作用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/53907291/179914727-b7a60378-10e3-424c-904c-91b83b10971c.png)

![image](https://user-images.githubusercontent.com/53907291/179914800-bda804d0-c884-4a48-9878-91371eceaf7d.png)

![image](https://user-images.githubusercontent.com/53907291/179915003-9c221efb-9d72-47b4-bcd5-e1dc4811d98c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044092
