### ISSUE TITLE
自定义POP弹出层，表格主子表样式问题

### ISSUE THREAD

**Issue by LancCJ** [jeecgboot/jeecg-boot#3904]
##### 版本号：
3.2.0

##### 问题描述：
自定义做了个POP弹出层，表格是内嵌风格，点击展开的时候样式出现错误，大概啥问题

我都是直接复制CV大法的

##### 截图&代码：
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/2968042/180122889-464e8d09-11aa-450c-81e5-9b0bf9c6c47d.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
自己写的，我们处理不了

**Comment by LancCJ** [comment]
> 自己写的，我们处理不了

好的 没事，已经解决
