### ISSUE TITLE
SQL注入漏洞

### ISSUE THREAD

**Issue by iarray** [jeecgboot/jeecg-boot#3905]
##### 版本号：
3.2.0

##### 问题描述：
SQL注入漏洞

##### 截图&代码：
SysUserServiceImpl.java
![1658454399115](https://user-images.githubusercontent.com/5656171/180343935-31e30d46-e511-4e17-8c25-16ee12fe8d8d.png)

以及SysDepartPermissionController.java
![1658454355553](https://user-images.githubusercontent.com/5656171/180343841-4a39d60e-14ba-49e2-8dde-a138898b67f4.png)

和SysDictMapper.xml
![1658454315846](https://user-images.githubusercontent.com/5656171/180343760-54ae7499-1a54-4b20-aaec-83e95d699e36.png)

注入攻击模拟:
/api/sys/sysDepartPermission/queryTreeListForDeptRole?departId=' or depart_id<>'&_t=1658451902793

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
新版已经处理
