### ISSUE TITLE
逻辑判断有问题

### ISSUE THREAD

**Issue by iarray** [jeecgboot/jeecg-boot#3906]
##### 版本号：
3.2.0

##### 问题描述：
IF逻辑判断有问题

##### 截图&代码：
![1658457232635](https://user-images.githubusercontent.com/5656171/180350218-8c1648ad-8e51-403c-bcb1-fe9bed81ee67.png)

这里的"或"应该是"与"

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
修复
