### ISSUE TITLE
导入代码格式化模板文件网盘链接失效了

### ISSUE THREAD

**Issue by lifengtour1** [jeecgboot/jeecg-boot#3909]
##### 版本号：
3.30

##### 问题描述：

http://doc.jeecg.com/2214350
导入代码格式化模板文件
给的那个网盘的文件找不到了

##### 截图&代码：

![image](https://user-images.githubusercontent.com/39182805/180409594-d7b6a084-d27b-41ef-b107-27896bedfc7b.png)

![image](https://user-images.githubusercontent.com/39182805/180409659-a5d1d62b-3ebb-44d4-9071-e5eb266b5a09.png)

https://pan.baidu.com/s/1QvMhHyC01qfO-yuS2xJMxw
这个地址

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
链接：https://pan.baidu.com/s/1czSCNAhEjRqA5jSK8wDL3w?pwd=dyyc 
提取码：dyyc
