### ISSUE TITLE
新版本登录报错

### ISSUE THREAD

**Issue by AlphaIkaross** [jeecgboot/jeecg-boot#3910]
##### 截图&代码：
![错误图片](https://user-images.githubusercontent.com/98371306/180411290-117263ad-692d-4d00-b4fc-d3bb7104382c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
F12看看都哪里报错了，前台还有后台
