### ISSUE TITLE
使用 j-select-depart设置的部门信息，在代码生成模式导出excel文档时，不能导出为部门名称

### ISSUE THREAD

**Issue by gaojianpin** [jeecgboot/jeecg-boot#3912]
##### 版本号：
3.1.0

##### 问题描述：
使用 j-select-depart设置的部门信息，使用代码生成模式导出excel文档时，不能导出为部门名称，但使用online方式时导出的可以

##### 截图&代码：

![image](https://user-images.githubusercontent.com/109848136/180597344-8fcb98e7-45cd-4b68-af88-b58819ed2a17.png)
![image](https://user-images.githubusercontent.com/109848136/180597372-c34f575a-e009-4be8-993b-413803399624.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
导出的地方，手工翻译下
或者配置下字典注解
