### ISSUE TITLE
 v3.2.0升级至 v3.3.0websocket连接校验失败，token不能为空

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3913]
##### 版本号：
v3.3.0

##### 问题描述：
升级后出现的问题，v3.2.0少了Sec-WebSocket-Protocol的请求头
 websocket连接校验失败，token不能为空!，token:null
websocket连接 Token安全校验，Path = /jeecg-boot/websocket/e9ca23d68d884d4ebb19d07889727dae，token:null
##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/180600261-cb65ccf9-e91d-4ece-b51f-234fdff808d5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 3509282792** [comment]
没更新到位，找到原因了

**Comment by yangkui001** [comment]
我直接拉的最新版本还是有这个异常啊，怎么解决这个问题喔
