### ISSUE TITLE
开发模式下面在浏览器上面前端打不了断点，调试不了代码

### ISSUE THREAD

**Issue by caiyixin** [jeecgboot/jeecg-boot#3914]
##### 版本号：
3.3.0

##### 问题描述：
在浏览器上面前端打不了断点，调试不了代码！！还没有解决！！！  之前提了问题被关闭了是啥原因？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35724941/180708546-18dc2108-360a-408d-a3a8-8e46b0c0a137.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
调试跟代码没关系

**Comment by caiyixin** [comment]
> 在浏览器上面前端打不了断点，调试不了代码！！还没有解决！！！ 之前提了问题被关闭了是啥原因？



> 调试跟代码没关系
我知道是跟代码没关系  但是如果我自己写的代码出错   也要调试呀  总不能让我去console.log()去打印定位哪里出错了吧  之前我自己写vue3代码和vue2都可以断点调试 为啥这个框架不能断点  到时候自己的代码出了bug  bug定位不是都很麻烦  能不能有什么解决方法
