### ISSUE TITLE
JEditableTable  disabledRows使用问题

### ISSUE THREAD

**Issue by pwyGouxiong** [jeecgboot/jeecg-boot#3916]
##### 截图&代码：
![Z}C16@GB(AL9I 7@8U40P1W](https://user-images.githubusercontent.com/26954826/180712204-41bf997b-7600-4bb2-987f-8dd2f4b87b21.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by pwyGouxiong** [comment]
已解决

**Comment by StevenQin97** [comment]
> 已解决

**Comment by StevenQin97** [comment]
老哥如何解决的，我一直查找到源代码，发现此属性的处理逻辑是被注释掉的

**Comment by pwyGouxiong** [comment]
> 老哥如何解决的，我一直查找到源代码，发现此属性的处理逻辑是被注释掉的

> 

不好意思，刚看见你的问题。
html部分添加禁用属性：
![image](https://user-images.githubusercontent.com/26954826/191451327-eef3b8f7-3241-472f-9c2b-159ea790fcd8.png)
data里定义一下：
![image](https://user-images.githubusercontent.com/26954826/191451477-04ea780b-a687-4979-ab35-611343513e3f.png)
然后this.disabledRows={ key: value },意思就是你希望在columns中的哪个key在什么值的时候禁用掉
因为业务需求（我们是切换选项会重置掉这个附表的数据），所以在JEditableTable.vue里也做了修改，在watch监听里增加了对disabledRows的监听：
disabledRows: {
        immediate: true,
        handler: function (newValue) {
            let disabledRowIds = []
            this.dataSource.forEach((data, newValueIndex) => {
              // 不能直接更改数据源的id
              let dataId = data.id
              // 判断源数据是否带有id
              if (dataId == null || dataId === '') {
                dataId = this.generateId(this.rows)
                
              } else if(!this.hasCaseId(dataId)) {
                dataId = this.caseId + dataId
                
              }
              let application = data.application
              if(application == null || application === '' || application==undefined){
                application = ""
              }else{
                application = application
              }
              let row = { id: dataId,application:application }
              let disabled = false
              this.columns.forEach(column => {
                for (let columnKey in newValue) {
                  // 判断是否有该属性
                  if (newValue.hasOwnProperty(columnKey) && data.hasOwnProperty(columnKey)) {
                    if (disabled !== true) {
                      let temp = newValue[columnKey]
                      // 禁用规则可以是一个数组
                      if (temp instanceof Array) {
                        disabled = temp.includes(data[columnKey])
                      } else {
                        disabled = (temp === data[columnKey])
                      }
                      if (disabled) {
                        disabledRowIds.push(row.id)
                      }
                    }
                  }
                }
              })
            })
            this.disabledRowIds = disabledRowIds
        }
      },

以上代码中出现的application这类词汇为业务需求下自己对JEditableTable.vue文件做出的改动，供你参考关于disabledRows的部分，思路还是看JEditableTable.vue文件中disabledRowIds出现的地方，分析源码，大概就能理解了
