### ISSUE TITLE
autopoi 模板导出横向遍历不起作用

### ISSUE THREAD

**Issue by qh2332449176** [jeecgboot/jeecg-boot#3918]
版本号：1.3.6 官方最新版本
org.jeecgframework autopoi-web 1.3.6 commons-codec commons-codec
问题描述：
#fe: | 横向遍历失效，无数据

截图&代码：

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
经测试未发现问题，请提供一下你的遍历模板和数据
