### ISSUE TITLE
微服务在nacos里配置独立数据呀报错

### ISSUE THREAD

**Issue by xiamy-summer** [jeecgboot/jeecg-boot#3922]
##### 版本号：
3.1.0

##### 问题描述：
使用微服务在nacos里新的模块配置独立数据源报错。

##### 截图&代码：
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/39183612/180972647-811f833e-1fdc-404e-90c9-a9f5be5b5030.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
截图说明，如何配置

**Comment by xiamy-summer** [comment]
已经搞定了。😁
