### ISSUE TITLE
tab多个标签时，右键点击标签页的刷新导致表单填写的数据被刷新

### ISSUE THREAD

**Issue by xuhongshuai** [jeecgboot/jeecg-boot#3931]
##### 截图&代码：
![292dfff46a79efb17355b9ac11ac6d6](https://user-images.githubusercontent.com/41218717/181470472-fba680a9-e324-4346-8905-7fd6bc77e663.png)

![f8268b702923de2ee557f81dc910bc3](https://user-images.githubusercontent.com/41218717/181470565-f4e6919d-17f8-482d-a95f-3bc5d5ac01d9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
菜单设置路由缓存

**Comment by xuhongshuai** [comment]
菜单是设置了路由缓存，切换标签不会导致表单数据丢失，但是在其他标签页右键刷新，会导致其他页面表单填充的数据被重置

**Comment by xuhongshuai** [comment]
能不能设置标签页右键菜单的刷新只刷新当前页面，现在是把其他页面的缓存也刷新了

**Comment by zhangdaiscott** [comment]
哪得自己改改刷新逻辑了。vue2不做深入修改了
