### ISSUE TITLE
微服务模式下online怎么切换到其他数据库

### ISSUE THREAD

**Issue by xiamy-summer** [jeecgboot/jeecg-boot#3934]
##### 版本号：
3.1.0

##### 问题描述：
jeecgboot从单体切换成微服务后并且每个模块都有独立的数据，online怎么切换到其他数据库进行在线开发？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
不支持
