### ISSUE TITLE
多级缓存问题

### ISSUE THREAD

**Issue by yellowseasky** [jeecgboot/jeecg-boot#3935]
##### 版本号：
2.4.6

##### 问题描述：
菜单栏超过三级时配置了路由缓存无效果

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
是存在这个bug

**Comment by tujindong** [comment]
@zhangdaiscott 这个缺陷vue2修复了吗
