### ISSUE TITLE
maven依赖 jeecg-boot-parent:pom:3.3.0 找不到

### ISSUE THREAD

**Issue by liuhongtian** [jeecgboot/jeecg-boot#3936]
##### 版本号：

3.3.0

##### 问题描述：

构建后端代码时，报：jeecg-boot-parent:pom:3.3.0 找不到。（阿里云的Maven仓库里只能找到2.2.3版本。）

##### 截图&代码：

[ERROR] Failed to execute goal on project jeecg-cloud-gateway: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-cloud-gateway:jar:3.3.0: Failed to collect dependencies at org.jeecgframework.boot:jeecg-boot-starter-cloud:jar:3.3.0: Failed to read artifact descriptor for org.jeecgframework.boot:jeecg-boot-starter-cloud:jar:3.3.0: org.jeecgframework.boot:jeecg-boot-parent:pom:3.3.0 was not found in https://maven.aliyun.com/repository/public during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of aliyun has elapsed or updates are forced -> [Help 1]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/183046089-96a27d75-a766-4090-848c-27992652ea90.png)
