### ISSUE TITLE
微服务-新的微服务想要单独nacos-yaml配置

### ISSUE THREAD

**Issue by chenshili155** [jeecgboot/jeecg-boot#3940]
##### 版本号：
2.4.2

##### 问题描述：
各种报错说找不到配置（过滤器，swagger，mail配置），求教如何解决这个问题？只能克隆jeecg-dev过来？问题是还有一个jeecg.yaml，两个合在一起就很麻烦

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41871181/182572389-3ed662c0-a9bf-42d8-b8fc-da581bd7fad2.png)
![image](https://user-images.githubusercontent.com/41871181/182572483-154e5b31-7e31-4421-bcbe-a18f0de27353.png)

**Comment by zhangdaiscott** [comment]
下个版本马上发布，已经重构，采用最新import模式

**Comment by chenshili155** [comment]
我自己解决了昨天，太难了，版本不敢往上升，怕出事

**Comment by zhangdaiscott** [comment]
最新版已经发布了，可以简单实现你的需求
https://my.oschina.net/jeecg/blog/5563250
