### ISSUE TITLE
online表单生成里面，列设置没有选项

### ISSUE THREAD

**Issue by dnangelxueaoran** [jeecgboot/jeecg-boot#3941]
##### 版本号：
3.3.0

##### 问题描述：
 online表单生成里面，列设置没有选项，功能测试及配置菜单之后都是这种情况

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布

**Comment by dnangelxueaoran** [comment]
谢谢
