### ISSUE TITLE
如何支持https访问

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3942]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by yangkui001** [comment]
![image](https://user-images.githubusercontent.com/50698315/182984176-4f316e80-c322-4eb0-975d-96b74ee31a33.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/183045869-282b7ed2-44d0-42f9-98eb-1009ca3dede1.png)

**Comment by yangkui001** [comment]
在后端配置文件application.yml，需要添加支持https的代码吗？目前报错如下所示：
![image](https://user-images.githubusercontent.com/50698315/183048019-213fa91f-d86c-41fb-b030-dd4c6c36f9d6.png)

**Comment by yangkui001** [comment]
在后端配置文件application.yml，需要添加支持https的代码吗？目前报错如下所示：
![image](https://user-images.githubusercontent.com/50698315/183048400-1ff4a939-7aaa-4ef8-8819-1a6eb3c2d5fc.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/183048542-11d0c1c2-432d-43a5-8821-6a54d937e7d4.png)

改成https

**Comment by yangkui001** [comment]
在后端配置文件application.yml，需要添加支持https的代码吗？目前报错如下所示：
![image](https://user-images.githubusercontent.com/50698315/183048922-13d1c49b-dc27-4b42-a8a9-f9e61f78a983.png)

**Comment by yangkui001** [comment]
在后端配置文件application.yml，需要添加支持https的代码吗？目前报错如下所示：
![image](https://user-images.githubusercontent.com/50698315/183049409-1a8e2363-779e-4505-8c30-956f1264f815.png)

**Comment by GitACDreamer** [comment]
@zhangdaiscott 根据官网配置 http://vue3.jeecg.com/2503893#_nginx__232，不使用https可以用，使用了https, 运行 https://domain 一直会404错误

**Comment by zhangdaiscott** [comment]
这个很简单，自己百度也可以，平台没限制
