### ISSUE TITLE
SystemApiController类名改了大小写导致git有历史的SystemAPIController

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3944]
##### 版本号：
 v3.4.0

##### 问题描述：
SystemApiController类名改了大小写导致git有历史的SystemAPIController

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/183320537-2cd251f2-9b0d-4616-be64-d3fb38f287ad.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
设置git区分小写
