### ISSUE TITLE
请问新版jeecgboot对外接口用什么啊

### ISSUE THREAD

**Issue by mxz112233445566778899** [jeecgboot/jeecg-boot#3945]
##### 版本号：
3.3

##### 问题描述：
我看老版本有集成webservice，新版本好像没了，系统推荐用什么对外发布接口啊，有相关文档吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
http

**Comment by mxz112233445566778899** [comment]
> http

多谢 用您这个平台使用http接口的标准范例吗，怕自己写不标准
