### ISSUE TITLE
框架体验感

### ISSUE THREAD

**Issue by qiqi707** [jeecgboot/jeecg-boot#3948]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/68047089/183382825-eb140d54-dcf6-4872-93e2-e9029b178cf6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by Haowensheng** [comment]
可以设置的 这样设置就可以吸顶了
![image](https://user-images.githubusercontent.com/39179126/186060271-d7fb9068-b6fd-4f3e-b9b0-81e6fb420577.png)

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
默认是有吸顶效果的，侧边菜单栏也是固定的。

![image](https://user-images.githubusercontent.com/34293221/194757558-fe954817-cd96-492b-ad14-5450776d52a1.png)
