### ISSUE TITLE
如何在后端项目实现接口支持ssl

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3949]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/183387788-66b92838-d966-48bf-9217-1cc22bb03904.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/4494367
https://my.oschina.net/jeecg/blog/4988863
