### ISSUE TITLE
Excel 文档异常http://doc.autopoi.jeecg.com

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#3951]
##### 版本号：
Excel 文档异常http://doc.autopoi.jeecg.com

##### 问题描述：

Excel 文档异常http://doc.autopoi.jeecg.com
##### 截图&代码：

Excel 文档异常http://doc.autopoi.jeecg.com

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  
Excel 文档异常http://doc.autopoi.jeecg.com

**Comment by zhangdaiscott** [comment]
先临时用这个地址

https://www.kancloud.cn/zhangdaiscott/autopoi/content/%E5%89%8D%E4%BC%A0.md
