### ISSUE TITLE
新建用户，新用户首次登录访问首页会404，点击返回首页，可以正常访问

### ISSUE THREAD

**Issue by zlyylzmax** [jeecgboot/jeecg-boot#3953]
##### 版本号：
3.1.0

##### 问题描述：
新建用户，新用户首次登录访问首页会404，点击返回首页，可以正常访问。浏览F12看提示是首页没有权限跳转到404页面的问题

##### 截图&代码：
新建用户，新用户首次登录访问首页会404

![图片](https://user-images.githubusercontent.com/94462465/183561327-59e29b47-6e7e-4930-8cdd-b194244325f9.png)

点击返回首页，可以正常进入访问首页
![图片](https://user-images.githubusercontent.com/94462465/183561441-0c491b76-62de-4506-b25e-a0d3b790330f.png)

从数据库中数据看，该用户首页也是有授权了

![图片](https://user-images.githubusercontent.com/94462465/183561514-45c22ff3-e160-4272-be92-cc422518b621.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by 2428552874** [comment]
请问这个问题是怎么解决的？我也遇到了相同的问题

**Comment by gaoyuan98** [comment]
这个问题怎么处理的呢。我还是卡这。。
