### ISSUE TITLE
微服务启动时，数据源被切换为 H2，有什么处理方向？

### ISSUE THREAD

**Issue by tzou24** [jeecgboot/jeecg-boot#3955]
##### 版本号：

        <jeecgboot.version>3.0.0</jeecgboot.version>
##### 问题描述：
登录后报错

        SysUser sysUser = sysUserService.getOne(queryWrapper);
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "SYS_USER" not found; SQL statement:

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
H2未测试过
