### ISSUE TITLE
NgAlain模块是干什么用的？代码大部分都注释了，能否直接移除掉？

### ISSUE THREAD

**Issue by zhangyingrepo** [jeecgboot/jeecg-boot#3959]
##### 版本号：
jeecgboot 3.4.4

##### 问题描述：
NgAlain模块是干什么用的？代码大部分都注释了，能否直接移除掉？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/21967199/184275271-39af0047-c440-4e67-b436-eccd4c95e648.png)

**Comment by zhangdaiscott** [comment]
可以
