### ISSUE TITLE
Vue 3.0  菜单配置bug

### ISSUE THREAD

**Issue by yanyanpeng** [jeecgboot/jeecg-boot#3962]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/60538506/184499417-82bb3ca6-a23a-44c7-9778-a8fb5f06105e.png)

![image](https://user-images.githubusercontent.com/60538506/184499381-e3716b99-611d-4ff3-bb52-51fce6e325b8.png)

![image](https://user-images.githubusercontent.com/60538506/184499395-b653dd9e-7ddc-460d-b3f0-ab58fdce4f7b.png)

![image](https://user-images.githubusercontent.com/60538506/184499438-2eaeffd8-2f08-40c1-82f7-ab1a058f47c2.png)
![image](https://user-images.githubusercontent.com/60538506/184499450-63e150ca-8045-4029-a9d4-0ee5245f60e2.png)
![image](https://user-images.githubusercontent.com/60538506/184499474-db3019a7-26f3-4cef-a117-75fbd50c2bb9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
角色给菜单授权了吗

**Comment by yanyanpeng** [comment]
🤣🤣🤣，感谢感谢，恍然大悟😁😁😁


 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年8月14日(周日) 凌晨0:20写道:

  

 
角色给菜单授权了吗
