### ISSUE TITLE
下拉树选择控件j-tree-select无数据显示

### ISSUE THREAD

**Issue by desert1005** [jeecgboot/jeecg-boot#3964]
![image](https://user-images.githubusercontent.com/17897758/183867738-107ceb77-1437-4f3e-83a9-66d20d8b84ef.png)

在自定义组件界面，小部分电脑上，下拉树选择控件失灵，换过任何的浏览器（google chrome，360，百度等），均失灵。目前只能重装系统

**Comment by zhangdaiscott** [comment]
跟系统有啥关系？
