### ISSUE TITLE
Docker镜像启动前端 (单体模式)，前端访问接口出现502的错误

### ISSUE THREAD

**Issue by valsun2016** [jeecgboot/jeecg-boot#3966]
版本号：

后端   jeecg-boot-3.2.0-last
前端   jeecgboot-vue3 3.4.0

问题描述：

docker 后端部署ok，也可以访问 http://localhost:8080/jeecg-boot/doc.html
宿主机映射皆有配置：
127.0.0.1 jeecg-boot-system
127.0.0.1 jeecg-boot-gateway
127.0.0.1 jeecg-boot-mysql
127.0.0.1 jeecg-boot-redis
127.0.0.1 jeecg-boot-system
**但是，docker部署前端的时候，部署完毕后访问，登录不进去，出现：
502 Bad Gateway**

.env.production 也按照这里设置了 http://vue3.jeecg.com/3028878
Dockerfile 也来自官网，我没修改，我看也是映射为，，，，
 location   /jeecgboot { \
                      proxy_pass              http://jeecg-boot-system:8080/jeecg-boot; \

我进到前端的容器中，curl http://jeecg-boot-system 是ok的，
当然 ok，因为 宿主机配置了，127.0.0.1 jeecg-boot-system

但是  curl http://jeecg-boot-system:8080/jeecg-boot 就出现 
**curl: (7) Failed to connect to jeecg-boot-system port 8080: Connection refused**
会是这个原因吗？

另外我前端不用docker启动，而是直接在宿主机上启动，直接代理访问容器的后端是ok的，说明我的容器后端是正常的！

就是这个前端用容器启动就没法访问后端容器的api，另外分别测试了一下指定docker的网络模式都不行，依然是502错误，，，

--network=host  
或者
--add-host jeecg-boot-system:127.0.0.1

求帮助～～～tks

**Comment by zhangdaiscott** [comment]
1 直接访问 http://jeecg-boot-system:8080/jeecg-boot  看是否通
2 访问前端F12请求情况截图

**Comment by valsun2016** [comment]
> 1 直接访问 http://jeecg-boot-system:8080/jeecg-boot 看是否通 2 访问前端F12请求情况截图

1  http://jeecg-boot-system:8080/jeecg-boot  这个是可以正常访问的
2 如图  
<img width="1374" alt="WX20220816-142226@2x" src="https://user-images.githubusercontent.com/17111191/184811584-8283639b-2389-476a-a253-b418f6ba8bf7.png">

**Comment by zhangdaiscott** [comment]
哪问题就出在nginx转发上，前端和后端docker不是在一个服务器上？
![image](https://user-images.githubusercontent.com/3162115/184812212-37ff7fee-9da6-4b99-a491-6a2a1e53d368.png)

**Comment by valsun2016** [comment]
> 哪问题就出在nginx转发上，前端和后端docker不是在一个服务器上？ ![image](https://user-images.githubusercontent.com/3162115/184812212-37ff7fee-9da6-4b99-a491-6a2a1e53d368.png)

在一个服务器上啊，就是我本机 mac 本

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/184812949-9d313c58-bc32-4e43-a096-ffcce5e80829.png)

**Comment by valsun2016** [comment]
@zhangdaiscott 感谢，解决了，，，直接把之前的映射全部设置成局域网的本机ip 而非 127.0.0.1 ，重启容器搞定
10.11.17.55 jeecg-boot-system
10.11.17.55 jeecg-boot-gateway
10.11.17.55 jeecg-boot-mysql
10.11.17.55 jeecg-boot-redis
