### ISSUE TITLE
建议将 jeecg-system-biz 模块的启动类及配置文件独立成单独的启动模块

### ISSUE THREAD

**Issue by ice2shell** [jeecgboot/jeecg-boot#3967]
##### 版本号：
3.4.0

##### 问题描述：
微服务模式下有单独的启动类，同时配置文件也交给 nacos 维护，但是现有 jeecg-system-biz 模块下的配置文件会覆盖 nacos上的同名配置。因此建议和微服务模块一样，将 jeecg-system-biz 模块的启动类及配置文件独立成单独的启动模块,如下所示：
```
|—— jeecg-boot
         ......
        |—— jeecg-module-system
                |—— jeecg-system-api
                |—— jeecg-system-biz
                |—— jeecg-system-start
       ......
```

然后微服务启动模块和单体启动模块都可以依赖同一个jeecg-system-biz 模块，这样该模块的 pom 文件也就不需要以下配置了：
```	
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<!--SpringCloud运行环境 ,值改为true跳过SpringBoot启动打包插件 -->
					<skip>${skip.springboot.maven}</skip>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
存在这个问题吗
` jeecg-system-biz 模块下的配置文件会覆盖 nacos上的同名配置`

最新版已经改成import方式了，应该不再存在这个问题

**Comment by zhangdaiscott** [comment]
之所以不拆，是怕两个system start又让人疑惑

**Comment by zhangdaiscott** [comment]
拆分完，请确认

**Comment by ice2shell** [comment]
感谢官方这么快响应。关于配置覆盖的问题，我也是在实践之后发现的。当时是部署完微服务版本的system模块的Docker镜像后，容器启动失败了。检查日志才发现数据库读取的地址不是 nacos 配置的地址而是 jeecg-system-biz 模块未拆分前本地配置文件中配置的地址。不过拆分后发现了新bug：`Error creating bean with name 'initCodeGenerateDbConfig' defined in class path resource`，我再提issue吧。
