### ISSUE TITLE
字典表能否根据字段排序

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3968]
##### 版本号：
v3.4.0

##### 问题描述：
比如sys_user表，根据realname排序

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90361617/185053869-52f9c8d6-5b77-4814-9215-f15392bd5ea5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/185179241-09bf1947-2347-49c6-b7ae-d3942f2f24eb.png)
直接写 sys_user order by 字段试试
应该可以

**Comment by zhangdaiscott** [comment]
不过你这个没有任何意义，@dict是用于列表翻译的，又不是页面渲染
