### ISSUE TITLE
前端访问跨域

### ISSUE THREAD

**Issue by xiamy-summer** [jeecgboot/jeecg-boot#3969]
##### 问题描述：
后端切换成微服务后，部署到服务器中前端访问提示跨域。是使用docker部署的。前端只改了evn.development 里的后端IP。

##### 截图&代码：
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/39183612/185066715-9b1507fa-5fce-4196-a3fa-c1a73b8dbbaf.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
单独访问后台地址，看看通吗

**Comment by xiamy-summer** [comment]
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/39183612/185071633-73228231-05c7-4e5d-880b-e054b8bec782.png">
可以访问的。

**Comment by zhangdaiscott** [comment]
项目微服务的情况下，后台也设置了支持跨域，你自己有没有改过什么

**Comment by xiamy-summer** [comment]
没有改动过什么呢。之前都可以的。现在突然就这样的。在我自己的本地启动都提示跨域。。。

**Comment by zhangdaiscott** [comment]
之前微服务也没有跨域问题？

**Comment by xiamy-summer** [comment]
同网段跨域的问题已经解决了。现在如果部署到不同的网段上还是会出现跨域
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/39183612/185270878-7c5293ef-45e0-4b4c-8e3d-f524c2f77e7a.png">

**Comment by zhangdaiscott** [comment]
怎么解决的，为什么会出现跨域？

**Comment by xiamy-summer** [comment]
同网段跨域是我同事挖得坑。在nacos里创建了一个新的空间，没把网关的配置克隆过去。现在这个不同网段的跨域怎么解决呢？

**Comment by zhangdaiscott** [comment]
跟网段没关系，程序后台已经是支持跨域，自己查问题吧
