### ISSUE TITLE
用户管理权限部门很多全选保存后导致编辑按钮消失

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#3972]
##### 版本号：
v3.4.1

##### 问题描述：
用户管理权限部门很多全选保存后导致编辑按钮消失

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/185083773-b6884650-adea-44e1-8730-5208054f5bd8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
描述太简单，不知道你的具体操作

**Comment by 3509282792** [comment]
> 描述太简单，不知道你的具体操作

就是新增的部门有很多，然后一个用户绑定所有的部门，就会导致操作列表不美观并且最右边的操作界面消失，我用的是dege游览器

**Comment by sjlei** [comment]
问题已修复。最新版Edge没问题
![image](https://user-images.githubusercontent.com/34293221/194853533-119d9fa5-e44e-4c3c-bac3-58967c8306ae.png)
