### ISSUE TITLE
使用jeecgboot最新版中遇到的404问题

### ISSUE THREAD

**Issue by WangWz9** [jeecgboot/jeecg-boot#3973]
##### 版本号：
3.4.0

##### 问题描述：
目前我用的是jeecgboot 3.4.0版
本地电脑启动了system和gateway两个
nacos用的另一台linux上的
nacos可以看到注册的服务列表，前端也修改了VUE_APP_API_BASE_URL

本地在后端也打了断点，发现没有进入断点

遇到了登录页面验证码404和网关访问接口文档异常的问题

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/31911782/185097157-7efe6c86-3e64-4295-993b-5416b3947728.png)
![图片](https://user-images.githubusercontent.com/31911782/185097354-5127e881-d139-4e1c-a626-062dfdb45132.png)
![图片](https://user-images.githubusercontent.com/31911782/185097157-7efe6c86-3e64-4295-993b-5416b3947728.png)
![图片](https://user-images.githubusercontent.com/31911782/185097468-06365c99-b462-4529-9ff5-8760fa690e78.png)
![图片](https://user-images.githubusercontent.com/31911782/185097773-03e6d4e1-15d5-4012-8058-599cefca9a93.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
直接访问gateway地址，看看什么情况

**Comment by WangWz9** [comment]
![图片](https://user-images.githubusercontent.com/31911782/185137632-3bec0365-67fa-4b2d-84fd-c69967352fbd.png)
![图片](https://user-images.githubusercontent.com/31911782/185138057-97f6c0c7-96be-45c8-b308-b7970d23b0ee.png)

也是如此 404

**Comment by zhangdaiscott** [comment]
哪说明 system服务实例，启动有问题，去看看system实例 日志

**Comment by WangWz9** [comment]
system微服务实例的端口明明是7001，为什么启动后还是8080呢
我启动的是jeecg-system-cloud-start  --System微服务启动项目(7001)呀
![图片](https://user-images.githubusercontent.com/31911782/185275027-b6ae9bcc-af1f-45cf-95bb-4300fc6d6f25.png)
![图片](https://user-images.githubusercontent.com/31911782/185275559-23832b6a-6f5d-4159-9f5a-f4206e59c110.png)

**Comment by zhangdaiscott** [comment]
把system-biz里面的配置文件yml删掉
