### ISSUE TITLE
部署到linux环境后 knife4ja 文档打开没有对应的服务列表

### ISSUE THREAD

**Issue by aikai123** [jeecgboot/jeecg-boot#3974]
**#####** 版本号：
3.2.0

##### 问题描述：
部署到linux环境后 knife4ja 文档打开没有对应的服务列表

##### 截图&代码：
![3DBE6D02CD74CF54FC6FD5A2CE808F2E](https://user-images.githubusercontent.com/52918163/185105449-b58bef09-191b-4208-8812-093a6ef81442.jpg)
![image](https://user-images.githubusercontent.com/52918163/185105461-88a82f7f-72c4-44e1-ad5f-e8e8dffc3048.png)
![3DBE6D02CD74CF54FC6FD5A2CE808F2E](https://user-images.githubusercontent.com/52918163/185105478-885868a6-6dbe-4c98-895f-4bfd1dc41bb8.jpg)
![image](https://user-images.githubusercontent.com/52918163/185105489-e2f85de2-f56f-4809-bb61-4edd73064bf9.png)
![image](https://user-images.githubusercontent.com/52918163/185105501-eee9e046-b0c4-4388-8230-b8d4a481e010.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
最后启动gateway
