### ISSUE TITLE
jeecg代码结构组织建议

### ISSUE THREAD

**Issue by zhangyingrepo** [jeecgboot/jeecg-boot#3975]
##### 版本号：
3.4.1

##### 问题描述：
下面是目前结构jeecg-boot仓库项目结构，jeecg-boot-starter在另外一个库。
项目结构
├─jeecg-boot-parent（父POM： 项目依赖、modules组织）
│  ├─jeecg-boot-base-core（共通模块： 工具类、config、权限、查询过滤器、注解等）
│  ├─jeecg-module-demo    示例代码
│  ├─jeecg-module-system  System系统管理目录
│  │  ├─jeecg-system-biz    System系统管理权限等功能
│  │  ├─jeecg-system-start  System单体启动项目(8080）
│  │  ├─jeecg-system-api    System系统管理模块对外api
│  │  │  ├─jeecg-system-cloud-api   System模块对外提供的微服务接口
│  │  │  ├─jeecg-system-local-api   System模块对外提供的单体接口
│  ├─jeecg-server-cloud           --微服务模块
|     ├─jeecg-cloud-gateway       --微服务网关模块(9999)
|     ├─jeecg-cloud-nacos       --Nacos服务模块(8848)
|     ├─jeecg-system-cloud-start  --System微服务启动项目(7001)
|     ├─jeecg-demo-cloud-start    --Demo微服务启动项目(7002)
|     ├─jeecg-visual
|        ├─jeecg-cloud-monitor       --微服务监控模块 (9111)
|        ├─jeecg-cloud-xxljob        --微服务xxljob定时任务服务端 (9080)
|        ├─jeecg-cloud-sentinel     --sentinel服务端 (9000)
|        ├─jeecg-cloud-test           -- 微服务测试示例（各种例子）
|           ├─jeecg-cloud-test-more         -- 微服务测试示例（feign、熔断降级、xxljob、分布式锁）
|           ├─jeecg-cloud-test-rabbitmq     -- 微服务测试示例（rabbitmq）
|           ├─jeecg-cloud-test-seata          -- 微服务测试示例（seata分布式事务）
|           ├─jeecg-cloud-test-shardingsphere    -- 微服务测试示例（分库分表）
目前单体和微服务源码混在同一个仓库，官方想让开发者可以自由切换架构更加方便，但按个人使用体验，这种自由切换不但没有带来方便，还造成了很多困扰，特别想长期追踪官方仓库的更新的时候。比如我使用的是单体版本，微服务相关代码更新我根本不关心，但因为官方仓库代码都在一起，只能被迫一起更新。

建议将System单体应用代码和微服务架构代码完全分离，jeecg-boot仓库只放单体架构的源码，另起jeecg-cloud仓库放微服务相关源码(jeecg-boot-starter不用单独放一个仓库，直接放在jeecg-cloud中)，做到业务模块和系统架构完全分离，这两块基本都是独立部署，由不同人的维护的。至于单体应用到微服务的迁移，出一篇迁移说明文档即可，没必要将配置混在一起，造成不必要的困扰。这样各个仓库代码更加纯粹，不同需求的人使用和理解jeecg都更加方便。具体如下：
1. jeecg-boot: System单体应用
![image](https://user-images.githubusercontent.com/21967199/185179963-770c9e38-ea61-4aee-a95e-b6a160d3b3bc.png)

3. jeecg-cloud: 微服务
![image](https://user-images.githubusercontent.com/21967199/185180116-9c3d0970-e843-4852-9b3c-f9d2e61794db.png)

望采纳！

**Comment by zhangdaiscott** [comment]
jeecg-system-cloud-start 
jeecg-system-biz

不在一个项目里，调试会不方便

**Comment by zhangyingrepo** [comment]
![image](https://user-images.githubusercontent.com/21967199/185309041-0595c611-f978-44ec-a04b-b2d67ae6312f.png)
这两个不需要，jeecg-system-cloud-start也放在system仓库里面 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
3q,暂时不采纳
