### ISSUE TITLE
JS增强，内置列表增强方法不生效

### ISSUE THREAD

**Issue by Jiangjun8888** [jeecgboot/jeecg-boot#3976]
##### 版本号：
v3.2.0

##### 问题描述：
在线表单，主题模版：默认模版，JS增强功能,我配置了列表事件，在新增前触发，但没生效，不知道触发的条件是不是理解错了。

##### 截图&代码：
![F785C8F74F51B51AC731A7CA0D609843](https://user-images.githubusercontent.com/59253510/185281436-b5800308-fe4b-4391-8882-76be741176f9.jpg)
![image](https://user-images.githubusercontent.com/59253510/185281539-c8ba05d1-501e-4573-884b-9ff400e1d543.png)

![A1773319913A9501C3C2DEA931719434](https://user-images.githubusercontent.com/59253510/185281467-04569fa1-a098-4d41-9c47-1e8b38253e64.jpg)

**Comment by zhangdaiscott** [comment]
你是vue3 还是vue2

**Comment by Jiangjun8888** [comment]
> 你是vue3 还是vue2

Vue3

**Comment by zhangdaiscott** [comment]
vue3再等等，当前版本还不不支持
