### ISSUE TITLE
ws连接就直接断了

### ISSUE THREAD

**Issue by xiamy-summer** [jeecgboot/jeecg-boot#3977]
##### 问题描述：
切换成微服务在本机启动可以正常的访问ws，但是通过docker部署到服务器后ws一连接就直接断开了。

##### 截图&代码：

<img width="793" alt="image" src="https://user-images.githubusercontent.com/39183612/185287960-191ec554-90fa-4a4a-b2e1-957449dab774.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
后台提示什么，最新版加了token验证

**Comment by xiamy-summer** [comment]
后台没有提示，就一直提示有多少用户连接了。我在我本地启动就没问题。用docker部署到服务器后就一直出现这个

**Comment by zhangdaiscott** [comment]
本地启动连接的是哪个后台

**Comment by zhangdaiscott** [comment]
如果是通过nginx映射
nginx配置需要加上 Upgrade 和Connection 协议头，不然WebSocket会404
