### ISSUE TITLE
你们的包在aliyun上传了吗？

### ISSUE THREAD

**Issue by harryheng** [jeecgboot/jeecg-boot#3983]
##### 前端版本：vue2

vue3版？还是vue2版？请说明清楚

##### 问题描述：
Could not find artifact org.jeecgframework.boot:hibernate-re:pom:3.2.2 in aliyunmaven 

##### 截图&代码：

Could not find artifact org.jeecgframework.boot:hibernate-re:pom:3.2.2 in aliyunmaven 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043876
