### ISSUE TITLE
online代码生成器提示非admin用户无权限操作

### ISSUE THREAD

**Issue by liner123456** [jeecgboot/jeecg-boot#3984]
##### 版本号：
2.4.6

##### 前端版本：

vue2版

##### 问题描述：

online代码生成器的导入数据库表功能无法使用，使用时提示”非admin用户无权限操作!“，在使用其它管理员角色下的用户登录时也是这样，本来想自行排查一下接口但是发现IDEA定位不到接口的位置，琢磨了半天还是没弄懂实现原理，所以希望大佬能给点思路，谢谢啦。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26665146/185739701-b328a5d1-7ad5-4a51-9b90-afe98d34ebbe.png)

**Comment by liner123456** [comment]
确定登录的用户都有代码生成器的权限并且都是管理员角色下的用户。

**Comment by zhangdaiscott** [comment]
必须用admin用户

**Comment by liner123456** [comment]
请问这部分的代码有开源吗？能否指点一下位置在哪里？希望能学习一下实现的思路但是之前找了半天也没找到代码在哪。。。
