### ISSUE TITLE
引入Springboot Devtools依赖启动报错sysBaseAPI bean not found

### ISSUE THREAD

**Issue by Skrait** [jeecgboot/jeecg-boot#3985]
##### 前端版本：

vue3版？还是vue2版？请说明清楚

##### 问题描述：
引入Springboot Devtools依赖启动后报错。
DevTools加了版本号也是一样

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23080181/185750001-424ba8c5-78a9-4437-95a8-9a394111d188.png)
![image](https://user-images.githubusercontent.com/23080181/185750044-253134f7-a326-43ba-a670-3bd52f36750f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用jrebel

**Comment by zhangdaiscott** [comment]
依赖版本号升级看看

```
<dependency>
  <groupId>org.jeecgframework.boot</groupId>
  <artifactId>hibernate-re</artifactId>
  <version>3.2.2</version>
</dependency>
```

**Comment by Skrait** [comment]
> 依赖版本号升级看看
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework.boot</groupId>
>   <artifactId>hibernate-re</artifactId>
>   <version>3.2.2</version>
> </dependency>
> ```

启动不了，
![image](https://user-images.githubusercontent.com/23080181/185815530-fe447ecb-c639-48e5-a7cb-63e148a5c6eb.png)

**Comment by zhangdaiscott** [comment]
刷maven
