### ISSUE TITLE
jeecg的xxl-job和nacos是不是只能用mysql数据库

### ISSUE THREAD

**Issue by hzitao** [jeecgboot/jeecg-boot#3986]
##### 版本号：
3.4.0

##### 前端版本：
无
vue3版？还是vue2版？请说明清楚
无
##### 问题描述：
jeecg的xxl-job和nacos是不是只能用mysql数据库？好像没看到相关的sql？想使用oracle

##### 截图&代码：
![9](https://user-images.githubusercontent.com/44660862/185823737-75f25c45-d127-41a1-b777-314d80e7efcd.jpg)
![1](https://user-images.githubusercontent.com/44660862/185823768-bae57f5b-1fcc-4c70-842e-ebaafe013401.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前默认是这样的，既然微服务分库，这两款独立就行，主业务可以切换不同的库
