### ISSUE TITLE
启动system微服务模块一直不走dev

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#3988]
##### 前端版本：

vue2

##### 问题描述：
   启动JeecgSystemCloudApplication, 一直没用profile为dev，是什么情况，以前的版本都是默认用的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/185892862-c75b2ba1-aace-4d44-9e2c-06f276c52330.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用我们的原始代码测试，确认你是否改坏导致
