### ISSUE TITLE
dict注解 实体嵌套翻译失效

### ISSUE THREAD

**Issue by 2720851545** [jeecgboot/jeecg-boot#3990]
##### 问题描述：
A类有dict注解字段,  B对象包含A对象.   

响应B对象, A对象中的dict注解不会处理

##### 截图&代码：

  
![image](https://user-images.githubusercontent.com/28623614/186086607-d21fbb0e-b564-4d26-b9e1-63ba4280a6d6.png)
![image](https://user-images.githubusercontent.com/28623614/186086620-635b1274-b3db-44fe-a38d-2406d0717694.png)

**Comment by 2720851545** [comment]
#3993

**Comment by xiaolinVV** [comment]
看了源码就知道，只会自动翻译分页列表的第一层对象。

**Comment by zhangdaiscott** [comment]
暂时不采纳，目前这块做的太高级，会导致性能下降，特殊的更意见手工翻译
