### ISSUE TITLE
数据表关联问题和已存在的数据完整性需要保证问题

### ISSUE THREAD

**Issue by GitACDreamer** [jeecgboot/jeecg-boot#3991]
##### 版本号：
3.4.1

##### 前端版本：
vue3
vue3版？还是vue2版？请说明清楚

##### 问题描述：
前端对用户数据进行删除，跟用户数据相关联的数据都会被自动清空，例如：操作日志数据等。

##### 截图&代码：
我创建一个test用户，当test用户被删除，操作日志等相关联的数据都会为空
![image](https://user-images.githubusercontent.com/19402747/186088605-249d6318-c297-4bfe-b61a-ab5a5f6019dc.png)

#####希望做到
1. 关联表相关数据被删除后，原来已存在的数据不受影响。
2. 存在关联的表，例如： 一个角色被某个用户使用，在删除角色前，应该改角色使用情况进行判断，如果已经被使用，应该提示相对应的用户解绑相关角色，否者，当前角色被删除，被授权的用户下次登录会没有权限。（部门表同理）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用户有个逻辑删除，你不真实删除就不会出现这个问题。
