### ISSUE TITLE
使用mq，进行sql更新操作报错

### ISSUE THREAD

**Issue by yzmking** [jeecgboot/jeecg-boot#3992]
##### 版本号：
3.2.0

##### 前端版本：
前端是vue2版
vue3版？还是vue2版？请说明清楚

##### 问题描述：
使用mq，监听到数据，然后进行sql更新操作报错，并且token也获取不了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44563730/186124173-2d2c9297-a4fd-4ccd-9450-534bbaae0f8e.png)
![image](https://user-images.githubusercontent.com/44563730/186124318-9d7e325b-2e50-46ef-9ea6-a81872917b4d.png)
![image](https://user-images.githubusercontent.com/44563730/186124393-4f22ee83-6986-47ff-9d48-6cba2216143e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你不用mq 执行你这个sql看看

**Comment by yzmking** [comment]
![image](https://user-images.githubusercontent.com/44563730/186300829-9e3d3cae-1675-4278-b941-4fa1a0970eeb.png)
正常调用是可以的

**Comment by yzmking** [comment]
![image](https://user-images.githubusercontent.com/44563730/186301067-5e1b60e0-17d9-4b3e-83b9-aea7723bb674.png)
我上网看，加了这个后是可以了，但是到这里
![image](https://user-images.githubusercontent.com/44563730/186301160-a2901de5-8930-4959-9550-0baf3898d86c.png)
又空指针了

**Comment by zhangdaiscott** [comment]
你的修改人字段是必填的？

**Comment by yzmking** [comment]
也不是必填，但也是要记录的

**Comment by zhangdaiscott** [comment]
非必须，不应该因为这俩字段报错，除非你设置了必填

**Comment by yzmking** [comment]
不是填入时报错，是39行获取用户名的时候报错，空指针

**Comment by zhangdaiscott** [comment]
updateFill(
这是你自己写的吧，我们没这个方法

**Comment by yzmking** [comment]
![image](https://user-images.githubusercontent.com/44563730/186347801-d917e41d-45f1-4001-8c74-c38f8e7c9189.png)
对，但是我觉得是因为这个获取token也是空的，所以后面才获取不到用户

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2725212
