### ISSUE TITLE
微服务下接口响应速度很慢

### ISSUE THREAD

**Issue by chenshili155** [jeecgboot/jeecg-boot#3994]
##### 版本号：
2.4.2

##### 问题描述：
接口响应速度经常很慢，大概要30s的样子，请问这是什么情况

##### 截图&代码：

![image](https://user-images.githubusercontent.com/41871181/186358220-9b3a69da-9937-4f9a-9494-319a15f2da5f.png)

**Comment by chenshili155** [comment]
时好时坏，是服务器问题还是网关问题鸭？

**Comment by zhangdaiscott** [comment]
版本有点老，可以自己在相关逻辑点加入耗时计算日志，跟踪下

**Comment by chenshili155** [comment]
链路追踪分析是网关的问题，你们有什么方向吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 微服务下接口响应速度很慢 (Issue #3994)





 
版本有点老，可以自己在相关逻辑点加入耗时计算日志，跟踪下
