### ISSUE TITLE
gateway网关超时，版本如果平滑升级

### ISSUE THREAD

**Issue by chenshili155** [jeecgboot/jeecg-boot#3996]
##### 版本号：
2.4.2

##### 问题描述：
gateway网关老是拦截请求导致响应时间很长最后访问超时，另外如何平滑升级jeecg版本，文档中有吗，暂未看到

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41871181/186570716-dfe6a3ce-713b-4375-b990-a68dc46573a2.png)
![image](https://user-images.githubusercontent.com/41871181/186570766-87512db3-4026-4ff4-a193-556c28d7445b.png)

**Comment by chenshili155** [comment]
![image](https://user-images.githubusercontent.com/41871181/186571558-70508936-b3d1-40a7-8a6e-f756fa954212.png)
我的接口监控消耗时间

**Comment by zhangdaiscott** [comment]
哪个代码拦截的？

**Comment by chenshili155** [comment]
![image](https://user-images.githubusercontent.com/41871181/186581958-6803a969-a568-4b94-8180-2f112023ea60.png)
这里  响应的

**Comment by zhangdaiscott** [comment]
可以只升级微服务相关启动模块，服务模块升级下依赖，应该改动不大

**Comment by chenshili155** [comment]
建议出一份升级手册~
