### ISSUE TITLE
缩小窗口后模态窗口会自动关闭，且表格数据刷新

### ISSUE THREAD

**Issue by lywxin** [jeecgboot/jeecg-boot#3997]
##### 版本号：
2.4.6

##### 前端版本：

vue2版

##### 问题描述：
缩小窗口后模态窗口会自动退出，且表格数据刷新，vue3版没有这个问题，希望能修改，或者指教怎么修改，谢谢

##### 截图&代码：
原窗口大小
![1](https://user-images.githubusercontent.com/28347607/186722256-8d357115-9b36-4567-ad87-ac33699f6228.png)
窗口缩小后，模态窗口消失，列表刷新一次，左边弹出菜单栏
![2](https://user-images.githubusercontent.com/28347607/186722276-4318bd0e-670d-4812-84f6-4b16ff69270b.png)

**Comment by zhangdaiscott** [comment]
以前别人提过，我们这个是做的移动端适配，自适应导致，正常没有这样操作的吧

**Comment by lywxin** [comment]
客户需要在页面里通过缩放来看某个表单的排版，然后出现这个情况反映给我的，还是有这种需求，有什么头绪或者思路怎么改吗？

**Comment by lywxin** [comment]
Vue3版本没这个问题，或许可以参考Vue3版本的jeecg代码

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/804
