### ISSUE TITLE
第三方登录字典没有缓存

### ISSUE THREAD

**Issue by 17782798075** [jeecgboot/jeecg-boot#3998]
##### 前端版本：vue2

vue3版？还是vue2版？请说明清楚

##### 截图&代码：
原始代码：
ThirdLoginController.java
![image](https://user-images.githubusercontent.com/75563099/186800680-d059e681-bb35-49b2-85b7-f95b7fcf583a.png)
user.js
![image](https://user-images.githubusercontent.com/75563099/186800722-0d94e2f0-1514-4992-9a78-a3a6f67ce4c3.png)
登陆后的现象：
![image](https://user-images.githubusercontent.com/75563099/186800851-008babcf-d1ab-4784-992e-bc09c9d681d7.png)
修改：
![image](https://user-images.githubusercontent.com/75563099/186801076-427200c0-f8ef-4871-bc69-7a8499e67f8a.png)
![image](https://user-images.githubusercontent.com/75563099/186801136-2734ad8c-f6ce-445e-aef8-b14ea6a48342.png)
修改后正常显示：
![image](https://user-images.githubusercontent.com/75563099/186801458-ef35c321-f2a1-4883-b14c-d60a693550ce.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 17782798075** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
收到
