### ISSUE TITLE
左侧最小化菜单按钮点击无法展开

### ISSUE THREAD

**Issue by admin-L** [jeecgboot/jeecg-boot#4002]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/61929139/187018359-6e76371d-9ffc-4c40-9d97-629478c29ba7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题未复现，可以展开

![image](https://user-images.githubusercontent.com/34293221/194757209-2ac30697-b195-44af-bde9-44730633f2f2.png)
