### ISSUE TITLE
jeecgboot3.3集成cas跳转到另一个系统时，无法自动登录

### ISSUE THREAD

**Issue by 348339749** [jeecgboot/jeecg-boot#4003]
使用jeecgboot 3.3.0 版本仓库代码，集成同一个cas（6.1版本，配置默认帐号密码：admin/123456）认证中心，A系统（3000端口）通过cas界面登录之后正常跳转到A系统里面，在A系统里面有个链接，链接到B系统（3001端口），打开链接的时候，界面会自动跳转到cas的登陆界面，不应该是直接进入到B系统对应的页面吗？另外一个问题，A系统登陆成功之后，点击右上角的退出，也成功退出了，并转到了cas的登陆界面，这时再次输入帐号密码（admin/123456）登陆，前端会一直转圈，后端控制台一直打印提示“未能够识别出目标 &#039;ST-2-gqQSrEpDwAQlHLdkJIEz-cas01.example.org&#039;票根”，无法登陆。

**Comment by zhangdaiscott** [comment]
你自己的cas服务端是怎么实现的 ，这个我们不清楚，没办法帮你分析
