### ISSUE TITLE
代码生成失败

### ISSUE THREAD

**Issue by lvnginx** [jeecgboot/jeecg-boot#4004]
##### 版本号：
3.4.0

##### 前端版本：
vue3版

##### 问题描述：
代码生成器生成代码失败，点击代码生成后前端显示页面提示生成失败，后台日志显示生成成功，但代码生成为空
检查了项目路径和生成路径均没有异常

##### 截图&代码：
前端提示信息：
      代码生成结果
      :::::: 生成失败ERROR提示 ::::::
      1.JeecgBoot项目所在路径是否含有中文或空格，去掉就好了！参考 http://doc.jeecg.com/2088984
      2.采用JAR包上线发布，需要做额外配置！参考 http://doc.jeecg.com/2043922

后台日志：
2022-08-28 21:15:32.733 [http-nio-8080-exec-1] INFO  org.jeecgframework.codegenerate.generate.impl.a.a:54 -   load template from templateRootDir = 'E:\idea_workspace\jeecg-boot\file:\D:\MAVEN\maven-repository\org\jeecgframework\boot\jeecg-system-biz\3.4.0\jeecg-system-biz-3.4.0.jar!\jeecg\code-template-online',stylePath ='default.one',  out GenerateRootDir:E:\jeecgcode
2022-08-28 21:15:32.734 [http-nio-8080-exec-1] INFO  o.j.codegenerate.generate.impl.CodeGenerateOne:140 -  ----- jeecg-boot ---- generate  code  success =======> 表名：v3_demo1

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这不是给了明确提示了吗
:::::: 生成失败ERROR提示 ::::::
1.JeecgBoot项目所在路径是否含有中文或空格，去掉就好了！参考 http://doc.jeecg.com/2088984
2.采用JAR包上线发布，需要做额外配置！参考 http://doc.jeecg.com/2043922

**Comment by lvnginx** [comment]
采用的idea,项目路径没有中文也没有空格，没有发布




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 代码生成失败 (Issue #4004)





 
这不是给了明确提示了吗
 :::::: 生成失败ERROR提示 ::::::
 1.JeecgBoot项目所在路径是否含有中文或空格，去掉就好了！参考 http://doc.jeecg.com/2088984
 2.采用JAR包上线发布，需要做额外配置！参考 http://doc.jeecg.com/2043922

**Comment by yuexushuang** [comment]
@lvnginx 这个你用管理员启动idea运行后台就好了，系统用户权限的问题

**Comment by dongjia2014** [comment]
看启动日期，会明确提示 "load template from templateRootDir" ，找到这个就去对应的路径复制 代码中 jeecg 目录所有文件（包含此目录），粘贴到提示的templateRootDir ，重启应用就 ok，不用太在意页面的错误提示
