### ISSUE TITLE
jeecg-boot 项目导入到 idea 后无法运行项目

### ISSUE THREAD

**Issue by goodthisway** [jeecgboot/jeecg-boot#4005]
##### 版本号：
3.1.0

##### 前端版本：
vue2版

##### 问题描述：
下载开源版项目后， 导入到idea  ， maven 及相关依赖完成更新后， 编译成功， 项目配置，已经配置java sdk 1.8，配置好编译输出目录， 但是不能运行项目。 点击【run】,【debug】按钮，由绿色变灰后， 无法启动项目。

##### 截图&代码：
![ppp66666](https://user-images.githubusercontent.com/17997051/187142461-8148adbe-d392-42e0-afd0-a6d1615e4087.png)

**Comment by zhangdaiscott** [comment]
刷新maven看看
