### ISSUE TITLE
vue3版本，online在线表单，新增页面无法显示联动控件

### ISSUE THREAD

**Issue by buptyanxl** [jeecgboot/jeecg-boot#4008]
##### 版本号：

3.4.1
##### 前端版本：

vue3版

##### 问题描述：
online表单开发，配置联动组件，新建页面无法显示联动组件

##### 截图&代码：

新建页面无法显示联动组件：省、市、区
![image](https://user-images.githubusercontent.com/6345299/187358026-225caa6c-12fd-4a3c-be71-aba9ab4da671.png)
配置页面
![image](https://user-images.githubusercontent.com/6345299/187358134-348924e1-8070-40f4-bf4c-c5c072f3fdf3.png)
![image](https://user-images.githubusercontent.com/6345299/187358158-3e621aab-0749-42c3-8050-408cba4357f2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
等新版发布

**Comment by zhangdaiscott** [comment]
已支持
