### ISSUE TITLE
 Could not find artifact org.jeecgframework.boot:jeecg-boot-parent:pom:3.3.0 in alimaven

### ISSUE THREAD

**Issue by harryheng** [jeecgboot/jeecg-boot#4009]
##### 版本号： 
     3.4.1

##### 前端版本：

vue2版

##### 问题描述：
不能更新包

##### 截图&代码：

 Could not find artifact org.jeecgframework.boot:jeecg-boot-parent:pom:3.3.0 in alimaven

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/187637586-c3249fc7-740e-4387-906f-747612afe825.png)
