### ISSUE TITLE
vue3版本，前端页面没有存储租户id，无法实现多租户

### ISSUE THREAD

**Issue by buptyanxl** [jeecgboot/jeecg-boot#4010]
##### 版本号：

3.4.1 
##### 前端版本：

vue3版

##### 问题描述：
使用多租户功能，前端页面没有存储租户id，无法实现多租户功能

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6345299/187420818-e75fa6b5-1290-413a-b262-166bde2e3d27.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么功能

**Comment by buptyanxl** [comment]
根据博客https://jeecg.blog.csdn.net/article/details/119780074改造部门、角色和菜单为多租户。
用户表没有改造，使用admin用户登录，其中rel_tenant_ids=1。
用户登录后，前端传过来的tenant_id 确是等于 0

**Comment by zhangdaiscott** [comment]
什么功能，哪个接口？我们默认已经实现了在header里面

**Comment by buptyanxl** [comment]
根据博客  https://jeecg.blog.csdn.net/article/details/119780074  改造
完成后测试无法通过，接口 /sys/permission/getUserPermissionByToken 报错，因为查询出来的菜单数量为0
![image](https://user-images.githubusercontent.com/6345299/187644107-220757b7-77b8-4c94-8821-68b0ef1cc759.png)
跟踪登录后发现在JwtFilter中tenant_id=0
![image](https://user-images.githubusercontent.com/6345299/187644451-d65a4bd7-d2f4-44e3-b031-548e6dededb4.png)

**Comment by buptyanxl** [comment]
跟踪了一下后台的调用情况
tenant_id =0 的情况在登录时有，后面在其他接口调用时有调整

**Comment by zhangdaiscott** [comment]
角色访问没问题
![image](https://user-images.githubusercontent.com/3162115/194745284-51b1fae3-960e-457d-bf9e-343992e03dae.png)
菜单列表也没问题
![image](https://user-images.githubusercontent.com/3162115/194745301-f59844a8-97e3-444f-89f7-cdfb0bc0ffdc.png)

经过测试，都没有问题
你的如果没有传递，应该是你这个登录用户未设置租户，再没有租户的情况下默认是0
