### ISSUE TITLE
请问如何实现根据token实现免密登陆跳转到指定的页面?

### ISSUE THREAD

**Issue by huguojia** [jeecgboot/jeecg-boot#4011]
##### 版本号：
3.20
##### 前端版本：

vue3

##### 问题描述：
请教大佬一下
我想通过外部系统跳转到jeecg的vue页面,请问需要哪些参数?如何实现?
能否根据token? 

举例:
在A系统配置jeecgboot页面某个菜单的url,能否不通过登陆直接访问到前端页面?

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by huguojia** [comment]
请问是否可以通过前端配置whitelist的方式?

**Comment by zhangdaiscott** [comment]
你既然拿到了token，自己实现一个模拟登录就可以了
