### ISSUE TITLE
配置下级菜单为隐藏路由后，二级菜单无法点击，并且显示了三角符号

### ISSUE THREAD

**Issue by TankCoder** [jeecgboot/jeecg-boot#4013]
##### 版本号：
3.4

##### 前端版本：
vue2

##### 问题描述：
配置【高级详情页】的下级菜单为 子菜单+路由菜单+隐藏路由 后，高级详情页菜单无法点击，并且显示了三角展开图标。（已设置权限）。

二级菜单为啥不能点击了。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/111105563/187472362-f55de477-834d-4a3f-9704-a4955b21e8f3.png)
![image](https://user-images.githubusercontent.com/111105563/187472574-196d2a2e-7faf-400d-b7e1-767c4a857cdb.png)

**Comment by TankCoder** [comment]
只要一个菜单有子菜单，那么他本身就不能被点击了？不论他的子菜单是不是隐藏的

就是这么设计的吗？

**Comment by TankCoder** [comment]
主要需求就是配置很多model 详情页面，不需要在左侧菜单中展示，仅做跳转使用。

但是使用官方示例配置后，似乎不行

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
修复，下个版本发布

**Comment by lytlucky** [comment]
@zhangdaiscott @TankCoder 请问下这个问题需要修改那块代码，提交记录没看到
