### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by wyue** [jeecgboot/jeecg-boot#4014]
##### 版本号：
3.3.0

##### 前端版本：

vue2

##### 问题描述：
请问j-modal组件如何打开默认全屏？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有个参数设置下
