### ISSUE TITLE
微服务新模块创建报错

### ISSUE THREAD

**Issue by xiaozahng** [jeecgboot/jeecg-boot#4017]
##### 版本号：
jeecg-boot 3.2.0

##### 前端版本：

vue3版？还是vue2版？请说明清楚

##### 问题描述：

用命令创建微服务模块,说找不到jeecg-cloud-gen:3.2.0这个文件,但是本地仓库有这个文件

##### 截图&代码：
![微信图片_20220831165405](https://user-images.githubusercontent.com/105843249/187639418-2232b470-ec4c-40cb-874e-ae1f26347afa.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://search.maven.org/artifact/org.jeecgframework.archetype/jeecg-cloud-gen

**Comment by liu595108672** [comment]
这个是要怎么做？去pom文件里面增加依赖吗？

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/199675281-53f0186b-be9c-4c9f-bfc0-af6878b1bc53.png)

**Comment by liu595108672** [comment]
知道我这边是什么原因引起的了。    3.4.0   需要用单引号括起来。
