### ISSUE TITLE
只能将详情页配置在第一层级或第二层级，第3层级就会无法访问或出现问题

### ISSUE THREAD

**Issue by TankCoder** [jeecgboot/jeecg-boot#4018]
##### 版本号：
3.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前的需求：要配置很多详情页面，并且不需要在左侧菜单中展示，仅做跳转使用。

但是使用官方示例配置后（将详情菜单设置为路由菜单+隐藏路由），无法使用/展示。

发现：

- 如果添加的是第三级菜单，将其设置为路由菜单+隐藏路由 ，通过URL的形式，无法直接访问到该菜单。未报404错误。使用$router.push时，URL变化了，但是页面打开的是它上一级的页面。

- 如果添加的是第二级菜单，将其设置为路由菜单+隐藏路由 ，通过URL的形式，可以访问到该菜单 （但是这样设置菜单结构，对于操作授权时不方便。）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以不配置菜单，直接在前端路由js里面写死
src\config\router.config.js

**Comment by TankCoder** [comment]
> 

感谢回复，这个是官方已知的问题吗？
我看过官方文档，确实可以直接写死，但是菜单的权限后边还是需要配置角色使用的， 这么改就不符合需求了。  还有别的解决方案吗？ @zhangdaiscott

**Comment by TankCoder** [comment]
> 

@zhangdaiscott  写死菜单，>=3级菜单也是无法访问的，它会直接访问到上一级别的组件。  我把高级详情放到了基本详情下边，访问高级详情时，页面实际展示的是基本详情。
