### ISSUE TITLE
JVxeTable动态切换列后页面不刷新并且校验失效

### ISSUE THREAD

**Issue by Haowensheng** [jeecgboot/jeecg-boot#4020]
##### 问题描述：
需求是根据主表字段选择不同的的内容后,明细会跟着改变填写不同的内容但是切换后产生了以下问题:
问题1.在动态切换列之后,明细不会跟着刷新,需要调用virtualRefresh()才会刷新,刷新后出现了问题2 
问题2,改变之后校验规则不生效了 我用的必填校验 ,我研究了会代码  前端不太行 没研究明白 我看的是watch里面的columns方法  
 也就是 validateRules: [{ required: true, message: '${title}不能为空' }]

**Comment by Haowensheng** [comment]
烦请大佬帮忙看看 🥹🥹🥹🥹🥹

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
JVxeTable 为了防止不必要的性能牺牲，没有做`deep`检测列变化，如果想要动态变更列，需要传一个新的列数组，如下图所示：

![image](https://user-images.githubusercontent.com/34293221/194855588-f28b176b-212e-43a1-abb8-9ec2fdaa4cd6.png)
