### ISSUE TITLE
三级菜单内容显示BUG

### ISSUE THREAD

**Issue by TankCoder** [jeecgboot/jeecg-boot#4021]
##### 版本号：
3.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
打开三级菜单时，展示的是二级菜单的内容。

我将基本详情页配置在高级详情页下方，点击后，

- URL显示为3级菜单：“/profile/basic”   即， 基础详情页的URL
- 但是打开的页面依然是高级详情页的内容，如图所示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/111105563/187934157-9765564f-5a3a-4778-b3a5-8517738fd68b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by TankCoder** [comment]
我用本地静态路由试了下，也会出现此问题。

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
![image](https://user-images.githubusercontent.com/27989856/198973348-65a69bd9-1d82-45b6-9819-179b22ff3e27.png)
测试无此问题
