### ISSUE TITLE
websocket连接校验失败，token不能为空

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#4022]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/188126199-acb50371-527a-4830-a95f-d5ed76bade5c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
最新后台ws加了token验证，你的前端代码是老的

**Comment by yangkui001** [comment]
好的，谢谢

**Comment by qhj210506** [comment]
你好，解决了吗？同样问题，我这缓存都清过了依然会有这个问题，如果更新前端代码应该更新哪个版本的，因为我是下载的压缩包，这应该是最匹配的版本

**Comment by qhj210506** [comment]
最新的jar不全，maven、Apache仓库没有部分jar，如：jeecg-boot-parent
![image](https://user-images.githubusercontent.com/83757152/202093435-fcab3c5c-5f66-4b7a-91fa-c9b66f2a11eb.png)
![image](https://user-images.githubusercontent.com/83757152/202093637-8389e2b8-06dc-4fd8-8297-74d045efc45f.png)

**Comment by qhj210506** [comment]
如果去掉还会报没有做错误处理，没有OnError
No error handling configured for [org.jeecg.modules.message.websocket.WebSocket] and the following error occurred
gateway:
![image](https://user-images.githubusercontent.com/83757152/202095448-26d0fac6-7a87-487b-9771-d654135a170e.png)

**Comment by zhangdaiscott** [comment]
> jeecg-boot-parent

![image](https://user-images.githubusercontent.com/3162115/202097622-8448ff22-b4f0-4540-b4b4-a97d9cacaded.png)

**Comment by qhj210506** [comment]
对对对，谢了

**Comment by yangkui001** [comment]
还有一种办法就是修改前端HeaderNotice.vue   
      // 前端旧版获取websock方式
      // this.websock = new WebSocket(url)
      // 改成如下所示 ，前端新版获取websock方式
      let token = Vue.ls.get(ACCESS_TOKEN)
      this.websock = new WebSocket(url, [token])

> 对对对，谢了
