### ISSUE TITLE
问题 oss外链经过转编码后，部分无效，大概在三分一；无需转编码直接返回即可

### ISSUE THREAD

**Issue by wang1223440313** [jeecgboot/jeecg-boot#4023]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
oss外链经过转编码后，部分无效，大概在三分一；无需转编码直接返回即可

##### 截图&代码：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
能具体说明代码位置吗

**Comment by wang1223440313** [comment]
org.jeecg.common.util.oss.OssBootUtil.getObjectUrl

![image](https://user-images.githubusercontent.com/39980681/189023676-3c5e796f-844c-4f6c-8279-485625cd289c.png)

**Comment by wang1223440313** [comment]
oss外链经过转编码后，直接tostring就能正常使用了，转编码后url有些内容就变了，最后是以=号结尾的，有三分之一的连接经过转编码后是无法访问的

**Comment by zhangdaiscott** [comment]
3q 已修复
