### ISSUE TITLE
IE11版本兼容问题

### ISSUE THREAD

**Issue by 517227989** [jeecgboot/jeecg-boot#4027]
##### 版本号：
2.0.1
##### 前端版本：vue3版？还是 vue2版？
VUE2
##### 问题描述：
IE11浏览器一直登录转圈
##### 截图&代码：
"name": "vue-antd-jeecg", "version": "2.0.1",
![image](https://user-images.githubusercontent.com/50901172/188775604-f43d29a0-c6af-4178-a583-1b1fee8aeb7e.png)
![image](https://user-images.githubusercontent.com/50901172/188775618-c3b5a1f2-4f16-495b-9b25-2c40c7e00379.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
删除qiankun相关代码

**Comment by 517227989** [comment]
@zhangdaiscott 
我的代码里面没有qiankun相关代码
![image](https://user-images.githubusercontent.com/50901172/188776959-22c1fb65-a50b-47dc-9e28-35436cec54c1.png)

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/188785625-6e0c7b4f-20ad-481f-ab1f-298bb4ef0ed3.png)

**Comment by 517227989** [comment]
> ![image](https://user-images.githubusercontent.com/3162115/188785625-6e0c7b4f-20ad-481f-ab1f-298bb4ef0ed3.png)

我的版本是2.0.1，没有最新版本里面的qiankun相关的

**Comment by zhangdaiscott** [comment]
哪不清楚了，不兼容的问题得自己查，或者看看历史issue
