### ISSUE TITLE
多页签模式，打开多个页签再切回上个页面，每次切换页面页面都会自动刷新，如何禁止刷新

### ISSUE THREAD

**Issue by hairuiVR** [jeecgboot/jeecg-boot#4028]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
菜单设置路由缓存就好了

**Comment by hairuiVR** [comment]
> 菜单设置路由缓存就好了

菜单里面写的外部链接呢？切换tab怎么禁止刷新

**Comment by zhangdaiscott** [comment]
外部也可以缓存吧，不重新加载iframe就行

**Comment by hairuiVR** [comment]
> 外部也可以缓存吧，不重新加载iframe就行

不行 用这个IframePageView，写了缓存路由，每次切换还是会刷新，大哥能不能认真点

**Comment by hairuiVR** [comment]
这个IframePageView 可以添加缓存吗，两个菜单都是外部链接 每次切换都刷新 ，我要专业的答案
