### ISSUE TITLE
聚合路由为什么是父子组件

### ISSUE THREAD

**Issue by z346158847** [jeecgboot/jeecg-boot#4029]
##### 问题描述：
聚合路由为什么是父子组件调用，按我的理解配置为聚合路由且下面的子路由隐藏后，可以在聚合路由的界面中对子路由进行跳转，而不是通过v-if父子组件显示，如果通过父子组件就算不配置聚合路由也可以实现吧？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/44332669/188821880-72668d79-3132-4573-b0f2-6c49aee0b160.png)

**Comment by zhangdaiscott** [comment]
ty
