### ISSUE TITLE
新建微服务模块启动报错

### ISSUE THREAD

**Issue by zhangmm1991** [jeecgboot/jeecg-boot#4030]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32173218/188834998-5d24dc73-cc21-4828-8568-cef8262b47bd.png)
![image](https://user-images.githubusercontent.com/32173218/188835087-bb167e54-145a-4d0d-b5f3-a2a40b392102.png)
![image](https://user-images.githubusercontent.com/32173218/188835614-e4e17695-4bee-441f-8c5d-df02ad06db37.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
日志表拷贝进去

**Comment by zhangmm1991** [comment]
测试用例日志分表是成功的，新建微服务模块也没问题，使用gateway都能测通。但是我自己新建一张业务表biz_sensor_data，复制了两张biz_sensor_data0和biz_sensor_data1，用biz_sensor_data生成代码，Nacos克隆jeecg-sharding.yaml生成的jeecg-synchdata-dev.yaml，修改里面的表名和分片列名（device_addr），启动成功后使用gateway添加数据没有达到分表的效果，数据都保存到biz_sensor_data里了
![image](https://user-images.githubusercontent.com/32173218/189030520-9242df81-d287-427f-9233-d462a6ab4d68.png)
![image](https://user-images.githubusercontent.com/32173218/189030630-23be15ba-c232-4b36-afac-b710eef0de67.png)
![image](https://user-images.githubusercontent.com/32173218/189030679-40c72e4a-4178-4ef6-8feb-d303b36b20f2.png)
![image](https://user-images.githubusercontent.com/32173218/189030801-6a9342ed-d8c0-436a-b301-1611fd6e371b.png)
![image](https://user-images.githubusercontent.com/32173218/189030841-4c69c300-a11f-49f2-bb9a-b3502b0bcd7b.png)
![image](https://user-images.githubusercontent.com/32173218/189030869-7006c1e3-2b7e-4f71-b28e-6c539a2e2a97.png)

**Comment by zhangmm1991** [comment]
怎么换成其它表做单库分表的，复制sys_log的表结构新建biz_log，biz_log0，biz_log1表，ShardingSysLog实体类的@TableName("biz_log")，Nacos里jeecg-sharding.yaml配置文件中sys_log替换成biz_log，启动成功后测试单库分表插入，数据都插入到biz_log表，没有达到分表的效果，没有执行StandardModTableShardAlgorithm类中的doSharding方法，除了sys_log能成功，换其他表都不能成功分表保存数据

**Comment by zhangdaiscott** [comment]
配置文件引入没成功吧？
1、nacos中配置文件有dev
![image](https://user-images.githubusercontent.com/3162115/192534753-e80adc84-4179-49c0-9e46-a8c82035898b.png)
2、引入的时候没加dev
![image](https://user-images.githubusercontent.com/3162115/192534829-fe93ba3c-1d49-45b7-a7c7-eea91de7389e.png)
