### ISSUE TITLE
高级查询失效

### ISSUE THREAD

**Issue by whoandwhere** [jeecgboot/jeecg-boot#4031]
##### 版本号：
3.2.0

online在线功能, 主题模板为 默认主题

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
高级查询失效
在更改权限后失效, 更改权限前正常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33681170/188838736-1711f18e-3e28-429a-8eed-d61f0b7c249f.png)

权限SQL:
更改前:
create_by ='#{sys_user_code}' or supporter= '#{sys_user_code}'  or responser = '#{sys_user_code}' or respon_dep = (select id from sys_depart where org_code ='#{sys_org_code}')
更改后:
create_by ='#{sys_user_code}' or supporter= '#{sys_user_code}' or checker= '#{sys_user_code}'  or responser = '#{sys_user_code}' or respon_dep = (select id from sys_depart where org_code ='#{sys_org_code}')

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请说明具体改的哪个文件

**Comment by whoandwhere** [comment]
Online表单开发--表单---数据权限--自定义SQL

权限SQL:

更改前:
create_by ='#{sys_user_code}' or supporter= '#{sys_user_code}' or responser = '#{sys_user_code}' or respon_dep = (select id from sys_depart where org_code ='#{sys_org_code}')
更改后:
create_by ='#{sys_user_code}' or supporter= '#{sys_user_code}' or checker= '#{sys_user_code}' or responser = '#{sys_user_code}' or respon_dep = (select id from sys_depart where org_code ='#{sys_org_code}')

添加的数据为:
supporter= '#{sys_user_code}'
