### ISSUE TITLE
生成代码功能：用生成的代码，配置前后端和菜单后，点击界面一直报错资源未找到

### ISSUE THREAD

**Issue by 2morning** [jeecgboot/jeecg-boot#4032]
##### 截图&代码：

![1662598598440](https://user-images.githubusercontent.com/57852159/189010270-84e116f1-c898-450c-a8ee-b2748233ecda.jpg)

![image](https://user-images.githubusercontent.com/57852159/189010346-ad46ca65-89d5-4ae6-9f98-6df5f8163e5e.png)

![image](https://user-images.githubusercontent.com/57852159/189010409-e66fb2d0-23cf-4b98-a7ea-8052249a3538.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台接口通吗
后台重启了吗

**Comment by 2morning** [comment]
后台重启过，怎么看后台接口通不通？
![image](https://user-images.githubusercontent.com/57852159/189012970-69be70c3-3774-4598-bdc8-222e50a9baaf.png)
