### ISSUE TITLE
不懂就问，为啥online表单功能没有开源代码

### ISSUE THREAD

**Issue by WallanceLee** [jeecgboot/jeecg-boot#4033]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
为什么online表单功能前后台代码没有开源，查看jar包发现还是用了部分代码混淆，小白请教，大神勿喷

##### 截图&代码：
不涉及代码功能

**Comment by zhangdaiscott** [comment]
因为此部分不开放
