### ISSUE TITLE
online的自定义弹窗，如何取消只能选择一条的限制？

### ISSUE THREAD

**Issue by jiazy-5280** [jeecgboot/jeecg-boot#4034]
##### 问题描述：online的自定义弹窗，如何取消只能选择一条的限制？
我的自定义弹窗是需要获取两条甚至以上的数据的，但是现在只能选择一条，多了就会提示请选择一条记录

又遇到一个新的问题，我放到列表中的按钮，link类型，这种应该是不需要选中记录的啊，为什么还会提示需要选中一条记录？？？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/93628463/189087264-2e704d75-0a9e-4c05-8345-9e11646b0d82.png)

union(){
  console.log(that)
  let rows = that.table.selectionRows;
  if(rows.length != 2){
    that.$message.warning('请选择两条记录！')
  }else{
    console.log(that)
    that.openCustomModal({
      //formComponent: 'info/res/ResUnion',
      title: '合并',
      width: 800,
    });
  }
},

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by jia13938505280** [comment]
啥意思？ty在哪用？

**Comment by jia13938505280** [comment]
> ty

啥意思？ty在哪用？

**Comment by OnlyShineTom** [comment]
官方:讨厌

**Comment by 45yangcoder** [comment]
hh

**Comment by jiazy-5280** [comment]
令人难过，官方不会没想到这个问题吧

**Comment by jiazy-5280** [comment]
又遇到一个新的问题，我放到列表中的按钮，这种应该是不需要选中记录的啊，为什么还会提示需要选中一条记录？？？

**Comment by tygithub1** [comment]
如果你没传参数row,系统默认从选中行中取数据，如果手动传了，就没有这个限制。
增强定义：
![image](https://user-images.githubusercontent.com/27989856/195756513-f108a3e0-dd19-4da2-9a77-cae1e8ea4125.png)
参数接收：
![image](https://user-images.githubusercontent.com/27989856/195756613-29696b8f-629e-4ee8-be5a-84a3da39eba5.png)
效果：
![image](https://user-images.githubusercontent.com/27989856/195756293-9d569d69-f3ec-43f0-aaac-9472948aa809.png)

**Comment by it-xhp** [comment]
你是付费版嘛 我看开源版 自定义弹窗好像是不行的

**Comment by it-xhp** [comment]
> 如果你没传参数row,系统默认从选中行中取数据，如果手动传了，就没有这个限制。 增强定义： ![image](https://user-images.githubusercontent.com/27989856/195756513-f108a3e0-dd19-4da2-9a77-cae1e8ea4125.png) 参数接收： ![image](https://user-images.githubusercontent.com/27989856/195756613-29696b8f-629e-4ee8-be5a-84a3da39eba5.png) 效果： ![image](https://user-images.githubusercontent.com/27989856/195756293-9d569d69-f3ec-43f0-aaac-9472948aa809.png)

你是付费版嘛 我看开源版 自定义弹窗好像是不行的

**Comment by it-xhp** [comment]
> 没传参数row,系统默认从选中行中取数据，如果手动传了，就没有这个限制。

这是自定义弹窗才能搞的吧  我看自定义弹窗好像是付费版
