### ISSUE TITLE
高级查询附表字段不能选

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4035]
##### 版本号：
2.4.2
3.3
都试过了

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
设计一对多主表和附表，主表和附表对应的字段都已勾选可查询，在测试的时候是可以在高级查询里查附表字段的，但在生成代码后在高级查询里不显示附表字段

##### 截图&代码：
生成代码的后自己的界面
<img width="243" alt="1662692900399" src="https://user-images.githubusercontent.com/15886620/189264077-18a8759b-b961-48b8-82ee-46984341e43e.png">
在线测试时的界面：
<img width="227" alt="1662692966130" src="https://user-images.githubusercontent.com/15886620/189264169-6a910ca9-d936-4191-9089-102977ea86e9.png">

请问要如何修改生成器生成的代码才能和在线测试时的功能一样？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码生成没实现这个逻辑
