### ISSUE TITLE
利用消息模板发送消息，模板里面配置的富文本没有效果

### ISSUE THREAD

**Issue by luotang123456** [jeecgboot/jeecg-boot#4036]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
利用消息模板发送消息，模板里面配置的富文本样式在实际消息查看中没有效果

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 3509282792** [comment]
同问，我今天试了试也是一样

**Comment by zhangdaiscott** [comment]
怎么用的？

**Comment by luotang123456** [comment]
> 怎么用的？

就是创建消息模板，然后根据这个消息模板去发消息，消息模板配置的用的是富文本
这个是我发消息的代码
            Map<String, String> map = new HashMap<>();
            map.put("orgName",sysBaseAPI.getDepartNamesByUsername(sysUser.getUsername()).get(0));
            map.put("projName",cospxSzglBatchVos.get(0).getProjName());
            map.put("salaryDate",DateUtil.formatDate(new Date()));
            map.put("name",cospxSzglDetail.getName());
            map.put("month", yearmonth);

            TemplateMessageDTO templateMessageDTO = new TemplateMessageDTO();
            templateMessageDTO.setFromUser(sysUser.getUsername());
            templateMessageDTO.setTitle(String.format("%s%s次数超上限",cospxSzglDetail.getName(),yearmonth));
            templateMessageDTO.setTemplateParam(map);
            templateMessageDTO.setTemplateCode(Constant.TEMPLATE_HIGH_TIMES);
            templateMessageDTO.setPriority(CommonConstant.PRIORITY_M);
            templateMessageDTO.setMsgCategory(CommonConstant.MSG_CATEGORY_2);
            List<LoginUser> sysUsers = sysBaseAPI.getUserByRoleCodes(Arrays.asList("govAdmin"));
            for(LoginUser toUser : sysUsers){
                templateMessageDTO.setToUser(toUser.getUsername());
                sysBaseAPI.sendTemplateAnnouncement(templateMessageDTO);
            }

**Comment by zhangdaiscott** [comment]
截图看下效果

**Comment by zhangdaiscott** [comment]
截图看看模板怎么设计的

**Comment by luotang123456** [comment]
> 截图看看模板怎么设计的

<img width="634" alt="1665380224299" src="https://user-images.githubusercontent.com/72056491/194804138-38bd0fd6-e37b-4923-8eed-b5d8a620037e.png">

**Comment by zhangdaiscott** [comment]
ws

**Comment by luotang123456** [comment]
> ws

??

**Comment by 1298191366** [comment]
未复现，请查看一下你的数据库存的是什么或者列表`通知模板`显示的是什么
测试效果图
前台模板配置
![image](https://user-images.githubusercontent.com/30997828/198951915-166e95c9-fc51-46d4-bba3-452b05ba7133.png)
后台代码
![image](https://user-images.githubusercontent.com/30997828/198952056-aa480a21-5353-4a73-9265-c570ae8fb92e.png)
信息发送
![image](https://user-images.githubusercontent.com/30997828/198952296-76f2b8f0-c50d-4328-9cf0-1922be2bb0fd.png)
数据库存储格式
![image](https://user-images.githubusercontent.com/30997828/198952951-79e03b7c-4d59-48f0-b4d2-8a57e12b0455.png)
