### ISSUE TITLE
限制上传文件的格式

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4037]
##### 版本号：

3.3
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
请问怎么在上传文件时限制上传文件的格式？比如我只想让用户上传pdf的格式的文件

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044010
设置上传类型
