### ISSUE TITLE
在线报表不支持子查询，解析报错

### ISSUE THREAD

**Issue by xiaoyizeng** [jeecgboot/jeecg-boot#4040]
##### 版本号：
3.4.0

##### 前端版本：
vue2版

##### 问题描述：
在线报表配置不支持子表查询

##### 截图&代码：
以下是正常情况，可以正常解析SQL
![image](https://user-images.githubusercontent.com/81517044/189801496-cb0c7de8-d090-46b3-97f1-e5241fc74c2e.png)
以下是子表查询语句，解析SQL返回失败
![image](https://user-images.githubusercontent.com/81517044/189801650-48f64939-5c22-4115-8306-eeba85328c23.png)
后台日志显示错误【net.sf.jsqlparser.statement.select.SubSelect cannot be cast to net.sf.jsqlparser.schema.Table】
![image](https://user-images.githubusercontent.com/81517044/189801728-a9476b7a-f244-49c4-a5bb-37368c095aa4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
已处理，请更新代码
