### ISSUE TITLE
代码生成,erp风格时,辅表mapper中的xml没有生成,也没有报错

### ISSUE THREAD

**Issue by jiangxiaozheng** [jeecgboot/jeecg-boot#4042]
##### 问题描述：代码生成,erp风格时,辅表mapper中的xml没有生成,也没有报错
日志打印出来, [1-n] 没有被替换
##### 截图&代码：
![image](https://user-images.githubusercontent.com/54165898/189902651-4a31361d-84e0-4719-a556-daa3bd295281.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没有任何提示，这个无法分析
