### ISSUE TITLE
查询配置的‘是否启用’列不生效

### ISSUE THREAD

**Issue by HuaJianZhong** [jeecgboot/jeecg-boot#4044]
##### 问题描述：Online表单开发-查询配置的‘是否启用’列存在bug。
操作步骤：1、勾选任一字段‘是否启用’，不点击保存。
                   2、取消‘是否启用’的勾选，点击保存。
                   3、进入在线表单，没有选中的字段出现在查询条件那里了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/39891957/190052069-5e5364e4-1574-4937-ab6f-51b968f58086.png)

![image](https://user-images.githubusercontent.com/39891957/190052155-07c6783b-32bc-42cb-8cc9-881e39f06d02.png)

**Comment by zhangdaiscott** [comment]
ty

**Comment by sjlei** [comment]
查询配置里的配置项是扩展配置，并不会真正控制是否显示查询条件，真正控制的是`页面属性`里的`是否查询`选项，当你这个选项没勾上的时候，在重新配置里点了启用会自动勾上，但取消勾选不会自动取消，防止出现问题，所以需要你手动去取消即可。

![image](https://user-images.githubusercontent.com/34293221/194850296-555d0f41-2c73-4488-8bc0-ca30a6b4e3fe.png)
