### ISSUE TITLE
编译test版本，弹窗后页面假死

### ISSUE THREAD

**Issue by Henryyanl** [jeecgboot/jeecg-boot#4046]
##### 问题描述：
通过 yarn build:test发布的版本，只要有弹窗再关闭窗口后页面就假死了，点击任何地方无反应

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看报什么错

**Comment by zhangdaiscott** [comment]
我这边测试无问题
