### ISSUE TITLE
在使用 nginx 部署前端后，再使用另一台服务器的 nginx 进行反向代理，不能正常加载的问题

### ISSUE THREAD

**Issue by ddwolf715** [jeecgboot/jeecg-boot#4048]
##### 问题描述：
在使用 nginx 部署前端后，再使用另一台服务器的 nginx 进行反向代理，不能正常加载。
前端要进行反向代理是需要什么特殊的配置吗？

情况说明：
后端和前端都部署在IP地址为 192.168.0.17 的服务器上，前端用 nginx 部署，访问地址分别为如下，且都可以正常访问和使用的。
http://192.168.0.17:8035/jeecg-boot
http://192.168.0.17:8036

需要使用另一台服务器进行反向代理，公司内的用户只能访问这个代理后的地址，后端已经配置成功，最终地址为如下，且是可以正常访问和使用
http://192.168.199.17/jeecg-boot-api

但前端用样的方法，无法正常加载，访问地址为
http://192.168.199.17/pc
访问代理后的地址，页面加载js和css等资源时，发现请求的地址是如下样例
http://192.168.199.17/js/chunk-fa1d133e.ae94ef8b.js

不是期望的，路径中带有 pc
http://192.168.199.17/pc/js/chunk-fa1d133e.ae94ef8b.js

##### 截图&代码：
以下是两个nginx的配置文件
-------------------
192.168.0.17 服务器的nginx
    server {
        listen       8036;
        server_name  jeecg-boot;

        location / {
            root   html;
            index  index.html index.htm;
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.html?s=$1 last;
                break;
            }
        }
    }    

192.168.199.17 服务器的nginx
server {
        listen       80;
        server_name  public_server;

        # 公司所有服务的统一入口，主页放置了所有服务的链接，作为入口，方便员工使用
        location / {
            root   html;
            index  index.html index.htm;
        }

        # api 后端
        location /jeecg-boot-api/ {
                proxy_pass              http://192.168.0.17:8035/jeecg-boot/;
                proxy_set_header        X-Forwarded-Scheme  $scheme;
                proxy_redirect          off;
                proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # web 前端
        location /pc/ {
                proxy_pass              http://192.168.0.17:8036;
                proxy_set_header        Host $host;
                #proxy_set_header       X-Real-PORT $remote_port;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 下面还翁公司其他服务的反向代理配置

        location ........以下省略
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043886#nginx_66

**Comment by ddwolf715** [comment]
> http://doc.jeecg.com/2043886#nginx_66

我的192.168.0.17服务器就是按这个文档配置的，是可以的，访问地址如下格式
http://192.168.0.17:8036/

但我要在以上基础，用另一台再配置反代理，提供给普通员工访问，后端反代理后没有问题，就前端有问题访问不了，

**Comment by ddwolf715** [comment]
这台192.168.199.17的服务器，是公司要做为统一的访问入口，提示给普通员工使用，所以要配置反代理，
发现前端怎么也配置不通，不知是不是前端是有什么特殊的配置要求或限制吗？

上面是两个nginx的配置文件，还各位大神支招，非常感谢。

**Comment by zhangdaiscott** [comment]
不清楚，这个服务器自己的配置，只能你自己看

**Comment by ddwolf715** [comment]
问题解决了，要改前端的publicPath，再重新部署到publicPath指定的目录，就可以了。
