### ISSUE TITLE
后端实体传递是否做了不同层实体隔离

### ISSUE THREAD

**Issue by yangyz** [jeecgboot/jeecg-boot#4050]
##### 问题描述：
后端 实体包名 主要作用与含义是？ 是否做了不同层实体隔离 比如： VO DTO PO 。。。等

##### 截图&代码：
![image](https://user-images.githubusercontent.com/6257884/190972825-02d4a3c2-8a4e-4a2b-9c23-203a24993d32.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
？

**Comment by yangyz** [comment]
请问 图片中 entity model  vo 实体有什么区别
