### ISSUE TITLE
Online表单能否支持目标数据库？

### ISSUE THREAD

**Issue by zxc1021** [jeecgboot/jeecg-boot#4054]
##### 版本号：
最新版

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
Online表单能否支持目标数据库？是非可跟Online报表一样可通过配置的方式配置数据库？

##### 截图&代码：
无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
