### ISSUE TITLE
企业微信官方通讯录同步接口调整

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4058]
##### 版本号：
v3.4.1

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
企业微信有调整导致官方的同步到企微失败

##### 截图&代码：
https://developer.work.weixin.qq.com/document/path/96079
![image](https://user-images.githubusercontent.com/90361617/191391434-87ebf18d-863d-49bf-b2c7-926739826c04.png)
![image](https://user-images.githubusercontent.com/90361617/191391471-c95d2bec-dc56-48af-8e85-e2979245ba32.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，由于企业微信接口调整，同步到本地功能不再支持，仅支持本地同步到企业微信。
