### ISSUE TITLE
多页签模式，嵌入外部链接例如百度和淘宝，在百度和淘宝两个页面来回切换收据如何防止刷新

### ISSUE THREAD

**Issue by hairuiVR** [jeecgboot/jeecg-boot#4062]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是iframe，url 他就是会刷新，加缓存也没有用

**Comment by zhangdaiscott** [comment]
试试这个方案
https://blog.csdn.net/qq_33475629/article/details/124884534
