### ISSUE TITLE
online 表单数据库配置不生效

### ISSUE THREAD

**Issue by findAgem** [jeecgboot/jeecg-boot#4063]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/41536144/191643130-1f1235f4-358d-4003-b372-c5f0974266e9.png)
![image](https://user-images.githubusercontent.com/41536144/191643156-ed30f0ae-b240-4046-b031-304434ad33bc.png)
![image](https://user-images.githubusercontent.com/41536144/191643174-e9076a09-a1d1-458c-af20-a0f79a278682.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
注释掉类org/jeecg/config/init/CodeGenerateDbConfig.java
