### ISSUE TITLE
多数据源设置validationQuery

### ISSUE THREAD

**Issue by 651418156** [jeecgboot/jeecg-boot#4066]
##### 问题描述：
设置多数据源oracle+SqlServer时，validationQuery设置报错，
如果设置SELECT 1 FROM DUAL，报错信息为
**2022-09-23 13:55:05.594 [Druid-ConnectionPool-Create-816421765]  [1;31mERROR [0;39m  [36mcom.alibaba.druid.pool.DruidDataSource:2781 [0;39m - create connection SQLException, url: jdbc:sqlserver://172.**.10.2:1433;DatabaseName=SenSor, errorCode 208, state S0002
com.microsoft.sqlserver.jdbc.SQLServerException: 对象名  'DUAL' 无效。**

如果设置SELECT 1，报错信息为
**2022-09-23 13:53:26.342 [Druid-ConnectionPool-Create-1803977656]  [1;31mERROR [0;39m  [36mcom.alibaba.druid.pool.DruidDataSource:2781 [0;39m - create connection SQLException, url: jdbc:oracle:thin:@39.**.***.***:1521:ORCL, errorCode 923, state 42000
java.sql.SQLSyntaxErrorException: ORA-00923: 未找到要求的 FROM 关键字**

如果不设置，报错信息为
**2022-09-23 13:57:35.350 [main] [1;31mERROR [0;39m  [36mdruid.sql.Statement:149 [0;39m - {conn-110005, stmt-120004} execute error. null
java.lang.NullPointerException: null**

##### 截图&代码：
![image](https://user-images.githubusercontent.com/79392888/191900307-576ac854-9080-41ab-9d72-0550ac80e574.png)

![image](https://user-images.githubusercontent.com/79392888/191900203-f27047f4-17ee-46fe-8e16-8710aaa4c3e7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043877
