### ISSUE TITLE
数据库链接参数建议

### ISSUE THREAD

**Issue by zwssunny** [jeecgboot/jeecg-boot#4067]
##### 问题描述：
由于使用微服务部署，很多地方需要修改数据库链接参数，很麻烦，增加很多挫败感！
建议不要用root作为用户参数，很容易跟其他系统冲突；数据库脚本同时创建一个默认的登录用户，这样就轻松了！
比如在jeecgboot-mysql-5.7.sql文件中，在创建数据库时候：
CREATE database if NOT EXISTS `jeecg-boot` default character set utf8mb4 collate utf8mb4_general_ci;
drop user if exists 'jeecg'@'%';
USE `jeecg-boot`;
create user 'jeecg'@'%' identified by 'jeecg123456';
grant all privileges on `jeecg-boot`.* to 'jeecg'@'%';
flush privileges;
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
微服务，数据库的配置不是在nacos的配置文件中吗
