### ISSUE TITLE
system微服务应用名称jeecg-system被更改之后无法登录

### ISSUE THREAD

**Issue by yangkui001** [jeecgboot/jeecg-boot#4068]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/50698315/191945111-be0b44f7-7b77-4dc2-b461-76412619920d.png)
![image](https://user-images.githubusercontent.com/50698315/191945767-b752803e-c617-4729-aacb-740dc31a2b2c.png)
![image](https://user-images.githubusercontent.com/50698315/191945805-5d7a5366-0380-4e74-96dc-ee7d50296be7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
全文搜索下就行

**Comment by yangkui001** [comment]
如何搜索呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] system微服务应用名称jeecg-system被更改之后无法登录 (Issue #4068)





 
全文搜索下就行
