### ISSUE TITLE
[模块引用问题]现在java后台的模块结构是system模块由api、biz和start组成，如果我新建了新的模块，可以引用biz模块吗？因为现在启动模块是start模块

### ISSUE THREAD

**Issue by buptyanxl** [jeecgboot/jeecg-boot#4071]
##### 版本号：
3.4.0

##### 问题描述：

现在java后台的模块结构是system模块由api、biz和start组成，如果我新建了新的模块，可以引用biz模块吗？因为现在启动模块是start模块。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
微服务独立模块的start 引用biz
如果是其他微服务项目，引入api
