### ISSUE TITLE
在线报表的sql中使用mysql的limit解析报错

### ISSUE THREAD

**Issue by fuzrong** [jeecgboot/jeecg-boot#4072]
##### 问题描述：
在线报表开发的时候，sql语句中含有limit 时解析报错，去除时ok，mysql版本5.7+

##### 截图&代码：

SELECT a.custom_name AS customName from
	popup_window_record limit 1;

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个是因为我们为了提升性能，在解析的时候自动加入了分页参数，与你的冲突了

**Comment by zhangdaiscott** [comment]
也可以理解为mybatis plus的分页bug，未考虑带limit情况

**Comment by zhangdaiscott** [comment]
下个版本修复
