### ISSUE TITLE
打印时只能生成一页内容

### ISSUE THREAD

**Issue by hjx44599** [jeecgboot/jeecg-boot#4074]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/49136510/192428386-1210e659-46d3-45a2-b644-53f9576c37d4.png)

![image](https://user-images.githubusercontent.com/49136510/192428330-8522f359-b370-40ab-b547-8d98e68f33b3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个插件没实现自动分页打印功能，得自己搞
