### ISSUE TITLE
<j-modal>全屏后切换非全屏前端会提示Cannot read properties of null（reading 'style'）

### ISSUE THREAD

**Issue by wjl-01** [jeecgboot/jeecg-boot#4078]
##### 问题描述：
<j-modal>全屏后切换非全屏前端会提示Cannot read properties of null（reading 'style'）

##### 截图&代码：

![image](https://user-images.githubusercontent.com/59073409/193226675-4e48977e-5c45-46c4-9c54-705d4630ee54.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wjl-01** [comment]
> ##### 版本号：/
> ##### 前端版本： vue2版
> ##### 问题描述：
> 全屏后切换非全屏前端会提示Cannot read properties of null（reading 'style'）
> 
> ##### 截图&代码：
> ![image](https://user-images.githubusercontent.com/59073409/193226675-4e48977e-5c45-46c4-9c54-705d4630ee54.png)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
修复，下个版本发布
