### ISSUE TITLE
Online报表生成代码，动态参数没有出现。

### ISSUE THREAD

**Issue by yshaoliang** [jeecgboot/jeecg-boot#4079]
##### 问题描述：Online报表设置了参数，生成的代码提交请求的时候URL里并没有关于该参数的传递。
请问，Online报表，生成的代码中该如何把动态参数添加进去？使得查询出来的数据符合业务需求。

##### 截图&代码：
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/50801985/193442077-21694dde-f8fe-48eb-95c1-c7497e65bba9.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
Online报表，生成的代码是什么意思？
这块不生成代码，是在线功能

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/3078798
