### ISSUE TITLE
js增强 that.changeOptions方法对 下拉搜索框不起作用么？

### ISSUE THREAD

**Issue by czcz1024** [jeecgboot/jeecg-boot#4083]
3.4.2 vue2版本测试
在js增强中，使用 that.changeOptions方法改变下拉框的选项
如果下拉框类型是 下拉框 就可以，如果是下拉搜索框 则不起 作用
这是就这么设置的，还是我哪里没搞对？

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
只能改变下拉框
