### ISSUE TITLE
去掉注册页面手机接收验证码的功能

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4085]
##### 版本号：

3.3
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
由于部署的环境不能连接外网，所以在注册页面也不能有接收手机验证码的步骤，请问有没有什么方法屏蔽手机接收验证码这个功能？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
哪你改逻辑，取消验证码规则
