### ISSUE TITLE
菜单栏在页面缩放后再次展开消失不见

### ISSUE THREAD

**Issue by man-tao** [jeecgboot/jeecg-boot#4086]
版本号：2.1.3

 前端版本： vue2版

问题描述：左侧的菜单栏在缩放后，再次展开会消失不见

 截图&代码：

![项目正常页面](https://user-images.githubusercontent.com/92165522/194732256-0719975a-7e33-496f-80ca-03bf3b3f4da5.png)
![页面缩放再次展开后的](https://user-images.githubusercontent.com/92165522/194732287-9affb755-70c8-49de-8e40-e6dc41f73125.png)

**Comment by zhangdaiscott** [comment]
版本太老了，无法处理
