### ISSUE TITLE
外部链接菜单打不开，白屏

### ISSUE THREAD

**Issue by skybabydad** [jeecgboot/jeecg-boot#4087]
##### 版本号：
3.4.2（

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
设置多个外部链接作为二级菜单,但就是打不开

##### 截图&代码：
配置菜单项
![image](https://user-images.githubusercontent.com/13517500/194756673-21ad5a26-2046-472e-933c-19dde65f9f0b.png)

控制台显示 router  不存在
![image](https://user-images.githubusercontent.com/13517500/194756642-d58f53b2-a4de-4ef3-867c-a0a2d2876c21.png)

点击菜单项
![image](https://user-images.githubusercontent.com/13517500/194756701-b601383a-b271-4143-8510-8c6607adabf2.png)

白屏

![image](https://user-images.githubusercontent.com/13517500/194756727-3c5be2c6-d2cb-46d1-919a-2e8eb4d6d207.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/194759968-e254d5e9-d5c8-413c-b1e2-60204e7919d4.png)
设置成否

**Comment by skybabydad** [comment]
还是有问题，如下：
按照zhangdaiscott说法关闭路由菜单
![image](https://user-images.githubusercontent.com/13517500/194791175-7bccc4f5-bffb-43b1-bf78-f3c37ff885cd.png)

角色授权无误
![image](https://user-images.githubusercontent.com/13517500/194791218-3864b782-0d80-45d3-95fc-3d772598c1a6.png)

看到链接，并点击
![image](https://user-images.githubusercontent.com/13517500/194791401-662dac12-79f4-4eef-8259-10873a4baa29.png)

出现404错误
![image](https://user-images.githubusercontent.com/13517500/194791470-fded7847-8f2b-433e-9b74-cb10e6b41f55.png)

**Comment by skybabydad** [comment]
最终解决了，注意以下点：
1、外链的上级菜单要开启“是否路由菜单"
2、外链的上级菜单”前端组件“配置为”layouts/RouterView“，注意，即使看着正确，有可能复制粘贴错误，导致失效，这个错误不容易发现
3、外链的“是否路由菜单“要设置为”是“，这点与二楼的回答不一致。
4、外链的”前端组件“配置为”layouts/IframePageView“，也可由于复制粘贴错误导致失败，这个错误不容易发现
5、外链既可以弹出新窗口打开，也可以在IFRAME内打开。如果出现it set 'X-Frame-Options' to 'sameorigin'提示，是因为外链所在服务器不允许。如果是自己的系统，可以在需要内嵌链接的服务器上设置HTTP头 x-frame-option。例如davinci的分享链接就可以嵌在IFRAME内
