### ISSUE TITLE
Online表单开发代码生成下载到本地报错

### ISSUE THREAD

**Issue by charmingPing** [jeecgboot/jeecg-boot#4088]
##### 问题描述：
前端nginx部署，后端jar包启动；
Online表单开发生成代码后下载到本地报错，413请求体过大；
有的成功有的不成功

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45278072/194805489-35ae3b42-7306-452e-a935-b36358500e70.png)

![image](https://user-images.githubusercontent.com/45278072/194805250-b7189a12-cdb8-423d-ab4c-db294693adaa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前端nginx配置下，大小

**Comment by charmingPing** [comment]
http，server，location都加上了配置，导出还是报错，请问这个是咋回事？
![image](https://user-images.githubusercontent.com/45278072/194997599-9e3ea012-1721-4589-9a7b-36c1913932da.png)

**Comment by zhangdaiscott** [comment]
在根上面加

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/195007719-a7dfe30d-8c62-44c4-a148-f80227367062.png)

**Comment by charmingPing** [comment]
http、server、location三个位置都加上了，还是报错，难道还有别的配置？
![image](https://user-images.githubusercontent.com/45278072/196325283-2d558739-c716-433a-99b7-b3bd1c01f065.png)
