### ISSUE TITLE
导入的数据库表单没有createTime字段，然后生成的代码，不知在何处重写排序

### ISSUE THREAD

**Issue by kailin98** [jeecgboot/jeecg-boot#4089]
##### 问题描述：
导入的数据库表单没有createTime字段，然后生成的代码，不知在何处重写排序

/* 排序参数 */
isorter:{
column: 'createTime',
order: 'desc',
},
Originally posted by @zhangdaiscott in https://github.com/jeecgboot/jeecg-boot/issues/244#issuecomment-507013118

##### 截图&代码：
生成的代码结构如下
![image](https://user-images.githubusercontent.com/40024182/194975436-7d7cb82e-3997-409f-a119-8ebbc4a658fe.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2426559
3
