### ISSUE TITLE
提示:很抱歉,资源未找到

### ISSUE THREAD

**Issue by moker321** [jeecgboot/jeecg-boot#4090]
##### 版本号：
3.4.0last

##### 问题描述：
把online中的表格,点功能测试,突然出现错误显示"资源未找到",但是里面各种功能都没问题,可以增删改查,就是一直有弹窗提示
后台显示拦截了get请求,前端报404
主要是本来没遇到过这个情况,我生成几次代码以后开始出现了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41774278/195299833-b0a9aef2-12f2-4402-907b-8aa2b66536ac.png)

![image](https://user-images.githubusercontent.com/41774278/195300272-a7f2a65a-e51a-49e4-8c83-ed0c2346e414.png)
![image](https://user-images.githubusercontent.com/41774278/195300459-6bc81045-5040-4edc-9108-ea638725b70e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你配置online的菜单了？

**Comment by moker321** [comment]
配置了,也授权了, 和它同个菜单下的另一个就没问题,就这两个刚弄好的表出现这个问题了,不知道哪里出了问题
![image](https://user-images.githubusercontent.com/41774278/195308925-533aa950-c56e-444b-a3cf-e8d3a52788c2.png)
![image](https://user-images.githubusercontent.com/41774278/195309099-3823a7a9-06e7-4b7d-bb42-ffdd75efc997.png)

**Comment by moker321** [comment]
而且,我用代码生成后的页面打开都是没有这个弹窗的

**Comment by zhangdaiscott** [comment]
删除，退出重新登录
