### ISSUE TITLE
多级路由缓存问题

### ISSUE THREAD

**Issue by NameAce** [jeecgboot/jeecg-boot#4091]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
在菜单配置里面设置了缓存路由，一级二级菜单没有问题，可以缓存，但是三级以上的菜单缓存不了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
修复了，请更新代码

**Comment by NameAce** [comment]
这样处理是不是会导致左边菜单栏展示有问题，this.$route.matched匹配到的routes不对。导致openKeys数据不正确从而菜单栏不展开。

**Comment by zhangdaiscott** [comment]
？

**Comment by NameAce** [comment]
就是现在点击菜单的时候，左边的菜单栏会收缩起来。

**Comment by zhangdaiscott** [comment]
更新吧

**Comment by qlf5027849** [comment]
很傻逼的一个解决方案，甚至比不缓存路由更影响用户体验
