### ISSUE TITLE
后端不想使用的依赖如何排除！

### ISSUE THREAD

**Issue by DreamMasteryang** [jeecgboot/jeecg-boot#4092]
##### 版本号：
3.4.2

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
jeecgboot 后端不想使用的依赖如何不加载bean，如org.jeecg.modules.jmreport.desreport.dao包下的bean不想使用，不加载bean。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/66147123/195485470-db254fc9-8b45-4046-aca9-06cda01f627d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven 排除

**Comment by DreamMasteryang** [comment]
minidao，没找到在哪里引入的依赖

**Comment by zhangdaiscott** [comment]
看看有没有这个配置，自定义扫描路径即可
![image](https://user-images.githubusercontent.com/3162115/195496693-7f4165ce-c4d1-4d4e-9efb-38ab6cebdfc8.png)

**Comment by DreamMasteryang** [comment]
![image](https://user-images.githubusercontent.com/66147123/195501750-e8da9a07-0b38-4a07-a9d4-61a122a3aab9.png) 
太麻烦了，这里面有东西被引用了，想排除和这个积木这么繁琐吗
