### ISSUE TITLE
less.modifyVars() 只对 @primary-color 生效

### ISSUE THREAD

**Issue by wanfzz** [jeecgboot/jeecg-boot#4094]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/45428227/195745473-9372251b-5110-4be9-bab1-d5a70cd36b6c.png)
![image](https://user-images.githubusercontent.com/45428227/195745507-63f23acc-d52e-4512-8b38-dc11c68fdbe6.png)
![image](https://user-images.githubusercontent.com/45428227/195745531-4357a9c3-ff75-4f1f-abf0-0a4219717f85.png)

**Comment by zhangdaiscott** [comment]
vue2?

**Comment by wanfzz** [comment]
已解决
