### ISSUE TITLE
token过期先加载页面然后才提示token过期

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#4097]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
第一天正常使用，第二天登录时在登录页面正在输入密码，页面突然刷新，提示token过期。
再次输入账号密码可正常登录

##### 截图&代码：
暂无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Chris-Arith** [comment]
> 这个是因为你浏览器缓存了一个过期的token导致 只有请求通过后台才能验证token是否过期，前端页面无法判断

明白，那这个只能通过延长token过期时间才能稍微改善一下体验对吧？

**Comment by zhangdaiscott** [comment]
也有个方案，点击登录的时候，先清理掉老的token缓存
