### ISSUE TITLE
Online在线开发，附表打勾了排序时间字段并且设不设置扩展参数，都无效

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#4099]
##### 截图&代码：

Online在线开发，附表打勾了排序时间字段并且设不设置扩展参数，都无效

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
附表？排序针对的是列表，不是表单打开的子表

**Comment by 378680487** [comment]
> 

不是有个主表，附表功能吗，在附表里面设置排序，生成出来的，附表那里没有效果

**Comment by zhangdaiscott** [comment]
附表不支持
