### ISSUE TITLE
目前框架都是用uuid做主键，mysql uuid性能比自增的差，有考虑改成自增long类型主键吗

### ISSUE THREAD

**Issue by iorilchen** [jeecgboot/jeecg-boot#4101]
##### 问题描述：
目前框架都是用uuid做主键，mysql uuid性能比自增的差，有考虑改成自增long类型主键吗，跟ruoyi一样

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前用的是雪花ID，虽然默认生成的id是string，你生成后可以改成long类型
