### ISSUE TITLE
后端地址拼接文件名，无法访问

### ISSUE THREAD

**Issue by DotNeter-Hpf** [jeecgboot/jeecg-boot#4103]
##### 截图&代码：
yml文件：
![image](https://user-images.githubusercontent.com/62707731/196347955-71e4c1b3-b420-428f-b187-b616296e2ea2.png)

WebMvcConfiguration文件：
![image](https://user-images.githubusercontent.com/62707731/196348070-ead596b5-7474-4e15-a9d7-a4326401a810.png)

ShiroConfig文件：
![image](https://user-images.githubusercontent.com/62707731/196348123-decf865c-27b6-4aeb-a7f6-e734fbbba08f.png)

已确认此路径下有mp4文件
![image](https://user-images.githubusercontent.com/62707731/196348355-512d9ea3-29ba-499e-9c28-bab1e6d8d63a.png)

**Comment by zhangdaiscott** [comment]
自己加的逻辑，我们不负责
