### ISSUE TITLE
v-has的bug

### ISSUE THREAD

**Issue by a2995921969** [jeecgboot/jeecg-boot#4106]
##### 版本号：

3.3.0
##### 前端版本：vue3版？还是 vue2版？

vue2版
##### 问题描述：
官网文档说v-has多个权限可以用逗号隔开 试了后发现不行, 我的用法 v-has="'seniorAppraiser,appraiser'"
##### 截图&代码：
![image](https://user-images.githubusercontent.com/64623626/196596368-ac974e74-dc62-41cd-af0b-97dbd6d28a4f.png)
![image](https://user-images.githubusercontent.com/64623626/196596378-f76738de-3f22-4103-acc8-9a7464a4ef5b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
不支持多个，目前支持一个
