### ISSUE TITLE
新增用户信息，点击确认，无法新增，提示操作失败，后台提示sql执行失败，不知道什么原因，执行的sql和前台的配置字段不一样

### ISSUE THREAD

**Issue by aikesaier** [jeecgboot/jeecg-boot#4107]
##### 截图&代码：
 
![DSM9P)G%UFC_}7%L_IMOKR7](https://user-images.githubusercontent.com/42740810/196639740-d339cc13-e403-4e88-9226-475cc2fff8c2.png)

![X`SXHFN(N{`VDE3~L5 Y6IQ](https://user-images.githubusercontent.com/42740810/196639878-935369eb-e163-4066-9efc-7f9b1673a9f0.png)

![62 NFS YNV}2YJ4C5G6CC5G](https://user-images.githubusercontent.com/42740810/196639913-bba706ee-717f-4db4-8e7d-1631e1161bfc.png)

**Comment by zhangdaiscott** [comment]
测试无问题，自己debug看看
