### ISSUE TITLE
平台用户登录失败锁定用户

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4109]
##### 版本号：
 v3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

我们平台没有登陆失败几次锁定账号，锁定时长，这是安全漏洞，等保也会扣分
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
