### ISSUE TITLE
富文本控件tinymce 上传到后台的图片如何配置不带原文件名

### ISSUE THREAD

**Issue by zhangchunkui** [jeecgboot/jeecg-boot#4110]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/15085549/196738010-28f502bb-e2cf-48b9-b111-4bb4f5bc4183.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自定义上传接口就行
![image](https://user-images.githubusercontent.com/3162115/196981959-861a3376-e661-47ce-8793-e507762cdf21.png)
