### ISSUE TITLE
树结构和一对一

### ISSUE THREAD

**Issue by caleb-hxs** [jeecgboot/jeecg-boot#4113]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

您好，我想问问您，用代码生成器在表本来是树结构基础下，还能用树节点与别的表一对一关联吗
##### 截图&代码：

![Uploading Snipaste_2022-10-20_13-15-08.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
描述过于简单，请详细说明你的需求

**Comment by caleb-hxs** [comment]
![Snipaste_2022-10-20_13-15-08](https://user-images.githubusercontent.com/116248596/196864584-f03d858e-2aec-4ffb-b41d-9fecf94ddfcd.png)
![Snipaste_2022-10-20_13-38-24](https://user-images.githubusercontent.com/116248596/196865015-123670cd-d5a2-49d6-916b-3892ee9acf29.png)
您好，即我有张表即做主表有是树结构可以的吗

**Comment by zhangdaiscott** [comment]
代码生成后，手工改造实现

**Comment by caleb-hxs** [comment]
好的谢谢
