### ISSUE TITLE
报表的数据规则权限设置在功能测试中是正常的，但是在JPopup上是无效的

### ISSUE THREAD

**Issue by blackknifes** [jeecgboot/jeecg-boot#4114]
##### 问题描述：
报表的数据规则权限设置在功能测试中是正常的，但是在JPopup上是无效的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9638801/196866813-c51465a3-bcef-4bb6-91ee-2deaa39397e8.png)
![image](https://user-images.githubusercontent.com/9638801/196866846-988948c7-752e-4067-bdce-6484a23bd99b.png)

**Comment by zhangdaiscott** [comment]
数据权限是针对菜单配置的，popup不走菜单逻辑，所以不支持数据权限
