### ISSUE TITLE
报表动态参数问题

### ISSUE THREAD

**Issue by wangsiyue** [jeecgboot/jeecg-boot#4116]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/24864022/196916122-db2e5125-a696-426b-8fb8-27f0def5b5b1.png)
![image](https://user-images.githubusercontent.com/24864022/196916189-7585f545-729a-41a7-9d78-0b4459b96754.png)
![image](https://user-images.githubusercontent.com/24864022/196916341-304b7a5c-9120-40fa-b1a6-dcf1bea7698d.png)
![image](https://user-images.githubusercontent.com/24864022/196916414-5405bf59-4678-4a9e-8699-0705ba326f5c.png)
![image](https://user-images.githubusercontent.com/24864022/196916465-a849a02d-5269-4513-b511-8b86a759693d.png)
![image](https://user-images.githubusercontent.com/24864022/196916640-86097e89-b390-4d30-ae7d-fa5c4c7db20e.png)
![image](https://user-images.githubusercontent.com/24864022/196917155-2a949e9c-feba-42fa-8058-c3332c62da40.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你如果是想用sex作为查询条件，不需要设置 ${sex}参数
 ${sex}用法主要是给路由参数用的

**Comment by wangsiyue** [comment]
你好，我这个主要是整的一个简单测试，因为我们有许多 【统计】的功能，会根据很多条件查询统计，比如页面只需要展示2个字段，但是实际条件过滤选择那块会有5个条件选择
![image](https://user-images.githubusercontent.com/24864022/197089218-6fe94ba9-41dd-4029-bdb2-b891b03b42c9.png)
；

**Comment by wangsiyue** [comment]
主要是 选择的条件不起作用，默认的可以查询出数据，但是选择另外一个值就不得行了，和那个sex一样，为啥选择了sex的非默认值就不能查询出了呢，现在就是配置的默认参数可以查，写了其他的参数就不能查询到数据，后台也没有报错啥的。【复杂的也没问题，还有积木报表可以尝试】，就是**参数选择**的问题。积木后边会看看的。

**Comment by wangsiyue** [comment]
![image](https://user-images.githubusercontent.com/24864022/197091227-6dc75720-9644-481b-8a12-a85a054b3250.png)
![image](https://user-images.githubusercontent.com/24864022/197091273-d2a6eaf3-1012-4763-bbc5-e321cc1e5ed5.png)
![image](https://user-images.githubusercontent.com/24864022/197091308-3ca590b2-3dee-4c16-b62e-ba19f48af3d1.png)
![d30e6efe953d05e3d2ce3ffcf85b87f](https://user-images.githubusercontent.com/24864022/197091989-2fc4b313-afbc-497a-b7f3-3378d37e3268.png)

就这样的，我咋控制动态参数呢，选择的日期和默认值一样，就查不出

**Comment by lkmtao** [comment]
这个解决了吗？

**Comment by lkmtao** [comment]
路由传参只能读取默认值，无法读取动态参数，是存在这个问题吗？

**Comment by lkmtao** [comment]
路由传参只能读取默认值，无法读取动态参数，是存在这个问题吗？ @zhangdaiscott
