### ISSUE TITLE
online代码生成Tab风格，新增数据中的字表tab页面错乱

### ISSUE THREAD

**Issue by james-curtis** [jeecgboot/jeecg-boot#4117]
##### 版本号：
后端版本：https://github.com/jeecgboot/jeecg-boot/commit/5558c302230440eb3dbc7f1c0d2773b44a27b175
前端版本：https://github.com/jeecgboot/jeecgboot-vue3/commit/1dff1f0d9347fac32e97093d5525cdc277027786

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online代码生成Tab风格，新增数据中的字表tab页面错乱

##### 截图&代码：

![image](https://user-images.githubusercontent.com/49338067/197108949-e14f15c4-d997-4013-86c9-35d86baf9b31.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
