### ISSUE TITLE
online功能测试中无法正常显示主题模板

### ISSUE THREAD

**Issue by james-curtis** [jeecgboot/jeecg-boot#4118]
##### 版本号：
后端版本：https://github.com/jeecgboot/jeecg-boot/commit/5558c302230440eb3dbc7f1c0d2773b44a27b175
前端版本：https://github.com/jeecgboot/jeecgboot-vue3/commit/1dff1f0d9347fac32e97093d5525cdc277027786

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online功能测试中无法正常显示主题模板，只能显示默认的jvxe，erp，tab，inner都不行

##### 截图&代码：
![image](https://user-images.githubusercontent.com/49338067/197109215-88091669-16d5-4b0c-841e-7901bbe29f55.png)
![image](https://user-images.githubusercontent.com/49338067/197109302-3119fad3-b5f6-4f14-aeb1-a6a9f94b3fcd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue3版本，不打算实现哪三套风格了
