### ISSUE TITLE
JSelectMultiUser 用户多选组件 查询bug

### ISSUE THREAD

**Issue by a2995921969** [jeecgboot/jeecg-boot#4120]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue2版本

##### 问题描述：
默认存储的值是realname， 但是改为id后 查询也会变为id查询， bug地方在部门管理 选择部门负责人处

##### 截图&代码：
![image](https://user-images.githubusercontent.com/64623626/197150932-43a78936-ffc0-4402-91db-c61da6eab99c.png)![image](https://user-images.githubusercontent.com/64623626/197150770-2418efb2-ee62-4628-8b53-609ec7cc6c23.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
但是改为id后 查询也会变为id查询，这个逻辑不是对的吗
