### ISSUE TITLE
3.4.3 vue2版本的菜单会自动折叠

### ISSUE THREAD

**Issue by yanmeng-liang** [jeecgboot/jeecg-boot#4121]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/55771760/197187144-67f8e2fe-5480-4c10-a506-6ec709a73247.png)

![image](https://user-images.githubusercontent.com/55771760/197187242-c2d0682d-3754-425d-91b5-c8221ad393aa.png)

下载下来后启动项目出现的问题

**Comment by zhangdaiscott** [comment]
加这个逻辑导致的，如果不需要三级以上的菜单缓存，可以删除
https://github.com/jeecgboot/ant-design-vue-jeecg/commit/d05a54abec0038038d3c5df2bf90c58a66b66131
