### ISSUE TITLE
部门管理员能获取系统全部角色

### ISSUE THREAD

**Issue by MichaelZhao315** [jeecgboot/jeecg-boot#4122]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
部门管理员角色，在管理本部门用户的分配角色时，能获得全系统的角色，导致权限设置泄露，是新版代码有问题吗？
请问这是什么问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/105337053/197344333-6ce117dd-3204-451c-820e-e5f74b67d968.png)
![image](https://user-images.githubusercontent.com/105337053/197344383-41b070bf-05c4-439d-93e1-0d7e899cbd17.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已经修复，下个版本发布
