### ISSUE TITLE
引入openlayers的css文件出错。

### ISSUE THREAD

**Issue by EVELEs** [jeecgboot/jeecg-boot#4124]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
前端引入openlayers包的 ol.css 文件后，npm run serve报错。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/31362251/197669331-7a7440f7-a653-4321-9ea8-b62f1608324f.png)
![image](https://user-images.githubusercontent.com/31362251/197669391-d6c13a6e-7b35-47dc-869e-e3c6dbba31b3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己加的代码，请自己分析
