### ISSUE TITLE
/sys/duplicate/check存在sql注入漏洞

### ISSUE THREAD

**Issue by azraelxuemo** [jeecgboot/jeecg-boot#4129]
[jeecg-boot漏洞.pdf](https://github.com/jeecgboot/jeecg-boot/files/9858362/jeecg-boot.pdf)

**Comment by zhangdaiscott** [comment]
你这个是哪个版本，针对注释这种我们处理过

**Comment by azraelxuemo** [comment]
就是最新的，但是可以绕过



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 下午3:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] /sys/duplicate/check存在sql注入漏洞 (Issue #4129)




 
你这个是哪个版本，针对注释这种我们处理过

**Comment by zhangdaiscott** [comment]
截图版本号

**Comment by azraelxuemo** [comment]
你们自己看我发的内容，里面你们加check了啊，但是check有问题，可以被bypass我已经说的很详细了，我是直接clone你们的项目



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] /sys/duplicate/check存在sql注入漏洞 (Issue #4129)




 
截图版本号

**Comment by zhangdaiscott** [comment]
改成这样就好了
![image](https://user-images.githubusercontent.com/3162115/198869233-317be4e0-71a1-480e-977a-7801b111fd7d.png)

**Comment by azraelxuemo** [comment]
okok好的好的，因为我看到的是checksql可以被绕过，所以就提出来了哈哈哈2333



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月30日(周日) 下午4:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] /sys/duplicate/check存在sql注入漏洞 (Issue #4129)




 
改成这样就好了

**Comment by azraelxuemo** [comment]
<img width="611" alt="截屏2022-10-31 10 16 06" src="https://user-images.githubusercontent.com/60163868/198917504-cc64acb4-3a67-419a-9bed-86de83a2466d.png">
这个是我的版本号

**Comment by azraelxuemo** [comment]
您看我详细的，我知道你们patch了但是你们关键字后面有空格
<img width="1170" alt="截屏2022-10-31 10 28 39" src="https://user-images.githubusercontent.com/60163868/198918804-635bd245-d5c3-4085-bd21-9c169499f79c.png">
updatexml(1,(select/**/if(length("aaa")>5,1,sleep(10)) union select/**/1),1)
这是我输入的，过滤之后是这样的
<img width="948" alt="截屏2022-10-31 10 30 24" src="https://user-images.githubusercontent.com/60163868/198918855-50221202-9d38-4a8d-8cf9-cee806191276.png">
您看您这个规则是检测不到的
我的意思就是您要把select后面的空格删掉，这样就不会被绕过

**Comment by azraelxuemo** [comment]
我个人建议还是把sql注入里面的空格删掉
因为你们替换了/**/
但还可以用()绕过
updatexml(1,(select(if(length("aaa")>5,1,sleep(10)))union select(1)),1)
所以索性你们就不替换/**/这些
然后直接把输入的字符串转成小写
判断有没有select,这种关键字

**Comment by zhangdaiscott** [comment]
已修复

**Comment by azraelxuemo** [comment]
好的，辛苦嘞

**Comment by ninggf** [comment]
拼接SQL，你们是认真的！！！

**Comment by ninggf** [comment]
拼接SQL，你们是认真的！！！

**Comment by sleepyGao** [comment]
getting comments
