### ISSUE TITLE
进入低代码开发，online表单开发，没有数据，提示token失效，请重新登录。已经清空vite缓存，还是不管用

### ISSUE THREAD

**Issue by aikesaier** [jeecgboot/jeecg-boot#4132]
##### 截图&代码：
![` TSI}P3DY2$Z)BTL1G_N5U](https://user-images.githubusercontent.com/42740810/197919926-3b182351-7355-42cf-b8a0-4f37214bf2f3.png)

![ZTLJ_UQT%QL@U90}M5SHHWT](https://user-images.githubusercontent.com/42740810/197920044-55601d59-3bb9-4c5a-9573-0c6f807ecb90.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已经发现，请在调查

**Comment by zhangdaiscott** [comment]
暂时还原回    ` "@jeecg/online": "3.4.3-beta",`
好像可以，可以尝试下，记得把报错代码注释掉

**Comment by zhangdaiscott** [comment]
https://gitee.com/jeecg/jeecgboot-vue3/commit/6dfcfbcf2ae22fc15b01886ca29be5a980607090

**Comment by zhangdaiscott** [comment]
已经修复，请更新vue3代码
