### ISSUE TITLE
如何实现一个输入框模糊查询两个字段

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#4135]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2版本

##### 问题描述：
如何实现一个输入框模糊查询两个字段

##### 截图&代码：
比如说，页面上有一个输入框叫产品信息，输入后去匹配产品编码和产品名称两个字段，只要匹配到了其中一个就返回这条数据，目前有这样的功能吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台改下查询逻辑
