### ISSUE TITLE
online表单加载速度慢的问题

### ISSUE THREAD

**Issue by lch245298** [jeecgboot/jeecg-boot#4136]
##### 问题描述：
online表单加载的时候是不是还得从数据库里边读取配置，比自开发表单加载速度感觉还慢不少
把这个加载放到内存中里边，还不用读文件和数据库，速度会提高不少吧

##### 截图&代码：

![image](https://user-images.githubusercontent.com/62693683/198165085-1557cbc9-47aa-4783-9f14-b6026c96744c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是的，但是有redis层缓存
