### ISSUE TITLE
在多数据源模式下数据字典Dict不能指定自定义数据源

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4138]
##### 截图&代码：
![输入图片说明](https://images.gitee.com/uploads/images/2022/0613/134853_1e114d0d_1143419.png "屏幕截图.png")

希望可以增加数据源指定方法,通过该方法可以像@Ds那样指定自定义数据字典的数据源

**Comment by BruceOuyang** [comment]
> ##### 版本号：3.2.0
> ##### 问题描述：在多数据源模式下数据字典Dict不能指定自定义数据源
> ##### 截图&代码：
> ![输入图片说明](https://camo.githubusercontent.com/cf49caeeedc57c6340d85b9be22e3d8d47360c3cad09ca7d8b9fbf9024635a6c/68747470733a2f2f696d616765732e67697465652e636f6d2f75706c6f6164732f696d616765732f323032322f303631332f3133343835335f31653131346430645f313134333431392e706e67)
> 
> 希望可以增加数据源指定方法,通过该方法可以像@ds那样指定自定义数据字典的数据源

同样的问题，有解决思路嘛？

**Comment by kinglyx** [comment]
mysql 可以在dictTable 上用点表示 如 test.user
kingbase数据库占时没想到好办法

**Comment by zjarlin** [comment]
@DS里的参数怎么在运行时写活,研究出来这个应该就解决了;假设我执行一个翻译方法service.transDict(dictcode,dictKey);这将返回String dictName;但是我希望这个方法增加一个形参datasource,在运行时,动态切换数据源,换句话说,这个方法上的@DS注解里的内容,要是这个方法运行时的参数datasource,创建动态代理,运行时把方法上的运行时注解替换了;

**Comment by zhangdaiscott** [comment]
采用mybaits plus的动态数据源就可以实现
