### ISSUE TITLE
列表默认按两个字段排序的问题

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4140]
##### 问题描述：
jeect client端开发时遇到列表默认按两个字段排序的问题，用isorter怎么配置，第一个字段正向排序，第二个字段逆向排序

##### 截图&代码：

 /* 排序参数 */
      isorter: {
        column:'status, create_time',
        order: 'asc, desc',        
      },

可以按两个字段排序，但只能正向排序 asc，desc不起作用

**Comment by LiangYongAI** [comment]
我也碰到同样的问题，有答案

**Comment by xiaolinVV** [comment]
要改后台查询构造器逻辑，目前的逻辑是判断有 ASC 就直接全部按照  asc 排了，没有 asc 的话，直接使用 desc . 

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/20742044/201505682-0df11337-5579-42c1-a968-aefb3b9e9e72.png">

**Comment by zhangdaiscott** [comment]
目前不打算支持，针对个性化的排序，可以自定义查询那块
