### ISSUE TITLE
springboot actuator未授权访问漏洞

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4141]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
springboot actuator未授权访问漏洞，该漏洞在jeecgboot上该如何处理呢？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
org\jeecg\config\shiro\ShiroConfig.java


注释掉即可
![输入图片说明](https://foruda.gitee.com/images/1663557661582669361/65e1f6a4_57093.png "屏幕截图")

**Comment by yang105** [comment]
这个漏洞好像没有解决。我通过url 可以直接访问actuator的相关接口。
