### ISSUE TITLE
exlce模板导出如果模板中有多个合并单元格的循环表格，第二个表格读取错误

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4142]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
在进行excel模板导出是，如果模板中含有多个包含合并单元格的循环表格，第二个表格读取的时候会出现BUG，看了下代码，在第一个表格循环完成之后，合并单元格缓存没有刷新，导致取到第二个表格模板那一行的读取不到对应的合并单元格信息

##### 截图&代码：
![excel模板](https://foruda.gitee.com/images/1663726092121022690/cc60ccdb_428914.png "企业微信截图_16637260167214.png")

![报错信息](https://foruda.gitee.com/images/1663726131681179210/87c5636b_428914.png "屏幕截图")
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/198179875-fa7898db-0c64-4eb4-a93b-be7a4a4db7ff.png)
问题出在shiftRows方法，这个方法在移动行之后，移动的行合并单元格样式就全部没有了
![image](https://user-images.githubusercontent.com/3162115/198179889-b9c58a7c-2da0-4187-8ce0-63e79025fa1a.png)

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
