### ISSUE TITLE
导入获取Key-Value，这个功能删除了吗？

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4143]
##### 版本号：
autopoi 1.4.3

##### 问题描述：
autopoi 1.4.3 版本里面，取消了 setKeyMark 了吗？和文档此功能实现说明不一致。
详细见如下文档：http://doc.autopoi.jeecg.com/1623977

--------------文档描述------------------------
需要设置两个或者一个值 params.setKeyMark("："); 判断一个cell是key的规则,可以自定义,默认就是 ":" params.setReadSingleCell(true); 是否需要读取这种单独的sql 读取完毕后,通过result.getMap() 就可以拿到自己想要的值了比如上面的Excel读取到的map就是

{境内详细收货地址、联系人、电话：=1.3112345678E10, 委托方：=一众科技有限公司, 代理方：=上海一众金融信息服务有限公司, 委托单号：=XH-HZHY-20170504, 日期：=2017.5.4, 供应商交货方式：=, 合计：=, 境内交货方式：=, 指定收货人身份证号：=3.7082719880102099E17}

这样就比较方便的处理较为复杂的Excel导入了

##### 截图&代码：

params.setKeyMark("："); 
params.setReadSingleCell(true);

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
该功能暂不支持
