### ISSUE TITLE
autopoi导入时报错：Cannot get a STRING value from a NUMERIC formula cell

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4144]
##### 版本号：
jeecg-boot3.4.1

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
在使用autopoi做导入功能时，报错：Cannot get a STRING value from a NUMERIC formula cell，
测试发现过后，是读取excel第一列时报错，将第一列删除可以正常运行，但是并未发现文件中的第一列与其他列有什么区别，我有大量的类似文件需要导入，我该怎么处理

##### 截图&代码：

![报错截图](https://foruda.gitee.com/images/1665384371084681418/760f30e3_7437197.png "屏幕截图")
![测试代码](https://foruda.gitee.com/images/1665384413205587103/73476106_7437197.png "屏幕截图")
![文件上传截图](https://foruda.gitee.com/images/1665384518794869684/15f9e3f6_7437197.png "屏幕截图")

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
测试不易复现你说的问题，麻烦提供一下你的  ArticleImportDTO  和  导入的文件

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
