### ISSUE TITLE
edge浏览器 点击 顶部导航栏 右键无效果

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4146]
##### 截图&代码：
edge版本=== 106.0.1370.52 (正式版本) (64 位)
![输入图片说明](https://foruda.gitee.com/images/1666681698710139468/ae3dde7f_5475942.png "屏幕截图")

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by BlackCatCats** [comment]
> jl

？？？

**Comment by sjlei** [comment]
未复现该问题，应该是安装了什么插件导致的。

![image](https://user-images.githubusercontent.com/34293221/199221756-10f9d0e7-55ae-47f9-ab3c-7fbfe0bc2615.png)
