### ISSUE TITLE
shardingjdbc分表，采用标准分片策略，查询没有问题，insert数据时分片规则里有几张表就往几张表里插入数据，同时自定义分片规则的类无法进入断点

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#4148]
##### 版本号：

2.4.5
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

shardingjdbc分表，采用标准分片策略，查询没有问题，insert数据时分片规则里有几张表就往几张表里插入数据，同时自定义分片规则的类无法进入断点，这是为什么？难道项目中有自带的关于shardingjdbc的东西影响到了我的自定义的分片策略？
##### 截图&代码：
![这张是yml分片规则的配置](https://foruda.gitee.com/images/1666616067297239766/e8a477a6_1659648.png "1.png")![这张是自定义的分片策略](https://foruda.gitee.com/images/1666616096737548616/e756eb58_1659648.png "2.png")![这张是数据库的两张表](https://foruda.gitee.com/images/1666616128574375747/296d0572_1659648.png "3.png")![这张是分片规则所在目录](https://foruda.gitee.com/images/1666616276474067229/b5f71dc6_1659648.png "1666616254725.png")
正常来说假如今天25号，就只往25号的表里插入数据，但是实际是两张表都会插入数据，而且断点无效。
本来还想自动刷新分片节点的，但是现在插入就有问题，麻烦帮忙看看是什么问题，十分感谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
yf

**Comment by accpman** [comment]
如果需要根据日期进行分片那分片规则里需要编写日期分片算法，比如根据日期字段跟当前日期进行比对，你用的分库分表不是系统集成的5.0版本把，你参考下https://www.kancloud.cn/zhangdaiscott/jeecg-boot/3085227这个集成例子，这个是根据name进行的分表插入算法，测试是没问题的
