### ISSUE TITLE
online表单开发代码生成选择Vue3风格,生成的代码却是vue2的

### ISSUE THREAD

**Issue by Tech--man** [jeecgboot/jeecg-boot#4151]
##### 截图&代码：

<img width="709" alt="image" src="https://user-images.githubusercontent.com/5569639/198187145-ca9901f5-cd5a-41ca-852d-b054cfe5ff35.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/5569639/198187212-b9398293-6a5e-4d3b-b3cd-d986b33cc6c1.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前后端代码都是最新的吗？确认下

**Comment by zhangdaiscott** [comment]
修复，请更新代码
