### ISSUE TITLE
租户自己产生的数据自己看不到啊，数据表租户ID还是默认值0

### ISSUE THREAD

**Issue by my-mark** [jeecgboot/jeecg-boot#4152]
##### 版本号：
v3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
租户自己产生的数据自己看不到

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
哪个表的数据

**Comment by my-mark** [comment]
自己的业务表
![image](https://user-images.githubusercontent.com/37830645/198204690-444167f9-898a-4f71-9075-f0f5eea55852.png)

**Comment by zhangdaiscott** [comment]
租户怎么配置的

**Comment by my-mark** [comment]
http://doc.jeecg.com/2044164 按照文档来的
创建租户-》给用户配置租户
租户请求头里租户ID为1，但是创建数据落到库里还是0；

**Comment by zhangdaiscott** [comment]
截图看配置

**Comment by my-mark** [comment]
![image](https://user-images.githubusercontent.com/37830645/198211270-6fa25e55-5d44-4aec-b003-941fb4844f05.png)
![image](https://user-images.githubusercontent.com/37830645/198211575-0818d6f4-6c1b-436d-aa99-cd4bdb236def.png)

**Comment by zhangdaiscott** [comment]
能不能一次性说清楚，哪个表是你的业务表

**Comment by my-mark** [comment]
上面截图里的就是啊，很难理解吗？enjoy开头的啊
业务表里也加了租户字段，用户也配置了租户；
查询数据没有问题，根据配置的租户id查询；但是保存数据时没有将对应的租户ID保存进去（还是字段默认值0）
或者你直接说具体这块代码在哪，我自己去看～

**Comment by zhangdaiscott** [comment]
这个是mybatis plus的机制，自动注入和自动追加查询条件，你确认下你这个实体按照文档配置了，并且你的添加接口没有排除shiro拦截，就不应该有问题

**Comment by my-mark** [comment]
业务表是在线开发的，没有实体，对应表里有租户字段。
在线开发的不支持吗？

**Comment by zhangdaiscott** [comment]
online暂时不支持

**Comment by my-mark** [comment]
接收online方式请求的代码实现在哪一块？我直接在里面操作。

**Comment by zhangdaiscott** [comment]
ty

**Comment by my-mark** [comment]
通过修改拦截器已解决
