### ISSUE TITLE
定时任务启动后不生效

### ISSUE THREAD

**Issue by 1441853031** [jeecgboot/jeecg-boot#4153]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
定时任务启动后不生效， 但是手动执行一下可以看到日志，一直启动（前端显示已开启）状态看不到日志

##### 截图&代码：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/63350299/198202883-6972e950-d644-4bf9-99cf-55f12daa4f58.png">

点击执行一次，有打印日志，可以看到后台被调用
![image](https://user-images.githubusercontent.com/63350299/198203150-4ac8834f-4a97-4f14-8249-fa7669120010.png)

<img width="1437" alt="截屏2022-10-27 下午1 58 10的副本" src="https://user-images.githubusercontent.com/63350299/198203545-ca35001a-6281-4b5a-a0e2-0b5d4900c426.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
常见问题有这个问题：http://jeecg.com/doc/qa
52

**Comment by 1441853031** [comment]
> 

设置的每秒钟一次，等了半天也没看到执行

**Comment by 1441853031** [comment]
> 常见问题有这个问题：http://jeecg.com/doc/qa 52

设置的每秒钟一次，等了半天也没看到执行

**Comment by panyuzhe73** [comment]
> 常见问题有这个问题：http://jeecg.com/doc/qa 52

不管几台机器数据库数据都没有增加啊
