### ISSUE TITLE
消息中心-我的消息可以删除吗？

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4154]
##### 版本号：

3.3
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

消息中心-我的消息可以删除吗？
##### 截图&代码：

![image](https://user-images.githubusercontent.com/15886620/198218006-a37a64c9-c2dd-4c1c-9309-7c0647f782ec.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
应该没做这个功能，需要自己加一个把
