### ISSUE TITLE
jar包部署后，本机用域名打开网站，局域网内其他机器怎么打开网站

### ISSUE THREAD

**Issue by 2morning** [jeecgboot/jeecg-boot#4155]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
jar包部署后，本机用域名打开网站，比如http://requirements能直接进入网站；
其他服务器输入http://requirements无反应，怎么才能让局域网其他服务器也正常使用？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
局域网，要么通过IP访问。
也可以百度下局域网域名怎么设置

**Comment by 2morning** [comment]
怎么能实现通过ip访问阿？ 目前只能jar包部署的形式
