### ISSUE TITLE
增值编码

### ISSUE THREAD

**Issue by caleb-hxs** [jeecgboot/jeecg-boot#4156]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

您好，后台能使用增值编码的功能，生成后没有。有解决方法吗，谢谢您
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
online很多功能是在线概念，不支持生成的，生成代码后，手工补逻辑即可。
http://doc.jeecg.com/2044051
