### ISSUE TITLE
代码生成后规则无法实现

### ISSUE THREAD

**Issue by Noodles12138** [jeecgboot/jeecg-boot#4159]
##### 版本号：
3.40

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
在线工具生成的表单有id自动新增规则，生成代码后，自己部署到项目中，没有激活规则，请问如何解决

##### 截图&代码：

![1](https://user-images.githubusercontent.com/74094547/198522924-dfb5672a-5787-4ecc-9cfd-01f6bb90a258.png)
![2](https://user-images.githubusercontent.com/74094547/198522949-e21c6df0-0890-4f9d-9ae8-e5c462edd19f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Noodles12138** [comment]
上图为 代码生成后的结果
下图为 在线开发结果

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/4156
