### ISSUE TITLE
/src/components/NumberInfo/NumberInfo.vue

### ISSUE THREAD

**Issue by Dior1314** [jeecgboot/jeecg-boot#4160]
##### 问题描述：yarn install 安装完 ant-design-vue-jeecg-master 项目依赖，yarn run serve启动后项目报错，百度帖子上大多解决方式注释掉 src/components/NumberInfo.vue 文件中style部分
<style lang="less" scoped>
  //@import "index";
</style>
我想问下是什么原因导致这个问题的，最佳解决方式是什么！！！

##### 截图&代码：./src/components/NumberInfo/NumberInfo.vue?vue&type=style&index=0&id=4370c5af&lang=less&scoped=true& (./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/NumberInfo/NumberInfo.vue?vue&type=style&index=0&id=4370c5af&lang=less&scoped=true&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/stylePostLoader.js):
TypeError: Cannot set property 'parent' of undefined
    at D:\project\vue\exercise\ant-design-vue-jeecg\src\components\NumberInfo\NumberInfo.vue:1282:1
![image](https://user-images.githubusercontent.com/18045477/198527318-ca33b562-26f2-49a2-8aff-c7af0fe3d850.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by zhangdaiscott** [comment]
临时修复了，请更新代码

**Comment by sjlei** [comment]
问题已修复，将`src\components\NumberInfo\index.less`文件的第45行的`:global`替换成`:deep`即可，经测试样式与替换前一致。

![image](https://user-images.githubusercontent.com/34293221/199639607-f9525faf-629a-4eff-963f-e0fadaa9899d.png)

**Comment by Dior1314** [comment]
> 问题已修复，将`src\components\NumberInfo\index.less`文件的第45行的`:global`替换成`:deep`即可，经测试样式与替换前一致。
> 
> ![image](https://user-images.githubusercontent.com/34293221/199639607-f9525faf-629a-4eff-963f-e0fadaa9899d.png)
好的 谢谢！

**Comment by Dior1314** [comment]
> 临时修复了，请更新代码

谢谢！
