### ISSUE TITLE
页面右上方查看全部消息SQL报错

### ISSUE THREAD

**Issue by cui5782052** [jeecgboot/jeecg-boot#4161]
##### 版本号：
3.4.3

##### 问题描述：
页面右上方查看全部消息SQL报错

##### 截图&代码：
![image](https://user-images.githubusercontent.com/62142959/198549729-7f2ad771-2926-48e3-a99f-7892a101fb4d.png)

代码：
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'b.star_flag' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'b.star_flag' in 'field list'

**Comment by zhangdaiscott** [comment]
你是自己升级的，没有去执行每个版本的升级sql

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/blob/v3.4.2/db/%E5%A2%9E%E9%87%8FSQL/3.4.0%E5%8D%87%E7%BA%A7%E5%88%B03.4.2%E5%A2%9E%E9%87%8F%E8%84%9A%E6%9C%ACsql

https://github.com/jeecgboot/jeecg-boot/blob/v3.4.3/db/%E5%A2%9E%E9%87%8FSQL/3.4.2%E5%8D%87%E7%BA%A7%E5%88%B03.4.3%E5%A2%9E%E9%87%8F%E8%84%9A%E6%9C%AC.sql

**Comment by zhangdaiscott** [comment]
每个版本里都有个增量升级sql,缺什么自己找吧
![image](https://user-images.githubusercontent.com/3162115/198564332-6ec06807-b0f9-4d6e-9d37-2c608e8148cf.png)
