### ISSUE TITLE
MyBatis  ${} 动态表名存在 SQL 注入高危漏洞

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#4162]
##### 版本号：
v3.4.2

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
MyBatis SQL 注入漏洞。 项目源码经过代码漏洞扫描工具发现 `SysDictMapper .xml` 中大量使用 ${} 变量方式，存在 SQL 注入高危漏洞，必须整改。  但是这些代码又是功能必须，请问有什么替代方案么？  

##### 截图&代码：

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/20742044/198604472-a1576c70-3e1e-4463-b00f-b053d09656aa.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没什么问题，调用的地方，接口都加了签名校验，针对敏感的sql也做了check
