### ISSUE TITLE
项目刚启动的时候redis连接是没问题的，但是在一段 时间后就会出现连接超时的问题。

### ISSUE THREAD

**Issue by microhard21** [jeecgboot/jeecg-boot#4165]
##### 版本号：
Jeecgboot3.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
nginx-1.20.2
apache-tomcat-9.0.55
Redis-x64-5.0.14

项目刚启动的时候redis连接是没问题的，但是在一段 时间后就会出现连接超时的问题。

##### 截图&代码：
2022-10-29 19:57:49.589 [http-nio-8080-exec-4] [31mWARN [0;39m [36morg.apache.shiro.authc.AbstractAuthenticator:216[0;39m - Authentication failed for token submission [org.jeecg.config.shiro.JwtToken@20896bb6].  Possible unexpected error? (Typical or expected login exceptions should extend from AuthenticationException).
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图 看看你的redis是怎么配置的

**Comment by firebear-ssl** [comment]
#redis 配置
  redis:
    timeToLive: 15
    lettuce:
      pool:
        MaxTotal: 50
        minIdle: 5
        maxWaitMillis: 10000
        maxIdle: 100
        testOnBorrow: true
        testOnReturn: true
        testWhileIdle: true
    database: 0
    host: 
    port: 6379
    password: ''

**Comment by firebear-ssl** [comment]
我们也遇到同样的问题，一会就超时了。

**Comment by zhangdaiscott** [comment]
直接改成这样
```
  #redis配置
  redis:
    database: 0
    host: {你的IP}
    port: 6379
    password: ''
```
