### ISSUE TITLE
online开发，使用部门选择组件时，多个默认参数时，仍然有问题。点击“确认”按钮，没反应。

### ISSUE THREAD

**Issue by wwwhellowww** [jeecgboot/jeecg-boot#4166]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/117026340/198885769-112c25a8-f12e-4737-82c5-db924b13cbe9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
我测试最新的没有该问题了，使用最新的试试
![image](https://user-images.githubusercontent.com/27989856/199184447-d6ec9e28-6aa8-40ad-aac9-7ed67c177bdd.png)

**Comment by zhangdaiscott** [comment]
修复了，请更新代码
