### ISSUE TITLE
后端版本3.4.2搭配前端vue2可以升级至3.4.3版本么？

### ISSUE THREAD

**Issue by ShadowYu0518** [jeecgboot/jeecg-boot#4167]
##### 问题描述：

后端版本3.4.2，前端vue2，请问一下可以跟随开源的更新 跟随一起把前后端更新到3.4.3-GA吗？感谢

##### 截图&代码：

无

**Comment by zhangdaiscott** [comment]
vue2暂时不要升级，可能会出现不兼容，当前版本发的功能主要是vue3版的
