### ISSUE TITLE
Online JTreeSelect控件changeOptions方法未生效

### ISSUE THREAD

**Issue by 02Amy** [jeecgboot/jeecg-boot#4173]
##### 问题描述：
设置TID1字段中JTreeSelect控件下拉框选项根据TACTID1变化，当TACTID1 变化时，触发onlChange事件，重新调用获取下拉树数据。图1为调用接口获取数据返回的值，并利用下面语句给TID1赋值，
that.changeOptions("tid1",treeAllData);
截图2中显示赋值未生效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/95427332/199144515-ed500c0c-9fc2-4651-9ebd-05693edf7d11.png)
图1

![image](https://user-images.githubusercontent.com/95427332/199144047-93603eba-4b2a-4670-b740-67e970f27b6c.png)

图2

//下图为online表单中 js增强代码
onlChange(){
  debugger;
  console.log('onchange')
  return {
	 
     tactid1(){
		  let value = event.value;
                  let treeAllData = [];
                  const tid1_value = that.getSelectOptions("tid1")
                  let params = {              
                         pid: value,
                         tableName: "dk_attack",
                         text: "name",
                         code: "code",
                         pidField: "pcode",
                         hasChildField: "has_child",
                         condition: ""
                  }
                  getAction("/sys/dict/loadTreeData",params).then(res=>{
                        treeAllData=res.result;
		        that.changeOptions("tid1",treeAllData);
                 })
		}
	}
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你这是online js增强？

**Comment by 02Amy** [comment]
是的，仿照这个链接里面的代码写的
http://doc.jeecg.com/2044110

**Comment by zhangdaiscott** [comment]
树下拉，应该不支持changeOptions

**Comment by 02Amy** [comment]
那有其他方法可以设置下拉树的下拉选项吗

**Comment by zhangdaiscott** [comment]
目前没提供 对应的api

**Comment by zhangdaiscott** [comment]
已提供方案，下个版本发布
http://vue3.jeecg.com/3085992
