### ISSUE TITLE
前端vue2转3，在线报表出错

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecg-boot#4174]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
vue2转vue3，后端数据库只改了sys_permission和sys_role_permission.其他均可正常使用。但是在线报表会报数据库连接不上，在线报表的一直是接口获取失败，是这么原因呢？现在有需求是不动太多数据库的前提下，升级前端版本

##### 截图&代码：
![image](https://user-images.githubusercontent.com/24811278/199146362-fd311093-29a5-4d1e-ac34-4b9d28d2908f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前端vue2转3 你是怎么转的？数据库是老的？切换vue3新版UI?

**Comment by jinbear** [comment]
目前这个已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 中午12:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 前端vue2转3，在线报表出错 (Issue #4174)





 
前端vue2转3 你是怎么转的？数据库是老的？切换vue3新版UI?
