### ISSUE TITLE
vue3配置在线报表的菜单后，点击响应的报表菜单，左侧菜单展开在线报表菜单，而不是停留在我们配置的菜单位置

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecg-boot#4175]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：

vue3配置在线报表的菜单后，点击响应的报表菜单，左侧菜单展开在线报表菜单，而不是停留在我们配置的菜单位置
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你把低代码开发菜单，排序改到 99 刷新首页看看

**Comment by jinbear** [comment]
可以了，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] vue3配置在线报表的菜单后，点击响应的报表菜单，左侧菜单展开在线报表菜单，而不是停留在我们配置的菜单位置 (Issue #4175)





 
你把低代码开发菜单，排序改到 99 刷新首页看看
