### ISSUE TITLE
online生成代码功能选择vue3生成的还是vue2代码

### ISSUE THREAD

**Issue by xuxin468** [jeecgboot/jeecg-boot#4176]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online生成代码功能选择vue3生成的还是vue代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36890132/199223588-94fcf43d-b5cc-4c32-8b76-68e3ffdd5973.png)

![image](https://user-images.githubusercontent.com/36890132/199223466-35daf8ad-0e18-4934-9b27-3ecea6dad832.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你怎么下载的代码？这个已经处理过了

**Comment by xuxin468** [comment]
先同步码云代码，然后合并到本地分支

**Comment by xuxin468** [comment]
抱歉已发现是代码合并的问题，已解决
