### ISSUE TITLE
前端版本：vue2 问题描述：idea安装前端项目npm run serve一老报Error: Cannot find module './_baseValues'是怎么回事

### ISSUE THREAD

**Issue by PaigeZhou** [jeecgboot/jeecg-boot#4178]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
错误截图

**Comment by PaigeZhou** [comment]
![图片](https://user-images.githubusercontent.com/75821841/199387924-58cbea99-fc8d-4ab3-9bbe-961f9b2e479e.png)

**Comment by zhangdaiscott** [comment]
没遇到过，你可以百度看看
