### ISSUE TITLE
jeecgboot2.x vue2 微前端qiankun集成

### ISSUE THREAD

**Issue by Lemnaminor** [jeecgboot/jeecg-boot#4179]
##### 问题描述：
项目背景：
       有几个项目都是用jeecgboot2.x版本开发，因后端整合成一套代码，共用了sys系统模块，前端之前都是单个项目独立开发，导致前端每个项目共用了一个导航菜单数据。

项目需求：
       因共用一个菜单导致A项目看到了B项目的菜单 无法点击。故考虑集成qiankun微前端模式使A项目可以点击B项目菜单实现不同项目之前跳转。

问题解决：
        自己根据贵方官方文档 http://doc.jeecg.com/2554339 微前端高级改造 修改项目。把id="content" class="app-view-box" div 容器盒子挂载到/components/layouts/TabLayout.vue下并未成功显示子应用。
        故挂载到App.vue 根节点 可以访问。但是不同应用跳转的时候，逻辑会先走utils.js generateChildRouters()方法下的componentPath = resolve => require(['@/' + component + '.vue'], resolve)  报错：Cannot find module './views/crm/company/qyIntention/QyIntentionList.vue' 截图在下，因A项目本来没有B项目的组件模块导致报错，无法跳转。
        因曲线救国在跳转前permission.js router.beforeEach前判断手动改变添加子应用url路径实现 加载不用子应用模块。但是这样跳转不用子应用的时候会刷新下页面。
        请问怎么可以做到无刷加载不用子应用呢。有具体的代码供参考一下吗。qiankun了解不深，望大佬解惑。

##### 截图&代码：

  
![image](https://user-images.githubusercontent.com/17738001/199447515-1a4ef493-b9e5-4c51-b15a-701bcc281c56.png)
![image](https://user-images.githubusercontent.com/17738001/199450093-67a6af2e-c648-4f85-bddf-0c27c3857de6.png)

**Comment by accpman** [comment]
[jeecg-app-1.zip](https://github.com/jeecgboot/jeecg-boot/files/9949618/jeecg-app-1.zip)
给你提供一个子项目集成的具体示例主项目的集成还是参考文档

**Comment by Lemnaminor** [comment]
感谢大佬的回复。我刚浏览了一下，你给的子项目配置跟我自己配的差不多。我的问题出在 主、子应用都是用jeecgboot框架下，主应用跳转子应用，框架自身菜单路由阻止跳转报错了。还有子应用挂载节点挂载到哪里的问题。现在我是想借鉴一下主、子应用都是jeecgboot的情况下是怎么集成的，希望能有代码参考一下。现在自己把子应用挂载到app.vue根节点是能加载子应用，不过我是手动判断改变url实现跳转不用子应用，这种会造成跳转不同子应用会重新加载刷新页面。希望能做到无刷新加载子应用。

**Comment by Lemnaminor** [comment]
> [jeecg-app-1.zip](https://github.com/jeecgboot/jeecg-boot/files/9949618/jeecg-app-1.zip) 给你提供一个子项目集成的具体示例主项目的集成还是参考文档



> [jeecg-app-1.zip](https://github.com/jeecgboot/jeecg-boot/files/9949618/jeecg-app-1.zip) 给你提供一个子项目集成的具体示例主项目的集成还是参考文档

感谢大佬的回复。我刚浏览了一下，你给的子项目配置跟我自己配的差不多。我的问题出在 主、子应用都是用jeecgboot框架下，主应用跳转子应用，框架自身菜单路由阻止跳转报错了。还有子应用挂载节点挂载到哪里的问题。现在我是想借鉴一下主、子应用都是jeecgboot的情况下是怎么集成的，希望能有代码参考一下。现在自己把子应用挂载到app.vue根节点是能加载子应用，不过我是手动判断改变url实现跳转不用子应用，这种会造成跳转不同子应用会重新加载刷新页面。希望能做到无刷新加载子应用。

**Comment by Lemnaminor** [comment]
> [jeecg-app-1.zip](https://github.com/jeecgboot/jeecg-boot/files/9949618/jeecg-app-1.zip) 给你提供一个子项目集成的具体示例主项目的集成还是参考文档

感谢大佬的回复。我刚浏览了一下，你给的子项目配置跟我自己配的差不多。我的问题出在 主、子应用都是用jeecgboot框架下，主应用跳转子应用，框架自身菜单路由阻止跳转报错了。还有子应用挂载节点挂载到哪里的问题。现在我是想借鉴一下主、子应用都是jeecgboot的情况下是怎么集成的，希望能有代码参考一下。现在自己把子应用挂载到app.vue根节点是能加载子应用，不过我是手动判断改变url实现跳转不用子应用，这种会造成跳转不同子应用会重新加载刷新页面。希望能做到无刷新加载子应用。

**Comment by accpman** [comment]
目前还没对主子项目都是jeecgboot的集成示例，也就是说目前是集成上了，只是刷新问题，随后我整合下试试你加我下QQ 574501933,抽时间咱们线下交流下

**Comment by Lemnaminor** [comment]
> 目前还没对主子项目都是jeecgboot的集成示例，也就是说目前是集成上了，只是刷新问题，随后我整合下试试你加我下QQ 574501933,抽时间咱们线下交流下

是的，本地已经集成好了的，使用体验不是很理想。好的大佬，已经添加你的QQ了。

**Comment by qinghechaoge** [comment]
> 

有没有vue3 antd 版的示例啊
