### ISSUE TITLE
Online表单开发，点保存无响应

### ISSUE THREAD

**Issue by XiaoBiaoYin** [jeecgboot/jeecg-boot#4180]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在online表单开发时，选择表，点击编辑，再点击保存时，没响应，但是新增并同步数据都没问题。

##### 截图&代码：
![2](https://user-images.githubusercontent.com/117286662/199511530-4d166f07-8efa-498a-b153-802eed37011d.png)
![3](https://user-images.githubusercontent.com/117286662/199511591-9831a189-4104-43ae-9716-5b54ca3da66c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by XiaoBiaoYin** [comment]
不报错，就一直转圈圈

**Comment by XiaoBiaoYin** [comment]
> 报什么错

不报错，一直转圈，没有响应

**Comment by XiaoBiaoYin** [comment]
> 报什么错

![image](https://user-images.githubusercontent.com/117286662/199515394-37aea6f6-0cea-4d4e-849c-864ed8466f23.png)
这个样子

**Comment by zhangdaiscott** [comment]
java后台报什么错

**Comment by zhangdaiscott** [comment]
现在的vue2 对应的  后台v3.1.0
你别用最新版后台试试

**Comment by XiaoBiaoYin** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月02日 23:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] Online表单开发，点保存无响应 (Issue #4180) |

现在的vue2 对应的 后台v3.1.0
你别用最新版后台试试

**Comment by XiaoBiaoYin** [comment]
> 现在的vue2 对应的 后台v3.1.0 你别用最新版后台试试

今天试着用v3.1.0和v2.4.6，但是问题没得到解决，还有就是对已有的表单(不止新增的表，也包含源码中的表)进行功能测试，发现点击新增，没有填写的表单，如下图
![image](https://user-images.githubusercontent.com/117286662/199651162-564402b4-077b-4dee-bcbc-3e27d8a8e18d.png)
编辑也是一样，如图
![image](https://user-images.githubusercontent.com/117286662/199651212-3ead40c9-819e-4a5f-b596-70104e91bff5.png)
后端是不报错

**Comment by XiaoBiaoYin** [comment]
> 现在的vue2 对应的 后台v3.1.0 你别用最新版后台试试

请问和这个有关系么，我换成公网ip,没问题，换成本地的就不行
![image](https://user-images.githubusercontent.com/117286662/199756655-dabc8736-9355-4bed-a430-48607bc5bf42.png)

**Comment by zhangdaiscott** [comment]
是数据问题，有个字段校验不通过，校验提示的不友好，不是后台问题

![image](https://user-images.githubusercontent.com/3162115/199875562-5f7d0fba-3c36-45f8-b87e-5a248b3b2143.png)

**Comment by XiaoBiaoYin** [comment]
> 是数据问题，有个字段校验不通过，校验提示的不友好，不是后台问题
> 
> ![image](https://user-images.githubusercontent.com/3162115/199875562-5f7d0fba-3c36-45f8-b87e-5a248b3b2143.png)
可是我随便选择一个表，啥也不改动，直接进行保存，也是会出现问题的。

**Comment by zhangdaiscott** [comment]
有字段提示红吗

**Comment by XiaoBiaoYin** [comment]
没有



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月04日 15:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] Online表单开发，点保存无响应 (Issue #4180) |

有字段提示红吗

**Comment by XiaoBiaoYin** [comment]
问题已得到解决，redis的问题。

**Comment by XiaoBiaoYin** [comment]
感谢...

**Comment by tclwh** [comment]
> 问题已得到解决，redis的问题。

您这个是redis的什么问题？我也出现了相同的问题

**Comment by XiaoBiaoYin** [comment]
redis具体什么问题没细查，重装一个redis就好使了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月29日 14:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] Online表单开发，点保存无响应 (Issue #4180) |

问题已得到解决，redis的问题。

您这个是redis的什么问题？我也出现了相同的问题
