### ISSUE TITLE
Nessus扫描出Apache Tomcat Default Files

### ISSUE THREAD

**Issue by ZoeZhong93** [jeecgboot/jeecg-boot#4181]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/63279683/199638004-50097c66-6298-4bc9-9a6e-d9045d93e007.png)
![image](https://user-images.githubusercontent.com/63279683/199638039-968e214b-14b6-4445-9766-c7922001edca.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
默认文件是指这俩文件吗
![image](https://user-images.githubusercontent.com/3162115/201087184-104c95d6-1e3b-4f26-bce1-9eac36c0fede.png)

**Comment by ZoeZhong93** [comment]
> 默认文件是指这俩文件吗 ![image](https://user-images.githubusercontent.com/3162115/201087184-104c95d6-1e3b-4f26-bce1-9eac36c0fede.png)

不是，这个是参考的网站

**Comment by ZoeZhong93** [comment]
已修复
