### ISSUE TITLE
Vue2 版本前端支持生成代码在线预览等新功能

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#4182]
##### 版本号：
v3.4.2

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
请问 Vue2 版本前端会支持生成代码在线预览等新功能么？看到 Vue3 版本支持了不少心功能特性，生成代码在线预览还是很好用的，可是目前公司还是在用 Vue2 版本，暂时没有计划升级

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2 不支持
