### ISSUE TITLE
online表单开发代码生成的功能提示"资源不存在"

### ISSUE THREAD

**Issue by TaoYangGItHub** [jeecgboot/jeecg-boot#4188]
##### 版本号：

2.4.0
##### 前端版本：vue3版？还是 vue2版？

vu2
##### 问题描述：

通过online表单开发代码生成代码，配置好了菜单后，提示"资源不存在"
查看后台服务API接口文档也没有对应接口

之前都是好好的，突然不能用了
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/25076129/199919856-82339704-823e-476b-b259-28e5723da5ef.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
哪个功能？接口地址

**Comment by TaoYangGItHub** [comment]
> 哪个功能？接口地址

一个二次开发的功能，重新下载了maven包后可以正常访问了，不知道是不是这个原因引起的，毕竟之前创建新功能都没问题

**Comment by zhangdaiscott** [comment]
应该是依赖没下载成功
