### ISSUE TITLE
必填的form的validate校验反过来了

### ISSUE THREAD

**Issue by xu-yanwen** [jeecgboot/jeecg-boot#4189]
版本号：
最新版本

前端版本：vue3版？还是 vue2版？
vue3

问题描述：

截图&代码：
必填的form的validate有问题，必填字段选中值后validate出来，清空选项validate消失，反过来了

1.线上代码的用户管理的角色字段设为必填，选中值后
![image](https://user-images.githubusercontent.com/78189212/199921215-a57a63d4-a401-4c5d-8b82-d9107c51072c.png)
2.角色字段取消选中值后

  
![image](https://user-images.githubusercontent.com/78189212/199921337-901d28a8-5131-4f32-a740-5201f9fb3d10.png)

**Comment by zhangdaiscott** [comment]
最新版没问题，我们也没加必填校验，请先按照issue格式要求补充内容
再自己测试下

**Comment by zhangdaiscott** [comment]
ok。我们看下

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by zhangdaiscott** [comment]
修复了，请更新代码
