### ISSUE TITLE
Online表单一对多表单开发问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4191]
##### 版本号：
 v3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
主子表情况下，代码生成的页面风格是tab风格，我选择的是一列，但是他默认变成了两列，然后点击后下拉框出来的位置不协调，我点击的是添加按钮，那弹窗的左上角也没显示是添加的操作，

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/199948008-d7b903f1-371f-4db3-8a71-825a8aff9fd1.png)
![image](https://user-images.githubusercontent.com/90361617/199948341-a82bc79e-bdc9-4054-a6c1-fd6e964b63e1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果你是生成的代码，建议效果自己修代码调整

**Comment by 3509282792** [comment]
不是应该在线生成的预览什么样子，生成代码后也应该什么样子吗？现在是预览没问题，生成后有问题呢

**Comment by 3509282792** [comment]
> 如果你是生成的代码，建议效果自己修代码调整

不是应该在线生成的预览什么样子，生成代码后也应该什么样子吗？现在是预览没问题，生成后有问题呢

**Comment by zhangdaiscott** [comment]
online开发是零代码概念，也就是在线功能！有的控件是给专门给online在线使用的，并不支持所有功能点都通过代码生成器生成
https://github.com/jeecgboot/jeecg-boot/issues/3689
