### ISSUE TITLE
j-vxe-table 不支持vxe-table的动态列显示/隐藏的配置

### ISSUE THREAD

**Issue by LvJianfeng** [jeecgboot/jeecg-boot#4194]
##### 问题描述：
`j-vxe-table` 不支持`vxe-table`的动态列显示/隐藏的配置吗? 我看`vxe-table`的v3+(vue.2.6+稳定版)支持设置表格的列配置

##### 截图&代码：
![image](https://user-images.githubusercontent.com/9586013/200174105-4b85e2e0-c316-4d1d-8cdf-d11decdae034.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个点击确认好使，你是有什么疑问？

**Comment by LvJianfeng** [comment]
@zhangdaiscott 这个截图是`vxe-table`官方的，我用`j-vxe-table`无法显示这个功能，是不是不支持哦

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/200219741-57680155-1e68-4c1d-ae38-baa29696218b.png)

http://vue3.jeecg.com/2561638#_8

**Comment by LvJianfeng** [comment]
@zhangdaiscott 哦哦， 😢，我用的v2版本，可能这个问题。
