### ISSUE TITLE
JeecgDemoCloudApplication 启动这个，然后监控，下面有身份认证失败，没动过代码和配置，直接运行的

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#4195]
##### 问题描述：
JeecgDemoCloudApplication 启动这个，然后监控，下面有身份认证失败，没动过代码和配置，直接运行的

##### 截图&代码：

org.jeecg.config.shiro.ShiroRealm:97 - ————————身份认证失败——————————IP地址:  192.168.23.1，URL:/actuator/health

#### 友情提示（了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不影响，这个:/actuator/health有漏洞，默认shiro给拦截了

**Comment by zhangdaiscott** [comment]
如果你是内网系统，不怕攻击，可以把这个注释放开
https://github.com/jeecgboot/jeecg-boot/issues/4141

**Comment by 378680487** [comment]
可是我的监控显示，demo，和system，两个项目不在线，离线状态

**Comment by 378680487** [comment]
明白了
