### ISSUE TITLE
代码生成时能否判断del_flag存在自动生成软删除代码

### ISSUE THREAD

**Issue by reltian** [jeecgboot/jeecg-boot#4196]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以加

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
以支持，待新版本发布

**Comment by zhangdaiscott** [comment]
已实现，更新代码
