### ISSUE TITLE
Online表单权限控制问题

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecg-boot#4197]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
Online表单开发的”权限控制“问题。
点击设置了权限控制的表单菜单项后，后续再点未设置权限控制的表单，权限控制没有解除，影响了其它表单。（似乎影响的是主子表的表单）

##### 截图&代码：
1、下面的”采购订单信息没有经过“权限控制”，“新增”等按钮正常：
![1667809687626](https://user-images.githubusercontent.com/36326638/200269340-ac4710b8-9832-430e-94f3-2a51005385f5.png)
2、然后点击”订单交期反馈“，这个表单是有”权限控制“的，界面中”新增“等按钮不显示，是正确的：
![1667809966660](https://user-images.githubusercontent.com/36326638/200269649-f528b893-cb90-4175-a173-af96e5769ee3.png)
权限控制如下：
![1667812690204](https://user-images.githubusercontent.com/36326638/200273005-5ede01db-d24b-44a7-a531-8ede359826ea.png)

3、再回到先前那个”采购订单信息“页面，发现也被”权限控制“了，”新增“等按钮都没显示出来：
![1667810112886](https://user-images.githubusercontent.com/36326638/200270114-2bed30b8-79e2-4905-8ffb-89cd4fd40a35.png)
4、此时点击其它菜单项（ERP风格的主子表），均是这样，应该显示的”新增“等按钮都不现实了，也被权限控制了：
![1667812293698](https://user-images.githubusercontent.com/36326638/200272791-66002a22-a6d8-4ee7-ab8b-0b98981c3409.png)

5、手动刷新一下，或者点击到某个”单表“的表单菜单项，权限控制恢复正常，”新增“等按钮回来了：
![1667810374669](https://user-images.githubusercontent.com/36326638/200271207-7fbb8c72-412d-46a7-8283-f887b3ebe379.png)
![1667811117245](https://user-images.githubusercontent.com/36326638/200271283-7eb097a2-8439-4782-aeca-639c6cb56f02.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
确认是bug

**Comment by zhangdaiscott** [comment]
你看下你online lib js 是不是最新的，我们代码已经修复了，忘记发布了没有

**Comment by gxzhou** [comment]
好的，谢谢！

**Comment by gxzhou** [comment]
> 你看下你online lib js 是不是最新的，我们代码已经修复了，忘记发布了没有

老师好，测试了下，问题依然存在的。
我先是手动更新了源码，后来怕有些源码更新不完整，就直接下载3.4.3版本的ant-design-vue-jeecg了，问题确实还存在呢。

**Comment by gxzhou** [comment]
> 你看下你online lib js 是不是最新的，我们代码已经修复了，忘记发布了没有

老师好，测试了下，问题依然存在的。
我先是手动更新了源码，后来怕有些源码更新不完整，就直接下载3.4.3版本的ant-design-vue-jeecg了，问题确实还存在呢。

**Comment by zhangdaiscott** [comment]
你确定下载是今天最新版本？

**Comment by gxzhou** [comment]
> 你确定下载是今天最新版本？

对的。

**Comment by gxzhou** [comment]
![1667879914909](https://user-images.githubusercontent.com/36326638/200471980-3d452255-07ec-4e72-8095-de2e41013934.png)
![1667879951291](https://user-images.githubusercontent.com/36326638/200472001-5950927e-d59f-4d42-ac85-6493c948543f.png)

**Comment by zhangdaiscott** [comment]
按照此步骤升级看看

1、升级依赖  package.json
```
"@jeecg/antd-online-mini": "3.4.3-beta2"

2、重新install

看看

**Comment by gxzhou** [comment]
> 按照此步骤升级看看
> 
> 1、升级依赖 package.json
> 
> ```
> "@jeecg/antd-online-mini": "3.4.3-beta2"
> 
> 2、重新install
> 
> 看看
> ```

OK了！非常感谢。
