### ISSUE TITLE
钉钉账号有多个组织在集成钉钉第三方登录时报错

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#4198]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3/vue2都有这个问题

##### 问题描述：
钉钉账号有多个组织在集成钉钉第三方登录时报错

##### 截图&代码：
![图片](https://user-images.githubusercontent.com/28818320/200277322-b2606f3d-227f-44b0-8111-2988f350b116.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

  我自己是修改ThirdLoginController.java
第三方登录回调接口下
query.eq(SysThirdAccount::getThirdType,thirdType)
为query.eq(SysThirdAccount::getThirdType,thirdType).last(“limit 1”);

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
未复现，切换到其他公司 数据库始终是一条数据。如果有不同的用户绑定手机号，数据库会更新到最新的一条记录，避免重复
