### ISSUE TITLE
nacos 密钥配置问题

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#4200]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

nacos 模块中的配置文件里的密钥的作用是什么？上线之前这个密钥如何修改？
##### 截图&代码：

![此处密钥修改涉及到其他地方修改么？修改了会有哪些影响？](https://user-images.githubusercontent.com/8438712/200456709-a8217d7a-cf53-47bd-b48c-83542ab9ee46.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个是nacos官方默认，我们没改过，你可以看看官方文档
