### ISSUE TITLE
5个服务部署到5台不同的服务器上，该如何部署呢？

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#4202]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

目前算系统服务、网关、nacos，总共5个服务，每个服务部署不同的服务器上，该如何部署呢？
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个没什么固定要求，按照自己规划就行
