### ISSUE TITLE
代码生成的列表支持查询关联子表的数据吗？

### ISSUE THREAD

**Issue by liaohongsen** [jeecgboot/jeecg-boot#4203]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
VUE2

##### 问题描述：
就是online的联合查询打开以后，在顶部搜索区域能 查询关联子表的数据，如下图，麻烦问下，如果我不用online，我使用代码生成能实现相同的效果吗？ 我想自己在vue模板去控制

##### 截图&代码：
![image](https://user-images.githubusercontent.com/16487300/200534385-cd09fb33-1901-4d8d-ba97-fa3bde414b2f.png)

**Comment by zhangdaiscott** [comment]
不支持，生成后，自己手工改代码实现吧
