### ISSUE TITLE
自定义弹框传参

### ISSUE THREAD

**Issue by wangsiyue** [jeecgboot/jeecg-boot#4206]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/24864022/200728458-0e7f43cb-6bc6-45c1-8397-9b0afcf01b07.png)
![1667963483053](https://user-images.githubusercontent.com/24864022/200728980-99686fd3-4dee-4087-ac45-f422f0bc1cc9.png)
![image](https://user-images.githubusercontent.com/24864022/200729226-1fa541dd-d206-497b-b2ec-f66e7783f81a.png)

![image](https://user-images.githubusercontent.com/24864022/200728999-d2084987-271c-479d-90df-7208328ab82e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
参考文档： https://www.kancloud.cn/zhangdaiscott/vue3/2743578
