### ISSUE TITLE
我想一进页面，查询框就可以看到多列多行，能配置吗？

### ISSUE THREAD

**Issue by BigRoseAndBoss** [jeecgboot/jeecg-boot#4207]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
目前页面，查询框只展示两列，要点展开才可以看到更多。
我想一进页面，查询框就可以看到多列多行，能配置吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50453506/200730948-a1c7c032-587f-4e3e-9eab-b39b5f143c15.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/200770512-182c177a-dd11-4f19-8450-c8c0c44a6361.png)

可以多阅读代码，TypeScript 的好处就是有了类型定义，参数什么都有注解，
文档有的没写那么细
