### ISSUE TITLE
分类字典上传模板在哪?

### ISSUE THREAD

**Issue by he410542236** [jeecgboot/jeecg-boot#4208]
官网vue2在线演示,分类字典里面的导入,请问导入模板在哪?  用下载的模板进行导入不会读取模板内容

**Comment by zhangdaiscott** [comment]
你导入数据截图看看

**Comment by he410542236** [comment]
![image](https://user-images.githubusercontent.com/62490028/200972911-bfb7f6fe-3c9b-43a4-aa21-b1a0f3232699.png)
直接用的导出模板

**Comment by zhangdaiscott** [comment]
按照issue要求，补充版本号等信息

##### 版本号：


##### 前端版本：vue3版？还是 vue2版？


##### 问题描述：


##### 截图&代码：




#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
测试导入可以，记着导入的时候，需要把编码改了

![image](https://user-images.githubusercontent.com/3162115/200994531-155054cc-3c2b-41ea-b579-703f61b0ea04.png)

![image](https://user-images.githubusercontent.com/3162115/200994506-7d50a42a-8c0a-41a2-8178-e27c9810e471.png)
