### ISSUE TITLE
Vue2版系统顶部菜单部分没有冻结导致直接上滑

### ISSUE THREAD

**Issue by menglanglang** [jeecgboot/jeecg-boot#4209]
##### 截图：

![image](https://user-images.githubusercontent.com/58501651/200888664-da43efbf-30ee-419f-9d8d-64c2e2c0af40.png)

**Comment by zhangdaiscott** [comment]
右上角不是设置吗，自己配置

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/200994713-43164e3b-5741-43df-8a83-9d0cf7ecd195.png)

**Comment by menglanglang** [comment]
这个默认不会持久化吧，只是针对本次设置有效，清除缓存又回到默认设置的。

**Comment by menglanglang** [comment]
> 右上角不是设置吗，自己配置


这个默认不会持久化吧，只是针对本次设置有效，清除缓存又回到默认设置的。

**Comment by zhangdaiscott** [comment]
你可以改下配置

**Comment by menglanglang** [comment]
> 你可以改下配置

有文档说明或者配置指导啥的没？还是说需要开发直接改代码。就说说框架有是否持久化配置的操作么？

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043973
