### ISSUE TITLE
线开发-online表单开发-导入数据库表 功能异常

### ISSUE THREAD

**Issue by NZQ2472025825** [jeecgboot/jeecg-boot#4210]
##### 版本号：

3.4.1
##### 前端版本：vue3版？还是 vue2版？

vue3

##### 问题描述：

数据库切换为postgre后，在线开发-online表单开发-导入数据库表 功能异常
我这边是需要在prod里获取数据  而不是public里获取数据
##### 截图&代码：
配置：   登录用户是prod
![image](https://user-images.githubusercontent.com/110712575/200910487-68a8a466-401a-4f48-a2cc-509c501d3a6b.png)
想要prod的     
![image](https://user-images.githubusercontent.com/110712575/200913189-12c9a90d-ace9-4813-8184-fcd0fcb2bad9.png)
但他遍历的是public的
![image](https://user-images.githubusercontent.com/110712575/200913316-ac99f131-8410-4c28-a72f-ae712500dc90.png)
![image](https://user-images.githubusercontent.com/110712575/200915427-1fd3bcc6-acf9-48ef-8aa2-d1ace2eca6ba.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级到最新版看看

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
需要在`src/main/resources/jeecg/jeecg_database.properties`中配置`schemaName`即可解决
参考文档： [常见问题 4](http://doc.jeecg.com/2088984)
![image](https://user-images.githubusercontent.com/30997828/203550514-55e03a45-a023-43eb-826f-de873d4e44a4.png)
![image](https://user-images.githubusercontent.com/30997828/203550566-efbc8225-46ce-4c23-874e-e9f273a0f01e.png)
后台配置截图
