### ISSUE TITLE
菜单管理，保存菜单报错Request failed with status code 404

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#4211]
##### 问题描述：
菜单管理，保存菜单报错Request failed with status code 404新建菜单也不行（直接编辑已经有的菜单，什么都没改，保存也报错）

##### 截图&代码：
Request failed with status code 404

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如何重现？把错误贴以下

**Comment by 378680487** [comment]
就是下载最新的3.4.3ge，然后点菜单管理，，随便点一个菜单，点编辑，什么都别改，再点，确定保存，就保错啊，不是说得很清楚吗，自己去试试就知道了

**Comment by zhangdaiscott** [comment]
测试无问题，无论新增和编辑
![image](https://user-images.githubusercontent.com/3162115/200994133-8bd0a7b8-4072-4bbc-a665-9dbaa6b16716.png)
