### ISSUE TITLE
免登录问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4212]
##### 版本号：
v3.4.3-GA 

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
请教个问题，我们现在是要登录的到token才能调用其他接口的，现在有个项目，他们希望做成免登录的方式，因为他们app已经输入账号密码登录了，可我这又不想丢失token功能，这该怎么弄呢？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
哪你可以在他们的app登录接口，加入jeecg的token生成规则
也就是他们按照jeecg的token规则生成token，给你用
