### ISSUE TITLE
JSearchSelectTag如何改造支持多选

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#4213]
##### 版本号：
v3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前JSearchSelectTag异步下拉搜索支支持单选, 如何改造才可以支持多选。
后台接口貌似是支持多选的，前端页面需要改造，尝试改造了一下，不能回显

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
以支持，待新版本发布

**Comment by Chris-Arith** [comment]
> 以支持，待新版本发布

谢谢, 期待新版本的发布
