### ISSUE TITLE
表格线分离了

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4214]
##### 版本号：
2.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在做图片展示的时，操作列的表格线分离了

##### 截图&代码：

![U`CNB}_U6{0 )Z@}C@LK)V9](https://user-images.githubusercontent.com/15886620/201135264-8456903f-801b-408b-a006-5fa145420809.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么浏览器

**Comment by zhangdaiscott** [comment]
我们项目里也有带图片的列表，格式没问题，你可以参考下代码区别
![image](https://user-images.githubusercontent.com/3162115/201240683-89972fa7-1b29-4aab-94c0-5da9914dcd85.png)

**Comment by LiangYongAI** [comment]
我用的chrome浏览器，我测了一下，发现第一次加载页面时会存在表格线分离的问题，但是我点了一次操作下面的链接后，表格刷新后，线就对齐了，不知道这是不是一个线索？

**Comment by zhangdaiscott** [comment]
这个不好重现，没法处理

**Comment by qq893518283** [comment]
.
