### ISSUE TITLE
打包部署后顶部菜单栏不见，出现空白页情况

### ISSUE THREAD

**Issue by fengliu-A** [jeecgboot/jeecg-boot#4215]
##### 版本号：

v3.3.0
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
打包部署后顶部菜单消失了，无法显示，本地运行正常，切换菜单到左侧也常，用顶部菜单出现空白页的情况

##### 截图&代码：

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/117929123/201245629-de62eb13-0685-40e7-baf3-2fc84ec47179.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看有错吗，你vue2是什么时间下载的代码

**Comment by fengliu-A** [comment]
> F12看看有错吗，你vue2是什么时间下载的代码

可以关闭这个issue了，因为有个页面要设置菜单隐藏，结果作用到所有页面了，辛苦了
