### ISSUE TITLE
个人中心路由跳转

### ISSUE THREAD

**Issue by TBX1314521** [jeecgboot/jeecg-boot#4216]
##### 前端版本：vue2
l

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55613008/201246884-2966784d-c928-46e8-8919-ff4cb7c1f825.png)

![image](https://user-images.githubusercontent.com/55613008/201246941-4dc45542-1bdd-4c14-8488-4bc0a561fce9.png)

个人中心路由怎么跳转

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
补充版本和问题描述

**Comment by TBX1314521** [comment]
![image](https://user-images.githubusercontent.com/55613008/201250099-ac9fe46e-e1d5-42d4-964c-e1e1655c8fe2.png)
我点击个人中心,的时候跳转的是空白页面
![image](https://user-images.githubusercontent.com/55613008/201250221-4d90a8a1-9901-4467-abec-f90f633acb9e.png)
这个路由我去路由文件去配置也不能生效
下面的是版本
![image](https://user-images.githubusercontent.com/55613008/201250301-c7515182-5e8f-456e-8e57-21a8f2172c3f.png)

**Comment by zhangdaiscott** [comment]
菜单角色授权，现在的路由是在菜单配置里，不是你截图的地方配置
![image](https://user-images.githubusercontent.com/3162115/201253472-74a7edb8-82ed-4a4e-b8d7-e171c37c2979.png)

**Comment by TBX1314521** [comment]
菜单配置在那个文件,谢谢啦 我去看看

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/201255157-14b6e417-1d60-4bf8-9595-51dcad33fd7d.png)

**Comment by TBX1314521** [comment]
您好技术人员&nbsp; 一直出现这种情况 是什么问题导致的呢&nbsp; 网速正常,就是在自己电脑上跑不起来,在朋友的电脑上都能跑起来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月11日(星期五) 中午11:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 个人中心路由跳转 (Issue #4216)
