### ISSUE TITLE
无缓存时无法获取数据字典

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecg-boot#4217]
版本号：3.4.3
前端版本：vue3版
问题描述：
src/utils/dict/index.ts的initDictOptions函数只能获取缓存数据，没缓存数据时返回空数组，根本不会请求后台获取数据

截图&代码：
![Dingtalk_20221111133206](https://user-images.githubusercontent.com/23691018/201271148-d58cb4b3-9e71-4884-9f7d-041fcbdec667.jpg)

**Comment by zhangdaiscott** [comment]
这个在启动的时候会初始化
