### ISSUE TITLE
侧边栏导航菜单能否配置成多列的？

### ISSUE THREAD

**Issue by xcne** [jeecgboot/jeecg-boot#4218]
##### 版本号：
v3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
系统功能比较多的时候，现有左侧边栏导航菜单会很长，使用体验不太好
有没有办法配置成图中多列的布局方式？阿里云平台还有用友都是使用的这种菜单
不能的话，能否大概指教一下，从哪个文件下手去修改？
谢谢~
##### 截图&代码：
![menu](https://user-images.githubusercontent.com/10359030/201314421-c49441b1-0a9d-4aa1-b8a8-ef00c21c883b.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己二开，实现路由加载逻辑
