### ISSUE TITLE
附表怎么获取主表字段的信息

### ISSUE THREAD

**Issue by yangylGit** [jeecgboot/jeecg-boot#4219]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/38969228/201508093-13b0fe89-89a6-4704-b759-0719040d2ced.png)
![image](https://user-images.githubusercontent.com/38969228/201508122-55eda11e-6fcc-4b60-837a-97bc65204931.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by yangylGit** [comment]
你说的ty什么意思，没明白你说的，你能够说得具体一点吗

**Comment by yangylGit** [comment]
没明白你说的

**Comment by Chris-Arith** [comment]
> 没明白你说的

哈哈哈, issue里搜一下ty你就明白了

**Comment by zhangdaiscott** [comment]
任务分配的意思，目前不支持你说的功能，规划中

**Comment by tygithub1** [comment]
获取不到, 只能获取配置的外键的值，如果你配置的外键字段是main_id对应主表ID，在js增强中通过`that.form.getFieldsValue()`可以获取到一个对象，其中main_id的值，即为主表ID的值

**Comment by yangylGit** [comment]
好的，感谢

**Comment by gxzhou** [comment]
> ![image](https://user-images.githubusercontent.com/27989856/201636748-fef79e35-2af7-4ff0-99d1-076c5446aa8f.png)

获取到外键值后，我是通过getAction()到后端去获取主表数据的，您不妨一试。
