### ISSUE TITLE
租户：穿透租户查询

### ISSUE THREAD

**Issue by yimogithub** [jeecgboot/jeecg-boot#4220]
##### 问题描述：
因为MybatisPlusSaasConfig中配置了 
        tenantTable.add("sys_role");
        tenantTable.add("sys_permission");
        tenantTable.add("sys_depart");
       等多张表，每次查询，都会默认加上 tenantid=？ 条件查询，但有的时候，我需要不分租户查询所有数据，如何解决？

**Comment by zhangdaiscott** [comment]
用这个注解 @SqlParser 

https://gitee.com/baomidou/mybatis-plus/blob/v3.4.0/mybatis-plus-annotation/src/main/java/com/baomidou/mybatisplus/annotation/SqlParser.java
