### ISSUE TITLE
SysBaseApiImpl中使用了过时的方法

### ISSUE THREAD

**Issue by depthwood** [jeecgboot/jeecg-boot#4224]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
SysBaseApiImpl中使用了过时的方法，如图所示，是否有新的方法来替换？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/65118489/201805946-56ca380a-e3e5-4eec-afb1-00854c3b43ee.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时没有，这个是提醒有sql注入风险的方法，一时半会不会删除
