### ISSUE TITLE
auto-poi 1.3.6 导入2007 xlsx 格式失败, 导入2003 xls 格式正常

### ISSUE THREAD

**Issue by lihongguang-lhg** [jeecgboot/jeecg-boot#4225]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/66587661/201810917-563fc1fa-333b-432a-a1d9-80e1785e7a76.png)
![image](https://user-images.githubusercontent.com/66587661/201810959-f2d4cad3-b060-4d9e-ac15-025a1ddc535f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
现在最新版1.4.4可以先升级看看

**Comment by lihongguang-lhg** [comment]
1.4.4也是同样的错误!
![image](https://user-images.githubusercontent.com/66587661/201814990-14f103aa-e57f-4c1a-8b3a-08caecb18651.png)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lihongguang-lhg** [comment]
那请问用什么版本不会报错呢?

**Comment by lsqGitHub716** [comment]
你新建的导入文件是不是有多余的空白sheet？把多余的sheet删除掉以后，再试试看是否可以上传

**Comment by Sandaman2015** [comment]
> 

删除多余sheet之后可以！

**Comment by lsqGitHub716** [comment]
1
