### ISSUE TITLE
a-button添加v-has报错

### ISSUE THREAD

**Issue by DEC-QI** [jeecgboot/jeecg-boot#4229]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
生成的前端代码按照文档配置页面按钮权限后报错

##### 截图&代码：
![1 1O$XZ`({7K3C4E LKUCN](https://user-images.githubusercontent.com/25652436/202064889-6c2694ab-0c70-405a-8e5b-fa500a28cbda.jpg)
![ZD4`P 7SUHRQ6_1Y%HY$5_J](https://user-images.githubusercontent.com/25652436/202064907-3b661234-ddbe-4ddb-bbd7-ef8baea20505.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by DEC-QI** [comment]
![1 1O$XZ`({7K3C4E LKUCN](https://user-images.githubusercontent.com/25652436/202065117-9fde1288-65da-41c1-b3cf-c7f7844b24b7.jpg)

**Comment by maxxious** [comment]
vue3使用 v-auth
![image](https://user-images.githubusercontent.com/118323262/202072997-649207db-658f-4a22-b218-c1961b666cdb.png)
![E GCAC1Y}D0D)B_7_(W)J`O](https://user-images.githubusercontent.com/118323262/202073077-6c053707-6b89-452b-aa95-6890e0d55d1c.png)
