### ISSUE TITLE
文件的手动上传

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4230]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线表单设计中配置的文件上传使用组件JUpload是自动上传，是否有手动上传组件，在表单提交时完成文件上传动作

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前没有
