### ISSUE TITLE
表单开发和代码生成问题

### ISSUE THREAD

**Issue by wangsiyue** [jeecgboot/jeecg-boot#4231]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/24864022/202076612-fbeff8b5-68ee-43ff-aab0-1be58c2881db.png)
![image](https://user-images.githubusercontent.com/24864022/202076705-db99acf4-96ce-44a3-aac6-aec5b18a770d.png)
这个【查看详情】就是自定义的按钮，请问怎么操作在前端页面能生成相关配置的按钮及函数呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
因为online是低代码在线开发功能，增强不支持代码生成

**Comment by wangsiyue** [comment]
所以，增强的所有功能，怎么移到相关的页面去呢

**Comment by zhangdaiscott** [comment]
做不到，生成完代码，手工开发补充
