### ISSUE TITLE
org.jeecg.common.api.CommonAPI  错误

### ISSUE THREAD

**Issue by zhym86848658** [jeecgboot/jeecg-boot#4232]
##### 问题描述：
我新建了一个微服务模块，包是自定义的；有两张表做了一对一的关联，在获取一张表的列表数据时报错：
No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}

我检查了，在我的启动类我添加了"org.jeecg"的包名

##### 截图&代码：
启动类的代码
`
@Slf4j
@SpringBootApplication(scanBasePackages = {"com.felix", "org.jeecg"})
@EnableFeignClients(basePackages = {"org.jeecg","com.felix"})
@EnableScheduling
@MapperScan(value = {"com.felix.modules.**.mapper*"})

public class FelixParkCloudApplication extends SpringBootServletInitializer implements CommandLineRunner {

    @Autowired
    private RedisTemplate<String, Object> redisTemplate;
    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(FelixParkCloudApplication.class);
    }

    public static void main(String[] args) throws UnknownHostException {
        ConfigurableApplicationContext application = SpringApplication.run(FelixParkCloudApplication.class, args);
        Environment env = application.getEnvironment();
        String ip = InetAddress.getLocalHost().getHostAddress();
        String port = env.getProperty("server.port");
        String path = oConvertUtils.getString(env.getProperty("server.servlet.context-path"));
        log.info("\n----------------------------------------------------------\n\t" +
                "Application Jeecg-Boot is running! Access URLs:\n\t" +
                "Local: \t\thttp://localhost:" + port + path + "/doc.html\n" +
                "External: \thttp://" + ip + ":" + port + path + "/doc.html\n" +
                "Swagger文档: \thttp://" + ip + ":" + port + path + "/doc.html\n" +
                "----------------------------------------------------------");
    }

    /**
     * 启动的时候，触发下gateway网关刷新
     *
     * 解决： 先启动gateway后启动服务，Swagger接口文档访问不通的问题
     * @param args
     */
    @Override
    public void run(String... args) {
        BaseMap params = new BaseMap();
        params.put(GlobalConstants.HANDLER_NAME, GlobalConstants.LODER_ROUDER_HANDLER);
        //刷新网关
        redisTemplate.convertAndSend(GlobalConstants.REDIS_TOPIC_NAME, params);
    }
}
`

报错内容
`
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(value=true), @org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355)
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:95)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:195)
	at com.sun.proxy.$Proxy124.translateDictFromTableByKeys(Unknown Source)
	at **org.jeecg.common.aspect.DictAspect.translateAllDict(DictAspect.java:279)**
	at **org.jeecg.common.aspect.DictAspect.parseDictText(DictAspect.java:164)**
	at **org.jeecg.common.aspect.DictAspect.doAround(DictAspect.java:66)**
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhym86848658** [comment]
我在JeecgSystemCloudApplication这个启动类和我自己新建的启动类都加上了com.felix自定义包名；还是会包上面的错误


@SpringBootApplication(scanBasePackages = {"org.jeecg", "com.felix"})
@EnableFeignClients(basePackages = {"org.jeecg", "com.felix"})

**Comment by zhangdaiscott** [comment]
新的微服务模块，加入了那些依赖？

**Comment by zhym86848658** [comment]
微服务start模块
`<dependencies>
        
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-boot-starter-cloud</artifactId>
        </dependency>
        <dependency>
            <groupId>com.felix.boot</groupId>
            <artifactId>felix-park-biz</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>`


felix-park-biz模块pom依赖

`
<dependencies>
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-system-local-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-boot-base-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>hibernate-re</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.jeecgframework</groupId>
            <artifactId>jeewx-api</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.jeecgframework.jimureport</groupId>
            <artifactId>jimureport-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
`

**Comment by zhangdaiscott** [comment]
微服务为什么引用这个依赖
![image](https://user-images.githubusercontent.com/3162115/202094796-807cd0c3-ae77-4be7-9a1e-cc8c9f715dc3.png)


应该引入system微服务api

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/blob/master/jeecg-server-cloud/jeecg-demo-cloud-start/pom.xml

![image](https://user-images.githubusercontent.com/3162115/202095105-c978185e-45b5-4f5a-ba0c-1b11ffa20498.png)

**Comment by zhym86848658** [comment]
可以了，谢谢；还得再研究一下
