### ISSUE TITLE
添加菜单-访问路径出现404

### ISSUE THREAD

**Issue by YiGuZhiPeng** [jeecgboot/jeecg-boot#4240]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在加菜单时，访问路径怎么写都说404，我前台已经配好了，然后我发现原本已经存在的列表项，他们的访问路径也报404，这是我的原因吗

##### 截图&代码：
![5](https://user-images.githubusercontent.com/88045276/202338714-e898cfc4-6b2e-4fc4-b7d1-34a4de5ee482.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直理的，会接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by YiGuZhiPeng** [comment]
低代码开发是拿过来就有的一级菜单

**Comment by zhangdaiscott** [comment]
前台代码和后台不一致
前台更新了
后台未更新导致

处理方案：把后台更新到最新即可
