### ISSUE TITLE
项目里的README中说 流程管理模块 未开源

### ISSUE THREAD

**Issue by TomZheng1** [jeecgboot/jeecg-boot#4241]
##### 版本号：
11月15日下载的jeecg-boot-master

##### 前端版本：
vue3版

##### 问题描述：
我看项目里的README中说 流程管理模块 未开源，请问这个是不是需要收费？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/vip
