### ISSUE TITLE
代码生成器模板：默认生成的菜单SQL中 is_leaf 字段为1，导致该菜单下的权限子菜单不可见。

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#4242]
##### 版本号：
v3.4.3

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
场景：多表内嵌子表风格

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
已修复，待新版本发布
