### ISSUE TITLE
Online在线功能，数据同步失败

### ISSUE THREAD

**Issue by Mr-chen1144** [jeecgboot/jeecg-boot#4243]
##### 截图&代码：
这是sqlserver，没有注释
![image](https://user-images.githubusercontent.com/103888400/202361647-12e62a6b-743e-458b-b0d4-d8ac70119deb.png)
这是mysql，有注释
![image](https://user-images.githubusercontent.com/103888400/202361783-d1592621-c57b-4802-b386-8626eef32ed1.png)

**Comment by zhangdaiscott** [comment]
注释只有添加的时候会加，变更的时候不同步

**Comment by Mr-chen1144** [comment]
但是我添加的时候，也是没有

**Comment by zhangdaiscott** [comment]
注释这块的逻辑我们非强制，因为有的数据库同步会有问题
