### ISSUE TITLE
一对多ERP风格代码生成，前端页面异常

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#4244]
##### 版本号：
v3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
一对多ERP风格代码生成后，查询区域，主表区域都缺失，分页等也缺失。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20742044/202373392-0dfcf870-5e6a-4e2f-b126-5d6010621383.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
？

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
为复现，你新增一条数据试试，有数据才有分页
![image](https://user-images.githubusercontent.com/30997828/203022724-f452e573-1b9f-4891-a39d-6eeb8f3b1333.png)
