### ISSUE TITLE
自定义树控件，或者下拉控件，在选择其他表的一条数据后，能否像popup一样回填多个值

### ISSUE THREAD

**Issue by lgl8522** [jeecgboot/jeecg-boot#4245]
##### 问题描述：
1.自定义树控件，或者下拉控件，在选择其他表的一条数据后，能否像popup一样回填多个值
2.这里我通过树控件选了一个数据后，记录了他的id，怎么把这个id传到另外一个字段type_id上
![T3 7B3$1M F 583FP681CPD](https://user-images.githubusercontent.com/85995485/202383432-6ce7b67e-3a75-460e-9daa-83f8a38c4885.png)

**Comment by zhangdaiscott** [comment]
不支持
