### ISSUE TITLE
Online报表配置参数设置完如何调用

### ISSUE THREAD

**Issue by ORDHALE** [jeecgboot/jeecg-boot#4249]
##### 截图&代码：

![图片](https://user-images.githubusercontent.com/88198254/202611219-cf335b2b-e2db-4da9-bd0b-e55cfd516a1b.png)
![图片](https://user-images.githubusercontent.com/88198254/202611237-ecab854e-a163-4163-8a2b-c44720a512a0.png)
![图片](https://user-images.githubusercontent.com/88198254/202611249-f54649ca-9e61-4fb9-bae4-ea41bf7bc65f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
参数是url上传递的，不是查询条件
http://vue3.jeecg.com/3078798
