### ISSUE TITLE
建议JUpload组件，disabled为true的时候上传button能够变灰或者其他样式图案，便于知晓无法再点击上传。

### ISSUE THREAD

**Issue by Simonrocker6** [jeecgboot/jeecg-boot#4250]
##### 版本号：
2.4.5

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
文件上传log

##### 截图&代码：

![image](https://user-images.githubusercontent.com/17208248/202640784-bad5b46f-aa26-42d1-be32-aba0c671d94a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
已修改
