### ISSUE TITLE
修改排序字段无效

### ISSUE THREAD

**Issue by xhyuan0426** [jeecgboot/jeecg-boot#4253]
##### 截图&代码：

[1.截图](url)

2.代码
   const { prefixCls,tableContext,onExportXls,onImportXls } = useListPage({
       tableProps:{
            title: 'smallcost',
            api: list,
            columns,
            canResize:false,
            formConfig: {
               labelWidth: 120,
               schemas: searchFormSchema,
               autoSubmitOnEnter:true,
               showAdvancedButton:true,
             },
            actionColumn: {
                width: 120,
             },
             beforeFetch:(params)=>{
           return Object.assign({'column':'costbig_code','order':"desc"},params)
           },
        },
        exportConfig: {
             name:"smallcost",
             url: getExportUrl,
           },
           importConfig: {
             url: getImportUrl
           },
          
   })

**Comment by zhangdaiscott** [comment]
老版本可能有bug,先升级到最新版
