### ISSUE TITLE
导出功能导出的xls异常

### ISSUE THREAD

**Issue by a2995921969** [jeecgboot/jeecg-boot#4255]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2版本3.3.0

##### 问题描述：
本地导出的xls是正常的，部署到服务器导出就有问题，没改过关于导出功能的代码， 日志也没有报错， Linux centos7

##### 截图&代码：
![~`4{9LH C(I$ALV4EZ811GP](https://user-images.githubusercontent.com/64623626/202670131-ae6ac547-e230-4a59-abb6-9b88eac721f0.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题只能你自己排查，多加点日志跟踪看看
