### ISSUE TITLE
Table性能问题

### ISSUE THREAD

**Issue by q060831** [jeecgboot/jeecg-boot#4256]
版本号：3.4.3

前端版本：vue3版

问题描述：
          当table的列中存在多个数据字典替换(render.renderDict)时，性能相当糟糕.我试过当有10数据字典替换是单单选择行都要5s以上，而且经常性卡住。
          虽然后台使用@Dict返回字典文本的话，就不会有这个问题，但是是否考虑优化一下这个呢？
         感觉vue3版的table的性能没vue2版的性能好啊，是我的错觉吗？
         就拿"用户管理"这个原有的页面做比较，同样的环境下在选择行时vue3版的响应明显的没有vue2版的快

**Comment by zhangdaiscott** [comment]
(render.renderDict)时
这个是怎么翻译的？ 调用接口去查询字典翻译。还是初始化的时候一次性加载

**Comment by q060831** [comment]
读取缓存啊
![image](https://user-images.githubusercontent.com/23691018/202837708-884402a3-2da5-4399-82d0-a724ef41dee3.png)

**Comment by zhangdaiscott** [comment]
走缓存应该很快，你多少个字段，几个设置了字典翻译

**Comment by zhangdaiscott** [comment]
你使用vuet tools了吗

**Comment by zhangdaiscott** [comment]
测试了9个字段的翻译，没什么大问题
![20221121_165933](https://user-images.githubusercontent.com/3162115/203008581-e9aebedd-74b0-4c80-a3fc-94ddc9ddb6cb.gif)


现在vue tools有严重bug很卡，你可以看看你是不是vue tools的问题，是的话，关闭后看看效果

**Comment by q060831** [comment]
前两天没空，我今天卸载vue tools还是慢。
我再研究研究

**Comment by 1298191366** [comment]
我这里也没有复现出来，我是用了10个字典，每个字典有9项，走的缓存
![1](https://user-images.githubusercontent.com/30997828/203486788-2800790c-4777-44d8-8fc8-47edef54e687.png)
![卡顿](https://user-images.githubusercontent.com/30997828/203486838-0f5e0cc8-140a-49e0-bb20-de2990f96846.gif)
