### ISSUE TITLE
低代码平台3.3.0  online报表模糊查询

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecg-boot#4260]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
当前版本的online报表（JPopup组件） 查询字段不支持默认模糊查询功能，看到 3.4.4 有升级低代码平台，修改pom parent 的版本到3.4.4，发现也不行，请问有什么办法支持默认模糊查询吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue3版实现了，vue2没实现

**Comment by cdsuifeng** [comment]
那除了加 * 处理，有其他的办法吗

**Comment by cdsuifeng** [comment]
解决方案：JPopupOnlReport.vue
查询部分修改如下：
`<template v-else>
              <a-col :md="8" :sm="24" :key=" 'query'+index ">
                **<j-input v-if="item.view == 'string'" v-model="queryParam[item.field]" :placeholder="'请输入'+item.label"></j-input>**
                <online-query-form-item v-else :queryParam="queryParam" :item="item" :dictOptions="dictOptions"></online-query-form-item>
              </a-col>
 </template>`
