### ISSUE TITLE
vue2版，去掉前端指定的排序字段

### ISSUE THREAD

**Issue by xnhel** [jeecgboot/jeecg-boot#4261]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/98070616/202945823-6029771a-d728-48e0-9d43-d0ad0cb9664e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
多看文档和示例
![image](https://user-images.githubusercontent.com/3162115/202946496-61ef7f7e-0141-4816-b6bb-3d4573de44f6.png)

**Comment by xnhel** [comment]
> 多看文档和示例 ![图像](https://user-images.githubusercontent.com/3162115/202946496-61ef7f7e-0141-4816-b6bb-3d4573de44f6.png)

谢谢大佬，明白了
