### ISSUE TITLE
JAVA后端权限问题

### ISSUE THREAD

**Issue by gyf946958761** [jeecgboot/jeecg-boot#4262]
##### 问题描述：
controller的方法上加@RequiresPermissions注解，提示 没有权限，请联系管理员授权，已在菜单和角色管理里面添加相应的权限

##### 截图&代码：
![QQ图片20221121102920](https://user-images.githubusercontent.com/118702500/202950238-d06a7594-31ee-41d6-8e9b-303bf0387647.png)
![QQ图片20221121102926](https://user-images.githubusercontent.com/118702500/202950246-5cda0c16-2e58-4013-941f-b03468ef8ad3.png)
![QQ图片20221121102931](https://user-images.githubusercontent.com/118702500/202950255-eec28424-bd29-4cfc-ae89-d2dee8495102.png)
![QQ截图20221121103029](https://user-images.githubusercontent.com/118702500/202950495-0e2b4a3d-5c81-4f83-9c84-841898a073d4.png)
![QQ截图20221121103118](https://user-images.githubusercontent.com/118702500/202950712-19725656-58c5-46fc-85ef-08ab7c838cd6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
退出重现登录

**Comment by 19373842811** [comment]
前后端重启，也重新登录了，还是这样

**Comment by lzl19900514** [comment]
遇到同样问题了，升级的sql也执行了，授权了，但还是存在

**Comment by zhangdaiscott** [comment]
退出重新登录
