### ISSUE TITLE
定时任务相关的一直会报表不存在

### ISSUE THREAD

**Issue by jinbear** [jeecgboot/jeecg-boot#4266]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

定时任务相关的一直会报表不存在
是否是mysql表名大小写问题？
那怎么去配置？
##### 截图&代码：
![image](https://user-images.githubusercontent.com/24811278/202986182-6b4420d3-f53d-4434-8ed6-8930c15325b6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
3
