### ISSUE TITLE
列表查询-下拉框查询条件选择值后不自动触发查询

### ISSUE THREAD

**Issue by BruceOuyang** [jeecgboot/jeecg-boot#4267]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
代码生成生成的代码，任意字典类型的下拉字段设为查询条件，选择值后都不会自动触发执行查询。

##### 截图&代码：
代码生成生成的代码

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
本来也没实现自动触发查询，需要，自己js事件即可
