### ISSUE TITLE
如何生成多对多关系低代码

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4269]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
多对多关系是否能用低代码来生产，文档上只介绍了一对多、一对一，是否可以用生成多次合并的方式来生成多对多关系，其中一个表还要改成多对多中间表，是否可行？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不可行

**Comment by yingw** [comment]
> 不可行

那有什么建议吗？

**Comment by zhangdaiscott** [comment]
如果不需要中间表，只是为了关联其他记录，可以用popup实现，支持生成；
如果非要中间表，只能生成完代码，自己写代码；

**Comment by yingw** [comment]
> 如果不需要中间表，只是为了关联其他记录，可以用popup实现，支持生成； 如果非要中间表，只能生成完代码，自己写代码；

好的，谢谢建议。你说的popup是指这种弹出页选择多个记录吗？如果是的话取到了这些ids就正常是记录在主表的某个字段里？你说的这种不需要中间表是不是就是这个存储方式？好像能实现多对多，但是不能从另一端找到这层关系。

那如果同时这些id再手动存到中间表，在第二个表也做同样的事情，再想办法在读取的时候关联到自己的popup id上，是不是勉强能实现

![image](https://user-images.githubusercontent.com/1177503/203018865-40c13c46-f8c9-4c4e-9237-569ac8f6bf42.png)
