### ISSUE TITLE
生产好的低代码和online表单是数据记录建议如何发布到生产环境去

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4270]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在开发或测试环境做好了系统设计，用online表单生成了代码、创建了数据表，官方建议如何发布到生产环境去？代码和业务表可以手动打包和发布脚本，但是online表单里面的 记录是没有的，这部分就没有一个版本控制么？如果从数据库反向导入online表单，会缺失一些备注信息，暂时没想到特别好的方式。请指教。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码都生成了，哪就自己原生搞。
关于online的配置，可以用Jeecg online数据同步工具
http://cloud.jeecg.com/page?id=1322087025830039554

**Comment by yingw** [comment]
感谢，可能是我文档没看仔细，没注意到在这里还有个同步工具，我试一下
