### ISSUE TITLE
SysUser 缺少注解@TableName("sys_user") 同样 SysPermission SysRolePermission SysUserRole 缺少注释

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#4271]
##### 版本号：

3.4.0
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
SysUser 缺少注解@TableName("sys_user") 同样 SysPermission SysRolePermission SysUserRole 缺少注释

会有影响吗
我反向代理 测试建表 发现少了这么几张表  

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
驼峰符合命名规范的，不显示声明也可以

**Comment by TomYule** [comment]
> 

好的
