### ISSUE TITLE
online接口SQL注入攻击

### ISSUE THREAD

**Issue by smilebeggar** [jeecgboot/jeecg-boot#4272]
##### 截图&代码：

![微信图片_20221121205357](https://user-images.githubusercontent.com/38646117/203060618-34f5d3dd-6098-445b-95cf-2aa3a3504d9e.png)

![微信截图_20221121205415](https://user-images.githubusercontent.com/38646117/203060632-ffee7f2f-9bca-4a44-bf08-6a5a2f7c9e5f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
建议先升级到最新版，我们在不断优化，类似的问题修复过，你看看最新版是否还存在，存在的话，反馈给我们
