### ISSUE TITLE
popup组件可以设置为只能单选返回一个记录么？

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4273]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
3

##### 问题描述：
发现popup只能多选，不太适用于外键使用popup单选一个数据返回id的场景，是否支持如何配置？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2503900
multi
