### ISSUE TITLE
只读字段发布后不显示

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4274]
##### 版本号：
最新的3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
只读字段代码在部署后不起作用

##### 截图&代码：
我设置了一个：不和数据库同步、只读的字段，只用作popup返回时在表单上显示看。
![image](https://user-images.githubusercontent.com/1177503/203080337-b98bb2ad-dafa-4016-ab73-e896332f584a.png)

但是发现设置后在online表单测试时正常显示：
![image](https://user-images.githubusercontent.com/1177503/203080080-898fe7cc-f886-4443-baa4-0c4a722545fe.png)
但代码发布上去后就不显示这个只读的字段了：
![image](https://user-images.githubusercontent.com/1177503/203080204-1877f585-9d74-4218-baad-47d2895313d5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by yingw** [comment]
还发现有点奇怪的是第二个图里面两个字段的名称应该是“编码定义ID”和“编码定义名称”的，都变成了“编码定义”？发不上去名字对了一个，少了一个字段字段

**Comment by zhangdaiscott** [comment]
你怎么发布的

**Comment by yingw** [comment]
就是“生成代码”，在开发环境，重启java和node环境看的，用的还是本地的数据库，和做online设计一个环境，其他模块都是正常的

**Comment by zhangdaiscott** [comment]
I fu l ~
online是在线功能，低代码概念。不是给代码生成专用
代码生成，并不支持所有的功能点生成

https://github.com/jeecgboot/jeecg-boot/issues/4231

**Comment by yingw** [comment]
可能是我没说清楚，我是在online表单设计里：设计了表结构、同步数据库、用online表单测试（这时候是好的）、再生成代码，本来就在一个页面里做的事情，不是你理解的online在线功能

**Comment by yingw** [comment]
看了你应用的issue，可能是我理解错了，也就是online表单设计好，如果用了增强功能就直接用，不用生成低代码，那是不是要么生成代码手动实现一遍在线可以做的事情，再写自己的代码，要么在线用增强功能，但是不能加自己的部分。这低代码只能做online的最基础功能

**Comment by yingw** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
online是完全在线模式，不需要生成代码，如果需要增加逻辑，使用增强

**Comment by yingw** [comment]
好的，明白了，谢谢。online表单有增强功能，能实现大部分定制逻辑（不改界面），只有碰到很特殊的需要无法用online实现再生成代码，但只能包含基础部分功能。官方推荐的应该是online表单，而不是生产代码改，对吧。谢谢。 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
如果online实现满足不了需求的情况下，再使用代码生成，哪个时候就得完全手写了，跟online就脱离了

**Comment by zhangdaiscott** [comment]
未来的趋势是尽量少写代码，所以低代码肯定是jeecgboot的主打概念

**Comment by yingw** [comment]
> 如果online实现满足不了需求的情况下，再使用代码生成，哪个时候就得完全手写了，跟online就脱离了

原来如此。。看来是我理解有误了，非常感谢指教，以后尽量用online
