### ISSUE TITLE
vue2缓存bug

### ISSUE THREAD

**Issue by huangzenghuang** [jeecgboot/jeecg-boot#4276]
##### 版本号：
![image](https://user-images.githubusercontent.com/45776589/203199129-bb92cbf9-e2aa-431a-9aaf-d64b141f17a0.png)

##### 前端版本：vue3版？还是 vue2版？
Vue2

##### 问题描述：
在A页面里面关闭B页面，再重新打开B页面未清除缓存，但localstore和Vuex里面的include已经把B页面的缓存删了，估计是Vue keep-alive的bug，个人建议手写一个缓存组件，提供手动清除缓存api

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by huangzenghuang** [comment]
是要什么版本，vue还是node，
vue :2.9.6
node: v16.17.1
package.json
{
  "name": "vue-antd-jeecg",
  "version": "3.1.0",
  "private": true,
  "scripts": {
    "pre": "cnpm install || yarn --registry https://registry.npm.taobao.org || npm install --registry https://registry.npm.taobao.org ",
    "serve": "vue-cli-service serve",
    "build:test": "vue-cli-service build --mode test",
    "build": "vue-cli-service build",
    "report": "vue-cli-service build --report",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@antv/data-set": "^0.11.4",
    "@jeecg/antd-online-mini": "3.1.0-beta",
    "@tinymce/tinymce-vue": "2.1.0",
    "@toast-ui/editor": "^2.1.2",
    "@vue/composition-api": "^1.7.0",
    "ant-design-vue": "^1.7.2",
    "awe-dnd": "^0.3.4",
    "axios": "^0.18.0",
    "babel-runtime": "^6.26.0",
    "china-area-data": "^5.0.1",
    "clipboard": "^2.0.4",
    "codemirror": "^5.46.0",
    "cron-parser": "^2.10.0",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.8.0",
    "dingtalk-design-libs": "^0.0.24",
    "dom-align": "1.12.0",
    "enquire.js": "^2.1.6",
    "hard-source-webpack-plugin": "^0.13.1",
    "js-cookie": "^2.2.0",
    "js-xlsx": "^0.8.22",
    "lodash.get": "^4.4.2",
    "lodash.pick": "^4.4.0",
    "md5": "^2.2.1",
    "mini-css-extract-plugin": "^2.6.1",
    "nprogress": "^0.2.0",
    "object-sizeof": "^1.6.3",
    "purgecss-webpack-plugin": "^5.0.0",
    "qiankun": "^2.5.1",
    "speed-measure-webpack-plugin": "^1.5.0",
    "svg-sprite-loader": "4.1.3",
    "tinymce": "5.4.1",
    "viser-vue": "^2.4.8",
    "vue": "^2.6.10",
    "vue-area-linkage": "^5.1.0",
    "vue-cropper": "^0.5.4",
    "vue-i18n": "^8.7.0",
    "vue-loader": "^15.7.0",
    "vue-ls": "^3.2.0",
    "vue-photo-preview": "^1.1.3",
    "vue-print-nb-jeecg": "^1.0.9",
    "vue-router": "^3.0.1",
    "vue-splitpane": "^1.0.4",
    "vuedraggable": "^2.20.0",
    "vuex": "^3.1.0",
    "vxe-table": "2.9.13",
    "vxe-table-plugin-antd": "1.8.10",
    "webpack-bundle-analyzer": "^4.6.1",
    "xe-utils": "2.4.8",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.2.5",
    "@vue/cli-plugin-babel": "^3.3.0",
    "@vue/cli-plugin-eslint": "^3.3.0",
    "@vue/cli-service": "^3.3.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "7.2.3",
    "compression-webpack-plugin": "^3.1.0",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.1.0",
    "html-webpack-plugin": "^4.2.0",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "unplugin-vue2-script-setup": "^0.10.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/strongly-recommended",
      "@vue/standard"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {
      "generator-star-spacing": "off",
      "no-mixed-operators": 0,
      "vue/max-attributes-per-line": [
        2,
        {
          "singleline": 5,
          "multiline": {
            "max": 1,
            "allowFirstLine": false
          }
        }
      ],
      "vue/attribute-hyphenation": 0,
      "vue/html-self-closing": 0,
      "vue/component-name-in-template-casing": 0,
      "vue/html-closing-bracket-spacing": 0,
      "vue/singleline-html-element-content-newline": 0,
      "vue/no-unused-components": 0,
      "vue/multiline-html-element-content-newline": 0,
      "vue/no-use-v-if-with-v-for": 0,
      "vue/html-closing-bracket-newline": 0,
      "vue/no-parsing-error": 0,
      "no-tabs": 0,
      "indent": [
        "off",
        2
      ],
      "no-console": 0,
      "space-before-function-paren": 0
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/203324198-0bbe4d2b-5349-4922-8d3d-4c5bb83de638.png)
