### ISSUE TITLE
同步online表单数据工具的建议

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4277]
##### 问题描述：
使用online数据同步工具： http://cloud.jeecg.com/page?id=1322087025830039554  发现是通过配置两边数据源直接导入的方式，建议增加导出SQL后手工导入的方式，毕竟生产环境的数据库一般情况下是和开发测试连不上的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不采纳，我们需要兼容不同的数据库，采用你的方案工作量太高

**Comment by yingw** [comment]
那可否告知这个工具大概会操作哪几个表，也就是online表单和online报表配置相关表，我至少可以在迁移后用导数据的方式更新同步到生产环境。同步工具的源码也没找到，看不了。 @zhangdaiscott
