### ISSUE TITLE
数据字典的字段名称不统一

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4278]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
V3

##### 问题描述：
在数据字典功能里，注意到列表上“字典编号”，实际是表单里“字典编码”，估计是笔误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1177503/203208922-0226065b-3c21-4025-b611-6ed74a31bab5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
修复了，回头发布
