### ISSUE TITLE
3.4.4的操作区域跑左侧了？

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4279]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
发现3.4.4 的在线表单功能测试时，列表里面原本在最右侧的操作栏跑到最左侧来了。我测试了3.4.3还是左侧的，官网的demo也跑到右侧去了。但是生成的代码还是在右侧的

##### 截图&代码：
3.4.4 online
![image](https://user-images.githubusercontent.com/1177503/203211097-bbf095fb-b8e3-4cde-9c2e-7cdeab3cc5a9.png)
官网的3.4.4 demo
![image](https://user-images.githubusercontent.com/1177503/203211213-1c4d904d-0255-4fb3-9442-e5faac2bc65c.png)
3.4.3的
![image](https://user-images.githubusercontent.com/1177503/203211288-1e00ac18-7ae5-46d4-994f-437a4c16d7ee.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/203217647-dae59062-33e9-44d3-9cd8-e60c08b0b609.png)

**Comment by yingw** [comment]
收到，谢谢
