### ISSUE TITLE
列表界面的字段宽度是否可调

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4281]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
3

##### 问题描述：
注意到在online表单设计好表后，查询列表结果集界面以及表单界面的每个字段好像是等宽的，即使在页面属性里面设置了宽度，也不起作用，文档说明这个宽度是一对多子表编辑用的，http://doc.jeecg.com/2044062

那列表里面的字段能否通过扩展参数或哪里调整一下？我试了几个width、length都无作用

另外：某些字段比较长，超出部分就显示。。。了正常，但是在关联记录类型里，只显示了十几个字符就显示。。。了，大部分内容都看不到。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1177503/203219159-e11c8bd4-900f-4f40-8342-81d99a8557f4.png)
![image](https://user-images.githubusercontent.com/1177503/203219250-c4bfd1b0-d73d-43f8-99cb-2192432510cd.png)

![image](https://user-images.githubusercontent.com/1177503/203219316-373a51fd-2316-4a2a-87a9-98ec07bcad09.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前列表和表单是做了自适应，没有做宽度设置

**Comment by yingw** [comment]
好的，希望后面加上相关功能，这个没有，还是挺不方便的

**Comment by yingw** [comment]
可否将这个问题改成建议，不要关闭，谢谢。
