### ISSUE TITLE
使用online表单同步工具同步数据后同步数据库时报错

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4284]
##### 版本号：
3.4.4 + Sync Tool

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
使用online表单同步工具  (<http://cloud.jeecg.com/page?id=1322087025830039554>)，同步成功，在系统里同步数据库会报错，打开表单什么也不改保存一下，再同步就好了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1177503/203258271-1aea14cc-a825-4939-bb33-5222de9d508a.png)

![image](https://user-images.githubusercontent.com/1177503/203258444-763b461c-5e0b-4166-965a-d85bf8a9dae5.png)

```
Could not parse mapping document: null (INPUT_STREAM)
org.hibernate.boot.InvalidMappingException: Could not parse mapping document: null (INPUT_STREAM)
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么数据库

**Comment by zhangdaiscott** [comment]
应该是某些字段同步的不完整，版本不一致

**Comment by yingw** [comment]
两边都是一样的MySQL5.7版本，区别是一个是Windows版，一个是CentOS

**Comment by zhangdaiscott** [comment]
跟数据库没关系，应该是同步工具老了

**Comment by zhangdaiscott** [comment]
ldd

**Comment by yingw** [comment]
ldd 是啥？

**Comment by lvdandan16** [comment]
已修复，下个版本升级
