### ISSUE TITLE
Text类型多行文本在内容过长时预览详情页面会超出页面

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4285]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
如图

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1177503/203267304-f29af361-12bb-4ace-b3b1-ab2f7b6d677a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收到

**Comment by tygithub1** [comment]
测试未发现该问题，你这个是自己写的页面？
