### ISSUE TITLE
官网上的前端示例怎么找不到代码

### ISSUE THREAD

**Issue by 17671670801** [jeecgboot/jeecg-boot#4287]
##### 版本号：
v2

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
在官网示例网站里找到了想要实现的例子，但是在下载下来的前端代码里找不到该例子。
http://boot.jeecg.com/  统计报表模块-项目性质收入统计
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是online图表的功能，目前开源暂时没有
