### ISSUE TITLE
数据迁移时id外键无法导出导入

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4290]
##### 版本号：
3.x

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
发现在使用导入导出工具（导出Excel）往其他环境迁移数据的过程中，由于id是自增长不导出的格式，如果表之间保存了id作为外键，导入后外键关系会丢失。

数据库设计上设置了外键，界面上使用popup和关联记录试过都是如此，再加上id字段默认不允许设置为列表显示以导出，就无法在导出Excel里保留和导入id数据。

请教官方的建议用法

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1177503/203460733-520e48ee-d4f5-42e2-b4fd-823cb443eb58.png)
![image](https://user-images.githubusercontent.com/1177503/203461181-736ca4fd-4aa3-4719-be5c-411d3a42f92e.png)
![image](https://user-images.githubusercontent.com/1177503/203461245-40d3d361-a3d5-497f-9ba2-3291e919c0d4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
导入导出，不做外键关系。如果你需要迁移online配置，使用http://cloud.jeecg.com/page?id=1322087025830039554

**Comment by yingw** [comment]
这个online同步工具我用过了可以用，这个是同步配置数据的。我关注的主要还是业务数据的导入导出，并且需要用到外键关联，不然这个导入导出功能只有导出到线下有用，导入没用了，导数据只能用数据库，不方便用户自己操作备份恢复。
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
哪没这功能
