### ISSUE TITLE
online  1对多表， 怎么配置 隐藏子表的列；

### ISSUE THREAD

**Issue by masenmiao** [jeecgboot/jeecg-boot#4291]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online  1对多表， 没法隐藏子表的列；
如果页面属性配置成 表单不显示，则无法增强设置数据保存到DB；这个怎么通过Online的配置或 增强来实现；

**Comment by zhangdaiscott** [comment]
目前还不支持，我们考虑下
