### ISSUE TITLE
测试菜单单体部署可以，升级成微服务失效

### ISSUE THREAD

**Issue by aseaofword** [jeecgboot/jeecg-boot#4292]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
还是 vue2版

##### 问题描述：
自己加的测试菜单，单体部署的时候正常，升级成微服务后，请求localhost:9999报错404，但是其他的本来有的项目正常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/73841358/203492430-1477acf8-a06d-4b87-a4a6-07d10be5e4e5.png)

![image](https://user-images.githubusercontent.com/73841358/203492477-7868164d-4e90-471b-ba8e-b4a4c0dd872b.png)
其他菜单：
![image](https://user-images.githubusercontent.com/73841358/203492515-99cdcf5e-3136-4753-a3f1-186efcee0887.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
新的请求地址是什么？
有没有做网关配置？

**Comment by aseaofword** [comment]
> 新的请求地址是什么？ 有没有做网关配置？

什么地址？我前端是配成gateway的地址了，而且其他模块也没问题
![image](https://user-images.githubusercontent.com/73841358/203520287-b7ce1a27-aa94-42af-b844-fb8973def136.png)
起了4个模块gateway、demo、system、nacos，我后来自己建了一个只有一个字段的表可以，但是自带的ai_control_single这个表不行

**Comment by zhangdaiscott** [comment]
gateway网关配置，不懂的话，百度下

**Comment by zhangdaiscott** [comment]
有新的实例或者实例下新增请求前缀，需要做网关配置
![image](https://user-images.githubusercontent.com/3162115/203675735-e83df589-c013-4902-8b14-d30e5bdba75b.png)
