### ISSUE TITLE
3.4.0版本中缺少3.3升3.4.0的增量SQL，且无法跳过从直接3.3升3.4.0+

### ISSUE THREAD

**Issue by guoqmao** [jeecgboot/jeecg-boot#4293]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue3 & vue2

##### 问题描述：
发布的3.4.0版本中增量SQL中仍然是3.2升级到3.3增量sql，并没有3.3升级到3.4的增量sql，如果直接跳过，再从3.4.0升级到3.4.2时缺少表。这也就导致无法从3.2.0平滑升级到3.4.3

##### 截图&代码：
<img width="301" alt="image" src="https://user-images.githubusercontent.com/31772412/203500957-a3b03bc3-63f8-4952-8d94-8fcef2a5ec03.png">

**Comment by zhangdaiscott** [comment]
每个版本里面都有一个增量升级sql，如果没有的话就是没有可执行的升级sql

https://gitee.com/jeecg/jeecg-boot/tags

**Comment by guoqmao** [comment]
3.4版本里的增量SQL和3.3版本里一样。我起初也认为3.4.0是没有增量SQL的，但实际验证从3.4.0升级到3.4.2时，执行3.4.2版本里的增量SQL报表缺失错误，说明从3.3升到3.4.0时，肯定有增量SQL产生过，只是放错（我认为）SQL脚本，放了个3.2到3.3的版本增量SQL，烦请作者核实验证下。谢谢

**Comment by guoqmao** [comment]
可能确实3.3升级到3.4.0时，确实没有增量sql。
我自己已经解决，是3.4.2版本中的增量SQL（3.4.0升级到3.4.2增量脚本sql）有点问题，如图，需把ALTER TABLE `sys_comment`
MODIFY COLUMN `comment_content` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '回复内容' AFTER `comment_id`;。
给注释掉，可执行成功。
但后面的sys_comment表创建的字符集是utf8，应该会有emoji表情包存储的问题，所以我猜测才有前面的ALTER comment_content字段的语句，应该将ALTER语句放到create后面，不知道我理解是否正确。
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/31772412/203689074-0816a11a-e572-4a63-8e7f-f42bf705726c.png">

**Comment by zhangdaiscott** [comment]
ok
