### ISSUE TITLE
【BUG】--数据源管理-新增数据源未返回正确结果

### ISSUE THREAD

**Issue by AaronWang3369** [jeecgboot/jeecg-boot#4294]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/16057795/203505499-7e72e4ea-cbc2-469a-807c-707e989fd2e0.png)
用了mysql的驱动却连接成功了。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
预期是什么结果？

**Comment by AaronWang3369** [comment]
> 预期是什么结果？

SqlServer数据源 选择的却是mysql驱动类 为什么会连接成功呢？

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
