### ISSUE TITLE
WebSocket中jeecgRedisClient会报null，debug发现没有成功注入

### ISSUE THREAD

**Issue by Qiang-Ming** [jeecgboot/jeecg-boot#4296]
##### 截图&代码：
<img width="738" alt="image" src="https://user-images.githubusercontent.com/69196947/203667273-0e5e1c90-d00a-4551-a71a-9114257f9b75.png">
改造成
<img width="556" alt="image" src="https://user-images.githubusercontent.com/69196947/203667325-4eb616e6-97fc-4255-81c1-6844cbba3ea6.png">
才能成功注入值。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你确认下你本地环境问题吧，这个是基础功能，如果不好使，我们本地早发现了

**Comment by Qiang-Ming** [comment]
> 

项目运行都是正常的，就是官方system模块下的websocket，连接都正常，但是调用jeecgRedisClient会直接报null。我看了你们自己的代码是没有实际使用jeecgRedisClient这个变量的。按照Spring的注入规则，Websocket连接时新创建的Websocket对象不在spring的管理中，所以这个注入会失败。

**Comment by zhangdaiscott** [comment]
是你自己新写的socket调用？

**Comment by davewang** [comment]
确实式这样，我也遇到了

**Comment by Qiang-Ming** [comment]
> 确实式这样，我也遇到了



> 大佬解决了吗？

第二张图给出来解决办法，定义为静态，然后set方法统一给静态变量赋值即可
