### ISSUE TITLE
用户管理里的数据权限不生效

### ISSUE THREAD

**Issue by microjava00101** [jeecgboot/jeecg-boot#4297]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
用户管理里的数据权限不生效，设置了管理员角色只能看性别为男的用户，没有效果

##### 截图&代码：

![image](https://user-images.githubusercontent.com/118946900/203672675-c2881138-83ff-45b8-adf7-852c6a47b18f.png)
![image](https://user-images.githubusercontent.com/118946900/203672726-0b94625d-a21f-484c-9691-81be99e3884e.png)
![image](https://user-images.githubusercontent.com/118946900/203672744-a75165b6-6324-41fd-b3d5-71d5a7ca1b6f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044047
