### ISSUE TITLE
钉钉中访问项目问题

### ISSUE THREAD

**Issue by yydAble** [jeecgboot/jeecg-boot#4299]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在钉钉微应用中配置pc端首页地址，访问提示应用不存在。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/101792055/203684374-e7e8ef79-fba3-4cfa-b3d8-94ee23674332.png)
还原测试  新建钉钉应用把 http://boot3.jeecg.com/ 房间pc端首页访问即可

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
你的`client-id`或者`client-secret`是否正确，还有这个你需要配置你的前台，而不是官网的，回调地址不一致的话，也无法实现钉钉登录
![image](https://user-images.githubusercontent.com/30997828/205567322-8732f5b5-d9d6-47e3-aa79-f992fd1a0b9c.png)


不正确的页面
![image](https://user-images.githubusercontent.com/30997828/205565644-df6e3b3c-a4cf-4b72-8c24-a0dfd6ca4a2f.png)

正确的页面
![image](https://user-images.githubusercontent.com/30997828/205567399-e76ed13f-6cdb-4802-859b-807f9ff50c10.png)

**Comment by yydAble** [comment]
> 2022年12月5日 下午2:48，1298191366 ***@***.***> 写道：
首先说一下，问题已经解决。
再来说说问题产生的原因：主要原因是jeecg-boot-v3中配置了如果在钉钉中打开会直接跳转到Oauth2LoginRoute，而实际上在钉钉中打开是直接通过钉钉api获取code来实现登录的。我们的项目是从v2升级到v3的所以没有配置appid这些参数，再加上钉钉中调试比较麻烦，所以导致这样的原因。如果可以的话，希望把第三方登录做个配置。
