### ISSUE TITLE
Online表单开发 导入数据库表 没有把MySQL 表注释查到

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#4301]
##### 版本号：
3.4.0

##### 问题描述：
![图片](https://user-images.githubusercontent.com/13266764/203700650-c1e77c1b-2a79-4091-ab8d-a7cd39b41073.png)
Online表单开发
导入数据库表 没有把MySQL 表注释查到

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/13266764/203700795-e599a758-ca12-476a-a25c-87253b7fbf6f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
注释非必须逻辑，手工改吧

**Comment by TomYule** [comment]
要符合什么逻辑呢

**Comment by zhangdaiscott** [comment]
是注释并代码没做那么强的限制，不同的数据库兼容性不一样，所以注释不是必须的同步逻辑
所以可能某些场景，表名、字段的注释会不同步

**Comment by TomYule** [comment]
> 

这算不算bug呢

**Comment by TomYule** [comment]
新增一条 在线开发的表 同步后 注释 还是没有到MySQL里面
![图片](https://user-images.githubusercontent.com/13266764/205242628-5a7fd2c3-1e7c-439b-b1b3-c0793d9dead2.png)
