### ISSUE TITLE
附表树形

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4303]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
附表需要树表结构 可以手动改写么

##### 截图&代码：
![image](https://user-images.githubusercontent.com/118323262/203730340-d9eabbf8-4f50-43da-a2a0-90ab9a56c87b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码生成手工编码可以，在线online不行

**Comment by softboy99** [comment]
希望未来版本可以支持
