### ISSUE TITLE
vue2版本前端，如何给菜单添加自定义参数，并在选择菜单时候存起来

### ISSUE THREAD

**Issue by a000tc** [jeecgboot/jeecg-boot#4304]
##### 问题描述：
想要的效果：在菜单加上自定义参数（第一级菜单名字，第二级菜单名字，第三级菜单名字）并在点击菜单时把这三个属性的内容存到session,想知道哪个文件哪个方法加上上这些自定义参数，哪个文件的select方法可以保存这些数据
![project](https://user-images.githubusercontent.com/23735356/203747266-5d68e75b-a48a-4eeb-ba9d-7984002a793d.png)
类似以下 ：first,second,third

####所做尝试：
在menu文件夹下index.js的renderMenuItem和renderSubMenu方法，该尝试无效。
![jeecgMenu](https://user-images.githubusercontent.com/23735356/203747149-176204eb-aaa3-49dd-ac65-10bb1ae1fdd8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
？没明白，你的目的是什么

**Comment by a000tc** [comment]
您好，我想每次点击菜单的时候在session存下他的中文名和它所有父级的中文名


***@***.***
 
发件人： JEECG
发送时间： 2022-11-24 18:30
收件人： jeecgboot/jeecg-boot
抄送： yangshengzhen; Author
主题： Re: [jeecgboot/jeecg-boot] vue2版本前端，如何给菜单添加自定义参数，并在选择菜单时候存起来 (Issue #4304)
？没明白，你的目的是什么
