### ISSUE TITLE
关于报表的查询功能--模糊查询

### ISSUE THREAD

**Issue by hanpeiting1996** [jeecgboot/jeecg-boot#4305]
##### 问题描述：
1-制作数据报表的时候会使用模糊查询，但是使用模糊查询搜索会出现精确想搜索某数无法精确搜出，请问目前报表会支持模糊搜索可以配置下拉选择嘛？

2-请问下按照视频教程在模糊搜索加入*，可以模糊搜索，
但是如果数列为矿泉水和矿泉水瓶1，这两种，
想通过模糊搜索 *泉水把所有矿泉水搜索出来，但是加*的无法使用，搜索不出信息，请问有办法通过模糊查询搜索出来我想要的某个信息嘛？谢谢

##### 截图&代码：
![1669282748598](https://user-images.githubusercontent.com/118969528/203749948-e862310c-d43e-4166-8037-4d14756107ee.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
问题1：你可以使用下拉框或者下拉多选框配置字典，可以支持模糊查询的，下个版本支持名称搜索
参考文档：http://report.jeecg.com/2083759
问题2：不加星号也可以查询出来，你说的依稀是我下面这种吗
![image](https://user-images.githubusercontent.com/30997828/204077412-367ab157-2f54-44d9-a5dc-afed2915745b.png)

**Comment by 1298191366** [comment]
> 问题1：你可以使用下拉框或者下拉多选框配置字典，可以支持模糊查询的，下个版本支持名称搜索 参考文档：http://report.jeecg.com/2083759 问题2：不加星号也可以查询出来，你说的依稀是我下面这种吗 ![image](https://user-images.githubusercontent.com/30997828/204077412-367ab157-2f54-44d9-a5dc-afed2915745b.png)
