### ISSUE TITLE
下拉列表框字段字典table加条件后搜索区域的字典没加载进去

### ISSUE THREAD

**Issue by HWGALLEN** [jeecgboot/jeecg-boot#4306]
##### 版本号：
3.4.4

##### 前端版本：
vue2版

##### 问题描述：
前端的下拉列表框字段字典table加条件之后，modal里面的下拉框可以正常将字典内容加载到搜索框里，但是在list.vue的搜索区域的下拉框无法加载字典内容。后端提示：
ERROR o.j.config.sign.interceptor.SignAuthInterceptor:69 - request URI = /jeecg-boot/sys/dict/getDictItems/sys_user%20where%20id%20in%20(select%20user_id%20from%20sys_user_depart%20where%20dep_id%20in%20(select%20id%20from%20sys_depart%20where%20org_code%20regexp%20'%5E
ERROR o.j.config.sign.interceptor.SignAuthInterceptor:70 - Sign 签名校验失败！Header Sign : 20D0659E1E662FF6A028330E3C56D112

经过看后端，显示sql语句从^#{sys_org_code}的“^”后面被截断了，但是数据库里会完整记录整个语句。将#{sys_org_code}换成不带#号的语句，可以正常搜索，初步估计是#号的问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/23203833/203789168-8cd78953-b5fa-48b5-bf80-7ceb143fcdb8.png)
![image](https://user-images.githubusercontent.com/23203833/203789312-13baecd1-ba19-4a40-867d-e70908d3a0c5.png)
![image](https://user-images.githubusercontent.com/23203833/203823525-583efd63-b5c8-4248-a4a3-0263866e3917.png)
![image](https://user-images.githubusercontent.com/23203833/203789573-37be52ac-fc00-43ab-82be-8e844d229549.png)
![image](https://user-images.githubusercontent.com/23203833/203789650-da6e3712-fa3a-450d-8edb-6daac00e2756.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by gxzhou** [comment]
这个问题没有解决哎，目前非但下拉搜索框是这样，下拉框也是这样，一旦加了where user_id='#{sysUserName}'后，就报“Sign 签名校验失败”。前端vue3,  后端3.5.0
