### ISSUE TITLE
报表配置，字段添加字典code不好用

### ISSUE THREAD

**Issue by DotNeter-Hpf** [jeecgboot/jeecg-boot#4307]
##### 问题描述：
report_user 报表配置，给sex字段添加字典code：sex，保存后使用功能测试，性别下拉菜单数据显示正常
表单配置中使用Popup弹框，功能测试时，性别下拉菜单没有数据

##### 截图&代码：
**`报表配置：`**
![image](https://user-images.githubusercontent.com/62707731/203811370-fc4b1887-ae83-410e-9059-40fc4fd2fe34.png)
**`报表配置功能测试：`**
![image](https://user-images.githubusercontent.com/62707731/203812061-4336e250-f743-4699-8475-49772a84dd95.png)
**`表单开发：`**
![image](https://user-images.githubusercontent.com/62707731/203812157-f833d6e3-5e85-4a6f-8124-bd32d1394529.png)
**`表单开发功能测试：`**
![image](https://user-images.githubusercontent.com/62707731/203812420-34ce744c-0cb3-4dc6-897e-2608ce96440b.png)

**Comment by zhangdaiscott** [comment]
升级到最新版，印象中处理过
