### ISSUE TITLE
vue3的auth2登录重定向错误

### ISSUE THREAD

**Issue by liuxiaofan** [jeecgboot/jeecg-boot#4309]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
按照这个教程配置钉钉 [钉钉](http://doc.jeecg.com/2315001)，但是显示
![image](https://user-images.githubusercontent.com/8596255/203939219-394a6d41-2679-490a-92a6-9991534a959b.png)
显示重定向错误

##### 截图&代码：
这是登陆时候后台的日志
`2022-11-25 16:35:17.117 [http-nio-7996-exec-2] INFO  org.jeecg.common.util.RestUtil:62 -  RestUtil.getBaseUrl: http://*****/jeecg-boot
2022-11-25 16:35:17.118 [http-nio-7996-exec-2] INFO  o.j.modules.system.controller.ThirdLoginController:345 - oauth2 login url:https://login.dingtalk.com/oauth2/auth?redirect_uri=http%3A%2F%2F*******%2Fjeecg-boot%2Fsys%2FthirdLogin%2Foauth2%2Fdingtalk%2Fcallback&response_type=code&client_id=*********&scope=openid&state=http://*******&prompt=consent`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by MaidongAndYida** [comment]
一样的问题，你解决了吗

**Comment by liuxiaofan** [comment]
> 一样的问题，你解决了吗

没有

**Comment by MaidongAndYida** [comment]
我解决了，就是钉钉的回调地址多谢了一个路径，就是路径重复了一段，比如我最开始配置的是http://127.0.0.1:8080/dinglogin,但是后来我改为http://127.0.0.1:8080，它就work了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 上午8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] vue3的auth2登录重定向错误 (Issue #4309)





  
一样的问题，你解决了吗
  
没有
