### ISSUE TITLE
jeecg如何多请求地址代理配置

### ISSUE THREAD

**Issue by xiaohzang** [jeecgboot/jeecg-boot#4311]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2版本为了更好的适配jeecgboot，写死了配置，目前只能对接一个后台地址

接口地址在参数
![image](https://user-images.githubusercontent.com/3162115/204418063-49ff883a-f8fb-4f89-b664-7a28f13fb45d.png)


如果你想对接多个后台地址，你大概需要改改几个地方
1、axiso配置
![image](https://user-images.githubusercontent.com/3162115/204417687-4a8c769f-4295-4ab1-8959-eb969b37e7e0.png)

2、vue.config.js
![image](https://user-images.githubusercontent.com/3162115/204418178-96292746-7df5-4714-bff7-1f380dd783c5.png)
