### ISSUE TITLE
 online 单表 导入Excel数据报错

### ISSUE THREAD

**Issue by xxlsasa** [jeecgboot/jeecg-boot#4312]
##### 截图&代码：

![SN`TJHA~_L@ZU@S(SVC%17F](https://user-images.githubusercontent.com/23720414/204076964-fce8072a-a48f-468c-9948-2c1fbb147e0c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xxlsasa** [comment]
![1669446909798](https://user-images.githubusercontent.com/23720414/204077084-3ce7297d-aa0e-41bf-b22a-6a1236cdb7da.jpg)
![1669446909807](https://user-images.githubusercontent.com/23720414/204077096-9194bc95-699e-4836-9b7c-edad41e5e938.jpg)

**Comment by zhangdaiscott** [comment]
支持导入不好使？其他的功能好使吗

**Comment by zhangdaiscott** [comment]
为什么两个项目名？
![image](https://user-images.githubusercontent.com/3162115/204078841-44b71b03-5e7c-4996-837e-913f6cc7f20b.png)

**Comment by xxlsasa** [comment]
刚接触，不清楚前端是哪个vue 文件请求。其他功能都好使。
