### ISSUE TITLE
APP端/小程序端和管理端使用不同用户体系的问题

### ISSUE THREAD

**Issue by Chris-Arith** [jeecgboot/jeecg-boot#4313]
##### 版本号：
3.4.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前使用功能 jeecgboot 做的是管理端做一些配置相关的工作(微服务版), 现在希望开通 APP 端或者小程序端作为用户来使用这些配置, 想要使用不同的用户账号, 请问怎么实现比较合理?
想要新起一个微服务来写 APP 或小程序的逻辑, 由于使用不同的用户表, 登录注册是不是要重新写? 通过 Feign 调用管理端服务时是不是会存在 token 问题

##### 截图&代码：
无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个没现成的思路，得你自己梳理，改造工作量不小
