### ISSUE TITLE
JVxeTable  下拉框组件 如何绑定数据源？目前只能写死在option后才能显示下拉选项

### ISSUE THREAD

**Issue by eric609** [jeecgboot/jeecg-boot#4316]
版本号：3.0

前端版本：vue2

问题描述：

截图&代码：
使用JVxeTable组件，其中下拉框组件，该下拉框数据需要从后台加载，从后台正确的加载数据后，无法下拉数据？
如图1、图2、图3
![1](https://user-images.githubusercontent.com/24542004/204180227-18d9dd19-fae1-485d-bf38-f7556e026c83.png)
![2](https://user-images.githubusercontent.com/24542004/204180248-de8549fa-7007-49b3-83db-ec15d15ee1af.png)
![3](https://user-images.githubusercontent.com/24542004/204180274-2c3459e6-ca97-45f5-b316-8937bd204e8d.png)
只能写成图4这样，才能显示数据

![4](https://user-images.githubusercontent.com/24542004/204180414-cfad9634-ca25-4c15-b14d-59913806eb2b.png)

请问下拉框如何做数据绑定？

**Comment by zhangdaiscott** [comment]
系统字典用法
![image](https://user-images.githubusercontent.com/3162115/204415997-c95171f5-e30c-446c-863c-482e7d3963a9.png)
表字典用法
![image](https://user-images.githubusercontent.com/3162115/204416140-91231638-b28b-455c-8362-a9f26dbafa79.png)

**Comment by eric609** [comment]
> 系统字典用法 ![image](https://user-images.githubusercontent.com/3162115/204415997-c95171f5-e30c-446c-863c-482e7d3963a9.png) 表字典用法 ![image](https://user-images.githubusercontent.com/3162115/204416140-91231638-b28b-455c-8362-a9f26dbafa79.png)

你好  我使用了表字典的用法了，下拉框的确是可以使用可是，回显一直无法回显，但是如果写死在在options后面就能正常回显，请看下
![1](https://user-images.githubusercontent.com/24542004/204417457-a5504047-97cb-49d7-87ba-6b33a86e6020.png)
![2](https://user-images.githubusercontent.com/24542004/204417484-d64c6e4f-89f2-455f-a377-90bc5d01aecf.png)
![3](https://user-images.githubusercontent.com/24542004/204417611-cf32d12b-d6ce-406d-bc7a-40743210a6bf.png)
![4](https://user-images.githubusercontent.com/24542004/204417625-6a3981f5-7a16-4051-b480-145c95fb4f3a.png)
