### ISSUE TITLE
在线开发页面如何取消详情功能

### ISSUE THREAD

**Issue by HuSangHai** [jeecgboot/jeecg-boot#4319]
##### 问题描述：
在线开发-编辑-表单显示-所有字段取消勾选，页面点击详情就报错
最好有地方可以取消详情按钮

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51265406/204214575-b6168618-63b6-47bc-914c-7749d937b745.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么业务会一个字段都不要？

**Comment by HuSangHai** [comment]
单纯不想要详情按钮

**Comment by zhangdaiscott** [comment]
online可以设置按钮权限
