### ISSUE TITLE
Online在线功能使用主副表时副表无法操作

### ISSUE THREAD

**Issue by dulio** [jeecgboot/jeecg-boot#4320]
后端版本号：3.4.3
前端版本：vue3版

问题描述：
在使用Online在线功能时，使用了主、副表
![image](https://user-images.githubusercontent.com/1264524/204221980-13d42aea-6c75-48d6-b18d-5301544dc09c.png)
![image](https://user-images.githubusercontent.com/1264524/204222256-fe16f408-54b3-4b60-aa64-180a87a8d192.png)

问题：主表使用没有问题，副表表单无法操作。
![image](https://user-images.githubusercontent.com/1264524/204222331-8ff2df26-a4d0-4592-9ad2-c44806227bc3.png)

**Comment by zhangdaiscott** [comment]
输入不了数据还是什么意思？

**Comment by dulio** [comment]
> 
对的，新增没有表单。选择一条编辑后，也没有表单内容
![image](https://user-images.githubusercontent.com/1264524/204233214-937429d5-be95-4428-9481-4735a2bfa420.png)

**Comment by zhangdaiscott** [comment]
前端vue3 是哪个版本

**Comment by dulio** [comment]
> 前端vue3 是哪个版本

https://github.com/jeecgboot/jeecgboot-vue3上的tag v3.4.3last

**Comment by zhangdaiscott** [comment]
你可以把所有的依赖删掉，重现install，再看看
或者更新到master最新，
我们没发现这个问题

**Comment by dulio** [comment]
该问题已经确认，是角色权限没有配置对，没有给用户添加“online表单配置权限”
