### ISSUE TITLE
正在加载 JeecgBoot 低代码平台,请耐心等待 一直加载

### ISSUE THREAD

**Issue by TBX1314521** [jeecgboot/jeecg-boot#4321]
##### 截图&代码：
![4a4c8aa16206ebefd3c299554dca6b0](https://user-images.githubusercontent.com/55613008/204471082-72a77bf5-2076-4b42-a2b2-e7cef2a9a6a6.jpg)

![image](https://user-images.githubusercontent.com/55613008/204471119-d34e3989-1083-4265-98e1-2b6b0e2bc231.png)
项目也跑起来啦  就是在浏览器进入的时候 进不去  但是在别人的电脑上能跑起来进去  遇到了几天了 感谢技术大佬帮忙解决一下 谢谢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
js没报错？

**Comment by TBX1314521** [comment]
谷歌和 window自带的浏览器都尝试了 都是最新的浏览器  
![image](https://user-images.githubusercontent.com/55613008/204472551-e9e51b45-4bcc-4eaa-a780-3bb5e1abe12e.png)
请求的都是 本地的js  然后 好像一个请求都没有发送过去  
![image](https://user-images.githubusercontent.com/55613008/204472846-26fb101f-d3df-4a0b-85a9-4bba4913601f.png)
刚出现这个问题的时候我以为是我电脑的网络问题   然后也尝试了 不是网络问题   node 版本我也切换过 去尝试

**Comment by TBX1314521** [comment]
公司电脑和 个人都出现这样的问题,在别人电脑是正常运行访问，我代码拉取是最新的能跑的代码,是电脑自身的问题吗

**Comment by TBX1314521** [comment]
刚刚又跑起来了,然后重新运行项目进来  又跑不起来 进去不了网页

**Comment by zhangdaiscott** [comment]
大概率是依赖安装的问题
