### ISSUE TITLE
Online代码生成的代码表单验证问题

### ISSUE THREAD

**Issue by pangole** [jeecgboot/jeecg-boot#4322]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
1.使用Online代码生成的表单，把生成的代码拷贝到项目中，配置菜单运行后，所有的字段都是必填校验，在Online配置中是只配置了几个字段是必填校验的
2.在Online表单开发中，使用功能测试地址进入表单，则是正常
3.页面风格是Jvxe

##### 截图&代码：
1.拷贝代码运行
![图片](https://user-images.githubusercontent.com/22371548/204499878-cd8ee4f3-3625-4f99-8a67-94258112bd35.png)
2.使用功能测试地址运行
![图片](https://user-images.githubusercontent.com/22371548/204500045-39d695f4-4493-447e-84d3-def9910552ec.png)
3.配置
![图片](https://user-images.githubusercontent.com/22371548/204500281-7abe89d9-a561-44c4-be3a-566066c1b2e6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by 1298191366** [comment]
vue3和vue3native模板均未复现，进行多个验证均未复现，你去官网试试是否可以
online配置1：
![image](https://user-images.githubusercontent.com/30997828/205440183-34bb807d-683b-4528-bd85-ebd02fbd7880.png)

代码页面1：
![image](https://user-images.githubusercontent.com/30997828/205440029-647c1615-c34d-46e9-8f73-a382ebac6405.png)

**Comment by pangole** [comment]
是数据库属性没有设置成允许为空的问题，但是直接使用online在线的地址是可以的，生成代码后放到项目里再运行就有问题。

**Comment by zhangdaiscott** [comment]
哪就是没问题，代码生成器会根据数据库是否为空 生成必填校验
