### ISSUE TITLE
JVxeTable 中columns的type为select时使用表字典方式无法正确回显的问题

### ISSUE THREAD

**Issue by eric609** [jeecgboot/jeecg-boot#4323]
版本号：3.0

前端版本：vue2

问题描述：
JVxeTable中columns某列为下拉框时使用了dictCode表字典方式显示下拉框，但是回显却无法回显，请见下图

截图&代码：

![1](https://user-images.githubusercontent.com/24542004/204695010-75c17795-23bb-4eaf-b21a-0ea158eb3fb0.png)
![2](https://user-images.githubusercontent.com/24542004/204695023-6ab533a1-788c-42ce-b723-eb6ad9478bd1.png)
![3](https://user-images.githubusercontent.com/24542004/204695034-42145aa8-7843-44e7-a7cf-73f153be47b8.png)

请问如何解决这个问题？已经试过，如果直接使用字典方式却可以正确回显，但是很多业务场景需要的数据不好作为字典数据

**Comment by sjlei** [comment]
经测试没有发现回显问题

![image](https://user-images.githubusercontent.com/34293221/205648473-5acedcac-7b56-4830-847b-593896ba4c3a.png)
![image](https://user-images.githubusercontent.com/34293221/205648603-160bc1fb-8a8e-4385-b5b6-12db188085c7.png)

**Comment by HWGALLEN** [comment]
我也遇到了同样的问题，jvxetable当列为select时，如果我记录的是id，显示的是文字，会经常出现不显示文字，显示成id的情况，如图：
![8DA0DF08-0402-4C63-BCF4-51ACC63BAB47](https://user-images.githubusercontent.com/23203833/208299685-6def8ed4-929b-459b-8c7a-9502906cca0c.jpeg)
![DB7C8CC7-483E-4490-8764-7F324999874E](https://user-images.githubusercontent.com/23203833/208299706-951f05ba-f576-46df-8343-1bc64ff188b4.jpeg)

**Comment by xiaohuang-123** [comment]
问题解决了吗，我的给options赋值，页面不显示

**Comment by eric609** [comment]
> 问题解决了吗，我的给options赋值，页面不显示

没解决，目前官方没有给出答案

**Comment by eric609** [comment]
> 经测试没有发现回显问题
> 
> ![image](https://user-images.githubusercontent.com/34293221/205648473-5acedcac-7b56-4830-847b-593896ba4c3a.png) ![image](https://user-images.githubusercontent.com/34293221/205648603-160bc1fb-8a8e-4385-b5b6-12db188085c7.png)

你好，目前多人都遇到这个问题，应该是存在的

**Comment by xiaohuang-123** [comment]
请问dicctCode后面多个字段用逗号隔开什么意思呢

**Comment by HWGALLEN** [comment]
一个临时的解决方法，可以参照开发文档里面关于jvxe-table当type为select时二级联动的方法，如果没有二级联动的需求，可以只设置一级，不设置linkageKey，初步测试可以成功回显。
