### ISSUE TITLE
菜单配置的问题求助

### ISSUE THREAD

**Issue by KongZongz** [jeecgboot/jeecg-boot#4324]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
?

**Comment by KongZongz** [comment]
![image](https://user-images.githubusercontent.com/97158728/204704988-e8aed9e8-076c-4a89-90b2-b1ade8272282.png)
即我希望能够在前端组件的位置上填写src下的开发的vue组件，然后通过外部打开的方式，可以吗？目前好像是外部菜单需要组件以http:开头才能外部打开

**Comment by zhangdaiscott** [comment]
外部打开只支持http开头，不支持你这个需求
