### ISSUE TITLE
找不到postgresql相关脚本

### ISSUE THREAD

**Issue by ordinary-JAVA** [jeecgboot/jeecg-boot#4325]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
jeecg-boot项目db/其他数据库 目录中 能否提供下postgresql的相关脚本

##### 截图&代码：

![image](https://user-images.githubusercontent.com/56779025/204698708-b0a7b68e-faa9-4fbf-81bb-f488e27f588c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/3065594
