### ISSUE TITLE
jeecg-boot-module-online获取mac地址报错

### ISSUE THREAD

**Issue by clhforne** [jeecgboot/jeecg-boot#4331]
##### 版本号：
2.4.0

##### 前端版本：vue3版？还是 vue2版？
未涉及到前端，仅是后端jeecg-cloud-system-start包的启动报错

##### 问题描述：
jeecg-cloud-system-start 的jar包，在部分环境启动成功，部分环境启动失败。经排查，是jeecg-boot-module-online的问题。

##### 截图&代码：
**异常报错情况如下：**
<img width="928" alt="1669796403159" src="https://user-images.githubusercontent.com/68947113/204745254-5fd6e7b7-c7f2-4c98-8409-571ed54ed823.png">
<img width="1056" alt="1669796466356" src="https://user-images.githubusercontent.com/68947113/204745365-608a6aca-47e6-42b5-b006-60a0f5a8b040.png">

**具体代码如下：**
![1669797118786](https://user-images.githubusercontent.com/68947113/204746374-355cecaa-fe28-4109-b16d-39ff0906af48.jpg)

网络中包含下图的网络设备，根据代码逻辑，修复本issue后126行也可能会报错。
![image](https://user-images.githubusercontent.com/68947113/204750164-02de9b1e-fe4e-424a-9052-f1d1425d7098.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
我们没有这个类，这不是我们的代码，请自己排查
