### ISSUE TITLE
多租户如何调用xxljob任务

### ISSUE THREAD

**Issue by flycatony** [jeecgboot/jeecg-boot#4335]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在多租户环境下，通过后台任务执行微服务时，无法按租户执行。
试着通过参数传递租户信息“{tenantId:1}”，但在任务中如何处理呢？

##### 截图&代码：
package org.jeecg.modules.capp.xxljob;

import com.alibaba.fastjson.JSON;
import com.xxl.job.core.biz.model.ReturnT;
import com.xxl.job.core.handler.annotation.XxlJob;
import lombok.extern.slf4j.Slf4j;
import org.jeecg.common.config.mqtoken.UserTokenContext;
import org.jeecg.common.constant.CommonConstant;
import org.jeecg.common.system.util.JwtUtil;
import org.jeecg.common.util.RedisUtil;
import org.jeecg.common.util.SpringContextUtils;
import org.jeecg.modules.capp.bom.model.CappBomTreeModel;
import org.jeecg.modules.capp.bom.service.ICappBomService;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.List;

@Component
@Slf4j
public class CappJobHandler {
    @Resource
    private ICappBomService cappBomService;
    @XxlJob(value = "cappJob")
    public ReturnT<String> cappJobHandler(String params) {
        //获取租户ID信息。
        String tenantId=JSON.parseObject(params).get("tenantId").toString();
        // log.info(tenantId);
        //1.生成临时令牌Token到线程中
        UserTokenContext.setToken(getTemporaryToken(tenantId));
        try {
            log.info("我是定时任务,同步资源开始...............................");
            List<CappBomTreeModel> list = cappBomService.rollingLowCode(null);
            log.info("我是定时任务,同步资源成功...............................");
        } catch (Exception e) {
            log.info("程序出错了！");
            log.info(e.getMessage(),e);
            return ReturnT.FAIL;
        }
        //2.使用完，删除临时令牌Token
        UserTokenContext.remove();
        return ReturnT.SUCCESS;
    }

   public void init() {
       log.info("init");
   }

   public void destroy() {
       log.info("destory");
   }

   /**
    * 获取临时令牌
    *
    * 模拟登陆接口，获取模拟 Token
    * @return
    */
   public static String getTemporaryToken(String tenantId) {
       RedisUtil redisUtil = SpringContextUtils.getBean(RedisUtil.class);
       // 模拟登录生成Token
       String token = JwtUtil.sign("??", "??");
       // 设置Token缓存有效时间为 5 分钟
       redisUtil.set(CommonConstant.PREFIX_USER_TOKEN + token, token);
       redisUtil.expire(CommonConstant.PREFIX_USER_TOKEN + token, 5 * 60 * 1000);
       redisUtil.set(CommonConstant.TENANT_ID + tenantId,tenantId);
       redisUtil.expire(CommonConstant.TENANT_ID + tenantId , 5 * 60 * 1000);
       return token;
   }
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台作业是无法通过请求获取参数，你应该根据你的业务数据中的租户ID来进行业务区分处理
