### ISSUE TITLE
jeecgboot 3.4.3定时任务的微服务之间调用失败

### ISSUE THREAD

**Issue by hjgCka** [jeecgboot/jeecg-boot#4338]
##### 问题描述：
配置了一个定时任务，该定时任务使用了feign客户端，调用其它微服务模块。
报Token失效，请重新登录。

##### 截图&代码：

<img width="966" alt="1669865990992" src="https://user-images.githubusercontent.com/18320869/204962227-89639d25-8bf5-4682-af1c-630b4c5087d0.png">

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2725212
