### ISSUE TITLE
在功能测试时设置的系统编码规则有效，可以显示出来，但是生成代码后，系统编码规则不显示，请问是哪里有问题呢？

### ISSUE THREAD

**Issue by wangfei0928** [jeecgboot/jeecg-boot#4339]
##### 问题描述：
在功能测试时设置的系统编码规则有效，可以显示出来，但是生成代码后，系统编码规则不显示，请问是哪里有问题呢？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/87455709/204971009-20f1cd61-7816-4bda-853e-a88054adfa3c.png)
![image](https://user-images.githubusercontent.com/87455709/204971240-242a26f5-5e48-48d4-abc0-1ebf79c4f94f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
生成后不支持，得手工集成
http://doc.jeecg.com/2044051
