### ISSUE TITLE
nacos 配置中心的敏感信息，譬如数据库用户密码怎么加密？

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#4340]
##### 前端版本：vue3版？还是 vue2版？

vue2版本
##### 问题描述：

nacos 配置中心的敏感信息，譬如数据库用户密码怎么加密？
nacos是1.4.1版本的
##### 截图&代码：

![用户名和密码怎么加密？](https://user-images.githubusercontent.com/8438712/204986919-dd385d37-ec0b-4701-8cea-5629f3025cb8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前nacos没做账号密码逻辑，你正式发布的时候，把nacos弄成内网即可

**Comment by ming820214** [comment]
> 目前nacos没做账号密码逻辑，你正式发布的时候，把nacos弄成内网即可

nacos如何弄成内网呢？

**Comment by zhangdaiscott** [comment]
就是部署的时候，外网端口和访问权限不开通。只把jeecgboot后台接口对外即可
