### ISSUE TITLE
autopoi导出带副标题的数据表，副标题缺左边框

### ISSUE THREAD

**Issue by Doris0310** [jeecgboot/jeecg-boot#4342]
##### 问题描述：
导出数据表，若没有副标题，边框正常，如果加上副标题，副标题的左边框缺失

##### 截图&代码：

![1669882076205](https://user-images.githubusercontent.com/79900251/204999016-6c2ddb5b-3fc6-4dd5-ba46-c122a06b41ec.png)
![1669882224941](https://user-images.githubusercontent.com/79900251/204999522-5cab48b4-fb33-4c09-8237-3482a41a47e6.png)
![1669882352613](https://user-images.githubusercontent.com/79900251/204999949-3361d09f-462d-42f8-bc51-a520ebb9f7a5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
你先升级1.4.4看看

**Comment by lsqGitHub716** [comment]
测试带副标题的正常
![image](https://user-images.githubusercontent.com/65587928/205546898-ca8cd7c8-9856-458e-9628-f59008c7f0d3.png)

**Comment by Doris0310** [comment]
> 测试带副标题的正常 ![image](https://user-images.githubusercontent.com/65587928/205546898-ca8cd7c8-9856-458e-9628-f59008c7f0d3.png)

你这个没有边框，主要是副标题的左边框没有，加上边框， 通过打印预览看会比较清楚

**Comment by lsqGitHub716** [comment]
已修改
