### ISSUE TITLE
配置了校验字段绑定其他表字段,绑定那个表删除字段,本表显示出来一个id,并没有同步删除

### ISSUE THREAD

**Issue by 18376596459** [jeecgboot/jeecg-boot#4344]
##### 截图&代码：
![QQ图片20221202120056](https://user-images.githubusercontent.com/110648221/205212126-94798ea9-0c38-41b0-ae25-b52ff973b9cf.png)

**Comment by zhangdaiscott** [comment]
这个肯定不关联删除，你业务主数据删掉了，这块强删也不对

**Comment by 18376596459** [comment]
> 这个肯定不关联删除，你业务主数据删掉了，这块强删也不对

他既然不能关联删除,那他主表残留的id怎么办

> ##### 版本号：3.4.3-GA
> ##### 前端版本： vue2版
> ##### 问题描述：配置了校验字段绑定其他表字段,绑定那个表删除字段,本表显示出来一个id,并没有同步删除
> ##### 截图&代码：
> ![QQ图片20221202120056](https://user-images.githubusercontent.com/110648221/205212126-94798ea9-0c38-41b0-ae25-b52ff973b9cf.png)

**Comment by zhangdaiscott** [comment]
自己手工删
如果觉得的确需要关联删除，你可以通过sql增强和java增强来扩展
