### ISSUE TITLE
【建议】多租户授权设计建议

### ISSUE THREAD

**Issue by yimogithub** [jeecgboot/jeecg-boot#4347]
##### 问题描述：目前官方授权模式，基本上是直接将权限相关代码进行复制，导致复制的权限停留在当前版本，无法实时更新，例如：今天给A租户授权了 用户管理 菜单权限，但明天突然觉得，不想给这个菜单，那么只能进数据库，或者自己在写一套修改代码（也是遍历各租户的数据修改），体验不够优秀。

【建议】是将原本无租户的菜单表保留不修改，新增一张租户菜单配置表（id，permissionid，tenantid.......），权限最终通过联表表查询获取，如此，总管理员即便修改菜单路径，排序，或者是别的，也无需遍历所有租户的菜单表

当然，除了菜单可以用这个方式以外，其他租户功能设计也可以使用中间表设计达到比较好的体验

**Comment by zhangdaiscott** [comment]
新版已经提供了租户套餐概念
