### ISSUE TITLE
开启多租户时同个浏览器切换账户，使用的还是同一个租户ID

### ISSUE THREAD

**Issue by baboony** [jeecgboot/jeecg-boot#4349]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
例如A和B两个后台账户，A租户ID是1，B的租户ID是2；登录A账户时新增数据，这时候保存到数据库的租户ID是1，切换账户时（退出系统）登录B账户，这时候新增数据入库租户ID还是1。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/82131952/205373405-ab60b539-454f-4aaf-8373-0fb58d41f5e5.png)

我这边使用的解决方法是：
![image](https://user-images.githubusercontent.com/82131952/205373538-587cb6c2-30f6-4dc0-8c1f-312c63f1f072.png)

退出系统是也把" JEECGBOOTADMIN__DEVELOPMENT__3.4.4__COMMON__LOCAL__KEY__ " 删除

localStorage.removeItem("JEECGBOOTADMIN__DEVELOPMENT__3.4.4__COMMON__LOCAL__KEY__");

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by BruceLiu3385** [comment]
这里这样处理应该没有问题
