### ISSUE TITLE
vue2 请求接口一个接口同时请求了两次，两个请求一个带上了参数，另一个请求没有带上参数

### ISSUE THREAD

**Issue by xnhel** [jeecgboot/jeecg-boot#4350]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
哪是谷歌的机制，第一次是尝试链接吧

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/weixin_43275277/article/details/119858417
