### ISSUE TITLE
线程无法释放

### ISSUE THREAD

**Issue by xikp** [jeecgboot/jeecg-boot#4351]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
项目运行后，服务器线程会一直增长，过一两周就会达到上万线程，一直无法释放，必须重启网关后才能释放，请问是哪里配置没设置好吗

##### 截图&代码：

<img width="794" alt="image" src="https://user-images.githubusercontent.com/99701908/205416730-a4d13f46-f63d-4546-b3fb-2d817b08d30f.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个不清楚，自己跟踪日志吧，一般不是程序问题，别是被黑了
