### ISSUE TITLE
Token失效，请重新登录!

### ISSUE THREAD

**Issue by littlecheng** [jeecgboot/jeecg-boot#4352]
##### 版本号：

3.1.0
##### 前端版本：vue3版？还是 vue2版？
前端是小程序

##### 问题描述：

在本地机器，小程序访问本地后台，正常可以获得token;
把后端代码上传到服务器，通过nginx 转发 https请求到后端http接口，报401，Token失效，请重新登录！
##### 截图&代码：
日志显示
![图片](https://user-images.githubusercontent.com/19911428/205445530-967bfed8-1877-40d8-b203-c0d4be957987.png)

postman调用显示
![图片](https://user-images.githubusercontent.com/19911428/205445670-9e1eb9a4-98bf-454c-a334-fcc5baa40bfa.png)

这是我的nginx 针对server 的配置。

**server {
        listen       80;
        server_name  cpu.ifeixiang.world;
        rewrite ^(.*) https://$server_name$1 permanent;
        include /etc/nginx/default.d/*.conf;
        error_page 404 /404.html;
        location = /404.html {
        }
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
    }
    server {
	     listen 443 ssl;
         server_name  cpu.ifeixiang.world;
         ssl_certificate /etc/nginx/cert/8919572_cpu.ifeixiang.world.pem;
         ssl_certificate_key /etc/nginx/cert/8919572_cpu.ifeixiang.world.key;
         ssl_session_cache shared:SSL:1m;
         ssl_session_timeout  10m;
         ssl_ciphers HIGH:!aNULL:!MD5;
         ssl_prefer_server_ciphers on;
         location /nx-plan-web/ {
		proxy_pass  http://47.122.0.119:18080;	
        }
    }**

请给予帮助，谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
部署问题，我们没办法帮你分析
