### ISSUE TITLE
系统是否提供接口间的登陆认证

### ISSUE THREAD

**Issue by huang905429452** [jeecgboot/jeecg-boot#4353]
##### 问题描述：
系统是否提供接口的登陆认证，假设A系统想访问JEECG系统的某一个接口，需要认证才可访问，那么首先应该通过JEECG的接口获取token，然后再带着TOKEN来访问接口。现在系统只提供了带验证码的登陆，那么就需要先获取验证码，然后解析在获取TOKEN。是否有额外的登陆接口是可以直接通过用户名和密码来获取token的呢？不需要免登陆取消Token验证机制，而是保持TOKEN验证机制来访问JEECG暴露的接口。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36957339/205446224-6daa6847-cb37-43f8-8a42-df6291f53f5e.png)
![image](https://user-images.githubusercontent.com/36957339/205446250-c2f35905-9f9c-420b-addd-cb9e8e8c93f6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
src\views\sys\login\TokenLoginPage.vue

可以实现带token直接免登录
