### ISSUE TITLE
本地部署问题--登录页面没有验证码

### ISSUE THREAD

**Issue by zhaohuating** [jeecgboot/jeecg-boot#4354]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhaohuating** [comment]
> ##### 版本号：
> 3.4.4
> 
> ##### 前端版本：vue3版？还是 vue2版？
> vue3版
> 
> ##### 问题描述：vue3版本地部署，后台使用docker部署单体版，访问登录页后无验证码图片
> ##### 截图&代码：
> 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/13688825/205451168-c8d95c8c-136c-4f0a-a516-bb3dbb900768.png">
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/13688825/205451190-f20930b5-7bcb-4c10-952e-ace195cfe84f.png">

> 
> 
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
niginx映射需要配置成ip

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/205562318-140d9ffa-844e-4877-8ad8-da98d51702b9.png)
