### ISSUE TITLE
JVxeTable 如何动态计算单元格值

### ISSUE THREAD

**Issue by jevonsii** [jeecgboot/jeecg-boot#4356]
##### 版本号：
最新版

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用JVxeTable 输入数据后，如何将计算结果给其他column赋值
如，A列数量：3个、B列单价：5元，C列总价：（如何赋值15元）
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by jevonsii** [comment]
有大神帮忙解答一下吗？

**Comment by sjlei** [comment]
你可以监听`valueChange`事件，在这个事件里面计算完之后用`setValues`方法赋值。

文档地址：http://vue3.jeecg.com/2561638
![image](https://user-images.githubusercontent.com/34293221/205614659-4f3c06d6-ecb5-4b6b-92a7-c6e31326e5af.png)

**Comment by jevonsii** [comment]
你好，请教一下，const { methods } = useMethods(props, context, data, refs, activeKey);
这几个参数应该怎么传？demo里面没有样例。请指教。

**Comment by jevonsii** [comment]
// 单元格编辑完成之后触发的事件
    function handleEditClosed(event) {
      let {$table, row} = event;
      const cost = computed(() => row.quantity * row.priceWan).value;
      $table.methods.setValues([{rowKey: row.id, values: {'sumWan': cost}}]);
    }


这样会报错。请指教。

**Comment by jevonsii** [comment]
> 你可以监听`valueChange`事件，在这个事件里面计算完之后用`setValues`方法赋值。
> 
> 文档地址：http://vue3.jeecg.com/2561638 ![image](https://user-images.githubusercontent.com/34293221/205614659-4f3c06d6-ecb5-4b6b-92a7-c6e31326e5af.png)


// 单元格编辑完成之后触发的事件
function handleEditClosed(event) {
let {$table, row} = event;
const cost = computed(() => row.quantity * row.priceWan).value;
$table.methods.setValues([{rowKey: row.id, values: {'sumWan': cost}}]);
}

这样会报错。请指教。

**Comment by sjlei** [comment]
> // 单元格编辑完成之后触发的事件 function handleEditClosed(event) { let {$table, row} = event; const cost = computed(() => row.quantity * row.priceWan).value; $table.methods.setValues([{rowKey: row.id, values: {'sumWan': cost}}]); }
> 
> 这样会报错。请指教。


调用 setValues 方法，要通过 ref 调。

![image](https://user-images.githubusercontent.com/34293221/206949841-a8a0dd6f-bdb6-4a1d-a93f-0861212d1505.png)
![image](https://user-images.githubusercontent.com/34293221/206949476-f79a6b1f-363a-4c30-a4e1-bf3cc48c7ff0.png)

**Comment by jevonsii** [comment]
> > // 单元格编辑完成之后触发的事件 function handleEditClosed(event) { let {$table, row} = event; const cost = computed(() => row.quantity * row.priceWan).value; $table.methods.setValues([{rowKey: row.id, values: {'sumWan': cost}}]); }
> > 这样会报错。请指教。
> 
> 调用 setValues 方法，要通过 ref 调。
> 
> ![image](https://user-images.githubusercontent.com/34293221/206949841-a8a0dd6f-bdb6-4a1d-a93f-0861212d1505.png) ![image](https://user-images.githubusercontent.com/34293221/206949476-f79a6b1f-363a-4c30-a4e1-bf3cc48c7ff0.png)

谢谢大神~！
