### ISSUE TITLE
springCache中的清除缓存的操作使用了“keys”。

### ISSUE THREAD

**Issue by yekaka** [jeecgboot/jeecg-boot#4358]
##### 问题描述：
清除缓存的时候使用了redis的keys命令，不怕出问题吗？（虽然spring官方也是这样干的）

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33684170/205478892-e7aac967-5bda-4256-a85b-aec2cdb36eb6.png)

Set keys = redisTemplate.keys(CacheConstant.SYS_DICT_CACHE + "*");
		Set keys7 = redisTemplate.keys(CacheConstant.SYS_ENABLE_DICT_CACHE + "*");
		Set keys2 = redisTemplate.keys(CacheConstant.SYS_DICT_TABLE_CACHE + "*");
		Set keys21 = redisTemplate.keys(CacheConstant.SYS_DICT_TABLE_BY_KEYS_CACHE + "*");
		Set keys3 = redisTemplate.keys(CacheConstant.SYS_DEPARTS_CACHE + "*");
		Set keys4 = redisTemplate.keys(CacheConstant.SYS_DEPART_IDS_CACHE + "*");

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
已修改
