### ISSUE TITLE
报表中文数字排序问题

### ISSUE THREAD

**Issue by xikp** [jeecgboot/jeecg-boot#4359]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
报表分组之后，默认，正序，倒序，数字的一二三四五排序都有问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/99701908/205484647-d2288643-3487-4675-ad61-0cd85d3bfbd1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
中文无法按照数字排序
