### ISSUE TITLE
希望作者大大提交代码时尽量规范一些

### ISSUE THREAD

**Issue by xiedi-w** [jeecgboot/jeecg-boot#4360]
按照git commit template插件即可，这样有利于我们更新代码时进行bug复现或者更大胆的更新生产环境。谢谢

**Comment by xiedi-w** [comment]
您在最近一次提交中`@RequiresPermissions注解写的有问题`，这个注解是判断接口权限，为什么要把他给去掉了呢？

前端可以在角色配置中让用户看不到此按钮。但是如果我获取token，在postman是不是也能调用这个接口呢。或者我的担心是多余的呢？

**Comment by zhangdaiscott** [comment]
这只是你的理解，需要请自己放开，默认加权限控制，问的人太多，增加我们的支持成本

**Comment by xiedi-w** [comment]
明白 谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月04日 22:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] 希望作者大大提交代码时尽量规范一些 (Issue #4360) |

Closed #4360 as completed.
