### ISSUE TITLE
想添加自定义下来选择控件在在线开发表单的页面属性的控件类型的下拉选项里面，不知怎么添加

### ISSUE THREAD

**Issue by xchao1995** [jeecgboot/jeecg-boot#4361]
##### 版本号：
我使用的是VUE2版本，在在线开发表单时候我想对页面属性里面的控件类型里面新增一个，需要怎么新增到选择这里呢，我在selectDemo里面有新增了一个控件类型，我想把这个控件加入到在线开发表单的页面属性的控件类型的下拉选项里面，请问需要怎么添加呢
##### 问题描述：
想添加自定义下来选择控件在在线开发表单的页面属性的控件类型的下拉选项里面，不知道怎么在下拉选择里面存在

##### 截图&代码：
![$KHB)WJO{KS}WF WI}D69M](https://user-images.githubusercontent.com/29296640/205529133-e53a4387-7546-4ca6-be78-3e8a9d1d18cf.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
