### ISSUE TITLE
怎么在online表单读取online报表里的数据

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4365]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
1.想问下，如何在online表单里生成online报表里的数据，又或者表单怎么关联报表里
因为有一个想法，就是我可以在数据源里配置另一个数据库，然后再表单里可以进行操作
希望能在online表单里能开发。

2.想问下online报表能不能像online表单那个开发，增强js 等等。。

因为我想读取另一个数据源里面的某个表，想在online表单里进行开发
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by LiCain** [comment]
> 不支持其他数据源

就是说重新在online表单进行新建？

**Comment by zhangdaiscott** [comment]
你可以从其他数据源导入表，就是通过代码生成器哪个单独的数据库配置
http://doc.jeecg.com/2043917
