### ISSUE TITLE
新增用户时，密码加密参数顺序问题

### ISSUE THREAD

**Issue by xiaolinVV** [jeecgboot/jeecg-boot#4368]
##### 版本号：

v3.4.3
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

新增用户时，密码加密时，传参为账号 + 密码。 相当于对账号加密了，应该是密码 + 参数 + salt 才对。 
##### 截图&代码：

![image](https://user-images.githubusercontent.com/20742044/205564045-b976a555-fffa-41ef-8540-886ce9cc2108.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
无所谓，是通过三个参数生成的密码就行
