### ISSUE TITLE
online 如何导入其他数据库里面的表

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4369]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 截图&代码：
![0X~CA 7QPR(E998O8KB~ZKL](https://user-images.githubusercontent.com/19221237/205578559-cda4ea29-6692-4db6-b293-1f07ce66542a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043917
