### ISSUE TITLE
3.4.2版本如何配置online相关jeecg参数

### ISSUE THREAD

**Issue by ylggreenleaf** [jeecgboot/jeecg-boot#4371]
##### 版本号：
3.4.2

##### 问题描述：
在3.3版本中，有配置文件可以配置online在线开发相关的数据库及其他配置的配置文件，在路径jeecg-boot-module-system\src\main\resources\jeecg下面的jeecg_database.properties、jeecg_config.properties，请问在3.4.2及以上版本，这两个配置文件在哪？或者在哪里配置。3.4.2 在线生成的代码，包名前缀是com.jeecg，想修改配置，找不到地方修改了。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/119847539/205596652-aff9c01a-fab1-4afb-be17-6e28f7567be2.png)

**Comment by zhangdaiscott** [comment]
一样
jeecg-system-biz
