### ISSUE TITLE
钉钉 免登链接 RestUtil.getBaseUrl() = 127.0.0.1

### ISSUE THREAD

**Issue by EvilMir** [jeecgboot/jeecg-boot#4373]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
RestUtil.getBaseUrl()
在做钉钉工作台里面直接打开网站，但是这个函数永远出来时127.0.0.1，改了前端的
 VUE_APP_API_BASE_URL，也看了编译后的内容，都是我得域名，就这个函数不知道为什么，一直时本地地址，有老哥教下吗？
同时如果我把127.0.0.1改成我得域名，是可以成功登录的
##### 截图&代码：
![image](https://user-images.githubusercontent.com/13412832/205786840-29cdf8c4-6dde-4a62-83fa-29db83e785c6.png)

![AK `4F0)OZI1{K)H8`4P}~L](https://user-images.githubusercontent.com/13412832/205786552-68f5d6c5-fe4c-432d-a8a3-78d89e2c983d.png)
![image](https://user-images.githubusercontent.com/13412832/205786659-1bf74232-4549-42e9-b271-da62e0302f7d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EvilMir** [comment]
> 

那我应该修改什么，是在前端vue项目里改什么配置吗？不太熟悉前端的工作

**Comment by zhangdaiscott** [comment]
部署方案改改，把后端通过一个外网域名映射
前端映射后台的外网域名
