### ISSUE TITLE
Online表单开发

### ISSUE THREAD

**Issue by duangdangding** [jeecgboot/jeecg-boot#4375]
##### 版本号：3.4.3
Jeecg  Boot Version: 3.4.3
Spring Boot Version: 2.6.6 (v2.6.6)

##### 截图&代码：

[https://s1.xptou.com/2022/12/06/638ee83cbd29e.png](url)

```
"tableVo": {
    "tableName": "base_product",
    "ftlDescription": "base_product",
    "primaryKeyPolicy": "null",
    "sequenceCode": "null",
    "entityPackage": "baseinfo",
    "entityName": "BaseProduct",
    "fieldRowNum": "2",
    "searchFieldNum": "-1",
    "fieldRequiredNum": "4"
  },
```
数据库里的 base_product 这张表，我是有些注释的（货品资料），ftlDescription的值应该是”货品资料“，但是他现在是表名，应该是没有写注释才是表名，写了注释要显示注释 货品资料，正确返回应该是下面：
```
"tableVo": {
    "tableName": "base_product",
    "ftlDescription": "货品资料",
    "primaryKeyPolicy": "null",
    "sequenceCode": "null",
    "entityPackage": "baseinfo",
    "entityName": "BaseProduct",
    "fieldRowNum": "2",
    "searchFieldNum": "-1",
    "fieldRequiredNum": "4"
  },
```
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by duangdangding** [comment]
还是说这个功能的代码不是你们的 你们没有办法改吗

**Comment by zhangdaiscott** [comment]
注释生成对我们来讲不重要，能不能生成无所谓，不影响在线功能。
之所以不去强制实现，前面的issue已经说过了，有的数据库把注释作为必须逻辑会导致同步数据失败
