### ISSUE TITLE
使用local方式导入，图片显示不了，没有报错但是数据库没有数据

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#4377]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用local方式导入，图片显示不了，没有报错但是数据库没有数据。测试系统管理-用户管理导入是有图片的，但是自己新建一张表使用代码生成后，导入就没有图片。后台也没有报错。

##### 截图&代码：
本地方式上传
![image](https://user-images.githubusercontent.com/42790595/205900930-587b572d-04d7-482b-bfe5-5b4369e04cc1.png)

新增的模块不显示图片
![image](https://user-images.githubusercontent.com/42790595/205900638-b4501431-d339-4a17-882a-7366bfef0012.png)

系统自带的用户管理就能上传
![image](https://user-images.githubusercontent.com/42790595/205900720-61600dc7-f32e-4a1e-9d93-b4def4731384.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你跟踪下代码，看看导入逻辑有什么区别
