### ISSUE TITLE
online 表单  通过扩展参数限制大文本在列表页面的展示长度 不能用

### ISSUE THREAD

**Issue by yang2009** [jeecgboot/jeecg-boot#4378]
##### 截图&代码：
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/42491511/205902700-0b99a9e1-30c8-4e89-859d-dc9514974b4f.png">
<img width="1547" alt="image" src="https://user-images.githubusercontent.com/42491511/205902900-3179a843-9d91-454e-afc0-a03973e14848.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/42491511/205903155-01fa41f0-aab7-4568-bcec-69e93fd4067c.png">
![Uploading image.png…]()

**Comment by zhangdaiscott** [comment]
这个新版是自适应的，不支持此参数
