### ISSUE TITLE
online表单开发，在线测试

### ISSUE THREAD

**Issue by duangdangding** [jeecgboot/jeecg-boot#4380]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
生成的时候，需要再选一下模板

**Comment by zhangdaiscott** [comment]
?

**Comment by duangdangding** [comment]
单表 点击在线测试得时候 没有选择 测试哪个模板得选项，也不知道在线测试是哪个模板

**Comment by zhangdaiscott** [comment]
截图说明

**Comment by duangdangding** [comment]
[https://www.hualigs.cn/image/639044629a2fd.jpg](url)
https://www.hualigs.cn/image/639044629a2fd.jpg
说错了  点击功能测试  没有选择模板得选项  或者在哪里可以更改测试模板

**Comment by duangdangding** [comment]
我把其他得模板选项都删除了 ， 只保留了自己的自定义模板 ，

**Comment by duangdangding** [comment]
功能测试的时候 我不选择模板 ， 现在也只有一个自定义模板 默认应该也是测试我自己得模板了吧，但是效果测试得效果并不是我自定义模板得东西

**Comment by zhangdaiscott** [comment]
你自定义的模板？

**Comment by zhangdaiscott** [comment]
描述不清
