### ISSUE TITLE
页面上，查询框的宽度，列的宽度，新增表单的文本框的宽度，能在online开发里面配置吗？还是说必须到处导出前端代码，改前端代码？

### ISSUE THREAD

**Issue by BigRoseAndBoss** [jeecgboot/jeecg-boot#4382]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

现在看查询框的宽度，新增表单的文本框的宽度是不能修改的。列的宽度是自适应的。

查询框的宽度，列的宽度，新增表单的文本框的宽度，能在online开发里面配置吗？
还是说必须到处导出前端代码，改前端代码？

因为这样页面看起来丰满一点，突出层次感。有的列需要人工指定他的宽度。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/50453506/206138725-04181e0f-99e7-4463-b13e-ba8c83722594.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前online模式不支持
