### ISSUE TITLE
定时任务丢失问题

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4383]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
创建多个同方法不同参数的定时任务 在执行时出现任务丢失的问题
5秒执行一次的W1只执行了一次，10秒一次的W5正常
请问我应该怎么做 能够使这些同方法不同参数的定时任务正常执行
##### 截图&代码：
![~GQNZP(JVGO(9X{1EXK%O_Y](https://user-images.githubusercontent.com/118323262/206332180-f6eedb49-0222-47b4-9699-84194a6dc786.png)
![83G1_D2AW11W76%FS6U2Y%L](https://user-images.githubusercontent.com/118323262/206332203-e105dbaa-924d-4282-819e-a39fdbc4b422.png)
![T@}C@(GR2V6}6OX}8K1ZM$P](https://user-images.githubusercontent.com/118323262/206332301-aa25c3b6-21c9-4a5a-bf29-6082dffe9516.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
52

**Comment by zhangdaiscott** [comment]
如果能提供重现步骤，我们可以研究下，无步骤无法处理
