### ISSUE TITLE
代码生成器里的：请注意，将要排序的列字段不存在：id 是否可以改成自己需要排序的字段？

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4385]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：

问题1：我在生成代码后，因为我们的数据库用fuserid作为主键ID，而且还有很多表都是用不一样的ID来起名，想问下应该怎么改动才不会大改？还是需要添加什么？请求指教一下，这个需求可能比较独特。谢谢了大神
问题2：可代码生成可以把视图作为表生成？我想应该是不可以。
麻烦了  :)
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/206369149-3f5e8194-4eb3-4016-b5fc-8d0460855294.png)
![image](https://user-images.githubusercontent.com/19221237/206369320-931d7018-3680-422d-ac6d-eb3a6787635f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以自定义排序字段，看看项目里的例子

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2426559
6
