### ISSUE TITLE
m1启动nacos报错

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#4387]
##### 版本号：
最新版

##### 问题描述：

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namingHealthController': Unsatisfied dependency expressed through field 'healthOperatorV2'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthOperatorV2Impl' defined in URL [jar:file:/Users/addzero/.m2/repository/org/jeecgframework/nacos/nacos-naming/2.0.4/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/HealthOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/addzero/.m2/repository/org/jeecgframework/nacos/nacos-naming/2.0.4/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/addzero/.m2/repository/org/jeecgframework/nacos/nacos-naming/2.0.4/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/47/d3dfl_fd6q95yyf6f51p133h0000gn/T/librocksdbjni9008396453434844449.jnilib: dlopen(/private/var/folders/47/d3dfl_fd6q95yyf6f51p133h0000gn/T/librocksdbjni9008396453434844449.jnilib, 0x0001): tried: '/private/var/folders/47/d3dfl_fd6q95yyf6f51p133h0000gn/T/librocksdbjni9008396453434844449.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/47/d3dfl_fd6q95yyf6f51p133h0000gn/T/librocksdbjni9008396453434844449.jnilib' (no such file), '/private/var/folders/47/d3dfl_fd6q95yyf6f51p133h0000gn/T/librocksdbjni9008396453434844449.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

##### 截图&代码：

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/67467679/206450564-dcf9d1cf-1c33-48d8-aabb-8606ce482f1e.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以自己弄个nacos服务，执行我们提供的初始化sql就行

**Comment by zjarlin** [comment]
这是我的命令
#------------------启动nacos容器    ---------------------

containerName='nacos' #指定容器名字
containerDataName='DockerData'
reference="$HOME/$containerDataName/$containerName"
restartStrategy='always'
mkdir -p $reference/conf
docker run -dit --restart=$restartStrategy  \
-p 8848:8848 \
-p 9848:9848 \
-p 9849:9849 \
-v $reference/logs:/home/nacos/logs \
-v $reference/conf/application.yml:/home/nacos/conf/application.yml \
--name $containerName \
-e MODE=standalone \
zhusaidong/nacos-server-m1:2.0.3

把jeecg-boot项目nacos模块的yml挂载了,然后把容器里自带那个application.properties删了
可是容器日志说找不到mysql
然后就想到了你们文档里说host里加这个
127.0.0.1 jeecg-boot-redis
127.0.0.1 jeecg-boot-mysql
127.0.0.1 jeecg-boot-nacos
127.0.0.1 jeecg-boot-gateway
127.0.0.1 jeecg-boot-system
127.0.0.1 jeecg-boot-sentinel
127.0.0.1 jeecg-boot-xxljob
127.0.0.1 jeecg-boot-rabbitmq

我把host也挂载试了下,想了想不对劲,yml变量里定义的好像是容器的,跟宿主机隔离啊,问下大佬配置文件怎么搞才能用,
或者文档里能更新下M1  docker启动jeecg-nacos的教程咩,不胜感激
