### ISSUE TITLE
在线报表里，如何配置弹出第二个报表来？

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4390]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：

在online报表里创建2个报表
进入第一个报表时，点击内容弹出第二报表对应的内容？
报表与报表之间能不能相互动态传值并且弹框，不要配置成路由配置成组件弹框。
请问如何配置，我看了文档和教程也没有找到。希望能帮忙解决一下这个问题。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/206826583-237daec6-df2b-4ac2-b2a4-c62871ae376c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以配置herf http://doc.jeecg.com/2044155

**Comment by LiCain** [comment]
> 你可以配置herf http://doc.jeecg.com/2044155

配置了，但是没有生效很奇怪
![image](https://user-images.githubusercontent.com/19221237/206831638-1feaea14-6199-43c3-9aed-ebfdcfaf179a.png)

![image](https://user-images.githubusercontent.com/19221237/206831652-5f609947-24f7-4d06-b516-ae295839f744.png)
