### ISSUE TITLE
feign远程调用 Permission

### ISSUE THREAD

**Issue by xagpx** [jeecgboot/jeecg-boot#4391]
##### 版本号：
最新版本2.4.6

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
feign 远程调用服务接口，服务接口配置shiro 注解@RequiresPermissions，前端传递授权标识info.addStringPermissions(permissionSet);成功，调用服务接口出现错误，org.apache.shiro.authz.AuthorizationException: Not authorized to invoke

Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.apache.shiro.authz.UnauthenticatedException: This subject is anonymous - it does not have any identifying principals and authorization operations require an identity to check against.  A Subject instance will acquire these identifying principals automatically after a successful login is performed be executing org.apache.shiro.subject.Subject.login(AuthenticationToken) or when 'Remember Me' functionality is enabled by the SecurityManager.  This exception can also occur when a previously logged-in Subject has logged out which makes it anonymous again.  Because an identity is currently not known due to any of these conditions, authorization is denied.] with root cause
单体服务访问正常。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/13012069/206829385-c99b7fae-daf4-4949-a2bd-f0342c08949c.png)

![image](https://user-images.githubusercontent.com/13012069/206829585-af647083-941b-4057-baf1-1437684d0cb3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
授权了吗

**Comment by xagpx** [comment]
info.addStringPermissions(permissionSet);授权成功

**Comment by xagpx** [comment]
> 授权了吗
info.addStringPermissions(permissionSet);授权成功

**Comment by zhangdaiscott** [comment]
不是角色授权吗

**Comment by xagpx** [comment]
> 不是角色授权吗

授权标识@RequiresPermissions

**Comment by zhangdaiscott** [comment]
用法不对

**Comment by xagpx** [comment]
> 用法不对
 feign 与permission 如何配合使用？
