### ISSUE TITLE
online表单自动生成后不会生成href字段

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4392]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
表单自动生成不会生成href字段，即生成的代码没有超链接，但功能测试中又有超链接
想问下前端哪里可以添加呢？找了半天教程一个都没有，实在难以下手，就差一步就能实现，望大神帮帮忙，谢谢
告诉我在哪里添加就可以，感谢
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/206837764-c3454a45-06de-44cc-8f22-e8f60846459d.png)

![image](https://user-images.githubusercontent.com/19221237/206837705-e542d4f5-9a45-4915-b63c-3162310234c0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
在线支持，代码生成不支持

**Comment by LiCain** [comment]
> 在线支持，代码生成不支持

等于白问
