### ISSUE TITLE
jeecg-gateway-router配置无效

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4398]
##### 版本号：
v3.4.4 

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
jeecg-gateway-router.json的predicates新增"_genkey_5": "/piano/**"，但是重启gateway没有加载到,
我在jeecg-dev中配置的route:data-type: nacos,可是gateway提示的是 初始化路由模式，dataType：database

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/206894820-40b4a29e-f593-4180-b32a-4cfe63461468.png)

![image](https://user-images.githubusercontent.com/90361617/206894984-9d85097d-c8d0-431f-8eb3-6b05f5279dce.png)
![image](https://user-images.githubusercontent.com/90361617/206896484-bdb8d144-81e5-413a-b8ad-e273c38a398c.png)
 
![image](https://user-images.githubusercontent.com/90361617/206896528-43c72629-33f6-413a-be8b-133bc35d7dbf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己排查配置是否正确
