### ISSUE TITLE
表单字段配置了helpMessage没生效

### ISSUE THREAD

**Issue by aseaofword** [jeecgboot/jeecg-boot#4399]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

表单字段配置了helpmessage没生效
##### 截图&代码：
![MX9ZMG29Q}MTJ6FL%8WJV(T](https://user-images.githubusercontent.com/73841358/206955525-f206aa55-b610-4ee3-8674-c5c0c0ac43b4.png)

![JI {X%~)N)D4WNSHKE(MD@V](https://user-images.githubusercontent.com/73841358/206955532-b027380a-381d-479a-8f26-ff11c0b76272.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by aseaofword** [comment]
生成的vue3可以了，但是生成的vue3原生不行

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
这个只是给vue3用的JSON结构
![image](https://user-images.githubusercontent.com/30997828/229449999-e7c6a2f4-5fe7-4298-9097-f2c83ac63e80.png)
vue3natve是没有用到这个文件的，他的数据结构如下图所示，需要自行增加
![image](https://user-images.githubusercontent.com/30997828/229450378-c43170b9-d3a6-410b-8de5-ec1e7a2cebe7.png)
