### ISSUE TITLE
docker 启动后端的问题

### ISSUE THREAD

**Issue by wileywu** [jeecgboot/jeecg-boot#4400]
##### 版本号：
Jeecg  Boot Version: 3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
根据文档 http://doc.jeecg.com/2043889 （Docker镜像单体启动项目），里面有一句话 “修改application-dev.yml 的数据库连接和redis连接，将连接改成host方式”， host 方式我理解 127.0.0.1, 那我的mysql 数据库的地址比如 是 192.168.1.116， 不是我本地的。这个时候如果按照上述说法，我127.0.0.1 上没有mysql , 那么我启动肯定失败啊。这个不理解。请解释下。
还有docker-compose.yml 这个文件中哪些值需要修改，还是完全不需要修改？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改成截图的内容
![image](https://user-images.githubusercontent.com/3162115/207205685-9f2594a5-6a21-411c-88fc-15714abf7a27.png)
![image](https://user-images.githubusercontent.com/3162115/207205710-4442da47-da95-4a79-b181-3065c48c4140.png)

**Comment by wileywu** [comment]
我觉得你没有回答我的问题。
