### ISSUE TITLE
App中的各个模块，如何处理权限问题？

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4405]
##### 截图&代码：
![1670830895820](https://user-images.githubusercontent.com/89574140/206989041-32095604-95e1-4d8f-9024-43cabe24658a.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
得单独做，目前没这功能
