### ISSUE TITLE
柱状图x轴文本重叠

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#4406]
##### 版本号：

2.4.6
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
柱状图在x轴数据较多，且文本罗长时，会产生重叠，请问如何解决？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15886620/207035312-11fb9203-2884-4a92-aa67-e89d54ac093c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
[[你得自己设置比例](https://blog.csdn.net/hrbust_cxl/article/details/106872683?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-106872683-blog-103665829.pc_relevant_3mothn_strategy_recovery&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-106872683-blog-103665829.pc_relevant_3mothn_strategy_recovery&utm_relevant_index=2)](https://blog.csdn.net/hrbust_cxl/article/details/106872683)

**Comment by hzl7652** [comment]
jeecgboot 的这个问题要怎么设置
