### ISSUE TITLE
online 表单Href组件内‘该文件不存’

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4409]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

按照文档去填写了正确的路径结果还是无法找到文件
##### 截图&代码：
文档
![image](https://user-images.githubusercontent.com/19221237/207206586-cc93de6a-8854-43a2-a30b-6b9a06170529.png)

我的
![image](https://user-images.githubusercontent.com/19221237/207206630-6e5c3f56-4943-4cbb-8393-2ef9b067ef87.png)
![image](https://user-images.githubusercontent.com/19221237/207206687-171b64d4-2390-49bf-9260-86d3ac28ac9d.png)
![image](https://user-images.githubusercontent.com/19221237/207206720-5befd28f-51ef-4379-a9c1-9b1be2d0eed7.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by LiCain** [comment]
> 在线吗

是的

**Comment by zhangdaiscott** [comment]
开源版本目前还不支持href
