### ISSUE TITLE
table expand列宽如何设置，求大神指导

### ISSUE THREAD

**Issue by jevonsii** [jeecgboot/jeecg-boot#4410]
##### 版本号：
最新版

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
table expand列宽如何设置

##### 截图&代码：
![DJXDIYE@_P8F6 Q{ITL7N6O](https://user-images.githubusercontent.com/115225297/207221591-7239d191-cc22-4cae-a3ad-d872f024e6a3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个看antd底层文档
