### ISSUE TITLE
表单设计 > APP智能设计【没有此菜单】

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4411]
##### 截图&代码：
![1670913381083](https://user-images.githubusercontent.com/89574140/207244304-2a9b9bc4-7989-4a6e-9df5-88d4400a0992.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时未开源
