### ISSUE TITLE
cloud框架下多数据库字段自动翻译问题

### ISSUE THREAD

**Issue by iskaola** [jeecgboot/jeecg-boot#4420]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
我是用的是cloud框架，各个系统分成不同的数据库，字段自动翻译的话只能翻译system库中的内容，其他库翻译不了，翻译的切面是在system的，调用的是system的数据库，有办法翻译其他子系统数据库的数据么？
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以自行改造字典拦截器，默认肯定满足不了你的需求
