### ISSUE TITLE
请问在线表单控件类型为【他表字段】时应该如何配置？

### ISSUE THREAD

**Issue by LyuKhao** [jeecgboot/jeecg-boot#4421]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
请问在线表单控件类型为【他表字段】时应该如何配置？我需要将其他表的一些数据显示在这个表里，且不冗余存储，这个控件看起来可以实现我的需求，但我在开发文档中未找到这个控件的使用说明，测试使用时也碰到了一些问题。
另外控件【关联记录】部分能否也提供一下使用说明，麻烦了

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40912886/208034230-a160de49-9c25-4aa5-9d3e-60c4082c2329.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/3087563#222__79
