### ISSUE TITLE
代码生成器 VUE页面出现将要排序的列字段不存在：id

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4422]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
这个前端在哪里自定义排序，VUE3我知道在哪里，VUE2不知道

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/208042630-777bfb14-c727-4182-91e3-90e291668247.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
混入
