### ISSUE TITLE
spring.config.import引入nacos中配置 问题咨询

### ISSUE THREAD

**Issue by 1127945027** [jeecgboot/jeecg-boot#4423]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：

咨询：
请问，后端中存在logback-spring.xml，是否能放到nacos中进行配置，项目通过spring.config.import引入nacos中配置的logback-spring.xml
谢谢！

同理，项目中yaml中配置，如redis、rabbitmq等等，能否抽离单独的yaml，分别引入；
现在子项目(模块较多)，每个模块都有一个yaml，配置的redis rabbitmq地址均相同，如果地址变更，需要去nacos修改N个子项目的配置文件，可能会修改遗漏；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没有导入logback配置的，spring相关的可以单独引入
