### ISSUE TITLE
autopoi导入excel 如果bean中设置相同的name ，但是属于不同的groupname，导入时，数据为null

### ISSUE THREAD

**Issue by a616707902** [jeecgboot/jeecg-boot#4424]
##### 版本号：
autopoi:1.4.0

##### 问题描述：
autopoi导入excel 如果bean中设置相同的name，但是属于不同的groupname，在数据导入时，前面的数据会无法赋值。
##### 截图&代码：
![1671267779747](https://user-images.githubusercontent.com/13585075/208234688-35c66394-6bf9-4267-a085-96ab50767f76.jpg)
![1671268007804](https://user-images.githubusercontent.com/13585075/208234696-541e1223-0b78-45c6-aa23-4d046b68f635.jpg)
![1671268189478](https://user-images.githubusercontent.com/13585075/208234700-2e5fc5c9-aee4-48e0-aac6-ab1cecc0ab73.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
你是参考哪个地方这样使用的？

**Comment by lsqGitHub716** [comment]
看到回复

**Comment by a719953132** [comment]
请问这个问题解决了吗
