### ISSUE TITLE
网络超时

### ISSUE THREAD

**Issue by flycatony** [jeecgboot/jeecg-boot#4426]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
前端触发后端较长时间的服务时，前端提示“系统提示：网络超时”

##### 截图&代码：

![042b115fc1c190ad41f769895fadca7](https://user-images.githubusercontent.com/61395677/208280516-8a0c2180-9ddb-4b53-a2bc-3ce2983eddfc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果你后台的确很慢，可以改下前端axiso的超时设置

**Comment by flycatony** [comment]
具体从哪也呢？谢谢

**Comment by zhangdaiscott** [comment]
axiso
