### ISSUE TITLE
配置了一级菜单但是左边菜单栏不显示一级菜单

### ISSUE THREAD

**Issue by xnhel** [jeecgboot/jeecg-boot#4427]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/98070616/208378231-311066b9-e597-4ffa-ade0-faa02455892a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/209040500-71450af0-18ea-45d1-9893-a4dec38f82a0.png)

这个配置不 对吧
