### ISSUE TITLE
online在线表单使用popup的问题

### ISSUE THREAD

**Issue by jdbcpp** [jeecgboot/jeecg-boot#4429]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
  online在线表单中使用 popup弹出框控件，无法使用带参数的online报表，这种需求很常见。不要说自己写代码实现，要自己写代码还要online在线表单卵用。
##### 截图&代码：
报表sql 查询未选择过的列表

![image](https://user-images.githubusercontent.com/121014765/208391844-a65d155d-1247-4c21-b56b-868025390270.png)

表单使用popup控件
![image](https://user-images.githubusercontent.com/121014765/208392577-b63a5549-25d3-4067-9215-175020b414f0.png)
![image](https://user-images.githubusercontent.com/121014765/208392991-57a30d2e-876f-41d1-8e9f-2fea7da36056.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://vue3.jeecg.com/2503900

**Comment by jdbcpp** [comment]
说真的，这个回答没什么卵用
