### ISSUE TITLE
java增强功能使用报错

### ISSUE THREAD

**Issue by Xlivel** [jeecgboot/jeecg-boot#4431]
##### 版本号：
jeecg-boot 3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用java增强功能报错.本地调试结果是不知道为什么会多传一个分录的ID，到底层包里只查了主表的数据，没查分录的逻辑。还有就参数的分割符用的是@符号，低层用的是英文,分割的。谁能帮忙解惑下。

##### 截图&代码：
链接: [https://pan.baidu.com/s/1pjHNQaSw28-lj-Y6BSFi3A?pwd=n91h](url)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没理解，你提供的链接，点不开

**Comment by Xlivel** [comment]
我这边不知道为什么上传不了图片，直接吧链接在浏览器上打开就可以了，链接是百度网盘分享的图片。https://pan.baidu.com/s/1pjHNQaSw28-lj-Y6BSFi3A?pwd=n91h

**Comment by zhangdaiscott** [comment]
什么会多传一个分录的ID

这个分录是子表的意思？

**Comment by Xlivel** [comment]
![WX20221222-170248](https://user-images.githubusercontent.com/14935038/209098408-bc113642-47f5-43f0-b5d0-17b86fdbbe26.png)
请求里有带@符号和子表ID，这里查不到信息就会报错。

**Comment by zhangdaiscott** [comment]
明白，我们会尽快处理

**Comment by tygithub1** [comment]
已修改

**Comment by Xlivel** [comment]
好的👌
