### ISSUE TITLE
j-editable-table嵌套子表格

### ISSUE THREAD

**Issue by NameAce** [jeecgboot/jeecg-boot#4432]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
j-editable-table是否可以嵌套子表格，子表格也是j-editable-table

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by NameAce** [comment]
好的，谢谢
