### ISSUE TITLE
Jedittable显示找不到列

### ISSUE THREAD

**Issue by AliceGame** [jeecgboot/jeecg-boot#4434]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/46731971/208602727-fc018582-0be3-4b78-a697-fb1633544357.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by AliceGame** [comment]
我想使用setValue添加一条自定义数据，或者在jedittable中datasource中添加一条默认数据，但是均不显示

**Comment by zhangdaiscott** [comment]
补充版本号

**Comment by zhangdaiscott** [comment]
无回复，关闭
