### ISSUE TITLE
在线报表动态传参

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4435]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线报表动态传参问题 按照官网配置 访问结果错误

##### 截图&代码：
按照官网配置
![H4X46V41MQR64B06$J0NCEC](https://user-images.githubusercontent.com/118323262/208603292-727a11ab-ce13-4f9e-a15b-5d1405b2a23d.png)
![N`1QCDPL((WF HBO(FLX(5B](https://user-images.githubusercontent.com/118323262/208603318-5dfa8e3c-b873-47d8-b9c6-521e1fe8cd2f.png)
![{SOEXC_V%4Q7(~HCZEBMLSM](https://user-images.githubusercontent.com/118323262/208603395-fa6f10a9-0412-4269-ae33-677c138f2239.png)
数据库查询结果 动态参数似乎不起作用
![H8$GAH(G%Z{BEK97`LP`STB](https://user-images.githubusercontent.com/118323262/208603440-24427e9b-2b0d-4ee3-9d70-3dd08ab73d7d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by maxxious** [comment]
似乎缺少了几张截图
![N`1QCDPL((WF HBO(FLX(5B](https://user-images.githubusercontent.com/118323262/208604291-056af34b-5444-4b14-8eb5-6d61d27daebc.png)
![{SOEXC_V%4Q7(~HCZEBMLSM](https://user-images.githubusercontent.com/118323262/208604308-25abc586-6f69-4a15-b25e-3a50eee5de9c.png)

**Comment by zhangdaiscott** [comment]
你最好先升级到最新，我们修复过类似问题，不知道是不是跟你这个一样

**Comment by maxxious** [comment]
> 你最好先升级到最新，我们修复过类似问题，不知道是不是跟你这个一样

请问升级版本是修改版本号就可以升级 还是需要重新下代码

**Comment by zhangdaiscott** [comment]
当然是合并代码
