### ISSUE TITLE
部门组件JSelectDept点击选择回显失败

### ISSUE THREAD

**Issue by rain2119488** [jeecgboot/jeecg-boot#4436]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

部门组件选择了部门后点击确定，再次打开点击取消或者右上角关闭模态框按钮后，再次点开后之前选择了的部门没有打钩

##### 截图&代码：
![1671619631253](https://user-images.githubusercontent.com/121165194/208887482-6c066f3b-c3bf-469c-8a33-29c91e91ab79.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用户维护所属部门不是好使的吗，是你的赋值有问题？
