### ISSUE TITLE
服务器上采用docker部署后端报数据库连接问题

### ISSUE THREAD

**Issue by jacobcyl** [jeecgboot/jeecg-boot#4437]
##### 问题描述：
与 #3579  是同样的问题
按照[《Docker镜像单体启动项目》](http://doc.jeecg.com/2043889) 这个指引配置docker启动，运行docker-compose up 后出现下面的问题，数据库无法成功连接，导致http://localhost:8080/jeecg-boot/doc.html  无法访问：

> jeecg-boot-system  | 2022-12-21 19:48:55.303 [Druid-ConnectionPool-Create-1037955032] ERROR com.alibaba.druid.pool.DruidDataSource:2781 - create connection SQLException, url: jdbc:mysql://127.0.0.1:3306/jeecg-boot?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai, errorCode 0, state 08S01
jeecg-boot-system  | com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
jeecg-boot-system  | 
jeecg-boot-system  | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
jeecg-boot-system  |    at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
jeecg-boot-system  |    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
jeecg-boot-system  |    at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)

##### 截图&代码：

> 使用的是mac pro电脑

1.  hosts文件：

<img width="444" alt="截屏2022-12-21 下午8 01 05" src="https://user-images.githubusercontent.com/906128/208901110-a4ce1884-bd87-430a-a4d2-44440ae3b92f.png">

2. jeecg-boot\jeecg-module-system\jeecg-system-start\src\main\resources\application-dev.yml 配置文件截图：

<img width="1559" alt="截屏2022-12-21 下午8 05 51" src="https://user-images.githubusercontent.com/906128/208901466-97724d3e-fb39-4134-9d05-979629fa8d76.png">
3. 报错日志：
<img width="1649" alt="截屏2022-12-21 下午8 06 46" src="https://user-images.githubusercontent.com/906128/208901651-994ded50-9075-45ef-a16b-e33483e5886b.png">
4. docker状态截图：
<img width="1266" alt="截屏2022-12-21 下午8 08 31" src="https://user-images.githubusercontent.com/906128/208902913-193fd511-8faa-4dea-80b6-0cd3a560a7fc.png">

5. mysql是docker上安装的，版本号是:mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)
在docker环境下mysql是可以通过命令行登录且能看到已经创建了“jeecg-boot”数据库以及相应的表
<img width="745" alt="截屏2022-12-21 下午8 12 55" src="https://user-images.githubusercontent.com/906128/208902626-ef0273c4-1007-4f68-b9d5-76db511130ee.png">

请您帮我看看这个问题是我自己配置的问题还是docker的问题，麻烦您了，跪谢

**Comment by zhangdaiscott** [comment]
看这错误提示，你数据库配置没改
![image](https://user-images.githubusercontent.com/3162115/209034499-909b27ff-e07f-4ec9-8536-484fddf7850a.png)

**Comment by jacobcyl** [comment]
> 看这错误提示，你数据库配置没改 ![image](https://user-images.githubusercontent.com/3162115/209034499-909b27ff-e07f-4ec9-8536-484fddf7850a.png)

![image](https://user-images.githubusercontent.com/906128/209052843-c7a54a99-2357-4d24-803b-8eb4fa5225eb.png)
已经改了的，按照教程修改的。

**Comment by jacobcyl** [comment]
搞定了，配置是没有问题的，只不过我没有运行docker-composer build，先运行这个命令，修改的配置才能生效。谢谢

**Comment by jacobcyl** [comment]
搞定了，配置是没有问题的，只不过我没有运行docker-composer build，先运行这个命令，修改的配置才能生效。谢谢

**Comment by petma** [comment]
作为小白，我也遇到了和你同样的错误
