### ISSUE TITLE
代码生成器使用

### ISSUE THREAD

**Issue by Eason0803** [jeecgboot/jeecg-boot#4438]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
你好 我想问下 代码生成器生成的代码可以直接用于其他项目且数据库与jeecg-boot数据库不一致，可以吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
具体不清楚你要怎么用，你可以配置链接其他库，把表导入到jeecg库里
