### ISSUE TITLE
Zip格式不支持

### ISSUE THREAD

**Issue by LvJianfeng** [jeecgboot/jeecg-boot#4440]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
修复#4197权限问题后，生成代码的zip包解压提示格式不支持，请问下还需要升级哪个呢？

##### 截图&代码：
升级描述：
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9586013/209422171-5c1186d3-e186-4a76-a2df-bd0d9099cdbe.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
？
