### ISSUE TITLE
VUE代码

### ISSUE THREAD

**Issue by Eason0803** [jeecgboot/jeecg-boot#4441]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：

利用表单生成前端VUE代码之后，我看你们官方视频都是放入前端项目ant-design-jeecg-vue项目中，我想问下这个VUE代码能像后台代码一样放入其他业务项目中吗？
##### 截图&代码：

![image](https://user-images.githubusercontent.com/121207992/209493333-9643b808-1a61-4dc7-8344-a6d27ec236f8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不能，因为前后端是分离的，没办法

**Comment by Eason0803** [comment]
跟前后端分离没有关系，比如我利用低代码生成的代码，我将后端代码放入我的业务程序中，加入低代码的依赖是可以运行的，是否可以将前端的VUE代码放入我前端的业务程序中【并非ant-design-jeecg-vue】运行？

**Comment by dishuicanghai** [comment]
为啥全部是各种错误啊！白激动了一场啊。哥们们




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月26日(星期一) 下午2:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] VUE代码 (Issue #4441)





 
不能，因为前后端是分离的，没办法

**Comment by Eason0803** [comment]
这个我知道了 关了就行

**Comment by dishuicanghai** [comment]
具体是怎么造成的啊？可以在下面贴出你的解决方案和错误原因，不要一个解决就完事啦。让其他人遇到同样问题后，直接就能解决了，省的来回问。麻烦了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月28日(星期三) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] VUE代码 (Issue #4441)





 
这个我知道了 关了就行

**Comment by Eason0803** [comment]
这个没有报错 就是想问问前端生成的VUE代码能用于其他前端项目吗
