### ISSUE TITLE
window下vue项目启动一段时间后停止运行too many file open

### ISSUE THREAD

**Issue by litao123123** [jeecgboot/jeecg-boot#4442]
##### 版本号：
3.4.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
vue前端项目运行一段时间后自行停止出现报错

##### 截图&代码：
![1](https://user-images.githubusercontent.com/21337660/209495556-5c41934c-5022-4b19-aeba-aab4c1e16237.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没遇到过，百度有相关的问题，可以自行排查
https://blog.csdn.net/Viogs/article/details/101365125
