### ISSUE TITLE
变更数据库中导入表单数据是不是不能线上测试

### ISSUE THREAD

**Issue by Eason0803** [jeecgboot/jeecg-boot#4443]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版
##### 问题描述：
我想变更online数据库，已经注释掉类：CodeGenerateDbConfig，并调整了jeecg-boot-module-system/jeecg/jeecg_database.properties，然后页面中点击【导入数据库】，显示的是我新库的数据库表列表，但是我导入表单之后，关于表单的在线功能测试时报错：java.sql.SQLSyntaxErrorException: Table 'jeecg-boot.goms_qqqqqq_111' doesn't exist

问题是：从变更数据库中导入表单数据是不是不能线上测试？

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/121207992/209497692-f028450b-6134-4baa-bdf3-dd8c3f2e01e6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
导入后，同步数据库了吗

**Comment by Eason0803** [comment]
没有 那么就是这样的 线上功能测试与后端服务用的是一个数据 如果不同步数据库 是无法进行线上测试的 是吗

**Comment by zhangdaiscott** [comment]
不同步，你库里没生成这个表
