### ISSUE TITLE
代码生成器VUE代码运行问题

### ISSUE THREAD

**Issue by Eason0803** [jeecgboot/jeecg-boot#4444]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
利用低代码生成的代码，我将后端代码放入我的业务程序中，加入低代码的依赖是可以运行的，是否可以将前端的VUE代码放入我前端的业务程序中【并非ant-design-jeecg-vue】运行？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的前端不是我们的jeecgboot的项目，用不了
