### ISSUE TITLE
文档预览使用kkfileview报错

### ISSUE THREAD

**Issue by WangXin0105** [jeecgboot/jeecg-boot#4446]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用开发文档中的kkfileview:v2.2.1版本，docker正常启动，且修改了JUpload组件，文件可以正常上传和下载，但是点击预览提示文件下载异常

##### 截图&代码：
![录屏_选择区域_20221226163943](https://user-images.githubusercontent.com/44919592/209526489-bebbccfd-2781-474c-9c12-f218cead1886.gif)
![image](https://user-images.githubusercontent.com/44919592/209526701-3ecf8603-976c-42ca-b337-926c3194aa97.png)
![image](https://user-images.githubusercontent.com/44919592/209526796-732d4bca-f1fc-4dc3-a148-db54fac2dc58.png)
![image](https://user-images.githubusercontent.com/44919592/209527110-68534b98-261c-4f07-b6a1-509b46b5b9ba.png)
![image](https://user-images.githubusercontent.com/44919592/209528131-94ce30dc-b4bc-40ad-a5fd-9ab773444198.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用云存储
