### ISSUE TITLE
最新版本后端总是连不上redis

### ISSUE THREAD

**Issue by yanglphf** [jeecgboot/jeecg-boot#4447]
##### 问题描述：
后端启动后，通过验证码登录，报错：
java.lang.NoClassDefFoundError: org/HdrHistogram/DoubleRecorder

1. 检查过redis，可访问，路径密码端口都正确。2.4.6版本的后端可以访问。
2. 检查过配置文件，redis、分布式锁全都配置了正确地址，启动环境明确dev
3. 检查了jar包，有HdrHistogram包
4. 尝试外部引用HdrHistogram包，无效
5. 尝试切换springboot 2.6.4、2.6.7，仍报错无效

实在没有办法了，特求助

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不清楚，我们没遇到这个问题
