### ISSUE TITLE
如何自定义配置nacos的namespace命名空间

### ISSUE THREAD

**Issue by maxiaofang-nnn** [jeecgboot/jeecg-boot#4448]
##### 问题描述：
使用新版本代码后，按照原来的方式配置nacos的namespace命名空间不生效

##### 截图&代码：
这是原来的配置方式，使用这种方式，调用到的是默认的命名空间，没有调用到新配置的这个
![image](https://user-images.githubusercontent.com/27114816/209632510-71ac049c-a55d-4d88-b28a-ae2e008c228a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
具体遇到了什么错误？

**Comment by dishuicanghai** [comment]
白激动了一场，全是报错啊！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月28日(星期三) 中午11:35
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 如何自定义配置nacos的namespace命名空间 (Issue #4448)





 
具体遇到了什么错误？
