### ISSUE TITLE
修改org.jeecg的包名为org.xxx后，已经更改mapper的扫描配置，但是报错仍然有，扫描不到依赖中的内容。

### ISSUE THREAD

**Issue by guanghao95** [jeecgboot/jeecg-boot#4450]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
修改org.jeecg的包名为org.xxx后，已经更改mapper的扫描配置，但是报错仍然有，扫描不到依赖中的内容。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/26452352/209752735-e9bfe91b-f9ba-4258-92c8-6a5dfd89a9f1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
常见问题有这个问题：http://jeecg.com/doc/qa

**Comment by dishuicanghai** [comment]
你这错误，也值得发个邮件啊，你是不是故意发的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月28日(星期三) 中午11:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 修改org.jeecg的包名为org.xxx后，已经更改mapper的扫描配置，但是报错仍然有，扫描不到依赖中的内容。 (Issue #4450)





 
Closed #4450 as completed.
