### ISSUE TITLE
在线表单不能自定义显示序号

### ISSUE THREAD

**Issue by colaliu1** [jeecgboot/jeecg-boot#4452]
##### 版本号：
3.4.4

##### 问题描述：
表单应添加序号自定义显示字段，且目前主键设置无法显示

##### 截图&代码：

![image](https://user-images.githubusercontent.com/56527113/209895471-b8ff4e4f-9fa7-41be-be68-62314c3ac487.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
