### ISSUE TITLE
excel导出可以增加权限控制吗

### ISSUE THREAD

**Issue by 0xCoding** [jeecgboot/jeecg-boot#4458]
##### 版本号：
2.4.2

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
excel导出时可以和像表格列表的字段通过简单权限配置就可以控制是否显示该字段

##### 截图&代码：
像列表的字段权限配置
![1](https://user-images.githubusercontent.com/61595017/210130579-fc49a7d1-8b9e-4871-a528-998374f7a8dd.png)

1.Excel注解新增一个权限的属性
![@Excel增加权限标识](https://user-images.githubusercontent.com/61595017/210130639-8df2213d-98ca-4443-8e78-e1a02930dfc6.png)

2.使用@Excel
![2](https://user-images.githubusercontent.com/61595017/210130678-77032c00-3e0d-469a-9715-6df214d2123c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没做这逻辑，可以自己扩展实现
