### ISSUE TITLE
iE11 无法进入页面，一直处于加载状态

### ISSUE THREAD

**Issue by LYHHS** [jeecgboot/jeecg-boot#4460]
##### 问题描述：
IE11 浏览器无法进入页面，一直在加载状态，qiankun相关代码已经禁用，还是无效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/17923609/211145030-b694fabe-232d-474c-a6a5-38804bd57201.png)

**Comment by james-curtis** [comment]
增加fetch polyfill， github.com/fetch
下载fetch.umd.js，然后添加到index.html中babel-polyfill前面

**Comment by LYHHS** [comment]
> 增加fetch polyfill， github.com/fetch 下载fetch.umd.js，然后添加到index.html中babel-polyfill前面
多谢，已经解决了

**Comment by liangct** [comment]
怎么解决的哦，能否帖个代码

**Comment by LYHHS** [comment]
> 怎么解决的哦，能否帖个代码

先下载fetch.umd.js文件到本地项目文件，public/index.html 文件引入fetch.umd.js，
![image](https://user-images.githubusercontent.com/17923609/218371625-994ba38c-976a-475b-beb4-b7e7d0278736.png)

**Comment by liangct** [comment]
您好，非常感谢您的解答，fetch.umd.js 这个文件在哪里下载，能给个链接地址不 万分感谢

**Comment by liangct** [comment]
> > 怎么解决的哦，能否帖个代码
> 
> 先下载fetch.umd.js文件到本地项目文件，public/index.html 文件引入fetch.umd.js， ![image](https://user-images.githubusercontent.com/17923609/218371625-994ba38c-976a-475b-beb4-b7e7d0278736.png)


您好，非常感谢您的解答，fetch.umd.js 这个文件在哪里下载，能给个链接地址不 万分感谢

**Comment by LYHHS** [comment]
> 



> > > 怎么解决的哦，能否帖个代码
> > 
> > 
> > 先下载fetch.umd.js文件到本地项目文件，public/index.html 文件引入fetch.umd.js， ![image](https://user-images.githubusercontent.com/17923609/218371625-994ba38c-976a-475b-beb4-b7e7d0278736.png)
> 
> 您好，非常感谢您的解答，fetch.umd.js 这个文件在哪里下载，能给个链接地址不 万分感谢



> > > 怎么解决的哦，能否帖个代码
> > 
> > 
> > 先下载fetch.umd.js文件到本地项目文件，public/index.html 文件引入fetch.umd.js， ![image](https://user-images.githubusercontent.com/17923609/218371625-994ba38c-976a-475b-beb4-b7e7d0278736.png)
> 
> 您好，非常感谢您的解答，fetch.umd.js 这个文件在哪里下载，能给个链接地址不 万分感谢

下载地址：https://github.com/github/fetch/releases/tag/v3.4.1

**Comment by liangct** [comment]
> > 您好，非常感谢您的解答，fetch.umd.js 这个文件在哪里下载，能给个链接地址不 万分感谢
> 
> 下载地址：https://github.com/github/fetch/releases/tag/v3.4.1

谢谢谢谢，非常感谢~~！
