### ISSUE TITLE
注册账号 登录报错  

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4461]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/210311855-4285d951-ecf1-431d-9d53-2bc8508f5376.png)
![image](https://user-images.githubusercontent.com/121850941/210311878-8f7a809c-97c7-4146-a7c9-0075b15a97ef.png)
![image](https://user-images.githubusercontent.com/121850941/210311926-8b088d0d-4148-4fea-b73d-4797bd9a05aa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可能跟数据有关，你debug应该能跟踪到原因
