### ISSUE TITLE
j-vxe-table columns 自定义验证规则问题

### ISSUE THREAD

**Issue by miluotao** [jeecgboot/jeecg-boot#4462]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
j-vxe-table columns  validateRules  自定义 handler里面是不是拿不到外部变量

##### 截图&代码：

```
  {
            title: '联系人电话',
            key: 'supplierLinkmanPhone',
            type: JVXETypes.input,
            width: "200px",
            placeholder: '请输入${title}',
            defaultValue: '',
            validateRules:[{
              handler({ cellValue, row, column }, callback, target) {
                if (this.isMust) {
                  callback(false, '${title}不能为空') // false = 未通过，可以跟自定义提示
                } else {
                  callback(true) // true = 通过验证
                }
              }
            }],
          },
```

**Comment by xiaohuang-123** [comment]
大佬 type: JVXETypes.select,用过吗

**Comment by miluotao** [comment]
> 大佬 type: JVXETypes.select,用过吗

没有 我也是刚开始用

**Comment by sjlei** [comment]
`this` 作用域问题，可以把`handler`换成箭头函数即可。

[箭头函数 - ECMAScript 6 入门](https://es6.ruanyifeng.com/#docs/function#%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0)

**Comment by miluotao** [comment]
> `this` 作用域问题，可以把`handler`换成箭头函数即可。
> 
> [箭头函数 - ECMAScript 6 入门](https://es6.ruanyifeng.com/#docs/function#%E7%AE%AD%E5%A4%B4%E5%87%BD%E6%95%B0)

感谢提醒
