### ISSUE TITLE
求助：如何配置后端接口HTTPS访问？

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecg-boot#4463]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前访问后端接口为: http://jeecgboot:8081/jeecg-boot/
想要改为https访问后端接口：https://bomaiinfo.com/jeecg-boot/
后端原来是通过以下命令启动的：java -jar C:\JeecgBoot\jeecg-system-start-3.4.4.jar
应该如何配置443端口以及ssl证书，然后如何部署后端，才能达到https访问接口的目的？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/36326638/210473313-7ba3546e-c0a6-4a30-99df-7fbe9d448d57.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
仅供参考，其实可以通过Nginx
https://my.oschina.net/jeecg/blog/4494367

**Comment by gxzhou** [comment]
好的。多谢。
