### ISSUE TITLE
JTreeSelect能选择自己的问题

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4464]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
JTreeSelect组件能够选择节点本身引发的问题，选择自己后该会消失，消失原因已知是查询逻辑导致查询不到。
查看了菜单管理，发现也没有进行处理，存在同样的问题（官网远程没有权限，无从得知官网菜单管理是否存在同样问题）；
想询问如何在候选中过滤掉自己本身。
##### 截图&代码：
组件的调用
![image](https://user-images.githubusercontent.com/118323262/210496596-17abd0f2-760f-4a2a-9a20-fecdd053c0c3.png)
可以选择自己，确认后记录消失
![image](https://user-images.githubusercontent.com/118323262/210497605-a3410c3c-285f-4e49-87e9-76141e7a3824.png)
![image](https://user-images.githubusercontent.com/118323262/210497723-afba05c5-52d7-44dc-96aa-33b4ce4c9f4e.png)
在本地 我的菜单管理也有同样的问题存在

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个可以忽略
