### ISSUE TITLE
微信钉钉二维码登录

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4465]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/210511183-013b51a6-15a8-4ee3-9ad5-5e4edcbcc03e.png)

这个扫描二维码是怎么判断是钉钉扫描还是微信扫码啊

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2200339
