### ISSUE TITLE
主表增强js没有效果

### ISSUE THREAD

**Issue by erichui2017** [jeecgboot/jeecg-boot#4466]
##### 问题描述：
新建主表，使用增强js没有效果，而且没有任何错误提示，加上日志输出也没有任何提示，js是完全按照文档写的。
请问如何进行调试，在哪里看js有没有运行。

##### 截图&代码：
onlChange(){
  return {
    type1(){
      console.log('get enchange');
      alert(event.value);
      let value = event.value
      that.changeOptions('city',cityOptions);
    },
    name1(){
      console.log('get enchange');
      alert(event.value);
      let value = event.value
      that.triggleChangeValues('moudel1', "id");
    }
  }
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by james-curtis** [comment]
生成代码之后是无法使用各种增强的

**Comment by zhangdaiscott** [comment]
增强是在线的概念，不支持生成

**Comment by dahailiu123** [comment]
不支持生成，那怎么使用呢？文档里没看到具体使用的例子啊？
