### ISSUE TITLE
想问一下，feign调用传递的token之类的头信息在哪增加修改呢

### ISSUE THREAD

**Issue by 903249871** [jeecgboot/jeecg-boot#4468]

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot-starter/blob/master/jeecg-boot-starter-cloud/src/main/java/org/jeecg/config/FeignConfig.java

**Comment by 903249871** [comment]
> 

下载的源码里没有这个项目

**Comment by 903249871** [comment]
> 

git里面也看不到的，是没有权限吗

**Comment by 903249871** [comment]
> https://github.com/jeecgboot/jeecg-boot-starter/blob/master/jeecg-boot-starter-cloud/src/main/java/org/jeecg/config/FeignConfig.java

找到了
