### ISSUE TITLE
奇安信检测好多漏洞

### ISSUE THREAD

**Issue by 132504j** [jeecgboot/jeecg-boot#4469]
##### 截图&代码：
![1672882478449](https://user-images.githubusercontent.com/40945559/210681662-7d5b5c40-04c0-4807-bda3-ccaf7675e6d1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以发详细的日志给邮件 jeecgos@163.com
