### ISSUE TITLE
a-drawer使用bug

### ISSUE THREAD

**Issue by lhpdemo** [jeecgboot/jeecg-boot#4470]
##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
在使用a-drawer时 在切换菜单的时候 a-drawer不消失

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请提供截图说明
