### ISSUE TITLE
租户管理系统角色表

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4471]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/210733666-0fc3473b-682e-439b-bbe5-9cb23efbadb1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by LJL888999** [comment]
我的想法是角色就是这些 用户 和角色 租户和租户的关系都用第三个表

**Comment by zhangdaiscott** [comment]
有一个租户角色概念，也就是租户维护自己名下的角色

**Comment by LJL888999** [comment]
那就是比如两个租户 下面的角色都叫财务 那我在角色表要弄两条数据 不能弄一条了

**Comment by zhangdaiscott** [comment]
本来就应该自己维护自己的
