### ISSUE TITLE
报表打印不全

### ISSUE THREAD

**Issue by MrZhang111** [jeecgboot/jeecg-boot#4473]
##### 问题描述：
查看了下积木报表给的示例，打印和pdf导出的时候，即使更换纸张规格，还是显示不全

##### 截图&代码：
![1672972639185](https://user-images.githubusercontent.com/31603555/210918548-9f70f792-4351-4f66-ad75-8691f12d8d59.png)
![1672972672909](https://user-images.githubusercontent.com/31603555/210918602-0d537277-7227-4c09-b3a2-638c63f3ef64.png)
![1672972749304](https://user-images.githubusercontent.com/31603555/210918750-6a4adaf9-6062-456d-9ed3-4874df3944f1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
打印是根据你设置的纸张站位来打印的，所以你需要打印成什么样，需要提前设置，并根据纸张设计报表

![image](https://user-images.githubusercontent.com/3162115/211445154-a23355bf-94aa-493f-8710-c018bf441204.png)
