### ISSUE TITLE
online在线开发表单编辑弹窗关闭无响应

### ISSUE THREAD

**Issue by jessedog** [jeecgboot/jeecg-boot#4476]
##### 问题描述：
online在线开发表单编辑弹窗关闭无响应

##### 截图&代码：
在自己电脑上运行的dev版本，在线开发表单的编辑弹窗出现后如果点击右上角“关闭”按钮要等20s左右才会关闭，期间页面无响应
![image](https://user-images.githubusercontent.com/7986198/210975436-3829f45a-d5ae-4931-bd55-39828e71ed53.png)

如果点点击“保存”的话，“/online/cgform/api/editAll”接口需要耗时6-9s，然后‘online/cgform/head/list’接口会卡在待处理状态20秒左右才会继续，不过显示接口耗时不到1s，最终才关闭调弹窗
![image](https://user-images.githubusercontent.com/7986198/210975805-3b2ececd-eaad-4067-b06a-9d52f2adef62.png)
![image](https://user-images.githubusercontent.com/7986198/210976613-7d91da13-128c-4af1-ac68-8655813d4172.png)

**Comment by zhangdaiscott** [comment]
是不是开启了vue tools调试工具

**Comment by jessedog** [comment]
> 是不是开启了vue tools调试工具

确实开了vue tools调试工具，关掉之后页面无响应的问题就没有了，但是修改表单之后调用“editAll”接口还是需要5-6s

**Comment by zhangdaiscott** [comment]
修改数据不至于吧，数据库慢？

**Comment by jessedog** [comment]
![image](https://user-images.githubusercontent.com/7986198/211482776-7127c2fb-44a8-4567-9b95-25dbc125d6e4.png)
确实大部分时间花在了数据库上，我连的是台式机上mysql8，但性能应该不至于这么差吧。跑之前的3.0版本也没这么慢呢

**Comment by zhangdaiscott** [comment]
数据库的问题得你自己确认
