### ISSUE TITLE
在线生成from.vue的this.visible参数问题

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4478]
##### 版本号：
v3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
vue2在线生成发现edit(record) 方法中有个参数是this.visible = true;，感觉这个参数没用到，不起作用，删除了也不影响，是在线生成的代码问题吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/211141197-e725456d-afd8-4be6-8b4f-924adc618bd2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
忽略
