### ISSUE TITLE
RabbitMq 消费中异常，消息重复投递

### ISSUE THREAD

**Issue by hyoutom** [jeecgboot/jeecg-boot#4481]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
现象: 在消费队列的代码当中， 比如生成文件 io异常， mq的 onMessage会自动捕捉异常，然后将消息 重新放回队列，无限重复。
之前版本可以修改BaseRabbiMqHandler  下的onMessage ，可是这一版的框架 将BaseRabbiMqHandler  改成外部引入包无法修改，不知道该怎么处理了。
在配置文件当中 
default-requeue-rejected =false 也没有效果。

期望: 队列消费代码中异常， 可以自己选择 是丢弃该消息还是 重复投递该消息。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/51776513/211232323-e0fe560d-cb19-4435-9e0e-09231da52283.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot-starter

**Comment by Kyle13145** [comment]
@zhangdaiscott 目前我看源码是写死的，RabbitMq这一块后续会考虑优化吗，可以在yaml文件中可以进行灵活配置。
