### ISSUE TITLE
公司部门员工数据规则权限问题

### ISSUE THREAD

**Issue by Leevampire** [jeecgboot/jeecg-boot#4482]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？ 
vue3版

##### 问题描述：
疑问：超级管理员新建一个公司管理员A账号，新建公司TEST给予店铺管理权限以及数据规则，且店铺管理新建了数据规则根据syscode只能看到本公司的。登陆公司管理员A账号后，新建部门账号李四，新建部门角色店铺管理员。给部门账号李四给予店铺管理员权限，但是未勾选数据规则，会默认看到所有公司的店铺信息。存在数据安全隐患
总结：这部分数据权限管控是否存在遗漏，部门授权了数据规则，部门员工还需要重新授权吗？

##### 截图&代码：
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/54231464/211235162-ee1cbd62-0b7b-4896-9d97-38f129df7a68.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
数据权限这块是分配了权限做数据控制，不分配不控制

**Comment by Leevampire** [comment]
那我这部分怎么控制不同公司数据源。。。因为我新建了数据规则只能看到本公司。 如果新建部门员工，部门角色授权我不勾选规则默认可以看到所以的，这对其他公司来说不是有数据泄露的风险吗？
