### ISSUE TITLE
online表单的测试页面的翻页器设置在哪里

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4483]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
请教online表单的测试页面的翻页器设置在哪里？其他功能的翻页器可以在 componentSetting.ts 里面设置 defaultPageSize, pageSizeOptions 设置生效，但是好像对online表单的测试页面无效果，找了一番也没有，望指教

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1177503/211256429-6d0bfa91-e850-4762-8643-3e6b6a672932.png)

![image](https://user-images.githubusercontent.com/1177503/211256532-70a97b4a-dbb0-46ab-a237-5f67b17363da.png)

![image](https://user-images.githubusercontent.com/1177503/211256708-a730eae8-cc05-4bba-98d0-c9260c7deb5f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前是底层写死的，不支持自定义


![image](https://user-images.githubusercontent.com/3162115/211444765-580eb494-674c-4005-82bb-039aa0c28692.png)

**Comment by yingw** [comment]
好的，谢谢，不分页还能稍微用下，那个默认10，应该在前台哪里可配置的，我是否可以修改基础代码改成20或30？@zhangdaiscott
