### ISSUE TITLE
查询条件的名称截取了4个字符

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4484]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
查询条件的名称截取了4个字符？可否关闭此功能

发现字段的中文描述大于4个字符时候，在作为查询条件时，文本内容被截取了4个字符，后面的看不到，不知是否有设置地方可关闭这个功能，此功能用意是什么？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1177503/211257555-61845032-86dc-4a9e-a5bb-40ec483c4dd7.png)

![image](https://user-images.githubusercontent.com/1177503/211257643-8032e764-3afc-4195-82c2-01699793c6f9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
超长截取显示，不然查询样式会很丑，鼠标放上去可以显示全文

**Comment by yingw** [comment]
谢谢。可是，这会造成很多歧义，我能否手动去掉？相关功能在前后台哪里？

**Comment by yingw** [comment]
@zhangdaiscott
