### ISSUE TITLE
修改了全局模糊查询对online表单无效

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4485]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
根据文档： http://doc.jeecg.com/2043926 的方式修改了全局文本查询条件模糊查询，对系统功能查询页面有效，对online表单建模的测试功能无效，请问online表单的查询不是 QueryGenerator.installMplus ，应该在哪里修改？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1177503/211267612-3e9b5d2d-92a8-48f7-b9d2-c74af2960c72.png)
![image](https://user-images.githubusercontent.com/1177503/211267868-abc40fde-3c87-46d4-81fd-0abe4e4ca5d1.png)
![image](https://user-images.githubusercontent.com/1177503/211267907-8e7651ee-d047-4b5b-9d69-c279194c9c97.png)
![image](https://user-images.githubusercontent.com/1177503/211267951-c8841bb2-6eb8-4455-a118-1ebe5a3d4e41.png)
![image](https://user-images.githubusercontent.com/1177503/211268087-c7e6a125-ed54-42c7-a6f5-dc9f10f2480a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不建议这么改，有个前端jinput组件可以实现默认模糊查询

**Comment by zhangdaiscott** [comment]
是的

**Comment by ImOkkkk** [comment]
你好 请问最后怎么解决的呢？
