### ISSUE TITLE
Apache Tomcat HTTP请求走私漏洞，威助等级: 高危

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/jeecg-boot#4487]
##### 截图&代码：
![1ffa94fcb9a2a1fb2ea7d6d4cfac039](https://user-images.githubusercontent.com/55725161/211438587-7aa56195-839a-4546-bafa-6c0233089ae9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
spring-boot-starter-parent
升级到
2.6.14
![image](https://user-images.githubusercontent.com/3162115/211442705-8f869e88-d092-42b2-b0fd-8510a9baf4d2.png)
