### ISSUE TITLE
切换主表选中行子表选中行不清空问题

### ISSUE THREAD

**Issue by maxxious** [jeecgboot/jeecg-boot#4490]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
选中主表数据加载子表数据时默认没有清空子表的选中，即我在选中一条子表数据之后，去选中一条别的主表别的数据，此时子表数据刷新但是选中子表的数据没有清空，我在子表有选中行操作，这就使得我页面上子表没有选中的数据，但是可以进行选中行操作。
于是我尝试调用setSelectedRowKeys清空子表数据
1.在子表的watch中调用setSelectedRowKeys，结果主表的选中行被清除。
2.在afterFetch中调用setSelectedRowKeys，结果子表选中行被清除达到预期效果，但是出现一个新的问题：在该页面第一次进入时，选中主表不会刷新子表。
3.在beforeFetch中调用setSelectedRowKeys，结果选中主表数据后子表数据不刷新。
4.在@fetch-success="onFetchSuccess"的onFetchSuccess中调用setSelectedRowKeys([])结果，子表一直刷新。

综上，我想请教一下我应该如何正确的在改变主表选中行时去清空子表的行选中。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/118323262/211476006-7e06f0a2-3f51-4a4a-9d85-71e675c504b8.png)
![X(3TOO~8P2(P(~6UL98SLFO](https://user-images.githubusercontent.com/118323262/211476326-3d8df509-9a1a-49c7-af02-10f7b3bad302.png)
![)ZGL{09~LV~@6Y_VMF0XT U](https://user-images.githubusercontent.com/118323262/211477304-ce7344c1-1165-4e5e-a367-27a0b63820a5.png)
代码
![image](https://user-images.githubusercontent.com/118323262/211477631-a39c55e6-ec4c-4c34-939f-a559972dd1d3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by sjlei** [comment]
子表watch监听主表id变化，然后清空自身的选中状态即可。可以见下图或者我发的压缩包里的示例代码。
你说的第一个问题：
> 1.在子表的watch中调用setSelectedRowKeys，结果主表的选中行被清除。
应该是调串了方法，调成了主表的方法导致主表选中行被清空了，你可以分组件开发即可。

[点击下载：ERP主子表示例.zip](https://github.com/jeecgboot/jeecg-boot/files/10637391/ERP.zip)

![image](https://user-images.githubusercontent.com/34293221/216873440-a4e33b52-7652-4d24-88d0-e8df89b8331f.png)
