### ISSUE TITLE
修改了自动折叠相关参数但不起作用

### ISSUE THREAD

**Issue by yingw** [jeecgboot/jeecg-boot#4491]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
在后台修改了 props.ts 修改了自动折叠相关的参数，前台表单也已经拿到，但是界面显示不起作用

##### 截图&代码：

![image](https://user-images.githubusercontent.com/1177503/211500841-764345f5-ae3a-4d9d-854c-8d09cb5a930b.png)
![image](https://user-images.githubusercontent.com/1177503/211500962-2ba492dc-94e6-48d6-a8cd-6b210d812932.png)
![image](https://user-images.githubusercontent.com/1177503/211501036-e1e18102-9f8c-4c6a-a330-bb7c30053eae.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
online表单的搜索没有用到props.ts 中的折叠配置；
自定义列表页面的的查询搜索折叠配置要生效，需要修改useListPage.ts 205行formConfig的配置；
![image](https://user-images.githubusercontent.com/65587928/229779108-e65f7886-d053-4788-a4d2-2f11dfb3d306.png)
