### ISSUE TITLE
WebSocket无法连接

### ISSUE THREAD

**Issue by Kyle13145** [jeecgboot/jeecg-boot#4493]
##### 版本号：
3.3.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
按照 https://github.com/jeecgboot/jeecg-boot/issues/699 进行配置配置以后还是无法连接。

##### 截图&代码：
nginx配置
![image](https://user-images.githubusercontent.com/34505623/211748931-62126b1e-9149-4045-83fa-7f247f98ea9e.png)
报错信息
![image](https://user-images.githubusercontent.com/34505623/211749270-d17b605d-3672-47eb-b421-d69786b21640.png)
请求信息
![image](https://user-images.githubusercontent.com/34505623/211749585-396ecd0b-e474-4f29-9a77-fd3cd8dfb004.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
本地好使？

**Comment by Kyle13145** [comment]
@zhangdaiscott 本地没问题，线上连接不上

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
搜 websocket

**Comment by Kyle13145** [comment]
都看了，应该是nginx代理问题，但是看了好几遍，不知道问题出在那里，其他接口都可以，就这个websocket有问题，我在过滤器那里打了日志，发现日志没有输入，具体原因还不清楚。

**Comment by Kyle13145** [comment]
VITE_GLOB_DOMAIN_URL 后台接口全路径没写完整导致的
