### ISSUE TITLE
数据字典表使用的一个小BUG，字典编码名称类似时未能准确区分

### ISSUE THREAD

**Issue by gxzhou** [jeecgboot/jeecg-boot#4494]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
一个表的状态字段rowstate使用下拉框系统字典，编码为ShipRowState，但发现列表中该字段显示是code，没有把text显示出来。
##### 截图&代码：
一个表的状态字段rowstate使用下拉框系统字典，编码为ShipRowState，但发现列表中该字段显示是code，没有把text显示出来：
![1673424554892](https://user-images.githubusercontent.com/36326638/211754302-92ea5d6f-8633-4b69-9803-98e000a24d2a.png)
![1673424633032](https://user-images.githubusercontent.com/36326638/211754490-105296bd-50d1-436d-b212-e32ad6f703e3.png)
![1673424746242](https://user-images.githubusercontent.com/36326638/211754529-2a985fff-d00f-4898-8769-3e5727d9afd8.png)

偶尔发现其中有一个“可配送”是转换了的，实际上数据库表中的rowstate是3，因为状态编码曾经修改过，原来用数字编码，后改为用英文单词编码，那条数据正好没有修改过来。于是顺腾摸瓜查后，发现有一个老的字典编码为“ShipRowState1”能把3转换为“可配送”，因此应该可以判断此处系统在数据字典转换时，没有使用“ShipRowState”而使用了类似的“ShipRowState1"，会不会是因为数据库表查询时字典编码名称匹配问题引起？
![1673424806316](https://user-images.githubusercontent.com/36326638/211755785-fb8779b6-61e5-4db0-9838-94b091ff7c72.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by gxzhou** [comment]
不是bug，可能是运行环境问题？我重新用不同浏览器使用类似功能，然后就又好了。
![1673426407912](https://user-images.githubusercontent.com/36326638/211759449-845772e4-4643-4885-9893-72a01c2b1d3b.png)

**Comment by gxzhou** [comment]
这个问题还真的是问题，我用谷歌浏览器，今天又出现取错字典代码了：
![1673861608738](https://user-images.githubusercontent.com/36326638/212646606-2afdff64-5c73-47e4-a382-1c25c6768d62.png)
![1673861633460](https://user-images.githubusercontent.com/36326638/212646672-32dc8df3-0084-4efe-8995-930a822b0828.png)
以上是在线表单。
代码生成的表单是对的：
![1673862205187](https://user-images.githubusercontent.com/36326638/212649849-87f70292-0037-4c44-a4cd-d3fe0c5ea979.png)

这次我改变浏览器等环境，也没能解决。将ShipRowState1改为zShipRowState1，然后清除缓存后， 就正常了。

**Comment by zhangdaiscott** [comment]
你是采用那种编码方式实现的字典翻译?
如果是前端的话，看看是不是因为接口慢

**Comment by gxzhou** [comment]
这个有可能是因为缓存问题引起？我起了几个应用都使用同一个redis，会不会有问题。暂时先不管了。我先关闭这条吧。

**Comment by gxzhou** [comment]
我用的是前端配置字典代码的方式。
