### ISSUE TITLE
jeecg的角色管理页面权限问题

### ISSUE THREAD

**Issue by zhangchunkui** [jeecgboot/jeecg-boot#4495]
##### 问题描述：jeecg配置了一个角色caiwu Leader，这个角色只有系统管理的所有菜单。然后这个角色对应的用户登录之后，在系统管理-->角色管理，却可以看到所有的菜单，并且也能对这些不属于他的菜单进行授权。这个问题怎么解决？谢谢！
我期望的是：这个caiwu Leader角色对应的用户登录之后打开角色管理，应该只能看到他自己的菜单，不应该看到其他的菜单。请大神们给与解惑，非常感谢！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/15085549/211764480-0a46667d-96c6-4f71-a60f-3dcb4964c664.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你应该使用部门角色，那个可以限制只能看那些菜单，进行授权
