### ISSUE TITLE
脱敏时List中的实体类没有正确识别

### ISSUE THREAD

**Issue by luoxiangggv** [jeecgboot/jeecg-boot#4497]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
想问下，脱敏这块，文档上说List也支持，但是我测试发现List中的对象被识别为Object，并不是实体对象，导致无法脱敏，请问这个问题应该如何处理？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/48273019/211998645-5db0d614-13cd-4119-ab71-dfb58ed62496.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
如果方法返回list，注解配置如下：
![image](https://user-images.githubusercontent.com/27989856/230849510-0c43ee28-5777-4715-a792-3428ea3e2bc1.png)
