### ISSUE TITLE
表结构主键id为bigint导入，无法用表单开发中的功能测试进行修改

### ISSUE THREAD

**Issue by Ping1kl** [jeecgboot/jeecg-boot#4500]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vu2

##### 问题描述：
操作步骤：
1.表导入后点击功能测试
![L0YDTOQZV5P8PTFR$}0MF46](https://user-images.githubusercontent.com/116577791/212264363-16061132-537c-448d-9b99-e44523ba30bc.png)
2.进入功能测试页面，点击编辑，然后修改，但修改后值还是没变
![image](https://user-images.githubusercontent.com/116577791/212264741-8a6f3650-53db-4638-9d5e-c8db25147db8.png)
![image](https://user-images.githubusercontent.com/116577791/212264912-528e4c98-347c-431e-8bda-d25b7679cce9.png)

3.查看接口请求，发现删除时入参id不对，id应是1613793031042715650，但是接口请求的id为1613793031042715600
数据库中数据id为1613793031042715650

![CJT5_~BA3W186J%W)QRJKCF](https://user-images.githubusercontent.com/116577791/212265232-2c8487a6-8bef-4b1d-bf7a-523c3a7dda9c.png)

![2}KHM~PVE6 2I849 FMD%)9](https://user-images.githubusercontent.com/116577791/212265307-1678cdf2-b986-4d30-9b79-eaa5a5094028.png)

表结构sql

create table my_table
(
    id           bigint auto_increment comment '主键'
        primary key,
    create_by    varchar(50) null comment '创建人',
    create_time  datetime    null comment '创建日期',
    update_by    varchar(50) null comment '更新人',
    update_time  datetime    null comment '更新日期',
    sys_org_code varchar(64) null comment '所属部门',
    tes          varchar(32) null comment '的'
);

**Comment by zhangdaiscott** [comment]
是的，目前只支持string类型id
