### ISSUE TITLE
导入的excel中字段如何截取数据

### ISSUE THREAD

**Issue by chao199604** [jeecgboot/jeecg-boot#4501]
##### 版本号：

jeecgboot商业版
##### 问题描述：

导入的excel中字段如何截取数据？后台获取的数据，怎么把excel中的数字和括号截去，只取后面的汉字，同时用字典表，excel中是汉字，数据库存的是id
##### 截图&代码：

![image](https://user-images.githubusercontent.com/112382411/212289231-f71eed7c-e346-4692-a9d8-5d3e55a90745.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
导入逻辑，自己二开，加入自己逻辑就行
