### ISSUE TITLE
gateway服务启动报错

### ISSUE THREAD

**Issue by qiuastq** [jeecgboot/jeecg-boot#4502]
##### 版本号：
3.4.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
启动gateway服务报其它module中的class文件找不到，实际target中是有class文件的

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/35282239/212532675-44a07ca6-b1d3-450f-be28-61564a911f45.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
clean下，刷新下maven看看
