### ISSUE TITLE
mysql8数据库引入sql文件时候有警告

### ISSUE THREAD

**Issue by a61206115** [jeecgboot/jeecg-boot#4504]
##### 版本号：
jeecg-boot 3.4.4

##### 前端版本：vue3版？还是 vue2版？
无

##### 问题描述：
数据库版本：8.0.31-0ubuntu0.20.04.2
引入github上拉的jeecg-boot 3.4.4里面自带sql文件有很多警告，不知道是不是正常的，其中一个文件（jeecgboot-mysql-5.7.sql）
不知道和我用的mysql8兼容不兼容。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/55905292/213067239-ec5765f8-4e4f-4e2b-9ba4-88bcdfd7526a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不影响表导入忽略就行
