### ISSUE TITLE
部门管理模块增加多租户功能。新增数据，db中sys_depart,tenant_id为0

### ISSUE THREAD

**Issue by jin2001** [jeecgboot/jeecg-boot#4505]
##### 问题描述：部门管理模块增加多租户功能。新增数据，db中sys_depart,tenant_id为0；已经做了初步排查。
1.sys_depart追加tenant_id int
2.MybatisPlusSaasConfig中追加 TENANT_TABLE.add("sys_depart");
3.前端请求的header中存在 tenant-id: 1
4.后端JwtFilter中代码也实现了 TenantContext.setTenant(tenantId);

**Comment by zhangdaiscott** [comment]
近期会发布成熟的多租户方案，直接切换系统管理模块
