### ISSUE TITLE
JDictSelectTag组件使用时，浏览器给出警告提示：Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array...

### ISSUE THREAD

**Issue by sxx412** [jeecgboot/jeecg-boot#4507]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
JDictSelectTag组件使用时，提示警告信息：
Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array...

##### 截图&代码：
访问菜单：jeecg组件示例-单表原生示例，为了便于演示，屏蔽了其他组件

![image](https://user-images.githubusercontent.com/51403156/213134782-4c9a4124-9675-4522-8d78-9d7cb5ef3b6d.png)

![image](https://user-images.githubusercontent.com/51403156/213134935-a13541aa-0a6e-48a5-bc6d-073008b5ab92.png)

![image](https://user-images.githubusercontent.com/51403156/213135267-fd38be2e-9a7a-4204-a218-e7aa0089b988.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by bantu4me** [comment]
我也想问，源码看得不明白，我看组件里面声明props的value类型时，用的是propTypes.oneOfType([propTypes.string, propTypes.number, propTypes.array]，所以报错说onUpdate:value". Expected Function, got Array，期待函数类型，是不是这个propTypes.oneOfType，但是为什么选择数据后，又说得到的是一个数字。。。没看懂

**Comment by 1298191366** [comment]
已修复，待新版本发布
