### ISSUE TITLE
多租户情况下，切换用户登录，提示错误。

### ISSUE THREAD

**Issue by jin2001** [jeecgboot/jeecg-boot#4509]
##### 问题描述：
                              多租户情况下，用户A与用户B分属不同的租户。
                              用户A登录后退出。用户B再登录，画面提示错误：【Cannot destructure property 'userInfo' of '(intermediate value)' as it is undefined.】。  再次登录成功。
                             初步调查，访问后台的接口getUserInfo返回的是{success: true, message: "用户租户信息变更,请重新登陆!", code: 401, result: null, timestamp: 1674100143058}

**Comment by zhangdaiscott** [comment]
我们近期会发布完整的多租户解决方案。
