### ISSUE TITLE
vue3 前端pnpm build报错

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#4510]
##### 问题描述：
vue3 前端pnpm build报错

##### 截图&代码：
file: D:/jeecgboot-vue3-masterc/components/Formc/jeecg/components/JSwitch.vue:undefined:undefined

ERROR  error during build:                                                                                                                                                                                                   04:23:17  
SyntaxError: v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.

**Comment by zhangdaiscott** [comment]
你升级到最新，改过这个问题
