### ISSUE TITLE
报表跨页导出不生效

### ISSUE THREAD

**Issue by knigtZ** [jeecgboot/jeecg-boot#4512]
##### 截图&代码：
![1675052134006](https://user-images.githubusercontent.com/123919812/215386266-ae3be7ea-48d6-40d5-b19a-d6d950ef9c10.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
非bug 暂时归集到  https://github.com/jeecgboot/jeecg-boot/issues/1312 ，待后期规划

**Comment by liaozhiyang** [comment]
这个功能后期加上了，版本升级下试试
