### ISSUE TITLE
列表优化建议

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#4513]
##### 版本号：

v3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
列表页面上下滚动条位置放在如图长条框表单数据右侧好点，上面查询、表头，下面左右滚动条，分页固定不用动；
然后每页条数弄大点最好，现在最多才30条，我们客户大多都要求列表默认200-500条以上

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55084864/215639477-9762eb81-e20e-44ff-b72a-f7ca19af0f2e.png)

![image](https://user-images.githubusercontent.com/55084864/215639331-78625161-451f-4361-bf09-b520a84bdcfa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个自定义即可
