### ISSUE TITLE
jeecgboot如何导出前端页面统计图和对象数据

### ISSUE THREAD

**Issue by pengpenghello** [jeecgboot/jeecg-boot#4514]
##### 截图&代码：效果图如下：
![QQ截图20230131103139](https://user-images.githubusercontent.com/96603310/215647248-4a7c29b6-7ad0-41fe-bacc-cb1cbd252777.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个跟jeecgboot没关系，自己编码实现就行
