### ISSUE TITLE
应用管理中应用问题

### ISSUE THREAD

**Issue by zjhzgxl** [jeecgboot/jeecg-boot#4517]
##### 版本号：
v3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
导航栏中，应用管理->应用首页中我新建一个应用，新建的应用是否可以导出，并脱离平台运行。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19724978/215961505-4ea280d4-c321-4d78-8c9e-06856cf8a50c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个功能后期会去掉，你可以看下敲敲云平台，我们独立拆分的项目
https://www.qiaoqiaoyun.com/
