### ISSUE TITLE
使用菜单配置Online表单页面，路由缓存没用

### ISSUE THREAD

**Issue by xiaohundun** [jeecgboot/jeecg-boot#4518]
##### 版本号：
jeecg-boot 3.4.0
vue-antd-jeecg 3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用菜单配置Online表单页面，路由缓存没用

##### 截图&代码：
<img width="608" alt="image" src="https://user-images.githubusercontent.com/38812912/215991658-cd8e179a-b644-4a97-a35e-bbc9f6435e58.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你想缓存什么内容
