### ISSUE TITLE
ISysBaseAPI 没有相关业务方法

### ISSUE THREAD

**Issue by hzl7652** [jeecgboot/jeecg-boot#4519]
##### 版本号：

v3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前ISysBaseAPI 中没有，如根据部门代码获取用户列表，获取公司详情等相关业务方法。我想在新建的业务模块需要调用system里面的相关业务数据，如何处理比较好。再自定义个mapper吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己在这里面定义新方法即可
参考这个
http://doc.jeecg.com/2159190

**Comment by hzl7652** [comment]
收到，感谢
