### ISSUE TITLE
手机号登录 SQL

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4520]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/216483961-280eaaca-5047-432d-afd1-02fbd357267e.png)
![15666351cddf15fc1397ee1cb3841a2](https://user-images.githubusercontent.com/121850941/216484036-3b2eea89-dc11-4cb4-8fcc-0eb5b004bc95.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是不是把用户表加入到租户隔离配置里了
