### ISSUE TITLE
企业微信移动端报错ERROR_CONNECT

### ISSUE THREAD

**Issue by chenjiazhong** [jeecgboot/jeecg-boot#4521]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
链接在企业微信移动端打开时，首先加载一会儿，加载完成后，安卓端报错ERROR_CONNECT，IOS端报错NSURLErrorCannotConnectToHost，但是链接在企业微信PC端，浏览器，微信PC端，微信移动端均可以使用。

##### 截图&代码：

错误代码如下：
企业微信安卓端：ERROR_CONNECT
企业微信IOS端：NSURLErrorCannotConnectToHost

**Comment by 1298191366** [comment]
vue3不支持企业微信移动端，后期支持uniapp集成微信移动端
