### ISSUE TITLE
版本号解决方案

### ISSUE THREAD

**Issue by 346069073** [jeecgboot/jeecg-boot#4522]
##### 版本号：
3.0.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
我这边是边使用边开发, web端版本升级非常频繁.  但是某些用户浏览器内的缓存导致他们使用的经常不是最新版本, 导致提交上来一些脏数据,  请问这种情况有没有 依赖版本号 之类的解决方案?

**Comment by zhangdaiscott** [comment]
暂时没有
