### ISSUE TITLE
同步钉钉部门到本地-原本两级部门中间多加了一级，导致orgCode有误

### ISSUE THREAD

**Issue by luoqiuqiu** [jeecgboot/jeecg-boot#4526]
##### 问题描述：
1、原先同步过钉钉部门到本地，结构如下
部门A：A01
       部门B：A01A01
2、后钉钉部门更改，在A和B中间加了C部门，导致orgCode有误
部门A：A01
       部门C：A01A02
              部门B：A01A01
请问这种情况该如何解决
##### 截图&代码：
![image](https://user-images.githubusercontent.com/52776176/216903736-bbe6c633-7323-4231-ba60-b793fb3e7478.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个只能手工改数据
