### ISSUE TITLE
在菜单配置外网打开的链接并刷新过后，点击跳转404.

### ISSUE THREAD

**Issue by reset-0** [jeecgboot/jeecg-boot#4527]
##### 截图&代码：
![A_I__9OV_ GF54)9J%LSM7P](https://user-images.githubusercontent.com/85207273/217123480-b2ee7e64-3b96-4c26-af74-d756a5440508.jpg)
![J CJK4)DO )$1VS(12G ZCG](https://user-images.githubusercontent.com/85207273/217123494-312f5046-7eea-4908-9e62-06d5c0f4bf4f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
参考下项目的外网链接例子是怎么配置的
