### ISSUE TITLE
低代码开发方式配置的【文件上传】组件，会报nginx 405 not allowed, 如何解决？

### ISSUE THREAD

**Issue by niulixin0123** [jeecgboot/jeecg-boot#4529]
##### 问题描述：
   低代码开发方式（即Online在线功能）配置的【文件上传】组件，会报nginx 405 not allowed, 如何解决？

##### 截图&代码：
<img width="972" alt="image" src="https://user-images.githubusercontent.com/32357651/217131688-10ebd627-958b-46a1-b7d7-3ea7564e9744.png">

**Comment by zhangdaiscott** [comment]
不清楚，你看看是不是限制了什么，我们部署是没问题的

**Comment by XiaoQiaoLiuShui97** [comment]
@niulixin0123 你好，不知这个问题是否解决了呢，遇到同一个问题
