### ISSUE TITLE
Online表单修改后可以消息推送？

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4531]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
想问下2个问题：
1.Online表单是否可以消息推送？
2.Online表单是否可以发送邮件？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没这功能
