### ISSUE TITLE
微信钉钉扫码登录

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4533]
##### 问题描述：
我这个前端显示二维码  扫码授权以后 他前端弹窗登录失败  控制台 后端 啥错都没有

##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/217407896-d9b5f66d-f137-416d-8b4d-1234615b4a56.png)
![image](https://user-images.githubusercontent.com/121850941/217407915-42655753-7334-46b0-9516-ab53c6f2bd9c.png)
![image](https://user-images.githubusercontent.com/121850941/217407933-470e542c-0dd0-41ab-8147-59a39e283b80.png)
![image](https://user-images.githubusercontent.com/121850941/217407950-280f9a3e-6007-4f13-bf6a-b3adbd60fcb2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
你看一下微信配置的回调地址、秘钥是否匹配。如果debug没有进这个方法，那就说明回调地址不对
