### ISSUE TITLE
vue3版online报表配置数据权限失效问题

### ISSUE THREAD

**Issue by ZhengRongHuan** [jeecgboot/jeecg-boot#4534]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
online报表配置，配置了数据权限只看自己的，发现页面会刷新两次，第一次有带数据权限查询条件，第二次没带数据权限查询条件。点击查询也是没带数据权限查询条件，数据权限不生效。vue2版只会调用一次接口，数据权限生效，vue3版的才有这个问题。

**可能原因：**
/online/cgreport/api/getColumnsAndData/  该接口实现了数据权限控制
/online/cgreport/api/getData/  该接口没实现数据权限控制

**使用的是online在线功能**

##### 截图&代码：
![Y~}141Y{7HO68HN%$VX1OCU](https://user-images.githubusercontent.com/44467852/217412501-7a7fdf96-c735-4cc3-843f-5cc81acc3d9b.png)
![image](https://user-images.githubusercontent.com/44467852/217412701-a8e65618-c11c-4c66-9611-76d89028d053.png)
![71UOM`W R49REZPYGEX5RMQ](https://user-images.githubusercontent.com/44467852/217412537-d6a8e09e-6af1-4c37-ba5e-0edfe9a77071.png)
![image](https://user-images.githubusercontent.com/44467852/217412737-4bd98dae-6504-4d36-a51a-a148e6c4ab08.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by ZhengRongHuan** [comment]
后续会修复吗？

**Comment by tygithub1** [comment]
已修复
