### ISSUE TITLE
网络超时

### ISSUE THREAD

**Issue by zhaozhiqiang2038** [jeecgboot/jeecg-boot#4535]
##### 问题描述：分页写成30条数每页查询列表页面访问超时频率很大，改成默认的10条每页，时而还是会访问超时，
3.4.4中的gatway并没有设置超时时间，这是啥情况

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/26137250/217420875-3d808ed6-3214-4305-b62c-bc5dbcce76ab.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以加下耗时代码，看看耗时哪里了，目前前端axiso有超时设置
