### ISSUE TITLE
控制台输出__COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined 一直加载

### ISSUE THREAD

**Issue by zhangpeng0090** [jeecgboot/jeecg-boot#4536]
前端版本：vue3 版本3.4.3
问题描述：
后端启动正常 前端启动之后 一直加载资源 未显示登录页面
报错如下：
Uncaught ReferenceError: __COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined
 at client.js?v=4a61e190:5

**Comment by zhangdaiscott** [comment]
升级到最新呢

**Comment by zhangpeng0090** [comment]
有没有不升级的方法(特殊原因暂时无法升级)，之前忘记是在哪里加个东西 找不到解决的地址了，所以来求助一下。

**Comment by zhangdaiscott** [comment]
我们也不好分析
