### ISSUE TITLE
多租户模块功能不完善，与http://boot3.jeecg.com地址演示不一致

### ISSUE THREAD

**Issue by Francis-Yang1** [jeecgboot/jeecg-boot#4537]
个人下载版本：3.4.4 + vue3
问题描述：
上述版本项目跑起来后，多租户相关功能不完善；但是按：http://boot3.jeecg.com  地址演示，多租户功能还是较为完善的。

想问  http://boot3.jeecg.com/  该地址演示的源码下载地址是？

**Comment by zhangdaiscott** [comment]
近期会发布
