### ISSUE TITLE
build打包生产环境端口号改变问题

### ISSUE THREAD

**Issue by Jarvisssss** [jeecgboot/jeecg-boot#4539]
##### 问题描述：build打包生产环境端口号改变问题
网站后台应用是http://43.143.142.32:81访问，调的后台地址应该是http://43.143.142.32:16931/qtn-mgr
但是浏览器调试实际地址是http://43.143.142.32:81，请帮忙看一下
接口地址是http://43.143.142.32:16931/qtn-mgr
网站后台http://43.143.142.32:81

##### 截图&代码：
这是nginx配置
![QQ图片20230208164436](https://user-images.githubusercontent.com/39944949/217479360-2009ffbc-67cf-45ad-8514-b620b8e8dd93.png)

![QQ图片20230208164600](https://user-images.githubusercontent.com/39944949/217479676-b05b7d0a-af71-4fb7-8dfb-660598cd7a25.png)
![QQ图片20230208164606](https://user-images.githubusercontent.com/39944949/217479679-6ba55d92-9b50-49ba-8271-06d61026546b.png)

**Comment by zhangdaiscott** [comment]
部署问题自己解决

**Comment by Jarvisssss** [comment]
你好，邮件已收到，我会尽快回复你，谢谢

**Comment by Jarvisssss** [comment]
你好，我用jeecg的上传组件Upload在生产环境报错：
ae.upload.addEventListener is not a function
这是这块的代码
![QQ图片20230209142443](https://user-images.githubusercontent.com/39944949/217734686-1fc932e3-d51b-4cdf-aaf3-354461cad885.jpg)
请相关技术解决一下

**Comment by Jarvisssss** [comment]
> 部署问题自己解决

你好，我用jeecg的上传组件Upload在生产环境报错：
ae.upload.addEventListener is not a function
这是这块的代码
![QQ图片20230209142443](https://user-images.githubusercontent.com/39944949/217736685-452926d3-b2a4-4759-84f1-2b465efa0bc3.jpg)

请相关技术解决一下
