### ISSUE TITLE
请问online在线表单支持数据加解密功能吗

### ISSUE THREAD

**Issue by a792883583** [jeecgboot/jeecg-boot#4540]
##### 版本号：
前端：3.4.4
后端：3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
请问online在线表单支持加解密功能吗？能将加密后的数据存放在数据库，前端在列表展示的时候只能看到密文，在查看详情或者编辑的时候才能看到加密前的内容。请问online在线表单开发能做到这个功能吗？感谢回复

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时不支持
