### ISSUE TITLE
Online在线功能 jeecg_database.properties

### ISSUE THREAD

**Issue by biteDance** [jeecgboot/jeecg-boot#4542]
##### 版本号：
3.4.3
Online在线功能
##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
jeecg_database.properties 配置文件可以不写死吗  设置为自动获取

##### 截图&代码：

diver_name=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/jeecg-boot?useUnicode=true&characterEncoding=UTF-8
username=root
password=root
database_name=jeecg-boot

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持动态
