### ISSUE TITLE
online表单怎么通过js增强提示用户处理完或者sql增强

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4543]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

online表单
1.通过js增强或者sql增强，用户点击按钮顶部提示消息？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/217734105-f1deef11-8ac7-43bb-a0a5-3d7d52fe906c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
js可以自己加提示，java增强没有
