### ISSUE TITLE
插入自增表时，报 Out of range value for column 'id' at row 1

### ISSUE THREAD

**Issue by liuqing0504** [jeecgboot/jeecg-boot#4548]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by newcardriver** [comment]
![image](https://user-images.githubusercontent.com/44741731/218316121-d405bc5d-d085-4488-8f56-92bc3eef0644.png)
引用来源：https://blog.csdn.net/qq_41070393/article/details/115556299
可以根据以上情况检查一下。
