### ISSUE TITLE
解密方法PasswordUtil.decrypt疑问

### ISSUE THREAD

**Issue by FireQinbo** [jeecgboot/jeecg-boot#4549]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/32409091/218029602-eb4c0321-217a-4d08-ad53-b473f15d2af0.png)
![image](https://user-images.githubusercontent.com/32409091/218029703-1f706396-d50a-4ee8-b649-b7e5b9e2073e.png)
![image](https://user-images.githubusercontent.com/32409091/218029755-37c225d0-83fc-4608-8198-5963413d2806.png)

**Comment by newcardriver** [comment]
因为在进行添加用户的时候就用的是username。
![image](https://user-images.githubusercontent.com/44741731/218315473-e84310ff-323d-4701-9a5e-9261cd884323.png)
