### ISSUE TITLE
如何让自定义的用户表直接登录系统？

### ISSUE THREAD

**Issue by baileixin** [jeecgboot/jeecg-boot#4553]
##### 问题描述：
Online在线功能
做一个学生管理系统，创建了学生、教师表，它们的字段都包含账号、密码，请问jeecgboot可以让这两张表里存在的角色直接登录系统吗？
同时要求学生、教师这两个角色的增删改查模块分开，如果将学生和教师的数据都一个个录入jeecgboot自带的角色管理里，是可以登录系统，但这样就没办法用代码生成器生成他们的增删改查模块了，请问该如何解决？

**Comment by zhangdaiscott** [comment]
你可以写java增强，把学生和教师表的数据，插入到用户表里

**Comment by baileixin** [comment]
您好，感谢回复，如果像您所说的这样，用一个按钮把学生、教师表的数据插入到用户表里，那么当这两张表的数据发生变化时，是否也需要手动地（比如写一个同步按钮让它们和系统用户表进行同步？初学者真心求教，盼望回复

**Comment by baileixin** [comment]
> 您好，感谢回复，如果像您所说的这样，用一个按钮把学生、教师表的数据插入到用户表里，那么当这两张表的数据发生变化时，是否也需要手动地（比如写一个同步按钮让它们和系统用户表进行同步？初学者真心求教，盼望回复



> 你可以写java增强，把学生和教师表的数据，插入到用户表里

您好，感谢回复，如果像您所说的这样，用一个按钮把学生、教师表的数据插入到用户表里，那么当这两张表的数据发生变化时，是否也需要手动地（比如写一个同步按钮让它们和系统用户表进行同步？初学者真心求教，盼望回复

**Comment by zhangdaiscott** [comment]
是的，既然同步就得双向，增改都得同步
