### ISSUE TITLE
自定义弹窗不显示

### ISSUE THREAD

**Issue by it-xhp** [jeecgboot/jeecg-boot#4557]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
自定义弹窗不显示

##### 截图&代码：
![image](https://user-images.githubusercontent.com/96649838/218383314-13304b45-2bfe-47e0-8f35-6575aa8f769b.png)
![image](https://user-images.githubusercontent.com/96649838/218383396-17b2ac1c-4489-4ba4-a5a8-b3a818e7c229.png)
![image](https://user-images.githubusercontent.com/96649838/218383513-9bcfa92c-191a-490c-9c05-372d188769dc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时不支持
