### ISSUE TITLE
<j-editable-table 列表换行显示

### ISSUE THREAD

**Issue by yimogithub** [jeecgboot/jeecg-boot#4560]
##### 问题描述：
j-editable-table 列表数据怎么设置换行显示（不要过长裁剪，也不要一行全显示）

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44832000/218399991-89348930-d30f-4248-b097-d8d9429de319.png)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044028
