### ISSUE TITLE
访问http://服务器ip:9080/xxl-job-admin/页面显示空白

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4561]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
访问http://服务器ip:9080/xxl-job-admin/页面显示空白

##### 截图&代码：
![image](https://user-images.githubusercontent.com/89574140/218406371-6d1415c3-4bdd-444a-8d23-1f607bfcf23e.png)
![image](https://user-images.githubusercontent.com/89574140/218406530-004dba56-d799-46ba-a1d8-b67a1152c6d3.png)
![image](https://user-images.githubusercontent.com/89574140/218406678-0f6f39ad-1fbe-4a0c-bfd6-457c5424d950.png)
![image](https://user-images.githubusercontent.com/89574140/218406838-633d9b87-17ba-45ab-bf94-ddcd12510029.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你需要先访问下gateway网关，就有数据了

**Comment by baiqingxia888** [comment]
我已经网文过网关了，还是空白页面啊




在 2023-02-13 16:32:44，"JEECG" ***@***.***> 写道：

你需要先访问下gateway网关，就有数据了

**Comment by baiqingxia888** [comment]
但是我访问过网关，也还是空白。
![image](https://user-images.githubusercontent.com/89574140/218412726-29c9120f-7cab-4791-98d5-9246c3db77eb.png)
![image](https://user-images.githubusercontent.com/89574140/218412766-88f30022-ed4e-4020-bb48-d853bd1695a7.png)
