### ISSUE TITLE
Online报表配置，SQL不能调用存储过程?

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4562]
##### 版本号：

最新版
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

Online报表配置，SQL不能调用存储过程?
我想在报表里面执行存储过程语句，有什么办法可以解决拿到这个存储过程的数据？
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂时不做这功能，可以考虑用积木报表
