### ISSUE TITLE
Spring Boot Admin 服务离线

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4563]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
为什么服务都启动的好好的，但是有两个服务显示离线？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/89574140/218413943-a1a5ac77-4546-4161-b901-f51da1f939e5.png)
![image](https://user-images.githubusercontent.com/89574140/218414098-50fb3974-6525-48d3-9405-7cf172a48fde.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个注释放开就好了，但放开有安全风险
![image](https://user-images.githubusercontent.com/3162115/218416801-db95e1d8-fc79-4265-939a-e45ac4aacf53.png)

**Comment by baiqingxia888** [comment]
我只有system和demo的项目是离线，放开这个配置，这两个服务就都上线了吗？

**Comment by zhangdaiscott** [comment]
en
