### ISSUE TITLE
Sentinel服务访问控制台空白

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4564]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Sentinel服务访问控制台空白，调用过gateway服务，依然无用。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/89574140/218418179-50307197-7913-4434-a7ca-86e9fc62c678.png)
![image](https://user-images.githubusercontent.com/89574140/218418200-9270d895-4a11-4c48-b90b-ec84112c2d81.png)
![image](https://user-images.githubusercontent.com/89574140/218418211-b004bcec-9909-4484-b001-198ac6b57a36.png)
![image](https://user-images.githubusercontent.com/89574140/218418226-a55c9549-922a-4a76-bddf-0d7dc6e82a7e.png)
![image](https://user-images.githubusercontent.com/89574140/218418252-0d125d43-0d82-4519-b7cf-393fccf6421e.png)
![image](https://user-images.githubusercontent.com/89574140/218418273-248ab9d5-2a33-4da2-a63a-339adde52099.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2350293

![image](https://user-images.githubusercontent.com/3162115/218693848-b0740526-6821-403f-9f65-7bc07989fb30.png)
