### ISSUE TITLE
手机号登录 和账号密码登录

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4566]
##### 问题描述：
用小红的手机号登录啥也看不见 小红账号密码登录有权限

##### 截图&代码：
![ZA7%2GATS4CSQF~ VRLPWZ6](https://user-images.githubusercontent.com/121850941/218615203-9e667d39-281f-47f0-9b5d-304fcf361fa9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个猜不到，你得看看你怎么授权的
