### ISSUE TITLE
提示:很抱歉,资源未找到

### ISSUE THREAD

**Issue by yuafei** [jeecgboot/jeecg-boot#4570]
##### 问题描述：
新建module, 不以 org.jeecg 开头的包路径，yml中的mybatis plus 设置已修改，MybatisPlusSaasConfig扫描路径也添加上了，菜单授权也授过了， online在线测试也没问题，生产代码配置菜单后就出现了这样的问题，清除缓存以及退出登录也试过了，就是不行，请问是哪个地方问题？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/78579012/218667754-5a9a2077-ef17-4b26-892d-e43907687e07.png)
![image](https://user-images.githubusercontent.com/78579012/218667813-da963631-cea7-48f0-b9ec-28f0fc6399a2.png)
![image](https://user-images.githubusercontent.com/78579012/218671886-71c6f59b-85bc-40ec-b563-30c74ca7968c.png)
![image](https://user-images.githubusercontent.com/78579012/218672091-9e32da55-2528-4295-94e0-2cfc7bf0c51f.png)
![image](https://user-images.githubusercontent.com/78579012/218672227-ac3ce589-8c4e-4165-82b4-459b24a71284.png)
![image](https://user-images.githubusercontent.com/78579012/218671464-0c222a41-1227-48e9-a87f-759983369172.png)
![image](https://user-images.githubusercontent.com/78579012/218667927-d6c63268-881e-4461-b4b6-4f490437c30f.png)
![image](https://user-images.githubusercontent.com/78579012/218668057-4f70ad0a-75fe-4b3d-8f87-166b43f54e63.png)
![image](https://user-images.githubusercontent.com/78579012/218668234-51844c02-559a-41b6-9345-dabaad57266e.png)
![image](https://user-images.githubusercontent.com/78579012/218668340-4a94c74d-c7b6-409e-822d-7f671968d7c3.png)
![image](https://user-images.githubusercontent.com/78579012/218668399-4456dcb8-ff92-4a4e-a43e-c60eb0c58536.png)
![image](https://user-images.githubusercontent.com/78579012/218668595-6a03efe0-1b6d-447d-872f-d5aaed272c36.png)
![image](https://user-images.githubusercontent.com/78579012/218669764-3dbea545-5134-40ad-bc70-c9dae58eea10.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by mangdehuang** [comment]
重启后端了吗？

**Comment by mangdehuang** [comment]
我重启之后可以了

**Comment by yuanfei726** [comment]
> 重启后端了吗？
重启过了，也不行，重启，清除缓存都试了，不行，实在是找不出毛病了才来求助了

**Comment by mangdehuang** [comment]
看一下那个  自动生成的sql文件

**Comment by zhangdaiscott** [comment]
启动类，加额外的路径扫码地址了吗
https://github.com/jeecgboot/jeecg-boot/issues/2331

**Comment by yuafei** [comment]
> 启动类，加额外的路径扫码地址了吗 #2331

在哪加？

**Comment by yuafei** [comment]
谢谢，确实是启动类没有添加扫描地址
