### ISSUE TITLE
swagger微服务使用

### ISSUE THREAD

**Issue by eyuan** [jeecgboot/jeecg-boot#4571]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
Gateway的swagger中仅有jeecg-system服务，其他服务没有列出来。
检查是因为nacos检查健康状态过滤了。
private Boolean checkRoute(String routeId) {
        Boolean hasRoute = false;
        try {
            NamingService naming = NamingFactory.createNamingService(serverAddr);
            List<Instance> list = naming.selectInstances(routeId, true);
            if (ObjectUtil.isNotEmpty(list)) {
                hasRoute = true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return hasRoute;
    }
但从nacos的8848 web端进去一切正常，各服务都健康，请问是哪里配置错误造成的？
将checkRoute返回TRUE，knife报错。
为什么其他微服务nacos web显示正常，但代码检查却不通过？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1910132/218681817-b6717e5b-a076-4a8e-9b3f-dbb91b72a5b0.png)
![image](https://user-images.githubusercontent.com/1910132/218681873-72408e02-ede7-435e-9427-142858d8a439.png)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/4597
