### ISSUE TITLE
Online 表单自定义按钮+js增强实现自定义弹框

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4572]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
弹框默认打开的是当前表单，然后再默认弹出的框底部添加按钮，因为当前弹出的框是编辑内容的弹框，不知道能不能在底部添加按钮？
我是根据文档来的，但是文档没有说能在编辑弹框底部添加按钮
##### 截图&代码：

默认自定义弹框的图片
![image](https://user-images.githubusercontent.com/19221237/218921699-cef0ae74-c076-4a09-bb4f-9d64c31bc800.png)

新增弹框的图片
![image](https://user-images.githubusercontent.com/19221237/218921814-c99aea5e-4126-43b7-bea0-187f4886b93f.png)

如果能没有此功能希望后期新增这个
![image](https://user-images.githubusercontent.com/19221237/218922468-0cbc7f26-f0f4-4168-93b8-fc2d367c56a1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
开源版本暂时不支持弹窗
