### ISSUE TITLE
同步钉钉用户显示类型引用转换异常

### ISSUE THREAD

**Issue by DaiMagic** [jeecgboot/jeecg-boot#4573]
##### 版本号：
3.4.4

##### 问题描述：
同步钉钉用户显示类型引用转换异常，TypeReference转换有3层的都会有这个问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/22704808/218951597-f76ef8b4-1af5-44f0-910d-a6613e31bddf.png)

**Comment by 1298191366** [comment]
这个当前

**Comment by DaiMagic** [comment]
您的邮件已收到，稍后给您回复

**Comment by 1298191366** [comment]
你是怎样调用的。我调用没发现有问题
