### ISSUE TITLE
linux环境启动后端报错

### ISSUE THREAD

**Issue by github361470** [jeecgboot/jeecg-boot#4575]
##### 版本号：
后端 jeecg-boot 3.4.4

##### 问题描述：
后端部署在linux启动，启动中显示定时任务报错查不到表，但是我mysql已经正常启动，可以连接了,表也是存在的
这个问题在本地windows启动不会出现，请帮忙解答下，非常感谢！

##### 截图&代码：
![SLFJO1J{(C W{ZF0XE4HK6X](https://user-images.githubusercontent.com/55338605/218964221-5765d3d1-4180-4f9a-98de-c92abdb1ab43.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写
