### ISSUE TITLE
数据权限：相同的功能不同角色的人看到不一样的数据如何处理

### ISSUE THREAD

**Issue by weidadong** [jeecgboot/jeecg-boot#4576]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
有一个功能（销售记录），现在有3个角色：总监、经理、销售。现在有个需求，他们都在权限进入这个页面，但是要求：
1、总监 	      能看所有的数据
2、区域经理  能看到他下级销售录入的数据 
3、销售 	      只能看到自己录入的数据

现有的数据权限不能获取当前用户的角色编码
![image](https://user-images.githubusercontent.com/64127503/218987476-dbd1bb3c-fcae-489f-92fd-1919d328a69d.png)

请问该如何实现这个需求

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044045

**Comment by weidadong** [comment]
...
