### ISSUE TITLE
微信 Illegal code [WECHAT_OPEN]

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4577]
##### 版本号：
vue2

##### 问题描述：
所有的都配好了 本地测试不行 是什么原因呢

##### 截图&代码：
![image](https://user-images.githubusercontent.com/121850941/219230922-042d9d7b-208a-45b4-8019-b91db92534ae.png)

![image](https://user-images.githubusercontent.com/121850941/219230953-4b9e6d9a-f372-4959-a443-1a4d09031777.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
这个提示就是`client-id`及 `client-secret`没有配置，或者不匹配
![image](https://user-images.githubusercontent.com/30997828/221360091-9a31bf62-961b-497e-a7d4-45fda169c7c5.png)

**Comment by FlawlessChen** [comment]
我也是这个问题，请问你解决了吗

**Comment by zhangdaiscott** [comment]
企业微信打算放弃了，现在限制太多，基本很难对接
