### ISSUE TITLE
演示代码与源码代码功能不统一

### ISSUE THREAD

**Issue by chenruizhi-github** [jeecgboot/jeecg-boot#4583]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/63765507/219344419-affd6b78-0d0d-47e4-b6b7-ec8c315ad1c7.png)
![image](https://user-images.githubusercontent.com/63765507/219344521-0eb40db7-0687-4997-bef8-0bfa6453fc19.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
看项目的功能介绍

**Comment by chenruizhi-github** [comment]
> 

你的意思是菜单本来就不统一吗？我看项目的功能介绍也没有哪里说关于菜单少了的事情啊

**Comment by chenruizhi-github** [comment]
> 看项目的功能介绍

或者是我哪里没看到说明菜单的文档   可以发个链接给我看看吗
