### ISSUE TITLE
谷歌50版本不兼容（在不能升级浏览器的前提下）

### ISSUE THREAD

**Issue by StreakerHan** [jeecgboot/jeecg-boot#4587]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

前端项目部署至云服务器之后，在谷歌浏览器（版本v50.*）上访问点击登录之后无法跳转至主页。
##### 截图&代码：

错误信息：Uncaught SyntaxError: Unexception token *

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
具体版本号截图

**Comment by StreakerHan** [comment]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/30434079/219593319-4f56f7f7-55e7-4479-be59-1886d2402729.png">
![image](https://user-images.githubusercontent.com/30434079/219593597-9b29f5e5-8204-4f0c-99b1-14e468020823.png)
浏览器下载地址[](https://www.slimjet.com/chrome/download-chrome.php?file=win%2Fchrome64_50.0.2661.75.exe)

**Comment by zhangdaiscott** [comment]
版本太老了吧

**Comment by StreakerHan** [comment]
是的。。。客户比较特殊，内网环境。如没有解决方案就算了，辛苦！
