### ISSUE TITLE
online表单编辑页面是否应该显示默认值？

### ISSUE THREAD

**Issue by tsgdnwxg** [jeecgboot/jeecg-boot#4591]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
新增有默认值是对的，编辑肯定是数据库是什么值，显示什么值
