### ISSUE TITLE
登录的时候，查一遍数据字典是多余的吗

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#4592]
##### 版本号：

3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue3

##### 问题描述：

登录的时候查了一遍数据字典 sysAllDictItems
getUserInfo 的时候又查了一遍，
我发现登录的时候查的数据字典去掉 也一样运行
会有什么影响吗

##### 截图&代码：

![image](https://user-images.githubusercontent.com/3311840/219991755-18020d64-9e1a-473b-8e49-3eaea62d7279.png)
![image](https://user-images.githubusercontent.com/3311840/219991807-9f5d0f81-d593-47dc-82c6-66c129709552.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
一次性加载到前端缓存，提升性能

**Comment by qinghechaoge** [comment]
> 

登录后查的根本没有往缓存里放
