### ISSUE TITLE
文件上传失败

### ISSUE THREAD

**Issue by WebFE0415** [jeecgboot/jeecg-boot#4593]
##### 版本号：
2.4.6（发布日期：20210816）

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
上传文件失败，后端报错。
代码是用Online表单开发生成的，前后端上传代码都没有修改。发现生成的代码上传失败以后，就去自带的菜单，常见案例-自定义组件里面下方上传文件进行测试，也是上传失败。麻烦大佬看看

##### 截图&代码：
前端报错截图：
![image](https://user-images.githubusercontent.com/63940128/219995259-c68c3daa-3826-4bfd-8316-ae2422352f4b.png)
后端报错截图：
![image](https://user-images.githubusercontent.com/63940128/219995340-44574ca9-fae9-469a-ac24-0efc99ab1194.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
minio账号配置正确了吗

**Comment by WebFE0415** [comment]
> minio账号配置正确了吗

大佬，这个需要配置minio吗？之前的我也没配置能上传

**Comment by WebFE0415** [comment]
> minio账号配置正确了吗

大佬，这个minio怎么配置呢，能不能给个帖子我看看，麻烦了。

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043970

**Comment by WebFE0415** [comment]
> http://doc.jeecg.com/2043970

感谢大佬
