### ISSUE TITLE
角色管理的权限配置，保存首页配置提示出错，经过排查发现是SysRoleIndex 类没有无参构造函数

### ISSUE THREAD

**Issue by GitACDreamer** [jeecgboot/jeecg-boot#4594]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
```
JSON parse error: Cannot construct instance of org.jeedca.modules.svstem.talthouah at least one Creator exists): cannot deserialize from Object value (no delegateor property-based Creator); nested exception iscEn astem soatndan mmaepun at nt sneoge me  e a s  e tn t ae togappt-ea(org.springframework.util.StreamUtils$NonClosinglnputStream); line: 1, column: 2]
```

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19402747/220241506-41e35e78-294c-4a66-8c6b-7e5778f84964.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
已修改
