### ISSUE TITLE
代码生成器生成的代码能用于其他项目吗？不是jeecg后端项目

### ISSUE THREAD

**Issue by Eason0803** [jeecgboot/jeecg-boot#4595]
##### 版本号：
3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
代码生成器生成的代码能用于其他项目吗？不是jeecg后端项目

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Eason0803** [comment]
如果可以的话，是否有使用教程？

**Comment by zhangdaiscott** [comment]
不支持
