### ISSUE TITLE
企微ACCESS_TOKEN替换后出现无效的token问题

### ISSUE THREAD

**Issue by a616707902** [jeecgboot/jeecg-boot#4596]
##### 版本号：
3.4.4

##### 问题描述：
在请求企微API时，调用地址通过替换的方式会出现错误替换，如：access_token中包含ID时，通过ID查询的时候，会将access_token中的ID替换成参数值。造成请求一直无效token错误。

##### 截图&代码：
 public static List<Department> getDepartmentById(String depId, String accessToken) {
        logger.info("[JW_DEPARTMENT] getDepartmentById param:accessToken:{}", new Object[]{accessToken});
        String url = department_list_url_get.replace("ACCESS_TOKEN", accessToken).replace("ID", depId);
        JSONObject response = HttpUtil.sendPost(url);
        logger.info("[JW_DEPARTMENT] getDepartmentById response:{}", new Object[]{response.toJSONString()});
        return response.getJSONArray("department").toJavaList(Department.class);
    }

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
这个企业微信已经被禁用掉了，目前有只能获取到部门id
![image](https://user-images.githubusercontent.com/30997828/222674930-63ac1046-b1d0-42f5-b7f8-5e4dfdaae2fe.png)

**Comment by zhangdaiscott** [comment]
企业微信接口都停了， 后期此功能可能得作废了
