### ISSUE TITLE
spring cloud gateway actuator等端点未授权访问漏洞

### ISSUE THREAD

**Issue by yang105** [jeecgboot/jeecg-boot#4597]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
这个漏洞好像没有解决。我通过url 可以直接访问actuator的相关接口。
通过 POST 网关ip端口/actuator/gateway/routes/ 执行恶意代码，然后refresh，服务就报错了。
通过 GET  网关IP端口/actuator/env，还能获取到服务的相关配置信息

##### 截图&代码：
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: true
  endpoint:
    health:
      show-details: ALWAYS
这里暴露了actuator的所有端点，但是没有做任何安全防护措施，比如引入spring security之类

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
默认不要放开
![image](https://user-images.githubusercontent.com/3162115/221069689-39598c26-30d7-4325-b6dc-ea54083b8d2a.png)

**Comment by yang105** [comment]
我上面说的问题是已经基于图中的配置已经是注释掉，没有放开的了。在这个情况下这个漏洞还是能复现
@zhangdaiscott

**Comment by yang105** [comment]
> 默认不要放开 ![image](https://user-images.githubusercontent.com/3162115/221069689-39598c26-30d7-4325-b6dc-ea54083b8d2a.png)
我上面说的问题是已经基于图中的配置已经是注释掉，没有放开的了。在这个情况下这个漏洞还是能复现 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
没有放开，shrio会拦截的，你是怎么复现的

**Comment by yang105** [comment]
> 没有放开，shrio会拦截的，你是怎么复现的

通过GET 网关IP端口/actuator/env， 比如GET http://localhost:9000/actuator/env

**Comment by zhangdaiscott** [comment]
那你这是访问的gateway的吧

**Comment by yang105** [comment]
> 那你这是访问的gateway的吧 把gateway的参数配置注释掉

对。从网关进来的。gateway的什么参数配置？
原因如下：
management:
health:
mail:
enabled: false
endpoints:
web:
exposure:
include: "*"
health:
sensitive: true
endpoint:
health:
show-details: ALWAYS
这里暴露了actuator的所有端点，但是没有做任何安全防护措施，比如引入spring security之类

**Comment by yang105** [comment]
我自己做的修改如下：
management:
  health:
    mail:
      enabled: false
  endpoints:
    gateway:
      enabled: false

**Comment by zhangdaiscott** [comment]
你的修改没问题
