### ISSUE TITLE
上传速度问题

### ISSUE THREAD

**Issue by aliaizhetaozi** [jeecgboot/jeecg-boot#4598]
##### 版本号：
所有版本

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用系统内的上传功能，直接上传到服务器，上传的速率很慢，直接上传文件到服务器的上传下载速度都是正常的，修改了yml配置也没有任何上传速度的提升

##### 截图&代码：
![image](https://user-images.githubusercontent.com/30401919/220552994-828acc7c-0ea5-467d-af75-6dec71e103c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个速度不清楚，跟你的nginx部署有关？
