### ISSUE TITLE
打包部署后不能访问后台服务

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecg-boot#4601]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/30968914/220687860-f5fc2403-9e6f-436d-957b-e2f940e2accf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
肯定还是部署问题，你发这个截图没有帮助
