### ISSUE TITLE
微服务字典翻译有实现方式吗

### ISSUE THREAD

**Issue by tony2y** [jeecgboot/jeecg-boot#4602]
##### 问题描述：
1.目前字典表是在system服务中，比如其它服务（order）要调用system中的字典数据，怎么翻译？
2.不同服务直接有关联关系，比如order服务表中保存了用户ID，这时候就需要翻译用户名称返回给前端，这种跨服务的查表翻译有实现放不？
目前的@Dict里面好像就是只能处理当前服务的。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
关于微服务的翻译好像做了，DictAspect这个是在底层的，只有你的接口符合分页返回结果，加了对应的注解就能翻译

**Comment by tony2y** [comment]
好的 ，我明天验证一下

**Comment by zjarlin** [comment]
请问微服务的字典翻译需要改动哪些类,项目因为使用了老版本的代码不支持,迁移太麻烦,请教下替换哪些文件就好了
