### ISSUE TITLE
字段权限配置可见性无效

### ISSUE THREAD

**Issue by geosmart** [jeecgboot/jeecg-boot#4606]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1. Online表单开发-权限控制，开启字段A的列表可见性控制，功能测试正常，列表中字段A不见了
2. Online表单开发-角色授权，确认角色A没有开启可见性
3. 角色A的用户重新登录，还是能看到字段A

为什么功能测试的效果和实际的效果不一致？

##### 截图&代码：
没有给任何角色授权
![未开启授权](https://user-images.githubusercontent.com/3156608/221067767-27464dc0-8d77-4e5b-807f-884d24aacba9.jpg)

Online表-功能测试中，字段【订单金额】不可见，是对的
![ok](https://user-images.githubusercontent.com/3156608/221067752-e3bb2b09-c0ef-47b9-8f37-4eececda694a.jpg)

其他角色登录，还是能看到【订单金额】这个字段
![error](https://user-images.githubusercontent.com/3156608/221067783-6accce80-4668-4460-afc1-1b12339091b7.jpg)

也就是说配置没有生效。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你指的是代码生成后？

**Comment by geosmart** [comment]
> 你指的是代码生成后？

是的，代码生成后，配置菜单点进去，字段权限（是否可见，是否启用）无效

**Comment by zhangdaiscott** [comment]
代码生成后，权限需要重新配置，用法跟online不一样

**Comment by cyberfeipunk** [comment]
有没有代码生成后字段权限的配置方法？
