### ISSUE TITLE
设置按钮权限后页面访问不到

### ISSUE THREAD

**Issue by liu2582497403** [jeecgboot/jeecg-boot#4607]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

设置 v-has=“‘权限代码’” 后页面访问不到

##### 截图&代码：

```html
<a-button type="primary" @click="handleAdd" v-has="'demo:add'" preIcon="ant-design:plus-outlined"> 新增</a-button>
```
加入v-has后，在菜单管理中添加权限代码

[![菜单管理添加权限代码](https://s1.ax1x.com/2023/02/24/pSzJcT0.jpg)](https://imgse.com/i/pSzJcT0)

给角色授予权限

[![授予角色权限](https://s1.ax1x.com/2023/02/24/pSzJHTx.jpg)](https://imgse.com/i/pSzJHTx)

重启前后端服务，清除缓存，重新登录，打开页面后

[![页面](https://s1.ax1x.com/2023/02/24/pSzJv1e.jpg)](https://imgse.com/i/pSzJv1e)

不清楚是什么问题，都是按照官方文档一步步设置的

http://doc.jeecg.com/2044038

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看代码是不是报错了
