### ISSUE TITLE
Online代码生成一对多的问题

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4608]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
为什么生成代码后，前端不带详情呢？是我的版本不够新？
还是前端的详情需要自己写？后端接口是生成了，但是前端没调用以及没代码？

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/221116632-79690226-91b6-4f5e-b74f-540d853d6e4e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
online在线的效果与代码生成不完全一致
