### ISSUE TITLE
云表单设页面属性设置了showLength 列长度值无效

### ISSUE THREAD

**Issue by 572936554** [jeecgboot/jeecg-boot#4610]
##### 版本号："dependencies": {
    "@antv/data-set": "^0.11.4",
    "@jeecg/antd-online-mini": "2.4.0-beta4",
    "@tinymce/tinymce-vue": "^2.1.0",
    "@toast-ui/editor": "^2.1.2",
    "ant-design-vue": "^1.7.2",
    "area-data": "^5.0.6",
    "axios": "^0.18.0",
    "clipboard": "^2.0.4",
    "codemirror": "^5.46.0",
    "cron-parser": "^4.2.1",
    "dayjs": "^1.8.0",
    "dom-align": "1.12.0",
    "echarts": "^5.0.0",
    "element-resize-detector": "^1.2.1",
    "element-ui": "^2.15.2",
    "enquire.js": "^2.1.6",
    "js-cookie": "^2.2.0",
    "lodash.get": "^4.4.2",
    "lodash.pick": "^4.4.0",
    "md5": "^2.2.1",
    "nprogress": "^0.2.0",
    "signature_pad": "^4.0.1",
    "throttle-debounce": "^3.0.1",
    "tinymce": "^5.3.2",
    "viser-vue": "^2.4.8",
    "vue": "^2.6.10",
    "vue-area-linkage": "^5.1.0",
    "vue-cropper": "^0.5.4",
    "vue-i18n": "^8.7.0",
    "vue-loader": "^15.7.0",
    "vue-ls": "^3.2.0",
    "vue-pdf": "^4.2.0",
    "vue-photo-preview": "^1.1.3",
    "vue-print-nb-jeecg": "^1.0.9",
    "vue-router": "^3.0.1",
    "vue-splitpane": "^1.0.4",
    "vuedraggable": "^2.20.0",
    "vuex": "^3.1.0",
    "vxe-table": "2.9.13",
    "vxe-table-plugin-antd": "1.8.10",
    "xe-utils": "2.4.8"
  },

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
在Online表单中设置页面属性  扩展参数为{"showLength":20}  在页面中不生效

##### 截图&代码：
![image](https://user-images.githubusercontent.com/35718169/221145156-9796ce54-003a-4b90-b7c5-a8cd22cd4fe3.png)
 

![image](https://user-images.githubusercontent.com/35718169/221145317-990e5e74-1a78-417d-b6d7-c90fefd82767.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个无效了vue3版本
