### ISSUE TITLE
IE11浏览器打开一直停留在loading 解决办法是什么

### ISSUE THREAD

**Issue by TonyChenChina** [jeecgboot/jeecg-boot#4613]
##### 版本号：
3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
IE兼容问题 IE11浏览器打开一直停留在loading

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28721391/221460124-d5c97057-98e9-4b4b-88ff-b06d33e4b29a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
去掉qinkun的代码
