### ISSUE TITLE
路由过滤无法生效

### ISSUE THREAD

**Issue by shuofeng01** [jeecgboot/jeecg-boot#4614]
##### 版本号：
4.3.3

##### 前端版本：vue3版？还是 vue2版？
后端jeecgboot

##### 问题描述：
配置shiro的filter anon之后，不起作用

##### 截图&代码：

![image](https://user-images.githubusercontent.com/126216363/221469103-da3aa580-9946-4be6-abe9-8eb37f040e9c.png)

![image](https://user-images.githubusercontent.com/126216363/221470296-22861fa1-f387-4c7c-b9c4-546f505ddd97.png)

![image](https://user-images.githubusercontent.com/126216363/221470017-5704f630-60de-4624-8153-02a3bd83fd94.png)

感谢各位大大的帮助！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1369521908** [comment]
你好  请问你是怎么解决的呀?

**Comment by 1369521908** [comment]
可以参考下解决方法
https://github.com/jeecgboot/jeecg-boot/issues/4786
