### ISSUE TITLE
我想将Online表单开发中列表操作中的删除功能去掉，应该如何修改

### ISSUE THREAD

**Issue by Sheshuaishuai** [jeecgboot/jeecg-boot#4616]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我想将Online表单开发中列表操作中的删除功能去掉，应该如何修改

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41417216/221722968-89ce58fc-6d01-48fb-a990-ad17bcb9403d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改不了
