### ISSUE TITLE
定时任务执行丢失（常见问题52无法解决，任务100%没执行）

### ISSUE THREAD

**Issue by Ambition26** [jeecgboot/jeecg-boot#4618]
##### 问题描述：
每天凌晨1点执行定时任务，当前项目是微服务模式，通过feigh调用另一个模块执行业务。
表达式：0 0 1 * * ?
【任务每一次执行会有日志输出，任务100%绝对没有执行】
已排查项目中所有可能执行失败的情况，均无法解决。

排查情况如下：
1.常见问题52指的是多机器连同一个库，任务已执行但不知道哪个机器执行。
结果：这个数据库只有此项目连接，并且只部署了一个system的jar包，不存在多机器情况
并且任务绝对未执行，如果执行了会有日志输出，而且在另一个模块也没有执行结果

2.可能是cron表达式不对？
将任务改成了10s执行一次，测试一小时后，任务执行正常。
改为1小时执行一次后，任务只在接下来的两个小时执行了，然后中断了，一次也没执行（0 0 0/1 * * ? *）

3.自己本机写了的demo跑了一天，执行时间5s、10s、1min、30min、1hour、2hour，任务执行均正常

4.任务配置绝对正常，每次手动点击界面的执行一次，任务执行正常

##### 截图&代码：
任务截图：
![gegrerg](https://user-images.githubusercontent.com/59362509/222024608-5fdb0402-e635-4bad-ac75-13975c9f396e.png)
本机测试任务demo截图
![微信截图_20230301100237](https://user-images.githubusercontent.com/59362509/222025696-9bdf45c3-5ca7-4c7c-a43c-3527be91c04b.png)
前端任务配置截图
![1](https://user-images.githubusercontent.com/59362509/222026125-fe3e6e75-43e5-41d4-a778-5d56d2bc4953.png)

此开源项目的所有有关定时任务的issues（github和gitee）以及常见问题以及论坛都浏览了一遍，未找到解决方案，请作者帮忙排查下（解决方案肯定不是常见问题52）

**Comment by Ambition26** [comment]
![1](https://user-images.githubusercontent.com/59362509/222029610-69a399e3-bc56-462b-916a-3a76772f5e00.png)

**Comment by zhangdaiscott** [comment]
路径改成了自己的，配置额外的扫码路径了吗，也就是你的类注入到spring容器里面了吗

**Comment by Ambition26** [comment]
> 

肯定是扫描i到了啊，您没看issues的详细问题描述吧？
任务是在执行了三四次后停止了执行，并且表中的状态字段变成了Error
1.您给的回答是扫描路径是否配置了？
感觉和问题毫不相关？ 如果根本就没扫描到，任务应该是一次也不会执行的，现在状况是执行了几次后自动终端！！！

麻烦您有时间的情况下帮忙看下

**Comment by Ambition26** [comment]
> 路径改成了自己的，配置额外的扫码路径了吗，也就是你的类注入到spring容器里面了吗

肯定是扫描i到了啊，您没看issues的详细问题描述吧？
任务是在执行了三四次后停止了执行，并且表中的状态字段变成了Error
1.您给的回答是扫描路径是否配置了？
感觉和问题毫不相关？ 如果根本就没扫描到，任务应该是一次也不会执行的，现在状况是执行了几次后自动终端！！！

麻烦您有时间的情况下帮忙看下

**Comment by niezixu** [comment]
遇到同样的问题，到现在还是没有找到解决办法

**Comment by Ambition26** [comment]
> 遇到同样的问题，到现在还是没有找到解决办法

我当时的场景问题解决掉了，可以加我的q：3398077610，共同探讨学习下，希望对您有所帮助
