### ISSUE TITLE
nacos权限认证漏洞依旧未解决

### ISSUE THREAD

**Issue by Aricalone** [jeecgboot/jeecg-boot#4619]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/74175532/222039310-1695a545-00e9-47ab-abe5-faeff0863a18.png)

**Comment by zhangdaiscott** [comment]
gateway层面关闭 相关的功能
![image](https://user-images.githubusercontent.com/3162115/222952120-b2001aec-9606-4436-b465-20164794b7c5.png)
