### ISSUE TITLE
生成的表格里的下拉框条件怎么动态赋值

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecg-boot#4627]
##### 截图&代码：
![3IF(4)OQ V}@O8{SK7MCT6A](https://user-images.githubusercontent.com/30968914/222088715-7607a7bd-86f2-429d-94bd-65db87975079.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改成字典或者自己编码赋值
