### ISSUE TITLE
如何将table的搜索栏设置成一列？

### ISSUE THREAD

**Issue by 1161325721** [jeecgboot/jeecg-boot#4628]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/61100025/222129923-1b4408e3-deab-44ea-bdc9-38ed8ca7c613.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个目前不支持个性化设置
