### ISSUE TITLE
按钮权限分配后，看权限接口为什么会把所有的安全授权标识都返回了

### ISSUE THREAD

**Issue by LvJianfeng** [jeecgboot/jeecg-boot#4629]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
Vue2

##### 问题描述：
按钮权限分配后，看权限接口为什么会把所有的安全授权标识都返回了，导致v-has生效

##### 截图&代码：
<img width="457" alt="image" src="https://user-images.githubusercontent.com/9586013/222328141-1d72ddc9-04b4-4cb8-8e75-ff46e211d5e6.png">

实际分配如下：
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9586013/222328313-6e431912-4610-41bc-9931-17487ff2358e.png">

角色权限分配：
![image](https://user-images.githubusercontent.com/9586013/222328400-a30cbf93-6bdd-41fa-bf60-99614ab196d2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
别的是其他菜单下的按钮

**Comment by LvJianfeng** [comment]
@zhangdaiscott 是的，下发的所有的，但是我其他我都没有授权呢

**Comment by zhangdaiscott** [comment]
截图看授权
这个人几个角色

**Comment by LvJianfeng** [comment]
用户管理下面就分配了一个角色，下图：
![image](https://user-images.githubusercontent.com/9586013/223004095-583ef01b-55b7-40c1-99e1-66b18814353d.png)

角色授权：
![image](https://user-images.githubusercontent.com/9586013/223004360-8ee34ea1-c67c-43a3-a9fd-e16d49b1d7c9.png)

两个新增编辑是没有授权的，但是接口是下发了的
![image](https://user-images.githubusercontent.com/9586013/223004432-1b272e77-7283-4c05-b19c-89bb1185539c.png)

**Comment by zhangdaiscott** [comment]
其他菜单下没截图看看，比如用户菜单

**Comment by LvJianfeng** [comment]
角色授权
![image](https://user-images.githubusercontent.com/9586013/223011279-3ff99d07-40bb-4240-9476-df2c290c56e0.png)

用户分配角色
![image](https://user-images.githubusercontent.com/9586013/223011386-11e93c20-d572-4471-bbec-092a2fa16c93.png)

**Comment by zhangdaiscott** [comment]
自己好好确认下吧，没有授权不可能有权限的
