### ISSUE TITLE
autopoi 添加isNullObject() 方法，判断导入对象是否为空，分页查询报错

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/jeecg-boot#4633]
##### 问题描述： 添加判断对象是否为空， 查询报错，把方法 isNullObject 当成数据库对象了
返回·：SQLSyntaxErrorException: Unknown column 'null_object' in 'where clause'
    /**
     * 判断该对象是否为空
     * @return
     */
    public boolean isNullObject(){
        return this.workNo == null;
    }

##### 截图&代码：
SELECT COUNT(*) FROM equipment WHERE (null_object = ?)
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'null_object' in 'where clause'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'null_object' in 'where clause'

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
添加一下截图和示例代码

**Comment by catlvsuger** [comment]
![image](https://user-images.githubusercontent.com/39261781/230267640-8aaa0a80-b188-4872-90b8-9ce90c8c90fe.png)
![image](https://user-images.githubusercontent.com/39261781/230267570-33c29c22-e069-4e59-91a6-5e6300378174.png)

**Comment by catlvsuger** [comment]
把 QueryGenerator.initQueryWrapper注释掉就没问题，我再看看里面哪里解析问题

**Comment by catlvsuger** [comment]
![image](https://user-images.githubusercontent.com/39261781/230268990-6b0fc1eb-b4d5-429d-a0dd-0fd221cdcafd.png)
PropertyDescriptor origDescriptors[] = PropertyUtils.getPropertyDescriptors(searchObj); 这个方法会有nullObject字段，
![image](https://user-images.githubusercontent.com/39261781/230269625-4577538a-f077-4e0e-b152-3d700051b630.png)
judgedIsUselessField 过滤掉 nullObject 可以解决该问题
