### ISSUE TITLE
xxljob 被 shiro 拦截是为什么？job进不去

### ISSUE THREAD

**Issue by lm627691338** [jeecgboot/jeecg-boot#4637]
##### 截图&代码：

![1677916945372](https://user-images.githubusercontent.com/20734673/222884624-bc1d0d02-709b-4da7-9085-b9373964e988.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1369521908** [comment]
可以参考下解决方法
https://github.com/jeecgboot/jeecg-boot/issues/4786

**Comment by miniFrank** [comment]
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/3614917/232324285-661ea02f-4336-4a7d-a1b4-6b301c887b0f.png">

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/3614917/232324353-0abc56aa-914b-4b8b-b077-86c0c704d238.png">


我本地运行的是3.4.3版本，貌似没有遇到，可以正常run。

**Comment by zhangdaiscott** [comment]
微服务之间的feign调用，如何免登录，同时又不会被暴露网关
https://help.jeecg.com/java/springcloud/dev/token.html
