### ISSUE TITLE
字段设置关联记录后，低代码平台测试效果和代码生成器的效果不一样

### ISSUE THREAD

**Issue by ytlibin** [jeecgboot/jeecg-boot#4638]
3.5.0 版本号：

##### 截图&代码：
![image](https://user-images.githubusercontent.com/33979703/222958208-2ba29710-d787-4ac4-a1ac-8650e78efef8.png)

功能测试:
![image](https://user-images.githubusercontent.com/33979703/222958228-4c369a5f-df3f-42d6-be57-28ee88d7eee1.png)
生成代码:
![image](https://user-images.githubusercontent.com/33979703/222958250-5601c606-aa67-4be3-8bbc-62b63270c19a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
关联记录 只有在线好使，不支持代码生成
