### ISSUE TITLE
 vue2版自动生成表单中新增自定义组件提交按钮没有反应

### ISSUE THREAD

**Issue by AiTaiShan** [jeecgboot/jeecg-boot#4640]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：

我在自动生成的表单`SalOrderForm`中加了一个自定义组件，在子表单中添加数据数据后点击确定没有反应，不添加子表单时可以保存的，我查看handleOk()方法发现 return validateFormModelAndTables(this.$refs.form,this.model, tables) 这句代码并没有获取到数据交给validateFormModelAndTables()方法执行，请问这种问题怎么解决。
##### 截图&代码：
![image](https://user-images.githubusercontent.com/125786180/223034013-6c93d8fc-4a0e-4d6a-8bdb-e1466bf2ae63.png)

![image](https://user-images.githubusercontent.com/125786180/223034384-653035bc-a4ad-4365-bfc3-d7d1585c7396.png)

![image](https://user-images.githubusercontent.com/125786180/223034806-cb5a4d8c-9cdc-48db-92b0-981a0ff44179.png)

![image](https://user-images.githubusercontent.com/125786180/223035267-58f871a6-17af-449c-b32f-8e4e0d5b7fbe.png)

**Comment by zhangdaiscott** [comment]
自己写的代码，自己debug跟踪下吧

**Comment by AiTaiShan** [comment]
后边的handleOk()方法是jeecgboot自带的，没有获取表的相关信息
