### ISSUE TITLE
请问页面数据来源支持API吗？

### ISSUE THREAD

**Issue by zijin-zj** [jeecgboot/jeecg-boot#4641]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
请问页面的数据来源支持服务端的API吗？目前看到只支持表的数据，没有看到支持API。
类似这种功能
![image](https://user-images.githubusercontent.com/48403386/223080197-1c2083ab-b90c-4b4e-b87f-0f7e24debb50.png)

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by zijin-zj** [comment]
就是后端自己提供API 然后低代码可以提供页面 每个页面操作可以指定后端API请求

**Comment by zhangdaiscott** [comment]
大屏只执行数据展示，目前没有操作性的api支持
