### ISSUE TITLE
使用docker-compose up启动报错

### ISSUE THREAD

**Issue by whtcgh** [jeecgboot/jeecg-boot#4642]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/24699872/223142934-1490f9f6-3e84-48b1-9890-5bbb488c6730.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by whtcgh** [comment]
3.5版本

**Comment by zhangdaiscott** [comment]
刚亲测，无问题

**Comment by zjarlin** [comment]
@whtcgh  解决了吗,俺也一样
<img width="916" alt="image" src="https://user-images.githubusercontent.com/67467679/233814563-b5d56265-6cac-46e0-92a7-ed2988461149.png">
