### ISSUE TITLE
hive

### ISSUE THREAD

**Issue by lego2533** [jeecgboot/jeecg-boot#4643]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

 版本号：3.4.4
前端版本：vue2
问题描述：多数据源如何配置hive数据

**Comment by zhangdaiscott** [comment]
参考mybatis plus多数据源配置
