### ISSUE TITLE
部门全部勾选后，点击确认按钮，部门信息丢失

### ISSUE THREAD

**Issue by winterbao** [jeecgboot/jeecg-boot#4646]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
部门选择里，全部勾选后，点击确认按钮，没有任何信息带到父页面上

##### 截图&代码：
![764D6A23F155FBC167C24A9BC2ADA606](https://user-images.githubusercontent.com/929719/223312743-a93661eb-b9bf-41b1-a856-1aa02c80f1cc.jpg)

**Comment by zhangdaiscott** [comment]
那个页面

**Comment by winterbao** [comment]
就是系统只带添加用户弹窗页面，选择所属部门时

**Comment by zhangdaiscott** [comment]
请图文并茂，不要让猜

**Comment by winterbao** [comment]
![image](https://user-images.githubusercontent.com/929719/223356509-81701243-1590-4de5-ac63-5241c9ef0e93.png)

**Comment by zhangdaiscott** [comment]
收到

**Comment by winterbao** [comment]
> 收到

非常感谢关注，我更新了一版图片，期待您的回复

**Comment by feihui233** [comment]
我修改了全部/全不选的代码，您可以参考
`  /**
   * 勾选全部
   */
  function checkALL(checkAll:boolean) {
        // 是否设置树组件全部勾选
    if(checkAll == true){
      let inList = [];
      let labelList = [];
      function getList(res) {
        const data = unref(res);
        for (let item of data) {
          inList.push(item.id);
          labelList.push(item);
          if (item.children != null && item.children.length) {
            getList(item.children);
          }
        }
      }
      getList(treeData.value);
      checkedKeys.value = inList;
      selectRows.value = labelList;
    }    
    if(checkAll == false){
      checkedKeys.value = [];
      selectRows.value = [];
    }
  }`

**Comment by zhangdaiscott** [comment]
3Q

**Comment by 1298191366** [comment]
已修复，待新版本发布
