### ISSUE TITLE
3.5.0版本多租户的几个问题

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#4647]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1.多租户每次添加完租户再打开会默认增加0
2.租户角色中没有授权和配置首页功能
3.管理员用户配置多个租户后，角色中没有非租户角色信息了
4.租户用户无法新增
5.租户无法编辑
6.租户用户在角色授权的时候 会出现低代码开发，组件&功能，mock示例等菜单，
是否可以增加判断在租户角色中，不显示这些菜单
##### 截图&代码：
问题1截图
![租户+0](https://user-images.githubusercontent.com/3311840/223312029-222c559c-8c58-40a5-99c3-b12e29335d57.png)

问题4截图
![微信截图_20230307113746](https://user-images.githubusercontent.com/3311840/223314881-7af8241b-6e2f-40fd-a45d-e0e3dcbb5c80.png)
问题5截图
![image](https://user-images.githubusercontent.com/3311840/223315434-be3c1e80-8585-4d44-8f9c-5ebcd8fecfb1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
每个步骤配合截图补充下说明

**Comment by qinghechaoge** [comment]
一.多租户每次添加完租户再打开会默认增加0
     操作步骤：
        1.编辑用户选择租户后关闭页面
        2.重新编辑页面，切换一下租户
        3.再次打开就有这个问题了
![image](https://user-images.githubusercontent.com/3311840/223456229-ba39e54b-ca75-422d-8521-92b5fddde2ad.png)
二.租户角色中没有授权和配置首页功能
         其实租户角色没有必要，角色管理已经按租户读取数据了
三.管理员用户配置多个租户后，角色中没有非租户角色信息了
         无法复现了，但是出了另外一个问题，切换租户后没有作用，需要重新登录
![image](https://user-images.githubusercontent.com/3311840/223458364-1ae8fff0-5442-43a9-b308-4baffc8a0050.png)
四.租户用户新增，编辑报错
![image](https://user-images.githubusercontent.com/3311840/223459085-87d6fe75-5466-4e74-ad1c-382d0cd59918.png)
         问题原因在于租户用户添加编辑时，没有读取租户列表权限。
         本来租户用户编辑时就应该不能修改租户信息，我已经调整了
![image](https://user-images.githubusercontent.com/3311840/223459699-d77dfeb1-2be9-420b-910c-70965979306a.png)
![image](https://user-images.githubusercontent.com/3311840/223459510-70f2442b-9ded-4132-a0cf-fe064928b48e.png)
五.租户无法编辑
        已经改好了，sys_user_tenant里经常出现重复情况，删了就能用了
六.租户用户在角色授权的时候 会出现低代码开发，组件&功能，mock示例等菜单，
        租户角色在授权时候，显示的全部菜单，建议改成租户管理员的菜单，或者菜单表加个过滤非用户功能的字段。
        因为有些时候，新增角色需要开放给用户的
![image](https://user-images.githubusercontent.com/3311840/223461537-a31f38f4-70ff-44e7-ae33-82afbbbd0096.png)
七.租户登录时，返回的userStore.getLoginInfo.departs里一直是空的。
       原因我也看了，登录时候，租户所在部门是按sys_depart.tenant_id = 0。不知道怎么解决
![image](https://user-images.githubusercontent.com/3311840/223463303-e5f7ecb6-ef6c-4f72-b812-fa057dbf93d7.png)
八.登录时返回的数据字典没有用，前后端也都没有进行缓存处理
![image](https://user-images.githubusercontent.com/3311840/223464119-a397d297-2a88-458c-8b0b-cd88bd7c8412.png)
九.RoleIndexConfigEnum中配置首页不起作用，前端还是会显示 dashboard/Analysis 路由
![image](https://user-images.githubusercontent.com/3311840/223464656-06685451-57c8-41de-a134-56b2016157e0.png)

**Comment by zhangdaiscott** [comment]
1.多租户每次添加完租户再打开会默认增加0
回复：未重现
2.租户角色中没有授权和配置首页功能
回复: 目前的设计，租户角色只是角色没有授权功能，授权通过租户套餐
3.管理员用户配置多个租户后，角色中没有非租户角色信息了
回复: 切换到对应租户下，租户角色才会展示，这个只展示当前租户下的橘色
4.租户用户无法新增
回复：租户用户列表，不应该有新增用户，已经去掉
5.租户无法编辑
回复: 不清楚你的重复数据如何产生的
6.租户用户在角色授权的时候 会出现低代码开发，组件&功能，mock示例等菜单，
是否可以增加判断在租户角色中，不显示这些菜单
回复：租户用户的权限是通过套餐来控制，不是角色

另外没考虑租户下自定义首页的配置功能

**Comment by zhangdaiscott** [comment]
你测试的时候开启了全系统多租户模式了吗
http://vue3.jeecg.com/3131258

**Comment by qinghechaoge** [comment]
> 你测试的时候开启了全系统多租户模式了吗 http://vue3.jeecg.com/3131258

开启了

**Comment by Evan98521** [comment]
> 
问题一：多租户每次添加完租户再打开会默认增加0
遇见过相同情况，编辑用户时，更改sys_user_tenant中索引类型为unique 就没在出现，但是如果保存会添加当前租户id, 到用户租户关系表

**Comment by zhangdaiscott** [comment]
改了索引还存在？

**Comment by Evan98521** [comment]
> 改了索引还存在？

改索引不会出现0的情况，但是在不动用户信息的情况下保存，会将当前租户id保存到用户租户关系表，而且会多次编辑 重复保存，因为改了索引 所以会出错

**Comment by Evan98521** [comment]
> 改了索引还存在？

还有请问 为什么 数据字典表没有在TENANT_TABLE添加 也会通过租户id隔离

**Comment by zhangdaiscott** [comment]
已经修复了，有硬编码方式实现租户隔离
