### ISSUE TITLE
Ajax 传递的 Token 写法问题

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [jeecgboot/jeecg-boot#4648]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
3.4.4         vue3

##### 问题描述：
1. 请问请求头中 Authorization 是否多余？
2. 如果 Authorization 不是多余，请问写法是否存在问题？
3. 如果 Authorization 不是多余，请问使用 Authorization 为何无效过？使用 X-Access-Token 才能访问？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46893436/223328431-108b33d8-57ab-493f-97ff-b628ade3514b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/223328865-6ed515a9-8f81-415d-a008-81b3ff12b94c.png)
![image](https://user-images.githubusercontent.com/46893436/223328895-d5d30b76-0cb0-43f5-b4d1-7d0c94022748.png)

**Comment by zhangdaiscott** [comment]
有用的是X-Access-Token:

**Comment by xuxiaowei-com-cn** [comment]
请问 Authorization 是否考虑删除？
