### ISSUE TITLE
Token 增加文件夹前缀

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [jeecgboot/jeecg-boot#4650]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
3.4.4 vue3

##### 问题描述：
是否可以在Token前缀增加一个类似于 下面 sys 的文件夹，防止数据较多时，软件不方便查看数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/46893436/223333008-34f93222-67ae-457c-9845-88061ab2d7fe.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以加

**Comment by xuxiaowei-com-cn** [comment]
已 PR
