### ISSUE TITLE
管理员账号无权限操作，但已授权

### ISSUE THREAD

**Issue by fenghao7** [jeecgboot/jeecg-boot#4651]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
后端增加@RequiresPermissions访问权限注解后管理员账号操作都报没有权限。但确实已经授权!比如浏览用户列表！

##### 截图&代码：

![image](https://user-images.githubusercontent.com/90027522/223333064-8d152554-d246-4397-8dca-0f7ea6a5208b.png)

![image](https://user-images.githubusercontent.com/90027522/223333142-7ff1f83a-d192-41fa-a8f3-37139885c3c1.png)

![image](https://user-images.githubusercontent.com/90027522/223333531-c10d37e1-8e23-44fc-aa7d-001090d7eaa6.png)

![image](https://user-images.githubusercontent.com/90027522/223333659-08015e00-b5a1-4b8a-a193-610c5bea113d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
退出重新登录了吗

**Comment by fenghao7** [comment]
重新登录了，缓存也清了


Bill
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 管理员账号无权限操作，但已授权 (Issue #4651)





 
退出重新登录了吗

**Comment by fenghao7** [comment]
去掉注解就可以了


Bill
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月7日(星期二) 下午2:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 管理员账号无权限操作，但已授权 (Issue #4651)





 
退出重新登录了吗

**Comment by zhangdaiscott** [comment]
不清楚，没遇到过
