### ISSUE TITLE
没有权限，请联系管理员授权

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#4653]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：

升级到3.5版本，菜单操作时提示：没有权限，请联系管理员授权

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/28818320/223348818-bc4dc8b8-bd22-4f2c-bc82-4177f3d38a59.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
更新最新代码
