### ISSUE TITLE
online在线表单（一对多），对子表记录进行新增或编辑时，无法获取到表单信息

### ISSUE THREAD

**Issue by 13806062016** [jeecgboot/jeecg-boot#4655]
##### 问题描述：
online在线表单，表一对多，对子表的记录进行新增和编辑时，admin角色页面正常 ，可正常获取到表单信息，而普通角色，列表可正常 显示记录信息，但新增或编辑时却空白。
通过排查权限控制和角色授权，均没有问题，请帮忙排查，谢谢！如下两张图。

##### 截图&代码：
admin角色显示正常
![image](https://user-images.githubusercontent.com/80078720/223371506-3b7f3872-5efd-4772-95e3-453351caa364.png)

普通用户显示为空白
![image](https://user-images.githubusercontent.com/80078720/223371773-ce4df66c-1fa7-41b4-93cb-32da1674c74c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看

**Comment by 13806062016** [comment]
列表数据都有取到，只是新增和编辑两个按钮，点击后弹窗是空白
![image](https://user-images.githubusercontent.com/80078720/223613660-d9a2ff30-035b-47b7-93c3-2474b4be8c1e.png)

**Comment by tygithub1** [comment]
已修改
