### ISSUE TITLE
vue2版本如果用jeecg-boot：3.4.4 版本会有什么问题？

### ISSUE THREAD

**Issue by immarktube** [jeecgboot/jeecg-boot#4656]
##### 版本号：  "name": "vue-antd-jeecg",
  "version": "3.4.3",

##### 问题描述：
请问我目前用的vue2版本，后台用的是jeecg-boot 3.4.4版本，我注意到了vue2版本库里更新的readme，我目前3.4.4版本有必要全删掉重新拉3.4.3版本吗？？如果不重新拉的话会造成什么影响呢？

**Comment by zhangdaiscott** [comment]
3.4.4应该还是兼容的，最好是版本匹配
