### ISSUE TITLE
swagger扫描不到自己新增的modules

### ISSUE THREAD

**Issue by biekaiqiangshiwo** [jeecgboot/jeecg-boot#4657]
##### 问题描述：
我新增自己的modules无法扫描到我自己的controller，包的路径是org.jeecg都没有问题，并且已经加个@api和@ApiOperation注解

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你发这样的问题，我们只能靠想像
