### ISSUE TITLE
在线开发 online表单开发

### ISSUE THREAD

**Issue by 1187717503** [jeecgboot/jeecg-boot#4660]
版本号：3.5.0

前端版本：vue3版

问题描述：在线开发online表单开发新建的表怎么样同步数据库？？？
截图&代码：
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/33123836/223638712-50ad80a1-f6df-4326-90af-efd8f26c4f3c.png">

  - 用的Online在线功能(需说明用的主题模板)

**Comment by zhangdaiscott** [comment]
表名得是英文的
