### ISSUE TITLE
如何修改打包后控制台的日志级别

### ISSUE THREAD

**Issue by ainxHub** [jeecgboot/jeecg-boot#4661]
##### 版本号：
2.4.5

##### 前端版本：vue3版？还是 vue2版？

vu2版本
##### 问题描述：
分离jar包后，logback.xml和logback-spring.xml里面的级别修改为INFO或者WARN，打包后控制台输出日志依然是debug，一直有输出，日志文件中是正常的，请问在哪里能提高它的日志级别呢

##### 截图&代码：
![image](https://user-images.githubusercontent.com/1772373/223657256-0f291d0a-ae40-4caf-a433-b49f5991bccf.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是不是你包里有logback.xml，删掉就好了

**Comment by ainxHub** [comment]
> 是不是你包里有logback.xml，删掉就好了

还是不行，完全删掉jeecg-boot-module-system里面的logback.xml，只剩下logback-spring.xml，config里面也删除logback.xml，也是一样的，每隔5秒，10秒会出现之前的debug消息。
下面是logback-spring.xml里面的一段配置
![image](https://user-images.githubusercontent.com/1772373/223893218-2bbf6110-1e65-47f0-a858-351405aa6df6.png)

**Comment by zhangdaiscott** [comment]
也有可能jeecgboot的引用的某个jar里面有logback.xml

**Comment by ainxHub** [comment]
> 也有可能jeecgboot的引用的某个jar里面有logback.xml

很有可能，但是包很多，而且不好改别个的jar，能否用覆盖的方法指定它的级别呢？
