### ISSUE TITLE
online表单主表(内嵌) 能否控制子表的展开的宽度？

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4664]
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
我想问下online表单主表(内嵌) 能否控制子表的展开的宽度？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19221237/223958942-db4e0675-a9fe-4ec9-b477-5f035d25c918.png)

![image](https://user-images.githubusercontent.com/19221237/223958763-99672be9-4038-4c70-bdaf-aa03cdb0f3ee.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不能
