### ISSUE TITLE
关于online表单里的子表，设置了权限不起作用问题

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4665]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
online表单里的子表，设置了权限按钮，为什么不显示出来，
子表的权限好像起不来效果，不知道是什么问题?

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19221237/223960972-26e6da22-2e5b-4e89-98f4-91aab6533aca.png)

![image](https://user-images.githubusercontent.com/19221237/223960399-0057defe-76dd-430d-9c91-20015b7fe9b0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
