### ISSUE TITLE
数据权限规则，不生效

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#4667]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
添加了数据权限规则，不生效，重新退出登录也不生效，还是查出了所有用户。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/89574140/223970629-9b5348b4-38b8-4dfa-93e2-f98f31940529.png)
![image](https://user-images.githubusercontent.com/89574140/223970790-be7ec3a5-c558-49bd-98c2-fb77b2fa5e5e.png)
![image](https://user-images.githubusercontent.com/89574140/223970950-da154b10-94ae-4b62-9e9e-27aea9a178b6.png)
![image](https://user-images.githubusercontent.com/89574140/223971209-5eb4f6f2-94c6-46bf-9b3d-b28e8b341849.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重启了吗

**Comment by baiqingxia888** [comment]
重启了，不管用。







在 2023-03-09 17:51:57，"JEECG" ***@***.***> 写道：

重启了吗

**Comment by zhangdaiscott** [comment]
可以加个断点跟踪看看

**Comment by zhangdaiscott** [comment]
你应该是给用户管理菜单配置数据权限，不是给他下面的按钮配置数据权限
