### ISSUE TITLE
前端编辑表单之后点击保存 /online/cgform/api/editAll 这个接口时，报错

### ISSUE THREAD

**Issue by shi-jing-peng** [jeecgboot/jeecg-boot#4668]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/65392504/223983291-3140beb0-d94b-48df-b276-99f2f4502fb9.png)

**Comment by zhangdaiscott** [comment]
版本号

**Comment by shi-jing-peng** [comment]
/online/cgform/api/authButton
 
 
 /online/cgform/api/authColumn



> 版本号
请问这些接口都加了锁的嘛
