### ISSUE TITLE
SAAS多租户设置

### ISSUE THREAD

**Issue by qiangyujia** [jeecgboot/jeecg-boot#4669]
##### 版本号：
2.4.2

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
多租户配置 如何能够让超管看到所有租户的信息 而不是每次进行选择某一种租户,有没有层级关系可以设置最高层可以查看所有租户的所有信息

##### 截图&代码：

![image](https://user-images.githubusercontent.com/45445573/224213661-ae3ec480-6b65-495e-86d5-54350a7b5cf5.png)
![image](https://user-images.githubusercontent.com/45445573/224213895-172afb02-5d0c-4052-8234-962acc4cd2c9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没明白

**Comment by qiangyujia** [comment]
我想要一个租户的管理员 权限大于任何租户 可以看到所有租户的数据。不知道如何实现，现在项目中有的模式是个人管理时选多个租户，进入时还是要选择某一个进入 这样数据还是被筛选了。我想要一个整体的数据。
![image](https://user-images.githubusercontent.com/45445573/224294087-c6da489a-1ce0-4dac-9f8d-0c2457801e34.png)

**Comment by zhangdaiscott** [comment]
那你得针对那个功能实现这个不隔离了，自己单独实现
