### ISSUE TITLE
3.5打开报表设计时出错

### ISSUE THREAD

**Issue by suisou** [jeecgboot/jeecg-boot#4670]
##### 版本号：
3.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
打开报表设计时，后台日志： 
{conn-10007, pstmt-21096} execute error. SELECT * FROM jimu_report_data_source where type = 'report'
java.sql.SQLSyntaxErrorException: Unknown column 'type' in 'where clause'

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
少字段，根据升级sql，自己执行下
http://jimureport.com/doc/log
