### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by aizyxaizyx** [jeecgboot/jeecg-boot#4672]
##### 问题描述：
部署war包上传文件 tomcat文件上传的临时文件因为占用无法删除掉
经测试发现是FileTypeFilter.fileTypeFilter(file);此方法造成的文件被占用，注释掉此方法tomcat就能自动清理掉临时文件

##### 截图&代码：
![1678434451427](https://user-images.githubusercontent.com/43277517/224255220-fc6ed475-1227-4276-bdaa-f97573c1ec4e.jpg)
![1678434412006](https://user-images.githubusercontent.com/43277517/224255269-a9584815-3e40-4be3-9c2d-39175c44d3bf.jpg)

**Comment by aizyxaizyx** [comment]
我看此方法方法只有在使用oss或者minio上传才有
本地上传未调用此方法，是正常的

**Comment by zhangdaiscott** [comment]
已修复
