### ISSUE TITLE
多种用户类型不同用户表登录怎么实现？

### ISSUE THREAD

**Issue by lq-java** [jeecgboot/jeecg-boot#4674]
##### 版本号：
3.5.0

##### 问题描述：
例如电商平台，有商家端，有用户端，有管理端。这种多种用户类型是绝大多数系统都存在的场景，如果是各自的用户账号表，系统中是不是自己实现多个ShiroRealm，对应不同的表查询，同时还要兼容的修改token，缓存或者登录用户信息等地方。

这样的话关于角色和权限的注解是没办法使用在用户端和商家端的。

建议官方是不是考虑后期增加登录类型和登录设备类型的实现。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
二开
