### ISSUE TITLE
积木报表数据库表字段缺失

### ISSUE THREAD

**Issue by flover28** [jeecgboot/jeecg-boot#4675]
##### 版本号：

3.5.0

##### 问题描述：

jimu_report_data_source 表缺少字段：type

##### 截图&代码：

![image](https://user-images.githubusercontent.com/13178197/224472756-9e842228-b49d-4f52-9439-294a95cb415e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ALTER TABLE jimu_report_data_source
ADD COLUMN type  varchar(10) NULL COMMENT '类型(report:报表;drag:仪表盘)';
UPDATE jimu_report_data_source SET type= 'report';
