### ISSUE TITLE
关于JeecgBootV3.5版本多租户实现的思路及问题

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/jeecg-boot#4676]
##### 版本号：
v3.5

##### 前端版本：vue3版？还是 vue2版？
Vue3+ts

##### 问题描述：
1.请问，租户用户权限管理是通过套餐来控制，后端已实现“产品包下人员申请”，“添加用户和产品包的关系数据”等接口，但前端相关业务页面未开源，导致数据库sys_tenant_pack_user存储信息无法正常维护，用户登录时无法获取产品包下权限，导致配置产品包权限不生效，是否对于租户管理中，产品包对应的用户管理、个人申请租户管理员等功能，是否需要二次开发，是否有开源的打算？

2.在租户管理套餐中，对于新增或编辑菜单列表时，配置菜单列表选项中，存在树形结构勾选后菜单选中错乱等问题，如勾选子级菜单，而无法选中父级，勾选父菜单，只能选中下一级菜单，层级越多，配置越困难。

望回复！

##### 截图&代码：
![image](https://user-images.githubusercontent.com/362930/224522914-1c152f5e-bc2a-4a14-be0e-e1d265cda3c8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
问题2，特意做的层级不关联，手工选
问题1，已经提交代码
