### ISSUE TITLE
【Online报表配置】使用第二个数据库时【报表参数】通过URL传入不生效

### ISSUE THREAD

**Issue by bit-walk** [jeecgboot/jeecg-boot#4679]
##### 版本号：
3.5.0（发布日期：2023-03-08） 
##### 前端版本：
vue3
##### 问题描述：Online报表配置功能问题
【多数据源管理】新增加的数据源，在进行【Online报表配置】中的【报表参数】只生效默认值，通过URL传入的值不生效，master数据库则可以。

**Comment by bit-walk** [comment]
![Uploading 20230312-164846.jpg…]()

**Comment by zhangdaiscott** [comment]
截图看不到
