### ISSUE TITLE
在线测试时使用数据字典能够转义，然后使用代码生成功能将页面添加到菜单之后无法转义

### ISSUE THREAD

**Issue by luoysuan** [jeecgboot/jeecg-boot#4682]
##### 问题描述：
在线测试时使用数据字典能够转义，然后使用代码生成功能将页面添加到菜单之后无法转义

##### 截图&代码：
在线测试
![image](https://user-images.githubusercontent.com/51365362/224729714-b1c1fa75-d0aa-4bf7-819e-199b415cdbb1.png)

对应字典code配置 
![image](https://user-images.githubusercontent.com/51365362/224729928-ccd157b6-67e8-4272-9bf4-b572bf4e704e.png)

生成代码 其中风格jvxe和风格Tab都试过
![image](https://user-images.githubusercontent.com/51365362/224730230-4fc3401b-3973-4406-afc6-0160f94a8068.png)

生成后的代码菜单
![image](https://user-images.githubusercontent.com/51365362/224730559-873c79b8-5327-44aa-a693-6112c5360a86.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Freezeu** [comment]
![image](https://user-images.githubusercontent.com/54260346/225223716-e7e0ec04-5498-4ce6-8d24-85544dce6a19.png)
你看看实体类字段上面有没有@Dict这个注释，加上后就有了

**Comment by luoysuan** [comment]
文档上有关于字典转义的逻辑吗，我找了一下相关的代码，以为是在前端处理的
&nbsp;


无妻徒刑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 下午2:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 在线测试时使用数据字典能够转义，然后使用代码生成功能将页面添加到菜单之后无法转义 (Issue #4682)





 

 ***@***.***这个注释，加上后就有了

**Comment by Freezeu** [comment]
你从@dict这个注解找，是可以找到处理逻辑的切面的

**Comment by luoysuan** [comment]
好的 十分感谢
&nbsp;


无妻徒刑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月15日(星期三) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 在线测试时使用数据字典能够转义，然后使用代码生成功能将页面添加到菜单之后无法转义 (Issue #4682)





 
***@***.***这个注解找，是可以找到处理逻辑的切面的
