### ISSUE TITLE
微服务之间调用免Token方案的问题

### ISSUE THREAD

**Issue by towelong** [jeecgboot/jeecg-boot#4683]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
微服务之间调用免Token方案，我设置了临时令牌，并且令牌能被存入Redis，但是FeignConfig并不会走如下截图的逻辑
![image](https://user-images.githubusercontent.com/41502558/224861588-85921d68-c268-48ff-909a-eeef53d48f15.png)

##### 截图&代码：
![image](https://user-images.githubusercontent.com/41502558/224861788-ba9ce5fe-5ac3-4a76-a890-7297c599b462.png)

日志如下：
![image](https://user-images.githubusercontent.com/41502558/224861846-34ade261-b44a-4f92-951c-02f477795466.png)

**Comment by lch245298** [comment]
同问，我也是这个问题

**Comment by towelong** [comment]
> 同问，我也是这个问题

我这边解决了，需要你自己去改这个FeignConfig
思路就是：
![image](https://user-images.githubusercontent.com/41502558/225178037-b1f370e0-d2f1-4110-8c82-a0ddaf98fcbe.png)
把这个地方token为null的时候，用UserTokenContext再取一遍

**Comment by zhangdaiscott** [comment]
已修复
