### ISSUE TITLE
中危漏洞修复:Springfox输入验证错误漏洞

### ISSUE THREAD

**Issue by CenMinghao** [jeecgboot/jeecg-boot#4684]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
中危漏洞修复
漏洞名称：Springfox输入验证错误漏洞
影响版本：springfox-swagger23.0.0

##### 截图&代码：
![image](https://user-images.githubusercontent.com/29631645/224869022-a2d2beb5-8f28-4ffe-b98f-e61bf92736b6.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by miniFrank** [comment]
关于该漏洞，snyk已经定义为【This was deemed not a vulnerability.】，同时springfox并未将commit合入master分支，具体请参考：
https://github.com/springfox/springfox/pull/3549
https://security.snyk.io/vuln/SNYK-JAVA-IOSPRINGFOX-674160
