### ISSUE TITLE
druid远程连接mysql数据库, 会出现包超时

### ISSUE THREAD

**Issue by qlanto224** [jeecgboot/jeecg-boot#4685]
##### 版本号：
3.4.1

##### 问题描述：
我这边连接的并不是本地mysql数据库, 而是另一台服务器的。
本地和远程的mysql版本都是5.7.
不确定是否是版本和jdbc版本的问题。
后端druid默认的配置, 会出现
`The last packet successfully received from the server was 20,243 milliseconds ago. The last packet sent successfully to the server was 20,245 milliseconds ago.`的问题

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58463221/224867788-175942ea-1afe-4cf8-a46f-54e2908672b3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个问题跟环境有关，你需要自己分析
