### ISSUE TITLE
mvn打包报错

### ISSUE THREAD

**Issue by Lihy6472** [jeecgboot/jeecg-boot#4686]
##### 版本号：

3.4.0

##### 前端版本：vue3版？还是 vue2版？

vuew

##### 问题描述：
* java代码打包报错

##### 截图&代码：

* 报错截图
![image](https://user-images.githubusercontent.com/116717391/224883458-41ae5b23-a822-4c78-ba60-97ca11c1ccf5.png)

* 配置文件截图
![image](https://user-images.githubusercontent.com/116717391/224883564-e4470da9-7a93-48b6-81c5-150bcc91e8c7.png)
![image](https://user-images.githubusercontent.com/116717391/224883591-6a4426d7-52f5-4817-ba00-feb7b700f79e.png)

* 本地host截图
![image](https://user-images.githubusercontent.com/116717391/224883751-66d64f2f-776f-41ec-beb6-7b71077daad1.png)

* mvn配置私服截图
![image](https://user-images.githubusercontent.com/116717391/224883919-edc3cf58-7b68-4f41-a012-c002c4e462f6.png)
![image](https://user-images.githubusercontent.com/116717391/224883987-448b9812-95e7-43db-ac7c-4e998a8aaeed.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是maven版本太高了吗？

**Comment by Lihy6472** [comment]
* 这是mvn版本和jdk版本
![image](https://user-images.githubusercontent.com/116717391/224933756-bde2c5e1-0d15-4dae-99fa-daf846ea1908.png)

**Comment by zhangdaiscott** [comment]
降低下maven版本试试

**Comment by Lihy6472** [comment]
降到多少呢？

**Comment by zhangdaiscott** [comment]
降低到3.5看看

**Comment by zhangdaiscott** [comment]
百度把，应该是你的环境问题
