### ISSUE TITLE
关联记录不支持代码生成

### ISSUE THREAD

**Issue by orienthong** [jeecgboot/jeecg-boot#4687]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
⚠️关联记录不支持代码生成
Online配置可以配置关联记录并正常预览，代码生成并没有生成相关关联记录代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/16395416/224886470-ef2b2b13-f1b9-40d8-8467-4855e4cd99b3.png)
![image](https://user-images.githubusercontent.com/16395416/224886555-fd0a2612-b0a5-47f6-bb4b-ddf93aaffaa2.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前的确不支持生成

**Comment by orienthong** [comment]
未来是否有支持计划呢
