### ISSUE TITLE
请问，能否在后台菜单管理中，添加main-out类型的页面，也就是脱离于框架之外的前台页面

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecg-boot#4688]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以，不设置layout就行

**Comment by IIIIIIIIF** [comment]
您好，这是我配置的脱离于框架之外的前台页面路由这是我原始的路由表，我想配成这个样子，配完之后，给角色授权之后，访问页面是404，请问我应该怎么配置呢？？？





诡异的蜗牛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 中午1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 请问，能否在后台菜单管理中，添加main-out类型的页面，也就是脱离于框架之外的前台页面 (Issue #4688)





 
可以，不设置layout就行

**Comment by IIIIIIIIF** [comment]
![fcfa46f3c5a3b4510429cecfda046ff](https://user-images.githubusercontent.com/29888011/224925694-4d0aa855-6a23-48c0-9c5d-730d9e9d3535.png)
这是我配置的路由，我想要配置成这种结构
![7c35abf91daf22757b4e2f8f253a710](https://user-images.githubusercontent.com/29888011/224925823-5d011a6f-9bfe-4303-8fcd-c177d674ade7.png)
，我想在前台，有相应权限的角色可以访问他，但是我授权之后，访问路径是404
![1b579599094b7238c4d6bf221d3862e](https://user-images.githubusercontent.com/29888011/224925989-44c9de36-dbfc-45af-9487-a6d107d9c21c.png)
，请问我该怎么配置呢？？

**Comment by IIIIIIIIF** [comment]
![f57df50aedbe200410d2923673107e0](https://user-images.githubusercontent.com/29888011/224926169-96e0f9d6-1043-4a8f-9acb-7f9b181d5efd.png)
