### ISSUE TITLE
在线Auto测试的效果，与生成代码后导入项目运行后的效果不一致。

### ISSUE THREAD

**Issue by jsbhb** [jeecgboot/jeecg-boot#4689]
##### 问题描述：online配置完表单后，在线测试没问题，代码导入后，却发现和在线测试效果不一样。
1、table中需要存的是关联表主键，需要转换成描述，在先测试没问题，但是代码中无效，还是显示id
2、table中图片组件，无法展示。在线测试没问题
3、新增form表单中，在线测试可以添加多个图，代码导入后，只能新增一张图。

怀疑在线Auto测试的代码，和代码生成后不一致。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28796920/224907377-fe885cec-6983-47d7-826b-d0da087dbe1e.png)
![image](https://user-images.githubusercontent.com/28796920/224907680-525e40b4-7658-4974-8486-eb1bcf815a92.png)
![image](https://user-images.githubusercontent.com/28796920/224908309-1bea8316-3c65-4e11-b972-c4be79c80277.png)
![image](https://user-images.githubusercontent.com/28796920/224908399-2c573862-32d1-46a9-be77-10e8e07585e3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
怀疑在线Auto测试的代码和代码生成后就是不一致。
online是在线功能，并不支持所有功能代码生成
比如：关联记录就不支持
