### ISSUE TITLE
请问，如何在后台菜单配置，配置类似mainout的页面，同时保留权限控制？有没有例子可以参考

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecg-boot#4691]
##### 截图&代码：

![fcfa46f3c5a3b4510429cecfda046ff](https://user-images.githubusercontent.com/29888011/224931599-d33aaaac-2a4d-4534-83d5-1d78107a34f7.png)
我想要配置成下面这个结构
![7c35abf91daf22757b4e2f8f253a710](https://user-images.githubusercontent.com/29888011/224931615-194040c0-3077-41c0-a854-5cac6aba7bac.png)

![f57df50aedbe200410d2923673107e0](https://user-images.githubusercontent.com/29888011/224931704-ae41ffdd-b70a-4e11-b1dc-a32546451cff.png)
但是配置完之后，访问404
![1b579599094b7238c4d6bf221d3862e](https://user-images.githubusercontent.com/29888011/224931822-e9d9ae8c-d563-4822-9731-dcd1fa828d3f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改代码，不是通过菜单配置

**Comment by IIIIIIIIF** [comment]
> 

咋改啊大哥，有例子吗
