### ISSUE TITLE
一万多条数据的excel导入方法读不不出数据ExcelImportUtil.importExcelBySax方法不行

### ISSUE THREAD

**Issue by lijibing0** [jeecgboot/jeecg-boot#4692]
版本号：1.4.0
前端版本： vue2
 问题描述：
一万多条数据的excel导入方法读不不出数据,看文档用这个ExcelImportUtil.importExcelBySax方法不行
ExcelImportUtil.importExcel又读不动 ,表头都设置正确了
截图&代码：

![image](https://user-images.githubusercontent.com/69373495/224941563-3ab0f2bf-0074-4987-b331-c5bf233c5ee6.png)

**Comment by zhangdaiscott** [comment]
你可以试试分页导入处理

**Comment by lijibing0** [comment]
您是指将一个excel拆成多分吗 , 可是他们用户不能拆啊

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/224952542-56a6363e-4d8e-4895-bb28-5a673ef19a9e.png)

**Comment by lijibing0** [comment]
哦哦谢谢您, 不过目前是没超过限制,用这个SAX方法读不到数据
![1678785738367](https://user-images.githubusercontent.com/69373495/224955006-7edc4e38-bde9-4967-a4da-2cb292ca6948.jpg)

![image](https://user-images.githubusercontent.com/69373495/224954340-ae3b6436-529f-4081-9baa-22c312e21fe3.png)

**Comment by lijibing0** [comment]
还有老师,这几个方法 怎么没有呀 = =
<img width="748" alt="1678786335474" src="https://user-images.githubusercontent.com/69373495/224957755-50c0cb01-d4e8-4656-be51-cf3c6ad90546.png">

用的autopoi-web1.4.0的版本不支持吗是

<img width="797" alt="1678786367181" src="https://user-images.githubusercontent.com/69373495/224958105-8dfd92d9-19f8-43b0-952d-e038e21f6af7.png">
还有请问这个IReadHandler接口怎么定义,然后传入呀
