### ISSUE TITLE
online表单展示问题

### ISSUE THREAD

**Issue by 2354844557** [jeecgboot/jeecg-boot#4693]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
online报表设计方便,风格更贴近于系统,但是有些联动操作无法做,比如左侧树操作选择传参到在线报表页.或者将报表页作为一个子页面做左右结构展示,现在想做左右结构展示,报表页包含了头部和左侧的导航栏.希望去掉头部和左侧导航栏.

##### 截图&代码：
![jeecg在线报表问题咨询](https://user-images.githubusercontent.com/49184838/224951087-1c7fbb8c-6071-4431-a4c4-1b15c8271d95.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 2354844557** [comment]
加了群.发了消息.没人回复.说到github来提问题.这里提了也没人理.哪怕你有个官方渠道.发红包解决下问题(或者给个说法)也好啊.三不管也不吸收意见.怎么做大做强.

**Comment by zhangdaiscott** [comment]
不支持，可以生成代码，自定义开发
