### ISSUE TITLE
gateway启动成功，服务是健康的。gateway页面出不来swagger文档，Knife4j文档请求异常

### ISSUE THREAD

**Issue by BigRoseAndBoss** [jeecgboot/jeecg-boot#4696]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
gateway启动成功，服务是健康的。gateway页面出不来swagger文档，Knife4j文档请求异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/50453506/224994403-0a7c3765-36f1-46af-a81e-3b6b144f49ce.png)

![image](https://user-images.githubusercontent.com/50453506/224994135-399e8be1-95dd-49f4-b6d5-8a4ee0453930.png)

![image](https://user-images.githubusercontent.com/50453506/224993892-7ff91bc3-dcef-4ce4-ba85-30380d0b4431.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
老版本需要先启动单个微服务模块，最后启动gateway
