### ISSUE TITLE
online自定义按钮弹窗报错

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4697]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

我复制文档的代码过去也无法使用，自己弄得也无法使用，不知道是路径的问还是什么问题？
或许这个只是一个小的问题，但是希望能帮帮，我是忠实粉丝，感谢你

##### 截图&代码：
![image](https://user-images.githubusercontent.com/19221237/225183817-9527da9a-8d42-4872-8a85-b5338fac7e6e.png)

![J0GSN W9M_G(~) D )$WCFB](https://user-images.githubusercontent.com/19221237/225183578-cd9fb9d6-f437-4bce-aaf0-c016f2dfa7aa.png)

![LVM{}R{CRAM@~ID)U0V%2$E](https://user-images.githubusercontent.com/19221237/225183596-7f0bff8d-73a5-4356-ba60-fafe3c55b91a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
具体怎么写的截图

**Comment by LiCain** [comment]
> 具体怎么写的截图
请您看下：
`<template>
  <a-spin :spinning="confirmLoading">
    <j-form-container :disabled="formDisabled">
      <a-form-model ref="form" :model="model" :rules="validatorRules" slot="detail">
        <a-row>
          <a-col :span="24">
            <a-form-model-item label="订单编号" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="orderNumber">
              <a-input v-model="model.orderNumber" placeholder="请输入订单编号"  ></a-input>
            </a-form-model-item>
          </a-col>
          <a-col :span="24">
            <a-form-model-item label="类型" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="etype">
              <j-dict-select-tag type="list" v-model="model.etype" dictCode="crmmailtype" placeholder="请选择类型" />
            </a-form-model-item>
          </a-col>
          <a-col :span="24">
            <a-form-model-item label="收件人" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="addresseeri">
              <a-input v-model="model.addresseeri" placeholder="请输入收件人"  ></a-input>
            </a-form-model-item>
          </a-col>
          <a-col :span="24">
            <a-form-model-item label="附件" :labelCol="labelCol" :wrapperCol="wrapperCol" prop="filesdata">
              <j-upload v-model="model.filesdata"   ></j-upload>
            </a-form-model-item>
          </a-col>
        </a-row>
      </a-form-model>
    </j-form-container>
  </a-spin>
</template>

<script>

  import { httpAction, getAction } from '@/api/manage'
  import { validateDuplicateValue } from '@/utils/util'

  export default {
    name: 'MyCrmMailSysForm',
    components: {
    },
    props: {
      //表单禁用
      disabled: {
        type: Boolean,
        default: false,
        required: false
      }
    },
    data () {
      return {
        model:{
         },
        labelCol: {
          xs: { span: 24 },
          sm: { span: 5 },
        },
        wrapperCol: {
          xs: { span: 24 },
          sm: { span: 16 },
        },
        confirmLoading: false,
        validatorRules: {
        },
        url: {
          add: "/mycrmmailsys/myCrmMailSys/add",
          edit: "/mycrmmailsys/myCrmMailSys/edit",
          queryById: "/mycrmmailsys/myCrmMailSys/queryById"
        }
      }
    },
    computed: {
      formDisabled(){
        return this.disabled
      },
    },
    created () {
       //备份model原始值
      this.modelDefault = JSON.parse(JSON.stringify(this.model));
    },
    methods: {
      add () {
        this.edit(this.modelDefault);
      },
      edit (record) {
        this.model = Object.assign({}, record);
        this.visible = true;
      },
      submitForm () {
        const that = this;
        // 触发表单验证
        this.$refs.form.validate(valid => {
          if (valid) {
            that.confirmLoading = true;
            let httpurl = '';
            let method = '';
            if(!this.model.id){
              httpurl+=this.url.add;
              method = 'post';
            }else{
              httpurl+=this.url.edit;
               method = 'put';
            }
            httpAction(httpurl,this.model,method).then((res)=>{
              if(res.success){
                that.$message.success(res.message);
                that.$emit('ok');
              }else{
                that.$message.warning(res.message);
              }
            }).finally(() => {
              that.confirmLoading = false;
            })
          }
         
        })
      },
    }
  }
</script>`

**Comment by LiCain** [comment]
> 具体怎么写的截图

![image](https://user-images.githubusercontent.com/19221237/225196610-f948d44b-c845-4822-9061-596c61ae85b2.png)
![image](https://user-images.githubusercontent.com/19221237/225196668-238341ef-033a-4315-b157-834d849f8a20.png)
![image](https://user-images.githubusercontent.com/19221237/225196705-b08253cd-1e9c-4ddd-8270-2a2ce5a1d0f8.png)

**Comment by zhangdaiscott** [comment]
JS增强是在线写的脚本，你这个都是生成的代码，不需要采用js增强的写法，也不兼容

**Comment by LiCain** [comment]
> JS增强是在线写的脚本，你这个都是生成的代码，不需要采用js增强的写法，也不兼容

但是用你们的文档也不行啊
![image](https://user-images.githubusercontent.com/19221237/225218260-34edffba-9de6-49ca-8445-e951f827477a.png)
![image](https://user-images.githubusercontent.com/19221237/225218274-f640aec8-3361-44e5-a0ff-065e6534e2fa.png)
