### ISSUE TITLE
用户租户表（sys_user_tenant）未做唯一性约束，会造成多次添加默认租户

### ISSUE THREAD

**Issue by ion1ze** [jeecgboot/jeecg-boot#4698]
##### 截图&代码：

[![Snipaste-2023-03-15-09-50-34.png](https://i.postimg.cc/28fbWtbT/Snipaste-2023-03-15-09-50-34.png)](https://postimg.cc/K4J8SJ5g)
定位：`org.jeecg.modules.system.service.impl.SysUserServiceImpl.java` 866行

**Comment by zhangdaiscott** [comment]
收到

**Comment by 1298191366** [comment]
已修复，待新版本发布
