### ISSUE TITLE
online表单怎么增加合计功能，是不是在扩展参数哪里

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4699]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

我想在online表单怎么增加合计功能，但是没找到相应的文档，这个应该怎么弄呢？
不知道有没有这个功能，麻烦你了
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/225196068-bc392b73-95bc-45ec-944d-f72748f6a623.png)
![image](https://user-images.githubusercontent.com/19221237/225196148-6e2c4ef5-5239-4176-a13e-a7601a3cc148.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
online报表支持合计，online表单没这功能

**Comment by bmrainc** [comment]
online表单，几个专项升级后，是否支持合计功能？
