### ISSUE TITLE
代码生成，文件上传失败

### ISSUE THREAD

**Issue by it-xhp** [jeecgboot/jeecg-boot#4704]
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 截图&代码：
![image](https://user-images.githubusercontent.com/96649838/225267069-1d02005c-cf96-4640-adf4-1c0f4af1de08.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个看不出来，debug跟一下
