### ISSUE TITLE
online表单中 自定义按钮在从表中不显示

### ISSUE THREAD

**Issue by icgreat** [jeecgboot/jeecg-boot#4705]
##### 版本号：
3.4.2

##### 前端版本：vue3版？还是 vue2版？
vue3 3.4.2

##### 问题描述：
online表单中 子表的自定义按钮不显示
我发现在线演示版本中   只有在vue2的  erp主题中才能够正确显示从表的 自定义按钮，
但是在vue3的在线演示版中没有这个 erp主题
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
erp未做，暂时不考虑做了

**Comment by icgreat** [comment]
这是来自邮箱的自动回复邮件。您好，您的邮件已收到，如有需要本人会尽快回复。
