### ISSUE TITLE
微服务部署正式服务器跨域问题

### ISSUE THREAD

**Issue by lm627691338** [jeecgboot/jeecg-boot#4707]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
微服务项目分开部署，跨域怎么设置，怎么处理？nginx设置了跨域也没用

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20734673/225370322-f597a4c2-a00a-4442-bf9a-64ae4d34a862.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不是通过gateway访问的吗？gateway做了跨域处理

**Comment by lm627691338** [comment]
> 不是通过gateway访问的吗？gateway做了跨域处理

是通过gateway访问的，我的Nginx配置你看下
![image](https://user-images.githubusercontent.com/20734673/225486067-92a7c78f-ecfc-403b-b2db-234d62353c2b.png)

而且导入的时候报错405是什么原因？
![image](https://user-images.githubusercontent.com/20734673/225486148-814c9ed8-38f3-4bde-843d-7cbb026a9df6.png)

**Comment by zhangdaiscott** [comment]
那你直接通过gateway的后台地址访问看看，先判断是不是你的nginx配置文档

**Comment by lm627691338** [comment]
已解决

**Comment by lm627691338** [comment]
已解决
