### ISSUE TITLE
online表单中 从表自定义按钮不显示

### ISSUE THREAD

**Issue by icgreat** [jeecgboot/jeecg-boot#4709]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3  3.5.0

##### 问题描述：
online表单中  从表的自定义按钮不显示，已经自定义按钮了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
