### ISSUE TITLE
调用JEditableTable 可编辑表格添加超过9行时超过第9行的数据记录被隐藏，表格最下面出现空白

### ISSUE THREAD

**Issue by yangshuang321** [jeecgboot/jeecg-boot#4710]
##### 截图&代码：
![1678935399607](https://user-images.githubusercontent.com/68838901/225499214-a569b7dc-0bb7-4bd6-8c04-648f2b0ad532.png)

**Comment by zhangdaiscott** [comment]
版本太老，建议先手工升级到最新版

**Comment by wmh1006** [comment]
最新版本依然有问题
试着把mounted改为updated以后暂时解决了，不知道影响，但是目前来看没啥影响
