### ISSUE TITLE
导入时报错 org.apache.poi.xssf.usermodel.XSSFSimpleShape cannot be cast to org.apache.poi.xssf.usermodel.XSSFPicture

### ISSUE THREAD

**Issue by menghj1992** [jeecgboot/jeecg-boot#4711]
##### 版本号：
jeecg-boot3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用autopoi导入时报错：org.apache.poi.xssf.usermodel.XSSFSimpleShape cannot be cast to org.apache.poi.xssf.usermodel.XSSFPicture
试了一下升级到最新版的autopoi1.4.5也报同样的错误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40202782/225509551-fc3156d8-6ef2-46f1-8ea7-297752d1f715.png)
![image](https://user-images.githubusercontent.com/40202782/225510406-06222dd6-70db-46b3-96a7-55bc3a7f097e.png)

public class ProjectExcelDTO {
    /**
     * 项目编号,非空
     */
    @Excel(name = "项目编号", width = 15)
    private String projectCode;
    /**
     * 项目名称,非空
     */
    @Excel(name = "项目名称", width = 15)
    private String projectName;
    /**
     * 区县,非空
     */
    @Excel(name = "区县", width = 15, dicCode = "ict_county")
    @Dict(dicCode = "ict_county")
    private Integer county;
    /**
     * 行业,非空
     */
    @Excel(name = "行业", width = 15, dicCode = "ict_trade")
    @Dict(dicCode = "ict_trade")
    private Integer trade;
    /**
     * 预算类型,非空
     */
    @Excel(name = "预算类型", width = 15, dicCode = "ict_budget_type")
    @Dict(dicCode = "ict_budget_type")
    private Integer budgetType;
    /**
     * 合同金额,非空
     */
    @Excel(name = "合同金额", width = 15)
    private BigDecimal contractAmount;
    /**
     * 签约主体,非空
     */
    @Excel(name = "签约主体", width = 15, dicCode = "ict_contracted_subject")
    @Dict(dicCode = "ict_contracted_subject")
    private Integer contractedSubject;
    /**
     * 签约时间,非空
     */
    @Excel(name = "签约时间", width = 20, format = "yyyy-MM-dd")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date contractTime;
    /**
     * 客户经理,非空
     */
    @Excel(name = "客户经理", width = 15)
    private String accountManager;
    /**
     * 支局,非空
     */
    @Excel(name = "支局划分", width = 15)
    private String branch;
    /**
     * 项目开始时间
     */
    @Excel(name = "项目开始时间", width = 20, format = "yyyy-MM-dd")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date startTime;
    /**
     * 约定交付时长
     */
    @Excel(name = "约定交付时长", width = 15)
    private Integer contractDeliveryTime;
    /**
     * 项目内容
     */
    @Excel(name = "项目内容", width = 15)
    private String projectContent;
    /**
     * 列收类型,非空
     */
    @Excel(name = "列收类型", width = 15, dicCode = "ict_collection_type")
    @Dict(dicCode = "ict_collection_type")
    private Integer collectionType;
    /**
     * 业务类型,非空
     */
    @Excel(name = "业务类型", width = 15, dicCode = "ict_business_type")
    @Dict(dicCode = "ict_business_type")
    private Integer businessType;
    /**
     * 含税金额
     */
    @Excel(name = "含税金额", width = 15)
    private BigDecimal amountIncludingTax;
    /**
     * 不含税金额
     */
    @Excel(name = "不含税金额", width = 15)
    private BigDecimal amountExcludingTax;
    /**
     * 税额
     */
    @Excel(name = "税额", width = 15)
    private BigDecimal tax;
    /**
     * 税率,非空
     */
    @Excel(name = "税率", width = 15, dicCode = "ict_tax_rate")
    @Dict(dicCode = "ict_tax_rate")
    private Integer taxRate;
    /**
     * 收入类型,非空
     */
    @Excel(name = "收入类型", width = 15, dicCode = "ict_income_type")
    @Dict(dicCode = "ict_income_type")
    private Integer incomeType;
    /**
     * 列收方式,非空
     */
    @Excel(name = "列收方式", width = 15, dicCode = "ict_collection_mode")
    @Dict(dicCode = "ict_collection_mode")
    private Integer collectionMode;
    /**
     * 列收期数
     */
    @Excel(name = "列收期数", width = 15)
    private Integer collectionPeriod;
    /**
     * 列收开始时间
     */
    @Excel(name = "列收开始时间", width = 20, format = "yyyy-MM")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM")
    @DateTimeFormat(pattern = "yyyy-MM")
    private Date collectionStartTime;
    /**
     * 列收结束时间
     */
    @Excel(name = "列收结束时间", width = 20, format = "yyyy-MM")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM")
    @DateTimeFormat(pattern = "yyyy-MM")
    private Date collectionEndTime;
    /**
     * 每月列收(不含税)
     */
    @Excel(name = "每月列收(不含税)", width = 15)
    private BigDecimal monthlyCollection;
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by menghj1992** [comment]
怎么把excel文件传上去呢?好像是excel文件的问题,新建了一个excel文件把数据粘过去了就能转成功

**Comment by lsqGitHub716** [comment]
测试未复现，麻烦提供一下你的示例文件，方便测试
