### ISSUE TITLE
表单生成问题

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4712]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用Onile表单开发时，显示404，资源未找到
##### 截图&代码：

![353V14887PKB38Q50C(TEZF](https://user-images.githubusercontent.com/128020569/225527551-efa171bb-ae68-40f8-a4ce-45e9bdaadf96.png)

![image](https://user-images.githubusercontent.com/128020569/225527641-2f3fe98e-c639-406b-a3b0-4b5a195cb07f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台online的依赖没下载成功
