### ISSUE TITLE
[功能建议]Online功能-系统级增强

### ISSUE THREAD

**Issue by chzhm159** [jeecgboot/jeecg-boot#4715]
##### 版本号：
    期望未来某个版本能支持

##### 前端版本：vue3版？还是 vue2版？
    期望未来某个版本能支持

##### 问题描述：
    目前的各种表单增强还是聚焦在 单表功能的 SQL,Java,JS增加,缺少整体的增强设计. 
    那么如果完全基于 Online 仍然无法满足一个完整站点的功能需求.例如

- 数据统计类需求不好实现, 往往需要联合多表查询
- 定时统计类需求不好实现
- 想增加一些工具类,无法互相调用

### 想法/建议：
将 Online 功能发挥到极致,目标是可以基于Online构建一个系统!

- **插件机制**:  通过设计插件接口,以插件的形式扩展系统本身功能,同时可以打造插件社区
- **事件机制**:  将系统级事件/表单级的各种事件(增,删,改,查)对外暴露,可以基于事件做出各种额外处理
- **动态加载功能**:  比如直接上传一个 jar包(插件/各种增强)就能被动态加载(OSGI/ClassLoader等技术实现)
- **定时任务增强**: 可以直接上传一个Jar包或者平台相关的脚本,能够自动得到调用

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以看下 [敲敲云](https://app.qiaoqiaoyun.com/) 这块的自定义规则和按钮结合已经趋于完美
