### ISSUE TITLE
打包发布以后日期控件无法点选

### ISSUE THREAD

**Issue by menghj1992** [jeecgboot/jeecg-boot#4716]
##### 版本号：
jeecg-boot3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在本地通过yarn dev的方式启动前端没问题,通过yarn run build打包发布以后,日期控件无法点选,点得话就消失

##### 截图&代码：
![image](https://user-images.githubusercontent.com/40202782/225788559-68186b01-eb3a-4216-857e-f1456eaac2d1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by menghj1992** [comment]
在test环境a-date-picker不能点击,生产环境没问题.感觉像是vite或者andesign的问题,和jeecg框架没关系.

**Comment by zhoupengTim** [comment]
现在这个问题解决了吗？我也遇到了同样的问题，打包发布之后日期组件就回失效，无法使用

**Comment by menghj1992** [comment]
> 现在这个问题解决了吗？我也遇到了同样的问题，打包发布之后日期组件就回失效，无法使用

@zhoupengTim 改成了打包pro环境可以了,具体也不知道什么问题,可以看下https://ask.csdn.net/questions/7784732
