### ISSUE TITLE
Could not find artifact org.jeecgframework.boot:jeecg-boot-base-core:pom:3.5.0 in aliyunmaven 

### ISSUE THREAD

**Issue by 1zero0** [jeecgboot/jeecg-boot#4720]
##### 版本号：
maven：3.3.5

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
MAVEN Could not find artifact org.jeecgframework.boot:jeecg-boot-base-core:pom:3.5.0 in aliyunmaven 

##### 截图&代码：
![image](https://user-images.githubusercontent.com/119936405/226148430-92a037ce-fd49-4aea-8fdc-ddb653c688ba.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你这导入的有问题，为什么base 哪些模块没进来
