### ISSUE TITLE
多租户管理流程，如何给租户账号授权？

### ISSUE THREAD

**Issue by guojingbing** [jeecgboot/jeecg-boot#4724]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
多租户管理仍然是个半成品吧？
租户角色授权没有？如何给租户角色授权？
租户账号以及权限管理的流程是什么？
##### 截图&代码：
![image](https://user-images.githubusercontent.com/5864899/226239526-7884d250-2407-4c9c-9cd6-d771927d57bd.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
权限用租户套餐授权，租户角色不是干这个用的
