### ISSUE TITLE
多租户，tenant_id没起效果

### ISSUE THREAD

**Issue by ainxHub** [jeecgboot/jeecg-boot#4727]
##### 版本号：
2.4.5

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
按照[文档](http://doc.jeecg.com/2044164)要求，查询的时候没有带上tenant_id

##### 截图&代码：
1、修改了MybatisPlusConfig配置
![image](https://user-images.githubusercontent.com/1772373/226290323-4ac661ce-6c3e-4601-8a7d-4da4a9d2d3cb.png)
2、数据库添加了字段
![image](https://user-images.githubusercontent.com/1772373/226290497-717695a5-4833-4411-b7ef-069ad73e56df.png)
3、请求头里面也带了tenant_id
![image](https://user-images.githubusercontent.com/1772373/226294267-c3b11353-32c9-457d-8b03-7597b3e2de39.png)
4、结果返回了tenant_id为0的数据
![image](https://user-images.githubusercontent.com/1772373/226294438-3e248693-85df-4830-b6df-21904cc58188.png)
请问下是怎么回事呢，还要做那些修改呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改完重启了吗
代码是怎么写的？有没有排除shiro拦截

**Comment by ainxHub** [comment]
重启了的
代码是指查询的代码吗，
![image](https://user-images.githubusercontent.com/1772373/226508492-6b0e0cb1-331c-4586-a936-b79a246ae424.png)
和正常的查询是一样的

shiro拦截是排除了的

**Comment by ainxHub** [comment]
> 改完重启了吗 代码是怎么写的？有没有排除shiro拦截

重启了的
代码是指查询的代码吗，
![image](https://user-images.githubusercontent.com/1772373/226508650-9c21a17d-ebdd-4da6-a28b-0a74dd88e994.png)
和正常的查询是一样的

shiro拦截是排除了的
