### ISSUE TITLE
表中设置单元格为“可修改”时，单选记录或者全选记录时会卡顿严重

### ISSUE THREAD

**Issue by 3akur6** [jeecgboot/jeecg-boot#4729]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
当表中启用cell为edit=true时，单选记录或者全选记录时会卡顿严重，控制台输出大量的循环调用警告，将edit改为false就不会卡顿。

##### 
截图&代码：
<img width="1512" alt="Screenshot 2023-03-21 at 10 17 51" src="https://user-images.githubusercontent.com/47488871/226505103-7a84492b-65a7-45e0-9138-0bf30f7dfba0.png">
![Screenshot 2023-03-21 at 10 21 28](https://user-images.githubusercontent.com/47488871/226504639-694c635a-a19c-44b5-923d-3a400f0bce0f.png)
<img width="322" alt="Screenshot 2023-03-21 at 10 22 48" src="https://user-images.githubusercontent.com/47488871/226504520-877d739c-ff92-4786-b371-959398f6eef4.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vben封装的table是存在卡的问题，如果需要行编辑可以用这个控件


JVXETable 
http://vue3.jeecg.com/2561638
https://vxetable.cn/#/table/start/install
