### ISSUE TITLE
online表单开发，《显示复选框》选项不生效

### ISSUE THREAD

**Issue by dxy0814** [jeecgboot/jeecg-boot#4731]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图看配置

**Comment by dxy0814** [comment]
![77777_20230322140710](https://user-images.githubusercontent.com/29192507/226816710-8c0a8d77-8027-4198-a68d-e6444c9fb162.png)

**Comment by zhangdaiscott** [comment]
测试无问题

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/229977989-256b3945-239e-4f41-ae1d-fef0598b1e3d.png)
