### ISSUE TITLE
Token失效，请重新登录!

### ISSUE THREAD

**Issue by xiays88** [jeecgboot/jeecg-boot#4732]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
总是时不时的报Token失效，请重新登录!，而且报这个的时间间隔不一样，感觉设置的Token失效的时间
不起作用，3.4.4版本好像也有此问题，我试过总是时不时的需要人登录一下，十几分钟二十分钟 的就要重新登录
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
token超时是两个小时，你这边如果有人清理redis缓存会出现这个问题
