### ISSUE TITLE
新建的模块前端请求不到地址，报错404，代码放在system中就好使

### ISSUE THREAD

**Issue by lishuanghe214** [jeecgboot/jeecg-boot#4735]
##### 版本号：

1.0
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
新建的模块前端请求不到地址，报错404，代码放在system中就好使

##### 截图&代码：
![image](https://user-images.githubusercontent.com/72898445/226610189-bf17b48c-d436-47c1-a64a-cb778ff42b9b.png)
![image](https://user-images.githubusercontent.com/72898445/226610234-48842e74-a572-4190-811d-6938d58a7c78.png)
![image](https://user-images.githubusercontent.com/72898445/226610272-67d18d07-1f28-4990-b256-6884309b645d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lishuanghe214** [comment]
已解决！新建的模块需要在start中追加一下依赖

**Comment by greenlgy** [comment]
> > 
> 
> 怎么弄 详细一些可以吗

1. 在【jeecg-system-start】工程上点击右键， 选择【打开模块设置】， 会打开【项目结构】窗口，并自动定位在【模块】面板
2. 在【模块】面板上，选中【jeecg-system-start】工程，点击【+】图标，在菜单中选择【模块依赖】，会打开【选择模块】面板
3. 在【选择模块】面板中，选择你自己建立的模块即可，如下图：
![f60adfc698889070a48976feeff0e22](https://github.com/jeecgboot/jeecg-boot/assets/35718003/b1b2e30b-1dd6-4e53-a007-fd136f51607c)
