### ISSUE TITLE
租户数据问题

### ISSUE THREAD

**Issue by ainxHub** [jeecgboot/jeecg-boot#4736]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我用管理员账号admin创建了租户A,B,C，给租户A创建了一个人员（A1），A1又在租户管理里面创建了一个人员A11。
问题是：人员A1能看到全部的租户信息，全部的人员信息，默认有了系统管理的菜单权限，我没有进行分配
              人员A11登陆进去看到了全部的人员和租户信息，
是不是我这边要给sys_user表加入tenant_id字段呢，还是其他原因没做好导致的呢？

**Comment by zhangdaiscott** [comment]
开启全局租户隔离模式了吗
http://help.jeecg.com/javaback/saas.html

**Comment by LuckyDouer** [comment]
遇到同样的问题，路径如下：
