### ISSUE TITLE
前端新建了个触发按钮，提示404。后台接口能够调试通过

### ISSUE THREAD

**Issue by sangjiexun** [jeecgboot/jeecg-boot#4738]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
前端新建如图红框刀具报废按钮，点击后提示404。后台接口能够调试通过

##### 截图&代码：
![image](https://user-images.githubusercontent.com/59449516/226812418-d4622c97-fa88-4293-aa4d-4497949e5c27.png)

![image](https://user-images.githubusercontent.com/59449516/226812325-cd9e0177-7985-4df0-8d2d-2dd9b32053b8.png)

![image](https://user-images.githubusercontent.com/59449516/226812358-a2de4233-febf-4cf4-adce-0e0cd2347084.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己新代码，需要自己分析
