### ISSUE TITLE
修改密码时希望增加密码强度校验，与新增用户时一致，另外能否增加多次登录失败后锁定账号的功能

### ISSUE THREAD

**Issue by patrickhu1** [jeecgboot/jeecg-boot#4739]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
修改密码时希望增加密码强度校验，与新增用户时一致，另外能否增加多次登录失败后锁定账号的功能

##### 截图&代码：
![image](https://user-images.githubusercontent.com/26364818/226836669-dc619e2d-768d-4789-bd3b-f23c0cfba641.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
最新版有登录错误锁定功能
