### ISSUE TITLE
请问部门权限和角色权限的区别是什么？

### ISSUE THREAD

**Issue by 865242636** [jeecgboot/jeecg-boot#4741]
##### 问题描述：
给角色设置菜单权限，给部门也设置了菜单权限，把同一个用户分配该角色且设置该部门，但是部门的菜单权限不展示，想问下菜单的展示逻辑是什么？部门的菜单权限作用是什么？谢谢

##### 截图&代码：
1 设置角色的菜单权限
![image](https://user-images.githubusercontent.com/24559266/226850511-062816b4-70cc-488c-b59a-60abc681053e.png)
2 设置部门的权限
![image](https://user-images.githubusercontent.com/24559266/226852778-2c215b07-2736-4a94-a008-c3d68e1caf75.png)

3 给用户设置角色和部门
![image](https://user-images.githubusercontent.com/24559266/226851292-24a85435-a90d-4869-a5a7-24b5a6b9f1a4.png)
4 最终展示菜单效果，只有角色的权限
![image](https://user-images.githubusercontent.com/24559266/226852176-cff24238-c6cf-4497-a3f2-ba4c78efc3c1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044050
