### ISSUE TITLE
j-select-position取消预加载

### ISSUE THREAD

**Issue by LJL888999** [jeecgboot/jeecg-boot#4742]
##### 前端版本：vue3版？还是 vue2版？
vue
2

##### 问题描述：
![image](https://user-images.githubusercontent.com/121850941/226858751-efe150b9-663a-481b-a194-e7db71049f40.png)

职位怎么取消预加载 变成实时加载  如果 同时打开 添加用户 和职位  在职位页面 删减 后  添加用户的职位 还是之前的数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
实时加载不支持，需要您自行修改。
