### ISSUE TITLE
jeecg3.5.0最新版本的nacos无法启动是什么问题？

### ISSUE THREAD

**Issue by huangshengjie** [jeecgboot/jeecg-boot#4744]
##### 截图&代码：
这是nacos依赖
<img width="662" alt="image" src="https://user-images.githubusercontent.com/24750392/227073109-7fb9cef2-d39f-4a78-a800-12224960a51a.png">
这是运行log
<img width="880" alt="image" src="https://user-images.githubusercontent.com/24750392/227072871-d4d8e676-7c8a-47e2-b5b8-47c4d0ebd6dd.png">
<img width="877" alt="image" src="https://user-images.githubusercontent.com/24750392/227072926-12fbf7c9-113c-4a1a-af38-15b90758a963.png">
<img width="874" alt="image" src="https://user-images.githubusercontent.com/24750392/227072985-d8998902-c998-411e-863f-332974c8249b.png">

**Comment by zhangdaiscott** [comment]
配置数据库了吗

**Comment by huangshengjie** [comment]
配置了

**Comment by huangshengjie** [comment]
没有配置数据库肯定是报数据库连接错误的

**Comment by huangshengjie** [comment]
我本地配置的数据库，数据库就叫nacos，账号密码root/root，和jeecg一致，不用做修改，host也配置了
