### ISSUE TITLE
菜单管理中链接中写系统变量无效。

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#4745]
##### 版本号：
3.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
菜单管理中链接中写系统变量无效。想在菜单链接中传登录的username。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/28818320/227080284-843b5454-b7a8-44b6-a92e-cdd298d1f0a3.png)
![image](https://user-images.githubusercontent.com/28818320/227080346-4b176962-0e5c-48cb-bc26-84778623643e.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持这样的功能
