### ISSUE TITLE
Vue3 iframe 组件访问不到 public 文件下的静态资源

### ISSUE THREAD

**Issue by 18237966658** [jeecgboot/jeecg-boot#4746]
##### 截图&代码：
<template>
  <a-modal :title="title" :width="1300" :visible="visible" @cancel="onCancel" :confirmLoading="confirmLoading" :footer="null" switchFullscreen>
    <div style="height: 100%">
      <iframe id="iframe" src="public/static/modeler.html" frameborder="0" width="100%" height="650px" scrolling="auto"></iframe>
    </div>
  </a-modal>
</template>
![image](https://user-images.githubusercontent.com/50265705/227093265-c705542b-5105-4784-8361-ac1a4feccce2.png)
![image](https://user-images.githubusercontent.com/50265705/227093420-cb92f463-2c84-4da7-a4bf-92801e273a01.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://user-images.githubusercontent.com/3162115/227821440-8c7042cf-262b-4c25-89fa-93fcfd51cf55.png)

**Comment by qinghechaoge** [comment]
请问你解决了吗 怎么解决的
