### ISSUE TITLE
租户用户编辑会导致重复添加一模一样的数据

### ISSUE THREAD

**Issue by boywangqin** [jeecgboot/jeecg-boot#4747]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
开启多租户，进入租户用户，点击编辑功能，点击确定，就出现添加了一模一样的租户数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
<img width="1270" alt="1679552362587" src="https://user-images.githubusercontent.com/13937384/227120103-1bd96e0c-ffde-4ec8-8f04-b188f76013d7.png">

  
<img width="1267" alt="1679552417218" src="https://user-images.githubusercontent.com/13937384/227120213-5eb22d0e-1de0-40ca-b1ff-e61cad83b8c4.png">

<img width="1276" alt="1679552450603" src="https://user-images.githubusercontent.com/13937384/227120310-8be458ad-f2b0-4b8d-9594-2f8378684698.png">

**Comment by 1298191366** [comment]
已修复，待新版本发布
