### ISSUE TITLE
Seata示例启动不了

### ISSUE THREAD

**Issue by xy187006** [jeecgboot/jeecg-boot#4748]
##### 版本号：
3.4.4

##### 问题描述：
想要整合seata，启动测试代码失败

##### 截图&代码：
第一次启动报如下错误
![1](https://user-images.githubusercontent.com/51348800/227203212-83368ea2-d2bd-43f9-806e-5781e8c334e2.png)

在配置文件中添加    
 spring.main.allow-bean-definition-overriding: true 
后启动又报如下错误
![2](https://user-images.githubusercontent.com/51348800/227203130-e053bca2-5057-4abe-b26a-455a8939ec85.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by miniFrank** [comment]
这个问题已经找到了，后续会提交PR，谢谢反馈

**Comment by javaow** [comment]
还是不能启动 如上第二个问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/89126850/e090df69-b11e-4808-b98e-ac34cc7e41f3)

**Comment by javaow** [comment]
解决了 将nacos配置加上就好了，需要读取yaml，也不知道是不是大佬代码忘记提交了
![image](https://github.com/jeecgboot/jeecg-boot/assets/89126850/b6387c8d-c553-4f5a-accc-b62d860b3e06)

**Comment by zhangdaiscott** [comment]
好了，请更新代码
