### ISSUE TITLE
Online在线表单不能正常编辑

### ISSUE THREAD

**Issue by zj14261535** [jeecgboot/jeecg-boot#4749]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
新的主分支,还没有做过任何开发或修改的状态
3.4.3版本
自己用navicat 16建了表,倒进Online在线,然后Online上编辑这个表,点击保存就一直转圈,不能完成编辑

##### 截图&代码：
![微信截图_20230324104947](https://user-images.githubusercontent.com/17996423/227411870-6e47fcf3-d90e-4676-b1f8-8430ec02713f.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看什么错误

**Comment by zj14261535** [comment]
有访问editAll接口 但是接口没有相应

**Comment by zj14261535** [comment]
后端也完全没有反应 就没有访问到接口

**Comment by zhangdaiscott** [comment]
好像有个这个bug处理过，你下载最新的试试
