### ISSUE TITLE
Online表单文本框如何输入默认去掉前后空格？

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#4750]
##### 版本号：
3.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online表单文本框如何输入默认去掉前后空格？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前后端空格是什么意思？

**Comment by snkever** [comment]
文本框里保存时，去掉字符串两侧的空白字符。trim功能


| |
snkever
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年3月27日 09:47 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] Online表单文本框如何输入默认去掉前后空格？ (Issue #4750) |

前后端空格是什么意思？

**Comment by zhangdaiscott** [comment]
你是自己输入了空格，想自动trim把，这样的需求不能做，万一别人需要空格呢
