### ISSUE TITLE
在线测试中点击行数据的“编辑”时，无法转义字典字段

### ISSUE THREAD

**Issue by WeiFengo** [jeecgboot/jeecg-boot#4751]
##### 问题描述：
在线测试中点击行数据的“编辑”时，无法转义字典字段。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/103655726/227451625-d357ca93-a75e-414b-b8a7-b1bed7fe575b.png)
![image](https://user-images.githubusercontent.com/103655726/227451702-74d7304a-e864-4942-8378-8b1d900a07a1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by WeiFengo** [comment]
![image](https://user-images.githubusercontent.com/103655726/227456246-ee9cfe75-4469-40b0-a804-22af46901e7d.png)
字段类型为Integer时，存在此问题，String时可以正常转义

**Comment by zhangdaiscott** [comment]
ty

**Comment by zhangdaiscott** [comment]
jl

**Comment by tygithub1** [comment]
已修改
