### ISSUE TITLE
建议多租户模式下只允许未关联任何租户的用户才能看到租户列表界面

### ISSUE THREAD

**Issue by chenkline** [jeecgboot/jeecg-boot#4753]
### 版本号：
v3.5.0

### 前端版本：
vue3

### 问题描述：
切换到多租户模式下时，关联了租户的用户在列表界面也能看到所有租户，建议只允许未关联租户的用户才能看到租户列表界面，或者只允许用户看到本用户的关联租户
建议规则：没有关联租户的用户，其数据权限不受租户范围限制，关联了租户的用户，其数据权限被限制在关联租户的范围内

### 截图&代码：
无

### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
租户列表是给超级管理员看的，不是给普通租户下的用户看的，你可以通过授权角色实现不同的人看不同的菜单

**Comment by zhangdaiscott** [comment]
具体用法参考 “敲敲云”

**Comment by guojingbing** [comment]
多租户的说明文档在哪儿？开发文档里都是旧的啊

**Comment by guojingbing** [comment]
> 多租户的说明文档在哪儿？开发文档里都是旧的啊

**Comment by guojingbing** [comment]
> 

多租户的说明文档在哪儿？开发文档里都是旧的啊

**Comment by zhangdaiscott** [comment]
http://help.jeecg.com/javaback/saas.html

**Comment by guojingbing** [comment]
> 租户列表是给超级管理员看的，不是给普通租户下的用户看的，你可以通过授权角色实现不同的人看不同的菜单

现在给租户用户分配操作权限只能通过租户管理的套餐中的产品包邀请用户，那租户如何自己管理自己租户下的租户用户权限呢？
