### ISSUE TITLE
单体架构模式下集成分库分表无法成功

### ISSUE THREAD

**Issue by xuxin468** [jeecgboot/jeecg-boot#4754]
##### 版本号：
3.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
按照官方文档：单体架构模式下集成分库分表整合案例，整合单体下分表不成功，无法正常分表插入不同sys_log，检查日志发现分表sharding的DataSoure未成功加载，具体见下图
##### 截图&代码：

![image](https://user-images.githubusercontent.com/36890132/227722915-e6411fc7-3d78-44c5-b2af-6401e8ec5ca6.png)

**Comment by lzz2017** [comment]
我单体下集成也失败

**Comment by DotNeter-Hpf** [comment]
请问楼上已经解决了吗，我也遇到问题，按照文档操作不行
