### ISSUE TITLE
请问JVxeTable如何实现表头分组？

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecg-boot#4755]
##### 版本号：
最新版

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
JVxeTable如何实现表头分组，BaseTable有children参数实现分组，JVxeTable如何实现？
看了代码好像没封装vxe-colgroup，
而如果采用传统标签方式<vxe-colgroup>来实现分组的话，
jeecgboot的自定义组件JVxeTypes.select等就无法使用。
以上，请确认。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by IVanMissAya** [comment]
遇到一样的问题了.. 请问大佬解决了吗？
![Z42QZL 3FYT2@SLO~N}1P07](https://github.com/jeecgboot/jeecg-boot/assets/38241168/9b27020b-e366-4dfb-acd5-f70d10a77bd2)
![XBC%~2S@YE }$PL1U7NZ5 S](https://github.com/jeecgboot/jeecg-boot/assets/38241168/37fb57fd-8fdc-41b4-b88c-c7d5ef65d8e4)
