### ISSUE TITLE
netty的jar包不全

### ISSUE THREAD

**Issue by MasterDDD** [jeecgboot/jeecg-boot#4756]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/40188720/227857899-84d3f090-abfb-4007-91f8-2c1dab8d2d90.png)

![image](https://user-images.githubusercontent.com/40188720/227858123-678eeee7-422f-47ed-861e-62c471002093.png)

请问有什么办法解决吗？

**Comment by zhangdaiscott** [comment]
可以改
