### ISSUE TITLE
Required String parameter 'token' is not present

### ISSUE THREAD

**Issue by haodongheng-cool** [jeecgboot/jeecg-boot#4757]
##### 版本号：
2.3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
我通过vue2登录，后端为2.3.0版本，登录时候报错Required String parameter 'token' is not present，应该是缺少token参数，这个怎么解决呢，一登录就报错然后自动退出，或者有什么方法不登录直接进入后台吗

##### 截图&代码：
![image](https://user-images.githubusercontent.com/71823737/227894343-7154b901-6ecf-46e7-ad33-704ec6cf64fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jeecg 2.3版本吗？ 很老了

**Comment by haodongheng-cool** [comment]
还有个问题是，直接导入db/sql文件会失败，
![image](https://user-images.githubusercontent.com/71823737/227900986-a74cbc14-9a35-4111-a91b-fc6661156509.png)

**Comment by zhangdaiscott** [comment]
版本太老了
