### ISSUE TITLE
使用saveBatch无法批量插入数量，提示主键重复

### ISSUE THREAD

**Issue by lijinlang** [jeecgboot/jeecg-boot#4758]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

使用在controller中调用saveBatch方法，无法批量插入数据，主键ID重复

##### 截图&代码：

![微信图片_20230327200502](https://user-images.githubusercontent.com/54636793/227936906-0788db56-1f6f-4bb1-a287-eb88182110b4.png)

**Comment by zhangdaiscott** [comment]
生成的代码？还是那个功能

**Comment by lijinlang** [comment]
> 生成的代码？还是那个功能

   是的在生成的controller中加了个方法，就是批量保存saveBatch方法，多少条记录ID都是同一个，提示主键重复。不用saveBatch方法，改成for循环调用save方法一样也是产生同个ID无法保存。

   现在只能在保存之前自己先手工生成个UUID赋值给每条记录ID再用for循环插入，如果调用saveBatch即使手工生成ID一样也是不行，同样提示ID重复无法插入，跟上片图片上的一样，所有记录都变成同一个ID。

**Comment by zhangdaiscott** [comment]
你自己写的saveBatch？

**Comment by lijinlang** [comment]
> 你自己写的saveBatch？

没有啊，就是IService里的saveBatch啊，批量保存就是会主键重复啊

**Comment by zhangdaiscott** [comment]
贴代码

**Comment by lijinlang** [comment]
> 贴代码

这个是我目前的实现方法，本想用实体的数组直接调用saveBatch批量保存搞不定，现在只能先改成用for单条插入了。

![微信图片_20230330145653](https://user-images.githubusercontent.com/54636793/228755113-e7727a06-6079-460c-8bc3-162026cd3e9a.png)

**Comment by zhangdaiscott** [comment]
例子没问题
![image](https://user-images.githubusercontent.com/3162115/230054585-33024359-03b2-40ef-a703-448686b28a79.png)
