### ISSUE TITLE
3.4.4，Vue3版本，online在线表单，下拉联动在线测试可行，代码生成后无联动效果

### ISSUE THREAD

**Issue by HHC0541** [jeecgboot/jeecg-boot#4760]
##### 问题描述：
online在线表单，下拉联动在线测试可行，代码生成后运行的无联动效果

##### 截图&代码：
在线测试有对应效果：
<img width="887" alt="image" src="https://user-images.githubusercontent.com/56616772/228110192-02bf5873-eb52-4f7d-ae05-650ad9bec085.png">

代码生成后效果：
<img width="947" alt="image" src="https://user-images.githubusercontent.com/56616772/228110339-d4fd0cdd-b7db-4a09-a93a-5f8a2294cfa8.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
联动组件不支持生成

**Comment by HHC0541** [comment]
您的来信已接收，感谢您的来信！
