### ISSUE TITLE
表sys_depart的org_code有两个索引

### ISSUE THREAD

**Issue by jin2001** [jeecgboot/jeecg-boot#4761]
##### 截图&代码：
   UNIQUE INDEX `uniq_depart_org_code`(`org_code`) USING BTREE,
  INDEX `idx_sd_parent_id`(`parent_id`) USING BTREE,
  INDEX `idx_sd_depart_order`(`depart_order`) USING BTREE,
  INDEX `idx_sd_org_code`(`org_code`) USING BTREE

**Comment by jin2001** [comment]
sys_role也有同样的。
字段role_code有两个索引。一个是唯一索引。一个是普通索引
截图&代码：
 UNIQUE INDEX `uniq_sys_role_role_code`(`role_code`) USING BTREE,
  INDEX `idx_sr_role_code`(`role_code`) USING BTREE

**Comment by jin2001** [comment]
另外，关于索引我不太明白。
sys_user的索引，以下两个字段的值的区分度不大，用索引有什么好处吗？
截图&代码：
`status` tinyint(1) NULL DEFAULT NULL COMMENT '性别(1-正常,2-冻结)',
 `del_flag` tinyint(1) NULL DEFAULT NULL COMMENT '删除状态(0-正常,1-已删除)',

  INDEX `idx_su_status`(`status`) USING BTREE,
  INDEX `idx_su_del_flag`(`del_flag`) USING BTREE

**Comment by zhangdaiscott** [comment]
加重复了，删了非唯一索引就行
