### ISSUE TITLE
字段命名不能以单个字母加下滑线开头

### ISSUE THREAD

**Issue by zhangjian4** [jeecgboot/jeecg-boot#4763]
##### 问题描述：
事情是这样的，现在要替换老的一套系统，但是不能直接把原系统下线，所以和原系统公用数据库，表结构不能修改，现在通过导入数据库表功能生成了一个在线表单，生成是成功了，但是想修改一下页面属性保存不了，提示不能以单个字母加下滑线开头，想知道为什么会有这个限制

##### 截图&代码：

![image](https://user-images.githubusercontent.com/23302214/228409930-4b0de035-bbe5-4e44-a93b-4d620f4aa374.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你这样的要求不符合我们的规范
