### ISSUE TITLE
新建菜单使用外部路由不进行跳转

### ISSUE THREAD

**Issue by lego2533** [jeecgboot/jeecg-boot#4764]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 截图&代码：

![image](https://user-images.githubusercontent.com/82588178/228459936-efd69ec3-4f07-4e0b-b816-966148f99d5b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
参考下项目里的例子，看看哪里配置不对
