### ISSUE TITLE
当前vue2如何实现按需加载？  每次点击一个模块都需要加载一段时间

### ISSUE THREAD

**Issue by 2morning** [jeecgboot/jeecg-boot#4766]
##### 截图&代码：
![Uploading 1680080365240.jpg…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前就是分页加载的啊

**Comment by 2morning** [comment]
可以告诉我分页加载的代码在哪定义的吗 ？  那前端点进一个模块的耗时还有其他可优化的思路吗

**Comment by 2morning** [comment]
nginx压缩已经开启了
