### ISSUE TITLE
部门数据权限

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4770]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
通过online在线生成，使用部门组件，发现部门组件是加载所有部门，调用后台方法queryTreeList，也就是说当新建管理用户只管理子级部门时，查询部门还是加载的全部部门，无法做到只能看自己部门的数据

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/228810422-23211f7a-0426-4dd9-bef9-af7cc466b213.png)
![image](https://user-images.githubusercontent.com/90361617/228810638-fd5aaaf0-a476-4067-b8d2-df8d9ffe1e96.png)
![image](https://user-images.githubusercontent.com/90361617/228810908-4e40ab3c-b06c-4953-bca2-9505d48f5fb1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044050
