### ISSUE TITLE
用户组件数据权限

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4771]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
新增了管理员用户，只能管理二级部门，但是使用用户组件加载的还是全部部门，应该正确的话是只能加载本级部门吧

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/228820683-8b85c021-8812-4bc2-870d-05bb85d05186.png)
![image](https://user-images.githubusercontent.com/90361617/228822930-cd8679d6-bd56-4566-b8c0-9a65eec7e814.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
理解不对，看这个
http://doc.jeecg.com/2044050

**Comment by 3509282792** [comment]
可能是我没描述清楚，我要的功能是当我设置的权限只能管理子级部门时，那么查询栏中的用户组件弹窗也应该只加载负责的部门，而不是加载全部部门，比如我上图，分配了二级部门C，那么用户组件这个应该也只能加载二级部门C才对
