### ISSUE TITLE
vue3版本中缺失sys_permission_v3 

### ISSUE THREAD

**Issue by dcempire** [jeecgboot/jeecg-boot#4772]
##### 版本号：

3.5
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
看前端 文档要切换央vue3路由
alter table sys_permission rename as sys_permission_v2;
alter table sys_permission_v3 rename as sys_permission;
但数据库中没有  sys_permission_v3 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前最新版不需要切换了，默认就是vue3的菜单表
