### ISSUE TITLE
自动锁屏输入用户登录密码失败

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecg-boot#4773]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
自动锁屏输入用户登录密码，进入系统失败，接口可能需要调整。退出登录的话，再次登录后，自动锁屏信息不会清除。

##### 截图&代码：

![bug2](https://user-images.githubusercontent.com/23712951/229015450-dd715021-3eed-4b12-bbb5-949db290849a.png)
![bug3](https://user-images.githubusercontent.com/23712951/229015456-ed1b1eea-56ed-4762-a6c5-ffc2df7dc968.png)
![bug4](https://user-images.githubusercontent.com/23712951/229015459-0940962e-52e6-4b34-802a-7cd6bccf9a56.png)
![bug1](https://user-images.githubusercontent.com/23712951/229015460-3425511b-a531-46e2-9e47-63f142f68d81.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by cdsuifeng** [comment]
再次登录后，自动锁屏信息不会清除   这一点建议可以自定义配置项，设置是否下次登录是否清除

**Comment by zhangdaiscott** [comment]
锁屏密码，不是登录用户的密码，是你设置的锁屏密码

**Comment by cdsuifeng** [comment]
但是自动锁屏是没有设置密码的地方的，前端会走 /login 接口

**Comment by zhangdaiscott** [comment]
你肯定手工点击过锁屏，那个点击的时候会让你设置个密码，你忘记了
![image](https://user-images.githubusercontent.com/3162115/230254747-51d509d2-367d-4700-863f-dfde8c4b0320.png)
