### ISSUE TITLE
mvn 命令生成微服务模块，parent pom.xml 文件中文乱码

### ISSUE THREAD

**Issue by shanggushenlong** [jeecgboot/jeecg-boot#4775]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用 通过mvn 命令生成微服务模块 jeecg-module-erp，按照文档操作生成模块后，parent 的 pom.xml 文件中文乱码，并且pom.xml 文件多一行代码

##### 截图&代码：
![image](https://user-images.githubusercontent.com/20007857/229037722-6550dd08-51e4-4833-b9d9-749ac022055d.png)
![image](https://user-images.githubusercontent.com/20007857/229037802-979431a0-d7dd-428c-9fd6-0b9e948f9bc0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by miniFrank** [comment]
你好，你的执行环境和命令还请粘贴下。

**Comment by miniFrank** [comment]
你好，你的执行环境还方便告知下(mvn -version)？
我如下环境：
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 19.0.2, vendor: Oracle Corporation
Java home: /Users/pgh/Library/Java/JavaVirtualMachines/openjdk-19.0.2/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"

执行结果：
1. 会多一行文件编码头；
2. 没有出现中文乱码；

**Comment by miniFrank** [comment]
你好，为了更进一步排查问题，您的执行环境还方便告知下(mvn -version)？以下是我的环境和说明
1. 如下环境：
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 19.0.2, vendor: Oracle Corporation
Java home: /Users/pgh/Library/Java/JavaVirtualMachines/openjdk-19.0.2/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"
2. 执行命令：
   mvn archetype:generate \
   -DgroupId=org.jeecg.modules.order \
   -Dmodule=order\
   -Dmodule-up-first=Order\
   -DartifactId=jeecg-module-order \
   -Dversion=3.5.0\
   -DarchetypeGroupId=org.jeecgframework.archetype \
   -DarchetypeArtifactId=jeecg-cloud-gen \
   -DarchetypeVersion=3.4.0

3. 执行结果：
3.1 会多一行文件编码头；
3.2 没有出现中文乱码；
![image](https://user-images.githubusercontent.com/3614917/230750085-44de4f6e-a0af-47ee-83bb-a18068ad16c8.png)

**Comment by shanggushenlong** [comment]
> 你好，为了更进一步排查问题，您的执行环境还方便告知下(mvn -version)？以下是我的环境和说明
> 
> 1. 如下环境：
>    Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
>    Maven home: /usr/local/Cellar/maven/3.3.9/libexec
>    Java version: 19.0.2, vendor: Oracle Corporation
>    Java home: /Users/pgh/Library/Java/JavaVirtualMachines/openjdk-19.0.2/Contents/Home
>    Default locale: zh_CN_#Hans, platform encoding: UTF-8
>    OS name: "mac os x", version: "12.6.2", arch: "x86_64", family: "mac"
> 2. 执行命令：
>    mvn archetype:generate 
>    -DgroupId=org.jeecg.modules.order 
>    -Dmodule=order
>    -Dmodule-up-first=Order
>    -DartifactId=jeecg-module-order 
>    -Dversion=3.5.0
>    -DarchetypeGroupId=org.jeecgframework.archetype 
>    -DarchetypeArtifactId=jeecg-cloud-gen 
>    -DarchetypeVersion=3.4.0
> 3. 执行结果：
>    3.1 会多一行文件编码头；
>    3.2 没有出现中文乱码；
>    ![image](https://user-images.githubusercontent.com/3614917/230750085-44de4f6e-a0af-47ee-83bb-a18068ad16c8.png)

1. 环境如下：
![image](https://user-images.githubusercontent.com/20007857/230752045-e0face10-3fe9-41d9-b8ca-fb93a2ce5e1f.png)

2. 执行的脚本命令是官方文档，一字没改

**Comment by shanggushenlong** [comment]
是否是因为我 windows的电脑 platform encoding 是 GBK 编码导致

**Comment by zhangdaiscott** [comment]
可能

**Comment by miniFrank** [comment]
> 

mvn -Dfile.encoding="UTF-8" 加个参数试下
