### ISSUE TITLE
queryWrapper.like模糊查询拼接SQL错误

### ISSUE THREAD

**Issue by Durant-Wen** [jeecgboot/jeecg-boot#4779]
##### 截图&代码：
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/46209098/229400814-c7beb30b-391f-49d6-b60b-78c9af08f508.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
得看你装载查询条件的地方，应该先是装载了一个等于查询
