### ISSUE TITLE
vue3文档部署ng配置问题

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecg-boot#4781]
##### 版本号：

3.5.0
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
在vue3文档中，上线部署-快速部署，二、通过nginx部署前端  中 ng配置缺失 导致websocket 连不上。

##### 截图&代码：
![bug5](https://user-images.githubusercontent.com/23712951/229447152-e468720a-fd8e-4923-840d-864e9eab279a.png)
![bug6](https://user-images.githubusercontent.com/23712951/229447171-54f6ac4c-1267-4b3c-bfa7-83deece35b8a.png)
![bug7](https://user-images.githubusercontent.com/23712951/229447420-be3eccf1-898c-4769-93fd-9916c24f14dc.png)

建议补全以下配置：
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个https配置属于个性化配置，没必须硬性加到文档中，会增加其他人的学习成本。
需要的同学，一般都会
