### ISSUE TITLE
online 表单列表里怎么把右侧的操作区，改成左侧，

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4783]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
online 表单怎么把右侧的操作区，改成左侧？
vue3 就有这个功能，vue2 能不能进行修改

##### 截图&代码：

![image](https://user-images.githubusercontent.com/19221237/229677553-e05a20a7-08d8-458e-b120-83f8619c842c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2不支持

**Comment by Sunnyweii** [comment]
Vue3上的功能在哪里配置？怎么配置？
