### ISSUE TITLE
j-multi-select-tag多选变形

### ISSUE THREAD

**Issue by lhpdemo** [jeecgboot/jeecg-boot#4785]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用j-multi-select-tag进行多选时，数据太长导致变形

##### 截图&代码：
![image](https://user-images.githubusercontent.com/97373576/229752102-ebd86986-f0d6-4581-b78e-d752ed7a727b.png)
<a-form-model-item label="行业范围：" prop="type" :lableCol="labelCol" :wrapperCol="wrapperCol">
                    <j-multi-select-tag
                      v-model='queryCriteria.type'
                      :options='ccerSelectDataSource'
                      placeholder="请选择行业范围"
                      >
                    </j-multi-select-tag>
                 </a-form-model-item>

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
你可以手动将`GlobalLayout.vue`中的`.ant-form-item-control`类样式`height`注释掉，或在单独页面中写样式进行覆盖
![image](https://user-images.githubusercontent.com/30997828/230266126-3e3be6d0-e4dd-4989-bf86-2808834e0530.png)
