### ISSUE TITLE
Shiro权限新加了一条防止拦截的链接，但是启动后请求还是显示身份认证失败

### ISSUE THREAD

**Issue by mob-sdk** [jeecgboot/jeecg-boot#4786]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
添加了链接，请求后依然显示401

##### 截图&代码：

![23671680660854_ pic](https://user-images.githubusercontent.com/32882824/229963606-464c53b2-96e7-4cc6-834b-0046b4d4fb78.jpg)
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/32882824/229963637-f9c44b71-5fef-4ecc-a206-402476467004.png">
<img width="1483" alt="image" src="https://user-images.githubusercontent.com/32882824/229963660-d20369c8-42a3-48dc-8ad8-586cdbc1bf12.png">
![image](https://user-images.githubusercontent.com/32882824/229963714-62a79568-5cab-4b5b-8f8e-a07e0b191bf0.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不清楚

**Comment by zhangdaiscott** [comment]
core 项目install?

**Comment by mob-sdk** [comment]
重新install很多次了，还是不行

**Comment by 1369521908** [comment]
我也遇到这个问题了 也是重新把core install 了很多次 还是不行

**Comment by mob-sdk** [comment]
我感觉就是这个代码的bug，必须放到那个demo里，才能执行那个防止过滤，其他新建的任何module都会被认为需要token

**Comment by mob-sdk** [comment]
单步执行的时候只有demo不会跳那个检测token的方法

**Comment by mob-sdk** [comment]
我现在有问题，你不给我解决，而是立刻关闭issue？什么意思？

**Comment by mob-sdk** [comment]
如果重新install能好，我就不会创建这个issue

**Comment by 1369521908** [comment]
因为在输出认证失败那个日志 路径是error的 
![image](https://user-images.githubusercontent.com/32727597/230805245-f95a0a80-450d-4e8c-9bff-2a94d30fae0a.png)

于是我就把/error配置过滤了再次重新启动
![image](https://user-images.githubusercontent.com/32727597/230805272-9c03924f-a357-4a88-8887-f9cd88e9e773.png)

执行的时候 是报了404了
![image](https://user-images.githubusercontent.com/32727597/230805328-469388e3-2e6b-4533-8728-6fe00a987697.png)

**Comment by 1369521908** [comment]
我找到解决方法了
要在start模块上面加上业务模块的依赖 重新启动就行了
![image](https://user-images.githubusercontent.com/32727597/230805667-f5310bdc-f835-4b7c-83ad-66fbad55e890.png)
