### ISSUE TITLE
积木报表无法解析API接口

### ISSUE THREAD

**Issue by libing83** [jeecgboot/jeecg-boot#4788]
##### 截图&代码：
界面操作报错如下：
![image](https://user-images.githubusercontent.com/13805923/230263105-7f813f45-1b82-46af-b6df-608fe2599f2a.png)

直接访问接口有数据返回，按照要求封装的data
![image](https://user-images.githubusercontent.com/13805923/230262982-7ee7a6cf-8aaf-44c4-8420-a21fcff94a2b.png)

后台运行日志：
![image](https://user-images.githubusercontent.com/13805923/230263172-b2c12bed-7b8a-4c90-ba04-fa87a26964eb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
看提示，说明你返回的数据为空或者格式不对
![image](https://user-images.githubusercontent.com/3162115/230281270-c3c59cb4-4a59-44b8-85bf-0ffec6cd9c50.png)

**Comment by libing83** [comment]
我问题里面有贴图哦，接口单独访问是有数据的。并且我点击解析后，自定义接口的后台日志里面也没有接收到请求数据。不知道该如何排查了

**Comment by libing83** [comment]
根据帮助文档中设定token的方式，进行了指定，但是后台始终获得的是固定值：token value 2
![image](https://user-images.githubusercontent.com/13805923/230331928-4132d2b1-14a4-41b9-84ad-4279f66fd3e5.png)

**Comment by jxlgzwh** [comment]
我也碰到类似问题，不知道哪里有问题
