### ISSUE TITLE
用户组件数据权限

### ISSUE THREAD

**Issue by 3509282792** [jeecgboot/jeecg-boot#4789]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
我有个yanglihang用户，这个用户只有二级部门C的部门权限，但是查询栏用的用户组件，选择部门的话还是全部部门，这是为什么，已经再部门角色那里分配了菜单权限，好像没什么用

##### 截图&代码：
![image](https://user-images.githubusercontent.com/90361617/230275363-61584250-6a66-449a-91b9-dd6fdfdd9ae3.png)
![image](https://user-images.githubusercontent.com/90361617/230275577-fd983e4d-8248-47b5-9e16-622506ab06f8.png)
![image](https://user-images.githubusercontent.com/90361617/230275682-41f42fe6-eff4-4442-846c-c68a104c8b85.png)
![image](https://user-images.githubusercontent.com/90361617/230275733-a0d9a158-d92e-47f7-93ae-7e49130fb242.png)
![image](https://user-images.githubusercontent.com/90361617/230275843-6877e423-3586-49e2-8ebc-5a5013774a92.png)
![image](https://user-images.githubusercontent.com/90361617/230276051-4ae54bf2-11ba-4aad-b183-1bedc7c70969.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复问题不要提

**Comment by 3509282792** [comment]
> 重复问题不要提

老哥，我的问题没有解决呢。。那个用户组件支持我提的问题吗

**Comment by zhangdaiscott** [comment]
已经回复过了，我们的设计不是你的需求

**Comment by 3509282792** [comment]
> 已经回复过了，我们的设计不是你的需求

是不是要实现我的那个部门数据权限控制需求得自己二次开发才行呀？你们的这个是不支持吗？

**Comment by 3509282792** [comment]
> 已经回复过了，我们的设计不是你的需求

老哥教下我，指导下。。感谢感谢，困惑我了好久了

**Comment by zhangdaiscott** [comment]
自己二开实现

**Comment by 3509282792** [comment]
> 自己二开实现

谢谢。
