### ISSUE TITLE
普通用户注册配置权限后登录404

### ISSUE THREAD

**Issue by mygeorge** [jeecgboot/jeecg-boot#4792]
##### 版本号：
3.4.3last

##### 前端版本：vue3版？还是 vue2版？

vue2 版
##### 问题描述：
在admin,管理员账户下，新建角色，新建普通用户分配菜单权限，使用新注册的用户账号密码登录，登录后，提示登录成功，页面报404

##### 截图&代码：

![864b952344e500b2897f2d215d31daf](https://user-images.githubusercontent.com/52056350/230297514-2f5635a9-c7ec-4521-aa51-1e3928109c4b.png)

![721b45fa23ac95ac15a5e6fbb2d063d](https://user-images.githubusercontent.com/52056350/230297557-bfc90af2-9852-42ea-aa13-3b1ec819817c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不要提重复问题

**Comment by mygeorge** [comment]
刚刚那个不符合要求，给我删除 了

**Comment by 2428552874** [comment]
请问这个问题解决了吗

**Comment by modakai** [comment]
解决了吗；我也遇到了，就普通用户第一次登入的时候，永远都是404。第二次就会进入首页，并且我早给普通用户角色赋予首页的权限
