### ISSUE TITLE
websocket 关闭问题

### ISSUE THREAD

**Issue by MasterDDD** [jeecgboot/jeecg-boot#4795]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/40188720/230354618-930b0015-2e28-4d46-959c-d46286f1a0af.png)

![image](https://user-images.githubusercontent.com/40188720/230354654-0a9a5657-9f2f-4f9f-a441-85b92feb922c.png)

**Comment by zhangdaiscott** [comment]
自己写的代码，请自己排查
