### ISSUE TITLE
vue3中，针对于主子表，如何在子表中获取到主表某个字段的值，并且将该值作为JVxeTypes.selectDictSearch中dict的过滤条件

### ISSUE THREAD

**Issue by liqingelio** [jeecgboot/jeecg-boot#4796]
##### 截图&代码：
![1680783040033](https://user-images.githubusercontent.com/38447510/230375038-d92a21a4-cb86-411a-ba20-9456b1652a48.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
主表的值更新时，手动写代码改一下子表column的dict字段即可。
