### ISSUE TITLE
popup弹出框使用j-editable-table 缺失行数据

### ISSUE THREAD

**Issue by yimogithub** [jeecgboot/jeecg-boot#4798]
##### 问题描述：

popup弹出框使用j-editable-table ，当popup弹出框内容高度超过一屏，且设置较高的 j-editable-table高度，会丢失行数，高度越高，丢失行数越多。

例如online表单开发中的编辑页面，将j-editable-table 设置1000 ，就会出现行数缺失bug。

##### 截图&代码：

![image](https://user-images.githubusercontent.com/44832000/230535785-a3226813-e602-4f0c-9dd1-9616c93530f1.png)

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布。更新后可以设置新参数`maxShowLines`来设置最大显示行数，由于显示过多输入框，所以限制了最大显示行数，不建议把行数调太高，否则会导致根据设备性能造成不同程度的卡顿。

![image](https://user-images.githubusercontent.com/34293221/231151907-11d4e994-fba0-40f7-8bac-f0984df51bb7.png)
