### ISSUE TITLE
jeecg-system服务出现 Customize redis listener handle [ loderRouderHandler ], does not exist！如何解决

### ISSUE THREAD

**Issue by austinuMyaccount** [jeecgboot/jeecg-boot#4799]
##### 版本号：
jeecg-boot-3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
jeecg-system服务出现
org.jeecg.common.util.SpringContextHolder:53[0;39m - Customize redis listener handle [ loderRouderHandler ], does not exist！

##### 截图&代码：
2023-04-07 12:18:35.017 [redisContainer-2] [31mWARN [0;39m [36morg.jeecg.common.util.SpringContextHolder:53[0;39m - Customize redis listener handle [ loderRouderHandler ], does not exist！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by austinuMyaccount** [comment]
服务启动的时候就有这个bug

**Comment by austinuMyaccount** [comment]
gateway 使用database路由，进行保存或者修改路由调用接口的时候也会出现这个bug。

**Comment by zhangdaiscott** [comment]
不影响功能，忽略即可

**Comment by zhangdaiscott** [comment]
如果影响功能，请提供详细的重现步骤

**Comment by bob920304** [comment]
开一个application监听类   调用 ConfigurableApplicationContext 获取RedisMessageListenerContainer,然后把这个类stop就可以了
