### ISSUE TITLE
前端public文件下html访问不到

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#4801]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
为了实现pdf预览，我在前端public文件夹新增了pdfjs文件夹，想直接访问html文件，后端进行了忽略鉴权
但是访问的时候 还是进入带菜单的404页面 用iframe访问也是一样

是我哪里配置错了吗？请指点，谢谢
##### 截图&代码：
1.public下pdfjs文件夹
![image](https://user-images.githubusercontent.com/3311840/230652818-75031951-6f7b-4132-acd7-032753d8b82a.png)
2.访问404
![image](https://user-images.githubusercontent.com/3311840/230652908-839c452a-ef12-4a3d-83a6-4678f1ea2e6a.png)
3.后端进行了忽略拦截
![image](https://user-images.githubusercontent.com/3311840/230653023-081da407-0ef0-4146-b2dd-7d3809671b9a.png)
![image](https://user-images.githubusercontent.com/3311840/230653160-f9714e4e-f8fa-4941-afae-66641e19b4d5.png)

**Comment by zhangdaiscott** [comment]
这是后台的资源，你截图的又是前端的，二者不要混

**Comment by qinghechaoge** [comment]
> 这是后台的资源排除，你截图的又是前端的，二者不要混

我知道，只是不能访问，我才病急乱投医的 现在我是注释掉configHtmlPlugin解决的

![image](https://user-images.githubusercontent.com/3311840/233819910-2a236da2-412d-4184-b545-c8306cae13b9.png)
![image](https://user-images.githubusercontent.com/3311840/233819956-b1f78845-866d-40fb-9186-778fe0fdbb90.png)

有没有别的办法？

**Comment by hyhff** [comment]
解决了吗

**Comment by 1zlk** [comment]
解决了么，我也遇到了，public下放html文件，按照直接url格式访问，被重定向到首页去了
