### ISSUE TITLE
@Excel导出模板时候如何设置单元格为下拉框格式并添加下拉框数据

### ISSUE THREAD

**Issue by oday-xiexin** [jeecgboot/jeecg-boot#4803]
##### 版本号：
最新版
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
@Excel导出模板时候如何设置单元格为下拉框格式并添加下拉框数据

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by oday-xiexin** [comment]
> 不支持


> 不支持
有计划支持一下吗

**Comment by zhangdaiscott** [comment]
没有，个性化需求，自己二开实现吧

**Comment by oday-xiexin** [comment]
> 没有，个性化需求，自己二开实现吧

哥 能帮忙在autopoi那个项目下 推下1.4.5最新代码吗 辛苦了

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/autopoi

**Comment by oday-xiexin** [comment]
> https://github.com/jeecgboot/autopoi

是的 我看tag最新代码是1.4.3 但是boot项目已经在用1.4.5了
