### ISSUE TITLE
Online报表配置带参数失效

### ISSUE THREAD

**Issue by xinuo** [jeecgboot/jeecg-boot#4805]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
Online报表配置 -> 编写带参数的语句，查询时候连接带参数了，会报错，然后查询的是默认值。。
例如:
select * from demo where key_word = '${key_word}'

##### 截图&代码：
后台提示。
![image](https://user-images.githubusercontent.com/7897771/230877295-3ac62185-b7f3-4394-bf72-b93362c0472f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
菜单怎么配置的，说明你参数没解析成值

**Comment by zhangdaiscott** [comment]
测试无问题
