### ISSUE TITLE
导出大量数据内存溢出问题

### ISSUE THREAD

**Issue by fengliu-A** [jeecgboot/jeecg-boot#4809]
##### 版本号：
3.2.0

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

调用exportXls导出大量数据（几十万，存在一定的并发），出现内存溢出的情况（服务器内存32g），f服务器中存在大量close_wait,并爆出：java.lang.OutOfMemor yError: GC overhead limit exceedec
##### 截图&代码：

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/117929123/230924934-dfe4aaba-fe0a-4006-9dc1-ce052f56464b.png">
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/117929123/230925068-e800a83a-9b7f-45b5-b07f-71f37319472e.png">

**Comment by fengliu-A** [comment]
![image](https://user-images.githubusercontent.com/117929123/230927164-1a90e57d-2c20-456d-88ae-e6434b37ecf1.png)

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2595247

**Comment by fengliu-A** [comment]
> http://doc.jeecg.com/2595247

您看一下是不是导出的时候有流没关，可以优化一下

**Comment by fengliu-A** [comment]
> http://doc.jeecg.com/2595247

您看一下是不是导出的时候是不是有流没关，可以优化一下
