### ISSUE TITLE
数据库id主键使用bigint 使用 Online表单会有精度丢失问题 以及解决方案

### ISSUE THREAD

**Issue by GuanWeiGit** [jeecgboot/jeecg-boot#4811]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
数据库id主键使用bigint 使用 Online表单会有精度丢失问题

##### 截图&代码：
![image](https://user-images.githubusercontent.com/74446777/231040937-8e470964-0bb6-4f7e-8cc6-24bd7097f565.png)

##### 解决方案
org.jeecg.config.WebMvcConfiguration
修改这个方法
org.jeecg.config.WebMvcConfiguration#objectMapper

`        //这里避免精度丢失问题
        //JSON Long ==> String
        javaTimeModule.addSerializer(Long.class, ToStringSerializer.instance);`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
我们默认用的是string，不建议用Long类型
