### ISSUE TITLE
后端线上总是自莫名其妙挂掉

### ISSUE THREAD

**Issue by lhpdemo** [jeecgboot/jeecg-boot#4812]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？
2

##### 问题描述
线上，后端总是自动停止服务，有懂得大佬没有啊

##### 截图&代码：
![image](https://user-images.githubusercontent.com/97373576/231084215-8aa558c1-826c-4210-bca8-cbecc6d62b5c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题查日志

**Comment by lhpdemo** [comment]
日志也没问题

**Comment by lhpdemo** [comment]
> 这种问题查日志

日志也没问题
