### ISSUE TITLE
引入best-pay-sdk 导致okhttp3 出现依赖错误

### ISSUE THREAD

**Issue by Smithjoppa** [jeecgboot/jeecg-boot#4818]
##### 问题描述：
引入best-pay-sdk1.3.7在demo模块下引入的
运行best-pay-sdk接口会出现 Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: okhttp3.internal.platform.Platform.log(ILjava/lang/String;Ljava/lang/Throwable;)V

##### 截图&代码：
![Uploading image.png…]()

**Comment by Smithjoppa** [comment]
![Uploading 微信图片_20230411182441.png…]()

**Comment by Smithjoppa** [comment]
`<dependency>
            <groupId>cn.springboot</groupId>
            <artifactId>best-pay-sdk</artifactId>
            <version>1.3.7</version>
            <exclusions>
                <exclusion>
                    <artifactId>okhttp</artifactId>
                    <groupId>com.squareup.okhttp3</groupId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by zhangdaiscott** [comment]
应该是依赖冲突了，解决下maven依赖冲突即可
