### ISSUE TITLE
Online在线功能 代码生成器指定自己的数据库以后，生成代码报异常  紧急！！

### ISSUE THREAD

**Issue by ssdai123** [jeecgboot/jeecg-boot#4820]
##### 截图&代码：

![image](https://user-images.githubusercontent.com/31784020/231182494-c80bf3ca-97be-425c-9014-105e7e18da75.png)
![image](https://user-images.githubusercontent.com/31784020/231182628-49137b54-e31d-4a08-9b79-fe3b89d2be67.png)
![image](https://user-images.githubusercontent.com/31784020/231182688-21fc7b06-8fa9-47e1-83c1-b4147f70efca.png)
![image](https://user-images.githubusercontent.com/31784020/231182737-a9cfd434-95de-4723-bcea-dfb697b1afaf.png)

o.j.codegenerate.database.DbReadTableUtil:140 -  connect databaseName xxxx 
String index out of range: 1

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
指定一个库，只是支持导入别的库表到online里面，真正生成的时候，这个表必须在平台表里有

**Comment by ssdai123** [comment]
![image](https://user-images.githubusercontent.com/31784020/231186043-92dfbe59-aac8-4fc7-9df0-0f0a5763b8fd.png)
这个已经导入了呀

**Comment by zhangdaiscott** [comment]
vue2最高适配3.4.3 你为什么用3.5.0

**Comment by zhangdaiscott** [comment]
vue2最高适配3.4.3 你为什么用3.5.0

**Comment by ssdai123** [comment]
我需要的是怎么解决这个BUG. 不是讨论前端用什么框架. 如果您确信用VUE3 的框架来请求可以解决问题，我也乐意马上试一试。不过我断定结果是一样的。

**Comment by ssdai123** [comment]
这里的问题很明显是读取数据库时候，解析表字段失败. 而为什么已经连接上数据库，把表都看的到了，还能解析表字段失败。这个就是你们底层代码BUG了。
![image](https://user-images.githubusercontent.com/31784020/231192200-2b5cf960-df9f-4897-bcea-7df9c8e1dfdb.png)
看这个图，能把表展示出来，说明数据库连接成功了。而Java层面报了String index out of range: 1  这个异常是不是解析表字段时候失败了？

**Comment by zhangdaiscott** [comment]
截图看你的pom jeecgboot版本号

**Comment by ssdai123** [comment]
![image](https://user-images.githubusercontent.com/31784020/231200931-86dfec17-fdf1-429a-acda-38d1a7feb9a8.png)
BUG 已经cha查到了，你们代码里面SQL写的就有问题 ！
![image](https://user-images.githubusercontent.com/31784020/231201121-170eb5e3-7962-48bf-b950-72b0e0c0c67f.png)
第一个参数应该就是表名称，第二个参数是视图名称么? 我一定会建立视图么? 我建表除非必要根本不建立视图. 我这已经给你们通过反编译方式查询出来BUG在哪里了，接下来怎么修复总该可以修复了吧?

**Comment by oday-xiexin** [comment]
> 

嘿嘿，有没有可能table_schema 是数据库名称

**Comment by zhangdaiscott** [comment]
楼上理解正确，所以定位问题不准确
