### ISSUE TITLE
开源版？& 商业版？

### ISSUE THREAD

**Issue by hongxiao2016** [jeecgboot/jeecg-boot#4821]
##### 问题描述：
![image](https://user-images.githubusercontent.com/54490229/231333127-bdff1f2c-f0b0-4048-a5f2-da1d0e6e4a3e.png)
是开源版本吗？ 在官网关于开源版描述的底部链接跳转到了  https://github.com/jeecgboot/jeecg-boot    

![image](https://user-images.githubusercontent.com/54490229/231333305-cc06a763-0ff1-4f87-806c-5b67e1f7cb42.png)

但是关于商业版的描述出现了Online表单

所以https://github.com/jeecgboot/jeecg-boot是开源版还是商业版？
使用https://github.com/jeecgboot/jeecg-boot开发商业系统有什么限制吗？

##### 截图&代码：
![image](https://user-images.githubusercontent.com/54490229/231333540-9f29b18e-c802-42b9-9c39-459565608c65.png)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot
功能模块介绍，哪些不开源里面有标记
![image](https://user-images.githubusercontent.com/3162115/231360658-6dbd4a2a-5d11-42b8-884c-747597508f53.png)

**Comment by hongxiao2016** [comment]
谢谢 了解了
