### ISSUE TITLE
jeecg-boot项目中pom文件${project.parent.version}取值问题

### ISSUE THREAD

**Issue by youzhanghao** [jeecgboot/jeecg-boot#4822]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
jeecg-boot项目中pom文件${project.parent.version}取的是3.5.0

##### 截图&代码：

![image](https://user-images.githubusercontent.com/24401230/231641032-edc90ecd-86d5-446c-a64c-be464a46bbac.png)
执行`mvn help:effective-pom`
<img width="565" alt="image" src="https://user-images.githubusercontent.com/24401230/231641184-02e3a734-7e8b-42cf-bfbc-57746e047fe8.png">
![image](https://user-images.githubusercontent.com/24401230/231641413-b348c0af-415c-4553-a6e5-23d86d7cb460.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你改出的问题吧
