### ISSUE TITLE
联动组件如何给子项添加筛选条件

### ISSUE THREAD

**Issue by NGLSL** [jeecgboot/jeecg-boot#4823]
##### 版本号：

3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？

Vue2

##### 问题描述：

联动组件如何给子项添加筛选条件?比如省市区，省可以筛选全部，市虽然可以通过parnet_id关联，但是想添加一些条件限制一下，请问怎么实现

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己写代码啊
