### ISSUE TITLE
vue 一级菜单 改成二级菜单 点了它自己本身 就出问题了 菜单就不展示了

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#4826]
##### 版本号：

3.5.0
##### 问题描述：
脑子抽风 或者点错了 一级菜单 改成二级菜单 点了它自己本身 就出问题了 菜单就不展示了

建议增加 功能 如果它等于它本身id  不让它选

##### 截图&代码：

![图片](https://user-images.githubusercontent.com/13266764/232373880-0bd68f7f-df6b-4292-891a-ada6353eff83.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue几？

**Comment by TomYule** [comment]
vue3

**Comment by zhangdaiscott** [comment]
为什么要自己选父亲自己呢，这本身就不应该这么做

**Comment by TomYule** [comment]
点错的情况下
