### ISSUE TITLE
表主键字段名是否可以自定义

### ISSUE THREAD

**Issue by ghostry** [jeecgboot/jeecg-boot#4827]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
目前oline开发新建表，主键固定为id，并且不能修改。
不符合实际项目使用。
是否可以支持自定义主键字段名？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by huangwei2013** [comment]
考虑一下吧，并不是所有项目都是完全依赖/从这框架0开始的。 阻挡了很多迁入的项目。
