### ISSUE TITLE
为什么访问不存在的url时会提示Token失效，请重新登录呢？

### ISSUE THREAD

**Issue by codeh2o** [jeecgboot/jeecg-boot#4829]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
excludeUrls添加了/test/jeecgDemo/list2，（这个路由实际上不存在）,返回的错误信息为Token失效，请重新登录!,这太奇怪了。路由不存在不应该是返回404吗？而且我已经把excludeUrls添加到了配置文件中，为什么还是报Token失效，请重新登录?

##### 截图&代码：
```
  shiro:
    excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**,/test/jeecgDemo/list,/test/jeecgDemo/list2,
```
```
{"success":false,"message":"Token失效，请重新登录!","code":401,"result":null,"timestamp":1681737086112}
```

还有个更奇怪的是
把控制器程序出错也会"导致Token失效，请重新登录"？

**Comment by miniFrank** [comment]
1. 解决办法，在excludeUrls中加入/error。
shiro:
excludeUrls:/test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/category/**,/visual/**,/map/**,/jmreport/bigscreen2/**,/test/jeecgDemo/list,/test/jeecgDemo/list2,/error

2. 原因：如果访问资源不存在404，那么会执行如下代码，将请求转发至/error，而/error刚好在不在排除名单，所以会进行token校验。
![image](https://user-images.githubusercontent.com/3614917/233826315-9d200bd7-2f33-491e-856a-ed059ccb9546.png)

3. 后续处理：我们会将/error加入到默认处理excludeUrls。
