### ISSUE TITLE
微服务打包启动报错“Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.”

### ISSUE THREAD

**Issue by jessedog** [jeecgboot/jeecg-boot#4831]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/7986198/232509218-d5787d87-050d-4aa8-a164-b602565580ef.png)
![image](https://user-images.githubusercontent.com/7986198/232509313-dd320790-b90f-4282-97e6-408f96b88a9f.png)
![image](https://user-images.githubusercontent.com/7986198/232509437-a34f379d-1bac-405c-a73b-69df2cf12c3a.png)
![image](https://user-images.githubusercontent.com/7986198/232509710-c3e5b291-e87b-42f3-bd6a-b50d21c927ed.png)

**Comment by zhangdaiscott** [comment]
启动命令是什么

**Comment by zhangdaiscott** [comment]
打包的时候
![image](https://user-images.githubusercontent.com/3162115/232541916-5cf1437c-3c32-430f-860b-f555a5f7e91f.png)

**Comment by jessedog** [comment]
dev 和 SpringCloud都勾上了的，prod 和 SpringCloud也试过。启动命令用的是 java -jar xxx.jar

**Comment by zhangdaiscott** [comment]
看看打包的JAR包，里面的配置文件是什么样的
![image](https://user-images.githubusercontent.com/3162115/232645046-01f4ce67-462d-4387-8b7c-2ddce7d2fa41.png)

看看这些参数有没有变成真实的配置

**Comment by jessedog** [comment]
![image](https://user-images.githubusercontent.com/7986198/232647460-ce59e670-bee1-4b77-9f37-ecb8b50fba75.png)
大暴出来的配置文件没问题
刚发现用 java -Dfile.encoding=utf-8 -jar 来启动就没问题，但是输出会变成乱码
用 java -jar 启动就会报错

**Comment by zhangdaiscott** [comment]
我们的文档里面不是写了要带着编码了吗，是你的问题或者你把nacos里面的全部中文删掉
