### ISSUE TITLE
多租户问题，系统自动生成租户为【0】的数据

### ISSUE THREAD

**Issue by jin2001** [jeecgboot/jeecg-boot#4833]
##### 问题描述：多租户的问题。
 用户A属于两个租户。
 用户A登录后，在用户管理画面，点击自己账号的编辑按钮，在弹出画面内，租户这一项多显示两个租户，租户名称为【0】.
 查看数据库，sys_user_tenant表用户A有四条记录，其中两条的tenant_id的值为【0】

##### 截图&代码：
![租户](https://user-images.githubusercontent.com/24690725/232655145-8d38c74b-4fca-4f6e-bb0e-3f014b5b51ec.png)

  
![租户DB](https://user-images.githubusercontent.com/24690725/232655230-d718d8aa-2e73-4d26-a19d-fe179cf7f41a.png)

**Comment by zhangdaiscott** [comment]
我们后期加了唯一索引，你可以把老数据清理下，自己补下唯一索引
![image](https://user-images.githubusercontent.com/3162115/232666470-1422dbf9-7024-47ec-afb0-965ef13e82a1.png)
