### ISSUE TITLE
网关模块无法解析DynamicRouteLoader

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4834]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
拉下来的项目，网关模块部分类无法解析，但能够正常启动

##### 截图&代码：
![image](https://user-images.githubusercontent.com/128020569/232687859-667844a3-4a16-42d9-bd03-05acb86cdafd.png)
![image](https://user-images.githubusercontent.com/128020569/232687926-b5222652-d604-4a73-a9f5-5d32ac211805.png)
![image](https://user-images.githubusercontent.com/128020569/232687978-1c1bbe75-d10a-420d-9b34-fcc7a2e1162c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven 刷新下，或者关掉IEDA 重新打开

**Comment by wlqwcs** [comment]
重启又好了
