### ISSUE TITLE
vue2版本，mysql数据库文件运行生成表出现错误

### ISSUE THREAD

**Issue by dongtiandaole** [jeecgboot/jeecg-boot#4835]
##### 版本号：
v3.4.3last

##### 问题描述：
vue2版本，mysql数据库文件运行生成表以及插入数据出现错误

##### 截图&代码：
![image](https://user-images.githubusercontent.com/55953630/232702236-a92c8d01-220b-469e-8223-826e8605d5d8.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by dongtiandaole** [comment]
并且表文件中缺少sys_user表以及相应数据

**Comment by zhangdaiscott** [comment]
仔细看下sql执行错误，按照错误提示调整
