### ISSUE TITLE
修改了网关端口，表单开发使用不了

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4837]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

后端修改了网关端口，表单开发使用不了，表单开发请求的接口依然是之前的端口，其他模块能够正常使用
##### 截图&代码：

<img width="955" alt="微信图片_20230418212919" src="https://user-images.githubusercontent.com/128020569/232940144-e91a43d0-c5b4-404e-a283-3b8de1996ca4.png">

![image](https://user-images.githubusercontent.com/128020569/232940527-dc4e4556-5680-4fdc-ad96-ccb434da07eb.png)
![image](https://user-images.githubusercontent.com/128020569/232940577-7081807a-9067-4dcb-ae79-0a8c49986a3b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
清下缓存
![image](https://user-images.githubusercontent.com/3162115/232942655-d145ca40-628c-4611-8d44-ffe468052632.png)

**Comment by wlqwcs** [comment]
可以了
