### ISSUE TITLE
定时任务运行一段时间，服务自动停掉了

### ISSUE THREAD

**Issue by 1050wang** [jeecgboot/jeecg-boot#4838]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
定时任务运行一段时间，服务自动停掉了

##### 截图&代码：

> 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1050wang** [comment]
我图片为什么上传不了

**Comment by zhangdaiscott** [comment]
可以传
![image](https://user-images.githubusercontent.com/3162115/232967782-a02ab4cd-4496-4d37-8faf-6c0db327c655.png)

**Comment by 1050wang** [comment]
We don't support that file type. Try again with a GIF,JPEG,JPG
提示这个
我上传的是jpg 格式的

**Comment by 1050wang** [comment]
![aaa](https://user-images.githubusercontent.com/131227204/232979224-2cf7cbc0-5adf-420e-8b5e-d388fef9c56a.jpg)

**Comment by zhangdaiscott** [comment]
这个不清楚，你可以把日志级别改成debug，跟踪下日志看看

**Comment by 1050wang** [comment]
我这个定时任务是调用第三方数据库，获取数据，数据库是达梦的，跟这个有关系吗

**Comment by zhangdaiscott** [comment]
这种问题猜不到，自己分析日志
