### ISSUE TITLE
多租户模式下，新增或编辑用户，选择角色一栏，角色选项没有做租户隔离

### ISSUE THREAD

**Issue by NeilGPT** [jeecgboot/jeecg-boot#4844]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
多租户模式下，无论是在系统用户还是租户用户中，新增或编辑用户，选择角色一栏，角色选项没有做租户隔离。正常的逻辑应该是某个租户在编辑用户时不能看到别的租户的数据，但现在a租户编辑a租户下的用户角色，却能看到b租户添加的b租户角色，这是不对的吧？

##### 截图&代码：
![7B80CF3F-6908-4255-8978-A9FF54F9BBA9](https://user-images.githubusercontent.com/129829204/233251681-e0655a60-adf9-446c-9f88-0a8bded4a0a5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by BruceLiu3385** [comment]
最近也在看多租户saas,估计你没有开启saas设置，这个我测试是可以的。
![image](https://user-images.githubusercontent.com/7733877/233517111-b2a4b436-7dd4-45dc-afe7-fcf6b979836b.png)

**Comment by erichui2017** [comment]
之前更新的时候，role表说这样处理有问题，给注释掉了。

**Comment by NeilGPT** [comment]
> 最近也在看多租户saas,估计你没有开启saas设置，这个我测试是可以的。 ![image](https://user-images.githubusercontent.com/7733877/233517111-b2a4b436-7dd4-45dc-afe7-fcf6b979836b.png)

因为你没更新到3.5.1

**Comment by NeilGPT** [comment]
@zhangdaiscott 请问是已修复了吗？

**Comment by 1298191366** [comment]
已修复发，待新版本发布
