### ISSUE TITLE
开启saas多租户功能后，租户管理员在添加分类字典时，报错

### ISSUE THREAD

**Issue by BruceLiu3385** [jeecgboot/jeecg-boot#4846]
##### 问题描述：

系统开启saas多租户功能后，测试租户管理员在添加“分类字典”的一级分类时，报数据库错误。通过错误提示，发现创建是一级分类默认code为A01, 数据库设置为唯一索引index_code导致

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7733877/233339462-c2b87de4-6894-4a50-b3a0-e52f694893f0.png)

![image](https://user-images.githubusercontent.com/7733877/233340177-9385ae9b-e74f-4e31-bb21-c68f83f6ec36.png)

![image](https://user-images.githubusercontent.com/7733877/233340530-805279e6-9183-4cbb-97af-ec6210973a15.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
