### ISSUE TITLE
接口连接超时

### ISSUE THREAD

**Issue by favoriteviolet** [jeecgboot/jeecg-boot#4847]
##### 问题描述：
隔十几分钟不操作页面，重新操作时，接口会报错，连接超时，重新刷新后又好了。

##### 截图&代码：
前端页面报错：
https://s1.ax1x.com/2023/04/20/p9Aej9H.png
后端控制台报错：
https://imgse.com/i/p9Amput
https://imgse.com/i/p9AmiE8
https://imgse.com/i/p9Amk4g
https://imgse.com/i/p9Amnuq
https://imgse.com/i/p9AmQET

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  
 我想知道是哪里出的问题？该怎么改？

**Comment by favoriteviolet** [comment]
initial-size: 10
        min-idle: 3
        maxActive: 50
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        
        我试着改变连接池的配置，还是不行。
        前端在修改主表代码时，页面容易卡死。得刷新或者关掉重开才好。
        不知道是哪方面的问题。

**Comment by favoriteviolet** [comment]
对一对多表单进行操作时，容易卡死。页面没反应。需要重新刷新。
单表倒是没出现这种情况，但是有主表和附表的列表就会卡死，特别是进行操作，比如点击新增按钮，

**Comment by zhangdaiscott** [comment]
maxActive: 50  改大了试试，环境问题得靠你自己

**Comment by favoriteviolet** [comment]
接口等待超时时间设置是在哪里设置的？
我这接口有数据返回，不过还是会显示接口超时，我觉得可能是我设置接口超时时间太短了。

**Comment by zhangdaiscott** [comment]
src\utils\http\axios\index.ts
![image](https://user-images.githubusercontent.com/3162115/233878456-ea8d95ad-3dc5-43e4-87f1-334bed3c9238.png)
