### ISSUE TITLE
404找不到请求的资源

### ISSUE THREAD

**Issue by jaylogin** [jeecgboot/jeecg-boot#4848]
##### 问题描述：新建子项目，单独改成单体或者微服务时，url都能访问，但是改成可单体与微服务切换的，url就访问不了

**Comment by zhangdaiscott** [comment]
没明白

**Comment by jaylogin** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jaylogin** [comment]
可以了，单独引入业务模块就行了，谢谢
