### ISSUE TITLE
Online在线生成代码，设置字段关联记录，没有效果

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#4849]
##### 前端版本：vue3版 

Online在线生成代码，设置字段关联记录，没有效果，我设置了一个表的一个字段关联另外一个表，高级配置也设置了对应的表，点功能测试，新增的时候，那个字段有+号能直接选其他表，，但是，生成代码以后，，还是输入框，没有+号选择其他表，效果没出来。
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
关联记录是在线用的，不支持代码生成

**Comment by 378680487** [comment]
不支持在线用是什么意思，，那我生成出来的，和功能测试内容不一样啊

**Comment by 378680487** [comment]
官方都案例说明，都写把一个字段关联记录以后，，新增就会有个选择功能，干嘛功能测试有这个功能，，我生成代码以后，这个功能没有生效

**Comment by sportscar** [comment]
同问，为啥功能测试有这个效果，代码生成后就没了？！

**Comment by lvcAI** [comment]
原来如此，就说怎么测试功能有，生成代码之后就没有了。

**Comment by UuluHan** [comment]
应该怎么解决呢
