### ISSUE TITLE
开启saas多租户功能后，某租户设置其下某部门权限，右侧权限树拉到的是整个系统的权限，不是租户套餐包里的权限

### ISSUE THREAD

**Issue by BruceLiu3385** [jeecgboot/jeecg-boot#4850]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
开启saas多租户功能后，某租户设置其下某部门权限，右侧权限树拉到的是整个系统的权限，不是租户套餐包里的权限。设置成只拉取租户下所有套餐权限，体验更好哇

##### 截图&代码：

![image](https://user-images.githubusercontent.com/7733877/233527798-e858da76-0b6d-4328-831d-ed62441f9e7a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
我们目前的设计，部门权限不作为租户体制内
部门、角色只是单纯的对象
租户单独权限，是通过租户套餐来的

**Comment by guojingbing** [comment]
> 我们目前的设计，部门权限不作为租户体制内 部门、角色只是单纯的对象 租户单独权限，是通过租户套餐来的

租户权限为什么不延用角色的方式呢，现在通过套餐设置权限不是一般的复杂，操作很不人性化，也不好理解

**Comment by guojingbing** [comment]
> 我们目前的设计，部门权限不作为租户体制内 部门、角色只是单纯的对象 租户单独权限，是通过租户套餐来的

 这种模式已经确定不会调整了吗？
租户要如何管理自己租户下的用户授权呢？总不能都在租户管理的套餐管理下邀请用户吧，这操作太迷了。
![image](https://github.com/jeecgboot/jeecg-boot/assets/5864899/e3de8e1c-6f01-4c68-bd2d-a2fd3ed6c01a)

**Comment by yinjianan** [comment]
> > 我们目前的设计，部门权限不作为租户体制内 部门、角色只是单纯的对象 租户单独权限，是通过租户套餐来的
> 
> 这种模式已经确定不会调整了吗？ 租户要如何管理自己租户下的用户授权呢？总不能都在租户管理的套餐管理下邀请用户吧，这操作太迷了。 ![image](https://user-images.githubusercontent.com/5864899/246055847-e3de8e1c-6f01-4c68-bd2d-a2fd3ed6c01a.png)

就是故意做的阉割版本恶心人的

**Comment by zhangdaiscott** [comment]
我们会逐步的根据大部分人的理解去优化此功能，我们的saas的项目使用方式，可能不满足某些场景，可以自己扩展
