### ISSUE TITLE
能不能写个注解，或者利用mybatisplus 的注解 指定某些列模糊查询呢？ 

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecg-boot#4852]
##### 版本号：

3.5.0
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
列要么都是模糊查询，要么加上* 不太习惯 有没有其他解决方法？ 
 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/component/JInput.html

**Comment by hongbo1030** [comment]
如果查询条件不是输入框，而是下拉框、下拉树、popu弹出框的模糊匹配，而且代码是online表单或报表配置的。如何实现？
