### ISSUE TITLE
online表单-权限控制-数据权限

### ISSUE THREAD

**Issue by jadentangsjfood** [jeecgboot/jeecg-boot#4853]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online表单的权限控制这里的数据权限，有办法做到只查询自己和自己直属下级的数据吗？下级的下级数据不查询。只查直属下级。我看文档用的是sys_org_code  但是这个是查询所有下级，我只需要查询自己的直属下级。谢谢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
直属下级的逻辑没有
