### ISSUE TITLE
查询过滤器不支持LocalDateTime ,LocalDate,LocalTime  

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#4854]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是怎么用的？的确不支持

**Comment by zjarlin** [comment]
就是java8的日期时间用惯了;导入导出和查询过滤器这一块建议支持一下;还有就是导入导出的基类方法我觉得可以用service.getEntityClass()来获取字节码而省略形参,还有HttpServletRequest 是不是也可以用注入的方式省略形参

**Comment by zhangdaiscott** [comment]
？

**Comment by zhangdaiscott** [comment]
个性化需求，自己二开吧
