### ISSUE TITLE
Modal控件设置 :title = null 无效，标题栏无法隐藏

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#4856]
##### 版本号：
V3.5.1

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
Modal对话框全屏时，title区域的左侧显示对话框标题，右侧显示【还原】和【关闭】按钮。

现在有一个业务厂景，希望可以隐藏 title 和 footer，从而可以使用整个对话框的区域自行布局。

footer可以通过设定属性 :footer="null" 来隐藏，但标题头无法完全隐藏。

ModalWrapper.vue 的 setModalHeight 函数中，有一行代码计算对话框的最大高度：

          let maxHeight = window.innerHeight - modalTop * 2 + (props.footerOffset! || 0) - props.modalFooterHeight - props.modalHeaderHeight;

 modalHeaderHeight默认值是57，最终计算出来的对话框高度就会少了57。

我自己做了个临时的方案，也不清楚是否合理。
1. 在 ModalWrapper.vue 的 props 增加了一个属性
     hideHeader: { type: Boolean, default: false }

2. 修改 setModalHeight 函数中计算最大高度的代码

          const modalHeaderHeight = props.hideHeader == true ? 0 : props.modalHeaderHeight;
          let maxHeight = window.innerHeight - modalTop * 2 + (props.footerOffset! || 0) - props.modalFooterHeight - modalHeaderHeight;

3. 修改 BasicModal.vue
3.1 <ModalWrapper
         ....
       v-bind="omit(getProps.wrapperProps, 'visible', 'height', **'hideHeader',** 'modalFooterHeight')"
        **:hideHeader="getProps.hideHeader"**>

3.2 <template #title **v-if="getMergeProps.hideHeader == false"**>
      <ModalHeader :helpMessage="getProps.helpMessage" :title="getMergeProps.title" @dblclick="handleTitleDbClick" />
    </template>

通过新增 hideHeader 属性，在使用 BasicModal 时，可以通过 :hideHeader="true" 来完全隐藏 title。

若有更佳的方法，还请告之！若暂时不支持这类配置，希望能为Modal控件增加类似的属性来控制对 title 的完全隐藏。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by citynook** [comment]
@zhangdaiscott 请问这个是否可以做为一个改善优化点？或是我实现的方式不正确，现有的功能就可以实现？

**Comment by lsqGitHub716** [comment]
问题已收录，后期优化修改
