### ISSUE TITLE
请问这个online表单代码生成是本身就不支持生成Mapper和service层的方法和XML的代码吗

### ISSUE THREAD

**Issue by chenyuan001** [jeecgboot/jeecg-boot#4857]
##### 截图&代码：
例：生成的是官方的测试请假表用例
mapper：
/**
 * @Description: 测试请假表
 * @Author: jeecg-boot
 * @Date:   2023-04-23
 * @Version: V1.0
 */
public interface CeshiNoteMapper extends BaseMapper<CeshiNote> {

}

XML：
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.jeecg.modules.demo.ceshi_note.mapper.CeshiNoteMapper"

</mapper>

Service：
/**
 * @Description: 测试请假表
 * @Author: jeecg-boot
 * @Date:   2023-04-23
 * @Version: V1.0
 */
public interface ICeshiNoteService extends IService<CeshiNote> {
	
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
泛型设计，有的可以不需要生成
