### ISSUE TITLE
找不到表单设计的菜单

### ISSUE THREAD

**Issue by wangzhGh11** [jeecgboot/jeecg-boot#4858]
##### 截图&代码：
![1682221519656](https://user-images.githubusercontent.com/126642042/233818737-f0771f2c-e7c1-48c4-91ad-9e64a3987e39.jpg)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
(未开源)
