### ISSUE TITLE
运行 pnpm preview 命令进入预览模式，登录界面验证码显示404

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#4859]
##### 版本号：
V3.5.1

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
1. 从官网下载最新的3.5.1版本，修改前端 .env.production 配置：

#后台接口全路径地址(必填)
VITE_GLOB_DOMAIN_URL=http://localhost:8080/jeecg-boot

2. 运行 pnpm preview 命令进入预览模式，登录界面验证码显示404，详见后面的截图。
 ➜  Local:   http://localhost:4173/
  ➜  Network: http://172.29.96.1:4173/ 
  ➜  Network: http://192.168.3.24:4173/
  ➜  Network: http://172.28.160.1:4173/

3. 后端也是在本机运行
----------------------------------------------------------
	Application Jeecg-Boot is running! Access URLs:
	Local: 		http://localhost:8080/jeecg-boot/
	External: 	http://172.29.96.1:8080/jeecg-boot/
	Swagger文档: 	http://172.29.96.1:8080/jeecg-boot/doc.html

4. 开发模式一切正常，但进入预览模式就会发生这个情况，不知是否哪里的配置有问题。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/127393297/233818893-41ecc69a-d52c-4739-806b-033810f14970.png)

![image](https://user-images.githubusercontent.com/127393297/233818917-010d34bf-7bb5-4820-82a0-f11df2d1063c.png)

![image](https://user-images.githubusercontent.com/127393297/233818933-f958f91f-e465-43de-9cce-27931eae9b3d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台启动了吗

**Comment by citynook** [comment]
后台启动了，请见第3点的内容是后台启动后的访问链接。
下载的最新代码，前后端都在本机运行，pnpm dev 一切正常，pnpm preview就会出验证码404

**Comment by citynook** [comment]
@zhangdaiscott 请问这个问题是bug？还是哪里配置不正确？

**Comment by zhangdaiscott** [comment]
test模式不要用，可能有缺陷，相关issue
https://github.com/jeecgboot/jeecgboot-vue3/issues/479
https://github.com/jeecgboot/jeecgboot-vue3/issues/331
https://github.com/jeecgboot/jeecgboot-vue3/issues/149
