### ISSUE TITLE
微服务模式下调用ISysBaseAPI.sendWebSocketMsg 401

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4860]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

微服务模式下调用ISysBaseAPI.sendWebSocketMsg 401 显示token失效
##### 截图&代码：
![image](https://user-images.githubusercontent.com/128020569/233819730-57cd5ed4-19f5-4cb2-ba12-43ebfc53e155.png)
![image](https://user-images.githubusercontent.com/128020569/233819769-418158bb-57cd-4d84-9cb1-779ab88e407d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图与你的问题描述不一致
