### ISSUE TITLE
jeecg 3.5.1 版本下在线表单的主题只有默认模式，没有ERP等其他模式

### ISSUE THREAD

**Issue by 365mailme** [jeecgboot/jeecg-boot#4861]
##### 问题描述：
在线表单编辑中，对于主表类型的表单，主题模版只有“默认主题” ，没有其他如ERP 主题的支持

##### 截图&代码：

![image](https://user-images.githubusercontent.com/58126040/233823210-728c34f7-de19-4253-a873-ac4e52d01f4d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前只有这一个风格

**Comment by 365mailme** [comment]
哦，所以后面也不打算增加原先的ERP风格了么？ 还是说购买商业化版本的话，会有这些额外的模版支持？
