### ISSUE TITLE
AUTO在线表单新增数据可以不通过代码开发直接配置规则实现价格x数量=总金额字段吗

### ISSUE THREAD

**Issue by chenyuan001** [jeecgboot/jeecg-boot#4862]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/96572112/233824333-0651689f-79b3-4a4a-86ca-6af47a160976.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
写js增强   https://help.jeecg.com/online/enhanceJs.html

**Comment by chenyuan001** [comment]
> 写js增强 https://help.jeecg.com/online/enhanceJs.html

必须通过代码的方式吗，不能像配置数据规则一样，配置字段的值更新事件
