### ISSUE TITLE
a-pagination 被解析成自定义标签

### ISSUE THREAD

**Issue by wufang95** [jeecgboot/jeecg-boot#4863]
##### 截图&代码：
code ：``` <a-pagination /> ```
截图 ：
![1682234523495](https://user-images.githubusercontent.com/29749802/233825875-870a1a1d-357b-4ae9-9740-c38c7af06b72.jpg)

**Comment by zhangdaiscott** [comment]
你确认引入吧，这种基础问题自己排查
