### ISSUE TITLE
导出的excel 可以根据值改变背景颜色么？

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecg-boot#4866]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
到处的excel 可以根据 值修改颜色么？ 比如不及格的变红这种

我看了一下 用的autoapi 跟easyapi 还是不太一样 在IExcelExportStyler 没有获取值的方法  

现在只有两个思路 一个是生成excel 然后再修改颜色 

第二个是 看看用模板 在模板里用excel vb去进行判断 

还有什么好办法吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持，可以自定义实现导出逻辑
