### ISSUE TITLE
online在线开发创建的表单，在线调试时暴露的接口http://127.0.0.1:8088/jeecg-boot/online/cgform/api/getData/{code} 能不能配置到shrio里面不做token的校验呢？

### ISSUE THREAD

**Issue by Sunnyweii** [jeecgboot/jeecg-boot#4867]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue2或vue3

##### 问题描述：
online在线调试暴露的接口 能不能配置到shrio里面不做校验的呢？
  @@怎么配置都不生效。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/125847059/233888793-7af41819-9d68-423f-b507-e193110762f8.png)

![image](https://user-images.githubusercontent.com/125847059/233888875-2c5a107f-e210-4205-ae1b-14d9bb848ce1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Sunnyweii** [comment]
![image](https://user-images.githubusercontent.com/125847059/233889111-86cb39ea-a87c-434d-8952-eeffe50ab03b.png)
![image](https://user-images.githubusercontent.com/125847059/233889138-02a3180f-4f61-475f-a4cd-0b0a70a51397.png)
有看到这个注解，但是不知道怎么用，大佬麻烦解答解答一下~

**Comment by zhangdaiscott** [comment]
不能，不控制就是安全漏洞

**Comment by Sunnyweii** [comment]
> 不能，不控制就是安全漏洞


那我如果想给外部系统调用这个接口的话，能怎么做才能实现外部系统调用呢？

**Comment by Sunnyweii** [comment]
那就是我外部系统也通过登录接口获取token值吗？token的值是只能通过登录认证接口获取吗？

**Comment by rehmetjan** [comment]
我觉得非常有必要把这个接口`filterChainDefinitionMap.put("/online/cgform/api/getData/**", "anon"); `免登录可访问。
做小程序后台的时候直接用online的方式做查询非常方便。
