### ISSUE TITLE
Excel 导出 能够几列用同一个表头吗？ 另外 模板中怎么输出序号啊？ &index& 没有吗？

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecg-boot#4870]
##### 版本号：
3.5.0

##### 问题描述：
excel 导出  如果表头名字一样，能自动合并表头吗？

想要下面这种表头格式 如果不行 只能考虑模板了 
 如果是模板 那么 &index& 能输出序号么

##### 截图&代码：
![image](https://user-images.githubusercontent.com/67778969/233935878-9fd8e6a2-7545-43df-b098-5569699260e1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以合并标题，二级标题，不支持用一个
https://help.jeecg.com/autopoi/autopoi/annotation/list.html
