### ISSUE TITLE
单纯想问一下，有没有轻量版的jeecgboot后台

### ISSUE THREAD

**Issue by a792883583** [jeecgboot/jeecg-boot#4871]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
想问一下，有没有删减版的jeecgboot后台，比如删掉租户、权限、在线开发等等，只保留最基础的登录、注册、用户管理等功能

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没有，可以自己精简
