### ISSUE TITLE
字典表某个字典改了，可是返回的还是之前未改的

### ISSUE THREAD

**Issue by caleb-hxs** [jeecgboot/jeecg-boot#4873]
##### 版本号：
3.4.3    

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
你好，我把字典表某个字典改了，可是返回的还是之前未改的

##### 截图&代码：

![image](https://user-images.githubusercontent.com/116248596/234154898-5a27d26c-09b7-4fba-8518-7e2cef19e536.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
字典列表上方有个刷新缓存按钮

**Comment by caleb-hxs** [comment]
你好，点了之后还是不行，是要重新部署吗
