### ISSUE TITLE
删除提示“很抱歉，资源未找到!”接口地址正确，vue2

### ISSUE THREAD

**Issue by dilys912** [jeecgboot/jeecg-boot#4874]
##### 问题描述：
1、确认接口地址正确
2、生产环境提示异常

##### 截图&代码：
![image](https://user-images.githubusercontent.com/42336667/234161064-dd13cf88-4948-4b7b-b3ac-8334a96f1998.png)
![image](https://user-images.githubusercontent.com/42336667/234161104-5e268f69-66fc-4d0f-8e18-7cd2ac6a5c99.png)
![image](https://user-images.githubusercontent.com/42336667/234161175-104de29c-5e65-4eec-9844-dc15247563ec.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题得靠自己
