### ISSUE TITLE
微服务模块引用其他模块，被引用模块生成jar包，运行时没有清单属性

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4877]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
微服务模块引用其他模块，被引用模块生成jar包，运行时没有清单属性
如果被引入模块不配置 <classifier>exec</classifier>的话，引入模块打包时又会显示程序包不存在
##### 截图&代码：
![image](https://user-images.githubusercontent.com/128020569/234344882-9b0bd463-e2cc-4c6a-8af0-a71a71b86925.png)
![image](https://user-images.githubusercontent.com/128020569/234345096-740ffd96-5bf1-4a7f-a267-3786a9b69c49.png)
![image](https://user-images.githubusercontent.com/128020569/234345264-3ae9b4e3-c092-4328-ae49-e0dc7e66e8c3.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wlqwcs** [comment]
![image](https://user-images.githubusercontent.com/128020569/234346529-040f7281-8387-41ff-bdd7-6a53df43c678.png)

**Comment by zhangdaiscott** [comment]
参考通过 archetype 生成的start项目配置
http://doc.jeecg.com/3040736
