### ISSUE TITLE
数据字典 查询某个表  这个表使用了逻辑删除标识  @TableLogic  还是能选择已删除部分 建议前端能加个过滤条件

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#4879]
##### 版本号：

3.5.0
##### 问题描述：
  {
    label: '卡座房间号',
    field: 'boothRoomId',
    component: 'JDictSelectTag',
    componentProps:{
      dictCode: 't_booth_room_seating,room,id',
    },
  },

Java
```
    @Excel(name = "是否删除", width = 15)
    @ApiModelProperty(value = "是否删除")
    @TableLogic
    private Integer delFlag;

```
已经删除了test 部分 下拉列表 还是能选择
##### 截图&代码：
![图片](https://user-images.githubusercontent.com/13266764/234452714-92b083c6-8f45-4450-9d24-6fe6a3886f51.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你自己改的代码吧？应该是你没改好

**Comment by WeiFengo** [comment]
确实有这个问题哦
