### ISSUE TITLE
#fe: | 横向遍历不生效

### ISSUE THREAD

**Issue by Heath-Ho** [jeecgboot/jeecg-boot#4880]
##### 问题描述：
`#fe:`横向遍历不生效。

##### 截图&代码：
模板：
![image](https://user-images.githubusercontent.com/76432039/234502964-124a51fd-f019-41dd-a85b-b8205d2496fb.png)
代码：
![image](https://user-images.githubusercontent.com/76432039/234502986-500503da-88ce-4a7e-8b7b-319daac8d710.png)
结果：
![image](https://user-images.githubusercontent.com/76432039/234503009-284852e4-6359-45f6-adba-ff4724a6af5b.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Heath-Ho** [comment]
这是不支持`#fe:`吗？
![image](https://user-images.githubusercontent.com/76432039/234521168-9721fcbc-483d-4e73-8a83-916942bd66e5.png)

**Comment by lsqGitHub716** [comment]
试试设置列循环配置： params.setColForEach(true);
![image](https://user-images.githubusercontent.com/65587928/236594067-08ce6bb9-a97e-474b-ac2a-3ebbd07a8538.png)
