### ISSUE TITLE
微服务模块下 引入类无法解析符合

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#4881]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
微服务模块下 引入另外模块的类无法解析符号，本模块引入也会无法解析符号

##### 截图&代码：
![image](https://user-images.githubusercontent.com/128020569/234531552-419d4a9d-9490-4434-ac89-e876d30830fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven刷新
