### ISSUE TITLE
前端 /@/utils/common/compUtils 里的dateFormat 功能有bug

### ISSUE THREAD

**Issue by 157677678** [jeecgboot/jeecg-boot#4882]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
dateFormat(new Date(),"yyyyMMdd");
出来只能获得dd的 值  如果是yyyy-MM-dd 则正确
dateFormat里的正则不太明白

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
已修改，下版本发布

**Comment by 157677678** [comment]
> 

后来发现 vben里 有dayjs  有同样的功能

**Comment by 157677678** [comment]
> 已修改，下版本发布

后来发现 vben里 有dayjs 有同样的功能
