### ISSUE TITLE
远程下拉组件，开启多选后，返回的value值为空

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecg-boot#4883]
##### 截图&代码：
![微信截图_20230427143547](https://user-images.githubusercontent.com/29888011/234779511-d64b7c77-9a1d-4795-967e-3911bd7742fb.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by IIIIIIIIF** [comment]
![image](https://user-images.githubusercontent.com/29888011/234779675-01584c9a-5402-49b2-b3c9-26306c457c68.png)
![image](https://user-images.githubusercontent.com/29888011/234779716-7e7e1f1d-6f0e-4923-82e8-3f153b7e4faa.png)

**Comment by 1298191366** [comment]
已修复，待新版本发布，在新版本中，当您在`EditCellTable`使用`apiSelect`组件时多选是返回数组
