### ISSUE TITLE
table自适应高度不生效

### ISSUE THREAD

**Issue by jfrong** [jeecgboot/jeecg-boot#4887]
##### 截图&代码：
const {prefixCls, tableContext, onExportXls, onImportXls} = useListPage({
  tableProps: {
    canResize: true

![image](https://user-images.githubusercontent.com/57884843/235052661-8d17086f-0985-4e83-897a-e8aa44e6d57f.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Peter-HJJ** [comment]
+1
