### ISSUE TITLE
开启租户功能，是否每增加一个业务表都必须在 MybatisPlusSaasConfig.java 文件中 TENANT_TABLE 添加一个表

### ISSUE THREAD

**Issue by shanggushenlong** [jeecgboot/jeecg-boot#4891]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：开启租户功能，是否每增加一个业务表都必须在 MybatisPlusSaasConfig.java 文件中 TENANT_TABLE  添加一个表
这样业务表数据才能进行按照租户来进行过滤，此操作是否不简便，代码侵入性过强

##### 截图&代码：

![image](https://user-images.githubusercontent.com/20007857/235291538-714945d8-c74b-43c8-952c-f01c51a1813d.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是的
