### ISSUE TITLE
多个已有用户的单体升级为微服务的SSO单点登录疑惑

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#4892]
##### 版本号：虽然看了官方文档中的单体升级为微服务,但还是有些疑惑,希望作者能看完;
1.老的单体jboot系统(假设有三个abc)各自有各自的注册,用户登录,和权限,角色等等
2.现在需求:jboot微服务项目cloud-app要求abc的sys_user在cloud中都可以登录
我的做法是(测了可以勉强实现):    
1.同步abc 的 sys_user  用户注册表
2.fegin调用单体接口(仅使用nacos的服务发现,使得他们在一个注册中心);
3.实现fegin拦截器
根据Request.getHeader()拿到当前方法的 "X-Access-Token"    逆向出用户名密码
        String username = JwtUtil.getUserNameByToken(request);
        LoginUser userByName = commonAPI.getUserByName(userNameByToken);
        String password = userByName.getPassword();

拿到用户名密码 调用外部接口拿到外部单体的   mytoken=getToken(username,password)  然后实现fegin拦截器把转发后的token设置进去  requestTemplate.header( "X-Access-Token", mytoken);
这样通过fegin的调用拿到的结果集是在各个单体中配置的带有权限的结果集
<img width="605" alt="image" src="https://user-images.githubusercontent.com/67467679/235351248-6c96f8ac-c5f4-448b-8feb-b9d528935fed.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/67467679/235351258-4588867d-c41d-4155-b090-dd1ffb51b77b.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/67467679/235351263-74cba339-ae4b-41b8-8066-bbf383c4c23e.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/67467679/235351271-a7540ee7-5829-4b2c-8ad8-141ce24b0876.png">
(图中还遇到了feign对于@Component标记的配置重复代理无限递归的问题,使用spring 3支持的泛型注入会遇到这个问题;
我实现InitializingBean在构造函数中初始化泛型解决了fegin重复代理的问题)

假设我的系统没有用户的情景,从0开发可以参考官方文档中的单体升级为微服务,可是已经有单体上线的情况下,要适配老系统的所有用户及其权限,阁下该如何升级为微服务且老系统的用户都可以在新的cloud系统中登录呢?

##### 前端版本：vue3版？还是 vue2版？
vue2

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
3个独立用户独立权限的系统，只是注册到nacos上，那其实就是后台互相调用方便点，用户互相登录？有什么用？，不清楚你的实际业务关系，就这个需求：2.现在需求:jboot微服务项目cloud-app要求abc的sys_user在cloud中都可以登录，提出方案如下：
解决两个问题，1：登录问题
再写一个服务d，以后所有的其他服务访问的时候，一旦发现没有登录状态，全部跳该服务的登录界面，后台校验，挨个去调用其他服务的用户接口，是否有用户对上了，对上了，生成token...然后就是一些和单体类似的操作，登录成功，前后端都有token了
2.token有效问题
那么有了token之后，abc系统自己访问的时候还会作token校验，哎，一校验，发现这个用户不是我系统里的，ok这个时候再调用一个服务d的接口，这个接口和登录的类似会调用其他的服务的用户信息，服务d能认证通过，那说明也是ok的，那么这个token也是有效的。

**Comment by zjarlin** [comment]
> 3个独立用户独立权限的系统，只是注册到nacos上，那其实就是后台互相调用方便点，用户互相登录？有什么用？，不清楚你的实际业务关系，就这个需求：2.现在需求:jboot微服务项目cloud-app要求abc的sys_user在cloud中都可以登录，提出方案如下： 解决两个问题，1：登录问题 再写一个服务d，以后所有的其他服务访问的时候，一旦发现没有登录状态，全部跳该服务的登录界面，后台校验，挨个去调用其他服务的用户接口，是否有用户对上了，对上了，生成token...然后就是一些和单体类似的操作，登录成功，前后端都有token了 2.token有效问题 那么有了token之后，abc系统自己访问的时候还会作token校验，哎，一校验，发现这个用户不是我系统里的，ok这个时候再调用一个服务d的接口，这个接口和登录的类似会调用其他的服务的用户信息，服务d能认证通过，那说明也是ok的，那么这个token也是有效的。

目前是其他系统的接口都在cloud里远程调用一下,cloud里的用户表是其他系统用户表的并集,其他系统的根据用户名和密码getToken开放;在cloud中做token转换为abc各自的token,通过feign拦截器塞到请求头调用下游;但是这么做写的代码感觉很枯燥(写过的接口都要再d系统中调用一下);

**Comment by zhangdaiscott** [comment]
公用一个redis，一套token不就可以了
