### ISSUE TITLE
主从表操作按钮导致页面卡死

### ISSUE THREAD

**Issue by favoriteviolet** [jeecgboot/jeecg-boot#4893]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
主从表生成代码后，在主表前端界面点击新增或者其他按钮，页面就卡死，动不了。过一会提示等待或者关闭页面，需要关掉标签页重新打开才行。
也不是每次点击就卡死，偶尔吧。也没有任何报错。就是会卡死动不了。
单表生成的代码就没出现这种情况，出现这种情况的都是主从表生成的代码。

##### 截图&代码：
https://s1.ax1x.com/2023/05/01/p98vx6e.png

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有报错吗，看看F12

**Comment by favoriteviolet** [comment]
https://s1.ax1x.com/2023/05/04/p9YjiTA.png
现在这样就卡死了，我更新了一些代码，保存后去操作就这样了。

**Comment by zhangdaiscott** [comment]
用最新代码试试

**Comment by favoriteviolet** [comment]
https://s1.ax1x.com/2023/05/04/p9YjW0H.png
目录是没问题的，关掉标签页重进，也是能加载的。

**Comment by favoriteviolet** [comment]
还有其他解决办法吗？因为更新代码，我还需要处理合并代码之类的。

**Comment by lsqGitHub716** [comment]
测试生成主从表，操作点击未发现你说的情况。
请排查：
1.你生成的主从表是那种页面风格的？
2.你表单是否有配置一些特别的字段？
3.你后台代码是否是最新的？
4.你本地测测生成一个简单的主从表，是否也会必现你说的情况？

**Comment by favoriteviolet** [comment]
我的版本是3.4.4的，页面风格是嵌套子表格。这个是问题偶尔出现，也不是经常，有时候用着用着就突然卡住了。需要关掉重开。

**Comment by zhangdaiscott** [comment]
了解，那应该是online打包问题，建议升级到最新版试试
