### ISSUE TITLE
 ExcelImportUtil.importExcelBySax导入数据解析不到数据

### ISSUE THREAD

**Issue by Evan98521** [jeecgboot/jeecg-boot#4895]
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

> ExcelImportUtil.importExcelBySax，使用importExcelBySax导入数据解析不到数据，得到的list数据是空的。

##### 截图&代码：

>     public Result<?> importExcel(HttpServletRequest request, HttpServletResponse response, Class<Uers> clazz) throws Exception  { 
>       MultipartHttpServletRequest multipartRequest = (MultipartHttpServletRequest) request;         
>       Map<String, MultipartFile> fileMap = multipartRequest.getFileMap();     
>       for (Map.Entry<String, MultipartFile> entity : fileMap.entrySet()) {             
>         MultipartFile file = entity.getValue();         
>         ImportParams params = new ImportParams();         
>         params.setTitleRows(1);          
>         params.setHeadRows(1);           
>         params.setNeedSave(true);          
>         List<Uers> list = ExcelImportUtil.importExcelBySax(file.getInputStream(), clazz, params);

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Evan98521** [comment]
ExcelImportUtil.importExcel  可以使用

**Comment by Evan98521** [comment]
为什么关了啊，这个文档有但是不能用啊？

**Comment by zhangdaiscott** [comment]
例子没问题，确认下你的用法是否有问题

**Comment by Evan98521** [comment]
> 例子没问题，确认下你的用法是否有问题

好的 我再看看 感谢
