### ISSUE TITLE
人大金仓数据库数据字典无法指定数据库

### ISSUE THREAD

**Issue by kinglyx** [jeecgboot/jeecg-boot#4897]
##### 截图&代码：

![微信图片_20230505115822](https://user-images.githubusercontent.com/91453805/236375022-de769ea6-df08-4d7d-b6ea-fb0a97aeb548.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持此写法

**Comment by kinglyx** [comment]
1

**Comment by kinglyx** [comment]
没有解决办法吗

**Comment by CRIOWN** [comment]
你好 能讲解一下如何用jeecg连接人大金仓数据库吗🥺
