### ISSUE TITLE
jeectBoot 3.5.1版本相关jeect封装开源包本地导入不了

### ISSUE THREAD

**Issue by LuckyLi04** [jeecgboot/jeecg-boot#4898]
##### 版本号：
3.5.1

##### 问题描述：
jeectboot相关封装开源包本地导入不了，maven仓库是按照操作手册配置的

##### 截图&代码：
![image](https://user-images.githubusercontent.com/132631775/236383788-6359694b-e39d-4059-8a2a-3fdbaf24109c.png)
![image](https://user-images.githubusercontent.com/132631775/236383833-33cb3a31-0576-4c1d-95fd-e18758374858.png)
![image](https://user-images.githubusercontent.com/132631775/236384023-d035c4f5-2604-4881-82da-b2c68631c4ab.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么开发工具？

**Comment by zhangdaiscott** [comment]
无回复关闭

**Comment by LuckyLi04** [comment]
IDEA开发工具



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月05日 13:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] jeectBoot 3.5.1版本相关jeect封装开源包本地导入不了 (Issue #4898) |

什么开发工具？

**Comment by sunrisesong** [comment]
我也是这个问题
