### ISSUE TITLE
Online表单开发，使用代码生成功能怎么绑定表单的创建用户为当前登录用户

### ISSUE THREAD

**Issue by chenyuan001** [jeecgboot/jeecg-boot#4899]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/96572112/236400385-de8155cf-85f7-4641-b176-a2102e9f7ee4.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码生成后，自己补充逻辑即可
