### ISSUE TITLE
online表单开发,导入数据库表时,datetime类型字段被识别为date

### ISSUE THREAD

**Issue by w31896905** [jeecgboot/jeecg-boot#4903]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么数据库，请详细说明

**Comment by w31896905** [comment]
mysql5.7 docker-compose 创建的


通过前端建表,然后移除保单再做导入,仍然识别为date




31896905
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] online表单开发,导入数据库表时,datetime类型字段被识别为date (Issue #4903)





 
什么数据库，请详细说明

**Comment by zhangdaiscott** [comment]
sq

**Comment by tygithub1** [comment]
已修改

**Comment by 401878750** [comment]
项目需要怎么升级，才能解决这个问题

**Comment by zhangdaiscott** [comment]
下个版本
