### ISSUE TITLE
Online在线功能   修改回显规则拦截长度超长

### ISSUE THREAD

**Issue by 15375956592** [jeecgboot/jeecg-boot#4904]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
数据库字段是decimal 或者int 等数值类型时，在线表单不会有长度限制

##### 截图&代码：
![image](https://user-images.githubusercontent.com/131235287/236606057-4436a8b9-69e2-41d4-85e2-fedb8874c686.png)

![be28d99798c9c6ce07e9373119a98d8](https://user-images.githubusercontent.com/131235287/236605960-eb58003a-768d-4ea4-addc-0e43a7865ff1.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没做这个控制
