### ISSUE TITLE
表单生成器字段配置时，选择关联字段，在进行高级配置时，无法加载数据库列表，提示 Sgin签名校验错误！

### ISSUE THREAD

**Issue by climpeaker** [jeecgboot/jeecg-boot#4905]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
表单生成器字段配置时，选择关联字段，在进行高级配置时，无法加载数据库列表，提示 Sgin签名校验错误！

##### 截图&代码：
![T~O(ZBR6QEY Q{I46VO2`M](https://user-images.githubusercontent.com/10292915/236611996-fec60a27-90dc-4b36-9d88-8974043121f9.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by tygithub1** [comment]
使用开源项目测试无此问题，参考 #445

**Comment by tygithub1** [comment]
已修改
