### ISSUE TITLE
表格点击选中框时卡顿

### ISSUE THREAD

**Issue by ESWN-1234** [jeecgboot/jeecg-boot#4907]
##### 版本号：
jeecgboot-vue3@3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
创建表格后点击标的的选择框会卡顿

##### 截图&代码：

![无标题](https://user-images.githubusercontent.com/53074936/236614191-14301887-07ad-4fe8-9e87-9229b1c69aae.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ESWN-1234** [comment]
这个应该不是数据量多少的问题，这个表格的数据都没有超过500，并且我其它地方使用表格没有这种情况。

**Comment by ESWN-1234** [comment]
@zhangdaiscott 这个应该不是数据量多少的问题，这个表格的数据都没有超过500，并且我其它地方使用表格没有这种情况。

**Comment by ESWN-1234** [comment]
选择的数据也不是太多，即使是选择一条数据也会卡顿 @zhangdaiscott

**Comment by zhangdaiscott** [comment]
我们会继续跟踪分析，目前已知提升性能的方案是：
少写render，或者直接用原生模式
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/88dd87b6-515e-4e0f-af9f-565d374c3300)

**Comment by ESWN-1234** [comment]
没有什么好的解决办法，只能是少用一点vue3
________________________________

**Comment by zhangdaiscott** [comment]
最新版已经解决

**Comment by ESWN-1234** [comment]
OK
________________________________
