### ISSUE TITLE
开启多租户隔离，但新增时tenant_id并没有自动注入

### ISSUE THREAD

**Issue by qiuzx20** [jeecgboot/jeecg-boot#4908]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
开启了多租户隔离，使用online表单创建了表单也设置了tenant_id，但新增的时候tenant_id并没有自动注入；修改表记录添加上tenant_id的值后查询是可以的。
##### 截图&代码：

![image](https://user-images.githubusercontent.com/19650843/236614645-8e66fdbe-727d-455d-ab8a-4a87d8af0b0c.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
得升级online lib 过段时间发布
