### ISSUE TITLE
先在数据库创建表，然后再导入系统，数据库数据类型是datetime类型，在生成表单页面属性设置时，设置年月日时分秒，校验不通过

### ISSUE THREAD

**Issue by climpeaker** [jeecgboot/jeecg-boot#4909]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
数据库数据类型是datetime类型，在生成表单页面属性设置时，设置年月日时分秒，校验不通过;数据表是先在数据库创建，然后再导入系统的。

##### 截图&代码：
![image](https://user-images.githubusercontent.com/10292915/236617346-94452e62-b4e8-4316-aa2a-cf0a97c6649a.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tygithub1** [comment]
已修改
