### ISSUE TITLE
代码闭环问题

### ISSUE THREAD

**Issue by chenyuan001** [jeecgboot/jeecg-boot#4910]
##### 问题描述：假设代码已经生成，想要在已经使用代码生成的表单再次加字段，可以通过Online表单添加字段重新生成代码吗，两边代码是否能同步形成有效的闭环，通过代码生成的代码和Online表单还有没有联系，如果没有关联请问有没有计划往这个方向去实现闭环

**Comment by zhangdaiscott** [comment]
不支持，已经生成的代码如果没有改动可以覆盖生成。做了修改，就不要重复生成
