### ISSUE TITLE
微服务下nacos启动失败

### ISSUE THREAD

**Issue by shanggushenlong** [jeecgboot/jeecg-boot#4911]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：微服务下nacos启动失败
本地版本jdk是64位，也已查看了当前所有相关的issue，排除了相关问题，依旧是启动失败，怀疑是 nacos 不能有中文路径，截图中已给出，nacos默认启动是 C:\Users\xx丽\nacos\logs，此路径是否可以更改，相同代码，英文的用户名路径nacos启动正常

##### 截图&代码：
![1683514927549](https://user-images.githubusercontent.com/20007857/236724638-be07690d-e47d-4e2d-aba1-f030e6103af1.png)

![1683514711109](https://user-images.githubusercontent.com/20007857/236724185-226d0f47-386c-46b5-92a4-7188f185b040.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
那就不要有中文路径
