### ISSUE TITLE
微前端 JeecgBoot+ qiankun,打开子应用后，子应用内跳转无法正常加载，请问是什么原因？给个提示就行，实在找不到原因，网上也几乎没有关于 JeecgBoot + qiankun的资料，拜托了

### ISSUE THREAD

**Issue by zl871122** [jeecgboot/jeecg-boot#4912]
##### 截图&代码：
![image](https://user-images.githubusercontent.com/56527065/236753813-f882e5ea-a18e-4197-8715-e2b85fcaeffa.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2554339
