### ISSUE TITLE
导入功能异常

### ISSUE THREAD

**Issue by chenglutao** [jeecgboot/jeecg-boot#4914]
##### 版本号：
v3.4.4last

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
导入功能前后端 请求方式都是post，但提示 网络请求错误，请求方法未允许
系统代码未做修改

##### 截图&代码：

![image](https://user-images.githubusercontent.com/51188496/236782564-b56b1150-d5e1-40b6-8b2a-e920e08e3242.png)
![image](https://user-images.githubusercontent.com/51188496/236783020-6539179d-b5fb-4163-9aaa-5027ca86c1b6.png)
![image](https://user-images.githubusercontent.com/51188496/236783077-7ffa9120-5db1-4234-99a2-96c48f60fe88.png)
![image](https://user-images.githubusercontent.com/51188496/236783166-ee91ebdc-3f2a-4aab-9fe4-56a83e0ea3fc.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
本地还是服务器?

**Comment by chenglutao** [comment]
> 本地还是服务器?

服务器

**Comment by zhangdaiscott** [comment]
那就是跟部署有关，程序无问题

**Comment by chenglutao** [comment]
> 那就是跟部署有关，程序无问题

跟部署那块有关系呢？有什么指导思路吗？

**Comment by chenglutao** [comment]
> 那就是跟部署有关，程序无问题

是和前端部署相关还是后端部署相关？
