### ISSUE TITLE
jeecg-boot将单体引入注册中心,如果有contextPath,swagger 404,聚合各个服务的swagger;怎么获取那个服务contextPath并拼接在swagger url后呢

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#4915]
##### 问题描述：
MySwaggerResourceProvider聚合各个服务的swagger接口
   // 拼接url
            String url = "/" + instance.toLowerCase() + SWAGGER2URL;
这里instance如果有contextPath,网关要怎么配置呢,uri中获取不到contextPath

##### 截图&代码：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67467679/236809575-05fe1d90-28c9-4e3d-b5cd-295e72119ecd.png">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
为什么要将单体引入注册中心？

**Comment by zhangdaiscott** [comment]
为什么要将单体引入注册中心？

**Comment by zjarlin** [comment]
> 为什么要将单体引入注册中心？
单体当做一个外部服务,提供一些接口让其他服务调用;
使用archetype命令快速生成微服务模块怎么拆分成单独的git仓库?
况且需要迁移老的单体代码;一个仓库一个服务,这样流水线也好配置

**Comment by zhangdaiscott** [comment]
不支持单体注册到nacos，你可以把单体模块改成微服务模块
