### ISSUE TITLE
请问积木报表插入二维码打印的时候会自动多出来一页的问题如何解决了？

### ISSUE THREAD

**Issue by easonjim** [jeecgboot/jeecg-boot#4916]
请问积木报表插入二维码打印的时候会自动多出来一页的问题如何解决了？

**Comment by easonjim** [comment]
@zhangdaiscott

**Comment by zhangdaiscott** [comment]
提供截图

**Comment by bundyal** [comment]
easonjim i have a question.
I saw your AutoIT Installation Tool V3.0,
do you have the SkinCrafterDll.dll version 3.0 for me please
I now have the v2.7.2.0
I hope you can help me.
If so can you send me the link.

Greetings
