### ISSUE TITLE
积木报表导出PDF内容不全

### ISSUE THREAD

**Issue by zmj-upupup** [jeecgboot/jeecg-boot#4922]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用积木报表示例导出PDF，内容补全，发现是以虚线截断了后面的内容，请问如何解决？

##### 截图&代码：
<img width="1007" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/94438796/2f7dc97e-3aa8-4a91-afe7-50c5842acb6b">

<img width="1475" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/94438796/c3f4d873-6a10-4704-806d-8b41321cff74">

<img width="594" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/94438796/fa1f6d4a-9c85-4967-a415-c670e1737573">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/jimureport/print/rule.html

**Comment by zmj-upupup** [comment]
> https://help.jeecg.com/jimureport/print/rule.html

这是打印时的设置，我指的是导出功能， 导出excel、PDF等等，  这种没有解决办法吗？
