### ISSUE TITLE
查询组织的一些接口响应值code为0

### ISSUE THREAD

**Issue by zkai0102** [jeecgboot/jeecg-boot#4925]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
后端

##### 问题描述：
响应值code现在成功返回为0，能不能返回200

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/26482379/92243f03-f75d-43b7-a21d-ff332ce4186e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/26482379/4ce0eb72-5bae-48c8-80c9-2d829a2c09ce)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没明白，有什么问题？

**Comment by zhangdaiscott** [comment]
无回复关闭
