### ISSUE TITLE
前端设置了两个代理，不同业务请求不同域名下的接口，本地运行接口请求没问题，发到服务器上变为都请求一个域名下的地址

### ISSUE THREAD

**Issue by liumengqiang666** [jeecgboot/jeecg-boot#4926]
##### 截图&代码：
vue.config.js
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/ad0e562e-29bb-451c-9282-57f47353f68b)
utils
![NX)CONB%{RC`Z9C9TA0H7LQ](https://github.com/jeecgboot/jeecg-boot/assets/40190484/135b0974-5521-4dab-b5ac-982bfacc3220)
![YC$VW @7NL~F(8Z5OXBM$RE](https://github.com/jeecgboot/jeecg-boot/assets/40190484/fe2409c7-694d-475e-a029-76ae6e8d363c)
![Z%Z {TM$}W$)06X (P}K NH](https://github.com/jeecgboot/jeecg-boot/assets/40190484/5aaf1bae-2b1f-4452-9cd1-d3cbfa651571)
api
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/3909f80d-7f8b-46dc-8626-1bc9afbc6ef3)
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/f1278dd6-c985-4078-8429-440c6e3a7620)
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/6737821f-da0f-438f-baf9-469dc6ed6fa9)
使用/jeecg-boot代理的页面
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/aa7a9cfc-566b-4f84-b7c9-ea8c7c0e58d6)
使用/manager代理的页面
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/df289971-6656-45e1-ad49-6cf643a6944e)
index.html
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/6e134d2e-67de-4f9d-bcfe-d2beecc81512)
线上b页面的请求
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/c104e6ce-09d7-4014-8b53-1d97807aaa72)
线上a页面的请求
![image](https://github.com/jeecgboot/jeecg-boot/assets/40190484/dd7e9ca0-b8de-4fd6-b0df-e04b21edd6f2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
nginx自己映射
