### ISSUE TITLE
online开发的表单，使用Java增强后，配置了2个按钮，只有一个新增是生效的

### ISSUE THREAD

**Issue by JJFJJ218** [jeecgboot/jeecg-boot#4927]
##### 截图&代码：

<img width="964" alt="9b4c3f29a7403647ad920f173282f22" src="https://github.com/jeecgboot/jeecg-boot/assets/72841195/5db6a661-4ace-4d01-816c-813f588a99be">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没理解

**Comment by zhangdaiscott** [comment]
无回复，关闭
