### ISSUE TITLE
开发几天后，出现Online表单开发和Online报表配置功能出现“Token失效”无法访问的问题

### ISSUE THREAD

**Issue by damage-o** [jeecgboot/jeecg-boot#4928]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
开发几天后（之前正常），出现Online表单开发和Online报表配置功能出现“Token失效”无法访问的问题

##### 截图&代码：
开发几天后，出现Online表单开发和Online报表配置功能出现“Token失效”无法访问的问题,  其他系统菜单可以正常点击！

![image](https://github.com/jeecgboot/jeecg-boot/assets/18347954/9a294e0a-01a3-4cda-a65c-fe999c28cc2f)

服务是正常的
![image](https://github.com/jeecgboot/jeecg-boot/assets/18347954/10a32e48-e775-4be9-9e64-dd462be31ab2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
清下vite缓存
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/004b1b29-5810-4294-a66f-707f7e9964a5)
