### ISSUE TITLE
vue3版本

### ISSUE THREAD

**Issue by ByteisNull** [jeecgboot/jeecg-boot#4930]
##### 版本号：
jeecgboot3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
minio的yml文档配置失效，应该将prefix 改为·jeecg.minio·

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/23698928/c56cec53-e270-40e2-a4f3-2cf13b354602)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
感谢，修复了
