### ISSUE TITLE
SAAS模式下租户管理员创建的用户如何赋予权限

### ISSUE THREAD

**Issue by zmj-upupup** [jeecgboot/jeecg-boot#4931]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用多租户，通过admin账号新增租户，必须admin用户绑定上租户才能给租户分配一个用户套餐。 
由于角色管理没有进行租户隔离，所以此菜单不会分配给租户账号，请问租户用户的账号登录后，在租户用户菜单下新建的菜单，如何分配权限菜单？只能使用admin账号去进行分配吗？ 

##### 截图&代码：
![企业微信截图_16836896101660](https://github.com/jeecgboot/jeecg-boot/assets/94438796/5287969f-5853-4db5-b119-28b681af48ad)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/javaback/saas.html

**Comment by yinjianan** [comment]
> https://help.jeecg.com/javaback/saas.html

这个文档压根牛头不对马嘴，就是阉割版的多租户，逻辑一大堆问题，理论上租户创建后，租户下的子账号都改由租户的admin账号分配权限，但是现在还是只能超管去分配
