### ISSUE TITLE
代码生成的方式也展示 开启表单评论 功能

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecg-boot#4932]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online可以对表单进行评论，但代码生成的方式就不行，
是本身就不支持吗，我应该怎么处理配置，使生效。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by 45592858** [comment]
online可以对表单进行评论？怎么配置的，我试了在online表单开发中开启评论怎么也不行的？我也想在online表单中使用评论功能。

**Comment by 45592858** [comment]
哦哦，我找到了，在详情页，谢谢
