### ISSUE TITLE
前端vue2 如何升级到vue3

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecg-boot#4934]
##### 版本号：
 2.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
官方大大，请问vue2版的前端有什麽方法能升级到vue3呢？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持的，vue3是全新架构
