### ISSUE TITLE
租户用户编辑界面中租户下拉框未过滤，显示当前系统所有的租户

### ISSUE THREAD

**Issue by shanggushenlong** [jeecgboot/jeecg-boot#4935]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1. 租户用户  编辑界面中，租户栏位未过滤，会出现所有的租户，我当前登录的是云格致租户，编辑的时候，租户应该只有云格致租户，不应该出现 敲敲云  租户，看文档说一个用户可以有多个租户，但是目前我这种情况是，当前存在的两个租户，是完全不相关的租户，那么难道不应该是这个地方的租户只能是当前租户，不会切换到其他的租户下吗？

![image](https://github.com/jeecgboot/jeecg-boot/assets/20007857/082234ba-d7d3-4ec0-893b-376525519723)

2. 此接口 `/sys/tenant/queryList`  中参数，后端接受的是 ids，但是前端传入参数的如图为空，所以我目前看到的是 后端接口  ids  获取的值永远为 null，所以不生效，所以才会出现第一个问题，会查询出所有的租户，是否我理解业务的有误，还是此处确实有代码bug？

![1683977250972](https://github.com/jeecgboot/jeecg-boot/assets/20007857/9c82098f-b418-4c92-abe6-32d5012513b9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/20007857/8d074fb7-2f41-4092-946a-589aaed2df57)
![image](https://github.com/jeecgboot/jeecg-boot/assets/20007857/7a0b6765-a903-4703-9c62-b7cd3450e1ce)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已经处理了，现在是禁用状态
