### ISSUE TITLE
在自己的实现类中引入自己的依赖提示循环引入问题

### ISSUE THREAD

**Issue by lichangyou1981** [jeecgboot/jeecg-boot#4936]
##### 版本号：
 3.5.1  

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
在ServiceImpl实现类中，注入自己的接口启动服务时提示循环引入，需要@Lazy才能正常启动

##### 截图&代码：
NailSubjectServiceImpl 代码

@Service
public class NailSubjectServiceImpl extends ServiceImpl<NailSubjectMapper, NailSubject> implements INailSubjectService {
    @Autowired
    private INailSubjectService nailSubjectService;

The dependencies of some of the beans in the application context form a cycle:

   nailSubjectController (field protected com.baomidou.mybatisplus.extension.service.IService org.jeecg.common.system.base.controller.JeecgController.service)
┌─────┐
|  nailSubjectServiceImpl (field private org.jeecg.modules.colorpath.service.INailSubjectService org.jeecg.modules.colorpath.service.impl.NailSubjectServiceImpl.nailSubjectService)
└─────┘

Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你这是出现循环调用问题，改写法
