### ISSUE TITLE
:heavy_minus_sign: 删除 junit 4，使用默认的 junit 5

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [jeecgboot/jeecg-boot#4939]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
后端问题

##### 问题描述：
删除 junit 4，使用默认的 junit 5，简化代码

##### 截图&代码：
PR：https://github.com/jeecgboot/jeecg-boot/pull/4938

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
非bug 暂时归集到  https://github.com/jeecgboot/jeecg-boot/issues/1312 ，待后期规划
