### ISSUE TITLE
vue3版本online开发功能无法自动注入tenant_id的值

### ISSUE THREAD

**Issue by Michael4134** [jeecgboot/jeecg-boot#4941]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如题，vue3版本online开发功能无法自动注入tenant_id的值（题主按照官方文档配置发现online开发功能无法实现，其他功能如系统字典、发布公告等测试了没问题）。

##### 截图&代码：
![5c4411a4fda09970f306a5f605357844](https://github.com/jeecgboot/jeecg-boot/assets/50390254/8ef8f68f-3e46-42d8-ab36-de0a96044803)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
下个版本
