### ISSUE TITLE
popup 如何才能设置多选数据呢？

### ISSUE THREAD

**Issue by yanyanpeng** [jeecgboot/jeecg-boot#4942]
##### 前端版本：vue3版？还是 vue2版？

VUE3
##### 问题描述：
进销存系统：选择多条商品 插入到商品表中，如果选择3条商品，自动在数据表中插入 3条数据

##### 截图&代码：
![`X (2OR VWZ `72YVW0ZR W](https://github.com/jeecgboot/jeecg-boot/assets/60538506/cd894897-4b56-46c0-8f77-976b46bc9ce2)
![Z`DU} _9@GLBUIT)8{N`PM3](https://github.com/jeecgboot/jeecg-boot/assets/60538506/b21d8711-65de-463b-9c70-aa9e0199aec4)
![}R%2CN)4U}0D(DOKN%T8N6C](https://github.com/jeecgboot/jeecg-boot/assets/60538506/421b7691-2b5a-4722-afa2-8bfb0f63e75a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是在线还是代码生成？

**Comment by yanyanpeng** [comment]
在线的 怎么生成呢？
如果生成后的代码 好不好再改呢









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年5月16日(周二) 中午12:09写道:

  

 
你是在线还是代码生成？

**Comment by xiaomanvip** [comment]
我当时设置的时候是否多选没有进行配置，代码生成之后是可以使用的
