### ISSUE TITLE
菜单国际化和字典国际化要怎么实现？一个key对应多国语言

### ISSUE THREAD

**Issue by guduqiucai** [jeecgboot/jeecg-boot#4943]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37198471/eb0399d5-2998-4583-bdc1-bd85d1796ba6)

**Comment by guduqiucai** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/37198471/a918406f-8681-4bb8-b2d3-4a6a7aef3bf7)
菜单的配置已经找到了，字典要怎么配置呢？

**Comment by zhangdaiscott** [comment]
默认没这功能，你得自己改造

**Comment by guduqiucai** [comment]
有改造方案吗？麻烦说明一下
