### ISSUE TITLE
请问下JPopupOnlReport vue 文件问题

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4944]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
请问下components/jeecg/modal/JPopupOnlReport.vue
这个文件里的请输入在哪里啊，我找了半天没找到，我需要把请输入翻译成英文，能否告诉我在哪呢
全局搜索也没找到莫非是后端传到前端？
麻烦大佬们了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/d63dc517-3449-409d-9a5c-fe614383de64)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个是在底层，你改不了
