### ISSUE TITLE
数据字典功能在数据未重复的情况下提示“该值不可用，系统中已存在！“

### ISSUE THREAD

**Issue by Michael4134** [jeecgboot/jeecg-boot#4945]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如题，数据字典功能在数据未重复的情况下提示“该值不可用，系统中已存在！“，题主的版本是开启了多租户模式（不知道是否跟该设置有关系）。

##### 截图&代码：
![5d78674b5092312b6ac30a33f0e7d5b0](https://github.com/jeecgboot/jeecg-boot/assets/50390254/baa1e105-ae05-4abe-95e1-b4e3b149bf14)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws
