### ISSUE TITLE
使用oracle或mysql启动后端报未找到合适的驱动程序

### ISSUE THREAD

**Issue by liuhuan22** [jeecgboot/jeecg-boot#4946]
##### 版本号：
Jeecg  Boot Version: 3.5.1
Spring Boot Version: 2.7.10 (v2.7.10)

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
使用oracle或mysql启动报未找到合适的驱动程序

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/47617651/214a781b-7ebb-4399-bfc9-5674934c8f7f)

![image](https://github.com/jeecgboot/jeecg-boot/assets/47617651/40f329fe-2873-44bc-8d7b-5c11763d300a)

![image](https://github.com/jeecgboot/jeecg-boot/assets/47617651/351d46c2-9b93-4317-abc4-66970741d2c0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/676aa85c-fddd-446f-9060-e36fc25a75ac)
直接改成dev,maven没编译成功的问题

**Comment by liuhuan22** [comment]
> ![image](https://user-images.githubusercontent.com/3162115/238557677-676aa85c-fddd-446f-9060-e36fc25a75ac.png) 直接改成dev,maven没编译成功的问题

但是我用pom文件reload project并没有报错，重新编译项目也没有报错，我也对比过编译后的文件，配置是一致的，我按照你的要求改成了dev，启动后还是一样的问题
