### ISSUE TITLE
菜单编辑页面菜单图标选择模板，每页显示数量切换无效

### ISSUE THREAD

**Issue by Michael4134** [jeecgboot/jeecg-boot#4947]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如题，菜单编辑页面菜单图标选择模板，每页显示数量切换无效，从140条/页切换到其他如10条/页功能不生效。

##### 截图&代码：
![1684219327225_43E75087-AEAF-434e-9DED-636239C89C2B](https://github.com/jeecgboot/jeecg-boot/assets/50390254/46b1aaa8-8a19-4d2f-91a2-6c99cef92da9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
