### ISSUE TITLE
修改包扫描根路径，并按照文档说明调整了，但是启动报错

### ISSUE THREAD

**Issue by leilei0204** [jeecgboot/jeecg-boot#4948]
##### 问题描述：
修改包扫描根路径，并按照文档说明调整了，但是启动报错

##### 截图&代码：
![企业微信截图_16842196611918](https://github.com/jeecgboot/jeecg-boot/assets/133744894/f31d5d4d-7853-423f-b38e-46fc1f24ebed)
![image](https://github.com/jeecgboot/jeecg-boot/assets/133744894/a01a47de-158e-426b-8f7e-37db4d568e74)
![image](https://github.com/jeecgboot/jeecg-boot/assets/133744894/5fe2e04a-a87e-4f0e-b939-f6fea4e3e52b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
错误日志截全了

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
20

**Comment by CRIOWN** [comment]
请问解决这个问题了吗 我也遇到了相同的问题 已按照常见错误的改了 它只读了服务 没有对应的接口列表
