### ISSUE TITLE
怎么单独修改加载页面的文字呢？我修改了TokenLoginPage页面之后不管用，如果修改VITE_GLOB_APP_TITLE，其他地方也会修改....

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecg-boot#4952]
##### 问题描述：
怎么单独修改加载页面的文字呢？我修改了TokenLoginPage页面之后不管用，如果修改VITE_GLOB_APP_TITLE，其他地方也会修改....我只想修改加载页面的文字怎么办呢？
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/29888011/a8b43eb1-2094-4386-913e-ab273e5279e6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
只能改VITE_GLOB_APP_TITLE，你的那个需求不满足
