### ISSUE TITLE
图片导出数量缺少

### ISSUE THREAD

**Issue by xiaomanvip** [jeecgboot/jeecg-boot#4953]
##### 截图&代码：
@Excel(name = "图片", width = 15, height = 20,type=2)这是导出字段设置的图片类型
数据格式：http://1.png,http://2.png
![1684380924122](https://github.com/jeecgboot/jeecg-boot/assets/73579349/0c460339-3ce1-4621-a4db-8277ef0dbb97)
![image](https://github.com/jeecgboot/jeecg-boot/assets/73579349/ae5a9bc0-cbca-4d1d-b8df-4008d9f491cf)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
暂不支持
