### ISSUE TITLE
上传文件到oss,提示nginx 405 not allowed

### ISSUE THREAD

**Issue by XiaoQiaoLiuShui97** [jeecgboot/jeecg-boot#4954]
##### 问题描述：上传文件到oss，前端【文件上传】组件，提示 nginx 405 not allowed问题, 如何解决呢？
1.打包发布在服务器（阿里服务器）运行，会提示这个405的提示
2.但在本地运行，同样上传到oss则是成功的，很是奇怪

##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecg-boot/assets/105139366/f4ac45e9-7029-4f1b-8e21-53049aed19bd)

**Comment by zhangdaiscott** [comment]
F12看看什么错，是不是ngnix配置问题

**Comment by XiaoQiaoLiuShui97** [comment]
这边是使用宝塔面板来部署项目的
配置：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/105139366/2545d753-1f49-4971-91bb-e796d69698eb)
是不是哪里配置错了呢？

F12输出：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/105139366/4809a233-9cfd-4124-99c2-8097d49d6659)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/105139366/1e1d486e-c9d8-42d2-b8f0-ca786bfbd470)

**Comment by zhangdaiscott** [comment]
部署问题，请自己排查，这个我们帮不了

**Comment by TernenceZhou** [comment]
@XiaoQiaoLiuShui97 你好 请问您是怎么解决的呀 改了好久还没发现
