### ISSUE TITLE
online表单树形表单与单表导出图片问题

### ISSUE THREAD

**Issue by Sunnyweii** [jeecgboot/jeecg-boot#4955]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
发现online表单里面，
树形表单的导出功能使用的接口为/online/cgform/api/exportXls，
而单表表单的导出功能使用的接口为/online/cgform/api/exportXlsOld，前者导出时图片数据导出正常能显示图片，后者导出的时候图片则不正常，为对应图片的文件名，这个能不能统一使用前者作为导出的接口呢？

##### 截图&代码：
![P}3Q94R5)MZ%1T~%CK(O$G0](https://github.com/jeecgboot/jeecg-boot/assets/125847059/5fa868dd-6725-4af2-94a1-7f5994156612)
![image](https://github.com/jeecgboot/jeecg-boot/assets/125847059/eba7ae33-01d2-488f-9275-2520e9989476)
![$93F5SHEP_70`_PYNDC0J%B](https://github.com/jeecgboot/jeecg-boot/assets/125847059/f8842c19-6e80-4e31-97a2-f66d37114e92)
![image](https://github.com/jeecgboot/jeecg-boot/assets/125847059/20974af0-1054-4e71-b8b0-178430112495)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by Sunnyweii** [comment]
> ty

大佬，有解决办法吗？ @zhangdaiscott

**Comment by Sunnyweii** [comment]
> ty

我刚刚想用增强直接让它调/online/cgform/api/exportXls，但是增强只能用post，它这个是get的，没办法用增强搞

**Comment by Sunnyweii** [comment]
> 已修改

你好 能告知改的是哪个位置吗？我需要怎么在我本地修改

**Comment by Sunnyweii** [comment]
@tygithub1 你好 能告知改的是哪个位置吗？我需要怎么在我本地修改

**Comment by zhangdaiscott** [comment]
下个版本发布

**Comment by Sunnyweii** [comment]
那我现在这个问题能通过其他方式解决吗

> 下个版本发布

**Comment by Sunnyweii** [comment]
> 下个版本发布

能告知是前端的问题还是后端的问题吗？下个版本是指新版本还是新的commit呢？

**Comment by Sunnyweii** [comment]
> 已修改

@tygithub1 您好啊~能告知我一下这个是要怎么修改吗？我现在项目急着解决这个问题。

**Comment by tygithub1** [comment]
> > 已修改
> 
> @tygithub1 您好啊~能告知我一下这个是要怎么修改吗？我现在项目急着解决这个问题。
org.jeecg.modules.online.cgform.controller.OnlCgformApiController
![image](https://github.com/jeecgboot/jeecg-boot/assets/27989856/f659a778-5079-4a09-bcde-7f950f39dffd)

**Comment by zhangdaiscott** [comment]
下个版本发布才能解决，你自己改不了

**Comment by Sunnyweii** [comment]
> 下个版本发布才能解决，你自己改不了

@zhangdaiscott 是等新版本还是等新的commit呀？
