### ISSUE TITLE
在根路径下打包时报错了mvn install -P prod,SpringCloud

### ISSUE THREAD

**Issue by haijie3505** [jeecgboot/jeecg-boot#4956]
##### 截图&代码：
[ERROR] Failed to execute goal on project jeecg-boot-base-core: Could not resolve dependencies for project org.jeecgframework.boot:jeecg-boot-base-core:jar:3.4.0: Could not find artifact org.jeecgframework.boot:jeecg-module-mf-api:jar:1.0.0-SNAPSHOT in jeecg-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]

![image](https://github.com/jeecgboot/jeecg-boot/assets/5211886/7127665d-4d3e-4458-96ca-3a15637733ae)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
先全部install
