### ISSUE TITLE
PREFIX_USER_SHIRO_CACHE刷新bug

### ISSUE THREAD

**Issue by hhw3KevinHou** [jeecgboot/jeecg-boot#4957]
##### 问题描述：
doGetAuthorizationInfo中的SimpleAuthorizationInfo存储了roles和Permissions信息。只有退出才清空缓存：
![image](https://github.com/jeecgboot/jeecg-boot/assets/14155363/413047a2-ccdd-4ef1-a21b-97f4b77ba0ed)

1、编辑用户角色和权限时都没有清空，导致使用
subject.hasRole等内置方法不能得到正确结果。

2、源码中所有获取角色的操作都用查数据库的方式，没有利用缓存的好处，不知为何：
![image](https://github.com/jeecgboot/jeecg-boot/assets/14155363/27aba56b-b2dc-41b8-b85e-2909b23a0e06)

 

 建议shiro权限这整体考虑下缓存的作用，如果不需要就干掉缓存，可能引起bug。

**Comment by zhangdaiscott** [comment]
sq

**Comment by hhw3KevinHou** [comment]
sq？死球？

**Comment by hhw3KevinHou** [comment]
sq？死球？

**Comment by lsqGitHub716** [comment]
1.目前系统更新角色和权限的时候，需要退出重新登录
2.目前缓存暂时没有用到，后期优化
