### ISSUE TITLE
Online表单开发对数据库表结构进行CRUD的源代码在哪里啊？

### ISSUE THREAD

**Issue by liuzemin2010** [jeecgboot/jeecg-boot#4958]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online表单开发对数据库表结构进行CRUD的源代码在哪里啊？

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/31055725/bbfcdbc1-96ea-42dc-bf46-720228207216)

就是这个模块对应的源代码，前端的没找到，后端的也没找到，请问这个Online表单开发对应的源代码在哪里啊，在线等大佬求助啊，谢谢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个是零代码
