### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by jincj** [jeecgboot/jeecg-boot#4959]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
使用范型返回数据时@SensitiveEncode敏感数据加密失效

##### 截图&代码：

<img width="1053" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/20831866/7ade6f30-c4a4-4f56-9078-1f930bc7a8c6">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by lsqGitHub716** [comment]
请参考文档方式编写：http://doc.jeecg.com/2767952；

**Comment by lsqGitHub716** [comment]
如果设置还是有问题，请把你配置的相关代码贴图

**Comment by jincj** [comment]
分页查询试试
![image](https://github.com/jeecgboot/jeecg-boot/assets/20831866/9a5b7a74-709d-4c10-a486-2d1132b5dddf)

**Comment by lsqGitHub716** [comment]
目前支持以下返回类型，其他类型如IPage等特殊格式不支持
![image](https://github.com/jeecgboot/jeecg-boot/assets/65587928/4855def3-ff2e-47e5-ae75-6f743fc4a400)
