### ISSUE TITLE
rabbitmq 消费 报 reply-code=406, reply-text=PRECONDITION_FAILED  消息重复投递

### ISSUE THREAD

**Issue by vegaxh** [jeecgboot/jeecg-boot#4960]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
当项目引入jeecg-boot-starter-rabbitmq  版本为3.5.1 时， 消费端当异常中断后，报 消息重复投递。
reply-code=406, reply-text=PRECONDITION_FAILED - unknown delivery tag 1, class-id=60, method-id=80。
如下图所示：

##### 截图&代码：、
1、报错信息截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/1691234/3bbc78c0-11d2-4c2a-b2ff-454916d240dd)

2、消费端代码截图

![image](https://github.com/jeecgboot/jeecg-boot/assets/1691234/9ac3d0a6-ef62-4001-8db2-605c1bc734eb)

3、yml配置代码截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/1691234/a1ab1f6e-1b96-4cb5-be03-df8cf562ac44)

4、查看jeecg 封装好的配置源文件，发现如图所示factory.setAcknowledgeMode(AcknowledgeMode.AUTO);
![image](https://github.com/jeecgboot/jeecg-boot/assets/1691234/cd8e9da8-b0ec-40b5-ab36-d4c1a65a21ba)

网上还有人说 配置文件里引用了  MappingJackson2MessageConverter 这个，当用这个去解析时，会优先使用AUTO ?
看这个帖子：
https://blog.csdn.net/m912595719/article/details/83787486

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xfangs** [comment]
请问下，你解决了这个问题了吗？，我也遇到相同的问题了

**Comment by zhangdaiscott** [comment]
xp

**Comment by EightMonth** [comment]
如果切换手动消费模式，需要在消费代码中调用函数channel.basicAck()进行手动确认
