### ISSUE TITLE
springboot 3.X支持，加速spring进化

### ISSUE THREAD

**Issue by weir2010** [jeecgboot/jeecg-boot#4961]
对于springboot3.0 整合shiro我已经写了一个demo：http://www.loveweir.com/view/141
可以参考。也算是我对jeecg社区做的一点贡献，希望jeecg的 java底层也能紧跟时代脉搏

**Comment by zhangdaiscott** [comment]
3q

**Comment by zhangdaiscott** [comment]
非bug 暂时归集到  https://github.com/jeecgboot/jeecg-boot/issues/1312 ，待后期规划
