### ISSUE TITLE
希望可以出一版  把微服务架构拆分更加细致一点 还有数据库表设计分开解耦合 配置文件也分开  遵循cloud的设计思想

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#4963]

**Comment by zjarlin** [comment]
这位道友,想到一块去了;我目前理解的微服务单服务应该单服务单个仓库;微服务部署连不同服务器的redis应当也可以互相调用接口不报token失效问题(感觉要搭主从集群jboot-system连master,业务模块连slave1,slave2...);是不是应当关闭对jboot core模块和system模块的修改;打成jar包放进jboot私服让业务模块引用呢;这个我们就可以单仓库单服务使用

**Comment by hutianxi** [comment]
> 这位道友,想到一块去了;我目前理解的微服务单服务应该单服务单个仓库;微服务部署连不同服务器的redis应当也可以互相调用接口不报token失效问题(感觉要搭主从集群jboot-system连master,业务模块连slave1,slave2...);是不是应当关闭对jboot core模块和system模块的修改;打成jar包放进jboot私服让业务模块引用呢;这个我们就可以单仓库单服务使用

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/9d3fa33d-4565-4e39-80cb-43b55591f7e6)
我也在思考做这个事儿

**Comment by EightMonth** [comment]
插一句嘴，一：微服务没错，但是不要过度微服务。二：微服务划分，个人觉得吧，第一看体量，如果没有多少万级的体量，微服务划分，无非在炫技而已。第二看业务复杂度，如果一个用户服务，总共也就只需要那么十几个接口，会员服务两个接口，积分服务两个接口，需要划分三个服务么，我想不需要吧。第三看团队人数，如果一个团队只有两三个人，需要去维护十几个服务的代码，是否合理，再者说，20个人的团队在一个分支上折腾，合代码耗费了大量时间又是否合理，建议从实际问题考虑微服务代码工程的设计。

Part ||
可以看下jeecg-boot-starter，这其实是个典型的微服务划分的仓库，如果觉得看懂了，再进一步看下spring cloud的微服务划分。

**Comment by xiaobing006** [comment]
后续考虑这样拆分微服务吗？
