### ISSUE TITLE
online表单代码生成后，没有权限新增/编辑/删除，提示“没有权限，请联系管理员授权”

### ISSUE THREAD

**Issue by jianchunzhu** [jeecgboot/jeecg-boot#4964]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online表单代码生成后，新增/编辑/删除都会提示“没有权限，请联系管理员授权
sql执行了，sys_permission有表单数据。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/58016472/5d6fe75d-51ef-430a-9258-3388d0bde043)

去掉@RequiresPermissions("qingjia:ceshi_note:add")后，可以增加。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
执行升级sql，授权按钮操作权限
