### ISSUE TITLE
已逻辑删除的数据仍然可以显示

### ISSUE THREAD

**Issue by WeiFengo** [jeecgboot/jeecg-boot#4965]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
已逻辑删除的数据，前端下拉框通过dictCode="line,description,id"获取，仍然可以显示被删除的。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/103655726/4bfd8ba2-9116-4fe7-a4d2-0fb4127b36ba)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这块查询没考虑逻辑删除逻辑，你需要的话可以自己改造加上
