### ISSUE TITLE
online在线表单没有此菜单的角色使用时提示无权限

### ISSUE THREAD

**Issue by HongxunDou** [jeecgboot/jeecg-boot#4966]
##### 版本号：

 v3.5.1
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

online在线表单，字段使用关联记录，在角色有online表单菜单的权限下，关联记录可以使用，在角色没有online表单菜单权限下提示没有权限，要是使用online创建的表单还非得要使用的角色有online表单菜单权限吗？谢谢大佬回复~~
##### 截图&代码：
此账号没有online表单菜单权限
![image](https://github.com/jeecgboot/jeecg-boot/assets/134220606/3c78b1d3-2afb-4b61-9583-cab39520c0e5)

有online表单菜单权限
![image](https://github.com/jeecgboot/jeecg-boot/assets/134220606/44e34878-56b4-4968-acee-be486ceb2b5d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
关联记录用的也是online的表，理论上你想访问某个表的数据也是需要配置该表对应菜单的访问权限的，如果没有配置菜单，会依据online表单的菜单权限判断
