### ISSUE TITLE
部署到线上出现online报表无法访问sql获取数据以下问题

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#4967]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
本地环境就可以访问报表，但是部署到线上就不行，但是其他接口又可以hen很奇怪，mysql 也检查过了都没问题，
网上各种方法都试过，没用

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/eb97b597-9b96-4346-9ebf-eb466b344f9a)

![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/a4429135-e41e-4ff9-8fd0-84e915c9c3e8)

![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/033f1899-bba3-4535-b006-b8c028ba4a63)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by LiCain** [comment]
前端是通过j-popup 弹框出来没数据，本地后台显示正常，部署上线就出现这个问题

**Comment by zhangdaiscott** [comment]
提示的是账号密码不对，online是不是配置的单独数据源，修改下
