### ISSUE TITLE
代码生成后，按照教程配置子菜单，报VUE没找到相关模块的路由

### ISSUE THREAD

**Issue by ElricWu1980** [jeecgboot/jeecg-boot#4968]
##### [截图&代码：]
<img width="568" alt="4afb25fea4d2c9d7b620961d225967c" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/13b4899e-5178-47b8-b167-e54702703190">
<img width="799" alt="a3c95a780e74b12fca9ee56a2500b14" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/2d9e70f0-789c-4765-8fd5-0fbd4307a749">
<img width="808" alt="f1938eaa163b64367a6d98106103d1b" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/1ff72583-9010-4801-a108-6e463709980f">
<img width="829" alt="f5d1562204b8d62b08faf215f3150de" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/476b4af5-b363-4490-9fd4-6db4adb6c70e">
<img width="757" alt="e8231967564167e0b0c9f56e6d4cba0" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/b28447bd-89e3-4665-947d-1cf5eb17680a">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
前端组件的路径肯定有问题

**Comment by ElricWu1980** [comment]
<img width="456" alt="50089260084ff93f3f3b290af588e28" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/f641246d-f140-4151-9d78-f4534cbdb03a">
已经放在views下~

**Comment by ElricWu1980** [comment]
> 前端组件的路径肯定有问题

<img width="456" alt="50089260084ff93f3f3b290af588e28" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/d8c991c7-0419-476e-9862-96e12b4f7f5e">
在views下新建了一个company目录，并且文件已放进去，也配置了子菜单
<img width="829" alt="f5d1562204b8d62b08faf215f3150de" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/6f430578-4b68-48b7-87df-63dd204087d3">
