### ISSUE TITLE
生成代码后，按照教程配置子菜单，报没有找到相关模块的路由，怎么解决?

### ISSUE THREAD

**Issue by ElricWu1980** [jeecgboot/jeecg-boot#4969]
##### 版本号：
3.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
生成代码后，按照教程配置子菜单，报没有找到相关模块的路由

##### 截图&代码：
按照教程把生成的代码放到views目录下：<br>
<img width="456" alt="50089260084ff93f3f3b290af588e28" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/df8fc6f3-e559-4755-9940-634e25c880e7">
然后，配置一级菜单<br>
<img width="808" alt="f1938eaa163b64367a6d98106103d1b" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/9ea56283-2264-47c9-b53d-130b6814bed5">
接着配置子菜单<br>
<img width="829" alt="f5d1562204b8d62b08faf215f3150de" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/2f64d300-528a-4dbc-ad4b-44b6040173e6">
但是应用时报没找到相关模块
<img width="799" alt="a3c95a780e74b12fca9ee56a2500b14" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/f1ebdde3-6e70-4105-894b-01f2ea384826">
<img width="757" alt="e8231967564167e0b0c9f56e6d4cba0" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/139d87ac-4bc1-487a-ae4e-be0f8b15119e">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己配错了，这种问题，好好看文档

**Comment by ElricWu1980** [comment]
已经对了，好几回了，还是一样~

**Comment by ElricWu1980** [comment]
知道了，区分大小写
