### ISSUE TITLE
为什么会出现接口这样的404找不到资

### ISSUE THREAD

**Issue by ElricWu1980** [jeecgboot/jeecg-boot#4970]
##### 版本号：
V3.4

##### 前端版本：vue3版？还是 vue2版？
VUE2

##### 问题描述：
同样的接口地址， http://localhost:8080/jeecg-boot/testop/testOp/list?_t=1684815368&column=createTime&order=desc&field=id,,,name,action&pageNo=1&pageSize=10
Request Method: OPTIONS 访问正常,Request Method: GET 出现404

##### 截图&代码：
<img width="918" alt="bb89cfe186ec01481ef6d739c28dc83" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/63a937e6-e53e-4b16-9e78-3c3361947a7a">
<img width="959" alt="5755452990cc348dd2a785ca40863cc" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/ac38515f-6d11-47b6-88a3-7c10c266aa4f">
<img width="956" alt="30b861a922224935d65bbeb25604ee4" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/8e648e51-19d6-42a4-89fb-99906e675543">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是你自己新增接口，请自己排查
