### ISSUE TITLE
ReferenceError: Cannot access 'pageWrapper' before initialization  

### ISSUE THREAD

**Issue by IVanMissAya** [jeecgboot/jeecg-boot#4971]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
本地运行，会时不时的报这个错误 导致项目崩溃，页面访问不了。

##### 截图&代码：
![微信图片_20230523153453](https://github.com/jeecgboot/jeecg-boot/assets/38241168/333bf251-6852-409f-bb54-156f15e78dfa)
![微信图片_20230523153507](https://github.com/jeecgboot/jeecg-boot/assets/38241168/e2cb5968-db06-44c9-997b-c8f40cff2ec3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
刚提了，你更新下代码
https://github.com/jeecgboot/jeecgboot-vue3/commit/87580883d188cb38e3babe497f527cdfcd89be72

**Comment by IVanMissAya** [comment]
好的 谢谢大佬
