### ISSUE TITLE
用户导出失败报错

### ISSUE THREAD

**Issue by Asenlen** [jeecgboot/jeecg-boot#4972]
##### 问题描述：
你好：

我在配置文件中设置了上传目录为绝对路径：
/Users/boot/jeecg/opt/upFiles

但是我在用户管理界面导出用户时，提示错误，错误内容为：
ERROR o.j.poi.excel.export.ExcelExportServer:210 - Index 0 out of bounds for length 0

如果我把 exportParams.setImageBasePath(upLoadPath);这个代码注释起来就不会出现错误，这个如何解决？

##### 截图&代码：

@RequestMapping(value = "/exportXls")
    public ModelAndView exportXls(SysUser sysUser,HttpServletRequest request) {
        // Step.1 组装查询条件
        QueryWrapper<SysUser> queryWrapper = QueryGenerator.initQueryWrapper(sysUser, request.getParameterMap());
        //Step.2 AutoPoi 导出Excel
        ModelAndView mv = new ModelAndView(new JeecgEntityExcelView());
        //update-begin--Author:kangxiaolin  Date:20180825 for：[03]用户导出，如果选择数据则只导出相关数据--------------------
        String selections = request.getParameter("selections");
        if(!oConvertUtils.isEmpty(selections)){
            queryWrapper.in("id",selections.split(","));
        }
        //update-end--Author:kangxiaolin  Date:20180825 for：[03]用户导出，如果选择数据则只导出相关数据----------------------
        List<SysUser> pageList = sysUserService.list(queryWrapper);

        //导出文件名称
        mv.addObject(NormalExcelConstants.FILE_NAME, "用户列表");
        mv.addObject(NormalExcelConstants.CLASS, SysUser.class);
        LoginUser user = (LoginUser) SecurityUtils.getSubject().getPrincipal();
        ExportParams exportParams = new ExportParams("用户列表数据", "导出人:"+user.getRealname(), "导出信息");
        exportParams.setImageBasePath(upLoadPath);
        mv.addObject(NormalExcelConstants.PARAMS, exportParams);
        mv.addObject(NormalExcelConstants.DATA_LIST, pageList);
        return mv;
    }

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
路径是不是不存在？

**Comment by lsqGitHub716** [comment]
测试未发现你说的情况，除了设置upLoadPath=/Users/boot/jeecg/opt/upFiles；您是否还有其他配置修改，或者详细描述一下你的bug复现步骤
