### ISSUE TITLE
online表单开发在线表格配置的多租户无效

### ISSUE THREAD

**Issue by liuzhenyin** [jeecgboot/jeecg-boot#4974]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/3850530/0a04e89f-7bbe-4cd4-b7d7-017a3fad113c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/3850530/3919a4a4-04aa-463d-b5ca-fde64d3b2607)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
需要等online升级
