### ISSUE TITLE
GlobalAccessTokenFilter类StripPrefix作用没生效,导致调用微服务接口失败

### ISSUE THREAD

**Issue by yangyang122** [jeecgboot/jeecg-boot#4980]
##### 版本号：
jeecg-boot  3.5.1  以springcloud nacos运行 微服务调用

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
微服务context-path无配置，gateway GlobalAccessTokenFilter类StripPrefix作用没生效,导致调用微服务接口失败.

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/12775735/cc34a685-23ee-4f3b-b55b-a20a9817a629)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/12775735/cd2b170c-02c3-4175-8b0d-78d925279cf9)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/12775735/4b6cfea5-4160-4214-b894-5f770e5d78ef)

修改后的代码可以支持这种处理

`public class GlobalAccessTokenFilter implements GlobalFilter, Ordered {
    public final static String X_ACCESS_TOKEN = "X-Access-Token";
    public final static String X_GATEWAY_BASE_PATH = "X_GATEWAY_BASE_PATH";

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpRequest request = exchange.getRequest();
        String scheme = request.getURI().getScheme();
        String host = request.getURI().getHost();
        String uri=request.getURI().getRawPath();
        int port = request.getURI().getPort();
        String basePath = scheme + "://" + host + ":" + port;
        log.info("request origin uri:{}",uri);
        // 1. 重写StripPrefix(获取真实的URL)
        addOriginalRequestUrl(exchange, request.getURI());
        String rawPath = request.getURI().getRawPath();
        String newPath = "/" + Arrays.stream(StringUtils.tokenizeToStringArray(rawPath, "/")).skip(1L).collect(Collectors.joining("/"));
        //2.将现在的request，添加当前身份
        ServerHttpRequest newRequest = request.mutate().path(newPath)
                .header("Authorization-UserName","")
                .header(X_GATEWAY_BASE_PATH,basePath)
                .build();
        exchange.getAttributes().put(GATEWAY_REQUEST_URL_ATTR, newRequest.getURI());
        log.info("handle request origin uri:{}",newRequest.getURI().getRawPath());
       
        ServerWebExchange mutableExchange = exchange.mutate().request(newRequest).build();
        return chain.filter(mutableExchange);
    }

    @Override
    public int getOrder() {
        return 0;
    }

}`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
既然微服务了，为什么不是通过gateway转发调用，你这个用法不符合常理吧

**Comment by yangyang122** [comment]
我是通过微服务转发的，只不过我在网关route上配置了/jeect-system/**匹配这个微服务

**Comment by yangyang122** [comment]
![图片](https://github.com/jeecgboot/jeecg-boot/assets/12775735/84b9bcd9-b9c5-4094-b1a4-6c0848e6d7f3)
把其他的去掉了，配置了个统一的前缀
