### ISSUE TITLE
请问jeecgboot一定需要开启redis吗？可否把redis关掉？怎么操作？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#4981]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/930cc811-41d7-441c-8b9f-b8455aaf51b3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
必须
