### ISSUE TITLE
代码生成Vue3缺失data.ts和List.vue文件

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/jeecg-boot#4982]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by catlvsuger** [comment]
后端升级到3.5.1， 代码生成器版本 <codegenerate.version>1.4.3</codegenerate.version> 模板文件、CgformEnum 已经文件更新到最新

**Comment by zhangdaiscott** [comment]
报错了吗

**Comment by catlvsuger** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/39261781/f6a76415-41ae-4b59-8581-295b0c5af5dd)

**Comment by zhangdaiscott** [comment]
配置有问题，自己排查下

**Comment by catlvsuger** [comment]
新建的表是可以的，以前的表的就生成报错，经检查 db_is_persist 字段区别，以前的表 db_is_persist 为 null，
