### ISSUE TITLE
online在线表单Popub控件展示数据问题

### ISSUE THREAD

**Issue by a1643977841** [jeecgboot/jeecg-boot#4985]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
online在线表单Popub控件配置online报表之后弹出的选择器数据不对。
当分页选择10页每条时，只加载了一条数据。
当分页选择20页每条时，才加载完两条数据。
按照我的理解应该在10页每条时，两条数据就应该全部展示
##### 截图&代码：
<img width="1220" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/4c421037-5f39-4ca4-9410-16ef5c523cd2">
<img width="1212" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/0d34bbba-1486-40f9-b681-77dd3e24a87f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
怎么出现的？

**Comment by a1643977841** [comment]
就是正常按照视频步骤，先创建online报表，然后在online在线表单配置里面选择校验字段配置字典，配置完成之后功能测试的时候就出现了以下情况，数据源一共有2条数据，但是弹出的选择器里面只有一条数据，需要选择分页为20页的时候，第二条数据才出现。发件人: ***@***.*** ***@***.***> 代表 JEECG ***@***.***>日期: 星期六, 2023年5月27日 18:27收件人: jeecg-boot ***@***.***>抄送: 1643977841 ***@***.***>, author ***@***.***>主题: Re: [jeecgboot/jeecg-boot] online在线表单Popub控件展示数据问题 (Issue #4985)怎么出现的？—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by a1643977841** [comment]
就是正常按照视频步骤，先创建online报表，然后在online在线表单配置里面选择校验字段配置字典，配置完成之后功能测试的时候就出现了以下情况，数据源一共有2条数据，但是弹出的选择器里面只有一条数据，需要选择分页为20页的时候，第二条数据才出现。发件人: ***@***.*** ***@***.***> 代表 JEECG ***@***.***>日期: 星期六, 2023年5月27日 18:27收件人: jeecg-boot ***@***.***>抄送: 1643977841 ***@***.***>, author ***@***.***>主题: Re: [jeecgboot/jeecg-boot] online在线表单Popub控件展示数据问题 (Issue #4985)怎么出现的？—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by a1643977841** [comment]
> 怎么出现的？

就是正常按照视频步骤，先创建online报表，然后在online在线表单配置里面选择校验字段配置字典，配置完成之后功能测试的时候就出现了以下情况，数据源一共有2条数据，但是弹出的选择器里面只有一条数据，需要选择分页为20页的时候，第二条数据才出现

**Comment by a1643977841** [comment]
> 怎么出现的？

我重新删除该报表之后，重新换了一个编码重新创建一模一样的sql，然后在配置到表单里面 弹出的选择器数据就正常了能正常显示

**Comment by a1643977841** [comment]
> 怎么出现的？

还有一个问题
就是一切配置完成之后，我去修改了报表，增加了某个字段，但是弹窗选择器并没有增加这个字段。看下图

<img width="1426" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/eba14695-dbb8-4387-8097-59cc29aaa468">

<img width="1301" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/7cdaccdc-ed94-458f-a594-7bf9ea0867de">

**Comment by a1643977841** [comment]
> 怎么出现的？

以及用户选择器数据回显问题
<img width="895" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/023fcd3a-2104-4e8b-9fc5-f86b850b1dda">

**Comment by zhangdaiscott** [comment]
ty 应该是缓存问题

**Comment by a1643977841** [comment]
> ty 应该是缓存问题

用户选择器数据回显问题呢

**Comment by tygithub1** [comment]
1.popup问题未重现，并且popup控件查询列表数据没有缓存，请确认自己的配置是否有问题
2.报表添加某一列后，popup没有出来的问题，测试未重现，列的信息查询有缓存，但是在报表编辑的时候会清除，所以不会出现该问题。
3.用户选择器默认是存的用户账号，你这个显示id说明之前你配置了用户组件的自定义存储字段，然后又把配置删掉了，旧数据导致的问题。
