### ISSUE TITLE
菜单管理勾选隐藏Tab无效

### ISSUE THREAD

**Issue by a1643977841** [jeecgboot/jeecg-boot#4986]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
菜单管理勾选隐藏Tab保存之后 实际保存失效（再次打开还是未勾选）

##### 截图&代码：

<img width="1251" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/507de4b2-eb1f-4d22-8a52-dbfa5258cf32">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by UxieVerity** [comment]
我在演示的页面没遇到这个问题，因为我修改的时候直接提示没有权限

**Comment by zhangdaiscott** [comment]
已经提交
