### ISSUE TITLE
vue3演示页面菜单异常

### ISSUE THREAD

**Issue by UxieVerity** [jeecgboot/jeecg-boot#4988]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
演示页面：[vue3演示页面](http://boot3.jeecg.com/online/cgreport/6c7f59741c814347905a938f06ee003c)
点击左侧菜单 **_统计报表_**》**_online用户统计_** 的时候会 收起统计报表菜单并打开**_在线开发_**菜单

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/27985668/78ce65c7-0910-48bb-bcca-0e9020ceb304)
![image](https://github.com/jeecgboot/jeecg-boot/assets/27985668/674c005d-1450-4acd-9630-718c90b1784a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已经修复了，下个版本发布
