### ISSUE TITLE
在线开发中配置的表，操作删除后，提示删除成功，但数据却还在，修改数据保存后，也还是原来的

### ISSUE THREAD

**Issue by ElricWu1980** [jeecgboot/jeecg-boot#4989]
##### 版本号：
V3.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在线开发中配置的表，操作删除后，提示删除成功，但数据却还在，修改数据也一样保存后，也还是原来的，后端也没报错
##### 截图&代码：
<img width="894" alt="dfb483a4b9eb9b57037a4f78e0e60af" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/deda860c-990b-45d5-9e78-0c8d26b2e94d">
<img width="877" alt="cde4c99697dfeff0ac430f454280316" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/6fbda821-a799-40cd-9030-cc4252b9bdc0">
<img width="960" alt="f94feda348f609eee9ee06d1288d2b4" src="https://github.com/jeecgboot/jeecg-boot/assets/54934157/247c4957-8d45-4e68-ab53-52783dee067b">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
具体版本号？
