### ISSUE TITLE
nacos开启鉴权报403bug

### ISSUE THREAD

**Issue by hzitao** [jeecgboot/jeecg-boot#4991]
##### 版本号：
2.4.3

##### 问题描述：

nacos服务端开启鉴权后，可以获取配置，但无法注册
原因：在排除了nacos-client版本问题之后，应用还是注册不上nacos。后来经过debug发现bootstrap.yml配置少了 discovery的用户名密码配置，必须加上！！！不然nacos开启鉴权时可以获取配置，但是无法注册，报403，然后处于假死状态
##### 截图&代码：
需要在bootstrap.yml的discovery下面加入username和password的配置用于注册
![image](https://github.com/jeecgboot/jeecg-boot/assets/44660862/f48260e3-169c-433f-8331-1931e75c962e)

具体配置如下
`spring:
  profiles:
    # 当前激活环境
    active: @profile.name@
  cloud:
    #配置Bus id(远程推送事件)
    bus:
      id: ${spring.application.name}:${server.port}
    nacos:
      config:
        # Nacos 认证用户
        username: nacos
        # Nacos 认证密码
        password: nacos
        # 命名空间 常用场景之一是不同环境的配置的区分隔离，例如开发测试环境和生产环境的资源（如配置、服务）隔离等
        namespace: @config.namespace@
        # 配置中心地址
        server-addr: @config.server-addr@
        # 配置对应的分组
        group: @config.group@
        # 配置文件后缀
        file-extension: yaml
        prefix: @prefix.name@
          # 支持多个共享 Data Id 的配置，优先级小于extension-configs,自定义 Data Id 配置 属性是个集合，内部由 Config POJO 组成。Config 有 3 个属性，分别是 dataId, group 以及 refresh
          #shared-configs[0]:
          #data-id: @prefix.name@-common.yaml # 配置文件名-Data Id
          #group: @config.group@   # 默认为DEFAULT_GROUP
        #refresh: false   # 是否动态刷新，默认为false
      discovery:
        # Nacos 认证用户
        username: nacos
        # Nacos 认证密码
        password: nacos
        namespace: @config.namespace@
        server-addr: @config.server-addr@
        watch:
          enabled: false`

**注意**：用户名密码根据自己nacos配置改变
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by hzitao** [comment]
你们好像理解错了，我说的是nacos服务端开启鉴权无法请求（官网自己下载的），因为在bootstrap.yml配置少了discovery的相关配置，导致nacos客户端可以获取到nacos服务端的config，但是无法获取到注册的实例信息，加上那个discovery相关信息即可。

**Comment by symbre** [comment]
com.alibaba.nacos.client.security.SecurityProxy的login(String server)方法中，POST里传输的password被URL编码了bodyMap.put("password", URLEncoder.encode(password, "utf-8"));实际不需要，设置nacos控制台密码的时候尽量不要出现@之类的字符，否则会登录失败

**Comment by symbre** [comment]
com.alibaba.nacos.client.security.SecurityProxy的login(String server)方法中，配置在jeecg-boot-parent POM.xml里的<config.password>nacos@123</config.password>中的password被URL编码了bodyMap.put("password", URLEncoder.encode(password, "utf-8"));实际不需要，设置nacos控制台密码的时候尽量不要出现@之类的字符，否则会登录失败
