### ISSUE TITLE
online表单开发 字段控件类型是关联记录  新增的时候选择列表可以添加查询么

### ISSUE THREAD

**Issue by guotiantian111** [jeecgboot/jeecg-boot#4992]
##### 版本号：

3.5.1
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

online表单开发 字段控件类型是关联记录  新增选择其他表记录的时候列表可以添加查询么

##### 截图&代码：

<img width="919" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/30343082/a0b9ccd8-bc7a-4aca-a6e8-62cf17f67697">
<img width="772" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/30343082/9d30ecc9-ac4d-4cff-86e4-f89bb2482d00">
<img width="1138" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/30343082/9dbe7a79-9e52-4ab7-930b-a5c4dd091566">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

后期考虑扩展
