### ISSUE TITLE
online表单代码生成功能提示“网络请求错误，未找到该资源”

### ISSUE THREAD

**Issue by Michael4134** [jeecgboot/jeecg-boot#4996]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如题，题主按照教程一步步操作online表单代码生成功能，操作了很多次，都是提示“网络请求错误，未找到该资源”。

##### 截图&代码：
![e74c1eaf4413f23df0cef51ad36091f5](https://github.com/jeecgboot/jeecg-boot/assets/50390254/6604b000-cfc2-497e-bf4e-1af8262a2dab)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Michael4134** [comment]
补充一下，是新创建的module模块有这个问题。

**Comment by zhangdaiscott** [comment]
微服务？

**Comment by Michael4134** [comment]
单体的。我看到文档那里“ IDEA快速创建module模块”没有更新，是不是创建module出了问题，如果是这个问题可否更新一下通过IDEA创建module模块的文档内容，谢谢。

**Comment by Michael4134** [comment]
> 

单体的。我看到文档那里“ IDEA快速创建module模块”没有更新，是不是创建module出了问题，如果是这个问题可否更新一下通过IDEA创建module模块的文档内容，谢谢。
