### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by Sallenkey** [jeecgboot/jeecg-boot#4997]
系统登录不上报错
![image](https://github.com/jeecgboot/jeecg-boot/assets/65650810/2184fe86-a234-4eec-bbe1-e2665d7cc0e3)

**Comment by zhangdaiscott** [comment]
你本地？

**Comment by Sallenkey** [comment]
对的

**Comment by Sallenkey** [comment]
> 你本地？

对的

**Comment by Sallenkey** [comment]
> > 你本地？
> 
> 对的

数据库脚本我也运行了数据库确实是id

**Comment by zhangdaiscott** [comment]
那就是你数据库有问题，自己排查把
