### ISSUE TITLE
JAR分离打包部署excel导出报错：NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

### ISSUE THREAD

**Issue by mbh1210554992** [jeecgboot/jeecg-boot#4999]
##### 版本号：
2.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

1. 开发环境：

     poi依赖冲突，在开发上解决冲突后，开发上导出excel功能正常

2. 使用JAR包部署方案（不分离lib）:

     使用不分离lib的方式部署，导出excel功能页正常

3. 使用JAR分离打包部署方式（分离出lib）：
     将lib文件夹单独分离出来部署时，导出Excel会报错：NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

4. 总结：
     解决poi依赖冲突后，**开发环境**和 **jar包部署方案(不分离lib)** 导出excel都正常，但 **jar分离打包部署方案(分离出lib)** 还是会存在poi依赖冲突

##### 截图&代码：
<img width="1012" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/49233247/c6d20b1c-fed5-4a9a-be09-195ad7118ff4">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
说明你还是存在冲突问题，分离方式下jar的lib有冲突
