### ISSUE TITLE
提供一个跨平台数据库的思路 数据读取存储到json 文件 初始化 查询数据库 如果为空则读取JSON 创建记录

### ISSUE THREAD

**Issue by TomYule** [jeecgboot/jeecg-boot#5000]
##### 版本号：
3.5.0

##### 问题描述：
提供一个跨平台数据库的思路 数据读取存储到json 文件 初始化 查询数据库 如果为空则读取JSON 创建记录
Java 框架只用更换jdbc 就可以适配不同数据 但是 要支持不同数据库 需要分别进行处理 避免麻烦
本人尝试过 跨平台dao 框架 如nutz 但数据库是个问题  最终就是把数据查询存到JSON文件 项目启动检查是否有数据 然后读取 插入数据库 实现支持各类数据库目的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by TomYule** [comment]
或者用  liquibase

**Comment by zhangdaiscott** [comment]
增删改查呢？关联查询呢

**Comment by TomYule** [comment]
mybatis 不太行  nutz dao 就可以
