### ISSUE TITLE
表单开发j-category-select placeholder不显示问题

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#5003]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用表单开发时，弹框组件里的下拉框使用了分类字典，设置placeholder不显示的问题

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/2ad162bc-b4dd-4d55-a129-00731104b976)
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/fd5b7c0c-96a7-4c79-84f8-79945f64889d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/97f0c257-d396-408d-a145-12c2d915e825)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
