### ISSUE TITLE
微服务 Redis 设置密码时启动JeecgSystemCloudApplication失败；不设置密码时：gateway项目启动失败

### ISSUE THREAD

**Issue by lixuzhen2019** [jeecgboot/jeecg-boot#5004]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用微服务方式调试程序，使用本机的Redis **有密码**，启动 nacos 服务正常； 启动gateway服务正常；
启动：JeecgSystemCloudApplication 时  报错：
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required.

停掉已启动的项目，关掉Idea ；重置Redis 为**无密码**；启动 nacos 服务正常；启动gateway服务报错：Caused by: io.lettuce.core.RedisCommandExecutionException: ERR Client sent AUTH, but no password is set

##### 截图&代码：
redis设置了密码，启动JeecgSystemCloudApplication 时  报错：
![image](https://github.com/jeecgboot/jeecg-boot/assets/51704248/e9bc707f-3ce7-4aa2-8a5f-961e6989b67a)

redis不设置密码时，启动 gateway报错截图：
![image](https://github.com/jeecgboot/jeecg-boot/assets/51704248/890dcb9a-16fa-4597-b573-95ad02060101)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
nacos中redis的配置改了吗

**Comment by lixuzhen2019** [comment]
我知道问题所在了，谢谢您的解答提醒
