### ISSUE TITLE
在maven依赖中引用积木报表是否需要支付费用？

### ISSUE THREAD

**Issue by namelessmyth** [jeecgboot/jeecg-boot#5006]
##### 版本号：
    <dependency>
        <groupId>org.jeecgframework.jimureport</groupId>
        <artifactId>jimureport-spring-boot-starter</artifactId>
        <version>1.5.8</version>
    </dependency>

##### 前端版本：vue3版？还是 vue2版？
无

##### 问题描述：
我在项目的maven依赖中引用了积木报表的依赖。不修改积木的源码，只是使用他开发业务报表。
我们的项目属于商用，功能上线之后，源代码会交付给客户。
请问像我们这种情况是否需要收费？或者是否需要把自己的项目开源？

##### 截图&代码：
相同问题链接：https://github.com/jeecgboot/JimuReport/issues/1784

**Comment by zhangdaiscott** [comment]
不需要
