### ISSUE TITLE
当规则字段是create_by的时候，数据权限不起作用

### ISSUE THREAD

**Issue by RelaxAndNotIndulge** [jeecgboot/jeecg-boot#5007]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
当规则字段是create_by的时候，数据权限不起作用，其他字段可以正常起作用

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/32625268/e0e1f66c-c9ac-4815-b88f-2e3212d3d3b6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by RelaxAndNotIndulge** [comment]
补充2个截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/32625268/d7e325d7-0f3c-4ac2-b12a-62416a64b871)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32625268/30ea480d-353c-4009-918a-1dc5ea10fed8)

**Comment by Contour-D** [comment]
如果使用createBy呢？
![image](https://github.com/jeecgboot/jeecg-boot/assets/40132326/ab3e516a-9e11-425d-bb6b-47ece70da645)
