### ISSUE TITLE
子表数据权限设置不生效

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecg-boot#5008]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
根据文档  http://doc.jeecg.com/2653462 操作，不生效
经排查 如图，第210行 数据为空导致211行没有加载出 数据的自定义sql的数据规则

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/15beb66f-ec2f-483c-bb3e-0a29511e2e3b)

![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/36fa7a1b-c7d5-404a-bf11-67bb203b2134)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
url路径的前斜杠去掉试试

**Comment by 506764932** [comment]
不行，我尝试了多种格式都不行，最近一次我甚至把url设置为了：queryDmpEamAssetProfilingByMainId 也不行。
其实 是 JeecgDataAutorUtils 类的55行 获取的数据为空
`SpringContextUtils.getHttpServletRequest().getAttribute(MENU_DATA_AUTHOR_RULES);`

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
