### ISSUE TITLE
组织机构变更带来的sysOrgCode大面积更新问题

### ISSUE THREAD

**Issue by huangguocai** [jeecgboot/jeecg-boot#5009]
##### 截图&代码：
如题，如果碰到集团层面的大范围的组织机构（部门）变更，整个部门从顶层到底层全部大范围调整，jeecg现有的业务数据都已经和sysOrgCode绑定，如果部门的sysOrgCode都变更了，业务数据如何跟随做变更，希望官方大佬给个思路或者建议，感谢！

**Comment by zhangdaiscott** [comment]
业务数据可搞不了，尽量项目刚开始的时候，修改编码，后期不要改，不然业务数据不好跟着调整
