### ISSUE TITLE
主表的popup弹窗修改后增强js无法获取弹窗的值完成填值规则赋值

### ISSUE THREAD

**Issue by zhenxunsong** [jeecgboot/jeecg-boot#5010]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
使用的是Online在线功能,
通过implements IFillRuleHandler实现了一个文本框的填值规则，这个填值规则会读取form表单的值；当表单字段badge，控件类型是popup弹窗，其修改后，填值规则类中获取不到该弹窗的值。即调用that.executeMainFillRule()获取到该弹窗的值是空字符串。【说明：popup弹窗选择后是回写父页面成功的】

##### 截图&代码：
填值规则：
<img width="768" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/18681436/a8d5f577-46ee-4af5-a577-04e57b206e31">

增强js：【表单字段名:badge】
onlChange(){
   return {
    badge() {
      that.executeMainFillRule()
    }
  }
 }
弹窗配置：【弹窗是正常的，正常回写父页面表单数据的】
<img width="1439" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/18681436/5256a52f-21d8-495a-bfc5-4dc5b1e334cc">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
popup控件没有触发change事件

**Comment by tb2888** [comment]
> popup控件没有触发change事件

怎么之前的老版本还触发change事件，现在为什么不行了？
