### ISSUE TITLE
JSelectDept原生组件，选择部门以后，输入框里面小叉叉点了没反应

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#5012]
##### 前端版本：vue3版 

   <JSelectDept class="jselectdept" v-model:value="formData.bumeng" :multiple="true" type="array"/>
JSelectDept原生组件，选择部门以后，输入框里面小叉叉点了没反应
##### 截图&代码：

![)(QD}@L7O`(EO4GJ%IW3~8J](https://github.com/jeecgboot/jeecg-boot/assets/57313995/8845e0dd-639e-4788-9d42-6882b5c1c9b4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 378680487** [comment]
<JSelectDept class="jselectdept" v-model:value="formData.bumeng" :multiple="true" type="array"/>通过这种方式调用的

**Comment by 378680487** [comment]
JSelectDept class="jselectdept" v-model:value="formData.bumeng" :multiple="true" type="array"

**Comment by zhangdaiscott** [comment]
sq

**Comment by 378680487** [comment]
> sq

不要骂人，我看得懂q

**Comment by 378680487** [comment]
到底怎么解决这个问题，，能不能解决

**Comment by lsqGitHub716** [comment]
请更新到最新版本
