### ISSUE TITLE
请问最新节点这个如何通过调用接口获取access token,我是想从外部用python程序自动给数据库传数据

### ISSUE THREAD

**Issue by 280185386** [jeecgboot/jeecg-boot#5013]
##### 版本号：
2023/3/15 11:34的版本
git hash:    d81fa1f908c589f731cabf0146cb41b98e372f24

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

请问这个节点这个如何通过调用接口获取access token,我是想从外部用python程序自动给数据库传数据，现在每次我是从chrome F12模式下手动copy access token，想改成自动的，麻烦指导一下，感谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
调用登录接口获取
