### ISSUE TITLE
JSelectMultiple 下拉多选页面无法渲染

### ISSUE THREAD

**Issue by chenglutao** [jeecgboot/jeecg-boot#5014]
##### 版本号：
v3.4.4last

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
JSelectMultiple 下拉多选页面无法渲染

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/51188496/9f9b3819-1672-46dc-8573-78b8f8429951)

![image](https://github.com/jeecgboot/jeecg-boot/assets/51188496/12ff45d6-fd46-46ca-9c4f-27fd9addad2a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by anime777** [comment]
一样的问题，online测试 列表页能正常渲染  ，编辑 新增    ，下拉搜索框就 空白    <version>3.5.1</version>

**Comment by anime777** [comment]
[已解决]   把字典配置 放在{校验字段} 栏目 而不是 {个性查询配置}
