### ISSUE TITLE
针对#4985提出的Popub控件分页显示数据问题已复现

### ISSUE THREAD

**Issue by a1643977841** [jeecgboot/jeecg-boot#5016]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
针对#4985提出的Popub控件分页显示数据问题，已复现（数据一共三条  必须选择每页展示20页才会全部展示完3条数据否则只有一条）

##### 截图&代码：
<img width="1499" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/cd2ae38a-9064-4e0a-8834-37ebc7b47740">

<img width="1240" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/28393dea-2f77-4ff3-af00-fb58ad9fb4ca">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by a1643977841** [comment]
> 如何？

**Comment by tygithub1** [comment]
配置截图

**Comment by a1643977841** [comment]
> 配置截图
第三图是online在线表单的配置，使用的代码生成之后的页面
<img width="608" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/751a4b50-82f6-4496-8d20-88714fc66efe">
<img width="1510" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/c064e60c-fdfb-454d-a820-49e9a1c4583b">
<img width="1508" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/10590f4a-f9e3-4a7b-b50f-45ee7aee19d4">

**Comment by ciahua** [comment]
> 配置截图

请问配置截图在哪里看？

**Comment by tygithub1** [comment]
测试没有问题，请开启sql日志，看一下这个popup弹窗查询数据的sql是什么样的

**Comment by a1643977841** [comment]
> 你加个排序试试

加一个默认排序就数据就正常了

**Comment by a1643977841** [comment]
> 测试没有问题，请开启sql日志，看一下这个popup弹窗查询数据的sql是什么样的

开启了之后 似乎并没有找到这个查询数据的sql，
<img width="507" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/9bebb11f-f189-43ef-81da-ac5ce84039ba">

**Comment by zhangdaiscott** [comment]
那就加排序解决吧
