### ISSUE TITLE
super-query高级查询配置自定义popup

### ISSUE THREAD

**Issue by yang-jh971** [jeecgboot/jeecg-boot#5018]
##### 截图&代码：
这样配置只能显示官方配置的统计用户总数的popup，请问有没有什么方法可以做到自定义的popup？？？？
![image](https://github.com/jeecgboot/jeecg-boot/assets/105487241/af0e4441-e268-4669-b24c-b3bcfe26525e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by yang-jh971** [comment]
还有超级查询完毕后  如何关闭高级查询的弹窗呀？

**Comment by zhangdaiscott** [comment]
不支持popup，没做这功能
