### ISSUE TITLE
jeecgboot登陆功能需要优化策略

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#5019]
##### 版本号：
3.3
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
登陆功能需要优化以下策略，不知道方不方便实现？
1、建议实现应用系统登录失败锁定机制，合理设置非法登录阈值与锁定时间，可针对账号和登录IP进行锁定。
2、提供密码有效期检查功能，要求用户定期比如3个月更改口令。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这块特意预留，不做改造，不同的项目要求不要，自己个性化订制就行了
