### ISSUE TITLE
前端日期组件月份和星期为英文

### ISSUE THREAD

**Issue by m2075498242** [jeecgboot/jeecg-boot#5021]
##### 版本号：
jeecgbootvue3版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
前端日期组件月份和星期为英文 我想要中文
我已经尝试了升级版本和antd官网的例子 都没效果 

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/d25541da-1c84-4ff9-8a36-0c3ca4c1c34d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本号

**Comment by m2075498242** [comment]
3.4.0

**Comment by zhangdaiscott** [comment]
升级到最新的看看，印象中改过

**Comment by m2075498242** [comment]
您是指升级什么版本  antd版本？

**Comment by zhangdaiscott** [comment]
更新jeecg-boot到最新版本
