### ISSUE TITLE
antd组件库中的datepicker组件在测试环境中无法选中时间

### ISSUE THREAD

**Issue by MetalSu** [jeecgboot/jeecg-boot#5022]
##### 问题描述：
antd组件库中的datepicker组件在测试环境中无法选中时间，如果将datpicker的日期面板改为受控模式，通过事件进行开启和关闭可以选中时间，但本地环境不需要进行这样处理也可以选中时间，只有在测试环境中会有这样的问题，且这种方式需要在组件上绑定很多事件，如果是通过uselistpage生成的表单筛选中的datepicker要怎么处理，现在没有头绪。项目中自带的组件在测试环境中也会有这样的问题。代码完全照抄组件&功能/jeecgboot组件示例/单表原生示例/新增功能中的年月日时分秒组件。

##### 截图&代码：
<a-date-picker show-time v-model:value="formState.nyrsfm" style="width: 100%" valueFormat="YYYY-MM-DD HH:mm:ss" />

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
test模式已经删掉

**Comment by MetalSu** [comment]
已经删掉是什么意思？上正式环境就不会出现这个无法选中的问题？造成这个无法选中情况的原因是什么

**Comment by zhangdaiscott** [comment]
test模式有问题，prod模式没问题
test模式已经去掉了

**Comment by MetalSu** [comment]
好的明白了
