### ISSUE TITLE
nacos启动报错

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#5023]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
重启项目后，发现nacos启动报错

##### 截图&代码：
nacos配置文件：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/6fae1120-8653-46dd-8327-d0e8e2d3f73b)
启动类：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/7caf90e4-ca21-46b1-9f5d-1c8f74bc4f6d)
报错：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/3479958d-6fc4-4683-9e5d-d776d064592d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/656d12b2-7163-4c11-9d7d-6a84f9768a37)
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/a4c6678b-fc0c-4fc2-8ae4-beabe73e1e3b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
错误信息太少，无法判断
