### ISSUE TITLE
JVueTable的事件 @valueChange重复触发问题

### ISSUE THREAD

**Issue by a1643977841** [jeecgboot/jeecg-boot#5025]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
JVueTable的事件 @valueChange使用过程中，发现会重复触发。
比如：原数据值为4567 首次修改成45678之后触发了红色框内的一次打印。如下图
当焦点移除时候，连续触发了三次值改变事件函数(打印了三次 如粉色框内数据。)
为何会如此呢？

##### 截图&代码：
<img width="444" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/c52f5517-3c03-4dc4-a90d-e7c75229493f">

<img width="894" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/75775858/731b68f6-59de-4bbb-a08f-df41855586f7">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
