### ISSUE TITLE
上传文件后保存出错

### ISSUE THREAD

**Issue by ZhuSunQAQ** [jeecgboot/jeecg-boot#5026]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用oline表单开发创建好表单后，使用功能测试发现上传文件后点击保存出错

##### 截图&代码：

![b5a1ad9fc71ec96fceae28df18c9ea9](https://github.com/jeecgboot/jeecg-boot/assets/57900374/1c81585e-d6e1-4a3e-9e59-16700293c67a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
长度不够

**Comment by ZhuSunQAQ** [comment]
> 长度不够

您好，请问要怎么解决这个问题呢
