### ISSUE TITLE
富文本编辑器菜单偏移

### ISSUE THREAD

**Issue by MetalSu** [jeecgboot/jeecg-boot#5029]
##### 问题描述：
使用j-editor组件，使用无问题，但当页面发生滚动，组件上面的菜单栏定位会发生偏移

##### 截图&代码：

![WX20230607-141155](https://github.com/jeecgboot/jeecg-boot/assets/62043893/bf971c86-18d2-4c2a-998b-e0c64786eb1b)

**Comment by liaozhiyang** [comment]
这是TinyMCE编辑器底层的问题，j-editor组件引用的时候已经简化把这个功能去掉了，这个问题需要可能需要你自己解决。
<img width="1337" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/1b2b6ecc-189d-4806-b54f-a60bdf407c49">
