### ISSUE TITLE
单体服务启动报错

### ISSUE THREAD

**Issue by baiqingxia888** [jeecgboot/jeecg-boot#5031]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
启动jeecg-system-start直接报以下错误

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/89574140/cf4e2c7a-6f99-4fe0-b11d-87b659f69794)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是更新的代码，没更新全吧
