### ISSUE TITLE
a-image无法显示

### ISSUE THREAD

**Issue by LvJianfeng** [jeecgboot/jeecg-boot#5032]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
```a-image```无法显示，顺便问下什么原因整个框架里都没有```a-image```的使用呢，目前使用的场景是在JVxeTable中展示

##### 截图&代码：
```
<a-image
     :width="200"
     src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
/>
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/component/JImageUpload.html

**Comment by LvJianfeng** [comment]
这个我试过，在JVxeTable使用不行，代码如下：
```
<template #tempImg="props">
    <JImageUpload v-model:value="props.row.tempImg" disabled></JImageUpload>
</template>
```
