### ISSUE TITLE
积木报表调用存储过程异常

### ISSUE THREAD

**Issue by chenyuan001** [jeecgboot/jeecg-boot#5033]
##### 截图&代码：
数据库查询结果：
<img width="564" alt="1686129723147" src="https://github.com/jeecgboot/jeecg-boot/assets/96572112/acd4fcae-54cf-42a9-b1e3-08a25c677e99">

数据集选择异常：
<img width="839" alt="1686129851026" src="https://github.com/jeecgboot/jeecg-boot/assets/96572112/d96bda31-f29d-4335-a170-e8dba15e69d1">

jeecg-boot异常截图：
<img width="887" alt="1686129652465" src="https://github.com/jeecgboot/jeecg-boot/assets/96572112/371c2b6f-2177-4f01-aed0-e2db1881598d">

**Comment by zhangdaiscott** [comment]
ws
