### ISSUE TITLE
/drag/page/list接口不存在

### ISSUE THREAD

**Issue by jcjw2019** [jeecgboot/jeecg-boot#5034]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
/drag/page/list接口不存在

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你依赖下载成功了都？

**Comment by jcjw2019** [comment]
> 你依赖下载成功了都？

我是基于3.5.1，进行git pull的

**Comment by zhangdaiscott** [comment]
maven刷新，新增的依赖没生效

**Comment by 412498569** [comment]
我也一样，看了引用，drag-free有引用
