### ISSUE TITLE
Unable to correctly extract the Initialization ,shiro cookie问题

### ISSUE THREAD

**Issue by anime777** [jeecgboot/jeecg-boot#5035]
##### 版本号：
  <version>3.5.1</version>

##### 前端版本：vue3版？还是 vue2版？
VUE 3

##### 问题描述：
重现步骤

1.  clone 项目  ，设置redis 和数据库地址
2. 新建     @GetMapping(value = "/ping")
    @ResponseBody
    public String ping() {
        return ("ping ok");
    }
3. 添加过滤    filterChainDefinitionMap.put("/ping", "anon");    在 // org.jeecg.config.shiro.ShiroConfig
4.  启动前后台。  登录管理后台后  访问该/ping地址 ，**界面正常显示，但是后台报错**         jeecg-boot/ping
5. 清除COOKIE 或 隐身模式  访问  该/ping地址   界面正常显示，后台也正常

http://www.manongjc.com/detail/21-isuuzsdftfxxoad.html

##### 截图&代码：
后台报错    偶尔会整个后台崩溃  访问任何网址都出现500
 Delegate RememberMeManager instance of type [org.apache.shiro.web.mgt.CookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.crypto.CryptoException: Unable to correctly extract the Initialization Vector or ciphertext.
	at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:378)
	at org.apache.shiro.mgt.AbstractRememberMeManager.decrypt(AbstractRememberMeManager.java:482)
	at org.apache.shiro.mgt.AbstractRememberMeManager.convertBytesToPrincipals(AbstractRememberMeManager.java:419)
	at org.apache.shiro.mgt.AbstractRememberMeManager.getRememberedPrincipals(AbstractRememberMeManager.java:386)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
清空所有的cookie

**Comment by zhangdaiscott** [comment]
具体原因不清楚
