### ISSUE TITLE
Online配置报表，为popup弹出框提供数据，在新增数据后无法显示，但是切换分页的条数之后又能显示了？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5038]
##### 问题描述：
发现一个问题，我试用Online报表配置功能，通过select从mysql数据库的数据表中选取数据，作为一个子表的popup弹出框中的可选数据，本来一切正常。后来我在select选取的数据表中增加了几条数据（原来是20条数据，后来加了3条数据，变成了23条），但是发现popup弹出框弹出的可选数据中还是20条数据，但是我把分页的数量从每页10条改成每页30条，结果那23条数据就出来了。很奇怪。这是怎么回事？
截图如下。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ciahua** [comment]
![主子表1](https://github.com/jeecgboot/jeecg-boot/assets/37827583/b6e80c0b-b5ba-4d92-ae3a-b484cf362d85)
![主子表2](https://github.com/jeecgboot/jeecg-boot/assets/37827583/88690b31-859e-4a29-acbf-76efd6f00bb8)

**Comment by zhangdaiscott** [comment]
加个排序
