### ISSUE TITLE
Online在线建表同步表结构的时候没有将表描述同步到数据库的注释上；外键没有生成到数据库

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#5039]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
Online在线建表同步表结构的时候没有将表描述同步到数据库的注释上

##### 截图&代码：
online在线建表中填写了表描述
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/9234a55a-83e4-4cea-a37d-fe9c5c22b6f1)
MySQL数据库中表注释没有
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/ce464455-cbfb-4b29-9d41-8be54f3393cb)

指定了外键
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/b1d1c07d-d62e-431c-8f72-7f88f3d474d3)
数据库中没有显示外键呢
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/c7be8ea7-3ce1-4247-99c6-5b760e4e2df1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没做这功能
