### ISSUE TITLE
首页加载缓慢，请问下是vue3的问题吗，vue2的版本首页还是很快的

### ISSUE THREAD

**Issue by yylstudy** [jeecgboot/jeecg-boot#5042]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
首页加载缓慢，请问下是vue3的问题吗，vue2的版本首页还是很快的，谢谢！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/26402953/bfa3365a-63f3-46c3-8bac-2f2ceccd2e04)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是指发布后还是开发环境？

**Comment by yylstudy** [comment]
官网的演示环境以及开发环境，特别是第一次加载，开发环境需要30s+，这个是什么原因呢，谢谢

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/qa.html
1
