### ISSUE TITLE
代码生成 - 没有自定义列功能

### ISSUE THREAD

**Issue by nodepade** [jeecgboot/jeecg-boot#5043]
##### 版本号：
3.0.0（发布日期：20220220）

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
online表单开发生成的列表代码，查询部分最右侧没有看到自定义列按钮，缺少自定义列功能，之前的版本是有的，请问怎么在代码生成的时候添加上自定义列功能

##### 截图&代码：
https://imgse.com/i/pCAEZI1
https://imgse.com/i/pCAEVaR

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by nodepade** [comment]
![has](https://github.com/jeecgboot/jeecg-boot/assets/67412567/c0bae129-1bd0-4ef6-a224-4907f14b15e4)
![no](https://github.com/jeecgboot/jeecg-boot/assets/67412567/8d6a91e6-62d9-48fe-9f0d-6d390a48e604)

**Comment by zhangdaiscott** [comment]
默认没这功能，可以自己扩展
