### ISSUE TITLE
系统权限有问题，给角色分配了菜单权限，然后给此角色关联用户，用户没有权限，急！！！

### ISSUE THREAD

**Issue by ssdai123** [jeecgboot/jeecg-boot#5044]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/31784020/277348dc-c8f6-4b02-bdb2-016cd2200e92)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
退出重新登录了吗
