### ISSUE TITLE
仪表盘分享链接404

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5046]
##### 版本号：

3.5.2
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
使用仪表盘的分享链接，其中包含null链接，再次复制到浏览器上无法访问404

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/38182329/18049a78-b93d-462b-9db7-ac062b71881c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
