### ISSUE TITLE
租户id为什么需要前端传递，不可以和登录的token进行绑定吗

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5050]
##### 版本号：

3.5.2
##### 问题描述：
租户id为什么需要前端传递，不可以和登录的token进行绑定吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前就是这样设计的，你说的也可以
