### ISSUE TITLE
开源项目vue2后端代码，启动报错

### ISSUE THREAD

**Issue by lwdhyt** [jeecgboot/jeecg-boot#5052]
##### 截图&代码：
我从github拉单体的后端代码，依赖拉取完成后，启动报错了。一个叫TenantContext类的找不到
![image](https://github.com/jeecgboot/jeecg-boot/assets/75429277/740a1e71-82d3-4faa-8f2f-ef06ef35f7ea)

**Comment by zhangdaiscott** [comment]
依赖没下载全？

**Comment by wgamand** [comment]
是登录的在线版，网址输入登录的，http://boot.jeecg.org/user/login，不需要下载依赖吧
