### ISSUE TITLE
[代码生成 BUG] 一对多代码生成的页面，外键关联字段错误   主表3个页面风格 不显示子表数据

### ISSUE THREAD

**Issue by anime777** [jeecgboot/jeecg-boot#5053]
##### 版本号：
**3.5.1 last**

##### 前端版本：vue3版？还是 vue2版？
**VUE3**

##### 截图&代码：

一对多代码生成，外键关联字段错误  queryDocExtDefByMainId 函数入参主表外键写死了ID，   不是自己  onl 配置的 xxx_id

### 影响范围：

1.  **主表=页面风格=》 第一个除外三个风格   列表页和编辑页  无法加载子表数据**  

2. **数据导出按钮** 没有导出子表数据
3.  点击列表页的排序字段 sort   直接报错 ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:36 - 请注意，将要排序的列字段不存在：sort

类似问题：好像只修复了风格一
#3528 

	if (!allColumnExist(column, allFields)) {
		throw new JeecgBootException("请注意，将要排序的列字段不存在：" + column);
	}

**Comment by zhangdaiscott** [comment]
配置截图

**Comment by zhangdaiscott** [comment]
无回复，暂关闭
