### ISSUE TITLE
自动生成的代码，用前端接口/xx/xx/add添加数据，提示无权限？shiroconfig已添加过滤

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5055]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
通过自动生成代码生成前后端，然后我用第三方软件调用前端接口，例如'/xxx/xxx/add'，来添加数据，并通过自动生成的sql脚本加了权限，在shiroconfig里也加了过滤，但还是添加不了数据。后来我尝试把controller里面的@RequiresPermissions("xxx:xxx:add") 注释掉了。就可以添加数据了。但这样操作应该不太正确。而且当我删除数据数据的时候，又提示没有权限。
请问，我应该怎么操作才能实现从第三方软件，调用前端的接口，给数据库添加、删除数据呢？

##### 截图&代码：
![微信截图_20230613102812](https://github.com/jeecgboot/jeecg-boot/assets/37827583/7ea2f067-d9e7-447f-b5f1-75c65c54c710)
![微信截图_20230613103236](https://github.com/jeecgboot/jeecg-boot/assets/37827583/7c827fe8-5402-419d-ad50-09af9b411a53)
![微信截图_20230613103237](https://github.com/jeecgboot/jeecg-boot/assets/37827583/c3e22b28-6452-4b3d-bba0-1cdc440bb08a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重启了吗
