### ISSUE TITLE
No versions available for vue-plugin-preset.

### ISSUE THREAD

**Issue by FengHuangDong** [jeecgboot/jeecg-boot#5059]
##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：
ERR_PNPM_NO_VERSIONS  No versions available for vue-plugin-preset. The package may be unpublished.

##### 截图&代码：
https://github.com/jeecgboot/jeecgboot-vue3/blob/master/pnpm-lock.yaml#L3479

https://registry.npmmirror.com/vue-plugin-preset/3.12.2
response: {"error":"[NOT_FOUND] vue-plugin-preset@3.12.2 not found"}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
忽略，没有用

**Comment by FengHuangDong** [comment]
> 忽略，没有用

这个是一个子依赖
    "@qiaoqiaoyun/drag-free": "^1.0.2", 
这个库里面用了，如果不需要，建议去掉或者升级它

**Comment by zhangdaiscott** [comment]
已经删了，更新最新代码
