### ISSUE TITLE
你好！请问开源版的Jeecg-Boot有3个问题咨询一下

### ISSUE THREAD

**Issue by linzym** [jeecgboot/jeecg-boot#5060]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
1. 登录页的图片文字怎样修改，附图？
2. 打开登录页的时间是否可以缩短？
3. 请问http改https是否方便？

##### 截图&代码：
![779FF2E1AA79A545C793B007D8873EBB](https://github.com/jeecgboot/jeecg-boot/assets/23232114/fc49b34e-0395-4f68-ac0f-dec8e469db52)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
登录页的图片文字怎样修改，附图？
F12定位，自己定位源码修改
打开登录页的时间是否可以缩短？
具体情况说明
请问http改https是否方便？
随便改

**Comment by linzym** [comment]
登录页的图片文字怎样修改，附图？

**Comment by linzym** [comment]
> 您好！
> 
> 请问http改https是否方便？ 随便改 好的，谢谢！
> 
> 登录页的图片文字怎样修改，附图？ 就是下面这幅图片的橙色箭头所指的图案和文字怎样修改（我改了src\locales\lang\zh-CN\sys.ts中相关的文字，但是没有起作用）？ ![image](https://user-images.githubusercontent.com/23232114/245955988-34e81e59-0b88-40a4-b7dd-0975faa0f04f.png) ![image](https://user-images.githubusercontent.com/23232114/245963759-4221ed39-c0d3-4489-aaef-c5d0124e3c9c.png)
> 
> 打开登录页的时间是否可以缩短？ 具体情况说明 参见下图，这是启动页（vue3版），这个页打开时需要等一些时间，请看是否可以说缩短？ ![image](https://user-images.githubusercontent.com/23232114/245970620-0288ee18-a9e1-48b3-80a3-11fdb11d797e.png)

您好！

请问http改https是否方便？
随便改
好的，谢谢！

登录页的图片文字怎样修改，附图？
就是下面这幅图片的橙色箭头所指的图案和文字怎样修改（我改了src\locales\lang\zh-CN\sys.ts中相关的文字，但是没有起作用）？
![image](https://github.com/jeecgboot/jeecg-boot/assets/23232114/5c0558ca-8d96-4489-8079-6d85f1573307)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23232114/74b987ee-5664-4028-b9c9-1586c8597617)



打开登录页的时间是否可以缩短？
具体情况说明
参见下图，这是启动页（vue3版），这个页打开时需要等一些时间，请看是否可以说缩短？
![image](https://github.com/jeecgboot/jeecg-boot/assets/23232114/a3357e26-b219-4401-8c4c-a1586c0782fe)
