### ISSUE TITLE
jeecg-boot-starter 和jeecg-cloud-server  之间的关系

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#5061]
##### 版本号：

3.5.2
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
jeecg-boot-starter项目和jeecg-cloud-server 项目之间的关系是什么？微服务模式开发的项目这两个都需要使用么？这部分文档里没有介绍。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/fc7e7dc6-b8bf-4014-8637-71318afe5401)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
都需要
