### ISSUE TITLE
Online 表单开发字段校验  设置Popup后 字典table无法使用参数 #2582

### ISSUE THREAD

**Issue by anime777** [jeecgboot/jeecg-boot#5062]
##### 版本号：

3.5.1
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
重现步骤
1.online 报表 录入  带参SQL  ,测试报表功能  参数可以正常查询  /online/cgreport/1668783531440099329?doc_id=500004
2.字典table设置参数   字典table?doc_id=${doc_id}
3.online表单 功能测试 发现 参数不生效

#2582
##### 截图&代码：
类似于
#2582
Online 表单开发字段校验  设置Popup后 字典table无法使用参数

**Comment by zhangdaiscott** [comment]
不支持这功能

**Comment by softboy99** [comment]
这个现在似乎还未支持
