### ISSUE TITLE
Mybatis-Plus动态全局变量不生效

### ISSUE THREAD

**Issue by LjPro** [jeecgboot/jeecg-boot#5064]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在application.yml中，按照mybatis-plus文档设置了全局变量，在mapper.xml中无法获取，一直是空

##### 截图&代码：
<img width="641" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19380370/e9e16e71-e19a-4d67-8b56-3d72e11a9245">
<img width="810" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19380370/8cea5743-9db2-4cde-962c-8ae6d2778271">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是mybatis-plus的机制，你应该仔细研究下相关文档
