### ISSUE TITLE
用户图标在远程访问的时候不显示，怎么办？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5065]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
当远程访问jeecgboot vue3页面的时候，右上角的用户图标不显示。本地访问是正常的，也就是localhost来访问是正常的。请问是什么问题？看了一下devtools，这个图标的路径好像有问题。没有变成远程的路径，仍然显示localhost路径。要怎么改？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/942012f6-76b4-4ac6-b04d-2f582be72bf9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/3603a930-b644-444e-9190-d85b5341c008)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不清楚，我们线上发布没这问题

**Comment by zhangdaiscott** [comment]
是不是数据库里，存的路径有问题

**Comment by ciahua** [comment]
> 

后来查了一下，好像是配置文件里的路径要改成服务器的ip地址的，就可以了。
谢谢！
