### ISSUE TITLE
用户列表-冻结用户，再解冻之后，用户还是无法登陆，有缓存问题

### ISSUE THREAD

**Issue by fhj857676433** [jeecgboot/jeecg-boot#5066]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

vue3版本，给用户冻结，再解冻后。
用户登录调用登陆接口成功，再后续调用了/sys/user/getUserInfo接口返回的还是冻结状态，用户无法登陆后报错了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
redis中未变过来吗

**Comment by zhangdaiscott** [comment]
你可以清下缓存看看

**Comment by fhj857676433** [comment]
> redis中未变过来吗

是的，缓存没更新。因为redis我本地连不了，我只能曲线救国 ,删除用户，再回收站弄回来，这样才把缓存更新掉

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
