### ISSUE TITLE
仪表盘编辑保存报错

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/jeecg-boot#5070]
##### 版本号：
jeecgboot 3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
仪表盘编辑保存，报空指针异常，异常问题DEBUG在org.jeecg.modules.drag.b类，140行 ，入参@RequestBody OnlDragPage var1 对象中updateCount为null,导致var1.setUpdateCount(var1.getUpdateCount() + 1); 抛异常。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/362930/4df1f90e-3396-4595-b231-454b1bf8c846)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by dfreng** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/362930/312d9fb5-0345-4054-a5f7-399b2c71ed11)

**Comment by zhangdaiscott** [comment]
你的前端仪表盘是那个版本

**Comment by dfreng** [comment]
view/super/drage/page ,formSchema中需添加updateCount，可解决该问题
{
    label: '',
    field: 'updateCount',
    component: 'InputNumber',
    show: false,
  },

**Comment by zhangdaiscott** [comment]
仪表盘的前端依赖升级下就好了，你的应该是老的
```
    "@qiaoqiaoyun/drag-free": "^1.0.52",
```
