### ISSUE TITLE
切换微服务架构以后出现404

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#5071]
##### 问题描述：

后端采用单体运行的时候都没问题 
但是切换微服务版本以后
请求追踪 404
性能监控中：服务器信息404  jvm信息404  tomcat信息404  磁盘监控正常  
仪表盘设计器404
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/73856d14-3462-4a5a-bcf3-580621023df6)

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/f19e70fe-812c-4fd0-84cd-ade9a6ef3be9)

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/6d00b130-e345-4ad3-89cc-074ffb2d7f88)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
缺少网关配置，加上仪表盘的请求前缀就好了

**Comment by hutianxi** [comment]
> 缺少网关配置，加上仪表盘的请求前缀就好了

仪表盘问题已解决 非常感谢  
服务器信息404 ， jvm信息404 ，tomcat信息404， 在线追踪 404 问题请教如何处理呢？
