### ISSUE TITLE
2.2.0 版本升级到支持微服务启动

### ISSUE THREAD

**Issue by zxthah** [jeecgboot/jeecg-boot#5073]
##### 问题描述：
要把之前基于2.2.0开发的单体项目，升级成微服务，请问
1，前端不升级，只升级后端是否可以？
2，升级到那个版本最合适？不要求新，要稳定，且升级成本低
3，如果把安全框架修改成Spring Security，方便么？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本太老了，你只能自己评估

**Comment by zxthah** [comment]
那第一个问题和第三个问题呢
