### ISSUE TITLE
设置了数据字典，进行添加时能正常显示，添加完后进行编辑或者查看时显示的是数据字典的数值，而不是名称。

### ISSUE THREAD

**Issue by doublez-ten** [jeecgboot/jeecg-boot#5074]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
设置了数据字典，进行添加时能正常显示，添加完后进行编辑或者查看详情时显示的是数据字典的数值，而不是名称。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/f42acf0b-de96-41db-af45-2b5fe31d6de9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/ef556441-c31d-4e83-8dfd-d25796e6d14e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/8cc0c506-ddd5-402b-8ee8-83f87544c35a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/77f356aa-648c-456b-a37b-10bbae65efc6)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/d19a9c5f-a80c-4154-811d-3042205325b7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
用的什么控件

**Comment by doublez-ten** [comment]
> 

下拉框控件，控件值使用的是数据字典里的字典code，编辑或查看表单时，表单的数据并没有被翻译为字典值所对应的名称，而是只显示字典数值。

**Comment by doublez-ten** [comment]
> 用的什么控件

下拉框控件，控件值使用的是数据字典里的字典code，编辑或查看表单时，表单的数据并没有被翻译为字典值所对应的名称，而是只显示字典数值。

**Comment by zhangdaiscott** [comment]
具体那个控件

**Comment by doublez-ten** [comment]
> 具体那个控件

![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/5fa201f1-f210-47a2-9199-276338455500)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/0d3cbcd4-31d2-4088-96eb-dff012cb6122)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/6a1f62d6-6a38-4e69-8344-ce7d3e1f8c44)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/d6a8824b-450e-4edd-8009-783eb97e7650)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/01ea4a75-fc53-445f-8a5d-2028328a0014)
type和status类型设置为Integer类型，字典的控件类型为下拉框，校验字典code码为test_type、test_status，数据值0和1分别对应的名称为测试类型0/测试状态0和测试类型1/测试状态1。
在新增完一条数据后，再进行编辑时，所显示的类型和状态并不是其对应的名称，而是其数值0或1。
![image](https://github.com/jeecgboot/jeecg-boot/assets/102229872/c158efda-3910-4a44-aaae-397dd3e2420b)

**Comment by zhangdaiscott** [comment]
类型改成一致，都改成字符串类型
