### ISSUE TITLE
新手启动jeecgboot项目后端

### ISSUE THREAD

**Issue by leellz** [jeecgboot/jeecg-boot#5079]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
后端代码JeecgSystemApplication.java无法正常运行

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/49784772/91649854-bcc5-4e1f-9a8a-5bfc5607c3d5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven 刷新

**Comment by leellz** [comment]
之后又出现了这种问题
![图片](https://github.com/jeecgboot/jeecg-boot/assets/49784772/b923a5b0-59c8-42a9-9e5d-0ccf2fdf87de)
