### ISSUE TITLE
后台管理员权限时不时丢失

### ISSUE THREAD

**Issue by net12580** [jeecgboot/jeecg-boot#5080]
##### 前端版本：vue3版？还是 vue2版？
v3

##### 截图&代码：

<img width="983" alt="0b4bd49f9cb62f30aaaa660d33c713d" src="https://github.com/jeecgboot/jeecg-boot/assets/57471542/cba28ebc-6452-489f-a796-0b8e842f4dd4">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个得你自己排查，我们帮不了你
