### ISSUE TITLE
nacos版本 能否升级2.2.3 腾讯云 漏洞扫描出现很多漏洞

### ISSUE THREAD

**Issue by afish177** [jeecgboot/jeecg-boot#5081]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
nacos版本 能否升级2.2.3 腾讯云 漏洞扫描出现很多漏洞(大部分都是nacos那边)

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/32056262/8a3a5e55-9ba5-4e6b-b02c-6d4403f0bb35)
几乎都是naocos得
麻烦大佬看看了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sc

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/10088557
