### ISSUE TITLE
生成代码 按照教程配置前端路由 页面不显示

### ISSUE THREAD

**Issue by Caoam** [jeecgboot/jeecg-boot#5082]
##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
生成代码 按照教程配置前端 页面不显示
具体控制台输出：Record with path "/eidoc/web/watch/watchSleep/watchSleepList" is either missing a "component(s)" or "children" property.

##### 截图&代码：
![A$XAUB}XZDSQVE2AGGM9DQ0](https://github.com/jeecgboot/jeecg-boot/assets/67316496/76196060-806f-4730-91fc-a1f3ca4ed493)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不清楚，你得自己阅读下生成的代码，看看是不是有什么特殊的

**Comment by huangwei2013** [comment]
同遇到。
没看到任何其他有效提示信息。
前端似乎完全没发出任何对后端的请求，应该是前端处理逻辑不严谨。

同一个表，第一次正常。后续对比尝试的3次都一样问题。
对比过其他3张表的操作，也都出问题。

**Comment by huangwei2013** [comment]
> 同遇到。 没看到任何其他有效提示信息。 前端似乎完全没发出任何对后端的请求，应该是前端处理逻辑不严谨。
> 
> 同一个表，第一次正常。后续对比尝试的3次都一样问题。 对比过其他3张表的操作，也都出问题。

并未生成代码，仅使用界面提供的   “online报表配置 + 菜单管理”， jeecg 版本 3.6.1

**Comment by huangwei2013** [comment]
设置 “是否路由菜单：否  “ 后正常可用。
