### ISSUE TITLE
列表页的table的标题行不能固定

### ISSUE THREAD

**Issue by liqingelio** [jeecgboot/jeecg-boot#5083]
##### 截图&代码：
![1687249266939](https://github.com/jeecgboot/jeecg-boot/assets/38447510/29894de8-960f-4d82-80bd-808df8d306b5)
![1687249364544](https://github.com/jeecgboot/jeecg-boot/assets/38447510/df897765-d6bf-4e2d-bed9-73ba67049b7f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
参考下菜单列表的实现
http://boot3.jeecg.com/system/menu
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/16e53da3-565c-48e1-b38b-01fa01ded737)
