### ISSUE TITLE
最新版本登录报错

### ISSUE THREAD

**Issue by liqingelio** [jeecgboot/jeecg-boot#5084]
##### 截图&代码：
![1687253599287](https://github.com/jeecgboot/jeecg-boot/assets/38447510/08876d64-2098-4f20-990d-a42756a48fc7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wlqwcs** [comment]
是不是报错
<img width="1281" alt="d555b7ff8b3338e6d86bdad9ab8a39c" src="https://github.com/jeecgboot/jeecg-boot/assets/128020569/944d96ac-f3e5-4930-99d7-4801a7301bb0">
给LoginUser实体类添加jiubu就不报错了 你看看是不是同样的错误，求解为啥
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/152b10b6-a4ce-4e08-9372-6dad09c4eb1c)

**Comment by zhangdaiscott** [comment]
清理浏览器和redis缓存，应该是不一致

**Comment by liqingelio** [comment]
是由于redis缓存不一致，导致了redis 反序列化deserialize异常问题解决，需要清理一下redis的缓存。就直接在redis-cli 执行了flushall（删除所有数据库中的所有key ） 命令
