### ISSUE TITLE
自己编写的vue页面，设置了路由缓存，切换tab的时候还是会刷新页面导致填写的数据被清空，怎么解决？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5086]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
自己编写了一个前端vue页面，填写表单，切换tab的时候之前填写的表单内容全部都丢失了。按照网上在菜单管理里面设置了路由缓存还是无效，又设置了一级菜单的缓存（本页面为二级菜单），也无效。请问是什么原因？要如何解决？

##### 截图&代码：
![缓存无效](https://github.com/jeecgboot/jeecg-boot/assets/37827583/119d69a5-c333-42f9-8007-ad196dcd332e)
![缓存无效1](https://github.com/jeecgboot/jeecg-boot/assets/37827583/d87f45c6-565b-4a45-86b8-8c39666cfd1f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/config/menu/cache.html

**Comment by ciahua** [comment]
> https://help.jeecg.com/config/menu/cache.html

谢谢！
