### ISSUE TITLE
online保存表单没有拿到当前登录的租户id

### ISSUE THREAD

**Issue by enfne** [jeecgboot/jeecg-boot#5089]
##### 问题描述：
hibernate-re 3.4.4-beta 版本里获取header里的tenantId没有使用X-Tenant-Id

##### 截图&代码：
SpringContextUtils.getHttpServletRequest().getHeader("tenant-id")

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
需要下个版本
