### ISSUE TITLE
使用autopoi导出excel时，实体类使用了“needMerge = true”但是存在一列数据没有合并！

### ISSUE THREAD

**Issue by hml110** [jeecgboot/jeecg-boot#5090]
##### 版本号：
jeecgBoot版本：3.4.4    autopoi版本：1.46

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在进行一对多导出数据生成excel时候，使用了needMerge = true的列没有预期进行合并。
![001](https://github.com/jeecgboot/jeecg-boot/assets/55190660/ed1c7cd2-1992-4e7e-a09c-76d056747d54)

![002](https://github.com/jeecgboot/jeecg-boot/assets/55190660/60ec1e37-21fb-43c4-878d-1f52296c73eb)

![image](https://github.com/jeecgboot/jeecg-boot/assets/55190660/25047474-b6fd-4eb3-964c-130dfee79e03)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by FuFengs** [comment]
这个怎么解决的
