### ISSUE TITLE
登录界面背景图打包部署过后图片模糊

### ISSUE THREAD

**Issue by wlqwcs** [jeecgboot/jeecg-boot#5091]
##### 版本号：
3.4.4
##### 前端版本：vue3版？还是 vue2版？
vue2
##### 问题描述：
登录界面背景图打包部署过后图片模糊，在本地图片不怎么模糊

##### 截图&代码：
本地运行的效果：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/c0d2384e-bfc5-4b31-a6a0-8396acc477f1)
打包部署后的效果：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/2d1569f1-9930-4a3f-a2f1-000e3cf4aac4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
压缩了吧

**Comment by wlqwcs** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/128020569/a88b551b-35b0-4d9b-970e-0fcbda5263f9)
是这里吗，不压缩的话会不会部署过后 加载会很慢
