### ISSUE TITLE
设置了拦截忽略还是显示token失效

### ISSUE THREAD

**Issue by SupYouM** [jeecgboot/jeecg-boot#5094]
##### 截图&代码：
我之前认为是我自己写的代码的问题，然后我就用你们提供的如下代码
filterChainDefinitionMap.put("/test/jeecgDemo/hello", "anon");

我在postman中设置为get，输入如下网址：
http://localhost:9002/jeecg-boot/test/jeecgDemo/hello
别的设置没有额外添加，都是默认，没有加入token

**Comment by Haowensheng** [comment]
其他的不知道 插图片直接cv就行
