### ISSUE TITLE
请问怎样动态设置form中某一个组件的属性？比如，动态设置某一个文本框disable？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5096]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
请问怎样动态设置form中某一个组件的属性？比如，动态设置某一个文本框disable？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/9eb89e08-a1d9-4f94-a462-ade0dcc81a6e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/ff788c00-051e-4d93-b98e-b9a46ee5dabb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/vue3/auth/form.html

**Comment by ciahua** [comment]
> https://help.jeecg.com/vue3/auth/form.html

谢谢！
