### ISSUE TITLE
在JPopup里打开窗口，希望在窗口的表格上实现搜索功能，按照BasicTable打开了搜索框，但是搜索没反应，怎么回事？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5098]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在JPopup里打开窗口，从报表配置中获取表格数据，希望在窗口的表格上实现搜索功能。按照BasicTable打开了搜索框，但是点击搜索没反应，怎么回事？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/1f6e2bd0-629f-4f66-8137-a7f3d2105280)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/dcfe0e5d-7214-405a-9c4b-4cedd639dd9a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/e301159b-a910-4b3c-b465-34bfbe711825)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ciahua** [comment]
另外，上面这个搜索框是我自己添加的。但我看到JPopupOnlReportModal这个组件似乎本身就是带了搜索框的，要如何打开？这样我就不需要自己写搜索框了，怕引起不必要的冲突。

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
在Online报表处找到你的表单配置查询。
![image](https://github.com/jeecgboot/jeecg-boot/assets/34293221/9a6304c8-ff79-4d85-9d64-c00d9c664e8c)

**Comment by ciahua** [comment]
> 在Online报表处找到你的表单配置查询。 ![image](https://user-images.githubusercontent.com/34293221/252843673-9a6304c8-ff79-4d85-9d64-c00d9c664e8c.png)

谢谢！
