### ISSUE TITLE
online报表本地测试没问题，发布后查不出数据

### ISSUE THREAD

**Issue by 378680487** [jeecgboot/jeecg-boot#5099]
##### 问题描述：
online报表本地测试没问题，发布后查不出数据，点功能测试，也没数据
数据库里面有数据，比如表abc里面有数据，用online报表添加了个sql，select * from abc  
本地能查得出，但是发布到服务器，查不出数据.
我的域名后面加了admin,,# 发布路径VITE_PUBLIC_PATH = /admin  我也配置。nginx里面也加了admin。不知道是哪里配置不对，还是bug？其他数据都没问题，就是这个online报表有问题。

##### 截图&代码：
![8 JOC_ NS}7}@(4JVZ~O~1C](https://github.com/jeecgboot/jeecg-boot/assets/57313995/a80618ba-ec37-4a96-8624-04ba19860695)

![NJZ_3N3SP6JO1%C{45CSQXJ](https://github.com/jeecgboot/jeecg-boot/assets/57313995/89681fa4-e5a1-4efe-9296-bb03f2e09149)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台地址不要通过nginx映射，直接配置死后台全路径

**Comment by 378680487** [comment]
在哪里配置死后台全路径。
#后台接口全路径地址(必填)，在这里吗？？填什么？写死8080端口？写死的话，怎么负载均衡
VITE_GLOB_DOMAIN_URL=http://xxx.com/jeecgboot

**Comment by 378680487** [comment]
{"success":false,"message":"SQL执行失败：Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 30000, active 0, maxActive 8, creating 0, createErrorCount 1","code":500,"result":null,"timestamp":1687707512486}

**Comment by 378680487** [comment]
我知道是什么原因了，报表编辑那里，只要选了动态数据源就不行，，不能选
