### ISSUE TITLE
Online报表配置,新增一个新的报表sql长度超过1000之后会报错

### ISSUE THREAD

**Issue by fengjidong** [jeecgboot/jeecg-boot#5100]
##### 版本号：
v3.4.3last

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
Online报表配置,新增一个新的报表sql长度超过1000之后会报错。

##### 截图&代码：
SQL: INSERT INTO onl_cgreport_head (id, code, name, cgr_sql, create_time, create_by) VALUES (?, ?, ?, ?, ?, ?)
Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'cgr_sql' at row 1

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
改数据库的字段长度
