### ISSUE TITLE
登录人有多个部门的上级看下级   右模糊sys_org_code就不好使了,有什么建议吗

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#5101]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
为什么不好使，按照issue发帖
