### ISSUE TITLE
3.5.2 版本仪表盘的数据源类型是不是 不支持 表单数据？

### ISSUE THREAD

**Issue by neo0820** [jeecgboot/jeecg-boot#5103]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
3.5.2 版本仪表盘的数据源类型是不是 不支持 表单数据？

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/39484553/1937fd4a-2503-452c-a735-719923e02efe)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
shi d
