### ISSUE TITLE
docker 部署后如何查看log.info("日志”)

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#5105]
##### 版本号：

3.5.1
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
请问 我用docker 部署后如何查看 log.info("日志”) 记录的日志
我用 docker logs -f 只看到mybatis的日志

**Comment by zhangdaiscott** [comment]
你可以进入docker看日志
