### ISSUE TITLE
Unable to scan documentation context default

### ISSUE THREAD

**Issue by lokells** [jeecgboot/jeecg-boot#5106]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
我整合flow able然后启动项目，swagger报了"Unable to scan documentation context default"
"Type org.jeecg.modules.online.cgform.model.OnlComplexModel not present"
swageer无法进入，其他接口正常
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/97097470/c022017b-df63-405e-b2ff-c5d158ef859b)
![image](https://github.com/jeecgboot/jeecg-boot/assets/97097470/26276234-cb6e-48f7-8374-4b32939b50f1)

**Comment by zhangdaiscott** [comment]
自己整合的，我们负责不了啊
