### ISSUE TITLE
部署后上传较大的文件无法上传

### ISSUE THREAD

**Issue by LiCain** [jeecgboot/jeecg-boot#5107]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/9c6e3b1b-dca7-4e39-80a8-68e83329fdac)
![image](https://github.com/jeecgboot/jeecg-boot/assets/19221237/6826c4a0-4714-4897-af1a-3acfaf99bf4d)

##### 截图&代码：

理论上是没有问题的，部署到服务器就上传不了超过10M的文件了
各种网上都查询都有没有，服务器各种资源开满都不行。请求帮帮忙，感谢大佬们！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
nginx？限制

**Comment by LiCain** [comment]
http {
    include       mime.types;
    default_type  application/octet-stream;
    client_max_body_size 1024m;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       3108;
        server_name  localhost;

        #后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问        
        location ^~ /jeecg-boot {
            proxy_pass              http://XXXX/jeecg-boot/;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 1024m;   #允许客户端请求的最大单文件字节数
            client_body_buffer_size 1024k; #缓冲区代理缓冲用户端请求的最大字节数
            proxy_connect_timeout 90;   #nginx跟后端服务器连接超时时间(代理连接超时)
            proxy_read_timeout 90;      #连接成功后，后端服务器响应时间(代理接收超时)
            proxy_buffer_size 1024k;       #设置代理服务器（nginx）保存用户头信息的缓冲区大小
            proxy_buffers 6 500k;        #proxy_buffers缓冲区，网页平均在32k以下的话>，这样设置
            proxy_busy_buffers_size 1024k; #高负荷下缓冲大小（proxy_buffers*2）
            proxy_temp_file_write_size 1024k; #设定缓存文件夹大小，大于这个值，将从upstream服务器传

        }
        #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
        location / {
            root   E:\jeecg\vue;
            index  index.html index.htm;
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.html?s=$1 last;
                break;
            }
        }
    }

**Comment by LiCain** [comment]
> nginx？限制

请看下我的nginx
http {
包括 mime.types;
default_type 应用程序/八位字节流；
client_max_body_size 1024m；
发送文件；
keepalive_timeout 65；
服务器{
听3108;
服务器名称本地主机；

    #后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问        
    location ^~ /jeecg-boot {
        proxy_pass              http://XXXX/jeecg-boot/;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 1024m;   #允许客户端请求的最大单文件字节数
        client_body_buffer_size 1024k; #缓冲区代理缓冲用户端请求的最大字节数
        proxy_connect_timeout 90;   #nginx跟后端服务器连接超时时间(代理连接超时)
        proxy_read_timeout 90;      #连接成功后，后端服务器响应时间(代理接收超时)
        proxy_buffer_size 1024k;       #设置代理服务器（nginx）保存用户头信息的缓冲区大小
        proxy_buffers 6 500k;        #proxy_buffers缓冲区，网页平均在32k以下的话>，这样设置
        proxy_busy_buffers_size 1024k; #高负荷下缓冲大小（proxy_buffers*2）
        proxy_temp_file_write_size 1024k; #设定缓存文件夹大小，大于这个值，将从upstream服务器传

    }
    #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
    location / {
        root   E:\jeecg\vue;
        index  index.html index.htm;
        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.html?s=$1 last;
            break;
        }
    }
}

**Comment by LiCain** [comment]
http {
    include       mime.types;
    default_type  application/octet-stream;
    client_max_body_size 1024m;
    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       3108;
        server_name  localhost;

        #后台服务配置，配置了这个location便可以通过http://域名/jeecg-boot/xxxx 访问        
        location ^~ /jeecg-boot {
            proxy_pass              http://192.168.11.27:3109/jeecg-boot/;
            proxy_set_header        Host $host;
            proxy_set_header        X-Real-IP $remote_addr;
            proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 1024m;   #允许客户端请求的最大单文件字节数
            client_body_buffer_size 1024k; #缓冲区代理缓冲用户端请求的最大字节数
            proxy_connect_timeout 90;   #nginx跟后端服务器连接超时时间(代理连接超时)
            proxy_read_timeout 90;      #连接成功后，后端服务器响应时间(代理接收超时)
            proxy_buffer_size 1024k;       #设置代理服务器（nginx）保存用户头信息的缓冲区大小
            proxy_buffers 6 500k;        #proxy_buffers缓冲区，网页平均在32k以下的话>，这样设置
            proxy_busy_buffers_size 1024k; #高负荷下缓冲大小（proxy_buffers*2）
            proxy_temp_file_write_size 1024k; #设定缓存文件夹大小，大于这个值，将从upstream服务器传

        }
        #解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
        location / {
            root   E:\jeecg\vue;
            index  index.html index.htm;
            if (!-e $request_filename) {
                rewrite ^(.*)$ /index.html?s=$1 last;
                break;
            }
        }
    }

**Comment by zhangdaiscott** [comment]
这种问题得你自己排查，如果本地没问题，那就是部署的问题
