### ISSUE TITLE
nacos2.0.4出现安全漏洞

### ISSUE THREAD

**Issue by turui0223** [jeecgboot/jeecg-boot#5108]
##### 问题描述：
nacos2.0.4出现安全漏洞

##### 截图&代码
移动那边测试提出的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/10088557
