### ISSUE TITLE
单点登录密码问题

### ISSUE THREAD

**Issue by whongli** [jeecgboot/jeecg-boot#5110]
##### 版本号：

3.0
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：

集成cas后 登录页面输入明文密码不行，要输入数据库中加密后的密码才能登录 什么原因
##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecg-boot/assets/38310548/0446f42a-8992-4cab-9c55-2b99c516537d)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/38310548/981687b2-34cc-4396-a1bf-326431a9843c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是你集成的问题，cas服务端得跟我们一样的登录加密后验证规则
