### ISSUE TITLE
每次刷新加载过慢

### ISSUE THREAD

**Issue by he-jt** [jeecgboot/jeecg-boot#5111]
版本号：3.5.1

前端版本：vue3版

问题描述：jeccgBoot首次加载过慢

截图&代码：
![Uploading 微信图片_20230629192241.png…]()

**Comment by zhangdaiscott** [comment]
图片裂了

**Comment by he-jt** [comment]
版本号：3.5.1

前端版本：vue3版

问题描述：jeccgBoot首次加载过慢

截图&代码：
![1688357006335](https://github.com/jeecgboot/jeecg-boot/assets/54670053/a67d6a6e-531b-4800-adbf-a47777005649)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/qa.html

如果是发布后，可以开启nginx压缩
https://help.jeecg.com/publish/nginx.html

**Comment by he-jt** [comment]
不是发布，是本地开发目前还未发布只是本地调试，是不是有什么不需要的可以清除掉的
