### ISSUE TITLE
用户密码解密无效

### ISSUE THREAD

**Issue by zhengxh247** [jeecgboot/jeecg-boot#5112]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/51809301/4930cd75-e394-4110-ab98-49027ab5d147)
![image](https://github.com/jeecgboot/jeecg-boot/assets/51809301/2af73c3b-b902-4767-8f1f-561b762304c5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持解密
