### ISSUE TITLE
集成CAS换浏览器单点登录无效

### ISSUE THREAD

**Issue by whongli** [jeecgboot/jeecg-boot#5114]
##### 版本号：

3.0
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
系统集成了单点登录，拿着url到另一个浏览器访问，还要在登录下，不符合预期

##### 截图&代码：

![MC9M3`NCTRL(76KP@9@@}K0](https://github.com/jeecgboot/jeecg-boot/assets/38310548/9275c91e-2c57-4d10-a71e-6dd940209f2f)

![8ZKV A2BN8JDXGTUI5C{`D4](https://github.com/jeecgboot/jeecg-boot/assets/38310548/174cabcb-df8a-4bd0-94fa-0054bf96b40c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
服务端是你自己实现的吧，这个我们不清楚你的实现方式
