### ISSUE TITLE
因swagger文档导致gateway内存溢出

### ISSUE THREAD

**Issue by wang-linbo** [jeecgboot/jeecg-boot#5115]
##### 版本号：
  v3.5.2及以前

##### 前端版本：vue3版？还是 vue2版？
无

##### 问题描述：

每次请求swagger文档时会创建NamingService，
会导致线程增多并不会释放,最终导致内存溢出

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/30817788/bd2e17c7-bbf0-4556-a469-881712ad49a7)
![image](https://github.com/jeecgboot/jeecg-boot/assets/30817788/61e12a43-7737-42ba-99b6-29f2194e6654)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
修复已提交
