### ISSUE TITLE
上传文件时报错：Cross-Origin Request Blocked 

### ISSUE THREAD

**Issue by jianchunzhu** [jeecgboot/jeecg-boot#5116]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用docker 启动jeecg-boot-system, jeecgboot-vue3-nginx.

在vue3的Dockerfile 里配置了proxy.
proxy_pass              http://jeecg-boot-system:8080/jeecg-boot/; 

.env.production：
#后台接口父地址(必填)
VITE_GLOB_API_URL=/jeecgboot

#后台接口全路径地址(必填)
VITE_GLOB_DOMAIN_URL=http://jeecg-boot-system/jeecg-boot

系统上传文件的时候总是提示上传失败，原因见下面。

##### 截图&代码：

http://jeecg-boot-system/jeecg-boot/sys/common/upload
CORS Missing Allow Origin

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://jeecg-boot-system/jeecg-boot/sys/common/upload. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 405.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://jeecg-boot-system/jeecg-boot/sys/common/upload. (Reason: CORS request did not succeed). Status code: (null).

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
阿里云存储是如何配置的？

**Comment by jianchunzhu** [comment]
我检查了一下，我本以为是 local， 原来application-prod.yml里默认是alis.

我现在改成local了，但是还是有这个错误，只是错误类型有点变化。
  uploadType: local
  # 前端访问地址
  domainUrl:
    pc: http://localhost:3100
    app: http://localhost:8051
  path:
    #文件上传根目录 设置
    upload: /opt/jeecg-boot/upload

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://jeecg-boot-system/jeecg-boot/sys/common/upload. (Reason: CORS request did not succeed). Status code: (null).

**Comment by jianchunzhu** [comment]
经过反复测试，应该是前端访问域名和[jeecg-boot-system不一致导致的。不好意思，打扰了。
