### ISSUE TITLE
新增微服务模块，使用webflux模式开发，请求接口报错UnavailableSecurityManagerException

### ISSUE THREAD

**Issue by wangxueping520** [jeecgboot/jeecg-boot#5117]
##### 截图&代码：
@Slf4j
@Api(value = "用户信息、基础学习DEMO", tags = {"用户信息DEMO"})
@RestController
@RequestMapping("/iot")
public class UserReactiveController
{

    @ApiOperation(value = "回显测试", notes = "提示接口使用者注意事项", httpMethod = "GET")
    @GetMapping(value = "/hello2")
    public Mono<String> hello(@RequestParam(name = "name") String name)
    {
        log.info("方法 hello 被调用了");
        return  Mono.just("hello " + name);
    }
    
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wangxueping520** [comment]
无效的应用配置？是指哪儿的配置无效呢

**Comment by wangxueping520** [comment]
> This is an invalid application configuration.

无效的应用配置？是指哪儿的配置无效呢

**Comment by wangxueping520** [comment]
> This is an invalid application configuration.

目前整个项目其他配置没变，整个流程就是新建一个微服务，在core包添加了webflux的依赖，然后在controller层加了一个demo接口，返回mono，接口能正常返回，但是控制台日志就会报错org.apache.shiro.UnavailableSecurityManagerException: No SecurityManager accessible to the calling code, either bound to the org.apache.shiro.util.ThreadContext or as a vm static singleton.  This is an invalid application configuration.

**Comment by zhangdaiscott** [comment]
gateway加上这个新服务了吗

**Comment by wangxueping520** [comment]
> gateway加上这个新服务了吗

gateway上加了  用的swagger调试,用shrio把这个接口排除不校验，把这个接口放在jeecg-system服务里面，都试过，接口可以正常访问返回，但是控制台会报错上述日志

**Comment by zhangdaiscott** [comment]
截图看配置

**Comment by wangxueping520** [comment]
> 截图看配置
路由配置：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/88adc758-cf14-44cb-a2e8-0174b2072430)

原接口代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/ed3f37fb-2c87-4c15-a54a-58d7c3b6928e)


swagger请求成功：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/a2ec74ab-e2fa-4531-96e0-29ce416fe776)

服务控制台报错：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/ac350dd4-91ed-4aee-a8f7-6e769d9d1ccf)

**Comment by wangxueping520** [comment]
> 截图看配置

普通返回不会有任何异常，返回Mono也就是webflux的标准，接口能成功返回，但是控制台感觉是shrio抛异常了

**Comment by wangxueping520** [comment]
发布了一个详细的issues,关闭这个
