### ISSUE TITLE
online表单使用关联记录组件提示无权限访问(操作)

### ISSUE THREAD

**Issue by Yunfly** [jeecgboot/jeecg-boot#5119]
##### 问题描述：

使用Online在线功能， 主体模版是默认，online 表单开发后，A表页面属性中， 字段ref使用关联记录B表，  给测试角色【人力资源】的授权了两张表单的路由
人力资源角色下的人员创建表A数据时提示 无权限访问(操作) ，
涉及 接口/jeecgboot/online/cgform/api/getData/ceshi_note
jeecgboot/online/cgform/api/getQueryInfoVue3/:id

给人力资源分配授权online表单开发权限后，问题解决， 但是这样，普通用户也会有online表单开发路由，有没有其他解决方法
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
关联记录 这个表也配置成菜单，授权给对应的人员即可

**Comment by Yunfly** [comment]
> 关联记录 这个表也配置成菜单，授权给对应的人员即可

我在问题中补充了图片，两张表都配置了路由，对应人员也能看到菜单可编写，但是关联项提示无访问权限

**Comment by Yunfly** [comment]
我看了查询sql 是		  select *
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			and b.url =  '/online/cgform'
			
查询权限是查这个路由地址的，正好跟授权online表单开发的path一致， 所以才会表现为开了授权online表单开发之后可以关联页面？

**Comment by zhangdaiscott** [comment]
> 我看了查询sql 是 select * from sys_role_permission a join sys_permission b on a.permission_id = b.id join sys_role c on a.role_id = c.id join sys_user_role d on d.role_id = c.id join sys_user e on d.user_id = e.id where e.username = ? and b.url = '/online/cgform'
> 
> 查询权限是查这个路由地址的，正好跟授权online表单开发的path一致， 所以才会表现为开了授权online表单开发之后可以关联页面？

特意这么做的，有配置菜单就不限制online的具体菜单

**Comment by Yunfly** [comment]
> > 我看了查询sql 是 select * from sys_role_permission a join sys_permission b on a.permission_id = b.id join sys_role c on a.role_id = c.id join sys_user_role d on d.role_id = c.id join sys_user e on d.user_id = e.id where e.username = ? and b.url = '/online/cgform'
> > 查询权限是查这个路由地址的，正好跟授权online表单开发的path一致， 所以才会表现为开了授权online表单开发之后可以关联页面？
> 
> 特意这么做的，有配置菜单就不限制online的具体菜单

hello,  那你看我发的两张图中，图1我用出库记录中的字段关联测试请假表，然后在人力资源角色下分配了这两张表的菜单如图2，他们也都能打开显示并各自创建数据， 但是出库记录这张表的关联字段点+号查询测试请假就会提示无访问权限， 是我哪个的配置有问题吗
