### ISSUE TITLE
表单上传文件失败后，依旧会记录失败的结果，将上传失败文本记录到数据库中了。

### ISSUE THREAD

**Issue by henryhe-cn** [jeecgboot/jeecg-boot#5120]
##### 版本号：
3.5.1last

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
表单上传文件失败后，依旧会记录失败的结果，将上传失败文本记录到数据库中了。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/23736507/7957bb57-70f8-4006-b053-3bb4fa7d641d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23736507/422e8c0a-c88e-4091-92c5-b70347381c89)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ty

**Comment by tygithub1** [comment]
已修改
