### ISSUE TITLE
关于Online表单的视图功能的使用场景

### ISSUE THREAD

**Issue by Strayfash** [jeecgboot/jeecg-boot#5121]
##### 版本号：
jeecgboot-3.5.2 antd-design-jeecg-boot-3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
关于Online在线的视图功能，文档上的说明是：
[1. 针对一对多表，需要单独修改时，可单独生成子表视图进行配置子表视图内容]
[2. 针对流程中各个节点需要显示不同页面时，比如节点1显示前两个字段，节点2显示后两个字段；可根据节点来配置不同视图]
我个人没有理解，可以举个例子讲一下吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
就是子表需要单独的数据增删改查，可以通过视图来实现
