### ISSUE TITLE
发现所有接口控制层，只要返回Mono类型，接口能正常返回数据，控制台就会报错org.apache.shiro.UnavailableSecurityManagerException

### ISSUE THREAD

**Issue by wangxueping520** [jeecgboot/jeecg-boot#5122]
##### 截图&代码：
场景模拟：在jeecg-system服务里新建一个接口，测试返回Mono.just(),在swagger上面进行调用，接口正常返回控制台报错，说是配置问题，但是这样在jeecg-system服务新建的接口应该不需要多余的其他配置。

代码示例：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/c5464f38-91b3-4e10-bc8f-bffaff51ac4c)

调用示例：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/0c66834f-35e2-4e0b-b198-0a77e15e428d)

控制台报错示例：
![image](https://github.com/jeecgboot/jeecg-boot/assets/41947857/72d35b4d-b07a-46a8-bf4c-9e5d03048417)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
xp

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/Japhet_jiu/article/details/131177210

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/c232dbed-dfad-4992-aa98-b5f972ee8fc6)

这么写没有报错

**Comment by wangxueping520** [comment]
谢谢大哥
