### ISSUE TITLE
运行容器 替换tomcat为Undertow容器 websocket失效 网关报错

### ISSUE THREAD

**Issue by afish177** [jeecgboot/jeecg-boot#5125]
##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
替换tomcat为Undertow容器  websocket失效 网关报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/32056262/198275e9-9bce-4f99-9b9b-b0caf726b5a5)
相关包 排除tomcat组件 引入Undertow
运行微服务
websocket 网关后台会报错
错误如下
![image](https://github.com/jeecgboot/jeecg-boot/assets/32056262/715efcd1-bd33-4c0d-8b6a-ecf1cf1533a8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己改造的无法处理
