### ISSUE TITLE
在线生成 大屏 积木报表 能否适配jdk17吗？ 能否发适配版本呢(目前在升级jdk17)

### ISSUE THREAD

**Issue by afish177** [jeecgboot/jeecg-boot#5126]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线生成 大屏 积木报表 能否适配jdk17吗？ 能否发适配版本呢(目前在升级jdk17 目前就差这些了)
感激 感激 
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有什么兼容问题？

**Comment by afish177** [comment]
> 有什么兼容问题？

有包名 没改过来 javax 像 request response这些

**Comment by zhangdaiscott** [comment]
非bug 暂时归集到  https://github.com/jeecgboot/jeecg-boot/issues/1312 ，待后期规划
