### ISSUE TITLE
在docker中配置nginx自定义请求头无效。

### ISSUE THREAD

**Issue by Lemnaminor** [jeecgboot/jeecg-boot#5129]
##### 问题描述：在docker中配置nginx自定义请求头无效。
大佬你好，请教一个问题。我想在nginx配置中设置proxy_set_header X-Test "1002";自定义请求头，前端页面请求接口请求头中并没有显示X-Test。网上搜索方案添加underscores_in_headers on;允许请求头带下划线也无效。请求头配置在location  /jeecgboot/，location  / 块中都不行。望大佬解惑，不甚感激。

##### 截图&代码：
![82472f3e6b72d4a325299d77ee62e6d](https://github.com/jeecgboot/jeecg-boot/assets/17738001/afdbaf86-c213-4372-a883-79a4794fd524)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个问题得你自己排查
