### ISSUE TITLE
切换postgresql数据库，nacos配置不生效，无法读取pgsql数据库的nacos配置

### ISSUE THREAD

**Issue by mili-li** [jeecgboot/jeecg-boot#5130]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
从mysql切换为postgresql，在配置nacos的postgresql数据库时，不生效，无法读取配置，没有任何报错

##### 截图&代码：
![1688716095998](https://github.com/jeecgboot/jeecg-boot/assets/66288141/95676a67-e4ce-4a02-b750-a9d67669b4d6)
![1688716175187](https://github.com/jeecgboot/jeecg-boot/assets/66288141/13cf82a8-c066-4653-a681-fa4c7eb9f2d9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
说明nacos项目数据库配置有问题，具体问题请自己排查
