### ISSUE TITLE
数据库字段设置了不允许为空，生成的实体类没有非空的注解，生成的swagger文档也没有显示非空

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#5131]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
数据库字段设置了不允许为空，生成的实体类没有非空的注解

##### 截图&代码：
数据库字段设置了不允许为空
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/2118a291-1799-4c04-b068-91fe9f63a199)

生成的实体类并没有非空的注解
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/116631ca-412c-473f-82ba-c9be59d283cf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
生成没加这逻辑，非空只online模式有效
