### ISSUE TITLE
批量删除部门时未正确置为叶子节点

### ISSUE THREAD

**Issue by DomXin** [jeecgboot/jeecg-boot#5132]
##### 版本号：
3.5.1、master

##### 问题描述：

批量删除部门时，一个部门下的所有子部门被删除，但并未正确把这个部门设置为叶子节点

##### 截图&代码：

数据库中是否为叶子节点和界面相对应，iz_leaf，是否是叶子节点，1是0不是

![+新罐+添加下级 C号入口号出◎同沙企國？ ◎阿沙打舒？](https://github.com/jeecgboot/jeecg-boot/assets/59043303/a0c6d86d-b54a-4ea6-a5fc-547529f0f542)

![Pasted Graphic 3](https://github.com/jeecgboot/jeecg-boot/assets/59043303/d6cc1435-c4c5-4081-b17f-b9bbd928913c)

批量删除a1、a2、a3、b，
期待结果：a是叶子节点，数据库中iz_leaf被置为1
结果：数据库中a的iz_leaf仍为0
![Pasted Graphic 5](https://github.com/jeecgboot/jeecg-boot/assets/59043303/02269118-3a74-41f1-9e19-21092805bc6a)
![Pasted Graphic 6](https://github.com/jeecgboot/jeecg-boot/assets/59043303/5b73ced5-5a39-47be-abb3-80e3973dc725)

修改代码后，测试
￼
![y M](https://github.com/jeecgboot/jeecg-boot/assets/59043303/89701e92-5c28-41f3-a95f-d96bf8215f71)

￼
![Pasted Graphic 8](https://github.com/jeecgboot/jeecg-boot/assets/59043303/907c52e2-8dda-42f9-9577-687cba81fe06)

删除a4、a5、a6、b2后，数据库中a的iz_leaf正确的置为1
![新增](https://github.com/jeecgboot/jeecg-boot/assets/59043303/28f65ec2-690f-478c-bd4c-3105b3407c09)
![Pasted Graphic 10](https://github.com/jeecgboot/jeecg-boot/assets/59043303/7a375603-1800-4652-bf99-873e71ee0d6d)

另：部门的批量删除是否有意义，只有大规模裁员时才有这个需求，让操作员费点事没事。部门的拆分、合并更常见

**Comment by zhangdaiscott** [comment]
ws

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/pull/5133/commits/1113739af97cef12c9881f3a9a12b8cf63b6efeb

**Comment by 1298191366** [comment]
已修复，待新版本发布
