### ISSUE TITLE
online表单的字段href设置，建议增加表单详情、编辑的popup配置，操作列按钮望增加全部展开或者折叠配置

### ISSUE THREAD

**Issue by jy05568536** [jeecgboot/jeecg-boot#5136]
##### 版本号：
master

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1、online表单的字段href设置，建议增加表单详情、编辑的popup配置
2、操作列希望增加全部展开或者折叠选项

**Comment by zhangdaiscott** [comment]
新需求归集到 https://github.com/jeecgboot/jeecg-boot/issues/1312  待后期考虑
