### ISSUE TITLE
部门组件 传的是部门id不能用于sys_org_code范围筛选

### ISSUE THREAD

**Issue by Feng-Xg** [jeecgboot/jeecg-boot#5139]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
表单开发，控件选择‘部门选择’，查询选中部门，送到后端的值是部门id，而非org_code。数据表中sys_org_code字段存储的是org_code。无法进行匹配得到有效数据。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/19472852/f126fb78-13ad-4882-b359-2f868dfc963f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/19472852/baef3b96-b09b-4a7f-936b-ad0f5bb011d2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/4447eee2-39e0-4a2a-a5a0-19fe1ac3366c)
允许自定义
https://help.jeecg.com/online/form/component1.html#4-%E7%94%A8%E6%88%B7%E9%80%89%E6%8B%A9--%E9%83%A8%E9%97%A8%E9%80%89%E6%8B%A9

**Comment by Feng-Xg** [comment]
> ![image](https://user-images.githubusercontent.com/3162115/252636718-4447eee2-39e0-4a2a-a5a0-19fe1ac3366c.png) 允许自定义 https://help.jeecg.com/online/form/component1.html#4-%E7%94%A8%E6%88%B7%E9%80%89%E6%8B%A9--%E9%83%A8%E9%97%A8%E9%80%89%E6%8B%A9

这儿只是配置的数据字典参数，问题是在查询的部门选择组件那儿，表单定义不能更改传给后端org_code。看后端代码，给组件value传的也是id，这儿需要调整。
![image](https://github.com/jeecgboot/jeecg-boot/assets/19472852/b792bc89-1d8f-4e8e-bd4f-c03244adba4a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/19472852/6f99f4dc-2a5d-4cfa-8d8c-cfa96ff3cfd0)

**Comment by zhangdaiscott** [comment]
自定义配置code了，但是查询的控件传递的是ID，是这个意思吗？

**Comment by Feng-Xg** [comment]
> 自定义配置code了，但是查询的控件传递的是ID，是这个意思吗？

是的，需要更改给前端传的key值为orgCode就可以了。页面属性扩展的只针对查询列表字典值生效

**Comment by tygithub1** [comment]
已修改
