### ISSUE TITLE
jeecgbootVue3 使用JtreeSelect 组件 控制台报错

### ISSUE THREAD

**Issue by yepbader** [jeecgboot/jeecg-boot#5141]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
jeecgbootVue3 使用JtreeSelect 组件 控制台报错

##### 截图&代码：
 <a-form-item label="树形下拉测试" style="width: 300px">
      <j-tree-select
        v-model="departId"
        placeholder="请选择部门"
        dict="sys_depart,depart_name,id"
        pidField="parent_id">
      </j-tree-select>
      {{ departId }}
    </a-form-item>

报错
在组件&功能菜单 自定义组件  下拉树选择 那 选择数据后控制台报错 功能可以正常运行
 Invalid prop `value` supplied to `TreeSelect`. You should use { label: string, value: string | number } or [{ label: string, value: string | number }] instead.
 `value` should not be array when `TreeSelect` is single mode.
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by gbblyx** [comment]
![Snipaste_2023-07-12_15-48-30](https://github.com/jeecgboot/jeecg-boot/assets/139325466/38f61086-07be-4c31-a859-914c4a11eb7f)
