### ISSUE TITLE
数据权限的配置是否可以支持spel表达式

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#5143]
##### 问题描述：
有些值或者集合,希望能用java的方法的返回结果集来表示,sql可能写出来比较复杂
等于或者in的东西,来自于一个和登录人扯上关系java方法,比如getLoginAreaCode()
希望QueryGenerator这个类加入对于spel表达式的解析
##### 截图&代码：
后来发现这个字符串才能被解析  "@permitionBiz.getLoginAreas()",下方截图只是尝试一下
![image](https://github.com/jeecgboot/jeecg-boot/assets/67467679/b6da6813-c4a3-48e5-bef7-62515b9d6bde)
permitionBiz是个bean
<img width="424" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/67467679/bb8f3baa-7e29-4aa1-8015-4a3c853421c3">
<img width="490" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/67467679/0b4d8b7e-e1cc-4a0a-bbef-5df152608bb9">

<img width="1082" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/67467679/caff07ee-fe2d-4c84-a7c4-8fd663fd0d8c">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by zhangdaiscott** [comment]
非bug 暂时归集到  https://github.com/jeecgboot/jeecg-boot/issues/1312 ，待后期规划
