### ISSUE TITLE
【重要】现在系统都有切换角色功能，为啥jeecg没有呀

### ISSUE THREAD

**Issue by luotang123456** [jeecgboot/jeecg-boot#5145]
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
现在主流系统都有切换部门切换角色（有的叫切换岗位）功能，为啥jeecg不支持呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
右上角有切换部门和租户功能

**Comment by luotang123456** [comment]
> 右上角有切换部门和租户功能

这个和切换角色（切换岗位）是两个概念
