### ISSUE TITLE
为什么开了ShiroConfig之后，在前端里增删改查，都会提示没有权限？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5147]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
为了能从外部添加数据到mysql数据库，我需要使用后端controller里的接口url，刚开始提示没有token，于是我就去ShiroConfig.java文件里添加了类似下面的语句
filterChainDefinitionMap.put("/matdeliverrecords/matdeliverrecords/**", "anon");//发料记录

这样就可以添加了。但问题是，当我再用前端页面的对数据增删改查的时候，就会提示没有权限，这是怎么回事？我是希望既可以利用后端controller的接口添加数据，又不影响前端页面的增删改查，要怎么做？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/b4b94dfb-24b7-47d6-96a2-375ba2c66b14)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/44e4244a-36ac-4a7f-9965-5031b55c2c5e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ciahua** [comment]
我必须去controller代码里把@RequiresPermissions注释掉，才能进行增删改查，这似乎不太科学吧？

**Comment by zhangdaiscott** [comment]
代码生成的菜单sql里面有对应的按钮脚本，你不授权肯定提示，
不需要控制可以把权限注解删除
