### ISSUE TITLE
如何在加载dev配置的时候同时加载位于application.yml同级的XXXX.yml配置

### ISSUE THREAD

**Issue by main-key** [jeecgboot/jeecg-boot#5148]
##### 版本号：
jeecgboot 2.4.5 

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
因为XXXX.yml是公用的，所以想直接作为一个配置加载，现在在application.yml添加
spring:
  application:
    name: jeecg-system
  profiles:
    active: dev, XXXX
  config:
    import: classpath:XXXX.yml
后没有加载到XXXX.yml配置中的配置。
要如何在加载dev配置的时候同时加载位于application.yml同级的XXXX.yml配置

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
通过nacos的config: import: classpath:XXXX.yml
