### ISSUE TITLE
修改密码时的校验问题

### ISSUE THREAD

**Issue by EvilMir** [jeecgboot/jeecg-boot#5149]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
密码验证问题，登录密码、确认密码，两者不同
修改登录密码，仍然报不同
![1](https://github.com/jeecgboot/jeecg-boot/assets/13412832/a942d05b-f4bc-4cb0-bd99-26f05816e36f)

![2](https://github.com/jeecgboot/jeecg-boot/assets/13412832/cc92e8e2-52cc-4a8f-ac31-e17944721263)

是不是登陆密码上面也应该触发校验规则
(右上角的修改密码也是)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
写的有点乱
