### ISSUE TITLE
修改包名和pom后，项目启动时报错No bean of type 'org.apache.shiro.realm.Realm' found.

### ISSUE THREAD

**Issue by M666666L** [jeecgboot/jeecg-boot#5152]
##### 问题描述：修改包名和pom后，启动报错，org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgSystemApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/jeecg/common/util/security/AbstractQueryBlackListHandler.class] cannot be opened because it does not exist
于是我在启动类添加了@ComponentScan("org.jeecg.modules.system")，但是这个时候启动报错：No bean of type 'org.apache.shiro.realm.Realm' found.
我重新reload了项目，以及clean了项目，但是启动依然报错

##### 截图&代码：
修改完成后：
第一步启动报错：
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [org.jeecg.JeecgSystemApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/jeecg/common/util/security/AbstractQueryBlackListHandler.class] cannot be opened because it does not exist
之后我在启动类添加了：
@ComponentScan("org.jeecg.modules.system")
![image](https://github.com/jeecgboot/jeecg-boot/assets/40979453/9b0fad64-94e3-4373-b956-e29e7b786ca6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa
20

**Comment by M666666L** [comment]
> http://jeecg.com/doc/qa 20
按照您给出来的配置，还是不行，还是报错：No bean of type 'org.apache.shiro.realm.Realm' found.

**Comment by M666666L** [comment]
> 

项目从官网拉下来后，只修改了部分包名和pom，其他的结构都没动
