### ISSUE TITLE
使用在线的Online表单开发出现固定表头列溢出table

### ISSUE THREAD

**Issue by 19522640242** [jeecgboot/jeecg-boot#5153]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/129490278/40453e32-093f-47fb-ad40-d8caeef336a1)

**Comment by zhangdaiscott** [comment]
Online表单开发 目前不支持表头，你是怎么做的

**Comment by zhangdaiscott** [comment]
无回复，关闭
