### ISSUE TITLE
仪表盘 堆叠柱状图 查询的时候视图未清空旧数据的 bug

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/jeecg-boot#5154]
##### 版本号：
 v3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线开发-  仪表盘设计 - 堆叠柱状图查询 按照条件 视图不更新  控制台数据已经输出，如果按照截图查询正常只出现一个颜色才对  ，但是旧数据没有清空

##### 截图&代码：

![1689663496250](https://github.com/jeecgboot/jeecg-boot/assets/139849659/7ca785a6-9fe6-4c8c-8c39-080badb29bf9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq 收录

**Comment by lsqGitHub716** [comment]
只是堆叠图还是其他图表也会存在这个问题？

**Comment by lsqGitHub716** [comment]
测试正常，请提供一下你的联动配置方式截图
