### ISSUE TITLE
越权操作，zhangsan用户可以修改admin用户插入的数据

### ISSUE THREAD

**Issue by 1614196964** [jeecgboot/jeecg-boot#5156]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
越权操作
登录admin账户，使用postman发送POST请求：http://localhost:8080/jeecg-boot/sys/dictItem/add ，插入一条数据id：1333

登录zhangsan账户，使用postman发送POST请求：http://localhost:8080/jeecg-boot/sys/dictItem/edit 请求可以修改admin插入的数据

add和edit都是org.jeecg.modules.system.controller.SysDataSourceController类中的方法

##### 截图&代码：
admin插入id为1333的数据
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718210253.png)

zhangsan用户修改id为1333的数据
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718210728.png)

问题代码定位
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718213323.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
默认没有这个规则控制，需要你自己来实现
