### ISSUE TITLE
普通用户可以删除、查询、修改管理员的数据

### ISSUE THREAD

**Issue by zhy1234554321** [jeecgboot/jeecg-boot#5157]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
问题代码在：org.jeecg.modules.system.controller.SysDepartRoleController类中
zhangsan用户可以删除、查询、修改管理员操作的数据
登录admin用户，访问http://localhost:8080/jeecg-boot/sys/sysDepartRole/add  插入id为12345和id为1234的两条数据
切换zhangsan用户，可以删除id为12345的数据，访问http://localhost:8080/jeecg-boot/sys/sysDepartRole/list  可以查看到admin部门的角色，可以id可以修改id为1234的roleName

##### 截图&代码：
admin插入id为12345和1234的数据
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718220424.png)

切换zhangsan删除id为12345的数据
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718220752.png)

![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718220720.png)

zhangsan查询admin的部门信息
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718223853.png)
查询结果
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718221740.png)

zhangsan修改id为1234的roleName
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718222216.png)
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718222245.png)
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718222324.png)

问题代码
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718223002.png)
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718223526.png)
![](https://gitee.com/AWallFlower/picture/raw/master/img/20230718223040.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
默认没有这个规则控制，需要你自己来实现
