### ISSUE TITLE
第一次进去也太慢了吧，转圈10几分钟

### ISSUE THREAD

**Issue by javaAjun** [jeecgboot/jeecg-boot#5158]
##### 截图&代码：
![)UH }68M6RF@WJ9BNRGT8ET](https://github.com/jeecgboot/jeecg-boot/assets/38597827/a7931d93-a834-4aba-a366-344aba252240)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by javaAjun** [comment]
而且还是localhost

**Comment by javaAjun** [comment]
第一个加载10分钟，等不及刷新了，图片是第二次加载，用了6分多钟，后面再访问快了

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/qa.html

```
1. 首屏加载慢问题
1.1 开发环境性能分析
- 平台经过优化目前启动到首屏加载完成，大概需要`30秒`左右。
- 首屏后，强制刷新 在 `2~3秒`左右。
提升性能技巧

如果你的首屏加载时间过分超过1分钟以上，请确认浏览器、node、vite版本。
谷歌浏览器版本过低 会导致慢，升级到最新版就可以解决 （此方法比较有效）
尽量不要用其他浏览器比如360，经测试 360浏览器 强刷的时间大概是谷歌浏览器 的两倍。
首屏的加载时间也跟电脑性能有关
Vue.js devtools 6.4.5 存在bug,会导致非常的卡[ #1987](https://github.com/vuejs/devtools/issues/1987)
```

**Comment by javaAjun** [comment]
好的，感谢！用vue2的版本是不是快一点

**Comment by zhangdaiscott** [comment]
vue2没这问题
