### ISSUE TITLE
仪表盘配置进菜单后 显示的bug

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/jeecg-boot#5159]
##### 版本号：
v3.5.2 

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
配置仪表盘到菜单后  拓展图标会来回切动 不固定， 在左边 鼠标切换不同组件会有抖动，  右边又不会，其次拓展后的 图标感觉也怪怪的 应该是浮起来 会比好

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/910a1755-01fd-4970-9106-16f5579a1499)
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/122ce94b-0161-4c90-be5d-413389064797)

![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/bb8114d2-550a-4f5c-94c9-bb26a1d5ed9d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收录 sq

**Comment by lsqGitHub716** [comment]
重新下依赖看样式是否还有问题

**Comment by zhoulel** [comment]
重新下载了依赖&nbsp; &nbsp;还是会存在抖动问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 仪表盘配置进菜单后 显示的bug (Issue #5159)





 
重新下依赖看样式是否还有问题

**Comment by lsqGitHub716** [comment]
你可以临时将样式 import 'jeecg-drag-design/lib/index.css'; 引入到main.ts中来解决这个问题

**Comment by zhangdaiscott** [comment]
已修复
