### ISSUE TITLE
一对多代码生成时子表xml文件未生成

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecg-boot#5161]
##### 版本号：
v3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
一对多代码生成时子表xml文件未生成，只有主表xml文件，后台生成时未报错，其他文件正常

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/253ad08a-3e07-46ba-af71-a03bfd371966)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/a48995b5-d201-44f4-be8a-5264eaaf3aad)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/8adc411e-053e-4d8c-bf1a-cd88960e399c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/ebb2cfab-e9c1-4cf5-8c98-b2ed10dcd3c3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的意思，截图标红提示生成成功了，但是实际没生成？

**Comment by cdsuifeng** [comment]
截图标红生成的是主表的xml，但是子表的没有生成

**Comment by zhangdaiscott** [comment]
你的表单类型设置的单表吧

**Comment by cdsuifeng** [comment]
设置的是主表，图3里有
