### ISSUE TITLE
新增服务调用接口404

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/jeecg-boot#5163]
##### 版本号：

最新版
##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
网关配置文件获取方式是通过数据库获取，数据库已经增加了规则，如下图，redis也已经存入该规则

##### 截图&代码：
数据库配置：
![image](https://github.com/jeecgboot/jeecg-boot/assets/63895685/db4025a0-f172-4389-aeb0-7fb656bc6dde)

404地址：
![8437dd27242014dd4bd7fa9231597ed](https://github.com/jeecgboot/jeecg-boot/assets/63895685/46d36bdc-36e9-4f45-9211-385f331943dd)

把act替换成jeecg-activiti是通的
![1689759820017](https://github.com/jeecgboot/jeecg-boot/assets/63895685/7b1083c1-c25c-4521-81a9-2e3e8a38fa24)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 15098731779** [comment]
为啥直接关闭了 @zhangdaiscott

**Comment by yichen-m** [comment]
解决了吗 求解
