### ISSUE TITLE
张三用户可以随意篡改管理管理员的个人信息

### ISSUE THREAD

**Issue by 1614196964** [jeecgboot/jeecg-boot#5164]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
张三用户可以随意篡改管理管理员的个人信息
User zhangsan can arbitrarily tamper with the personal information of the management administrator.
问题发生在org.jeecg.modules.system.controller.SysUserController类中的edit方法中
The issue occurs in the 'edit' method of the 'SysUserController' class in org.jeecg.modules.system.controller.

##### 截图&代码：
张三可以修改管理员的信息，修改之前：
Before the modification
![222fffca206c1d11cd1e7bb0197865b9](https://github.com/jeecgboot/jeecg-boot/assets/65948993/8aeaf12f-8dbf-4da6-87d9-74273dcd8ba7)

修改之后：
After the modification
![679cbb2e278688d854e087a3fc48e6d7](https://github.com/jeecgboot/jeecg-boot/assets/65948993/eef17f99-9407-40dd-ae94-d97a0cf34ba2)

问题代码定位：
Problem code localization:
![6a490888c946b929ffa776caa34abde8](https://github.com/jeecgboot/jeecg-boot/assets/65948993/a3162cfa-cdf1-44f1-bb16-c5e56157253d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复的问题不要再提
https://github.com/jeecgboot/jeecg-boot/issues/5156

如果你想控制权限，你可以针对某些敏感接口
1、加上操作按钮权限
2、需求控制创建人修改自己的数据，自己在代码里面加逻辑
