### ISSUE TITLE
在角色管理中，zhangsan用户可以修改和删除管理员的角色

### ISSUE THREAD

**Issue by 1614196964** [jeecgboot/jeecg-boot#5165]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在角色管理中，zhangsan用户可以修改和删除管理员的角色
In the role management system, the user "zhangsan" can modify and delete the roles of administrators.
问题代码出现在：org.jeecg.modules.system.controller.SysRoleController的edit和delete方法中
The issue code is present in the 'edit' and 'delete' methods of the 'SysRoleController' class in org.jeecg.modules.system.controller.

##### 截图&代码：
zhangsan用户修改管理员信息之前：
Before zhangsan user modifies the administrator's information:
![28ba3735f23aeb0a7013f1a7b79b8176](https://github.com/jeecgboot/jeecg-boot/assets/65948993/ff70c68e-2638-4be5-8df9-19f9acc46551)

修改之后：
After zhangsan user modifies the administrator's information:
![7bf3f2c54eac8004aef4f4fbdeff960c](https://github.com/jeecgboot/jeecg-boot/assets/65948993/6eac2c30-2e05-4e53-bd7d-3b7263c8f9c4)

zhangsan用户删除管理员信息之前：
Before zhangsan user deletes the administrator's information:
![c357d105606804e85bf5ae561ba4710b](https://github.com/jeecgboot/jeecg-boot/assets/65948993/732cb06e-e852-4497-95b1-e8dd7ca43ed6)

删除之后：
After zhangsan user deletes the administrator's information:
![15500cf298f80f7d42fe7ae531a96ca2](https://github.com/jeecgboot/jeecg-boot/assets/65948993/1baba502-0e0d-4594-a098-29dc6a03b998)

问题代码定位
Problem code localization:
![983cb0d77e9b756797df65248e961254](https://github.com/jeecgboot/jeecg-boot/assets/65948993/0fc1743e-6b56-438d-bc19-ad3f60d76b08)

![9b366d41b12918dc43a7da4d37b0199b](https://github.com/jeecgboot/jeecg-boot/assets/65948993/c69c778f-babc-425b-a734-3c5065de6fcf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复的问题不要再提
https://github.com/jeecgboot/jeecg-boot/issues/5156

如果你想控制权限，你可以针对某些敏感接口
1、加上操作按钮权限
2、需求控制创建人修改自己的数据，自己在代码里面加逻辑
