### ISSUE TITLE
张三可以修改并删除admin添加的规则

### ISSUE THREAD

**Issue by 1614196964** [jeecgboot/jeecg-boot#5166]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
zhangsan用户可以删除管理员添加的规则，也可以修改admin创建的规则
‘zhangsan’ user can delete the rules added by the administrator and can also modify the rules created by the 'admin' user.
问题代码出现在org.jeecg.modules.system.controller.SysCheckRuleController的edit和delete方法中
The issue code is present in the 'edit' and 'delete' methods of the 'SysCheckRuleController' class in org.jeecg.modules.system.controller.

##### 截图&代码：
zhangsan用户使用postman请求http://localhost:8080/jeecg-boot/sys/checkRule/delete?id=1234  删除之前：
Before zhangsan user sends a request using Postman to delete the rule with ID 1234 at http://localhost:8080/jeecg-boot/sys/checkRule/delete?id=1234, the state is as follows:
![006b2ee1228e47e36bbd01bac13a546c](https://github.com/jeecgboot/jeecg-boot/assets/65948993/8884c549-522b-49f5-aa7e-43cb29cf48a2)

删除之后，只剩下三条：
After the deletion, there are only three rules remaining.
![6882130530fa0533b796a43539c9036d](https://github.com/jeecgboot/jeecg-boot/assets/65948993/1f273afe-887a-4f13-aa6f-c4c58bd971dc)
![965e342d68c39c18f488af6f3cceb90f](https://github.com/jeecgboot/jeecg-boot/assets/65948993/ced887ac-c2de-46f4-87fb-c448c43d42d1)

张三可以修改admin创建的规则：
‘zhangsan’ user can modify the rules created by the 'admin' user.
![c76719d9afabdd84bd4406798ffa43d2](https://github.com/jeecgboot/jeecg-boot/assets/65948993/b157a607-ecd4-47b1-bdc1-3e5f623dd5c5)

postman发送请求：http://localhost:8080/jeecg-boot/sys/checkRule/edit  修改成功
Postman request sent to http://localhost:8080/jeecg-boot/sys/checkRule/edit was successful. The modification was completed successfully.
![34e54c2ae92cb1788294dc65c6783018](https://github.com/jeecgboot/jeecg-boot/assets/65948993/90b17cff-2f78-4382-8fde-502cfa4156b8)

![82d839f89e3e9b178b3ca2d2ba011399](https://github.com/jeecgboot/jeecg-boot/assets/65948993/b2a29410-de1f-4881-a9f9-905d481c61ff)

问题代码定位：
code localization
![6394e85f1c5accdd26b6766bb2ed28cc](https://github.com/jeecgboot/jeecg-boot/assets/65948993/bb56e298-2874-4414-8b5b-734ae475c933)

![f6df712981380be6b612c8c26fc17f8f](https://github.com/jeecgboot/jeecg-boot/assets/65948993/521c4d57-69c5-4cc2-b789-eb941e7ca3f8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复的问题不要再提
https://github.com/jeecgboot/jeecg-boot/issues/5156
