### ISSUE TITLE
数据脱敏注解 未生效

### ISSUE THREAD

**Issue by wangq2008** [jeecgboot/jeecg-boot#5168]
##### 截图&代码：
![e1](https://github.com/jeecgboot/jeecg-boot/assets/9882597/3a65d734-c3f5-482f-b3bb-158ff39276c6)
![e2](https://github.com/jeecgboot/jeecg-boot/assets/9882597/8ddec645-d6d8-464e-af3c-1f5931a8af38)
![e3](https://github.com/jeecgboot/jeecg-boot/assets/9882597/c3173efc-39cc-44e6-9c1a-bee042f274cf)
![image](https://github.com/jeecgboot/jeecg-boot/assets/9882597/4906f619-0562-425f-970d-0499546ce39a)

按文档中的脱敏说明操作，实体加注解，sevice方法加注解，但结果并没有脱敏处理。

**Comment by zhangdaiscott** [comment]
我们的脱敏方案，不是针对数据库层，是把数据库的明文数据加密传递给前端
