### ISSUE TITLE
关于接口文档的问题

### ISSUE THREAD

**Issue by CRIOWN** [jeecgboot/jeecg-boot#5169]
##### 问题描述：
关于knife4j 3.0.3
我刚入职做开发 公司要把基于jeecg的平台升级到3.5.2版本 我在做接口文档这一块
![图片](https://github.com/jeecgboot/jeecg-boot/assets/128948671/7d2db62e-52fb-4fde-a6d5-1371b1f93755)

老版本这样是可以的（两个包 jeecg只有启动项 另一个包公司的模块）
所以我想要扫描这个包和org.jeecg
但是目前 只扫描org.jeecg，jeecg自带的模块接口文档没有问题，公司模块不被扫描 
如果写成上图的样式（扫描两包） 则都不显示。。。。
![图片](https://github.com/jeecgboot/jeecg-boot/assets/128948671/3fff1e56-5e3d-4238-b412-adb76d6bcc2b)
这是jeecg-system的接口文档 也不显示接口列表了
 
已知公司类的代码没有问题（能在原来的jeecg平台上正常运行，不过原来的knife4j版本是2.09）

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;

**Comment by zhangdaiscott** [comment]
抱歉，自己升级的我们没办法处理
