### ISSUE TITLE
微服务新建服务配置gateway路由转发，该服务内的接口路径需要增加统一的接口前缀？

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/jeecg-boot#5175]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
新建一个quality服务，配置的转发是/quality/**，那我这个服务下所有的接口前缀都必须加上/quality这个吗？不加就404
加上就是正常的

##### 截图&代码：
**网关配置**
![image](https://github.com/jeecgboot/jeecg-boot/assets/63895685/3012da91-265d-4e88-8a6d-1272f04a45f4)

**前端请求**
![fc7e141354ac01c44320191f66c8f99](https://github.com/jeecgboot/jeecg-boot/assets/63895685/f397c319-9019-48d0-a211-fe1a115d25c6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
微服务模块的请求就应该统一前缀

**Comment by 15098731779** [comment]
是应该统一前缀，但是不应该在接口名写吧，在网关配置了路由转发不就可以了，前端请求正常加，就不需要再controller上面在加这个了吧
