### ISSUE TITLE
jeecg-boot-redis:6379 相关问题

### ISSUE THREAD

**Issue by CRIOWN** [jeecgboot/jeecg-boot#5176]
##### 问题描述：
想要修改默认的redis连接  jeecg-boot-redis:6379

##### 截图&代码：
![微信图片_20230724144257](https://github.com/jeecgboot/jeecg-boot/assets/128948671/9fa8feef-3d4c-4d2e-bd65-9c6f6bcb8529)
由于我的服务器端口受限还有远程服务器的原因 我想要修改这个redisurl，但是看了很久都没看出来它从哪里读的配置文件，而且直接在gateway的module下写application.yml也不能直接覆盖掉，请问如何修改这个 或者说这个的配置文件在哪

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
nacos

**Comment by Jinyilong** [comment]
> nacos中的yaml文件

![image](https://github.com/jeecgboot/jeecg-boot/assets/102419278/318b0e19-abf9-4954-8b5d-e5be5001d9ca)
改哪一个兄弟 我把网关和 在外层的改了还有一个地方报错 
![image](https://github.com/jeecgboot/jeecg-boot/assets/102419278/8df886d5-c161-4e1e-9c82-8a0b93de6e99)
![image](https://github.com/jeecgboot/jeecg-boot/assets/102419278/6853e4d0-5a47-4ee7-8aa2-241fe533c537)
