### ISSUE TITLE
a-input-number输入后变空白

### ISSUE THREAD

**Issue by xiaose1970** [jeecgboot/jeecg-boot#5180]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在插槽模式下数字输入框输入数字后变空白

##### 截图&代码：
	{
		title: '汇款金额',
		key: 'amount',
		type: JVxeTypes.slot,
		width: "200px",
		placeholder: '请输入${title}',
		slotName: 'amount',
	},

					<template #amount="props">
						<a-input-number v-model:value="props.value" :min="1" :max="10"/>
					</template>
![微信截图1](https://github.com/jeecgboot/jeecg-boot/assets/140490787/aec74e92-bbfe-45f1-a2dd-0807bbf9dcd8)
![2](https://github.com/jeecgboot/jeecg-boot/assets/140490787/0e3fd591-d5c1-47f7-8ef7-fed7901ac3e0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
xp

**Comment by zhangdaiscott** [comment]
描述过于简单
