### ISSUE TITLE
仪表盘设计器重命名保存时空指针异常

### ISSUE THREAD

**Issue by oneincase** [jeecgboot/jeecg-boot#5184]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？

vue3版本
##### 问题描述：
仪表盘设计器重命名保存时空指针异常

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/57388318/9e4de136-7c06-4cfc-976b-c7a920108ec5)
后台异常日志
![image](https://github.com/jeecgboot/jeecg-boot/assets/57388318/f71586ea-b6e5-4e56-a16e-49c9389fa62c)

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试未复现你遇到的问题
