### ISSUE TITLE
创建了一个给外部第三方调接口用的账号，且没有设置超时时间，为啥还是会提示Token失效

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#5185]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
新增了一个api用户，判断了如果是api用户不设置超时时间，第三方系统调用接口的时候使用这个token，为啥过段时间还是会报token失效？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/6ee506df-da29-413f-9468-0baab7327d5f)
登录方法里面添加了判断，如果是api用户则不添加超时时间，也就是永不超时，但是为啥第三方使用这个用户的token调用接口的时候还是会提示token失效。

![image](https://github.com/jeecgboot/jeecg-boot/assets/42790595/1d2438e2-5e29-4ae2-83dc-0cd269496e71)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己写代码，请自己分析

**Comment by peak666** [comment]
> 自己写代码，请自己分析

那我想让某一个用户登录后永不超时，永远在线，要怎么配置？
