### ISSUE TITLE
问下为什么代码生成器的数据库读取要拆出来，而且不支持多库？

### ISSUE THREAD

**Issue by luxx-lq** [jeecgboot/jeecg-boot#5186]
##### 版本号：
最新版本
##### 前端版本：vue3版？还是 vue2版？
无关
##### 问题描述：
问下为什么代码生成器的数据库读取要拆出来，而且不支持多库？
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/58515565/c7b7d726-5cf0-40d5-b6cc-8749c58349b2)

**Comment by zhangdaiscott** [comment]
参考这个
http://doc.jeecg.com/2043917

**Comment by luxx-lq** [comment]
我看过这个文档，我的意思是为什么不做动态读取当前yml的，这样还方便操作支持多库

**Comment by luxx-lq** [comment]
我们在本地项目改造使用了yml里面的多数据库方式，感觉很好用，不知道你们项目安排所以问问，如有需要，我可以提pr

**Comment by zhangdaiscott** [comment]
欢迎
