### ISSUE TITLE
修改项目包名后，同时按照http://jeecg.com/doc/qa 第22条修改扫描路径，启动出现异常

### ISSUE THREAD

**Issue by wenhai2000** [jeecgboot/jeecg-boot#5187]
##### 版本号：
Jeecg  Boot Version: 3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 截图&代码：
[![pCvOOkd.png](https://s1.ax1x.com/2023/07/27/pCvOOkd.png)](https://imgse.com/i/pCvOOkd)
[![pCvOqTH.png](https://s1.ax1x.com/2023/07/27/pCvOqTH.png)](https://imgse.com/i/pCvOqTH)
[![pCvOb0e.png](https://s1.ax1x.com/2023/07/27/pCvOb0e.png)](https://imgse.com/i/pCvOb0e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wenhai2000** [comment]
问题描述有误，应该是已根据 http://jeecg.com/doc/qa 第20条修改扫描路径，启动出现异常

**Comment by zhangdaiscott** [comment]
mybatis那块需要保留jeecg的扫码路径

**Comment by Boctopus** [comment]
mapper-locations、application都更改了，还是报错，还需要改什么地方吗？
