### ISSUE TITLE
仪表盘 数据集 和表单的 时间动态值 设置无效

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/jeecg-boot#5189]
##### 版本号：
 v3.5.3 

##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：
仪表盘 设置数据集的时候 如果是时间为查询条件 需要设置动态的 比如当天或者前几天  都没有办法起作用  只能写死固定值 
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/2e99b092-454c-4619-9e6c-680b3381f71b)

以及 表单的时间查询 默认值不管怎么设置也没有起作用
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/ce57c35c-10d4-4689-9655-d2ba5dddaa3e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
问题已收录
