### ISSUE TITLE
JPopup控件选择并回填数据到控件不能触发onChange事件？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5191]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
点击JPopup后弹窗，选择数据行后返回，并回填数据到JPopup本身，以及其他intpu文本框，但是却不能触发onChange事件，是怎么回事？我希望在从JPopup弹窗选择数据返回后，能够产生一个触发事件，以便触发下一步动作。应该怎么做？

在我的程序里，有两个JPopup，我希望把第一个JPopup的返回值，作为第二个JPopup的选择条件，因此，需要获得第一个JPopup的返回值。但是第一个JPopup返回数据后却没有产生触发事件，连常用的onChange事件也不触发，无法得知第一个JPopup已经返回，从而无法把参数传递给下一个JPopup。

##### 截图&代码：
这段代码没反应：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/5e5285ea-b8b3-4c6e-975e-a2ce3660da07)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
xp

**Comment by ciahua** [comment]
> xp

??? 还请多指教！
