### ISSUE TITLE
未找到jeecg-uniapp的后台管理界面

### ISSUE THREAD

**Issue by simeng66** [jeecgboot/jeecg-boot#5193]
##### 问题描述：
未找到jeecg-uniapp的后台管理界面

##### 截图&代码：
开发手册中的：JeecgUniapp开发->APP首页排版设计  里面描述的可以更改排版、模块的后台管理界面没有找到

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
排版不是开源的功能
