### ISSUE TITLE
vxe表格的异步删除，不触发事件

### ISSUE THREAD

**Issue by zhichengbohui** [jeecgboot/jeecg-boot#5194]
##### 问题描述：
vxe表格添加异步删除触发事件，删除的时候没有任何反应，也不执行handleTableRemove函数（采用低代码自动生成的一对多代码）

##### 截图&代码：

![微信图片_20230730112332](https://github.com/jeecgboot/jeecg-boot/assets/40782576/ff99f95a-076e-4f09-8b6f-bfb89c7dffad)
![微信图片_20230730112324](https://github.com/jeecgboot/jeecg-boot/assets/40782576/517c9b2b-26e6-4a1b-a1c2-05239cf037f4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by liqingelio** [comment]
您好，请问您是怎么操作的？另外就是您有遇到过在这个vxe明细表格里出获取到主表的数据的这种情况吗?这种您是怎么处理的呢？麻烦您了
