### ISSUE TITLE
websocket怎么用在线工具测试

### ISSUE THREAD

**Issue by wangheso** [jeecgboot/jeecg-boot#5198]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wangheso** [comment]
vue3版本

**Comment by zhangdaiscott** [comment]
https://www.zhihu.com/question/576667114?utm_id=0&wd=&eqid=c9fe270f001898b7000000036476d6f9

百度 websocket Postman

**Comment by wangheso** [comment]
默认自带的websocket测试页面里 的地址不正确 链接不上，正确的 地址是什么，在哪里配置
