### ISSUE TITLE
在线表单开发字段提示超过4个字符时，查询条件与编辑中只显示前面四字，建议加长

### ISSUE THREAD

**Issue by skillful2002** [jeecgboot/jeecg-boot#5200]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线表单开发字段提示超过4个字符时，查询条件与编辑中只显示前面四字，建议加长

##### 截图&代码：

<img width="767" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/07903585-9dda-4781-ad7e-59b1158d0d18">

**Comment by zhangdaiscott** [comment]
最新版可以自定义label长度
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/5bd6cc2b-733c-4eb6-a87d-648ae38eae74)

**Comment by skillful2002** [comment]
> ，查询条件与编辑中只显示前面四字，建议加长

没有找到配置的地方啊？最新版本是指哪个版本？

**Comment by skillful2002** [comment]
> 最新版可以自定义label长度 ![image](https://user-images.githubusercontent.com/3162115/257384570-5bd6cc2b-733c-4eb6-a87d-648ae38eae74.png)

没有找到啊，最新版本是指哪个版本？
