### ISSUE TITLE
同步外部数据库功能报错

### ISSUE THREAD

**Issue by chaose** [jeecgboot/jeecg-boot#5202]
##### 版本号：
jeecg-boot-parent:3.0
ant-design-vue-jeecg:3.0.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
配置jeecg_database.properties后，使用“从数据库导入表单”导入外部表。对导入的表单进行编辑后，使用同步数据库功能报错

##### 截图&代码：
选择普通同步：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55130483/e11b6510-431d-4b42-ad63-97a00eb31e0d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55130483/d1a805e9-9e41-4132-8756-950fac7b36e5)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55130483/6bfb11e3-eb5e-42e0-ad6e-52a9c0f496ed)
同步数据库失败，Unable to perform unmarshalling at line number 5 and column 6. Message: cvc-complex-type.2.4.a: Invalid content was found starting with element 'property'. One of '{"http://www.hibernate.org/xsd/orm/hbm":meta, "http://www.hibernate.org/xsd/orm/hbm":tuplizer, "http://www.hibernate.org/xsd/orm/hbm":subselect, "http://www.hibernate.org/xsd/orm/hbm":cache, "http://www.hibernate.org/xsd/orm/hbm":natural-id-cache, "http://www.hibernate.org/xsd/orm/hbm":synchronize, "http://www.hibernate.org/xsd/orm/hbm":comment, "http://www.hibernate.org/xsd/orm/hbm":id, "http://www.hibernate.org/xsd/orm/hbm":composite-id}' is expected. : origin(null)
选择强制同步：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55130483/173a084d-d17b-4f47-863d-c55ffd0301da)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by martinzh717** [comment]
### 同样的问题，有大佬看一眼吗？ 版本： v3.6.3 | 2024-03-11 @zhangdaiscott

**Comment by martinzh717** [comment]
@chaose 帅哥，为什么close了？ 问题有解决吗？

**Comment by chaose** [comment]
没有解决，使用强制同步说不定可以同步成功，但是也有少数表普通同步和强制同步都会报错，我把这种表用jeecg自带的创建表，一个一个字段手工创建就可以了。我一个字段一个字段去排查也没找出问题，你要是想问，我可以把这个重新打开
