### ISSUE TITLE
Online报表配置，单条件查询能否支持模糊查询

### ISSUE THREAD

**Issue by chendong2** [jeecgboot/jeecg-boot#5203]
##### 问题描述：
在Online报表配置中添加了报表，也设置了查询条件，但是查询条件不支持模糊搜索，请问要如何处理？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/9476636/49d335db-fb54-4b2a-82bb-e00e4d470ec8)

**Comment by hongbo1030** [comment]
vue3怎么支持的啊，链接在哪?
