### ISSUE TITLE
求助：无法将JPopup获取的值传递给另一个JPopup作为搜索条件？？？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5204]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在一个Form上放了几个JPopup组件，比如3个JPopup，每个JPopup都绑定了一个报表。现在需要将第一个JPopup的筛选结果作为第二个JPopup的报表搜索条件，不知道该如何实现。我了解报表有个param参数，但是，如何能取到第一个JPopup的回填值给第二个JPopup的param呢？而且触发动作是什么呢？第一个JPopup回填没有触发动作，第二个JPopup弹出也没有触发动作，该如何把值传过去呢？不太了解Jeecg的机制，看了很多视频，文档也没有明白。搞了好久了，都不理想。

还请各位大牛指点一下！！！
谢谢！

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/37827583/08f9d98c-9e38-4886-9afe-00aaf72c6a08)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
测试无问题
