### ISSUE TITLE
online报表越权访问问题

### ISSUE THREAD

**Issue by healkerzk** [jeecgboot/jeecg-boot#5205]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线报表（/online/cgreport）未授权访问问题
“online报表配置”界面的授权是好使的,未授权用户访问会提示404
但是一旦访问实际的报表，如"online/cgreport/6c7f59741c814347905a938f06ee003c"等，任意非授权的用户都可以访问到，存在越权访问问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
online/cgreport/6c7f59741c814347905a938f06ee003c 你配置菜单后，就只有有菜单权限的人，才能访问
