### ISSUE TITLE
关于quartz定时任务点击启动后没有立刻执行

### ISSUE THREAD

**Issue by JockeryYue** [jeecgboot/jeecg-boot#5207]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/119843116/ef7fd4be-a5ab-4247-abd2-cb9c6f8fbcf3)
![image](https://github.com/jeecgboot/jeecg-boot/assets/119843116/e08c7aa3-4e13-4fd5-a6b9-51c1b4e2668a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/119843116/512aa244-9dd9-4034-8774-3a020b7dfae3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/1ae8e175-bb9f-4126-bcae-178ba601e45f)
