### ISSUE TITLE
redis客户端4.x版本爆nosuchMethod

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5210]
##### 版本号：

3.5.3
##### 前端版本：vue3版？还是 vue2版？

vu3
##### 问题描述：
现在公司升级jedis版本到4.x了，但是会导致nosuchMethod的问题，我看项目中用的crazycake最高支持的jedis是3.x版本，
后续有没有考虑移除这块，自己写redis管理器，因为crazycake很久没有更新了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
他现在最新的版本是 3.3.0，升级不好使吗
https://github.com/alexxiyang/shiro-redis/releases

**Comment by zhangdaiscott** [comment]
等后面官方升级吧，我们自己写目前没这个需求
