### ISSUE TITLE
jeecgboot 是否支持同一模板批量下载Excel或pdf？

### ISSUE THREAD

**Issue by zhangpeng0090** [jeecgboot/jeecg-boot#5211]
##### 版本号：
前端 Vue3  3.4.2
后端           3.4.2
##### 问题描述：
jeecgboot 是否支持pdf下载？
jeecgboot 是否支持批量Excel/pdf下载

##### 截图&代码：

无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没有这功能
