### ISSUE TITLE
Form中的JPopup组件为何不能触发onChange

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5213]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在Form中放置一个JPopup组件，然后绑定一个报表，通过弹窗选择回填数据，本来想回填数据之后，能触发该组件的onChange事件，或者整个表单的onChange事件，但没有反应，这是为何？我希望JPopup弹窗回填数据以后有一个触发事件，或者回调函数，该怎么做呢？
或者说，回填的数据怎样双向绑定到某个数据呢？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/535424d5-fb6f-4c14-848a-3d0d83fe5cfb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/5191

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/677

**Comment by ciahua** [comment]
> [jeecgboot/jeecgboot-vue3#677](https://github.com/jeecgboot/jeecgboot-vue3/issues/677)

上面两个都没用解答啊，还请明示。多谢！

**Comment by liaozhiyang** [comment]
已添加，下一版本发布
