### ISSUE TITLE
积木报表中的数据报表是否可以设置固定标题行，因为数据量太大，往下滚动后，看不到标题行

### ISSUE THREAD

**Issue by liqingelio** [jeecgboot/jeecg-boot#5215]
##### 截图&代码：

![1691038749930](https://github.com/jeecgboot/jeecg-boot/assets/38447510/ddeb6ca0-c8e7-4ae3-b5ec-49dbe67e4be7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
暂不支持

**Comment by liqingelio** [comment]
请问这个大概什么时候可以有实现
