### ISSUE TITLE
jeecgboot后端项目，把tomcat替换成国产的宝兰德，应该怎么做？

### ISSUE THREAD

**Issue by lijl-vb** [jeecgboot/jeecg-boot#5217]
##### 版本号：
3.4.4

##### 问题描述：
参考 https://blog.csdn.net/yujiubo2008/article/details/128973760 文档把jeecgboot后台项目中tomcat替换为宝兰德中间件后，程序本地可以运行，但打包的时候提示有些依赖包不存在，实际上这些依赖包是存在的。请问题是什么原因？

##### 截图&代码：
![8284ac96d3aa5fc9dea58dab980e37b](https://github.com/jeecgboot/jeecg-boot/assets/73126845/553323ad-d6ed-4e25-83e9-25d1f849692a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的错误看着很不应该，你还是自己多看看，非严重问题
