### ISSUE TITLE
LoginUser中@SensitiveField注解导致getUserPermissionByToken接口获取到中文的username是??;菜单权限失效

### ISSUE THREAD

**Issue by zjarlin** [jeecgboot/jeecg-boot#5221]
##### 截图&代码：
<img width="1427" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/67467679/de333882-b8e6-4b3f-98ca-22c7b0fda58b">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
按照issue补充信息
