### ISSUE TITLE
前端用户页面进行新增用户时，如果填入的用户账号是后端逻辑删除的，它也会扫描数据库认为其存在

### ISSUE THREAD

**Issue by onism111** [jeecgboot/jeecg-boot#5222]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/76649871/ec572c76-9fff-4884-9263-3081f24b73fd)
![image](https://github.com/jeecgboot/jeecg-boot/assets/76649871/e2044c4e-1e13-47a5-be48-e448141bfd7a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/76649871/67a99be5-d1cd-40de-8666-4b57b1d1f7c0)
![image](https://github.com/jeecgboot/jeecg-boot/assets/76649871/ba92263e-3ebc-43c3-ab0c-19d060dc78ba)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这样是对的
