### ISSUE TITLE
在线表单的附表配置了字典不生效。

### ISSUE THREAD

**Issue by skillful2002** [jeecgboot/jeecg-boot#5224]
##### 截图&代码：
配置界面：
<img width="1118" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/8fdbbb5d-3876-46d7-9abe-fc9727093878">

效果界面：
<img width="634" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/81d93960-6457-4f0a-b1d5-393852feddc6">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你为什么要用标准字段

**Comment by zhangdaiscott** [comment]
字段的控件类型也一块改了

**Comment by skillful2002** [comment]
> 你为什么要用标准字段
因为我要显示创建人所在的部门。
另外：
其他字段也一样不行啊，我只是一个示例。

**Comment by skillful2002** [comment]
> 字段的控件类型也一块改了

搞定了，谢谢！
