### ISSUE TITLE
nacos与gateway的dockerfile暴露端口一样，docker-compose的时候会冲突

### ISSUE THREAD

**Issue by WJLMGQS** [jeecgboot/jeecg-boot#5225]
##### 问题描述：
nacos的Dockerfile: EXPOSE 8848, 与gateway定义的8848端口一样了，用docker-compose结合Dockerfile的时候端口回冲突，我改成9000了

##### 截图&代码：

<img width="1257" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/5037479/4f5c2380-c4e2-47fc-8ef4-213a0e3be00f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
gateway 是EXPOSE 9999，你自己改坏的吧
