### ISSUE TITLE
jeecgboot连接redis的国产替代产品Tendis(腾讯)/Pika(360)报错

### ISSUE THREAD

**Issue by lijl-vb** [jeecgboot/jeecg-boot#5233]
##### 版本号：
3.4.4

##### 问题描述：
jeecgboot连接redis的国产替代产品Tendis(腾讯)/Pika(360)报错，这两个产品号称完全兼容redis。请问一下应该怎么处理？

##### 截图&代码：
1、连接Pika(360)报错截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/73126845/993c56d8-e5af-4ca0-a007-8d6dcb5f2096)

2、连接Tendis(腾讯)报错截图
![$Y(B(I{6~M8)W9 KARL%MB](https://github.com/jeecgboot/jeecg-boot/assets/73126845/9c959281-94d3-49bc-9360-58fcc062d3f4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
百度，多联调吧，目前我们没这个需求，没办法帮你去集成测试
