### ISSUE TITLE
后端新建模块，接口404

### ISSUE THREAD

**Issue by wangzuojun** [jeecgboot/jeecg-boot#5234]
##### 问题描述：后端新建模块，接口404。
后端新建模块，pom中引入了jeecg-boot-base-core，项目pom和start的pom中都引入了新建的模块，application-dev.yml中mybitisPlus和MybatisPlusSaasConfig添加了mapper路径，Swagger2Config添加了包路径，清过缓存，始终404。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/cfa8609f-00f3-4d9f-b9b0-9420889a287c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/3485a8ca-d420-41eb-a55f-1195b2a7a374)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/4c24b22a-826f-48e3-9e7d-55ea0d1b6343)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/5012bdcb-99ae-4b8d-b3e0-5c75b06e93a8)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/302f9418-0cad-4a6f-a9d6-4600138ac571)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/faf085d3-6a88-4f4e-883d-6913dda57ea8)
![image](https://github.com/jeecgboot/jeecg-boot/assets/112042455/e067e013-21e6-4ebb-8798-7a19828498d9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven刷新生效了吗
