### ISSUE TITLE
自定义包根路径问题

### ISSUE THREAD

**Issue by Boctopus** [jeecgboot/jeecg-boot#5235]
##### 版本号：
3.5.3
##### 前端版本：vue3版？还是 vue2版？
vue2
##### 问题描述：
按照官网常见问题：http://jeecg.com/doc/qa 第20.条：自定义包根路径，application的scanBasePackages、mapper-locations都改掉了，启动还是报错。
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/39395705/5bf74f2a-ad85-4918-a2b7-148192332561)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Boctopus** [comment]
system-biz模块引入了hibernate-re模块，这个模块下面有个a类（onlReportQueryBlackListHandler类），他有对core模块中AbstractQueryBlackListHandler类的引用，按照官网变更包根路径后，导致初始化这个类失败。
<img width="845" alt="jeecg-error1" src="https://github.com/jeecgboot/jeecg-boot/assets/39395705/e84e8f92-7afa-410f-90a9-73e30758eaf1">

**Comment by zhangdaiscott** [comment]
你为什么要改core的路径，你新的代码用新路径不就可以了

**Comment by coral-zone** [comment]
后面还有方法改吗？

**Comment by zhangdaiscott** [comment]
文档
https://help.jeecg.com/java/advanced/basepath.html

**Comment by coral-zone** [comment]
如果要改core的路径，现在是不是没办法了
