### ISSUE TITLE
低代码开发中，配置了扩展配置，生成后没有对应功能。

### ISSUE THREAD

**Issue by baoxituo1** [jeecgboot/jeecg-boot#5236]
##### 截图&代码：

<img width="1441" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8840719/16d1936d-a0d6-4d4d-acf1-f77e9adade1c">
在线测试右侧有功能区，也能正常弹窗全屏
<img width="1792" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8840719/37f8f681-022d-4b7b-b361-1e53bcf4afc7">
生成代码导入到项目后和在线测试不一致
<img width="1577" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8840719/7557492b-64a7-4efd-974f-ca62a44b86b0">
请问这是什么问题？

另外在线测试一对多的时候，新增旁边有弹窗新增和编辑。我在生成代码后一对多新增也想要这个功能，请问该怎么实现?
在线预览效果：

<img width="448" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8840719/43a045df-4f79-497d-9441-ecd79534f2a6">

目前生成代码效果：

<img width="339" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8840719/089e1f49-8fd8-4458-b63d-22094f9025b4">

非常感谢能帮忙回答疑问🙏

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持生成
