### ISSUE TITLE
Online表单开发，代码生成后下载本地报错

### ISSUE THREAD

**Issue by zgh1121** [jeecgboot/jeecg-boot#5237]
##### 问题描述：：Online表单开发，代码生成，下载到本地，中文文件名出现编码问题

是否可以对文件名进行一次转义：URLEncoder.encode("生成代码_1691400108803.zip", "UTF-8");

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/108775523/8775006a-47d1-49e3-9e14-28816ba1bbca)
![image](https://github.com/jeecgboot/jeecg-boot/assets/108775523/9bdb5a3b-6f79-4e55-a633-b40011ceed20)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是什么场景下出现的问题？

**Comment by zgh1121** [comment]
> 是什么场景下出现的问题？

老师，具体业务场景就是：Online表单开发——>生成代码——>点击下载到本地按钮报错

![image](https://github.com/jeecgboot/jeecg-boot/assets/108775523/2c09946c-eb8d-404b-8faa-917e2c12d174)
![image](https://github.com/jeecgboot/jeecg-boot/assets/108775523/ba68d2d7-0d2d-4168-a23a-66f7d674b6a0)

**Comment by zhangdaiscott** [comment]
为什么我们的演示环境没问题

**Comment by zgh1121** [comment]
> 为什么我们的演示环境没问题

老师，具体原因不是很清楚，我也是从git上拉下来代码后，跑了一下项目，然后就有这个问题了。
我从咱们官方QQ群询问此问题，也有不少同学有类似的问题，也没解决。
困惑了好几天，无奈之下，我就来请教老师了。
看是否可以进行UTF-8转义一下URLEncoder.encode("生成代码_1691400108803.zip", "UTF-8");

**Comment by zgh1121** [comment]
> 为什么我们的演示环境没问题


> 为什么我们的演示环境没问题

老师，这个问题可以优化吗？
对中文，文件名进行UTF-8转义，应该会让代码更加完美把
URLEncoder.encode("生成代码_1691400108803.zip", "UTF-8");

**Comment by zhangdaiscott** [comment]
下个版本发布
