### ISSUE TITLE
系统管理-我的部门

### ISSUE THREAD

**Issue by 123brl** [jeecgboot/jeecg-boot#5239]
##### 问题描述：我的部门没有数据，即使用户绑定了部门id，但是用
LoginUser user = (LoginUser) SecurityUtils.getSubject().getPrincipal();
获取的user对象的departIds字段为空字符

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个对象里面存的是登录的部门不是用户与部门的关系
