### ISSUE TITLE
访问微服务接口超时，导致数据加载不出来

### ISSUE THREAD

**Issue by CRIOWN** [jeecgboot/jeecg-boot#5241]
##### 版本号：
3.5.2 后端

##### 问题描述：
想要修改超时访问时间 发现常见问题文档中的那段配置和对应的代码已经都没了或者被注释掉了 
那现在版本是怎么去设置这个超时访问时间呢，或者说我把注掉部分重新打开可以解决吗    为什么要注掉呢

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/128948671/b9af1530-b351-47cf-8eff-b7d3c231f3a4)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/128948671/f2ef82c3-2ac8-4748-a350-081ef8df377c)

**Comment by zhangdaiscott** [comment]
你应该是修改前端的超时设置吧
src/utils/http/axios/index.ts
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/e669da5c-837d-42f7-85a7-ef6546752475)

**Comment by CRIOWN** [comment]
> 你应该是修改前置的超时设置吧src/utils/http/axios/index.ts ![image](https://user-images.githubusercontent.com/3162115/268452805-e669da5c-837d-42f7-85a7-ef6546752475.png)

后面我修改了这个地方改为100s 但是前端还是在十秒左右（默认10s）就自动断掉连接（不接收数据）并且报超时错误，请问是什么原因呢？ 我是在 在线表单设计 这里遇到这个问题的 这里的超时好像不是在你发的这个地方设置的 我也没找到 是被封装的吗？
![21d5a701f86b271c54a3bf9192f1dc5](https://github.com/jeecgboot/jeecg-boot/assets/128948671/07cf05cf-25af-4db4-b77d-fe9a7d1c32f9)

**Comment by zhangdaiscott** [comment]
online表单的超时是在打包js里面，你改不了

**Comment by CRIOWN** [comment]
> online表单的超时是在打包js里面，你改不了

那有什么办法可以绕过吗😢
