### ISSUE TITLE
数据库字段备注错误，部门表

### ISSUE THREAD

**Issue by 123brl** [jeecgboot/jeecg-boot#5242]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/29086664/0f23aa85-47be-4783-a29e-5c071ae9e435)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
