### ISSUE TITLE
通过网关请求system中某个接口，没有加上服务名（jeecg-system）也能正常请求

### ISSUE THREAD

**Issue by tony2y** [jeecgboot/jeecg-boot#5244]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue#

##### 问题描述：
通过网关请求system中某个接口，没有加上服务名（jeecg-system）也能正常请求，请问这是在哪里处理的呢？

##### 截图&代码：

<img width="934" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/38598582/38a4e0c9-880e-4088-b80e-c398b78fb25c">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
gateway转发的
