### ISSUE TITLE
租户整体逻辑改造是否已生效？

### ISSUE THREAD

**Issue by NeilGPT** [jeecgboot/jeecg-boot#5245]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
请问文档中的租户整体逻辑改造是否已生效，我运行最新的代码，发现租户逻辑还不是文档中介绍的。
文档里写v3.5.3+生效，是否指下一个版本才会生效，如果是的话，大概要多久？
谢谢！

##### 截图&代码：
![1691657054398](https://github.com/jeecgboot/jeecg-boot/assets/129829204/0a584d95-bf04-4f40-81ee-9946df7bd800)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
3.5.3开始
