### ISSUE TITLE
jeecgboot后端如何通过token获取用户信息

### ISSUE THREAD

**Issue by main-key** [jeecgboot/jeecg-boot#5246]
##### 版本号：
2.4.5

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
jeecgboot后端如何通过token获取用户信息，最终目的是为了获取用户所在的部门编码
或者，将token用request.setAttribute("X-Access-Token",token);手动添加到HttpServletRequest request中后通过 LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();怎么能取到值

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
通过token获取用户，你再调用接口自己查部门

**Comment by main-key** [comment]
好的，我也是这么干的String username = JwtUtil.getUsername(token);。。感谢
