### ISSUE TITLE
关于 org.jeecgframework.poi.excel 的一些建议

### ISSUE THREAD

**Issue by rock-li-k** [jeecgboot/jeecg-boot#5248]
##### 问题描述：

1、autopoi @interface Excel 类希望可以加上 @Inherited，这样可以方便继承扩展使用；
2、ExcelExportUtil 的 final 是否可以去除掉，方便继承扩展使用；

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/108796676/5be169f3-213f-42a5-a52d-3a1ddd60354f)

![image](https://github.com/jeecgboot/jeecg-boot/assets/108796676/4486b6ab-df7a-4b5f-84da-1ec3521a0a7f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by hoperunChen** [comment]
已修复，待新版本发布

**Comment by rock-li-k** [comment]
收到。非常感谢；望jeecg越做越好；


风若止水
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 关于 org.jeecgframework.poi.excel 的一些建议 (Issue #5248)





 
已修复，待新版本发布
