### ISSUE TITLE
JS增强无效

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5250]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
按照开发文档给出的例子，写了个JS增强，测试了一下无效。。。不应该啊。。。哪里不对了？从控制台看，说是“增强没找到”？

##### 截图&代码：
![微信截图_20230812123439](https://github.com/jeecgboot/jeecg-boot/assets/37827583/f94d0f19-513e-4cbb-8671-31ba9ea9856a)
![微信截图_20230812123508](https://github.com/jeecgboot/jeecg-boot/assets/37827583/ba046bff-0965-4602-8853-06625c4a060e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你写的方法靠猜吗？不看文档？
