### ISSUE TITLE
JS增强代码不生效，请问JS增强是在哪个地方执行生效的

### ISSUE THREAD

**Issue by hjldev** [jeecgboot/jeecg-boot#5253]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在Online表单开发中增加了JS增加代码，没有执行。请问JS增强是在哪个地方执行生效的，怎么通过配置去查找到具体的生效页面。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
应该是你配置错误，有问题其他人早反馈了
