### ISSUE TITLE
代码生成报空

### ISSUE THREAD

**Issue by ZhaoDiDiDi** [jeecgboot/jeecg-boot#5257]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
 vue2版

##### 问题描述：
代码生成报空

##### 截图&代码：
![微信图片编辑_20230815013402](https://github.com/jeecgboot/jeecg-boot/assets/39619927/4dc7a9da-149c-4eb3-856e-99182c1dcb89)
![微信图片编辑_20230815013411](https://github.com/jeecgboot/jeecg-boot/assets/39619927/de435533-3e56-4307-a220-fb558a00961d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
看错误，你的配置有问题
