### ISSUE TITLE
MySQL 数据库初始化表名大小写不一致导致的问题

### ISSUE THREAD

**Issue by MagicZer0** [jeecgboot/jeecg-boot#5259]
##### 问题描述：
db/jeecgboot-mysql-5.7.sql：
<img width="1226" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19569793/c2b1ebf1-86e0-4e14-8fc5-6f5dc9f317de">

运行控制台报错：
<img width="1354" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19569793/553a51eb-c246-4722-914e-0c826b661eab">

此外数据库名称中因为包含-，创建数据库会报错。建议修改为下划线(_)。

##### 截图&代码：
见问题描述。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写

**Comment by livizy** [comment]
有没有不设置数据库能解决的方案？
