### ISSUE TITLE
创建了一个系统用户，分配了非管理员角色，登录时报错，

### ISSUE THREAD

**Issue by jhuihan** [jeecgboot/jeecg-boot#5260]
##### 版本号：
 3.5.2（发布日期：2023-06-12

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

创建了一个系统用户，分配了非管理员角色，登录时报错，没有修改系统设置相关的代码，添加上管理员角色就正常了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/126668943/ed9058a4-3e47-4422-ab04-9cada340f2c7)

谷歌报错

![image](https://github.com/jeecgboot/jeecg-boot/assets/126668943/488c2462-b120-41b3-9609-e91a7a067b52)
hu火狐报错

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
测试无问题，你看看你是不是配置了不存在的路由
