### ISSUE TITLE
您好老师，这边看到jeecg官网发布了Freemarker模板注入漏洞的修复方案，请问下此方案是否适用于以前版本的jeecgboot，能否兼容修复，麻烦老师抽空解答，谢谢

### ISSUE THREAD

**Issue by chaojiping1126** [jeecgboot/jeecg-boot#5262]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
很老的够呛兼容，但是你可以尝试升级看看

**Comment by chaojiping1126** [comment]
好的，谢谢张老师

**Comment by zhangdaiscott** [comment]
可以参考方案四
https://my.oschina.net/jeecg/blog/10096283
