### ISSUE TITLE
打印模板页面二维码不显示

### ISSUE THREAD

**Issue by HhZzCcMm1** [jeecgboot/jeecg-boot#5264]
##### 版本号：
jeecg-boot-parent 3.1.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
打印模板页面二维码不显示，前端控制台报错：Uncaught Error: code length overflow. (1684>1056)
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/142368743/e6337764-b2a8-4291-b362-585cf4fabe65)
对应的二维码的解析内容为：H4sIAAAAAAAAAGXLuwrCQBCF4Xc59QqzMzubdbugAQutbESxEhTEeEVThLy7I/FS2J7/Oy02yBhXAyYWCszCynC4IZNDY22+9TGpMnv1Fg7IqxYXZHaoX/l81MaEfdVHTuLRuR4Q9aQK+8nyS0SS/pHdrLhOf2TI8iHyFo/FXUYmhIoUpPAxoFs7nCyVxCWFkm15AlHTgf3PAAAA
但是有比这个二维码解析内容更长的却能生成二维码：H4sIAAAAAAAAAGXQT2vCQBCH4e8y5wiz8ycbcwskSEVRWlrF0oMEFSRFbWhyEL97h6pZief32d/CnKGEFPJiQEiMQsSkAhHUkGIErbW3rYsTVSKnzkIF6ecZTpCq9W/ri2ZTfxixx+piQnZwif6Fu4L5/LX87YCg8h3QbWK2bKbaCeYY+2Ln1qfFg9BOyF1M/c8kiCE9/bKfbarWBKNPhDVx1IkrwGq5HYeJhH1/YvTe5McgfJhgxJup20Jewj2YpL9SxivMgxA/hMtXBAdLGVKGkpHd8A+CGyKomgEAAA==

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
那个功能，详细说明

**Comment by HhZzCcMm1** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/142368743/e0d79e2e-d671-4818-a537-3b6f8b56325b)
就是打印预览的页面中，有一个二维码，二维码没有生成，前端的控制台报出code length overflow错误，但是看其请求接口数据也返回了

**Comment by HhZzCcMm1** [comment]
二维码的生成是根据后端传过来的压缩后的字符串进行创建生成的，然而长的字符串却能生成其二维码，个别短的字符串却没能生成二维码（没生成的前端报错：code length overflow）
![image](https://github.com/jeecgboot/jeecg-boot/assets/142368743/89939699-26a8-4600-9592-18a339053a28)
错误原因是因为js解析时这段代码产生的问题

**Comment by zhangdaiscott** [comment]
升级积木报表到最新，再看
