### ISSUE TITLE
jeecgboot现在没有集成flyway了吗？

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#5265]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
早期的jeecgboot我记得有集成的flyway，还可以通过浏览器的一个地址管理数据库的改动，现在是去掉了吗？

##### 截图&代码：
早期的jeecgboot我记得有集成的flyway，还可以通过浏览器的一个地址管理数据库的改动，现在是去掉了吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没集成，升级脚本，在每个版本里面都提供了
