### ISSUE TITLE
单元格设置为数值格式后，当返回数据为0时，打印页面显示不全

### ISSUE THREAD

**Issue by haishinageni** [jeecgboot/jeecg-boot#5266]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by haishinageni** [comment]
单元格设置为数值格式后，当返回数据为0时，打印页面显示不全

**Comment by zhangdaiscott** [comment]
积木报表的问题
- 积木报表：http://jimureport.com/doc/help
