### ISSUE TITLE
关于升级fastjson2.0.39后不兼容问题

### ISSUE THREAD

**Issue by xy187006** [jeecgboot/jeecg-boot#5267]
##### 版本号：

3.4.4
##### 问题描述：
升级最新fastjson版本2.0.39后缺省SwaggerJsonSerializer导致FeignConfig报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/51348800/f5b40b4b-59c0-47f8-b1a4-95ffa34a0f05)
![image](https://github.com/jeecgboot/jeecg-boot/assets/51348800/ead0eeb4-b2d9-410f-a294-80ccee6fc785)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xy187006** [comment]
建议官方进行升级

**Comment by EightMonth** [comment]
有什么非升不可的理由么

**Comment by zhangdaiscott** [comment]
springboot3版本已经升级完成，接口文档换成了springdoc
https://github.com/jeecgboot/jeecg-boot/tree/springboot3
