### ISSUE TITLE
时间盲注SQL注入绕过

### ISSUE THREAD

**Issue by springkill** [jeecgboot/jeecg-boot#5269]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
sql注入检测模块org.jeecg.common.util.SqlInjectionUtil.checkSqlAnnotation
存在SQL注入绕过

##### 截图&代码：
虽然过滤了sleep字段，但是因为先判断后转大小写，所以还是可以用大写SLEEP绕过：
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/3e8f3317-2624-4b55-93bc-397f06f2d97c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/c86a61fb-60d4-4fcd-a71e-10caf58795de)
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/127ea205-efba-4879-b563-5008a39403ae)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已提交
