### ISSUE TITLE
jeecg存在权限提升漏洞，可直接获得管理员权限

### ISSUE THREAD

**Issue by springkill** [jeecgboot/jeecg-boot#5270]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
权限提升

##### 截图&代码：
创建一个新用户testup，不给任何权限：
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/d484238e-5de2-4e49-bd16-b919b1489aae)
使用testup登录，拿到没权限的token，发送如下数据包拿到admin1组的id和用户id：
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/d2adc121-beb6-40e9-a016-ed84dfad99ea)
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/89cc1da7-eaa0-42ee-8c9b-278ded89f59f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/44d42ab7-5223-45d6-b5a1-997d8bb93995)
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/ab185f09-aa5f-4bd2-b35e-7daa1aef2f66)
用拿到的数据作为内容，发送：
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/51e23f68-01ba-44d4-b312-a6173941e1af)
重新登陆，完成权限提升，后面的手动添加组就行了不用发包：
![image](https://github.com/jeecgboot/jeecg-boot/assets/118535366/74450d5b-e879-4d9b-b149-d68b77702178)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Caisen1988** [comment]
是的，我也遇到了，好像之前的版本都有这个问题，得自己研究一个JWT来解决这个问题

**Comment by zhangdaiscott** [comment]
针对敏感接口加上权限注解，需要授权才能访问
@RequiresPermissions("system:user:list")

![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/b5d2360c-c4fa-497c-8c72-b377ea95c06b)

**Comment by zhangdaiscott** [comment]
把权限注解放开，没有注解的加上

**Comment by zhangdaiscott** [comment]
下次发版本会放开，放开的话，大家配置菜单工作麻烦，所以

**Comment by hacker-routing** [comment]
感谢分享
