### ISSUE TITLE
JVxeTypes.popup 的bug

### ISSUE THREAD

**Issue by jfrong** [jeecgboot/jeecg-boot#5271]
##### 截图&代码：
title: 'JPopup',
      key: 'popup',
      type: JVxeTypes.popup,
      width: 180,
      popupCode: 'demo',
      // field: 'name,sex,age',
      // orgFields: 'name,sex,age',
      // destFields: 'popup,popup_sex,popup_age',
      fieldConfig: [
        { source: 'name', target: 'popup' },
        { source: 'sex', target: 'popup_sex' },
        { source: 'age', target: 'popup_age' },
      ],

弹出的选择界面截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/57884843/768ef372-e34d-41df-bee3-7acef5401b8a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/57884843/ea927a5f-9f9b-4a35-acc1-9f67c67e8139)

原始数据表截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/57884843/cf27fda5-e8ea-4120-ba51-20a618947a84)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
更新到最新，这块有缓存bug，已经修复
