### ISSUE TITLE
jeecg 老版本

### ISSUE THREAD

**Issue by hengguangjie** [jeecgboot/jeecg-boot#5274]
##### 前端版本：vue3版？还是 vue2版？
jsp版本

##### 问题描述：
技术文档图片不显示

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/65932982/14e4f377-3775-4542-b766-7ba612b60117)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
地址

**Comment by hengguangjie** [comment]
http://idoc.jeecg.com/1275919  整个文档图片不显示
