### ISSUE TITLE
后台报错token异常

### ISSUE THREAD

**Issue by Javlgh** [jeecgboot/jeecg-boot#5275]
##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/91462036/4417a236-a1b5-4b5c-96a0-edd7e78a7471)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
redis清一下，前端缓存清一下
