### ISSUE TITLE
nacos如何通过命名空间走不同配置？

### ISSUE THREAD

**Issue by caigaolin** [jeecgboot/jeecg-boot#5279]
##### 版本号：

[jeecg-boot-starter](https://gitee.com/jeecg/jeecg-boot-starter)

##### 前端版本：vue3版？还是 vue2版？
无
##### 问题描述：

这个项目如何部署?nacos配置中没有看到命名空间的的地方，多个服务用的都是一个nacos根据命名空间走的不同配置，咱们这个如何设置？

##### 截图&代码：

无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/d8848687-257d-49e8-9a93-8dd2da0e58d6)

nacos创建对应的命名空间，命名空间下创建对应配置文件

**Comment by caigaolin** [comment]
好的，感谢指导
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月18日 11:54 |
| 收件人 | jeecgboot/jeecg-boot ***@***.***> |
| 抄送人 | caigaolin ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] nacos如何通过命名空间走不同配置？ (Issue #5279) |

nacos创建对应的命名空间，命名空间下创建对应配置文件
