### ISSUE TITLE
下拉单选

### ISSUE THREAD

**Issue by cw0301** [jeecgboot/jeecg-boot#5283]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
下拉单选不想使用字典的数据如何操作呢？并且想使用下拉单选的change事件如何监听？
##### 截图&代码：
无

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题很基础，自己研究下代码就可以了
