### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by nashuang123** [jeecgboot/jeecg-boot#5287]
版本号：3.5.1
前端版本：vue3版
问题描述：本地启动正常 部署到生产环境报错
截图&代码:
image

**Comment by nashuang123** [comment]
版本号：3.5.1
前端版本：vue3版
问题描述：本地启动正常 部署到生产环境报错
截图&代码:
![image](https://github.com/jeecgboot/jeecg-boot/assets/32831079/7cebaa36-ecde-401c-bf5e-9beaa0176895)

**Comment by zhangdaiscott** [comment]
环境问题，具体不清楚
