### ISSUE TITLE
需求建议：在Online在线开发中，已有数据库的情况下，实现连接多个第3方数据源，生成表单，能增删查改

### ISSUE THREAD

**Issue by ahshTao** [jeecgboot/jeecg-boot#5291]
##### 问题描述：在Online在线开发中，已有数据库的情况下，实现连接多个第3方数据源，生成表单，能增删查改。类似online表单开发和online报表配置的综合功能。
不需要迁移已有数据库和表，数据内容还是存放在原数据库中，中间过程可存放jeecgboot默认数据库。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持

**Comment by heyes-yang** [comment]
强烈希望能提供该功能支持！！！
