### ISSUE TITLE
在线生成代码权限问题

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecg-boot#5292]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线生成的代码会强制将按钮部分的权限强制加入后台代码中，并且在配置玩角色权限后依旧显示没有权限

##### 截图&代码：
![1692696136108](https://github.com/jeecgboot/jeecg-boot/assets/71683167/2043ad30-6754-493d-af5e-a98796af9f4b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
推出重新登录
