### ISSUE TITLE
代码生成一对多，选择的erp风格页面选择vue3原生但是生成出来的还是vue3

### ISSUE THREAD

**Issue by lishuanghe214** [jeecgboot/jeecg-boot#5294]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
代码生成一对多，选择的erp风格页面选择vue3原生但是生成出来的还是vue3

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/72898445/170ef419-3abd-4410-be5c-6736e40b1c79)

![image](https://github.com/jeecgboot/jeecg-boot/assets/72898445/a2576573-db64-46a2-afea-aa3f649d0743)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue3有什么问题？

**Comment by lishuanghe214** [comment]
> vue3有什么问题？

就行官网说的一样区别，vue3想更改表单的布局是没有原生方便的，比如我想设置一个分割线，我想设置表格站位等

**Comment by zhangdaiscott** [comment]
ERP风格目前没有提供原生表单方式，可以自己先改造下

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
