### ISSUE TITLE
用户配置多租户后，登录后点击切换部门按钮，报错

### ISSUE THREAD

**Issue by SherryOfLF** [jeecgboot/jeecg-boot#5298]
##### 前端版本：vue3版？还是 vue2版？
VUE3版

##### 问题描述：
给某个用户配置多租户后，登录后点击切换部门按钮，报错，后端缺少API 
getCurrentUserTenants = '/sys/tenant/getCurrentUserTenant'

##### 截图&代码：

从之前3.5.0版本扒了代码

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
提交了
