### ISSUE TITLE
修改表单弹窗名称与菜单对应

### ISSUE THREAD

**Issue by Qinjialiang** [jeecgboot/jeecg-boot#5299]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
如何将弹窗的名称改为与菜单名称对应，例如下图的弹窗名称由新增改为 制令单新增

##### 截图&代码：
![2KJZ@}$}L@Z0WDT{Y(~6WWR](https://github.com/jeecgboot/jeecg-boot/assets/116338746/94da8b89-4b41-4eaa-beef-71c07f06f4a2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化需求，请自己二开
