### ISSUE TITLE
表单默认值带不出来

### ISSUE THREAD

**Issue by cdbmfrcjj** [jeecgboot/jeecg-boot#5304]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
代码生成原生vue3，表单默认值带不出来，非原生和online都没问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布
