### ISSUE TITLE
JVxeColumn ，type: JVxeTypes.select  无法按照预期进行搜索

### ISSUE THREAD

**Issue by leophs** [jeecgboot/jeecg-boot#5305]
##### 版本号：
v3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
JVxeColumn ：type: JVxeTypes.select 
该类型下进行搜索无法通过text进行搜索，反而出现通过value进行搜索

##### 截图&代码：
1：![image](https://github.com/jeecgboot/jeecg-boot/assets/103886298/b7dc086e-aa7b-4fc4-a182-ff2ceae58558)
2：![image](https://github.com/jeecgboot/jeecg-boot/assets/103886298/caa3c74e-a43a-443b-bd18-79446313639c)
3：![image](https://github.com/jeecgboot/jeecg-boot/assets/103886298/f433c168-6fe0-4446-b604-a51c740392a1)
4：![image](https://github.com/jeecgboot/jeecg-boot/assets/103886298/629359d4-58eb-4d32-8b9b-3aafac31df01)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by leophs** [comment]
> 刘
什么意思呢？

**Comment by leophs** [comment]
在 vue3 在线演示 系统管理-用户管理-编辑 -租户 下拉框中可复现该bug

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
