### ISSUE TITLE
JVxeTypes.userSelect选择用户界面卡死

### ISSUE THREAD

**Issue by guocong3425** [jeecgboot/jeecg-boot#5307]
##### 问题描述：
子表单type为JVxeTypes.userSelect选择用户后，再次点击选择用户弹窗后界面卡死，代码是使用Online表单开发中的主子表代码生成出来的，主题是默认主题

##### 截图&代码：
![H03WPPQ2FUJE)( JGQ6RI~A](https://github.com/jeecgboot/jeecg-boot/assets/50916091/f16618db-8d0c-419d-bf3b-7e842428231b)
<img width="415" alt="20230824173719" src="https://github.com/jeecgboot/jeecg-boot/assets/50916091/d88df968-c176-4ae2-9f1d-05ef19317943">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
此组件的性能问题已经提了，你更新到最新看看是否还存在问题

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/687
