### ISSUE TITLE
在线开发=》功能测试=>无权限访问操作

### ISSUE THREAD

**Issue by Gq66** [jeecgboot/jeecg-boot#5309]
##### 版本号：
最新

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
按照网上说的删掉这个在线生成代码组件后，减少首页加载时间。恢复后，为什么点完这个会说无权限访问呢

##### 截图&代码：
![TNL%)}D ZGKX3 I8O3C8}GH](https://github.com/jeecgboot/jeecg-boot/assets/67729007/e909200a-eef6-4070-94ee-4307eb0ffab2)

![9O6(44HG0ZS}ILHVP3}XBKX](https://github.com/jeecgboot/jeecg-boot/assets/67729007/0beccf69-108d-4664-880e-f55bbfd8c79f)

![M W`Y$87OKUNBNS}`%)I803](https://github.com/jeecgboot/jeecg-boot/assets/67729007/0c5a508a-e272-43c5-9a89-8654e457e961)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Gq66** [comment]
hello~有人在不~
![image](https://github.com/jeecgboot/jeecg-boot/assets/67729007/42f0605d-b7a4-4418-ac42-4d4f7cc91ece)

**Comment by Gq66** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/67729007/812bc66a-6241-4bac-b7d2-7dfee88e3f1a)

**Comment by zhangdaiscott** [comment]
你自己改了什么，还原
