### ISSUE TITLE
QueryGenerator initQueryWrapper 未授权下报空指针异常

### ISSUE THREAD

**Issue by wuwu955** [jeecgboot/jeecg-boot#5314]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
 定时任务位授权 调用service 方法 中QueryGenerator initQueryWrappe 报空指针异常

##### 截图&代码：
<img width="1051" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/26872462/b9517676-9963-4abd-bc51-4b3c4264bb83">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你自己try catch吧，应该你有逻辑调用了此处
