### ISSUE TITLE
数据Web埋点

### ISSUE THREAD

**Issue by Leevampire** [jeecgboot/jeecg-boot#5315]
##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
请问能够提供插件网页埋点，需要做用户信息采集。做网页访问量分析、流量分析等

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化的自己搞吧
