### ISSUE TITLE
启动Nacos报错

### ISSUE THREAD

**Issue by cwf404** [jeecgboot/jeecg-boot#5316]
A fatal error has been detected by the Java Runtime Environment:

 EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d) at pc=0x00007ffea08203a9, pid=144600, tid=0x0000000000005398

 JRE version: Java(TM) SE Runtime Environment (8.0_202-b08) (build 1.8.0_202-b08)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.202-b08 mixed mode windows-amd64 compressed oops)
 Problematic frame:
 C  [librocksdbjni7145777911216708172.dll+0x5203a9]

 Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

 An error report file with more information is saved as:
 D:\yun\geta\jeecg-boot-master\hs_err_pid144600.log
Compiled method (c1)   19422 4420       1       java.util.concurrent.ConcurrentHashMap$MapEntry::<init> (20 bytes)
 total in heap  [0x0000000003ffffd0,0x00000000040002b0] = 736
 relocation     [0x00000000040000f0,0x0000000004000118] = 40
 main code      [0x0000000004000120,0x00000000040001e0] = 192
 stub code      [0x00000000040001e0,0x0000000004000270] = 144
 metadata       [0x0000000004000270,0x0000000004000280] = 16
 scopes data    [0x0000000004000280,0x0000000004000288] = 8
 scopes pcs     [0x0000000004000288,0x00000000040002a8] = 32
 dependencies   [0x00000000040002a8,0x00000000040002b0] = 8

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

Disconnected from the target VM, address: '127.0.0.1:49920', transport: 'socket'

**Comment by zhangdaiscott** [comment]
自己百度吧，你的环境问题
https://blog.csdn.net/hale_hale/article/details/117735122
