### ISSUE TITLE
对下拉框类型的唯一性校验无效

### ISSUE THREAD

**Issue by sundayha** [jeecgboot/jeecg-boot#5317]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
页面属性是下拉框，校验字段为唯一校验。下拉框采用字典table的形式获取下拉框的数据。新增数据时没有进行唯一性校验。也没有调用 /sys/duplicate/check 这个接口 

##### 截图&代码：

<img width="1171" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/13161708/1b55a414-3d46-44ed-ba6d-43192a4465e8">
<img width="1296" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/13161708/b10a7b41-4e40-4945-a3f4-d9b6c04fd9bb">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
唯一校验只支持输入框

**Comment by sundayha** [comment]
> 唯一校验只支持输入框

ok
