### ISSUE TITLE
字典 多选框

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#5318]
##### 问题描述：字典（数据源+表名） 下拉多选 
在线表单配置
页面属性 ：下拉多选

前端部署在服务器使用时：下拉框正常   下拉多选框 报错

前端本地运行启动使用时：下拉框选择正常，下拉多选正常

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/7f2bf9a5-c82e-4065-919f-cf1833d440bd)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/c1bc800b-3763-4cf0-8938-48bfec703909)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/fa0ff8c9-6a03-4c51-999f-8c3833c0c7c0)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/31c2d728-3b30-448e-91ad-1064d04cb9f9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个怎么重现？错误日志提供下

**Comment by hutianxi** [comment]
重现前端打包放nginx中代理到网关  配置在线表单  使用（`数据源`+表名) （`test`.tags,tags,id）下拉多选 测试
网关报错

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/8fa68efa-28b3-40be-a0c8-990eac26a7a0)

nginx 400

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/ba707509-f51a-4afc-8e80-bb14f138cb73)

APIfox 测试 直接访问网获取字典

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/b5a86cf7-6cc9-423e-a95c-ea511a458bc4)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/14b0adbe-5ef8-402e-bda1-b2a461ca9ac2)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/eb90e7e5-cdd7-452e-8325-badd5414eece)

通过nginx发起访问

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/fd09f14f-28ad-4a76-945d-573714212e8b)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/2b7cbcdf-c3b6-4f19-8f14-60fa85f4e215)

nginx配置

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/245c6945-8d97-4c58-b5a4-760fea14f998)

本地启动前端采用 （数据源+表名) （`test`.tags,tags,id）下拉多选 单选 测试 正常

**Comment by hutianxi** [comment]
我的解决方式是
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/1091cdff-673f-4b6d-871b-18c9854fbb99)
把GET请求换成POST 通过nginx转发到访问过去没问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/fc193594-e8cf-4123-ab80-7f9ac831863c)

**Comment by zhangdaiscott** [comment]
什么问题导致的？

**Comment by hutianxi** [comment]
现在的情况我不太清楚是不是nginx代理那边的问题  但是现在我使用了POST 前端发请求过来给我说  sign签名校验失败!
<img width="187" alt="337b821223562d46c171ae5f8983b1d" src="https://github.com/jeecgboot/jeecg-boot/assets/67693982/6dd0b92b-dd6d-427e-9d48-3e40afe9ccf1">
然后我测试的时候是直接把判断改成true了的现在这边我拿着前端给我的Sign 校验和我算出来的不一样 不知道是不是前端加密方式不对
![375596d6e120040c0a633d5285d3068](https://github.com/jeecgboot/jeecg-boot/assets/67693982/c61c833c-32a4-481c-93ac-e6c6df227f5f)

**Comment by zhangdaiscott** [comment]
确认下nginx header设置

**Comment by hutianxi** [comment]
我就是按照给的文档直接写上去的  nginx  我不太懂
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/74eddfc2-67cd-4f29-b2de-bd7aa8c2cb14)
