### ISSUE TITLE
3.5.3_vue3 redis 远程主机强迫关闭了一个现有的连接的提示

### ISSUE THREAD

**Issue by chengwei1104** [jeecgboot/jeecg-boot#5319]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
只要前段访问功能，后台就答应redis重连的错误，很频繁，远程主机强迫关闭了一个现有的连接的提示

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8801177/27750c99-850c-4b10-9356-b0afef52619d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
无法复现问题，单方面认为该问题不存在，该问题如果存在，严重级别属于P0，或已修复或为本地原因，建议检查redis及本地运行情况以及配置。
