### ISSUE TITLE
单体下单库分表失败

### ISSUE THREAD

**Issue by lzz2017** [jeecgboot/jeecg-boot#5320]
##### 截图&代码：
配置如下：
![1693271479757](https://github.com/jeecgboot/jeecg-boot/assets/28996304/1067f368-8a21-4b79-bb7d-ac6946a1fc1f)
自定义规则代码模块：
![image](https://github.com/jeecgboot/jeecg-boot/assets/28996304/6e473647-ce06-44e3-8e5d-9c6a017e89dc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
无法复现问题，建议提供代码协助排查

**Comment by zhangdaiscott** [comment]
sq
