### ISSUE TITLE
 oracle数据，online表单中的 “关联记录” 功能模块BUG

### ISSUE THREAD

**Issue by 78739749haiyang** [jeecgboot/jeecg-boot#5321]
##### 问题描述：
oracle数据由于默认数据库字段都为大写。
使用 online表单中的 “关联记录” 功能模块时，使用 “页面属性”中的“高级配置”完后，在“校验字段”中字典code和字典text默认都是小写。这样生成后的表单，显示列表不会展示。

##### 截图&代码：
![GMM40UV`QU33G~ZB4``G05P](https://github.com/jeecgboot/jeecg-boot/assets/98626116/359b4508-2fed-46eb-a00b-3e5ae8d69fc5)

![`}P_JIIX0}%A677OM `4VKD](https://github.com/jeecgboot/jeecg-boot/assets/98626116/be08ba98-5a2f-468c-8328-9dc0365ae090)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图看生成的代码

**Comment by 78739749haiyang** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/98626116/3a0956e0-52ef-4892-b6df-a20b874dceed)

**Comment by zhangdaiscott** [comment]
代码生成后，手工调整代码吧，因为这个做不到兼容

**Comment by zhangdaiscott** [comment]
scott

**Comment by sjlei** [comment]
问题已修复，下版本发布
