### ISSUE TITLE
vue3代码拉取下来运行成功后，不会跳转到登录页面，浏览器报错tinymce is not defined

### ISSUE THREAD

**Issue by XiuXinJ** [jeecgboot/jeecg-boot#5323]
##### 截图&代码：

![微信图片_20230829175740](https://github.com/jeecgboot/jeecg-boot/assets/50459372/b0491d3f-ce4e-43de-9718-4b1e452b6ef6)
![微信图片_20230829123404](https://github.com/jeecgboot/jeecg-boot/assets/50459372/0a884c05-7a4e-4826-b192-ef82c45c8ac5)

**Comment by zhangdaiscott** [comment]
用的那个启动命令，说下重现步骤

**Comment by zhangdaiscott** [comment]
最新版没有这个命令，你是下载的那个版本？
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/92c7898e-a73b-4f3d-ac4d-49a47d28e697)

**Comment by zhangdaiscott** [comment]
你下载的代码有问题，不是最新的，你是从哪个地址下载的

**Comment by zhangdaiscott** [comment]
你不会是通过CSDN的加速下载的吧？？
```
https://gitcode.net/mirrors/jeecgboot/jeecgboot-vue3
```

**Comment by XiuXinJ** [comment]
这个不是你们的官网吗？我就从这里点进去拉取的呀-------- 原始邮件 --------发件人： JEECG ***@***.***>日期： 2023年8月29日周二 19:25收件人： jeecgboot/jeecg-boot ***@***.***>抄送： XiuXinJ ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/jeecg-boot] vue3代码拉取下来运行成功后，不会跳转到登录页面，浏览器报错tinymce is not defined (Issue #5323)
你下载的代码有问题，不是最新的，你是从哪个地址下载的

**Comment by zhangdaiscott** [comment]
这是cdn加速有问题

**Comment by zhangdaiscott** [comment]
保险期间通过
https://gitee.com/jeecg/jeecgboot-vue3

**Comment by Raspberry-souffle01** [comment]
版本3.5.3，遇到同样问题了，代码都是github下的，老哥解决了吗？
![image](https://github.com/jeecgboot/jeecg-boot/assets/73213361/476a3747-3894-40a4-9081-0201974feb66)
