### ISSUE TITLE
router.addRoutes(store.getters.addRouters) 不会替换路由菜单

### ISSUE THREAD

**Issue by qfzc** [jeecgboot/jeecg-boot#5324]
##### 问题描述：
我的需求是，点击不同的按钮，进行左边菜单的切换，使用原生的Vue-Route，router.addRoutes(store.getters.addRouters) 会切换菜单，但是在jeecg-boot中不会生效，求助大佬

##### 截图&代码：
<img width="705" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/7496918/6e2380a0-e7f9-404b-8781-ab640d9ee8db">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
个性化的自己深度二开就行
