### ISSUE TITLE
租户管理的问题

### ISSUE THREAD

**Issue by xuhc-x** [jeecgboot/jeecg-boot#5325]
##### 版本号：

3.5.3
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
开启SaaS多租户模式，租户用户页面提示“网络请求错误,未找到该资源!”；
点击租户的用户按钮，也是提示“网络请求错误,未找到该资源!”；
已经是admin的账号了，角色授权里所有权限都授权了，为什么点击租户--套餐 提示“没有权限，请联系管理员授权”？
（ 只是把org.jeecg.config.mybatis.MybatisPlusSaasConfig#OPEN_SYSTEM_TENANT_CONTROL 改成 true，其他源码也没去动过）
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/ae1e360b-1eb8-4d51-83ab-85f5684da933)
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/0435f1b9-f3e0-483f-a0ec-cfae7498d63a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/027ee0c1-ccd7-416c-9d6b-f2d31b50f462)
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/8bf459a0-dc2b-45ee-b7f5-4ee02cf3a826)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xuhc-x** [comment]
更新代码了，但是点击套餐还是提示“没有权限，请联系管理员授权”，管理员已经都已经授权了
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/21cbf89d-0216-4b42-80f4-22d4d1e8fc67)
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/34e6cfc5-32e9-4c6e-82c9-94432fec2b2b)
![image](https://github.com/jeecgboot/jeecg-boot/assets/61675222/f3856c23-aeb9-4303-bd6b-22a83abe7da5)

**Comment by zhangdaiscott** [comment]
授权后，退出重新登录了吗

**Comment by xuhc-x** [comment]
可以了，刚才授权后没有退出登录
