### ISSUE TITLE
生成的前端代码处理树形结构的时候有些问题

### ISSUE THREAD

**Issue by zhaoFenG8917** [jeecgboot/jeecg-boot#5326]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
处理树形结构的时候  componentProps: 字段显示不全，只显示了 
   componentProps:{
        dict: '',
        pidValue: '',
    },

为什么 dict：，pidField：，hasChildField：只能三选一？

其实也需要
pidField：
hasChildField：

##### 截图&代码：
${entityName}__data.tsi 模版其中

  <#elseif po.classType == 'sel_tree'>
    component: 'JTreeSelect',
    componentProps:{
        <#if po.dictText??>
          <#if po.dictText?split(',')[2]?? && po.dictText?split(',')[0]??>
            dict:"${po.dictTable},${po.dictText?split(',')[2]},${po.dictText?split(',')[0]}",
          <#else if po.dictText?split(',')[1]??>
            pidField:"${po.dictText?split(',')[1]}",
          <#else if po.dictText?split(',')[3]??>
            hasChildField:"${po.dictText?split(',')[3]}",
          </#if>
        </#if>
        pidValue:"${po.dictField}",
    },
   <#else>

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请配合截图说明

**Comment by zhaoFenG8917** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhaoFenG8917** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
