### ISSUE TITLE
JUpload组件returnUrl为false时上传的字段值返回了一个'[object Object]'

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5327]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/d184c632-e443-4816-9975-c083c469b299)
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/bc28773b-6e0a-47d2-915e-1ab67626325b)

**Comment by zhangdaiscott** [comment]
sq

**Comment by RacingK93** [comment]
> 

大佬sq是啥意思？

**Comment by facedark** [comment]
建议放弃JEECG的组件。 组件过多的封装并且BUG居多   过渡的封装只会加大耦合度。你这个组件完全可以使用官方的element的el-upload来替代。并且有完整的示例

**Comment by RacingK93** [comment]
> 建议放弃JEECG的组件。 组件过多的封装并且BUG居多 过渡的封装只会加大耦合度。你这个组件完全可以使用官方的element的el-upload来替代。并且有完整的示例

就是用上jeecg了，用的antdv，不用element，主要官方这个组件目前就这个问题，官方解决掉就完美了。

**Comment by lsqGitHub716** [comment]
已修改，下版本发布
