### ISSUE TITLE
在使用在线表单开发时会出现sys.api.errMsg404错误

### ISSUE THREAD

**Issue by gxx3000** [jeecgboot/jeecg-boot#5330]
##### 版本号：
Jeecg  Boot Version: 3.5.3

##### 问题描述：
在使用Online表单开发时会出现sys.api.errMsg404错误，

##### 截图&代码：

![20230830161003](https://github.com/jeecgboot/jeecg-boot/assets/44794996/f80524e4-ca36-4881-81cc-0d71742f7c21)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
测试没有问题，你是什么时间下载的版本？
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/b2f03fb1-9890-4bc8-8067-1bf3d52a2def)
