### ISSUE TITLE
网关路由配置问题

### ISSUE THREAD

**Issue by Chenzhexian** [jeecgboot/jeecg-boot#5331]
#####版本号： 3.5.3

#####前端版本：vue3版

#####问题描述：
网关路由配置时，如果前端添加了相同name的路由条件，就会出现配置失效的问题。(经过测试，添加多个相同的路由条件，最后一个会生效其他都会失效),

##### 截图&代码：
具体可以看pull requests 的第一个

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
sq

**Comment by Chenzhexian** [comment]
UPDATE
    sys_gateway_route 
SET
    router_id = '1597493163487543297',
    name = {},
    uri = {},
    predicates = {},
    filters = {},
    status = {},
    create_by = {},
    create_time = {} 
WHERE
    id = {};
    
==>  Preparing: UPDATE sys_gateway_route SET router_id = ?, name = ?, uri = ?, predicates = ?, filters = ?, status = ?, create_by = ?, create_time = ? WHERE id = ?
==> Parameters: jeecg-rcm(String), jeecg-rcm(String), lb://jeecg-rcm(String), [{"args":["/rcm/**","/daily/**","/franchise/**","/qrcompany/**","/store/**"],"name":"Path"},{"args":["/czx"],"name":"Path"}](String), [](String), 1(Integer), admin(String), 2022-11-29 15:30:25.0(Timestamp), 1597493163487543297(String)

**Comment by Chenzhexian** [comment]
更新时会多加一个  {"args":["/czx"],"name":"Path"},这样就导致前一个失效
可以看看我提交的pull requests是否可以解决这个问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/92191856/ae3b0779-35d7-4581-91c3-8bde3298bbd4)

**Comment by Chenzhexian** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/92191856/7077bbef-d1b3-498e-9fee-a74e3612c64d)

**Comment by lsqGitHub716** [comment]
已修改
