### ISSUE TITLE
积木报表打印预览内容多个学生信息重复

### ISSUE THREAD

**Issue by zhoucod** [jeecgboot/jeecg-boot#5332]
##### 问题描述：
积木报表打印预览部分，学生1信息数据正常，但是从学生2开始到最后一个学生的信息都会与学生1的信息数据重复

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/143678029/fce0ebdd-bd4b-4d76-8206-7ddba4e57c88)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhoucod** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/143678029/d741f1f8-caa2-4a0e-8ded-decc4e160fd2)

**Comment by zhangdaiscott** [comment]
- JimuReport: https://github.com/jeecgboot/JimuReport/issues/new
