### ISSUE TITLE
你好！请问仪表盘设计是不是商业组件，价格是多少？

### ISSUE THREAD

**Issue by linzym** [jeecgboot/jeecg-boot#5338]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
开源版有仪表盘，可以免费用

**Comment by linzym** [comment]
谢谢！
