### ISSUE TITLE
部门管理下部门赋权代码逻辑缺少判断条件

### ISSUE THREAD

**Issue by zhaohao007** [jeecgboot/jeecg-boot#5339]
##### 问题描述：
部门管理——>部门赋权——>修改保存部门权限。src/main/java/org/jeecg/modules/systemrvice/impl/SysDepartPermissionServiceImpl.java  第63行。这段代码是不是有问题，我们在线上复现。场景：A部门和B部门，如果同时有权限Z，当我取消A部门的权限Z的时候，B部门也被自动勾选掉。代码63行再删除权限的时候，没有添加对应角色或者部门的条件限制，直接删除了系统内包含此权限的所有部门角色权限关联关系。

##### 截图&代码：

![OP_VZC6URP~ @ZC{J(3QF6J](https://github.com/jeecgboot/jeecg-boot/assets/7615815/b4f41f7f-de3c-441b-942b-95314fbbc597)

`    

    public void saveDepartPermission(String departId, String permissionIds, String lastPermissionIds) {
        List<String> add = getDiff(lastPermissionIds,permissionIds);
        if(add!=null && add.size()>0) {
            List<SysDepartPermission> list = new ArrayList<SysDepartPermission>();
            for (String p : add) {
                if(oConvertUtils.isNotEmpty(p)) {
                    SysDepartPermission rolepms = new SysDepartPermission(departId, p);
                    list.add(rolepms);
                }
            }
            this.saveBatch(list);
        }
        List<String> delete = getDiff(permissionIds,lastPermissionIds);
        if(delete!=null && delete.size()>0) {
            for (String permissionId : delete) {
                this.remove(new QueryWrapper<SysDepartPermission>().lambda().eq(SysDepartPermission::getDepartId, departId).eq(SysDepartPermission::getPermissionId, permissionId));
                //删除部门权限时，删除部门角色中已授权的权限
                List<SysDepartRole> sysDepartRoleList = sysDepartRoleMapper.selectList(new LambdaQueryWrapper<SysDepartRole>().eq(SysDepartRole::getDepartId,departId));
                List<String> roleIds = sysDepartRoleList.stream().map(SysDepartRole::getId).collect(Collectors.toList());
                if(roleIds != null && roleIds.size()>0){
                    departRolePermissionMapper.delete(new LambdaQueryWrapper<SysDepartRolePermission>().eq(SysDepartRolePermission::getPermissionId,permissionId));
                }
            }
        }
    }
`

**Comment by zhangdaiscott** [comment]
scott

**Comment by lsqGitHub716** [comment]
按照你的测试步骤未复现你说的情况，能够详细说明一下你的操作步骤或者录制一个复现的gif动图或者视频

**Comment by lsqGitHub716** [comment]
已修改
