### ISSUE TITLE
菜单怎么配置页面跳转打开浏览器新标签页面？

### ISSUE THREAD

**Issue by 01-jiang** [jeecgboot/jeecg-boot#5340]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
jeecgboot-vue3-maste

菜单怎么配置页面跳转打开浏览器新标签页面？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 01-jiang** [comment]
不是后台路径页面，是前台已经写好的页面，正常配置内部打开没问题。设置外部打开后，打开新标签页面后有重定向到了首页

**Comment by bantu4me** [comment]
> 不是后台路径页面，是前台已经写好的页面，正常配置内部打开没问题。设置外部打开后，打开新标签页面后有重定向到了首页

你好，请问下找到解决方式了吗？我之前用vue2版本是可以配置的，但是vue3我试了文档的配置也没有起作用

**Comment by zhangdaiscott** [comment]
下载最新版看看
