### ISSUE TITLE
在线开发这个菜单隐藏不掉

### ISSUE THREAD

**Issue by LiangYongAI** [jeecgboot/jeecg-boot#5341]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2 3.4.3

##### 问题描述：
想把在线开发这个菜单隐藏掉不显示，在角色授权里面把在线开发这个菜单及子菜单都不勾选，然后刷新后，发现界面左侧的在线开发这个菜单还是存在，但是在线开发的子菜单没有了。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/15886620/fea029b8-c38b-47c0-98e8-d990c568a292)

**Comment by zhangdaiscott** [comment]
自己改造下后台菜单加载逻辑，或者升级到对应版本，应该处理过了
