### ISSUE TITLE
通用的查询过滤器问题  

### ISSUE THREAD

**Issue by 17732150827** [jeecgboot/jeecg-boot#5342]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

后端问题 
1.通用的查询过滤器问题  
  -- 包含查询问题 ：对于实体类中的Integer类型的字段进行包含查询的时候 传递参数进行查询导致报错，报错如（截图&代码）
包含查询的规则为：
包含查询：查询数据格式采用逗号分隔：{ , }
例如：
格式：  张三,李四  
       (含义：In('张三','李四'))                             

以上包含查询对于字符型的字段查询 没有问题  但是数值型的就存在查询问题   例如 查询的字段 为 orderStatusDic 数值型 我想查询 数值包含8和9的  我传递参数为 8，9  到后端接收参数的时候直接报错 报错如下 

##### 截图&代码：
操作失败，org.springframework.validation.BeanPropertyBindingResult: 1 errors\nField error in object 'guaranteeOrder' on field 'orderStatusDic': rejected value [8,9]; codes [typeMismatch.guaranteeOrder.orderStatusDic,typeMismatch.orderStatusDic,typeMismatch.java.lang.Integer,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [guaranteeOrder.orderStatusDic,orderStatusDic]; arguments []; default message [orderStatusDic]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'orderStatusDic'; nested exception is java.lang.NumberFormatException: For input string: \"8,9\"]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个报错是接受参数就报错了，还没到查询过滤器逻辑
