### ISSUE TITLE
jeecg-cloud-gateway模块中#Sentinel配置缩进问题

### ISSUE THREAD

**Issue by GuZhi-0114** [jeecgboot/jeecg-boot#5343]
##### 版本号：
v3.5.1last

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
jeecg-cloud-gateway模块中#Sentinel配置缩进问题，导致启动时WARN：converter can not convert rules because source is empty，导致前端启动后访问提示功能404

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/138742970/5c1afa50-db85-4326-a11d-fe43146ae57c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by GuZhi-0114** [comment]
改为这样启动正常![image](https://github.com/jeecgboot/jeecg-boot/assets/138742970/80d4ce96-9ab2-4c21-aa31-b8306d2e81d3)

**Comment by zhangdaiscott** [comment]
这样改不对
