### ISSUE TITLE
表单中的ApiTreeSelect组件设置多选，选择多个值时input框中只显示一个值

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5345]
##### 截图&代码：
{
    field: 'orgIdList',
    label: '选择机构',
    component: 'ApiTreeSelect',
    show: false,
    componentProps: ({ formModel, formActionType }) => {
      return {
        api: orgTreelist,
        params: { id: roleId.value },
        labelField: 'title',
        valueField: 'id',
        multiple: true,
        getPopupContainer: (node) => document.body,
      };
    },
  },

**Comment by RacingK93** [comment]
并且发现使用多勾选时，我需要拦截数据自处理才能对数据使用，不然多勾选然后的字段都是[object,object]这种形式

**Comment by zhangdaiscott** [comment]
sq

**Comment by liaozhiyang** [comment]
<img width="630" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/714e0e1c-537e-4f4e-9ab8-055cea3303e8">
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/e898f04f-1c37-4fe6-9403-bf68fc732225)
import { treeOptionsListApi } from '/@/api/demo/tree';   项目中的mock数据

经测试没发现你所说的情况，你可以把以上代码放在src/views/demo/jeecg/jeecgComponents.data.ts（自定义组件示例）中测试下，看是否正常。

**Comment by liaozhiyang** [comment]
页面效果：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/4a0abc64-007b-4b9e-8b9f-1303a4572854)
测试代码：
<img width="839" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/317bfec6-9ae5-4555-a299-2ffe311f95e0">

import { treeOptionsListApi } from '/@/api/demo/tree';   项目中的mock数据
经测试没发现你所说的情况，你可以把以上代码放在src/views/demo/jeecg/jeecgComponents.data.ts（自定义组件示例）中测试下，看是否正常。
