### ISSUE TITLE
请问jeecgboot2.4.6也存在此漏洞吗？请问如何测试已修正完毕呢？

### ISSUE THREAD

**Issue by lntlky7** [jeecgboot/jeecg-boot#5346]
##### 问题描述：
---重构表字典逻辑，深度解决SQL注入漏洞问题，新旧版本都可以参考此修改合并---

9月5日发布的jeecgboot的漏洞问题，重构表字典逻辑，请问这个漏洞影响到哪个接口，如何验证已修复完毕。
我们用的jeecgboot2.4.6版本，也存在这个漏洞吗？请问如何验证？
重构表字典逻辑的代码我看了一下，有些类在2.4.6中不存在，请问是不是只处理存在的类就可以了？
期望答复，谢谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
老版本都存在

已经处理过（JEECG SQL漏洞）
https://github.com/jeecgboot/jeecg-boot/issues/4983
https://github.com/jeecgboot/jeecg-boot/issues/5134
https://github.com/jeecgboot/jeecg-boot/issues/5150
https://github.com/jeecgboot/jeecg-boot/issues/5173
https://github.com/jeecgboot/jeecg-boot/issues/5268
https://github.com/jeecgboot/jeecg-boot/issues/5269
https://github.com/jeecgboot/jeecg-boot/issues/5296
https://github.com/jeecgboot/jeecg-boot/issues/4393
https://github.com/jeecgboot/jeecg-boot/issues/4162
https://github.com/jeecgboot/jeecg-boot/issues/4129
https://github.com/jeecgboot/jeecg-boot/issues/4127
https://github.com/jeecgboot/jeecg-boot/issues/3905
https://github.com/jeecgboot/jeecg-boot/issues/3300
