### ISSUE TITLE
shardingsphere和多数据源冲突

### ISSUE THREAD

**Issue by yimogithub** [jeecgboot/jeecg-boot#5347]
##### 版本号：
3.0

##### 问题描述：

shardingsphere和多数据源冲突，配置shardingsphere后还需要配置@DS("sharding")才生效。

有没有办法去掉多数据源，直接全部按shardingsphere配置生效，

因为实际业务中，部分代码被不方便加上@DS("sharding")。

或者提供不需要配置@DS("sharding")的方案也行

**Comment by zhangdaiscott** [comment]
版本号多少？

**Comment by yimogithub** [comment]
> 版本号多少？

3.0.0版本

**Comment by EightMonth** [comment]
建议升至最新版本看问题是否依旧存在

**Comment by EightMonth** [comment]
如果想要不需要指定@DS注解特指数据源，可以使用spring.datasource.dynamic.primary指定默认数据源，也可以不需要添加@ds注解
