### ISSUE TITLE
在仪表盘的数据设置，在websoket选项上操作一直没对呢，下面的输入框也是sql的，亲，这块我看官方文档上写的这么搞，是不是这个模块还没上线的，亲

### ISSUE THREAD

**Issue by webmonsters** [jeecgboot/jeecg-boot#5348]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请图文并茂
