### ISSUE TITLE
online 在线表单 一对多 代码生成   通过docker 打包发布后 功能失效

### ISSUE THREAD

**Issue by zhoulel** [jeecgboot/jeecg-boot#5353]
##### 版本号：
 v3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online 在线表单 一对多 代码生成后 通过dockerfile 打包发布docker 后  新增和编辑按钮失效 子表的 暂无数据还错行  ，本地 vscode没有问题 但是打包发布有问题

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/71f09ce9-767a-4cbe-860f-389ddf01c6d9)

按钮失效问题 以及 子表“暂无数据” 错行
![image](https://github.com/jeecgboot/jeecg-boot/assets/139849659/44e1cb82-de98-4801-aba1-5d37569fb3aa)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
把
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/5b6894b7-f8d0-42bd-ad12-2841e33e4aec)
依赖版本号固定试试
