### ISSUE TITLE
修复sql注入问题，PR和master中SysDictServiceImpl.java不一致，master报错

### ISSUE THREAD

**Issue by ahshTao** [jeecgboot/jeecg-boot#5355]
##### 问题描述：修复sql注入问题。
我原有是3.5.3版本，想通过替换PR里的文件，修复漏洞，发现master中对应文件与PR不一致，且有些方法没有来源。
jeecg-module-system/jeecg-system-biz/src/main/java/org/jeecg/modules/system/service/impl/SysDictServiceImpl.java	
中466行的CommonUtils.getFilterSqlByTableSql(tableSql)和494行的CommonUtils.getTableNameByTableSql(tableSql)报错，没有找到对应方法的声明。
##### 截图&代码：
PR中jeecg-module-system/jeecg-system-biz/src/main/java/org/jeecg/modules/system/service/impl/SysDictServiceImpl.java	
463行
		//为了防止sql（jeecg提供了防注入的方法，可以在拼接 SQL 语句时自动对参数进行转义，避免SQL注入攻击）
		// 1. 针对采用 ${}写法的表名和字段进行转义和check
		table = SqlInjectionUtil.getSqlInjectTableName(table);
		text = SqlInjectionUtil.getSqlInjectField(text);
		code = SqlInjectionUtil.getSqlInjectField(code);

490行
		//【JTC-631】判断如果 table 携带了 where 条件，那么就使用 and 查询，防止报错
        if (table.toLowerCase().contains(sqlWhere)) {
            sqlWhere = " and ";
		}

master中同一文件
464行
		//为了防止sql（jeecg提供了防注入的方法，可以在拼接 SQL 语句时自动对参数进行转义，避免SQL注入攻击）
		// 1. 针对采用 ${}写法的表名和字段进行转义和check
		String table = SqlInjectionUtil.getSqlInjectTableName(CommonUtils.getTableNameByTableSql(tableSql));
		text = SqlInjectionUtil.getSqlInjectField(text);
		code = SqlInjectionUtil.getSqlInjectField(code);
492行
		//【JTC-631】判断如果 table 携带了 where 条件，那么就使用 and 查询，防止报错
        if (tableSql.toLowerCase().contains(sqlWhere)) {
            sqlWhere = CommonUtils.getFilterSqlByTableSql(tableSql) + " and ";
		}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/commit/473875a9d261780a3400cf6f8260ca441b768ed1
