### ISSUE TITLE
JPopup的bug

### ISSUE THREAD

**Issue by jfrong** [jeecgboot/jeecg-boot#5357]
##### 截图&代码：
<img width="860" alt="error0" src="https://github.com/jeecgboot/jeecg-boot/assets/57884843/f38dd0e3-0fb4-41fc-9b50-389bd58ec97b">

<img width="904" alt="err1" src="https://github.com/jeecgboot/jeecg-boot/assets/57884843/db37ecad-9af4-423f-913d-af42b873ab35">

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布。
问题一：是点了行选中导致的。
src/components/jeecg/OnLine/hooks/usePopBiz.ts
clickThenCheck方法
<img width="941" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/81386bc9-7d12-4d26-9aac-4bb6839624ef">
问题二：关闭没清空选择
src/components/Form/src/jeecg/components/modal/JPopupOnlReportModal.vue
handleCancel方法
<img width="424" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/2f90095d-e607-415a-b4b7-726abea40e76">
