### ISSUE TITLE
自动生成代码，控件默认值丢失？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5361]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在线表单里创建了一张表，其中有自定义的用户名和创建时间字段，默认控件值填入#{sysUserCode}和#{datetime}，在线测试的时候一切正常，新建数据也能自动带出控件默认值，然后在线”代码生成“后，就带不出来了？？？请问是我那里没做对吗？

##### 截图&代码：
![微信截图_20230907102620](https://github.com/jeecgboot/jeecg-boot/assets/37827583/adf0b231-81f7-4042-a544-ee8dd8ce625d)
![微信截图_20230907102715](https://github.com/jeecgboot/jeecg-boot/assets/37827583/916b7c6b-4583-45a8-8337-def14531819d)
![微信截图_20230907102807](https://github.com/jeecgboot/jeecg-boot/assets/37827583/7287c4a2-8fa9-4523-a85e-afede9da136b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有的功能，不支持生成的
