### ISSUE TITLE
咨询：jeecg是否可以接入外部数据库（而不是更换jeecg内部数据库类型）

### ISSUE THREAD

**Issue by heebaobao** [jeecgboot/jeecg-boot#5362]
#### 版本号：
v3.5.1

#### 前端版本：vue3版？还是 vue2版？
vue3

#### 问题描述：期望jeecg可以接入外部数据源（而不是更换jeecg内部数据库类型）
预期实现的功能
![image](https://github.com/jeecgboot/jeecg-boot/assets/99261084/9d0929b2-66ee-4f09-ab8d-28c7dd755ac6)
类似在平台上创建外部数据库的链接
![image](https://github.com/jeecgboot/jeecg-boot/assets/99261084/542fce18-95a2-481d-8a49-a5da4019efa8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by KoToXir** [comment]
online功能在网页上可直接配置，手写代码部分可在applycation.yml配置多个从数据源，配合@DS注解实现自己的业务流程

**Comment by heebaobao** [comment]
> online功能在网页上可直接配置，手写代码部分可在applycation.yml配置多个从数据源，配合@ds注解实现自己的业务流程
请问可以说的详细点吗？online网页配置是在哪里配置呢？
![image](https://github.com/jeecgboot/jeecg-boot/assets/99261084/8fcce8a5-06f6-48f2-bda9-431df0d77d7d)

**Comment by heebaobao** [comment]
> online功能在网页上可直接配置，手写代码部分可在applycation.yml配置多个从数据源，配合@ds注解实现自己的业务流程

**Comment by zhangdaiscott** [comment]
不支持
