### ISSUE TITLE
昨天还能好好的，今天就不行了。

### ISSUE THREAD

**Issue by AdminQQZ** [jeecgboot/jeecg-boot#5363]
##### 版本号：
3.5.3

##### 问题描述：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-07 15:40:05.879 [main] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter:40 - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (the profiles @profile.name@ are currently active).

Process finished with exit code 1

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/12959954/d0297d80-a2b8-4501-8ac0-4f518a6a0440)

![image](https://github.com/jeecgboot/jeecg-boot/assets/12959954/af842df7-1694-4950-befb-32cd11f67a02)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven clean
