### ISSUE TITLE
onlin表单授权菜单后没有权限

### ISSUE THREAD

**Issue by 956373939** [jeecgboot/jeecg-boot#5364]
Jeecg  Boot Version: 3.5.3

vue3版

##### 问题描述：
online表单代码生成菜单授权后，提示“没有权限，请联系管理员授权”，尝试了注释掉@RequiresPermissions，和配置按钮权限依然没有权限

##### 截图&代码：

![screenshot20230907 (1)](https://github.com/jeecgboot/jeecg-boot/assets/112368110/2cf98bc7-f6a3-49a8-81b3-9fd656601722)

![screenshot20230907 (2)](https://github.com/jeecgboot/jeecg-boot/assets/112368110/2b318a74-7bb3-487a-b6bc-e2fd11439e57)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码生成了对应的按钮权限，授权后，退出重新登录
