### ISSUE TITLE
页面f5刷新之后401

### ISSUE THREAD

**Issue by 354752672** [jeecgboot/jeecg-boot#5365]
##### 版本号：
3.5.4

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
正常路由跳转正常，页面f5刷新之后，401，查看network，发现向后端请求路由地址的接口

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/56473652/d9e99409-28ad-4dc6-9a27-985ee51f0a8a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/56473652/0cfef81c-0b6a-438d-9d8f-56f585fc6748)
![image](https://github.com/jeecgboot/jeecg-boot/assets/56473652/5895d504-8c0b-4c5b-9b5a-5aba058a2343)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么意思？

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
这边无法复现。贴下.env.development看下，看你的代理是怎么配置的

**Comment by 354752672** [comment]
您帮忙看下，看有不对的嘛





辰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月11日(星期一) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 页面f5刷新之后401 (Issue #5365)





 
这边无法复现。贴下.env.development看下，看你的代理是怎么配置的

**Comment by 354752672** [comment]
> 这边无法复现。贴下.env.development看下，看你的代理是怎么配置的

![image](https://github.com/jeecgboot/jeecg-boot/assets/56473652/71dcfbdf-b0ff-4fb6-bbc4-3c6d9612a239)

**Comment by 354752672** [comment]
> 这边无法复现。贴下.env.development看下，看你的代理是怎么配置的

![image](https://github.com/jeecgboot/jeecg-boot/assets/56473652/ed0e4eca-ce4b-43e9-b036-71930cb08081)
您看下，有啥问题呢？

**Comment by 1369521908** [comment]
> > 这边无法复现。贴下.env.development看下，看你的代理是怎么配置的
> 
> ![image](https://private-user-images.githubusercontent.com/56473652/266902761-ed0e4eca-ce4b-43e9-b036-71930cb08081.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTQ1NTgsIm5iZiI6MTcyNDM5NDI1OCwicGF0aCI6Ii81NjQ3MzY1Mi8yNjY5MDI3NjEtZWQwZTRlY2EtY2U0Yi00M2U5LWIwMzYtNzE5MzBjYjA4MDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2MjQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5OGY3NDhmNDE5ZTAwZWI3MjVjNDkyYmU5YTgzZmFkNjM0OWE1ZGFmYjcyNTEyY2JmYWFmNzBmYThlZjRjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DbQCLxcJwQJRSFNy2hMLwTEdCa6Q0EJ9ADX_NGbo5k4) 您看下，有啥问题呢？

修改后端api接口根据路径和你页面的路径不一致就行 被代理掉了
