### ISSUE TITLE
@Excel注解有没有转义功能？

### ISSUE THREAD

**Issue by lijl-vb** [jeecgboot/jeecg-boot#5367]
##### 版本号：
3.4.4

##### 问题描述：
请问一下，jeecg @Excel注解有没有转义功能？类似 https://zhuanlan.zhihu.com/p/621059202 该网站中的readConverterExp。

比如：@Excel(name = "状态", readConverterExp = "0=不可用,1=可用", width = 15)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有字典注解 
https://help.jeecg.com/autopoi/2.2zhujiezidianshiyong.html
