### ISSUE TITLE
使用登陆成功获取的token调用后端api ，直接显示token失效了

### ISSUE THREAD

**Issue by ahaostillcoding** [jeecgboot/jeecg-boot#5370]
##### 问题描述：

> 使用登陆成功获取的token调用后端api ，直接显示token失效了

> 只使用过Online在线功能生成代码新增了几个菜单，其他都没改动

> 本地运行没有问题，部署服务器后会出现此问题`

##### 截图&代码：
**直接调用api调试截图**

![3031a8edcd576cf0b438bbb856059a3a](https://github.com/jeecgboot/jeecg-boot/assets/93025680/2e40933b-1636-4473-85a0-7bd5b24b804e)

![62e8eca16b0cb5acc15a66b471138220](https://github.com/jeecgboot/jeecg-boot/assets/93025680/dd4988b3-a24a-413e-a3d4-182e2d09a69c)

**前端页面显示**
![d33f2d0e680901ea6a83913a77ae8f40](https://github.com/jeecgboot/jeecg-boot/assets/93025680/51e09fb1-69d3-4ae1-bd19-0ff3e7ce696b)
![d2a4e591903fcbb3f1990db09840024c](https://github.com/jeecgboot/jeecg-boot/assets/93025680/a579b8e9-ca58-4332-b2e6-dd9c4535f48c)
![d61d1955de77a056d73c8dd2dd195b9d](https://github.com/jeecgboot/jeecg-boot/assets/93025680/caff66fe-ce59-43c8-bd7a-b56fc9851743)

错误日志给gpt分析结果如下
![2a2519d54eb892005889882a0d6a68ec](https://github.com/jeecgboot/jeecg-boot/assets/93025680/db8f152a-cd35-481f-98ca-d9639b12ca61)

**Comment by ahaostillcoding** [comment]
> ##### 版本号：
> ##### 前端版本：vue3
> ##### 问题描述：
> 使用登陆成功获取的token调用后端api ，直接显示token失效了 只使用过Online在线功能生成代码新增了几个菜单，其他都没改动 本地运行没有问题，部署服务器后会出现此问题
> 
> ##### 截图&代码：
> 直接调用api调试截图
> 
> ![3031a8edcd576cf0b438bbb856059a3a](https://user-images.githubusercontent.com/93025680/266814881-2e40933b-1636-4473-85a0-7bd5b24b804e.png)
> 
> ![62e8eca16b0cb5acc15a66b471138220](https://user-images.githubusercontent.com/93025680/266814893-dd4988b3-a24a-413e-a3d4-182e2d09a69c.png)
> 
> 前端页面显示 ![d33f2d0e680901ea6a83913a77ae8f40](https://user-images.githubusercontent.com/93025680/266814909-51e09fb1-69d3-4ae1-bd19-0ff3e7ce696b.png) ![d2a4e591903fcbb3f1990db09840024c](https://user-images.githubusercontent.com/93025680/266814913-a579b8e9-ca58-4332-b2e6-dd9c4535f48c.png) ![d61d1955de77a056d73c8dd2dd195b9d](https://user-images.githubusercontent.com/93025680/266814919-caff66fe-ce59-43c8-bd7a-b56fc9851743.png)
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
redis清一下，应该是不匹配有老数据
