### ISSUE TITLE
一对多子表popup建议增加多选

### ISSUE THREAD

**Issue by tesren73** [jeecgboot/jeecg-boot#5371]
##### 问题描述：
一对多子表popup建议增加多选，
或者子表实现 下拉搜索框的异步查询搜索功能。
谢谢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
一对多子表popup多选功能已经添加，新一版本发布

**Comment by tesren73** [comment]
谢谢
