### ISSUE TITLE
菜单设置了删除和批量删除权限，给管理员勾选了这两个权限，没有给临时角色勾选，但是临时角色也可以直接用（编辑权限好像没有这个问题）

### ISSUE THREAD

**Issue by linzym** [jeecgboot/jeecg-boot#5372]
##### 问题描述：菜单设置了删除和批量删除权限，给管理员勾选了这两个权限，没有给临时角色勾选（就是帮助文档的第3点中的勾选），但是重新登录后，管理员和临时角色都可以删除和批量删除。
就是说实际使用效果是管理员未授权这两个权限，未授权的临时校色不能使用这里两个权限，但是只要管理员授权了这两个权限，未授权的临时角色好像也自然被授权了这两个权限可以使用。这个好像与帮助文档说明得不一样。

我还试过编辑权限，这个权限没有问题，管理员和临时角色都必须授权了（就是帮助文档的第3中的勾选）才能使用，与帮助文档说明的一样。

帮助文档：
请求权限控制
https://help.jeecg.com/java/system/auth/request.html

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
图文并茂看看你怎么设置的

**Comment by linzym** [comment]
Hi,


    您好！


    附件是这个问题的图文说明文档，供参考。


    如果需要再进一步的说明，请尽管提出！


    谢谢！


Best Regards,


linzym
















在 2023-09-16 21:36:44，"JEECG" ***@***.***> 写道：

图文并茂看看你怎么设置的
