### ISSUE TITLE
Official website vue2 demo login fail

### ISSUE THREAD

**Issue by sl2026** [jeecgboot/jeecg-boot#5376]
##### 截图&代码：
两个账号都登不上
![image](https://github.com/jeecgboot/jeecg-boot/assets/48578521/142bd671-8afe-4c18-8211-f7539ff13f1f)

![image](https://github.com/jeecgboot/jeecg-boot/assets/48578521/fa10c8fb-63a7-4637-b046-64a2f2b9b1c5)

**Comment by zhangdaiscott** [comment]
好了
