### ISSUE TITLE
Websocket连接不上，报错1002，求大佬看看，

### ISSUE THREAD

**Issue by 81219122** [jeecgboot/jeecg-boot#5378]
##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
Websocket连接不上，报错1002，求大佬看看

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/57030006/043be5c5-2e7a-45d4-b86c-5a2fe9fa1d23)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
补充后台版本号
