### ISSUE TITLE
版本信息不一致

### ISSUE THREAD

**Issue by jcjw2019** [jeecgboot/jeecg-boot#5380]
##### 版本号：

当前最新版本： 3.5.4（发布日期：2023-09-04）
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
当前最新版本： 3.5.4（发布日期：2023-09-04），但是代码里面还是3.5.3

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
本计划2023-09-04发版，延期了，后期会发新版
