### ISSUE TITLE
实体类添加@Version版本标识不生效

### ISSUE THREAD

**Issue by zhangmm1991** [jeecgboot/jeecg-boot#5382]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/48120ab8-0948-4727-aa90-46acaa8a2b58)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/2c2254a1-6f99-496b-9940-406e354a57cc)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/a44cf374-1beb-4332-95a0-a1f25a6a04cb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不清楚，我们用的没问题

**Comment by zhangdaiscott** [comment]
https://baomidou.com/pages/0d93c0/#_1-%E9%85%8D%E7%BD%AE%E6%8F%92%E4%BB%B6
