### ISSUE TITLE
后端PDF文件的byte[]，前端该怎么接受并下载

### ISSUE THREAD

**Issue by jujubetree** [jeecgboot/jeecg-boot#5383]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
后端PDF文件的byte[]，前端该怎么接受并下载

##### 截图&代码：
后端响应代码：
![Dingtalk_20230913122512](https://github.com/jeecgboot/jeecg-boot/assets/49394098/0d6b2519-bab3-487c-8273-015031c5f647)
或者这样：
![Dingtalk_20230913122641](https://github.com/jeecgboot/jeecg-boot/assets/49394098/bd075a70-130c-4f19-97ca-438cd8f056c1)
都试过
前端：
![Dingtalk_20230913121914](https://github.com/jeecgboot/jeecg-boot/assets/49394098/b8a17eb5-e24c-4a72-9f41-e8695b3c1e25)
![Dingtalk_20230913122956](https://github.com/jeecgboot/jeecg-boot/assets/49394098/c85bd7ba-6e09-4c8c-8e5d-f3b6f45b00b9)

前端接受时，responseType设哪种值，都无法接收到，报typeerror

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以参考jeecg的下载源码实现
