### ISSUE TITLE
积木报表使用循环块后，子表数据无法显示

### ISSUE THREAD

**Issue by Qinjialiang** [jeecgboot/jeecg-boot#5384]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

积木报表使用循环块后，子表数据无法显示
##### 截图&代码：
使用循环块前
![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/54677ef7-f3ca-4669-8501-4ae9063c1d9c)

使用循环块后
![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/6efe6d5e-76e4-4cee-86f3-6ec74098c569)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
