### ISSUE TITLE
使用在线Online开发，出现搜索框前面的label字被截断

### ISSUE THREAD

**Issue by hxzpp** [jeecgboot/jeecg-boot#5387]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
使用在线Online开发，出现搜索框前面的label字被截断，看如下图，扩展参数配置的label长度，也是配置了50的

##### 截图&代码：
<img width="1164" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/22518103/c1007155-6371-426e-85fe-7c5d123977ca">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
默认显示4个字，鼠标放上去可以提示

**Comment by hxzpp** [comment]
嗯，但是司机名字就是4个字的，最后一个“名”没显示全部，我试了下在13寸和15寸的mac pro上都是显示不全的，但是17寸以上的才能显示全，应该是有兼容性问题

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你可按如下图修改。
src/settings/componentSetting.ts
<img width="712" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/970c6df9-d95d-40a1-b2c8-4eb82a37a5c6">
