### ISSUE TITLE
有没有方法在JVxeTable外面选中里面的数据

### ISSUE THREAD

**Issue by Whiteyingshan** [jeecgboot/jeecg-boot#5388]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
1、如何在JVxeTable外面选中里面的某一行吗，比如说有一个按钮，点击后选中JVxeTable的第一行
2、如何聚焦于JVxeTable的某一行
3、如何在不用鼠标点击的情况下，触发JVxeTable的selectRowChange方法

**Comment by KoToXir** [comment]
看vxetable的文档试试？

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/component/JVxeTable.html
