### ISSUE TITLE
技术咨询--数据权限问题

### ISSUE THREAD

**Issue by davide0123** [jeecgboot/jeecg-boot#5390]
##### 版本号：
最新开源版
##### 前端版本：vue3版？还是 vue2版？
最新开源版Vue3版本

##### 问题描述：
根据官方文档的数据权限用法配置后，用户管理不生效。男性测试用户在用户管理中还可以看到女性用户。
咨询一下，是哪个地方的问题？

##### 截图&代码：

<img width="681" alt="1694747562916" src="https://github.com/jeecgboot/jeecg-boot/assets/15645859/42e7c993-4407-4357-bdee-3641dce28c75">

![1694747710058](https://github.com/jeecgboot/jeecg-boot/assets/15645859/858bdd21-7c24-46d0-9e14-9c217dde902f)

![image](https://github.com/jeecgboot/jeecg-boot/assets/15645859/e755758d-2402-4755-a1fb-a39e090d44b1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by davide0123** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/15645859/d754b680-3a72-408c-9081-06ab3d1b7c79)

**Comment by davide0123** [comment]
开源版本用户管理菜单的/sys/user/listall接口需要增加@PermissionData(pageComponent = "system/user/index") ，是吧？

**Comment by zhangdaiscott** [comment]
重启了吗，后台接口配置的对吗，确认下请求的接口加了注解

**Comment by davide0123** [comment]
已经解决了，就是注解的问题，谢谢
