### ISSUE TITLE
/sys/prodCategory/loadDictItem/ 接口返回第一次查询结果id和值顺序不对应

### ISSUE THREAD

**Issue by wangyujiaoflag** [jeecgboot/jeecg-boot#5391]
##### 问题描述：/sys/prodCategory/loadDictItem/ 接口返回第一次查询结果id和值顺序不对应

数据库查询 1664083991818539174 对应的是 G5319，但是第一次结果并未按顺序返回

##### 截图&代码：

<img width="347" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/41095916/d8665082-241b-46ae-a605-0424ec54b7ea">
<img width="202" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/41095916/c36c74fe-f327-496e-b8ff-4d02ccbbbbd8">
<img width="208" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/41095916/2347bd65-af6a-4811-b7cc-99ac4a88d50f">

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/7db9a9bb-c8eb-4452-8081-dbc59913d3f3)
jeecg默认没有提供这个接口地址
