### ISSUE TITLE
微服务免token登录方案失效

### ISSUE THREAD

**Issue by zhangmm1991** [jeecgboot/jeecg-boot#5392]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/d003abfa-c1b2-49af-831b-5f56d80859f8)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/a1c250a0-9320-41f6-a330-c8e4e7746807)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/ff2a90ae-e684-42a3-b414-9067286ed8dd)
![image](https://github.com/jeecgboot/jeecg-boot/assets/32173218/85d48874-6e73-4c47-9575-b0b8c9a4024d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你都shiro排除权限控制了，还用这个方案干啥

**Comment by zhangmm1991** [comment]
我是直接用免token登录的方案失效才排除权限控制的，本意是不想暴露接口的

**Comment by zhangdaiscott** [comment]
对外接口，采用token方案，为什么要采用这免token登录方式

**Comment by zhangmm1991** [comment]
我这个权限放开的不是system服务里的接口，是新建的一个transmission微服务，供外部系统请求的开放接口服务，不登陆；但是接口内部需要调用system服务里接口数据，需要token的，所以用的临时token，但是不生效

> 我是直接用免token登录的方案失效才排除权限控制的，本意是不想暴露接口的
