### ISSUE TITLE
怎么自己定义时间组件

### ISSUE THREAD

**Issue by zjc676685962** [jeecgboot/jeecg-boot#5395]
##### 版本号：
     3.5.4

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
  请问 表单的时间组件 自己能自定义在加吗? 就是数据库想存yyyyMMddHHmmss的字符串时间 但是目前的时间组件 只能让存datetime

##### 截图&代码：
![a9cfa169cd567dba39c276af4ddc268c](https://github.com/jeecgboot/jeecg-boot/assets/53850054/66181700-05fb-40b4-bdc1-69165da2aa49)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
