### ISSUE TITLE
数据字典配置时，数据值不能输入特殊字符

### ISSUE THREAD

**Issue by PleromaMilla** [jeecgboot/jeecg-boot#5397]
##### 版本号：
3.5.4

##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述： 数据字典配置时，数据值不能输入特殊字符。
该校验规则是否可以去除？

##### 截图&代码：
<img width="867" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/103876560/2c7b4c0c-ba43-48b0-876f-79dca62d072d">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化请自己扩展，容易出问题

**Comment by PleromaMilla** [comment]
好的，谢谢
