### ISSUE TITLE
菜单icon不支持显示自定义svg icon显示？

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5398]
##### 截图&代码：

{
    field: 'icon',
    label: '菜单图标',
    component: 'IconPicker',
    componentProps: {
      mode: 'svg'
    },
    ifShow: ({ values }) => !isButton(values.menuType),
  },

**Comment by zhangdaiscott** [comment]
你的代码有点少，你是怎么改的，详细点说明

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
暂不支持
