### ISSUE TITLE
在线表单中设置的页面配置中高级配置中设置的label长度，在列表与详情界面无效

### ISSUE THREAD

**Issue by skillful2002** [jeecgboot/jeecg-boot#5400]
##### 版本号：
3.5.4

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
在线表单中设置的页面配置中高级配置中设置的label长度，在列表与详情界面无效，只在查询条件与编辑界面生效！

##### 截图&代码：

<img width="1311" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/be4932cc-57f3-441e-bf40-3765f0cea6cc">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
列表什么效果？

**Comment by skillful2002** [comment]
> 列表什么效果？

<img width="1255" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/23468bc5-50ab-4d92-a134-621b98dda91d">

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
