### ISSUE TITLE
如何将某个路由外链出去

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/jeecg-boot#5403]
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
目前只能将外部URL链接到平台中，如何将平台中的某个路由URL外链到其他平台做集成？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个暂时不支持
