### ISSUE TITLE
列表内字典表的渲染需求

### ISSUE THREAD

**Issue by youngswell** [jeecgboot/jeecg-boot#5404]
##### 问题描述：生成的代码，希望列表内渲染支持字典表。
本人能理解在列表内渲染字典表有性能问题，但希望官方能支持该功能。

已在本地实现，方案是：
1. 重构/utils/common/renderUtils.ts文件中的renderDict方法；
2. 重构/utils/dict/index.ts文件中的initDictOptions方法

将字典表数据动态加入缓存管理，渲染时等待第一次获取字典表数据并存入缓存（有是否缓存选项，可以选择不缓存），之后的访问直接访问本地。有更新时使用页面内“刷新缓存”功能，也可考虑采用过期时间的方案。

以上是个人见解，如官方认可并愿意实施，本人可以提供源码！

##### 截图&代码：
无

**Comment by zhangdaiscott** [comment]
支持啊
