### ISSUE TITLE
多租户场景使用online表单开发的新增数据的时候，Postgresql会报数据异常

### ISSUE THREAD

**Issue by tangrongjian6** [jeecgboot/jeecg-boot#5405]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
微服务版本，多租户场景下使用online表单开发的新增数据的时候，Postgresql会报数据异常，提示tenant_id类型不匹配

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/31211752/588625ae-c163-4ccc-b23f-d3a447fc1e43)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
scott

**Comment by zhangdaiscott** [comment]
iwms_warehouse 这个表字段如何设计的截图

**Comment by zhangdaiscott** [comment]
无回复的话，暂时关闭了
