### ISSUE TITLE
积木报表api请求超时时间

### ISSUE THREAD

**Issue by xikp** [jeecgboot/jeecg-boot#5406]
##### 版本号：
<jeecgboot.version>3.2.0</jeecgboot.version>
<artifactId>jimureport-spring-boot-starter</artifactId>
			<version>1.5.0-beta</version>
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
积木报表1.5.0-beta版本，数据源是sql时，查询超过10秒不会中断连接

现在数据sql是api的方式，api调用超过10秒报表就是空的，是在哪里配置了10秒超时连接吗

##### 截图&代码：
<img width="1085" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/99701908/1d90cd0b-416a-47de-bc4f-25bbe6dcf30c">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by antbuster** [comment]
可参考#5249 解决
官方不修复，还莫名close了。
别merge最新提交，
官方把druid升到1.2.15，而dynamic-datasource-spring-boot-starter还保留在3.2.0。

**Comment by xikp** [comment]
> 可参考#5249 解决 官方不修复，还莫名close了。 别merge最新提交， 官方把druid升到1.2.15，而dynamic-datasource-spring-boot-starter还保留在3.2.0。

排除了还是一样，报表api调用还是10秒就超时了

**Comment by xikp** [comment]
> 可参考#5249 解决 官方不修复，还莫名close了。 别merge最新提交， 官方把druid升到1.2.15，而dynamic-datasource-spring-boot-starter还保留在3.2.0。

<img width="543" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/99701908/427bad10-7e0f-452b-bd83-ba5e2b39ae23">
druid版本是1.1.22

**Comment by zhangdaiscott** [comment]
为什么不升级积木报表到最新版

**Comment by xikp** [comment]
> 为什么不升级积木报表到最新版
