### ISSUE TITLE
如何修改“从数据库导入表功能”功能底层SQL

### ISSUE THREAD

**Issue by blatwo** [jeecgboot/jeecg-boot#5408]
##### 版本号：
jeecg 3.0

##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
jeecg 从数据库导入表功能，在使用Postgres数据库时，底层SQL是 select tablename from pg_tables where schemaname in( 'public')，是写死的public？能改模式么，想把public改为xmgl，如何修改？还有的就是MySQL时可以把视图查出来，postgresql的这个pg_tables只有表。我也想改一下这个SQL。

##### 截图&代码：
select tablename from pg_tables where schemaname in( 'public')

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/3fd80c54-aa21-4b44-9ad9-712914ca802a)
