### ISSUE TITLE
BasicTable 配置maxColumnWidth 未生效

### ISSUE THREAD

**Issue by jhaso1988** [jeecgboot/jeecg-boot#5411]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/34854608/4f41bbe8-29a3-456f-bdc3-a402ae6f7105)
![image](https://github.com/jeecgboot/jeecg-boot/assets/34854608/e3dfe1d5-4567-4025-a5da-393ca0e5d361)
<img width="617" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/34854608/81db4cc3-a2d8-4791-9d62-4931970034d7">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布。
你本地可按下图代码先行修改。
src/components/Table/src/hooks/useTableScroll.ts
<img width="915" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/d90bb37c-893c-4057-bf34-e0a22a900702">
