### ISSUE TITLE
后端启动正常,前端一启动连接的话就会一直在转圈圈

### ISSUE THREAD

**Issue by TBX1314521** [jeecgboot/jeecg-boot#5412]
##### 问题描述：
后端项目可以正常启动,但是一打开前端页面就会一直在加载转圈圈,然后后端控制台会报出错误,好想是数据库连接超时的问题,感谢各位大佬帮忙解答一下,搞了两三天没有解决,实在

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/33d7eedd-bf24-484c-b326-3f32b0da94cc)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/dea8cb6f-c4ed-40ee-99ea-8f76870e54fa)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/0367986e-57e3-408f-a0f8-9ac7c7219f4c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/d42d3f91-1e4f-479c-9648-95f3fb5b5380)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/c2a67cdc-74f8-4a32-bc35-c5b3d24cf56d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/c81dd435-434e-4fc1-b1e7-1f9d566333f3)

错误代码:
er-WIN-6A3N83B0UIP1695180592124_ClusterManager] ERROR druid.sql.Statement:148 - {conn-10004, pstmt-20017} execute error. UPDATE QRTZ_SCHEDULER_STATE SET LAST_CHECKIN_TIME = ? WHERE SCHED_NAME = 'MyScheduler' AND INSTANCE_NAME = ?
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 10,027 milliseconds ago. The last packet sent successfully to the server was 14,091 milliseconds ago.

**Comment by TBX1314521** [comment]
转了大概十几分钟打开了

**Comment by zhangdaiscott** [comment]
数据库没连上？用的是vue2还是vue3

**Comment by TBX1314521** [comment]
这好像是一个bug,不知道什么原因我的电脑上，vue的jeecgboot项目就是进不去登录页面,能运行成功,但是页面一直在卡着,很难受,大概第一次加载都需要十分钟以上,我用我朋友的电脑测试过都是很正常的,node版本我用过14 也用过16的版本都是一样的效果,浏览器的版本是最新的,以前也遇到过这样的问题,后面好像是把电脑重新装了,问题就解决了,我jeecgboot3的vue3的版本是能秒进入登录页面的,希望官方帮忙解答一下,感谢
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/555c5bb7-3414-4137-be87-e677993f7317)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/d5929c88-d577-4236-816e-8a560763c2fb)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/7ed845b5-3694-4a3b-b355-dbd7cc4e8e5a)

**Comment by zhangdaiscott** [comment]
可能安装的依赖有冲突，可以要一下别人的lock试试

**Comment by TBX1314521** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/55613008/9d92eea6-8793-4eff-9cac-3b9473f53692)
我也尝试使用过别人安装的依赖,我用jeecg差不多快一年左右,但是只出现过两次 这样的情况,,上次是重装系统,但是现在电脑里面的资料比较多，

**Comment by tsgdnwxg** [comment]
我今天升级到3.5.5也出现这个问题了，但是我这边测试的结果是edge浏览器可以打开页面，360极速浏览器不行，其它浏览器暂时未测试，因为我这边没有。能看到的浏览器console信息是卡在vite那里了。

**Comment by tsgdnwxg** [comment]
换了电脑，换了gitee的下载源，结果神奇的好了
