### ISSUE TITLE
createMessage的提示icon没有垂直居中

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5413]
##### 截图&代码：createMessage的提示icon没有垂直居中，请全局修复一下，谢谢！

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/a65efd7f-3430-4c9d-96c9-7b5be8bc832d)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
最新的3.5.5版本已经修复了此问题。你本地的src/design/ant/index.less文件span.anticon:not注释掉了即可
