### ISSUE TITLE
仪表盘设计中，数据集中获取分组报错

### ISSUE THREAD

**Issue by skillful2002** [jeecgboot/jeecg-boot#5416]
##### 版本号：
3.5.4

##### 前端版本：vue3版？还是 vue2版？
VUE3
drga-free版本为1.0.1

##### 问题描述：
仪表盘设计中，数据集中获取分组报错，新增数据必填项分组无数据，导至无法新增数据集。

##### 截图&代码：

1、无分组
<img width="995" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/468eeeff-4b4d-4e5f-9fb2-4e4494fc29a7">
2、分组接口报错（前端图）
<img width="971" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/c969f809-de4a-4378-a022-86ef8829d145">
3、分组接口报错（后端图）
<img width="1046" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/c1437e74-c65b-4d8f-b8e0-02e02a49271f">
4、新增数据集时无分组
<img width="1146" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/10183545/8b072b66-ebf3-45e3-be8c-ae85048b6b26">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
修复了，更新代码

**Comment by skillful2002** [comment]
非常感谢
