### ISSUE TITLE
RangePicker组件打包上线之后，点击没任何反应

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5417]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/ddfc5df2-3745-44e2-876f-f5b512ce6a47)

**Comment by RacingK93** [comment]
版本号：3.5.4

**Comment by zhangdaiscott** [comment]
好像修复过了，看看git历史

**Comment by zhangdaiscott** [comment]
升级到最新版本

**Comment by RacingK93** [comment]
解决了，把build:test，test替换成别的就行了
