### ISSUE TITLE
popup多选后，返回多条独立的数据，而不是归并到一起作为数组

### ISSUE THREAD

**Issue by sangjiexun** [jeecgboot/jeecg-boot#5418]
##### 版本号：
3.4.5

##### 前端版本：vue3版？还是 vue2版？

2
##### 问题描述：
popup多选后，返回多条独立的数据，而不是归并到一起，作为数组显示

##### 截图&代码：
https://github.com/jeecgboot/jeecg-boot/issues/2876

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化自己改造
