### ISSUE TITLE
字典默认值问题

### ISSUE THREAD

**Issue by yanglihangissue** [jeecgboot/jeecg-boot#5421]
##### 版本号：
v3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
已经默认值了，120是2小时，可是界面显示还是120而不是字典的2小时，这怎么解决

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/131324243/2a03c718-f8b6-468c-a8a2-f65564b57595)
![image](https://github.com/jeecgboot/jeecg-boot/assets/131324243/073a505e-238b-427a-86d9-397c31d35ee7)
![image](https://github.com/jeecgboot/jeecg-boot/assets/131324243/0340be00-ff5b-49c5-bdaf-0149393c88cf)
![image](https://github.com/jeecgboot/jeecg-boot/assets/131324243/1755afeb-3243-48d2-a863-0ee29546bfa2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
类型的问题，字段类型是数值？

**Comment by zhangdaiscott** [comment]
设置下 stringToNumber属性

**Comment by yanglihangissue** [comment]
谢谢，确实是类型问题
