### ISSUE TITLE
SQL字典在哪里配置和使用？

### ISSUE THREAD

**Issue by aiyuefine** [jeecgboot/jeecg-boot#5424]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
SQL字典在哪里配置和使用？

##### 截图&代码：

下面是文档中的说明，没有具体的使用方法

![image](https://github.com/jeecgboot/jeecg-boot/assets/5071109/54152365-9e73-4568-8104-7c458f9b9272)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是说的那个地方功能？
