### ISSUE TITLE
JVxeTypes.popup 没有param参数吗，那么我要在弹出框给出动态的查询条件怎么处理呢

### ISSUE THREAD

**Issue by freeleepm** [jeecgboot/jeecg-boot#5426]
##### 版本号：
jeecgboot 3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：

1. 怎么在
![53BE6CA07E7A0D457F651E276E00DC1B](https://github.com/jeecgboot/jeecg-boot/assets/17607013/df7d74fd-5457-4421-9f29-bd6beeb99672)
就是我 【2】的查询要依赖【1】选择的内容，这个应该在那里可以获得呢【1】的值呢，🙏
![53BE6CA07E7A0D457F651E276E00DC1B](https://github.com/jeecgboot/jeecg-boot/assets/17607013/1a98c141-e537-4ce6-bf1e-708e5d43ec50)
是在上面的方法里面吗

3. JVxeTypes.popup 没有param参数吗，那么我要在弹出框给出动态的查询条件怎么处理呢

##### 截图&代码：

谢谢官方的技术同学，帮忙解答一下

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/3df37760-9679-4d35-b4d9-8246391dc3c5)

**Comment by freeleepm** [comment]
谢谢作者抽空回答我的问题。使用这个参数之后会报错，同时在代码里面没有办法接收对应的值
<img width="858" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/17607013/79fd3729-8312-4e00-a79d-f062cdee1092">
