### ISSUE TITLE
online生成的vue代码单独删除的确认框样式有问题

### ISSUE THREAD

**Issue by yanglihangissue** [jeecgboot/jeecg-boot#5427]
##### 版本号：
 v3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
online生成的vue代码单独删除的确认框样式有问题，vue3Native的代码

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/131324243/eff23c5c-122c-433b-9b76-8bf2c226ad85)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
