### ISSUE TITLE
搜索框字段加了前后空格，翻页时未去除前后空格，导致查不到数据

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5430]

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
你本地版本可按如下修改
src/components/Table/src/hooks/useDataSource.ts
<img width="1060" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/7304075f-6ac1-411e-ad36-3e6a87ea8507">
以上仅仅对antd原生组件生效（单表示例中的搜索就是antd原生组件）。如果你使用的是Jinput组件，需要配置中加入componentProps:{trim: true }
如系统用户：
<img width="648" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/db55361e-c301-4284-8cfd-7283ea69e642">
