### ISSUE TITLE
我在使用

### ISSUE THREAD

**Issue by m2075498242** [jeecgboot/jeecg-boot#5433]
##### 版本号：
3.4.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我在使用了表头合并后  就出现了 序号列这样的问题

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/088e7bd5-9f8f-4789-bb78-53806de592a5)

![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/e3e2e4e7-b27f-462a-8f9a-9b8ff31baa17)
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/10c0c6e0-f446-456c-854f-ba06cf35878d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/f8c21731-d776-44ac-99a8-a1ff0bfb8005)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by m2075498242** [comment]
方便说一下怎么解决吗

**Comment by liaozhiyang** [comment]
经测试没复现此问题，能否转成静态数据试试再贴上来。或者你那边升级版本看看，3.4.0版本是一年前的了。
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/e61e00e3-90d7-4b4a-b812-08cc6c238709)

**Comment by m2075498242** [comment]
试过了 还是不行的 方便问下怎么升级版本呢 会影响到项目吧

**Comment by m2075498242** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/458eeff0-d2da-4012-9704-2e44305b98f9)
控制台打印出来序号列是这样的 但是就是渲染出了问题
