### ISSUE TITLE
{"success":true,"message":"Token失效，请重新登录!","code":401,"result":null,"timestamp":1695784589562}

### ISSUE THREAD

**Issue by liuguang-lg** [jeecgboot/jeecg-boot#5434]
登录成功   token也已经返回了
使用postman访问就报错   说没有扫描的mapper包
![image](https://github.com/jeecgboot/jeecg-boot/assets/58280388/b991bf21-9c0e-4555-a2bd-64c4ce8a4421)

**Comment by liuguang-lg** [comment]
No qualifying bean of type 'org.jeecg.common.api.CommonAPI' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.context.annotation.Lazy(value=true), @javax.annotation.Resource(shareable=true, lookup=, name=, description=, authenticationType=CONTAINER, type=class java.lang.Object, mappedName=)}

**Comment by zhangdaiscott** [comment]
jeecg的mybatis的包你不管了吗

**Comment by zhangdaiscott** [comment]
http://jeecg.com/doc/qa

**Comment by liuguang-lg** [comment]
不好意思   昨天有点事情

![image](https://github.com/jeecgboot/jeecg-boot/assets/58280388/86c936ec-dc2d-498e-8f88-aac440fa1fd2)


lombok下载了

web访问就可以  使用postman就不行

**Comment by liuguang-lg** [comment]
mybatis使用的是   
![image](https://github.com/jeecgboot/jeecg-boot/assets/58280388/1bfec47f-23a1-4fcc-a443-e4a222b3e501)

**Comment by liuguang-lg** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/58280388/00af9378-f825-437e-b61b-944b7e19a490)
实在执行认证的时候出的问题

**Comment by liuguang-lg** [comment]
还请麻烦帮我看下

**Comment by liuguang-lg** [comment]
问题解决了   
![image](https://github.com/jeecgboot/jeecg-boot/assets/58280388/7679c0ce-6250-4f41-92d6-ee81caa286f2)


包引错了   后来改过之后  打包应该是出问题了  第二次打包重新运行好了
