### ISSUE TITLE
修改包路径后，Gateway无法转发请求（Knife4j报404）

### ISSUE THREAD

**Issue by Hao9807** [jeecgboot/jeecg-boot#5435]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在自定义包路径后，按照文档修改了
MybatisPlusSaasConfig、配置文件扫包路径、Swagger2Config、DictAspect、启动类
在启动system和gateway后（先启动了system后启动的gateway），发现通过localhost:9999访问，一直会报404
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/38185045/822359d4-0523-4b4b-9084-d881bb59b6d5)
查看nacos后，发现服务是正常注册的
![image](https://github.com/jeecgboot/jeecg-boot/assets/38185045/e0a400c5-9c44-4f28-8e82-461be138da93)
然后直接访问system是没有问题的
![image](https://github.com/jeecgboot/jeecg-boot/assets/38185045/81ce86fc-7d8a-47aa-a96e-313c86eb7fef)
想请问还有什么原因导致这种问题呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己改造后导致的问题，我们无法分析
