### ISSUE TITLE
教学文档里的SQL字典的具体使用方法有吗？最好有个DEMO

### ISSUE THREAD

**Issue by aiyuefine** [jeecgboot/jeecg-boot#5436]
##### 截图&代码：
![68b3a2e27b341c5e3a8fdaf485f3f0f4_270095297-54152365-9e73-4568-8104-7c458f9b9272](https://github.com/jeecgboot/jeecg-boot/assets/5071109/0435500d-78ca-4cd5-ae11-fe7092b5c025)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
都不知道你说的哪里
