### ISSUE TITLE
代码生成完成了，忘记配置部门选择 用户选择的映射字段跟单选 。怎么处理呢 必须重新生成代码吗？可以在 componentProps加参数处理吗

### ISSUE THREAD

**Issue by jc-Liiiii** [jeecgboot/jeecg-boot#5438]
##### 版本号：
3.5.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
代码生成完成了，而且页面有比较大的调整，但是忘记部门选择单选 跟 忘记用户选择，展示username了  怎么后续处理呢。可以不重新生成代码处理吗 

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
手工修改代码参数就行了，不用重新生成
