### ISSUE TITLE
低代码生成-自定义按钮JS增强，生成的页面不显示按钮

### ISSUE THREAD

**Issue by jourk** [jeecgboot/jeecg-boot#5439]
##### 问题描述：
低代码生成-自定义按钮JS增强，生成的页面不显示按钮
Online生成代码中使用自定义按钮，增加JS增强，按钮在在线测试中可以展示，生成vue3文件放到项目里前端就不展示，而且生成的vue文件中也没有对应按钮的前端代码。

生成的是主子表ERP样式。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自定义按钮JS增强是在线功能，不支持代码生成
