### ISSUE TITLE
online表单的子表记录没有边框线

### ISSUE THREAD

**Issue by watchworld** [jeecgboot/jeecg-boot#5441]
##### 版本号：

3.1.0
##### 前端版本：vue3版？还是 vue2版？
vue2版？

##### 问题描述：
表单一对多情况下，明细行记录风格有异常，各字段间没有边框线。（用Online在线设计的。）

##### 截图&代码：
![屏幕截图 2023-10-05 013417](https://github.com/jeecgboot/jeecg-boot/assets/7036776/6008b422-6e06-4a29-861b-9edce4509d09)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请截图标识说明下

**Comment by watchworld** [comment]
已经截图，就是新增仓库信息明细，看明细记录是没有边框线的。请看<截图&代码>
仓库编码列有边框，我是鼠标放上去的。
