### ISSUE TITLE
SQL监控登录成功页面重定向没反应

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#5443]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/86f7aa61-94a9-4707-b580-a5102d784bf3)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/5eeb1b9d-7c22-4ae8-8927-c739eb6aa75c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
gateway下的确是这样
