### ISSUE TITLE
knife4j

### ISSUE THREAD

**Issue by 88mao** [jeecgboot/jeecg-boot#5444]
版本号：3.5.5

前端版本：vue3版

问题描述：nacos中配置knife4j线上模式和密码不生效

截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37680798/0b6aae01-c374-4672-8f4d-e104540cb194)
微服务模式。nacos中设置生产模式后，knife4j依然能访问，设置认证开启依然不需要密码

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
印象中是有这个bug，微服务上线情况下，你可以先关闭knife4j服务

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/965085f5-dd7c-4d18-8b31-0cbf29f919c9)
刚测试了下，现在的版本没有问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/136239cd-e31b-4c26-b19b-4574512ea8b0)
