### ISSUE TITLE
当前版本按根据官方教程，无法为xxl-job执行器指定端口

### ISSUE THREAD

**Issue by tangrongjian6** [jeecgboot/jeecg-boot#5445]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue

##### 问题描述：
当前版本按根据官方教程，无法为xxl-job执行器指定端口

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/31211752/1d75fc78-6ff7-4236-aaf3-4362e0112a8e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/31211752/335cc774-b708-4b11-a112-21c8c9979477)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
因为固定端口会导致多个微服务有冲突，如果你有个性化需求，可以扩展底层starter
