### ISSUE TITLE
online表单开发，生成主附表，主表选择erp风格，配置菜单+auto，用户无权限访问（操作）

### ISSUE THREAD

**Issue by tsgdnwxg** [jeecgboot/jeecg-boot#5446]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online表单开发，生成主附表，主表选择erp风格，配置菜单+auto，用户无权限访问（操作）

##### 截图&代码：
必须要赋予用户所属角色online表单权限，才能打开erp风格的主子表的子表数据，否则就会提示无权限访问（操作）。
默认风格的正常，不需要授予online表单权限就可以显示子表数据。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
配置菜单截图

**Comment by zhangdaiscott** [comment]
无回复暂时关闭

**Comment by tsgdnwxg** [comment]
![微信截图_20231023204141](https://github.com/jeecgboot/jeecg-boot/assets/3140447/8caa64f1-1556-4951-ae7d-3e6c4fd109ee)
不好意思，这几天没搞开发，没上来看。
