### ISSUE TITLE
下拉多选框内容没有渲染出来

### ISSUE THREAD

**Issue by Qinjialiang** [jeecgboot/jeecg-boot#5447]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
下拉框内容为空，但是打印下拉框选项内容是存在值的

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/38841996-66dd-4e80-89e9-d78f81b40bdb)
![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/3f82f693-b51c-4337-9569-63a01ccf589f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码截图

**Comment by Qinjialiang** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/f10699f1-55eb-4ed3-8a43-372d74f0f7f1)
![image](https://github.com/jeecgboot/jeecg-boot/assets/116338746/804d5b58-9a89-4f06-8ef3-57d6941cbe59)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/4814a882-c76e-4b9a-8c4b-21bd22d80870)
这个是你自己赋值的，你自己debug跟踪看看赋值成功没有
