### ISSUE TITLE
minio使用域名错误

### ISSUE THREAD

**Issue by yuanbao1124** [jeecgboot/jeecg-boot#5449]
使用IP时能正常上传下载

换成域名后 idea 启动正常，打成jar 后提示错误
![image](https://github.com/jeecgboot/jeecg-boot/assets/55846949/97d076ab-f8a7-4707-9c45-207d2feda2cb)

maven 配置如下
![image](https://github.com/jeecgboot/jeecg-boot/assets/55846949/771ab698-2dee-4740-b199-5538dd1e7ca3)

**Comment by yuanbao1124** [comment]
idea启动 正常
![image](https://github.com/jeecgboot/jeecg-boot/assets/55846949/a7c66ce4-4137-4d19-9c4e-add835dbbfa3)

尝试过升级依赖但是一样的提示错误

**Comment by zhangdaiscott** [comment]
应该是部署问题，我们的演示环境minio没有问题
