### ISSUE TITLE
BasicModal弹框无法垂直居中

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5450]
##### 截图&代码：

<BasicModal
    v-bind="$attrs"
    @register="registerModal"
    destroyOnClose
    :title="title"
    :width="900"
    :bodyStyle="{
      padding: '6px',
    }"
    :height="600"
    :min-height="600"
    :centered="true"
    :useWrapper="true"
  >

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
去掉:height="600"属性即可，当BasicModal弹框的高度（含内容）小于可视区域高度，就是垂直居中，当BasicModal弹框的高度（含内容）大于可视区域高度，是顶部跟可视区域顶部对齐，这个是和antd-design-vue是保持一致的。
