### ISSUE TITLE
Online在线表单设计，点击【功能测试】报【无权限访问（操作）】

### ISSUE THREAD

**Issue by li-ml** [jeecgboot/jeecg-boot#5453]
##### 版本号：
v3.5.x

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

Online在线表单设计，点击【功能测试】报【无权限访问（操作）】，谁知道解决办法

是这个接口报错：online/cgform/api/getData/1711642016501284866?hasQuery=true&column=id&order=asc&pageNo=1&pageSize=10&_t=1696939475104

![image](https://github.com/jeecgboot/jeecg-boot/assets/7353901/26d0f905-a7f0-4383-a960-16d1a562a8df)

##### 截图&代码：
![RZ`XTEGY NNEFYVEY73{SU](https://github.com/jeecgboot/jeecg-boot/assets/7353901/8cd1fc18-7fa5-415b-9e2e-0990e0558594)

![O$SL4WA8CZKQYP9(`G9O{2](https://github.com/jeecgboot/jeecg-boot/assets/7353901/8ae12b4d-736c-453b-af12-efb8850d639b)

**Comment by zhangdaiscott** [comment]
具体版本？什么时间下载的版本

**Comment by li-ml** [comment]
应该是这个版本： 3.5.1（发布日期：2023-04-20）

**Comment by li-ml** [comment]
sys_permission  这个表没有那个form的数据，不知道怎么给它自动加数据？
