### ISSUE TITLE
请问下，现在还支持从企业微信同步部门到本地么

### ISSUE THREAD

**Issue by qinjiacheng** [jeecgboot/jeecg-boot#5454]
##### 问题描述：
请问下，现在还支持从企业微信同步部门到本地么

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
逐步会去掉企业微信，企业微信的接口限制太多了，不支持对接
