### ISSUE TITLE
企业微信集成后，本地无法同步通信录到企业微信

### ISSUE THREAD

**Issue by jackfangyijun** [jeecgboot/jeecg-boot#5455]
##### 截图&代码：
#在这里图片无法上传，我描述一下提示信息：
点击【同步企微】按钮，最后弹出：**同步失败，失败信息如下：1企业微信用户列表查询失败！**

----application-dev.yml-----
#第三方APP对接
third-app:
  enabled: true
  type:
    #企业微信
    WECHAT_ENTERPRISE:
      enabled: true
      #CORP_ID
      client-id: ww85417de0fa800218
      #SECRET
      client-secret: xHu26Sd7jzWDJwca9BsT8i0eOS-bZrdLtsmT5hrt0-4
      #自建应用id
      agent-id: 1000002
      #自建应用秘钥（新版企微需要配置）
      agent-app-secret: tlrN3IAymj6RZWOKE7tb86EQ1298fCUgE3xnFtLnx-M

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
企业微信接口调整了，不支持了

**Comment by jackfangyijun** [comment]
那么我这里还有个疑问，是不是企业微信Oauth2登录这个也不支持了，还有就是钉钉的集成和Oauth2登录是不是也不支持了呢？
&nbsp;


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月11日(星期三) 中午1:47
收件人: ***@***.***&gt;; 
抄送: "my ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 企业微信集成后，本地无法同步通信录到企业微信 (Issue #5455)





 
企业微信接口调整了，不支持了
