### ISSUE TITLE
gateway网关路由问题

### ISSUE THREAD

**Issue by moumoukings** [jeecgboot/jeecg-boot#5459]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/35523332/b2ab21d9-3578-4143-b461-ca0a26f615a3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by moumoukings** [comment]
正常应该是找不到接口的报错

**Comment by zhangdaiscott** [comment]
这是gateway转发

**Comment by moumoukings** [comment]
是我ShiroConfig配置的问题吗？

**Comment by moumoukings** [comment]
> 这是gateway转发

是我ShiroConfig配置的问题吗？

**Comment by moumoukings** [comment]
> 这是gateway转发

大佬，求教一下。
我还是没找到为什么通过网关调用sys/user/list可以访问，正常应该是jeecg-system/sys/user/list这样才可以调用的呀
