### ISSUE TITLE
代码生成器报错，not found for name "common/sql/menu_insert.ftl"

### ISSUE THREAD

**Issue by hhqz2333** [jeecgboot/jeecg-boot#5461]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：
1.使用Online生成代码报错，如下图。现象是只生成一个空的xml文件，如下
2.使用GUI代码生成，控制台不报错，但是也是只生成了一个空的xml文件，入下
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.jeecg.modules.demo.sys_user.mapper.SysUserMapper">

</mapper>
自己排查：
1.不存在中午路径或者空格
2.数据库配置都改了，项目可以正常链接数据库。

##### 截图&代码：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by hhqz2333** [comment]
[/[](url)](url)
![image](https://github.com/jeecgboot/jeecg-boot/assets/50733766/7e771238-c4a4-4b45-8191-2873f23d4727)

**Comment by hhqz2333** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.jeecg.modules.demo.b_house_main.mapper.BHouseMainMapper">

</mapper>

**Comment by hhqz2333** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.jeecg.modules.demo.b_house_main.mapper.BHouseMainMapper">

</mapper>`

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/4c998c5d-0333-4b64-9189-06181a2dba3c)
看看有没有这个文件

**Comment by hhqz2333** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/50733766/237ac2a3-30b6-452c-90aa-330b1565560c)
从idea里面看没有这两个文件，但是直接从电脑文件夹里看，就有。

**Comment by zhangdaiscott** [comment]
那就是你本地环境问题，看看为什么会这样

**Comment by hhqz2333** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/50733766/5f8e2d5d-482a-49d3-9692-dc0cfb009d03)

找到原因了，因为我的idea配置屏蔽了.java.和.vue.等文件，改一下这个地方就好啦，谢谢！
