### ISSUE TITLE
多租户是否打算完全开源

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/jeecg-boot#5464]
##### 版本号：
jeecgboot 3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1.按照 [[租户功能介绍](https://help.jeecg.com/javaback/tenantFunction.html)] 文档的介绍，[我的租户]功能和[租户默认套餐]，在开源版中未看到。是否有开源打算。

2.[租户管理]和[我的租户]中，都存在产品包添加用户功能，参考官方demo截图如下，和开源版不一样，是否有升级的打算。

在线等，望回复！

##### 截图&代码：

![img_v2_ddd2932a-cee9-440f-b9e4-f5bfd816b57g](https://github.com/jeecgboot/jeecg-boot/assets/362930/decb3af7-6f7e-4d75-b755-11b1e3491c94)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by moloStudio** [comment]
你勾选租户前面的复选框就出来套餐按钮了。

**Comment by zhangdaiscott** [comment]
下个版本会更新
