### ISSUE TITLE
关于访问主页logo.png加载的问题

### ISSUE THREAD

**Issue by SevenLiu666** [jeecgboot/jeecg-boot#5465]
##### 问题描述：
前后端均已经启动完毕，但是在访问页面的时候发现一个问题，logo.png加载不出来，如图1

然后进行以下排查

1. logo.png访问不到是404导致，然后去项目寻找logo.png图片，发现logo.png在根目录下的public/resource/img/logo.png路径，初步怀疑是因为缺少public目录导致。
 2. 在浏览器中直接访问logo.png，访问路径加入public层级，发现可以访问，如图2
3.  将前端项目打包，发现打完的dist包中，logo.png路径在dist根目录下的/resource/img/logo.png，这样前端加载该资源没有问题（
http://localhost:3000/resource/img/logo.png）
请问，开发环境需要加入public这个访问层级，打包之后则不需要，这个是不是应该是动态配置的，不应该是我开发环境加上public，而打包之前再去掉public吧？或许现在框架就是这样的，而是我没有看到，如果是这样也欢迎指正。谢谢

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/59589423/9085bf51-2b8b-4d4b-a9a0-ad1a64c0b5b5)
![image](https://github.com/jeecgboot/jeecg-boot/assets/59589423/d04fcbf8-bc10-4462-8bf8-831618b85287)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果你没改过代码，不会有这样的问题

**Comment by SevenLiu666** [comment]
没有修改




--
发自我的网易邮箱手机智能版



在 2023-10-13 14:51:17，JEECG ***@***.***> 写道：


如果你没改过代码，不会有这样的问题

**Comment by SevenLiu666** [comment]
> 如果你没改过代码，不会有这样的问题

后端是在https://gitee.com/jeecg/jeecg-boot下载的，前端是在https://gitee.com/jeecg/jeecgboot-vue3下载的，你们可以留个联系方式，联系一下，我什么都没有动，但是就是存在这个问题

**Comment by zhangdaiscott** [comment]
测试未发现问题

**Comment by SevenLiu666** [comment]
但是我下载下来 什么都没改  就是有这问题 不能找个技术给排查一下吗
