### ISSUE TITLE
表格禁用勾选后，点击全选还是会选中

### ISSUE THREAD

**Issue by ttnzhang** [jeecgboot/jeecg-boot#5466]
##### 截图&代码：
rowSelection: {
			  type: 'checkbox',
			  getCheckboxProps(record: Recordable) {
			    if (record.processStatus == 'approve' && record.stageStatus!='publicity') {
			      return { disabled: false };
			    } else {
			      return { disabled: true };
			    }
			  },
				onChange(keys,rows){
					console.log(keys)
					console.log(rows)
				}
			},

![GK9E$63~AHB94D1 8QAIGPE](https://github.com/jeecgboot/jeecg-boot/assets/30816717/e61f2986-b5d5-4e5a-b9da-85c7c7ca983d)

官方vue3演示版 组件&功能>树形表格 有同样的问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可按如下更改
src/components/Table/src/hooks/useCustomSelection.tsx
const flattedData = computed(() => {
const data = flattenData(tableData.value, childrenColumnName.value);
const rowSelection = propsRef.value.rowSelection;
if (rowSelection?.type === 'checkbox' && rowSelection.getCheckboxProps) {
for (let i = 0, len = data.length; i < len; i++) {
const record = data[i];
const result = rowSelection.getCheckboxProps(record);
if (result.disabled) {
data.splice(i, 1);
i--;
len--;
}
}
}
return data;
});
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/19e3cf53-f0fa-4309-bbd2-0e9c1b52d9db)
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/fcbcb4fb-bc77-47c8-ac87-ef4c68eb6638)

src/components/Table/src/components/CustomSelectHeader.vue
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/5adc2187-dce4-4c78-b603-67d5484f0e7b)

**Comment by liwenpmz** [comment]
加了为啥没用啊 @liaozhiyang

**Comment by liwenpmz** [comment]
@ttnzhang  解决了吗

**Comment by liwenpmz** [comment]
@zhangdaiscott  打包后会出现样式问题

**Comment by liwenpmz** [comment]
打包后 全选按钮样式不生效 @zhangdaiscott

**Comment by liwenpmz** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/62593298/877f0e3c-362b-4ed1-81a5-0b0fbfc05161)

**Comment by zhangdaiscott** [comment]
好像是vue版本号问题，固定版本号就好了

![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/3958c4a3-b4c9-42dd-b009-915a18c1fed7)
