### ISSUE TITLE
3.5.5 ApiSelect修复错误

### ISSUE THREAD

**Issue by HWT-coder** [jeecgboot/jeecg-boot#5467]
##### 截图&代码：

错误代码截图：

![image](https://github.com/jeecgboot/jeecg-boot/assets/68092325/c268b757-5c65-4798-bdde-1f985ee59867)
正确代码截图：
![image](https://github.com/jeecgboot/jeecg-boot/assets/68092325/3ab4fc67-1370-4792-a08c-16c09cfd5497)
**将过滤方法放在v-bind="attrs_"上面即可**

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已经修复，下一版本发布
