### ISSUE TITLE
升级导致shardingsphere 异常，程序启动失败。

### ISSUE THREAD

**Issue by dfreng** [jeecgboot/jeecg-boot#5469]
##### 版本号：
sprint boot 3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
dynamic-datasource-spring-boot-starter 升级4.1.3后，导致
jeecg-boot-starter-shardingsphere-3.5.5.jar 依赖
import com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DataSourceProperty 
报错，
Caused by: java.lang.NoSuchMethodError: com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider: method <init>()V not found

该插件jeecg-boot-starter-shardingsphere-3.5.5 maven 依赖 需同步升级。

##### 截图&代码：
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jimuReportTokenService': Unsatisfied dependency expressed through field 'sysBaseApi'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysBaseApiImpl': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysUserMapper' defined in file [/Users/pdf/IdeaProjects/eco-boot-backend-v3.5/jeecg-module-system/jeecg-system-biz/target/classes/org/jeecg/modules/system/mapper/SysUserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sqlSessionFactory' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataSource' defined in class path resource [org/jeecg/boot/shardingsphere/config/DataSourceConfiguration.class]: Unsatisfied dependency expressed through method 'dataSource' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dynamicDataSourceProvider' defined in class path resource [org/jeecg/boot/shardingsphere/config/DataSourceConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.baomidou.dynamic.datasource.provider.DynamicDataSourceProvider]: Factory method 'dynamicDataSourceProvider' threw exception; nested exception is java.lang.NoSuchMethodError: com.baomidou.dynamic.datasource.provider.AbstractDataSourceProvider: method <init>()V not found

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你先下载starter项目，本地install吧
https://github.com/jeecgboot/jeecg-boot-starter/commit/9af268f9325602132810d41f5ba7cce1ceb464ed
