### ISSUE TITLE
数值类型导出后为字符串类型

### ISSUE THREAD

**Issue by lisuguozhi** [jeecgboot/jeecg-boot#5472]
##### 版本号：
  <modelVersion>4.0.0</modelVersion>
    <groupId>org.jeecgframework.jimureport</groupId>
    <artifactId>jimureport-spring-boot-starter</artifactId>
    <version>1.6.1</version>

##### 问题描述：

设计为数值类型，但导出为字符串类型，导致EXCLE报错
##### 截图&代码：

![360380643fc1c26952b1cca63c6fbe8](https://github.com/jeecgboot/jeecg-boot/assets/46182603/55391d4f-b111-4c5c-bbf4-a4241c01ffdc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级积木报表到最新版本
