### ISSUE TITLE
批量插入时，事务长时间不提交

### ISSUE THREAD

**Issue by index-jie** [jeecgboot/jeecg-boot#5473]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
事务长时间不提交，没有修改数据源参数配置，不知道为什么一直不提交，是批量插入

##### 截图&代码：

![1697122613080](https://github.com/jeecgboot/jeecg-boot/assets/129490278/f84e9319-66f8-414d-b97f-96d1cc891ebf)
![1697122613091](https://github.com/jeecgboot/jeecg-boot/assets/129490278/bf6f1425-fe4b-4ef3-86ab-e66c00450268)
![image](https://github.com/jeecgboot/jeecg-boot/assets/129490278/afcab5a1-25a0-44e4-b93c-8a873da98f03)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2最高版本是3.4.3
