### ISSUE TITLE
仪表盘配置到首页且角色也做了首页配置后，对普通角色关闭仪表盘设计器，普通角色访问首页显示404

### ISSUE THREAD

**Issue by smo123** [jeecgboot/jeecg-boot#5475]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
仪表盘配置到首页且角色也做了首页配置后，对普通角色关闭仪表盘设计器，普通角色访问首页显示404

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/5967043/cc5e51c4-05fb-4109-b18c-cd18cadb9a27)
![image](https://github.com/jeecgboot/jeecg-boot/assets/5967043/ff29b491-9fad-4b79-a956-22b7fed32b51)
![image](https://github.com/jeecgboot/jeecg-boot/assets/5967043/d6d69e7c-2a72-42d7-a850-3b88b0d00275)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你这个不是路由菜单

**Comment by smo123** [comment]
> 你这个不是路由菜单

@zhangdaiscott 不是啊，我关闭了路由菜单这个按钮也是不行的，你应该可以重现的

**Comment by smo123** [comment]
@zhangdaiscott 你只需要把仪表盘设计器的菜单给关了，就能重现我说的问题了

**Comment by zhangdaiscott** [comment]
预览隐藏路由，给用户分配了吗
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/7aa2d364-bce3-4a6c-9e60-8c02fd4b0871)

**Comment by smo123** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/5967043/f1cca555-00ad-444f-942d-16e1fcce120b)

你的菜单界面跟我貌似不一样，我的面板预览是在低代码之下：低代码>仪表盘设计器>面板预览

一分配面板预览，仪表设计器必须也选中，则仪表盘设计器也必然显示出来

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/1f56181e-88f8-4e98-893c-6e19d2ae69aa)

你手工调整下位置即可
