### ISSUE TITLE
前端代码打包特别慢，需要5分钟，怎么调整？

### ISSUE THREAD

**Issue by zhaoFenG8917** [jeecgboot/jeecg-boot#5478]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
前端代码打包特别慢，需要5分钟，怎么调整？

##### 截图&代码：
![微信截图_20231013191416](https://github.com/jeecgboot/jeecg-boot/assets/98065365/86770362-9e0c-4287-ab72-43279fc9a4ec)

![微信截图_20231013191443](https://github.com/jeecgboot/jeecg-boot/assets/98065365/39f3e3b3-e0f3-45ef-9c40-6d6f960b4d3c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级到最新版，看更新日志已经优化了

**Comment by zhaoFenG8917** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
