### ISSUE TITLE
部门管理中，如何添加上级部门（即添加根节点）

### ISSUE THREAD

**Issue by Panda-Chuanchuan** [jeecgboot/jeecg-boot#5479]
##### 前端版本：vue3版？还是 vue2版？
vue2版本

##### 问题描述：
部门管理中，如何添加上级部门（即添加根节点）

#####
 截图&代码：
![QQ截图20231016120929](https://github.com/jeecgboot/jeecg-boot/assets/26615178/6b04edb7-2510-405a-a75a-e77b57a51031)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/4c0ccccf-a16f-48ff-aecb-a99cbefeff2d)
