### ISSUE TITLE
Online报表配置，参数传入后不生效

### ISSUE THREAD

**Issue by djq1102** [jeecgboot/jeecg-boot#5483]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
在Online报表配置中，使用${}参数设置

##### 截图&代码：
select *
from dwd_contract_attendance_items where user_id='${user_id}' order by attendance_date desc

<img width="1165" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/855921/d5d3f282-84a3-4c02-afad-5db5bb9a2167">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
提供的信息太少，无法分析

**Comment by zhangdaiscott** [comment]
无回复暂时关闭
