### ISSUE TITLE
单元格合并失效

### ISSUE THREAD

**Issue by 1laohutu** [jeecgboot/jeecg-boot#5485]
##### 版本号：
3.5.2

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
合并行、列单元格失效，以下是ant  design vue官方代码，运行时报错：
warning.js:6 Warning: `columns.customRender` return cell props is deprecated with perf issue, please use `customCell` instead

##### 截图&代码：
<template>
    <a-table :columns="columns" :data-source="data" bordered>
      <template slot="name" slot-scope="text">
        <a>{{ text }}</a>
      </template>
    </a-table>
  </template>
  <script>
  // In the fifth row, other columns are merged into first column
  // by setting it's colSpan to be 0
  const renderContent = (value, row, index) => {
    const obj = {
      children: value,
      attrs: {},
    };
    if (index === 4) {
      obj.attrs.colSpan = 0;
    }
    return obj;
  };
  
  const data = [
    {
      key: '1',
      name: 'John Brown',
      age: 32,
      tel: '0571-22098909',
      phone: 18889898989,
      address: 'New York No. 1 Lake Park',
    },
    {
      key: '2',
      name: 'Jim Green',
      tel: '0571-22098333',
      phone: 18889898888,
      age: 42,
      address: 'London No. 1 Lake Park',
    },
    {
      key: '3',
      name: 'Joe Black',
      age: 32,
      tel: '0575-22098909',
      phone: 18900010002,
      address: 'Sidney No. 1 Lake Park',
    },
    {
      key: '4',
      name: 'Jim Red',
      age: 18,
      tel: '0575-22098909',
      phone: 18900010002,
      address: 'London No. 2 Lake Park',
    },
    {
      key: '5',
      name: 'Jake White',
      age: 18,
      tel: '0575-22098909',
      phone: 18900010002,
      address: 'Dublin No. 2 Lake Park',
    },
  ];
  
  export default { 
    data() {
      const columns = [
        {
          title: 'Name',
          dataIndex: 'name',
          customRender: ({ text, index }) => {
                const obj = {
                    children: text,
                    attrs: {},
                };
                if (index === 0) {
                    obj.attrs.colSpan = 2;
                }
                return obj;
        }
        //   customRender: (text, row, index) => {
        //     if (index < 4) {
        //       return text;
        //     }
        //     return {
        //       children: text,
        //       attrs: {
        //         colSpan: 5,
        //       },
        //     };
        //   },
        },
        {
          title: 'Age',
          dataIndex: 'age',
        //   customRender: renderContent,
        },
        {
          title: 'Home phone',
          colSpan: 2,
          dataIndex: 'tel',
        //   customRender: (value, row, index) => {
        //     const obj = {
        //       children: value,
        //       attrs: {},
        //     };
        //     if (index === 2) {
        //       obj.attrs.rowSpan = 2;
        //     }
        //     // These two are merged into above cell
        //     if (index === 3) {
        //       obj.attrs.rowSpan = 0;
        //     }
        //     if (index === 4) {
        //       obj.attrs.colSpan = 0;
        //     }
        //     return obj;
        //   },
        },
        {
          title: 'Phone',
          colSpan: 0,
          dataIndex: 'phone',
        //   customRender: renderContent,
        },
        {
          title: 'Address',
          dataIndex: 'address',
        //   customRender: renderContent,
        },
      ];
      return {
        data,
        columns,
      };
    },
  };
  </script>
  

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy
