### ISSUE TITLE
在线生成表单没有见到空行，但页面属性会报空行数据错误

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/jeecg-boot#5487]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/dfb09fa9-5f92-4543-8fca-f1d32474761a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/858d9bf2-6537-43f0-8624-4ec1121d6316)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 520-x** [comment]
表单删除后，页面属性还有空格
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/dbc8ede0-8bbe-492e-99f7-daae3e5f2a7d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/de454a8d-8fdc-4cda-a05b-b637b39f2939)

**Comment by zhangdaiscott** [comment]
下个版本会更新online

**Comment by 520-x** [comment]
什么时候发布嘞
