### ISSUE TITLE
上线执行打包命令全部都用的.env.production环境文件中的配置，其它配置文件不生效

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5488]
##### 问题描述：上线执行打包命令全部都用的.env.production环境文件中的配置，其它配置文件不生效，
不管是执行npm run build:dev,npm run build:bug,npm run build:pre，最终都是用的.env.production文件中的配置

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/62dc314b-f564-458b-a641-7c6f5577d73d)

**Comment by zhangdaiscott** [comment]
这是你自己加的命令吧，默认没有

**Comment by RacingK93** [comment]
> 这是你自己加的命令吧，默认没有

但是package.json里只有npm run buid命令，虽然我看有.env.development，但是没有build:dev

**Comment by RacingK93** [comment]
> 这是你自己加的命令吧，默认没有

简单点说，目前项目不支持自定义环境配置。

**Comment by mrmyn** [comment]
请问解决了吗

**Comment by mrmyn** [comment]
vite build --mode staging
在 --mode加上你的env的命名就行了
