### ISSUE TITLE
3.6.0登录报错，始终转圆圈

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#5489]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
登录时报错，始终转圆圈。
GET http://localhost:8080/jeecg-boot/sys/permission/getPermCode?_t=1697697350736 404 (Not Found)
GET http://localhost:8080/jeecg-boot/sys/permission/getUserPermissionByToken?_t=1697697350737 404 (Not Found)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台启动了吗

**Comment by snkever** [comment]
启动了

**Comment by zhangdaiscott** [comment]
截图看配置，详细说明

**Comment by snkever** [comment]
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/c395fc67-6e38-49bb-b8b2-9646359464bd)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/db033a3b-6ee6-46c0-aadf-5f845637606d)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/4f5c5fa7-e622-4beb-bcbc-62d7d6100122)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/4183f4f1-034e-49f1-aa71-87fba125196b)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/c4017e7d-2ac5-42c7-ab8b-30c4a269c249)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/29ff31b2-255b-45ac-bfe2-b7d33c7ac4ae)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/f6fde03b-0cea-43df-ad2d-ba55fdc85322)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/41155809-183b-4044-b167-f1e8f7e80bd3)
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/e1424344-ffb3-4736-87eb-cc2229491bee)

**Comment by snkever** [comment]
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/27081d03-1e90-4e61-a5af-4ff96085ccfd)

**Comment by zhangdaiscott** [comment]
你发的信息没有价值，去QQ群里交流下
