### ISSUE TITLE
仪表盘设计器中的甘特图的数据源，其数据格式是怎样的？

### ISSUE THREAD

**Issue by liuwa666** [jeecgboot/jeecg-boot#5490]
##### 版本号：
v3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

请教各位大神，有没有用过仪表盘设计器的，这个甘特图的数据格式是怎样的。

比如jeecg中给出的这个甘特图示例，这里面画出了了三个项目的甘特图，每个项目相当于分成了几个不同的阶段。像这么样的甘特图数据源，其数据格式是怎样的？有没有哪位大神帮帮我，不胜感激

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/12774287/0a22c920-a294-4df7-9d78-f35e6406b969)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个只是个样子，还未对接完成

**Comment by liuwa666** [comment]
> 这个只是个样子，还未对接完成
好的明白了
