### ISSUE TITLE
为什么 “我的部门”菜单下的信息一直是空的？

### ISSUE THREAD

**Issue by ZJRui** [jeecgboot/jeecg-boot#5491]
##### 版本号：
3.5

##### 前端版本：vue3版？还是 vue2版？
Vu3

##### 问题描述：

1.
![image](https://github.com/jeecgboot/jeecg-boot/assets/40123628/669d5909-c45f-487e-a03d-8ff213e4112f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/40123628/d949ac57-a52b-4f62-9eff-fa8f272db92c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/40123628/842cd193-3dde-4f87-b013-76efd25f3b80)

1. 相关问题 
[相关问题](https://github.com/jeecgboot/jeecg-boot/issues/5239#issue-1842924190)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你需要是部门负责人
