### ISSUE TITLE
主题覆盖不全

### ISSUE THREAD

**Issue by KTBOY** [jeecgboot/jeecg-boot#5493]
##### 问题描述：
在**themeConfig.ts**默认主题修改为#0e7a3e，但打包后生成环境没有生效，在本地运行开发环境生效

![image](https://github.com/jeecgboot/jeecg-boot/assets/52773276/907f066e-1a45-4fac-84eb-09890422e2b4)

##### 截图&代码：
本地运行的开发环境效果图
![image](https://github.com/jeecgboot/jeecg-boot/assets/52773276/0e074f23-2087-41aa-be59-f7affa8b070a)
打包后的生产环境
![image](https://github.com/jeecgboot/jeecg-boot/assets/52773276/f886ccee-dccc-446b-b89f-e985695e040a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请先升级到最新版
