### ISSUE TITLE
新建模块 请求 出现404

### ISSUE THREAD

**Issue by 18350269219** [jeecgboot/jeecg-boot#5494]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/49049873/8cf69798-e820-48ee-ac7f-efc8ce63714d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/49049873/17ce0083-8e5d-496b-9554-0615ea47cbd6)
![image](https://github.com/jeecgboot/jeecg-boot/assets/49049873/0f6532a4-a61e-4c90-9425-3f3a1b1c982b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你引入到system启动模块里了吗

**Comment by zhangdaiscott** [comment]
无回复暂时关闭

**Comment by 18350269219** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/49049873/3fcf5fcb-4f97-4346-abcb-8b649a6aab56)
system-start  里面pom  已经引入了
![image](https://github.com/jeecgboot/jeecg-boot/assets/49049873/e7eef266-2405-4b88-9347-783d7b35bfa0)
最外层的pom 也引入了

**Comment by zhangdaiscott** [comment]
maven刷新了吗
