### ISSUE TITLE
苹果手机使用tinymce富文本获取内容时，某些汉字自动识别为拼音

### ISSUE THREAD

**Issue by qiqijiayao** [jeecgboot/jeecg-boot#5496]
##### 截图&代码：
  {
    field: 'commentsProgress',
    component: 'Input',
    label: '进度说明',
    defaultValue: '',
    render: ({ model, field }) => {
      return h(Tinymce, {
        value: model[field],
        onChange: (value: string) => {
          model[field] = value;
        },
      });
    },
  },

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
截图详细描述
