### ISSUE TITLE
前端校验字符串规则提示错误

### ISSUE THREAD

**Issue by EightMonth** [jeecgboot/jeecg-boot#5497]
##### 版本号：
3.6.0

##### 问题描述：
前端校验字符串规则提示错误，进入用户详情页面时，邮箱和手机号部分提示：“校验失败，存在SQL注入风险！白名单校验未通过！”

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/9de79fe9-a152-4edb-9c53-7b564bae3b7a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个应该是未配置白名单字典

**Comment by EightMonth** [comment]
3.6.0升级的sql执行过了，需要额外再加数据才能覆盖这个错误提示么
