### ISSUE TITLE
org.jeecg.common.util.DySmsEnum类不见了

### ISSUE THREAD

**Issue by tsgdnwxg** [jeecgboot/jeecg-boot#5500]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
原来使用了org.jeecg.common.util中的DySmsEnum开发短信发送功能，升级到3.6.0版本后org.jeecg.common.util包中缺失DySmsEnum类

##### 截图&代码：
![微信截图_20231023214905](https://github.com/jeecgboot/jeecg-boot/assets/3140447/6f8943c3-4e4f-46b0-8c41-0336d217190e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
在core里，换位置了
