### ISSUE TITLE
新增账号无法登录

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5501]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
当新增一个用户的时候，sys_user_tenant表会插入一条租户id为0的关联数据，然后这个账号就无法登录了，因为租户为0的租户是一个特殊的，没有存在系统的
![image](https://github.com/jeecgboot/jeecg-boot/assets/38182329/d965611e-5633-4d02-9fd5-2921fa02f239)
zhe'l这里查询的时候是否应该移除租户为0的租户

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是切换租户模式了？

**Comment by zflzqy** [comment]
并没有切换啊，用的都是默认0的租户

**Comment by zhangdaiscott** [comment]
那不会登录不了啊，提示什么

**Comment by zflzqy** [comment]
与该用户关联的租户均已被冻结，无法登录！

**Comment by zflzqy** [comment]
数据库中有一条INSERT INTO `traceability`.`sys_user_tenant`(`id`, `user_id`, `tenant_id`, `status`, `create_by`, `create_time`, `update_by`, `update_time`) VALUES ('1706218638440738818', '1715209341749506049', 0, '1', 'admin', '2023-06-02 11:11:38', NULL, NULL);
这样的数据

**Comment by zhangdaiscott** [comment]
那你是不是把租户设置冻结了啊

**Comment by zhangdaiscott** [comment]
我们刚发的新版3.6.0，测试过新建账号登录没问题，你可以看看

**Comment by zflzqy** [comment]
我是开启了多租户的配置的

**Comment by zflzqy** [comment]
更新版本已解决
