### ISSUE TITLE
通知无法接收

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5503]
##### 版本号：

3.6.0
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
![image](https://github.com/jeecgboot/jeecg-boot/assets/38182329/0d290b92-b9b1-437d-aeb9-82d9043d4f70)
这里当用户id传入的后缀没有带英文的,比如123最后会被截取成12，是否应该兼容这种单个用户的情形呢

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
已修改
