### ISSUE TITLE
开源版本 商业使用权限问题

### ISSUE THREAD

**Issue by noodzhan** [jeecgboot/jeecg-boot#5504]
##### 版本号：

3.4.4

##### 前端版本：vue3版？还是 vue2版？

vue2

##### 问题描述：

基于开源版本3.4.4 jeecgboot ，自己写的工作流模块和其他功能，是否可以商业使用或者二开，是否对公司造成侵权。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/37291977/6fdcd21f-f65a-494e-b743-7f2252441c6f)

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/b7b62336-afc3-4c33-884b-0a06fdcd10c0)

**Comment by noodzhan** [comment]
比如说现在有一个项目，准备技术选型，使用jeecgboot 开源版本作为基础框架，然后在上面整合工作流、自定义表单、代码生成、库存、物联网等等，然后商业使用，是否和上面所说功能类似，构成侵权。
