### ISSUE TITLE
Online表单开发-在数据库属性页面新增字段删除后，页面属性没有同步删除

### ISSUE THREAD

**Issue by DewsLi** [jeecgboot/jeecg-boot#5505]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online表单开发-在数据库属性页面新增字段删除后，页面属性没有同步

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18074622/5297def2-552c-4237-a49f-dfa5d2ca9d6d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已经修复，请更新前端代码
