### ISSUE TITLE
3.6.0 Knife4j文档请求异常

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#5506]
##### 版本号：
3.6.0
gateway打开页面显示Knife4j文档请求异常
启动顺序是按照nacos->demo->system->gateway
gateway前启动也不行
我照着文档操作的，是哪里有问题么？
启动有两个警告，看了前面的问题好像说是不影响
一个是demo和system启动警告：Customize redis listener handle [ loderRouderHandler ], does not exist！
一个是gateway启动警告：converter can not convert rules because source is empty

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tb2888** [comment]
Knife4j文档请求异常   图片
![1698204814144](https://github.com/jeecgboot/jeecg-boot/assets/55084864/ae20bdf7-a92d-4328-ab43-d1e9697fdef2)

**Comment by ppanjiabao** [comment]
我也是这样的，启动不了

**Comment by ppanjiabao** [comment]
请问你如何解决的？
