### ISSUE TITLE
登录界面验证码出不来

### ISSUE THREAD

**Issue by tb2888** [jeecgboot/jeecg-boot#5507]
##### 版本号：
3.6.0

##### 问题描述：
微服务启动，前端请求的IP地址是哪来的？不是localhost，也不是我的IP地址；请求不通报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55084864/cbab9bb6-39b5-4bce-a3ab-0a539680dfdd)

![image](https://github.com/jeecgboot/jeecg-boot/assets/55084864/6bef2422-e10e-4e58-b0b0-7fd9b402acf3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你前端怎么配置的后台接口地址

**Comment by tb2888** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jeecgboot/jeecg-boot] 登录界面验证码出不来 (Issue #5507)





 
你前端怎么配置的后台接口地址

**Comment by tb2888** [comment]
> 你前端怎么配置的后台接口地址
前端我就按照文档改了这里
![image](https://github.com/jeecgboot/jeecg-boot/assets/55084864/ecffb794-0ba6-46e9-a338-4115280c37fa)

![image](https://github.com/jeecgboot/jeecg-boot/assets/55084864/231a8a1a-699d-477e-a322-dbe273dedfda)

**Comment by zhangdaiscott** [comment]
你后台启动成功了吗，通过这个地址能访问吗
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/e799deff-7a6b-43cc-84da-78139d869779)

**Comment by tb2888** [comment]
> 你后台启动成功了吗，通过这个地址能访问吗 ![image](https://user-images.githubusercontent.com/3162115/277901942-e799deff-7a6b-43cc-84da-78139d869779.png)

后台启动了，但是打开这个地址会有错误提示：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55084864/f477f7f5-48ea-4f7e-8601-e07dedea9188)

**Comment by tb2888** [comment]
> 你后台启动成功了吗，通过这个地址能访问吗 ![image](https://user-images.githubusercontent.com/3162115/277901942-e799deff-7a6b-43cc-84da-78139d869779.png)
不好意思，打扰了，这个问题是我电脑有个移动网咯的问题，取的我移动网咯的IP，禁掉移动网咯就好了！localhost:9999也可以打开了
