### ISSUE TITLE
Online表单中限定了上传文件数量，实际生成代码未生效，缺少参数maxCount

### ISSUE THREAD

**Issue by DewsLi** [jeecgboot/jeecg-boot#5508]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online表单中限定了上传文件数量，实际生成代码中未生效，因为缺少了参数maxCount，加上这个参数以后能够限制文件上传数量了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18074622/63691171-a58b-4e20-9bda-019f6fcdc937)

![image](https://github.com/jeecgboot/jeecg-boot/assets/18074622/bc71062c-1b3b-4ef9-aa43-d9cd6334db63)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码生成后，手工调整即可，不是所有的配置项都支持生成，更多的是online在线使用
