### ISSUE TITLE
测试微服务模块下的rabbitmq产生的问题

### ISSUE THREAD

**Issue by MaTengfei513** [jeecgboot/jeecg-boot#5509]
### 问一下简单的问题就不用模板了
`jeecg-boot\jeecg-server-cloud\jeecg-visual\jeecg-cloud-test\jeecg-cloud-test-rabbitmq`
想要测试一下rabbitmq，看到这个模块下没有启动类，想问一下作者没有启动类的模块需要自己创建启动类和配置文件吗？
自己创建以后启动就报错了
`No bean of type 'org.apache.shiro.realm.Realm' found.`

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/f6941f72-583c-4063-b13f-33dbe7c813e9)
