### ISSUE TITLE
乐观锁在更新失败时，返回给前端的Json内容却是“编辑成功”

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5510]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
为了测试乐观锁，按文档添加了 update_count 字段 以及 @Version 注释，每次保存时 update_count 会 +1。

在保存前，手动修改了记录的 update_count 字段，然后再点击前端页面的【保存】按钮，记录确实没有更新，但前端也没有显示“记录已经被修改，无法更新！”这类的提示信息，后端返回的结果为：
{
    "success": true,
    "message": "编辑成功!",
    "code": 200,
    "result": "编辑成功!",
    "timestamp": 1698290770762
}

正常情况下，乐观锁在更新失败后，应该返回给前端错误信息，而不是成功。

##### 截图&代码：
![1698291125013](https://github.com/jeecgboot/jeecg-boot/assets/127393297/b089284c-9f1c-4b5d-b4f4-77a3df73da2f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
那个功能？

**Comment by citynook** [comment]
@zhangdaiscott 我自己新建的页面，不过可以用【仪表盘设计器】这个功能测试，这个功能对应的表中也添加了乐观锁的字段，但在保存时，即使锁的字段值被手动修改了，记录虽然没有保存成功，但也不会报错，是同样的效果。

**Comment by citynook** [comment]
@zhangdaiscott 澄清一下，【仪表盘设计器】虽然有乐观锁的字段，但返回给前端的数据中 updateCount 值一直是 null，即使手动在表里修改了字段值，在保存的时候也一样会成功，对乐观锁的判断没有生效。

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
仪表盘设计器测试未发现你说的问题，请截图描述你问题的复现过程
![image](https://github.com/jeecgboot/jeecg-boot/assets/65587928/64fa98ac-4be3-40d5-89cb-56a6ea76406b)

**Comment by citynook** [comment]
暂时先关闭此问题，待有时间再详细验证。
