### ISSUE TITLE
引入第三方JAR包 部署失败

### ISSUE THREAD

**Issue by rehe0216** [jeecgboot/jeecg-boot#5511]
##### 前端版本：vue3版？还是 vue2版？   
vue3

##### 截图&代码：

<img width="953" alt="fba1fabc2a47ed5adecad06b0eaf76d" src="https://github.com/jeecgboot/jeecg-boot/assets/149066934/307ddde0-2c7a-4292-92f9-96bc5ed8fb39">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己改的问题，请自己排查
