### ISSUE TITLE
<BasicTable>标签汇总栏的滚动条和tbody的不同步

### ISSUE THREAD

**Issue by tzzt01** [jeecgboot/jeecg-boot#5513]
##### 问题描述：
<BasicTable>标签通过useListPage公共页面方法设置 showSummary: true 的方式使用“合计”功能时，tbody和合计栏都出现了x方向的滚动条，并且拖动滚动条不同步。
我看到ant design 新版本已经解决了这个问题，如果不升级ant版本，有没有办法解决？如果必须升级ant版本的话，有指导手册吗？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/16750040/1809f924-023d-41a7-8fa6-ad7f4ee46bb4)
![image](https://github.com/jeecgboot/jeecg-boot/assets/16750040/c5227df6-d7c5-4b48-95d9-0f802d9ef47b)
![image](https://github.com/jeecgboot/jeecg-boot/assets/16750040/6a8d01e5-e1b4-45aa-8dc6-2299001bdf7b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
3.5.5+版本修复过这个问题。
针对这个问题进行了两次改动：
第一次是滚动同步（代码在src/components/Table/src/BasicTable.vue）
第二次是隐藏了合计栏的滚动条即最新版。（代码在src/components/Table/src/components/TableFooter.vue）


<img width="971" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/b35d060a-b935-4aba-b402-1faea83362a8">
<img width="1064" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/710d57bb-5dff-4648-96a4-3999779d25b2">
