### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by KoToXir** [jeecgboot/jeecg-boot#5516]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
登陆时有个报错的Notification框一闪而过，报错内容为【Cannot destructure property 'userInfo' of '(intermediate value)' as it is undefined】

##### 截图&代码：
初步排查为src\store\modules\user.ts文件的afterLoginAction方法的末尾，在return data前，执行了一块特殊的逻辑：
`window.open(redirect, '_self')
return;`
导致上层函数接收不到userInfo的信息，查看git历史发现是3.6.0的那次提交8ff3f4db252d017e917295478b059ad35ccf1a7e合入的相关代码，望排查修复

**Comment by zhangdaiscott** [comment]
已经安排

**Comment by zhangdaiscott** [comment]
更新代码把
