### ISSUE TITLE
微服务登录报错getTenantNoCancel

### ISSUE THREAD

**Issue by 1395961821** [jeecgboot/jeecg-boot#5518]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
微服务启动登录报错，无法正常使用系统：Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/31942432/b8015224-e0ff-4c4d-a955-54991bc1d741)
![image](https://github.com/jeecgboot/jeecg-boot/assets/31942432/d0e776a1-78df-4834-850c-e0557faa2829)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是下载的默认版本？还是增量升的级

**Comment by 1395961821** [comment]
> 你是下载的默认版本？还是增量升的级

最新默认版本

**Comment by zhangdaiscott** [comment]
你跟下代码，看看这块，微服务模式我们测试过没问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/6ef45eca-3db5-4598-b633-963122f9b552)

**Comment by 1395961821** [comment]
重新拉取部署一套，还是不行，可能是我电脑的问题，放弃了

**Comment by szh18** [comment]
我的前端vue3也是这个问题，但是我的是登陆成功依然会报错，是因为minilogin页面中那个userInfo没有值，是因为那个data还没返回就直接重定向了

**Comment by zhangdaiscott** [comment]
跟浏览器有关？

**Comment by 1395961821** [comment]
我直接换成服务器跑，没问题了

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/commit/734068c685c031bd1cb5037aa389efb44dacb798

更新这个看看

**Comment by zhangdaiscott** [comment]
再次测试无问题，有问题请再反馈
