### ISSUE TITLE
接口微服务版，nacos从数据表读取配置文件信息接口在哪里找，全局搜找不到接口的位置

### ISSUE THREAD

**Issue by TengflyMa** [jeecgboot/jeecg-boot#5520]
![微信图片_20231031194527](https://github.com/jeecgboot/jeecg-boot/assets/101609997/51a77008-8df0-45af-b328-e8c26ccfcea9)

**Comment by zhangdaiscott** [comment]
？

**Comment by MaTengfei513** [comment]
JeecgBoot后端微服务版本，nacos中读到的配置文件不是从数据库的数据表里面拿的吗？，f12看了一下调了这个接口nacos/v1/cs/configs，传统的方式不是要到把配置文件手动导入到nacos，想看一下这种读表的方式怎么实现的，但是代码里面全局搜索查不到这个接口，想问一下，这个接口在哪里实现的

**Comment by TengflyMa** [comment]
> ？

JeecgBoot后端微服务版本，nacos中读到的配置文件不是从数据库的数据表里面拿的吗？，f12看了一下调了这个接口nacos/v1/cs/configs，传统的方式不是要到把配置文件手动导入到nacos，想看一下这种读表的方式怎么实现的，但是代码里面全局搜索查不到这个接口，想问一下，这个接口在哪里实现的

**Comment by zhangdaiscott** [comment]
可以自己去解读nacos源码
