### ISSUE TITLE
分享的大屏，顶部的菜单可以隐藏吗

### ISSUE THREAD

**Issue by qinjiacheng** [jeecgboot/jeecg-boot#5521]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
请问下这上面的菜单可以隐藏吗

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/19253611/b390e786-b568-4de4-a63f-0dd56fb1d172)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是积木报表不是大屏，大屏可以到这里设计
http://jimureport.com/
