### ISSUE TITLE
项目启动时Quartz没有自动执行任务

### ISSUE THREAD

**Issue by 345L** [jeecgboot/jeecg-boot#5522]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 345L** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/49482890/8e4a8c71-8bef-4369-8c75-c305672d41d3)

**Comment by zhangdaiscott** [comment]
看这块的配置
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/3bfe6590-f5bf-4e86-807b-5dbce58d52d5)
