### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by moumoukings** [jeecgboot/jeecg-boot#5523]
##### 问题描述：
使用admin账户给别的账户分配了权限，然后登录对应账户时还是会报没有权限

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35523332/e129aa02-56b3-42a6-9141-8a6c0cdab542)
![image](https://github.com/jeecgboot/jeecg-boot/assets/35523332/76993868-cc86-47e2-8b67-6592c024366e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by moumoukings** [comment]
退出用户时，没有正常删除redis中保存的权限导致

**Comment by zhangdaiscott** [comment]
退出重新登录了吗

**Comment by moumoukings** [comment]
是的，退出时找到了问题所在，感谢回复谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月1日(周三) 下午5:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 权限问题 (Issue #5523)




 
退出重新登录了吗

**Comment by hjhcos** [comment]
可以把 Redis 配置自动刷新吗
