### ISSUE TITLE
钉钉第三方登录回调地址

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#5524]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
与钉钉集成，justauth配置完钉钉参数，在钉钉H5小程序中运行，提示 应用不存在。

##### 截图&代码：

后台回调地址参数没有。
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/a5fbd435-c2cf-421e-91ee-b0c39c20d099)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
应用不存在 一般就是 client-id 和 client-secret 不正确。你是怎样配置的
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/572ae5f7-eb15-4816-a5ef-5e891f005f5b)

**Comment by snkever** [comment]
justauth里 enabled 都开了，dingtalk 按照钉钉小程序里填的。之前都正常用的。这次版本更新之后才不行的。


| |
snkever
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月10日 17:42 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] 钉钉第三方登录回调地址 (Issue #5524) |

应用不存在 一般就是 client-id 和 client-secret 不正确。你是怎样配置的

**Comment by 1298191366** [comment]
你这是auth登录吧，因为新版anth登录改版了，需要配置租户id，你说的那个开启是控制扫码登录的，请参考新文档尝试一下：https://help.jeecg.com/java/dingdingjicheng.html

**Comment by snkever** [comment]
我按照文档重新配置了，提示

**Comment by 1298191366** [comment]
> 我按照文档重新配置了，提示 Message ID: ***@***.***>

那你能进去吗，对应的租户id是否有对应的租户配置，默认没有租户是0；你把日志截全了看一下

我这测着没问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/ee5d4c3d-4341-4d17-b413-9d3ca384679a)

你把这两个写成一样的试一下
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/ee5d4c3d-4341-4d17-b413-9d3ca384679a)
