### ISSUE TITLE
导出表格的时候在哪里额外的添加其他条件

### ISSUE THREAD

**Issue by WZander** [jeecgboot/jeecg-boot#5525]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/30968914/fc026130-5259-40e3-9cea-64fecaeeaa04)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己扩展导出方法
