### ISSUE TITLE
POI导出一对多只有一条数据时，疯狂打印错误日志

### ISSUE THREAD

**Issue by lq-java** [jeecgboot/jeecg-boot#5528]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

POI导出一对多只有一条数据时，疯狂打印错误日志，查看了源码，这个几年前有人提过issues #1840 ，官方回复说是解决了，但我查看了源代码，就是加了一个try-catch，并且打印了一个日志就完了。
##### 截图&代码：
下图为源代码，这个地方是每个单元格都会走的地方，也就是说一行如果有20个单元格，会打印20条错误日志，行数多了以后，日志非常多。个人认为此处只需要加一个判断maxHeight>1才能走合并单元格的逻辑就可以。这种try-catch捕获异常并打印了一条日志的办法有点不妥
![image](https://github.com/jeecgboot/jeecg-boot/assets/59862687/a24b41ca-55e3-415b-b257-fc4dd6b856a8)

另外下图中此处源代码的地方也有多处这么处理的地方
![image](https://github.com/jeecgboot/jeecg-boot/assets/59862687/12dbbffc-7f4f-499e-8ab9-5bf8b88ee645)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
已对图1加判断处理，图2以及其它相同处理处，与图1逻辑不同，个人认为不需要处理

**Comment by zhangdaiscott** [comment]
已修复，autopoi 升级到 1.4.7即可解决

**Comment by lq-java** [comment]
> 已修复，autopoi 升级到 1.4.7即可解决

1.4.7的包还没放到中央仓库呢吗？依赖下不下来，去中央仓库搜了一下，最新的1.4.6

**Comment by zhangdaiscott** [comment]
配置jeecg私服
