### ISSUE TITLE
AUTO在线表单导出null

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#5529]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
AUTO在线表单导出excel 显示null，后台显示null
##### 截图&代码：

![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/39754681-c588-4ce0-93f0-379cb416b849)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
应该是字典配置有问题，确认下配置

**Comment by snkever** [comment]
有一个字典返的子项返回了空值，过滤掉空值就正常了
