### ISSUE TITLE
使用AUTO表单代码生成的页面导入产生空白行

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#5530]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用AUTO表单导入都能成功的，但是使用前端AUTO代码生成的页面导入产生空白行，后端报错。

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/4d99ff86-f873-4cbf-bbb5-a2b0d928409e)

![图片](https://github.com/jeecgboot/jeecg-boot/assets/28818320/a0c9d9df-a2cd-400e-b36b-055e386f96f2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
导入的格式不一致？

**Comment by zhangdaiscott** [comment]
生成代码后，先导出模板，再用这个模板导入，模板不一定一致

**Comment by snkever** [comment]
用楼主的方法可以成功的。我比较了下，就是导出模板里多了表头和导出人，行标题都一样的
