### ISSUE TITLE
Online报表【选择行】导出报错

### ISSUE THREAD

**Issue by snkever** [jeecgboot/jeecg-boot#5532]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online报表【选择行】导出报错

##### 截图&代码：

{"success":false,"message":"SQL执行失败：\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause'\n### The error may exist in URL [jar:file:/usr/local/jeecg/jeecg-system-start-3.6.0.jar!/BOOT-INF/lib/hibernate-re-3.5.3.jar!/org/jeecg/modules/online/cgreport/mapper/xml/OnlCgreportHeadMapper.xml]\n### The error may involve defaultParameterMap\n### The error occurred while setting parameters\n### SQL: SELECT COUNT(*) AS total FROM (SELECT p.project_name '项目名称', p.isc '项目编号', m.category '材料种类', m.project_contact '项目联系人', m.color '颜色', m.archive '存档材料', CONCAT(\"http://app.9m-design.com:8088/material.\", url_encode(m.number), \".html\") '二维码编码内容', m.location '存放位置' FROM tb_material m JOIN tb_project p ON p.isc = m.project) jeecg_rp_temp WHERE jeecg_rp_temp.id = ?\n### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause'\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'jeecg_rp_temp.id' in 'where clause'","code":500,"result":null,"timestamp":1698892130990}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
scott

**Comment by zhangdaiscott** [comment]
测试了下，没发现问题，请提供重现步骤
