### ISSUE TITLE
租户管理员如何配置产品套餐

### ISSUE THREAD

**Issue by zmj-upupup** [jeecgboot/jeecg-boot#5534]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在租户下的创建用户，配置权限是通过产品套餐配置， 但是这个套餐，租户管理员能授权的套餐只能在租户管理模块下创建套餐，看官方文档租户管理又属于平台管理员所用。 相当于租户管理员要给下面的用户配置产品套餐的话， 这些套餐必须提前由平台管理员配置好。因此租户管理员没法自定义产品套餐，这样是否有局限呢？

##### 截图&代码：

<img width="764" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/94438796/3a56059e-ea58-4bb2-8a5f-87c9b3351387">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是这样设计的，你不可能让租户任意配置权限，肯定是平台设计好规则，哪些租户有哪些权限

**Comment by zmj-upupup** [comment]
> 是这样设计的，你不可能让租户任意配置权限，肯定是平台设计好规则，哪些租户有哪些权限

比如说租户管理员有10个权限， 下面的用户只想赋予其中的5个权限， 按照这个设计， 那就只能是跟租户管理员一样拥有10个全新了。

**Comment by zhangdaiscott** [comment]
那个是默认套餐，你可以让管理员给你配置个性化套餐
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/ce3281f6-4341-45df-8bb1-97c1220af67c)

**Comment by zmj-upupup** [comment]
> 那个是默认套餐，你可以让管理员给你配置个性化套餐 ![image](https://user-images.githubusercontent.com/3162115/280589621-ce3281f6-4341-45df-8bb1-97c1220af67c.png)

大佬好， 是这样的，我明白这里可以配置套餐，但是需要管理员配置， 我现在的需求是这样的， 平台管理员给租户配置一个套餐，比如有10个菜单权限。  然后租户管理员下面去创建多个用户， 有的用户只想赋予租户管理员那10个菜单其中的5个权限 ， 这个目前只能通过平台管理员重新创建一个5个权限的套餐实现是吧？   没有办法做到租户管理员的权限部分授予给下面的租户是吧
