### ISSUE TITLE
BUG，导入excel，获取到公式

### ISSUE THREAD

**Issue by Tangcool** [jeecgboot/jeecg-boot#5537]
##### 版本号：
3.5.3

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
autopoi版本是1.4.5
autopoi导入，如果单元格是另一个单元格+xxx，报错，类型是时间格式，获取不到底层单元格的值，获取到的是A1+30(加入A1单元格是2023-01-01)

##### 截图&代码：
![1111](https://github.com/jeecgboot/jeecg-boot/assets/39690619/1494318d-fd6a-4b7b-8dda-ba19e393f7bd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持表达式
