### ISSUE TITLE
导出表格设置了数字格式导出之后仍然是文本格式，并且无法进行计算

### ISSUE THREAD

**Issue by duangdangding** [jeecgboot/jeecg-boot#5538]
##### 版本号：
当前最新版本： 3.4.3-GA（发布日期：2022-10-31） 

##### 问题描述：
导出表格设置了数字格式导出之后仍然是文本格式，并且无法进行计算

##### 错误日志&截图：
![image](https://github.com/jeecgboot/JimuReport/assets/38204865/19f8f263-3b53-467d-b72f-5fb2873bef65)
![image](https://github.com/jeecgboot/JimuReport/assets/38204865/f1692bf2-8699-43e7-84d3-13f3d1727275)
而且修改之后小箭头又出来了
![image](https://github.com/jeecgboot/JimuReport/assets/38204865/b0a339c1-63e7-4cfa-96c1-04eea158ef4f)
使用计算函数也不可以计算
![image](https://github.com/jeecgboot/JimuReport/assets/38204865/a6d6d026-a066-476d-87ac-c9b2e976741b)
结果没有计算
![image](https://github.com/jeecgboot/JimuReport/assets/38204865/6b84e485-dee1-4675-bda4-3a8a379d7de8)

#### 友情提示（为了提高issue处理效率）：
  - 积木报表是一款免费报表产品，功能免费源码不开放;
  - 未按格式要求发帖，会被直接删掉;
  - 请针对问题提供[[报表设计配置或SQL脚本]](https://help.jeecg.com/jimureport/issues.html)或在官网制作报表示例并提供ID;
  - 针对不好重现的问题，请录制操作视频或详细的重现步骤；

**Comment by zhangdaiscott** [comment]
autopoi可以升级到最新版，印象中处理过了

**Comment by duangdangding** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/38204865/51cf1c48-3b0b-4671-8ee6-7f10244db867)
![image](https://github.com/jeecgboot/jeecg-boot/assets/38204865/4f0e9e07-6679-44b1-a829-be336c45a18e)
我刚刚看了官网 然后升级了版本 
![image](https://github.com/jeecgboot/jeecg-boot/assets/38204865/b6fa3b93-20a1-404d-a5f3-70924ff0df7d)
导出之后还是一样呢

**Comment by zhangdaiscott** [comment]
sq

**Comment by zhangdaiscott** [comment]
已修复，autopoi 升级到 1.4.7即可解决

**Comment by duangdangding** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/38204865/dc721e16-a6f6-4f6c-bba3-751d7ff12f9b)
这个方法是不是也更新了，这部分代码在哪能找到呢
ImportFileServiceImpl，ImportFileServiceI这两个文件

**Comment by duangdangding** [comment]
找到了 一样的内容
