### ISSUE TITLE
如何只有一个账号不能两个人同时在线

### ISSUE THREAD

**Issue by 15098731779** [jeecgboot/jeecg-boot#5539]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
想设置同一个账号，如果第二个人登录会把第一个人顶下去

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
登录token都存在redis中，有个在线用户菜单，可以根据这个自己扩展
