### ISSUE TITLE
单体启动服务system报错

### ISSUE THREAD

**Issue by shuaidiao** [jeecgboot/jeecg-boot#5540]
##### 版本号：
3.6.0

##### 问题描述：
单体服务启动system报错数据库找不到

##### 截图&代码：

![QQ图片20231106101438](https://github.com/jeecgboot/jeecg-boot/assets/42376214/7e119e65-f684-433e-b619-26a51b3d4c7d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by shuaidiao** [comment]
我把代码生成器bean注释就可以了，什么原因

**Comment by zhangdaiscott** [comment]
你删了代码生成器的配置文件了？

**Comment by shuaidiao** [comment]
没有，并且这个数据库也不是读的我配置的，这个jeecg_database哪来的
#mysql
diver_name=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:9111/wccg-boot?useUnicode=true&characterEncoding=UTF-8
username=root
password=123456
database_name=wccg-boot
