### ISSUE TITLE
使用数据权限功能时，添加数据规则不生效

### ISSUE THREAD

**Issue by ddww** [jeecgboot/jeecg-boot#5541]
##### 问题描述：
使用Online生成的代码模块后，在该模块下：
使用数据权限功能时，添加数据规则，不生效。参考官网给出文档https://help.jeecg.com/java/system/dataauth/use.html。经过多次配置，数据规则始终不生效

##### 截图&代码：
参考官网给出文档https://help.jeecg.com/java/system/dataauth/use.html，配置，数据规则不生效

**Comment by zhangdaiscott** [comment]
你的权限配置截图，详细说明

**Comment by ddww** [comment]
> 你的权限配置截图，详细说明

好的，第一步，登录管理员账号，进入菜单管理，选择我自定义的一级菜单，然后添加数据规则。
![image](https://github.com/jeecgboot/jeecg-boot/assets/29270868/ceb67e47-0506-451b-9c58-0893e6b75150)
第二步，点击角色管理，给管理员角色赋权限。保存数据规则
![image](https://github.com/jeecgboot/jeecg-boot/assets/29270868/5983f340-3148-4992-b794-77d4f4eb07cf)
第三步，退出管理员账号，在登录。到配置数据规则的模块，发现数据规则，自己定义的数据规则是，只查询a8数据，现在情况是，所有数据都查出来了。有没有大佬碰到这种问题，或者给一些解决思路。
![image](https://github.com/jeecgboot/jeecg-boot/assets/29270868/8325ad87-795a-4c6f-9f17-e585d36897a3)
