### ISSUE TITLE
达梦数据库代码生成，导入表报错

### ISSUE THREAD

**Issue by a546109781** [jeecgboot/jeecg-boot#5542]
##### 版本号：

生成插件1.4.4

##### 前端版本：vue3版？还是 vue2版？

vue2

##### 问题描述：

saveDbTable2Online 这个方法 当轮询到时间字段时 
var7中的charmaxLength是"0.0" 

{"fieldDbName":"SEND_TIME","fieldName":"sendTime","filedComment":"发送时间","fieldType":"java.util.Date","fieldDbType":"timestamp","classType":"inputxt","classType_row":"","optionType":"","charmaxLength":"0.0","precision":"","scale":"0.0","nullable":"Y","fieldLength":"null","fieldHref":"null","fieldValidType":"null","fieldDefault":"null","fieldShowType":"null","fieldOrderNum":"null","isKey":"null","isShow":"null","isShowList":"null","isQuery":"null","uploadnum":"null","defaultVal":"null","sort":"N","readonly":"N","queryMode":"null","dictField":"null","dictTable":"null","dictText":"null"}

格式化为long时报错

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/8340fcb5-d466-4eba-937d-0ef7349fad39)
![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/72746b59-cea6-45c2-ac7c-45150261b285)
![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/26bc58e4-40ab-4841-aeff-1995069455fa)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
scott

**Comment by zhangdaiscott** [comment]
数据库字段的配置截图看下

**Comment by a546109781** [comment]
> 数据库字段的配置截图看下 我这边测试无问题，导入成功
> 
> ![image](https://user-images.githubusercontent.com/3162115/283797593-fcf39c5f-86c3-4dd8-94ca-53d247636c93.png)

我看了下，只要CHAR_LENGTH是0的类型好像都不行 比如DEC也报错

![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/9842a40c-4776-4ad8-8240-931bf85f6f8a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/d0c416b0-b4bc-4ff1-a213-28eae07eec2c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/f6aaa98a-fc5a-42b0-9a65-78eafc763a01)

**Comment by zhangdaiscott** [comment]
日期为什么要设置小数

**Comment by a546109781** [comment]
> 日期为什么要设置小数

不设置也是这样
这里这个SQL查询出来的结果类型是DEC，会不会是自动把结果集里0变成带小数的0.0了
![image](https://github.com/jeecgboot/jeecg-boot/assets/7327840/2138d601-a7b8-456f-964f-3a38b19b4d81)

**Comment by zhangdaiscott** [comment]
那为什么我们的没问题？

**Comment by zhangdaiscott** [comment]
是的
