### ISSUE TITLE
打包后前端组件异常

### ISSUE THREAD

**Issue by sevenfate** [jeecgboot/jeecg-boot#5543]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
表单中我点击了保存1按钮，一直在加载中，没有响应，也没报错，也没发送请求，但是我点击保存2按钮，正常使用，这是什么原因，怎么解决

##### 截图&代码：
组件：
`    <div style="margin-top: 16px;">
      <a-button type="primary" class="save-button-1" @click="handleSave123">保存1</a-button>
      <a-button type="primary" class="save-button-2" @click="handleSaveAndPost">保存2</a-button>
    </div>
`
用到的函数：
    handleSave123() {
      debugger
      this.$bus.$off('ok111111')
      const that = this
      debugger
      //其他逻辑代码
}
    handleSaveAndPost() {
      //保存并发布
      this.$bus.$off('ok111111')
      const that = this
     //其他逻辑代码
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个代码应该是你自己写的，我们的例子里没有保存1 保存2，请自己排查
