### ISSUE TITLE
MySQL 8.0下当lower_case_table_names=1时启动失败，提示QRTZ前缀表大写

### ISSUE THREAD

**Issue by HorseLuke** [jeecgboot/jeecg-boot#5544]
##### 版本号：

3.5.3

##### 前端版本：vue3版？还是 vue2版？

任意版本

##### 问题描述：

当lower_case_table_names=1时，jeecg boot提示找不到QRTZ前缀表大写：

```
SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = ? FOR UPDATE
java.sql.SQLSyntaxErrorException: Table 'r2023_cbkp.QRTZ_LOCKS' doesn't exist
```

该问题描述即为#1521 ，但看到官方当时关闭了issue。然而目前考虑到MySQL 8.0开始批量采用，并且MySQL明显倾向小写设置即lower_case_table_names=1，故建议官方将所有表小写，或在文档中载明本框架不支持组复制的高可用。

证据有：

1、从8.0.11开始，lower_case_table_names只允许初始化数据库时候定义，任何初始化数据化后再更改lower_case_table_names将导致数据库无法启动：

**It is now prohibited to start the server with a [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) setting that is different from the setting used when the server was initialized.** The restriction is necessary because collations used by data dictionary table fields are determined by the setting defined when the server is initialized, and restarting the server with a different setting would introduce inconsistencies with respect to how identifiers are ordered and compared.

摘自 8.0.11 Changelog：https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-11.html

例子：

```
2023-11-02T14:03:04.5643Z 1 [ERROR] [MY-011087] [Server] Different lower_case_table_names settings for server ('0') and data dictionary ('1').
```

2、MySQL手册指明组复制必须启用lower_case_table_names=1，即所有表小写

**Lower Case Table Names.** Set lower_case_table_names to the same value on all group members. **A setting of 1 is correct for the use of the InnoDB storage engine, which is required for Group Replication.** Note that this setting is not the default on all platforms.

摘自 MySQL 8.0 Reference Manual  /  18.3.1 Group Replication Requirements ：https://dev.mysql.com/doc/refman/8.0/en/group-replication-requirements.html

##### 截图&代码：

无

**Comment by zhangdaiscott** [comment]
设置完参数，需要重新创建库，才算不区分大小写

**Comment by HorseLuke** [comment]
> 设置完参数，需要重新创建库，才算不区分大小写

你好，由于服务器开启了主从复制，并且有可能考虑设置组复制，故只能保持lower_case_table_names=1以满足MySQL官方文档要求。所以建议官方认真考虑改为全小写。MySQL目前的内置表也改为小写了，这会是个趋势。

**Comment by HorseLuke** [comment]
看到官方的初始化sql文件似乎已经是全小写qrtz_locks，我再调查一下原因。

**Comment by HorseLuke** [comment]
协助查询后发现了问题，问题来源于quartz scheduler组件。不是本框架问题，问题关闭。

另附quartz scheduler修改方案：

可尝试修改org.quartz.impl.jdbcjobstore.Constants、org.quartz.impl.jdbcjobstore.StdJDBCConstants
