### ISSUE TITLE
online表单在线生成 功能测试跳转页面404

### ISSUE THREAD

**Issue by limpiditys** [jeecgboot/jeecg-boot#5545]
##### 前端版本：vue3版？还是 vue2版？
这个东西 应该是vue3 vue 生成之后粘贴的vue包下的 里面的

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/100334268/99bd8eae-4e3f-430c-972a-4b6c8c4f3785)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
按照格式发帖

**Comment by zhangdaiscott** [comment]
隐藏路由菜单没有给用户分配权限 auto开头的菜单
