### ISSUE TITLE
Sign 签名校验失败！

### ISSUE THREAD

**Issue by Limxxx** [jeecgboot/jeecg-boot#5546]
##### 版本号：

3.4.4
##### 前端版本：vue3版？还是 vue2版？

vue3版
##### 问题描述：
新建的微服务模块，接口请求出现Sign 签名校验失败

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/48424134/bbfe1218-f015-426e-8940-037542eef278)
![image](https://github.com/jeecgboot/jeecg-boot/assets/48424134/8488c5da-ad50-4219-b0e8-dd9099d48f9e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/48424134/e9adcedd-de5d-4dc3-89ac-aae04a2840c0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以参考下git历史，处理过类似问题

**Comment by Limxxx** [comment]
git历史是3.4.4之后的历史记录吗？我没看到有类似问题？

**Comment by Limxxx** [comment]
> 你可以参考下git历史，处理过类似问题

git历史是3.4.4之后的历史记录吗？我没看到有类似问题？
