### ISSUE TITLE
Online在线开发问题

### ISSUE THREAD

**Issue by xjx-rgb** [jeecgboot/jeecg-boot#5548]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
接手了一个老项目代码 、用这个框架的 上一个开发剥离可一些功能。
现在导致online表单在线开发无法使用 接口一直报404 找不到怎么解决。
后端找不到这个接口。不知道上一个开发改动了哪里 或者删除了哪里。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/65055614/3e8fe0ff-c4b4-45e6-87c5-10837370286c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/65055614/6b896092-aab6-48c0-bc2c-7d180e371902)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是删除了online的依赖jar吧

**Comment by xjx-rgb** [comment]
请问online是那个依赖，找不到哎



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月8日(周三) 中午11:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] Online在线开发问题 (Issue #5548)




 
是删除了online的依赖jar吧
