### ISSUE TITLE
点击表单开发菜单进入页面后提示资源找不到

### ISSUE THREAD

**Issue by ZorionS01** [jeecgboot/jeecg-boot#5552]
##### 截图&代码：

![Uploading Snipaste_2023-11-09_10-39-22.png…]()
![图片](https://github.com/jeecgboot/jeecg-boot/assets/106093796/7a7c20d3-bae0-4622-ba24-37e5b617e7c1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台依赖有问题
