### ISSUE TITLE
想请问仪表盘/门户设计器有开源计划吗，有的话什么时候开源

### ISSUE THREAD

**Issue by suyang1023** [jeecgboot/jeecg-boot#5553]
看到官方文档上有说仪表盘设计器即将开源，想确认下大概开源时间。
![image](https://github.com/jeecgboot/jeecg-boot/assets/11532782/39a873d2-1581-4c5d-bdc0-73e33b3169f7)

**Comment by zhangdaiscott** [comment]
功能已经放出来了

**Comment by suyang1023** [comment]
> 功能已经放出来了

是在jeect-boot中能用，但是不开源我们不好单独用到别的项目中，现在jimureport已经集成到我们项目中且用的非常棒，但是仪表盘设计器貌似不好集成到我们项目中

**Comment by zhangdaiscott** [comment]
积木报表版本已经在规划
