### ISSUE TITLE
前端菜单管理是否可以跳转外部连接？能否动态带参？

### ISSUE THREAD

**Issue by cxyax** [jeecgboot/jeecg-boot#5554]
##### 版本号：
2.4

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
前端菜单管理是否可以跳转外部连接？能否动态带参？

##### 截图&代码：
菜单配置相关

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2043933

**Comment by cxyax** [comment]
携带的参数我想要携带当前登录部门的id或者code值，而不是配置文件中的静态值，这种可以实现吗？
