### ISSUE TITLE
jeecgboot的导入功能，当我导入的文件是xlsx格式的excel时，报错了。当上传文件是xls，就没有这个报错，这是为什么？

### ISSUE THREAD

**Issue by xxb1** [jeecgboot/jeecg-boot#5555]
##### 问题描述：
jeecgboot的导入功能（我没有修改过），当我导入的文件是xlsx格式的excel时，报错了。当上传文件是xls，就没有这个报错，这是为什么？
数据可以导入进去，但是会有报错，文件流似乎没有关闭，但是代码里流已经关了
##### 截图&代码：
![S1$ ZY`Z~YK~ 4HJFWJO_N5](https://github.com/jeecgboot/jeecg-boot/assets/54920974/6d3775d2-2e34-4206-aeac-7cc8e18507e2)

![image](https://github.com/jeecgboot/jeecg-boot/assets/54920974/38108b08-55d4-4813-8bc1-d13e6356e7a0)
![1699585148814](https://github.com/jeecgboot/jeecg-boot/assets/54920974/dc9a3699-3da5-41ee-bf8f-9e952e9540af)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这说明导入没适配对应的格式，按照要求来

**Comment by xxb1** [comment]
但是，我使用了错误的格式，也应该关闭文件流啊。如果用户一直上传错误的格式的excel，可能会内存泄漏，导致程序挂掉的吧

![1699588430801](https://github.com/jeecgboot/jeecg-boot/assets/54920974/96237708-53a2-4f81-83a1-f002725779fc)

**Comment by xxb1** [comment]
> 这说明导入没适配对应的格式，按照要求来

但是，我使用了错误的格式，也应该关闭文件流啊。如果用户一直上传错误的格式的excel，可能会内存泄漏，导致程序挂掉的吧
![image](https://github.com/jeecgboot/jeecg-boot/assets/54920974/fa0bc825-99ea-449b-82ec-258d0fe2743f)

**Comment by xxb1** [comment]
> 这说明导入没适配对应的格式，按照要求来
我这么改，问题就解决了，大佬，你看一下。    =.=
import lombok.Cleanup;

![image](https://github.com/jeecgboot/jeecg-boot/assets/54920974/fdb779fb-4710-4e18-b2d2-784f4aa54bb6)
