### ISSUE TITLE
sentinel配置文件修改账号密码，logging.level.pattern 等配置无效！

### ISSUE THREAD

**Issue by fengbindev** [jeecgboot/jeecg-boot#5556]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/28595220/6a22161b-9c44-4305-9a73-b248fa933785)

**Comment by EightMonth** [comment]
logging.pattern配置已检查，是生效的，麻烦检查user.home/logs/csp/sentinel-block.log日志文件。
用户名密码配置不生效，后续已修改成sentinel.dashboard.auth.username/password

**Comment by fengbindev** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/28595220/dfdaebfd-91d6-4154-a36c-2d89893ef46f)
请再检查一下 jeecg-cloud-sentinel 工程的配置，使用 application.yml 里的 logging.pattern 配置 sentinel-dashboard.log 文件格式 不起作用，需要写在application.properties文件里面才生效，应该是配置文件优先级问题，sentinel自带的包里面的application.properties会优先加载

**Comment by EightMonth** [comment]
并不是这个问题，核心原因是因为alibaba sentinel 1.8.3版本存在bug，如何引用sentinel-nacos-source依赖，会导致本地application配置对sentinel失效，导致sentinel加载默认配置。这个bug在1.8.4版本修复了，但是jeecg-sentinel引用的还是sentinel 1.8.3版本，该问题已上报社区。
你也可以看我的提交，我做的临时处理，看是否需要这两个配置一起临时处理下，或者你本地也可以参考我这样临时处理的写法补充下。
