### ISSUE TITLE
在线报表

### ISSUE THREAD

**Issue by zjtyxy** [jeecgboot/jeecg-boot#5557]
##### 问题描述：
报表设置了字典，字典条数不能超过10条

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
啥意思？

**Comment by zjtyxy** [comment]
就是在线报表如果配置了了字典翻译，这时候如果你使用查询，下拉框中只有前10条，看了一下代码，用的是page查询，只会返回第一页，
翻译字典列的时候，也是只有字典table中的前10条能被翻译。







图中所属量表有19条，只显示10条




在 2023-11-10 19:42:02，"JEECG" ***@***.***> 写道：

啥意思？

**Comment by zhangdaiscott** [comment]
看不到图

**Comment by zjtyxy** [comment]
图发到附件里了













在 2023-11-13 09:36:19，"JEECG" ***@***.***> 写道：

看不到图
