### ISSUE TITLE
j-vxe-table中多级表头中无法单元格编辑

### ISSUE THREAD

**Issue by QWK-001** [jeecgboot/jeecg-boot#5558]
##### 截图&代码：

```
 <j-vxe-table
          ref="table"
          keep-source
          row-number
          :dataSource="list"
          :columns="columns"
>


columns:[{
          title: '年龄',
          dataIndex: 'age',
          key: 'age',
          width: 200,
          align: 'center',
          type: JVXETypes.inputNumber
        },
 {
          title: '用户表头',
          align: 'center',
          children: [
 {
              title: '名字',
              dataIndex: 'name',
              key: 'name',
              width: 200,
              align: 'center',
type: JVXETypes.inputNumber
            },
]}
```
年龄可以编辑，名字却无法编辑

**Comment by zhangdaiscott** [comment]
截图看效果

**Comment by QWK-001** [comment]
他们没修复，我自己另外写了一个。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月23日 20:52 |
| 收件人 | jeecgboot/jeecg-boot ***@***.***> |
| 抄送人 | 瞿伟康 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] j-vxe-table中多级表头中无法单元格编辑 (Issue #5558) |

我也遇到了，这个问题解决了吗

**Comment by QWK-001** [comment]
快速点的解决方案就用element 或者react 的组件封装一个，根据自己的业务场景来。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月23日 20:58 |
| 收件人 | jeecgboot/jeecg-boot ***@***.***> |
| 抄送人 | 瞿伟康 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [jeecgboot/jeecg-boot] j-vxe-table中多级表头中无法单元格编辑 (Issue #5558) |

他们没修复，我自己另外写了一个。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2024年04月23日 20:52 | | 收件人 | jeecgboot/jeecg-boot @.> | | 抄送人 | 瞿伟康 @.>, Author @.> | | 主题 | Re: [jeecgboot/jeecg-boot] j-vxe-table中多级表头中无法单元格编辑 (Issue #5558) | 我也遇到了，这个问题解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

可以共享学习下吗
