### ISSUE TITLE
docker启动后, /drag/page 仪表盘不能展示

### ISSUE THREAD

**Issue by balzaron** [jeecgboot/jeecg-boot#5561]
##### 截图&代码：

<img width="1520" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/9757578/164ebd1d-ee37-49f2-8dac-63edbf5006cd">
前台日志返回200
<img width="1665" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/9757578/1dc981b3-83ef-4f57-a7eb-b58733486b80">

**Comment by zhangdaiscott** [comment]
不通外网吧？

**Comment by balzaron** [comment]
不是不通外网哦, 其他功能都是正常的, 只有仪表盘设计器访问的localhost
