### ISSUE TITLE
Online在线功能打开一直转圈，控制台报错

### ISSUE THREAD

**Issue by chenjs1989** [jeecgboot/jeecg-boot#5565]
#### 友情提示（为了提高issue处理效率）：
  Online在线功能打开一直转圈，控制台报错
![微信图片_20231113153626](https://github.com/jeecgboot/jeecg-boot/assets/55540650/7240c3a8-9536-4eed-a72c-1873f6fa0cb9)

**Comment by zhangdaiscott** [comment]
版本太老了，建议升版本

**Comment by chenjs1989** [comment]
版本升级影响比较大，之前是没有问题的，导致这个问题的原因是什么，是否有其他的解决方法

**Comment by zhangdaiscott** [comment]
你只能自己分析了
