### ISSUE TITLE
quartz 不支持 oracle

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#5570]
##### 版本号：
3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
quartz 在oracle环境下会卡死，执行语句为
SELECT * FROM QRTZ_LOCKS WHERE SCHED_NAME = 'MyScheduler' AND LOCK_NAME = 'TRIGGER_ACCESS' FOR UPDATE

**Comment by tianxingdao** [comment]
我也遇到了

**Comment by zhangdaiscott** [comment]
你可以单独执行仪表quartz 的初始化sql
