### ISSUE TITLE
菜单布局顶部一级菜单，侧边栏子级菜单如何设置？

### ISSUE THREAD

**Issue by Xgs97** [jeecgboot/jeecg-boot#5573]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如何将菜单布局改为左侧子菜单，顶部一级菜单样式

##### 截图&代码：
![菜单布局需求](https://github.com/jeecgboot/jeecg-boot/assets/136789176/3b8638b4-89df-422c-abd0-c2693ac97495)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by xu8117** [comment]
有解决方案了吗，可以分享下吗
