### ISSUE TITLE
租户隔离问题

### ISSUE THREAD

**Issue by arno-yu** [jeecgboot/jeecg-boot#5574]
##### 版本号：
gitee的master分支

##### 前端版本：
vue3版

##### 问题描述：
租户隔离问题
开始租户隔离未配置sys_dict表参与隔离,打印的sql和显示的数据表明参与了隔离

##### 截图&代码：

MybatisPlusSaasConfig中配置
public static final Boolean OPEN_SYSTEM_TENANT_CONTROL = true;
static {
        //1.需要租户隔离的表请在此配置
        if (MybatisPlusSaasConfig.OPEN_SYSTEM_TENANT_CONTROL) {
            //a.系统管理表
            //TENANT_TABLE.add("sys_role");
            //TENANT_TABLE.add("sys_user_role");
            TENANT_TABLE.add("sys_depart");
            TENANT_TABLE.add("sys_category");
            TENANT_TABLE.add("sys_data_source");
            TENANT_TABLE.add("sys_position");
        }
打印的sql为:
SELECT COUNT(*) AS total FROM sys_dict WHERE del_flag = 0 AND (tenant_id = ?)

**Comment by zhangdaiscott** [comment]
版本号

**Comment by arno-yu** [comment]
v3.6.0

**Comment by zhangdaiscott** [comment]
字典这块的数据隔离是通过逻辑编码实现的
https://help.jeecg.com/javaback/saas.html

**Comment by myitsite** [comment]
超级管理员就读取不到租户为0的字典
