### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wmm-wrb** [jeecgboot/jeecg-boot#5576]
##### 问题描述：
Could not resolve placeholder 'cas.prefixUrl' in value "${cas.prefixUrl}"

##### 截图&代码：
Could not resolve placeholder 'cas.prefixUrl' in value "${cas.prefixUrl}"

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你改了什么，还是默认什么都没改启动

**Comment by wmm-wrb** [comment]
我没有改动  重新下载了一遍依赖  正常启动了   谢谢

**Comment by GerhardYang** [comment]
我遇到和你一样的问题，是idea编码问题，这两个地方设置为utf-8就好了，希望其他遇到同样问题的小伙伴能看到快速解决问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/23150744/cdf5dfea-63d3-4e80-b5bc-6ad6a6927231)

**Comment by hjhcos** [comment]
我是关闭IDEA，重新加载Maven解决的
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/d83203c4-04f1-48f7-ae33-850d7f80efbd)
