### ISSUE TITLE
BasicTable组件全选和取消全选时不触发事件；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5577]
##### 问题描述：
BasicTable组件全选和取消全选时不触发事件；

##### 截图&代码：
<BasicTable @register="registerTable" :rowSelection="rowSelection">
      </BasicTable>

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/9f78ffed-c896-40b4-b40a-fc11945ee9e4)

onSelectInvert和onSelectAll不触发；

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/90ca0a00-2515-4076-bd84-6dadf48aec48)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。（全选和取消全选都是触发的onSelectAll事件，通过selected参数可知道是全选还是反选。同antd的用法）。

你本地可按如下图修改：



<img width="767" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/2f446061-1a44-4c86-b1b0-5319b6ef938b">

let changeRows: Recordable[] = [];
let allSelected: boolean = false;

<img width="889" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/2cbfaa3f-cbb1-4fd6-aa34-87a1e5a936a0">

if (unref(propsRef)?.rowSelection?.onSelectAll) {
      allSelected = checked;
      changeRows = getInvertRows(selectedRows.value);
    }

<img width="638" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/b5805b8b-20c4-4932-834c-f35320586a54">

<img width="592" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/2d2e0019-362c-45fd-b66c-44e6e3c9d205">

<img width="903" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/dc2200f5-c51d-471c-a608-560c16d68fbf">

if (mode == 'all') {
      const rowSelection = unref(propsRef)?.rowSelection;
      if (rowSelection?.onSelectAll) {
        rowSelection.onSelectAll(allSelected, toRaw(getSelectRows()), toRaw(changeRows));
      }
    }

<img width="936" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/e4ae82f6-c2f0-47aa-9920-dc3ca98adca5">

function getInvertRows(rows: any): any{
    const allRows = findNodeAll(
      toRaw(unref(flattedData)),
      () => true,
      {
      children: propsRef.value.childrenColumnName ?? 'children',
    });
    if (rows.length === 0 || rows.length === allRows.length){
      return allRows;
    } else {
      const allRowsKey = allRows.map((item) => getRecordKey(item));
      rows.forEach((rItem) => {
        const rItemKey = getRecordKey(rItem);
        const findIndex = allRowsKey.findIndex((item) => rItemKey === item);
        if (findIndex != -1) {
          allRowsKey.splice(findIndex, 1);
          allRows.splice(findIndex, 1);
        }
      });
    }
    return allRows;
  }
