### ISSUE TITLE
BUG：导入excel出错 

### ISSUE THREAD

**Issue by williamhatch** [jeecgboot/jeecg-boot#5578]
##### 版本号：

3.6.0
##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：

在低代码开发模式中测试ok，但是在菜单栏中报错，不能识别该文件。

文件格式如下：

最新公告日	证券代码	证券简称
20230426	H01832.HK	哈萨克斯坦石油
该文件在mac 的wps生成。

我发现路径也不一样：
admin的路径是：jeecgboot/online/cgform/api/importXls/7bafa1f29e1f4205bb13d49dd04ee1f6
但是菜单那里是别的：xxx/importExcel 就是你的controller

##### 截图&代码：

<img width="1217" alt="截屏2023-11-17 06 08 54" src="https://github.com/jeecgboot/jeecg-boot/assets/40409716/07548bd0-f424-4b2f-a964-df6c81c4d4ba">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复问题，不是发过了吗
