### ISSUE TITLE
BasicForm表单中第一次就使用复制粘贴操作input框，规则校验没触发

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5579]
##### 问题描述：
第一次就使用复制粘贴操作input框，规则校验没触发，input组件trigger设置了trigger: ['change', 'blur'],都没用

##### 截图&代码：

{
    label: '密码',
    field: 'password',
    component: 'StrengthMeter',
    componentProps: {
      autocomplete: 'new-password'
    },
    dynamicRules: ({ model, schema }) => {
      return [
        { required: true },
        {
          validator: (rule: any, value: any) => {
            const reg = /^[\u4E00-\u9FA5]+$/;
            const regSpace = /\s/;
            if (reg.test(value)) {
              return Promise.reject('密码不能含有中文');
            } else if (regSpace.test(value)) {
              return Promise.reject('不能输入含有空格的字符');
            } else if (value && (value.length < 6 || value.length > 18)) {
              return Promise.reject('请输入6-18位字符');
            } else {
              return Promise.resolve();
            }
          },
          trigger: ['change', 'blur'],
        },
      ];
    },
  },

**Comment by RacingK93** [comment]
并且第一次输入的时候获取到的value值是undefined，需要再次change才能获取上一次的值，第一次都是不对的。
备注：只有StrengthMeter组件有这个问题，Input组件没问题；

**Comment by RacingK93** [comment]
StrengthMeter这个组件真的在校验必填上有毒啊，把我搞死了，搞一天了，拜托官方紧急看看

**Comment by RacingK93** [comment]
{
    label: '密码',
    field: 'password',
    component: 'StrengthMeter',
    required: true,
    rules: [
      { required: true, message: '请输入密码！', trigger: 'blur' },
      {
        validator: (rule: any, value: any) => {
          const reg = /^[\u4E00-\u9FA5]+$/;
          const regSpace = /\s/;
          console.log('password', password.value);
          if (!password.value) {
            return Promise.reject('');
          } else {
            if (reg.test(password.value)) {
              return Promise.reject('密码不能含有中文');
            } else if (regSpace.test(password.value)) {
              return Promise.reject('不能输入含有空格的字符');
            } else if (
              password.value &&
              (password.value.length < 6 || password.value.length > 18)
            ) {
              return Promise.reject('请输入6-18位字符');
            } else {
              return Promise.resolve();
            }
          }
        },
        trigger: 'blur'
      },
    ],
    componentProps: ({ formModel, formActionType }) => {
      return {
        autocomplete: 'new-password',
        onChange: async (e: any) => {
          console.log('onChange', e);
          password.value = e;
          const {
            setFieldsValue,
          } = formActionType;
          await setFieldsValue({ password: e });
        },
      };
    },
  },

我用这种方式才让密码完美运行；

但是这个操作不大众，不是所有人都能这么写的，还是要改组件的逻辑；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可按如下图进行修改：
在src/components/StrengthMeter/src/StrengthMeter.vue文件中
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/39478d66-b657-46f9-951e-cf7b2336169b)
