### ISSUE TITLE
使用默认page分页的时候in不起作用

### ISSUE THREAD

**Issue by chaixingtan** [jeecgboot/jeecg-boot#5580]
##### 版本号：
3.6.0（发布日期：2023-10-23） 
##### 问题描述：
使用默认page分页的时候in不起作用

##### 截图&代码：
 LoginUser sysUser = (LoginUser) SecurityUtils.getSubject().getPrincipal();
        List<String> classIfyIds = sysUserRoleMapper.getRoleUserClassIfy(sysUser.getId());
        if (Objects.nonNull(classIfyIds) && classIfyIds.size() > 0) {
            queryWrapper.in("type_id",classIfyIds);
        }
        Page<CmsArticle> page = new Page<>(pageNo, pageSize);
        IPage<CmsArticle> pageList = cmsArticleService.page(page, queryWrapper);

#### 友情提示（为了提高issue处理效率）：

  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你把sql日志打印出来，看看执行的sql是怎么样的

**Comment by chaixingtan** [comment]
请问下sql日志在哪里打开呢

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/a0017eb0-0725-4c6c-8ef6-fc86b313b5df)
