### ISSUE TITLE
多租户 积木报表api接口取数据没带上tenantId

### ISSUE THREAD

**Issue by gdgzczh** [jeecgboot/jeecg-boot#5581]
##### 版本号：
积木报表 1.6.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
多租户下，积木报表的 数据源用api 取数时，在后台没有把传递的x-tentant-id 或tentantid  继续传递到真正取数据的接口上

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by zhangdaiscott** [comment]
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot-starter</artifactId>
  <version>1.6.6</version>
</dependency>
