### ISSUE TITLE
Springboot单体项目升级Cloud Nacos启动报错

### ISSUE THREAD

**Issue by pinktigerkk** [jeecgboot/jeecg-boot#5582]
##### 截图&代码：
<img width="1066" alt="667f3bb6baa01e5f7dfb11486a124444" src="https://github.com/jeecgboot/jeecg-boot/assets/45219794/74bcf652-5b91-4b4c-835c-841bf2676806">
<img width="1063" alt="9a8d59c871f2b1e864cb9bee130a0a93" src="https://github.com/jeecgboot/jeecg-boot/assets/45219794/e299a681-504b-45f3-8f52-861666531c5e">
<img width="560" alt="c1cb3ab3fe9da53ac40f930e03f1ad4f" src="https://github.com/jeecgboot/jeecg-boot/assets/45219794/8029f8b0-dba9-4ba9-802e-dbb2c600f8c3">
<img width="1082" alt="b395151cf24e12d0dea982cfdcaee977" src="https://github.com/jeecgboot/jeecg-boot/assets/45219794/27c4d89d-c282-41e2-a570-26d06f0be234">

我全部是按照官方文档操作步骤来的实在不知道到底是哪一步出现了问题

**Comment by zhangdaiscott** [comment]
数据库联上了吗
