### ISSUE TITLE
远程加载表格，如何单页排序不调用接口。

### ISSUE THREAD

**Issue by Ryanx1001** [jeecgboot/jeecg-boot#5583]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
远程加载表格，如何单页排序不调用接口。
目前因为数据量比较大，每次排序时都会调用查询接口，这样的话点击排序时返回数据会有延时，影响使用体验。请问应该怎么操作才能单页排序不调用接口。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果你的数据是远程接口获取，排序不调用接口不现实，或者你不分页，一次性把数据加载出来，前端自己排序
具体实现看antd官方文档
