### ISSUE TITLE
请问积木报表兼容IE浏览器嘛

### ISSUE THREAD

**Issue by jackqweqwe123** [jeecgboot/jeecg-boot#5584]
##### 截图&代码：

图1
![1e95b6c0caa55e08ad5777903e1f2e1](https://github.com/jeecgboot/jeecg-boot/assets/151148816/7c738955-5b5a-4af7-ba5a-91f78776327c)

图2
![微信图片_20231117183048](https://github.com/jeecgboot/jeecg-boot/assets/151148816/6edb05bb-35de-4e88-852a-71917cda917a)

**Comment by zhangdaiscott** [comment]
不兼容
