### ISSUE TITLE
basicTable中formConfig设置alwaysShowLines无效

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/jeecg-boot#5585]
##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
在basicTable组件中的formConfig配置里添加alwaysShowLines属性无效，还是显示一行

##### 截图&代码：

```js
// 注册table数据
const { tableContext } = useListPage({
  tableProps: {
    title: 'alwaysShowLines无效',
    api: list,
    columns,
    canResize: false,
    formConfig: {
      schemas: getSearchForm.value,
      alwaysShowLines:2, // 设置后还是只显示一行查询条件
    },
    actionColumn: {
      width: 300,
      fixed: 'right',
    },
  },
})

```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
补充版本号和截图效果
