### ISSUE TITLE
vue2积木报表没有数据

### ISSUE THREAD

**Issue by gh503** [jeecgboot/jeecg-boot#5586]
##### 版本号：
Jeecg  Boot Version: 3.0
Spring Boot Version: 2.3.5.RELEASE (v2.3.5.RELEASE)
MySQL 5.7
org.jeecgframework.jimureport   1.4.0

##### 问题描述：积木报表没有数据
按指导部署http://report.jeecg.com/2078875，没有数据展示

##### 截图&代码：
当前网络不能提供截图，问题和这个链接的图一状态一样，http://report.jeecg.com/2506684
但是项目路径是没有问题的

@Component
public class JimuReportTokenService implements JmReportTokenServiceI {
    @Autowired
    private ISysBaseAPI sysBaseAPI;
    @Autowired
    @Lazy
    private RedisUtil redisUtil;

    @Override
    public String getToken(HttpServletRequest request) {
        return TokenUtils.getTokenByRequest(request);
    }

    @Override
    public String getUsername(String token) {
        return JwtUtil.getUsername(token);
    }

    @Override
    public Boolean verifyToken(String token) {
        return TokenUtils.verifyToken(token, sysBaseAPI, redisUtil);
    }

    @Override
    public Map<String, Object> getUserInfo(String token) {
        String username = JwtUtil.getUsername(token);
        //此处通过token只能拿到一个信息 用户账号  后面的就是根据账号获取其他信息 查询数据或是走redis 用户根据自身业务可自定义
        SysUserCacheInfo userInfo = sysBaseAPI.getCacheUser(username);
        Map<String, Object> map = new HashMap<String, Object>();
        //设置账号名
        map.put(SYS_USER_CODE, userInfo.getSysUserCode());
        //设置部门编码
        map.put(SYS_ORG_CODE, userInfo.getSysOrgCode());
        // 将所有信息存放至map 解析sql/api会根据map的键值解析
        return map;
    }
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
图文并茂，没有数据是什么意思？

**Comment by zhangdaiscott** [comment]
自己改的，我们无法分析
