### ISSUE TITLE
nginx使用https 上传文件出现跨域

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#5587]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/2be4f450-06fa-40ee-879d-1c3b5c41540c)

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/f8f31d86-c573-4df5-b1d8-803d34c83b2e)

![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/9acb8e5f-d7ef-46f8-bc69-22393d0688de)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是不是前端是https,后端不是https，前后端保存一致

**Comment by hutianxi** [comment]
> 是不是前端是https,后端不是https，前后端保存一致
大佬 但是后端发布出来的网关地址是http的呀  采用的是微服务版本  现在的情况是 前端部署到nginx中配置了ssl启用了https  上传就出现了上述问题

**Comment by zhangdaiscott** [comment]
必须一致
