### ISSUE TITLE
员工管理修改姓名

### ISSUE THREAD

**Issue by zflzqy** [jeecgboot/jeecg-boot#5592]
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
员工管理修改姓名，邮箱和手机号不生效，查看代码，发现只改了workNo

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
补充操作截图

**Comment by zflzqy** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/38182329/444c1a5d-c2bf-4151-8b3c-c3da8957d223)
最终调用的
![image](https://github.com/jeecgboot/jeecg-boot/assets/38182329/086f3883-d4e5-45e2-a7db-f81ebd0ca421)
这个方法，但是并没有修改用户手机号等信息，如果这里不打算修改，是不是前端也要禁用输入框

**Comment by zhangdaiscott** [comment]
界面是你自己的界面，接是我们的，这种我们无法分析
