### ISSUE TITLE
默认加入test角色，加入test角色后会导致出现没有配置过的菜单目录

### ISSUE THREAD

**Issue by java1c** [jeecgboot/jeecg-boot#5596]
##### 版本号：

3.6.0
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
开启租户的时候 如果没有test角色，默认加入test角色，加入test角色后会导致出现没有配置过的菜单目录。这个问题如何解决？

##### 截图&代码：
List<SysPermission> permissionList = this.sysPermissionMapper.queryByUser(username);
		//================= begin 开启租户的时候 如果没有test角色，默认加入test角色================
		if (MybatisPlusSaasConfig.OPEN_SYSTEM_TENANT_CONTROL) {
			if (permissionList == null) {
				permissionList = new ArrayList<>();
			}
			List<SysPermission> testRoleList = sysPermissionMapper.queryPermissionByTestRoleId();
			//update-begin-author:liusq date:20230427 for: [QQYUN-5168]【vue3】为什么出现两个菜单 菜单根据id去重
			for (SysPermission permission: testRoleList) {
				boolean hasPerm = permissionList.stream().anyMatch(a->a.getId().equals(permission.getId()));
				if(!hasPerm){
					permissionList.add(permission);
				}
			}
			//update-end-author:liusq date:20230427 for: [QQYUN-5168]【vue3】为什么出现两个菜单 菜单根据id去重
		}
		//================= end 开启租户的时候 如果没有test角色，默认加入test角色================
		return permissionList;
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
test就是为了给注册用户一些默认的权限，你可以针对test角色调整权限授权
