### ISSUE TITLE
Online在线表单功能，填值规则调用无效

### ISSUE THREAD

**Issue by wyerp** [jeecgboot/jeecg-boot#5598]
##### 截图&代码：

tjbpm(row){
  alert('提交流程')
  console.log('row',row)
}

bt1(){
   console.log('that.table.selectionRows',this.selectedRowKeys)
   console.log('that.table.selectedRowKeys',this.selectedRows)
   alert('激活全部数据')
  putAction('/sys/fillRule/executeRuleByCode/order_num_rule').then(res=>{
    if (res.success){
        console.log('order_num_rule',res.result)
        console.log('order_num_rule',res)
      alert(res)
    }
    })
  
}

控制台返回结果：
{
    "success": true,
    "message": "",
    "code": 200,
    "result": null,
    "timestamp": 1700636967020
}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wyerp** [comment]
![获取订单号](https://github.com/jeecgboot/jeecg-boot/assets/15017225/a10b98d8-8b16-47f7-9ce2-d4a10048a5f2)

**Comment by zhangdaiscott** [comment]
F12看看接口返回的什么

**Comment by wyerp** [comment]
我的问题，调用填值规则的编码写错了，不过，没有的填值规则编码，是否应该报错“填值规则”不存在？

**Comment by wyerp** [comment]
> F12看看接口返回的什么

返回的是null，原因是我把天之规则为编码写错了
