### ISSUE TITLE
同步数据库时报错

### ISSUE THREAD

**Issue by a805034104** [jeecgboot/jeecg-boot#5600]
##### 截图&代码：
![Uploading 图片.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by a805034104** [comment]
![QQ图片20231122163623](https://github.com/jeecgboot/jeecg-boot/assets/130194654/7d621a52-78c6-4e53-9e74-d29b4b41d641)

**Comment by zhangdaiscott** [comment]
版本太老了，无法支持

**Comment by a805034104** [comment]
但是我其他项目还是可以正常的，也是用的这个版本的
