### ISSUE TITLE
麻烦请教下，如何获取jeecg设置的系统主题颜色，在style中设置

### ISSUE THREAD

**Issue by Ryanx1001** [jeecgboot/jeecg-boot#5602]
##### 版本号：
3.6.0 微服务版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
麻烦请教下，如何获取jeecg设置的系统主题颜色，在style中设置。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/config/index.html
