### ISSUE TITLE
ONLINE表单，填值规则通用单据编号

### ISSUE THREAD

**Issue by wyerp** [jeecgboot/jeecg-boot#5606]
##### 问题描述：现在需要每个单据自己写一个编号类，是否可以做一个通用的类，通过传入参数后，按照一定的规则，自定生成单据号，比如2位前缀CN+8位年月日20231123+4位流水号【CN2023111230001】，或2位前缀KH+6位年月202311+5位流水号【KH20231100001】,这种场景在ERP软件中应用较多
![编码规则设置](https://github.com/jeecgboot/jeecg-boot/assets/15017225/028c7ebb-a349-45eb-a695-218f749d0687)

##### 截图&代码：
发了一个ERP软件的编码规则配置截图，好像无效，需要的话单独发给你们吧

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你自己写一个填值规则就行了
https://help.jeecg.com/java/advanced/fillValRule.html
https://help.jeecg.com/online/form/comp/rule.html
