### ISSUE TITLE
页码设置

### ISSUE THREAD

**Issue by Yxw521** [jeecgboot/jeecg-boot#5607]
##### 截图&代码：
![8332136aabb754e84a22417612223423](https://github.com/jeecgboot/jeecg-boot/assets/76502207/5b7391fd-1e9c-4805-be1e-ebf5f254c3ac)

**Comment by zhangdaiscott** [comment]
dd

**Comment by Yxw521** [comment]
> DD的

请问下个版本能支持吗

**Comment by lvdandan16** [comment]
参考文档：https://help.jeecg.com/jimureport/7.pagenumset.html

**Comment by Yxw521** [comment]
> 参考文档：https://help.jeecg.com/jimureport/7.pagenumset.html

这个只能设置显示位置，我想自定义显示什么样式页码，可以定制吗
