### ISSUE TITLE
建议省市区组件可以默认只显示某个省

### ISSUE THREAD

**Issue by maxid** [jeecgboot/jeecg-boot#5609]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
项目只需要某省数据
目前通过分类字典解决

建议省市区组件可以设置只显示某个省数据，简化开发

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
jeecg的目的是输出功能性组件，而非业务组件。如果需要定制化最好建议自己完成，否则jeecg难调众口。
