### ISSUE TITLE
整体风格主题背景色如何修改，求教

### ISSUE THREAD

**Issue by WebFE0415** [jeecgboot/jeecg-boot#5610]
##### 版本号：
2.4.6

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
整体风格主题背景色如何修改，求教

##### 截图&代码：
![809F9393-F5D3-49D7-B5DE-EA4C2183761C](https://github.com/jeecgboot/jeecg-boot/assets/63940128/71b54655-fb28-4b10-91ed-a7e935d15ca3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/65560db3-02f8-4db1-9820-849a4535bfb4)

**Comment by EightMonth** [comment]
本身就自带主题配置功能，你把这个功能放开就好了，自己给隐藏掉了
