### ISSUE TITLE
js增强触发弹窗提示文件不存在

### ISSUE THREAD

**Issue by zyx13544359595** [jeecgboot/jeecg-boot#5612]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：
js增强触发弹窗提示文件不存在

##### 截图&代码：
报错截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/66946053/57af1d23-9a4a-4687-98d4-dc4893d80e1b)
文件截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/66946053/944806e1-dca7-4d9a-9281-f5c625a5fa16)
js增强截图
![image](https://github.com/jeecgboot/jeecg-boot/assets/66946053/a2548c92-a9f3-4daa-9dd9-20c120236844)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本有点老，升级到最新版试试

**Comment by zyx13544359595** [comment]
![~J$}2(YB71F4B85MPY_%_R4](https://github.com/jeecgboot/jeecg-boot/assets/66946053/2d1eaf6e-68ef-4b5f-b9ee-53166278abca)
我升级了还是不行,我看到源码里面这个allModules参数是空的,所以导致了找不到这是什么原因呢

**Comment by zhangdaiscott** [comment]
那可能开源版本不支持这么用
