### ISSUE TITLE
docker 部署前端后, 仪表盘设计不能正确显示

### ISSUE THREAD

**Issue by balzaron** [jeecgboot/jeecg-boot#5619]
##### 问题描述：docker 部署前端后, 仪表盘设计不能正确显示, 查看后台接口走的是127.0.0.1:8080
其他功能正常, 请问如何处理?

##### 截图&代码：

<img width="1567" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/9757578/598dbc76-4369-473b-8cff-e9e49e331aad">

**Comment by zhangdaiscott** [comment]
ZJ

**Comment by balzaron** [comment]
> 使用的是我们提供docker file脚本吗

是的, 前端除了增加一个ssl配置, 其他都一样, 启动起来后发现只有drag/page 仪表盘这里会去访问127.0.0.1:8080 其他的正常访问域名地址

**Comment by EightMonth** [comment]
首先我需要讲一下docker的概念，docker概念每一个容器如果不在同一网络（network）内，127.0.0.1仅仅指在单个容器内，而不是宿主机，然后启动前程工程容器时，最好是修改两个地方，1。如文档如说的.env.production。2修改Dockerfile，将这两个文件里面的jeecg-boot-system，替换为真实IP即可，以下是我启动无问题的图
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/8bfd0197-5d3f-49c1-ba7f-2db136238cf6)

**Comment by EightMonth** [comment]
修改这两个文件之后，需要重新打包和打镜像

**Comment by EightMonth** [comment]
不知道是否可以提供服务器IP\用户名、密码，如果可以的话，麻烦提供QQ，我加你，我连你服务器帮忙看下

**Comment by EightMonth** [comment]
也需要执行一下docker rmi，删除之前的镜像
