### ISSUE TITLE
elasticsearch配置能否增加适应账号密码设置，增加安全性

### ISSUE THREAD

**Issue by CenMinghao** [jeecgboot/jeecg-boot#5620]
##### 版本号：
3.5.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
elasticsearch配置能否增加适应账号密码设置，增加安全性

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/29631645/32ea48ba-7298-491c-b720-9a41d798f075)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以自己扩展
