### ISSUE TITLE
使用restTemplate的post请求时出现链接超时的情况

### ISSUE THREAD

**Issue by jackfangyijun** [jeecgboot/jeecg-boot#5621]
##### 问题描述：
使用restTemplate的post请求时出现链接超时的情况；

报错信息：2023-11-30 15:18:37.887 [http-nio-8091-exec-4] ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:79 - I/O error on POST request for "http://crm.aussino.net:8088/service/queryBillInfo": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://crm.aussino.net:8088/service/queryBillInfo": Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out；

尝试解决：
方式1：
![image](https://github.com/jeecgboot/jeecg-boot/assets/147577207/7ae1d55d-df1c-4298-9c60-177f6ce38264)

方式2：

<img width="944" alt="21926b4fd213d02d395446ca83cbeaa" src="https://github.com/jeecgboot/jeecg-boot/assets/147577207/33ae88c2-5e0f-4aeb-b158-90a4bd1ae73a">

##### 截图&代码：
   @ApiOperation("1审批单据接口访问")
    @PostMapping("/approverBill")
    public JSONObject approverBill(@RequestBody ApproverBillReqvo approverBillReqvo){
        //实体类转换成JSONObject对象
        JSONObject params =JSONObject.parseObject(JSONObject.toJSONString(approverBillReqvo));

        JSONObject data = RestUtil.post(approverBill, params);

        return data;
    }

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是自己的实现代码，我们无法支持
