### ISSUE TITLE
jeecg-boot/mreport/testonnection Api接口未进行身份验证

### ISSUE THREAD

**Issue by Programmer-Eric** [jeecgboot/jeecg-boot#5622]
##### 版本号：
3.3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：

扫描到高危漏洞

##### 截图&代码：
<img width="902" alt="c594bd9778819545f7005b4010d0dcc" src="https://github.com/jeecgboot/jeecg-boot/assets/37928066/4db3834a-0a4c-4e23-9956-6d1dda47f4f6">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
早修复过了，升级 积木报表到最新版
http://jimureport.com/doc/log

**Comment by Programmer-Eric** [comment]
好的，谢谢了
________________________________
发件人: JEECG ***@***.***>
发送时间: 2023年12月1日 10:58
收件人: jeecgboot/jeecg-boot ***@***.***>
抄送: Programmer-Eric ***@***.***>; Author ***@***.***>
主题: Re: [jeecgboot/jeecg-boot] jeecg-boot/mreport/testonnection Api接口未进行身份验证 (Issue #5622)


早修复过了，升级 积木报表到最新版
http://jimureport.com/doc/log

―
