### ISSUE TITLE
校验失败，存在SQL注入风险！表名不合法，存在sql注入风险!--->aa wher name like '%a%'

### ISSUE THREAD

**Issue by wlbxh** [jeecgboot/jeecg-boot#5624]
##### 问题描述：
表单配置出现：校验失败，存在SQL注入风险！表名不合法，存在sql注入风险!--->aa wher name like '%a%'错误提示。

##### 截图&代码：
校验失败，存在SQL注入风险！表名不合法，存在sql注入风险!--->aa wher name like '%a%'
![image](https://github.com/jeecgboot/jeecg-boot/assets/152263539/e409b5ff-6e87-4c69-a75c-69a7261af09d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/152263539/aef42037-c2b3-4c55-b0db-f1b695178d56)
这个问题需要怎么处理呢？请大佬指点，谢谢。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本号错误
