### ISSUE TITLE
XxlJobAdmin 怎么配置成nacos

### ISSUE THREAD

**Issue by zrbg153359** [jeecgboot/jeecg-boot#5626]
##### 问题描述：
现在XxlJobAdmin只能使用配置文件配置数据库信息、不好切换数据库配置那些、怎么配置成nacos读取数据？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/39120309/f6e98175-93d8-4907-8520-541c6ecdb5fd)

![image](https://github.com/jeecgboot/jeecg-boot/assets/39120309/20aea0d5-8bf0-4cfd-94fb-8d52346cc422)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
有两种方式：
1.引入spring cloud alibaba

<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
</dependency>

<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
</dependency>
在配置文件中配置nacos连接信息即可
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        
  2.引入原生nacos config
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>2.0.0</version> 
</dependency>
在配置文件中nacos连接信息
# Nacos 配置
nacos.config.server-addr=127.0.0.1:8848
nacos.config.namespace=your-namespace
在代码里面获取nacos配置信息并自行配置
import com.alibaba.nacos.api.config.ConfigService;
import com.alibaba.nacos.api.config.annotation.NacosValue;

public class YourJobClass {

    // 使用 Nacos 注解获取配置值
    @NacosValue(value = "${your.config.key:default-value}", autoRefreshed = true)
    private String yourConfigValue;

    // 或者通过 Nacos API 获取配置
    public String getYourConfigValueFromNacos() {
        // 使用 NacosConfigService 获取配置
        ConfigService configService = NacosFactory.createConfigService("your-nacos-config");
        try {
            String config = configService.getConfig("your-data-id", "your-group", 5000);
            // 处理获取到的配置信息
            return config;
        } catch (Exception e) {
            // 处理异常
            return "default-value";
        }
    }
}
