### ISSUE TITLE
新增加的租户管理员，自带了系统管理权限

### ISSUE THREAD

**Issue by hold-day-day** [jeecgboot/jeecg-boot#5628]
##### 截图&代码：

![WX20231204-170837](https://github.com/jeecgboot/jeecg-boot/assets/4271480/2fdd4f64-4a81-407f-9014-0feb9f413387)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
系统默认角色test，自动注册租户用户会默认分配这个角色

**Comment by hold-day-day** [comment]
租户下的普通用户，不需要系统管理的菜单，怎么操作呢。

**Comment by zhangdaiscott** [comment]
test角色的权限去掉

**Comment by hold-day-day** [comment]
用户角色中并没有显示test这个角色
![2](https://github.com/jeecgboot/jeecg-boot/assets/4271480/e7507eac-23d6-4688-a96e-b54d07a0f79c)

**Comment by Fnckerpoi** [comment]
租户管理员管理自己的租户用户+角色；我们应该用我的租户提供的租户管理、租户用户、租户角色去管理；
还是应该把系统用户、系统角色提供给租户管理？
