### ISSUE TITLE
路由跳转报错(偶发)

### ISSUE THREAD

**Issue by kingAJIN** [jeecgboot/jeecg-boot#5629]
##### 截图&代码：
![err](https://github.com/jeecgboot/jeecg-boot/assets/129887992/50dd37f9-87d6-47b1-a649-07ce5f54b7b1)
   

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题，如果你能提供重现步骤，我们才可处理
