### ISSUE TITLE
短信接口配置了，但是出现该账号下找不到对应模板。

### ISSUE THREAD

**Issue by wlbxh** [jeecgboot/jeecg-boot#5633]
##### 版本号：vue3版
Jeecg  Boot Version: 3.6.0
Spring Boot Version: 2.7.10 (v2.7.10)

##### 问题描述：
短信接口配置了，但是出现如下错误。
请大佬帮忙指点。
{Code:isv.SMS_TEMPLATE_ILLEGAL,Message:该账号下找不到对应模板,RequestId:A48A9454-11EE-57B6-9C3A-EF934B501F9F,BizId:null}

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你需要在阿里后台配置模板，然后修改jeecgboot项目中编码
org\jeecg\common\constant\enums\DySmsEnum.java
