### ISSUE TITLE
online报表配置时，如果使用的数据源是动态数据源，参数名称必须加上"self_“才起作用

### ISSUE THREAD

**Issue by edwinlly** [jeecgboot/jeecg-boot#5635]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在使用online报表配置时，如果使用的数据源是动态数据源，在配置报表参数后，参数不起作用，需要手动在url中的参数名称前手动加上“self_“才可以起作用。
看了一下代码，使用本地数据源的就没有问题，因为代码里面做了兼容判断

##### 截图&代码：
数据源为本地的代码，var9和var10分别针对参数名带"self_"和不带的
                OnlCgreportParam var8 = (OnlCgreportParam)var7.next();
                Object var9 = params.get("self_" + var8.getParamName());
                Object var10 = params.get(var8.getParamName());
                String var11 = "";
                if (var9 != null) {
                    var11 = var9.toString();
                } else if (var9 == null && oConvertUtils.isNotEmpty(var10)) {
                    var11 = var10.toString();
                } else if (var9 == null && oConvertUtils.isNotEmpty(var8.getParamValue())) {
                    var11 = var8.getParamValue();
                }

数据源为动态的，可以看到var14取值的时候，直接强行加上了"self_"
            if (var11 != null && var11.size() > 0) {
                for(Iterator var12 = var11.iterator(); var12.hasNext(); sql = sql.replace("${" + var13.getParamName() + "}", var15)) {
                    var13 = (OnlCgreportParam)var12.next();
                    Object var14 = params.get("self_" + var13.getParamName());
                    var15 = "";
                    if (var14 != null) {
                        var15 = var14.toString();
                    } else if (var14 == null && oConvertUtils.isNotEmpty(var13.getParamValue())) {
                        var15 = var13.getParamValue();
                    }
                }
            }

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl
