### ISSUE TITLE
用户属于多个组织、怎么通过orgCode做数据筛选？

### ISSUE THREAD

**Issue by zrbg153359** [jeecgboot/jeecg-boot#5639]
##### 问题描述：
![image](https://github.com/jeecgboot/jeecg-boot/assets/39120309/36969cc1-342d-4d4a-8959-6a0f1a1a4fdb)
用户属于多个组织、怎么通过orgCode做数据筛选？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
无回复，关闭
