### ISSUE TITLE
分布式独立数据源 dictTable

### ISSUE THREAD

**Issue by pljay** [jeecgboot/jeecg-boot#5643]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35439240/841f4bca-cf81-4c6a-86f1-27ab94df1287)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by hutianxi** [comment]
@Dict(dictTable = "`ku`.biao", dicText = "fanyi", dicCode = "id")  "库".表 这样写试一下呢

**Comment by EightMonth** [comment]
参考此文档
https://help.jeecg.com/java/java/annotation.html

**Comment by zhangdaiscott** [comment]
你可以扩展下这个字典注解

1、字典注解加一个参数 数据源key

对应配置多数据源
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/d747e2f0-082c-4750-a229-b2efe7ebc1b7)

2、扩展字典拦截器，判断有数据源key注解，自动切换数据源
org\jeecg\common\aspect\DictAspect.java

3、如何切换数据源，参考
src/main/java/org/jeecg/config/mybatis/interceptor/DynamicDatasourceInterceptor.java

**Comment by pljay** [comment]
> @dict(dictTable = "`ku`.biao", dicText = "fanyi", dicCode = "id") "库".表 这样写试一下呢

必须是同源数据库

**Comment by pljay** [comment]
> 你可以扩展下这个字典注解
> 
> 1、字典注解加一个参数 数据源key
> 
> 对应配置多数据源 ![image](https://private-user-images.githubusercontent.com/3162115/290102197-d747e2f0-082c-4750-a229-b2efe7ebc1b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTEzNzcsIm5iZiI6MTcwMjQ1MTA3NywicGF0aCI6Ii8zMTYyMTE1LzI5MDEwMjE5Ny1kNzQ3ZTJmMC0wODJjLTQ3NTAtYTIyOS1iMmVmZTdlYmMxYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDcwNDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTg3OWNlYjcxZTk0MzY4OTkzYzQ1MWU3NGE3NjQ1Nzc4MGI0YzAyZjdhOGQ2ODFkOGJhNGVkNjdhMWI1ZTA2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VFOW5DCXYBbitzZVWIOiSeMgmR108KxRiZ_YumsP0_k)
> 
> 2、扩展字典拦截器，判断有数据源key注解，自动切换数据源 org\jeecg\common\aspect\DictAspect.java
> 
> 3、如何切换数据源，参考 src/main/java/org/jeecg/config/mybatis/interceptor/DynamicDatasourceInterceptor.java

我试一下，这种方式

**Comment by zhangdaiscott** [comment]
cr
