### ISSUE TITLE
新建用户第一次登陆时, 无法获取当前登陆人orgCode

### ISSUE THREAD

**Issue by monikaforever** [jeecgboot/jeecg-boot#5644]
##### 问题描述：

管理员新建一个有一个所属部门的用户,  这个用户在第一次登陆时, 前端无法获取到当前登陆人的orgCode; 第二次登陆后就可以正常获取orgCode

##### 截图&代码：

代码截取自 LoginController 中的 userInfo(SysUser sysUser, Result<JSONObject> result) 方法;
![image](https://github.com/jeecgboot/jeecg-boot/assets/33828109/6c154aec-939b-4727-9458-9534add30d75)

**Comment by zhangdaiscott** [comment]
版本有点老，自己处理吧，印象中处理过类似的bug，可以查查提交记录
