### ISSUE TITLE
Online表单开发使用功能测试出现了问题，无法解决。

### ISSUE THREAD

**Issue by lightbluedeep** [jeecgboot/jeecg-boot#5645]
##### 问题描述：
使用Online表单的生成代码功能的功能测试无法打开。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/71800287/77d2bd1e-6b8d-4b3a-b7fc-77afd88695b9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/71800287/74551941-4118-472a-8b61-b24274318c4e)

下面是我所设置得自动生成表单得字段
![image](https://github.com/jeecgboot/jeecg-boot/assets/71800287/069a604d-3945-45e1-b2bb-4bc71d599c31)

以下是我的页面属性配置
![image](https://github.com/jeecgboot/jeecg-boot/assets/71800287/06ac276b-39df-44e6-b6a8-f0114ab41d0d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
无回复，关闭
