### ISSUE TITLE
关于系统的权限问题

### ISSUE THREAD

**Issue by zxw-wxz** [jeecgboot/jeecg-boot#5646]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
创建了租户并且租户套餐里面只设置了 系统管理、Dashboard、低代码开发、消息中心。在登录租户里面的账号后创建了一个部门，在设置部门权限时发现这个部门权限里面的权限树居然还能看到租户套餐以外的权限。创建部门角色时也是一样的，部门角色配置角色权限也可以查询到租户套餐以外的权限。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/73735918/39f888bc-974c-4c47-86af-962bb15043b5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
错别字改改

**Comment by zhangdaiscott** [comment]
部门权限这块我们没改造，没打算租户还有这个概念
目前租户的权限只能通过租户套餐来设置

**Comment by startLight2019** [comment]
翻看了历史issue，看来有好多人对多租户的使用存在很大困扰，个人认为jeecg-boot做的租户这块不知道是不是不严谨还是说说明文档没说明白，提个中肯的建议，是否可以出个文档专门拿个例子演示下这块多租户的使用
