### ISSUE TITLE
打包之后，页面反应速度特别慢

### ISSUE THREAD

**Issue by IIIIIIIIF** [jeecgboot/jeecg-boot#5647]
##### 问题描述：
打包之后，页面反应速度特别慢，特别是后端获取权限的接口，循环了9w次，请问如何优化呢？？点击登录之后，权限不返回，页面就不会跳转，就会很长时间的白屏，然后每次页面刷新和跳转都会请求一次权限，就会非常卡

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
在浏览器不要把禁用缓存打开，在nginx  的 http模块增加配置，
    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;
    gzip                on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/jpeg image/png image/gif image/jpg;

    expires max;
    add_header Cache-Control public;



本质上就是服务器配置不行

**Comment by zhangdaiscott** [comment]
开启nginx压缩

**Comment by hypo1986** [comment]
遇到同样的问题，nginx都配置了也不行，本地运行没问题，服务器上只要刷新都卡很长时间，就是卡在权限的接口那
