### ISSUE TITLE
安全漏洞怎么解决

### ISSUE THREAD

**Issue by liruibingniubi** [jeecgboot/jeecg-boot#5651]
##### 版本号：

不知道
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
安全漏洞

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/105581852/2b46bb08-f87b-42b3-97d9-a7ebde307d2c)

**Comment by liruibingniubi** [comment]
平台未授权访问漏洞

**Comment by liruibingniubi** [comment]
![图片](https://github.com/jeecgboot/jeecg-boot/assets/105581852/4491d9b2-7e7e-408e-a3fc-8b8ca208efc3)

**Comment by zhangdaiscott** [comment]
老版本自己看升级日志或者搜issue
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/a2d573f0-1d7a-47f6-bf43-d23a5dd57153)
