### ISSUE TITLE
一个页面调用多个接口，这时token失效或者报错时，右侧会根据调用接口数量弹出，请问如何修改为只弹出一个

### ISSUE THREAD

**Issue by lhpdemo** [jeecgboot/jeecg-boot#5656]
##### 版本号：

3.2.0
##### 前端版本：vue3版？还是 vue2版？

2
##### 问题描述：

一个页面调用多个接口，这时token失效或者报错时，右侧会根据调用接口数量弹出，请问如何修改为只弹出一个
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/97373576/3468d595-90e6-407d-b339-b07977b76148)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化的需求，请自己扩展啊
