### ISSUE TITLE
请问代码生成，是否支持parent_id为bigint类型，目前测试发现只支持varchar类型

### ISSUE THREAD

**Issue by yangkebiao** [jeecgboot/jeecg-boot#5657]
##### 问题描述：
请问代码生成，是否支持parent_id为bigint或者int类型，目前测试发现只支持varchar类型

##### 截图&代码：
这是parent_id设置为int类型的样子
![1702365204830](https://github.com/jeecgboot/jeecg-boot/assets/17536440/72e3b994-681a-4f9a-81a4-15cbea633087)
![1702365222303](https://github.com/jeecgboot/jeecg-boot/assets/17536440/0dbc33a4-b2af-434c-9199-b296dfd091ea)

这是parent_id设置为Strngtring类型的样子
![image](https://github.com/jeecgboot/jeecg-boot/assets/17536440/72ba8a35-1253-4c74-99fc-61db48e94ebc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前默认只适配vachar类型
