### ISSUE TITLE
生成的前端代码，树展开后，点击搜索，展开按钮会消失

### ISSUE THREAD

**Issue by yangkebiao** [jeecgboot/jeecg-boot#5662]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/17536440/8a129fd4-5fc1-4df5-849d-c9a4e98e09c7)
![image](https://github.com/jeecgboot/jeecg-boot/assets/17536440/55e5c83a-c459-4a27-ba25-c941495d8de3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前是这样
