### ISSUE TITLE
生成的代码，编辑保存成功后，前端会报错

### ISSUE THREAD

**Issue by yangkebiao** [jeecgboot/jeecg-boot#5663]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/17536440/02c2b66e-9ab4-4ba0-87b2-66f6a7a7e194)
![image](https://github.com/jeecgboot/jeecg-boot/assets/17536440/3f636c79-2869-4296-ac14-c50e4d92b9a0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by yangkebiao** [comment]
const emit = defineEmits(['register', 'success']); 要改成 const emit = defineEmits(['register', 'fetch-success']);

**Comment by zhangdaiscott** [comment]
生成的什么类型，单表还是一对多，用的那套风格

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/047a44b6-7dfa-403c-a383-1a548d6c21ed)
> 版本号：v3.6.1
> 前端版本：vue3版 v3.6.0
> 表类型：树表
> 代码类型：vue3原生

未能复现该问题，烦请详细描述复现过程
