### ISSUE TITLE
修改数据的时候，创建日期的时分秒都被修改了

### ISSUE THREAD

**Issue by wen-yuan** [jeecgboot/jeecg-boot#5665]
##### 截图&代码：

 原数据，创建日期正常。

![1-修改qian](https://github.com/jeecgboot/jeecg-boot/assets/3355275/c7d36020-3404-4446-a04d-5ddfd9f03329)

随意修改数据后，创建日期的、时分秒被修改了。如图：

![修改后](https://github.com/jeecgboot/jeecg-boot/assets/3355275/f5cf911d-c503-4881-951f-1eed670add0e)

**Comment by zhangdaiscott** [comment]
你时间类型问题？

**Comment by wen-yuan** [comment]
![QQ图片20231213152527](https://github.com/jeecgboot/jeecg-boot/assets/3355275/582d2536-9b3c-4939-87f6-4818492b192b)
表结构是这样。
datetime类型

**Comment by wen-yuan** [comment]
entity 里面没改过，是直接生成的代码

![QQ图片20231213152812](https://github.com/jeecgboot/jeecg-boot/assets/3355275/ad3104fd-601b-496c-abfd-07cde61fa708)

**Comment by wen-yuan** [comment]
> 你时间类型问题？

请看下上面两个截图。这个是生成代码后，没改动过的。之前用旧版本框架没碰到这个问题。
是mybatis_plus 的BUG ？

**Comment by zhangdaiscott** [comment]
为什么是这个格式
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/867e9dd8-b793-4e41-a3d2-ad756bb5b235)

**Comment by wen-yuan** [comment]
> 为什么是这个格式 ![image](https://private-user-images.githubusercontent.com/3162115/290111769-867e9dd8-b793-4e41-a3d2-ad756bb5b235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTM2ODgsIm5iZiI6MTcwMjQ1MzM4OCwicGF0aCI6Ii8zMTYyMTE1LzI5MDExMTc2OS04NjdlOWRkOC1iNzkzLTRlNDEtYTNkMi1hZDc1NmJiNWIyMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDc0MzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJkMDM2YjNkMzc5OTgxZmExMTJiM2IwZGFiNDhjYzNkMWNjNmJhYjQ0YjQzMjJhYjkzOTM2MGYzODFhMTUyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZTz-bYjEnjVAOpM4KDSeAKtX8Rc9nVGcNXGVPDegpso)

![2222222222](https://github.com/jeecgboot/jeecg-boot/assets/3355275/08090813-5076-4d59-a25d-4caf9c97f8aa)

选择列表显示列的格式是，年月日。。生成后就是这样的年月日格式。

**Comment by wen-yuan** [comment]
> > 为什么是这个格式 ![image](https://private-user-images.githubusercontent.com/3162115/290111769-867e9dd8-b793-4e41-a3d2-ad756bb5b235.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTM2ODgsIm5iZiI6MTcwMjQ1MzM4OCwicGF0aCI6Ii8zMTYyMTE1LzI5MDExMTc2OS04NjdlOWRkOC1iNzkzLTRlNDEtYTNkMi1hZDc1NmJiNWIyMzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDc0MzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJkMDM2YjNkMzc5OTgxZmExMTJiM2IwZGFiNDhjYzNkMWNjNmJhYjQ0YjQzMjJhYjkzOTM2MGYzODFhMTUyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZTz-bYjEnjVAOpM4KDSeAKtX8Rc9nVGcNXGVPDegpso)
> 
> ![2222222222](https://private-user-images.githubusercontent.com/3355275/290114287-08090813-5076-4d59-a25d-4caf9c97f8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTQ2NDAsIm5iZiI6MTcwMjQ1NDM0MCwicGF0aCI6Ii8zMzU1Mjc1LzI5MDExNDI4Ny0wODA5MDgxMy01MDc2LTRkNTktYTI1ZC00Y2FmOWM5N2Y4YWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDc1OTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThkYzRjMDRiZDQ3MzMxMTYxODIwMzYwNGFhZTljZDBhY2IyZjliYWIyOThlYjllN2RlNzllNjc5N2EyMDYwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XvocrHuHWGnqNRgyLQdcyQLwxgr9B5qIGiVmshtsWBI)
> 
> 选择列表显示列的格式是，年月日。。生成后就是这样的年月日格式。

1、entity 格式改掉后，确实修改的时候【时分秒】就对了，但是毫秒被更新成0 了。
2、这个entity是代码生成的，没改过的。

**Comment by wen-yuan** [comment]
生成的update sql 要是能移除更新create_time 就好了。

![image](https://github.com/jeecgboot/jeecg-boot/assets/3355275/1c2194fc-7b8d-4d73-919a-19bcfc38388b)
