### ISSUE TITLE
分类字典 Table 'SYS_CATEGORY' doesn't exist

### ISSUE THREAD

**Issue by hutianxi** [jeecgboot/jeecg-boot#5667]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/5a7958d3-ab97-45ff-947c-337fa6178c00)
![image](https://github.com/jeecgboot/jeecg-boot/assets/67693982/a2521f26-7bd4-47fc-9591-9709f98cfc43)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
数据库设置不区分大小写
