### ISSUE TITLE
数字字典添加多租户隔离后各租户下创建相同字典编码提示失败。

### ISSUE THREAD

**Issue by liuzhenyin** [jeecgboot/jeecg-boot#5669]
##### 问题描述：
系统开启多租户模式后，把数据字典的也放到隔离的列表中，在数据字典维护时不同租户下维护相同字典编码时提示失败，排查了下原因主要是数据库做了唯一索引，这里是数据库设置的问题，看看产品上应该做好这块的设置，把字典编码和租户做成联合索引。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/3850530/94c48074-5b55-44ba-b6c2-bb9ee6d33e98)

![image](https://github.com/jeecgboot/jeecg-boot/assets/3850530/bc2fa918-919c-4822-81c6-81a916a4e4d3)

![image](https://github.com/jeecgboot/jeecg-boot/assets/3850530/2a218671-492d-4ce2-869f-7d31906bdc7d)

**Comment by zhangdaiscott** [comment]
目前编码是全局唯一的，未区分租户隔离，可以自行改造
