### ISSUE TITLE
Bug 升级3.6.1后, 在线表单同步数据库会没有权限. 

### ISSUE THREAD

**Issue by balzaron** [jeecgboot/jeecg-boot#5670]
##### 截图&代码：
<img width="1406" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/9757578/85e8748f-d6ef-4562-a4e4-bb8f227c1279">

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/log

看升级日志
