### ISSUE TITLE
1.6.6版本的poi-ooxml包是3.10-FINAL版本，无法导出Excel

### ISSUE THREAD

**Issue by xc925988564** [jeecgboot/jeecg-boot#5671]
##### 问题描述：
1、1.6.6版本的poi-ooxml包是3.10-FINAL版本，无法导出Excel
2、精简模式导出时不支持的格式希望给出友好提示
3、没有数据时，设计报表是选择数据源，希望给出友好提示，提示是没有数据的原因，不然会排查很久问题。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
未按格式要求发帖，会被直接删掉;
