### ISSUE TITLE
online生成的在线表单

### ISSUE THREAD

**Issue by ytwgogo** [jeecgboot/jeecg-boot#5675]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
online生成的在线表单中查询组件 下拉搜索框默认提示文字中都会多出来"qq"两个字母，这个想去掉的话该怎么去？

##### 截图&代码：

![微信图片_20231214142630](https://github.com/jeecgboot/jeecg-boot/assets/49088646/dc7af831-399c-4420-9f5a-23da234dc352)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
老版本无法支持
