### ISSUE TITLE
在线开发：Online表单 修改配置，增加字段，修改完后同步数据库结构，会清掉多租户tenant_id。

### ISSUE THREAD

**Issue by uddsoft** [jeecgboot/jeecg-boot#5683]
##### 版本号：
3.4.3-GA

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在线开发：Online表单 修改配置，增加字段，修改完后同步数据库结构，会清掉多租户tenant_id。有什么办法避免吗。

**Comment by zhangdaiscott** [comment]
清掉是什么意思？

**Comment by uddsoft** [comment]
> 清掉是什么意思？

删除了tenant_id 这个字段

**Comment by uddsoft** [comment]
例如：系统上线一段时间，通过在线表单调整字段。调整完后需要同步数据库。这个时候如果之前创建了tenant_id字段，会被删除。

**Comment by zhangdaiscott** [comment]
除非你的tenant_id不是通过online维护的
