### ISSUE TITLE
高级查询, 如何使用自己的业务表作为树

### ISSUE THREAD

**Issue by hareGuu** [jeecgboot/jeecg-boot#5684]
##### 版本号：
v3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在使用高级查询时, 只看到有 分类树, 但是我们想用自己的业务表来构建树, 该如何实现?

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不支持
