### ISSUE TITLE
建议代码中硬编码的"首页"改成动态的，避免国际化的时候报错

### ISSUE THREAD

**Issue by dahailiu123** [jeecgboot/jeecg-boot#5693]
##### 版本号：
3.6.1

##### 问题描述：

后台代码中有好几个地方写死了"首页" 我在做国际化的时候要修改首页菜单的名字就会报错！
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/154294503/b94edbe7-cb5d-488f-907e-719ddb462167)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by huangwei2013** [comment]
还有一个很神奇的首页问题：

将默认页的 dashboard/analysis 改成 dashboard/workbench，但：
1. 默认的 admin 账号，一直跳转默认页的还是 dashboard/analysis 
2. 新建的角色账号，默认页就可以跳转到 dashboard/workbench
