### ISSUE TITLE
后台系统监控

### ISSUE THREAD

**Issue by moumoukings** [jeecgboot/jeecg-boot#5696]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35523332/a9a6b845-f0b3-4b40-b67d-4109dd4b8f4d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/35523332/1983c73b-ca6f-4708-8bef-8dd8ca8d8a8d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by moumoukings** [comment]
springboot admin 配置问题，已处理

**Comment by gentlemango2016** [comment]
大哥，这个是怎么解决的？

**Comment by moumoukings** [comment]
> 大哥，这个是怎么解决的？

我是因为接口没有写对导致的，你的项目可以远程访问吗？可以的话可以帮你看下是否是和我类似的原因
