### ISSUE TITLE
【提问】请问下字典值编辑后缓存到redis的逻辑所在位置

### ISSUE THREAD

**Issue by 0xdevon** [jeecgboot/jeecg-boot#5697]
##### 版本号：
v3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
您好，我们是在原有字典基础上进行拓展字段，想请问下字典在编辑后（如添加item后），将字典值缓存到redis中的逻辑代码在什么位置？已经全局搜索了可以编辑的代码似乎并没有发现

##### 截图&代码：
<img width="1121" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/115865806/88614661-68ae-4b05-8145-6d2d26227e3d">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 0xdevon** [comment]
嗯嗯 这个地方我有看 但是@CacheEvict应该是清除缓存的作用吧🤔

**Comment by EightMonth** [comment]
jeecg没有缓存字典，每次操作都是直接到数据库的

**Comment by 0xdevon** [comment]
不是的兄弟 用客户端连接redis来看数据其实是有缓存到里面的

**Comment by EightMonth** [comment]
org.jeecg.modules.system.service.impl.SysBaseApiImpl#queryDictItemsByCode
