### ISSUE TITLE
管理员admin登录使用online表单（主表、从表、单表都有同样问题）同步数据库时前端报错：【没有权限，请联系管理员授权】，后端报错：【Subject does not have permission [online:form:syncDb]】

### ISSUE THREAD

**Issue by zhaibo01** [jeecgboot/jeecg-boot#5701]
##### 截图&代码：
![企业微信截图_1703059744354](https://github.com/jeecgboot/jeecg-boot/assets/85549959/d9385c06-7b38-4fba-93ad-f1a023512fc8)
![企业微信截图_17030597656816](https://github.com/jeecgboot/jeecg-boot/assets/85549959/7a45eb0f-a6a2-48d6-943e-f8b71dd2a7cd)
[后端报错信息.txt](https://github.com/jeecgboot/jeecg-boot/files/13724992/default.txt)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
看升级日志，执行sql并授权
https://jeecg.com/doc/log
