### ISSUE TITLE
高级查询拼接错误

### ISSUE THREAD

**Issue by zhangsgi** [jeecgboot/jeecg-boot#5702]
##### 问题描述：在进行高级查询的时候，会出现高级查询拼接失败。参考了issue#2687，查看了前端代码，主表的fieldList改造成子表的字段。再进行高级查询的时候使用queryWrapper = QueryGenerator.initQueryWrapper这个去获取传过来的参数并且拼接sql。但是报错拼接错误，该怎么改
第一张图片，拼接错误上一行，是获取到的参数

##### 截图&代码：

![1](https://github.com/jeecgboot/jeecg-boot/assets/122246065/fa59a88c-4939-45a1-a9c5-873d4ed702d0)
![2](https://github.com/jeecgboot/jeecg-boot/assets/122246065/afbc72ea-aa6c-438a-b5fc-d625a19e201e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本太老了，无法支持了
