### ISSUE TITLE
Online表单开发---同步数据库提示无权限

### ISSUE THREAD

**Issue by jinwe888** [jeecgboot/jeecg-boot#5707]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
更新至3.6.1前时是正常的。更新后其它都正常，就是同步数据库时一直提示无权限。请问这权限在那授权呢？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues?q=is%3Aissue+is%3Aclosed
