### ISSUE TITLE
@AutoLog新增日志失败

### ISSUE THREAD

**Issue by liuguang-lg** [jeecgboot/jeecg-boot#5708]
##### 版本号：
3.4.4

##### 问题描述：
打包后公共模块找不到导致日志新增失败，公共模块中的utils就可以使用
手动调用日志接口也不行
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecgboot-vue3/assets/58280388/0553b0a1-3db7-4bb4-9fd3-b224feedd4dd)

**Comment by zhangdaiscott** [comment]
重复
https://github.com/jeecgboot/jeecg-boot/issues/5686
