### ISSUE TITLE
配置了数据规则，但无效

### ISSUE THREAD

**Issue by jinwe888** [jeecgboot/jeecg-boot#5710]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
在代码开发里配置了数据权限，测试无效。在角色授权里也看不到相关配置！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/40389343/71f5a744-20fd-4c66-9e0d-45eeac870264)

![image](https://github.com/jeecgboot/jeecg-boot/assets/40389343/5555de7a-8948-4be1-8537-14483b78a975)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
online功能 的数据权限，是自己的用法，跟系统没关系
