### ISSUE TITLE
online生成代码的2个问题

### ISSUE THREAD

**Issue by 80676535** [jeecgboot/jeecg-boot#5711]
##### 问题描述：
online表单的功能测试正常使用，但是生成代码后，有两个问题。
1. 系统用户选择，会变成部门用户选择
2. 编辑时由系统用户id转换成用户名显示异常，导致搜索无法命中。

##### 截图&代码：

1 **这个是在功能测试里正常使用的情况：**
![6L`4UX})Z14J4Z_5Y@09V1F](https://github.com/jeecgboot/jeecg-boot/assets/28529815/48d530fc-0471-44b2-956f-8d1a1086f25f)

1 此时按用户搜索可以正常命中
![image](https://github.com/jeecgboot/jeecg-boot/assets/28529815/24d81846-9cce-4886-9450-63f3a24da5bd)
1 正常的用户选择框
![WGVDC`{_}W H_E895XRSX29](https://github.com/jeecgboot/jeecg-boot/assets/28529815/188ff038-157e-4545-9159-c2ac660683b9)

2 **现在这个生成代码之后是不正常的情况：**
![5~VNJ `QRK%GX1 5CYK ( 0](https://github.com/jeecgboot/jeecg-boot/assets/28529815/ff4344c7-0d81-4b52-bdd2-5f7da4e846d4)

2 并且按用户搜索无法命中
![~E800JGFSF5WOVIH8CHD}~R](https://github.com/jeecgboot/jeecg-boot/assets/28529815/b1ab9f40-6709-4670-b27a-a79b1e0d65d2)
![WDB`)5}4I0V3F(1LJ_X8KUD](https://github.com/jeecgboot/jeecg-boot/assets/28529815/1e149e63-9977-46dd-9a2f-eca615d3a5b0)

2 用户选择框变成部门用户选择
![image](https://github.com/jeecgboot/jeecg-boot/assets/28529815/0686b86b-70a5-4975-ae34-b295ffa9db9d)

**表设计结构：**
页面属性
![7XU2 AL%CE2`MB 2MA{_Y46](https://github.com/jeecgboot/jeecg-boot/assets/28529815/79450691-7f8d-4019-ab64-4b21f92d4736)
![(64)GS1 7UDKZ5N((G1SGLT](https://github.com/jeecgboot/jeecg-boot/assets/28529815/16b33d79-e475-488a-9d9a-0020065bb68b)

校验字段
![image](https://github.com/jeecgboot/jeecg-boot/assets/28529815/627c0a25-f91b-4d39-897c-2efeddc21c19)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by DDD1874** [comment]
这个跟我反馈的问题[3.6.1版本尝试Online表单和报表开发的8个问题反馈 #5681 ](https://github.com/jeecgboot/jeecg-boot/issues/5681#issue-2045218273)中，第1条问题相似，就是没有自动翻译（后端推给前端、前端回写后端没有同步）：

#1、建议Popup弹框增加id翻译text，目前尝试了一下，为了前端界面显示text而不显示为id，需要将Popup弹框、字典Table、字典Code、字典Text均作用在text字段上，这样表单设计就需要冗余存储id和text字段，建议像下拉框那样直接将id翻译成对应text字段即可；

**Comment by 80676535** [comment]
Popup弹框 的id 还算是能用，主要是框架自带的用户控件不对劲，在online功能测试里是正常的，生成代码之后，连根本没办法正常搜索到数据，用popup去选用户又有点不甘心。希望可以快一点修好

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
1. 系统用户选择，代码生成后会变成部门用户选择：已修复待新版本发布。
2. 编辑时由系统用户id转换成用户名显示异常，导致搜索无法命中：生成的代码中不包含online设计中的“页面属性”，需要在生成的代码中自定义存储和展示字段；可以通过“JSelectUser”控件的“rowKey”、"labelKey"参数来设置。
