### ISSUE TITLE
tomcat漏洞如何处理如何修改jeecgboot的tomcat版本

### ISSUE THREAD

**Issue by zhangYanWu0** [jeecgboot/jeecg-boot#5712]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
直接升级springboot
或者单独升级
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/5e5ada7e-86f4-4ed9-8ec4-f2c691e1d8bf)

**Comment by zhangYanWu0** [comment]
升级到那个版本合适呢
