### ISSUE TITLE
Online表单开发，显示数据时能否支持配置数据左对齐和右对齐或居中

### ISSUE THREAD

**Issue by chaose** [jeecgboot/jeecg-boot#5717]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55130483/28721543-51c6-45c3-8d21-d38aefa31302)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前没这功能

**Comment by chaose** [comment]
如果要修改的话可以在哪里修改样式呢？
