### ISSUE TITLE
配置字段href，跳转页面参数不生效，积木报表token带不过去，online报表跳转页签表头问题

### ISSUE THREAD

**Issue by nyzplymh** [jeecgboot/jeecg-boot#5718]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/14d8fcfe-6c1c-48d6-835c-cb7519398b8d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/0762a46a-97c9-4118-9787-49597a869fca)

#### 友情提示（为了提高issue处理效率）：
  - 在线文档中href配置说明的传参逻辑和源码中处理的参数逻辑不一致导致传参不生效的问题，截图中已经标识，麻烦及时更新文档，文档地址https://help.jeecg.com/online/form/comp/href.html

**Comment by nyzplymh** [comment]
第二个截图有问题 再这里补充
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/3f6ed634-aef0-40cb-8a92-729571ea086b)

**Comment by nyzplymh** [comment]
不知道为啥要加个self_

**Comment by nyzplymh** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/f8abe861-c619-45a4-a018-8d9d9deb3946)
1. href中配置积木报表时，token带不过去的问题，暂时只能走永久分享跳转
{{ window._CONFIG['domianURL'] }}/jmreport/shareView/893681561323524096?token=${token}
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/abf94975-3b28-4975-988a-261e23584d94)
2. online报表href配置后跳转的页签头默认是”Online在线报表“ 可不可以自定义或者通过传参设置的问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/13833688/b07e347b-c033-4dae-8b93-4788ebd3e493)

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
重复问题
https://github.com/jeecgboot/jeecgboot-vue3/issues/970#issuecomment-1875294417

**Comment by hongbo1030** [comment]
online报表href配置后跳转的页签头默认是”Online在线报表“ 可不可以自定义或者通过传参设置的问题
楼主的这个问题的解决在哪，我没看到。但是问题被关闭了
