### ISSUE TITLE
登录成功之后，报错无法跳转首页

### ISSUE THREAD

**Issue by binhtml5** [jeecgboot/jeecg-boot#5719]
##### 截图&代码：
<img width="804" alt="iShot_2023-12-27_13 10 20" src="https://github.com/jeecgboot/jeecg-boot/assets/34940439/375a9244-91e3-47f6-8393-a4d26f276d42">

**Comment by zhangdaiscott** [comment]
这种问题无法处理

**Comment by binhtml5** [comment]
初步认定为jenkins构建之后生成的哈希值JS文件，页面还没刷新，刚好在登录页面，引用的还是构建之前的哈希值JS文件，跳转的首页页面也一样，所以报错，无法跳转，刷新之后引用了最新的文件
