### ISSUE TITLE
tab切换的时候怎么不更新里面的内容

### ISSUE THREAD

**Issue by taopoppy** [jeecgboot/jeecg-boot#5721]
切换tab的时候，从tab1页面的表单里填一些内容 ，然后临时有事打开了tab2，处理完后，回到tab1的时候，页面刷新，表单里的东西都不见了，这种有没有配置可以配置tab不更新?

**Comment by zhangdaiscott** [comment]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
