### ISSUE TITLE
下拉操作栏中的按钮的disabled属性，只能写true和false，写表达式或者函数返回的布尔型全部都不生效；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5727]
##### 截图&代码：
/**
 * 下拉操作栏
 */
function getDropDownAction(record) {
  return [
    {
      label: 'xxxxx',
      onClick: handleOnClick.bind(null, record),
      disabled: handleDisabled.bind(null, record),// 这种方式不生效
      disabled: true,// 只能这样写才生效
      ifShow: handleIfShow.bind(null, record),
    }]
}

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
你可按如下图使用。disabled是antd组件所需，必须是布尔类型，跟antd类型保持一致。
<img width="741" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/b288b93f-b87f-4263-9cfa-0ae168f752dc">
