### ISSUE TITLE
Parameter 1 of method propertyResolverUtils in org.springdoc.core.configuration.SpringDocConfiguration required a bean of type 'org.springframework.context.MessageSource' that could not be found.

### ISSUE THREAD

**Issue by xueqimiao1113** [jeecgboot/jeecg-boot#5729]
##### 问题描述：
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of method propertyResolverUtils in org.springdoc.core.configuration.SpringDocConfiguration required a bean of type 'org.springframework.context.MessageSource' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.context.MessageSource' in your configuration.

##### 截图&代码：
Gateway能正常启动 业务模块启动报以上错误

**Comment by zhangdaiscott** [comment]
提供完整的重现步骤

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
未重现，请更新最新代码
