### ISSUE TITLE
升级到springboot3，积木报表版本:1.6.6-beta2, fastjson 升级到2.0.43，报表查询失败

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/jeecg-boot#5735]
##### 问题描述：积木报表查询失败，提示：
 操作失败，Handler dispatch failed: java.lang.NoSuchMethodError: 'com.alibaba.fastjson.JSONObject com.alibaba.fastjson.JSONObject.clone()'
fastjson还原到 1.2.83，查询是ok的，另外之前有个提示：少httpclient5包，
引入httpclient5后ok：        
        <dependency>
            <groupId>org.apache.httpcomponents.client5</groupId>
            <artifactId>httpclient5</artifactId>
            <version>5.3</version>
        </dependency>
 

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/39261781/750fb588-d1d7-423d-afe0-c75900197fd6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by catlvsuger** [comment]
还原到 1.2.83是ok的

**Comment by zhangdaiscott** [comment]
收到

**Comment by zhangdaiscott** [comment]
```
<dependency>
  <groupId>org.jeecgframework.jimureport</groupId>
  <artifactId>jimureport-spring-boot3-starter-fastjson2</artifactId>
  <version>1.6.6</version>
</dependency>
```
