### ISSUE TITLE
请问部分代码的多租户数据隔离处理方式和官方在线文档中提供的方案有什么不同？

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5739]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在官网的在线文档：https://help.jeecg.com/javaback/saasnew.html
提供了多租户隔离的实现方式，但是在一些代码中又使用了其它的方式处理多租户数据隔离。

根据在线文档中的说明，在查询数据时会自动按当前租户进行过滤，请问在什么情况下需要使用下面代码段中的数据隔离处理方式？

代码段1： SysDictCollector.java 的 queryPageList方法：
```
		//------------------------------------------------------------------------------------------------
		//是否开启系统管理模块的多租户数据隔离【SAAS多租户模式】
		if(MybatisPlusSaasConfig.OPEN_SYSTEM_TENANT_CONTROL){
			sysDict.setTenantId(oConvertUtils.getInt(TenantContext.getTenant(),0));
		}
		//------------------------------------------------------------------------------------------------

```

代码段2：SysDictServiceImpl.java 的 queryAllDictItems 方法：
```
		//------------------------------------------------------------------------------------------------
		//是否开启系统管理模块的多租户数据隔离【SAAS多租户模式】
		if(MybatisPlusSaasConfig.OPEN_SYSTEM_TENANT_CONTROL){
			sysDictQueryWrapper.eq(SysDict::getTenantId, oConvertUtils.getInt(TenantContext.getTenant(), 0))
					.or().eq(SysDict::getTenantId,0);
		}
		//------------------------------------------------------------------------------------------------
```

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
1、方案一
org\jeecg\config\mybatis\MybatisPlusSaasConfig.java
直接加入表名
2、方案二 （有的逻辑不能完全隔离，所以就采用硬编码）
硬编码
