### ISSUE TITLE
升级到springboot3 新建菜单 授权无用依然说没有权限

### ISSUE THREAD

**Issue by 13223746581** [jeecgboot/jeecg-boot#5741]
##### 版本号：
3.6.1 springboot3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
升级到springboot3 新建菜单 授权无用 增删改仍然提示没有权限 , 需要删除redis 中shiro:cache才行 

##### 截图&代码：
![1703815748187](https://github.com/jeecgboot/jeecg-boot/assets/68310022/cb65d5e6-262e-470c-992d-654d504231ef)

这个value值不更新

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
？

**Comment by 13223746581** [comment]
shiro:cache:org.jeecg.config.shiro.ShiroRealm.authorizationCache这个 redis中的key 保存的不是用户权限字符串么 ,然后我给角色授权以后,理论上这个值应该被删除 或者更新的 ;但是并没有

**Comment by zhangdaiscott** [comment]
退出重新登录了吗
