### ISSUE TITLE
springboot3 生成的代码 注解有问题 @Schema(value= "主键") 这是错误的 应该是 @Schema(description = "主键")

### ISSUE THREAD

**Issue by 13223746581** [jeecgboot/jeecg-boot#5742]
##### 版本号：
3.6.1 springboot3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

springboot3 生成的代码 注解有问题 @Schema(value= "主键") 这是错误的 应该是 @Schema(description = "主键")
##### 截图&代码：

![1703815857304](https://github.com/jeecgboot/jeecg-boot/assets/68310022/c2e39416-c992-4ef2-bb69-e72008edd711)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收到

**Comment by hoperunChen** [comment]
已修复，待新版本发布
