### ISSUE TITLE
 菜单管理，配置数据权限无效

### ISSUE THREAD

**Issue by ZSXee** [jeecgboot/jeecg-boot#5743]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：

菜单管理，配置数据权限无效，之前连接mysql数据库正常，现在换成了瀚高数据库，怀疑是这个原因，但是切换数据库相关配置已按照操作手册配置好
##### 截图&代码：
<img width="848" alt="4" src="https://github.com/jeecgboot/jeecg-boot/assets/92899953/fbcf1a1e-e3dc-4781-a30c-15483fe95a45">
<img width="567" alt="3" src="https://github.com/jeecgboot/jeecg-boot/assets/92899953/39b937db-d7ef-44e9-8352-0d6f596ccb5a">
<img width="811" alt="2" src="https://github.com/jeecgboot/jeecg-boot/assets/92899953/8c84d2c1-3ddb-4a05-a3c6-040080b6998d">
<img width="323" alt="1" src="https://github.com/jeecgboot/jeecg-boot/assets/92899953/f29e5621-ee8b-439e-b3ae-83cfa6880360">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可能数据库兼容问题，自己debug跟踪下代码
