### ISSUE TITLE
如何在后端获取当前用户选择的语言？

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5744]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
应用场景要求：后端要获取用户选择的当前语言，对一些信息进行本地化处理。

好像代码里并没有提供，希望平台在下一个版本升级时，在前端 request 时当前语言也返回给后端。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个自己扩展吧
