### ISSUE TITLE
Online表单开发不支持oracle数据库

### ISSUE THREAD

**Issue by cometzhao** [jeecgboot/jeecg-boot#5745]
##### 版本号：
spring3

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：
online开发，点击同步数据库报错：Property 'driverClassName' must not be empty

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/26214293/7d64626e-9a5f-4037-b7ec-0a29ee11e649)
![image](https://github.com/jeecgboot/jeecg-boot/assets/26214293/14f60972-6ed6-4487-aac6-9a9c51830e7b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是oracle什么版本。什么配置

我们测试oracle11g 12g都没问题
