### ISSUE TITLE
菜单链接url中传token，jwt验证获取不到token参数

### ISSUE THREAD

**Issue by mfc-97** [jeecgboot/jeecg-boot#5753]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
菜单链接url中传token，jwt验证获取不到token参数

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/50943687/d3bf517b-ff16-4567-9f84-3796da5e0e74)
![image](https://github.com/jeecgboot/jeecg-boot/assets/50943687/a19988d1-b7c3-44b5-bb96-d08957fd0587)
![image](https://github.com/jeecgboot/jeecg-boot/assets/50943687/2d3838b5-d15d-4752-ab0d-8e42317a2b6b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没明白你杂用的

**Comment by mfc-97** [comment]
我在项目中集成了magic-api，它自带一一个页面，也就是我在菜单中配置的链接。token以参数形式拼在url中，授权配置的是authc，但是token拿不到。走到第二张图片的代码位置，请求已被转发为403。我看文档中支持这种传token形式，但是现在拿不到。

**Comment by zhangdaiscott** [comment]
拿不到是什么现象？初步感觉你的用法不对

**Comment by mfc-97** [comment]
拿不到现象是，提示token失效，无权限访问
