### ISSUE TITLE
gateway不停报错，还会占用本地线程池问题

### ISSUE THREAD

**Issue by xy187006** [jeecgboot/jeecg-boot#5754]
##### 版本号：
3.5.5

##### 问题描述：
查看生产上的gateway日志，每天都会刷这种warn日志，而且一段时间会占满服务器本地线程导致java.lang.OutOfMemoryError: unable to create new native thread问题，重启就能解决

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/51348800/6c51695f-2720-49fd-a848-ea83d6186136)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这种问题得你们自己，我们无法重现，看看是不是sentinel链接有问题
