### ISSUE TITLE
希望vue代码生成时表单和列表不要加入逻辑删除字段

### ISSUE THREAD

**Issue by depthwood** [jeecgboot/jeecg-boot#5755]
##### 截图&代码：
现在逻辑删除字段会默认加入列表和表单中，体验不是很好
![image](https://github.com/jeecgboot/jeecg-boot/assets/65118489/f0311027-7d35-4beb-bc4b-00e3952d7878)

![image](https://github.com/jeecgboot/jeecg-boot/assets/65118489/fa000cd2-beb4-487f-94d2-c0457730ec4c)

![image](https://github.com/jeecgboot/jeecg-boot/assets/65118489/236f11db-6c86-41e2-9802-909f0e8e4fbd)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已解决，待新版发布
