### ISSUE TITLE
表格可伸缩列设置resizable: true失效

### ISSUE THREAD

**Issue by weixiaoo** [jeecgboot/jeecg-boot#5756]
##### 问题描述：
表格可伸缩列失效

##### 截图&代码：
![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
上面的截图看不到，需要重新编辑下。

经测试发现resizable: true可用。
网站上面的“单表示例”页面，支持列拖动，你可查看对比下。
