### ISSUE TITLE
使用Quzrta任务调度框架定义定时任务，定时任务第一次执行完成之后重复执行的问题

### ISSUE THREAD

**Issue by TengflyMa** [jeecgboot/jeecg-boot#5758]
##### 问题描述：
这里定义一个时间间隔为30分钟的定时任务，也就是该任务在每小时的第2和第32分钟开始执行，当前定义的定时任务执行耗时不超过10s，监控控制台显示当前任务第一次执行完成之后还会继续执行该任务，一直到第2分钟59s结束才会停止执行

##### 截图&代码：
[
![QQ截图20240103153347](https://github.com/jeecgboot/jeecg-boot/assets/101609997/be765cfb-8a5b-446b-a520-665c6b6bc486)
](url)

**Comment by TengflyMa** [comment]
如果这个定时任务耗时不超过1分钟，那么这个定时任务执行完成之后，如果当前时间还是第2分钟和第32分钟，那么这个定时任务还是会重复执行。我在前面的秒设置了从第一秒开始间隔时间是59秒，测试了一下，正常了，定时任务没有重复执行，执行下了一次

**Comment by zhangdaiscott** [comment]
版本号
