### ISSUE TITLE
新版 3.6.2 的一些官方依赖库找不到

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5762]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/f2ef6d35-6347-4eea-8b1f-93994d6f90be)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你可以删除人大金仓的依赖，或者配置jeecg私服
https://help.jeecg.com/java/setup/maven.html
