### ISSUE TITLE
在线表单开发问题反馈

### ISSUE THREAD

**Issue by wang420520** [jeecgboot/jeecg-boot#5764]
##### 问题描述：
1、点击表格无反应，不能进行选中，全选也是一样无反应；
2、新增表单同步数据库成功后，弹窗不能关闭，点取消也不能关闭！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/977
