### ISSUE TITLE
online树表的变更父级节点保存报错

### ISSUE THREAD

**Issue by RongLiXu** [jeecgboot/jeecg-boot#5769]
##### 版本号：
jeecgboot 3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online树表在添加子节点后，重新编辑父级节点，点击保存报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/32008882/bc3a9c7c-1a9f-4356-9c2c-a06a10db6dc5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
jl

**Comment by sjlei** [comment]
问题已修复，下版本发布

**Comment by 78739749haiyang** [comment]
哪个版本修复了？
