### ISSUE TITLE
在线开发无法导入数据库

### ISSUE THREAD

**Issue by 520-x** [jeecgboot/jeecg-boot#5770]
##### 问题描述：切换完菜单后，一直显示无权限 3.4.3也是一样的问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/e924c5e3-0391-46c3-a5d3-a41950d509ef)

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/55725161/d51071b4-98d8-4662-b395-113b03f19b71)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
配置接口权限，角色授权

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/log
