### ISSUE TITLE
Online表单开发：“Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')”

### ISSUE THREAD

**Issue by alecui** [jeecgboot/jeecg-boot#5771]
##### 截图&代码：
![jeecg问题反馈](https://github.com/jeecgboot/jeecg-boot/assets/26320500/a19beaa8-f334-46df-bdd3-c57815e4d5d7)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/977

**Comment by alecui** [comment]
经验证固定vue版本，重新intall、build后，问题解决。
