### ISSUE TITLE
可以实现流程在多个租户之间流转吗？

### ISSUE THREAD

**Issue by cunsheng** [jeecgboot/jeecg-boot#5772]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我看了下代码，是不是可以把sys_depart从隔离名单中去掉就可以实现部门跨租户？是不是可以这种方式实现流程在多个租户之间流转？会不会有什么问题？

##### 截图&代码：
文件：https://github.com/jeecgboot/jeecg-boot/blob/6fe8f1d81a87e262a125ab5a1196fadb7e5fe6a2/jeecg-boot-base-core/src/main/java/org/jeecg/config/mybatis/MybatisPlusSaasConfig.java

<img width="512" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/965618/b953b0f4-254a-461c-bebd-02cf36837f93">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
去掉采用硬编码方式实现
