### ISSUE TITLE
在JVxeTable列编辑时，JPopup在params中动态传参问题

### ISSUE THREAD

**Issue by GuobaoCui** [jeecgboot/jeecg-boot#5773]
##### 版本号：
jeecgboot-vue3   版本号：3.6.1
jeecg-boot-parent 版本号：3.6.1

##### 前端版本：
vue3版   版本号：3.6.1

##### 问题描述：
1.在JVxeTable中，如何根据一个列中的数据，作为另一JPopup列中的params参数进行选择数据过滤？
2.在JVxeTable组件配置文档中，如何根据选择的部门组件JVxeTypes.departSelect的部门数据，进行用户组件JVxeTypes.userSelect的用户过滤？

##### 截图&代码：
1.![image](https://github.com/jeecgboot/jeecg-boot/assets/64345558/82cc7af2-2816-4a5f-a6e8-854f3ae9f0dc)
![image](https://github.com/jeecgboot/jeecg-boot/assets/64345558/9852a275-c6ff-4e94-8277-983911c964bf)

2.![image](https://github.com/jeecgboot/jeecg-boot/assets/64345558/b8f8b5c9-1cbf-4865-b902-5bfa17867f70)
![image](https://github.com/jeecgboot/jeecg-boot/assets/64345558/ae3142e1-4151-4397-897e-88a6e0b416c2)

**Comment by zhangdaiscott** [comment]
cr

**Comment by liaozhiyang** [comment]
不支持
