### ISSUE TITLE
集成cas的问题

### ISSUE THREAD

**Issue by wkkkkk1024** [jeecgboot/jeecg-boot#5775]
##### 问题描述：
jeecg boot集成cas后，登陆时提示未认证授权的服务
不允许使用CAS来认证您访问的目标应用

##### 截图&代码：

![17166cb67991b1b99b4b3daffb23456](https://github.com/jeecgboot/jeecg-boot/assets/152457375/ee711b9e-9be2-4c31-b4b8-f620ced603b0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这是你集成的有问题
https://help.jeecg.com/java/cas.html
