### ISSUE TITLE
如何开启兼容IE

### ISSUE THREAD

**Issue by Coolmeow** [jeecgboot/jeecg-boot#5783]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2版本默认就就兼容IE11

**Comment by Coolmeow** [comment]
但是jeecgboot项目在ie11中一直加载项目中，你们的测试网站也是在ie浏览器上转圈

**Comment by Coolmeow** [comment]
> vue2版本默认就就兼容IE11

但是jeecgboot项目在ie11中一直加载项目中，你们的测试网站也是在ie浏览器上也是一直加载项目中

**Comment by zhangdaiscott** [comment]
ie几？你访问的是那个地址

**Comment by Coolmeow** [comment]
> ie几？你访问的是那个地址

IE11，访问的是http://boot.jeecg.com
![WX20240110-153110](https://github.com/jeecgboot/jeecg-boot/assets/18652150/50662587-fe71-4772-b4b5-ad182a33a824)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/4613
