### ISSUE TITLE
3.6.2版本online代码生成有分类字典树控件时出错

### ISSUE THREAD

**Issue by wxqlandy** [jeecgboot/jeecg-boot#5787]
##### 问题描述：
升级3.6.2后如果表单中有字典分类树字段，如果没有配置dictField为父类code，代码生成会报错。
##### 截图&代码：
![QQ截图20240109114321](https://github.com/jeecgboot/jeecg-boot/assets/5011982/618efb4d-b87a-42a1-aa37-3ae03d6cdba8)
![QQ截图20240109114350](https://github.com/jeecgboot/jeecg-boot/assets/5011982/d4f1cdd9-81c1-43b1-b034-eb68df54b2ae)

**Comment by zhangdaiscott** [comment]
修复了，更新代码
