### ISSUE TITLE
BasicTree组件设置defaultExpandAll不生效；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5790]
##### 截图&代码：
<BasicTree
    title="帮助中心"
    toolbar
    :clickRowToExpand="true"
    :treeData="treeData"
    :fieldNames="{ key: 'id', title: 'title' }"
    @select="handleSelect"
    :expandedKeys="expandedKeys"
    :selectedKeys="selectedKeys"
    :renderIcon="handleIcon"
    :defaultExpandAll="true"
  />

const treeData = ref<TreeItem[]>([]);
    const expandedKeys = ref<string[]>([]);
    const selectedKeys = ref<string[]>([]);

async function fetch() {
      treeData.value = (await getTreeApi()) as unknown as TreeItem[];

      let id = treeData.value[0].children[0].id
      expandedKeys.value.push(treeData.value[0].id);
      selectedKeys.value.push(id);
    }

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
没有defaultExpandAll这个props吧？使用defaultExpandAllRows
<img width="598" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/b674218d-a150-422d-b105-6138d17f7e06">
