### ISSUE TITLE
请问jeecg-boot中不需要的功能如何去除？

### ISSUE THREAD

**Issue by gitisbest** [jeecgboot/jeecg-boot#5792]
jeecg-boot 中默认自带了不少功能
但是对于我的使用情况来说，暂时用不上这些功能
请问是否有简便的方法可以去除这些功能？

这样后续的 jar 包可以小一些。

谢谢！

**Comment by zhangdaiscott** [comment]
直接删除就行，保证编译打包不报错就没问题
