### ISSUE TITLE
打包部署后，登录404错误

### ISSUE THREAD

**Issue by binrongsd** [jeecgboot/jeecg-boot#5793]

**Comment by binrongsd** [comment]
![404](https://github.com/jeecgboot/jeecg-boot/assets/8663398/7f664651-b2f0-4763-9e95-df215173a229)

**Comment by binrongsd** [comment]
[
![404](https://github.com/jeecgboot/jeecg-boot/assets/8663398/a3b8b2a5-74e0-4dc2-b6b1-25c136fd7992)
](url)

**Comment by zhangdaiscott** [comment]
配置有问题
https://help.jeecg.com/publish/quick.html
