### ISSUE TITLE
vue3版本from表单，动态添加项，校验内部报错

### ISSUE THREAD

**Issue by sanshiqi** [jeecgboot/jeecg-boot#5795]
##### 截图&代码：
![1](https://github.com/jeecgboot/jeecg-boot/assets/34674186/ad4cc242-c832-47d8-ae00-a6a8cc74417c)
![2](https://github.com/jeecgboot/jeecg-boot/assets/34674186/624d2ef6-b6b1-4466-9c06-69b40cb19cd1)
![3](https://github.com/jeecgboot/jeecg-boot/assets/34674186/bfff28c2-c276-4dcb-bac1-43da0bbda991)
![4](https://github.com/jeecgboot/jeecg-boot/assets/34674186/4946ef49-39b3-49c8-bd5b-658f471890dd)
![2](https://github.com/jeecgboot/jeecg-boot/assets/34674186/97397f3f-3dd9-478f-bdd9-a1b23042dfd1)
![5](https://github.com/jeecgboot/jeecg-boot/assets/34674186/93be8af2-2d5d-4972-b810-db98ff188413)
![6](https://github.com/jeecgboot/jeecg-boot/assets/34674186/ae5f0116-baef-4072-859c-7f1e9db87df7)
![7](https://github.com/jeecgboot/jeecg-boot/assets/34674186/e2f7ce6f-8d51-4694-8917-5bbdb0a3480a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没明白

**Comment by zhangdaiscott** [comment]
你说你的配置和操作即可

**Comment by sanshiqi** [comment]
就是在打开model弹窗的时候 动态添加form表单项  通过接口循环遍历进行添加是否为多选的选择器 然后现在的情况是动态添加Select 给他多选mode:'multiple', 属性的时候 在最后提交表单进行校验的时候 validate 这个方法会报错报组件内部出错

**Comment by zhangdaiscott** [comment]
录个视频或者写个图文并茂的操作步骤

**Comment by zhangdaiscott** [comment]
zy

**Comment by sanshiqi** [comment]
就是通过get接口 返回的数据进行数组的map循环添加调用appendSchemaByField这个form动态添加方法循环添加后 在提交表单的时候需要进行表单校验 通过 jeecg中from表单的validate()方法 触发表单的所有验证的时候会报jeecg中form表单内部报错

**Comment by sanshiqi** [comment]
![1](https://github.com/jeecgboot/jeecg-boot/assets/34674186/63784ce4-7654-4a2a-b2bd-272321e78595)
第一步通过setModalProps 修改其中的 visible= true 让弹出展示并重置表单 
![2](https://github.com/jeecgboot/jeecg-boot/assets/34674186/42328170-e086-48b8-8365-b022bf04bef6)
第二步通过接口将返回的数据进行遍历 通过数组的map循环调用appendSchemaByField 给from表单动态添加项
![3](https://github.com/jeecgboot/jeecg-boot/assets/34674186/32591ca4-ffce-4867-835e-f863e67afc08)
第三步 在点击提交的时候进行form表单的校验 通过 from表单的validate 方法进行整个表单的校验会出现之前的图中的 报错问题

**Comment by liaozhiyang** [comment]
有可运行的代码吗？
我在“表单增删示例”页面中也新增了一个多选的下拉框，选的是必填，校验正常啊。

```
<template>
  <PageWrapper title="表单增删示例">
    <CollapseContainer title="表单增删">
      <BasicForm @register="register" @submit="handleSubmit">
        <template #add="{ field }">
          <Button v-if="Number(field) === 0" @click="add">+</Button>
          <Button v-if="field > 0" @click="del(field)">-</Button>
        </template>
      </BasicForm>
    </CollapseContainer>
  </PageWrapper>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { BasicForm, useForm } from '/@/components/Form/index';
  import { CollapseContainer } from '/@/components/Container/index';
  import { Input } from 'ant-design-vue';
  import { PageWrapper } from '/@/components/Page';
  import { Button } from '/@/components/Button';

  export default defineComponent({
    components: { BasicForm, CollapseContainer, PageWrapper, [Input.name]: Input, Button },
    setup() {
      const [register, { appendSchemaByField, removeSchemaByFiled, validate }] = useForm({
        schemas: [
          {
            field: 'field0a',
            component: 'Input',
            label: '字段0',
            colProps: {
              span: 8,
            },
            required: true,
          },
          {
            field: 'field0b',
            component: 'Input',
            label: '字段0',
            colProps: {
              span: 8,
            },
            required: true,
          },
          {
            field: '0',
            component: 'Input',
            label: ' ',
            colProps: {
              span: 8,
            },
            slot: 'add',
          },
        ],
        labelWidth: 100,
        actionColOptions: { span: 24 },
      });

      async function handleSubmit() {
        try {
          const data = await validate();
          console.log(data);
        } catch (e) {
          console.log(e);
        }
      }

      const n = ref(1);

      function add() {
        appendSchemaByField(
          {
            field: `field${n.value}a`,
            component: 'Select',
            componentProps:{
              mode:"multiple",
              options:[{'value':0,'label':"零"},{'value':1,'label':"一"},{'value':2,'label':"二"}]
            },
            label: '字段' + n.value,
            colProps: {
              span: 8,
            },
            required: true,
          },
          ''
        );
        appendSchemaByField(
          {
            field: `field${n.value}b`,
            component: 'Input',
            label: '字段' + n.value,
            colProps: {
              span: 8,
            },
            required: true,
          },
          ''
        );

        appendSchemaByField(
          {
            field: `${n.value}`,
            component: 'Input',
            label: ' ',
            colProps: {
              span: 8,
            },
            slot: 'add',
          },
          ''
        );
        n.value++;
      }

      function del(field) {
        removeSchemaByFiled([`field${field}a`, `field${field}b`, `${field}`]);
        n.value--;
      }

      return { register, handleSubmit, add, del };
    },
  });
</script>

```

**Comment by sanshiqi** [comment]
就是这样写的 他所有的表单项都是动态的 这样点验证就会报错
<template>
  <PageWrapper title="表单增删示例">
    <CollapseContainer title="表单增删">
      <BasicForm @register="register" @submit="handleSubmit">
        
      </BasicForm>
      <button @click="add">测试</button>
    </CollapseContainer>
  </PageWrapper>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { BasicForm, useForm } from '/@/components/Form/index';
  import { CollapseContainer } from '/@/components/Container/index';
  import { Input } from 'ant-design-vue';
  import { PageWrapper } from '/@/components/Page';
  import { Button } from '/@/components/Button';

  export default defineComponent({
    components: { BasicForm, CollapseContainer, PageWrapper, [Input.name]: Input, Button },
    setup() {
      const [register, { appendSchemaByField, removeSchemaByFiled, validate }] = useForm({
        schemas: [
          {
            label: '',
            field: 'id',
            component: 'Input',
            show: false,
          },
        ],
        labelWidth: 100,
        actionColOptions: { span: 24 },
      });

      async function handleSubmit() {
        try {
          const data = await validate();
          console.log(data);
        } catch (e) {
          console.log(e);
        }
      }

      const n = ref(1);

      function add() {
        appendSchemaByField(
          {
            field: `field${n.value}a`,
            component: 'Select',
            componentProps: {
              mode: 'multiple',
              options: [
                { value: 0, label: '零' },
                { value: 1, label: '一' },
                { value: 2, label: '二' },
              ],
            },
            label: '字段' + n.value,
            colProps: {
              span: 8,
            },
            required: true,
          },
          ''
        );
        appendSchemaByField(
          {
            field: `field${n.value}b`,
            component: 'Input',
            label: '字段' + n.value,
            colProps: {
              span: 8,
            },
            required: true,
          },
          ''
        );

        appendSchemaByField(
          {
            field: `${n.value}`,
            component: 'Input',
            label: ' ',
            colProps: {
              span: 8,
            },
            slot: 'add',
          },
          ''
        );
        n.value++;
      }

      function del(field) {
        removeSchemaByFiled([`field${field}a`, `field${field}b`, `${field}`]);
        n.value--;
      }

      return { register, handleSubmit, add, del };
    },
  });
</script>

**Comment by sanshiqi** [comment]
复制到vue文件运行就可以复现

**Comment by liaozhiyang** [comment]
> 就是这样写的 他所有的表单项都是动态的 这样点验证就会报错 <BasicForm @register="register" @submit="handleSubmit"> <button @click="add">测试
> 
> <script lang="ts"> import { defineComponent, ref } from 'vue'; import { BasicForm, useForm } from '/@/components/Form/index'; import { CollapseContainer } from '/@/components/Container/index'; import { Input } from 'ant-design-vue'; import { PageWrapper } from '/@/components/Page'; import { Button } from '/@/components/Button'; export default defineComponent({ components: { BasicForm, CollapseContainer, PageWrapper, [Input.name]: Input, Button }, setup() { const [register, { appendSchemaByField, removeSchemaByFiled, validate }] = useForm({ schemas: [ { label: '', field: 'id', component: 'Input', show: false, }, ], labelWidth: 100, actionColOptions: { span: 24 }, }); async function handleSubmit() { try { const data = await validate(); console.log(data); } catch (e) { console.log(e); } } const n = ref(1); function add() { appendSchemaByField( { field: `field${n.value}a`, component: 'Select', componentProps: { mode: 'multiple', options: [ { value: 0, label: '零' }, { value: 1, label: '一' }, { value: 2, label: '二' }, ], }, label: '字段' + n.value, colProps: { span: 8, }, required: true, }, '' ); appendSchemaByField( { field: `field${n.value}b`, component: 'Input', label: '字段' + n.value, colProps: { span: 8, }, required: true, }, '' ); appendSchemaByField( { field: `${n.value}`, component: 'Input', label: ' ', colProps: { span: 8, }, slot: 'add', }, '' ); n.value++; } function del(field) { removeSchemaByFiled([`field${field}a`, `field${field}b`, `${field}`]); n.value--; } return { register, handleSubmit, add, del }; }, }); </script>

你这代码有缺少吧？复制不可直接运行。

**Comment by sanshiqi** [comment]
[新建 文本文档(1).txt](https://github.com/jeecgboot/jeecg-boot/files/14034966/1.txt)

**Comment by sanshiqi** [comment]
用这个文件中的试一下

**Comment by sanshiqi** [comment]
![1706081932300](https://github.com/jeecgboot/jeecg-boot/assets/34674186/bc7a4a02-5bf9-4ab6-a88b-70fea3e23d3d)
这个地方改成这样校验会报错

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/781a4cb6-4b10-451b-b3be-33fcbc3da7db)
运行你的代码，没发现你的问题。你升级版本试下看看，我是用的最新版本测试的。

**Comment by zhangdaiscott** [comment]
最新版  3.6.2
