### ISSUE TITLE
vue2/jeecgboot 表单页首页动态更改url

### ISSUE THREAD

**Issue by wangxinyu8** [jeecgboot/jeecg-boot#5796]
##### 版本号：
当前最新版本： 2.4.3（发布日期：20210322）

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
进入页面后能动态更改url吗，如何更改？需要更改底层代码吗？

##### 截图&代码：
![SG9{%@TY_ME)$ {(Q5G4WYA](https://github.com/jeecgboot/jeecg-boot/assets/111946787/69a49585-2acc-4f75-830f-0c597117e9dc)

![bfb6aac10ceab41f02b5a6bea7a9c03](https://github.com/jeecgboot/jeecg-boot/assets/111946787/13986470-b886-4720-9303-6813bfe42635)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
http://doc.jeecg.com/2044034

**Comment by wangxinyu8** [comment]
进入页面后能动态更改url.list吗，如何更改？需要更改基础代码吗？
