### ISSUE TITLE
jeecg-boot testConnection 任意代码执行漏洞

### ISSUE THREAD

**Issue by pengpenghello** [jeecgboot/jeecg-boot#5797]
##### 截图&代码：
![d040835e5ff0a48b838c02377695eac](https://github.com/jeecgboot/jeecg-boot/assets/96603310/4ec92953-397c-49c5-9667-a966910ed547)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
早修复了，升级积木报表版本
