### ISSUE TITLE
数据源切换为postgresql，后台查询报错

### ISSUE THREAD

**Issue by wudisorry** [jeecgboot/jeecg-boot#5801]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
数据库切换为postgresql15后，进入首页报错。SQL是“select annt_id from sys_announcement_send where user_id = #{userId} and read_flag = 0”。read_flag 是字符类型，必须使用read_flag =‘0’ 加上单引号这种写法。还在其他xml文件看到使用`符号也会引发报错。
是否有统一的解决方案解决postgresql语法严格引出的问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by wudisorry** [comment]
全文搜索<select id="querySysCementListByUserId" parameterType="String"  resultMap="SysAnnouncement"> 可以看到sql

**Comment by wudisorry** [comment]
xml全文搜索querySysCementListByUserId 可以看到sql

**Comment by zhangdaiscott** [comment]
收录 ws

**Comment by wudisorry** [comment]
-。---------------------------------------------
 
   This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by wudisorry** [comment]
> 收录 ws

ws是什么意思

**Comment by 1298191366** [comment]
前期我们做过升级，`read_flag`变成int类型的了，需要你自行修改一下
```
ALTER TABLE sys_announcement_send 
  ALTER COLUMN read_flag TYPE int4 USING read_flag::int4;
```
![Y30AZ$W4R(R`T03X4KSF N](https://github.com/jeecgboot/jeecg-boot/assets/30997828/5e22c5b1-380e-4946-868a-5c75ba94e358)
