### ISSUE TITLE
3.6.2版仪表盘 怎么实现 首页配置 和菜单配置？

### ISSUE THREAD

**Issue by sanmojushi** [jeecgboot/jeecg-boot#5804]
##### 版本号：
3.6.2

##### 前端版本：
vue3版

##### 问题描述：
新版的仪表盘预览完成后，按照帮助文档配置成为  角色首页，或者  菜单项，无法成功。

##### 截图&代码：
![1](https://github.com/jeecgboot/jeecg-boot/assets/4689724/e138420b-7fe0-4f8c-833c-4c9e82f44398)
![2](https://github.com/jeecgboot/jeecg-boot/assets/4689724/e0e5d2e2-131d-4d5f-bdfd-3df0aa3f8b00)
![3](https://github.com/jeecgboot/jeecg-boot/assets/4689724/2d89cb2e-d40e-4000-89f2-173356bafaa0)
![4](https://github.com/jeecgboot/jeecg-boot/assets/4689724/614661ad-7075-46ca-a704-f77089f91860)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/42528adb-254f-4e4d-9cd1-88f4d883b712)

**Comment by suyuanlin** [comment]
大哥你解决了吗？我按照上面的截图来配置还是出不来呢？
前后端版本：master，vue3
也没找到帮助文档上写的菜单，这个地址说的菜单
https://help.jeecg.com/chart/dashboard/config/menu.html
