### ISSUE TITLE
fastjson安全问题

### ISSUE THREAD

**Issue by dolphin-dragon** [jeecgboot/jeecg-boot#5805]
##### 版本号：
涉及所有版本

##### 问题描述：
由于fastjson安全漏洞频繁发生问题，能否考虑解除对fastjson的深度依赖处理

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/16265780/d7cd9058-28c7-427a-b725-235d562691ff)

**Comment by zhangdaiscott** [comment]
漏洞编号？
