### ISSUE TITLE
markdown插件加载不出来

### ISSUE THREAD

**Issue by Jarvisssss** [jeecgboot/jeecg-boot#5807]
版本号：jeecgboot-vue3 3.4.3
前端版本：vue3版
问题描述：markdown插件加载不出来，没有报错，找不到原因
官方演示地址的也加载不出来了
截图&代码：
这是应用上：
<img width="657" alt="微信图片_20240111162955" src="https://github.com/jeecgboot/jeecg-boot/assets/39944949/88e85c1d-fea4-43bc-b0bd-afd38c83b772">
这是官方演示地址也不显示：
![QQ图片20240111162810](https://github.com/jeecgboot/jeecg-boot/assets/39944949/bcea81bd-cbb8-47a1-8e66-b23ce5ee2709)

![QQ图片20240111162810](https://github.com/jeecgboot/jeecg-boot/assets/39944949/547b9128-0a5b-4f51-aba1-37c2377b3535)

**Comment by zhangdaiscott** [comment]
参考最新版改下地址

**Comment by Jarvisssss** [comment]
你好，邮件已收到，我会尽快回复你，谢谢

**Comment by Jarvisssss** [comment]
> 参考最新版改下地址
我改成最新版3.9.8的地址，还是加载不出来，您能具体贴一下改的地方吗？
