### ISSUE TITLE
编译后端报错

### ISSUE THREAD

**Issue by webbncom** [jeecgboot/jeecg-boot#5811]
##### 截图&代码：
![1705055464632](https://github.com/jeecgboot/jeecg-boot/assets/67270373/cbc99c50-11a2-4229-add3-31fee087dbbf)

**Comment by zhangdaiscott** [comment]
clean下项目，maven刷新下

**Comment by webbncom** [comment]
还是一样的报错，新下载的，是不是下载的源码有问题
