### ISSUE TITLE
lombok 版本与 jdk 21 不兼容

### ISSUE THREAD

**Issue by al0n9** [jeecgboot/jeecg-boot#5814]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
当前 pom 中未指定 lombok 版本，默认版本不支持 jdk21，导致用 jdk21 编译时报错：'Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field ‘com.sun.tools.javac.tree.JCTree qualid’

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
########

指定 logmbok 版本为 1.18.30 及以上，就可以解决问题。
	<properties>
...
		
		<lombok.version>1.18.30</lombok.version>
	</properties>
	<dependencies>
...
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
		</dependency>
  
	</dependencies>

**Comment by zhangdaiscott** [comment]
springboot3?

**Comment by EightMonth** [comment]
spring boot 3.2.x才开始支持JDK21
master分支的spring boot版本是2.7.x，最高支持JDK 17
springboot3分支的spring boot 版本是3.1.x，最高支持JDK 17
