### ISSUE TITLE
请问JimuReportConfiguration被多次创建应该如何处理

### ISSUE THREAD

**Issue by zau11berer** [jeecgboot/jeecg-boot#5817]
##### 版本号：
3.6.1

##### 问题描述：
> 使用componentScan扫描了自己的业务包，单体启动，加入了一个UniNameGenrator用来命名bean
> ![image](https://github.com/jeecgboot/jeecg-boot/assets/13461275/a14d1eda-3f8f-436b-bef7-89ace5cd3168)
> ![image](https://github.com/jeecgboot/jeecg-boot/assets/13461275/1bbd74e5-0cc3-464a-ac14-b7d1a85b746e)

basepackages中定义"org.jeecg", 并且加入nameGenerator后，启动时会报jmReportUploadConfig创建了两次
![image](https://github.com/jeecgboot/jeecg-boot/assets/13461275/4ca63e05-af23-4645-8656-f7bcb7fa13c1)

请问应该如何修改

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
什么意思？为什么会重复创建

**Comment by zau11berer** [comment]
> 什么意思？为什么会重复创建

我用一个新的项目测试，加入nameGenerator之后，就会提示创建两个jimuReportUploadConfig
![image](https://github.com/jeecgboot/jeecg-boot/assets/13461275/01ee182d-56a7-4ae2-bf26-ea614490f51f)
