### ISSUE TITLE
quartz 表名大小写的问题

### ISSUE THREAD

**Issue by lyongdee** [jeecgboot/jeecg-boot#5818]
##### 版本号：
v3.2.6

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
代码中有 quartz 相关的查询，表名是全大写，在 MySQL 大小写敏感的环境中会报错，建议全部改成小写 (jeecgboot-mysql-5.7.sql表名本是小写)。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
设置数据库不区分大小写，这个是quartz 底层问题
