### ISSUE TITLE
企业微信配置如何修改

### ISSUE THREAD

**Issue by dazhaozhao** [jeecgboot/jeecg-boot#5820]
##### 问题描述：
如图 这个api 写死了 无法更改，私有部署的企业微信获取token等地址都不一样 目前这个用不上啊。

##### 截图&代码：

<img width="1600" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/45939769/b583c3f4-a446-4441-86c0-2c9dd568ee4f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
jeecg暂不支持私有部署企业微信的对接
