### ISSUE TITLE
运行项目，提示redisServer bean命名冲突

### ISSUE THREAD

**Issue by Gui-lin-S** [jeecgboot/jeecg-boot#5821]
##### 截图&代码：
![QQ截图20240117231636](https://github.com/jeecgboot/jeecg-boot/assets/156915893/34ef421f-3122-4928-b6e2-544294c667cf)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你自己改什么了？

**Comment by Gui-lin-S** [comment]
我自己什么都没有更改，按照文档正常启动项目，但是就会出现这个问题

**Comment by zhangdaiscott** [comment]
我们无法重现
