### ISSUE TITLE
Subject does not have permission [screen:biz_compensate:add]

### ISSUE THREAD

**Issue by bzdqsmmzh** [jeecgboot/jeecg-boot#5822]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/83258750/a944f851-825c-488a-86de-c4db264c6833)
![image](https://github.com/jeecgboot/jeecg-boot/assets/83258750/1a6dd5d0-dcaa-4278-afef-08de7b3c12ac)
![image](https://github.com/jeecgboot/jeecg-boot/assets/83258750/c65360e5-3341-42ef-a949-68d7be23c4a1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你执行升级sql，分配接口权限

**Comment by bzdqsmmzh** [comment]
代码生成器生成的sql还是项目的升级sql

**Comment by bzdqsmmzh** [comment]
> 你执行升级sql，分配接口权限

代码生成器生成的sql吗，已经执行了，还是项目升级的sql文件

**Comment by zhangdaiscott** [comment]
执行后，给角色分配权限
