### ISSUE TITLE
微服务之间免Token问题

### ISSUE THREAD

**Issue by zhaohuating** [jeecgboot/jeecg-boot#5823]
##### 问题描述：
![1061705563363_ pic_hd](https://github.com/jeecgboot/jeecg-boot/assets/13688825/6549b55b-934e-40b0-8801-160b18002b29)

服务在启动时需要调用其他服务数据构建缓存，根据文档跨服务免token操作（https://help.jeecg.com/java/springcloud/dev/token.html），还是报token失效，删除redis相关用户token，重启服务就可以调通

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/13688825/abb7bfc1-1308-403c-bfcf-017801ef8261)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13688825/42351813-afed-46a8-b46c-4540dae56ae6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的客户端怎么写的

**Comment by zhaohuating** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13688825/c4015488-f360-4e7c-9d0c-1fa236037735)

**Comment by zhaohuating** [comment]
> 你的客户端怎么写的

![image](https://github.com/jeecgboot/jeecg-boot/assets/13688825/91304589-9c6c-4702-a702-b44ef0f93d9a)

**Comment by zhangdaiscott** [comment]
看不出来

**Comment by JiaLe-An** [comment]
解决了吗，我也是这个问题！
