### ISSUE TITLE
Nacos 403

### ISSUE THREAD

**Issue by lyongdee** [jeecgboot/jeecg-boot#5825]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
nacos 服务开启鉴权后，启动 demo-cloud-start 提示 403错误

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/369124/532e7193-71dd-47b7-9ca9-d97da91eb12d)

![image](https://github.com/jeecgboot/jeecg-boot/assets/369124/34f00ae2-f596-4318-b8f6-62c137139365)

![image](https://github.com/jeecgboot/jeecg-boot/assets/369124/66dc7b38-661f-44b9-8cfa-558418d0395e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不要设置账号和密码
