### ISSUE TITLE
最新3.6.2代码部署后，报表设计器、仪表盘设计器、通知公告查看等功能打开404

### ISSUE THREAD

**Issue by hejie3225** [jeecgboot/jeecg-boot#5827]
##### 问题描述：

官方代码按照文档部署后，界面出现部分功能不行访问的情况（如报表设计器、仪表盘设计器、通知公告查看等功能）无法访问，请问什么原因

##### 截图&代码：
![AXX6}93BVULWXBW04Q@_0}N](https://github.com/jeecgboot/jeecg-boot/assets/12691803/9d6488e5-1a98-4a1c-9a96-d45148061900)

![$Y~R}V S(V0BZDX%3S3)BGK](https://github.com/jeecgboot/jeecg-boot/assets/12691803/6bc6198f-688f-452a-ba23-f23ee965688d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
本地没问题？

**Comment by hejie3225** [comment]
本地没有问题，但是，生产环境下通过nginx代理后就有问题

**Comment by zhangdaiscott** [comment]
前端配置截图

**Comment by hejie3225** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/647b5103-fdef-449b-b1aa-58a2f3e7eaf1)

**Comment by hejie3225** [comment]
> 前端配置截图

![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/6a97b671-c08c-4da1-9a70-0565ed53a0da)

**Comment by zhangdaiscott** [comment]
这个是是后台接口访问地址吗
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/b05f9d23-816f-4b34-9bdd-27b1e8a6bae8)

**Comment by hejie3225** [comment]
这个不是后台接口地址，是前台访问地址，根据这个问题，我做了修改，但是访问出现如下问题，下方是截图信息，请指正，非常感谢
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/13fab4c5-bc42-40f2-a3ae-102d6c8a23dc)
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/6712b6ca-bb26-4558-b616-dc0607ea6ad6)
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/15e5453c-5f4f-4715-a9d0-1c4a4c3c8a21)
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/55b85631-ae38-430f-9e12-5c707c3064c8)
