### ISSUE TITLE
配置微服务报错

### ISSUE THREAD

**Issue by hengguangjie** [jeecgboot/jeecg-boot#5828]
##### 前端版本：vue3版？还是 vue2版？
 vue2

##### 问题描述：
gitee上下载源代码按照文档配置微服务，启动JeecgSystemCloudApplication时以下错误

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/65932982/67cb2438-f222-4c81-a92f-b7a8c6aa3264)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
maven 怎么勾选的

**Comment by hengguangjie** [comment]
> maven怎么勾选的

已解决。host文件注释掉了。sorry
