### ISSUE TITLE
@qiaoqiaoyun 依赖不自动下载 缺少相关依赖下载

### ISSUE THREAD

**Issue by hjhcos** [jeecgboot/jeecg-boot#5830]
##### 版本号：
v3.6.2 (3.6.0升级)

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
node_modules 缺少 @qiaoqiaoyun 依赖从而导致报错 @qiaoqiaoyun/drag-free/lib/index.css 不存在

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/f63d644b-ef83-46bd-a3b3-0b8d58c92ff7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
最新版不需要这个了，把老的仪表盘前端代码删掉就行
