### ISSUE TITLE
3.6.1 vue2版本，管理员没用角色管理的权限，无法查询（可以添加）

### ISSUE THREAD

**Issue by MuShan-bit** [jeecgboot/jeecg-boot#5832]
##### 问题描述：
vue2 版本启动之后，管理员没有角色管理和租户管理的权限（只有查询权限被限制，增删改都可以正常处理）。导致没办法通过修改角色权限获取其它权限。

##### 截图&代码：

![Snipaste_2024-01-20_22-36-53](https://github.com/jeecgboot/jeecg-boot/assets/77890771/2badd45a-d69b-40f3-9145-1860160c8366)

![Snipaste_2024-01-20_22-39-34](https://github.com/jeecgboot/jeecg-boot/assets/77890771/b0042f5e-ab51-46d1-82e6-4d68d0255408)

**Comment by MuShan-bit** [comment]
我对比了一下正常的功能，比如用户管理，它的代码是这样写的
```java
@PermissionData(pageComponent = "system/UserList")
```
`@RequiresPermissions` 在前台也只能提供给按钮权限设置，菜单分配的是前端组件，用户管理这里也是用前端组件控制的权限。所以这里代码是不是有问题，**还是有其它方法能处理**。
我将注解换成 `@PermissionData(pageComponent = "system/RoleUserList")` 后就能正常访问了。
```java
@PermissionData(pageComponent = "system/RoleUserList")
```

**Comment by MuShan-bit** [comment]
好像是sql的问题，db里面提供的数据库导入有1301个错误，全都是个权限有关的。
![Snipaste_2024-01-21_10-25-47](https://github.com/jeecgboot/jeecg-boot/assets/77890771/db504692-f0bf-470f-beb6-fe3abc135698)

**Comment by MuShan-bit** [comment]
没问题了，问题已经解决了，数据库报错。是我自己不小心鼠标碰到不知道，数据库源码错位了

**Comment by hengguangjie** [comment]
> 没问题了，问题已经解决了，数据库报错。是我自己不小心鼠标索引不知道，数据库源码错位了

是啥问题，我也遇到了？
