### ISSUE TITLE
登录失败5次后锁定10分钟有误，实际只锁定了10S

### ISSUE THREAD

**Issue by ma19881117** [jeecgboot/jeecg-boot#5833]
##### 版本号：
3.6.1

##### 问题描述：
登录失败5次后锁定10分钟有误，实际只锁定了10S

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ma19881117** [comment]
private void addLoginFailOvertimes(String username){
		String key = CommonConstant.LOGIN_FAIL + username;
		Object failTime = redisUtil.get(key);
		Integer val = 0;
		if(failTime!=null){
			val = Integer.parseInt(failTime.toString());
		}
		// 10分钟
		redisUtil.set(key, ++val, 10);
	}

**Comment by zhangdaiscott** [comment]
cr

**Comment by 1298191366** [comment]
已修复，待新版本发布
