### ISSUE TITLE
Knife4j文档请求异常

### ISSUE THREAD

**Issue by ppanjiabao** [jeecgboot/jeecg-boot#5834]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
无关

##### 问题描述：
模块：单体升级为微服务

gateway打开页面显示Knife4j文档请求异常
启动顺序是按照nacos->demo->system->gateway
gateway前启动也不行

我照着文档操作的，是哪里有问题么？
启动有两个警告，看了前面的问题好像说是不影响
一个是demo和system启动警告：Customize redis listener handle [ loderRouderHandler ], does not exist！
一个是gateway启动警告：converter can not convert rules because source is empty
![image](https://github.com/jeecgboot/jeecg-boot/assets/94954035/cfcd805a-239d-442d-a725-3f26839b1142)
![image](https://github.com/jeecgboot/jeecg-boot/assets/94954035/708beca1-e681-4f07-8c34-9aa886c949b9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/94954035/b9752aa6-29e0-482b-9526-437f547327fb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
dev模式启动？swagger开启了吗

**Comment by ppanjiabao** [comment]
> swagger开启了吗

<img width="289" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/94954035/cc37d66d-b4ba-442d-8792-7a0a0361916a">
请问网关的swagger在哪里开启？

**Comment by ppanjiabao** [comment]
> dev模式启动？swagger开启了吗

是dev+springcloud微服务启动，按照文档一步一步操作的，我看前面的issue都没说怎么解决的就关闭了，所以才来询问的

**Comment by zhangdaiscott** [comment]
dev模式默认是打开的，看看nacos中的配置文件
