### ISSUE TITLE
修改系统主题色代码，部分页面颜色变成了灰色

### ISSUE THREAD

**Issue by hejie3225** [jeecgboot/jeecg-boot#5835]
##### 问题描述：
修改系统主题色代码，后如下图所示，中间的颜色变成了灰色，请问如何处理，谢谢

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/e0521215-24da-4d59-b45c-d3748623a7ec)
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/d1b51041-f395-47e8-a605-7c7175a361c0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/3e58e968-3b9b-4dd1-941c-53db8b09c24e)
这是antd-design-vue基于主题色衍生（算法生成）出来的姊妹色（不透明度降低了），如果你觉得不好看需要自己调整了。
