### ISSUE TITLE
Jeecg服务器私服 Maven JeecgBoot 3.5.1 以后的依赖都不存在 

### ISSUE THREAD

**Issue by hjhcos** [jeecgboot/jeecg-boot#5837]
##### 版本号：
JeecgBoot 3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
相关问题 #5762 Maven库不存在
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project jeecg-boot-parent: Failed to deploy artifacts: Could not transfer artifact org.jeecgframework.boot:jeecg-boot-parent:pom:3.6.0 from/to jeecg (http://maven.jeecg.com:8090/nexus/content/repositories/jeecg): authentication failed for http://maven.jeecg.com:8090/nexus/content/repositories/jeecg/org/jeecgframework/boot/jeecg-boot-parent/3.6.0/jeecg-boot-parent-3.6.0.pom, status: 401 Unauthorized

##### 截图&代码：
![950b06513907c3a4611b7a504a0b6cd](https://github.com/jeecgboot/jeecg-boot/assets/54499588/05c11505-f260-4270-a5b3-69c5a771476a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
请参考文档：https://help.jeecg.com/java/setup/maven.html

**Comment by hjhcos** [comment]
现在服务器可以啦
