### ISSUE TITLE
多租户tenantId在本地环境和生产环境下不一样

### ISSUE THREAD

**Issue by peak666** [jeecgboot/jeecg-boot#5839]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
开启多租户模式下，本地和生产环境同连一个数据库，通过同一个账号登录，本地启动确实过滤了多租户数据，tenantId=当前登录人的tenantId，但是生产环境为啥没过滤呢，tenantId=0，很奇怪啊，看配置文件也没什么区别

##### 截图&代码：
本地idea控制台打印的sql语句
![003](https://github.com/jeecgboot/jeecg-boot/assets/42790595/b8481fb8-0923-4fc9-a516-68eeca7a5f4c)

![002](https://github.com/jeecgboot/jeecg-boot/assets/42790595/e63d573b-e740-4fcd-a52b-193389502606)

生产环境jar包运行的控制台
![001](https://github.com/jeecgboot/jeecg-boot/assets/42790595/95f86060-c145-4f37-99a6-f6551b65e1f6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
生产环境，看看请求header中传递租户了吗
