### ISSUE TITLE
Excel导入时空行校验问题

### ISSUE THREAD

**Issue by nooooom** [jeecgboot/jeecg-boot#5840]
##### 版本号：
3.6.2
##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：
有的行曾经有数据或者不小心动到单元格内容，后来给里边的内容都删了，但是没有内容也会被当做是一条数据导入。

看到过之前的一个 issue [autopoi导入excel 如果单元格被设置边框，即使没有内容也会被当做是一条数据导入](https://github.com/jeecgboot/jeecg-boot/issues/2484)，解决方法是在实体类中添加一个 isNullObject 方法，如果实体类字段过多，这个方法需要大量的判空校验，而且每个导入实体类都添加一个这种方法过于繁琐。

能否在 autopoi 中增加判断空行的逻辑，如果空字段数 >= 列数就不处理此行数据。

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，新版本发布。

**Comment by liuyuyua** [comment]
这个怎么使用呢
