### ISSUE TITLE
子表字段popup弹窗调用的配置报表数据不更新

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#5841]
##### 版本号：
v3.5.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1. 在配置报表中定义了一个表，并把这个配置报表绑定到主附表的附表中的一个字段，通过popup弹窗显示该报表；
2. 当配置报表中新增，或者删除一条数据的时候，在子表的popup弹窗里却没有更新，显示的还是之前的数据。这是怎么回事？
3. 由于项目已经开发了很多，如果已经在新版本中修复了此bug，是否可以告知，如何能手动修改此bug，而不是整体换新版本平台？

##### 截图&代码：
![微信截图_20240123180447](https://github.com/jeecgboot/jeecg-boot/assets/37827583/8d2a68bb-425b-4623-95ce-1b0459bc668f)
![微信截图_20240123181052](https://github.com/jeecgboot/jeecg-boot/assets/37827583/1d4e839b-e741-4b69-8a8a-5a10631195ec)
![微信截图_20240123181831](https://github.com/jeecgboot/jeecg-boot/assets/37827583/1e67b9bf-23c7-4608-a18f-e08a5041aa03)
![微信截图_20240123182050](https://github.com/jeecgboot/jeecg-boot/assets/37827583/3b6a2ccb-39b7-4f7f-bb5e-e48e68623b4e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个问题好像修复了，查下issue和pr

**Comment by ciahua** [comment]
> 这个问题好像修复了，查下issue和pr

看到有个帖子有说是在新版本里修复了，但是没有办法全部更新版本，只能针对这个问题具体修复，所以需要了解，在哪里修改才能解决这个问题。

已经困扰很久了，麻烦高手指点一下！谢谢啦！
