### ISSUE TITLE
a-progress组件直接在页面中使用，页面上无法显示进度条；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5842]
##### 截图&代码：
`<div class="progress">
            <a-progress :percent="50" :show-info="false" />
          </div>`

**Comment by zhangdaiscott** [comment]
截图说明

**Comment by RacingK93** [comment]
> 截图说明

<div class="progress">
            <a-progress :percent="50" :show-info="false" />
          </div>
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/cb74e7c8-1214-4d62-ad26-b840ae8f8816)
红框这儿没显示出来

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你本地可在 src/components/registerGlobComp.ts 文件：
<img width="817" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/cee63b48-c754-4d6f-9c2f-3fd8adaaef17">
<img width="820" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/f06e90dd-a73d-4f0c-92c6-bb93166ef18c">
把a-progress注册上即可。
