### ISSUE TITLE
菜单管理界面点击展开的加载速度很慢

### ISSUE THREAD

**Issue by yzbzwyyt** [jeecgboot/jeecg-boot#5843]
##### 版本号：
当前版本： 3.5.2（发布时间：2023-06-12）

##### 前端版本：vue3版？还是 vue2版？
VUE3

##### 问题描述：

打包后的环境下，菜单管理界面点击展开的加载速度非常慢，我已经将代码中使用render的地方去除，还是依旧很慢

##### 截图&代码：

![捕获](https://github.com/jeecgboot/jeecg-boot/assets/157555619/e03a9ab7-7b23-48bc-8975-d241843d1d11)

https://github.com/jeecgboot/jeecg-boot/assets/157555619/d671ec9b-6303-4a57-8f32-04553d9871ca

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
看看演示系统慢吗，不慢的话，看看自己升级下前端
