### ISSUE TITLE
微服务搭建后登录无权限

### ISSUE THREAD

**Issue by hengguangjie** [jeecgboot/jeecg-boot#5844]
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
根据文档搭建微服务，后端前端启动后使用admin登录，菜单只有一个 系统管理，角色管理提示 无权限

##### 截图&代码：
![fc1cd10f1187e20216ce66a2e7bef29](https://github.com/jeecgboot/jeecg-boot/assets/65932982/483afd8d-2687-4a67-a6e9-0cceb41efaa9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前vue2版本最新代码只支持到jeecgboot 3.4.3版本，一定注意。
