### ISSUE TITLE
token失效问题

### ISSUE THREAD

**Issue by hechademaonini** [jeecgboot/jeecg-boot#5846]
##### 版本号：
v2.1.2

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
throw new AuthenticationException("Token失效，请重新登录!"); 
后台返回前端的值并没有"Token失效，请重新登录!"，是http 500错误的网页，导致前端无法正确跳转登录页。

注意：我排除了spring boot 自带的Jackson依赖，重新引入了jackson-annotations、jackson-core、jackson-databind，版本为2.15.1，不知这个会否对AuthenticationException有影响

##### 截图&代码：
![1706083399266](https://github.com/jeecgboot/jeecg-boot/assets/128658211/02934517-57d8-4567-86bd-0351c3eb860d)

**Comment by zhangdaiscott** [comment]
版本太老，自己debug处理吧
