### ISSUE TITLE
项目打包上线控制台报错

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5852]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/c7d6021c-fc48-46f7-823b-b8a7b230a070)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果不影响功能，忽略，这种问题猜不出来
