### ISSUE TITLE
 当前vue依赖锁版本3.3.11一切正常 但是一旦升级到3.4+后 table表格展开|多选 全部失效

### ISSUE THREAD

**Issue by yangtaowei** [jeecgboot/jeecg-boot#5854]
##### 问题描述：
问题位置 全项目 table表格
好像是个严重问题 当前vue依赖锁版本3.3.11一切正常 但是一旦升级到3.4+后 table表格展开|多选 全部失效
PS:vue相关依赖也已同步更新

##### 截图&代码：

这个是点击之后的报错
<img width="443" alt="点击多选或者展开" src="https://github.com/jeecgboot/jeecg-boot/assets/46802927/8a475eb1-0437-41f9-b25c-851d610a4b96">

这个是我对多选的暂时处理方法，展开暂时没有一个好的解决方法
<img width="1007" alt="CustomSelectHeader文件变更" src="https://github.com/jeecgboot/jeecg-boot/assets/46802927/14b94ee8-2a9a-4490-90ae-fa6b6cb247ad">
<img width="1053" alt="CustomSelectHeader文件变更2" src="https://github.com/jeecgboot/jeecg-boot/assets/46802927/852a730a-b0f1-4811-8faa-413c28d48161">
<img width="936" alt="useCustomSelection tsx变更" src="https://github.com/jeecgboot/jeecg-boot/assets/46802927/9066938e-a3c2-45e8-a4ac-d3cd0bdd372c">

**Comment by zhangdaiscott** [comment]
Ant Design Vue的问题，先不升级
