### ISSUE TITLE
旧版登录页上线之后样式全都不生效

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#5857]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/f28a0f79-e9bf-42dd-9f68-c88b00c5029f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/4dd3b89a-a337-458d-9b60-89ccb6ebed92)
这部分代码全都无法生效；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by yidao2000** [comment]
3.6.2连官网按钮的颜色都没了,BasicButton Color
http://boot3.jeecg.com/comp/basic/button

**Comment by zhangdaiscott** [comment]
补充截图说明

**Comment by yidao2000** [comment]
![111112222](https://github.com/jeecgboot/jeecg-boot/assets/12994137/d03f5d51-215c-4d8d-a080-9ba28fbed5a9)

**Comment by zhangdaiscott** [comment]
旧版登录页的样式全都不生效，截图看看

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
> ##### 版本号：3.6.2
> ##### 前端版本：vue3版
> ##### 问题描述：旧版登录页面放开之后，旧版登录页面的style里的样式全都无法打包上线生效成功；也就是我上线之后，打包构建部署完毕之后，线上系统打开，旧版登录页的样式全都不生效，不知道为什么；
> ##### 截图&代码：
> ![image](https://private-user-images.githubusercontent.com/18101484/299601225-f28a0f79-e9bf-42dd-9f68-c88b00c5029f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTY3NDgsIm5iZiI6MTcwNjQ5NjQ0OCwicGF0aCI6Ii8xODEwMTQ4NC8yOTk2MDEyMjUtZjI4YTBmNzktZTliZi00MmRkLTlmNjgtYzg4YjAwYzUwMjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyNDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZmY0YWIwMzc1NDVlZWE2N2M4YzQ1YWU1YmRmNmQxYzk1MjZiYzc1YmMxZWZkY2UwZTk4OGZmMDdmOTFiYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZUy_CE8v4x6mlADDGj021WZ8w2l_wcE_ijpqdRbJ0HU) ![image](https://private-user-images.githubusercontent.com/18101484/299601673-4dd3b89a-a337-458d-9b60-89ccb6ebed92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTY3NDgsIm5iZiI6MTcwNjQ5NjQ0OCwicGF0aCI6Ii8xODEwMTQ4NC8yOTk2MDE2NzMtNGRkM2I4OWEtYTMzNy00NThkLTliNjAtODljY2I2ZWJlZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyNDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0YjY2MjViNzcwMDg5ZWFjNGFhNDkzNDczOGRjZDJjMWU4NTcxMjE5ODRkMzk0NmM0MjAxMjVkMzI0NzI4Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G15umNMPXwVW0Bps3DDzrkb73x3g9KroLMQ7UY5R_Ns) 这部分代码全都无法生效；
> 
> #### 友情提示（为了提高issue处理效率）：
> * 未按格式要求发帖，会被直接删掉;
> * 描述过于简单或模糊，导致无法处理的，会被直接删掉；
> * 请自己初判问题描述是否清楚，是否方便我们调查处理；
> * 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

<img width="617" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/8199499/f0f70e10-9e61-46de-958d-c730d2090e0f">
本页面的根元素的类名应该是.jeecg-login非.jeecg
所以应该是:
```
.jeecg-login .jeecg-app-logo { }
.jeecg-login .jeecg-app-logo__title {}
```

**Comment by liaozhiyang** [comment]
> ![111112222](https://private-user-images.githubusercontent.com/12994137/299860374-d03f5d51-215c-4d8d-a080-9ba28fbed5a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTY3NDgsIm5iZiI6MTcwNjQ5NjQ0OCwicGF0aCI6Ii8xMjk5NDEzNy8yOTk4NjAzNzQtZDAzZjVkNTEtMjE1Yy00ZDhkLWEwODAtOWJhMjhmYmVkNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyNDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MGQ1N2Y4NzdkMTNhYmEzMzU0MzFmZTViYTFiN2NjM2U5YThiYzk1NWRjMzZmMWMzNmFiMGJhY2ZhZThjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWhea3PWx9i1pGWYkw9ijTcg3kmB_YcbteKvCXR-dWY)

在src/design/ant/index.less文件
把这个注释@import './btn.less';放开即可。这个当时忘了为什么注释了

**Comment by RacingK93** [comment]
> > ![111112222](https://private-user-images.githubusercontent.com/12994137/299860374-d03f5d51-215c-4d8d-a080-9ba28fbed5a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTY3NDgsIm5iZiI6MTcwNjQ5NjQ0OCwicGF0aCI6Ii8xMjk5NDEzNy8yOTk4NjAzNzQtZDAzZjVkNTEtMjE1Yy00ZDhkLWEwODAtOWJhMjhmYmVkNWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAyNDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MGQ1N2Y4NzdkMTNhYmEzMzU0MzFmZTViYTFiN2NjM2U5YThiYzk1NWRjMzZmMWMzNmFiMGJhY2ZhZThjNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWhea3PWx9i1pGWYkw9ijTcg3kmB_YcbteKvCXR-dWY)
> 
> 在src/design/ant/index.less文件 把这个注释@import './btn.less';放开即可。这个当时忘了为什么注释了

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/d29095eb-0366-448f-a0ac-1abae1b9233f)
不行啊，放开注释@import './btn.less';之后还是不行，背景图都显示不出来，logo和title样式也是不对的（涉及公司就不截进去了），反正本地可以，打包上线之后就没有::before的样式；
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/5f7da0e8-e7d2-4923-bd04-f4e7db309fdc)

正常应该是有这个样式的，但是现在没有；
![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/12a648de-2b45-4b6f-a495-d4a6ca32c63c)

**Comment by liaozhiyang** [comment]
上面那个放开限制的，我是回复上面那位同学的。

![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/b3417593-a36d-45ec-84fd-3eaef08a0fce)
这是下载的3.6.2版本我打包之后的预览效果，没复现你的问题啊。你可以下载开源版本的3.6.2，改成旧版的登录然后打包本地访问下，看是否有如上问题。如果没有看看是不是因为你改了什么配置
