### ISSUE TITLE
仪表盘设计器编辑跳转页面无法获取接口

### ISSUE THREAD

**Issue by ysrdear** [jeecgboot/jeecg-boot#5859]
##### 问题描述：
仪表盘设计器跳转到编辑页面时，页面的domainURL没有端口，导致接口全部报错

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/36125827/e5a14d2c-6d93-4b0a-baa0-76262ce894ce)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你配置有问题，为什么不是通过后台地址访问

**Comment by ysrdear** [comment]
> 你配置有问题，为什么不是通过后台地址访问

128这个是后台地址啊，配置的话是在前端还是后台配置呢？

**Comment by ysrdear** [comment]
> 你配置有问题，为什么不是通过后台地址访问

我看了demo上的，是域名不带端口

![image](https://github.com/jeecgboot/jeecg-boot/assets/36125827/e0334a75-dc73-4550-b33e-9783a090f7e0)
