### ISSUE TITLE
springboot3  积木报表聚合分组失败

### ISSUE THREAD

**Issue by catlvsuger** [jeecgboot/jeecg-boot#5863]
##### 截图&代码：1 数据源：select * from test_order_product order by pro_type, product_name
![image](https://github.com/jeecgboot/jeecg-boot/assets/39261781/6c6c4992-1732-42e1-99be-2ab8f0e5fb60)
2 报表设置：
![企业微信截图_17064925603594](https://github.com/jeecgboot/jeecg-boot/assets/39261781/3041169a-e729-4ac5-8854-d9d7f9d8407c)
正常显示：
![image](https://github.com/jeecgboot/jeecg-boot/assets/39261781/4ca8ff80-0786-40d6-95a9-5c6c2bbc0132)
3 设置聚合分组，报错：
![企业微信截图_17064926743607](https://github.com/jeecgboot/jeecg-boot/assets/39261781/d3638efe-f3e7-4de2-941e-3702129ab01e)
![企业微信截图_17064926862504](https://github.com/jeecgboot/jeecg-boot/assets/39261781/3e324d6b-cac9-4536-8eee-5720156470d4)
4 报表配置JSON：
[聚合分组测试.json](https://github.com/jeecgboot/jeecg-boot/files/14078787/default.json)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
请先升级积木报表到最新版 1.7.0看问题是否存在
