### ISSUE TITLE
3.6.2 版本SQL升级语句不完整

### ISSUE THREAD

**Issue by hjhcos** [jeecgboot/jeecg-boot#5868]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
原本想着更新内容不大 直接使用版本说明的SQL语句来执行更新，结果发现SQL语句不完整

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/12163dbc-fcc7-4bbc-ae1f-52704c658adb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/log

**Comment by hjhcos** [comment]
建议不要修改原本设计好的字段的长度
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/0ec2d1f4-18e6-4eb1-b0bd-45ed95f02d70)

**Comment by hjhcos** [comment]
建议不要修改已经设置好的字段长度
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/4fdbc81b-9025-43ba-b3b8-b297697288f0)
