### ISSUE TITLE
数据字典编辑页展示问题

### ISSUE THREAD

**Issue by Witnin** [jeecgboot/jeecg-boot#5869]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/33174005/6f56e222-6c2b-43a1-bf36-f5cd7806369d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/33174005/792f4e02-d063-414b-bca6-c42fea51c329)
![image](https://github.com/jeecgboot/jeecg-boot/assets/33174005/928035a2-65f9-4168-81f1-cd6899b130b4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果值是数字，设置下类型
