### ISSUE TITLE
数据字典转换问题，通过配置dictTable、dicText、dicCode无法查询出dictText字段【急急急！！】

### ISSUE THREAD

**Issue by mili-li** [jeecgboot/jeecg-boot#5872]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
从3.6.1升级到3.6.2后，原来可以通过配置dictTable、dicText、dicCode做字典转换，现在只有dicCode的方式可以用
@Dict(dictTable = "xxx", dicText = "xxx", dicCode = "id") -- 不可以了
@Dict(dicCode = "xxx") --可以
##### 截图&代码：
<img width="1109" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/66288141/904d064c-679a-42a6-be86-f79615cdb1a2">
<img width="1012" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/66288141/34bcd3e3-adcf-45cc-b994-ce14ec512f86">
<img width="700" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/66288141/1bac973e-1a59-4a44-9326-7d7e51bb089b">
<img width="973" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/66288141/e0bc0e57-615a-41b3-ae6f-78e29867096a">

**Comment by zhangdaiscott** [comment]
默认没问题

**Comment by mili-li** [comment]
@zhangdaiscott 什么叫默认没问题，我用的也是jeecg官方默认的代码呀，是我写法不对吗？
