### ISSUE TITLE
js增强里添加个按钮的导出 使用getAction(url),后台返回流文件，但是浏览器不下载。 

### ISSUE THREAD

**Issue by ZhAnGYi706** [jeecgboot/jeecg-boot#5873]
##### 截图&代码：
![微信截图_20240201145732](https://github.com/jeecgboot/jeecg-boot/assets/98219873/9744e841-3df6-4bd5-9676-528fb11b371c)

**Comment by zhangdaiscott** [comment]
getaction是请求，不是用于下载的

**Comment by ZhAnGYi706** [comment]
那我应该怎么完成这个需求呢？

**Comment by ZhAnGYi706** [comment]
> getaction是请求，不是用于下载的
那我应该怎么完成我这个需求呢？

**Comment by zhangdaiscott** [comment]
使用js的原始方式去调接口

**Comment by ZhAnGYi706** [comment]
> 使用js的原始方式去调接口

身份认证这里能做吗？怎么配置

**Comment by ZhAnGYi706** [comment]
> 使用js的原始方式去调接口 例如window.open方式试试

window.open和location.href会跳转页面，不可用 我用fetch()发送请求需要权限配置
