### ISSUE TITLE
后端运行报错

### ISSUE THREAD

**Issue by IfMolu** [jeecgboot/jeecg-boot#5874]
##### 前端版本：vue3版？还是 vue2版？
 vue3

##### 问题描述：
后端运行时报错

##### 截图&代码：

![QQ截图20240201161532](https://github.com/jeecgboot/jeecg-boot/assets/114966221/3b237fbe-19aa-4843-a8c7-e030a1ee8a8a)
![QQ截图20240201161540](https://github.com/jeecgboot/jeecg-boot/assets/114966221/2a103001-cae2-45bd-afa5-034a400829f7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
缺表
