### ISSUE TITLE
3.6.2版本使用sql server2022无法启动

### ISSUE THREAD

**Issue by mianfeidog** [jeecgboot/jeecg-boot#5875]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我使用的数据库是sql server 2022，启动后台的时候控制台出现了mysql 的flyway的语句，导致无法启动，有什么方法可以使用sql server 数据并启动成功吗？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
其他数据库注释掉flyway依赖
