### ISSUE TITLE
单表树，数据库记录多了后速度极慢

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/jeecg-boot#5876]
##### 问题描述：
online表单开发，使用单表树，数据库记录多了后，速度极慢，几百行数据，差不多要几分钟甚至超时查询不出来！不启用树，速度正常。如果使用生成的代码，速度也很快！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35764692/511c5bcd-568b-41a5-adf3-f0ad4540555a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收录 cr

**Comment by hoperunChen** [comment]
已修复，请等待新版本发布。
