### ISSUE TITLE
菜单设置的时候，如何给页面传值呢？

### ISSUE THREAD

**Issue by gaohuangjin** [jeecgboot/jeecg-boot#5877]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/15665537/29d37870-be43-4a90-967e-aca4fa4d7ef0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
写死的参数直接？就行，参考
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/62e2e3b2-e1ca-40e9-a87c-e7bd02c46a8b)
