### ISSUE TITLE
数据库超时

### ISSUE THREAD

**Issue by 191474639** [jeecgboot/jeecg-boot#5878]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

连接数据库老是超时，应该怎么优化
##### 截图&代码：
![f1f6ecc0cb9343ee419b165b1213854](https://github.com/jeecgboot/jeecg-boot/assets/26876543/145603ae-b0d5-43de-9984-e1a37509b02e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
跟程序没关系，确认数据库配置或者连接池配置
