### ISSUE TITLE
考虑添加系统全局配置表

### ISSUE THREAD

**Issue by WMD001** [jeecgboot/jeecg-boot#5881]
##### 版本号：
master

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
考虑添加系统全局配置表，用于存储全局的系统配置，例如数据填报的开关

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
个性化需求，自定义即可
