### ISSUE TITLE
CAS单点登录，获取动态盐值问题

### ISSUE THREAD

**Issue by moumoukings** [jeecgboot/jeecg-boot#5885]
版本号：3.6.1

前端版本：vue3版

问题描述：
框架中使用了动态盐值，在实现服务端时动态盐值应该怎么获取。
求解答，谢谢！

_Originally posted by @bangcd999 in https://github.com/jeecgboot/jeecg-boot/issues/3353#issuecomment-1006255717_

**Comment by zhangdaiscott** [comment]
没明白
