### ISSUE TITLE
企业微信集成，同步用户信息时，特殊字符导致失败的问题

### ISSUE THREAD

**Issue by hejie3225** [jeecgboot/jeecg-boot#5887]
##### 问题描述：
系统设置-》第三方配置--》企业微信集成中，同步用户信息时，提示成功，但实际上sql插入报错，如下图，原因是用户的昵称有emoj表情导致的插入报错问题。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/1727852e-b0fb-4bc2-9f98-786a941ad463)
![image](https://github.com/jeecgboot/jeecg-boot/assets/12691803/915fd907-5487-4184-8714-f1036dc9e339)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你的数据库是什么版本，mysql升级高版本就支持特殊字符

**Comment by hejie3225** [comment]
> 你的数据库是什么版本，mysql升级高版本就支持特殊字符

我的是mysql 5.7

**Comment by hejie3225** [comment]
> 你的数据库是什么版本，mysql升级高版本就支持特殊字符

mysql版本是5.7，数据库字符集是utf8mb4

**Comment by 1298191366** [comment]
你修改字符集应该就没问题了。我也是5.7的mysql
报错日志
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/1b9d3541-1f01-4f0c-a8ce-e0f260cd8de8)
数据库realname字符集
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/16e4ba27-6b87-4666-8555-525d5dae9f76)

![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/5022bc81-62a7-4d3d-a311-953bbb85e3b9)
