### ISSUE TITLE
多端部署时websocket广播消息使用问题咨询

### ISSUE THREAD

**Issue by cxyax** [jeecgboot/jeecg-boot#5888]
##### 版本号：
v2.4.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在生产环境时我们会起多个服务端（同jar包不同端口，使用nginx进行负载均衡）
在本机起一个端使用websocket的时候，使用pushMessage可以正常的进行推送消息，但是sendMessage不行
想具体问一下像这种情景如何使用websocket发送数据？

在来问题之前已经看了以下两篇文章：
https://help.jeecg.com/java/advanced/WebSocket.html
https://help.jeecg.com/java/advanced/WebsocketBiz.html

没有找到适合我们这种场景的解决方案，我们在onOpen和onClose中已经添加了redis存储
并且还有一个问题是，在webscoket类中无法使用@Autowired注解引入，是什么原因？
麻烦帮忙解答一下

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/58779674/83507bf3-5608-4b47-a712-7bb3eaad7e69)
![image](https://github.com/jeecgboot/jeecg-boot/assets/58779674/94c5f70f-bf51-4f80-80c2-11e952482402)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本太老，你可以参考最新版采用redis发布订阅的机制推送消息，实现了类似MQ的功能
