### ISSUE TITLE
k8s微服务场景下xxl-job调度任务，微服务接口请求超时问题

### ISSUE THREAD

**Issue by 1395961821** [jeecgboot/jeecg-boot#5889]
##### 问题描述：
k8s部署的微服务系统，使用xxl-job调用任务成功，但是执行任务失败，微服务之间请求接口超时，执行时间向后推迟半个小时左右，无法正常运行任务，临时token过期时间设置5小时，若设置半个小时则会提示token请求过期。(微服务应用在本地开发环境可以正常使用)

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/31942432/71eedf1d-ff1d-487e-8d91-d1dea07513fb)
![image](https://github.com/jeecgboot/jeecg-boot/assets/31942432/6be1225f-9673-4caf-a748-5f6b0f3162d5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
由于楼主最后补充了说明本地环境运行正常，即可以认为按照官方文档指示来说是正常的，可以初步断定为不是jeecg的问题，而是k8s的部署问题。
不论是K8S还是docker环境，本质上是一样的，本地能访问通，要么是本地配置了jeecg-mis的host，如果没有配置按理来说也是走不通的，其次按照jeecg官方文档的docker部署方案，是所有服务都基于一个docker network下运行，docker network下的所有docker容器发生的docker 容器名称的网络请求会自动转到该docker容器下，导致不会报错，
所以需要排查一个点是k8s的xxl-job和jeecg-mis两个pod之间是否可以用pod名称来访问。
