### ISSUE TITLE
主表+附表代码生成报错

### ISSUE THREAD

**Issue by jujubetree** [jeecgboot/jeecg-boot#5890]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
主表+附表代码生成报错

##### 截图&代码：
   

![微信截图_20240206113947](https://github.com/jeecgboot/jeecg-boot/assets/49394098/24017f3a-5f9e-4aad-8091-f9ed6f9e4fcd)

[错误报文.txt](https://github.com/jeecgboot/jeecg-boot/files/14174395/default.txt)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
应该是你的popup或者那个组件，配置有缺失
