### ISSUE TITLE
多租户中，明明给zhangsan这个用户授予了添加角色的权限，但是在添加租户角色的时候，还是提示没有权限

### ISSUE THREAD

**Issue by onecorner** [jeecgboot/jeecg-boot#5891]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
如题

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/11347680/f72f26ba-9f53-431b-852d-b2eefdfb6f12)
![image](https://github.com/jeecgboot/jeecg-boot/assets/11347680/58054e7d-cce3-4111-945a-24f272f4c049)
![image](https://github.com/jeecgboot/jeecg-boot/assets/11347680/57964ec4-228d-41d4-b7d0-a3183caf66f4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
退出重新登录了吗
