### ISSUE TITLE
最新微服务版本登录报Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

### ISSUE THREAD

**Issue by Mrxuzw** [jeecgboot/jeecg-boot#5892]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
gateway、nacos、demo、system模块启动成功，前端vue3正常启动，获取验证码正常，但是登录报错Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/c22e78bd-0bd6-4225-93a4-efdd1b007044)
未复现该问题，请更新最新版代码后，参考文档运行

**Comment by zhangdaiscott** [comment]
你可以下载 starter最新的，本地下载install
https://github.com/jeecgboot/jeecg-boot-starter/commit/8b161de1836ae8067068802251ef3549049ee2d0

**Comment by zhanghecn** [comment]
我也出现过这个问题，发现是我jdk 版本问题高了, mybatis 那里有点问题。换哥 jdk 17 重新 打包就好了

**Comment by jeonboram0322** [comment]
我使用的jdk21，3.9.0版本，同样遇到了这个问题Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel
使用jdk17以后依旧报错
