### ISSUE TITLE
v3.6.1 升级到 v3.6.2, 找不到 Online图表配置的操作入口

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/jeecg-boot#5893]
##### 版本号：

v3.6.2

##### 前端版本：vue3版？还是 vue2版？

vue3

##### 问题描述：

1. v3.6.1 升级到 v3.6.2, 找不到 Online图表配置的操作入口
2. 仿造 http://boot3.jeecg.com/system/menu 添加菜单访问和权限，访问url （online/graphreport）也无作用（白屏，浏览器看未发起请求）

##### 截图&代码：

![企业微信截图_17079341233403](https://github.com/jeecgboot/jeecg-boot/assets/4926491/caf5f0dd-5e8c-4361-8aaa-43de6b5c6e52)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
图表功能未开源
