### ISSUE TITLE
微服务版本，使用admin成功登录系统，新建模块怎么获取不到系统当前登录用户

### ISSUE THREAD

**Issue by TengflyMa** [jeecgboot/jeecg-boot#5896]
##### 问题描述：
微服务版本，使用admin成功登录系统，新建模块怎么获取不到系统当前登录用户

##### 截图&代码：
`LoginUser loginUser =  (LoginUser) SecurityUtils.getSubject().getPrincipal();`

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
是不是排除了shrio拦截
