### ISSUE TITLE
使用online表单中的“关联记录”之后的授权问题

### ISSUE THREAD

**Issue by haveagooddaytoday** [jeecgboot/jeecg-boot#5897]
##### 版本号：
3.6.2

##### 前端版本：
vue3版

##### 问题描述：
Online在线功能；使用了online表单中的“关联记录”之后，须为对应角色开启“online表单开发”的授权，否则在表单界面将提示“无权限访问（操作）”。但授权“online表单开发”之后意味着该角色用户可以进入online开发界面，显然不安全也不合适，请问是否有解决方案？

##### 截图&代码：

![无权限](https://github.com/jeecgboot/jeecg-boot/assets/108015004/4777b610-2071-4891-8e22-65dc5b5d88e8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
收录 cr

**Comment by hoperunChen** [comment]
@haveagooddaytoday 您可以为被关联的表单新增一个隐藏路由，然后将该隐藏路由分配给需要该权限的用户。
示例：

**Comment by haveagooddaytoday** [comment]
似乎可以解决，感谢！
由于在线表单关联记录较多，目前采用的偷懒的方案是在nginx中屏蔽/online/cgform
