### ISSUE TITLE
boot3_sas 分支微服务模式下认证问题

### ISSUE THREAD

**Issue by cn-core** [jeecgboot/jeecg-boot#5903]
##### 问题描述：
  启动了三个服务（JeecgGatewayApplication、JeecgSystemCloudApplication、JeecgDemoCloudApplication），系统登录成功，使用 Authorization: Bearer xxx、X-Access-Token: xxx 访问 JeecgSystemCloudApplication 服务是没有问题的, 但访问 JeecgDemoCloudApplication 接口时认证错误 401.

  Debug 了下好像问题出在这里 SecurityConfig.jwkSource()，JeecgSystemCloudApplication、JeecgDemoCloudApplication 两服务分别都依赖了 jeecg-boot-base-core（含有认证），启动时又分别生成属于自己的 KeyPair 的公私钥，为 JWT(id_token)提供加密密钥，用于加密/解密或签名/验签。而首次登录时调用的是 JeecgSystemCloudApplication 服务生成的认证 Token，用此 Token 调用 JeecgDemoCloudApplication 时验证 Token 错误导致认证失败。

  该怎么解决？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/30290251/4c59c7a4-28fd-449f-90f6-3ad5adb32cca)
![image](https://github.com/jeecgboot/jeecg-boot/assets/30290251/db4b7a21-5234-4061-82bc-93cd67aa93e0)
![image](https://github.com/jeecgboot/jeecg-boot/assets/30290251/fc414548-b46d-4576-bcd1-3c01d4b5c900)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
已修复，sas分支目前不再更新，最新更新将会同步到boot3分支，等待jeecg社区合并PR

**Comment by cn-core** [comment]
有发布集成 spring-boot-starter-oauth2-authorization-server 后 Releases 版本的大概时间点吗?

**Comment by EightMonth** [comment]
关注这个PR的合并即可
https://github.com/jeecgboot/jeecg-boot/pull/5848

**Comment by cn-core** [comment]
> 关注这个PR的合并即可
> https://github.com/jeecgboot/jeecg-boot/pull/5848

好的, 谢谢...

**Comment by EightMonth** [comment]
sas分支已修复微服务认证问题 @cn-core
