### ISSUE TITLE
【用户管理】编辑对话框保存时，若选择了生日，则后台报错：java.time.format.DateTimeParseException: Text '2024-02-20 17:23' could not be parsed, unparsed text found at index 10

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5904]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在【用户管理】的编辑页面选择生日，保存时报错，后台错误信息为：
java.time.format.DateTimeParseException: Text '2024-02-20 17:23' could not be parsed, unparsed text found at index 10

##### 截图&代码：
![1708421309352](https://github.com/jeecgboot/jeecg-boot/assets/127393297/b8e0055b-b8f4-4672-b5a5-c6c9fd2ad737)
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/d21154b2-f51c-497d-872c-bc6dbe58706b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/3f469168-a5fe-444e-8f64-0eb7fb68a723)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/00529556-1c64-49e2-ace9-58bbedd3240f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/0066af16-bcac-467d-a7b3-0b193e3fc24d)
无法复现描述问题，请更新代码并再次深度
