### ISSUE TITLE
代码生成问题

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecg-boot#5905]
##### 版本号：
v3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
代码生成问题
1.导入数据库时，生成的记录中表注释能否优化下，比如mysql使用 tables.table_comment的；
2.导入数据库时，默认值丢失了、索引也丢失了，而且同步数据库复选框还不能取消，取消了查询表单就不显示对应字段了；
3.生成菜单脚本时默认的菜单模板中 menu_insert.ftl 中 sys_permission.component_name 直接设置与页面的保持一致 ，这样菜单缓存只要编辑时设置下缓存开关就好了，不用再跑页面去看component_name是啥，节约些时间
`  <script lang="ts" name="${componentName}" setup> `
4.数据库tab不允许为空，那检验tab的建议默认相应勾上
5.功能测试与代码生成的不一致，比如下拉联动、自定义按钮JS增强、钮权限控制等。
6.操作栏的移除、删除操作，建议提示清楚一些。比如点击删除，提示“确认删除记录并删除数据库表结构?”
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/ce71ceaa-95c6-4112-b40a-ca8b2db8f2bb)
![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/3cf1c85d-243d-4646-b573-a6b389e24f5b)
![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/31a28dd0-9d2c-4684-a2ed-204ae9fde716)

![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/0c35a7cc-c413-460c-9bc6-2f024d7ac3a3)
![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/7ac93a63-af8f-4f83-bf60-bad1fa211e6e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy 拆分
