### ISSUE TITLE
@Excel 导出excel 如果字典值有下划线会翻译失败

### ISSUE THREAD

**Issue by lpf-lpf** [jeecgboot/jeecg-boot#5906]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
@Excel注解翻译字典的时候，如果字典值有下划线，导出接口翻译会失败

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lpf-lpf** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/42594568/e5ff0ed4-6d89-4f5c-87ed-ac72325ace44)
类似这样，我的字典是：燕房线，值是：AZ_YF_LINE
代码直接lastIndexOf导致翻译的时候分割错误

**Comment by lpf-lpf** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/42594568/4b181961-e1be-4835-83cb-19b13df77874)
这是修改后的代码，自测没问题

**Comment by zhangdaiscott** [comment]
收录 cr

**Comment by lpf-lpf** [comment]
> 收录 cr

什么意思，是会在新版本修复吗？

**Comment by hoperunChen** [comment]
> ![image](https://private-user-images.githubusercontent.com/42594568/306836082-4b181961-e1be-4835-83cb-19b13df77874.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDExMzAsIm5iZiI6MTcwOTY0MDgzMCwicGF0aCI6Ii80MjU5NDU2OC8zMDY4MzYwODItNGIxODE5NjEtZTFiZS00ODM1LTgzY2ItMTliMTNkZjc3ODc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEyMTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NTdlN2EzMTkxOGE3Nzc1ZGYzOWE3MGVmYWZkZGMzMWVmZGU0NTcyZDhlNWFjZTQwZDVhZTBmNDlhY2MxOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T1RNBj-QJ9zBuGxRC5ibzmHKHcAkERl-hH5LHIWga98) 这是修改后的代码，自测没问题

您的这个修改方案在处理字典值有部分重叠的字典组时会出现问题，比如："男_N_A_N", "女_A_N"。
autopoi已经有了对于字典值有`_`的处理方案，您可以将字典注解的replace里的`_`替换成`---`；例如：`@Excel(name = "性别", replace = { "男_N--A---N", "女_A---N" })`。

**Comment by lpf-lpf** [comment]
我是用数据字典遇到的问题，不是用replace遇到的问题，您的意思是改代码吗？ 在text和value拼接的时候用---拼接？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月5日(周二) 晚上8:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] @Excel 导出excel 如果字典值有下划线会翻译失败 (Issue #5906)




  
 这是修改后的代码，自测没问题
  
您的这个修改方案在处理字典值有部分重叠的字典组时会出现问题，比如："男_N_A_N", "女_A_N"。
 ***@***.***(name = "性别", replace = { "男_N--A---N", "女_A---N" })。

**Comment by hoperunChen** [comment]
> 我是用数据字典遇到的问题，不是用replace遇到的问题，您的意思是改代码吗？ 在text和value拼接的时候用---拼接？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月5日(周二) 晚上8:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [jeecgboot/jeecg-boot] @Excel 导出excel 如果字典值有下划线会翻译失败 (Issue #5906) 这是修改后的代码，自测没问题 您的这个修改方案在处理字典值有部分重叠的字典组时会出现问题，比如："男_N_A_N", "女_A_N"。 ***@***.***(name = "性别", replace = { "男_N--A---N", "女_A---N" })。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

`replace`指的是@Excel注解翻译字典的属性值，针对您的情况：「字典是：燕房线，值是：AZ_YF_LINE」；`@Excel`注解可以修改为：`@Excel(name = "XXX", replace = { "燕房线_AZ---YF---LINE", "XX线_AZ---TF---LINE" })`。
