### ISSUE TITLE
【数据字典】回收站查找软删除记录时，没有判断是否启用多租户，造成可以查找并回收其他租户的数据

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#5907]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
【数据字典】回收站查询软删除记录时，没有判断是否启用多租户，造成可以查找并回收其他租户的数据

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/db6c6981-4632-4fce-b5dc-cdb041ec09a7)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
已修复，待新版本发布
