### ISSUE TITLE
springboot3 版本swagger无法使用

### ISSUE THREAD

**Issue by Ez2AcXz** [jeecgboot/jeecg-boot#5908]
##### 版本号：

3.6.2
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
3.6.2的springboot3分支 swagger无法使用

##### 截图&代码：

![微信截图_20240222101903](https://github.com/jeecgboot/jeecg-boot/assets/160806660/3fa04a7b-e912-4368-891e-a06b5c8e021b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Ez2AcXz** [comment]
有人捞一下嘛，对比swagger2的配置明显少了很多内容

**Comment by EightMonth** [comment]
未能复现该问题，请更新代码，并根据文档启动后重新尝试
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/c6a136e2-ab70-40c3-96d8-65feeb8cd485)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/341a61d4-da1e-4c84-9f3a-16f0528bc5d9)

**Comment by Ez2AcXz** [comment]
> 未能复现该问题，请更新代码，并根据文档启动后重新尝试 ![image](https://private-user-images.githubusercontent.com/23272421/307203753-c6a136e2-ab70-40c3-96d8-65feeb8cd485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzMyNjYsIm5iZiI6MTcwODY3Mjk2NiwicGF0aCI6Ii8yMzI3MjQyMS8zMDcyMDM3NTMtYzZhMTM2ZTItYWI3MC00MGMzLTk2ZDgtNjVmZWViOGNkNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA3MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OTcxYmU3NDk5NWU5NmRiZmE0ZWViMDk1YmY1ODk4MTY4YjI1OWIyYTk3MGNhYTc3YmRiYzRmMTA2ZjQ0NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YSeOKwjoTbndTsqJlCP6pMOECEG2najIHaYtJkJ80Ao) ![image](https://private-user-images.githubusercontent.com/23272421/307206261-5878549d-48d3-487d-b85e-d4a7d1d9713c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzMyNjYsIm5iZiI6MTcwODY3Mjk2NiwicGF0aCI6Ii8yMzI3MjQyMS8zMDcyMDYyNjEtNTg3ODU0OWQtNDhkMy00ODdkLWI4NWUtZDRhN2QxZDk3MTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA3MjI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMDYzNTNiNzhmN2MxNWZhZDgwNWI3Nzk2YzU1NjZmM2I4YmU0ZTU5MTQ5ZDU5NTBkMDUzNzg5ZGYwZDE3ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whvy2Re_-GExLkJNIkl_IqGRmRjyBO8VCRf381SLJlY)

代码是直接克隆下来的，发现是在初始请求路径里少了/jeecg-boot 这个路径

**Comment by EightMonth** [comment]
你要不执行一下mvn clean package 试试呢，然后用无痕模式访问该页面，我也是clone的最新的代码，并没有出现这个问题

**Comment by Ez2AcXz** [comment]
我刚才把缓存全都清了一遍好像还是不行，swagger3的basePath就是一个"/"。是springboot3分支哦不是springboot3_sas 用的java17。还有online表单开发的“从数据库导入表单” 查询失败。但是用主分支就是好的
![1](https://github.com/jeecgboot/jeecg-boot/assets/160806660/2227c702-093f-4d89-a9f8-9dc347952633)

**Comment by EightMonth** [comment]
不太清楚你问题的原因，我今天从github clone下来的代码，也并未复现你的这个问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/5c0e7cad-5049-4b00-a21b-b7787744934d)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/dee0c9b9-79f4-40f6-86d7-405406736be0)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/c9a5baea-846b-4d3e-9838-9f7eb4344ea6)
