### ISSUE TITLE
配置了online表单的菜单，tab页切换刷新页面，设置缓存不起作用

### ISSUE THREAD

**Issue by javaAjun** [jeecgboot/jeecg-boot#5910]
##### 版本号：
3.6.2

##### 问题描述：
自己写的vue页面可以使用菜单缓存，但是配了online的菜单，不能用缓存，否则访问不了，最终目的是为了tab页切换不刷新页面

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/38597827/cd449be6-552d-4137-b981-b2273c912324)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
文档链接 zy
