### ISSUE TITLE
 Consider defining a bean of type 'org.jeecg.config.JeecgBaseConfig' in your configuration.

### ISSUE THREAD

**Issue by xiamaocheng** [jeecgboot/jeecg-boot#5913]
##### 版本号：
 v3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3 

##### 问题描述：
demo 工程 升级微服务

##### 截图&代码：

Description:

A component required a bean of type 'org.jeecg.config.JeecgBaseConfig' that could not be found.

Consider defining a bean of type 'org.jeecg.config.JeecgBaseConfig' in your configuration.

Action:
工程clean 不行

**Comment by zhangdaiscott** [comment]
改了什么？默认不应该出这个问题

**Comment by xiamaocheng** [comment]
低版本的jeecg-module-demo 升级为微服务遇到的：
参考文档：https://blog.csdn.net/zhangdaiscott/article/details/108094170，按照这个步骤报上述异常，多谢

**Comment by xiamaocheng** [comment]
已经注释了base-core的依赖， 如下：

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jeecg-boot-parent</artifactId>
        <groupId>org.jeecgframework.boot</groupId>
        <version>3.6.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>jeecg-module-em</artifactId>

    <dependencies>





        <dependency>
            <groupId>net.sf.dozer</groupId>
            <artifactId>dozer</artifactId>
            <version>5.5.1</version>
        </dependency>

        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.55</version> 
        </dependency>




        

        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.5.3.Final</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>
        
        
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>1.5.0.Beta1</version>
        </dependency>
        
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>1.5.0.Beta1</version>
        </dependency>

        
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>1.3.3</version>
        </dependency>

        
        <dependency>
            <groupId>com.github.oshi</groupId>
            <artifactId>oshi-core</artifactId>
            <version>5.8.2</version>
        </dependency>

























    </dependencies>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                    <include>**/*.json</include>
                    <include>**/*.ftl</include>
                    <include>template/**</include>
                </includes>
            </resource>
        </resources>
    </build>

</project>



但是依然报错：

Description:

A component required a bean of type 'org.jeecg.config.JeecgBaseConfig' that could not be found.


Action:

Consider defining a bean of type 'org.jeecg.config.JeecgBaseConfig' in your configuration.

**Comment by zhangdaiscott** [comment]
jeecgboot默认支持单体和微服务自有切换，具体参考文档
https://help.jeecg.com/java/springcloud/switchcloud/monomer.html
