### ISSUE TITLE
单体转微服务

### ISSUE THREAD

**Issue by xiamaocheng** [jeecgboot/jeecg-boot#5920]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue 3

##### 问题描述：
单体构微服务，log 如下：

访问对应的url 地址：
http://192.168.3.106:8081/jeecg-boot/XXXXX/XXXXX
重定向到http://192.168.3.106:8081/jeecg-boot/login.jsp
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/8685152/6ee36744-2e60-4138-be35-db881576ca1b)

**Comment by zhangdaiscott** [comment]
jeecgboot默认支持单体和微服务自有切换，具体参考文档
https://help.jeecg.com/java/springcloud/switchcloud/monomer.html
