### ISSUE TITLE
online在线功能ERP导致的页大小问题

### ISSUE THREAD

**Issue by xiaohzang** [jeecgboot/jeecg-boot#5922]
##### 截图&代码：
![a36a53c59b17bedc902647053a3d8d3](https://github.com/jeecgboot/jeecg-boot/assets/41184811/b00d1fbb-362e-40a5-ba1e-eae17da48426)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
