### ISSUE TITLE
仪表盘页面 /drag/page进入后无显示 

### ISSUE THREAD

**Issue by daymax-byte** [jeecgboot/jeecg-boot#5923]
##### 问题描述：
目前仪表盘页面通过docker部署后，进入显示空白页面。是否是因为内网部署无法通过请求获取外网资源的问题。

##### 截图&代码：

![WechatIMG257](https://github.com/jeecgboot/jeecg-boot/assets/67035780/bc59365f-5589-45d8-8c1e-05ac0c637cc9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看看什么错
