### ISSUE TITLE
Mac代码生成无效

### ISSUE THREAD

**Issue by zhangqw2** [jeecgboot/jeecg-boot#5927]
##### 版本号：
3.4

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
mac系统代码生成失效并且无法下载到本地

##### 截图&代码：

:::::: 生成失败ERROR提示 ::::::

1.JeecgBoot项目所在路径是否含有中文或空格，去掉就好了！参考 http://doc.jeecg.com/2088984

2.采用JAR包上线发布，需要做额外配置！参考 http://doc.jeecg.com/2043922

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
按照提示文件做配置
或者升级代码到最新版
