### ISSUE TITLE
{"success":false,"message":"Token失效，请重新登录!","code":401,"result":null,"timestamp":1709184890314}

### ISSUE THREAD

**Issue by xiamaocheng** [jeecgboot/jeecg-boot#5928]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？

vue 3 

##### 问题描述：
试图访问后台控制器，但是后台返回如下；
但是我已经更改了对应的CommonConstant （TOKEN_IS_INVALID_MSG）引用的类
和对应的ShiroConfig 的配置文件，
但是还是会报如下异常

{"success":false,"message":"Token失效，请重新登录!","code":401,"result":null,"timestamp":1709184890314}

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8685152/4e1b3b28-9f83-48b3-8190-272bccdbb7af)

**Comment by zhangdaiscott** [comment]
怎么改的截图说明

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/qa
7.1
