### ISSUE TITLE
springboot3-sas分支启动问题

### ISSUE THREAD

**Issue by Chenzhexian** [jeecgboot/jeecg-boot#5932]
##### 版本号：
3.6.1
##### 问题描述：
springboot3-sas分支启动时，连接redis一直连接本地的，我naocs配置了ip也不生效
jdk版本21

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/92191856/57b315bd-2ba9-4bfe-ab2e-10a17f4b66a9)

![image](https://github.com/jeecgboot/jeecg-boot/assets/92191856/874bf931-035d-4198-9508-c4e1f1405d95)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/5902
