### ISSUE TITLE
我把jeecgboot的包名，改为自己的，然后一直报找不到这个类：org.jeecg.common.util.security.AbstractQueryBlackListHandler

### ISSUE THREAD

**Issue by kuai0901** [jeecgboot/jeecg-boot#5939]
##### 版本号：
3.6.2
##### 前端版本：vue3版？还是 vue2版？
vue2
##### 问题描述：
我把jeecgboot的包名，改为自己的，然后一直报找不到这个类：org.jeecg.common.util.security.AbstractQueryBlackListHandler

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/41226612/7581485e-e1d0-4439-94e5-f37572a2b77a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/qa
20
