### ISSUE TITLE
v3.6.2本地后台微服务启动后swagger接口登录报错，操作失败，Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

### ISSUE THREAD

**Issue by Lctiv** [jeecgboot/jeecg-boot#5945]
##### 版本号：
v3.6.2

##### 前端版本：vue3版？还是 vue2版？
Vue3

##### 问题描述：

1、既然是登录接口为什么默认还要开启token验证，这很不科学
2、登录接口按照说明文档 https://help.jeecg.com/java/publish/swagger.html 
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/88873311/8b3529d1-939b-4166-8ec9-4eb06b5da1bc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Lctiv** [comment]
操作失败，Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

**Comment by zhangdaiscott** [comment]
你代码更新到最新，好像修复过了

**Comment by Lctiv** [comment]
> 你代码更新到最新，好像修复过了

3.4号16点多gitee上下载的，这俩天更新修复了？

**Comment by zhangdaiscott** [comment]
那写下重现步骤，我们重新看下

**Comment by Lctiv** [comment]
> 那写下重现步骤，我们重新看下
说明:参考官方文档验证 https://help.jeecg.com/java/publish/swagger.html
step1：Get  获取验证码 /sys/randomImage/{key}  对应输入key:123 ;请求头：X-Access-Token：ww ->获得验证码
![image](https://github.com/jeecgboot/jeecg-boot/assets/88873311/33be910b-9b45-4fe4-851b-b45b05d15abb)

step2:  post 登录接口 /sys/login  请求头：X-Access-Token ：ww ， 请求参数：
{
  "captcha": "kxu7",
  "checkKey": "123",
  "password": "123456",
  "username": "admin"
}
返回：
{
  "success": false,
  "message": "操作失败，Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel",
  "code": 500,
  "result": null,
  "timestamp": 1709691628029
}
![image](https://github.com/jeecgboot/jeecg-boot/assets/88873311/7183c3ed-d8e9-4d7a-aee8-32ec4ca59dd2)

**Comment by Lctiv** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/88873311/01aaa752-e3f5-4a82-8af3-f42a2dbcc69e)

**Comment by Lctiv** [comment]
> 你代码更新到最新，好像修复过了

你好，我刚又试了单体应用是接口是可以正常返回的，切换为微服务的报错

**Comment by EightMonth** [comment]
直接把access_token的勾去掉即可
