### ISSUE TITLE
springboot3_sas vue3 启动 报错

### ISSUE THREAD

**Issue by weir2010** [jeecgboot/jeecg-boot#5946]
##### 版本号：
springboot3_sas

##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
本地启动：http://localhost:3100/jeecgboot/sys/randomImage/1629428467008?_t=1709697218150
报404
##### 截图&代码：

![C4433A0936C68641BE41C4B03384DA51](https://github.com/jeecgboot/jeecg-boot/assets/404015/85803690-6990-43b1-bd12-54866ab516a4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
后台启动了吗

**Comment by weir2010** [comment]
<img width="1172" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/404015/d2756702-272f-4c9e-8c2a-2df4bd58a3ac">
这个是后端没启动报的错   一个是500  一个是404

**Comment by weir2010** [comment]
该问题已解决
