### ISSUE TITLE
企业微信自动登录https下报错

### ISSUE THREAD

**Issue by zing-yang** [jeecgboot/jeecg-boot#5947]
##### 问题描述：企业微信配置登录情况下自动登录报错：redirect_uri需使用应用可信域名
![image](https://github.com/jeecgboot/jeecg-boot/assets/89351375/80739c82-7bef-4815-b93c-3401f7909439)

##### 截图&代码：后来打印相关日志，检查发现在https的环境下自动拼接443端口
类路径：org.jeecg.common.util.CommonUtils 下getBaseUrl(HttpServletRequest request)方法

修改后代码：
```
public static String getBaseUrl(HttpServletRequest request) {
        //1.【兼容】兼容微服务下的 base path-------
        String xGatewayBasePath = request.getHeader(ServiceNameConstants.X_GATEWAY_BASE_PATH);
        if(oConvertUtils.isNotEmpty(xGatewayBasePath)){
            log.info("x_gateway_base_path = "+ xGatewayBasePath);
            return  xGatewayBasePath;
        }
        //2.【兼容】SSL认证之后，request.getScheme()获取不到https的问题
        // https://blog.csdn.net/weixin_34376986/article/details/89767950
        String scheme = request.getHeader(CommonConstant.X_FORWARDED_SCHEME);
        if(oConvertUtils.isEmpty(scheme)){
            scheme = request.getScheme();
        }

        //3.常规操作
        String serverName = request.getServerName();
        int serverPort = request.getServerPort();
        String contextPath = request.getContextPath();

        //返回 host domain
        String baseDomainPath = null;
        int httpPort =  80;
        int httpsPort =  443;
        if(httpPort == serverPort||httpsPort == serverPort){
            baseDomainPath = scheme + "://" + serverName  + contextPath ;
        }else{
            baseDomainPath = scheme + "://" + serverName + ":" + serverPort + contextPath ;
        }
        log.debug("-----Common getBaseUrl----- : " + baseDomainPath);
        return baseDomainPath;
}
```
其中变量名int httpPort =  80;之前int length = 80;命名并不规范。考虑到部分用户可能会显示端口，故增加变量端口为可选项
```
public static String getBaseUrl(HttpServletRequest request,boolean showPort) {
        //1.【兼容】兼容微服务下的 base path-------
        String xGatewayBasePath = request.getHeader(ServiceNameConstants.X_GATEWAY_BASE_PATH);
        if(oConvertUtils.isNotEmpty(xGatewayBasePath)){
            log.info("x_gateway_base_path = "+ xGatewayBasePath);
            return  xGatewayBasePath;
        }
        //2.【兼容】SSL认证之后，request.getScheme()获取不到https的问题
        // https://blog.csdn.net/weixin_34376986/article/details/89767950
        String scheme = request.getHeader(CommonConstant.X_FORWARDED_SCHEME);
        if(oConvertUtils.isEmpty(scheme)){
            scheme = request.getScheme();
        }

        //3.常规操作
        String serverName = request.getServerName();
        int serverPort = request.getServerPort();
        String contextPath = request.getContextPath();

        //返回 host domain
        String baseDomainPath = null;
        int httpPort =  80;
        int httpsPort =  443;
        if((httpPort == serverPort||(httpsPort == serverPort&&showPort))){
            baseDomainPath = scheme + "://" + serverName  + contextPath ;
        }else{
            baseDomainPath = scheme + "://" + serverName + ":" + serverPort + contextPath ;
        }
        log.debug("-----Common getBaseUrl----- : " + baseDomainPath);
        return baseDomainPath;
}
```
望采纳，如果能添加我的名字zingyang 那更加不甚感激

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws

**Comment by zing-yang** [comment]
好的，没事，只要有这个Issue，可以让人知道有这个问题怎么处理就可以了

**Comment by 1298191366** [comment]
httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性

**Comment by zing-yang** [comment]
请求的地址变成加上了443端口。发自我的 iPhone在 2024年3月11日，11:27，1298191366 ***@***.***> 写道：﻿
httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性

**Comment by zing-yang** [comment]
> httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性 ![图像](https://private-user-images.githubusercontent.com/30997828/311577968-645fe54a-fc4c-4925-817f-a7670d234c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzU1MDYsIm5iZiI6MTcxMDEzNTIwNiwicGF0aCI6Ii8zMDk5NzgyOC8zMTE1Nzc5NjgtNjQ1ZmU1NGEtZmM0Yy00OTI1LTgxN2YtYTc2NzBkMjM0YzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA1MzMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwM2Y2ZjQ1OTA2OWFhMzNlNjZhZjc0NDkwNDViNjM0YzY0ZWY4MGU3MjI3Zjg0OWNiYzQ0ZWIwMDJhYTM4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D2ak_aN47eqVxPSTuTZ8t0ftjoeWqb707WxsGChbaqs)

可能我没描述清楚，上面的是原来的代码，下面的是我贴出来的自己修复后的代码。
复线路径：在https环境下在企业微信管理后台配置可信域名：如https://www.bug.com
企业微信内应用自动登陆报错：redirect_uri需使用应用可信域名
打印log，org.jeecg.common.util.CommonUtils 下getBaseUrl（HttpServletRequest request）方法变成了https://www.bug.com:443
导致回调redirect_uri错误。
可以尝试复现

**Comment by zing-yang** [comment]
> httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性 ![图像](https://private-user-images.githubusercontent.com/30997828/311577968-645fe54a-fc4c-4925-817f-a7670d234c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzU1MDYsIm5iZiI6MTcxMDEzNTIwNiwicGF0aCI6Ii8zMDk5NzgyOC8zMTE1Nzc5NjgtNjQ1ZmU1NGEtZmM0Yy00OTI1LTgxN2YtYTc2NzBkMjM0YzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA1MzMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwM2Y2ZjQ1OTA2OWFhMzNlNjZhZjc0NDkwNDViNjM0YzY0ZWY4MGU3MjI3Zjg0OWNiYzQ0ZWIwMDJhYTM4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D2ak_aN47eqVxPSTuTZ8t0ftjoeWqb707WxsGChbaqs)

请不要额外添加端口，谢谢
