### ISSUE TITLE
Online在线功能，关联记录卡片模式最多只能显示6个其他字段

### ISSUE THREAD

**Issue by haveagooddaytoday** [jeecgboot/jeecg-boot#5954]
##### 版本号：
3.6.2

##### 前端版本：
vue3

##### 问题描述：
Online在线功能，关联记录卡片模式最多只能显示6个其他字段（单选状态下。若是多选，最多只显示3个其他字段），是设计上如此考虑么？能否显示更多的其他字段，方便展示更多信息。感谢！

##### 截图&代码：

![Snipaste_2024-03-07_03-01-39](https://github.com/jeecgboot/jeecg-boot/assets/108015004/cef9dc06-59a1-4604-ad60-635324ed0428)

**Comment by zhangdaiscott** [comment]
zy  限制用户最多选6个

**Comment by haveagooddaytoday** [comment]
zy是什么？
