### ISSUE TITLE
online在线表单生成的页面，在开始多租户后无操作权限

### ISSUE THREAD

**Issue by chenjiayang2008** [jeecgboot/jeecg-boot#5957]
##### 截图&代码：
//3.online租户隔离测试
TENANT_TABLE.add("test_order");
TENANT_TABLE.add("test_order_detail");
TENANT_TABLE.add("test_file");
TENANT_TABLE.add("test_container_instance");
TENANT_TABLE.add("test_image");

![image](https://github.com/jeecgboot/jeecg-boot/assets/29227054/b6ed0213-19a2-433a-9703-781d54a495c8)

![MD3S5Y@019O48M)1I98YOYI](https://github.com/jeecgboot/jeecg-boot/assets/29227054/1e2a6482-5110-43f4-91a4-f2e132ee8be8)

![BFBYH Y9_YB@{V} 5MTA83M](https://github.com/jeecgboot/jeecg-boot/assets/29227054/51e06c37-65a1-447e-8e54-7f2454924d6e)

**Comment by chenjiayang2008** [comment]
//3.online租户隔离测试
TENANT_TABLE.add("test_order");
TENANT_TABLE.add("test_order_detail");
TENANT_TABLE.add("test_file");
TENANT_TABLE.add("test_container_instance");
TENANT_TABLE.add("test_image");

**Comment by zhangdaiscott** [comment]
后台日志打印一下

**Comment by chenjiayang2008** [comment]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5dd4e5de] was not registered for synchronization because synchronization is not active
Creating a new SqlSession
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@676b19b0] was not registered for synchronization because synchronization is not active
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4eff86eb] was not registered for synchronization because synchronization is not active
original SQL: SELECT id,table_name,table_type,table_version,table_txt,is_checkbox,is_db_synch,is_page,is_tree,id_sequence,id_type,query_mode,relation_type,sub_table_str,tab_order_num,tree_parent_id_field,tree_id_field,tree_fieldname,form_category,form_template,theme_template,form_template_mobile,ext_config_json,update_by,update_time,create_by,create_time,copy_type,copy_version,physic_id,scroll,is_des_form,des_form_code,low_app_id FROM onl_cgform_head WHERE id=? 
original SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
original SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
SQL to parse, SQL: SELECT id,table_name,table_type,table_version,table_txt,is_checkbox,is_db_synch,is_page,is_tree,id_sequence,id_type,query_mode,relation_type,sub_table_str,tab_order_num,tree_parent_id_field,tree_id_field,tree_fieldname,form_category,form_template,theme_template,form_template_mobile,ext_config_json,update_by,update_time,create_by,create_time,copy_type,copy_version,physic_id,scroll,is_des_form,des_form_code,low_app_id FROM onl_cgform_head WHERE id=? 
parse the finished SQL: SELECT id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, theme_template, form_template_mobile, ext_config_json, update_by, update_time, create_by, create_time, copy_type, copy_version, physic_id, scroll, is_des_form, des_form_code, low_app_id FROM onl_cgform_head WHERE id = ?
SQL to parse, SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
SQL to parse, SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
parse the finished SQL: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
parse the finished SQL: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.372, closeCount=0, lastValidateTimeMillis=2024-03-07 13:49:49.179}] will not be managed by Spring
==>  Preparing: SELECT id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, theme_template, form_template_mobile, ext_config_json, update_by, update_time, create_by, create_time, copy_type, copy_version, physic_id, scroll, is_des_form, des_form_code, low_app_id FROM onl_cgform_head WHERE id = ?
==> Parameters: ff8080818e176328018e1763287f0000(String)
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.375, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.369, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
<==    Columns: id, table_name, table_type, table_version, table_txt, is_checkbox, is_db_synch, is_page, is_tree, id_sequence, id_type, query_mode, relation_type, sub_table_str, tab_order_num, tree_parent_id_field, tree_id_field, tree_fieldname, form_category, form_template, theme_template, form_template_mobile, ext_config_json, update_by, update_time, create_by, create_time, copy_type, copy_version, physic_id, scroll, is_des_form, des_form_code, low_app_id
<==        Row: ff8080818e176328018e1763287f0000, test_image$1, 1, 1, 镜像, Y, N, Y, N, null, UUID, single, null, null, null, null, null, null, temp, 1, normal, null, {"reportPrintShow":0,"reportPrintUrl":"","joinQuery":0,"modelFullscreen":0,"modalMinWidth":"","commentStatus":0,"tableFixedAction":1,"tableFixedActionType":"right"}, null, null, admin, 2024-03-07 13:29:18, 1, 5, 97cf0a7d0f59452bb5d425a2a7fca729, 1, N, , null
==>  Preparing: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
==> Parameters: 0(Integer), /online/cgformInnerTableList/ff8080818e176328018e1763287f0000(String), /online/cgformErpList/ff8080818e176328018e1763287f0000(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), /online/cgformTreeList/ff8080818e176328018e1763287f0000(String), /online/cgformTabList/ff8080818e176328018e1763287f0000(String)
==>  Preparing: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
==> Parameters: 0(Integer), /online/cgformInnerTableList/ff8080818e176328018e1763287f0000(String), /online/cgformErpList/ff8080818e176328018e1763287f0000(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), /online/cgformTreeList/ff8080818e176328018e1763287f0000(String), /online/cgformTabList/ff8080818e176328018e1763287f0000(String)
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@4eff86eb]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5da4c546] was not registered for synchronization because synchronization is not active
original SQL: SELECT  id,cgform_head_id,db_field_name,db_field_txt,db_field_name_old,db_is_key,db_is_null,db_is_persist,db_type,db_length,db_point_length,db_default_val,dict_field,dict_table,dict_text,field_show_type,field_href,field_length,field_valid_type,field_must_input,field_extend_json,field_default_value,is_query,is_show_form,is_show_list,is_read_only,query_mode,main_table,main_field,order_num,update_by,update_time,create_time,create_by,converter,query_config_flag,query_def_val,query_dict_text,query_dict_field,query_dict_table,query_show_type,query_valid_type,query_must_input,sort_flag  FROM onl_cgform_field 
 
 WHERE (cgform_head_id = ? AND (is_show_list = ? OR is_query = ?) AND db_is_persist = ?) ORDER BY order_num ASC
<==    Columns: id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, leaf, route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external
<==    Columns: id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, leaf, route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external
<==        Row: 1762345696624713729, , 镜像, null, 0, ant-design:video-camera-twotone, layouts/default/index, , /online/cgformList/ff8080818e176328018e1763287f0000, null, 1.07, 0, 1, 0, 0, null, admin, 0, 0, 0, 0, 2024-02-27 13:15:32, admin, 2024-03-07 13:30:08, null, 0, 0
<==        Row: 1762345696624713729, , 镜像, null, 0, ant-design:video-camera-twotone, layouts/default/index, , /online/cgformList/ff8080818e176328018e1763287f0000, null, 1.07, 0, 1, 0, 0, null, admin, 0, 0, 0, 0, 2024-02-27 13:15:32, admin, 2024-03-07 13:30:08, null, 0, 0
<==      Total: 1
<==      Total: 1
SQL to parse, SQL: SELECT  id,cgform_head_id,db_field_name,db_field_txt,db_field_name_old,db_is_key,db_is_null,db_is_persist,db_type,db_length,db_point_length,db_default_val,dict_field,dict_table,dict_text,field_show_type,field_href,field_length,field_valid_type,field_must_input,field_extend_json,field_default_value,is_query,is_show_form,is_show_list,is_read_only,query_mode,main_table,main_field,order_num,update_by,update_time,create_time,create_by,converter,query_config_flag,query_def_val,query_dict_text,query_dict_field,query_dict_table,query_show_type,query_valid_type,query_must_input,sort_flag  FROM onl_cgform_field 
 
 WHERE (cgform_head_id = ? AND (is_show_list = ? OR is_query = ?) AND db_is_persist = ?) ORDER BY order_num ASC
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@676b19b0]
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5dd4e5de]
parse the finished SQL: SELECT id, cgform_head_id, db_field_name, db_field_txt, db_field_name_old, db_is_key, db_is_null, db_is_persist, db_type, db_length, db_point_length, db_default_val, dict_field, dict_table, dict_text, field_show_type, field_href, field_length, field_valid_type, field_must_input, field_extend_json, field_default_value, is_query, is_show_form, is_show_list, is_read_only, query_mode, main_table, main_field, order_num, update_by, update_time, create_time, create_by, converter, query_config_flag, query_def_val, query_dict_text, query_dict_field, query_dict_table, query_show_type, query_valid_type, query_must_input, sort_flag FROM onl_cgform_field WHERE (cgform_head_id = ? AND (is_show_list = ? OR is_query = ?) AND db_is_persist = ?) ORDER BY order_num ASC
Creating a new SqlSession
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1ac6ef18] was not registered for synchronization because synchronization is not active
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@11c83785] was not registered for synchronization because synchronization is not active
original SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
original SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.369, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
==>  Preparing: SELECT id, cgform_head_id, db_field_name, db_field_txt, db_field_name_old, db_is_key, db_is_null, db_is_persist, db_type, db_length, db_point_length, db_default_val, dict_field, dict_table, dict_text, field_show_type, field_href, field_length, field_valid_type, field_must_input, field_extend_json, field_default_value, is_query, is_show_form, is_show_list, is_read_only, query_mode, main_table, main_field, order_num, update_by, update_time, create_time, create_by, converter, query_config_flag, query_def_val, query_dict_text, query_dict_field, query_dict_table, query_show_type, query_valid_type, query_must_input, sort_flag FROM onl_cgform_field WHERE (cgform_head_id = ? AND (is_show_list = ? OR is_query = ?) AND db_is_persist = ?) ORDER BY order_num ASC
==> Parameters: ff8080818e176328018e1763287f0000(String), 1(Integer), 1(Integer), 1(Integer)
SQL to parse, SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
SQL to parse, SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
parse the finished SQL: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
parse the finished SQL: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.375, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.372, closeCount=0, lastValidateTimeMillis=2024-03-07 13:49:49.179}] will not be managed by Spring
==>  Preparing: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
==>  Preparing: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
==> Parameters: ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String)
==> Parameters: ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String)
<==    Columns: id, cgform_head_id, db_field_name, db_field_txt, db_field_name_old, db_is_key, db_is_null, db_is_persist, db_type, db_length, db_point_length, db_default_val, dict_field, dict_table, dict_text, field_show_type, field_href, field_length, field_valid_type, field_must_input, field_extend_json, field_default_value, is_query, is_show_form, is_show_list, is_read_only, query_mode, main_table, main_field, order_num, update_by, update_time, create_time, create_by, converter, query_config_flag, query_def_val, query_dict_text, query_dict_field, query_dict_table, query_show_type, query_valid_type, query_must_input, sort_flag
<==        Row: 39ff2cf7fc317641645a21c41ee66640, ff8080818e176328018e1763287f0000, uuid, 镜像UUID, null, 0, 1, 1, string, 255, 0, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 1, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==        Row: 1fba1ed32383748d92d2ad6b98a39712, ff8080818e176328018e1763287f0000, image_name, 镜像名称, null, 0, 1, 1, string, 255, 0, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 2, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==        Row: ffde0d59da70d62cf0516dbe385a3060, ff8080818e176328018e1763287f0000, image_length, 大小（GB）, null, 0, 1, 1, double, 20, 2, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 3, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==        Row: 7f406fb1b8a2f1f2e77e29d0334cac76, ff8080818e176328018e1763287f0000, image_status, 状态, null, 0, 1, 1, int, 1, 0, , image_status, , , list, , 200, , 0, , , 0, 1, 1, 0, single, , , 4, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
Creating a new SqlSession
<==        Row: 87915c29e22056ef3f0cfec6fc8f38ae, ff8080818e176328018e1763287f0000, share_info, 共享信息, null, 0, 1, 1, Text, 0, 0, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 5, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@465a5d70] was not registered for synchronization because synchronization is not active
<==        Row: 740af5d67bf0f4a82da8d2f7aad4f309, ff8080818e176328018e1763287f0000, cache_area, 缓存地区, null, 0, 1, 1, string, 255, 0, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 6, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==        Row: 1fc0c6f29ec72f72efff271b85f4968d, ff8080818e176328018e1763287f0000, image_time, 创建时间, null, 0, 1, 1, Datetime, 32, 0, , , , , datetime, , 200, , 0, , , 0, 1, 1, 0, single, , , 7, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==        Row: accc108d60adf233b627c813b1fa92b2, ff8080818e176328018e1763287f0000, tenant_id, 租户id, null, 0, 1, 1, int, 10, 0, , , , , text, , 200, , 0, , , 0, 1, 1, 0, single, , , 13, null, null, 2024-03-07 13:29:18, admin, , 0, , , , , text, null, null, 0
<==      Total: 8
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5da4c546]
<==    Columns: sum(cnt)
<==        Row: 0
<==    Columns: sum(cnt)
<==        Row: 0
<==      Total: 1
<==      Total: 1
original SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@11c83785]
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1ac6ef18]
SQL to parse, SQL: SELECT  id,parent_id,name,perms,perms_type,icon,component,component_name,url,redirect,sort_no,menu_type,is_leaf AS leaf,is_route AS route,keep_alive,description,create_by,del_flag,rule_flag,hidden,hide_tab,create_time,update_by,update_time,status,always_show,internal_or_external  FROM sys_permission 
 
 WHERE (del_flag = ? AND url IN (?,?,?,?,?))
parse the finished SQL: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.375, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
==>  Preparing: SELECT id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, is_leaf AS leaf, is_route AS route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external FROM sys_permission WHERE (del_flag = ? AND url IN (?, ?, ?, ?, ?))
==> Parameters: 0(Integer), /online/cgformInnerTableList/ff8080818e176328018e1763287f0000(String), /online/cgformErpList/ff8080818e176328018e1763287f0000(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), /online/cgformTreeList/ff8080818e176328018e1763287f0000(String), /online/cgformTabList/ff8080818e176328018e1763287f0000(String)
<==    Columns: id, parent_id, name, perms, perms_type, icon, component, component_name, url, redirect, sort_no, menu_type, leaf, route, keep_alive, description, create_by, del_flag, rule_flag, hidden, hide_tab, create_time, update_by, update_time, status, always_show, internal_or_external
<==        Row: 1762345696624713729, , 镜像, null, 0, ant-design:video-camera-twotone, layouts/default/index, , /online/cgformList/ff8080818e176328018e1763287f0000, null, 1.07, 0, 1, 0, 0, null, admin, 0, 0, 0, 0, 2024-02-27 13:15:32, admin, 2024-03-07 13:30:08, null, 0, 0
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@465a5d70]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5647a31f] was not registered for synchronization because synchronization is not active
original SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
SQL to parse, SQL: select sum(cnt) from (
		  select count(*) as cnt
			from sys_role_permission a
			join sys_permission b on a.permission_id = b.id
			join sys_role c on a.role_id = c.id
			join sys_user_role d on d.role_id = c.id
			join sys_user e on d.user_id = e.id
			where e.username = ?
			 
				and b.id =  ?
			 
			 
				and b.url =  ?
			 
		union all
		  select count(*) as cnt
			from sys_permission z
		    join sys_depart_role_permission y on z.id = y.permission_id
			join sys_depart_role x on y.role_id = x.id
			join sys_depart_role_user w on w.drole_id = x.id
			join sys_user v on w.user_id = v.id
			where v.username = ?
			 
				and z.id =  ?
			 
			 
				and z.url =  ?
			 
		) temp
parse the finished SQL: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
JDBC Connection [ConnectionProxyImpl{connectedTime=2024-03-07 11:47:39.375, closeCount=0, lastValidateTimeMillis=2024-03-07 13:57:39.137}] will not be managed by Spring
==>  Preparing: SELECT sum(cnt) FROM (SELECT count(*) AS cnt FROM sys_role_permission a JOIN sys_permission b ON a.permission_id = b.id JOIN sys_role c ON a.role_id = c.id AND c.tenant_id = 1000 JOIN sys_user_role d ON d.role_id = c.id AND d.tenant_id = 1000 JOIN sys_user e ON d.user_id = e.id WHERE e.username = ? AND b.id = ? AND b.url = ? UNION ALL SELECT count(*) AS cnt FROM sys_permission z JOIN sys_depart_role_permission y ON z.id = y.permission_id JOIN sys_depart_role x ON y.role_id = x.id JOIN sys_depart_role_user w ON w.drole_id = x.id JOIN sys_user v ON w.user_id = v.id WHERE v.username = ? AND z.id = ? AND z.url = ?) temp
==> Parameters: ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String), ceshi(String), 1762345696624713729(String), /online/cgformList/ff8080818e176328018e1763287f0000(String)
<==    Columns: sum(cnt)
<==        Row: 0
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@5647a31f]

**Comment by chenjiayang2008** [comment]
没有代码，使用的是在线生成的url

**Comment by chenjiayang2008** [comment]
> 后台日志打印一下
没有代码，使用的是online在线表单生成的url

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/8f311807-a14f-46bc-8531-8baa827e94fc)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/caddadb1-f003-49cb-a385-d47d95ed337a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/195f697a-9b4c-4ef9-8df6-5c9a747b2e72)
未复现，请先确认下您的测试账号的部门、租户、菜单权限配置无误；如果还存在问题烦请在官网提供复现案例。
