### ISSUE TITLE
springboot3分支下的jeecg-cloud-sentinel模块的pom文件parent标签错误

### ISSUE THREAD

**Issue by Iceberry-qdd** [jeecgboot/jeecg-boot#5959]
##### 版本号：
v3.6.2

##### 前端版本：vue3版？还是 vue2版？
不涉及

##### 问题描述：
springboot3分支的`jeecg-cloud-sentinel`模块的pom文件中的`parent`代码块，是否应与master分支中的`parent`代码块一致？该模块的Dockerfile文件要求添加`./target/jeecg-cloud-sentinel-3.6.2.jar`，而打出的jar包是`jeecg-cloud-sentinel-2.7.1.jar`，导致无法打包此镜像。

##### 截图&代码：
springboot3分支的`jeecg-cloud-sentinel`模块的Dockerfile文件，此处代码如下所示：
https://github.com/jeecgboot/jeecg-boot/blob/4caff75cce452bc26caba5f622c795186962d4bb/jeecg-server-cloud/jeecg-visual/jeecg-cloud-sentinel/Dockerfile#L13

springboot3分支的`jeecg-cloud-sentinel`模块的pom文件，此处代码所示的父工程如下：
https://github.com/jeecgboot/jeecg-boot/blob/4caff75cce452bc26caba5f622c795186962d4bb/jeecg-server-cloud/jeecg-visual/jeecg-cloud-sentinel/pom.xml#L5-L10

master分支的`jeecg-cloud-sentinel`模块的pom文件，此处代码所示的父工程如下：
https://github.com/jeecgboot/jeecg-boot/blob/2af165b201a64c05ca881a699614b18a1dfccbbd/jeecg-server-cloud/jeecg-visual/jeecg-cloud-sentinel/pom.xml#L5-L9

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
分支还没合并呢，还是3,6,2
