### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.jeecg.modules.system.mapper.SysUserTenantMapper.getTenantNoCancel

### ISSUE THREAD

**Issue by zqf-git** [jeecgboot/jeecg-boot#5966]
##### 截图&代码：
![微信截图_20240309151836](https://github.com/jeecgboot/jeecg-boot/assets/80464907/8ba5a131-0d1d-4e6a-8b1f-143bfcca8395)
![微信截图_20240309151907](https://github.com/jeecgboot/jeecg-boot/assets/80464907/81de195a-e43e-49b0-92cc-fa22184a0f2f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你数据库更新了吗 nacos gateway 等配置

**Comment by zqf-git** [comment]
更新了

> 你数据库更新了吗 nacos gateway 等配置

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/commit/734068c685c031bd1cb5037aa389efb44dacb798

更新这个看看

**Comment by zqf-git** [comment]
> [jeecgboot/jeecgboot-vue3@734068c](https://github.com/jeecgboot/jeecgboot-vue3/commit/734068c685c031bd1cb5037aa389efb44dacb798)
> 
> 更新这个看看

哥 这不是前端代码吗

**Comment by zhangdaiscott** [comment]
你更新试试，印象中是这个导致的

**Comment by zqf-git** [comment]
> 你更新试试，印象中是这个导致的

我没下前端代码，不会前端的东西呢

**Comment by zhangdaiscott** [comment]
最新版无问题
