### ISSUE TITLE
httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性

### ISSUE THREAD

**Issue by zing-yang** [jeecgboot/jeecg-boot#5968]
httpsPort 是你自己加的吧，我排查了一下，3.6.0版本没有新增httpsPort属性
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/645fe54a-fc4c-4925-817f-a7670d234c2b)

_Originally posted by @1298191366 in https://github.com/jeecgboot/jeecg-boot/issues/5947#issuecomment-1987571162_
            可能我没描述清楚，上面的是原来的代码，下面的是我贴出来的自己修复后的代码。
复线路径：在https环境下在企业微信管理后台配置可信域名：如 https://www.bug.com/
企业微信内应用自动登陆报错：redirect_uri需使用应用可信域名
打印log，org.jeecg.common.util.CommonUtils 下getBaseUrl（HttpServletRequest request）方法变成了 [https://www.bug.com:443](https://www.bug.com/)
导致回调redirect_uri错误。
可以尝试复现
请不要额外添加端口，谢谢

**Comment by 1298191366** [comment]
收到，我在测试一下

**Comment by zing-yang** [comment]
￼


￼
这是当时打印的log

**Comment by 1298191366** [comment]
已修改，待新版本发布

**Comment by zing-yang** [comment]
为你们的效率点赞👍发自我的 iPhone在 2024年3月15日，19:08，1298191366 ***@***.***> 写道：﻿
已修改，待新版本发布
