### ISSUE TITLE
自定义sql分页查询

### ISSUE THREAD

**Issue by LilyEvans123** [jeecgboot/jeecg-boot#5969]
##### 问题描述：后端写好相应的sql分页查询以后，返回给前端的信息正常，但是数据列表不会更新显示，想问一下自定义sql查询的前段代码应该怎么写，文档里只有后端实现，没有前端的文档
感觉勉强算生成的代码功能吧,高级查询什么的都正常

##### 截图&代码：

就是我想实现点击查询月检修计划以后,底下的数据显示的是我后端写的sql查出来的数据，但是现在这里的数据不变，但是给到前端的数据是对的
![Uploading am8_20240311134529657.jpg…]()

希望能帮助解决一下，卡好几天了一直解决不了，万分感谢！！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
图片裂 了
