### ISSUE TITLE
前端打包到nginx 中一直在index页面无法登录

### ISSUE THREAD

**Issue by xiamaocheng** [jeecgboot/jeecg-boot#5973]
##### 版本号：

3.6.1
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
打包部署，一直停留在index页面并没有登录

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8685152/bb7c6756-a1c2-4770-a138-84ea133dda1d)

**Comment by zhangdaiscott** [comment]
nginx端口是8099？

**Comment by xiamaocheng** [comment]
是8099-咋回事，卡着不动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 上午9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jeecgboot/jeecg-boot] 前端打包到nginx 中一直在index页面无法登录 (Issue #5973)




 
nginx端口是8099？

**Comment by fireinjava** [comment]
打开调试模式看下，可能是发布路径没改，静态文件访问地址少了层contextPath

# 发布路径
VITE_PUBLIC_PATH = /jeecg-admin/

**Comment by zhangdaiscott** [comment]
安装官方文档配置https://help.jeecg.com/publish/quick.html
