### ISSUE TITLE
getUserPermissionByToken 优化

### ISSUE THREAD

**Issue by fireinjava** [jeecgboot/jeecg-boot#5976]
##### 版本号：
最新版

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
http://boot3.jeecg.com/jeecgboot/sys/permission/getUserPermissionByToken
不太了解，这个普通用户登录，这边捞出所有按钮权限作什么用？
正常返回当前登录人员对应的菜单与按钮权限就好了。
另外 auth与codeList 这两个冗余了，
总得来说：allAuth、codeList 这两个可以删除

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/5036983/9eea768c-ef90-4753-b0d0-9d83485bc4bc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by huanongkou** [comment]
同问，佬友你知道答案了吗？我也觉得 不应该返回 allAuth。
