### ISSUE TITLE
使用Online表单开发功能，同步数据库后，验证测试页面打开报错

### ISSUE THREAD

**Issue by df837860925** [jeecgboot/jeecg-boot#5977]
##### 截图&代码：
           **1  点击截图功能测试按钮**：
![image](https://github.com/jeecgboot/jeecg-boot/assets/56633941/468b9d3c-7c02-476c-a6fd-7c2015183b2d)
            **2跳转页面报错**：
        
![image](https://github.com/jeecgboot/jeecg-boot/assets/56633941/248dd94f-c668-4544-9c53-5025909b586b)
            **3 报错具体代码如下**：
                      数据库查询失败，nested exception is org.apache.ibatis.exceptions.PersistenceException: ### Error querying database. Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT qyid,rcjgry,scdzhszfw,fzjg,qfr,fzrq,fzrq_start,fzrq_end,scdz,slh,ckdz,jgyjzc,fw,fwyw,bz,zs,cs,cp,cplb,cpmx,cz,dh,gg,jx,fj,wzyy,jsly,zt,ywlx,bbid,mkid,sjtb_gspt,sjtb_da,sjtb_xzsp,sjtb_gjj,sjtb_error,sjtb_gjj_time,sjtb_gspt_time,sjtb_da_time,sjtb_xzsp_time,ewm,ewm_lj,glzdb,lxryx,lxdh,qylx,ylzd1 ,id FROM cert_infos ORDER BY id desc ### Cause: com.baomidou.mybatisplus.core.exceptions.MybatisPlusException: Failed to process, Error SQL: SELECT qyid,rcjgry,scdzhszfw,fzjg,qfr,fzrq,fzrq_start,fzrq_end,scdz,slh,ckdz,jgyjzc,fw,fwyw,bz,zs,cs,cp,cplb,cpmx,cz,dh,gg,jx,fj,wzyy,jsly,zt,ywlx,bbid,mkid,sjtb_gspt,sjtb_da,sjtb_xzsp,sjtb_gjj,sjtb_error,sjtb_gjj_time,sjtb_gspt_time,sjtb_da_time,sjtb_xzsp_time,ewm,ewm_lj,glzdb,lxryx,lxdh,qylx,ylzd1 ,id FROM cert_infos ORDER BY id desc
         **4 将该报错内容的sql 在数据库中执行却是正常如下截图**：
![image](https://github.com/jeecgboot/jeecg-boot/assets/56633941/a5e6aff6-aa6a-4724-9be4-8f064df87f33)

  

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by df837860925** [comment]
补充说明：后台报错代码如下：
[后台报错代码.txt](https://github.com/jeecgboot/jeecg-boot/files/14568315/default.txt)

**Comment by zhangdaiscott** [comment]
重新步骤？
什么数据库？

**Comment by zhangdaiscott** [comment]
近期改过mybatsplus版本号导致，你更新下最新代码看看
