### ISSUE TITLE
Online表单中 下拉搜索框 搜索时报sql错误，生成的SQL多了一个 “and"

### ISSUE THREAD

**Issue by libaoo** [jeecgboot/jeecg-boot#5978]
##### 版本号：
3.6.3
##### 前端版本：vue3版？还是 vue2版？
vue3
##### 问题描述：
Online表单， 字段配置为下来搜索框，并配置了字典table，指定了id和name;在表单填报输入搜索时，系统报错

##### 截图&代码：

![Y8I}RGIQ_XURR$T}WJD~167](https://github.com/jeecgboot/jeecg-boot/assets/37819458/0f1d8c45-46a1-42f8-aac3-5b887b8aeb0a)
![Y8I}WDUG9O46~HN%{}I059QB](https://github.com/jeecgboot/jeecg-boot/assets/37819458/b38441dc-76ff-46c3-90f2-bc0f20db4ce1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待版本更新。
