### ISSUE TITLE
在线开发无法使用

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecg-boot#5985]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/734475ff-5db9-431d-ab03-0f86499e7a0b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
清下vite缓存试试

**Comment by cym1231** [comment]
> 清下vite缓存试试

我整个node_modules 删除 重新按照依赖也不行
