### ISSUE TITLE
导入excel，嵌入图片识别不到

### ISSUE THREAD

**Issue by fzh3816** [jeecgboot/jeecg-boot#5987]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
导入excel如果图片是嵌入形式的，则获取不到图片
与问题 https://gitee.com/jeecg/jeecg-boot/issues/I4LXNE 一样，我在更新日志中没找到这条更新

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待autopoi新版本发布

**Comment by zhangdaiscott** [comment]
升级autopoi到1.4.8版本就好了
```
<dependency>
  <groupId>org.jeecgframework</groupId>
  <artifactId>autopoi-web</artifactId>
  <version>1.4.8</version>
</dependency>
```
