### ISSUE TITLE
online表单获取数据库表404

### ISSUE THREAD

**Issue by duydwf** [jeecgboot/jeecg-boot#5988]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
jdk17 mysql5.7

http://localhost:3100/jeecgboot/online/cgform/head/queryTables/?_t=1710405832428 错误404
online表单无法导入数据表，查询不到数据库表，但是可以在“新增”里面创建新的表
拉的新代码，什么都没动！！！

##### 截图&代码：
![QQ截图20240314164358](https://github.com/jeecgboot/jeecg-boot/assets/163365887/9d30e1eb-b219-4c04-99ff-2ba9af3c3241)

![QQ截图20240314164424](https://github.com/jeecgboot/jeecg-boot/assets/163365887/9b8bdcec-0661-4833-a116-91ca51ba9deb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不太清楚，我们测试无问题

**Comment by shenyaojun** [comment]
遇到了同样的问题

**Comment by duydwf** [comment]
> 遇到了同样的问题

很无语，没解决就被关闭了

**Comment by huangwei2013** [comment]
> > 遇到了同样的问题
> 
> 很无语，没解决就被关闭了



同，3.6.1，但不是404，是200 但查询结果为空

```
http://localhost/jeecgboot/online/cgform/head/queryTables/?_t=1711959098731


{"success":true,"message":"","code":200,"result":[],"timestamp":1711959076021}
```

**Comment by yyancxt** [comment]
实测,是因为请求自动增加了?_t=1711959098731导致的,前端渣渣,懒得研究,直接反编译了后端对应controller,进行了覆盖,斜杠/即可
![WeChat113195c483df34234899e3c6297c7252](https://github.com/jeecgboot/jeecg-boot/assets/61650376/a35d9a4f-d98d-4fd7-bec8-9de0ab38e002)

**Comment by huangwei2013** [comment]
@yyancxt 麻烦联系我，有事请教，thx

**Comment by customysc** [comment]
> 实测,是因为请求自动增加了?_t=1711959098731导致的,前端渣渣,懒得研究,直接反编译了后端对应controller,进行了覆盖,斜杠/即可 ![WeChat113195c483df34234899e3c6297c7252](https://private-user-images.githubusercontent.com/61650376/319313800-a35d9a4f-d98d-4fd7-bec8-9de0ab38e002.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTYzMTQsIm5iZiI6MTcxMzM1NjAxNCwicGF0aCI6Ii82MTY1MDM3Ni8zMTkzMTM4MDAtYTM1ZDlhNGYtZDk4ZC00ZmQ3LWJlYzgtOWRlMGFiMzhlMDAyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyMTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYmI0MmMwMmFhMjZmM2NlZWFkMjUwOGM2YTA1MzNlZTEwNWIzMGFiODdkZmEyYWRmNTMzYzM2YjY1MjhmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LdXzPmySgTZs8pvHiolhU8ccLX-J2N7di-gvThV5wRk)

3.6.3相同问题，前端修改这里，删去'/'

**Comment by customysc** [comment]
3.6.3相同问题，前端删去这里的'/'
![Uploading 1713355656118.png…]()

**Comment by customysc** [comment]
3.6.3版本相同问题，前端反编译删去这里的 '/'

![1713355656118](https://github.com/jeecgboot/jeecg-boot/assets/127871625/5ce1f044-f7e2-4a58-9bce-40281ac7e588)

**Comment by ya0yy** [comment]
up dependencies.@jeecg/online version to 3.6.2-GA
