### ISSUE TITLE
系统用户》编辑》职务字段没有回显

### ISSUE THREAD

**Issue by jiaok1105** [jeecgboot/jeecg-boot#5990]
##### 版本号：
最新版本

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
系统用户》编辑职务没有回显

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/cda7db43-2e6f-4778-913b-756e805e47be)

演示系统测试没问题，看看是不是开启了saas隔离
