### ISSUE TITLE
v3.6.3仪表盘加载报错401

### ISSUE THREAD

**Issue by cdsuifeng** [jeecgboot/jeecg-boot#5991]
##### 版本号：
v3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
https://help.jeecg.com/chart/dashboard/config/menu.html
参考方式一修改后，访问首页加载仪表盘内数据集相关接口时报错401，token无效，发现仪表盘使用的token是上一次的缓存，旧的token。
经过 低代码开发->仪表盘设计器->点击对应的仪表盘-设计-预览 后，再次刷新首页，可以正常访问。退出后失效。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by cdsuifeng** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/3c534bed-8f5e-4842-998a-f40e86d90ec5)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/be0df89b-2179-489b-8648-f8383d3a5fd6)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/659a12a4-a15e-4640-89c8-3e7fc5b8041c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/4e132a9f-0b5c-47a3-ada8-ef0eabd1d8b9)

**Comment by zhangdaiscott** [comment]
你没有设置token吧
{{ window._CONFIG['domianURL'] }}/drag/view?pageId=899237617542529024&token=${token}&tenantId=${tenantId}

**Comment by cdsuifeng** [comment]
有设置的
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/7010ad9d-5514-4a78-a6e2-396740e18cd4)
{{ window._CONFIG['domianURL'] }}/drag/view?pageId=928196136470904832&token=${token}&tenantId=${tenantId}

**Comment by zhangdaiscott** [comment]
通过菜单点击有问题吗

**Comment by cdsuifeng** [comment]
也是一样的
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/f9cf95aa-eae1-42cc-a533-d19bc7a5da57)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/3c7820ec-d716-4aab-ab11-e3121cf7ce28)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23712951/88298c1d-d274-4e18-a208-2b549909e144)

**Comment by sxx412** [comment]
也碰到同样问题
