### ISSUE TITLE
引入ChatGPT使用过程中提示主机中的软件中止了一个已经建立的连接

### ISSUE THREAD

**Issue by LelandACM** [jeecgboot/jeecg-boot#5992]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1.升级jeecg-boot到3.6.3
2. 按照更新日志更新引入ChatGPT模块
3. 结合前端调用，发现服务器端出现错误
4. 使用官方chatgpt-java库的demo可以正常使用

##### 截图&代码：
连接sse建立是成功的
![image](https://github.com/jeecgboot/jeecg-boot/assets/19402747/a8996ef9-be4c-42cd-89bd-0fc297d6f254)
OpenAI建立sse连接...提示错误
![image](https://github.com/jeecgboot/jeecg-boot/assets/19402747/dfce2fd0-ddda-4fe1-ade3-a3247d8d5c1c)
chatgpt-java demo示例
![image](https://github.com/jeecgboot/jeecg-boot/assets/19402747/3e6a2951-ac04-4b97-835b-156c4fbf0ab1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你是直接下载的全新代码？还是自己升级的

**Comment by LelandACM** [comment]
> 你是直接下载的全新代码？还是自己升级的

自己升级的，服务器端太久没有更新了，只是自己直接更新jeecgboot.version 为3.6.3 ，前端使用的是clone最新的代码

**Comment by zhangdaiscott** [comment]
那可能代码更新不全
