### ISSUE TITLE
开启租户数据隔离后如何在某个方法上查询全局数据

### ISSUE THREAD

**Issue by zzw8421** [jeecgboot/jeecg-boot#5996]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
请问开启租户数据隔离后如何在某个方法或者SQL上进行注解或其他方式去除该方法或SQL租户查询条件变成全表查询。

##### 截图&代码：

![Uploading image.png…]()

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
@InterceptorIgnore(tenantLine = "true")

![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/837e686f-b03f-40cb-a04e-a8c9bc1ad81a)
