### ISSUE TITLE
bug：跳转到  Online表单 页面，tab标题显示为“AUTO在线报表”，而不是设置的自定义标题（如：告警列表）

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/jeecg-boot#5997]
##### 版本号：

3.6.1

##### 前端版本：vue3版？还是 vue2版？

vue3

##### 问题描述：

1.两个Online 表单配置的页面，从其中一个页面的指定字段，跳转到另一个页面

2.跳转到  Online表单 页面，tab标题显示为“AUTO在线报表”，而不是设置的自定义标题（如：告警列表）

##### 截图&代码：

1.
跳转页配置：

![企业微信截图_17104836886298](https://github.com/jeecgboot/jeecg-boot/assets/4926491/1317ed95-d61f-4387-ac18-c6f428ccf34e)
- 带了筛选条件参数，url如：http://127.0.0.1/online/cgreport/1752169391882768385?code=900010005&project_id=10002&device_id=12345

被跳转页：
![企业微信截图_1710483789127](https://github.com/jeecgboot/jeecg-boot/assets/4926491/bbc9ccd0-f161-4cae-96c0-8cbbd51b1c59)

2. 被跳转页，通过左边栏直接访问，可以正常显示 tab标题
url如：http://127.0.0.1/online/cgreport/1752169391882768385

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
最新版已经支持
