### ISSUE TITLE
3.4.3Cloud版本，gateway启动失败

### ISSUE THREAD

**Issue by youxidonxx** [jeecgboot/jeecg-boot#6002]
##### 问题描述：host已配置，都是127.0.0.1，nacos2.0.3版本使用自有地址，也根据sql文件提示创建相关配置，端口也已开放；
gateway启动后，提示nacos server register finished,但是提示初始化路由模式，dataType：null 导致启动失败，
未读取到配置，想问下是否有哪里遗漏的地方，可以从哪里入手

##### 截图&代码：
host配置
![image](https://github.com/jeecgboot/jeecg-boot/assets/1058543/7eba9799-3839-443b-89a4-94ef61a4f065)
nacos启动后配置列表
![image](https://github.com/jeecgboot/jeecg-boot/assets/1058543/7d75b0ce-e278-4c0d-8538-ed51ea053797)
gateway启动错误提示，中间还插着一个redis的链接失败
![image](https://github.com/jeecgboot/jeecg-boot/assets/1058543/e86b9b30-1cc6-4ffe-b60e-d29276bcc121)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
1、确认gateway连上nacos了吗
2、确认gateway采用那种路由加载模式
