### ISSUE TITLE
导入 读取数据值失败

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecg-boot#6003]
##### 问题描述：如果实体字段为int 类型  导入时单元格为负数如-1，-20 
会出现 报错excel值获取失败 
将实体类注解type 改为4也无效
@Excel(name = "xx", width = 15,type =4 )

##### 截图&代码：
报错位置：List<T> list = ExcelImportUtil.importExcel(file.getInputStream(), clazz, params);
EXCEL注解
/**
	 * 导出类型 1 是文本 2 是图片,3是函数,4是数字 默认是文本
	 */
	public int type() default 1;

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by cym1231** [comment]
> cr

佬 cr什么意思?

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/994e16b9-1cbf-4da1-bf40-b060ec54ac00)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/44718212-a9b8-477a-99a7-cd66c4e8df59)
未复现，后台有报错吗？报错堆栈能发一下吗？可以详细说明问题复现的步骤？

**Comment by cym1231** [comment]
> ![image](https://private-user-images.githubusercontent.com/13013558/318656252-994e16b9-1cbf-4da1-bf40-b060ec54ac00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Njg1NjQsIm5iZiI6MTcxMjQ2ODI2NCwicGF0aCI6Ii8xMzAxMzU1OC8zMTg2NTYyNTItOTk0ZTE2YjktMWNiZi00ZGExLWJmNDAtYjA2MGVjNTRhYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA1Mzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMTc0Y2Q5NGFmM2E3OWJhNjkwMWE0MGI5OGMxMzFjYzQxZDk5MjBkNWY3MjI1ZWExZDA5YzA5YjdhM2RhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TkymozIGLsU7zfdZ-rE_5Kt9NeMxN0KoTsd7gbBJ1wo) ![image](https://private-user-images.githubusercontent.com/13013558/318656450-44718212-a9b8-477a-99a7-cd66c4e8df59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Njg1NjQsIm5iZiI6MTcxMjQ2ODI2NCwicGF0aCI6Ii8xMzAxMzU1OC8zMTg2NTY0NTAtNDQ3MTgyMTItYTliOC00NzdhLTk5YTctY2Q2NmM0ZThkZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA1Mzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NDAzNzY2YTA5MzdjODg2YmIzZTNkNWY2MWZmNTlhODZhMWIxM2VjNjFmN2EwNjJlOTdjZTk5YTFiYWRmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyANKexNUKpcv3lKZM27kXZq8M4BUktmchMruqFwTvk) 未复现，后台有报错吗？报错堆栈能发一下吗？可以详细说明问题复现的步骤？

你好，你的版本是多少呢？ 而且我这边的操作是导出一个空的表格  然后输入负数值 并不是导出后修改值，关键细节在于 导出负数时 excel表格会在负数的单元格左上角出现一个绿色的三角  而手动输入负数并没有这个三角 最后导致报错

**Comment by hoperunChen** [comment]
> 你好，你的版本是多少呢？ 而且我这边的操作是导出一个空的表格 然后输入负数值 并不是导出后修改值，关键细节在于 导出负数时 excel表格会在负数的单元格左上角出现一个绿色的三角 而手动输入负数并没有这个三角 最后导致报错

我这边用的3.6.3版本，按照您的步骤，仍然未复现。
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/b768712f-cf0c-4a79-bd84-1bacd3fd5d88)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/327462c5-d7b3-4468-8d2a-8d5bbcfac2d0)

**Comment by cym1231** [comment]
> > 你好，你的版本是多少呢？ 而且我这边的操作是导出一个空的表格 然后输入负数值 并不是导出后修改值，关键细节在于 导出负数时 excel表格会在负数的单元格左上角出现一个绿色的三角 而手动输入负数并没有这个三角 最后导致报错
> 
> 我这边用的3.6.3版本，按照您的步骤，仍然未复现。 ![image](https://private-user-images.githubusercontent.com/13013558/320256194-b768712f-cf0c-4a79-bd84-1bacd3fd5d88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc0NzYsIm5iZiI6MTcxMjQ3NzE3NiwicGF0aCI6Ii8xMzAxMzU1OC8zMjAyNTYxOTQtYjc2ODcxMmYtY2YwYy00YTc5LWJkODQtMWJhY2QzZmQ1ZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4MDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTIyYTA3MmMzMWEzOTNkYzQ5NjBiMzQ1NTc2M2IzY2FlOTI1NWZiY2NiZTI3ZDUzNTMwMjZjYmEwM2MyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oN0SsMpMCS7-HKhqMZIyacNV0ArvVZ8mLRtUf077hmE) ![image](https://private-user-images.githubusercontent.com/13013558/320256229-327462c5-d7b3-4468-8d2a-8d5bbcfac2d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0Nzc0NzYsIm5iZiI6MTcxMjQ3NzE3NiwicGF0aCI6Ii8xMzAxMzU1OC8zMjAyNTYyMjktMzI3NDYyYzUtZDdiMy00NDY4LThkMmEtOGQ1YmJjZmFjMmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA4MDYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NDJlMGJkNzc2NWMwNDhjMTYwYjVhMWM4ODI3ZDUyNWYwZTllNWY5YmZhOTFhZWY5MzM5ZmU0MzY0NmYyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQrD2ZZI2KJjrnyZBbNr6JSM5KoyAeXzQyiEeraWg-0)

非常感谢您的耐心指导，这个问题我下次要是还遇到再另外提issue,l另外就是 #6087也是我提的问题如果可以的话麻烦您一起看下
