### ISSUE TITLE
JVXeTable下拉框组件使用字典首次未加载数据

### ISSUE THREAD

**Issue by lcrazyl** [jeecgboot/jeecg-boot#6005]
##### 前端版本：vue3版？还是 vue2版？

Vue3
##### 问题描述：

JVXeTable下拉框组件使用字典首次未加载数据，刷新后再次点击正常
##### 截图&代码：

![{ED2AFE17-B93C-402C-972B-6AFA1327B538}](https://github.com/jeecgboot/jeecg-boot/assets/56683317/73ee15eb-977c-4769-9aea-852950f59784)
![{1AA75907-B1B6-48B2-AF56-BF553C199EEC}](https://github.com/jeecgboot/jeecg-boot/assets/56683317/cef7716d-2612-495e-9216-8734cfa961a2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lcrazyl** [comment]
本地渲染正常，打包部署到测试环境后，第一次渲染页面加载失败，刷新当前路由后加载成功

**Comment by zhangdaiscott** [comment]
补充版本号
