### ISSUE TITLE
Quartz定时任务画面生成的表达式无法运行

### ISSUE THREAD

**Issue by antbuster** [jeecgboot/jeecg-boot#6006]
##### 版本号：
3.6.0

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Quartz定时任务画面生成的表达式最后一位自动带年[*],这种情况不管前面表达式这么写，quartz都不会运行，也没有任何异常log。
以自带的例子SampleParamJob为例，每秒执行【0/1 * * * * ? *】不会运行，但是把最后一位去掉【0/1 * * * * ? 】或者指定年份区间【0/1 * * * * ? 2024/1】就可正常运行
![image](https://github.com/jeecgboot/jeecg-boot/assets/10290156/da591bc5-2dbf-4b98-bf1f-bc81d8cc74c0)

另外，配置文件中Quartz的配置错了，
正确应该这么配置

![image](https://github.com/jeecgboot/jeecg-boot/assets/10290156/7eddba24-4d31-43e9-abc1-4b1047de468f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/e6aa959c-1b84-4495-85b6-648bdc6bcf0c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/caf1f983-a778-4aa7-887f-b66fa8f2b9e1)
未复现，请提供复现步骤。

**Comment by antbuster** [comment]
好神奇，今天正常了
