### ISSUE TITLE
Online表单导入表格时将文件名作为处理内容一并写入数据库表

### ISSUE THREAD

**Issue by SilenceLurker** [jeecgboot/jeecg-boot#6008]
##### 版本号：
3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我想在Online表单导入Excel表格的时候将文件名作为其中一个字段传入，除了在上传文件后在文件内添加字段以外有没有什么更好的方法？Java增强貌似只能对Excel表格内的数据进行操作，但是文件名之类的文件信息就被抛弃了。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
目前不支持
