### ISSUE TITLE
钉钉同步部门时没有最顶层的部门名，同步用户时，用户没有部门信息

### ISSUE THREAD

**Issue by ywcxx1994** [jeecgboot/jeecg-boot#6017]
##### 版本号：
3.4.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
首先钉钉同步部门到本地，部门没有最顶层的部门名；
钉钉同步用户到本地时， 用户没有部门信息。

##### 截图&代码：
部门没顶层截图
<img width="863" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19264854/8d84c132-27e9-40f5-ad63-6dc8999b2e7f">
用户没部门截图
<img width="1328" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19264854/5aed25d1-5cf1-4d10-80f8-63f4f8146d6c">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by ywcxx1994** [comment]
没有一级部门已经解决
<img width="926" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/19264854/994ebe60-0835-48f3-ad72-c847837627f6">

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
已修复，待新版本发布

**Comment by cnzhujigang** [comment]
这个bug修复了吗
