### ISSUE TITLE
3.4.4 租户登陆问题

### ISSUE THREAD

**Issue by GadXlf** [jeecgboot/jeecg-boot#6020]
##### 版本号：
v3.4.4

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
按照https://jeecg.blog.csdn.net/article/details/119780074进行配置后配置了用户租户设置后
登陆时提示用户无效
控制台中显示的时搜索了tenant_id = 0的角色，这个需要怎么操作才能正常登陆

##### 截图&代码：
![Uploading 微信截图_20240320155317.png…]()

==>  Preparing: SELECT id, username, realname, password, salt, avatar, birthday, sex, email, phone, org_code, status, del_flag, work_no, post, telephone, create_by, create_time, update_by, update_time, activiti_sync, user_identity, depart_ids, rel_tenant_ids, client_id, open_id, mp_open_id, union_id FROM sys_user WHERE del_flag = 0 AND (username = ?)
==> Parameters: admin(String)
<==    Columns: id, username, realname, password, salt, avatar, birthday, sex, email, phone, org_code, status, del_flag, work_no, post, telephone, create_by, create_time, update_by, update_time, activiti_sync, user_identity, depart_ids, rel_tenant_ids, client_id, open_id, mp_open_id, union_id
<==        Row: e9ca23d68d884d4ebb19d07889727dae, admin, 管理员, cb362cfeefbf3d8d, RCGTeGiH, https://static.jeecg.com/temp/国炬软件logo_1606575029126.png, 2018-12-05 00:00:00, 1, jeecg@163.com, 18611111111, A05, 1, 0, 00001, 总经理, null, null, 2019-06-21 17:54:10, admin, 2024-03-20 14:57:12, 1, 2, <<BLOB>>, 1, null, null, null, null
<==      Total: 1
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1d2dbab1]
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1022e71e] was not registered for synchronization because synchronization is not active
original SQL: select role_code from sys_role where id in (select role_id from sys_user_role where user_id = (select id from sys_user where username=?))
SQL to parse, SQL: select role_code from sys_role where id in (select role_id from sys_user_role where user_id = (select id from sys_user where username=?))
parse the finished SQL: SELECT role_code FROM sys_role WHERE id IN (SELECT role_id FROM sys_user_role WHERE user_id = (SELECT id FROM sys_user WHERE username = ?)) AND sys_role.tenant_id = 0
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@77188651] will not be managed by Spring
==>  Preparing: SELECT role_code FROM sys_role WHERE id IN (SELECT role_id FROM sys_user_role WHERE user_id = (SELECT id FROM sys_user WHERE username = ?)) AND sys_role.tenant_id = 0
==> Parameters: admin(String)
<==      Total: 0

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by GadXlf** [comment]
登陆接口中我写了一个查询用户角色的判断

**Comment by GadXlf** [comment]
请求头中包含Tenant-Id:1

**Comment by zhangdaiscott** [comment]
版本太老， 自己debug看看吧
