### ISSUE TITLE
过滤字段page_filter_fields无效

### ISSUE THREAD

**Issue by duangdangding** [jeecgboot/jeecg-boot#6023]
##### 问题描述：
配置了 page_filter_fields 过滤字段 ，打开编辑窗口的时候 还是要手动去选，这些字段不显示，理应自动不勾选这些过滤的字段的

##### 截图&代码：
#page_filter_fields
page_filter_fields=create_time,create_by,update_time,update_by,del_flag,tenant_id,del_time
![image](https://github.com/jeecgboot/jeecg-boot/assets/38204865/cf4b466a-7f64-4bb9-b5d3-7ee6ae1bd99b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
page_filter_fields  这个是给代码生成用的 ，你是说online功能测试默认不勾上，还是代码生成的时候，生成了

**Comment by duangdangding** [comment]
online功能的时候，配置文件配置了自定义过滤字段，然后理应默认的时候不应该勾上的，现在是没有效果，还是勾上了

**Comment by zhangdaiscott** [comment]
page_filter_fields 是控制代码生成的，不是online
