### ISSUE TITLE
3.6.2版本首屏加载慢问题

### ISSUE THREAD

**Issue by chenhengeng** [jeecgboot/jeecg-boot#6024]
版本号：3.6.2

前端版本：vue3版

问题描述：首屏第一次加载慢，无论是开发 还是测试环境（已开启nginx压缩）都是6、7s才加载出来。看vue3官网也说了 vue3是动态加载了，不在像vue2一样 首屏全部加载了。（我当时用jeecgboot vue2版本的时候，首屏加载慢，就很头疼）。我有如下两个问题，

1：我现在3.6.2版本不管什么环境，首屏加载6、7s。这个正常吗:？
2：我看3.6.3对首屏加载有提升，这个提升大概是什么级别，如果提升很大，我考虑升级到你们的3.6.3版本

截图&代码：

友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有一定的提升
