### ISSUE TITLE
auto poi 在导入包含图片的excel 时报错   但是导出没有问题

### ISSUE THREAD

**Issue by wpk1041578654** [jeecgboot/jeecg-boot#6025]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在使用auto poi 导入包含图片的excel 时报错   (使用的模板是用auto poi导出的)

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/164283898/697f6228-b027-4f89-ad40-10f151bd8489)

![image](https://github.com/jeecgboot/jeecg-boot/assets/164283898/9489fe05-2aa9-42eb-898c-169c0723204f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/164283898/c5526c45-3161-49fc-900d-5a76d7ac0f27)
![image](https://github.com/jeecgboot/jeecg-boot/assets/164283898/730faac1-5abc-4631-9200-48e4cd27de39)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
图片是什么格式

**Comment by wpk1041578654** [comment]
.png格式的

**Comment by wpk1041578654** [comment]
我的操作是 用auto poi 直接导出excel  再用auto poi 反手读取就报错

**Comment by zhangdaiscott** [comment]
截图

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待autopoi新版发布。

**Comment by zhangdaiscott** [comment]
升级autopoi到1.4.8版本就好了
```
<dependency>
  <groupId>org.jeecgframework</groupId>
  <artifactId>autopoi-web</artifactId>
  <version>1.4.8</version>
</dependency>
```
