### ISSUE TITLE
Online在线功能。配置href字段跳转之后，tab页不显示配置名称。

### ISSUE THREAD

**Issue by hongbo1030** [jeecgboot/jeecg-boot#6026]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
Online在线功能,单表默认主题。
配置href字段跳转之后，tab页不显示配置名称，只显示“AUTO在线报表”和“AUTO在线表单”。怎么修改?
尝试配置菜单、报表均不能解决。

##### 截图&代码：
![a5357185a520ad38c1c95a9bde3cdbdb](https://github.com/jeecgboot/jeecg-boot/assets/7260193/fc246418-ab28-4dab-b207-6c2e9c2292f6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你只有配置了对应的菜单，就会显示对应菜单的名字
