### ISSUE TITLE
online表单API接口权限问题

### ISSUE THREAD

**Issue by zwjsoft** [jeecgboot/jeecg-boot#6028]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在开发的一个综合页面中，用了不少online表单接口，主要是查询接口/online/cgform/api/getData/{code}，在使用的时候，提示权限不够，只有把这个表单的权限分配给用户后，才能正常使用，但是这些权限实际上对用户是没有任何意义的，怎么解决？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有意义，没有权限，表单不是可以随便访问

**Comment by zwjsoft** [comment]
> 有意义，没有权限，表单不是可以随便访问

我一个定义了大概7/8个基础字典，正式用的表单上用了这几个字典，用户只要能选这几个字典的值就行了，而且他们完全不能够修改处理这些字典的值，把权限都给他们干什么了，进系统就1个菜单有用，其他的都没用
