### ISSUE TITLE
【疑问】多机部署，日志怎么处理？怎么聚合？怎么判断来自哪个服务器？

### ISSUE THREAD

**Issue by JaneYork** [jeecgboot/jeecg-boot#6029]
##### 版本号：
最新

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
【疑问】多机部署，日志怎么处理？怎么聚合？怎么判断来自哪个服务器？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://segmentfault.com/a/1190000044471518

使用Loki、grafana套件
