### ISSUE TITLE
阿里的oceanbase,分页语法问题

### ISSUE THREAD

**Issue by luygege** [jeecgboot/jeecg-boot#6030]
##### 版本号：
2.4.5

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
使用jeecgboot的时候，数据库是阿里的oceanbase，oracle租户，分页的时候会使用limit，也就是mysql的分页方式，但实际上应该是oracle的分页语法

##### 截图&代码：
![dba19e62879d7fb1f3495b6dfbb3b428](https://github.com/jeecgboot/jeecg-boot/assets/57478167/da695527-2c38-4a57-9385-ea038d486a4e)
![be297b7ffc740cb50a939fcbb2330004](https://github.com/jeecgboot/jeecg-boot/assets/57478167/486daec6-86b8-4b90-a3b7-31adaa0fe4ba)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你应该去给mybatisplus提

**Comment by luygege** [comment]
好的，谢谢
