### ISSUE TITLE
3.6.3 LoginUser.java 缺了个 String parentId;

### ISSUE THREAD

**Issue by dahailiu123** [jeecgboot/jeecg-boot#6031]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
登录报错，加上这句就好了。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
为什么需要这个字段

**Comment by dahailiu123** [comment]
![Uploading image.png…]()
我根据错误提示加的，加上后就不报错了。

**Comment by dahailiu123** [comment]
不对，是我本地环境的问题。redis里之前的登录信息，清空redis后正常

**Comment by zhangdaiscott** [comment]
老的数据为什么会有parentId呢？
