### ISSUE TITLE
表单开发中编辑保存超时

### ISSUE THREAD

**Issue by zqzqhpj** [jeecgboot/jeecg-boot#6033]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
，取消超时时间后一直在转圈圈出不来。后台无报错，前台报后台返回超时。

##### 截图&代码：

![QQ图片20240323171109](https://github.com/jeecgboot/jeecg-boot/assets/77739481/6da911bd-5dc4-46bf-b2f8-2aef842d3449)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看下，再看下后台日志
