### ISSUE TITLE
Online表单开发 - 导入数据库表  无法获取数据库表信息

### ISSUE THREAD

**Issue by Sivan757** [jeecgboot/jeecg-boot#6034]
##### 版本号：
3.6.2 & sas

##### 前端版本：vue3版？还是 vue2版？
vue3 

jeecg/online 3.6.0.beta
jeecg/online 3.6.2.beta

##### 问题描述：
Online表单开发 - 导入数据库表 
无法获取数据库表信息，报错找不到接口，实际上是由于前端多了一层时间戳 path 导致

##### 截图&代码：

<img width="651" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/29885829/dbb4b315-fd1a-42b3-9b6e-b73397bac4ca">

<img width="836" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/29885829/db8eef16-457d-43bc-bbc5-20a1750a2f3e">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sas 版本才有问题?

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
已修复，得下个版本发布
