### ISSUE TITLE
【在线开发】【从数据库导入表单】时数据库表不展示，后端报空指针

### ISSUE THREAD

**Issue by Protector-001** [jeecgboot/jeecg-boot#6039]
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
online表单开发，导入数据库表，不展示数据，jar包部署，config下已经有相关配置了，online表单创建的表可以同步数据库

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/d1626128-d6d2-443e-bf4d-6657789be15f)
![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/e98c230a-79f9-4845-9d8a-a348026bc69f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
F12看下

**Comment by Protector-001** [comment]
> F12看下

![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/260feec6-5b08-4fc5-8eb0-071bbdfc44a9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/96367636/e49e0a73-89b8-49a7-8188-d3381342aa80)
我用3.6.2版本的system部署不会出现这个问题

**Comment by zhangdaiscott** [comment]
cr

**Comment by zhangdaiscott** [comment]
你的mybatis plus是那个版本？

**Comment by hoperunChen** [comment]
未复现，后端有没有报错堆栈发一下？

**Comment by 2112786079** [comment]
我出现了一样的问题，结果发现是application-dev.yml里的数据库配置  driver-class-name: com.mysql.cj.jdbc.Driver被我换数据源的时候删掉了，读不到这个配置代码生成器就读不到数据库，现在代码生成的配置走的jeecg-module-system\jeecg-system-biz\src\main\java\org\jeecg\config\init\CodeGenerateDbConfig.java这个文件，也就是当前数据库的动态信息。
