### ISSUE TITLE
excel导入主附表，附表有图片类型，导入报错

### ISSUE THREAD

**Issue by jihean** [jeecgboot/jeecg-boot#6040]
##### 版本号：
Jeecg  Boot Version: 3.5.2
Spring Boot Version: 2.7.10 (v2.7.10)

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
excel导入主附表，附表有图片类型(@excel:type=2)，导入报错

##### 截图&代码：
![issue1](https://github.com/jeecgboot/jeecg-boot/assets/20696760/5c03c51d-ed8e-4efc-9ee6-8f0965580256)
![issue2](https://github.com/jeecgboot/jeecg-boot/assets/20696760/12671691-6377-4e14-8c74-6d26f7ded365)
![issue3](https://github.com/jeecgboot/jeecg-boot/assets/20696760/0cfb05ce-6ff6-4d98-b4a9-dd287fd4282c)
这样提交子表的图片字段不处理
![issue4](https://github.com/jeecgboot/jeecg-boot/assets/20696760/58a8f7af-007d-4db2-9971-9c97b6345e7a)
这样提交报错object is not an instance of declaring class    ,   但是会保存图片

生成的代码功能

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已修复，待autopoi新版发布。

**Comment by zhangdaiscott** [comment]
升级autopoi到1.4.8版本就好了
```
<dependency>
  <groupId>org.jeecgframework</groupId>
  <artifactId>autopoi-web</artifactId>
  <version>1.4.8</version>
</dependency>
```
