### ISSUE TITLE
使用代码生成器生成树的结构，批量删除时报错，在很老的jeecg,vue2版本就在报错了

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6043]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？
vue3

##### 截图&代码：
![1711504014558](https://github.com/jeecgboot/jeecg-boot/assets/132029411/0985ad09-0754-4142-8dff-c43df156bb03)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/0832cb0a-5a08-43bf-a62a-15ea3aff4daf)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/874458b9-682b-4063-8816-5d647d27ab20)
未复现，请提供复现步骤。

**Comment by yzh20021029** [comment]
![微信图片_20240402102839](https://github.com/jeecgboot/jeecg-boot/assets/132029411/01a2d99b-0266-47cb-8c29-edbae22e2673)
![微信图片_20240402102950](https://github.com/jeecgboot/jeecg-boot/assets/132029411/9962c820-4b0a-44c4-b5e6-e3de988d167c)
![微信图片_20240402102952](https://github.com/jeecgboot/jeecg-boot/assets/132029411/4d945ba8-2c8e-4f70-8bb0-877839bd5fa4)

**Comment by hoperunChen** [comment]
已修复，下个版本更新。
