### ISSUE TITLE
excel模板导出报错

### ISSUE THREAD

**Issue by xjx-rgb** [jeecgboot/jeecg-boot#6047]
##### 版本号：

3.5.5
##### 前端版本：vue3版？还是 vue2版？
vuw2

##### 问题描述：
使用自定义模板导出 报错 

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/65055614/9f15bbfe-5b1f-4efd-af30-c405d5d71697)
![image](https://github.com/jeecgboot/jeecg-boot/assets/65055614/e8aaee26-1107-494e-a4ca-8fb77f310626)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请提供你的自定义模板
