### ISSUE TITLE
仪表盘设计时，图表设置了跳转地址，预览正常，但是集成到菜单后无法跳转

### ISSUE THREAD

**Issue by sxx412** [jeecgboot/jeecg-boot#6048]
##### 版本号：
3.6.2/3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1. 进入低代码开发-仪表盘设计器，选择或新建一个仪表盘
2. 添加一个饼图，选择交互-跳转配置，输入跳转地址，如http://www.baidu.com
3. 保存并预览，此时点击饼图，可跳转到设置的url
4. 集成到菜单后，点击拼图，无反应

* 官网用jeecg账号登录，操作后也有类似问题

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by sxx412** [comment]
通过自定义脚本倒是可以跳转，预览和集成到菜单都正常

**Comment by zhangdaiscott** [comment]
自定义脚本是什么意思

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
配置菜单用的是这种方式吗？{{ window._CONFIG['domianURL'] }}/drag/view?pageId=******
