### ISSUE TITLE
JSearchSelect的search事件在中文输入还没拼字成功时会触发，导致后端SQL注入

### ISSUE THREAD

**Issue by Aweia912** [jeecgboot/jeecg-boot#6049]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
JSearchSelect的search事件在中文输入还没拼字成功时就会触发搜索，然后后端SysDictServiceImpl.queryLittleTableDictItems方法会拼接错误的sql，导致sql注入风险。
在搜索框中包含单引号 **'** 符号，也会引发同样的问题。

##### 截图&代码：
![前端](https://github.com/jeecgboot/jeecg-boot/assets/79973338/8829c51b-99c0-4a22-acec-6a790c42e39b)
![后端](https://github.com/jeecgboot/jeecg-boot/assets/79973338/e4bd9f43-4df1-478c-8ca5-6fddc40e11a3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr
