### ISSUE TITLE
集合chatgpt出现问题，麻烦帮忙看一下

### ISSUE THREAD

**Issue by Yuqn** [jeecgboot/jeecg-boot#6050]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
开启chatgpt后，没办法正常使用，提示连接超时，开启代理配置后，提示找不到地址，可以帮忙看一下缺少什么东西吗

##### 截图&代码：

有开梯子的情况下：
![image](https://github.com/jeecgboot/jeecg-boot/assets/92110217/c1630732-8653-49ab-a522-35a23662728c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/92110217/c5b5a15d-18ff-4e3f-8a6f-f4b29e09988b)

代码启动本地代理地址后：
![image](https://github.com/jeecgboot/jeecg-boot/assets/92110217/f764b334-302a-431a-b96f-e51310625829)
![image](https://github.com/jeecgboot/jeecg-boot/assets/92110217/93790bf0-1b24-4288-bb3f-a5765e684127)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by Whiteyingshan** [comment]
是不是要写成这样
  proxy:
    host: 127.0.0.1
    port: 7890

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/chatgpt.html

**Comment by Yuqn** [comment]
> 是不是要写成这样 代理： 主机：127.0.0.1 端口：7890
> 
> 还有我记得梯子还得开启允许楼梯连接 ![图像](https://private-user-images.githubusercontent.com/43714420/317218705-4f85e9ce-1650-413e-939b-2a4a18106ecc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDYxMTgsIm5iZiI6MTcxMTcwNTgxOCwicGF0aCI6Ii80MzcxNDQyMC8zMTcyMTg3MDUtNGY4NWU5Y2UtMTY1MC00MTNlLTkzOWItMmE0YTE4MTA2ZWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5NTAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljM2ViMTVjZGRkNGI1NjA2NjNiNzU4ZWIzMGI5NTgwYTE4MDA5NGU2YjNjNDFkOGI4NGNkMDc2M2MzMDkzYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ygMqjkzOC3ElLvdYpGt6KrPQ6rYNyQIKebKeSy-Intc)

解决了，是这个问题，前面不能加http://，感谢

**Comment by Yuqn** [comment]
> https://help.jeecg.com/java/chatgpt.html

已解决
