### ISSUE TITLE
online表单列位置的id未做限制，拖动其他列到id列上面，同步数据库时报错

### ISSUE THREAD

**Issue by richuV** [jeecgboot/jeecg-boot#6054]
##### 版本号：
最新版
##### 问题描述：

online表单列位置的id未做限制，拖动其他列到id列上面，同步数据库时报错
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/38059206/4b7190e7-d85e-4e88-9496-2560cd073fd2)
![image](https://github.com/jeecgboot/jeecg-boot/assets/38059206/d7ed2c45-82ef-4a6c-bc1f-1b2ae6d91e37)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
