### ISSUE TITLE
AuoTo api 进行excel模板导出 如果表里面字段存储的是字典值在进行导出的时候怎么进行字典翻译，如果是注解导出可以用注解进行翻译，用模板导出怎么进行翻译

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6057]
##### 问题描述：
AuoTo api 进行excel模板导出 如果表里面字段存储的是字典值在进行导出的时候怎么进行字典翻译，如果是注解导出可以用注解进行翻译，用模板导出怎么进行翻译

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
模板的话，需要你自己手工编码实现导出翻译，导入转翻译
