### ISSUE TITLE
SQL注入

### ISSUE THREAD

**Issue by 1301878357** [jeecgboot/jeecg-boot#6058]
##### 版本号：
3.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
SQL注入

##### 截图&代码：
![1711704559037](https://github.com/jeecgboot/jeecg-boot/assets/61526387/0b57d30e-6e37-4791-8c3e-1216fadb00aa)
![1711704663468](https://github.com/jeecgboot/jeecg-boot/assets/61526387/379bf32c-e7bd-4dfa-bdb8-2755fda65942)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1301878357** [comment]
补充一张图片
![1711704894374](https://github.com/jeecgboot/jeecg-boot/assets/61526387/f3373e71-67ad-4776-964a-cff24d83d16c)

**Comment by zhangdaiscott** [comment]
https://my.oschina.net/jeecg/blog/10107636

**Comment by zhangdaiscott** [comment]
更多漏洞处理请自查
https://jeecg.com/doc/log
