### ISSUE TITLE
并发情况下mybatis IdWorker.getIdStr() 主键重复

### ISSUE THREAD

**Issue by qinghechaoge** [jeecgboot/jeecg-boot#6059]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
并发情况下mybatis IdWorker.getIdStr() 生成的主键重复

https://blog.csdn.net/yuechuzhixing/article/details/133703971
![image](https://github.com/jeecgboot/jeecg-boot/assets/3311840/909726e9-e8ee-43da-b00c-fbc380b95d3b)

用上面图片中解决办法也不行
请问 如何修改id生成的长度，如果解决并发下重复的问题

**Comment by EightMonth** [comment]
通过以下方法指定workerId和dataCenterId，两个ID最大均为31
IdWorker.initSequence(long workerId, long dataCenterId)
