### ISSUE TITLE
Online 表单开发 - 使用非框架数据库出错

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/jeecg-boot#6063]
##### 版本号：

3.6.1

##### 前端版本：vue3版？还是 vue2版？

vue3

##### 问题描述：

在界面上使用Online表单开发，希望使用非框架的数据库
   1. 界面上没有选择数据库的地方（对比：[Online 报表配置] 页面，可选择对应数据库 ）
   2. 若在界面上 [表名] 输入框填写  [自定义库名.表名] ，可以成功创建记录，可同步到对应数据库 ； 但点击 [更多-功能测试]，会提示 “表名不合法，存在SQL注入风险!”
   3. 查看对应代码，应该是代码中未 协调好  2. 中，界面可填写 vs 框架校验规则不允许。

##### 截图&代码：

界面提示：
![企业微信截图_17119401125696](https://github.com/jeecgboot/jeecg-boot/assets/4926491/22bdb5a4-a0cf-4aad-9d84-677718372b2d)

框架校验逻辑：
![企业微信截图_17119401365932](https://github.com/jeecgboot/jeecg-boot/assets/4926491/800349f2-fc7e-4f9a-9f80-98dc965d87f2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
配置界面，截图看看

**Comment by huangwei2013** [comment]
![企业微信截图_17121088274429](https://github.com/jeecgboot/jeecg-boot/assets/4926491/222a7d86-f098-49a7-805d-82017019b762)


1.上图的编辑，一直都OK
2.但保存后，要通过“功能测试”看效果，就会有以上提示。
  - 现在是屏蔽了代码中的 库表名 校验，才能顺利跑下去。

**Comment by zhangdaiscott** [comment]
你的表名为什么要带点呢

**Comment by huangwei2013** [comment]
我的表是在另一个 db 上。如果不用  dbname.tablename ，还有别的方法吗

**Comment by zhangdaiscott** [comment]
online报表只是报表，不涉及数据库结构的更新

**Comment by huangwei2013** [comment]
但对库表的基本隔离需求是一致的，都需要在不同性质的库，管理不同表。
而且从实现上来说，也只是横向扩展。
所以非常困惑，这两个 online 的操作性，为何没对齐
