### ISSUE TITLE
大屏设计器里面的sql编辑响应数据返回错误

### ISSUE THREAD

**Issue by luorichenying** [jeecgboot/jeecg-boot#6064]
##### 版本号：
不知道是哪个版本，不过是在线上进行操作的，从这个链接http://boot3.jeecg.com/system/menu进入的

##### 前端版本：vue3版？还是 vue2版？
也不确定，没有找到可以查看版本号的地方。

##### 问题描述：
在进入大屏设计器后，然后在数据源管理里面添加了数据库，测试连接提示是正常的。然后新建大屏，拉了一个折线图到图层里面，选择数据下面的sql数据，点击sql处理编辑后，在里面输入了sql语句【 SELECT ota ,COUNT(*)  FROM shijue_tourism.shijue_ota_comment_cooperate socc WHERE ctime between '2024-02-29' and '2024-03-01' and ota = '携程' GROUP BY ota 】，这个sql语句在数据库里面直接查询是有数据的，但是在返回的响应数据里面返回的结果有问题，没有准确的返回正常数据

##### 截图&代码：
<img width="854" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/165642445/707742d1-cc08-46f2-8245-5c29157c1674">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
有更详细的信息吗

可以使用http://jimureport.com/
