### ISSUE TITLE
复杂一点点的cgreport解析异常

### ISSUE THREAD

**Issue by flycatony** [jeecgboot/jeecg-boot#6066]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
1、查询正常，但cgreport解析不了，提示”解析失败，SQL语法错误.“。
2、查询匹配方式和boot2的不统一如何设定？boot2的是【不输入*】匹配，但JPOP【必须输入*】
##### 截图&代码：

select id,calendar_code,description,d.shift_ids,shift_descriptions,shift_per_day,time_per_shift,um,effective_time,expires_time,remark from base.base_calendar c ,
(SELECT GROUP_CONCAT(s.description) as shift_descriptions,GROUP_CONCAT(s.description) as shift_ids,cs.calendar_id  from base.base_calendar_shift cs,base.base_shift s WHERE cs.shift_id=s.id GROUP BY cs.calendar_id) d 
WHERE c.id=d.calendar_id and c.tenant_id='${tenantId}'

![查询日历](https://github.com/jeecgboot/jeecg-boot/assets/61395677/1cdc848e-fd8c-4391-a994-f5a8067cc608)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue2的前端不支持 最新版的后端，目前只支持到3.4.3
你这么用遇到的问题，我们无法判断是版本兼容问题还是功能问题
