### ISSUE TITLE
微服务情况下怎么进行分库！

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6067]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在微服务模式下，因为token校验以及权限校验（shiro）的操作都是在jeecg-boot-base-core这个模块下完成的，如果我自己创建了个微服务想token校验和权限校验那就必须要引入jeecg-boot-base-core这个模块才行，但是现在我自己创建了个微服务使用的是另一个自定义的数据库而不是jeecg提供的jeecg-boot数据库了那就不能引入jeecg-boot-base-core这个模块，我自己建的微服务连接的我自己新建的一个数据库怎么做token校验

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/springcloud/dev/datasource.html
