### ISSUE TITLE
使用代码生成器生成树的结构，批量删除时报错

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6068]
##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
使用代码生成器生成树的结构，批量删除时报错，在不展开树结构一次性选择所有，进行批量删除就报错

##### 截图&代码：
![微信图片_20240402102839](https://github.com/jeecgboot/jeecg-boot/assets/132029411/de0ab04c-a0db-4c64-957c-c8848e030b34)

![微信图片_20240402102950](https://github.com/jeecgboot/jeecg-boot/assets/132029411/c6418ad7-ddbc-47a0-a2d8-ad93602af061)

![微信图片_20240402102952](https://github.com/jeecgboot/jeecg-boot/assets/132029411/48664136-e8ff-4db5-bd38-12eedd9051e0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
已修复，下个版本发布
