### ISSUE TITLE
系统角色在点击编辑后再点击详情，关闭详情页面后，会出现空白编辑页面

### ISSUE THREAD

**Issue by zhujiaqizjq** [jeecgboot/jeecg-boot#6069]
##### 版本号：
V3.6.3 AI版本

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
系统角色在点击编辑后再点击详情，关闭详情页面后，会出现空白编辑页面

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/46023839/bc94dc93-9eb1-484d-a21c-f614448e3e7e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by 1298191366** [comment]
问题未复现，我看你一下出来两个弹窗，请问是如何出现的，是不是你自己修改的？
![2](https://github.com/jeecgboot/jeecg-boot/assets/30997828/b8198a78-9c7e-419d-a7a1-b2d9b734738b)

**Comment by zhujiaqizjq** [comment]
不是自己修改的。


复现步骤如下：
1.进入系统后选择‘系统角色’管理页面
2.点击任意角色的‘编辑’按钮，然后关闭编辑弹窗
3.再点击角色的‘详情’按钮，关闭详情弹窗时会出现上述情况




只是一个脾气好的蓝孩子
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeecgboot/jeecg-boot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月22日(星期一) 上午10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeecgboot/jeecg-boot] 系统角色在点击编辑后再点击详情，关闭详情页面后，会出现空白编辑页面 (Issue #6069)





 
问题未复现，我看你一下出来两个弹窗，请问是如何出现的，是不是你自己修改的？
 2.gif (view on web)

**Comment by 1298191366** [comment]
方便的话录制一下视屏，我这复现不出来，无法进行修改
