### ISSUE TITLE
角色功能报错，列表查询报错。

### ISSUE THREAD

**Issue by xizhuangchui** [jeecgboot/jeecg-boot#6070]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
角色功能报错，列表查询报错。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/77326573/2fd54154-617a-4e47-8232-130b79d14289)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级druid版本导致的，你按照下面的pr修复代码

https://github.com/jeecgboot/jeecg-boot/commit/ab49983759c71092910070e57838dd9bfa42e427

**Comment by fireinjava** [comment]
<img width="1242" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/5036983/c3068813-64ae-4c9c-8b41-0294dcf253d5">
