### ISSUE TITLE
在public命名空间中新加的配置没生效（文件上传大小限制），怎么能让这里配置的生效？

### ISSUE THREAD

**Issue by oujibakei** [jeecgboot/jeecg-boot#6075]
##### 版本号：
jeecg-boot v3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
在public命名空间中新加的配置没生效（文件上传大小限制），怎么能让这里配置的生效？
##### 截图&代码：

![issue截图](https://github.com/jeecgboot/jeecg-boot/assets/46774700/2f42f8b6-8075-44e9-b748-6f50b475b8d1)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你得看你怎么配置的，应该是配置不对

**Comment by oujibakei** [comment]
这能咋配置呀，就是在public命名空间里添加的配置文件，在我前边贴的图里引用的，但是实际效果就是没生效，你咋还给关掉了呢，回答也没结束呀，你如果觉得配置的不对，你给贴个图看看怎么样是生效的 ，我好参考一下呀
