### ISSUE TITLE
每次调用接口jwtTokenRefresh，校验token生效后，不刷新过期时间问题

### ISSUE THREAD

**Issue by chenhengeng** [jeecgboot/jeecg-boot#6076]
版本号：3.6.3

前端版本：vue3版

问题描述：
每次调用接口jwtTokenRefresh，校验token生效后，没有刷新过期时间问题，导致我设的token失效是4小时。到4小时中我一直在用，到4小时，突然就断了。看到jwtTokenRefresh方法 本来是包含，token没有过期，刷新过期时间的操作的，也就是只要我一直操作，就不会过期。但是看到2019年给代码注释掉了。想问一下注释掉处于什么考虑呢，频繁刷redis的token过期时间会有什么问题吗。或者说，对于我的一直请假接口，永远token不过期的需求。这边解决方案是什么呢

截图&代码：
![未命名1712122513](https://github.com/jeecgboot/jeecg-boot/assets/51589516/3372b902-5dc9-489c-8915-d89727b830c0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
操作中不过期这个功能是好使的

**Comment by chenhengeng** [comment]
我是这样操作的 把redis用户过期时间设置的很小  比如30秒 。然后我在页面端一直在点击查询。很快30秒或1分钟，token就过期了 跳回到了登录。我用的是我在你们官网下载的国内版本3.6.3

**Comment by chenhengeng** [comment]
问题为什么关闭了呀，你们代码这块我觉得真的有问题。因为我的现象是这样的

**Comment by zhangdaiscott** [comment]
再确认下
##### 版本号：

##### 分支： master？还是springboot3?


##### 前端版本: vue3版？还是 vue2版？

**Comment by chenhengeng** [comment]
版本号：3.6.3
前端版本：vue3版

**Comment by zhangdaiscott** [comment]
分支

**Comment by chenhengeng** [comment]
master

**Comment by chenhengeng** [comment]
确实没有问题
