### ISSUE TITLE
业务和数据服务分库后产生的问题

### ISSUE THREAD

**Issue by lianxidaqiang** [jeecgboot/jeecg-boot#6079]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
系统和业务分库后，调用数据字典下拉项获取接口的时候（/sys/dict/getDictItems/{dictCode}）会报错，因为这个字典数据表是存在于业务库里的，在system这个服务连接的数据库里找不到这个业务数据表，请问这个该如何解决

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
最新版字典注解支持指定数据源
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/aa28566d-abba-4988-8bea-078b2444b437)
