### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by etn0tw** [jeecgboot/jeecg-boot#6080]
##### 版本号：
jeecg-boot 3.5.1|last

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
登录时 后端报错,我是通过docker启动的 前后端。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/66959925/9ac80d4b-2996-447e-b677-8d1dc16327c7)

"操作失败，\n### Error querying database.  Cause: java.sql.SQLSyntaxErrorException: Unknown column 'post' in 'field list'\n### The error may exist in org/jeecg/modules/system/mapper/SysUserMapper.java (best guess)\n### The error may involve defaultParameterMap\n### The error occurred while setting parameters\n### SQL: SELECT id, username, realname, password, salt, avatar, birthday, sex, email, phone, org_code, login_tenant_id, status, del_flag, work_no, post, telephone, create_by, create_time, update_by, update_time, activiti_sync, user_identity, depart_ids, client_id, bpm_status FROM sys_user WHERE del_flag = 0 AND (username = ?)\n### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'post' in 'field list'\n; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'post' in 'field list'"

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
错误的意思少字段

**Comment by etn0tw** [comment]
我是使用docker 启动的后台程序，没有做过任何数据库操作，少字段 不应该是程序写的有问题吗？

**Comment by etn0tw** [comment]
解决方案：手动操作数据库 在sys_user表中添加post字段即可。
![image](https://github.com/jeecgboot/jeecg-boot/assets/66959925/57479669-2335-4a40-a463-8d1a84312d72)
