### ISSUE TITLE
拦截器放开接口校验后，＠RequiresPermissions　注解校验权限失败

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecg-boot#6087]
##### 截图&代码：
![7680436413e82d3d7f67c784996ff73](https://github.com/jeecgboot/jeecg-boot/assets/128006839/4d138ddd-c677-4d9e-b2b3-abd993a549ac)
![542af0eeeb729bb6cabe1dfd399dcd9](https://github.com/jeecgboot/jeecg-boot/assets/128006839/5da6c8f9-736b-42b2-accb-326d9d6691e5)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
啥意思

**Comment by cym1231** [comment]
> 啥意思
额不清楚么？ 就是 3.6.3的后端  我假设一个接口的路径是/xx/xx/getlist 接口配置注解@RequiresPermissions("xx:xx:getlist ") 然后我把这个路径配置在shiroconfig里 这个时候请求这个接口会出现上面图2的报错 说我没有xx:xx:getlist的权限标识  但是如果我把shiroconfig的路径配置去掉 或者去掉接口上的注解@RequiresPermissions 就没有问题

**Comment by cym1231** [comment]
> 啥意思

类似 #5147 这种 但是我很明确这个权限是存在的 并且已经授权过了

**Comment by cym1231** [comment]
> 啥意思

老哥查了一下，得到的结果是因为我们框架自定义了一个jwt拦截器 这个时候  自定义的拦截器和shiro自带拦截器是平级的，会导致走jwt拦截器通过了 但是同时走shiro自带拦截器就失败了所以这块需要老哥指点下应该如何调整。我参考的文档是：https://zhuanlan.zhihu.com/p/29161098

**Comment by cym1231** [comment]
> 啥意思

老哥查了一下，得到的结果是因为我们框架自定义了一个jwt拦截器 这个时候  自定义的拦截器和shiro自带拦截器是平级的，会导致走jwt拦截器通过了 但是同时走shiro自带拦截器就失败了所以这块需要老哥指点下应该如何调整。我参考的文档是：https://zhuanlan.zhihu.com/p/29161098

**Comment by lhj6167** [comment]
请问有后续了吗。我也碰到这个问题，权限菜单添加好了，角色也授权好了，前后端项目也都重启了，也是增删改权限不生效，F12抓包查看当前登陆用户是有这个权限的，但是后端报错
Subject does not have permission [setting:lite_customize_report_category:edit]
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [setting:lite_customize_report_category:edit]

**Comment by cym1231** [comment]
> 请问有后续了吗。我也碰到这个问题，权限菜单添加好了，角色也授权好了，前后端项目也都重启了，也是增删改权限不生效，F12抓包查看当前登陆用户是有这个权限的，但是后端报错 Subject does not have permission [setting:lite_customize_report_category:edit] org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [setting:lite_customize_report_category:edit]

官方展示没提供解决方案 我只能说另外写一个不需要鉴权控制层 来提供给三方使用

**Comment by zhangdaiscott** [comment]
该现象确实存在，但是原因为使用不当，同时配置了免登录和权限校验。因为＠RequiresPermissions注解会获取当前认证信息来判断是否满足访问权限，而该接口又配置了免登录，最终结果为了不携带认证信息访问了需要获取认证信息的接口，＠RequiresPermissions逻辑运行报错
