### ISSUE TITLE
java增强无效，新增增强是没问题的，但无法触发实现类的执行。

### ISSUE THREAD

**Issue by colorful3** [jeecgboot/jeecg-boot#6089]
##### 版本号：
3.6.3 3.6.2 都试了

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
java增强无效，不可用

##### 截图&代码：

配置：
<img width="1287" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/29156058/8ed3c89c-72d6-4ed4-9475-57b44cdb9369">

增强实现：
<img width="829" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/29156058/a205a2be-4809-4da0-aba0-e93bbb68024f">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by colorful3** [comment]
cr 是啥意思？

**Comment by hoperunChen** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/e35110c0-9335-4c09-8846-c5481f794a1a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/13013558/ca202c2e-6307-4c68-8b9c-bd918e58edfb)
未复现，请检查下日志，是不是有报错？
