### ISSUE TITLE
角色管理报错：select alway true condition not allow 

### ISSUE THREAD

**Issue by wangqian0628** [jeecgboot/jeecg-boot#6090]
##### 问题描述：角色管理点击后报错

"操作失败，\n### Error querying database.  Cause: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.22, select alway true condition not allow : SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1\n### The error may exist in URL [jar:file:/home/jeecg-boot/jeecg-system-cloud-start-3.6.3.jar!/BOOT-INF/lib/jeecg-system-biz-3.6.3.jar!/org/jeecg/modules/system/mapper/xml/SysRoleMapper.xml]\n### The error may involve org.jeecg.modules.system.mapper.SysRoleMapper.listAllSysRole_mpCount\n### The error occurred while executing a query\n### SQL: SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1\n### Cause: java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.22, select alway true condition not allow : SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1\n; uncategorized SQLException; SQL state [null]; error code [0]; sql injection violation, dbType mysql, druid-version 1.2.22, select alway true condition not allow : SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1; nested exception is java.sql.SQLException: sql injection violation, dbType mysql, druid-version 1.2.22, select alway true condition not allow : SELECT COUNT(*) AS total FROM sys_role WHERE 1 = 1"

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/16589026/5f15898d-5679-471e-908e-1a6a3d60bc8f)

**Comment by zhangdaiscott** [comment]
代码更新到最新就好了

或者按照这个处理
https://github.com/jeecgboot/jeecg-boot/issues/6070
