### ISSUE TITLE
前台存在SSRF

### ISSUE THREAD

**Issue by crisprss** [jeecgboot/jeecg-boot#6093]
##### 版本号：
3.6.3 最新版

##### 问题描述：
/jmreport/download/image该接口存在SSRF漏洞，攻击者可以利⽤该漏洞使服务器端向攻击者构造的
任意域发出请求

此处不需要登陆和token，未授权进行SSRF
##### 截图&代码：
当该路径不存在时，将可控参传入到e.a方法中
![image](https://github.com/jeecgboot/jeecg-boot/assets/55953931/c1dc5cd9-8979-478d-b31a-a3e4ee8909bd)

最后跟进传入到org.springframework.web.client.RestTemplate#doExecute

![image](https://github.com/jeecgboot/jeecg-boot/assets/55953931/545f1c37-1cdc-4fe0-8fee-a61641fdf372)

这里对传入参数做出限制，可以通过?a.png来绕过限制实现SSRF

![image](https://github.com/jeecgboot/jeecg-boot/assets/55953931/9cc86ee6-5ff2-4557-b25a-c5e67c5ecabe)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by crisprss** [comment]
> cr

cr是什么意思，需要确认吗？

**Comment by crisprss** [comment]
> cr

请问有跟进吗

**Comment by zhangdaiscott** [comment]
积木报表的问题，下个版本修复

**Comment by Drun1baby** [comment]
我也挖了这个，被 CNVD 当成垃圾洞丢到垃圾桶里了
