### ISSUE TITLE
Online表单开发功能运行异常：clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=2e186efb' does not provide an export named 'default' (at useCgformList-423282b7.mjs?v=2e186efb:36:8)

### ISSUE THREAD

**Issue by LZW-Andrewlu** [jeecgboot/jeecg-boot#6095]
##### 版本号：V3.6.3
node: V18.16.1
pnpm: 8.15.6

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
运行Online表单开发界面时出现：
```
SyntaxError: The requested module '/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=2e186efb' does not provide an export named 'default' (at useCgformList-423282b7.mjs?v=2e186efb:36:8)
```
**其他重要信息：**
同一台电脑，全新拉取官方代码，编译运行正常。
对比自己代码与官方代码，配置完全一致，仅修改增删vue相关代码。
**编译后代码差异对比：**
- 正常运行的编译后代码（useCgformList）：
`import __vite__cjsImport7_clipboard from "/node_modules/.vite/deps/clipboard.js?v=7d32ccba"; const $ = __vite__cjsImport7_clipboard.__esModule ? __vite__cjsImport7_clipboard.default : __vite__cjsImport7_clipboard;`
- 异常运行的编译后代码（useCgformList）：
`import $ from "/node_modules/.pnpm/clipboard@2.0.11/node_modules/clipboard/dist/clipboard.js?v=2e186efb";`

以上对比可以看出，应当是编译时针对原始语法：`import $ from "clipboard";` 的编译结果不同导致的。需要深入研究一下为什么同样的环境会解释出不同的编译语法。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/120624457/c9b33679-6b19-47db-9c58-13440cfc6fe0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
清楚vite缓存试试

**Comment by LZW-Andrewlu** [comment]
已经多次尝试清理npm 缓存，删除node_module目录等操作，未解决问题。
对比正常运行代码编译目录与 异常目录， 发现正常代码目录在.vite缓存目录中 存在clipboard.js缓存文件，且编译的代码中引用的是.vite目录路径，
而异常运行代码中，.vite目录中不存在clipboard.js缓存文件，编译后代码引用的是node_module目录下的clipboard模块。
这里存在差异。暂未找到是什么配置引起了这种差异 。
![image](https://github.com/jeecgboot/jeecg-boot/assets/120624457/7b307d85-ae72-47f3-ac70-54362c501362)

**Comment by LZW-Andrewlu** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/120624457/3e2ea48b-d485-4053-b5fb-6381b026c963)
折腾一下午，定位问题，找解决办法，原因基本定位，vite进行预构建时漏掉了clipboard包，感觉像是突然抽风了。

**Comment by LZW-Andrewlu** [comment]
进一步测试： 
1. 注释掉include:['clipboard'],  clipboard.js 在.vite缓存中会立即消失，且页面重新报错。
2. 强制在App.vue中 引入clipboard ：import 'clipboard'; 也会触发生成缓存，因此也可以作为一个解决方案。

问题猜测：由于@jeecg/online 是被排除在预构建范围外的， 在没有其他地方提前引用clipboard代码时，临时加载显示online中的功能，不会触发依赖文件预构建。必须在明确的非排除代码外显式import, 才会生成预构建代码。

最后：Vite的依赖预构建是一个启发式行为，并不总是可靠的，因此出现问题时的最佳解决办法就是添加include声明。
![image](https://github.com/jeecgboot/jeecg-boot/assets/120624457/8445472a-6330-41b0-9d9e-08a54ae6535b)

**Comment by zhangdaiscott** [comment]
点击这个清除缓存
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/74588d3e-f9e4-491b-9b3b-f9e847b0d225)

**Comment by LZW-Andrewlu** [comment]
> 点击这个清除缓存 ![image](https://private-user-images.githubusercontent.com/3162115/321070804-74588d3e-f9e4-491b-9b3b-f9e847b0d225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTkwODIsIm5iZiI6MTcxMjcxODc4MiwicGF0aCI6Ii8zMTYyMTE1LzMyMTA3MDgwNC03NDU4OGQzZS1mOWU0LTQ5MWItOWIzYi1mOWU4NDdiMGQyMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTBUMDMxMzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlM2ZlY2NiNTFiZGZhZDIwMDVkN2E3ZWY0YzkyY2I5OTRjNjJlYjZlM2QxZDllM2FhOWE3Yjc5Y2FiOWM3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SqH05nmrSfVHO0Eo9KYrlaZaNfrr8GdTvbyZOXVXHuI)

问题已经解决，清理缓存并不能解决问题。 原因应该是配置的optimizeDeps中的 exclude[] 项引起的。 clipboard的引入时机非常靠后，只在jeecg包里边，而优化选项又把jeecg包排除了，因此导致运行时并没有生成clipboard库的预构建包。

**Comment by zhangdaiscott** [comment]
好的
