### ISSUE TITLE
Jeecg访问页面太慢一直再转

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6097]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
前后端启动成功后，访问页面太慢了，一直再转，大概要过二十几秒才能出来登录页面，这个能不能优化一下，感觉是jeecg的通病

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vite首屏慢，第二次就快了

**Comment by chenhengeng** [comment]
指的是每次重启后端服务的首屏 还是前端服务的首屏呢

**Comment by zhangdaiscott** [comment]
用户第一次访问系统
