### ISSUE TITLE
同步数据库，导入数据库表提示没有权限，请联系管理员授权

### ISSUE THREAD

**Issue by ll17673878103** [jeecgboot/jeecg-boot#6099]
版本号：
3.4.3

前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
在线开发功能中的online表单开发，我新增了一张表，然后同步数据库没有权限导入数据库表也是没有权限

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/120300126/3748a24c-9bc9-4b66-8b04-efb68ea65430)
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://jeecg.com/doc/qa
4
