### ISSUE TITLE
微服务模式下，生产环境禁用swagger

### ISSUE THREAD

**Issue by chenhengeng** [jeecgboot/jeecg-boot#6100]
##### 问题描述：

微服务模式下，生产环境直接访问gateway路径 会暴露swagger的接口列表信息。
 怎么能像非微服务，在Swagger2Config加@Profile({"dev","test"})，即可禁用

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zj

**Comment by zhangdaiscott** [comment]
新版发布了，请验证
