### ISSUE TITLE
Jeecg 第一次访问页面速度很慢

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6102]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：

Jeecg 第一次访问页面速度很慢，一直在转圈要转二十多秒才能到登录页面，能不能优化一下啊
##### 截图&代码：

![1712732553135](https://github.com/jeecgboot/jeecg-boot/assets/132029411/48892a70-dd86-40e9-9943-a8cf9f66b062)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vite的机制
