### ISSUE TITLE
com.unfbx.chatgpt.OpenAiStreamClient没有初始化

### ISSUE THREAD

**Issue by liangbingbj** [jeecgboot/jeecg-boot#6104]
##### 版本号：
3.6.3（发布日期：2024-03-11）

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
chatgpt,配置后，问答报错：错误如下
ERROR o.jeecg.common.exception.JeecgBootExceptionHandler:78 - No qualifying bean of type 'com.unfbx.chatgpt.OpenAiStreamClient' available
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.unfbx.chatgpt.OpenAiStreamClient' available

##### 截图&代码：
![Uploading [chatgpt问答报错.png…]()]
![chatgpt问答报错](https://github.com/jeecgboot/jeecg-boot/assets/78679275/e9c13f72-7486-4447-a681-0648e9e5aa0c)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
说明配置不对
参考https://help.jeecg.com/java/chatgpt.html

**Comment by liangbingbj** [comment]
已解决，多谢



***@***.***
 
发件人： JEECG
发送时间： 2024-04-11 12:54
收件人： jeecgboot/jeecg-boot
抄送： liangbingbj; Author
主题： Re: [jeecgboot/jeecg-boot] com.unfbx.chatgpt.OpenAiStreamClient没有初始化 (Issue #6104)
说明配置不对
参考https://help.jeecg.com/java/chatgpt.html
