### ISSUE TITLE
SQL注入检测逻辑影响业务

### ISSUE THREAD

**Issue by testnet0** [jeecgboot/jeecg-boot#6105]
##### 版本号：
V3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
前端代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/18673513/e33ee4e7-2a93-4209-9b1e-bc2505b7f450)
唯一值校验时，会提示有SQL注入风险
![image](https://github.com/jeecgboot/jeecg-boot/assets/18673513/5886c80c-0cf0-44ca-aa05-27425fde6cb4)
http://localhost:3100/jeecgboot/sys/duplicate/check?tableName=abc&fieldName=a&fieldVal=123
这里测试发现只要是字段名包含了表名关键字就不行，比如表名是abc，字段名不能为a，这里是否不合理？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
我们确认下  cr

**Comment by zhangdaiscott** [comment]
已经提交
