### ISSUE TITLE
无法下载聊天插件 ，下载时会报错

### ISSUE THREAD

**Issue by tentechtop** [jeecgboot/jeecg-boot#6108]
##### 问题描述：无法下载该插件 ，下载时会报错

<dependency>
			<groupId>org.p3framework</groupId>
			<artifactId>jeecg-p3-biz-chat</artifactId>
			<version>1.0.0</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>

[WARNING] Failed to download maven-metadata-snapshots.xml [https://maven.aliyun.com/nexus/content/groups/public/]
[WARNING] Failed to download maven-metadata-alimaven.xml [http://maven.aliyun.com/nexus/content/groups/public/]
[WARNING] Failed to download maven-metadata-activiti-repos2.xml [https://app.camunda.com/nexus/content/groups/public/]
[WARNING] Failed to download maven-metadata-springsource-repos.xml [http://repo.spring.io/release/]
[WARNING] Failed to download maven-metadata-rdc-snapshots.xml [https://packages.aliyun.com/maven/repository/2362379-snapshot-3UlBPW/]
[WARNING] Failed to download maven-metadata-central-repos1.xml [http://repo1.maven.org/maven2/]
[WARNING] Failed to download maven-metadata-central-repos.xml [http://repo.maven.apache.org/maven2/]
[WARNING] Failed to download maven-metadata-jeecg-snapshots.xml [https://oss.sonatype.org/content/repositories/snapshots/]
[WARNING] Failed to download maven-metadata-activiti-repos.xml [https://maven.alfresco.com/nexus/content/groups/public/]
[WARNING] Could not transfer metadata org.p3framework:jeecg-p3-pom:1.0-SNAPSHOT/maven-metadata.xml from/to springsource-repos (http://repo.spring.io/release/): transfer failed for http://repo.spring.io/release/org/p3framework/jeecg-p3-pom/1.0-SNAPSHOT/maven-metadata.xml, status: 405 Not Allowed
[WARNING] Could not transfer metadata org.p3framework:jeecg-p3-pom:1.0-SNAPSHOT/maven-metadata.xml from/to central-repos (http://repo.maven.apache.org/maven2): transfer failed for http://repo.maven.apache.org/maven2/org/p3framework/jeecg-p3-pom/1.0-SNAPSHOT/maven-metadata.xml, status: 501 HTTPS Required
[WARNING] Could not transfer metadata org.p3framework:jeecg-p3-pom:1.0-SNAPSHOT/maven-metadata.xml from/to central-repos1 (http://repo1.maven.org/maven2/): transfer failed for http://repo1.maven.org/maven2/org/p3framework/jeecg-p3-pom/1.0-SNAPSHOT/maven-metadata.xml, status: 501 HTTPS Required
[WARNING] Failed to download jeecg-p3-pom-1.0-SNAPSHOT.pom [https://maven.aliyun.com/nexus/content/groups/public/]
[WARNING] Failed to download jeecg-p3-pom-1.0-SNAPSHOT.pom [https://packages.aliyun.com/maven/repository/2362379-snapshot-3UlBPW/]
[WARNING] Failed to download jeecg-p3-pom-1.0-SNAPSHOT.pom [http://maven.aliyun.com/nexus/content/groups/public/]
[WARNING] Failed to download jeecg-p3-pom-1.0-SNAPSHOT.pom [https://app.camunda.com/nexus/content/groups/public/]

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by tentechtop** [comment]
无法下载聊天插件 ，下载时会报错

**Comment by zhangdaiscott** [comment]
没有聊天插件提供
