### ISSUE TITLE
postgresql数据库在Online表单同步数据库的时候，选择普通同步也会导致原表数据丢失。

### ISSUE THREAD

**Issue by fuyongpingzoomkey** [jeecgboot/jeecg-boot#6109]
##### 版本号：
3.5.1

##### 前端版本：vue3版？还是 vue2版？
VUE2版本

##### 问题描述：
postgresql数据库在Online表单同步数据库的时候，选择普通同步也会导致原表数据丢失。

##### 截图&代码：
原因是，判断表是否存在，指定了模式，如果Oracle或者pg数据库新建其他模式会导致，代码判断表不存在，新建的时候，会删除原表。
如下所示：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35991617/c8584d07-193b-4649-8c59-6a6d6f51dc90)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
scott

**Comment by hoperunChen** [comment]
已修复，待新版本发布。
