### ISSUE TITLE
大屏设计器里面，文本框的内容不支持sql数据处理解析吗？

### ISSUE THREAD

**Issue by luorichenying** [jeecgboot/jeecg-boot#6110]
##### 版本号：
线上操作

##### 问题描述：
在新的一个大屏设计器里面，加入文本框之后，想在里面放一个可以更新变化的sql查询值，配置完毕后，刷新发现大屏上没有显示数据，这个是什么问题？
是不支持的原因吗？如果是的话，除了文本框之外，还有那些小的模块也是不支持的？

##### 截图&代码：
<img width="1009" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/165642445/2a84364b-6c5c-4c6d-89f8-e56040a7dafd">
<img width="594" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/165642445/e3fdf7c8-0fad-4bbb-bd48-0380ddee8404">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by lsqGitHub716** [comment]
你试试这种把数据as一个具体属性count(*) as total
