### ISSUE TITLE
单体服务切换微服务之后，原本单体服务的几个模块需要删除吗

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6112]
##### 截图&代码：
<img width="230" alt="1712886621007" src="https://github.com/jeecgboot/jeecg-boot/assets/48941638/0a7d9c64-9584-428f-be79-c371ca20f613">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/springcloud/switchcloud/monomer.html
不用删
