### ISSUE TITLE
online表单生成代码， 关联表生成vue3模板里的 *.data.ts 这个文件会有报错

### ISSUE THREAD

**Issue by mfh19891114** [jeecgboot/jeecg-boot#6113]
##### 版本号：

3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：

online表单开发 关联表生成vue3模板里的 *.data.ts 这个文件会有报错

##### 截图&代码：
<img width="1353" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/24469962/6bb873f6-18f0-4d8b-a2c3-23cdd04008bf">

**Comment by mfh19891114** [comment]
尝试改了下，估计是这个判断有问题，字段取错了，如下：
文件：jeecg-module-system/jeecg-system-biz/src/main/resources/jeecg/code-template-online/jvxe/onetomany/java/${bussiPackage}/${entityPackage}/vue3/${entityName}__data.tsi
第786行：
<#if (subCol.isShowList =='Y' && subCol.fieldName !='id' && po.fieldName !='delFlag')>

po.fieldName !='delFlag'  这个应该是 subCol.fieldName !='delFlag' 这样写吧

**Comment by zhangdaiscott** [comment]
ws

**Comment by mfh19891114** [comment]
> ws

啥意思？

**Comment by 1298191366** [comment]
已修复，待新版本发布
