### ISSUE TITLE
表单添加关联记录控件 将用户的权限 去掉模型开发模块 结果:无法查看表单中的 关联记录 控件内容 提示无无权限

### ISSUE THREAD

**Issue by 78739749haiyang** [jeecgboot/jeecg-boot#6117]
##### 问题描述：
问题复现条件:
1、表单添加关联记录控件
2、将用户的权限 去掉模型开发模块

结果:无法查看表单中的 关联记录 控件内容

##### 截图&代码：

![3](https://github.com/jeecgboot/jeecg-boot/assets/98626116/d0b25839-fbc9-45e4-bdc8-0c722db8a0c4)
![222](https://github.com/jeecgboot/jeecg-boot/assets/98626116/0ca7dd2a-32fb-4a6b-aa66-8ea1e179c335)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
请参考 #5897
