### ISSUE TITLE
后台启动的时候不停的输出日志，不知道是咋回事

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6119]
##### 版本号：

3.6.2
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
后台启动的时候不停的输出日志，不知道是咋回事

##### 截图&代码：
![1712906770742](https://github.com/jeecgboot/jeecg-boot/assets/132029411/ecb7f317-41ea-4fda-a8b9-8c24c705d0f0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不太清楚，百度看看
