### ISSUE TITLE
Onlineb表单开发，主表为ERP模式，当用户没有【Online表单开发】页面的权限时，用户无权查看从表的数据

### ISSUE THREAD

**Issue by HolaFish** [jeecgboot/jeecg-boot#6124]
##### 问题描述：
Onlineb表单开发，主表为ERP模式，当用户没有【Online表单开发】页面的权限时，用户无权查看从表的数据

##### 截图&代码：
以自带的的**测试订单主表**为例：
* 当没有【Online表单页面】权限时：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/5bafb57e-3537-40e1-a3ee-238f614eab6a)
选中主表记录，查看从表记录，效果如下：
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/e5d33f2b-30b2-4588-9827-e26bc35e590c)
系统提示无权查看。

* 当为该用户授予【Online表单开发】页面的权限后，功能正常
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/6152d5de-5e39-4246-8b1d-133077bded94)
![image](https://github.com/jeecgboot/jeecg-boot/assets/35533961/bcf07ff9-b709-438d-a2e2-9e6f6f8c3c59)

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/issues/5897

**Comment by liaozhiyang** [comment]
已解决，下一版本发布

**Comment by huanglf1024** [comment]
当前最新版本： 3.7.3（发布日期：2025-02-10）还是这样子呀，没有Online表单页面页面时，主表为主表(内嵌)模式，展开看不了数据。

 
![Image](https://github.com/user-attachments/assets/cbd609c4-f3a0-47e5-9347-6637a8e9bd52)
