### ISSUE TITLE
根据父表id查询字表数据不生效

### ISSUE THREAD

**Issue by AiTaiShan** [jeecgboot/jeecg-boot#6125]
##### 版本号：
2.2.0

##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
QueryGenerator.initQueryWrapper()  根据附表id 查询不生效

##### 截图&代码：

![1713170655202(1)](https://github.com/jeecgboot/jeecg-boot/assets/125786180/35ad48df-7aef-4b90-a6a8-f70940d215d7)

![image](https://github.com/jeecgboot/jeecg-boot/assets/125786180/901833a3-6262-4397-98c3-8195e85a0315)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
版本太老了，请自己解决吧
