### ISSUE TITLE
仪表盘设计器 数据集配置 使用SQL类型 SQL解析时没有权限

### ISSUE THREAD

**Issue by zj14261535** [jeecgboot/jeecg-boot#6126]
版本号：
3.6.3

前端版本：
vue3版

问题描述：
仪表盘设计器 数据集配置 使用SQL类型 SQL解析时没有权限

截图&代码：
![123](https://github.com/jeecgboot/jeecg-boot/assets/17996423/2b26c006-fb84-4a52-9305-6cf0290ada94)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
如果你用的不是admin账号，可以给用户的角色授权

https://jeecg.com/doc/qa
4
