### ISSUE TITLE
系统的缓存好难清除；

### ISSUE THREAD

**Issue by RacingK93** [jeecgboot/jeecg-boot#6128]
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/18101484/a58685bb-8564-4a7f-a81d-760947c33bfb)

这一条就是清除不掉；

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/df42aaa3-0187-4138-9301-a59c2343cf59)
