### ISSUE TITLE
spring3 分支的 acurator/httptrace 报错404

### ISSUE THREAD

**Issue by travisbikkle** [jeecgboot/jeecg-boot#6130]
##### 版本号：
spring3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
spring3 分支的 acurator/httptrace 报错404

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/15191577/f761432c-a442-42b0-9b6a-c8664502ba5a)

这个接口改名成 httpexchanges 了

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
shiro拦截器，默认拦截了，不让无token访问

**Comment by travisbikkle** [comment]
> shiro拦截器，默认拦截了，不让无token访问

不是。是spring 3把接口名称改了

**Comment by zhangdaiscott** [comment]
好的
