### ISSUE TITLE
首页配置无效，代码里面限制啦

### ISSUE THREAD

**Issue by hjhcos** [jeecgboot/jeecg-boot#6132]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
首页配置无效，代码里面限制啦，删除首页，使用lambda表达式会存在错误

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/c6773081-5f6c-4343-84c1-708f7981efec)
new LambdaQueryWrapper<SysPermission>().eq(SysPermission::getName,"首页")  代码值可能为空，而且首页不一定有，因为会被删除
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/c47fe78d-d77e-4415-9999-649124757c47)
![image](https://github.com/jeecgboot/jeecg-boot/assets/54499588/fca97905-ab96-401b-a957-1650f1263863)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by hjhcos** [comment]
这个设计互相冲突，必须要有一个菜单叫首页，然后我在【角色管理】--【更多】--【首页配置】设置首页菜单是Online表单开发，这个时候原来得首页页面会存在 并且内容会变化为Online表单开发，这个时候会有两个首页菜单，一个叫首页一个叫Online表单开发，首页页面原来得内容是图表被替换成Online表单开发得内容

**Comment by zhangdaiscott** [comment]
升级到3.6.3，优化了
