### ISSUE TITLE
excel 读取负数异常

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecg-boot#6133]
##### 截图&代码：
图一
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/daf97a49-2bad-483e-99ef-23956a2d2e20)
图二
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/2e6c4b53-0565-4567-a57f-c924cbf8489f)
图三
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/e06907e5-f1bb-463f-9007-b5dee2f6283d)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
@cym1231 已修复，待autopoi更新。 jeecgboot/autopoi#115

**Comment by cym1231** [comment]
> @cym1231 已修复，待autopoi更新。 [jeecgboot/autopoi#115](https://github.com/jeecgboot/autopoi/pull/115)

好的佬 辛苦了佬  所以要等新版本是么？

**Comment by zhangdaiscott** [comment]
升级autopoi到1.4.8版本就好了
```
<dependency>
  <groupId>org.jeecgframework</groupId>
  <artifactId>autopoi-web</artifactId>
  <version>1.4.8</version>
</dependency>
```

**Comment by cym1231** [comment]
> 升级autopoi到1.4.8版本就好了
> 
> ```
> <dependency>
>   <groupId>org.jeecgframework</groupId>
>   <artifactId>autopoi-web</artifactId>
>   <version>1.4.8</version>
> </dependency>
> ```

佬，非常感谢。

**Comment by lmhfq** [comment]
之前我提过，作者说没问题，https://github.com/jeecgboot/autopoi/pull/101
