### ISSUE TITLE
微服务项目新增的模块，调接口时报token失效问题

### ISSUE THREAD

**Issue by sunjianfeng961218** [jeecgboot/jeecg-boot#6134]
##### 截图&代码：
问题截图：
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/3883eec3-7e7d-4e29-9782-550d336a2bbd)
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/5a995640-6423-41ab-88d5-ea701e4c5cf3)
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/82f1d74e-2ca5-4399-ad54-461f376dcd39)

新模块架构图：
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/a56e3e30-299d-4381-bc4c-a4a4cfd0d15b)

jeecg-cloud-erp-start  pom.xml
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/a7820cca-818b-4b00-810d-2468b5cc3967)

启动类
![image](https://github.com/jeecgboot/jeecg-boot/assets/45301981/251e7abc-5e1a-4c6b-a01b-8eff92c07dec)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
本地无法复现所描述问题。
光从问题描述来看，无法直观的看到问题，是否可以将代码上传，提供地址给到测试。
