### ISSUE TITLE
Online表单开发怎么设置ERP（一对多）主题模板？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6135]
##### 问题描述：
我看最新版的主题支持多种，目前我的版本只有一种默认主题。请问是哪里设置没有打开，还是说需要升级一下？

##### 截图&代码：

![(QY}NQ)B7B_VR`U)L8O9QXQ](https://github.com/jeecgboot/jeecg-boot/assets/48941638/09c5f983-a0f7-4de7-beea-e0b01c6f68f4)
![2](https://github.com/jeecgboot/jeecg-boot/assets/48941638/e3b6e8bf-e701-4ef5-ade1-48dfde83da86)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级到最新版就有了
