### ISSUE TITLE
jeecg-boot下拉框搜索组件关键字搜索报错

### ISSUE THREAD

**Issue by fulin-peng-ydxs** [jeecgboot/jeecg-boot#6137]
##### 版本号：
3.6.3

##### 问题描述：
下拉框搜索组件的后端服务，关键字搜索报错，发现动态拼接sql逻辑有问题

##### 截图&代码：
SysDictServiceImpl-->
		//下拉搜索组件 支持传入排序信息 查询排序
		if(oConvertUtils.isNotEmpty(condition) && oConvertUtils.isNotEmpty(keywordSql)){
			filterSql += sqlWhere + sqlAnd + condition + sqlAnd + keywordSql;
		}else if(oConvertUtils.isNotEmpty(condition)){
			filterSql += sqlWhere + sqlAnd + condition;
		**}else if(oConvertUtils.isNotEmpty(keywordSql)){
			filterSql += sqlWhere + sqlAnd + keywordSql;**
		} else if (tableHasWhere){
			filterSql += sqlWhere; 
		}

**Comment by zhangdaiscott** [comment]
cr

**Comment by hoperunChen** [comment]
已解决 #5978 ，请更新到最新版本。
