### ISSUE TITLE
在线表单-js增强-表单api-表单加载事件中对详情事件不起作用

### ISSUE THREAD

**Issue by fulin-peng-ydxs** [jeecgboot/jeecg-boot#6139]
##### 版本号：
3.6.3

##### 问题描述：
在线表单-js增强-表单api-表单加载事件中对由查看数据“详情”的操作引起的表单表单加载事件无效，
只能在新增或编辑操作时才会有作用

##### 截图&代码：
![9899ba29a3876bdc40390c243608927](https://github.com/jeecgboot/jeecg-boot/assets/163669011/7025e250-f8a4-463b-af57-ba5f7a9fe356)

**Comment by zhangdaiscott** [comment]
zy

**Comment by zhangdaiscott** [comment]
详情页面需要吗

**Comment by fulin-peng-ydxs** [comment]
有对应的应用场景，保证新增、编辑、查看的交互一致

**Comment by fulin-peng-ydxs** [comment]
> 详情页面需要吗

有对应的应用场景，保证新增、编辑、查看的交互一致

**Comment by liaozhiyang** [comment]
已经新增，下一版本发布。
