### ISSUE TITLE
RestUtil.post怎么在往请求头里面加参数

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6140]
##### 问题描述：
RestUtil.post怎么在往请求头里面加参数，里面封装了三个api都没看到有往请求头里面塞参数的地方

##### 截图&代码：
` public static JSONObject post(String url, JSONObject variables, JSONObject params) {
        return postNative(url, variables, params).getBody();
    }`
![1713435370227](https://github.com/jeecgboot/jeecg-boot/assets/48941638/e180aa6c-1e11-4ddb-9971-31e2ae96ce09)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/1f05ea38-3a08-4107-9d99-ac95f35d0958)

自己扩展代码
