### ISSUE TITLE
nacos升级2.2.3后，nacos权限控制菜单不见了，密码也无法修改了。

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#6143]
##### 版本号：
jeecgboot3.0

##### 前端版本：vue3版？还是 vue2版？

vue2
##### 问题描述：
nacos升级到2.2.3 后如何开启权限控制或者更改密码一类的

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/f936ae66-4274-4d68-b881-da1894db05ed)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by EightMonth** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/c9ed15f1-c8da-4941-ba7d-11aae0d71f77)

**Comment by chenhengeng** [comment]
看懂你需求了 在这改
![image](https://github.com/jeecgboot/jeecg-boot/assets/51589516/d9dec7ec-db53-4f31-be2c-12d3d8cba240)

**Comment by EightMonth** [comment]
> 这个如果开启鉴权后，jeecgboot后台需要做什么调整么？ @EightMonth

需要配置spring.cloud.nacos.username/password

**Comment by ming820214** [comment]
> > 这个如果开启鉴权后，jeecgboot后台需要做什么调整么？ @EightMonth
> 
> 需要配置spring.cloud.nacos.username/password
spring.cloud.nacos.username/password
如果不加这个会有什么影响么？

**Comment by EightMonth** [comment]
如果nacos既开启了认证，又不配置nacos的用户名密码的话，将会导致服务与nacos之间无法交互，无法注册，也无法获取配置
