### ISSUE TITLE
两个jeecgboot微服务项目 在一个环境中启动2个jeecg-cloud-nacos时，第二个nacos会报错

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#6144]
##### 版本号：

3.0
##### 前端版本：vue3版？还是 vue2版？
vue2

##### 问题描述：
两个jeecgboot微服务项目， 在一个环境中部署，启动2个jeecg-cloud-nacos时，第一个能够正常启动，但是第二个nacos会报错

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/57dafffd-9be1-411d-986a-c909910740a0)
![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/b6a0590a-5c6d-4ee1-a00f-d6a53b606829)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by chenhengeng** [comment]
我之前也遇到过 。我这这么解决的，是因为nacos在PC端启动，会有缓存文件夹，把两个缓存文件夹分隔独立就好了。具体方法如下！！！！！！重写EnvUtil类的getNacosHomenacosHome = Paths.get(System.getProperty("user.home"), "nacos").toString();   变更为getNacosHomenacosHome = Paths.get(System.getProperty("user.home"), "nacos-demo").toString();

**Comment by ming820214** [comment]
@chenhengeng  EnvUtil是哪个类啊？

**Comment by chenhengeng** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/51589516/72696e22-b1cd-4095-804a-16ca56954d00)

**Comment by ming820214** [comment]
> 两套nacos代码）

这个类的源码在哪个位置啊？

**Comment by chenhengeng** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/51589516/0840ec3b-c72a-4e41-a2a1-7398c3cfd8f3)

**Comment by ming820214** [comment]
> ![image](https://private-user-images.githubusercontent.com/51589516/323887996-0840ec3b-c72a-4e41-a2a1-7398c3cfd8f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTU1NzksIm5iZiI6MTcxMzUxNTI3OSwicGF0aCI6Ii81MTU4OTUxNi8zMjM4ODc5OTYtMDg0MGVjM2ItYzcyYS00ZTQxLWEyYTEtNzM5OGMzY2ZkOGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4Mjc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYjUwZmExNjg4MzdhNjRlZjYzNWU3MDBjYmU1YmNmNzliYmM3YmYyMGNhOGNmOWU5NWVkOGY2NDQ5N2Y3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TCroRfEYt4hKHQ2EbgLzsx-bSIQOP7kidCya7SD4zak)

你得意思是每个微服务把这里的getNacosHomenacosHome = Paths.get(System.getProperty("user.home"), "nacos-demo").toString();  “nacos-demo"设置成不同的值就可以是么？

**Comment by chenhengeng** [comment]
对 是这个意思

**Comment by ming820214** [comment]
那可以这么写，就不用复写类了

**Comment by ming820214** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/4c962880-8731-42cb-8331-ef849f712883)

**Comment by ming820214** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/8438712/e2cb4a33-2353-4a4e-9aba-bde4bc3ef91a)

**Comment by chenhengeng** [comment]
我记得我当时跟踪过源码 改这块 当时是没生效 你可以试试 生效最好了

**Comment by ming820214** [comment]
> 我记得我当时跟踪过源码 改这块 当时是没生效 你可以试试 生效最好了
谢谢，我试试！
再多问一下，你nacos升级到2.2.3之后，权限控制和nacos用户密码修改这一块，你是怎么做的？

**Comment by chenhengeng** [comment]
就在这里修改密码呀
但是我看jeecgboot官方说不要开启权限认证，会有调用的问题。但是我开启了权限 一直在用 也没有发现什么问题。
不过生产环境nacos也没有暴露在公网。用的跳板机，登录nacos页面
![Uploading image.png…]()

**Comment by ming820214** [comment]
> 我记得我当时跟踪过源码 改这块 当时是没生效 你可以试试 生效最好了

我这边按照我说的System.setProperty("nacos.home","test"); 用这个方法就好使了，不用重写EvnUtil类了。
