### ISSUE TITLE
springboot3分支，online表单开页面，导入数据库表功能无法使用

### ISSUE THREAD

**Issue by siyuanli-49** [jeecgboot/jeecg-boot#6146]
##### 版本号：
springboot3分支3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
1、springboot3分支，online表单开发页面，点击“导入数据库表”按钮，弹窗出来无数据，并且打开控制台连接提示404错误。尝试jdk为21、17版本。
2、切换主分支，online表单开发页面，点击“导入数据库表”按钮，弹窗出来有数据。

上述1、2步骤，其它配置未变，只有分支切换。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by siyuanli-49** [comment]
补充图片
![image](https://github.com/jeecgboot/jeecg-boot/assets/50580795/3cd6a500-3dd8-4cb1-acd8-2b9e55bf1604)

**Comment by zhangdaiscott** [comment]
"@jeecg/online": "3.6.2-GA",
