### ISSUE TITLE
请问springboot3_sas分支与主干分支master维护问题

### ISSUE THREAD

**Issue by yunbaishu** [jeecgboot/jeecg-boot#6149]
##### 版本号：
前端：springboot_sas
后端：springboot_sas
v3.6.1

##### 前端版本：vue3版？还是 vue2版？
vue3版本

##### 问题描述：
请问springboot3_sas分支与主干分支master维护问题？目前发现springboot_sas前后端代码版本不一致，不知道会不会存在较多bug缺陷

##### 截图&代码：
![1713755488948](https://github.com/jeecgboot/jeecg-boot/assets/33892328/1620fcf1-8c76-479c-8a97-d293f12e74ed)

**Comment by zhangdaiscott** [comment]
zj

**Comment by EightMonth** [comment]
spring sas分支属于内部测试分支，主要测试场景为shiro切换到Spring Authorization Server，目前停留在3.6.1版本，前端vue3代码分支是sas，版本是3.6.2，目前只维护运行正常，不处理已在主干分支处理的Issue，只处理Spring Authorization Server的应用问题
