### ISSUE TITLE
springboot3_sas内部嵌入积木报表被拒绝

### ISSUE THREAD

**Issue by lxxsjia** [jeecgboot/jeecg-boot#6150]
##### 截图&代码：
![1713772221613](https://github.com/jeecgboot/jeecg-boot/assets/10191788/75093a81-deb7-46fe-911c-2dcb9b82bac9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zj

**Comment by zhangdaiscott** [comment]
菜单配置截图

**Comment by zhangdaiscott** [comment]
好了
