### ISSUE TITLE
自定义按钮获取token

### ISSUE THREAD

**Issue by ZhangWenZhen2000** [jeecgboot/jeecg-boot#6152]
##### 问题描述：
Online表单中如何自定义按钮获得token，同时传递参数跳转到积木报表详情

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/121787049/e11de72a-d7b3-40da-900e-42128eba3cf9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/online/systemVariables.html
