### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by zzpwsm** [jeecgboot/jeecg-boot#6153]
##### 版本号：
v3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
大面积没有权限，看了以往的issue也没能得到解决
Subject does not have permission [system:role:list]
（今天尝试了一下vue2的部署，后面报错之后已经拉全新的前端和后端代码，且重新删除数据库表后执行数据库脚本还是不行）

##### 截图&代码：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/102269878/8909f753-c895-4f3e-8ccc-14cef4d4ab80)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
自己补充配置下缺少的按钮权限，给角色分配按钮权限

**Comment by zzpwsm** [comment]
可是通过菜单配置了权限，需要通过角色管理给用户授权，我角色管理都没有权限，给角色管理配置完权限之后，直接就看不见这个菜单选项了。请教一下怎么解决

**Comment by zzpwsm** [comment]
补充一下：数据库对应的角色其实是有角色管理的权限？
![图片](https://github.com/jeecgboot/jeecg-boot/assets/102269878/844166ad-fe58-4295-9021-fc116d544148)
