### ISSUE TITLE
更改用户对于添加删除功能权限后，重新登陆用户权限不生效

### ISSUE THREAD

**Issue by lxxsjia** [jeecgboot/jeecg-boot#6154]
##### 版本号：
jeecg-boot-3.6.3

##### 前端版本：
vue3

##### 问题描述：
通过online代码生成新建一个模块，给一个角色授权（添加、删除、编辑）后，重新登陆权限不生效，删除redis中shiro->cache，权限才会生效

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
授权后，需要退出重新登录

**Comment by lxxsjia** [comment]
是的，退出重新登陆了，不生效

**Comment by zhangdaiscott** [comment]
后台下载的那个分支

**Comment by lxxsjia** [comment]
下载的tag：[v3.6.3](https://github.com/jeecgboot/jeecg-boot/releases/tag/v3.6.3)

**Comment by lhj6167** [comment]
请问有后续了吗。我也碰到这个问题，权限菜单添加好了，角色也授权好了，前后端项目也都重启了，也是增删改权限不生效，F12抓包查看当前登陆用户是有这个权限的，但是后端报错
 Subject does not have permission [setting:lite_customize_report_category:edit]
org.apache.shiro.authz.UnauthorizedException: Subject does not have permission [setting:lite_customize_report_category:edit]
