### ISSUE TITLE
vue3访问后端接口报错, 没有权限

### ISSUE THREAD

**Issue by cmc-x** [jeecgboot/jeecg-boot#6155]
##### 版本号：
3.6.3

##### 问题描述：
vue3访问后端接口报错 显示没有权限

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725189/974fcbdf-4c31-4ddc-80d1-13fc65ccf258)
![image](https://github.com/jeecgboot/jeecg-boot/assets/55725189/20d4e5bc-41f4-4861-aaa2-2048d68c2f2a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你后台启动了吗

**Comment by cmc-x** [comment]
> 你后台启动了吗

已经启动了 问题找到了 是Linux系统把访问给拦截了  谢谢回复
