### ISSUE TITLE
excel导入功能报错

### ISSUE THREAD

**Issue by duanzhihuaData** [jeecgboot/jeecg-boot#6157]
##### 问题描述：
excel导入功能报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/58547522/0e1779a0-26ce-47b7-aca9-704fc0cdd6e7)

**Comment by duanzhihuaData** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/58547522/0d347f2e-cc1b-4ff7-844e-392a44db8aee)
![image](https://github.com/jeecgboot/jeecg-boot/assets/58547522/6d181c0f-45fa-42b3-83b1-86d11dd8993c)
.xls .xlsx  isXSSFWorkbook都可以正确设置，但报错为不识别该文件

**Comment by zhengzhai** [comment]
问题解决了吗
