### ISSUE TITLE
 online表单新增异常

### ISSUE THREAD

**Issue by zzpwsm** [jeecgboot/jeecg-boot#6158]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
新电脑拉下来的代码， online表单新增异常，其他功能正常，不知道是不是版本冲突的问题。

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/102269878/c075442c-aac9-474f-830a-1db3a07dc864)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
异常？错误呢

**Comment by zzpwsm** [comment]
界面显示异常，可以看到截图下面没有字段显示，前段和后端代码是没有异常抛出的。

**Comment by zhangdaiscott** [comment]
F12

**Comment by zzpwsm** [comment]
F12压根没有网络包 换了个windows电脑 重新配置重新跑也出现这种情况

**Comment by zhangdaiscott** [comment]
后台下载的那个分支

**Comment by zzpwsm** [comment]
都是3.6.3的master分支跑起来的。 我现在切换到了saas分支，没遇到这个问题

**Comment by zhangdaiscott** [comment]
怎么可能sas 反而不稳定
