### ISSUE TITLE
反馈bug:3.5版本table setColumns方法无法触发watch,设置cacheColumns，导致表格设置字段显示与否的功能错乱 

### ISSUE THREAD

**Issue by MiaPerry** [jeecgboot/jeecg-boot#6160]
##### 问题描述：背景：动态表格&动态列，afterFatch动态请求表头和结果数据后，调用setColumns设置columns时候，设置表格功能无法正常使用

1、必须先设置 showTableSetting: false,请求处理完数据之后再设置setProps({showTableSetting: true})。直接设置showTableSetting: true会导致设置表中的字段加载不进去
![image](https://github.com/jeecgboot/jeecg-boot/assets/29267040/ae1b8968-e860-445a-a6e9-cb5455db78b5)

2、setColumns方法无法触发watch,进而无法设置cacheColumns，导致表格设置字段显示与否的功能错乱，无法按照勾选字段在列表上显示，如图所示，取消勾选一个字段之后，其他字段也消失
![image](https://github.com/jeecgboot/jeecg-boot/assets/29267040/0741011c-1123-4b8b-832a-ae8abcd90f2e)

建议在useColumns.ts中暴露一个方法，如

![image](https://github.com/jeecgboot/jeecg-boot/assets/29267040/d401cebb-8951-4224-931d-e6314f215f69)

在setColumns时候调用

3、目前动态设置表头，setProps({columns: myColumns})是可以正常触发watch的

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
经测试问题1复现了
问题2没复现
问题3即使出发了watch也没发让列设置中的字段是最新吧？

**Comment by liaozhiyang** [comment]
有图没发出来吧？麻烦操作步骤描述详细点，否则不太好定位

**Comment by ljw0106** [comment]
老哥，解决了吗？

**Comment by ljw0106** [comment]
> 有图没发出来吧？麻烦操作步骤描述详细点，否则不太好定位

哥 看看我的问题 跟他差不多 https://github.com/jeecgboot/JeecgBoot/issues/6989
