### ISSUE TITLE
vscode和webstorm打包有啥区别？vscode打包需要配置什么吗？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6163]
##### 截图&代码：

![1713943377218](https://github.com/jeecgboot/jeecg-boot/assets/48941638/5c72aa2a-d24c-4774-ad9c-f61a43e1dc3b)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
没区别，都是通过build命令
