### ISSUE TITLE
租户体系

### ISSUE THREAD

**Issue by YangYYK** [jeecgboot/jeecg-boot#6164]
##### 问题描述：
默默看了一天 发现租户体系是在是太难用了 
最基本的租户体系逻辑也没能实现
想问下 后期有没有升级的可能 如果有的话大约时间需要多久

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
你说没实现说明你没用明白把，敲敲云就是saas应用，采用的jeecgboot实现的
