### ISSUE TITLE
想看一下服务器监控的后端代码再那个位置 

### ISSUE THREAD

**Issue by keleyaojiab** [jeecgboot/jeecg-boot#6167]
##### 版本号：
3.6.3

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
我想实现这个功能 ，然后看你们的后端开源代码 。但是找不到代码位置.

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/137742376/731070f8-2ad2-48bd-b1d2-f05ef0d1a1a9)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
这个接口都是springBoot提供的

**Comment by keleyaojiab** [comment]
那我怎么调用这个地方

**Comment by keleyaojiab** [comment]
怎么对这个功能进行开发
