### ISSUE TITLE
富文本编辑器simpleToolbar配置增加 formatselect后页面不显示“段落”下拉框

### ISSUE THREAD

**Issue by zxdaly** [jeecgboot/jeecg-boot#6171]
##### 版本号：
3.6.2

##### 前端版本：vue3版？还是 vue2版？
vue3

##### 问题描述：
富文本编辑器simpleToolbar配置增加 formatselect后页面不显示“段落”下拉框

##### 截图&代码：
![微信截图_20240425143230](https://github.com/jeecgboot/jeecg-boot/assets/23379256/3579bcd1-78c2-4a88-92ec-53b985d2fc2e)
![image](https://github.com/jeecgboot/jeecg-boot/assets/23379256/a1062272-05c0-48c9-9041-7cbdf29d8b65)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
zy

**Comment by zxdaly** [comment]
> zy

请问大佬zy什么意思？

**Comment by 1298191366** [comment]
已修复，待新版本发布。根据tinymce 6.0 段落属性变成了`styles`
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/03ffdc30-986d-4cd7-9988-d79e37857dfe)
