### ISSUE TITLE
online表单开发，生成的vue原生代码中，form中j-dict-select-tag 标签配置了数据字典，无法回显

### ISSUE THREAD

**Issue by smt2235** [jeecgboot/jeecg-boot#6174]
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
online表单开发，生成的vue原生代码中，form中j-dict-select-tag 标签配置了数据字典，无法回显

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/46770935/fe321ccc-0fe7-424b-9368-7700443aa877)
<img width="1110" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/46770935/82d49e33-d265-49ab-970a-7d52709b41a4">

代码是生成的代码

**Comment by zhangdaiscott** [comment]
是不是类型问题，值是int?

**Comment by smt2235** [comment]
应该不是类型问题，在online表单里面，更多-功能测试-中正常回显，生成的代码不回显发自我的手机-------- 原始邮件 --------发件人： JEECG ***@***.***>日期： 2024年4月25日周四 17:27收件人： jeecgboot/jeecg-boot ***@***.***>抄送： smt2235 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/jeecg-boot] online表单开发，生成的vue原生代码中，form中j-dict-select-tag 标签配置了数据字典，无法回显 (Issue #6174)
是不是类型问题，值是int?

**Comment by zhangdaiscott** [comment]
自己确认类型

**Comment by smt2235** [comment]
确认了，数据库和实体类都改成int也不回显，都改成string也不行发自我的手机-------- 原始邮件 --------发件人： JEECG ***@***.***>日期： 2024年4月25日周四 17:27收件人： jeecgboot/jeecg-boot ***@***.***>抄送： smt2235 ***@***.***>, Author ***@***.***>主    题： Re: [jeecgboot/jeecg-boot] online表单开发，生成的vue原生代码中，form中j-dict-select-tag 标签配置了数据字典，无法回显 (Issue #6174)
是不是类型问题，值是int?
