### ISSUE TITLE
一个很大的BUG急需解决急需解决，微服务模式下在IDEA工具里启动jeecg-system-cloud-start模块可以启动打成jar包之后启动报错，包括jeecg-demo-cloud-start打成jar包也是报错

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6175]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
微服务模式下在IDEA工具里启动jeecg-system-cloud-start模块可以启动成功，打成jar包之后启动报错，包括jeecg-demo-cloud-start打成jar包也是报错

##### 截图&代码：
![1714036581126](https://github.com/jeecgboot/jeecg-boot/assets/132029411/b7f5f98b-9503-4eab-a4e3-8c1e92ebf155)
![1714036600926](https://github.com/jeecgboot/jeecg-boot/assets/132029411/fd1dd635-f069-472f-aefb-99afcb1af13d)
![1714036769224](https://github.com/jeecgboot/jeecg-boot/assets/132029411/920ec820-b4b0-44fd-a0e3-e4ba45b75d0c)
![1714036821354](https://github.com/jeecgboot/jeecg-boot/assets/132029411/1e43958c-f981-4a77-837e-4af6fc7d4d60)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
升级这个版本号		<codegenerate.version>1.4.7</codegenerate.version>

**Comment by yzh20021029** [comment]
1.4.7是最新的了 没有更新的版本了 求解决
![1714048090935](https://github.com/jeecgboot/jeecg-boot/assets/132029411/d1114d60-d812-4eae-8998-fd9c2cc69fd8)

**Comment by yzh20021029** [comment]
我想请问下有什么办法可以解决嘛，我现在正在用3.6.3版本做开发结果不能进行打包运行了。
