### ISSUE TITLE
JImageUpload组件有监听事件吗？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6176]
##### 截图&代码：
![1714047771363](https://github.com/jeecgboot/jeecg-boot/assets/48941638/239c85ae-92d4-443d-93c5-74c3c54d6dec)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
ws
