### ISSUE TITLE
很大的BUG急需解决急需解决，微服务模式下在IDEA工具里启动jeecg-system-cloud-start模块可以启动打成jar包之后启动报错，包括jeecg-demo-cloud-start打成jar包也是报错

### ISSUE THREAD

**Issue by yzh20021029** [jeecgboot/jeecg-boot#6178]
##### 版本号：

3.6.3
##### 前端版本：vue3版？还是 vue2版？

vue3
##### 问题描述：
微服务模式下在IDEA工具里启动jeecg-system-cloud-start模块可以启动打成jar包之后启动报错，包括jeecg-demo-cloud-start打成jar包也是报错,从github上面拉下来的codegenerate就是1.4.7就是最新版，拉下来直接打包就运行报错，jeecg的技术人员能去自己试一下。
##### 截图&代码：
![1714099535548](https://github.com/jeecgboot/jeecg-boot/assets/132029411/2772c4c5-4b90-41d5-9871-64d586d15ddc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重复问题不要提

**Comment by sunzhenwei22** [comment]
我也遇到了这个问题，升级到1.4.7问题依然没有解决
