### ISSUE TITLE
下载前端代码表格式样在没数据的情况下没有占满整屏

### ISSUE THREAD

**Issue by zealzhangz** [jeecgboot/jeecg-boot#6179]
##### 版本号：
3.5.0

##### 前端版本：vue3版？还是 vue2版？
vue3版

##### 问题描述：
生成前端代码表格在没数据的情况下，表格高度没有占满屏幕，查看了[文档](https://help.jeecg.com/component/BasicTable.html#tableprops)设置了`minHeight`参数不生效，参考以下截图。

##### 截图&代码：
**当前式样**
![1714101710460](https://github.com/jeecgboot/jeecg-boot/assets/8454011/ccfc8c10-1e91-4553-84b1-16ad17d9534b)
**期望式样**
![1714102047042](https://github.com/jeecgboot/jeecg-boot/assets/8454011/2b16627c-0c6d-4d76-9266-0e8ae455efe3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by 1298191366** [comment]
请参考文档：[表格如何占满高度](https://ojrjjvdr7z.k.topthink.com/2dev/jingyan/screen.html)
