### ISSUE TITLE
websocket断开重连

### ISSUE THREAD

**Issue by shaonianlang-ooo** [jeecgboot/jeecg-boot#6184]
##### 版本号：
v3.4.3last
##### 分支：
master？springboot3? 还是springboot3_sas

##### 前端版本:
vue3版？还是 vue2版？
vue2
##### 问题描述：
为什么websocket每隔20秒重连一次。时间长了，就会产生大量连接。
websocket不应该是连接上一直连着吗？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/82741120/601f0822-01d3-4e32-8a59-2ddd4e75a667)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by shaonianlang-ooo** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/82741120/29251f66-409a-41a0-a537-611b04da02f6)
这是 nginx转发配置

**Comment by fireinjava** [comment]
https://github.com/jeecgboot/jeecgboot-vue3/issues/1221
按这个改试下
