### ISSUE TITLE
关于仪表盘支持图表组件较少的问题

### ISSUE THREAD

**Issue by killer3210** [jeecgboot/jeecg-boot#6185]
##### 分支：master
master？springboot3? 还是springboot3_sas

##### 前端版本:vue3
vue3版？还是 vue2版？

##### 问题描述：
仪表盘设计功能在官网看到可以支持多种图表，包括地图等组件，但在本地部署之后只能使用几个常见的组件，支持功能较少

##### 截图&代码：
本地：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/50413075/3b90d1fc-8db1-40ca-928e-1f754a681e34)

官网：
![图片](https://github.com/jeecgboot/jeecg-boot/assets/50413075/125ff462-d57a-4eef-83b1-c2ee8d41f64c)

**Comment by zhangdaiscott** [comment]
陆续开放，开源版目前功能只开放了部分
