### ISSUE TITLE
vue2版本拉取到本地跑起来以后，菜单只有用户管理和首页

### ISSUE THREAD

**Issue by ririgriffin** [jeecgboot/jeecg-boot#6186]
##### 版本号：
3.4.3
##### 分支：
master？springboot3? 还是springboot3_sas
master
##### 前端版本:
vue3版？还是 vue2版？
vue2
##### 问题描述：
vue2版本拉取到本地跑起来以后，菜单只有用户管理和首页

##### 截图&代码：
<img width="1104" alt="9e4f612ad81c07709378743423234a07" src="https://github.com/jeecgboot/jeecg-boot/assets/100279771/65a19524-9e7c-45f4-adfc-9890ab433be5">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
重要说明：JeecgBoot前端提供两套解决方案，一套VUE2和一套VUE3版本，目前vue2版本最新代码只支持到jeecgboot 3.4.3版本，一定注意。

你的数据库不对，或者不是配套的后台代码，可以找到对应的后台代码或者自己手工授权
