### ISSUE TITLE
单机版连接不上websocket

### ISSUE THREAD

**Issue by zqf-git** [jeecgboot/jeecg-boot#6189]
##### 分支：springboot2
master？springboot3? 还是springboot3_sas

##### 前端版本:
vue3版？还是 vue2版？

##### 问题描述：jeecgSystemApplication单机版，服务跑起来，想测试下websocket，连不上ws://172.26.144.1:8081/jeecg-boot/websocket/112    我的路径写错了吗？
![微信图片_20240428154423](https://github.com/jeecgboot/jeecg-boot/assets/80464907/24a7a49d-75fa-4401-8c70-750f64df3a25)

##### 截图&代码：
![微信截图_20240428154224](https://github.com/jeecgboot/jeecg-boot/assets/80464907/3a50c283-196f-4d00-a4cb-ba743859a5e8)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
vue几？

**Comment by EightMonth** [comment]
如果用其它websocket连接工具测试，需要加上一个请求头，值为token，参考如下：
![image](https://github.com/jeecgboot/jeecg-boot/assets/23272421/eb87f82c-63e1-4c3f-92ff-bde7864bfe00)
