### ISSUE TITLE
版本升级到3.6.3之后，前端所写的 v-auth 权限全部失效不显示

### ISSUE THREAD

**Issue by HadesAaron** [jeecgboot/jeecg-boot#6190]
版本号：3.6.3

前端版本: vue3

问题描述：前后端同步从3.5.3升级到3.6.3之后，出现权限控制异常：
1、前端3.5.3+后端3.5.3，正常
2、前端3.5.3+后端3.6.3，正常
3、前端3.6.3+后端3.6.3，异常

目前没有思路，不知道应该从哪方面着手去排查，权限查询接口正常，返回的权限数据也正常。

**Comment by zhangdaiscott** [comment]
测试没问题，没权限的话，按钮隐藏
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/06600abc-b6b8-4ec7-ba62-79258e3b7293)
