### ISSUE TITLE
ApiSelect多次请求

### ISSUE THREAD

**Issue by mjlxiaoma** [jeecgboot/jeecg-boot#6191]
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
Vue3
##### 问题描述：
在Apiselect，如果传递了请求参数，在选择下拉的时候，还有初次进来的时候都会请求多次接口的问题

##### 截图&代码：
//默认进来的请求情况
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/1de96c1e-323e-4e12-9dc0-552acf651bfe)
// 选择下拉的时候的情况
![img_v3_02ad_26f5731f-68e5-4286-a676-6d2ba3e9699g](https://github.com/jeecgboot/jeecg-boot/assets/89441679/69cfa558-7535-4f04-bd16-3b73e1b658f6)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
zy

**Comment by mjlxiaoma** [comment]
复现不出来吗

**Comment by liaozhiyang** [comment]
经测没复现，你可用系统用户新增抽屉里面的角色测试。或可提供更加详细的信息
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/dac678c0-60ce-419d-b7f0-c33e2243c8a0)

**Comment by mjlxiaoma** [comment]
是这样的，你发的这个是用的配置项的方式去写入参数的，我发出的这个问题是通过组件传参的方式，使用方法不一样，我是用组件这种方式的原因是因为配置项的方式有些场景无法处理，您可以看一下我描述的是否正确，我附上代码。
//如果是这种使用方式会有问题把
 <BasicForm @register="registerForm">
        <template #store="{ model, field }">
          <ApiSelect
            :disabled="isEdit" 
            :api="()=>getspdStoragelist({delFlag: 0})"
            v-model:value="model[field]"
            allow-clear
            showSearch
            placeholder="请选择采购库房"
            optionFilterProp="storageNameAbbr"
            labelField="storageName"
            valueField="id"
            resultField="result"
            label-in-value
            :filterOption="true"
          >
          </ApiSelect>
        </template>
</BasicForm>

**Comment by mjlxiaoma** [comment]
<BasicForm @register="registerForm">
        <template #store="{ model, field }">
          <ApiSelect
            :disabled="isEdit" 
            :api="()=>getspdStoragelist({delFlag: 0})"
            v-model:value="model[field]"
            allow-clear
            showSearch
            placeholder="请选择采购库房"
            optionFilterProp="storageNameAbbr"
            labelField="storageName"
            valueField="id"
            resultField="result"
            label-in-value
            :filterOption="true"
          >
          </ApiSelect>
        </template>
        </BasicForm>

**Comment by mjlxiaoma** [comment]
代码发不出去，我截图了
![image](https://github.com/jeecgboot/jeecg-boot/assets/89441679/afcfb7e9-0bbc-4476-83a0-964b186fcc6e)

**Comment by liaozhiyang** [comment]
你传入immediate props 设置成false

**Comment by mjlxiaoma** [comment]
好的，看到了，所以是默认请求，设置后，点击下拉才去请求对吧
