### ISSUE TITLE
3.6.3版本与钉钉整合不成功，报“重定向URL错误”

### ISSUE THREAD

**Issue by billxu101** [jeecgboot/jeecg-boot#6192]
##### 问题描述：3.6.3版本与钉钉整合不成功，从钉钉PC桌面打开jeecgboot时，报出“重定向URL错误”
问题可能出在没有实现新版钉钉的第三方整合要求

![image](https://github.com/jeecgboot/jeecg-boot/assets/37691275/ff60eb1a-f617-46ad-8223-4302cae739c1)

参考钉钉文档说明：https://open.dingtalk.com/document/orgapp/tutorial-obtaining-user-personal-information
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/37691275/2a0426f5-2721-4cbf-9605-97a33901c8ee)

新版钉钉对第三方接入有新要求
![image](https://github.com/jeecgboot/jeecg-boot/assets/37691275/81ff293c-f45a-4287-9b40-db4f7209dda9)

按照现在的jeecgboot钉钉的配置说明无法实现整合
![image](https://github.com/jeecgboot/jeecg-boot/assets/37691275/2006852e-07f1-47b2-87e4-5ccf42b83786)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
ws

**Comment by 1298191366** [comment]
经测试可以使用，你说的和用ngrok没有关系，他那个只是其中的一个方案，本地测试的话用ngrok即可，如果你是线上，需要线上的服务器后台地址，如果配置ngrok不好用，说明ngrok或者回调的地址配的不对，回调地址需要加上项目名称
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/61d5674c-2e8d-4588-8dfc-9ddd9b77af12)

请再次确认 这里是否与回调地址一样
![image](https://github.com/jeecgboot/jeecg-boot/assets/30997828/99fec243-f266-4626-b8d3-fcb4c1112839)
