### ISSUE TITLE
websocket问题

### ISSUE THREAD

**Issue by shaonianlang-ooo** [jeecgboot/jeecg-boot#6195]
##### 版本号：
3.4.3
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue2
##### 问题描述：
使用时间长了后，为什么会出现大量websocket请求。

##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/82741120/04bc0843-f8eb-42f8-a6a3-0c717419b304)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
老版本，无法处理

**Comment by shaonianlang-ooo** [comment]
> 老版本，无法处理

能知道是什么问题吗？

**Comment by zhangdaiscott** [comment]
可以自行对比最新代码
