### ISSUE TITLE
在线表单-自定义树形控件是否含有子节点功能不生效

### ISSUE THREAD

**Issue by fulin-peng-ydxs** [jeecgboot/jeecg-boot#6197]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
在线表单基础控件-》自定义树类型控件，是否有含有子节点字段不起作用

##### 截图&代码：
![0Q4_%TEXHD_RZL@))766KYR](https://github.com/jeecgboot/jeecg-boot/assets/163669011/1c3af594-ed63-48a4-ba1e-4053b89a50ab)
![ECR0X`OXG)AQCP84X1XPTMG](https://github.com/jeecgboot/jeecg-boot/assets/163669011/5ed0201c-7106-4821-abb5-d84bfa3cec01)
![0P$G}}9F9TRR8)##### 版本号：3.6.3

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
在线表单基础控件-》自定义树类型控件，是否有含有子节点字段不起作用

##### 截图&代码：
![0Q4_%TEXHD_RZL@))766KYR](https://github.com/jeecgboot/jeecg-boot/assets/163669011/1c3af594-ed63-48a4-ba1e-4053b89a50ab)
![ECR0X`OXG)AQCP84X1XPTMG](https://github.com/jeecgboot/jeecg-boot/assets/163669011/5ed0201c-7106-4821-abb5-d84bfa3cec01)
 E5O3LW](https://github.com/jeecgboot/jeecg-boot/assets/163669011/b6493978-39d4-4a43-b733-63981ccd601a)
![}3 3@M~(T8X3AVN(`TY}B$I](https://github.com/jeecgboot/jeecg-boot/assets/163669011/cd254a85-ea67-4e91-8fbb-17d184147d23)
![ETKRFBN16Y5%$FX$(GAUK52](https://github.com/jeecgboot/jeecg-boot/assets/163669011/8bc20bbf-9794-4095-99a1-93d81573800d)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
