### ISSUE TITLE
在线表单-自定义树形控件使用-配置父节点的值不为0就会报错

### ISSUE THREAD

**Issue by fulin-peng-ydxs** [jeecgboot/jeecg-boot#6198]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
在线表单-自定义树形控件使用-配置父节点的值不为0，访问表单的功能测试就会报错，看报错是把对应的值当做一个字段名处理了

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/163669011/d20dc1cc-7450-4e20-82c6-867c5a58e1f3)
![I~SL W36G8B2RQRZRYHET3M](https://github.com/jeecgboot/jeecg-boot/assets/163669011/9c15285a-f3aa-425a-9906-7ffd9bad8875)

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
[自定义树类型-文档](https://help.jeecg.com/online/form/component1.html)
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/84d38a06-f813-44f2-b97c-ff88e51c2077)
字典code需填写树控件根节点的父ID的值

**Comment by fulin-peng-ydxs** [comment]
> [自定义树类型-文档](https://help.jeecg.com/online/form/component1.html) ![image](https://private-user-images.githubusercontent.com/8199499/328092392-84d38a06-f813-44f2-b97c-ff88e51c2077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzk0MzgsIm5iZiI6MTcxNTA3OTEzOCwicGF0aCI6Ii84MTk5NDk5LzMyODA5MjM5Mi04NGQzOGEwNi1mODEzLTQ0ZjItYjk3Yy1mZjg4ZTUxYzIwNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTA1MjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBjODIwZDE4MTI1ODEzNzhiOTllOGYwMWVkZWJmMzc5N2RlMjQ2ZWY2ZGVkYzIzNGMyYTNkZTc1ODFiY2Y0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EwToR7jAQtHPGwtznuboggOx9dP4KF8I8BO96crOcPM) 字典code需填写树控件根节点的父ID的值

我的根节点的父id值就是0，如果改成其他的，那么字典code引用时就会报错

**Comment by liaozhiyang** [comment]
其他值是？其他也得是节点的id啊，不乱填。
