### ISSUE TITLE
关于高级查询组件j-super-query缓存问题

### ISSUE THREAD

**Issue by NameAce** [jeecgboot/jeecg-boot#6204]
##### 版本号：
2

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue2

##### 问题描述：
目前在使用j-super-query的过程中，遇到了一个问题：

我们保存的查询是缓存在浏览器的Local storage中，当我们清除浏览器缓存时，保存的查询也会随之清除。
但是可能存在一些查询比较复杂的页面，我并不想只保存在浏览器。肯定是会考虑存到数据库，redis中，同时对这些保存的查询，也希望做到权限的控制（部门，角色……）。

在vue2的版本中，j-super-query是开源的，以上所说的问题，我可以自己去改动这个组件，实现我想要的功能。
但是在vue3的版本中，该组件不开源了，以上所说的问题应该就没法实现了。
不知道团队针对我说的这个问题，有没有什么更好的方案或建议。谢谢！

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
未按格式要求发帖、描述过于简抽象的，会被直接删掉；
