### ISSUE TITLE
关于高级查询组件j-super-query缓存问题

### ISSUE THREAD

**Issue by NameAce** [jeecgboot/jeecg-boot#6205]
##### 版本号：
3.4.3

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue2版

##### 问题描述：
目前在使用j-super-query的过程中，遇到了一个问题：

我们保存的查询是缓存在浏览器的Local storage中，当我们清除浏览器缓存时，保存的查询也会随之清除。
但是可能存在一些查询比较复杂的页面，我并不想只保存在浏览器。肯定是会考虑存到数据库，redis中，同时对这些保存的查询，也希望做到权限的控制（部门，角色……）。

在vue2的版本中，j-super-query是开源的，以上所说的问题，我可以自己去改动这个组件，实现我想要的功能。
但是在vue3的版本中，该组件不开源了，以上所说的问题应该就没法实现了。
不知道团队针对我说的这个问题，有没有什么更好的方案或建议。有没有可能在未来版本实现。谢谢！

有什么没描述清楚的请说明，不要直接关闭，谢谢！

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/42397253/7f5a28cc-53c8-4184-8050-92c6d35cb645)
![image](https://github.com/jeecgboot/jeecg-boot/assets/42397253/3ee732e0-f6fe-47e6-b31d-d3a767372235)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
zy

**Comment by liaozhiyang** [comment]
已解决，下一版本发布。
增加了三个参数，能接受传给组件的查询条件，点保存按钮时把保存的查询条件数据能传给组件外面。这应该就能实现你要的效果了。

参数说明：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/944aa2b7-212a-4930-9503-87a468af015f)

编码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/3c553e92-86a7-47fe-a648-0596c0f8799a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/1b112d2a-5444-4d51-8a2b-20ec929dd1c6)

**Comment by NameAce** [comment]
感谢！
