### ISSUE TITLE
BasicTable 表格

### ISSUE THREAD

**Issue by gw1583485820** [jeecgboot/jeecg-boot#6207]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：

同一个表单搜索表格，通过按钮点击事件切换不同类型的表格，怎么改变表格的 表头、请求接口呢？
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
版本号：
