### ISSUE TITLE
前端第一次发送心跳后，websocket监听消息失效

### ISSUE THREAD

**Issue by jackson03180824** [jeecgboot/jeecg-boot#6210]
##### 问题描述：
在前端发送第一次websocket心跳前，发送公告右上角的消息数量是会改变的，但是当第一次心跳发送后，后端会断开ws连接，之后马上再连接上，此时在发送公告，右上角的消息数量不会实时更新，相当于前端的onMessage方法无法监听到WebSocket消息了

##### 截图&代码：
<img width="1136" alt="c051e0f8c35dbe3f29366030274fc51" src="https://github.com/jeecgboot/jeecg-boot/assets/120036783/66550c09-866e-48d2-8032-759074f51197">

**Comment by fireinjava** [comment]
参考这个，我发现还是很多人有websocket问题
https://github.com/jeecgboot/jeecgboot-vue3/issues/1221

**Comment by zhangdaiscott** [comment]
新版发布了，请验证
