### ISSUE TITLE
可否出一个纯净版的,现在的代码生成器是不是有点重啊,希望可以出一个没有那么多封装比较纯净的版本,可否尝试接入智能ai自动生成代码

### ISSUE THREAD

**Issue by 13223746581** [jeecgboot/jeecg-boot#6212]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhouzhanwen** [comment]
我也期望出一个简化版的，目前版本太重了，首页装载也很慢。

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/2dev/mini.html

**Comment by 13223746581** [comment]
不是前端是 后端 一百多张表 很多超级多的组件 以及封装的jar包 想商用都难

**Comment by zhangdaiscott** [comment]
以下不需要的自己灵活删除就行

- 1、积木报表和演示数据的demo表
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/0823e7e4-7a8e-49f2-ad5d-e7464ce5249f)

如果不需要积木报表删除依赖即可

- 2、仪表盘表
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/3ee6e28e-3764-4f6e-a469-4871e330e14c)

- 3、online报表、online表单的相关表
![image](https://github.com/jeecgboot/jeecg-boot/assets/3162115/7f541faf-4b3c-4234-b282-2e61cabefdff)
