### ISSUE TITLE
请问怎么升级jeecgboot版本？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6215]
##### 截图&代码：
![1715246785260](https://github.com/jeecgboot/jeecg-boot/assets/48941638/0bf0fbce-8d0e-40e4-b6a5-21e6c6f3bf83)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
https://github.com/jeecgboot/jeecg-boot/blob/master/db/%E7%89%88%E6%9C%AC%E5%8D%87%E7%BA%A7%E8%AF%B4%E6%98%8E.md

版本升级方法
JeecgBoot属于平台级产品，每次升级改动较大，目前做不到平滑升级。

增量升级方案
1.代码合并
本地通过svn或git做好主干，在分支上做业务开发，jeecg每次版本发布，可以手工覆盖主干的代码，对比合并代码；

2.数据库升级
从3.6.2+版本增加flyway自动升级数据库机制，支持 mysql5.7、mysql8;
其他库请手工执行SQL, 目录： jeecg-module-system\jeecg-system-start\src\main\resources\flyway\sql\mysql
注意： 升级sql只提供mysql版本；如果有权限升级, 还需要手工角色授权，退出重新登录才好使。

3.兼容问题
每次发版，会针对不兼容地方重点说明。
