### ISSUE TITLE
autopoi导入excel数据行缺失，应该如何设置？

### ISSUE THREAD

**Issue by ciahua** [jeecgboot/jeecg-boot#6216]
##### 版本号：
v3.5.5
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3

##### 问题描述：
导入一个Excel，设置参数para，但始终无法正确地获取所有的数据行，是什么原因？

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/45c53a1c-06ec-43df-9257-a64a7b8c45f2)
![image](https://github.com/jeecgboot/jeecg-boot/assets/37827583/fafeb876-69fe-4830-989d-e309264f8d30)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
你这种复杂的，就自己用poi原生读取吧，通用格式不一定灵活
