### ISSUE TITLE
jeecgboot-vue3 tinymce报错

### ISSUE THREAD

**Issue by 17726697545** [jeecgboot/jeecg-boot#6218]
##### 版本号：
3.5.2

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3

##### 问题描述：
npm run server 正常运行
npm run build 发布服务器报错

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/67582909/563aa50b-f67f-47b1-a67e-20bc14a968b0)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
搜一下历史issue
