### ISSUE TITLE
[机制/需求] 租户运作机制：开启租户模式后，能否还建立一个业务管理员的角色（非系统管理员），能看到+管理租户的业务数据

### ISSUE THREAD

**Issue by huangwei2013** [jeecgboot/jeecg-boot#6222]
不涉及具体版本

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
你可以通过切换租户的方式来维护数据

**Comment by huangwei2013** [comment]
业务超管，也作为一个租户？ 他可拥有其他租户数据的管理权限？
