### ISSUE TITLE
redis无法访问远程地址

### ISSUE THREAD

**Issue by zqf-git** [jeecgboot/jeecg-boot#6229]
##### 问题描述：
微服务架构，启动我的业务模块(tszh)  ,程序初始化RedisContainner报错连接不到本地的redis服务，我本地没有redis服务访问的远程redis 服务，nacos配置文件指向的redis地址就是远程访问的服务地址，所有配置文件都检查了包括代码中没有写到localhost的redis服务，但是程序就是报错链接本地redis异常。。。。该怎么办

##### 截图&代码：
 
![微信图片_20240517131553](https://github.com/jeecgboot/jeecg-boot/assets/80464907/e9f96c3c-976e-4a09-a443-48ca110fbe96)
![微信图片_20240517131557](https://github.com/jeecgboot/jeecg-boot/assets/80464907/df699b82-7f0f-443e-a1fa-c24f701160e4)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

  
![微信图片_20240517131603](https://github.com/jeecgboot/jeecg-boot/assets/80464907/6cdb4a12-60e8-4278-bc47-8157d4fa0ef0)
![微信图片_20240517131608](https://github.com/jeecgboot/jeecg-boot/assets/80464907/caaf7680-08af-416b-89c8-9c1c2c3abf59)

**Comment by chenhengeng** [comment]
jeecgboot官方文档写的修改hosts文件，你是不是没修改hosts呀
https://help.jeecg.com/java/springcloud/switchcloud/monomer.html
