### ISSUE TITLE
想要排查修复jeecg-boot jmreport/queryFieldBySql接口调用控制不严。怎么确定是否是3.4.0-3.5.3版本，是否有漏洞补丁或升级版本可解决。

### ISSUE THREAD

**Issue by JN-nan** [jeecgboot/jeecg-boot#6236]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
::漏洞说明::

漏洞：Jeecg-Boot开发平台存在任意代码执行漏洞
方案：漏洞原因在积木报表，升级jimureport-spring-boot-starter到1.6.5+版本
日志：http://jimureport.com/doc/log
汇总：
https://my.oschina.net/jeecg/blog/10150942
https://my.oschina.net/jeecg/blog/10151069
