### ISSUE TITLE
新增module后，如何正确调用jeecg-system-biz

### ISSUE THREAD

**Issue by DotNeter-Hpf** [jeecgboot/jeecg-boot#6237]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
新建业务module，想调用websocket 或者 sysUserService，正确操作是怎样的，在新module的pom.xml，添加biz引用，发现也能用。
<dependency>
            <groupId>org.jeecgframework.boot</groupId>
            <artifactId>jeecg-system-biz</artifactId>
</dependency>

##### 截图&代码：
<img width="768" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/62707731/bc97d3e6-0eef-4e7f-b84c-7fae59e21562">

**Comment by zhangdaiscott** [comment]
都可以


		<dependency>
			<groupId>org.jeecgframework.boot</groupId>
			<artifactId>jeecg-system-local-api</artifactId>
		</dependency>

**Comment by DotNeter-Hpf** [comment]
非常感谢您的回答。还想请教一个问题，如果选择添加 jeecg-system-local-api 依赖的方式，就需要通过 ISysBaseAPI 获取biz中想要的内容吗？
