### ISSUE TITLE
大屏设计器是收费功能吗？

### ISSUE THREAD

**Issue by ak-2019** [jeecgboot/jeecg-boot#6240]
##### 截图&代码：
![MBI8L41@1}J Z V@Y ~7AI2](https://github.com/jeecgboot/jeecg-boot/assets/48941638/a5b9aa29-8c59-4596-9379-9170148ceab2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
是的
可以在[积木平台](http://jimureport.com/)上免费试用
