### ISSUE TITLE
online报表 SQL翻译 不翻译第二页的数据

### ISSUE THREAD

**Issue by cym1231** [jeecgboot/jeecg-boot#6242]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/a3f7e30b-588f-42c6-a878-5cb628e15318)
![image](https://github.com/jeecgboot/jeecg-boot/assets/128006839/5840e158-ac18-4141-b735-b9ecdc3ca182)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
cr

**Comment by liaozhiyang** [comment]
已修复，下一版本发布。
你可本地可按如图进行修改：
![image](https://github.com/jeecgboot/jeecg-boot/assets/8199499/8b4ac530-e8d9-47be-9937-14f03a73e9c3)
