### ISSUE TITLE
tinymce菜单栏第二次打开后样式错乱

### ISSUE THREAD

**Issue by yangfeng005** [jeecgboot/jeecg-boot#6247]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
"tinymce": "^6.6.2" 菜单栏第二次打开后样式错乱

##### 截图&代码：
![WX20240523-111627@2x](https://github.com/jeecgboot/jeecg-boot/assets/11865965/bb859353-ae9e-4660-9f5f-fd69e028f94a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
参考下最新的代码

**Comment by yangfeng005** [comment]
最新代码问题仍然存在
<img width="1040" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/11865965/27e1f8b5-7a35-4462-b17e-4a314307497a">
<img width="865" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/11865965/7834bec1-1b85-4aaa-a79f-3facd9da1ba2">

**Comment by zhangdaiscott** [comment]
新版发布了，请验证
