### ISSUE TITLE
功能页面无内容

### ISSUE THREAD

**Issue by bitxxw** [jeecgboot/jeecg-boot#6250]
##### 问题描述：
背景:本地部署，使用nginx代理前后端，idea启动后端服务
问题 : 启动后，登录页面可以正常访问，可以正常登录，首页可以正常展示,其他功能页面点击后都没有内容展示，页面调式模式下查看
无任何请求
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/34402503/355b3917-e5cb-4c14-b666-55d27aa631b7)
![image](https://github.com/jeecgboot/jeecg-boot/assets/34402503/a4db96c1-3873-4d05-8ef4-ff643210f38a)
![image](https://github.com/jeecgboot/jeecg-boot/assets/34402503/65d9bd41-d215-4c9c-9da0-2e268736719c)
![image](https://github.com/jeecgboot/jeecg-boot/assets/34402503/5b47f1a3-e2f5-4736-b429-004a033f3b71)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
清缓存，重新发布试试

**Comment by bitxxw** [comment]
> 清缓存，重新发布试试

已解决，版本问题
