### ISSUE TITLE
3.6.3 maven 依赖不存在

### ISSUE THREAD

**Issue by non-native** [jeecgboot/jeecg-boot#6251]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
从远端仓库：阿里云、mvnrepository以及 https://maven.jeecg.org/nexus/content/repositories/jeecg/org/jeecgframework/boot/jeecg-boot-parent/，均无法找到3.6.3版本的 jeecg-boot-parent

##### 截图&代码：

Non-resolvable parent POM for org.jeecgframework.boot:jeecg-cloud-demo:3.6.3: Failure to find org.jeecgframework.boot:jeecg-boot-parent:
pom:3.6.3  was cached in the local repository, resolution will not be reattempted until the update interval of xener-admin has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 13

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
先执行install

**Comment by non-native** [comment]
> 先执行install

执行了的，我看你们仓库里也没有这个版本

**Comment by UnderThis** [comment]
解决了吗哥们儿，得install这个总的，我也是搞了好久 
![微信图片_20240912143609](https://github.com/user-attachments/assets/7260a23f-afe3-4907-aaaf-0e15fa8f2bb6)

**Comment by non-native** [comment]
> 解决了吗哥们儿，得install这个总的，我也是搞了好久 ![微信图片_20240912143609](https://private-user-images.githubusercontent.com/52099637/366749480-7260a23f-afe3-4907-aaaf-0e15fa8f2bb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjM0MjMsIm5iZiI6MTcyNjEyMzEyMywicGF0aCI6Ii81MjA5OTYzNy8zNjY3NDk0ODAtNzI2MGEyM2YtYWZlMy00OTA3LWFhYWYtMGUxNWZhOGYyYmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2Mzg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYmU3YjNjNjVlYTkzNGZlMGVhYTcyN2RmYTY3OTIzYjY5NTRiNzI2ZjQ0YjIyYjgzYjY1Njk4OGZiODAzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70AZ6nME2f9FMOItRSAd5DJH4RRzD_CxEnADWyI9wao)

对的，后面我发现了  👍
