### ISSUE TITLE
我整合之前的单体项目到jeecg上，启动的时候报shiro的问题

### ISSUE THREAD

**Issue by AanFen-zhou** [jeecgboot/jeecg-boot#6253]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3

##### 问题描述：
我整合之前的单体项目到jeecg上，启动的时候报shiro的问题
提示信息：
Description:Field eventBus in org.apache.shiro.spring.config.AbstractShiroConfiguration required a bean of type 'org.apache.shiro.event.EventBus' that could not be found.
Action:
Consider defining a bean of type 'org.apache.shiro.event.EventBus' in your configuration.

##### 截图&代码：
![bba79230ee974486205973053ae1af7f](https://github.com/jeecgboot/jeecg-boot/assets/76689087/33bb107f-d0fa-42dd-aeac-c81553d52521)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
没明白

**Comment by AanFen-zhou** [comment]
> 没明白

就是我想问下，启动项目的时候为啥会提示上面图片的内容，我全局搜索都搜索不到有EventBus和AbstractShiroConfiguration类或方法
