### ISSUE TITLE
minio和oss可以同时使用吗？

### ISSUE THREAD

**Issue by cxyax** [jeecgboot/jeecg-boot#6255]
##### 版本号：
2.4.3 已用在生产环境

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue2

##### 问题描述：
minio和oss可以同时使用吗？
现在我们生产环境用了很久的minio，然后视频文件太大，要将视频文件用oss管理，剩余图片继续使用minio即可，对于这种需求我们需要同时使用oss和minio，在jeecg框架文档中未找到相关的内容，还请指点

##### 截图&代码：
<img width="729" alt="image" src="https://github.com/jeecgboot/jeecg-boot/assets/58779674/0b3a930b-e5d7-460e-b09c-c1eeb6424eeb">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
默认不行
