### ISSUE TITLE
sql增强添加权限在哪里配置？

### ISSUE THREAD

**Issue by bitxxw** [jeecgboot/jeecg-boot#6257]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3版
##### 问题描述：

添加sql增强时报没有权限
##### 截图&代码：
![}W`I6OT__$FUETYYI1QHY1B](https://github.com/jeecgboot/jeecg-boot/assets/34402503/e3a0fe39-823d-4a97-bafa-a7ce43b74e0a)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
使用admin账号配置试试或者看下后台提示什么权限有问题，手工配置上权限
