### ISSUE TITLE
菜单配置第三页跳转页面打不开

### ISSUE THREAD

**Issue by chenjiayang2008** [jeecgboot/jeecg-boot#6259]
##### 版本号：
3.6.2
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：

配置了第三方页面，但是无法打开
##### 截图&代码：

![image](https://github.com/jeecgboot/jeecg-boot/assets/29227054/2f0044c3-c924-499f-b9a7-676d98b9c4cb)
![image](https://github.com/jeecgboot/jeecg-boot/assets/29227054/700745d1-9910-49c2-998e-85492ac4e89b)

**Comment by zhangdaiscott** [comment]
前端 组件配置错误吧，参考官网示例
