### ISSUE TITLE
低代码开发代码覆盖问题

### ISSUE THREAD

**Issue by chengcheng007** [jeecgboot/jeecg-boot#6260]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
no

**Comment by 17356212005** [comment]
那在二次开发的基础上怎么保证代码不会被覆盖呢

**Comment by zhangdaiscott** [comment]
生成第一次后，后面手工了
