### ISSUE TITLE
docker部署仪表盘设计器返回的列表是空的，IP访问就可以。

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecg-boot#6264]
##### 问题描述：docker部署仪表盘设计器返回的列表是空的，IP访问就可以。
这是配置文件，是哪里配置的有问题吗

![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/c981ed3f-4c15-4eef-9e1d-a1ec61486651)

##### 截图&代码：
docker部署截图：
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/6c41a0b1-3c68-4f57-beb1-0e626712b3d0)
IP方式：
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/0c4caa55-b2d8-4df6-a728-56998f72d30f)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
F12什么错误

**Comment by 506764932** [comment]
> F12什么错误

没有报错，200 就是没返回数据
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/e72aa4e2-09fd-4b40-aa7a-b3bfc7954eb0)
我看域名地址后面的租户参数值是undified 。 【&tenantId=undefined】不知道和这个有没有关系

**Comment by zhangdaiscott** [comment]
后台报错吗

**Comment by 506764932** [comment]
> 后台报错吗

没有报错
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/df5bb793-e3df-49eb-993b-7ae0df731950)

**Comment by 506764932** [comment]
报表设计器域名也是可以的，但仪表盘设计器就是出不来

**Comment by zhangdaiscott** [comment]
新版已发布，请验证

**Comment by 506764932** [comment]
升级完3.7.0后 还是空的
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/542693d8-83a1-41b6-bf5e-c58e2beb543a)

**Comment by zhangdaiscott** [comment]
那你重新提个issue，详细写明重现步骤
