### ISSUE TITLE
字典颜色在列表中没有体现出效果呀

### ISSUE THREAD

**Issue by qingao88** [jeecgboot/jeecg-boot#6266]
##### 分支： master？还是springboot3?
springboot3  3.6.3

##### 前端版本: vue3版？还是 vue2版？
vue3版
##### 问题描述：
数据字典：字典颜色中配置了字典颜色，但是在online表单的效果显现中，数据列表数据字典这一列并没有显示对应的字体颜色。

##### 截图&代码：
![1](https://github.com/jeecgboot/jeecg-boot/assets/7710617/6e636e3e-eec5-4ea8-a53b-ef301340b65a)
![2](https://github.com/jeecgboot/jeecg-boot/assets/7710617/43fc7b76-7a65-4e80-ad0f-6d2037365769)

是不是需要哪里设置一下？或则可以通过JS增强的方式渲染字典项颜色？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
不是给这用的，需要用得自己写render

**Comment by desheng** [comment]
表单basicForm中的render怎么写啊大佬

**Comment by yang-xianzhu** [comment]
> 表单basicForm中的render怎么写啊大佬

![image](https://github.com/jeecgboot/JeecgBoot/assets/92789120/8ba5a8f6-a9f6-4f9e-8daa-f459e0d6eea5)

**Comment by desheng** [comment]
好的，感谢解答
