### ISSUE TITLE
生成的代码为空

### ISSUE THREAD

**Issue by pengchaojun** [jeecgboot/jeecg-boot#6267]
##### 分支： master？还是springboot3?
springboot

##### 前端版本: vue3版？还是 vue2版？
vue2
##### 问题描述：
生成的代码是空的。也不报错

##### 截图&代码：
![1717119512819(1)](https://github.com/jeecgboot/jeecg-boot/assets/163973344/cc493871-7f78-4ebf-8654-a7bfe9c89769)
![1717119512819(1)](https://github.com/jeecgboot/jeecg-boot/assets/163973344/d2c209d1-566b-4632-aa50-1c3d2b042ee2)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
版本号
