### ISSUE TITLE
表格如何不跨页选择

### ISSUE THREAD

**Issue by yidao2000** [jeecgboot/jeecg-boot#6282]
##### 分支： master？还是springboot3?
springboot3

##### 前端版本: vue3版？还是 vue2版？
vue3版

##### 问题描述：
表格跨页选择数据,有客户反映,第一页和第二页都选了数据,在第二页操作的时候,忘记了第一页也选择了,导致对不该操作的数据操作了.
我尝试了所有preserveSelectedRowKeys: true的地方改成false,也不好使.
请问怎么改成不跨页选择.

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
这个功能是特意做的，你不需要可以自行改造
