### ISSUE TITLE
后端3.4.3 last和前端vue2版  版本是不是不再维护？如果有bug、安全漏洞一类的是否还会更新？

### ISSUE THREAD

**Issue by ming820214** [jeecgboot/jeecg-boot#6284]
##### 版本号：
3.4.3 last
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
vue2版
##### 问题描述：

后端3.4.3 last和前端vue2版  版本是不是不再维护？如果有bug、安全漏洞一类的是否还会更新？
后端3.4.3 last是不是最后一个支持vue2前端的版本？
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
停止大版本维护，有严重安全漏洞会处理
