### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by a1069120636** [jeecgboot/jeecg-boot#6286]
##### 截图&代码：
vue3配置
 是否打开mock
VITE_USE_MOCK = true
发布路径
VITE_PUBLIC_PATH = /
跨域代理，您可以配置多个 ,请注意，没有换行符
VITE_PROXY = [["/jeecgboot","http://192.168.2.193/jeecg-boot"],["/upload","http://192.168.2.193:3300/upload"]]
后台接口全路径地址(必填)
VITE_GLOB_DOMAIN_URL=http://192.168.2.193:8080/jeecg-boot
后台接口父地址(必填)
VITE_GLOB_API_URL=/jeecgboot
接口前缀
VITE_GLOB_API_URL_PREFIX=
微前端qiankun应用,命名必须以VITE_APP_SUB_开头,jeecg-app-1为子应用的项目名称,也是子应用的路由父路径
VITE_APP_SUB_jeecg-app-1 = 'http://192.168.2.193:8092'
nginx配置
server {
    listen       80;
    server_name  192.168.2.193;
    root         D:/wwwroot/project;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /jeecgboot/ {
        proxy_pass http://127.0.0.1:8080/jeecg-boot/;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        if ($proxy_add_x_forwarded_for ~* "127.0.0.1"){
		   set $my_proxy_add_x_forwarded_for $remote_addr;
		}
		proxy_set_header   X-Forwarded-For $my_proxy_add_x_forwarded_for;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
}
java配置
![WeChatf60069c059b1df06bea9c4e011973e64](https://github.com/jeecgboot/jeecg-boot/assets/142473921/54bb0ce8-1f4e-44f5-ac21-eca2f955505f)
错误情况
![WeChat74f8affe5463bf571dc84192e3f78642](https://github.com/jeecgboot/jeecg-boot/assets/142473921/1c67a0a5-049d-4444-b7a8-5f3e3aa83ab1)
hosts配置
![WeChatb29f27ace83c4225ee8f45efe8a70740](https://github.com/jeecgboot/jeecg-boot/assets/142473921/ccd7dc58-16ac-4f17-a879-0f302182a722)
java用的install打包，vue用的是build

改完hosts配置后本机正常，其他电脑不正常

**Comment by zhangdaiscott** [comment]
这类问题需要自己确认配置是否正确
