### ISSUE TITLE
连接瀚高数据库报错

### ISSUE THREAD

**Issue by EricLongLiu** [jeecgboot/jeecg-boot#6288]
##### 问题描述： 连接瀚高数据库报错不支持的类型

![I`{R3$FLDGBV(Y1OJVRN $Q](https://github.com/jeecgboot/jeecg-boot/assets/48744561/fd79d623-bc27-4552-9825-062d1f935d70)

##### 截图&代码：
数据库配置
![77 LD`4WA4B8URS6J088{NA](https://github.com/jeecgboot/jeecg-boot/assets/48744561/38538dff-378b-4cef-b685-212531c6fe5c)

**Comment by zhangdaiscott** [comment]
https://blog.csdn.net/weixin_41070914/article/details/102742705
