### ISSUE TITLE
docker nginx部署前台刷新页面404

### ISSUE THREAD

**Issue by mylvOv** [jeecgboot/jeecg-boot#6291]
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
我用docker启动的nginx,部署前端后,页面一刷新就404,不用docker启动nginx的话就没问题,用的配置文件内容一样

##### 截图&代码：
![`SIGJP OHH$I@Z5~`J99J8H](https://github.com/jeecgboot/jeecg-boot/assets/138858940/d354640d-70df-42b8-9ac0-7932ec4471f3)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by Gloneliness** [comment]
![image](https://github.com/jeecgboot/jeecg-boot/assets/60883115/e586a623-aec0-4e4e-b325-e8d9d33ef1e7)

**Comment by mylvOv** [comment]
> ![image](https://private-user-images.githubusercontent.com/60883115/338812700-e586a623-aec0-4e4e-b325-e8d9d33ef1e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzkyMjcsIm5iZiI6MTcxODIzODkyNywicGF0aCI6Ii82MDg4MzExNS8zMzg4MTI3MDAtZTU4NmE2MjMtYWVjMC00ZTRlLWIzMjUtZThkOWQzM2VmMWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAwMzUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OTQ5MWFlODcyOGNkZTFkZGU5OTQyYjg2NmViYTczZTQxZThmMTBhMzU0NzBkYWZiOTQwN2VjYTZmYWRkMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBpDOysvmAcnslJ5tE2HEU2-FeS4fbP7tzJzMKOrdVE)
加上这个配置还是刷新就404
![image](https://github.com/jeecgboot/jeecg-boot/assets/138858940/fc616b79-300e-40e2-b6dc-b841f9dc16ba)

![image](https://github.com/jeecgboot/jeecg-boot/assets/138858940/cc4e06a1-cb86-4691-b74d-95f36c22d637)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/publish/quick.html#%E4%BA%8C%E9%80%9A%E8%BF%87nginx%E9%83%A8%E7%BD%B2%E5%89%8D%E7%AB%AF

**Comment by moguangjian** [comment]
我也是遇到同样的问题，完全按照教程[Docker一键启动前后端](https://help.jeecg.com/java/docker/quick.html)，出现验证码404错误，操作系统是rocky9

**Comment by moguangjian** [comment]
![image](https://github.com/user-attachments/assets/7d562a5c-9f36-4558-a155-071b4100025b)
我认为问题就是出在这，从192.168.1.4 访问到了docker的内网地址172.18.0.4:8080，所以出现了网络错误
