### ISSUE TITLE
单体模式启动失败，提示 dynamic-datasource can not find primary datasource

### ISSUE THREAD

**Issue by hw090807** [jeecgboot/jeecg-boot#6297]
##### 截图&代码：

![微信截图_20240606171529](https://github.com/jeecgboot/jeecg-boot/assets/39288604/53540b29-546a-4333-a3ac-f4568e8f3dcb)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
clean下

**Comment by hw090807** [comment]
昨天当时就clean过几次了，未解决

**Comment by hw090807** [comment]
> clean下

昨天当时就clean过几次了，未解决

**Comment by hw090807** [comment]
>

> clean下

![微信截图_20240607101900](https://github.com/jeecgboot/jeecg-boot/assets/39288604/e8911b86-936c-4311-b3f9-55da66f16430)
我全恢复原来的配置，启动还是找不到数据库，失败

**Comment by hw090807** [comment]
> clean下

![微信截图_20240607152324](https://github.com/jeecgboot/jeecg-boot/assets/39288604/02dd5569-6b5e-4607-b313-b1e661c54a86)
启动失败没有加载到正确的yaml文件，我把

 <config.server-addr>jeecg-boot-nacos:8848</config.server-addr>
给注释掉，启动就莫名奇妙好了，后门不信邪，把注释回滚，并且clean，居然可用正常启动了
