### ISSUE TITLE
online报表无法多选

### ISSUE THREAD

**Issue by mctz** [jeecgboot/jeecg-boot#6299]
##### 问题描述：
新增online报表后，选择框为单选类型，无法修改

##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/14092740/d273dd42-6f63-4ae5-a025-ef081a621b8f)

**Comment by zhangdaiscott** [comment]
?

**Comment by mctz** [comment]
> ?
我想要的是多选，官网演示地址也是多选，但是我不知道需要怎么配置，或者是个bug?

**Comment by zhangdaiscott** [comment]
你看看演示系统有问题吗

**Comment by mctz** [comment]
> 你看看演示系统有问题吗

演示系统没有问题，我本地重新拉取了代码部署还是有问题
![image](https://github.com/jeecgboot/jeecg-boot/assets/14092740/67d7951f-8b68-486d-9d15-9fc99e539759)

**Comment by zhangdaiscott** [comment]
新版发布了，请验证
