### ISSUE TITLE
管理员密码逻辑问题

### ISSUE THREAD

**Issue by sxvwuwqp** [jeecgboot/jeecg-boot#6302]
##### 版本号：
3.6.3
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
我想问下..这款低代码.token貌似有些问题..A用户登录admin后,B用户在其他地方登录后且进行对admin修改密码,但是A用户它不需要重新登录直接能够使用全部权限。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by zhangdaiscott** [comment]
如果需要你可以实现一个强制退出的功能
