### ISSUE TITLE
请教一下，怎么配置能直接使用官方的nacos，而不是使用jeecgboot封装的nacos

### ISSUE THREAD

**Issue by 1xiaofeng1** [jeecgboot/jeecg-boot#6304]
##### 问题描述：
因为需要适配国产化，考虑使用官方的nacos进行适配，因为官方有源码可以进行修改适配，所以想请教下，怎么配置能不用系统自带封装的nacos，直接使用官方的nacos独立部署

**Comment by zhangdaiscott** [comment]
直接用就行，需要的配置手工在自己的nacos中配置
