### ISSUE TITLE
org.jeecgframework.poi.exception.excel.ExcelExportException: Excel导出错误

### ISSUE THREAD

**Issue by ouoie** [jeecgboot/jeecg-boot#6306]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/105272847/e157009d-ecdc-46e9-8ffa-27fe0db32a40)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；
  - springboot3_sas分支采用 `Spring Authorization Server` 替换 `Shiro`，目前是beta版不稳定，生产项目不要使用;

**Comment by ouoie** [comment]
当前版本： 3.4.4（发布日期：2022-11-21） 
抱歉，当时没找到

> 版本号

**Comment by zhangdaiscott** [comment]
debug跟踪代码把，老版本无法处理

**Comment by niubaosama** [comment]
我也遇到了相同的报错内容，原因是 @Excel(name="最近的收货日期",width=15,format = "yyyy-MM-dd") private java.lang.String zlwedt; String类型的字段不能用format = "yyyy-MM-dd" 这个注解属性

**Comment by ouoie** [comment]
> 我也遇到了相同的报错内容，原因是 @Excel(name="最近的收货日期",width=15,format = "yyyy-MM-dd") private java.lang.String zlwedt; String类型的字段不能用format = "yyyy-MM-dd" 这个注解属性

好的，谢谢
