### ISSUE TITLE
3.7.0 人大金仓驱动 maven依赖不存在

### ISSUE THREAD

**Issue by yswang1024** [jeecgboot/jeecg-boot#6309]
##### 问题描述：
jeecg-boot-base-core   pom.xml中

<dependency>

	<groupId>org.jeecgframework</groupId>

	<artifactId>kingbase8</artifactId>

	<version>9.0.0</version>

	<scope>runtime</scope>

</dependency>

仓库中没有这个依赖，阿里云和mvnrepository都没有

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/java/setup/maven.html
