### ISSUE TITLE
JVxeTable 使用参数配置，如何动态地根据其他字段的值动态改变是否必填

### ISSUE THREAD

**Issue by 1411636270** [jeecgboot/jeecg-boot#6312]
##### 版本号：
3.6.2-GA
##### 分支： master？还是springboot3?

master
##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：

JVxeTable 使用参数配置，如何动态地根据其他字段的值动态改变是否必填
##### 截图&代码：
![3dac668e82bfda626040b021f3e75bd](https://github.com/jeecgboot/jeecg-boot/assets/75010786/57ef2957-1368-405c-b1f9-1348303e583f)
我本来想用handler来实现 但不会触发提交校验

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
可以更新到最新版
