### ISSUE TITLE
DictAspect 通过feign调用 ISysBaseAPI中的/sys/api/translateDictFromTableByKeys 出现401Token失效

### ISSUE THREAD

**Issue by leeore123** [jeecgboot/jeecg-boot#6313]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/a872ec69-4391-41ca-b799-653454937622)
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/79e42b2a-c4bc-4898-b75f-eaa9a248f6e9)
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/19b035eb-09c2-4f00-9e9e-391514629661)
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/df92d2d9-c6b2-4723-ae20-784179757463)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
类似问题发过了，我们重新不出来，需要处理，请用最新版测试，并提供重现步骤
