### ISSUE TITLE
signUrls这个配置在微服务POST带对象参数调用时，/*可以通，/**就调不通了

### ISSUE THREAD

**Issue by lq-java** [jeecgboot/jeecg-boot#6314]
##### 版本号：
3.5.0

##### 问题描述：

signUrls这个配置在调用其他微服务时，POST请求带对象参数调用，配置成/*可以通，配置成/**就调不通了

##### 截图&代码：
报错会提示说requestBody是空的，但是/*就可以
![image](https://github.com/jeecgboot/jeecg-boot/assets/59862687/ed7ddc02-8c01-4af9-936c-c099496409bc)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
原来没考虑post情况，可以参考最最新版代码
