### ISSUE TITLE
db目录下没有SQL Server数据库脚本，能否提供？

### ISSUE THREAD

**Issue by cwp221** [jeecgboot/jeecg-boot#6315]
##### 问题描述：
db目录下没有SQL Server数据库脚本，能否提供？

##### 截图&代码：

![91700dabcf428f115fc4b5d554d70223](https://github.com/jeecgboot/jeecg-boot/assets/107450849/c6504ea5-276a-4f0a-a0db-3cab25ef6506)

**Comment by zhangdaiscott** [comment]
过几天
