### ISSUE TITLE
数据表jimu_report_data_source，字段connect_times的类型问题

### ISSUE THREAD

**Issue by cwp221** [jeecgboot/jeecg-boot#6316]
##### 问题描述：
数据表jimu_report_data_source，字段connect_times的类型应该是int类型吧？否则使用navicat等工具转为其他数据库时会报错：[ERR] Source data type [int unsigned] is not supported

##### 截图&代码：
![f3d0b79969de73a4d78776ab0dd61959](https://github.com/jeecgboot/jeecg-boot/assets/107450849/82cab3b2-9c30-4422-af8d-e5cb574cd4b1)
![52b10527828aa2b558fb91447c09a8c2](https://github.com/jeecgboot/jeecg-boot/assets/107450849/ed06a39a-cc6b-42e0-ab7b-ff40351b2d3c)
![712402bee9e88048a75b41d4a177ec96](https://github.com/jeecgboot/jeecg-boot/assets/107450849/fd8449ec-6279-4fd6-bb1e-10bd5ad34ca7)

**Comment by zhangdaiscott** [comment]
是的，int就可以

**Comment by zhangdaiscott** [comment]
已经更新
