### ISSUE TITLE
微服务查询字段翻译，feign传递的token不一致

### ISSUE THREAD

**Issue by leeore123** [jeecgboot/jeecg-boot#6318]
##### 截图&代码：
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/cb486779-367e-4012-98df-3586ce346d89)
两个token解析结果
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/904572f3-5d5d-42c2-aca0-80b0cb515f94)
![image](https://github.com/jeecgboot/jeecg-boot/assets/171533019/25ead6c6-6f34-409f-a83e-634eb01808df)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
连的不是一个redis吗

**Comment by leeore123** [comment]
已解决，代码问题。
