### ISSUE TITLE
更改菜单路径地址，点击首页还是显示原来的，每次变化都需要清除浏览器缓存

### ISSUE THREAD

**Issue by 506764932** [jeecgboot/jeecg-boot#6319]
##### 问题描述：
更改菜单路径地址，点击首页还是显示原来的路径，每次变化都需要清除浏览器缓存，PC端还好，移动端就很麻烦了，
有没有办法让系统每次加载时后就自动清除，或者不存储这个页面路径？还是有其他办法解决呢？

##### 截图&代码：
1，菜单：路径由【dashboard/analysis1】改成了【dashboard/analysis2】
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/16f9a340-35e0-4679-9460-ecfaf0f44069)

2，同步修改了角色的首页配置由【dashboard/analysis1】改成了【dashboard/analysis2】
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/351f3533-7967-4760-b067-f437c15c3b2d)

点击【HRBI2.0】还是展示了老地址：
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/5c809049-ebca-4050-afb1-85301b951db5)
点击首页是正常的：
![image](https://github.com/jeecgboot/jeecg-boot/assets/6880877/8391b406-2746-4656-9bbe-dea734167171)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
先升级到最新版
