### ISSUE TITLE
后端在IDEA启动时报“驱动程式无法使用安全通讯端层 (SSL) 加密建立与 SQL Server 的安全连接”的错误

### ISSUE THREAD

**Issue by cwp221** [jeecgboot/jeecg-boot#6321]
##### 问题描述：
开发环境：Windows 10专业版 + SQL Server 2008 R2 + jdk-1.8.0.401

##### 截图&代码：
IDEA控制台报错：com.microsoft.sqlserver.jdbc.SQLServerException: 驅動程式無法使用安全通訊端層 (SSL) 加密建立與 SQL Server 的安全連接。錯誤: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]"。 

![209ef99af7b2b5255d957e6acbbca89d](https://github.com/jeecgboot/jeecg-boot/assets/107450849/63d582db-077e-40f6-a802-f6dcda222c3e)

**Comment by zhangdaiscott** [comment]
https://www.cnblogs.com/chengmuyu/p/16444009.html

此类问题百度
