### ISSUE TITLE
多租户模式下，【角色管理】能看到其他租户的角色，虽然不允许编辑，但看起来很混乱

### ISSUE THREAD

**Issue by citynook** [jeecgboot/jeecg-boot#6322]
##### 版本号：
3.7.0

##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3

##### 问题描述：
多租户模式下，【角色管理】能看到其他租户的角色，虽然不允许编辑，但看起来很混乱，建议优化下：
1. 新建角色时，保存当前租户ID到 sys_user.tenant_id 中，而不是保存0
2. 查询角色时，如果当前启用多租户，则在 where 条件后添加 sys_user.tenant_id = 当前租户的条件，过滤当前租户数据。

这个改动很小，希望可以改善下。

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
请附上截图

**Comment by citynook** [comment]
@zhangdaiscott 
1. 后台已启用多租户
2. 使用 jeecg 账号登录，修改角色时有提示。
3. 后台代码也对这个问题做了注释
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/1285146e-0602-49c4-bb1e-b467b64858f8)
![image](https://github.com/jeecgboot/jeecg-boot/assets/127393297/6ef24e81-11f8-4bf0-82fa-71c3315b1d76)

**Comment by zhangdaiscott** [comment]
有两个角色
1、系统角色，给超级管理员用的
2、租户角色，这个才是给租户管理员用的

**Comment by Mozzior** [comment]
我也遇到了会串数据的情况
A租户突然可以看到所有租户的信息了
并且这种情况是概率性触发
