### ISSUE TITLE
生产环境下部署jeecgboot，启动jar时报错

### ISSUE THREAD

**Issue by cwp221** [jeecgboot/jeecg-boot#6325]
##### 问题描述：
生产环境下部署jeecgboot，启动jar时报错：ElasticSearch 服务连接失败，原因：配置未通过。可能是BaseURL未配置或配置有误，也可能是Elasticsearch服务未启动。接下来将会拒绝执行任何方法！
如何解决？
服务器环境：Windows Server 2008 R2 Enterprise + SQL Server 2008 R2 + jre-1.8.0.401 + Redis3.0.504 + nginx1.24.0

##### 截图&代码：
![9942ee84054529378bc1c9197b2dcaba](https://github.com/jeecgboot/jeecg-boot/assets/107450849/f8825c10-7377-4587-85f8-83f009891a9c)

**Comment by zhangdaiscott** [comment]
这个错误不影响，你应该没配置es
