### ISSUE TITLE
部署后登录的时候报异常，查看好像接口缺失404

### ISSUE THREAD

**Issue by huangjx001** [jeecgboot/jeecg-boot#6326]
##### 截图&代码：
![A8B98A597C3FC0FDA83EB6656936C7C5](https://github.com/jeecgboot/jeecg-boot/assets/45821718/097173d1-d5c0-4b8c-9f75-dcefc6459128)

http://localhost:3100/jeecgboot/sys/user/getUserInfo 没有找到这个接口

**Comment by zhangdaiscott** [comment]
部署有问题吧，接口不会缺少
