### ISSUE TITLE
仪表盘设计器静态资源访问不到

### ISSUE THREAD

**Issue by sun-umbrella** [jeecgboot/jeecg-boot#6330]
版本号：

3.6.3

分支： master？还是springboot3?

springboot3

前端版本: vue3版？还是 vue2版？

vue3版

问题描述：
请问仪表盘设计器的静态文件访问不到是什么原因呀？。
配置文件加了customPrePath: /demo 报表设计器正常访问。

截图&代码：

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
不要自定义
