### ISSUE TITLE
3.7.0 微服务支持 dm适配吗 代码生成 直接开发吗 还是开发完适配达梦

### ISSUE THREAD

**Issue by YeyuchenBa** [jeecgboot/jeecg-boot#6331]
##### 版本号：
3.7.0
##### 分支： master？还是springboot3?
master

##### 前端版本: vue3版？还是 vue2版？
vue3
##### 问题描述：
3.7.0 微服务支持 dm适配吗 代码生成 直接开发吗 还是开发完适配达梦
我看官方文档适配达梦是单体的 不是微服务

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖、描述过于简抽象的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
代码默认都支持多种数据库，不用额外开发
