### ISSUE TITLE
JeecgBoot部署方案在生产环境下报错是怎么回事？

### ISSUE THREAD

**Issue by cwp221** [jeecgboot/jeecg-boot#6334]
##### 问题描述：
JeecgBoot使用WAR部署方案或JAR部署方案，部署在生产环境下报错是怎么回事？
环境：Windows Server 2008 R2 Enterprise + Tomcat9.0.85 + nginx-1.24.0 +SQL Server 2008 R2

##### 截图&代码：

  
![e0ff322fce89ab698a2ea5fc72113529](https://github.com/jeecgboot/jeecg-boot/assets/107450849/dbe78e24-608a-496a-9667-15403ab0096f)

![422815fa8647fa59fb6563981f956128](https://github.com/jeecgboot/jeecg-boot/assets/107450849/d3fe684a-8510-40e1-81be-5eff1885e82d)
![1d29608446b0227d9e13f38a09fc3795](https://github.com/jeecgboot/jeecg-boot/assets/107450849/95ab054e-e056-4811-8678-93ee34526b11)
![fe407d4d743c9c9e87364d9500ef0d75](https://github.com/jeecgboot/jeecg-boot/assets/107450849/66c42385-f887-4d46-abb1-b14f47f06735)

**Comment by zhangdaiscott** [comment]
https://help.jeecg.com/publish/quick.html#%E4%BA%8C%E9%80%9A%E8%BF%87nginx%E9%83%A8%E7%BD%B2%E5%89%8D%E7%AB%AF

接口是因为生产环境屏蔽了swaager，需要可以自己放开
