### ISSUE TITLE
JeecgBoot 吐槽大会

### ISSUE THREAD

**Issue by zhangdaiscott** [jeecgboot/jeecg-boot#757]
### JeecgBoot 吐槽大会

> 不吐不快，请大家尽情吐槽！！！ 我们会虚心学习，思考你的意见，改进项目 让其更加优秀，让你用起来更加的舒心。。。

**吐槽点**

-  JeecgBoot 存在的bug、缺陷、不好用的地方
-  JeecgBoot 存在功能比较弱的地方、功能不够完善不够强大，需要改进优化的地方
-  JeecgBoot 没有的功能（你觉得你需要的功能）、或者你有更好的想法
-  JeecgBoot 缺少文档、视频或者那些地方资料过少

**吐槽方法**

-   在此issue回复帖子即可
-   给项目点赞，点击右上方的Star

**Comment by bigalen** [comment]
online 报表~亲爱的

**Comment by 695588168** [comment]
1 菜单头 导航列表拖动固定，感觉整个体验晃动难用
2 分页表格行太多时，表头 分页栏固定，内容开启滚动
3 原框架字体大小挺好，为什么要把字体变小，如表单，查询条件字体
4 把表格前面 已选择0项框去掉 这个几乎没有用处却占用可视面积
5 整个分页表格统一样式 最好开启各标题间距自定义调整 
6 加高级查询/查询条件框可隐藏

**Comment by zhangdaiscott** [comment]
1、升级jeect-boot版本麻烦，本地版本，改了很多东西包括源码，就不能平滑的升级
2、首页的js太大了，好几M，首屏加载太慢

**Comment by Czar1994** [comment]
online-form 求开源

**Comment by ylca** [comment]
online 和 流转没有是个大伤

**Comment by qixiaodong** [comment]
1、JSelectUserByDep打开已选择的用户信息，如果用户没有在列表第一页，选择框上不会显示名字；选择后重新打开选择框，列表上不会自动勾上已选择的用户；
2、JSelectMultiUser第一页选择了用户，翻到第二页之后选择项会消失；打开之前选择的信息，如果信息没有在列表第一页，则选择框上没有名称；
3、

**Comment by Czar1994** [comment]
jeecg-boot-base-common 模块改包名后 online-form 里的依赖全部报错 无法代码在线生成 建议将功能模块开源 不要单独封装打包

**Comment by zhhang920** [comment]
1、未完全开源；
2、首页太大，加载慢；
3、分布式、服务管理这块支持的不好；
4、修改密码时不要传用户名，用户列表返回了密码、盐；
5、操作日志不全、权限点配置不全，升级比较麻烦；

**Comment by xinheblue** [comment]
假手机端支持，element-ui可以换vuetify吗

**Comment by tuyula** [comment]
我把jeecg-boot集成钉钉, token时间太短, 总是提示token过期, 能力暂时不够, 官方是否能够提供好的方案

**Comment by pitaoWang** [comment]
既然前后端分离为啥不搞两个项目，让项目可以直接从git clone导入？

**Comment by chenzj-king** [comment]
1.Online在线开发-页面属性-支持填值规则用法(提示说做了这块逻辑.但是看了一下代码生成.貌似没有相关的代码.看了一下混淆后的代码OnlCgformField->ColumnVo的时候.也没有用到fieldValueRuleCode的字段?这块主要是用于什么操作的?2.1.2说已经完整这块的开发.我只看到了有存到db.重新编辑也看到.没有看到实际跟生成代码联动起来)

**Comment by renmengkai** [comment]
移动端显示效果不好，尤其是时间选择器，希望引入效果更好的移动端DatePicker组件！

**Comment by ren-liang** [comment]
想法有时是好的，但是看了代码想打人

**Comment by dzzztzzzd** [comment]
online-report 有考虑开源吗

**Comment by chen110xi** [comment]
1.报表，图形报表开放使用和开源
2.报表，图形报表提供代码生成

**Comment by chenzj-king** [comment]
1.国际化
2.vue的webpack差异打包配置

**Comment by jave-joe** [comment]
1.能否添加顶部大的导航栏项项,点击后,刷新左边菜单树
2.能否集成拓扑图展示与配置功能,配置拓扑图和路由,并配置每个节点的内部信息,之前我项目中用过HT for Web,感觉还不错

**Comment by yanming1** [comment]
集成个内部实时通讯工具

**Comment by kevin-lr** [comment]
路由配置怎么能让页面显示到框架外，类似登录页面

**Comment by dskl1** [comment]
希望常见案例里的功能支持从数据库取数据，像表格合计，打印测试，pdf预览支持上传，下载功能

**Comment by LeeSheeQee** [comment]
最新版本bug实在太多了，点击隐藏左侧菜单后居然不能滚动了。。。body居然出现了overflow:hidden.

**Comment by gqf1995** [comment]
觉得ant design的设计风格不好吗，改了不少，关键还改坏了

**Comment by zhubinsheng** [comment]
无主从分离和数据库同步的架子

**Comment by mapleafly** [comment]
多租户改造后快要跟不上主版本发布了。是否考虑一个多租户版本或者设计多租户开关，避免改造太多平台代码。

**Comment by huyang19881115** [comment]
代码生成 的可以 考虑开源吗？  最好是支持 用户自己导入sql  语句，然后执行生成对应的 文件~

**Comment by huangye123** [comment]
nacos 建议升级为性能和稳定更优的 2.0 版本

**Comment by zhangdaiscott** [comment]
最新版已经是2.0

**Comment by BertQiu** [comment]
在线表单js希望能开源～

**Comment by Erimons-chan** [comment]
其他的国际化可以，online 这块的国际化该怎么做？有的提示还是中文

**Comment by KTBOY** [comment]
jvxetable无法自定义表头

**Comment by java-lyf** [comment]
在线报表能自定义请求头里的token名称吗

**Comment by alixiaodi** [comment]
代码部分开源，不给提供完整代码，大屏能开发低代码的吗
